### ISSUE TITLE
[V2] can't spawn git EACCESS

### ISSUE THREAD

**Issue by frank-dspeed** [cdr/code-server#1001]
- `code-server` version: latest
- OS Version: latest debian

## Description

on startup i see

```
SW#install
resourceServiceWorker.ts:48 SW#activate
editorWorkerServiceImpl.ts:70  INFO SW#ready
editorWorkerServiceImpl.ts:75   ERR spawn git EACCES: Error: spawn git EACCES
	at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
	at onErrorNT (internal/child_process.js:415:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```

## Steps to Reproduce

use the oneliner from README.md and then surf to localhost:8080 watch the console

**Comment by sr229** [comment]
Seems to be a docker-specific issue since I was able to confirm this works properly on local binary.

**Comment by frank-dspeed** [comment]
@sr229 ok i will look if i can debug the docker part

**Comment by frank-dspeed** [comment]
don't have the issue again at present closing temporary
