### ISSUE TITLE
Git authentication prompt not showing in editor view

### ISSUE THREAD

**Issue by elgandoz** [cdr/code-server#1002]
- `code-server` version: 2.1523-vsc1.38.1
- OS Version: CentOS / RHEL 7.7

## Description
When the user is unauthenticated in a repo and perform a pull/push via the SCM button, the user/password prompt appears in the (remote) terminal which launched code-server.
In the current VS Code the prompts appear as modal in the client.

## Steps to Reproduce
1. Open a folder in a git repository, where you don't have write permission
1. Commit anything
1. Hit the push/pull button

## Screenshots
*code-server 2.1523-vsc1.38.1*
<img width="863" alt="Screen Shot 2019-09-19 at 23 56 46" src="https://user-images.githubusercontent.com/5859926/65252227-ef8c1800-db3b-11e9-88f8-cb5d4158024f.png">

*vs code 1.38.1*
<img width="877" alt="Screen Shot 2019-09-20 at 00 08 59" src="https://user-images.githubusercontent.com/5859926/65252264-003c8e00-db3c-11e9-9c45-281426bb4851.png">

**Comment by sr229** [comment]
@elgandoz I agree this seems to be out of place, for now your workaround would be using the CLI.

**Comment by nhooyr** [comment]
Confirmed.
