### ISSUE TITLE
Saving files fail silently, causing data loss

### ISSUE THREAD

**Issue by brettp** [cdr/code-server#1003]
- `code-server` version: 1.38.1, Commit: 22058c5f861d6f39bc42a768d5cb65ffdf696ed1
- OS Version: Host: Debian SID, Client: ChromeOS

## Description

Sometimes files fail to save, but the user is given no indication. This makes it seem like everything is working as expected when no changes are actually be written to the files, which causes data loss when you close the tab.

## Steps to Reproduce

1. Open browser in remote browser
1. Wait a while. (Maybe disconnect and reconnect wifi?)
1. Make changes and save the file
1. Sometimes the file doesn't save, but there is no indication of this.

**Comment by sr229** [comment]
This has never happened to me before, especially on throttled networks. Are you sure your network is not dropping packets?

**Comment by brettp** [comment]
All other pages load on both my local and remote networks.

...but that's sort of the point of this report. If packets are being dropped or there are other network errors, shouldn't there be a warning?

**Comment by sr229** [comment]
Will raise this to the team, thanks for reporting.

**Comment by code-asher** [comment]
Closing this in favor of https://github.com/cdr/code-server/issues/1046 which is a bit more specific.
