### ISSUE TITLE
Improve CI caching

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#1004]
Having the CI handle caching would be great so we don't have to do it manually. :relieved: 

The main things are the node modules (both code-server's and VS Code's) and the default extensions. 

We'd need to have different caches for the different platforms due to the native modules. I'm not sure if it would make sense to have a single install and cache that and then force a rebuild in each platform on top of the initial install and also cache that or just cache a single install for each platform.

Ideally the default extensions would only rebuild if they've changed since they take so long to build. These can be shared among all the platforms since they don't contain native Node modules.

I assume the Docker builds will need to mount a volume or something in order to cache the Node modules.

I'm thinking we use CircleCI for this.

**Comment by code-asher** [comment]
The build script will also need to be modified since it will no longer need to handle installation and caching itself. Well it will need to run `yarn --production` at the very end so we only ship the production dependencies.

**Comment by code-asher** [comment]
I imagine we could cache the current clone of VS Code as well although I don't know if the clone really takes all that long.

**Comment by sr229** [comment]
I'll see if I can work on it by next week, CircleCI workflows are neat

**Comment by sr229** [comment]
@nhooyr Looks alright, I think instead of using CircleCI we wait out till November until we can switch to Actions because that's the time they'll hit GA as well with caching. @code-asher also determined we have faster builds in Actions as well.

**Comment by nhooyr** [comment]
Thats compared to travis, not compared to circleci. I can personally attest that circleci is 10x faster than GitHub actions. I switched nhooyr/websocket to actions because it's got a nicer UI but circleci was literally 10x faster. My jobs completed in little as 10s whereas on GitHub actions they take 1min 30s, even with caching inside my docker image.

Since you guys need to care a lot about performance as the jobs are bigger, I'd strongly recommend circle ci.

**Comment by nhooyr** [comment]
How do you know its coming in November?

**Comment by sr229** [comment]
> How do you know its coming in November?

[You're out of the loop](https://github.blog/changelog/2018-10-16-github-actions-limited-beta/) @nhooyr. 

>GitHub Actions makes it easier to automate how you build, test, and deploy your projects on any platform, including Linux, macOS, and Windows. Try out the beta before GitHub Actions is generally available on November 13.

**Comment by nhooyr** [comment]
Where does it say caching will hit November 13?

**Comment by sr229** [comment]
Actually according to GitHub [using artifacts is the way to do it](https://github.community/t5/GitHub-Actions/Caching-files-between-GitHub-Action-executions/m-p/29445)

**Comment by nhooyr** [comment]
Doesn't seem like it. They're implementing proper caching. They say it should be here mid November: https://github.community/t5/GitHub-Actions/Caching-files-between-GitHub-Action-executions/m-p/30974/highlight/true#M630

**Comment by code-asher** [comment]
If CircleCI is faster there doesn't seem to be any point in 
waiting for caching to hit Actions IMO.

**Comment by sr229** [comment]
@code-asher there's still a convinience factor with GitHub releases in Actions since the token secret is already built in within GitHub. And we also have a lot of third-party integrations that CircleCI lacks (such as the Google CLI, which would be a extra step in CircleCI)

**Comment by nhooyr** [comment]
It's really not a big deal to add a secret to CircleCI. It takes maybe a few minutes.

**Comment by sr229** [comment]
For now I'll be trying out something on oe of my personal projects then i'll port it to code-server to reduce the commits.
