### ISSUE TITLE
Setup coder for a couple of end users

### ISSUE THREAD

**Issue by crazytaj** [cdr/code-server#1006]
I have installed it on an Ubuntu 18 image, and it works great, but I was wondering how I would go about adding users to it (with their own directory) and maybe a custom login page as well. I am trying to use this for my Coding Club and I can't really figure it out. I can do all the database, PHP and stuff myself but I don't know how to A. find the spot to put it in and B. setup user directories that they are restricted to. Any help would be appreciated.

**Comment by frank-dspeed** [comment]
in your case the most easy way is to use one container per user and mount a directory for them .

**Comment by sr229** [comment]
Hi, what @frank-dspeed said. I highly recommend to mount a volume per user in a Docker container, or you can use `systemd-nspawn` and have a different `code-server` run in a `cgroup` and namespace per engineer.

**Comment by sr229** [comment]
Track it at GH-792 for now. Closing this as duplicate.
