### ISSUE TITLE
ssl.md does not exist

### ISSUE THREAD

**Issue by tischrei** [cdr/code-server#1008]
- `code-server` version: code-server v1.1156-vsc1.33.1
- OS Version: Ubuntu 18.04.1 LTS 

## Description

While running code-server as binary and insecure I see the following line in the output:
`WARN  Documentation on securing your setup: https://github.com/cdr/code-server/blob/master/doc/security/ssl.md`

Trying to invoke the website results in error code 404 because this doc does not exist.

## Steps to Reproduce

run code-server (not Docker) without any changes and see the output line:

`WARN  Documentation on securing your setup: https://github.com/cdr/code-server/blob/master/doc/security/ssl.md`

**Comment by sr229** [comment]
v1 is a deprecated version, we have moved everything over since v2. SSL is now in the Quickstart document.
