### ISSUE TITLE
Cleanup systemd unit file

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1010]
- Remove all the extra newlines
- And why do we need `/sbin/start-stop-daemon`
- Remove `User=1000`? If they're running the binary and not the container, they don't need to be running as UID 1000, they can chose whatever they want.
- Also don't need service=simple, it's default.
- Restart should be always
- Working directory should be just $HOME

**Comment by sr229** [comment]
This was a original copy from one of my systemd units, so the plan right now when we closed GH-379 was to fix it some more then PR it in

**Comment by nhooyr** [comment]
Mhmm. Lets clean it up in #1012
