### ISSUE TITLE
Update README.md gif for code-server v2

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1014]
Right now it's V1.

**Comment by frank-dspeed** [comment]
@nhooyr looks for me like it is still valid i see no need its also using port 8080 i vote for don't update

**Comment by sr229** [comment]
We're using v2 on README.gif so closing this

**Comment by nhooyr** [comment]
We're using V1 on the README.gif, not V2.

This is how V2 looks:

<img width="1268" alt="Screen Shot 2019-09-23 at 10 31 02 AM" src="https://user-images.githubusercontent.com/10180857/65439744-49673900-dded-11e9-8a9d-2fd71a0d0fc5.png">
