### ISSUE TITLE
Browser Preview not available

### ISSUE THREAD

**Issue by trigun539** [cdr/code-server#1018]
- `code-server` version: code-server2.1523-vsc1.38.1-linux-x86_64
- OS Version: Ubuntu 18.04
- Extension: https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-browser-preview

## Description

Unable to install Browser preview extension. Seems to not be available at all

## Steps to Reproduce

1. Click on extensions, search for browser preview
![image](https://user-images.githubusercontent.com/508205/65381623-46702980-dcc3-11e9-9064-906c8cdd3316.png)

Will this extension be supported in the future? Or is there a workaround for this? Thanks.

**Comment by sr229** [comment]
@trigun539 registry is a bit outdated, will let the team know you need it.

**Comment by lakshmanmallidi** [comment]
Please Try to integrate browser preview extension into code-server if possible. In the organization where i work they don't let any packet from internal network to external network from their machines except for http and https to browse internet. I can't take my machine but i can access code server in my machine which is very helpfull. with this extenstion i can access serves like spark, hadoop web interfaces from local network.

**Comment by nhooyr** [comment]
See #1299
