### ISSUE TITLE
Document extensions gallery

### ISSUE THREAD

**Issue by frank-dspeed** [cdr/code-server#1020]
I Would like to have a example or Documentation of the Extension Gallery
at minimum a example gallery.

**Comment by sr229** [comment]
We won't be open sourcing our extension gallery for now (which is part of the Enterprise offering), but we will strive to have a open source equivalent soon.

**Comment by frank-dspeed** [comment]
@sr229 no problem as code-remote comes in Nov 2019 with some luck that will support the nativ extension gallery.
