### ISSUE TITLE
Upgrade to new custom Gallery url as soon as the referenced commit is merged.

### ISSUE THREAD

**Issue by frank-dspeed** [cdr/code-server#1021]
The following url leads to a current PR for custom Gallery urls so we don't need to patch that anymore.
- https://github.com/microsoft/vscode/pull/81240/commits/60621cc3f3b62b1118167c5a9b1a0b65dacb6e34
- https://github.com/microsoft/vscode/pull/81240

**Comment by sr229** [comment]
Requires upstream update. CC @code-asher

**Comment by sr229** [comment]
As @code-asher said, we just provide extensions via `product.json` so I don't think we'd benefit from this.
