### ISSUE TITLE
Test if Portable mode works if not let it work.

### ISSUE THREAD

**Issue by frank-dspeed** [cdr/code-server#1022]
https://code.visualstudio.com/docs/editor/portable

if you have a data folder or data/tmp folder in the same directory as code-server use that as data directory.

**Comment by deansheather** [comment]
It's trivial for you to change this directory yourself using `--user-data-dir`. If you want a portable code-server, you can put code-server in a directory and create a startup script that adds the `--user-data-dir` flag.

"Portable" code-server doesn't seem like a popular usecase, as most people run one per *remote* server or project. Portable projects are usually intended for moving between computers on USBs, which doesn't make sense when you're working remote.

**Comment by sr229** [comment]
There's really no use case for this. Aformentioned by @deansheather, you can use `--use-data-dir`, but we won't be supporting this going forward.

**Comment by frank-dspeed** [comment]
@deansheather its a core feature of vscode it self i only wanted to make sure its compatible i am at present working on merging code-server into vscode online as so called server build https://github.com/microsoft/vscode/issues/81310

**Comment by sr229** [comment]
I don't see how portable mode would help in any way. We're running this on a server so there's no use case for this.

**Comment by frank-dspeed** [comment]
@sr229 the usecase comes up when you don't use docker for running it and you don't want to get additional files in your home Directory its the same edge case as for vscode it self.

Littel example setup for multitenancy

/usr/bin/code-server => /home/user1/project1/code-server
will load data from /home/user1/project1/data === user and extension configs all that is normal in .vscode

**Comment by sr229** [comment]
We already have `--user-data-dir` for this, there is no such need for such a use case that only a few people would benefit.
