### ISSUE TITLE
Text on the horizontal bars missing on Firefox

### ISSUE THREAD

**Issue by nothingto** [cdr/code-server#1026]
- `code-server` version:  2.1523-vsc1.38.1
- OS Version:  Ubuntu 18.04.3 Server Edition

## Description

![Annotation 2019-09-23 200847](https://user-images.githubusercontent.com/4995337/65561931-4e71d880-df12-11e9-97ee-7311ec7548a7.png)

The text on those bars are missing under "Explorer". They are supposed to show Outline, Current Directory, and Open Editor. 

## Steps to Reproduce

1. Use code-server with firefox

**Comment by sr229** [comment]
if I remember the VSCode team never actually tested the VSCode codebase against firefox so this'll be a pain to fix.

**Comment by antofthy** [comment]
I verified this, as part of testing v2 for student use...
This was with the exact same running instance of code-server,  2.1523-vsc1.38.1
just opening it in different browsers

Firefox...
![capture_firefox](https://user-images.githubusercontent.com/1214656/66175395-d38c8880-e69c-11e9-88a4-c2f6215d4756.png)

Chrome...
![capture_chrome](https://user-images.githubusercontent.com/1214656/66175392-d12a2e80-e69c-11e9-8a67-ddd7b511452c.png)

**Comment by sr229** [comment]
I don't think we can fix this without making another rather big patch to the stylesheets, this looks pretty large.

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
