### ISSUE TITLE
Having trouble with installing on Odroid-N2

### ISSUE THREAD

**Issue by cupjoo** [cdr/code-server#1029]
## Description

* OS: Ubuntu MATE 18.04.3
I'm installing code-server with binaries but having trouble with it.
`wget https://github.com/cdr/code-server/releases/download/1.1156-vsc1.33.1/code-server1.1156-vsc1.33.1-linux-x64.tar.gz`
`tar -xvzf code-server1.1156-vsc1.33.1-linux-x64.tar.gz`
`cd code-server1.1156-vsc1.33.1-linux-x64.tar.gz`
`./code-server`
Then the following log is taken.
`-bash: ./code-server: cannot execute binary file: Exec format error`

Is it a problem with 64bit architecture? I checked the architecture as arm64

**Comment by sr229** [comment]
@cupjoo We do not support ARM yet. Please be patient as we will release ARM builds on due time.

**Comment by sr229** [comment]
Closing in favor of #35
