### ISSUE TITLE
Microsoft Edge friendly?

### ISSUE THREAD

**Issue by working-name** [cdr/code-server#1030]
## Description

I ran `code-server2.1523-vsc1.38.1-linux-x86_64` and loaded the page on Edge v. 25.10586.0.0 only to have it spit:

```js
SCRIPT1053: Const must be initialized - workbench.web.api.js (6,968)
```

Also ran `code-server2.preview.11-vsc1.37.0-linux-x86_64` which says 

```js
HTML1506: Unexpected token.
```

Also tried `code-server1.1156-vsc1.33.1-linux-x64` which says 
```js
SCRIPT1006: Expected ')' - ide.main.5b173b.js (53,5812)
```

Of course any major browsers are fine - chrome, ff, safari. Kinda awkward since it's Microsoft's own creation.

**Comment by sr229** [comment]
@working-name try out their Insiders Beta, you'll have more luck using it than the vendor-supplied Edge.

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.

**Comment by working-name** [comment]
It is, but only because I can't upgrade Edge - it's a locked-down laptop. Having tried every release since v1 I can understand why no efforts are made to support the older versions of Edge. 

Great progress, however, it's impressive as a browser-based IDE. Thank you!
