### ISSUE TITLE
iPad: Scroll only editor when keyboard is open

### ISSUE THREAD

**Issue by neofuture** [cdr/code-server#1031]
When scrolling the editor view on an iPad the outer document body attempts to scroll which means the scrolling is hard to perform with touch events

**Comment by sr229** [comment]
@neofuture try with Desktop mode, we get reports that desktop mode in iPad OS tends to fix your issues.

**Comment by neofuture** [comment]
I have v1 does not scroll properly and v2 doesn’t work at all doesn’t render login correct and does not get passed login

**Comment by mattapperson** [comment]
@neofuture what version of iOS iPadOS are you running?

**Comment by frank-dspeed** [comment]
@neofuture scrolling got patched in mainline please wait for the next v2 release and test again

**Comment by sr229** [comment]
I assigned @code-asher for it so I think by 1.39.0 the scrolling will be fixed.

**Comment by neofuture** [comment]
Awesomew work people, sorry only just picked up iPad OS 13.1

**Comment by hahaschool** [comment]
Thanks for the awesome work, would also be happy to see *mouse* scrolling would also work properly on iPad OS 13, currently, if I scroll by external mouse's wheel, the whole page, rather than the editor region scrolls.

**Comment by sr229** [comment]
We're trying our very best! @code-asher discussed switching upstream to 1.39.1 immediately since that has some fixes we all need.

**Comment by nhooyr** [comment]
Just confirmed this works. If this is still a problem, please feel free to reopen.

**Comment by nhooyr** [comment]
My bad, this is not fixed, just tested. Only occurs when u have the keyboard open.

**Comment by awahlig** [comment]
Any update on this? iPadOS 13.4 added mouse cursor support throughout the OS and Apple is coming out with a keyboard that includes a trackpad so this issue will probably get more exposure.

**Comment by TobiaszCudnik** [comment]
Seems fixed in 3.0 pre-releases (iOS 13.3). The ios bottom keyboard bar covers the status bar while typing tho.

**Comment by awahlig** [comment]
I just tried the codercom/code-server:3.0.1 docker image and two-fingers scrolling doesn't work on the Magic Trackpad 2 on iPadOS 13.4.

**Comment by TobiaszCudnik** [comment]
> two-fingers scrolling doesn't work on the Magic Trackpad 2 on iPadOS 13.4.
This isnt the subject of this issue.

App container scroll is and now it works well.

**Comment by awahlig** [comment]
Ah, sorry then. I’ll file a separate issue.

**Comment by nhooyr** [comment]
> App container scroll is and now it works well.

Forgot to close this, thanks.
