### ISSUE TITLE
[v2] Remote - Containers extension v0.74.0 does not work

### ISSUE THREAD

**Issue by someone1** [cdr/code-server#1032]
- `code-server` version: 
Version: 1.38.1
Commit: 65caa26d40777131d8b95f71bc3de2a4da6d0e43
Date: 2019-09-23T22:16:30.007Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

- OS Version: Running v2 docker image on Windows 10 Pro 1809
- Extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

## Description

The latest versions of the extension report they are not compatible with code-server (although it matches the latest vscode version), so I downloaded version 0.74.0, setup docker-ce-cli on the v2 docker image, and tried loading an example container. The "Remote Connection" green bottom left icon never shows up after the extension installation and although the extension can detect when a folder is opened with a .devcontainer subfolder, when trying to relaunch the folder in a container (with docker verified to work), it just reloads the window and loses the project folder, nothing else happens.

The reason I prefer to use the Remote - Containers extension instead of setting up the code-server docker image how I want is that we have multiple projects with their own unique setup with Remote - Containers, including docker-compose setups with multiple containers, so having a single generic code-server image that can load and launch the Remote - Containers config depending on which project is open is ideal and more flexible than having multiple code-server images for each project.

## Steps to Reproduce

1. docker run -it -p 127.0.0.1:8080:8080 -v "${PWD}:/home/coder/project" -v "//var/run/docker.sock:/var/run/docker.sock" codercom/code-server:v2
2. Setup docker-ce-cli in the container (e.g. run `curl -sSL https://get.docker.com | CHANNEL=stable bash` and cancel out after all the repository stuff is setup, before it tries to install docker-ce)
3.  `chmod 0666 /var/run/docker.sock` 
4. Install the Remote - Containers v0.74.0 extension via VSIX install
5. git clone the example container project here: https://github.com/Microsoft/vscode-dev-containers
6. Open Folder to one of the example directories
7. Try to launch into the container when prompted by the extension
8. Failure

**Comment by someone1** [comment]
Just reporting in - still an issue with the 2.1638-vsc1.39.2 release (looking good, great job and thousands of thank yous!), though now the latest version of the extension (v0.81.1) installs without issue. Previously the latest version wouldn't even install.

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/1315
