### ISSUE TITLE
Extremely high ram usage

### ISSUE THREAD

**Issue by vincentchu37** [cdr/code-server#1033]
## Description
After running for a bit (2 weeks) or less after heavy code sessions using coder I see heavy RAM usage. Usually I restart the instance after I see over 4 gigs or so. Today I was during some heavy coding, git usage + tracking then noticed that coder was unresponsive. I checked the RAM allocated (dynamic, instance has the ability to use all free RAM available on the hypervisor) which in this case happened to be 9058MB and realized that the coder had run out of RAM. Unfortunately, in my haste to kill the VM I forgot to check the coder logs. I did manage to grab a couple of a screenshots. This is behavior expected? Thanks!

![image](https://user-images.githubusercontent.com/19421154/65670745-988ab500-e00b-11e9-85a2-cb46c95e6afb.png)

![image](https://user-images.githubusercontent.com/19421154/65670753-9c1e3c00-e00b-11e9-93cd-472202c7273c.png)

![image](https://user-images.githubusercontent.com/19421154/65670764-9fb1c300-e00b-11e9-8ec4-c3ba80fea16f.png)

**Comment by sr229** [comment]
@vincentchu37 which version is this on particular? We already solved some of the memory usage issues over in v2 so it might be you still using v1 which is really bad memory management

**Comment by vincentchu37** [comment]
I'm using latest prod 1.1156. Cool thanks for the update though!!

**Comment by sr229** [comment]
Awesome, please try out v2 Preview since we have more compatibility and better memory optimization than v1 as well and let us know how it'll turn out.

**Comment by Dj-jom2x** [comment]
yup .. I have 60gb ram .. sometimes like 5% chance, it takes 20gb xD like a memory leak or something.

**Comment by sr229** [comment]
> yup .. I have 60gb ram .. sometimes like 5% chance, it takes 20gb xD like a memory leak or something.

Likewise, please try out v2. We've been using it internally and a lot of people switched to it as well so please use v2 from then on. We fixed the memory issues that most of you encountered in v1.

**Comment by sr229** [comment]
I think OP has managed to acknowledge my recommendation so I'll mark this closed for now.
