### ISSUE TITLE
[v2] trys to fs.watch it self

### ISSUE THREAD

**Issue by frank-dspeed** [cdr/code-server#1036]
- `code-server` version: Version: 1.38.1
Commit: 65caa26d40777131d8b95f71bc3de2a4da6d0e43
Date: 2019-09-23T22:16:30.007Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
- OS Version: latest docker

## Description
On Startup it trys to set up file watchers for none project related directorys it watches for it self.
```
  ERR Error: [File Watcher (node.js)] Failed to watch /home/coder/.local/share/code-server/User/state/global.json for changes using fs.watch() (Error: ENOSPC: System limit for number of file watchers reached, watch '/home/coder/.local/share/code-server/User/state/global.json')
editorWorkerServiceImpl.ts:70  INFO SW#ready
editorWorkerServiceImpl.ts:75   ERR Error: [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
```

## Steps to Reproduce

1. docker run --rm -it -p 127.0.0.1:8080:8080 -v "${PWD}:/home/coder/project"  codercom/code-server:v2
1.

**Comment by frank-dspeed** [comment]
Confirmed to be also in mainline upstream https://github.com/microsoft/vscode/issues/81579

**Comment by sr229** [comment]
Leaving this open until upstream fixes this issue, thanks for the update @frank-dspeed

**Comment by frank-dspeed** [comment]
This can be closed its not really a bug but i will try to change that on mainline

**Comment by sr229** [comment]
Thanks for the update - I assume https://github.com/microsoft/vscode/issues/81702 is the proposed architectural change so we'll see if that gets merged soon.
