### ISSUE TITLE
[v2] auto updater tries to install v1

### ISSUE THREAD

**Issue by aptalca** [cdr/code-server#1040]
- `code-server` version: 2.1523-vsc1.38.1
- OS Version: linuxserver docker, ubuntu bionic based

## Description

Auto updater in the gui keeps finding an update with the pop-up message: `There is an available update.`
Clicking `Update` tries to install the `v1` version with the message: `code-server 1.1156-vsc1.33.1 is being installed in the background; we'll let you know when it's done.`
Of course the process fails because code-server is not running as root.

I also tried turning off all updates in the gui by setting `Update: Mode` to `none`. It makes no difference

## Steps to Reproduce

1. Create the docker container with the sample docker run from https://github.com/linuxserver/docker-code-server#docker with the image tag `development`
2. Open the gui and look for the pop up

**Comment by sr229** [comment]
Already a known issue. This is something to deal with our auto-updater still treating v2 as a outdated version. This should be fixed once v2 is GA.

**Comment by aptalca** [comment]
Is there at least a way to turn off the notifications? The gui setting does not seem to make a difference

**Comment by sr229** [comment]
For now, you cannot disable it

**Comment by aptalca** [comment]
Thanks

**Comment by code-asher** [comment]
@aptalca There definitely seems to be a bug with `Update: Mode`. I can't get it to work either. 

You could pass `--disable-updates` to the `code-server` invocation if that works for you. That disables the update mechanism entirely, even manual checks.

**Comment by bobhob314** [comment]
@code-asher Hi, the update popup from the bottom right keeps coming up even though I passed in `--disable-updates`. Any ideas?

**Comment by code-asher** [comment]
@bobhob314 Maybe the flag isn't actually making it to code-server somehow? How are you running code-server? 

Also if you could post the output when you run `code-server --disable-updates --log debug --version` it could help narrow down the problem.

**Comment by nhooyr** [comment]
@bobhob314 Latest releases have it disabled by default so that you don't even need the flag.

**Comment by renardeinside** [comment]
@code-asher is the `--disable-updates` still an option? In 3.8.0 it fails with:
```
Unknown option --disable-updates
```

**Comment by code-asher** [comment]
Nope, we removed automatic updates and the flag died with it. We do
still have an update checker though which can be disabled with
`--disable-update-check`.
