### ISSUE TITLE
Can't see any text in terminal

### ISSUE THREAD

**Issue by misaka00251** [cdr/code-server#1041]
- `code-server` version: 2.1523-vsc1.38.1
- OS Version: Debian 10

## Description

No text in terminal:

![image](https://user-images.githubusercontent.com/3908746/65850062-d24b1b00-e37f-11e9-9922-9abb415de57f.png)

When type `htop`:

![image](https://user-images.githubusercontent.com/3908746/65850074-dd05b000-e37f-11e9-8a90-4334e81b28bb.png)

Just black...but it is running.

```
    "workbench.colorCustomizations": {
        "terminal.foreground": "#37FF13",
        "terminal.background": "#2B2424"
    },
```

And above settings does not help.

## Steps to Reproduce

1. Open terminal

**Comment by misaka00251** [comment]
It seems the latest Firefox & Brave browser has this issue.

**Comment by sr229** [comment]
Try refreshing if that helps.

**Comment by misaka00251** [comment]
No, that didn't help.

**Comment by Dj-jom2x** [comment]
this happens to me if I don't have enough access to tmp.. like I cant execute, when my temp is mounted read-only that happened xD

**Comment by sr229** [comment]
> this happens to me if I don't have enough access to tmp.. like I cant execute, when my temp is mounted read-only that happened xD

That's weird. We'll investigate and see what happens, but I do know that VSCode does create tempfiles during its runtime.

**Comment by Dj-jom2x** [comment]
I wanted to say this before kindly keep putting files on tmp.. others restrict it because of whm or cyber panel web hosting panel.. you cant exec there most of the time. I don't care what folder ... or just keep them in one folder... so we can easily delete them ... or install on other jailed shell accounts. without having access to temp.

**Comment by sr229** [comment]
> I wanted to say this before kindly keep putting files on tmp.. others restrict it because of whm or cyber panel web hosting panel.. you cant exec there most of the time. I don't care what folder ... or just keep them in one folder... so we can easily delete them ... or install on other jailed shell accounts. without having access to temp.

I don't think we have control over that, that's how Visual Studio Code was designed, we just wrap around its codebase to make a rather flexible Cloud IDE that everyone can use @Dj-jom2x.

**Comment by misaka00251** [comment]
I found a solution, add this line to `settings.json` will solve it.

```
"terminal.integrated.rendererType": "dom"
```

Still, I don't understand what cause it.

**Comment by sr229** [comment]
@misaka00251 I think your browser does not support HTML5 Canvas or the canvas support in it is buggy. I tried it on CrOS 77 and it seems to be consistent with your behavior when the Wayland server reboots.

**Comment by misaka00251** [comment]
That's it!

**Comment by bchbar** [comment]
@misaka00251 I used this setting to fix black terminal background color on dark theme in firefox

**Comment by bchbar** [comment]
> I found a solution, add this line to `settings.json` will solve it.
> 
> ```
> "terminal.integrated.rendererType": "dom"
> ```

@misaka00251 I used this setting to fix black terminal background color on dark theme in firefox

**Comment by BenjaminWang236** [comment]
> I found a solution, add this line to `settings.json` will solve it.
> 
> ```
> "terminal.integrated.rendererType": "dom"
> ```
> 
> Still, I don't understand what cause it.

@misaka00251 Thanks that fixed it for me on Safari on iPadOS

**Comment by brakdag** [comment]
I have same problem, will solve it.

```"terminal.integrated.gpuAcceleration": "off"```

**Comment by RenzoCM** [comment]
> I have same problem, will solve it.
> 
> `"terminal.integrated.gpuAcceleration": "off"`

My Hero, worked on Opera
