### ISSUE TITLE
Chrome/Firefox Extension?

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#1043]
Kindof a dumb idea, but would be handy for chromebooks if its even possible

It would basically be a button you could click, it would launch code-server in a window/tab, it would probably not have the binaries availiable (git, tools, the likes) or one could store the files on a EXT USB, or a FAT32 and just ignore permissions that one would see in a ext partition. Or have it function just like `sshcode` where you supply user/pass/host, there is a SSH implementation for chromebooks/chrome
chrome.google.com/webstore/detail/secure-shell-app/pnhechapfaindjhompbnflcldabbghjo < APP
chrome.google.com/webstore/detail/secure-shell-extension/iodihamcpbpeioajjeobimgagajmlibd < EXTENSION
Again, dumb idea, not gonna be surprised if this is closed imediatly, but in theory, it would be interesting!

**Comment by sr229** [comment]
This is out of scope for code-server. We have sail for this.

**Comment by Merith-TK** [comment]
Well not everyone can use Docker. Specifically those with a WINDOWS HOME
LISCENCE, or have too many issues with Docker for it to even be a viable
option at all.

**Comment by sr229** [comment]
Again, out of scope of the project. We won't be discussing this further. Such a function is something reserved for PaaSes. We're not a PaaS, we're a IDE.

**Comment by sr229** [comment]
If you really want to, you can use this IDE as a building block, make a firefox extension that makes a button that will automatically make a workspace or clone stuff for you, ala Eclipse Che. But then, we're not a workspace server - we're a IDE. There's a difference between a PaaS and a Cloud IDE.
