### ISSUE TITLE
[v2] Remove mouse wheel fix from patch

### ISSUE THREAD

**Issue by frank-dspeed** [cdr/code-server#1044]
The mouse wheel error patched in our patch here is now in mainline so it can be droped from patch - at scripts/vscode.patch remove the  ```src/vs/base/browser/mouseEvent.ts``` part
- https://github.com/microsoft/vscode/issues/81472
- https://github.com/microsoft/vscode/commit/ad0906a03989c0c0499e5ddd6797dc6bb4fe1c7e

**Comment by sr229** [comment]
CC @code-asher

**Comment by code-asher** [comment]
Removed in master.
