### ISSUE TITLE
Run docker with HTTPS

### ISSUE THREAD

**Issue by dimdenGD** [cdr/code-server#1048]
Hi!

I'm total noob in docker, so I want to ask a question.

I know how to run code-server with cert and cert-key without docker, but how to do it with docker?

I tried this:
```
docker run -it -p 127.0.0.1:8080:8080 -v "./cs/code-server --cert [certpath] --cert-key [privatekey]" -v "./project" codercom/code
-server:v2
```

But it runs server without HTTPS.

Thanks

**Comment by sr229** [comment]
Heya @dimdenGD, make sure you mounted your certificates first, then invoke your certificates in the flags. You can use LE if you don't want to self-sign certificates, I think we outlined it pretty well on the quickstart.

**Comment by dimdenGD** [comment]
How do I mount my certificates? I was reading docker docs but I didn't understood anything ;-;

Also how do I change Dockerfile

**Comment by sr229** [comment]
it should be easy as `docker -v /path/to/certs.crt:/home/coder/cert.crt -v /path/to/cert-key.key:/home/coder/cert.key -p 8080:8080 run codercom/code-server:v2 --cert /home/coder/cert.crt --cert-key /home/coder/cert.key` if I remember how to do volumes right.

**Comment by dimdenGD** [comment]
Now i'm getting `error EACCES: permission denied, open '/home/coder/cert.key'`

**Comment by mateothegreat** [comment]
@dimdenGD you should use a reverse proxy so you don't have to expose your private key to the running container. You can use something like HAproxy or nginx even. Let me know if you need help!

**Comment by demyxco** [comment]
@dimdenGD check out my docker-compose.yml on my [repo](https://github.com/demyxco/code-server/), it has a configured reverse proxy for SSL using just environment variables. Just remove the comments (#).

**Comment by iambibhas** [comment]
Just came across this issue. It should be in the documentation somewhere. Can't seem to find it.
