### ISSUE TITLE
Local modules not found in ~/vc2/vscode

### ISSUE THREAD

**Issue by Dj-jom2x** [cdr/code-server#1054]
## Description
hello im trying to build the v2

im at yarn watch

```
[04:20:26] Node flags detected: --max_old_space_size=4095
[04:20:26] Respawned to PID: 12976
[04:20:27] Local modules not found in ~/vc2/vscode
[04:20:27] Try running: npm install
```

**Comment by Dj-jom2x** [comment]
nvm .  i will just put my next question here. if i still had a problem.. im currently stuck at 


![image](https://user-images.githubusercontent.com/12135498/66248605-4b20ed00-e75b-11e9-89f3-590ce304d230.png)

**Comment by Dj-jom2x** [comment]
omg too much error haha

![image](https://user-images.githubusercontent.com/12135498/66248614-8f13f200-e75b-11e9-9dc1-5eb64096fc45.png)

**Comment by Dj-jom2x** [comment]
```
Error: Could not locate the bindings file. Tried:
 → /root/vc2/vscode/node_modules/spdlog/build/spdlog.node
 → /root/vc2/vscode/node_modules/spdlog/build/Debug/spdlog.node
 → /root/vc2/vscode/node_modules/spdlog/build/Release/spdlog.node
 → /root/vc2/vscode/node_modules/spdlog/out/Debug/spdlog.node
 → /root/vc2/vscode/node_modules/spdlog/Debug/spdlog.node
 → /root/vc2/vscode/node_modules/spdlog/out/Release/spdlog.node
 → /root/vc2/vscode/node_modules/spdlog/Release/spdlog.node
 → /root/vc2/vscode/node_modules/spdlog/build/default/spdlog.node
 → /root/vc2/vscode/node_modules/spdlog/compiled/12.7.0/linux/x64/spdlog.node
 → /root/vc2/vscode/node_modules/spdlog/addon-build/release/install-root/spdlog.node
 → /root/vc2/vscode/node_modules/spdlog/addon-build/debug/install-root/spdlog.node
 → /root/vc2/vscode/node_modules/spdlog/addon-build/default/install-root/spdlog.node
 → /root/vc2/vscode/node_modules/spdlog/lib/binding/node-v72-linux-x64/spdlog.node
    at bindings (/root/vc2/vscode/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/root/vc2/vscode/node_modules/spdlog/index.js:3:35)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at Module.patchedRequire [as require] (/root/vc2/vscode/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at NodeScriptLoader.load (/root/vc2/vscode/out/vs/loader.js:747:39)
    at OnlyOnceScriptLoader.load (/root/vc2/vscode/out/vs/loader.js:585:32)
    at loadNextPath (/root/vc2/vscode/out/vs/loader.js:1523:41)
    at Object.errorback (/root/vc2/vscode/out/vs/loader.js:1531:25)
    at OnlyOnceScriptLoader.triggerErrorback (/root/vc2/vscode/out/vs/loader.js:598:36)
    at /root/vc2/vscode/out/vs/loader.js:585:151
    at ReadFileContext.callback (/root/vc2/vscode/out/vs/loader.js:764:25)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13) {
  tries: [
    '/root/vc2/vscode/node_modules/spdlog/build/spdlog.node',
    '/root/vc2/vscode/node_modules/spdlog/build/Debug/spdlog.node',
    '/root/vc2/vscode/node_modules/spdlog/build/Release/spdlog.node',
    '/root/vc2/vscode/node_modules/spdlog/out/Debug/spdlog.node',
    '/root/vc2/vscode/node_modules/spdlog/Debug/spdlog.node',
    '/root/vc2/vscode/node_modules/spdlog/out/Release/spdlog.node',
    '/root/vc2/vscode/node_modules/spdlog/Release/spdlog.node',
    '/root/vc2/vscode/node_modules/spdlog/build/default/spdlog.node',
    '/root/vc2/vscode/node_modules/spdlog/compiled/12.7.0/linux/x64/spdlog.node',
    '/root/vc2/vscode/node_modules/spdlog/addon-build/release/install-root/spdlog.node',
    '/root/vc2/vscode/node_modules/spdlog/addon-build/debug/install-root/spdlog.node',
    '/root/vc2/vscode/node_modules/spdlog/addon-build/default/install-root/spdlog.node',
    '/root/vc2/vscode/node_modules/spdlog/lib/binding/node-v72-linux-x64/spdlog.node'
  ],
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous2===' ]
}
info  Server listening on http://localhost:8080
info    - No authentication
info    - Not serving HTTPS
[nodemon] watching 4872 files
warn  ENOENT: no such file or directory, scandir '/root/.local/share/code-server/logs'


```

**Comment by Dj-jom2x** [comment]
![image](https://user-images.githubusercontent.com/12135498/66248672-414bb980-e75c-11e9-910a-6d76ff9ea137.png)

**Comment by Dj-jom2x** [comment]
`error: patch failed: build/gulpfile.vscode.js:47
error: build/gulpfile.vscode.js: patch does not apply
error: patch failed: src/vs/base/browser/mouseEvent.ts:160
error: src/vs/base/browser/mouseEvent.ts: patch does not apply
error: patch failed: src/vs/base/common/network.ts:48
error: src/vs/base/common/network.ts: patch does not apply
error: patch failed: src/vs/base/common/platform.ts:54
error: src/vs/base/common/platform.ts: patch does not apply
error: patch failed: src/vs/base/node/languagePacks.js:146
error: src/vs/base/node/languagePacks.js: patch does not apply
error: patch failed: src/vs/code/browser/workbench/workbench.html:18
error: src/vs/code/browser/workbench/workbench.html: patch does not apply
error: patch failed: src/vs/code/browser/workbench/workbench.js:8
error: src/vs/code/browser/workbench/workbench.js: patch does not apply
error: patch failed: src/vs/platform/environment/common/environment.ts:82
error: src/vs/platform/environment/common/environment.ts: patch does not apply
error: patch failed: src/vs/platform/environment/node/environmentService.ts:264
error: src/vs/platform/environment/node/environmentService.ts: patch does not apply
error: patch failed: src/vs/platform/extensionManagement/node/extensionManagementService.ts:731
error: src/vs/platform/extensionManagement/node/extensionManagementService.ts: patch does not apply
error: patch failed: src/vs/platform/localizations/electron-browser/localizationsService.ts:6
error: src/vs/platform/localizations/electron-browser/localizationsService.ts: patch does not apply
error: patch failed: src/vs/platform/log/common/logIpc.ts:26
error: src/vs/platform/log/common/logIpc.ts: patch does not apply
error: patch failed: src/vs/platform/product/node/package.ts:9
error: src/vs/platform/product/node/package.ts: patch does not apply
error: patch failed: src/vs/platform/remote/browser/browserSocketFactory.ts:133
error: src/vs/platform/remote/browser/browserSocketFactory.ts: patch does not apply
error: patch failed: src/vs/platform/update/electron-browser/updateService.ts:6
error: src/vs/platform/update/electron-browser/updateService.ts: patch does not apply
error: patch failed: src/vs/platform/update/electron-main/abstractUpdateService.ts:6
error: src/vs/platform/update/electron-main/abstractUpdateService.ts: patch does not apply
error: patch failed: src/vs/workbench/api/browser/extensionHost.contribution.ts:57
error: src/vs/workbench/api/browser/extensionHost.contribution.ts: patch does not apply
error: patch failed: src/vs/workbench/api/common/extHost.api.impl.ts:68
error: src/vs/workbench/api/common/extHost.api.impl.ts: patch does not apply
error: patch failed: src/vs/workbench/api/common/extHost.protocol.ts:614
error: src/vs/workbench/api/common/extHost.protocol.ts: patch does not apply
error: patch failed: src/vs/workbench/api/common/extHostExtensionService.ts:5
error: src/vs/workbench/api/common/extHostExtensionService.ts: patch does not apply
error: patch failed: src/vs/workbench/api/node/extHost.services.ts:26
error: src/vs/workbench/api/node/extHost.services.ts: patch does not apply
error: patch failed: src/vs/workbench/api/node/extHostExtensionService.ts:13
error: src/vs/workbench/api/node/extHostExtensionService.ts: patch does not apply
error: patch failed: src/vs/workbench/api/worker/extHostExtensionService.ts:10
error: src/vs/workbench/api/worker/extHostExtensionService.ts: patch does not apply
error: patch failed: src/vs/workbench/browser/dnd.ts:32
error: src/vs/workbench/browser/dnd.ts: patch does not apply
error: patch failed: src/vs/workbench/browser/layout.ts:260
error: src/vs/workbench/browser/layout.ts: patch does not apply
error: patch failed: src/vs/workbench/browser/web.main.ts:45
error: src/vs/workbench/browser/web.main.ts: patch does not apply
error: patch failed: src/vs/workbench/browser/web.simpleservices.ts:33
error: src/vs/workbench/browser/web.simpleservices.ts: patch does not apply
error: patch failed: src/vs/workbench/buildfile.web.js:20
error: src/vs/workbench/buildfile.web.js: patch does not apply
error: patch failed: src/vs/workbench/contrib/files/browser/files.contribution.ts:224
error: src/vs/workbench/contrib/files/browser/files.contribution.ts: patch does not apply
error: patch failed: src/vs/workbench/contrib/files/browser/views/explorerViewer.ts:47
error: src/vs/workbench/contrib/files/browser/views/explorerViewer.ts: patch does not apply
error: patch failed: src/vs/workbench/contrib/remote/common/remote.contribution.ts:79
error: src/vs/workbench/contrib/remote/common/remote.contribution.ts: patch does not apply
error: patch failed: src/vs/workbench/contrib/resources/browser/resourceServiceWorker.ts:34
error: src/vs/workbench/contrib/resources/browser/resourceServiceWorker.ts: patch does not apply
error: patch failed: src/vs/workbench/contrib/resources/browser/resourceServiceWorkerClient.ts:18
error: src/vs/workbench/contrib/resources/browser/resourceServiceWorkerClient.ts: patch does not apply
error: patch failed: src/vs/workbench/contrib/update/electron-browser/update.contribution.ts:4
error: src/vs/workbench/contrib/update/electron-browser/update.contribution.ts: patch does not apply
error: patch failed: src/vs/workbench/contrib/update/electron-browser/update.ts:5
error: src/vs/workbench/contrib/update/electron-browser/update.ts: patch does not apply
error: patch failed: src/vs/workbench/contrib/webview/browser/pre/main.js:411
error: src/vs/workbench/contrib/webview/browser/pre/main.js: patch does not apply
error: patch failed: src/vs/workbench/contrib/webview/browser/webviewElement.ts:184
error: src/vs/workbench/contrib/webview/browser/webviewElement.ts: patch does not apply
error: patch failed: src/vs/workbench/contrib/welcome/walkThrough/browser/editor/editorWalkThrough.ts:16
error: src/vs/workbench/contrib/welcome/walkThrough/browser/editor/editorWalkThrough.ts: patch does not apply
error: patch failed: src/vs/workbench/services/environment/browser/environmentService.ts:177
error: src/vs/workbench/services/environment/browser/environmentService.ts: patch does not apply
error: patch failed: src/vs/workbench/services/extensions/browser/extensionService.ts:119
error: src/vs/workbench/services/extensions/browser/extensionService.ts: patch does not apply
error: patch failed: src/vs/workbench/services/extensions/common/extensionsUtil.ts:12
error: src/vs/workbench/services/extensions/common/extensionsUtil.ts: patch does not apply
error: patch failed: src/vs/workbench/services/extensions/node/extensionHostProcessSetup.ts:41
error: src/vs/workbench/services/extensions/node/extensionHostProcessSetup.ts: patch does not apply
error: patch failed: src/vs/workbench/services/extensions/worker/extHost.services.ts:21
error: src/vs/workbench/services/extensions/worker/extHost.services.ts: patch does not apply
error: patch failed: src/vs/workbench/workbench.web.main.ts:34
error: src/vs/workbench/workbench.web.main.ts: patch does not apply
`

**Comment by Dj-jom2x** [comment]
xD now i tried to download the release instead but its taking a lot of time to open .. still white space with the font error sad... but the v1 works fine..

**Comment by Dj-jom2x** [comment]
![image](https://user-images.githubusercontent.com/12135498/66249076-f4b6ad00-e760-11e9-8000-0013f08f93be.png)

**Comment by Dj-jom2x** [comment]
seems to work xD but a lot of error i'm confuse

**Comment by Dj-jom2x** [comment]
hmm i think its closing it self.. no error at all. i should see ^c if i close it my self..

![image](https://user-images.githubusercontent.com/12135498/66249092-2c255980-e761-11e9-88f6-d2dbc89910e2.png)

**Comment by Dj-jom2x** [comment]
it kinda works? I see my extension at v1 are still there? are they supposed to be there? xD

![image](https://user-images.githubusercontent.com/12135498/66249126-a655de00-e761-11e9-87bb-7321b3db3d29.png)

**Comment by Dj-jom2x** [comment]
I think I'm going to stay at v1 for a Lil moment xD

**Comment by code-asher** [comment]
My bad with those type errors; master had some type conflicts but they are resolved now.

Sometimes Node seems to have issues with native node modules (like spdlog) and running `npm rebuild` in the root `VS Code` directory can fix it.

If the patch doesn't apply then it means it is targeting the wrong VS Code version. You will need to run `git checkout 1.38.1` in the containing VS Code repository.

If you just want to build it and not develop, following the build steps will be a bit easier: https://github.com/cdr/code-server#build

I'm not sure why it's exiting immediately; could you check your VS Code logs? By default they are in `~/.local/share/code-server/logs`. You can also try adding `--verbose` for more logging.

**Comment by code-asher** [comment]
Gonna close this since you got this building in another issue.
