### ISSUE TITLE
[v2] How to build from source?

### ISSUE THREAD

**Issue by fnoop** [cdr/code-server#1055]
## Description

To build from source, v2 seems to need to be part of vscode codebase 3 directories down the hierarchy, but I can't see any instructions in the docs or travis/docker files on how to do this.

**Comment by geiseri** [comment]
Check out the travis.yml file.  I used: 
```
docker build --pull --compress --build-arg vscodeVersion="1.38.1" --build-arg codeServerVersion="2.1523" --tag geiseri/code-server:git .
```

The important part is the `vscodeVersion` number.

**Comment by fnoop** [comment]
hi @geiseri, that pulls in a docker but doesn't show the steps needed to build from source.  For v1 there was a very simple sequence of steps needed:
https://github.com/goodrobots/maverick/blob/master/manifests/maverick-modules/maverick_web/manifests/codeserver.pp#L28

**Comment by sr229** [comment]
@fnoop We use a entirely different way of compiling binaries in CI. So follow the instructions [here](https://github.com/cdr/code-server#development) and should work.

**Comment by fnoop** [comment]
@sr229 I get as far as `yarn watch` and it gobbles up all memory and then crashes.  I notice that it starts compilation twice - is that right?

```
...
[16:15:20] Starting clean-extension-vscode-test-resolver ...
[16:15:20] Finished clean-extension-markdown-language-features-preview-src after 34 ms
[16:15:20] Starting watch-extension:markdown-language-features-preview-src ...
[16:15:20] Starting compilation...
[16:15:20] Finished clean-extension-typescript-basics-test-colorize-fixtures after 91 ms
[16:15:20] Starting watch-extension:typescript-basics-test-colorize-fixtures ...
[16:15:20] Finished compilation with 0 errors after 43 ms
[16:15:20] Finished clean-extension-configuration-editing after 248 ms
[16:15:20] Starting watch-extension:configuration-editing ...
[16:15:20] Starting compilation...
[16:15:20] Finished clean-extension-css-language-features-client after 259 ms
[16:15:20] Starting watch-extension:css-language-features-client ...
[16:15:20] Finished clean-extension-debug-auto-launch after 264 ms
[16:15:20] Starting watch-extension:debug-auto-launch ...
[16:15:20] Finished clean-extension-debug-server-ready after 274 ms
...
```

**Comment by sr229** [comment]
@fnoop yes its actually quite right since we have to do a production build on the second if I remember. Travis AFAIK has 8GB memory, so 4GB won't do when compiling v2.

**Comment by fnoop** [comment]
@sr229 - this makes it pretty much unuseable on embedded platforms, or any platform with low resource and that doesn't support a pre-built binary - any idea how this could be accomplished?

**Comment by sr229** [comment]
> @sr229 - this makes it pretty much unuseable on embedded platforms, or any platform with low resource and that doesn't support a pre-built binary - any idea how this could be accomplished?

You misunderstood compiling with running it. Compiling requires large resources for it, running it is not.

It only consumes 158MB on a production binary on idle, and hovers at 200MB* at average.

**Comment by fnoop** [comment]
How can we run it without compiling it?  Sorry if I'm misunderstanding the basics here.

**Comment by sr229** [comment]
> How can we run it without compiling it? Sorry if I'm misunderstanding the basics here.

Please grab from [releases](https://github.com/cdr/code-server/releases) if you cannot compile it. ARM binaries are not yet supported, that's for #35.

**Comment by fnoop** [comment]
My use-case is a build platform (for UAV computers, but that's not really relevant).  It uses puppet to build components - mostly from source - onto a wide variety of platforms.  v1 of codeserver was super simple to implement, although admittedly the memory run footprint was so large I disabled it by default - great to hear that's improved in v2:
https://github.com/goodrobots/maverick/blob/master/manifests/maverick-modules/maverick_web/manifests/codeserver.pp#L28

So are you saying this will not really be possible going forward with v2, and we'll have to rely on prebuilt binaries?

**Comment by sr229** [comment]
@fnoop not exactly, but you'll need to have you unattended upgrade system to build it on a suitable host then deploy it everywhere once the build has done.

**Comment by code-asher** [comment]
You might have better luck with the build instructions instead of the development instructions: https://github.com/cdr/code-server#build. You don't need to do anything other than clone the repository and follow those steps (no need to also clone VS Code). If anything there is unclear let me know so we can update it.

**Comment by fnoop** [comment]
@code-asher - Oh I completely missed that - thank you!  That works much better .  Still needs a lot of memory to build - >2Gb, but it works reliably and simple to integrate into build manifests.

Runtime memory requirements are waaaay down, thanks everyone who is responsible for that :)

What are the possible values for ${codeServerVersion}?

**Comment by sr229** [comment]
@fnoop see VSCode's repository, the tagged releases there are the valid VSCode versions we build against. Right now the supported version is 1.38.1.

**Comment by fnoop** [comment]
@sr229 That's ${vscodeVersion} - I was after the possible settings for ${codeServerVersion}.  The readme only refers to 'development' - what does this do?  Is there a 'production'?

**Comment by sr229** [comment]
@fnoop you can set it whatever since it just sets the version of your binary.

**Comment by code-asher** [comment]
Yup it's just an arbitrary string displayed when running `code-server --version`. We set ours using the Travis build number which lets us link binaries to the build that produced them.

**Comment by code-asher** [comment]
Oh it's also used during automatic updates so that's something to keep in mind. You can disable the updates entirely with `--disable-updates`.
