### ISSUE TITLE
[v2] Can't run Dart plugin

### ISSUE THREAD

**Issue by omarbelkhodja** [cdr/code-server#1056]
- code-server version: 2
- OS Version: docker/linux
- Extension: https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code

## Description
I have started a docker image with coder, and installed flutter tools + vscode extensions.

When opening a flutter project, I have the following error message:
Activating 'Dart-code.Dart-code' failed.
i.realpathsync.native is not a function

**Comment by sionicion** [comment]
Any update on fixing this? Still happens on latest release.

**Comment by 0xVesion** [comment]
This issue blocks me from using code-server. I really need dart support.

**Comment by LeonLiuY** [comment]
Exact same issue, code-server would be super valuable for me if it supports Flutter development.

**Comment by ansarizafar** [comment]
Any update on this issue?

**Comment by sr229** [comment]
Try invoking `npm install` in the extension folder and see if that fixes anything.

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.

Should have been fixed by @kylecarbs latest fixes.
