### ISSUE TITLE
[Feature] Updater

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#1057]
Sorry for not using a template, on mobile,

But as the title suggests, some sort of updater that let's you know there is a update, and then you can run the command `code-server --update <version number>` and then restart the service, maybe even have a patch notes system much like what Microsoft has for desktop vscode.

Just a idea, I don't expect this to be implemented until code-server becomes 98% stable. Or even considered until then

**Comment by sr229** [comment]
Already implemented, just broken atm on v2 since previews are treated as outdated versions.
