### ISSUE TITLE
[v2] side panel does not show text, but shows filenames

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#1061]
![image](https://user-images.githubusercontent.com/10422110/66341205-a1c52d00-e8fb-11e9-818e-aba4c40d34c6.png)

- Server OS: Archlinux

## Description
file manager does not show tab names (Active editor, current working folder, the thingy that shows where you are in the code)

![image](https://user-images.githubusercontent.com/10422110/66341075-5ca0fb00-e8fb-11e9-9284-164db35788aa.png) (see left side)

## Steps to Reproduce
Literally don't know, was working fine this morning (4 hours ago)

**Comment by sr229** [comment]
This is a intermittent bug with VSCode's styling because it wasn't really built properly for anything beyond Chromium. Might be worth investigating.

**Comment by Merith-TK** [comment]
Alright, i found that it happens seemingly at random, (usually when it isnt
loaded WITH the page the first time)
—Merith

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
