### ISSUE TITLE
[v2] Folder selector not working as intended (Firefox)

### ISSUE THREAD

**Issue by EnKrypt** [cdr/code-server#1063]
- `code-server` version: 2.1485-vsc1.38.1
- OS Version: Arch Linux (rolling release)

## Description

![test](https://user-images.githubusercontent.com/1106939/66378960-2f734c00-e9d2-11e9-8f8e-bedc225a0b26.gif)

The folder selector seems to be very glitched, making it near impossible to open the folder I want.

Specifically, one of the main bugs seems to be that selecting a folder by left clicking or hitting return on a dropdown entry, does not reflect on the path in the bar.

As such, the "OK" button does not work as intended either.

This bug is consistently reproducible.

**Comment by sr229** [comment]
Confirming bug existing on latest v2 and master branch.

**Comment by EnKrypt** [comment]
Any ideas where I can start looking if I wanted to find a fix myself?

Could this be coming from upstream, or is there any specific part of our codebase that I could probe?

**Comment by sr229** [comment]
From what can I see this is more than likely a upstream bug as well since we're not doing particularly anything on the "open folder" feature.

**Comment by code-asher** [comment]
Wow, there's some really weird behavior with the open dialog on Firefox. When I stepped through it the difference seemed to be that Firefox maintains the input as the active element while Chrome doesn't and VS Code runs different code based on whether the input is active or not which results in this discrepancy.

**Comment by code-asher** [comment]
And I'll also note that this affects the initial text in the input as describe in #1051.

**Comment by code-asher** [comment]
The code in question:
 
https://github.com/microsoft/vscode/blob/6ab598523be7a800d7f3eb4d92d7ab9a66069390/src/vs/workbench/services/dialogs/browser/simpleFileDialog.ts#L641

Essentially Firefox ends up running `execCommand` while Chromium ends up setting the text directly. I haven't looked deeper though to see whether this is a browser bug or a bug in the VS Code codebase.

**Comment by Developer626** [comment]
I've been having the same issue, and can confirm that this happens on Firefox and not Chrome (mobile and desktop).

**Comment by sr229** [comment]
Hey OP, I'll be closing this since Microsoft has stated they would want this be seen on the main vscode project. Make sure to prefix [web] and use the same exact details here (with the exception of code-server version). Thanks for helping us out spot bugs!

**Comment by EnKrypt** [comment]
Sounds good. No problem and thank you.

**Comment by danger89** [comment]
Include testcases/E2E (end-to-end) testcase in your CI, to cover both Firefox & Chrome in the future 👍
