### ISSUE TITLE
Todo tree extension

### ISSUE THREAD

**Issue by cortopy** [cdr/code-server#1065]
todo-tree: /bin/sh: 1: /src/build/code-server2.1523-vsc1.38.1-linux-x86_64-built/node_modules/vscode-ripgrep/bin/rg: not found

- `code-server` version: 2.1523-vsc1.38.1-linux-x86_64
- OS Version: Ubuntu
- Extension: [todo tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree)

## Description

When I open vscode I get this error

```
todo-tree: /bin/sh: 1: /src/build/code-server2.1523-vsc1.38.1-linux-x86_64-built/node_modules/vscode-ripgrep/bin/rg: not found
```

I've tries to install this dependency in the extension package itself,but it doesn't solve the issue

**Comment by code-asher** [comment]
I'm not sure how we're going to solve this one. The extension tries to find ripgrep but it's not going to be there. We can't execute binaries within our binary so we copy it out to /tmp and run it from there.

Setting `todo-tree.ripgrep.ripgrep` to `/tmp/code-server/rg` would be a workaround. In a future release we'll be moving it to `$XDG_CACHE_DIR/code-server/rg` though.

Maybe we could pre-populate this setting or maybe we can do some kind of injection at run time with the correct path somehow.

**Comment by patrikzudel** [comment]
As code-asher suggested, I managed to fix this by adding - 
`"todo-tree.ripgrep.ripgrep": "/tmp/code-server/tg"`
to the settings.

After that I had another error when opening the Tree tab which I fixed by creating a `"/globalStorage/gruntfuggly.todo-tree"` directory where it couldn't find one.

**Comment by nhooyr** [comment]
Will be fixed by https://github.com/cdr/code-server/issues/1306
