### ISSUE TITLE
portainer configuration ?

### ISSUE THREAD

**Issue by Dj-jom2x** [cdr/code-server#1067]
portainer configuration ? it always throws 

![image](https://user-images.githubusercontent.com/12135498/66510500-b9710100-eb07-11e9-8992-214bf2275193.png)

**Comment by Dj-jom2x** [comment]
its working if i just start it on ssh then duplicate the container.. i wanna know how to change dir? 

help example i wanted to install at /home/domaihere/

**Comment by Dj-jom2x** [comment]
how about fixing this ../build/Debug/pty.node ? i cant open terminal if i use non sudo account

**Comment by sr229** [comment]
> how about fixing this ../build/Debug/pty.node ? i cant open terminal if i use non sudo account

I'm not really sure how you managed to break the container. We've tried this over a OSIO instance and this is not the case. And it seems you're compiling it so why not try pulling from a prebuilt. 

And you seem to be building on Windows as well, `gcc` does not use that kind of path.

**Comment by sr229** [comment]
Seem to be just misconfiguration in OP's side so I'll be closing this off as a invalid bug
