### ISSUE TITLE
Can't change python interpreter when use Chrome on another PC.

### ISSUE THREAD

**Issue by bigany** [cdr/code-server#1068]
code-server 2.1523-vsc1.38.1
ubuntu 18.04LTS,  localhost  

## Description

Can't change python interpreter when use Chrome on another PC.
## Steps to Reproduce

1.start the code-server
2.  Open chrome on another PC,type the ip:8080, you will see the vscode , try edit a test.py file, then press CTRL+SHIFT+P, select python select interpreter : no response for  this action, I also try c++ extension, the same result, no response.
But when I try this on the chome shared the same PC with server, everything works fine.

**Comment by sr229** [comment]
Cannot confirm this since this might be an edge case.

**Comment by joewen85** [comment]
me too
command+shift+P
use chrome 77.0.3865.120 don't list virtualenv.but use safari brower is work

**Comment by MentalOmega** [comment]
firefox is ok

**Comment by joewen85** [comment]
may be chrome brower fail

发自我的iPhone

**Comment by hhoeflin** [comment]
I am facing the same issue using chrome

Version 73.0.3683.75 (Official Build) (32-bit)

Code-server about:
code-server
Version: 1.38.1
Commit: 22058c5f861d6f39bc42a768d5cb65ffdf696ed1
Date: 2019-09-18T18:29:50.261Z
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36

**Comment by sr229** [comment]
Seems to affect multiple people already so @code-asher might wanna take a look at this now.

**Comment by nhooyr** [comment]
Confirmed that it works.

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.

**Comment by KatiGithub** [comment]
Right now on Ubuntu Server 20.04 RPI, and version 3.7.4 I am still facing this problem. Is there any fix to this? 
![image](https://user-images.githubusercontent.com/19731334/102875949-1770d680-4477-11eb-856e-86c8a8ce44e8.png)

**Comment by nhooyr** [comment]
@KatiGithub Please update to the latest version.
