### ISSUE TITLE
Broken syntax highlighting on PHP files.

### ISSUE THREAD

**Issue by endridev** [cdr/code-server#107]
- `code-server` version: 1.31.1-100
- OS Version: Ubuntu 16.04
#### Steps to Reproduce

1. Create a blank PHP file.
2. Start coding by using `if ( isset( $some_variable ) ... `. You'll notice that the syntax is broken after `isset()`.

Attached to this report you'll find a screenshot related to this as well. Amazing product anyways :+1:  :smile: 
![screenshot from 2019-03-07 22-16-16](https://user-images.githubusercontent.com/28635526/53989770-08e0f000-4127-11e9-9713-eb428e4fb9c0.png)

**Comment by nhooyr** [comment]
Does this work in vscode?

**Comment by nhooyr** [comment]
@kylecarbs we're using vscode's syntax highlighting right so this shouldn't be a bug in code-server?

**Comment by kylecarbs** [comment]
Correct(ish). We use a wasm port of the library VS Code uses. It's possible there's an issue with that.

**Comment by NGTmeaty** [comment]
Vanilla VSCode does seem to work:

![](https://owo.whats-th.is/4TRYsfy.png)

**Comment by endridev** [comment]
I second 
![vscode-highlight](https://user-images.githubusercontent.com/28635526/54043953-18ffda80-41ce-11e9-9d23-117935f55643.png)
NGTmeaty. Here is my vanilla VSCode installation.

**Comment by kylecarbs** [comment]
Def something wrong here. Will investigate.

**Comment by pwFoo** [comment]
I need to install php-cli to get php highlighting working without error message. Maybe add php-cli to docker image?

**Comment by foresthoffman** [comment]
@pwFoo What was the error message that you received?

**Comment by pwFoo** [comment]
Without php-cli installed the message is that no php is found. Installed it in console fixes that, but highlighting has delay. It needs some time (maybe a half minute?) until directories and files are colored (local code is initially cloned from git) and code changes from plain to highlighted.

**Comment by code-asher** [comment]
v2 finally fixed this by downgrading onigasm https://github.com/NeekSandhu/onigasm/issues/17.
