### ISSUE TITLE
Manifest refuses to load because it violates 'self' directive

### ISSUE THREAD

**Issue by sr229** [cdr/code-server#1070]
- `code-server` version: `master` LKGR `1.38.1` 
- OS Version: Windows 10 Pro Insider for Workstations (18955.1)

## Description

Seems our CSP breaks when we try to run it on GCP Cloud shell

![image](https://user-images.githubusercontent.com/14976516/66622491-5ae87780-ec1a-11e9-9b5e-a49499cd37d8.png)

## Steps to Reproduce

1. Run `code-server` on [Cloud Shell](https://ssh.cloud.google.com/cloudshell/editor?shellonly=true)
2:) Go to web preview and try to run it without any flags.

**Comment by sr229** [comment]
Captured another error when you try to run it with `--host` 
![image](https://user-images.githubusercontent.com/14976516/66622580-c6cae000-ec1a-11e9-8cbb-32c41a8388c7.png)

**Comment by sr229** [comment]
Update: Commit 65caa26d40777131d8b95f71bc3de2a4da6d0e43 does not have this error, it seems to stop Terminal from working correctly as well.

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
