### ISSUE TITLE
vscode-database extension not working

### ISSUE THREAD

**Issue by dhananjayharel** [cdr/code-server#1071]
- `code-server` version: 1.38.1
- OS Version: Docker having Ubuntu 16 
- Extension: https://marketplace.visualstudio.com/items?itemName=bajdzis.vscode-database

## Description

I have deployed the vscode-database extension using extension option
which deployed successfully but when I try to create a new database connection then it doesn't work.
When I select to create new connection then the page opens but shows only "connect" button.
However it should suppose to show the full form to fill the server details(as same as desktop version).
on pressing that button it gives connection error.
Checked on console log and editor application logs but no message.
doesn't show any form inputs to fill the server details:

Screenshot 1:
![image](https://user-images.githubusercontent.com/902289/66694696-0e617280-ecd4-11e9-903c-134870c240a2.png)

**Comment by nhooyr** [comment]
Confirmed working on latest

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/10180857/73305599-07596400-41e0-11ea-9f7d-8674ab0abf85.png">
