### ISSUE TITLE
Sending TERM or INT signal ends in only the first process quitting

### ISSUE THREAD

**Issue by omusil24** [cdr/code-server#1076]
- `code-server` version: 2.1523-vsc1.38.1
- OS Version: Linux (any)

## Description

When I send a TERM or INT signal to the initial code-server process, that process quits but all the other child processes are left running. When I enter CTRL-C (interrupt - should be equivalent to INT signal) to the input of the initial process, it quits and all the other child processes quit too.

Sending TERM or INT signal to the initial process should IMHO lead to the other child processes also quitting, same like when CTRL-C is entered.

## Steps to Reproduce

1. Start code-server.
1. Run `kill -s INT <pid>` or `kill -s TERM <pid>` on the first code-server process.

**Comment by omusil24** [comment]
Just to be more specific, I'm running on Manjaro:
```
Linux borg 4.19.69-1-MANJARO #1 SMP PREEMPT Thu Aug 29 08:51:46 UTC 2019 x86_64 GNU/Linux
```

And here's exactly what I did:

1st terminal:
```
[omusil@borg ~]$ code-server
info  Server listening on http://localhost:8080
info    - No authentication
info    - Not serving HTTPS
```
2nd terminal:
```
[omusil@borg ~]$ ps -eo pid,ppid,pgid,user,args | grep code-server | grep -v grep
11569 11485 11569 omusil   code-server
11588 11569 11569 omusil   /x/dev/omqdir/develop/bin/code-server /src/build/code-server2.1523-vsc1.38.1-linux-x86_64-built/out/vs/server/main.js
[omusil@borg ~]$ kill -s TERM 11569
[omusil@borg ~]$ ps -eo pid,ppid,pgid,user,args | grep code-server | grep -v grep
11588     1 11569 omusil   /x/dev/omqdir/develop/bin/code-server /src/build/code-server2.1523-vsc1.38.1-linux-x86_64-built/out/vs/server/main.js
```

same thing with INT signal:
```
[omusil@borg ~]$ ps -eo pid,ppid,pgid,user,args | grep code-server | grep -v grep
11722 11485 11722 omusil   code-server
11733 11722 11722 omusil   /x/dev/omqdir/develop/bin/code-server /src/build/code-server2.1523-vsc1.38.1-linux-x86_64-built/out/vs/server/main.js
[omusil@borg ~]$ kill -s INT 11722
[omusil@borg ~]$ ps -eo pid,ppid,pgid,user,args | grep code-server | grep -v grep
11733     1 11722 omusil   /x/dev/omqdir/develop/bin/code-server /src/build/code-server2.1523-vsc1.38.1-linux-x86_64-built/out/vs/server/main.js
```

**Comment by sr229** [comment]
I think you misunderstood, the command is not killing the actual parent process rather the child process so it just respawns the killed one.

Running `htop` in tree view will render which is the child-processes
![Screenshot from 2019-10-16 14-07-00](https://user-images.githubusercontent.com/14976516/66892465-5c50e000-f01e-11e9-8caf-7dfcabd8e77f.png)

the `code-server` at the top is your parent process. This is what you should be killing. This is no longer our concern since this is more or less misuse of the kill commands.

**Comment by omusil24** [comment]
Okay, now with screenshots.

Initial state with htop:
![htop_1](https://user-images.githubusercontent.com/14920839/66893703-da11ed00-f018-11e9-8ccb-7f2c1c15a78e.png)

ps + kill:
![ps_kill](https://user-images.githubusercontent.com/14920839/66893748-f0b84400-f018-11e9-95d4-9ebafadd8596.png)

htop after kill:
![htop_2](https://user-images.githubusercontent.com/14920839/66893771-fc0b6f80-f018-11e9-8bb7-8aca2cc73243.png)

Please, tell me again how I'm not killing the initial process.

**Comment by code-asher** [comment]
I haven't been able to replicate yet. It's quite confusing that ctrl-c works since as you mentioned it just sends INT.

All we do is insert the main file in the arguments when `code-server` is invoked Ahttps://github.com/cdr/nbin/blob/master/src/patches/thirdPartyMain.ts#L21 so it should be the same as if you just ran `node /path/to/main.js` (which also spawns two processes) and then killed the parent process.

**Comment by code-asher** [comment]
I made a change regarding how our wrapper process exits when the child process exits. I don't know if it'll fix this since I can't replicate it but it might be worth trying out the latest version once it becomes available in a few hours.

**Comment by omusil24** [comment]
The problem persists.

Also, I tried to reproduce it inside the code-server docker. Output as follows:

1st terminal:
```
$ docker run -it --rm --entrypoint bash codercom/code-server:2.1655-vsc1.39.2
coder@aa97b5743243:~/project$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
coder        1  3.1  0.0  20180  3792 pts/0    Ss   09:08   0:00 bash
coder       15  0.0  0.0  36072  3360 pts/0    R+   09:08   0:00 ps aux
coder@aa97b5743243:~/project$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
coder        1  0.6  0.0  20180  3884 pts/0    Ss   09:08   0:00 bash
coder       16  1.6  0.0  20180  3844 pts/1    Ss   09:09   0:00 bash
coder       31 10.6  0.3 610452 54488 pts/1    Sl+  09:09   0:00 code-server
coder       42 12.4  0.3 901184 62428 pts/1    Sl+  09:09   0:00 /usr/local/bin/code-server /src/build/code-server2.1655-vsc1.39.2-linux-x86_64-built/out/vs/server/main.js
coder       56  0.0  0.0  36072  3368 pts/0    R+   09:09   0:00 ps aux
coder@aa97b5743243:~/project$ kill -s TERM 31
coder@aa97b5743243:~/project$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
coder        1  0.5  0.0  20180  3884 pts/0    Ss   09:08   0:00 bash
coder       16  0.8  0.0  20180  3844 pts/1    Ss+  09:09   0:00 bash
coder       42  2.7  0.3 901184 62428 pts/1    Sl   09:09   0:00 /usr/local/bin/code-server /src/build/code-server2.1655-vsc1.39.2-linux-x86_64-built/out/vs/server/main.js
coder       57  0.0  0.0  36072  3260 pts/0    R+   09:09   0:00 ps aux
```

2nd terminal:
```
$ docker exec -it romantic_shaw bash
coder@aa97b5743243:~/project$ code-server
info  Server listening on http://localhost:8080
info    - Password is 10c896c50f2c8e7f4b0ca900
info      - To use your own password, set the PASSWORD environment variable
info      - To disable use `--auth none`
info    - Not serving HTTPS
Terminated
coder@aa97b5743243:~/project$
```

You can try to reproduce it there too.

**Comment by omusil24** [comment]
I can confirm, that the fix is working. Thank you.
