### ISSUE TITLE
[v2] Java: Create project command doesn't work

### ISSUE THREAD

**Issue by WJayesh** [cdr/code-server#1077]
- `code-server` version:  1.38.1.
      commit: ea9c511db851b45e6a27d6dfaacbe9a89340205c 
- OS Version: Ubuntu 18.04.3, Docker(hosting locally) 
- Extension: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-dependency

## Description
On clicking the "Java: Create Java Project" command in the command palette, the status bar shows "Activating Extensions" which disappears in a while. There is no further activity. A project doesn't get created.

## Steps to Reproduce

1. Run `docker run -t -p 127.0.0.1:8080:8080 -v "LOCAL_PATH:/root/project" codercom/code-server:v2` and install JDK in the container
2. Go to the command palette and select "Java: Create Java Project"

**Comment by WJayesh** [comment]
> Please elaborate your code-server version so we know which revision that has problems.
Updated. Thanks

**Comment by WJayesh** [comment]
@sr229 Any updates on this?

**Comment by sr229** [comment]
I think we have seperate issues that are similar to yours, but I'll check for a bit and I'll close this so you can track it over there, if that's fine for you.

**Comment by WJayesh** [comment]
If the other issues relate well, I'm cool with closing this 👍

**Comment by code-asher** [comment]
Based on my testing the fix for https://github.com/cdr/code-server/issues/1081 has also fixed this. @WJayesh if you find that not to be the case lemme know.
