### ISSUE TITLE
[v2] Firefox - source control doesnt show project names.

### ISSUE THREAD

**Issue by loganto** [cdr/code-server#1079]
V2 Docker version of vs code in Firefox - project names are not displayed.   
So it makes it really hard to know which project changes are from.   
See image:  

![image](https://user-images.githubusercontent.com/3410509/66919437-5099f500-efef-11e9-8d1a-784a86419e26.png)
  

Git project names are visible just fine in chromium: 77.0.3865.90 on same box.

Firefox version: 69.0.3 on Fedora 30 linux.

**Comment by sr229** [comment]
Hey OP, I'll be closing this since Microsoft has stated they would want this be seen on the main vscode project. Make sure to prefix [web] and use the same exact details here (with the exception of code-server version). Thanks for helping us out spot bugs!
