### ISSUE TITLE
[v2] Java Run and Debug doesn't work

### ISSUE THREAD

**Issue by WJayesh** [cdr/code-server#1081]
- `code-server` version: 1.38.1
- OS Version: Ubuntu 18.04.3, Docker(running locally)

## Description
- *Run* and *Debug* commands, that are available after right-clicking on a file, do not work.  On clicking on any of these, an "Activating Extensions" message appears on the status bar which disappears in a while. There is no further activity.

- Running tests through *Java Test Runner* extension works and shows a report but *Debug Test* shows similar behavior as Run and Debug. 

## Steps to Reproduce

1.  Start a container with command `sudo docker run -t -p 127.0.0.1:8080:8080 -v "LOCAL_PATH:/root/project" codercom/code-server:v2`  
2. Open `localhost:8080` on your browser 
3. Create a terminal from the drop down menu "Terminal" 
4. Install JDK with the command `sudo apt install default-jdk`
5. Install Java Extension Pack through the Extensions option in the sidebar.
6. Git clone a sample java project with tests.
7. Use "Open Folder" to open the cloned directory.

**Comment by harunozceyhan** [comment]
Hi WJayesh,
I have same problems like you and that's why decided to work with VSCode desktop application via SSH. 
The only thing that I can help you is about 3rd problem. You need to set Default Shell to bash via "ctrl + shift + p -> Select Default Shell -> bash" command. Then you can launch a new terminal.

**Comment by WJayesh** [comment]
Thanks for the suggestion @harunozceyhan 
Also, the terminal problem is resolved :+1:

**Comment by WJayesh** [comment]
@sr229 @code-asher Any updates on this? Thanks

**Comment by emil-simeonov-se** [comment]
Java processes run and and can be debugged provided that `bash` is selected as a default shell in VS Code. This could be preset in the Docker image of the `code-server` by exposing an environment variable during the image build:

`ENV SHELL /bin/bash`

**Comment by code-asher** [comment]
@emil-simeonov-se Thanks for the fix! 

@WJayesh We'll have a new v2 image pushed once https://travis-ci.com/cdr/code-server/jobs/248856470 completes so give that a shot when you have some time and let me know if it doesn't fix the problem for you (it seems to fix it for me).

**Comment by WJayesh** [comment]
Thanks @code-asher @emil-simeonov-se . I will take a look and update this comment to confirm :+1:
