### ISSUE TITLE
Login redirect fail when using base-path and auth

### ISSUE THREAD

**Issue by yihengli** [cdr/code-server#1082]
- `code-server` version: 2.1523-vsc1.38.1
- OS Version: Ubuntu 18.04.2 LTS x86_64

## Description

Using Nginx to reverse proxy code-server with a subpath, I noticed `base-path` and `auth` cannot work together. The login page shows up properly, but always redirect to login page instead of actual editor page. If I disable the `auth` option, the subpath works fine.

I followed the instruction form https://github.com/cdr/code-server/blob/master/doc/quickstart.md#nginx-reverse-proxy and this issue https://github.com/cdr/code-server/issues/241. Not sure if this is an expected behaviour

## Steps to Reproduce

1. Nginx Conf
```
       location /code/ {

            proxy_pass https://localhost:8080/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host MY_HOST;
            proxy_set_header Accept-Encoding gzip;
       }
```
2. Initialized code-server
```
./code-server \
        --cert PATH/cert1.pem \
        --cert-key PATH/privkey1.pem \
        --auth password \
        --base-path /code
```
3. Goes to HOST/code -> login page -> enter password -> click enter -> still redirect to login page

**Comment by sr229** [comment]
CC @code-asher you might want to investigate this.

**Comment by code-asher** [comment]
I haven't been able to replicate this yet on `2.1523-vsc1.38.1`. Just to be sure, the login page doesn't say the password is invalid, does it?

**Comment by yihengli** [comment]
I tested today and could not replicate this issue anymore as well.. Not sure if my environment is changed or there was any cache issues in my browser before.

The issue can be closed now, thanks for all your helps

**Comment by sr229** [comment]
@yihengli I'm guessing it might be caching on your end, it takes a while before browsers invalidate their cache.
