### ISSUE TITLE
creatinhg docker image failed with Dockerfile

### ISSUE THREAD

**Issue by jgsun** [cdr/code-server#1083]
- `code-server` version: 

- OS Version: 

## Description
I tried to build docker image by using this Dockerfile, but it failed.

## Steps to Reproduce

1. 
import repository from https://github.com/cdr/code-server to https://github.com/jgsun/code-server/
1. 
create connection between docker hub image jgsun/code-server and https://github.com/jgsun/code-server, then trigger build docket image manually, but the build failed.

the failed log is below:
Step 9/21 : RUN yarn && MINIFY=true GITHUB_TOKEN="${githubToken}" yarn build "${vscodeVersion}" "${codeServerVersion}" && yarn binary "${vscodeVersion}" "${codeServerVersion}" && mv "/src/build/code-server${codeServerVersion}-vsc${vscodeVersion}-linux-x86_64-built/code-server${codeServerVersion}-vsc${vscodeVersion}-linux-x86_64" /src/build/code-server && rm -r /src/build/vscode-* && rm -r /src/build/code-server*-linux-*
---> Running in 48cb3fe2bbee
yarn install v1.13.0
$ yarn ensure-in-vscode && cd ../../../ && yarn || true
yarn run v1.13.0
$ bash ./scripts/tasks.bash ensure-in-vscode
+ main ensure-in-vscode
+ local rootPath
+++ dirname ./scripts/tasks.bash
++ cd ./scripts/..
++ pwd -P
+ rootPath=/src
+ local task=ensure-in-vscode
+ shift
+ [[ ensure-in-vscode == \e\n\s\u\r\e\-\i\n\-\v\s\c\o\d\e ]]
+ in-vscode /src
+ local dir=/src
+ shift
+ local maybeVsCode
+ local dirName
++ cd /src/../../..
++ pwd -P
+ maybeVsCode=/
++ basename /
+ dirName=/
+ [[ / != \v\s\c\o\d\e ]]
+ return 1
+ log 'Not in VS Code' error
+ local 'message=Not in VS Code'
+ shift
+ local level=error
+ [[ error == \e\r\r\o\r ]]
+ echo 'Not in VS Code'
Not in VS Code
+ exit 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @coder/logger@1.1.8" has unmet peer dependency "@google-cloud/logging@^4.5.2".
[4/4] Building fresh packages...
$ rm -rf node_modules/@types/node
Done in 91.21s.
yarn run v1.13.0
$ bash ./scripts/tasks.bash build '' docker
+ main build '' docker
+ local rootPath
+++ dirname ./scripts/tasks.bash
++ cd ./scripts/..
++ pwd -P
+ rootPath=/src
+ local task=build
+ shift
+ [[ build == \e\n\s\u\r\e\-\i\n\-\v\s\c\o\d\e ]]
+ local outPath=/src
+ local releasePath=/src/release
+ local stagingPath=/src/build
+ in-vscode /src
+ local dir=/src
+ shift
+ local maybeVsCode
+ local dirName
++ cd /src/../../..
++ pwd -P
+ maybeVsCode=/
++ basename /
+ dirName=/
+ [[ / != \v\s\c\o\d\e ]]
+ return 1
+ local vscodeVersion=
+ shift
+ local sourceName=vscode--source
+ local sourcePath=/src/build/vscode--source
+ [[ build == \p\a\c\k\a\g\e\-\p\r\e\b\u\i\l\t ]]
+ local codeServerVersion=docker
+ shift
+ local ci=
+ local minify=true
+ local arch
++ uname -m
+ arch=x86_64
+ local target=linux
+ local ostype=linux-gnu
+ [[ linux-gnu == \d\a\r\w\i\n* ]]
+ local output
++ ldd --version
+ output='ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.'
+ [[ ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper. == \m\u\s\l* ]]
+ local binaryName=code-serverdocker-vsc-linux-x86_64
+ local buildPath=/src/build/code-serverdocker-vsc-linux-x86_64-built
+ build-task
+ mkdir -p /src/build
+ [[ ! -d /src/build/vscode--source ]]
+ download-pre-built vscode-.tar.gz
+ local archiveName=vscode-.tar.gz
+ shift
+ local url=https://codesrv-ci.cdr.sh/vscode-.tar.gz
+ download-tar https://codesrv-ci.cdr.sh/vscode-.tar.gz
+ local url=https://codesrv-ci.cdr.sh/vscode-.tar.gz
+ shift
+ command -v wget
+ tar -C /src/build -xz
+ wget https://codesrv-ci.cdr.sh/vscode-.tar.gz --quiet -O -
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
+ [[ -n '' ]]
+ return 1
+ git clone https://github.com/microsoft/vscode --quiet --branch '' --single-branch --depth=1 /src/build/vscode--source
warning: Could not find remote branch to clone.
fatal: Remote branch not found in upstream origin
error Command failed with exit code 128.

**Comment by sr229** [comment]
You forgot to supply some build args, hence the build failed. Please supply the build args on your `docker build` properly.
