### ISSUE TITLE
Bluetooth keyboard some key invalid in code-server,including PgUp,PgDn,left and right 

### ISSUE THREAD

**Issue by reBiocoder** [cdr/code-server#1084]
I use code-server on ipad mini4.while I open code-server to edit .py file by safari browser ,my key of Bluetooth keyboard:up,down,left,right don’t use.

**Comment by sr229** [comment]
iPads has been known to have quite some issues with code-server so this is more or less upstream issue. Not something we have in control since we want to reduce how much we patch VSCode.
