### ISSUE TITLE
Is it possible to forward X11 without using any 3rd party SSH programs?

### ISSUE THREAD

**Issue by ahmed-ais** [cdr/code-server#1085]
In my use-case it is important that code-server can forward X11 such that GUI windows can appear on the client. This is seamless if I setup my Linux server to allow X11 forwarding in addition to starting code-server using PuTTY (with X11 forwarding option enabled in its settings). However, if I started code-server right from the server itself the X11 forwarding will not work.

Is it possible to forward X11 without using any 3rd party SSH programs?

**Comment by sr229** [comment]
This is not the use case of code-server. If you wanna forward X11 you'll have to use openssh

**Comment by ahmed-ais** [comment]
I see, thanks. I will have to figure out a suitable approach.

**Comment by lzd-1230** [comment]
have you get some ideas to do that? I've deploy my code-server in k8s, and I'm unwilling to expose and ssh for it, because it‘s very hard to use...
