### ISSUE TITLE
Update Digital Ocean Marketplace Droplet to the Latest Version of Code Server

### ISSUE THREAD

**Issue by Puddinglord** [cdr/code-server#1088]
The current version of code server on the digital ocean droplet in the marketplace is: 1.1156 which can also be seen in the screenshot below.

<img width="746" alt="PNG image" src="https://user-images.githubusercontent.com/4474799/67301066-e84e8600-f4bc-11e9-889d-b0572d294205.png">

As a heavy digital ocean user and an iPad Pro user it would wonderful if this could be updated to the latest version of code server which fixes many problems.

I asked in the discord if this could be fixed and it has not yet so making an issue to track the progress is the next step.

**Comment by sr229** [comment]
Tentatively assigning @kylecarbs since I think they have access in the DO button.

**Comment by kylecarbs** [comment]
@nhooyr could you give @sr229 access to modify our DO template?

**Comment by nhooyr** [comment]
I don't have access. Will DM with you.

**Comment by Puddinglord** [comment]
Any updates on this?

**Comment by djangossoul** [comment]
Also interested in this Droplet update!
If you're facing an access problem to the DO template, do you have a manual alternative for us ?
Thx

**Comment by sr229** [comment]
Manual Alternative is to run a blank Ubuntu image, then follow the instructions in `doc/` @djangossoul 

I'll reach out to the droplet one click maintainer to see what we can do.

**Comment by djangossoul** [comment]
Thank you @sr229 
I also found this tuto which was useful: https://www.digitalocean.com/community/tutorials/how-to-set-up-the-code-server-cloud-ide-platform-on-ubuntu-18-04

**Comment by Puddinglord** [comment]
I have looked at the marketplace page and it has been updated to v2. Thanks! I'll close this now.

**Comment by nhooyr** [comment]
Thanks @nathanpotter
