### ISSUE TITLE
Docker Build Fails Either on Mac or on Ubuntu

### ISSUE THREAD

**Issue by pioneerlabs** [cdr/code-server#1091]
## Description

We are trying to build the docker image but it fails.

sudo docker build --build-arg vscodeVersion=1.39.2 --build-arg githubToken=3231321312

On Mac

[build] Installing VS Code dependencies...failed
Command failed: yarn
warning " > @microsoft/applicationinsights-web@2.1.1" has unmet peer dependency "tslib@^1.9.3".
warning " > xterm-addon-search@0.2.0" has incorrect peer dependency "xterm@^3.14.0".
warning " > xterm-addon-web-links@0.2.0" has incorrect peer dependency "xterm@^3.14.0".
error /src/source/vscode-1.39.2-source/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /src/source/vscode-1.39.2-source/node_modules/vscode-ripgrep
Output:
Finding release for v11.0.1-2
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v11.0.1-2
Deleting invalid download cache
Downloading ripgrep failed: Error: Request failed: 401
    at ClientRequest.https.get.response (/src/source/vscode-1.39.2-source/node_modules/vscode-ripgrep/lib/download.js:106:24)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn    && MINIFY=true GITHUB_TOKEN="${githubToken}" yarn build "${vscodeVersion}" "${codeServerVersion}"   && yarn binary "${vscodeVersion}" "${codeServerVersion}"        && mv "/src/binaries/code-server${codeServerVersion}-vsc${vscodeVersion}-linux-x86_64" /src/binaries/code-server    && rm -r /src/build     && rm -r /src/source' returned a non-zero code: 1

On Ubuntu

[build] Building default extensions...failed
Command failed: yarn gulp compile-extensions-build --max-old-space-size=32384
(node:106) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
error Command failed with exit code 1.

error Command failed with exit code 1.

**Comment by sr229** [comment]
Your GitHub token is invalid, please grab a GitHub token via settings. You're getting ratelimited by GitHub so provision yourself a token.
