### ISSUE TITLE
Error in Browser opening 

### ISSUE THREAD

**Issue by qjq2126** [cdr/code-server#1093]
- `code-server` version: 1.1156/1.33.1
- OS Version: Ubuntu 18.04

## Description
After installation,Browser open error

Error: ENOENT: no such file or directory, open '/src/packages/server/build/web/favicon.ico'

## Steps to Reproduce

1. sudo ./code-server —port 8848 —password ********
1.  https://**.**.**.**:8848
1.  input password,Error: Error: ENOENT: no such file or directory, open '/src/packages/server/build/web/favicon.ico'

**Comment by sr229** [comment]
v1 is no longer maintained. Use the v2 versions instead.
