### ISSUE TITLE
Docker Build doesn't work on AWS Ubuntu 18.04

### ISSUE THREAD

**Issue by pioneerlabs** [cdr/code-server#1096]
- `code-server` version: <latest
- OS Version: Ubuntu 18.04, AWS

## Steps to Reproduce
Command failed: yarn
warning " > @microsoft/applicationinsights-web@2.1.1" has unmet peer dependency "tslib@^1.9.3".
warning " > xterm-addon-search@0.2.0" has incorrect peer dependency "xterm@^3.14.0".
warning " > xterm-addon-web-links@0.2.0" has incorrect peer dependency "xterm@^3.14.0".
error /src/source/vscode-1.39.2-source/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /src/source/vscode-1.39.2-source/node_modules/vscode-ripgrep
Output:
Finding release for v11.0.1-2
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v11.0.1-2
Deleting invalid download cache
Downloading ripgrep failed: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["authorization"]
    at ClientRequest.setHeader (_http_outgoing.js:473:3)
    at new ClientRequest (_http_client.js:194:14)
    at request (https.js:289:10)
    at Object.get (https.js:293:15)
    at Promise (/src/source/vscode-1.39.2-source/node_modules/vscode-ripgrep/lib/download.js:104:15)
    at new Promise (<anonymous>)
    at get (/src/source/vscode-1.39.2-source/node_modules/vscode-ripgrep/lib/download.js:98:12)
    at getAssetFromGithubApi (/src/source/vscode-1.39.2-source/node_modules/vscode-ripgrep/lib/download.js:152:27)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documen

1. gi clone
1.docker build --build-arg vscodeVersion="1.39.2" --build-arg githubToken="valid token
dc4190d7f3" -t code-server/filippo:1 .

**Comment by jasonharrison** [comment]
I just tried building from master without cache and it worked.

Try removing the githubToken build arg?

`docker build --build-arg vscodeVersion=1.39.2 -t foo/code-server .`

**Comment by sr229** [comment]
@pioneerlabs Mac builds are broken right now (as evident on our CI logs). Since it works already I'll mark it off as closed.
