### ISSUE TITLE
[v2] Tabbed editors overlap, so closing editors is a pain

### ISSUE THREAD

**Issue by emil-simeonov-se** [cdr/code-server#1097]
Couldn't find a similar existing issue.

- `code-server` version:
```
info  2.1637-vsc1.39.2
info  91f49e1efd67d1c3923228e2d0eb0b5286db90a1
info  x64
```
**N.B.** I don't think that this issue is caused by this exact release. I have tried a number of different `v2` builds for the last 3-5 days and the tabbed editors always used to overlap.

- OS Version: macOS Catalina 10.15, Docker Desktop 2.1.0.4, latest Firefox and Chrome browsers.

## Description
Tiles for multiple open tabbed editors overlap. This often makes it extremely difficult to close tabs. To make it even worse `ctrl+w` closes the VS Code tab in my web browser and not the current editor in VS Code.

Check the screenshot below.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/54935785/67441999-62872380-f5ff-11e9-8348-c29ae3304d6c.png">

## Steps to Reproduce

1. Create 3 empty text files (.txt) in your workspace. Choose file names longer than 13 symbols.
2. Open the files one by one and observe how the tiles of the open editors overlap. Try to navigate around.

**Comment by code-asher** [comment]
I'm not seeing this on Chromium (78.0.3904.70) but I do see it on Firefox. You're seeing it on both?

The `ctrl+w` thing is pretty unfortunate since we can't override that keybinding in the browser normally. One idea is to run it in an app window (change out `chromium` if you're using `chrome` or something like that):

```
chromium --app=https://domain.com
```

**Comment by emil-simeonov-se** [comment]
Yes, you are right. It seems to be a Firefox-specific issue. I just double checked with latest Chrome and VS Code tabbed editors do not overlap. From that perspective, I cannot judge what would be the severity of this bug. I personally mostly use Firefox, while I get it that usage of Chrome is still most significant.

**Comment by sr229** [comment]
This isn't the first time we had issues with Firefox to be honest, a lot of the UI is broken since they weren't built to be cross-browser at all. Will probably raise this to Microsoft.

**Comment by sr229** [comment]
Hey OP, I'll be closing this since Microsoft has stated they would want this be seen on the main vscode project. Make sure to prefix [web] and use the same exact details here (with the exception of code-server version). Thanks for helping us out spot bugs!
