### ISSUE TITLE
Docker build on ubuntu 18.04 doesn't wotk

### ISSUE THREAD

**Issue by pioneerlabs** [cdr/code-server#1098]
- `code-server` version: latesrt
- OS Version: Ubuntu 18.04, aws
node 10.16.0

## Description
Command failed: yarn
warning " > @microsoft/applicationinsights-web@2.1.1" has unmet peer dependency "tslib@^1.9.3".
warning " > xterm-addon-search@0.2.0" has incorrect peer dependency "xterm@^3.14.0".
warning " > xterm-addon-web-links@0.2.0" has incorrect peer dependency "xterm@^3.14.0".
error /src/source/vscode-1.39.2-source/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /src/source/vscode-1.39.2-source/node_modules/vscode-ripgrep
Output:
Finding release for v11.0.1-2
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v11.0.1-2
Deleting invalid download cache
Downloading ripgrep failed: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["authorization"]
    at ClientRequest.setHeader (_http_outgoing.js:473:3)
    at new ClientRequest (_http_client.js:194:14)
    at request (https.js:289:10)
    at Object.get (https.js:293:15)
    at Promise (/src/source/vscode-1.39.2-source/node_modules/vscode-ripgrep/lib/download.js:104:15)
    at new Promise (<anonymous>)
    at get (/src/source/vscode-1.39.2-source/node_modules/vscode-ripgrep/lib/download.js:98:12)
    at getAssetFromGithubApi (/src/source/vscode-1.39.2-source/node_modules/vscode-ripgrep/lib/download.js:152:27)

error Command failed with exit code 1.

## Steps to Reproduce

1. git clone
2. Command failed: sudo docker build --build-arg vscodeVersion="1.39.2" --build-arg githubToken="cf4ab38295df1a0b56a2035205f2b9
dc4190d7f3" -t code-server/filippo:1 .

**Comment by sr229** [comment]
You may have leaked your token to everyone else by the way, congrats, you just gave everyone permission to do anything on the GitHub API on your behalf.

**Comment by sr229** [comment]
Also try running the build again, this is not worth raising an issue since this is an issue with your network.
