### ISSUE TITLE
Running in Docker gives permission issues when mounting

### ISSUE THREAD

**Issue by YIREN1** [cdr/code-server#1099]
## Description

If I run docker with 
<img width="1572" alt="Screen Shot 2019-10-23 at 5 22 02 PM" src="https://user-images.githubusercontent.com/39056160/67451529-b5a4aa80-f5ee-11e9-9b1b-f9467abd746f.png">From the Readme
It starts fine but when I open it in the browser, I got 
<img width="1680" alt="Screen Shot 2019-10-23 at 5 21 51 PM" src="https://user-images.githubusercontent.com/39056160/67451568-cf45f200-f5ee-11e9-80bb-8d97bf86e862.png">
And the editor won't show up. It is saying it has permission issues insider the container? It won't be able to mkdir?

If I run 
<img width="1247" alt="Screen Shot 2019-10-23 at 5 22 31 PM" src="https://user-images.githubusercontent.com/39056160/67451596-e4bb1c00-f5ee-11e9-901c-ceb97a6024dd.png">

It seems to be working.

What did I do wrong..

Any help would be appreciated. Thanks

**Comment by sr229** [comment]
It does not have the permissions to read and write on that folder because of its permission mode. You're mounting a folder `coder` user has no access to. Please keep your extensions on another folder it owns instead on the host than mounting your extension directory.
