### ISSUE TITLE
code-server --cert fails and code-server --cert "" starts the server without SSL

### ISSUE THREAD

**Issue by wpitallo** [cdr/code-server#1101]
When I run code-server --cert it fails and code-server --cert "" starts the server without SSL?

How should we properly enable SSL using self signed cert?

![image](https://user-images.githubusercontent.com/12214559/67489019-1d9bd500-f671-11e9-94e7-0a9d5b033001.png)

**Comment by code-asher** [comment]
v1 handles the `cert` flag differently than `v2`. 

In `v1` if you leave off the `cert` flag it'll generate a self-signed certificate. 

In `v2` it won't generate a certificate unless you explicitly tell it to by passing the `cert` flag.

I recommend using v2 if you can.

**Comment by wpitallo** [comment]
Thanks @code-asher i tiried this tho code-server --cert but i receive "argument missing" error when i try this?

**Comment by code-asher** [comment]
Would you be able to try v2 instead? https://github.com/cdr/code-server/releases/tag/2.1638-vsc1.39.2

If you need to stick with v1 then drop the `--cert` flag and it should work.

**Comment by elgandoz** [comment]
Maybe I'm doing something wrong but I'm running the latest 2.1638-vsc1.39.2 like this:
```
code-server --auth password --cert --port 8443
```
But that's the output:
```
info  Server listening on http://localhost:8443
info    - Using custom password for authentication
info    - Not serving HTTPS
```
I also wiped my my `~/local/share/code-server` and I can see that the certificate doesn't get generated.
The empty `--cert` parameter was generating the certificate in the previous version i was using (2.1523-vsc1.38.1)

**Comment by elgandoz** [comment]
@code-asher

**Comment by code-asher** [comment]
Ah you're right something happened to the latest version of v2.

**Comment by code-asher** [comment]
It seems VS Code's parser changed to filter out empty string arguments. Thanks for the bug report! :heart: We'll have a new version released by end of day.
