### ISSUE TITLE
Handle non-executable tmp directory

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#1102]
It seems some hosting services mount /tmp without execute permissions which means search won't work since we extract and execute `rg` from there. We could try /tmp, the binary's directory, and then the system-installed `rg` if it exists in that order (possibly we'll want to ensure it's at least a certain version---I don't think VS Code makes any changes to ripgrep but we might want to double-check). If all fail we should output a message explaining that search won't work and how to fix it.

**Comment by deansheather** [comment]
It might be better to use `$XDG_CACHE_HOME` or `$HOME/.cache` instead of `/tmp`. [Golang stdlib](https://golang.org/src/os/file.go?s=11379:11414#L358) does a pretty good job of finding cache dir so I guess you could just copy that

**Comment by code-asher** [comment]
Ahh good point, I like that.

**Comment by Dj-jom2x** [comment]
+ 1 for this. I have a dream that I can install this easily as 123 on all of my clients with their own jailed account + to avoid rebuilding it manually on each account... so all their extensions, config and stuff won't mix by others...

**Comment by nhooyr** [comment]
Related #1287 

This should be fixed anyway by Asher.
