### ISSUE TITLE
markdown-preview-enhanced doese not work

### ISSUE THREAD

**Issue by bingyupiaoyao** [cdr/code-server#1103]
- `code-server` version: v2
- OS Version: Linux
- Extension: https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced

## Description

Does not work

## Steps to Reproduce

1. Create a markdown file
2. cannot load  the preview plugin

**Comment by bingyupiaoyao** [comment]
the default markdown preview does not work too

**Comment by code-asher** [comment]
Looks like it's another extension with missing modules. https://github.com/cdr/code-server/issues/971

The default preview should show though as long as you're on a secure URL (either https or localhost). I did find some other issues with it though.

**Comment by wpitallo** [comment]
I am also getting this and using it from an secure URL

**Comment by JtMotoX** [comment]
I am also facing issue with Default Preview.  If I create a README.md, right click it and choose "Open Preview", it opens a new tab but it is blank.  I do not experience this using the local VSC.

I am using https on localhost with untrusted self-signed cert.

**Comment by nhooyr** [comment]
Works fine now. If this is still a problem, please feel free to reopen.

**Comment by faisal-ijaz** [comment]
What was the resolution to this? Getting this issue on the latest build

**Comment by code-asher** [comment]
It is possible our marketplace had an error building the extension
again.  Please feel free to open an issue!

The long-term plan is to switch away from our marketplace and use Open
VSX so one workaround would be to switch now or download the extension
manually and install it.

https://github.com/cdr/code-server/blob/d0ca3aec207b097b4f2234f616811e65c574c0cc/docs/FAQ.md#how-do-i-use-my-own-extensions-marketplace
