### ISSUE TITLE
Source Control context menu missing some items

### ISSUE THREAD

**Issue by JtMotoX** [cdr/code-server#1104]
- `code-server` version: 2.1638-vsc1.39.2
- OS Version: macOS Mojave 10.14.6

## Description

Source Control context menu missing some items that I use frequently in VSC.
- Stage Selected Ranges
- Unstage Selected Ranges
- Revert Selected Ranges

## Steps to Reproduce

1. Git clone a repo
1. Make some changes to a file
1. Open the file diff working tree in Source Control
1. Right click one of the modified lines in the right pane
1. Under "Change All Occurrences" there should be 3 additional options listed in the description

![3](https://user-images.githubusercontent.com/7191259/67610154-be5bc480-f745-11e9-92d8-7bed36d4ffe3.jpg)

**Comment by sr229** [comment]
Can you tell us what UA/Browser you're using? It will help us alot.

**Comment by JtMotoX** [comment]
> Can you tell us what UA/Browser you're using? It will help us alot.

I am using Chrome version 77.  I have also updated the original post with a screenshot.

**Comment by sr229** [comment]
Hey OP, I'll be closing this since Microsoft has stated they would want this be seen on the main vscode project. Make sure to prefix [web] and use the same exact details here (with the exception of code-server version). Thanks for helping us out spot bugs!

**Comment by JtMotoX** [comment]
> I went ahead and patched this until VS Code makes a proper fix (since I'm not sure this is the ideal way to fix it). Will have a new release by the end of the day.

Thank you! 🥇   I opened issue with MS (link below) but they closed it right away without looking at it so I really appreciate your patch.

https://github.com/microsoft/vscode/issues/83454
