### ISSUE TITLE
editorconfig-vscode cannot be activated

### ISSUE THREAD

**Issue by emil-simeonov-se** [cdr/code-server#1107]
Couldn't find similar issue.

- `code-server` version:
```
info  2.1637-vsc1.39.2
info  91f49e1efd67d1c3923228e2d0eb0b5286db90a1
info  x64
```
- OS Version: macOS Catalina 10.15, Docker Desktop 2.1.0.4
- Extension:
**Github:** https://github.com/editorconfig/editorconfig-vscode
**VS Code Marketplace:** https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

## Description

I have been trying to install the `EditorConfig.EditorConfig` extension both as part of a Docker image build and also through VS Code UI in the browser. No matter how I do it, the extension fails to activate because the https://www.npmjs.com/package/editorconfig is not available in the running Docker container.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/54935785/67530005-151dbb80-f6be-11e9-96f4-4b28abe58b2b.png">

I have tried to:
1. Pre-install the `editorconfig` nodejs module **globally** during the build of a Docker image that I have created based on `v2`. To no success.
2. SSH into the running container (`docker exec -it ... bash`), install `npm` (also tried with `yarn`), and eventually install the `editorconfig` npm package **globally**. Didn't work.

Can you help me with overcoming this challenge one way or another?

## Steps to Reproduce

Try to install and activate https://github.com/editorconfig/editorconfig-vscode.

**Comment by code-asher** [comment]
Looks like another broken extension https://github.com/cdr/code-server/issues/971

The next big thing we need to tackle is our extension marketplace because it has quite a few of these extensions that didn't fully build for one reason or another.

The current workaround is to manually install the dependencies. For example:

```
cd ~/.local/share/code-server/extensions/editorconfig.editorconfig-0.14.0/
npm i
```

**Comment by emil-simeonov-se** [comment]
I tried out the proposed workaround and it works. Of course, updating to new versions of the `EditorConfig.EditorConfig` would be annoying, still manageble.

Thank you so much for the timely help!

**Comment by sr229** [comment]
Hey OP, let me know if this is fixed and I'll close it for you.

**Comment by code-asher** [comment]
We might want to keep it open until we fix the extension on our marketplace.

**Comment by code-asher** [comment]
Oh right we do have another issue about this extension though so never mind.

**Comment by nhooyr** [comment]
@kylecarbs Do your extension changes fix this?

**Comment by kylecarbs** [comment]
Yup, they'll fix this!
