### ISSUE TITLE
[v2] Clicking on the hamburger menu moves it when using Safari

### ISSUE THREAD

**Issue by jeremyalzona** [cdr/code-server#1110]
- `code-server` version: `2.1638-vsc1.39.2`

## Description

In Safari for macOS and iPadOS, clicking or tapping on the new hamburger menu moves it slightly to the top-left, to the point that it’s hidden. [Link to a video demo](https://streamable.com/7fndv)

## Steps to Reproduce

1. Click or tap on the hamburger menu

**Comment by sr229** [comment]
@jeremyalzona This is a upstream error. Will raise this to Microsoft.

**Comment by sr229** [comment]
Hey OP, I'll be closing this since Microsoft has stated they would want this be seen on the main vscode project. Make sure to prefix [web] and use the same exact details here (with the exception of code-server version). Thanks for helping us out spot bugs!

**Comment by robgraeber** [comment]
Doesn't look like this bug ever got reported to the vs code repo

**Comment by sr229** [comment]
> Doesn't look like this bug ever got reported to the vs code repo

@robgraeber feel free to raise it to them yourself since I really suggest we raise it there since we like some of it to be patched upstream :)

**Comment by robgraeber** [comment]
Actually looks like they already know about it, they closed a couple similar tickets as duplicate.
