### ISSUE TITLE
Host command flag broke?

### ISSUE THREAD

**Issue by watkinsmatthewp** [cdr/code-server#1112]
- `code-server` version: v10.15.1
- OS Version: Red Hat Enterprise Linux Server release 5.3 (Tikanga)

## Description

I just upgraded my installed code-server instance today. Since the previous version I was using was so old, my startup script had to change. Here's what it is now to get it to run:

```bash
export PASSWORD=MyPasswordHere
./code-server \
  --log trace \
  --disable-telemetry \
  --host my-host.my-domain.com \
  --port 9000 \
  --auth password \
  /my/path/
```

Notice I'm supplying the host. Yet still when I start the application on the remote, it binds to my IP address instead of the host name. This is different from the previous version, which bound to my host name just fine.

Is there something new I have to tell `code-server` to get it to bind it to my host name?

## Steps to Reproduce

1. Run `code-server` with the host flag

**Comment by sr229** [comment]
Try `0.0.0.0` instead. I would usually recommend nginx as well since I don't recommend doing this way.

**Comment by antofthy** [comment]
the `--host` option is just used to lookup the IP code-server should bind itself to.  This is generally either localhost (only the loopback network port of the local machine only), or `0.0.0.0` for all interfaces.

Note if you are using docker the network IP will generally be the docker intranet, also only available from the local host, unless docker connects ports to the outside world, OR you have some sort of ingress proxy connecting external URLs to the appropriate internal docker instances.

**Comment by sr229** [comment]
What @antofthy, we don't support domains, sadly.
