### ISSUE TITLE
Failed to install 'redhat.java'

### ISSUE THREAD

**Issue by watkinsmatthewp** [cdr/code-server#1114]
- `code-server` version: v10.15.1
- OS Version: Red Hat Enterprise Linux Server release 5.3 (Tikanga)
- Extension: https://github.com/redhat-developer/vscode-java

## Description

I can see the Language Support for Java(TM) by Red Hat (redhat.java) extension in the marketplae. But when I click install, I get an error saying it failed to install.

When I click the "Download Manually" button on the error message, it redirects me to https://v1.extapi.coder.com/publishers/redhat/vsextensions/java/0.47.0/vspackage, which serves a 404, so I'm guessing that's the reason.

## Workarounds

I was able to install the extension directly from the publisher's VSIX.

## Steps to Reproduce

1. Try to install the redhat.java extension.

**Comment by newk5** [comment]
same issue here

**Comment by sr229** [comment]
If any of you have VSO, please attempt to reproduce it there. If it does, then this is a upstream issue.

**Comment by code-asher** [comment]
I don't think our marketplace implements the direct download URL at the moment unfortunately. Also I tried installing `redhat.java` a few days ago and it failed due to missing files so I think it's just another one on our list of extensions to fix in our marketplace.

**Comment by nhooyr** [comment]
Works fine now. If this is still a problem, please feel free to reopen.
