### ISSUE TITLE
Need new manual for nginx 

### ISSUE THREAD

**Issue by kondr1** [cdr/code-server#1117]
This doc request already was earlier but after update code-server i have `ERR_TOO_MANY_REDIRECTS` error again with my old configs. Whats change i must make to resolve this problem?

**Comment by sr229** [comment]
Show us your nginx config so we know what's broken, thanks!

**Comment by ecrode** [comment]
Had the same issue, here is a config that worked. After I figured out a config that worked, I fixed too many redirects by clearing site's cookies, right config was not enough.

server {
	listen 443 ssl;
	
	server_name ide.*;
	
	# ssl cert, in dockers linuxserver/letsencrypt format
	include /config/nginx/ssl.conf;

	client_max_body_size 0;

	location / {
		proxy_set_header   Host $host;
		proxy_redirect http://$host/ /;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_pass http://<ip>:8080;
	}
	
	location ~* \.(?:jpg|jpeg|gif|bmp|ico|png|swf)$ {
		proxy_set_header   Host $host;
		proxy_pass http://<ip>:8080;
		access_log off;
	}
}

**Comment by sr229** [comment]
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.

**Comment by nhooyr** [comment]
We're removing the nginx manual.
