### ISSUE TITLE
The default project directory seems to be not working correctly

### ISSUE THREAD

**Issue by webarchymeta** [cdr/code-server#1123]
- `code-server` 2.1655-vsc1.39.2
- OS Version: ubuntu 18.0.4 server

## Description
We run multiple code server instances each of which has a default project directory specified using the `path` command line argument, e.g. run
```
[path to]/code-server --host x.x.x.x --port 8447 --auth none .
```
in the corresponding directory. It was ok in 2.1523-vsc1.38.1. But now default project directories seem always be set by the first opened instance

## Steps to Reproduce
(in separate systemd services)
```
cd dir1
[path to]/code-server --host x.x.x.x --port 8443 --auth none .
cd dir2
[path to]/code-server --host x.x.x.x --port 8444 --auth none .
cd dir3
[path to]/code-server --host x.x.x.x --port 8445 --auth none .
```
then
1. open http://x.x.x.x:8443, which opens directory `dir1`
2. open http://x.x.x.x:8444. It opens `dir1` directory again, instead of `dir2`

the same happens to opening http://x.x.x.x:8445

**Comment by webarchymeta** [comment]
ok, i see. thanks ...

**Comment by code-asher** [comment]
No problem. BTW if you have any thoughts on how to better improve this
behavior or need additional functionality I'm happy to hear it.

I think there may be cases where we don't always want to open the last
directory. For example when code-server is first ran we might want to
prioritize whatever is passed on the command line instead of the last
opened directory but I'm not sure.

**Comment by webarchymeta** [comment]
I think this particular feature could be realized by coverting the data structure in the original `coder.json` into a table with `port` number (of the code-server instance) as the `key` and the original data as the `value` and factoring the common settings across instances out ... just a thought

**Comment by code-asher** [comment]
Ohh that's neat. I opened a new issue that contains this idea: #1132
