### ISSUE TITLE
Update setting has no effect

### ISSUE THREAD

**Issue by ppkwiatkowski** [cdr/code-server#1125]
Is there a way to disable this notification or disable checking for updates in general?

Putting `"update.mode": "none"` in settings doesn't seem to work.

**Comment by code-asher** [comment]
Yeah for some reason that setting doesn't work but I haven't gotten
around to looking into it.

For now the only way is to pass `--disable-updates` to `code-server`.

**Comment by code-asher** [comment]
No problem! The flag will stay so no worries there.

**Comment by nhooyr** [comment]
@code-asher will take care of this in V3.

**Comment by jelizarovas** [comment]
![image](https://user-images.githubusercontent.com/15138718/80320042-c6fe8780-87c8-11ea-91c3-42f4c880e46c.png)

after clicking update available, still get this message

**Comment by nhooyr** [comment]
@jelizarovas Please open a new issue, I don't think that message is related to this one.
