### ISSUE TITLE
TypeScript autocomplete dropdown does not popup

### ISSUE THREAD

**Issue by Multivit4min** [cdr/code-server#1128]
- `code-server` version: 2.1662-vsc1.39.2
- OS Version: debian 10
- TypeScript Version: 3.6.4
- Chrome: 78.0.3904.70

## Description

Typescript autocomplete stopped working in 2.1662 the dropdown menue for types on a variable does not popup anymore
This worked in 2.1655-vsc1.39.2 but stopped working in 2.1662-vsc1.39.2

Version: 2.1655-vsc1.39.2
![image](https://user-images.githubusercontent.com/12112766/67836000-b4421900-faeb-11e9-9224-844b75ef46b7.png)

Version 2.1662-vsc1.39.2
![image](https://user-images.githubusercontent.com/12112766/67835981-aa201a80-faeb-11e9-9714-ec2b0b3af9a5.png)

## Steps to Reproduce

1. npm install @types/express express
2. create a file named example.ts
3. add following content
```typescript
import express from "express"
express
```
4. enter a dot behind express and the dropdown menue does not popup

**Comment by code-asher** [comment]
Fixed by https://github.com/cdr/code-server/commit/73cf8f34e32f854ed3d36456cdf0a665b04e779c.
