### ISSUE TITLE
[v2] Java language support does not work with code-server 2.1662-vsc1.39.2

### ISSUE THREAD

**Issue by emil-simeonov-se** [cdr/code-server#1129]
No dublicate issues found

- `code-server` version:
Java language support does not work with:
```
info  2.1662-vsc1.39.2
info  766efd6079d614c577ab411cfc3b655b0d21ad77
info  x64
```
Java language support is there with:
```
info  2.1657-vsc1.39.2
info  f65c9b23fc4d984e2f3c1885bbd617efe4cdefe9
info  x64
```
- OS Version: macOS Catalina, Docker Desktop 2.1.0.4, checked both with latest Firefox and Chrome

## Description

The extension `vscjava.vscode-java-pack` seems to misbehave with `2.1662-vsc1.39.2` and it seems the Java Language Server does not start at all (IntelliSense is not there, Java Test Runner does not work, etc.). Everything works as expected if I just downgrade with 1 release, i.e. `2.1657-vsc1.39.2`

Note that this is probably not related to the extension itself as its version is not changed. Only the version of `code-server` is bumped.

## Steps to Reproduce

1. Install `vscjava.vscode-java-pack` from the code-server marketplace 
2. Open a simple Maven project
3. Try to use any feature related to Java development, e.g. running a test, autocompletion, etc.

**Comment by code-asher** [comment]
2.1665-vsc1.39.2 was just released which should fix this issue. Had a very unfortunate mistyped scheme in the URI transformer which cause a whole bunch of issues.

**Comment by emil-simeonov-se** [comment]
`2.1665-vsc1.39.2` definitely fixes it. Thank you very much for the quick fix.
