### ISSUE TITLE
What do I need to do to get marlon407.code-groovy extension on the coders marketplace?

### ISSUE THREAD

**Issue by emil-simeonov-se** [cdr/code-server#1131]
## Description

The only VS Code extension that provides some kind of Groovy language support (except for the built-in syntax highlighting) is not part of the Coders marketplace. How can we bring it there?

Link to extension: https://marketplace.visualstudio.com/items?itemName=marlon407.code-groovy
Unique Id: `marlon407.code-groovy`

**Comment by kylecarbs** [comment]
Our extension marketplace fetches based on GitHub URLs.

Adding https://github.com/marlon407/code-groovy now :)

**Comment by kylecarbs** [comment]
Added the extension to our source list. It's now on the marketplace 🎊
