### ISSUE TITLE
Special characters not working

### ISSUE THREAD

**Issue by KrapK** [cdr/code-server#1133]
- `code-server` version: 2.1665
- OS Version: Debian 10 WSL

## Description

Special characters like accented letters, backticks(``), ´´, ¨, etc can't be written in any text input inside code-server

**Comment by sr229** [comment]
How exactly this crashes code-server? I'm trying it on Edge Insiders and in a Debian WSL2 container and it works fine. Same goes with WSL1.

**Comment by KrapK** [comment]
Sorry about the tag, didn't know bug tag is for crashes.
Anyway, I'm using latest Edge Dev and I can't type those characters with my physical keyboard in any possible way. It might be an issue in my end only but it also happened with old releases.

**Comment by code-asher** [comment]
`bug` sounds accurate for this issue IMO. 

I assume it works fine for you in local VS Code and in other web pages yeah?

**Comment by KrapK** [comment]
Yep, it works outside code-server

**Comment by gpid007** [comment]
Issue confirmed with builds above codercom/code-server:2.1688-vsc1.39.2
It appears to be related to Chrome browser as this does not happen in Firefox
Could you please advise on possible fixes?

**Comment by gabrieldesar** [comment]
Same problem here

code-server
Version: 1.39.2
Commit: 44c4722edfa107215824ac96fa9ae79c785880cb
Browser: Chrome/79.0.3945.88

**Comment by sr229** [comment]
Hey all, please try it on Visual Studio Online and see if they support special characters.

I got a hunch this is a upstream issue.

**Comment by KrapK** [comment]
Tried it now, working as expected using Chromium Edge Version 81.0.381.0

**Comment by sr229** [comment]
For now I'll mark this as resolved but if it persists let me know

**Comment by KrapK** [comment]
Woops, I meant that I tried Visual Studio Online and everything works fine there. Sorry for the confusion :C

**Comment by KrapK** [comment]
Just tried latest Code Server 2.1698-vsc1.41.1 and characters work fine now 😄
