### ISSUE TITLE
PowerShell Extension outdated? Latest should be v2019.9.0

### ISSUE THREAD

**Issue by pcgeek86** [cdr/code-server#1134]
- `code-server` version: v1.1156-vsc1.33.1
- OS Version: Using Docker image
- Extension: https://github.com/PowerShell/vscode-powershell/releases

## Description

The current PowerShell extension for VSCode is much newer than the one that gets installed in `code-server`. Is `code-server` pulling extensions from the Visual Studio Marketplace, or somewhere else?

The version that gets installed from a fresh `code-server` container is `1.11.0` instead of `v2019.9.0`.

## Steps to Reproduce

1. Run a new `code-server` container
1. Search for and Install PowerShell extension

**Comment by pcgeek86** [comment]
I just tried to install the latest PowerShell extension from the `.vsix` file.

```
coder@782b5a363163:~/project$ code-server --install-extension PowerShell-2019.9.0.vsix 
(node:757) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
INFO  code-server v1.1156-vsc1.33.1
ERROR (node:768) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ERROR 
ERROR Unable to install extension 'ms-vscode.powershell' as it is not compatible with VS Code '1.33.1'.
ERROR 
ERROR Failed Installing Extensions: PowerShell-2019.9.0.vsix
ERROR 
```

**Comment by sr229** [comment]
@kylecarbs might need to sync our repo again?

**Comment by nhooyr** [comment]
See #1299
