### ISSUE TITLE
Opening settings in Firefox causes typing to stop working properly elsewhere

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#1135]
It doesn't seem to matter how you open the settings (mouse, keyboard, refresh with it already open, tab over to it) and it doesn't seem to matter if or how you close it. Once the settings input has been focused certain keys stop working in editor windows (like Enter and the down arrow).

This happens with or without the selection clipboard enabled. No other inputs exhibit this behavior.

My current guess is that there is some focus-related event that is handled differently or improperly in Firefox (or Chrome has incorrect behavior that VS Code depends on).

**Comment by sr229** [comment]
Confirming this is a upstream issue, I'll mirror this over to Microsoft when able.

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
