### ISSUE TITLE
sqltools extension never connects

### ISSUE THREAD

**Issue by vnijs** [cdr/code-server#1140]
- `code-server` version: 2.1665-vsc1.39.2
- OS Version: Ubuntu 18.04 in Docker

SQLTools:
- https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools
- https://github.com/mtxr/vscode-sqltools

## Description

Connection Assistant doesn't start for 3-4 minutes and then doesn't allow connection information to be submitted and stored.

## Steps to Reproduce

1. Install the SQLtools extension
2. Start the extension and click in the "Connections box" to create a new connection. 
3. A black page will open but the connection assistant won't start. See last screenshot below for what it should look like. 
4. If you wait long enough, however (i.e., 3-4 minutes), the icons do show up. When trying to submit information about the connection through a form (see below) there is an error about "form's frame is sanboxed and the 'allow-forms' permission is not set". Could "allow-forms" be an argument that could be set for codeserver on launch? "Test connection" works fine.

![image](https://user-images.githubusercontent.com/2998956/68059694-aa224500-fcba-11e9-9056-9d27f44cc863.png)

![image](https://user-images.githubusercontent.com/2998956/68059654-7e9f5a80-fcba-11e9-8193-d36db0c06cc0.png)

Page in VScode on macOS:

![image](https://user-images.githubusercontent.com/2998956/68047255-27d65880-fc9b-11e9-8cb2-0d40dc73a0f4.png)

**Comment by vnijs** [comment]
Thanks for the updates @nhooyr. I'm using the latest release of code server and you are correct that the form now shows up! However, I still cannot get the extension to connect (see console errors below). I can access the postgres server that is part of the docker container I'm using from R and Python scripts open in codeserver but not using sqltools however. Bug in the extension?

![image](https://user-images.githubusercontent.com/2998956/73319681-f7e31680-41f1-11ea-9220-f3daae406e1e.png)

**Comment by nhooyr** [comment]
Can you try killing sqltools the process listening on port 8080 and try again?

**Comment by vnijs** [comment]
I changed the port number for the app that was previously running on 8080. sqltools now doesn't throw an error when I start it up but never connects to the postgres database and just hangs . When I refresh the browser sqltools complains about crashing "5 times in the last ..." again. 

Postgres from the docker container (vnijs/rsm-msba) works fine when connecting from R and Python (https://github.com/radiant-rstats/docker/blob/master/postgres/postgres-connect.ipynb) and also the jupyterlab-sql extension for jupyterlab ... but no luck sofar with sqltools

**Comment by nhooyr** [comment]
Very weird. Any ideas @mtxr?

**Comment by mtxr** [comment]
@nhooyr hey guys, pretty cool project code-server!

I'll take a look this weekend, ok? I wasn't aware of the project till you reach me, but I'll give it a try and check possible fixes for you 💪

**Comment by nhooyr** [comment]
Thank you @mtxr!

**Comment by massimocireddu** [comment]
Hi @mtxr @nhooyr ,
Thank you for your great work on sqltools extension and code-server.

I've tried to change the code-server port but it didn't solve the issue.

Do you have any update about how to solve the issue?

Thanks.

**Comment by nhooyr** [comment]
Looks like this extension doesn't work at all anymore.

No drivers are available.

@cmoog Can you please try to install and get it running?

**Comment by mtxr** [comment]
The extension is fixed already. I didn't test it on code server to be
honest, but shouldn't be a problem I believe

**Comment by nhooyr** [comment]
@mtxr Sorry I mean on our marketplace it doesn't work yet. We have no drivers published.

**Comment by thegrapesofwrath** [comment]
@mtxr I am on vscode 1.47.1 and the extension no longer works. It worked previously and I have tried reinstalling it but all I get is a black screen. I am unable to add any connections. Bummer because it was useful.

**Comment by vumaasha** [comment]
unable to install these drivers from code-server marketplace PostgreSQL/Redshift Driver. Can you please help
