### ISSUE TITLE
c++ configure bug

### ISSUE THREAD

**Issue by milkboylyf** [cdr/code-server#1144]
- `code-server` version: code-server2.1665-vsc1.39.2
- OS Version: centos7.4

## Description

I run code-server in Centos7.4 by run the code-server binary file code-server2.1665-vsc1.39.2-linux-x86_64.tar.gz. And then I use it to run a simple c++ program. But it 
report debug like below:

**Unable to start debugging. Launch options string provided by the project system is invalid. The type initializer for 'System.Xml.Serialization.XmlSerializationReader' threw an exception.**

## Steps to Reproduce
I configure my c++ program by referencing the "GCC on Windows Subsystem for Linux" in URL:https://code.visualstudio.com/docs/cpp/config-wsl

**Comment by sr229** [comment]
Don't follow the WSL documentation reference, you should follow the Linux configuration documentation instead.
