### ISSUE TITLE
Add password to latest release of codeserver

### ISSUE THREAD

**Issue by PyExtreme** [cdr/code-server#1146]
How to add password to latest release of codeserver?
I have tried using `export PASSWORD='pass'` but it didn't work.

Thank you

**Comment by sr229** [comment]
if you're using the legacy way

```
export PASSWORD="uwu"

./code-server --port=9000 --auth=password
```
that won't work, do it this way instead:

```
export PASSWORD="uwu"
./code-server --port=9000
```

**Comment by thierschi** [comment]
Hello,
I have exactly the same problem: Trying to run code-server on a azure VM running Ubunut 18.04 permanently, but setting the password does not work, neither with --auth=password nor without it. Never got it to work on a GCP VM too.

**Comment by PyExtreme** [comment]
Hi @sr229 , I've checked the mentioned method but it is not working. Please have a look.

**Comment by sr229** [comment]
> Hi @sr229 , I've checked the mentioned method but it is not working. Please have a look.

Try putting `--auth=password` or do it this way
```
PASSWORD="uwu" ./code-server [flags]
```

**Comment by PyExtreme** [comment]
Hi @sr229 , I have installed the next release and it worked.

Thank you
