### ISSUE TITLE
Web Socket connection failed after login with blank page

### ISSUE THREAD

**Issue by foryou8033j** [cdr/code-server#1147]
- code-server2.1665-vsc1.39.2-linux-x86_64
- Apache/2.4.18
- Ubuntu 16.04
- enable proxy proxy_http proxy_balancer proxy_connect deflate proxy_ajp
- Chrome, Edge, IE, Firefox

## Chrome Developer Console

![주석 2019-11-05 051247](https://user-images.githubusercontent.com/16064376/68154482-facfc180-ff8a-11e9-8968-a3a2bfe08d9c.png)

## Apache Error Log
```
No protocol handler was valid for the URL /. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.
```
... Is there a module i forgot?

## Description
I just follow [This](https://github.com/cdr/code-server/blob/master/doc/quickstart.md) quickstart guide 
but i got a blank page after login with Socket connection fail message

## Related Issues
#1122 , unlike this issue, i just using HTTP

**Comment by zhang3r** [comment]
I ran into this issue before, turns out my ingress was swallowing the websocket update message. so i had to switch to use node port to expose the port instead. check if anything is block the websocket update message.

**Comment by danger89** [comment]
I see the same issues, I'm using a Nginx reverse proxy", using this setup: https://github.com/cdr/code-server/blob/master/doc/quickstart.md

With the [docker-compose](https://github.com/cdr/code-server/blob/master/docker-compose.yml).

**Comment by mirsella** [comment]
hello @danger89 have you successfully fix this issue ? i'm facing the same problem

**Comment by nhooyr** [comment]
#1331

**Comment by sionuume** [comment]
Check out here: https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-securely-access-web-services
