### ISSUE TITLE
"Select TypeScript version" command doesn't work

### ISSUE THREAD

**Issue by xbtsw** [cdr/code-server#1153]
- `code-server` version: 2.1665-vsc1.39.2-linux-x86_64
- OS Version: Debian GNU/Linux 10 (buster)

## Description
This command have no effect.

![image](https://user-images.githubusercontent.com/4098537/68241822-3aff6600-ffc4-11e9-9a6c-56857b3b2368.png)

## Steps to Reproduce

1. Load code-server
2. Ctrl+Shift+P and select this command

**Comment by xbtsw** [comment]
I found that when a new user-data-dir is being populated, the visit to code-server must be from localhost. Using any other domain will lead to this behavior.

**Comment by sr229** [comment]
related to GH-999

**Comment by Dj-jom2x** [comment]
at centos 8 this is the issue but v2 at centos 8 are more stable than ubuntu.. for me. the only downside there is cant pick typescript version and cant copy and paste

**Comment by nhooyr** [comment]
Works fine now. If this is still a problem, please feel free to reopen.
