### ISSUE TITLE
vscodevim doesn't work

### ISSUE THREAD

**Issue by xbtsw** [cdr/code-server#1154]
- `code-server` version: 2.1665-vsc1.39.2-linux-x86_64
- OS Version: Debian GNU/Linux 10 (buster)
- Extension: https://github.com/VSCodeVim/Vim (1.11.3 installed from default marketplace)

## Description

After installation it has no effect.

## Steps to Reproduce

1. In extensions tab, install vscodevim 1.11.3
2. Open any file attempt to edit

**Comment by code-asher** [comment]
Just to confirm, did you refresh the browser after installing the
extension? Currently the page needs to be reloaded after installing an
extension.

**Comment by xbtsw** [comment]
Yes I did. After some investigation it turns out because of Safari. It doesn't support the new `RegExp` feature that `vscodevim` used. Use Chrome then it will work as normal.

After installing `vscodevim`, if I keep refresh Safari, there's a 50% chance it will show a message saying failed to load the extension because of invalid group qualifier in `RegExp`.

Which is very sad because for iOS devices, they are stuck with Safari (Chrome for iOS is still Safari). And for those devices vim key bindings is quite necessary.

I did a bisect and found the last working version of `vscodevim` that works inside Safari is 0.17.3.

**Comment by code-asher** [comment]
Ahh yeah that makes sense. I'd forgotten it has that issue on Firefox.
I think we'll need to send a fix to vscodevim (or Firefox/Safari but I
imagine that would be more difficult).

**Comment by code-asher** [comment]
> During the investigation I also noticed that if I use `--extra-extensions-dir` to load the extension, without modifying `publisher` or `name`, then `code-server` will keep attempting to update the extension and download an extra copy of latest and put into `<user-data-dir>/extensions`

Oof yeah I just ran into that yesterday. I'll open another issue for it.

**Comment by xbtsw** [comment]
Firefox seems working on their regex implementation to be the same as Chrome.
> Yes. My work is to re-sync our irregexp implementation with the one that is used in V8. When I'm done, our regexps should be at feature parity with Chrome.
[Link](https://bugzilla.mozilla.org/show_bug.cgi?id=1225665#c26)

But Safari seems not fixing this anytime soon.

I would love to contribute a fix to `vscodevim`. But I have such a difficult time trying to figure out how to debug extension when loaded in Safari. The error doesn't have any meaning stack, I tried to put `debugger;` in the `vscodevim` source but Safari doesn't seem to respect that.

I cannot use vscode to do the debugging, because this only repros in Safari. Any pointers?

**Comment by code-asher** [comment]
That's good news about Firefox!

Yeah debugging is going to be really hard due to the way we load
client-side extensions. I'm not sure it can be improved at all but I
should look into it at some point.

I think `debugger;` should work but since the extension is cached you
might need to check the "disable cache" box in the devtools if there is
one or clear the cache before loading the page.

**Comment by xbtsw** [comment]
Thanks for the tip about cache, that explains a lot of mysterious behavior when I was debugging it. 

Unfortunately `debugger;` doesn't work even in Chrome, so I am pretty stuck to find out which exact RegExp is failing. For now I think I have to settle with vscodevim 0.17.3.

**Comment by muammar** [comment]
> Thanks for the tip about cache, that explains a lot of mysterious behavior when I was debugging it.
> 
> Unfortunately `debugger;` doesn't work even in Chrome, so I am pretty stuck to find out which exact RegExp is failing. For now I think I have to settle with vscodevim 0.17.3.

 Installing `vscodevim` 0.17.3 did not solve the problem for me.

**Comment by black-desk** [comment]
> > Thanks for the tip about cache, that explains a lot of mysterious behavior when I was debugging it.
> > Unfortunately `debugger;` doesn't work even in Chrome, so I am pretty stuck to find out which exact RegExp is failing. For now I think I have to settle with vscodevim 0.17.3.
> 
> Installing `vscodevim` 0.17.3 did not solve the problem for me.

me, too

**Comment by patrikzudel** [comment]
Has anyone figured out a workaround? For now I use the amVim extension on iOS but the feature set of it isn’t as rich sadly. Or does anyone have a better alternative?

**Comment by xbtsw** [comment]
@muammar @black-desk, for 0.17.3 you will need to install the node_modules manually for the extension. 

As of 1.12.0 of vscodevim, even chrome stopped working because of the usage of `fs.readFileSync()` from the extension.

**Comment by black-desk** [comment]
@xbtsw I had tried 1.0.0,1.9.0 and 1.11.3, none of them work.

**Comment by xbtsw** [comment]
@black-desk if you load an older version, code-server will attempt to upgrade it to latest - which will make it stop working. You will need to modify the manifest file and give it a new name.

**Comment by nhooyr** [comment]
Regarding the missing modules see #1299 

Otherwise, the issue is with firefox/safari.

**Comment by dmin7b5** [comment]
I can happily confirm that with iPadOS 13.4 (GM) amVim works if you go into the Keyboard settings and map the Caps Lock key to Esc. I'm using the Brave browser.

**Comment by muammar** [comment]
> I can happily confirm that with iPadOS 13.4 (GM) amVim works if you go into the Keyboard settings and map the Caps Lock key to Esc. I'm using the Brave browser.

Thanks for this. I confirm that `amVim` extension works for me. I am using Safari. I access the `Esc` key with `Ctlr + [`.
