### ISSUE TITLE
Remote Development Extension

### ISSUE THREAD

**Issue by hyeongyun0916** [cdr/code-server#1155]
Can I use this extension?
https://github.com/Microsoft/vscode-remote-release

**Comment by sr229** [comment]
AFAIK you can use it but none of us has tested it that it actually works. Please open a new issue if those doesn't work.

**Comment by roflcoopter** [comment]
> Can I use this extension?
> https://github.com/Microsoft/vscode-remote-release

Did you get it to work? For med it does not show up at all when installed.

**Comment by tuxfamily** [comment]
Just tested: it's a YES and NO.

It seems that the latest version of the extension is not compatible with the vscode version shipped (and it's probably why it is not listed in the available extensions).

At time of writing, it is 0.48.0

```
./code-server --install-extension ms-vscode-remote.remote-ssh-0.48.0.vsixInstalling extensions...
Unable to install extension 'ms-vscode-remote.remote-ssh' as it is not compatible with VS Code '1.39.2'.
```

BUT, I've tested to manually "downgrade" and use an old version, and it works with the preivous version 0.47.0

```
./code-server --install-extension ms-vscode-remote.remote-ssh-0.47.0.vsix
Installing extensions...
Extension 'ms-vscode-remote.remote-ssh-0.47.0.vsix' was successfully installed.
```

You can download this version here:
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode-remote/vsextensions/remote-ssh/0.47.0/vspackage

(change 0.47.0 for other versions)

**Comment by roflcoopter** [comment]
I did the same but I went back further to older versions, however it won't connect to the remote machine.

Does 0.47.0 connect properly?

**Comment by tuxfamily** [comment]
Well, after more tests... NO :(

The extension is well installed, it appears in the left sidebar, hosts are well listed, but next, trying to connect to an host just refresh the window and nothing happen.

I tried debugging but nothing show nowhere, so... no clue. Too bad.

**Comment by roflcoopter** [comment]
Same experience here unfortunately

**Comment by qfettes** [comment]
With the release 2.1698-vsc1.41.1 of code server, it's possible to successfully install remote-ssh version 0.48.0:
```
./code-server --install-extension ms-vscode-remote.remote-ssh-0.48.0.vsix 
Installing extensions...
Extension 'ms-vscode-remote.remote-ssh-0.48.0.vsix' was successfully installed.
```
However, the extension is still not functional. Instead, it is grayed out with a warning that reads (also pictured)
> This extension cannot be enabled in the remote server

Support for this extension is essential for me personally.


![Screenshot 2020-01-18 at 4 38 34 PM](https://user-images.githubusercontent.com/8574075/72670956-bf815280-3a11-11ea-8b19-09890e908349.png)
