### ISSUE TITLE
ms-vscode.cmake-tools Quick Start command failed

### ISSUE THREAD

**Issue by xerothermic** [cdr/code-server#1158]
- `code-server` version: 2.1665-vsc1.39.2
- OS Version: Ubuntu 18.04
- Extension: ms-vscode.cmake-tools

## Description
CMake Tools extension has a convenient command: "CMake: Quick Start" which in the desktop version of VSCode will prompt two questions from the command prompt (1. project_name, 2. library or executable). With these two information, it will generate a nice template of CMakeLists.txt

However, when running the same command on code-server, the prompt never showed up and CMakeLists.txt never created.

## Steps to Reproduce

1. Open command prompt and type: CMake: Quick Start
2. (Expect) prompt for project name and library/executable. (Actual) nothing happened.

**Comment by nhooyr** [comment]
Works fine now. If this is still a problem, please feel free to reopen.
