### ISSUE TITLE
Connection gettting failed repeatedly

### ISSUE THREAD

**Issue by PyExtreme** [cdr/code-server#1161]
I am using the latest release of code-server released yesterday and the connection is failing again and again. Also, I have no internet issues and I have tested on different networks as well.

Attached is the screenshot which I am getting

![Screenshot from 2019-11-09 13-51-34](https://user-images.githubusercontent.com/45779665/68525642-b715e880-02f9-11ea-8b92-d7a35637620d.png)

**Comment by sr229** [comment]
Is this on a remote server or your local instance?

**Comment by elzafirox** [comment]
The same incident occurs to me, on a remote server, sometimes it connects quickly, others if it takes or does not.

**Comment by sr229** [comment]
I'm not able to replicate this, might be a QoS issue with your ISP?

**Comment by crossan007** [comment]
I'm seeing this too with codercom/code-server@sha256:e614b21e92593483d379d6a6bac77f283f988ec59207cd224a8ad6272c0f7208

**Comment by crossan007** [comment]
Might be related to #1147, #442

**Comment by crossan007** [comment]
I was having this issue when my VSCode instance was behind a Traefik reverse-proxy instance.  When I exposed the VSCode container's port 8080 directly, the websocket seemed to connect fine.

**Comment by geiseri** [comment]
I see this too with traefik, I am wondering if the websocket token is messed up.  I can't tell though because it seems verbose in the latest build are broken.

**Comment by geiseri** [comment]
I think this might actually be traefik specific.  It seems to work with nginx.

**Comment by geiseri** [comment]
I think it might be related to: https://github.com/containous/traefik/issues/5533#issuecomment-553823512

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
