### ISSUE TITLE
Very old svelte extension version

### ISSUE THREAD

**Issue by cortopy** [cdr/code-server#1162]
- `code-server` version:  2.1665-vsc1.39.2
- OS Version: Ubuntu 18
- Extension: https://marketplace.visualstudio.com/items?itemName=JamesBirtles.svelte-vscode

## Description

I don't quite understand why, but the version of this extension in the code-server is way to old and it causes a lot of problems. The version available is 0.4 which was released in 23 May 2018. There have been five more releases since then

Is this one of the limitations of the code-server marketplace?

**Comment by sr229** [comment]
Assigning @kylecarbs. Looks like the marketplace needs updating again.

**Comment by nhooyr** [comment]
#1299
