### ISSUE TITLE
Activating extension 'redhat.java' failed. Cannot read property 'join' of null.

### ISSUE THREAD

**Issue by WJayesh** [cdr/code-server#1163]
- Version: 1.39.2
- Commit: 2018024810269eeaa5ce868e555d5476da2a626d
- Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
- Extension: https://marketplace.visualstudio.com/items?itemName=redhat.java

## Description

I am trying to run a Java project but the extensions don't get activated. I have JDK installed and `java.home` set in `settings.json`. 

## Steps to Reproduce

1. Build an image from this [Dockerfile](https://github.com/WJayesh/Dockerfiles/blob/master/code-server-java)
1. Run a container and open `localhost:8080`
3. Open terminal and clone a repository. 
4. Click on any file to get prompted with this notification

![Screenshot from 2019-11-10 22-03-23](https://user-images.githubusercontent.com/37150991/68543160-74c3d880-03d9-11ea-94c2-b59d5b087d81.png)

**Comment by sr229** [comment]
We're getting reports it works fine in other systems, might be a Firefox-specific issue since extensions also has a client-side worker working while its backend runs.

**Comment by newk5** [comment]
> We're getting reports it works fine in other systems, might be a Firefox-specific issue since extensions also has a client-side worker working while its backend runs.

I'm getting the same error here, in firefox and chromium(74). I'm running ubuntu 16.04

**Comment by WJayesh** [comment]
I am getting the same result on Chrome too. Can you inspect the Dockerfile to see if I'm missing something? Thanks

**Comment by newk5** [comment]
Not sure if this makes a difference but I'm not using docker, I just downloaded the binary and ran it.

**Comment by IUSR** [comment]
Having the same problem using the latest Docker image and Firefox developer edition 71.0b8:

> Version: 1.39.2
> Commit: 2018024810269eeaa5ce868e555d5476da2a626d
> Date: 2019-11-07T22:06:35.047Z
> Browser: Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0

If a web worker problem is suspected, there's an error on the JS console that seems relevant:

> Failed to register/update a ServiceWorker for scope ‘https://xxxxxx/’: Bad Content-Type of ‘text/html’ received for script ‘https://xxxxxx/service-worker.js’.  Must be a JavaScript MIME type.

navigating to this "service-worker.js" from within the browser, I could see it's actually an HTML page, so the complaint looks legit.

BTW my set up uses HTTPS terminated by Nginx and forwards everything to the plaintext HTTP port of coder-server, so I don't expect a problem caused by Nginx when forwarding "service-worker.js".

**Comment by aak1247** [comment]
Same error with chrome(78) and binary running on debian 9(deepin 15)

**Comment by WJayesh** [comment]
If it helps, the `codercom/code-server:2.1657-vsc1.39.2` image does not have this particular problem. 
There instead, when you select _run/debug_ from the context menu or select any Java command like "_create a project_" from the command palette; "Activating _Extensions"  appears for a while on the status bar and there's no further activity @sr229

**Comment by sr229** [comment]
Probably need to do some investigation

CC @code-asher

**Comment by code-asher** [comment]
From what I've seen (https://github.com/cdr/code-server/issues/1136#issuecomment-549534426) the `join` error is because the extension is missing files. You can try:

```
npm install
./node_modules/.bin/gulp download_server
```

But we need to look into our marketplace and figure out why this is failing to fully build. At least, I think that's the source of the problem.

**Comment by code-asher** [comment]
Linked the wrong comment. Here's the right one: https://github.com/cdr/code-server/issues/1136#issuecomment-548939405

**Comment by code-asher** [comment]
Huh, but if earlier images don't have the problem then the issue you could be in the install phase in code-server rather than our marketplace.

**Comment by sstone1** [comment]
@code-asher I'm seeing a similar problem with `ms-vscode.go` - the version installed by `code-server --install-extension ms-vscode.go` does not have a `node_modules` folder, so fails to activate as one of its dependencies is missing.

**Comment by DreamUFO** [comment]
same issue 
centos 6.5
code-server Version: 1.39.2
Commit: 2018024810269eeaa5ce868e555d5476da2a626d
Date: 2019-11-07T22:06:35.047Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36

not docker version  install manually code-server2.1688-vsc1.39.2-linux-x86_64.tar.gz

I have JDK installed and java.home set in settings.json. system env have JAVA_HOME JDK_HOME too.

![image](https://user-images.githubusercontent.com/10512112/69111838-c0e9d980-0ab9-11ea-9cbf-3ca8bfc565a0.png)

**Comment by sstone1** [comment]
@code-asher @sr229 is there an update on this and similar issues with files missing in extensions downloaded from the Code Server marketplace?

**Comment by nhooyr** [comment]
See #1299
