### ISSUE TITLE
When using python extension jupyter notebook, changing python envs has no effect on the notebook kernel. 

### ISSUE THREAD

**Issue by alan-he** [cdr/code-server#1165]
- `code-server` version: code-server2.1478-vsc1.38.1-linux-x86_64
- OS Version: docker(Ubuntu 16.04.5 LTS)
- Extension: python extension(2019.10.44104)

## Description

When using python extension jupyter notebook, changing python envs has no effect on the notebook kernel immediately.  Run notebook cell still using last python kernel, the new switched do not work.
You have to refresh the browser and reload the vscode workspace. Only that can make notebook kernel change to the switched python env.

## Steps to Reproduce
1. code-server installed python extension.
2. prepare two python envs, one with tensorflow, another pytorch.
3. new 2 ipynb files, one import tensorflow, another import pytorch.
4. execute ipynb with tensorflow python env, and switch pytorch env to execute another pytorch ipynb. No module Named 'torch' will reported
5. refresh browser, and notebook will work corrently

**Comment by NegatioN** [comment]
Not affiliated with the project at all, but I'm quite sure this is a limitation of vscode right now.

They have a plan to fix it, and use something that is more similar to jupyter https://github.com/microsoft/vscode-python/issues/8207

**Comment by nhooyr** [comment]
Thank you @NegatioN
