### ISSUE TITLE
Adding binaries (e.g., Julia)

### ISSUE THREAD

**Issue by Nosferican** [cdr/code-server#1166]
## Description

I am trying to use the Julia language extension. For that, I need to pass the path to the binary. I have been trying to find some documentation on how to accomplish this. May be a generic Docker issues, but since I can think of a few alternatives, I wanted to know if there is a recommended approach or docs on how to do so...

For example, could I add the Julia binaries from a Julia container for the code-server container to use?

**Comment by sr229** [comment]
You'll need to install it manually by deriving from our image, or use the APT install inside your container.

Be warned, the latter does not persist your changes, so do it as a image instead.

**Comment by sr229** [comment]
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.

**Comment by Nosferican** [comment]
Worked like a charm. Thanks!

**Comment by Nosferican** [comment]
Leaving this for those that might have questions about adding binaries,
Here is an example for extending this container with Julia, Python, and R.
https://github.com/Nosferican/docker-vscode-jupyter/blob/master/Dockerfile
