### ISSUE TITLE
Where is the dockerFile located?

### ISSUE THREAD

**Issue by Justinborzi** [cdr/code-server#1167]
Hello! I have searched high and low and cannot seem to find the dockerfile as I need to add something to it. I used digital oceans image for code-server and have not found it anyway. would love to be pointed in the correct direction!

**Comment by sr229** [comment]
The Dockerfile is located in the root of this repository, if that's what you're looking for ;)

**Comment by Justinborzi** [comment]
see, I know. I have viewed the github. aswell as looked all over my machine but the dockerfile literally does not exist and thats what is confusing me.

**Comment by sr229** [comment]
![image](https://user-images.githubusercontent.com/14976516/68767356-83212700-065b-11ea-9a87-b1f9a17b4aef.png)

It's right in the root of the repository.
