### ISSUE TITLE
Live Server Extension will not load

### ISSUE THREAD

**Issue by misterjtc** [cdr/code-server#1168]
- `code-server` version: 1.39.2
- OS Version: Unraid 6.7.2/Docker 18.09.6
- Extension: https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

## Description

When I install the extension through the market place, I get the following error:

![image](https://user-images.githubusercontent.com/37029702/68608895-0424c680-0482-11ea-8952-52305edf998d.png)

## Steps to Reproduce

1. Install Live Server from the market place with VS Code / Coder
1. Reload.

**Comment by sr229** [comment]
Have you tried it in VS Online? If it does not replicate there, then I think we have a broken extension again.

**Comment by misterjtc** [comment]
I have not tried it in VS Online. I tried doing this the other day but I couldn't get a local environment going. Will report back if I am able to do this.

**Comment by nhooyr** [comment]
See #1299
