### ISSUE TITLE
[v2] Kotlin language support through fwcd/vscode-kotlin-ide does not work

### ISSUE THREAD

**Issue by emil-simeonov-se** [cdr/code-server#1169]
- `code-server` version: 2.1688-vsc1.39.2 and also older releases
- OS Version: Ubuntu 18.04 Docker image
- Extension: https://github.com/fwcd/vscode-kotlin-ide

## Description
`code-server` has two major issues with the most mature extension for Kotlin language support (`fwcd/vscode-kotlin-ide`) extension.
1. It seems to be outdated. Current version on Microsoft marketplace is: `0.2.10` and the one from the code-server's marketplace is `0.1.13`.
2. The language server cannot be started when opening a Kotlin file.

**From the Console in Web Developer Tools...**
```
 ERR spawn /home/coder/.local/share/code-server/extensions/fwcd.kotlin-0.1.13/server/build/install/server/bin/server ENOENT: Error: spawn /home/coder/.local/share/code-server/extensions/fwcd.kotlin-0.1.13/server/build/install/server/bin/server ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
	at onErrorNT (internal/child_process.js:415:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```
This is because the language server is probably not built at all or at least I cannot find this path `build/install/server/bin/server` within the server folder of the extension.

## Steps to Reproduce

1. Decompress the attached and zipped Maven project with Kotlin support (`kotlin-demo.zip`) in a dedicated folder.
2. Navigate to the project folder and build a Docker image out of the Dockerfile within.
3. Run a Docker container based on the image locally.
4. Open `http://localhost:8080`. You will notice a notification that the Kotlin language server (client) cannot be run.

[kotlin-demo.zip](https://github.com/cdr/code-server/files/3832710/kotlin-demo.zip)

**Comment by emil-simeonov-se** [comment]
By the way, how could I add the `extension` label? It used to be added automatically when I was creating Extension-related issues before. This time, not the case.

**Comment by emil-simeonov-se** [comment]
Considering https://github.com/cdr/code-server/issues/1176#issuecomment-553910849, can you share any plans about when the `code-server` registry will be updated to the point that it builds extensions correctly? For example, lack of decent Kotlin support is a show-stopper for me. I would love to find ways to work around it on my side, so if you can share any hints, I would be glad.

**Comment by sr229** [comment]
I've been inquiring the team about it but there are no solid plans as of

**Comment by emil-simeonov-se** [comment]
Thank you for the update. Well, it's a pity. Let's see when this will happen then.

**Comment by kylecarbs** [comment]
@emil-simeonov-se working on fixing up the extensions right now. This extension has been confirmed fixed 🎊
