### ISSUE TITLE
patch does not apply 

### ISSUE THREAD

**Issue by seeidea** [cdr/code-server#1170]
code-server git:(master) ✗ yarn build 1.40.0 development
yarn run v1.19.1
$ yarn && yarn runner build 1.40.0 development
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
success Already up-to-date.
$ cd ./scripts && node --max-old-space-size=32384 -r ts-node/register ./build.ts build 1.40.0 development
[build] Not running inside VS Code
[build] rootPath is "/apps/product/server/vscode/code-server"
[build] outPath is "/apps/product/server/vscode/code-server/build"
[build] arch is "x86_64"
[build] target is "linux"
[build] vscodeVersion is "1.40.0"
[build] codeServerVersion is "development"
[build] Installing code-server dependencies...took 422ms
[build] Using existing VS Code clone
[build] Using existing VS Code node_modules
[build] Using existing built-in-extensions
[build] Patching VS Code...failed
Command failed: git apply /apps/product/server/vscode/code-server/scripts/vscode.patch
error: patch failed: src/vs/base/common/network.ts:96
error: src/vs/base/common/network.ts: patch does not apply
error: patch failed: src/vs/platform/environment/node/argv.ts:185
error: src/vs/platform/environment/node/argv.ts: patch does not apply
error: patch failed: src/vs/platform/product/common/product.ts:22
error: src/vs/platform/product/common/product.ts: patch does not apply
error: patch failed: src/vs/workbench/api/worker/extHostExtensionService.ts:57
error: src/vs/workbench/api/worker/extHostExtensionService.ts: patch does not apply
error: patch failed: src/vs/workbench/browser/dnd.ts:32
error: src/vs/workbench/browser/dnd.ts: patch does not apply
error: patch failed: src/vs/workbench/browser/web.main.ts:48
error: src/vs/workbench/browser/web.main.ts: patch does not apply
error: patch failed: src/vs/workbench/common/resources.ts:200
error: src/vs/workbench/common/resources.ts: patch does not apply
error: patch failed: src/vs/workbench/contrib/files/browser/views/explorerViewer.ts:47
error: src/vs/workbench/contrib/files/browser/views/explorerViewer.ts: patch does not apply
error: patch failed: src/vs/workbench/contrib/webview/browser/pre/main.js:308
error: src/vs/workbench/contrib/webview/browser/pre/main.js: patch does not apply
error: patch failed: src/vs/workbench/services/environment/browser/environmentService.ts:15
error: src/vs/workbench/services/environment/browser/environmentService.ts: patch does not apply
error: patch failed: src/vs/workbench/services/extensions/browser/extensionService.ts:119
error: src/vs/workbench/services/extensions/browser/extensionService.ts: patch does not apply
error: patch failed: src/vs/workbench/services/extensions/common/extensionsUtil.ts:12
error: src/vs/workbench/services/extensions/common/extensionsUtil.ts: patch does not apply
error: patch failed: src/vs/workbench/services/extensions/worker/extensionHostWorker.ts:36
error: src/vs/workbench/services/extensions/worker/extensionHostWorker.ts: patch does not apply

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by seeidea** [comment]
1 git clone https://github.com/cdr/code-server.git
2 cd code-server
3 vim .travis.yml   for  vscode 1.40.0
4 yarn install
5 yarn build 1.40.0 development

**Comment by seeidea** [comment]
ls code-server/src 
browser  common  media  node

**Comment by seeidea** [comment]
linux == CentOS Linux release 7.2.1511
code-server == master
vs-code == 1.40.0
node == v10.17.0
yarn == 1.19.1

**Comment by sr229** [comment]
@seeidea we haven't supported 1.40.0 yet. Please wait for the patches to be modified for 1.40.0.

**Comment by seeidea** [comment]
cool, thank you
