### ISSUE TITLE
Can't install extension(s)

### ISSUE THREAD

**Issue by mar1ged** [cdr/code-server#1173]
- `code-server` version: 2.1688-vsc1.39.2
- OS Version: Ubuntu 19.10 eoan
- Extension: multiple

## Description

When trying to install extensions from the extension directory I receive "failed to install xyz"
If I follow the link to the download I get another error "cannot get publisher ..." in the browser.

## Steps to Reproduce

1. Open extensions
2. select "java extension pack" or "go" or "gitlens"
3. click "install"
4. see error
![image](https://user-images.githubusercontent.com/16045549/68752078-ffd3e700-0602-11ea-9069-135dc7eefa54.png)

5. click "download manually"
6. see next error
![image](https://user-images.githubusercontent.com/16045549/68751902-b2577a00-0602-11ea-8917-59441ea6c663.png)

**Comment by sr229** [comment]
CC @kylecarbs we have another registry bug apparently.

**Comment by kylecarbs** [comment]
@sr229 can you reproduce?

**Comment by sr229** [comment]
@kylecarbs Extension should install fine by now. If they still don't install, then it's a ISP/Network issue.

**Comment by mar1ged** [comment]
@sr229 can I enable some kind of log to see if such an issue happens on ISP or network level

**Comment by lonng** [comment]
The same issue has occurred.

**Comment by go1dfish** [comment]
I'm also seeing this

**Comment by lonng** [comment]
I have solved this issue, which is caused by ISP network.

**Comment by go1dfish** [comment]
Still failing for me:

https://v1.extapi.coder.com/publishers/esbenp/vsextensions/prettier-vscode/2.0.0/vspackage

**Comment by zigarn** [comment]
Can access the URL (so network is fine), but the path seams to be wrong and give 404:

```shell
$ curl -v https://v1.extapi.coder.com/publishers/vscode-icons-team/vsextensions/vscode-icons/9.5.0/vspackage
* About to connect() to v1.extapi.coder.com port 443 (#0)
*   Trying 216.58.204.115...
* Connected to v1.extapi.coder.com (216.58.204.115) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=v1.extapi.coder.com
* 	start date: Oct 25 14:41:37 2019 GMT
* 	expire date: Jan 23 14:41:37 2020 GMT
* 	common name: v1.extapi.coder.com
* 	issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
> GET /publishers/vscode-icons-team/vsextensions/vscode-icons/9.5.0/vspackage HTTP/1.1
> User-Agent: curl/7.29.0
> Host: v1.extapi.coder.com
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Date: Tue, 19 Nov 2019 00:03:41 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 209
< Vary: Accept-Encoding
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Content-Security-Policy: default-src 'self'
< X-Content-Type-Options: nosniff
< Via: 1.1 google
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /publishers/vscode-icons-team/vsextensions/vscode-icons/9.5.0/vspackage</pre>
</body>
</html>
* Connection #0 to host v1.extapi.coder.com left intact
```

**Comment by go1dfish** [comment]
I was also able to install through CLI get same error as @zigarn otherwise though

**Comment by 6234456** [comment]
the same problem

**Comment by zigarn** [comment]
When installing through the UI, I have this in the logs:

```
[2019-11-28 15:25:14.311] [remoteagent] [info] Installing extension: vscode-icons-team.vscode-icons
[2019-11-28 15:25:14.311] [remoteagent] [trace] Started scanning user extensions
[2019-11-28 15:25:14.314] [remoteagent] [trace] Scanned user extensions: 1
[2019-11-28 15:25:14.314] [remoteagent] [trace] Started downloading extension: vscode-icons-team.vscode-icons
[2019-11-28 15:25:14.314] [remoteagent] [trace] ExtensionGalleryService#download vscode-icons-team.vscode-icons
[2019-11-28 15:25:14.315] [remoteagent] [trace] RequestService#request https://storage.googleapis.com/coder-production-extensions/vscode-icons-team.vscode-icons/9.5.0/Microsoft.VisualStudio.Services.VSIXPackage?redirect=true&install=true
[2019-11-28 15:25:14.334] [remoteagent] [trace] RequestService#request https://storage.googleapis.com/coder-production-extensions/vscode-icons-team.vscode-icons/9.5.0/Microsoft.VisualStudio.Services.VSIXPackage?install=true
[2019-11-28 15:25:14.347] [remoteagent] [error] Failed to install extension: vscode-icons-team.vscode-icons unable to get local issuer certificate
```

Leads to #1007 
The workaround of setting environment variable `NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-bundle.crt` fixes the problem for me.

**Comment by HouCoder** [comment]
@zigarn How did you get the log? I have the same problem on macOS, but I see no detailed log from the OUTPUT panel.

**Comment by zigarn** [comment]
> @zigarn How did you get the log? I have the same problem on macOS, but I see no detailed log from the OUTPUT panel.

Logs are not in STDOUT but in `~/.local/share/code-server/logs`.

**Comment by HouCoder** [comment]
Thanks @zigarn.

This is unfortunate, I used to sync all my settings via Settings Sync extension, now it keeps telling me no internet connection, now I have to install & config them manually, don't know if it relates to this problem.

![image](https://user-images.githubusercontent.com/5292143/69819691-662f4b00-123a-11ea-9ae4-12f3e8cc82e5.png)

**Comment by nhooyr** [comment]
The manual installation is definitely a problem, we forgot to implement the endpoint properly in the extension marketplace.

I'll make sure this is mentioned in #1299 

Otherwise, if installation is still a problem, please feel free to reopen.
