### ISSUE TITLE
What does one need to do to convert a standard VSCode extension to a code-server one?

### ISSUE THREAD

**Issue by emil-simeonov-se** [cdr/code-server#1176]
## Description

There are more and more Github issues related to outdated and/or not working extensions on the code-server's marketplace. In this regards, what does it take to convert a standard VSCode extension to a code-server compatible one? Are there any documentation and examples on that?

I am asking as the community could probably help with porting and maintaining some of the extensions if using the Microsoft marketplace is really a no go from legal perspective.

For example, as part of https://github.com/cdr/code-server/issues/1169 I tried hard to bring the newest version of the Kotlin language server for VSCode to code-server. I also had in mind sharing the outcome with the community. However, I was not successful with running the newest version of https://github.com/fwcd/vscode-kotlin-ide with code-server while I managed to build the Kotlin language server and patch the VSCode extension to contain it.

## Related Issues
https://github.com/cdr/code-server/issues/1169 and also other Github issues reporting outdated and/or not working extensions.

**Comment by sr229** [comment]
I think this is something to deal with broken extensions, not really a compatibility issue since Microsoft has done a lot of stuff to make sure your extensions work without any code modifications to the extension. So this is more of our registry not building stuff properly.
