### ISSUE TITLE
redirected to `code-server://`

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#1179]
- `code-server` version:  1.39.2
- OS Version:  Arch

## Description
Occasionally as i try and open a directory in Firefox, i am redirected to the URL `code-server://example.com/path/on/server`
## Steps to Reproduce
Dont know, if a someone on the dev team is willing to email me i am willing to provide access

**Comment by sr229** [comment]
Must be a bug in upstream, since this might be an artifact of VSCode desktop since they have a `vscode://` handler AFAIK.

**Comment by Merith-TK** [comment]
That is what I was thinking as well. Definitely something to look into

**Comment by nhooyr** [comment]
Please try the latest version. If this is still a problem, please feel free to reopen.
