### ISSUE TITLE
Inserting a new line doesn't work after Find (Firefox)

### ISSUE THREAD

**Issue by waclaw66** [cdr/code-server#1180]
- `code-server` version: 
code-server2.1692-vsc1.39.2-linux-x86_64 and a few previous
- OS Version: 
Fedora 31

Firefox 70 @ Windows 10 1903

## Description
When you use Find function to search something, then press Esc to exit search field and try to insert a new line by Enter, the search field is opened instead of inserting a new line.
It works fine in Chrome though.

## Steps to Reproduce

1. Ctrl+F, type a text, press Enter
2. press Esc, eventually press End to deselect found text
3. press Enter
4. search field is opened again

**Comment by sr229** [comment]
This is a upstream issue, please open it instead in Microsoft/vscode under web.
