### ISSUE TITLE
Menu shortcut missing after clicking few times

### ISSUE THREAD

**Issue by nanotail** [cdr/code-server#1182]
- `code-server` version: 1.39.2
- OS Version: Ubuntu 18.04.3 LTS Safari
- Device: iPad Pro 3rd-Gen

## Description

The menu shortcut on top-left corner (icon with 3 lines) becomes unavailable when using a few times

## Steps to Reproduce

1. Launch vs-code on browser (Safari or Chrome)
2. Tap on the menu icon. Menu pop-up opens.
3. Click anywhere outside
4. Continue steps 2 & 3 couple of times. 

The icon seems to be moving up and apparently disappears. To get the icon back need to refresh the browser.

**Comment by ttfan240** [comment]
Me too. I use iOS 13.2.3 on 10.5 inch iPad Pro.

**Comment by sr229** [comment]
iPad is currently unsupported by VSCode, please open this on vscode upstream with web tag.
