### ISSUE TITLE
Jupyter crashes with latest python extensions

### ISSUE THREAD

**Issue by vnijs** [cdr/code-server#1186]
- `code-server` version: 2.1692-vsc1.39.2
- OS Version: Ubuntu 18.04 in a docker container
- Extension: https://marketplace.visualstudio.com/items?itemName=ms-python.python

## Description

When executing code in a python interactive windows jupyter crashes.

## Steps to Reproduce

1. Open a python file
2. Send to python interactive windows

If you run the vnijs/rsm-msba docker container, start CodeServer (VScode) from Jupyter, install the updated python extension that just came out (2019.11.49689), and try execute some code in the Pythyon Interactive Window (shift-enter) you will see the message "Jupyter server crashed" and the following messages in the developer tools.

![image](https://user-images.githubusercontent.com/2998956/69106756-32774880-0a24-11ea-9858-5e65a25d62f1.png)

**Comment by nhooyr** [comment]
Works fine now. If this is still a problem, please feel free to reopen.
