### ISSUE TITLE
Rust Language Server(RLS) extension not working

### ISSUE THREAD

**Issue by arpan-dhatt** [cdr/code-server#1187]
- `code-server` version: code-server 2.1692-vsc1.39.2
- OS Version: Ubuntu Linux Elementary OS
- Extension: https://github.com/rust-lang/rls-vscode

## Description
After installing the RLS vscode extension and attempting to open an .rs(rust) file I get this error
`Activating extension 'rust-lang.rust' failed: Cannot find module 'vscode-languageclient'.`
## Steps to Reproduce
1. Install rustup(instructions on rust website)
2. Get code-server(I used linux binary)
3. Create a new rust project(I used cargo new --bin rustproject)
4. Install RLS extension
5. Try to open rust file(.rs file extension)

**Comment by sr229** [comment]
Can you try browsing to the extension directory and run `npm install`? This might be a broken extension.

**Comment by arpan-dhatt** [comment]
This has fixed my problem! Thank you
