### ISSUE TITLE
Running docker/docker-compose - "Cannot mkdir, permission denied, EACCES"

### ISSUE THREAD

**Issue by simeneriks1** [cdr/code-server#1188]
- `code-server` version: Current ":latest" tag on docker.
- OS Version:  Debian 9 running in Crostini (chrome os)

## Description

 I am experiencing the following error when running the provided docker command in this repo, and when trying to run from a docker-compose config.

**Docker-compose**
```
simen.eriksen@penguin:~/docker/code-server$ sudo docker-compose up --build
Building code-server
Step 1/2 : FROM codercom/code-server:latest
 ---> 5ace6cdc3088
Step 2/2 : RUN chmod 777 /home/coder/ -R
 ---> Running in 58405903a982
Removing intermediate container 58405903a982
 ---> 20ed880ececf

Successfully built 20ed880ececf
Successfully tagged code-server_code-server:latest
Recreating code-server_code-server_1 ... done
Attaching to code-server_code-server_1
code-server_1  | error EACCES: permission denied, mkdir '/home/coder/.local/share/code-server/extensions'
code-server_code-server_1 exited with code 1
``` 

**Docker:** 
```
simen.eriksen@penguin:~/docker/code-server$ sudo docker run -it -p 127.0.0.1:8080:8080 -v "${HOME}/.local/share/code-serve
r:/home/coder/.local/share/code-server" -v "$PWD:/home/coder/project" codercom/code-server:v2
Unable to find image 'codercom/code-server:v2' locally
v2: Pulling from codercom/code-server
Digest: sha256:1095321ec1038acb23165dc53086b142793ddbb797bf8ee0375ddaf3d7c21a34
Status: Downloaded newer image for codercom/code-server:v2
error EACCES: permission denied, mkdir '/home/coder/.local/share/code-server/extensions'
```

I also tried chmod 777 -R on the home directory in the container with no luck. Not sure if it is directly related to code-server but thought it would be ok to check here

**Comment by simeneriks1** [comment]
Ok so after checking a few more things with a friend of mine, it turns out that docker does the following:

1. Mount/bind volumes as user root:root
2. The container then tries to create a folder in the root-generated directories, as the user "coder" in the container. This returns "permission denied".

See output below:
```
simen.eriksen@penguin:~$ sudo docker run -it -p 127.0.0.1:8080:8080 -v "${HOME}/.local/share/code-server:/home/coder/.local/share/code-server" -v "$PWD:/home/coder/project" --entrypoint /bin/bash codercom/code-server:v2
coder@8de04bb489d6:~/project$ ls
docker
coder@8de04bb489d6:~/project$ cd 
coder@8de04bb489d6:~$ ls
project
coder@8de04bb489d6:~$ cd .local/share/
coder@8de04bb489d6:~/.local/share$ ls
code-server
coder@8de04bb489d6:~/.local/share$ ls -lshd code-server/
0 drwxr-xr-x 1 root root 12 Nov 20 13:17 code-server/
coder@8de04bb489d6:~/.local/share$ cd code-server/
coder@8de04bb489d6:~/.local/share/code-server$ ls
bar  foo
coder@8de04bb489d6:~/.local/share/code-server$ touch baz
touch: cannot touch 'baz': Permission denied
coder@8de04bb489d6:~/.local/share/code-server$ 
```

**Comment by jake-bladt** [comment]
Seeing the same issue. Either the one-line docker launch is wrong or it requires some better explanation.

**Comment by simeneriks1** [comment]
I don't think it is something wrong with the command itself, but rather the setup of the Dockerfile or container. It seems that the container volumes are created during the container creation, while the extra directories are created on run-time. When this happens you have mismatch between the `.local/share/code-server` (owned by root) and the container user `coder` trying to create folders - which then get "permission denied".

May I know which OS/System you are running docker on? 

I also tried running `chown` and `chmod` on the folders runtime with no luck solving the issue.

**Comment by InsOpDe** [comment]
Did you found a version that works? I get the same error for nearly all versions from latest to `1.939`

**Comment by simeneriks1** [comment]
I found a workaround by modifying the Dockerfile, check https://github.com/cdr/code-server/pull/1191
