### ISSUE TITLE
Unable to start the C/C++ language server

### ISSUE THREAD

**Issue by ariesdevil** [cdr/code-server#1190]
- `code-server` version: 2.1692-vsc1.39.2
- OS Version: Ubuntu 18.04 LTS
- Extension: C/C++ Extension

## Description

Unable to start the C/C++ language server. IntelliSense features will be disabled. Error: Missing binary at /home/ariesdevil/.local/share/code-server/extensions/ms-vscode.cpptools-0.26.2-insiders/bin/Microsoft.VSCode.CPP.Extension.linux

## Steps to Reproduce

1. open a c++ project
1. then codeserver run CMake automatically and throws this error.

**Comment by ariesdevil** [comment]
I just found `Microsoft.VSCode.CPP.Extension.darwin` in the `.local/share/code-server/extensions/ms-vscode.cpptools-0.26.2-insiders/bin/` directory, but it seems need linux version.

My code-server setup is typing `sshcode xxxx@ubuntu18` from MacOS.

**Comment by Lochlanna** [comment]
I’m seeing the same issue with rust too

**Comment by thkrishn** [comment]
I have the same Issue - I connect from a Win 10 machine to a Ubuntu 16.04
So I fixed this by doing an `Install from VSIX` but since my code is residing on a linux machine I had to install `cpptools-linux.vsix`

**Comment by sr229** [comment]
@kylecarbs @code-asher looks like a broken extension issue here.

**Comment by nhooyr** [comment]
#1299

**Comment by SmartElec** [comment]
After two days of testing on different machines, I finally found out that the problem was that the remote Linux machine was not connected to the Internet

**Comment by maminio** [comment]
So I had the same problem on a newly booted Ubuntu server.
I was getting `Error: Unable to read process.env.HOME`.
Apparently it was caused by my NodeJS version. It requires 10 or above and I had 8.0.

**Comment by 940842546** [comment]
> So I had the same problem on a newly booted Ubuntu server.
> I was getting `Error: Unable to read process.env.HOME`.
> Apparently it was caused by my NodeJS version. It requires 10 or above and I had 8.0.
same error on NodeJS 10
how to resolve it
centos 7

**Comment by code-asher** [comment]
@940842546 code-server currently requires Node 12.

**Comment by 940842546** [comment]
> @940842546 code-server currently requires Node 12, although I don't know whether upgrading will resolve that particular error in your case.

node 12 with the same error

**Comment by code-asher** [comment]
In that case I'm not sure. Could you open a new issue and fill in all
the details?
