### ISSUE TITLE
Cursor can't access notebook input line. (Chrome)

### ISSUE THREAD

**Issue by NegatioN** [cdr/code-server#1192]
- `code-server` version: 2.1692-vsc1.39.2
- OS Version: Debian Buster
- Launch-options: `JUPYTER_CONFIG_DIR=myconfig /code-server/code-server --allow-http --auth none --user-data-dir mydir --disable-telemetry /startdir &`

## Description
On Chrome, I can't seem to make the cursor actually enter the "command line" of the python interactive window. I tried with all chrome-extensions disabled, it works on firefox, and it works if you exit the browser-window context first by clicking in the url-bar for example.

Running on ms-python version: 2019-10-44104

I see a lot of these pop up in the log, but I'm guessing it's not connected? https://github.com/microsoft/vscode-python/issues/8001

I put this as a "Bug", not "Extension Bug" since I don't see how this can be broken in vscode core.

## Steps to Reproduce
Adding a short video with debug log of how to repro as well: https://youtu.be/znb7LI8JtPQ

1. Click anywhere in vscode
2. Try clicking in python interactive window "text-box".
3. Cursor appears in the window for a millisecond, then disappears right away.

**Comment by NegatioN** [comment]
No longer using code-server so I'm not able to assist with further debugging.

**Comment by karas111** [comment]
Can we reopen the issue? I'm experiencing exactly the same issue. It seems like the interactive window lose focus immediately after clicking.

Worth to notice, it happens only if there is a code editor in the left panel. When I've opened _Help: Welcome_ view or _Settings_, the issue is gone.

**Comment by nhooyr** [comment]
Confirmed this works fine for me. Installed python + python extension and tested a file with the interactive window open. If this is still a problem, please feel free to reopen.

**Comment by NegatioN** [comment]
@nhooyr It doesn't happen 100% of the time sadly, something has to trigger this state first, then it happens 100% of the time after that.

However, I have noticed this bug in native VScode as well, so it's a bug in the Python extension itself.
