### ISSUE TITLE
Set up user accounts instead of coder

### ISSUE THREAD

**Issue by Nosferican** [cdr/code-server#1193]
## Description

We would like to specify a username to be used rather than the default `coder`. Is that something possible, and how?

## Related Issues

This would also be a nice feature for implementing some of the auth methods.

**Comment by oonqt** [comment]
For now, no. If you're looking for other authentication options, you should look at integrating them into your reverse proxy. If you want just a basic auth w/ user & pass (assuming you're using nginx, not sure about apache), you can look into [this guide](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/)
If you search google, you'll find that you can also implement other auth methods like Google OAuth, Github OAuth, etc. into Nginx

**Comment by Nosferican** [comment]
We'll experiment with [NetBadge](https://virginia.service-now.com/its?id=itsweb_kb_article&sys_id=1031e5ccdb7f0700f032f1f51d961988) and possibly contribute docs. I imagine the working directory is also hardcoded as well rather than as an env variable, no?

**Comment by oonqt** [comment]
If by working directory you mean the default directory that code-server will open to, you can set that using the --data-dir argument

**Comment by sr229** [comment]
`coder` is the Unix user for our Docker container, if you wish to link your instances to a different user, I suggest creating another container with a different user, or use our binary and run it bare.
