### ISSUE TITLE
What do do when - Cannot find module 'X'

### ISSUE THREAD

**Issue by bgold0** [cdr/code-server#1195]
- `code-server` version: 2.1692-vsc1.39.2
- OS Version: Ubuntu 8.04.3 (LTS) x64
- Extension: https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager

## Description
When installing this extension, I get the following error: 
> Activating extension 'alefragnani.project-manager' failed: Cannot find module 'walker'.

Is there anything I can do to fix this?

## Steps to Reproduce

1. Install extension
2. Reload and wait for error in bottom right hand corner

**Comment by sr229** [comment]
Our fixes for this is usually going to the extension folder and running `yarn` or `npm install`. I apologize on behalf of the team for this inconvinience but we promise by the next major version, this will be sorted out.

**Comment by bgold0** [comment]
It's totally fine @sr229. Extremely grateful for the fast response and your team for even building this project. I went ahead and did an `npm install` in the extensions folder but still ended up with the error for some reason :(

**Comment by omfgnuts** [comment]
Try installing the extension from vsix package, worked for me!

**Comment by nhooyr** [comment]
See #1299
