### ISSUE TITLE
Activating extension 'donjayamanne.jupyter' failed: Cannot read property 'indexOf' of undefined.

### ISSUE THREAD

**Issue by sogand145** [cdr/code-server#1196]
## Description
Hi,
I installed the extension donjayamanne.jupyter manually in vscode on remote server, but this it is not activated and appears this error :
Activating extension 'donjayamanne.jupyter' failed: Cannot read property 'indexOf' of undefined.
Thank you a lot for your help

**Comment by nhooyr** [comment]
It's deprecated.

**Comment by nhooyr** [comment]
(the extension)
