### ISSUE TITLE
Keyboard shortcut that conflicts with chrome cannot work in fullscreen mode.

### ISSUE THREAD

**Issue by LeuisKen** [cdr/code-server#1198]
- `code-server` version: code-server2.1692-vsc1.39.2-darwin-x86_64
- OS Version: 10.15.1

## Description

Enter chrome fullscreen mode, and with `View -> Always Show Toolbar in Full screen` switch `off`, the keyboard shortcut like `command + w` of code-server@1 could work like in vscode.

![image](https://user-images.githubusercontent.com/7701575/69541310-c5375a80-0fc3-11ea-8a9d-849c6cb8fb29.png)

But when we going to code-server@2, this keyboard shortcuts could not work.

## Steps to Reproduce

1. Enter IDE, open Untitled File.
1. Press: `Command + w`

## Expected

Untitled File close.

## What happened

The whole Web IDE close.

## Is this work before?

This works with code-server 1.

**Comment by nhooyr** [comment]
This isn't an issue with code-server afaik, just how browsers handle CMD+W, we can't override it.

Use an app window with `sshcode` if you need this.
