### ISSUE TITLE
Creating new folder from file 'Save As' prompt

### ISSUE THREAD

**Issue by ppkwiatkowski** [cdr/code-server#1200]
It would be useful to be able to create new folder from 'Save As' prompt.

For example: When i open new file and hit Ctrl-S it allows me to save the file in existing file tree, I would like to be able to type "examplefolder/file" at the end of path, so it would create "examplefolder" automaticaly and save the file there. Existing vscode GUI is a little bit confusing for me, as I am never sure where exactly the new folder will appear.

**Comment by sr229** [comment]
This is a upstream issue which we won't be fixing ourselves. Please go to Microsoft/vscode for this as this is also a pervalent issue in VSC Web.
