### ISSUE TITLE
Why does the agent keep reconnecting to the server when one extension is activated? 

### ISSUE THREAD

**Issue by renerchen** [cdr/code-server#1201]
When I activate  my private extension,  the extension fails to run. The agent begins to reconnect the server again and again?  Why and how to solve?  The logs is following:

log.ts:172 TRACE [remote-connection][Management   ][0d40b…][initial][myhost:8080] 1/6. invoking socketFactory.connect().
log.ts:172 TRACE [remote-connection][Management   ][0d40b…][initial][myhost:8080] 2/6. socketFactory.connect() was successful.
log.ts:172 TRACE [remote-connection][Management   ][0d40b…][initial][myhost:8080] 3/6. sending AuthRequest control message.
log.ts:172 TRACE [remote-connection][Management   ][0d40b…][initial][myhost:8080] 4/6. received SignRequest control message.
log.ts:172 TRACE [remote-connection][Management   ][0d40b…][initial][myhost:8080] 5/6. sending ConnectionTypeRequest control message.
log.ts:172 TRACE [remote-connection][Management   ][0d40b…][initial][myhost:8080] 6/6. handshake finished, connection is up and running after 231 ms!
log.ts:172 TRACE lifecycle: phase changed (value: 2)
log.ts:172 TRACE load() - enter _URI
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][initial][myhost:8080] 1/6. invoking socketFactory.connect().
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][initial][myhost:8080] 2/6. socketFactory.connect() was successful.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][initial][myhost:8080] 3/6. sending AuthRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][initial][myhost:8080] 4/6. received SignRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][initial][myhost:8080] 5/6. sending ConnectionTypeRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][initial][myhost:8080] 6/6. handshake finished, connection is up and running after 259 ms!
log.ts:172 TRACE load() - resolved content _URI
log.ts:172 TRACE load() - created text editor model _URI
log.ts:172 TRACE lifecycle: phase changed (value: 3)
log.ts:172 TRACE RequestService#request https://v1.extapi.coder.com/extensionquery
log.ts:172 TRACE No grammar found for scope source.asm
log.ts:172 TRACE No grammar found for scope source.x86
log.ts:172 TRACE No grammar found for scope source.x86_64
log.ts:172 TRACE No grammar found for scope source.arm
:8080/static-/out/vs/base/common/console.js:103 [Extension Host] Extension "nextcode-Reference" start to active!
log.ts:172 TRACE SearchService#search {"_reason":"startFileSearch","folderQueries":[{"folder":{"$mid":1,"external":"vscode-remote://myhost:8080/root/HERT","path":"/root/HERT","scheme":"vscode-remote","authority":"myhost:8080"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/.code-server-partial-upload-*":true},"fileEncoding":"utf8","disregardIgnoreFiles":true,"disregardGlobalIgnoreFiles":true,"ignoreSymlinks":false}],"usingSearchPaths":false,"includePattern":{"**/*.*":true},"type":1}
log.ts:172 TRACE CommandService#executeCommand setContext
v1.extapi.coder.com/extensionquery:1 Failed to load resource: the server responded with a status of 422 ()
log.ts:172 TRACE lifecycle: phase changed (value: 4)
log.ts:172 TRACE SearchService#search: 2898ms
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] waiting for 5 seconds before reconnecting...
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] resolving connection...
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] connecting to myhost:8080...
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 1/6. invoking socketFactory.connect().
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 2/6. socketFactory.connect() was successful.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 3/6. sending AuthRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 4/6. received SignRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 5/6. sending ConnectionTypeRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 6/6. handshake finished, connection is up and running after 227 ms!
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] reconnected!
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] waiting for 5 seconds before reconnecting...
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] resolving connection...
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] connecting to myhost:8080...
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 1/6. invoking socketFactory.connect().
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 2/6. socketFactory.connect() was successful.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 3/6. sending AuthRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 4/6. received SignRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 5/6. sending ConnectionTypeRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 6/6. handshake finished, connection is up and running after 224 ms!
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] reconnected!
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] waiting for 5 seconds before reconnecting...
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] resolving connection...
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] connecting to myhost:8080...
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 1/6. invoking socketFactory.connect().
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 2/6. socketFactory.connect() was successful.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 3/6. sending AuthRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 4/6. received SignRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 5/6. sending ConnectionTypeRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 6/6. handshake finished, connection is up and running after 227 ms!
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] reconnected!
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] waiting for 5 seconds before reconnecting...
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] resolving connection...
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] connecting to myhost:8080...
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 1/6. invoking socketFactory.connect().
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 2/6. socketFactory.connect() was successful.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 3/6. sending AuthRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 4/6. received SignRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 5/6. sending ConnectionTypeRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 6/6. handshake finished, connection is up and running after 229 ms!
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] reconnected!
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] waiting for 5 seconds before reconnecting...
log.ts:172 TRACE load() - enter _URI {scheme: "vscode-remote", authority: "myhost:8080", path: "/root/HERT/hert_bbu/5891/Source/sdk/comm/dfx/cdk_statistics.c", query: "", fragment: "", …}
log.ts:172 TRACE load() - enter _URI {scheme: "vscode-remote", authority: "myhost:8080", path: "/root/HERT/hert_bbu/5891/Source/sdk/comm/dfx/cdk_statistics.c", query: "", fragment: "", …}
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] resolving connection...
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] connecting to myhost:8080...
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 1/6. invoking socketFactory.connect().
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 2/6. socketFactory.connect() was successful.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 3/6. sending AuthRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 4/6. received SignRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 5/6. sending ConnectionTypeRequest control message.
log.ts:172 TRACE [remote-connection][ExtensionHost][3fc98…][reconnect][myhost:8080] 6/6. handshake finished, connection is up and running after 229 ms!
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] reconnected!
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:184  INFO [remote-connection][ExtensionHost][3fc98…][reconnect] waiting for 5 seconds before reconnecting...

**Comment by renerchen** [comment]
@sr229 @code-asher hi, do you know why?

**Comment by code-asher** [comment]
I'm not sure; to confirm this only happens with that extension enabled? If you disable it does the problem go away?

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
