### ISSUE TITLE
Terminal.Integrated:Font Family  Supported?

### ISSUE THREAD

**Issue by mingfure** [cdr/code-server#1203]
- `code-server` version: code-server2.1692 
- OS Version: Ubuntu 16.04 LTS 

## Description

Cannot change the font in Terminal. My shell is zsh.
what I want as blow:
![image](https://user-images.githubusercontent.com/14871429/69895747-84976280-1370-11ea-813e-641ce4e00e63.png)

- If I do nothing, set font to None as Default
![image](https://user-images.githubusercontent.com/14871429/69895671-a2b09300-136f-11ea-8001-57ec83a18944.png)
![image](https://user-images.githubusercontent.com/14871429/69895668-96c4d100-136f-11ea-8d20-e7de93e53a48.png)

- If I set font to `Meslo LG M for Powerline`, it's still useless.
![image](https://user-images.githubusercontent.com/14871429/69895640-36ce2a80-136f-11ea-9d7f-7aefefc06fc2.png)
![image](https://user-images.githubusercontent.com/14871429/69895636-228a2d80-136f-11ea-9458-37b9e7ffb3c9.png)

## Steps to Reproduce

1. install zsh
1. install  [Powerline fonts](https://github.com/powerline/fonts#powerline-fonts)
1. click vscode setting and set terminal font as `Meslo LG M for Powerline`
1. reload shell

**Comment by elgandoz** [comment]
Given that your font name contains spaces, you have to put it between quotes `('Meslo LG M for Powerline').` This is not a bug and on top the exact same behavior happens to normal VS Code (and many other editors)

**Comment by mingfure** [comment]
Well, I follow your advice and set font name to `'Meslo LG M for Powerline` or `"Meslo LG M for Powerline"`. But unfortunately it doesn't work. I can get the right font from Xshell, so the font should be install correctly.  This confused me a lot.


![image](https://user-images.githubusercontent.com/14871429/69953133-95440600-1533-11ea-9f00-e335f8365df3.png)

![image](https://user-images.githubusercontent.com/14871429/69953263-d76d4780-1533-11ea-9ffd-fdb59c284cc4.png)

from Xshell
![image](https://user-images.githubusercontent.com/14871429/69953607-90cc1d00-1534-11ea-9044-90e6361735db.png)

**Comment by InsOpDe** [comment]
@mingfure did you find a solution for that?

**Comment by mingfure** [comment]
@InsOpDe unfortunately, not.

**Comment by elgandoz** [comment]
I had in the past a similar bug with Atom, where the font was not working because it's name (seen by electron) was not exactly the same of what appears in the system. Somehow I found the alternative name and it worked. Likely could be a similar issue. 
Have you tried same font but from a different source? https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Meslo/L

**Comment by InsOpDe** [comment]
Solved it like this:
![image](https://user-images.githubusercontent.com/10099328/72708664-8527ca80-3b63-11ea-8d42-6deff66e2c86.png)

**Comment by yliu224** [comment]
> Solved it like this:
> ![image](https://user-images.githubusercontent.com/10099328/72708664-8527ca80-3b63-11ea-8d42-6deff66e2c86.png)
> `'Ubuntu Mono', 'PowerlineSymbols'`

Doesn't work for me : (

**Comment by JettScythe** [comment]
What's the status on this? Any ETA? I just spent 4 hours trying to figure SOMETHING out and the best I got is with a fork of https://github.com/tuanpham-dev/code-server-font-patch and even then, no icons :( 
![image](https://user-images.githubusercontent.com/37233887/157822433-26287faa-0e86-4b87-bff7-f3bb218a8f27.png)

**Comment by mingfure** [comment]
have you try this `'Ubuntu Mono', 'PowerlineSymbols'`

**Comment by mingfure** [comment]
Two years is so fast

**Comment by JettScythe** [comment]
![image](https://user-images.githubusercontent.com/37233887/157896416-ab79dd8d-0855-4c49-b351-9ca3ab167ec2.png)

Not much improvement unfortunately

**Comment by jsjoeio** [comment]
@JettScythe feel free to try @mingfure's solution, otherwise you can open a new issue.

**Comment by JettScythe** [comment]
@jsjoeio Tried @mingfure's solution, @tuanpham-dev's solution as well as a custom pacman hook https://gist.github.com/JettScythe/6d98633d5f98730661127bfe3dbc68a4 without luck. Rather than making a new issue, I'll continue here: https://github.com/coder/code-server/issues/1374

**Comment by JWleo** [comment]
the same problem just like two years ago.
o...ooop!
![image](https://user-images.githubusercontent.com/32316654/169475618-b85f476b-c396-4628-99b2-59a62828c0fd.png)

**Comment by ThatAnonyG** [comment]
Its really insane how slow this project is to implement or solve bugs. I have been trying to complete this setup for 2 days and every issue I came across is still unresolved even though they are so trivial.

**Comment by jsjoeio** [comment]
Sorry to hear you've felt that way - we're doing the best that we can. @ThatAnonyG PRs welcome if you'd like to help us!

**Comment by ThatAnonyG** [comment]
I have no reason to not contribute. But with my office work it becomes really hard to split my time and effort.

**Comment by jsjoeio** [comment]
No worries at all! I completely understand. Well, if you do find the time, we would welcome your support with open arms!
