### ISSUE TITLE
No Outline for Ruby files

### ISSUE THREAD

**Issue by KevinBerthier** [cdr/code-server#1204]
- `code-server` version: 2.1692-vsc1.39.2
- OS Version: ChomeOS 79 Crostini

## Description

For `.rb` files : 

![image](https://user-images.githubusercontent.com/25929311/69907363-43389e80-13d4-11ea-8dc8-a617695a7683.png)

## Steps to Reproduce

1. Install ruby extension
2. Open a `.rb` file

**Comment by sr229** [comment]
Did you try it on VSO and VSCode to see if they're similar? AFAIK by default VSCode doesn't know how to make up an outline of the code unless an extension is provided to allow it to represent the AST in a outline.

**Comment by KevinBerthier** [comment]
@sr229 Yes it's working well with others. It's seems that Ruby extension has a dependency on https://marketplace.visualstudio.com/items?itemName=wingrunr21.vscode-ruby wich is not available on code-server markerplace

**Comment by KevinBerthier** [comment]
No success with solargraph extension too. It seems that language server is not starting

**Comment by nhooyr** [comment]
See #1299
