### ISSUE TITLE
Activating extension 'ms-vscode.cpptools' failed: Cannot find module 'vscode-nls'.

### ISSUE THREAD

**Issue by shahidul56** [cdr/code-server#1206]
- `code-server` version: code-server2.1692-vsc1.39.2-linux-x86_64
- OS Version: Ubuntu 18.04
- Extension: cpp 

## Description

Activating extension 'ms-vscode.cpptools' failed: Cannot find module 'vscode-nls'.

![fsdf](https://user-images.githubusercontent.com/11449967/70069590-35755a00-161c-11ea-9bb4-0fb9f8102ba9.PNG)

## Steps to Reproduce

1. opening codeserver

**Comment by sr229** [comment]
Try going to the extension's directory and run a `yarn` or `npm install`.

**Comment by ZKL-VOILET** [comment]
I have the same problem. How can I solve it?

**Comment by code-asher** [comment]
Hmm yeah the extension seems to be broken again. I created a new issue for it: https://github.com/cdr/code-server/issues/2263
