### ISSUE TITLE
Arduino Board selection

### ISSUE THREAD

**Issue by raystream** [cdr/code-server#1207]
- `code-server` version: 2.1692-vsc1.39.2-linux-x86_64
- OS Version: debian 10

## Description

vscode is running behind a nginx server on an other vm.
i have installed the arduino extension to code-server
when i try to open the board selection menu, the window opens.
but it tries to get the content from 
`http://localhost:45001/boardConfig?theme=vscode-dark&backgroundcolor=%231e1e1e&color=%23d4d4d4`
 and not from the url the main page is loaded from.

## Steps to Reproduce

1. install code-server with arduino extension
2. use nginx server on an other server
3. open board selection menu

**Comment by sr229** [comment]
unfortunately not all extensions works as intended, this extension seems to be only looking for your Arduino in a localhost connection.

**Comment by nhooyr** [comment]
Unfortunately we can't really do anything about this. The extension has a bug.
