### ISSUE TITLE
Cannot install the Chinese language pack in the latest VSCode 1.41 version

### ISSUE THREAD

**Issue by FanyangMengDev** [cdr/code-server#1209]
- `code-server` version:  2.1692-vsc1.39.2
- OS Version:  Ubuntu 18.04 LTS
- Extension:  Chinese SImplified Language pack

## Description
Hi there,
I just run code-server by using the prebuild binary file, but I found that I canot install the Chinese language pack. Firstly I thought maybe that is because the network problem, but when I try to install some other extensions, I found that all of them can be installed quickly.

Then, I go to the code--server issues page and search that if anyone has the same problems as mine. I found that there are a few issues which  looks like the same as my issue. They cannot install Chinese Language pack too.

So I think this is not just happen on me. Would you please have a check that if you can install the Chinese Simplified Language Pack. If this is a bug, please fix it as soon as possible. It will be so much appreciated!

## Steps to Reproduce
1. download the binary from release page.
2. run it.
3. Try to install the Chinese Language pack.

**Comment by FanyangMengDev** [comment]
No one answer me?

**Comment by code-asher** [comment]
Currently I'm not able to install it because the version of VS Code is out of date. Is that the same error you're experiencing?

**Comment by FanyangMengDev** [comment]
@sr229

**Comment by FanyangMengDev** [comment]
@kylecarbs

**Comment by sr229** [comment]
Please answer the question @code-asher asked before we can help you further.

**Comment by FanyangMengDev** [comment]
Ah, sorry I see. I just install the latest docker version. I uninstall the binary verisons before. And the same hapenes on the docker version.

What's more, the latest docker verison ask me to reload again and again. So I reverse to the last version just a few minutes ago. Then the same happenes too,
You guy can have a try.

**Comment by FanyangMengDev** [comment]
![cannot install Chinese](https://user-images.githubusercontent.com/53750381/70997024-0c21f700-210f-11ea-8e75-15dc020ca7ca.PNG)
Please have a look on this. You can have a try. @sr229

**Comment by FanyangMengDev** [comment]
@code-asher Sorry that I thought you were just a user who has the same problems as mine and I did not reply to you. My appologize. I sent the screenshot on the latest docker verison and last docker version. Both of them cannot install Chinese language pack and do not have Remote Development extensions. These two are the things which I really need,

**Comment by FanyangMengDev** [comment]
@sr229

**Comment by fxbjhc** [comment]
这主要是目前的版本还是1.39而中文插件已经到1.41了，我前段时间找了个1.39的中文插件安装完后中文也能正常显示。不过现在我看1.41的commit已经提交想必release版很快就能正常使用了。

**Comment by FanyangMengDev** [comment]
@fxbjhc 嗯嗯多谢提醒~

**Comment by FanyangMengDev** [comment]
@fxbjhc 您好，我这边更新了最新版的docker 发现1.41版本已经更新，但是当安装完中文语音包之后出现了这种情况，提示我
`Cannot read property 'path' of undefined`

不知道您是否遇到了这种情况呢？

**Comment by FanyangMengDev** [comment]
@code-asher @sr229 

Hi there,

I just noted that you have already released the version 1.41 VSCode. And I install it via docker.

But after I install it and wanna configure its language, what made me confuse is that code server keep alerting me `Cannot read property 'path' of undefined`. This happens when I try to active the Chinese Simplified Language Pack.

Really weird, Could you please do some check?

And what' more, when I try to search some extensions on the code-server, the result displays is not like my computer. For an example, I tried to install Monokai Pro Theme on the code-server, but this theme does not appear in the search result even though it does on my computer.

If you could fix these it will be so much appreciated. Thank you in advance.

**Comment by sr229** [comment]
The Chinese extension pack might've been misconfigured during build time, try to rectify it by going to the extension's folder and running `npm install` or `yarn`. @fand

**Comment by FanyangMengDev** [comment]
@sr229 Thank you so much for your fast response. Although I have not  ever added extensions to VSCode through `npm install` or `yarn` but I will have a try.

**Comment by fxbjhc** [comment]
讲道理docker版应该还是1.39我这里点更新说没有更新的版本。至于你这个问题你先试试编个文本能不能保存。至于docker部署其实挺难整的主要是权限问题，我查issue看他们还没讨论出个结果，我都是给root权限部署的，他们好像都不建议用root，但是不用root我连文件都保存不了。我初步怀疑是你docker的root权限问题，导致储存不了文件。

**Comment by sr229** [comment]
@FanyangMengDev Visual Studio Code extensions are done with Node.js workflow so running `yarn` or `npm install` should get the missing deps.

We're actively looking for a solution for misconfigured extensions at this moment.

**Comment by FanyangMengDev** [comment]
@fxbjhc 对，他们最新版的1.41没有采用V2 或者 latest 标签，纯粹用的版本标签，你可以去dockerhub看一下，这个版本完全是独立出来的，不知道他们为什么这么设计。说到权限问题，全部文件夹其实都是root 755的，这个我检查了很多遍

**Comment by FanyangMengDev** [comment]
@sr229 Thank you so much for your hard working and fast response! : )

Hoping this issue will be solved soon : )

**Comment by nhooyr** [comment]
See #1299
