### ISSUE TITLE
Source Control Panel is blank

### ISSUE THREAD

**Issue by wjziv** [cdr/code-server#1210]
- `code-server` version: 2.1692-vsc1.39.2
- OS Version: ChromeOS 78.0.3904.106 (Official Build) (64-bit) (Pixelbook)
- Locally running build: code-server2.1692-vsc1.39.2-linux-x86_64.tar.gz

## Description

Seeing similar behavior described on VSCode v1.39.0 here:
https://github.com/microsoft/vscode/issues/82203

It looks like there isn't a solution present until v1.40.2 as mentioned here:
https://github.com/microsoft/vscode/issues/83440

Does this project lag behind VSCode entirely step-by-step, or could this fix be applied in an upcoming build?

I have no active attachments/extensions in the following screenshot:

<img src="https://user-images.githubusercontent.com/29553646/70359074-f37d2b80-1848-11ea-927c-d41dbdf314e7.png" height=300>

**Comment by sr229** [comment]
CC @code-asher we might need to sync with the new tree for the fixes.

**Comment by jrdnr** [comment]
I'm also seeing this issue, is this a code server issue or a vscode issue or something else?  this was the only issue thread I could find that hadn't been closed.

**Comment by nhooyr** [comment]
@jrdnr please update to the latest version.

If this is still a problem, please feel free to reopen.
