### ISSUE TITLE
Missing crossorigin="use-credentials" to manifest.json link for basic auth

### ISSUE THREAD

**Issue by jmbarbier** [cdr/code-server#1212]
This issue is a duplicate from https://github.com/microsoft/vscode/issues/86541 as i don't really know where this can be solved.

- VSCode Version: latest from codercom/code-server:v2
- OS Version: browser (Chrome)

Serving codercom/code-server:v2 VSCode behind a reverse proxy with basic auth managed by proxy works well; everything is OK *but* manifest.json gets a 401 Unauthorized on Chrome

It appears that at least for Chrome, we need to add <link rel="manifest" href="manifest.json" **crossorigin="use-credentials"**> in order for Chome to pass auth headers for manifest retrieval.

**Comment by sr229** [comment]
@code-asher this might be of your interest.
