### ISSUE TITLE
chrome-server

### ISSUE THREAD

**Issue by Vittitow** [cdr/code-server#1213]
Sorry for opening this question but I'm getting pretty desperate as my hours of searching have come up empty... I have a use case which involves connecting to a remotely isolated Chrome instance through a client's browser exactly how code-server works. So my question ultimately is can this project be adapted to simply run Chrome as it runs VS Code? And/or are you or anyone aware of a project that already does this?

Thanks!

**Comment by 4oo4** [comment]
Have you seen this?

https://github.com/cloud-computer/cloud-computer

It I think will do what you're asking, basically it installs Chrome (or other desktop apps) in a docker container, that you then connect to via VNC. So if you didn't want to run the whole thing then this might be all you need:

https://github.com/cloud-computer/cloud-computer/blob/master/infrastructure/containers/chrome/Dockerfile

**Comment by Vittitow** [comment]
I looked into that briefly but the sticking point for me on that project is the image is over a gig so there is likely a lot of unnecessary bloat I wouldn't be using. Thank you for your suggestion, I'll keep digging!

**Comment by sr229** [comment]
We have sshcode which you can auto-launch a directory then it opens a chrome instance to connect there.

So unfortunately, this is something that is out of scope for code-server.
