### ISSUE TITLE
[BUG] EACCES: permission denied, unlink '/usr/local/bin/code-server'

### ISSUE THREAD

**Issue by soakes** [cdr/code-server#1215]
- `code-server` version: latest (dockerhub image) 
```
codercom / code-server : v2
DIGEST:sha256:9b8fbbecd32ce4ffc477a7dba59df5a1d589ec4ce8207bf97eae2431230776ea
```
- OS Version: linux/amd64

## Description

An `eacces` error happens when you try and upgrade code from within UI.  Also can show up when you have selected updates disabled. 

`EACCES: permission denied, unlink '/usr/local/bin/code-server'`

<img width="494" alt="eaccess_error" src="https://user-images.githubusercontent.com/813389/70438659-3415b880-1a86-11ea-9620-9bb7e87c4de2.png">

## Steps to Reproduce

1. `docker run -p 8080:8080 -v "${PWD}/.local/share/code-server:/home/coder/.local/share/code-server" -v "$PWD:/home/coder/project" -d codercom/code-server:v2`
1. in browser type: http://localhost:8080
1. bottom left of screen you will see a (1) in notifications, click it and will try and upgrade
1. bottom right then you get a notification and clicking on it gives the above error.

This is caused because code is running a coder user (which is how it should be done) however the file is located in /usr/local/bin and owned by root.  Coder does not have access to unlink (remove/replace) this thus the error happens.

```
coder@coder-566b985854-cmfm5:~$ ls -la /usr/local/bin/
total 178224
drwxr-xr-x 1 root root      4096 Dec  5 19:52 .
drwxr-xr-x 1 root root      4096 Oct 29 21:25 ..
-rwxr-xr-x 1 root root 182491143 Dec  5 19:49 code-server
```

A good solution IMHO would be to place the `code-server` binary in `/home/coder/bin` for example and `chown` it to the `coder` user and then adjust the `ENTRYPOINT` to the new path.

**Comment by cjazinski** [comment]
Could you elaborate a little more for those of us not to familiar with docker. I've tried creating a folder in /usr/local/bin and chown to the user running docker but still same issue.

**Comment by soakes** [comment]
Hi @cjazinski sorry I didn't see this message till today due to all my GH notifications goes to my works address and I've not opened up works laptop till today.

After work, assuming got some time today ile do some test code for you to test.

**Comment by soakes** [comment]
HI @cjazinski 

Can you please give me the build tags/cmd your using as I'm having problems building what you have here (unusual) and sadly I don't know `yawn` too much to debug quickly.

Have tried a few variants of below which should have worked from what I can see as your `codeServerVersion` defaults in the dockerfile as `docker`.  You can see it entered values correctly.

Once this is building with what you currently have, it shouldn't be rocket science to make this change.
 
```
$ docker build  --build-arg vscodeVersion=1.41.0  --tag test/coder .
Sending build context to Docker daemon  10.46MB
Step 1/22 : FROM node:10.16.0
 ---> 4ae749096a47
Step 2/22 : ARG codeServerVersion=docker
 ---> Using cache
 ---> 54f8ce87bdd4
Step 3/22 : ARG vscodeVersion
 ---> Using cache
 ---> 43d68a7090b8
Step 4/22 : ARG githubToken
 ---> Using cache
 ---> 8861219d2dca
Step 5/22 : RUN apt-get update && apt-get install -y 	libxkbfile-dev 	libsecret-1-dev
 ---> Using cache
 ---> c6094bc28ee6
Step 6/22 : RUN npm install -g yarn@1.13
 ---> Using cache
 ---> 4c194af53b40
Step 7/22 : WORKDIR /src
 ---> Using cache
 ---> ed8a9b27cfd7
Step 8/22 : COPY . .
 ---> Using cache
 ---> d78f17e2db05
Step 9/22 : RUN yarn 	&& MINIFY=true GITHUB_TOKEN="${githubToken}" yarn build "${vscodeVersion}" "${codeServerVersion}" 	&& yarn binary "${vscodeVersion}" "${codeServerVersion}" 	&& mv "/src/binaries/code-server${codeServerVersion}-vsc${vscodeVersion}-linux-x86_64" /src/binaries/code-server 	&& rm -r /src/build 	&& rm -r /src/source
 ---> Running in 33e09107d317
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @coder/logger@1.1.8" has unmet peer dependency "@google-cloud/logging@^4.5.2".
[4/4] Building fresh packages...
Done in 35.65s.
yarn run v1.13.0
$ yarn && yarn runner build 1.41.0 docker
[1/4] Resolving packages...
success Already up-to-date.
$ cd ./scripts && node --max-old-space-size=32384 -r ts-node/register ./build.ts build 1.41.0 docker
[build] Not running inside VS Code
[build] rootPath is "/src"
[build] outPath is "/src"
[build] arch is "x86_64"
[build] target is "linux"
[build] vscodeVersion is "1.41.0"
[build] codeServerVersion is "docker"
[build] Installing code-server dependencies...took 610ms
[build] Cloning VS Code...took 6005ms
[build] Installing VS Code dependencies...took 264375ms
[build] Building default extensions...The command '/bin/sh -c yarn 	&& MINIFY=true GITHUB_TOKEN="${githubToken}" yarn build "${vscodeVersion}" "${codeServerVersion}" 	&& yarn binary "${vscodeVersion}" "${codeServerVersion}" 	&& mv "/src/binaries/code-server${codeServerVersion}-vsc${vscodeVersion}-linux-x86_64" /src/binaries/code-server 	&& rm -r /src/build 	&& rm -r /src/source' returned a non-zero code: 137```

**Comment by LindenLiu** [comment]
This is actually not related to build or docker nor yarn. I met the same problem when trying to update the code-server inside the vscode UI. It gave the same issue. I guess the update script does have problem. The step to reproduce is very clear though.

**Comment by LindenLiu** [comment]
> Could you elaborate a little more for those of us not to familiar with docker. I've tried creating a folder in /usr/local/bin and chown to the user running docker but still same issue.

I tried this way, it doesn't work as well. And I even moved the code-server to another folder and create a link there, but still doesn't work. I guess the update script has some problem?

**Comment by soakes** [comment]
As I couldn't get the docker build to build as tags etc wasn't supplied, I decided to create the same thing but on a VM instead for a few of my friends.

I can confirm doing exactly what I said works:

```
soakes     665     1  0 Jan07 ?        00:00:00 /data/coder/soakes/bin/code-server --base-path /u/soakes --host 0.0.0.0 --port 8081 --user-data-dir /data/coder/soakes/user-data /data/coder/soakes/projects
soakes     688   665  0 Jan07 ?        00:00:42 /data/coder/soakes/bin/code-server --base-path /u/soakes --host 0.0.0.0 --port 8081 --user-data-dir /data/coder/soakes/user-data /data/coder/soakes/projects
```

```
soakes@vscode01:~/bin$ ls -la
total 673612
drwxr-xr-x  2 soakes soakes      4096 Jan 15 15:57 .
drwx------ 18 soakes soakes      4096 Jan 15 15:56 ..
-rwxr-xr-x  1 soakes soakes 182491117 Nov 14 23:31 code-server
-rwxr-xr-x  1 soakes soakes  34625816 Nov 13 07:30 containerd
-rwxr-xr-x  1 soakes soakes   6116160 Nov 13 07:30 containerd-shim
-rwxr-xr-x  1 soakes soakes  18850136 Nov 13 07:30 ctr
-rwxr-xr-x  1 soakes soakes      4080 Nov 25 15:57 dgoss
-rwxr-xr-x  1 soakes soakes  65641786 Nov 13 07:30 docker
-rwxr-xr-x  1 soakes soakes  72090824 Nov 13 07:30 dockerd
-rwxr-xr-x  1 soakes soakes    764144 Nov 13 07:30 docker-init
-rwxr-xr-x  1 soakes soakes   2877369 Nov 13 07:30 docker-proxy
-rwxr-xr-x  1 soakes soakes  10448896 Nov 25 15:57 goss
-rwxr-xr-x  1 soakes soakes  40460288 Dec 24 13:11 helm
-rwxr-xr-x  1 soakes soakes  46681472 Dec  9 19:23 kubectl
-rwxr-xr-x  1 soakes soakes  16609280 Oct  9 23:57 mc
-rwxr-xr-x  1 soakes soakes   8649792 Nov 13 07:30 runc
-rwxr-xr-x  1 soakes soakes      6221 Dec 20 22:13 ssh-find-agent
-rwxr-xr-x  1 soakes soakes  51175008 Dec  2 18:22 terraform
-rwxrwxr-x  1 soakes soakes 132251875 Nov 12 20:42 vault
soakes@vscode01:~/bin$ pwd
/data/coder/soakes/bin
```

![image](https://user-images.githubusercontent.com/813389/72449046-f1937a00-37af-11ea-9202-a8a6819fba76.png)

Each user now can update their own code-server from the UI and there is no longer any errors.

```
[soakes@vscode01(~)> cat /etc/systemd/system/code-server-soakes.service
[Unit]
Description=Visual Studio Code Server (soakes)
After=network.target

[Service]
EnvironmentFile=/data/coder/soakes/.env
ExecStart=/data/coder/soakes/bin/code-server --base-path /u/soakes --host 0.0.0.0 --port 8081 --user-data-dir /data/coder/soakes/user-data /data/coder/soakes/projects
User=soakes
Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target
```

Extra tweak, save admin (me) to restart my mates instances if they want to change their password, they just need to change their password in ~/.env and incron will restart the process.

```
[root@vscode01(~)> incrontab -l
/data/coder/soakes/.env	IN_MODIFY	/usr/bin/systemctl restart code-server-soakes
```

Theres no reason I can see why the same sort of thing wouldn't work in docker.  I don't mind sorting it if someone can share how to build these images as the tags needed are a bit "weird".

**Comment by sr229** [comment]
@soakes they're not weird, you just need to supply the VSCode version (we only support 1.41.x upstream) and your code-server version (which can be whatever), just supply them via `--build-arg`. Nothing fancy.

**Comment by jeffreyworsley** [comment]
i found that if i do --user root it will update, so i guess they only need
to change the owner of /usr/local/bin/codeserver

**Comment by soakes** [comment]
@sr229 Thanks, if you see form initial post, this is exactly what I did.

```
docker build  --build-arg vscodeVersion=1.41.0  --tag test/coder .
```

Can you paste me exactly a working line?

Many thanks.

**Comment by code-asher** [comment]
I recently changed the Dockerfile so you don't need to specify any build
arguments. You can provide `--build-arg tag=mytag` if you want,
otherwise it'll default to `daily`. The correct VS Code version will be
selected for you.

So a simple `docker build .` should work; fingers crossed. I just ran it
on my machine without any issues.

Adding a `chown` to the Dockerfile sounds like a good plan to me.

**Comment by nhooyr** [comment]
Related #1307

**Comment by nhooyr** [comment]
See
