### ISSUE TITLE
SQLTools Extension can’t initiate SQLTools Language Server

### ISSUE THREAD

**Issue by grebeniuk** [cdr/code-server#1216]
- `code-server` version: code-server2.1694-vsc1.39.2-linux-x86_64 
- OS Version: Docker on Win 10 host 

## Description

SQLTools extension can’t initiate SQLTools Language Server. Works fine in desktop version. 

Output from SQLTools Language Server:

> [Info  - 5:14:03 PM] Connection to server got closed. Server will restart.
> Option 'node-ipc' is unknown. Ignoring.
> Option 'clientProcessId' is unknown. Ignoring.
> Option 'node-ipc' is unknown. Ignoring.
> Option 'clientProcessId' is unknown. Ignoring.
> error listen EADDRINUSE: address already in use :::8080

ps -auxww:

> USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
> coder        1  0.0  0.0   4380   780 ?        Ss   16:21   0:00 dumb-init code-server --host 0.0.0.0 --port 8880
> coder        6  0.0  2.5 611100 52928 pts/0    Ssl+ 16:21   0:00 code-server --host 0.0.0.0 --port 8880
> coder       17  0.4  3.6 990280 74956 pts/0    Sl+  16:21   0:51 /usr/local/bin/code-server --host 0.0.0.0 --port 8880
> coder       46  0.0  3.5 1295712 73612 pts/0   Sl+  16:21   0:06 /usr/local/bin/code-server /src/build/code-server2.1694-vsc1.39.2-linux-x86_64-built/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/src/build/code-server2.1694-vsc1.39.2-linux-x86_64-built/out/vs/server/src/node/uriTransformer
> coder       97  0.0  0.1  20296  3708 pts/1    Ss   16:26   0:00 /bin/bash
> coder      276  0.0  3.2 1149052 65860 pts/0   Sl+  16:35   0:06 /usr/local/bin/code-server /src/build/code-server2.1694-vsc1.39.2-linux-x86_64-built/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/src/build/code-server2.1694-vsc1.39.2-linux-x86_64-built/out/vs/server/src/node/uriTransformer
> coder     2170  0.0  3.2 1148560 66128 pts/0   Sl+  17:00   0:05 /usr/local/bin/code-server /src/build/code-server2.1694-vsc1.39.2-linux-x86_64-built/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/src/build/code-server2.1694-vsc1.39.2-linux-x86_64-built/out/vs/server/src/node/uriTransformer
> coder     2504  0.0  2.0 571660 42048 pts/0    Sl+  17:10   0:00 /usr/local/bin/code-server /src/build/code-server2.1694-vsc1.39.2-linux-x86_64-built/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=46
> coder     2513  0.0  2.6 619536 53288 pts/0    Sl+  17:11   0:00 /usr/local/bin/code-server /home/coder/.local/share/code-server/extensions/mtxr.sqltools-0.21.2/languageserver.js --node-ipc --clientProcessId=46
> coder     2524  0.0  2.5 972684 51856 pts/0    Sl+  17:11   0:00 /usr/local/bin/code-server /home/coder/.local/share/code-server/extensions/mtxr.sqltools-0.21.2/languageserver.js --node-ipc --clientProcessId=46
> coder     2541  0.0  3.1 1009800 65168 pts/0   Sl+  17:13   0:04 /usr/local/bin/code-server /src/build/code-server2.1694-vsc1.39.2-linux-x86_64-built/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/src/build/code-server2.1694-vsc1.39.2-linux-x86_64-built/out/vs/server/src/node/uriTransformer
> coder     2677  0.3  4.1 1014904 84888 pts/0   Sl+  19:10   0:00 /usr/local/bin/code-server /src/build/code-server2.1694-vsc1.39.2-linux-x86_64-built/out/bootstrap-fork --type=extensionHost --uriTransformerPath=/src/build/code-server2.1694-vsc1.39.2-linux-x86_64-built/out/vs/server/src/node/uriTransformer
> 

## Steps to Reproduce

1. Run code-server in container
2. Install extension: https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools
3. Try to add connection or do anything with the extension 
4. Check SQLTools Language Server Output

![9CBCB3E4-636A-4D68-B921-3B7743F0AB75](https://user-images.githubusercontent.com/839542/70464946-e4d38600-1a8d-11ea-9363-9b13cea79a8e.jpeg)

**Comment by nhooyr** [comment]
Change the port code-server is using to something other than 8080. It's conflicting with SQLTools.

**Comment by nhooyr** [comment]
Nvm, so it works the first time after my described fix but then errors again. It doesn't realize the server is already running on 8080 for some reason.

**Comment by rgogada** [comment]
I also have the same issue. is there a work around?

**Comment by si458** [comment]
im had a similar issue when first install i get a 8080 port in use,
BUT if you 1,2,3 it seems to fix it?
1. uninstall it
2. setup the prerequities for sqlite (https://vscode-sqltools.mteixeira.dev/driver/sqlite) in settings.json
3. install again, the error goes away

**Comment by nhooyr** [comment]
@si458 Does it work even if you refresh the browser?

Also let's move discussion re this extension into #1140
