### ISSUE TITLE
Add extension: ASCIIDecorator

### ISSUE THREAD

**Issue by roncli** [cdr/code-server#1217]
- `code-server` version: 1.39.2
- OS Version: Azure Container
- Extension: https://marketplace.visualstudio.com/items?itemName=helixquar.asciidecorator

## Description

I'd like for this extension to be added to the code-server marketplace.  I have been unable to successfully install this extension manually on an Azure Container.

**Comment by sr229** [comment]
OS Version is not clear, what exactly version Azure container runs at? I believe its just standard Ubuntu.

**Comment by nhooyr** [comment]
Related #1299
