### ISSUE TITLE
how to start a maven progect? redhat java cannot activate,please help me

### ISSUE THREAD

**Issue by pangedeshijie** [cdr/code-server#1218]
redhat cannot activate ,who can help me solve this problem
## Description

The java.home variable defined in VS code settings points to a missing or inaccessible folder
## Related Issues
can not activate extension 'Java Test Runner' because it depends on extension 'redhat.java',which failed to activate

**Comment by brandtkeller** [comment]
I believe this is related to #1163 and #1136 , where in if you inspect the /home/coder/.local/share/code-server/extensions/redhat.java-* folder you will notice there is no .node_modules folder. 
A comment by code-asher mentions the workaround:
`npm install
./node_modules/.bin/gulp download_server`

Can confirm this activates redhat.java extension after executing.
Note: Bad at linking items, issues and users may not be tagged correctly.

**Comment by pangedeshijie** [comment]
thanks for help! I did this as what you write ,but in  ./node_modules/.bin folder,there is no gulp file,execute the order ,error occurs ，so what should I do next?

**Comment by pangedeshijie** [comment]
thanks for help! I did this as what you write ,but in ./node_modules/.bin folder,there is no gulp file,execute the order ,error occurs ，so what should I do next?

**Comment by pangedeshijie** [comment]
sorry,I have to trouble you again,I want to describe my problems detaily,and hope you can help me to solve it.I have set a maven progect up,but I can not run App.java.&nbsp; I want to show you the detail points with pictures .&nbsp;
so thanks a lot for your help!
1.these are problems when I open this page



2.this is my maven progect&nbsp;&nbsp;

3.this is error when I run the App.java

**Comment by nhooyr** [comment]
See #1299
