### ISSUE TITLE
Keybindings don't work in webviews

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#1219]
- `code-server` version:  1.39.2
- OS Version: Archlinux server, Windows 10 Client (Brave Browser)

## Description
When veiwing extenstion details (this page)[https://i.imgur.com/ErWzRim.png]
And you try to use a hotkey, the browser itself will get the hotkey, and not code-server

## Steps to Reproduce

1. Visit extension page
2. perform hotkey such as `CTRL+SHIFT+P`

**Comment by karas111** [comment]
Shortcuts are not working if a webview is displayed. Here are a few examples where shortcuts do not work:
1. Python Interactive screen or Jupyter Notebook
Repro:
- install ms-python extension
- Ctrl+Shift+P -> Python: Show Python Interactive Window
- click on the opened window
- Ctrl+Shift+P -> Print Window is displayed

2. Extension preview as @Merith-TK mentioned
Repro:
- open Extension Tab
- type GitLens and click the extension
- Ctrl+Shift+P -> Print Window is displayed

3. GitLens: Welcome screen
Repro:
- install GitLens extension
- Ctrl+Shift+P -> GitLens: Welcome
- Ctrl+Shift+P -> Print Window is displayed

**Comment by Merith-TK** [comment]
ctrl+shift+p works when i use a chromium based browser,

**Comment by Merith-TK** [comment]
One way we could ensure something like this is maybe make a plugin that
reads a list of user provided urls, that listens and redirects as many
hotkeys as it can, to the site?

**Comment by sr229** [comment]
The problem is non-Chromium browsers hardbind their hotkeys and never allows them to be overriden. I suspect there's a open issue about it in Firefox already but I'm not sure.

**Comment by karas111** [comment]
@sr229 I have the problem on Chrome. The error happens when Web View has focus.
**OS Version:**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
**Web Browser**
Version 79.0.3945.117 (Official Build) (64-bit)

**Comment by sr229** [comment]
@karas111 Not relevant. If Web View has focus then that view takes precedence and code-server has no ability to listen to keyboard input when unfocused.

**Comment by code-asher** [comment]
https://github.com/microsoft/vscode/issues/82592
