### ISSUE TITLE
Visual Studio Code 1.40 support

### ISSUE THREAD

**Issue by sstone1** [cdr/code-server#1220]
I don't see anything open so far - will Code Server be moving to support Visual Studio Code 1.40?

https://code.visualstudio.com/updates/v1_40

**Comment by sr229** [comment]
Working on it.

**Comment by jgsun** [comment]
vs 1.41 released..

**Comment by sstone1** [comment]
@sr229 @code-asher I saw that you committed an update to 1.41. I pulled down the latest Docker image that includes this update `2.1699-vsc1.41.0`. However, I get an error message `Cannot reconnect. Please reload the window.`.

**Comment by Bessonov** [comment]
Get same error with `sshcode` and binary from docker image on a test VM:

```
$ ./sshcode root@xx.xx.xx.xx
2019-12-19 23:12:03 INFO	starting SSH master connection...
2019-12-19 23:12:04 INFO	ensuring code-server is updated...
sh: 26: [[: not found
mesg: ttyname failed: Inappropriate ioctl for device
++ uname -m
+ '[' x86_64 '!=' x86_64 ']'
+ pkill -f /root/.cache/sshcode/sshcode-server
+ true
+ mkdir -p /root/.local/share/code-server /root/.cache/sshcode
+ cd /root/.cache/sshcode
+ curlflags='-o latest-linux'
+ '[' -f latest-linux ']'
+ curlflags='-o latest-linux -z latest-linux'
+ curl -o latest-linux -z latest-linux https://codesrv-ci.cdr.sh/latest-linux
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
+ '[' -f /root/.cache/sshcode/sshcode-server ']'
+ rm /root/.cache/sshcode/sshcode-server
+ ln latest-linux /root/.cache/sshcode/sshcode-server
+ chmod +x /root/.cache/sshcode/sshcode-server
2019-12-19 23:12:04 INFO	syncing settings
sending incremental file list
deleting state/global.json
deleting state/empty-window.json
deleting state/
./

sent 107 bytes  received 77 bytes  368.00 bytes/sec
total size is 0  speedup is 0.00
2019-12-19 23:12:04 INFO	synced settings in 221.590633ms
2019-12-19 23:12:04 INFO	syncing extensions
sending incremental file list

sent 55 bytes  received 12 bytes  44.67 bytes/sec
total size is 0  speedup is 0.00
2019-12-19 23:12:05 INFO	synced extensions in 433.76324ms
2019-12-19 23:12:05 INFO	starting code-server...
2019-12-19 23:12:05 INFO	Tunneling remote port 3091 to 127.0.0.1:38913
sh: 26: [[: not found
Option 'allow-http' is unknown. Ignoring.
Option 'allow-http' is unknown. Ignoring.
info  Server listening on http://127.0.0.1:3091
info    - Password is xxxxxxxx
info      - To use your own password, set the PASSWORD environment variable
info      - To disable use `--auth none`
info    - Not serving HTTPS
```

**Comment by ikkerens** [comment]
If it helps, when running the docker image like @sstone1 does, and the client asks for a reconnect, this error appears in the server logs:
```
%c[IPC Library: File Watcher (chokidar)] %cUncaught Exception:  color: blue color:  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.normalize (path.js:1117:5)
    at F (nbin.js:1:2543)
    at Object.statSync (nbin.js:1:3222)
    at stat (internal/modules/cjs/loader.js:93:18)
    at Function.Module._findPath (internal/modules/cjs/loader.js:256:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:590:25)
    at Function.Module._load (internal/modules/cjs/loader.js:519:25)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/src/build/code-serverdocker-vsc1.41.0-linux-x86_64-built/out/bootstrap-fork.js:19:362)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:778:12)
    at startup (internal/bootstrap/node.js:288:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:748:3)
```

**Comment by sr229** [comment]
Please don't update to 1.40.x without syncing nbin to Node.js 12, which we are doing right now. The reason you're seeing this is because 1.40.x uses a different electron version compared to 1.39.x, which in turn uses Node.js 12.

**Comment by sr229** [comment]
I've done a [experimental build](https://github.com/sr229/cdr-web-lkgr/releases/download/1.41.0/code-server-1.41.0-warp.7z) using Node.js 12, this might be slower but it should work for now.

**Comment by vnijs** [comment]
@sr229 Since this is happening in the codercom/code-server:2.1699-vsc1.41.0 docker image, does that mean that the image has the wrong version of Node.js?

**Comment by sr229** [comment]
@vnijs quite so. nbin is still in Node.js 10 which is why we can't run VSCode Web in nbin.

**Comment by vnijs** [comment]
Thanks for the clarification @sr229. I'm not familiar with nbin but it looks like @code-asher is already working on upgrading (https://github.com/cdr/nbin/commit/3655faa8b11edef5de89298f8ae8d0ed4fb5d3ee). Looking forward to trying out the next release or docker image. Thanks!

**Comment by Bessonov** [comment]
> I've done a [experimental build](https://github.com/sr229/cdr-web-lkgr/releases/download/1.41.0/code-server-1.41.0-warp.7z) using Node.js 12, this might be slower but it should work for now.

Just make a smoke test - it seems to work with `sshcode` :+1:

**Comment by sstone1** [comment]
@sr229 @code-asher I checked out the latest Docker image today and it is working great AFAIK, thanks a lot 👍

**Comment by vnijs** [comment]
Nice! @code-asher Is there a time-line for a new binary release?

**Comment by code-asher** [comment]
Actually all I did was remove the broken images so Docker isn't using
1.40 either.

I'm hopeful that we'll have a working release this week for 1.41.1.
Future vscode updates shouldn't take so long even if we have to update
the Node version again.

**Comment by vnijs** [comment]
Installed the new release and it is working great!!! Thanks for making this available

https://github.com/cdr/code-server/releases/tag/2.1698
