### ISSUE TITLE
vscode-python extension cannot be activated

### ISSUE THREAD

**Issue by auzbuzzard** [cdr/code-server#1221]
- `code-server` version: 2.1692-vsc1.39.2
- OS Version: AWS Ubuntu 18.04.3 LTS
- Extension: ms-python.python 2019.10.44104
https://marketplace.visualstudio.com/items?itemName=ms-python.python

## Description

Whenever code-server is started or the window is reloaded, and a .py file is opened, VSCode would generate a notification saying the extension cannot be activated: 
`Activating extension 'ms-python.python' failed: Unexpected token , in JSON at position 3247.`

This is also shown in the Chrome browser console:

> `[Extension Host] Here is the error stack:  SyntaxError: Unexpected token , in JSON at position 3247
>     at JSON.parse (<anonymous>)
>     at o._getValue (http://localhost:26001/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3320:982)
>     at o.$getValue (http://localhost:26001/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3320:857)
>     at g._doInvokeHandler (http://localhost:26001/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3350:275)
>     at g._invokeHandler (http://localhost:26001/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3349:971)
>     at g._receiveRequest (http://localhost:26001/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3348:639)
>     at g._receiveOneMessage (http://localhost:26001/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3347:468)
>     at http://localhost:26001/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:3345:691
>     at c.fire (http://localhost:26001/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:116:519)
>     at v.fire (http://localhost:26001/static-44c4722edfa107215824ac96fa9ae79c785880cb/out/vs/workbench/workbench.web.api.js:346:97)`

Without the extension all Python linting and code suggestions do not work.
This is tried on both the docker image and the binary install of code-server, with only just the one plugin installed.

This plugin is the version available within code-server vscode. I have also tried the insider version by git cloning the extension source in the extensions folder, and also copying the latest version 2019.11.50794 from a local copy of vscode, but all have the same issue. 

## Steps to Reproduce

step 1: Start code-server on remote, either with the docker image or binary install
step 2: install the extension
step 3: reload required, let vscode reload window
step 4: wait for vscode to reload, if a .py file is opened, eventually a notification would pop up saying the extension cannot be activated.
step 5: the python extension and all of its functions are not activated.

**Comment by sr229** [comment]
Might be related to #697.

**Comment by vnijs** [comment]
@auzbuzzard I'm not seeing this issue using the same OS and python vsix version but in a docker container. 2019.11.50794 did cause issues but if you  install 2019.10.44104 and then 2019.11.50794 it seems to work. Still puts several messages and warnings in the the development tools, however. I'm hopeful that 2019.11.50794 will work as expected when codeserver updates to VSCode 1.41.0

**Comment by nhooyr** [comment]
Please update to latest version. If it still occurs feel free to reopen.
