### ISSUE TITLE
Where is the up.sh file?

### ISSUE THREAD

**Issue by cnTailor** [cdr/code-server#1224]
## Description
I can't continue in Deploy Coder to mykubernetes cluster.

In the  https://coder.com docs page? Installing Coder onto Kubernetes step2,Deploy Coder to your kubernetes cluster, 
`CLUSTER_USER=myname@myorganization.com ./up.sh --registry my.docker.registry.io`
here, `./up.sh` is placed where? because there is no this file in ther code-server tar archive

**Comment by cnTailor** [comment]
and how can i get the dashboard?  like this 
![dahboard](https://user-images.githubusercontent.com/10465889/70859559-a5ef7580-1f50-11ea-877f-22ed4a979e3f.png)

**Comment by sr229** [comment]
Heya, we do not cover Coder Enterprise here, so please use our official support contact for Coder Enterprise.

**Comment by deansheather** [comment]
If you're looking for instructions on how to install code-server, please consult the [readme](https://github.com/cdr/code-server#getting-started). The dashboard and the documentation on coder.com are for our enterprise product, not code-server (they are separate products).

**Comment by cnTailor** [comment]
OK, thanks!
