### ISSUE TITLE
Cannot reconnect. Please reload the window.

### ISSUE THREAD

**Issue by psinger** [cdr/code-server#1227]
- `code-server` version: current docker
- OS Version: Ubuntu 16.04.6 LTS

I ran the docker command and everything works fine, meaning I can access VS code throughout the browser remotely. However, after a few moments I always receive "Cannot reconnect. Please reload the window." as an error message in the browser.

I could not find any solution to this.

**Comment by realjohimself** [comment]
I also have this issue, running on UnRAID 6.8.0.

**Comment by FanyangMengDev** [comment]
Same here, it drives me crazy

**Comment by realjohimself** [comment]
I have reverted to previous. If anyone is unsure how to do this you need to replace codercom/code-server:latest (or codercom/code-server) with codercom/code-server:2.1697-vsc1.39.2 in your Docker manager

**Comment by psinger** [comment]
@realjohimself thanks, I can confirm that previous version works

**Comment by code-asher** [comment]
Sorry about this, the latest commit has an issue and I forgot the docker image deploys automatically on master. I'll be changing it to only deploy when we manually tag it or something like that. I'll also remove the broken image.

**Comment by renerchen** [comment]
I have the same problem. Any solution？

**Comment by code-asher** [comment]
@renerchen I recommend opening a new issue so you can fill out all the data that'll help us narrow down the problem. If you could also describe how you connect to code-server that could be helpful (for example if you use a reverse proxy).

**Comment by joeithub** [comment]
code-server version: v3.4.1 centos same question

**Comment by code-asher** [comment]
@joeithub Could you open a new issue describing your setup and logs?
