### ISSUE TITLE
Better authentication between JupyterHub + code-server

### ISSUE THREAD

**Issue by jrderuiter** [cdr/code-server#1228]
Currently we're running a multi-user setup, where multiple users are logging into JupyterHub and running notebooks on the same machine. We have integrated code-server with JupyterHub using the jupyter-server-proxy extension, which is working relatively nicely!

A drawback of the current setup is that we are using auth = none, which effectively means that any user can access another's user code-server instance if they identify the correct port.

Would it maybe be possible to setup better authentication between the two components? Maybe something might be possible by generating a password from within jupyter-server-proxy when starting the code-server instance and passing this password transparently via headers when redirecting the users browser to the proxied url?

**Comment by nhooyr** [comment]
> A drawback of the current setup is that we are using auth = none, which effectively means that any user can access another's user code-server instance if they identify the correct port.

You need to make sure only the proxy can access code-server directly, everything else must go through the proxy.

**Comment by wzrzt** [comment]
@jrderuiter  Excuse me, I'm trying to install code-server in jupyterhub, expecting to manage user auth by jupyterhub. However, I searched from google and github, found only examples for vscode or theia in jupyterlab, nothing about jupyterhub.  For the first I thought they are the same. But vscode shows only in jupyterlab not jupyterhub, on the same machine and same anaconda3 python3 env. Would you mind show me how to make vscode work in jupyterhub by  jupyter-server-proxy or is there any document to refer ? Thank you
