### ISSUE TITLE
Vim extension 1.12.0 doesn't work. I think code-server needs to let users have vim 1.12.2

### ISSUE THREAD

**Issue by kovkev** [cdr/code-server#1230]
This is the thread at VSCodeVim!

https://github.com/VSCodeVim/Vim/issues/4340

**Comment by Bessonov** [comment]
Should it be fixed by https://github.com/cdr/code-server/issues/1220?

**Comment by nhooyr** [comment]
Should work now, feel free to reopen if not.

**Comment by tidux** [comment]
This does not work with latest aarch64 .deb and latest Vim extension.

![Screenshot from 2020-05-21 23-18-52](https://user-images.githubusercontent.com/1330562/82637477-b370f180-9bb9-11ea-9ef0-d2a20da4715a.png)

**Comment by tidux** [comment]
This appears to be a code-server specific issue since the same version of the extension works on a regular OSS build of Code.
