### ISSUE TITLE
Unable to install ESLint extension because it is not compatible with the current version of VS Code

### ISSUE THREAD

**Issue by talentlessguy** [cdr/code-server#1232]
- `code-server` version: 1.39.2
- OS Version: Manjaro Linux 5.4
## Description

When I try to install ESLint extension, I get this:

![image](https://user-images.githubusercontent.com/35937217/71089520-177a2e80-21b2-11ea-895a-c9f698353c9a.png)

## Steps to Reproduce

1. Install `code-server` from AUR (`yay -S code-server`)
2. Search for ESLint
3. Hit "Install"

Related: #43

**Comment by Bessonov** [comment]
Should it be fixed by https://github.com/cdr/code-server/issues/1220?

**Comment by talentlessguy** [comment]
> Should it be fixed by #1220 

Yes, it should but it is not merged yet

**Comment by mwswindle** [comment]
FYI, theres a work around, building the latest supported version straight from the git repo.

```bash
cd
git clone https://github.com/microsoft/vscode-eslint.git
cd vscode-eslint
git checkout tags/release/1.9.1
npm i
npx vsce package
```

Next, click on the ***Extensions*** tab, and in the 3-dot-menu drawer, first click ***Disable Auto Updating Extensions***.
Then, click on ***Install from VSIX*** in the 3-dot-menu drawer, navigate to the git folder, and select the vsix.

You can delete the git folder now.

**Comment by hasip-timurtas** [comment]
download this to your server:
[https://dbaeumer.gallery.vsassets.io/_apis/public/gallery/publisher/dbaeumer/extension/vscode-eslint/1.9.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage](url)

and 
CTRL+SHIFT+P 
and type VSIX
then find the file you downloaded from the link above.
Now you installed an older version of ESlint that can work with your vscode.

**Comment by cstrat** [comment]
Thanks @hasip-timurtas - I wasn't able to get it to work by doing what @mwswindle suggested, but downloading the binary direct has worked so far.

**Comment by sr229** [comment]
We updated to 1.4x so this should be fixed now

**Comment by cstrat** [comment]
I updated to the latest release docker yesterday and it didn't work?
Is docker updated with 1.4x?

**Comment by code-asher** [comment]
The latest and v2 tags haven't been updated yet. There is a 2.1698 tag
but I'll go ahead and update latest and v2 now. I'll need to make sure
they get updated after we've verified it works in the future.

**Comment by cstrat** [comment]
Yeah my mistake. My experience with docker is limited largely to this project only so I didn’t realise `latest` wasn’t automatically the latest.

Thanks for all the good work on the project!

**Comment by code-asher** [comment]
Nah, it's definitely my bad for having a release and yet not updating
the latest tag. Shouldn't happen again. Thanks for the kind words!

**Comment by code-asher** [comment]
Oof, this is embarrassing. I didn't check the output of my push
yesterday and it didn't actually work. I did it just now so `latest` is
now actually latest.
