### ISSUE TITLE
Logging in not inheriting the https protocol from the request

### ISSUE THREAD

**Issue by TobiaszCudnik** [cdr/code-server#1233]
- `code-server` version: 2.1692-vsc1.39.2
- OS Version: ubuntu, scaleway

## Description

When tunneling default 8080 to an SSL endpoint, after logging in (via https) the app redirs to http. Have to manually type https to make it work.

## Steps to Reproduce

1. Start the server with defaults
1. Create an SSL-only tunnel using ngrok
  `ngrok http -bind-tls=true 8080`
1. Log in

Expected: redir keeps https as the protocol

Result: redir changes the protocol to http (which is not served and results in a blank page)

**Comment by sr229** [comment]
This is by design as your server is not HTTP/S from the start, you should tell the proxy server to redirect all traffic to HTTP/S (which I think is not possible in ngrok).

**Comment by TobiaszCudnik** [comment]
In theory I could create another http-only tunnel under the same address which redirs everything to https, but wouldnt it be much easier if your post-login redir use an inherited protocol schema `://whatever` instead of `http://whatver`? That way you'd never switch protocols.

Thanks anyway, I love this project :)

**Comment by sr229** [comment]
> In theory I could create another http-only tunnel under the same address which redirs everything to https.
> 
> Wouldnt it be much easier if your post-login redir use an inherited protocol schema `://whatever` instead of `http://whatever`? That way you'd never switch protocols.
> 
> Thanks anyway, I love this project :)

Yes.

**Comment by nhooyr** [comment]
Asher will take care of this.
