### ISSUE TITLE
Go Extension does not work

### ISSUE THREAD

**Issue by tristanjclarke** [cdr/code-server#1234]
## Description
When using any of the commands for the go extension the error `command 'go.gopath' not found` becomes present. 

This same thing happens for every go command and reduces usability of the go extension. 

Have tried `Go: Install/Update Tools` and `command 'go.tools.install' not found` is reported.

**Comment by tristanjclarke** [comment]
Is there any update on this bug?

**Comment by nhooyr** [comment]
Another broken extension due to the scraper. See #1299

**Comment by kylecarbs** [comment]
Fixed! The Go extension requires Go is in your path otherwise the extension will fail to install.

**Comment by Rudi9719** [comment]
Sorry for the necro, however I'm getting this exact issue using Go 1.14.1 on linux/amd64
```GO111MODULE=""
GOARCH="amd64"
GOBIN="/home/csnet/go/bin"
GOCACHE="/home/csnet/.cache/go-build"
GOENV="/home/csnet/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/csnet/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build390077288=/tmp/go-build -gno-record-gcc-switches"```

**Comment by nhooyr** [comment]
@cmoog

**Comment by Abhid14** [comment]
For me not only go but even html and simple vanilla javascript is not working even extensions are failing to work like html formatter.

**Comment by Abhid14** [comment]
![image](https://user-images.githubusercontent.com/34400585/78008857-d3282e00-735d-11ea-8c81-432af23a115d.png)

**Comment by Rudi9719** [comment]
Also in response to @kylecarbs my path is as follows:
```/usr/local/go/bin:/home/rudi/go/bin:/usr/local/go/bin::/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin```

**Comment by cmoog** [comment]
@Rudi9719 I think there is an issue with your path. Observe how your `GOBIN` and `GOPATH` are not present in the `PATH` you've just pasted above.

**Comment by nhooyr** [comment]
@Rudi9719 Your $GOBIN is `/home/rudi/go/bin` but your `$GOPATH` is `/home/csnet/go`. Not sure if you are intentionally using a different home directory.

@Abhid14 Can you open a new issue regarding what errors you're getting?

**Comment by Abhid14** [comment]
> @Abhid14 Can you open a new issue regarding what errors you're getting?

So far so Good since build 3.0.2 Will surely report if any problem occurs. Thank you!
