### ISSUE TITLE
Closing file/folder open dialogs

### ISSUE THREAD

**Issue by oonqt** [cdr/code-server#1235]
I believe there should be a feature to close the open file/folder dialogs. It's annoying whenever I accidentally go to "open folder" when I'm simply trying to open a file and I end up having to open the working folder AGAIN and wait for code-server to load just to get rid of the dialog.

**Comment by allquixotic** [comment]
You can press ESC to close the dialog.

**Comment by dom-insytesys** [comment]
Thanks, @allquixotic .  That's been bugging the hell out of me.  I couldn't figure out how to get the dialog box to disappear either!

**Comment by sr229** [comment]
While we're happy to add that, that's a upstream issue, so raise this to @microsoft instead. This is a VSCode UX issue we would like not only us to benefit, but the VSCode as a whole.
