### ISSUE TITLE
Passing Authorization Credentials Through URL 

### ISSUE THREAD

**Issue by Ceknaz** [cdr/code-server#1236]
## Description
Is there any possible way to add the key into the URL when `--auth password` is activated and redirecting to main page if the key is correct, instead of inserting the password on `/login` page manually?

**Comment by sr229** [comment]
It's not possible, if you want such functionality, I suggest looking at the community's input with their implementations in #792. We won't support this upstream for now.

**Comment by sr229** [comment]
It's not possible, if you want such functionality, I suggest looking at the community's input with their implementations in #792. We won't support this upstream for now.
