### ISSUE TITLE
base-path option is not use.

### ISSUE THREAD

**Issue by liucimin** [cdr/code-server#1237]
info  2.1692-vsc1.39.2
info  e14362f3224c101585a26bf7ee5fa6e3bf425046
info  x64

## Description

I use base-path in code-server.But i not use!!

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/8232349/71444668-09965180-274e-11ea-824d-25e8c0296fea.png)

![image](https://user-images.githubusercontent.com/8232349/71444685-30ed1e80-274e-11ea-9579-a8d60e137616.png)

If i use the base-path it not found!

![image](https://user-images.githubusercontent.com/8232349/71444703-4bbf9300-274e-11ea-8c09-d0b0e5b0bf07.png)

**Comment by sr229** [comment]
Heya, thanks for reporting, but we're all out of office till January 6, so this will be dealt on the end of the decade. Happy holidays!

**Comment by akhilputhiry** [comment]
@sr229 any update on this

**Comment by code-asher** [comment]
The base path flag is only for people using a reverse proxy. Do you have one set up, and if so could you post your configuration?

**Comment by nhooyr** [comment]
You need a reverse proxy setup, base-path can be better documented in the FAQ though.

**Comment by liucimin** [comment]
@nhooyr 
Would do you like to show me the config in  reverse proxy ? such as nginx.
I dont konw how to config the nginx to access the vscode server by a bath path.
