### ISSUE TITLE
Marketplace Question

### ISSUE THREAD

**Issue by GrimTheReaper** [cdr/code-server#1238]
This is probably a dumb and already asked question, but... Has anyone here _actually_ reached out to the VSCode team to see if they would change the TOS on the market place and possibly offer a stable API to consume? I feel like it wouldn't be a lot to ask from them, and wouldn't it add to the value of VSCode?

**Comment by sr229** [comment]
See GH-990

**Comment by GrimTheReaper** [comment]
That's rather ridiculous that Microsoft is keeping it closed. Thank you for the link.
