### ISSUE TITLE
VSCode in Browser 's setting.json should not same with the one in my MAC book 

### ISSUE THREAD

**Issue by GeorgeXc** [cdr/code-server#1240]
- `code-server` version: 
- OS Version: 
./latest-linux --version
info  2.1692-vsc1.39.2
info  e14362f3224c101585a26bf7ee5fa6e3bf425046
info  x64
## Description

I deploy the code-server in an linux server. And then I open it in my browser Safari.
When I open it's "settings.json", I found that it's the same with the one in my Mac book
## Steps to Reproduce

1. deploy the code-server
1. open the code-server url  in the browser Safari

**Comment by nhooyr** [comment]
Not really sure what's going on here. They can't be the same.
