### ISSUE TITLE
git history extension works wrong

### ISSUE THREAD

**Issue by lscgzwd** [cdr/code-server#1241]
- `code-server` version:  the latest docker image
- OS Version: ubuntu 18.04
- Extension: https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory

## Description

When view some file's git history, it shows localhost deny.
![image](https://user-images.githubusercontent.com/7054255/71577231-53a47c00-2b2e-11ea-85a3-9815ce4d01d1.png)

## Steps to Reproduce

1. open one file, click the git history icon

**Comment by LSmith-Zenoscave** [comment]
The gitHistory extension does not currently support remote editors. 
see https://github.com/DonJayamanne/gitHistoryVSCode/issues/379

Many extensions of this nature expect `localhost` to be reachable by the interface. This won't work with the browser.

I suggest taking a look at [DonJayamanne/gitHistoryVSCode](/DonJayamanne/gitHistoryVSCode) and seeing if a patch to their repo would be accepted

**Comment by nhooyr** [comment]
Thank you @LSmith-Zenoscave for answering. Nothing we can do here.
