### ISSUE TITLE
Jupyter Notebooks inside coder vscode?

### ISSUE THREAD

**Issue by bhope78** [cdr/code-server#1242]
Hello, 

Is it possible to run jupyter notebooks inside coder, if so is there any documentation about connecting anaconda and coder?

https://www.youtube.com/watch?v=FSdIoJdSnig

Thanks

**Comment by SPTKL** [comment]
yes, just install the python extension and make sure you have jupyter notebook python packages installed
https://marketplace.visualstudio.com/items?itemName=ms-python.python
you need to download the extension and install manually

**Comment by mirekphd** [comment]
Apparently, it is not enough to install those packages, as `code-server` does not seem to be able to start parsing `.ipynb` files (at least without access to the internet), even though we can run both notebook and jupyterlab packages in the python files editor (with output displayed in Terminal window).

You can test it for yourself in this container (the auto-generated password can be obtained from `docker logs`): 
`docker pull mirekphd/ml-cpu-py37-vsc-cust:20200114`

**Comment by nhooyr** [comment]
There is no way to run jupyter notebooks at the moment.

**Comment by nhooyr** [comment]
Ah I misinterpreted, I thought it was about running the jupyter notebook IDE in code-server.

We'll investigate this at some point.

**Comment by nhooyr** [comment]
Does it work in regular VS Code?

**Comment by mirekphd** [comment]
Yes, at least for Microsoft Devs:)
https://code.visualstudio.com/docs/python/jupyter-support

**Comment by nhooyr** [comment]
Just tested and the jupyter notebook hello world example from the VS Code docs works fine for me on code-server.

**Comment by umdstu** [comment]
I stumbled across this yesterday when I realized that 

- `Python: Import Jupyter Notebook`
- `Python: Specify Jupyter server URI`

were both missing from the Command Palette until I installed the ms-python extension. After that, the above commands were available, as well as the `Python: *` commands, including the one to specify the python interpreter that is required before you can use either of the above commands. After running `Python: Select Interpreter`, which does in fact seem to work, you can attempt to specify a Jupyter server URI, but nothing appears to happen after doing so. I'm unsure which steps to take after this point in order to assist in debugging. Let me know if I can help otherwise.

Thanks

**Comment by umdstu** [comment]
@nhooyr Just saw your message/closing of this after I submitted (I guess the tab didn't reload when I reopened the browser).
Two questions for you:
1. After you opened the .ipynb fille, did it prompt you to import the file? (It failed for me until I pip installed the `jupyter` python package)
2. If so, after importing the file, did you attempt to run any cells? 

For me, 2 above opened up a new Tab in vscode, called Python Interactive, but nothing else happened. Looking at the browser console, the following errors were present, did this happen to you?:
```
[Extension Host] Python Extension: Error ENOENT: no such file or directory, scandir '/resources/app/extensions' ... console.ts:137
Uncaught SyntaxError: Unexpected token '<' ... main.js:2
Uncaught SyntaxError: Unexpected token '<' ... host.js:2
```

Thanks

**Comment by nhooyr** [comment]
It prompted me to install the python packages and then I was able to run a simple print cell.

**Comment by nhooyr** [comment]
Also, I had no errors AFAIK but I will reopen and test again if this still occurs to you.

**Comment by umdstu** [comment]
I was able to get code-server to finally connect to the jupyter instance after updating the ms-python extension to the 2020 version. That said, I witnessed odd behavior where every time vscode connected to the kernel, an empty ipynb file was created in Jupyter. Not sure which side that would be a bug in.

Thanks for your consideration.
