### ISSUE TITLE
Installation Issue: Docker version wont run!

### ISSUE THREAD

**Issue by tomscatbilly** [cdr/code-server#1243]
Hey All,

I tried to add the container but i get the error
`error EACCES: permission denied, mkdir '/home/coder/.local/share/code-server/extensions'`

Any Ideas?

**Comment by azumag** [comment]
In my case, I solved this as follows:
```
$ cd ~/
$ sudo mkdir .local/share/code-server/extensions
```
It assumes that docker mounting `${HOME}/.local/share/code-server:/home/coder/.local/share/code-server`

However, for fundamental resolution, need fix commit like #1191

**Comment by bruce9399** [comment]
$ chown 1000:1000 -R ${HOME}/.local/share/code-server

Try it.

**Comment by tomscatbilly** [comment]
@bruce9399 Thank you that fixed it!
