### ISSUE TITLE
Update VSCode to Release 1.41.0

### ISSUE THREAD

**Issue by hmerk** [cdr/code-server#1244]
Is there already an ETA for the new release 1.41 ?

**Comment by sr229** [comment]
The team is out of office till January 6. We're working on it.

**Comment by hmerk** [comment]
:+1:

**Comment by kylecarbs** [comment]
It's on master, we'll just have to make a release for it. Expect this soon...

**Comment by omfgnuts** [comment]
Are there any issues with releasing the updated build?

**Comment by sr229** [comment]
@omfgnuts This release is extra special, because we're finally giving ARM users their long awaited binary release, so please have some patience, we want everyone to have fun with VSCode.

**Comment by hmerk** [comment]
Closed as Release is out.
