### ISSUE TITLE
Docker - Install Python in container

### ISSUE THREAD

**Issue by tomscatbilly** [cdr/code-server#1247]
Does anyone know how to install python into the docker container?
I've tried using the "command" field on docker but know luck.

Any Ideas?

**Comment by IBlackI** [comment]
You can create a Dockerfile to create an image which has python installed.

Something like this:
```
FROM codercom/code-server:v2

USER root
RUN apt-get update && apt-get install -y \
	python

USER coder
EXPOSE 8080

ENTRYPOINT ["dumb-init", "code-server", "--host", "0.0.0.0"]
```
