### ISSUE TITLE
Java Extension Pack not installable from Marketplace

### ISSUE THREAD

**Issue by hmerk** [cdr/code-server#1248]
Tried to install Java Extension Pack from code-server Marketplace but it fails.
First off all, the version in Marketplace is outdated, but most important it fails by installing Language Support for Java by Red Hat, showing incompatibility with VS Code 1.39.2

**Comment by sr229** [comment]
@kylecarbs looks like we might need to double up on the 1.4x update.

**Comment by hmerk** [comment]
Closed after, working after latest release.
