### ISSUE TITLE
Extension installer: Requests to the server have been blocked by an extension

### ISSUE THREAD

**Issue by fonnesbeck** [cdr/code-server#1249]
- `code-server` version: 1692-vsc1.39.2
- OS Version: Debian 9

## Description

When running code-server locally in my browser (Chrome), all extension pages that access the network are blank, except for a message "Requests to the server have been blocked by an extension".

Here's a screen shot:

![image](https://user-images.githubusercontent.com/81476/71771947-7ce75280-2f08-11ea-9bda-13a213dfa2cc.png)

## Steps to Reproduce

1. Run code-server on localhost
1. Open extensions tab
1. Choose any extension with information that is pulled from the network

**Comment by nhooyr** [comment]
I believe this is on your end, try to use a fresh browser without any extensions.
