### ISSUE TITLE
Start Code-server with non-root

### ISSUE THREAD

**Issue by TalonSilverStaff** [cdr/code-server#1250]
## Description

I've looked at the other question but no example how to start code-server in Full non-root user.   

I didn't see a setting for the Terminal to not Open into the root user.  I have the service setup to run from a non-root user but didn't see anywhere to change this.   I can't deploy the service until i've solved the work around for this . Any ideas please all are welcomed. 

Thank you

**Comment by sr229** [comment]
You can run `code-server` as a non-user. #1010 should've fixed the docs with systemd.

**Comment by tabs-not-spaces** [comment]
As @sr229 said, this issue is resolved - simply place the following in your code-server.service file (assuming you are using systemd to launch the service).

```
[service]
user=USERNAMEGOESHERE
```
