### ISSUE TITLE
Limit access to a folder

### ISSUE THREAD

**Issue by PhaserEditor2D** [cdr/code-server#1251]
It would be great to have a CLI option to limit the access of code-server to a particular folder, so users cannot read or write outside that folder. Something like:

```
server-code --data-dir $HOME/public-projects
```

**Comment by sr229** [comment]
We don't provide that functionality, but if you're a seasoned Linux veteran or taken Red Hat courses regarding Linux permissions, `chmod` and `chown` serves this purpose for you.

**Comment by sr229** [comment]
As for preventing the user to invoke `cd` to the folder, that's something we can't do. Perhaps container-based development workspaces might be your thing?

**Comment by PhaserEditor2D** [comment]
> Linux permissions, chmod and chown serves this purpose for you.

Yes, it could work for the Terminal. But what about this dialog?

![image](https://user-images.githubusercontent.com/12187299/71818927-56383180-3058-11ea-9055-d906039c5872.png)

Is there a way we can limit it to a particular folder?

> Perhaps container-based development workspaces might be your thing?

Yes, I guess it is the most secure solution. Thanks for your quick answer.

**Comment by sr229** [comment]
@PhaserEditor2D there's nothing we can solve about that, that's intended by design.

**Comment by PhaserEditor2D** [comment]
Thanks anyway!

**Comment by joeshub** [comment]
came here looking for the same thing. Seems weird to give anyone root level access to a server. Has anyone figured out a solution yet?

**Comment by nhooyr** [comment]
@joeshub Run `code-server` as a different user and only allow that user to edit those files. Or chroot `code-server` into that directory.

**Comment by vahid-neuralinc** [comment]
I would suggest to run code-server in docker and mount a host OS folder into that docker container
