### ISSUE TITLE
When/How are available extension updated

### ISSUE THREAD

**Issue by Confectrician** [cdr/code-server#1253]
Hi all,

One of our community members recently discovered/tried out code-server.
He discovered also that our [openHAB extension](https://marketplace.visualstudio.com/items?itemName=openhab.openhab) ([GitHub Repo](https://github.com/openhab/openhab-vscode)) is already available (Yay 🎈 ) in your marketplace, but unfortunately with an older release currently.

## Description

What would have to be done or how can we inform cdr about new releases of our vscode extension, to get new releases into the marketplace fast?
Is there maybe some automated way for us to verify us as extension owner and trigger a new cdr marketplace release?

Thanks in advance for your feedback.

## Related Issues

Corresponding issue in our extension repo:
https://github.com/openhab/openhab-vscode/issues/185

PS:
Happy new year to everyone reading this. 🙂

**Comment by sr229** [comment]
Hey there, our registry unfortunately, is private, and we tried our best efforts to keep it up to date. I'll mark this issue so it could be looked on.

**Comment by sr229** [comment]
if I remember, we're planning to have a open source registry soon, no ETA, but its definitely in the works.

**Comment by Confectrician** [comment]
So from what i read the current workflow would be,
to inform you with an new issue in this repository after release of a new extension version?

If yes, my question would have been answered for now and i will put adding in issue here on my release todo list. 🙂 

PS:
An open source registry would be neat indeed, but i have no problem with doing it the "issue way" for now. 🙂

**Comment by sr229** [comment]
@Confectrician No need for such now, We'll inform you once we've updated the extension.

**Comment by sr229** [comment]
Update: Looks like we update already, just make releases in GitHub and we'll build your extension in our registry.

**Comment by Confectrician** [comment]
Thanks for answers and clarification.
THis Issue is then solved from my side. 🙂

**Comment by hmerk** [comment]
Don‘t think it is solved, as the marketplace version does not reflect our latest release from last November but is 2 versions behind.

**Comment by sr229** [comment]
Thanks for letting me know @hmerk I'll let the team know.

Escalating to urgent.

**Comment by nhooyr** [comment]
Something is wrong with the scraper. Will investigate.

**Comment by nhooyr** [comment]
@kylecarbs

**Comment by kylecarbs** [comment]
We'll be documenting this soon. We have a new extension marketplace in the works that'll bring more transparency to this!

Once out, all extensions will be pulled from GitHub and rebuilt daily.

**Comment by nhooyr** [comment]
See #1299
