### ISSUE TITLE
Debugging not getting started in Visual Studio Code running in Browser with Omnisharp extension

### ISSUE THREAD

**Issue by somuamit** [cdr/code-server#1254]
Hi,
I have installed the code-server on my Ubuntu 16.04 aws instance and I was able to open VSCode in  the browser. I have created a new webapi project in DotNet and downloaded Omnisharp extension for debugging. But whenever I am trying to launch Debug it is giving me below error:
"**_You may only use the Microsoft .NET Core Debugger (vsdbg) with Visual Studio Code, Visual Studio or Visual Studio for Mac software"
Below are the steps followed:

1. FTP code-server2.1692-vsc1.39.2-linux-x86_64.tar.gz to my Ubuntu AWS instance and untar it by executing the command tar -xvf <file name>
2. Install DOT NET by executing command sudo snap install dotnet-sdk --channel=3.0/stable --classic
3. Created symbolic link by executing the command sudo ln -sv /snap/dotnet-sdk/current/dotnet /usr/local/bin/dotnet
4. Started code-server by executing the command nohup ./code-server --auth none & 
5. We can access the Visual Studio Code on <YOUR_IP>:8080
6. Installed Omnisharp extension on Visual Studio Code
7. Created new dot net project by executing the command dotnet new webapi on the Visual Studio Terminal 
8. Whenever we are trying to start the Debugging, it does not start the debugging and it displays the following message:
	You may only use the Microsoft .NET Core Debugger (vsdbg) with Visual Studio Code, Visual Studio or Visual Studio for Mac software

**Comment by sr229** [comment]
Unfortunately we can't fix this because of license restrictions with vsdbg.
