### ISSUE TITLE
support of right click as paste

### ISSUE THREAD

**Issue by Archer-Thane** [cdr/code-server#1255]
Hey there, awesome project! Really loved that!
Is there any support for paste with right click of mouse? there is a cool property in some terminals like bash, which you can paste via right click. 
VS code it self has this support, but as a I checked on code-server there isn't any.
is there any activation or something?

**Comment by sr229** [comment]
We already supported clipboard. You might be running in a non-whitelisted HTTP remote.

You must run code-server in `localhost`, `*.local`, `127.0.0.1/16` or similar.

**Comment by sr229** [comment]
Another option is to run it in HTTP/S. Browsers block Clipboard support by default on insecure remotes.

**Comment by mirsella** [comment]
Hello, not sure to understand your last comment. 
I'm running code-server (last aarch64 build) on https 
```
info  Server listening on https://localhost:444
info    - Using custom password for authentication
info    - Using provided certificate and key for HTTPS
```
and i can't CTRL+V, CTRL+Shift+V and in the right clic menu the past option isn't here. i tried running it with on https://0.0.0.0:444 but it hasn't worked too, i'm connecting to it by nginx.
