### ISSUE TITLE
How to exit from code-server

### ISSUE THREAD

**Issue by Samvid95** [cdr/code-server#1257]
Hey guys, 

Sorry a beginner issue but how do you stop the code-server? Because just pressing Ctrl+z doesn't kill the process so I have to do it separately and I don't know how to close the code-server.

**Comment by jms1989** [comment]
if you have it running in a terminal and not in the background then ctrl+c should do it.

if it is in the background then you'll need to do `docker ps` to get it's name then `docker stop <id>` and `docker rm <id>` to stop and remove it. removing it may not be necessary but it helps to keep things clean I guess.

**Comment by talentlessguy** [comment]
if you have installed it via AUR do this: `killall code-server`

**Comment by sr229** [comment]
I assume the OP has fixed it so going to close this now.

**Comment by PoChenKuo** [comment]
try
systemctl --user stop code-server

**Comment by Mooling0602** [comment]
> try systemctl --user stop code-server

Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)

**Comment by bfgoh** [comment]
I changed to 0.0.0.0:8080, shutdown and turn on my computer. And it works!
