### ISSUE TITLE
How to launch code-server for multiple users so that the landing page is different for different user

### ISSUE THREAD

**Issue by somuamit** [cdr/code-server#1259]
Hi,
I have take Ubuntu 16.04 AWS instance, and I have launched code-server and I am able to open VS Code on the port 8080. I have created multiple users (user1,user2, user3 and so on) and all the users will create their own workspace(folder). But the problem is when I launch code-server on the browser it will land to the page where the last user left. 
I want the landing page different for different users. Please advice how to achieve it. or any other better approach to allow multiple users to work on the same instance of code-server.

**Comment by hasip-timurtas** [comment]
I recommend you one server for each user.

**Comment by sr229** [comment]
Hey there, try doing a container-based approach, so whenever a user will login to a specific instance, they'll be directed to their own workspace.
