### ISSUE TITLE
humao.rest-client  extension command not found

### ISSUE THREAD

**Issue by voxsoftware** [cdr/code-server#126]
- `code-server` version: 1.31.1
- OS Version: ubuntu 18.04 x64

1. Install extension humao.rest-client
2. Reload editor
3. Create an .http File
4. Use command pallette to tap "Rest client: Send request"

will show an error: 
command 'rest-client.request' not found

**Comment by kylecarbs** [comment]
Seems like this extension may be failing. cc: @foresthoffman

**Comment by voxsoftware** [comment]
Any advance on this?

**Comment by foresthoffman** [comment]
@voxsoftware Thanks for checking. I don't have time to check this one right now, but it's definitely on the list.

**Comment by nhooyr** [comment]
Duplicate of #1299
