### ISSUE TITLE
code-server keep the terminal stuck

### ISSUE THREAD

**Issue by bbaltatu** [cdr/code-server#1262]
Hi,
I put the following command into a bash script:
`#!/bin/bash
export PASSWORD="asd1asd"
./code-server --port 18609 --cert /home/bogdan/certs/\*.domain.net/\*.domain.net.cer --cert-key /home/bogdan/certs/\*.domain.net/\*.domain.net.key --host dev.domain.net &`

After running the script, it remains stuck.
![image](https://user-images.githubusercontent.com/11313025/71989253-fd27f380-3239-11ea-9235-ec26335f7ffd.png)

**Comment by sr229** [comment]
Hey there, you should be running it as a service instead. `&` is usually only used to run two commands at once, so you shouldn't use that.
