### ISSUE TITLE
How and where to set command line switch: --enable-proposed-api ms-vsliveshare.vsliveshare

### ISSUE THREAD

**Issue by gotjoshua** [cdr/code-server#1263]
## Description
I am running the v2 docker container...   
How and where can I set command line switch: 
`--enable-proposed-api ms-vsliveshare.vsliveshare`
??
## Related Issues
#173 #388

**Comment by sr229** [comment]
We pass the VSCode flags so using that flag while invoking the binary should work.

**Comment by MarcSkovMadsen** [comment]
Hi @gotjoshua . Did you get live share working on code server? Do you have a full description of what to do.

I would be interested in getting this up and running too.

**Comment by gotjoshua** [comment]
> Did you get live share working on code server?

never managed. was convinced that it wouldn't work ( mostly due to licensing restrictions )

still curious about codestream and gitpod possibilities, but no success yet
