### ISSUE TITLE
Possible to open file from terminal

### ISSUE THREAD

**Issue by InsOpDe** [cdr/code-server#1264]
## Description
Id like to have a command with which I can open a file from the vs code terminal. The file should then open with vs code.

Edit: Something like this: https://stackoverflow.com/questions/41377489/how-to-open-a-file-from-the-integrated-terminal-in-visual-studio-code

**Comment by sr229** [comment]
We pass the regular vscode command line so try to use the same flags.

**Comment by code-asher** [comment]
This isn't currently possible but eventually it will be. Tracking for the feature can be found here: https://github.com/cdr/code-server/issues/164

We'll most likely detect if code-server is already running and if so we'll open the file in the existing instance.

**Comment by MacDada** [comment]
I came here from a search engine, but I already have found the answer, so I will share it: `core -r filename` already works.
