### ISSUE TITLE
Terminal doesnt load in Systemd Startup

### ISSUE THREAD

**Issue by FxMathSolution** [cdr/code-server#1265]
I installed code-server from release on ubuntu 18.04. When running it directly from the command line, it shows terminal, but when make it service and use Systemd, after restart my VPS, it doesn't shows terminal.
Any advice?

**Comment by litaxc** [comment]
How did you resolve this issue?
I’m hitting the same thing.

**Comment by FxPouya** [comment]
I used this:
http://supervisord.org/
