### ISSUE TITLE
setting active text editor with url parameter.

### ISSUE THREAD

**Issue by fanixus96** [cdr/code-server#1271]
Is it possible to pass parameter like &fileToOpen=index.js to url to open this file in editor?

**Comment by sr229** [comment]
this concerns upstream, please tell @microsoft about your feature request, thanks!

**Comment by PhaserEditor2D** [comment]
@fanixus96 this is a good idea. Maybe it can be done via extension?

**Comment by fanixus96** [comment]
But right now Im able to close editor and after refresh this editor will be opened. I have found https://github.com/cdr/code-server/issues/801 but I cant find file saved on localStorage? Where are you saving this configuration? I can t find where it is triggered.

**Comment by code-asher** [comment]
There should be a JSON file in ~/.local/share/code-server/state that
contains information about open editors and so on.
