### ISSUE TITLE
Run code-server with verbose logging

### ISSUE THREAD

**Issue by rohinwork** [cdr/code-server#1273]
## Description
How do I run code-server with mode verbose logging? 

I would like to troubleshoot some issues that I am facing with code-server but I was not able to find the flag to pass to code-sever to enable more verbose log levels.

**Comment by sr229** [comment]
We do have the `--verbose` flag AFAIK. Back then it didn't work (#939) but it should work now nonetheless.

**Comment by rohinwork** [comment]
@sr229 thanks for the quick response. Do you also know where these logs show up?
 - `stdout` or `.local/share/code-server/logs`

**Comment by sr229** [comment]
It shows in stdout as well AFAIK.

**Comment by rohinwork** [comment]
Great! I'll have a look. Thank you :)

**Comment by code-asher** [comment]
Our logging shows up in stdout but all of vscode's logging only appears
in the log directory (or you can use the output panel in vscode).
