### ISSUE TITLE
Google Cloud issue

### ISSUE THREAD

**Issue by talmarygold69** [cdr/code-server#1276]
Ok so i am following this tutorial: https://www.youtube.com/watch?v=N5WojMutddQ&t=239s

And i created a new vm instance in google cloud with 2 cpus and 7.5gb of ram as stated in the github
I opened my gcloud shell and input the following command
wget linkoflatestvscode
tar -xvzf codeservertarfile
cd folder
sudo ./code-server -p 80 but i get this in the shell and it doesnt return another line, its just there forever

Option 'p' is unknown. Ignoring.
info  Server listening on http://localhost:8080
info    - Password is 
info      - To use your own password, set the PASSWORD environment variable
info      - To disable use `--auth none`
info    - Not serving HTTPS

how do i fix this??

**Comment by sr229** [comment]
@talmarygold69 Make sure your VM is allowed to accept ingress in GCP. The instructions you just linked is done in Crostini, and there is no gurantee that cloud vendors has the same setup as Crostini.

**Comment by sr229** [comment]
This may also be your Firewall rules not allowing Port 80. Check your GCP Firewall rules.

**Comment by talmarygold69** [comment]
Yea, ok so i followed the steps on the code server github, but there is no instructions for the IP range section ( something about CIDR notation and stuff), what do i put in there?

**Comment by sr229** [comment]
Go to VPC Network and see your current Network, there would be a place for you to edit the firewall rules

by default AFAIK they don't expose port 80 in VMs in the VPC but YMMV

**Comment by talmarygold69** [comment]
What does YMMV mean? I can edit the firewall rules and all but, there is a column i have to fill in asking for ip ranges and the github instructions does not state what i shud do, im really confused. i made a firewall rule but its still not working. 
im referring to this https://github.com/cdr/code-server/blob/master/doc/deploy.md

**Comment by Bapi-Reddy** [comment]
So I figured out the problem the issue seems to be on latest code server version 2.1692-vsc1.39.2
try the above version with port 8080
