### ISSUE TITLE
Where does code-server cache recent info?

### ISSUE THREAD

**Issue by pairwiserr** [cdr/code-server#1279]
I'm on a Ubuntu 16.04 machine using code-server binary. Even after shutting down the machine, code-server seems to remember which folders were open (which is a good thing). I'm wondering where code-server keeps this information so that I can clear it routinely.

**Comment by code-asher** [comment]
By default it'll be in ~/.local/share/code-server. It can be changed by
setting the XDG_DATA_HOME environment variable in case you want do that.

There's a `User` directory in there that stores what files are opened,
settings, snippets, and so on.
