### ISSUE TITLE
Running docker command 

### ISSUE THREAD

**Issue by LucaGabi** [cdr/code-server#1281]
## Description
When I run the provided docker command  I get this error:

error EACCES: permission denied, mkdir '/home/coder/.local/share/code-server/extensions'

Why ?

**Comment by decaby7e** [comment]
I get the same error running this. Here is my Docker run command:

`docker run -it -p 192.168.2.6:5040:8080 -v "/tmp/code-server:/home/coder/.local/share/code-server" -v "/tmp/code-server-project:/home/coder/project" codercom/code-server:v2`

**Comment by sr229** [comment]
Duplicate #403 

**AVOID** opening duplicate issues.
