### ISSUE TITLE
Remote - SSH extension doesn't work

### ISSUE THREAD

**Issue by qfettes** [cdr/code-server#1284]
- `code-server` version: 2.1698-vsc1.41.1
- OS Version: Debian GNU/Linux 9.11
- Extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh

## Description

Installing the latest version of the remote-ssh extension from microsoft results in the extension being grayed out and unusable (pictured) with the below error message:
> This extension cannot be enabled in the remote server

![Screenshot 2020-01-18 at 4 45 32 PM](https://user-images.githubusercontent.com/8574075/72670988-0cfdbf80-3a12-11ea-8ae1-917222c6479a.png)

I'm opening this issue because @sr229 suggested opening a new issue on issue #1155 if the extension did not work after testing.

## Steps to Reproduce

1. Download code-server
2. Download the latest version of the remote-ssh extension (currently 0.48.0)
3. Install the extension via the following command:
```
./code-server --install-extension ms-vscode-remote.remote-ssh-0.48.0.vsix 
```
4. Launch code-server and navigate to the extensions section

**Comment by sr229** [comment]
Dupe #1155

**Comment by qfettes** [comment]
It appears the issue you linked was closed without a resolution too @sr229

**Comment by sr229** [comment]
@qfettes We are not willing to provide support for closed-source extensions. Unless Microsoft opens up the sources for them, they will remain de facto unsupported.
