### ISSUE TITLE
How to put the password in the request url?

### ISSUE THREAD

**Issue by ladyrick** [cdr/code-server#1285]
For example, can I use http://127.0.0.1:8080/?password=balabala to login instead of input the password manually?

Jupyter notebook does it well: http://127.0.0.1:8080/?token=balabala

**Comment by sr229** [comment]
If I remember, we use `Authorization`.

**Comment by sr229** [comment]
We set the authentication via `Set-Cookie`. there's a value in there called `key=`. That's how we set your password in there. Look in your network requests under `/login`.

**Comment by ladyrick** [comment]
But set-cookie is not so convenient for user to open it directly.

**Comment by ladyrick** [comment]
> We set the authentication via `Set-Cookie`. there's a value in there called `key=`. That's how we set your password in there. Look in your network requests under `/login`.

I type the vscode-server url in address bar and open it.
After input the password, I can get access to it.

Then every time I open the url, password is not asked.

But, when I put the vscode-server url in a button
`<a href="http://10.20.30.40:9900" target="_blank">code-server</a>`
and click it to open vscode-server, the password is always required.

Why is that?

**Comment by ladyrick** [comment]
> > We set the authentication via `Set-Cookie`. there's a value in there called `key=`. That's how we set your password in there. Look in your network requests under `/login`.
> 
> I type the vscode-server url in address bar and open it.
> After input the password, I can get access to it.
> 
> Then every time I open the url, password is not asked.
> 
> But, when I put the vscode-server url in a button
> `<a href="http://10.20.30.40:9900" target="_blank">code-server</a>`
> and click it to open vscode-server, the password is always required.
> 
> Why is that?

Solved.
It is because `SameSite=strict`
