### ISSUE TITLE
containered or native gcc on server side root?

### ISSUE THREAD

**Issue by Cyper77** [cdr/code-server#1286]
first of all, sorry for this stupid question,
i want to understand clearly how it works, 

for my purpose; 
i want to write a linux C++ code with chrome on my w10 pc, 
target and code-server device is debian based armbian on rpi 3,
so, can i compile it with g++  and run-stop(not debug) on rpi3 **with a few vscode clicks** on w10 remotely?
if say yes, is it containered like a CHE (sandboxed-virtualized eg..) or full rooted ? 
i need to test my app on rpi3 also for rpi3 natively.
thanks advise..

**Comment by sr229** [comment]
Your code-server instance runs on where you put it, so if you run it bare metal, it'll run on bare metal, if its on Docker, it'll have only limited resources to request.

**Comment by Cyper77** [comment]
thank you for very fast response,
so if i write a rat code with this way, when i click a compile button and run, than server pc infected :/
