### ISSUE TITLE
vscode c&s plugin

### ISSUE THREAD

**Issue by Cyper77** [cdr/code-server#1288]
can you make a simple vscode plugin for editing code-server configuration files-parameters, after login we can change a lot of things on vscode. eg: 
usernames-passwords-ports-shutdown unwanted connected users-backround programs-server side top like process monitors-update core files for c&s without using yarn...... ;)

**Comment by nhooyr** [comment]
> shutdown unwanted connected users-backround programs-server side top like process monitors-update core files for c&s without using yarn...... ;)

Could you elaborate on these?

What does c&s mean?

**Comment by nhooyr** [comment]
After discussion with the team we're not going to move forward on adding this feature since we don't see the value it provides.
