### ISSUE TITLE
How to minimize the built binary file size?

### ISSUE THREAD

**Issue by ladyrick** [cdr/code-server#1289]
The binary file I download is about 40MB.

But the one I built is about 250MB.

How to lower the file size?

**Comment by code-asher** [comment]
The binary should actually be around 185MB. You might be looking at the
compressed archive.

When building you can set the `MINIFY` environment variable which should
decrease the size. For example:

MINIFY=true yarn build 1.41.1 daily

**Comment by sr229** [comment]
@code-asher which reminds me, I forgot that one small detail

*All the Drone builds are built with no minifcation >_<*

**Comment by code-asher** [comment]
Nah don't worry I added it. :)

https://github.com/cdr/code-server/blob/f51e045cd5483561afc07694f39307fb673b6d1d/scripts/ci.bash#L27-L31

**Comment by nhooyr** [comment]
This has been answered.
