### ISSUE TITLE
macOS completely locks up when trying to perform a search

### ISSUE THREAD

**Issue by JtMotoX** [cdr/code-server#1291]
- `code-server` version: 2.1698-vsc1.41.1
- OS Version: macOS Mojave (10.14.6)

## Description

System crashes/locks-up when performing search from search pane.
- Network connectivity goes down.
- Not pingable.
- Not reachable via ssh.
- Does not respond to mouse or keyboard input.

## Steps to Reproduce

1. Navigate to a fairly large directory tree or project
1. Open the search pane (CTRL+Shift+F / Command+Shift+F)
1. Type in something to search.
1. Within 5 seconds, my Mac completely locks up and the fan goes to 100%.  I am then forced to hold down the power button.

**Comment by sr229** [comment]
Pretty sure this might be a pervalent issue within VSCode as well.

**Comment by JtMotoX** [comment]
@sr229 I just tried performing a search locally and getting same results.  You are absolutely correct in that this issue is with VSCode.  I found another user with the same issue (https://github.com/microsoft/vscode/issues/88865) so I will be posting my results there.

**Comment by sr229** [comment]
Great! Keep us updated informed and we'll see when we can ship that fix out

**Comment by JtMotoX** [comment]
Thank you @sr229.  As you can see from my comments on the vscode issue linked above, I have confirmed that this issue only occurs on 1.40.  I will be downgrading to 1.39 until this issue is resolved.

**Comment by roshanpal** [comment]
I'm facing the exact same issue. I have a large meteor js project. When I try to search for something in the project, my MacBook pro freezes and the only way out is to restart.

**Comment by JtMotoX** [comment]
@roshanpal, can you please go to the link below and thumbs-up that issue and put your comment there?

https://github.com/microsoft/vscode/issues/88385

**Comment by roshanpal** [comment]
@JtMotoX Done
