### ISSUE TITLE
Allow direct access to files under a path

### ISSUE THREAD

**Issue by smhsketch** [cdr/code-server#1292]
I am trying to open an HTML file on my PC. code-server is being hosted on a spare PC. I can open and view the file just file in the cloud IDE, but I'm trying to view the HTML file as it would be shown on a website. I've tried navigating to "MYIPADDRESS:8080/home/MYUSERNAME/Projects/alarm-clock/index.html", but that doesn't work. It's probably a very obvious answer, but I haven't been able to find anything about it here.

**Comment by sr229** [comment]
There's some extensions that facilitate proxying so try those.

**Comment by nhooyr** [comment]
You'd need to setup a HTTP web server. I suppose we could handle this under another endpoint.
 
Thoughts @code-asher

**Comment by nhooyr** [comment]
I'll take care of this.

**Comment by nhooyr** [comment]
We should add an easy way to open files by right clicking as well.

**Comment by smhsketch** [comment]
thanks!

**Comment by code-asher** [comment]
I recently had to make changes to the `/static` endpoint which made it possible to get any file on the system as long as you're authenticated. For example you can use `http://<domain>/static/-/home/coder/project/index.html`. Just need to add the context menu option.

**Comment by nhooyr** [comment]
> context menu option.

wdym by this?

Can this issue not be closed?

**Comment by code-asher** [comment]
Ah I was referring to your comment:

> We should add an easy way to open files by right clicking as well.

Currently we don't have that context menu option.

**Comment by code-asher** [comment]
We could wrap that into https://github.com/cdr/code-server/issues/1386 though.

**Comment by nhooyr** [comment]
Moved it into https://github.com/cdr/code-server/issues/2179
