### ISSUE TITLE
Problems loading reference /extensions/typescript-language-features/schemas/tsconfig.schema.json':

### ISSUE THREAD

**Issue by talentlessguy** [cdr/code-server#1296]
- `code-server` version:  2.1698-vsc1.41.1
- OS Version: Manjaro Linux x64

## Description

When I load a typescript project (which uses `typescript-language-features`), I get this:
```
problems loading reference 'file:///drone/src/build/code-server2.1698-vsc1.41.1-linux-x86_64-built/extensions/typescript-language-features/schemas/tsconfig.schema.json': Unable to load schema from '/drone/src/build/code-server2.1698-vsc1.41.1-linux-x86_64-built/extensions/typescript-language-features/schemas/tsconfig.schema.json'
```

here's a screenshot;

![image](https://user-images.githubusercontent.com/35937217/73121273-8dc83880-3f89-11ea-829d-92d9defc94b0.png)

## Steps to Reproduce

1. Create a project with `yarn init -y`, then `tsc --init`
1. Go to `tsconfig.json` file and see an error

**Comment by nhooyr** [comment]
Will test soon and get back to you.

**Comment by nhooyr** [comment]
Confirmed.

**Comment by nhooyr** [comment]
Related: the static-f51e045cd5483561afc07694f39307fb673b6d1d/node_modules/vscode-textmate/release/main.js.map file doesn't load.

Its specified as the source map for the main.js file.

**Comment by kylecarbs** [comment]
Fixed with v3.
