### ISSUE TITLE
Disconnect WebSocket if user is idle for 1 hour

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1297]
See https://github.com/cdr/code-server/issues/1274#issuecomment-578611924

**Comment by antofthy** [comment]
Depends on what you mean by idle.

In our case idle is when the web socket is NOT being used, in which can we want to terminate the containing docker environment.   We do this by watching the "heartbeat" file.
https://github.com/cdr/code-server/issues/1050

**Comment by nhooyr** [comment]
So this is independent of the heartbeat file. I think if someone leaves code-server open on their desktop for like 6 hours but does nothing, we shouldn't keep the WebSocket up, we should just disconnect the WebSocket.

Disconnect just means drop the WebSocket.

**Comment by coadler** [comment]
Maybe we could make this an option?

`--idle-timeout=1h`

**Comment by antofthy** [comment]
As long as it is clear in the doc's.  Mind you I don't think the "heartbeat" file is documented either, except here in git "issues".

**Comment by nhooyr** [comment]
Yea we really need to document that.

**Comment by antofthy** [comment]
Even if the option was provided, it is more likely we will continue to use the heartbeat file, as we monitor it from outside the docker instance, and shutdown the docker instance completely when we reach our time out.  That is we need to do more than shutdown the wbe socket on timeout.

So just the heartbeat file needs to be documented.

**Comment by nhooyr** [comment]
Yea I agree, the websocket will disconnect naturally anyway since their computer will just go to sleep if they leave it on for an excessive amount of time.

**Comment by nhooyr** [comment]
It's documented now.

https://github.com/cdr/code-server/blob/9a3b9fcac23e6bd7f01e46bae94ea7c017bbc0f7/doc/FAQ.md#heartbeat-file
