### ISSUE TITLE
Vale prose linter issues

### ISSUE THREAD

**Issue by omfgnuts** [cdr/code-server#1298]
- `code-server` version: 1.41.1
- OS Version: ChromeOS / Linux (Debian Buster)
- Extension: https://github.com/testthedocs/vscode-vale / https://marketplace.visualstudio.com/items?itemName=testthedocs.vale

## Description

So, I happily moved from VS Code to code-server and my primary extension (Vale) doesn't work, I suspect it's due to some sandboxing issues, but I'm not sure. 

## Steps to Reproduce

1. Download Vale v 1.7.1 (https://github.com/errata-ai/vale/releases) 
1. Download code-server 1.41.1
1. Drop Microsoft latest StyleGuide (https://github.com/errata-ai/Microsoft/releases) somewhere. i.e /home/%username%/Work/ci/styleguide
1. Create .vale.ini i.e /home/%username%/Work
1. Enter following info there
 
```
# Don't point this config directly to Microsoft folder, point it one directory before
#, i.e your path to styleguide is ci/styles/Microsoft, point this config to ci/styles

StylesPath = path/to/styles/folder
MinAlertLevel = suggestion # suggestion, warning or error

# Only Markdown and .txt files; change to whatever you're using.
[*]

# List of styles to load.
BasedOnStyles = Microsoft
```

6. Create .md document and write there "- Knowledge of OOP;" (OOP should trigger a linting error)
7. Nothing works 🤷‍♂

**Comment by nhooyr** [comment]
> Nothing works 🤷‍♂

Could you please elaborate on what you mean? Does linting throw an error?

**Comment by omfgnuts** [comment]
Nope, no errors, it just doesn't lint anything (0 issues in both vscode and chrome dev tools)

I instantly tried regular vs code and it worked like a charm.

markdownlint, plantuml and other extensions work just perfect

**Comment by sr229** [comment]
Try relaunching the binary with verbose flag and send us the logs, thank you!

**Comment by nhooyr** [comment]
@omfgnuts 

I'll investigate this and let you know if I can get it to work.

**Comment by omfgnuts** [comment]
@nhooyr  Thank you! I really appreciate your efforts.

@sr229 Um, some magic just happened, I did literally (really, I did nothing) nothing besides launching code-server with --verbose, and all of a sudden Vale worked! I managed to take a screenshot as a proof for Vale Devs & you guys. After taking a screenshot I happily relaunched code-server just to find out that it stopped working again, bummer. So the issue is definitely still somewhere there.

As for logs, both --verbose or --log not showing anything (is there a specific place code-server saves the logs?)

**Comment by ChrisChinchilla** [comment]
Hey all, I maintain  the VSCode vale extension and am also looking  into this now, but I am not familiar with code-server, so will take some experimentation.

**Comment by ChrisChinchilla** [comment]
I'm not sure how you feed extensions into the custom extension marketplace, or which one @omfgnuts installed, but on n first inspection I see that when I search for Vale in the Code Server marketplace, the results return a completely different and very old extension, which even shows a depreciation warning.

<img width="1680" alt="Screen Shot 2020-02-02 at 17 43 09" src="https://user-images.githubusercontent.com/42080/73611607-c5fff480-45e3-11ea-90b9-911f3daed3aa.png">

**Comment by nhooyr** [comment]
Thank you for the response @ChrisChinchilla 

I'm gonna close this for #1299 which is the tracking issue to improve the extension scraping process.

**Comment by omfgnuts** [comment]
I've installed the latest .vsix manually, not from the built-in marketplace (as it's been specifically noted in my initial post), why close issue report? It's not yet clear how to make it work permanently, there's a solution for sure, as it worked a couple of times, we just need to find what made it functional.

**Comment by ChrisChinchilla** [comment]
Sorry didn't see anything in original report about installing VSIX file… I think this is still highly likely because of browser sandboxing but will investigate again when I have time

**Comment by sr229** [comment]
Reopened because of request.

**Comment by jdkato** [comment]
I followed the repro instructions on macOS (both via Docker and the binary) and I was able to get it working permanently (from what I can tell):

<p align="center">
 <img src="https://user-images.githubusercontent.com/8785025/73905173-4bd5a700-4853-11ea-966b-a0d1825fed2c.png" width="50%">
</p>

(Vale `v1.7.1` running on `code-server` via Docker.)

- When using the macOS binary, it worked out-of-the-box after I manually installed the extension.

- When using Docker, I had to copy a Linux build of Vale into my workspace (`${workspaceFolder}/bin`) and then update the `vscode-vale.path` setting to `${workspaceFolder}/bin/vale`.

I think the best first debugging step here is to determine the output of `which vale` in `code-server`'s terminal. If it's empty, you'll likely need to manually set the path as I had to do on Docker.

**Comment by omfgnuts** [comment]
```
omfgnuts@penguin:~/Work$ which vale
/usr/bin/vale
```

It's weird that it randomly works, but can't quite get WHY :(

**Comment by omfgnuts** [comment]
Does anyone have any ideas about how to debug this issue further?

**Comment by omfgnuts** [comment]
I'm glad that it worked for macOS, but I'm not on macOS; is there any debug option I can turn on, maybe I should strace-launch code-server?

**Comment by code-asher** [comment]
We have version 0.9.1 of the extension in our marketplace now. I tried it out and it shows warnings/errors in the problems panel but not in the file itself.

It's fixed in a PR: https://github.com/cdr/code-server/pull/1338 so hopefully we can get it merged soon and get out a new release.

**Comment by omfgnuts** [comment]
@code-asher I can't even express how grateful I am, thank you so much

**Comment by ChrisChinchilla** [comment]
@code-asher Great thanks! I'll try to remember to test future updates with code server too…
