### ISSUE TITLE
Live Server extension not loading

### ISSUE THREAD

**Issue by rogerabm** [cdr/code-server#1301]
I created a Docker droplet from the link in the readme. As I'm setting up everything I searched in the included extension marketplace for: "Live Server" \

I tried to launch with F1 > Live Server: Open with Live Server and there is an error notification: "command 'extension.liveServer.goOnline' not found"

Tried updated the settings.json with a custom port and my IP `{
    "liveServer.settings.port": 5500,
    "liveServer.settings.host": "x.x.x.",
}`

Also tried to download the VSIX but it says `Corrupt ZIP: end of central directory record signature not found`.

Thanks!

**Comment by nhooyr** [comment]
Confirmed. Related #1299
