### ISSUE TITLE
Switch to proper semantic versioning

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1303]
We were discussing and the current version numbers are confusing as the build number doesn't communicate much.

cc @kylecarbs 

Major would be big changes, minor for new features and patch for bug fixes.

**Comment by sr229** [comment]
I think we should also ditch the `-vsc-x.y.z` since it'll make it hard for automation software to cope up with latest releases. I think we can do that right now by editing the build script.

**Comment by kylecarbs** [comment]
I agree the build number doesn't say much
