### ISSUE TITLE
Get PATH from new shell

### ISSUE THREAD

**Issue by kylecarbs** [cdr/code-server#1305]
Users may leave code-server run in the background but make adjustments to their shell scripts for new env vars.

For example, `/snap/bin` wasn't added to my path when I started code-server then I added it later.

**Comment by nhooyr** [comment]
What if a user runs code-server with PATH=.

I think we leave it as is for now, even though it is unfortunate.

**Comment by kylecarbs** [comment]
That's much more of an edge-case then a user adding to the path. We should support the primary workflow.

We can check the value of the PATH var against one obtained from the shell on startup. If they are different, we can warn the user of setting a custom path or disable the feature entirely.

**Comment by nhooyr** [comment]
Yea with a warning it sounds great to me. I'm surprised VS Code does not do that by default.

**Comment by nhooyr** [comment]
I think we should leave this alone tbh.

I'd expect only changes made to my `~/.bashrc` be available in a new shell and require restarting, esp if I'm just testing something and made a mistake. Autoreloading feels like it'd be confusing behaviour and for marginal benefit. Maybe we can add a command that lets you reload the environment from a system shell?

**Comment by code-asher** [comment]
Is this in regards to the built-in terminal? I wonder if VS Code implemented this because I added a variable to my `.bashrc` then opened a new terminal and the new variable was there.

**Comment by nhooyr** [comment]
> then opened a new terminal and the new variable was there.

That would work because it'd source `.bashrc` on startup. But @kylecarbs is referring to plugins and the vscode process itself I believe.

**Comment by code-asher** [comment]
Ahh yeah OK that makes a lot more sense. We'd have to restart the VS Code and plugins right? And then we'd need some way of detecting when the PATH has changed like with some kind of polling loop.

**Comment by nhooyr** [comment]
> We'd have to restart the VS Code process and plugins right?

Perhaps when we get a new connection, we run the user's shell, print `$PATH` and change our `$PATH` to match and then communicate the change to the extension host.

**Comment by nhooyr** [comment]
The systemd service right now doesn't get any env vars from the user's shell iirc. So idk if doing this would break user expectations.

**Comment by code-asher** [comment]
Ah I see, a new connection naturally starts a new extension host so we
don't need to restart anything. That sounds like a very reasonable
implementation to me.

It definitely would be nice to get some data on what user expectations
around this are since I imagine there aren't many (or any?) things out
there that do this.
