### ISSUE TITLE
Publish free file releases

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1306]
nbin is complicated and has caused a significant issues and impedes debugging.

We should publish free file releases for every platform and on the docker container in particular we ought to just not release an nbin based release.

cc @kylecarbs

**Comment by nhooyr** [comment]
Related #529

**Comment by nhooyr** [comment]
So we're gonna start release debs/rpms

**Comment by nhooyr** [comment]
So the other issue here is windows support for nbin @kylecarbs

**Comment by nhooyr** [comment]
Another annoying problem is the file paths reported are those in CI instead of those on the user's computer, e.g. the typescript version bundled says its in /drone which is confusing.

**Comment by sr229** [comment]
AFAIK this is similar to pkg with their snapshot-based file system approach so I think we do save the path since its what the path was during build time.

**Comment by orditeck** [comment]
What impact would it have on how easy code-server is easy to upgrade/revert back to previous version?

Right now I download the new binary, exit the old process, run the new binary then check if everything works. If not, I just relaunch the old binary and plan time to look into what's wrong with the new one.

I'm just curious.

Thanks!

**Comment by nhooyr** [comment]
Should be just as easy, just have to `tar -xzf` first.

**Comment by orditeck** [comment]
Awesome, so same as right now. Thanks!

**Comment by nhooyr** [comment]
nbin def offers nothing, see https://github.com/cdr/code-server/releases

We distribute as zips/tars anyway lol @kylecarbs

**Comment by nhooyr** [comment]
We'll also need a Mac DMG and a windows installer.

**Comment by nhooyr** [comment]
We're only going to support linux moving forward. See #1332

**Comment by nhooyr** [comment]
We're going to add a multi platform installer.

**Comment by maxloh** [comment]
> We're only going to support linux moving forward. See #1332

Are we going to get Windows release or not?

**Comment by sr229** [comment]
Unfortunately, we're no longer considering Windows releases. We will be building exclusively for Linux from now on @maxloh.

**Comment by sr229** [comment]
> > We're only going to support linux moving forward. See #1332
> 
> Are we going to get Windows release or not?

Based on our CI support, we can't build Windows images, so there won't be a Windows-compatible tarball for your to use at the moment. I suggest using WSL instead to workaround this.

**Comment by nhooyr** [comment]
> Based on our CI support, we can't build Windows images, so there won't be a Windows-compatible tarball for your to use at the moment. I suggest using WSL instead to workaround this.

Please don't use `we` without consulting myself, @kylecarbs or @code-asher.

We will provide windows releases @maxloh with this issue.

**Comment by nhooyr** [comment]
@kylecarbs I don't believe this has been taken care of yet, we have no windows release for 3.0.

**Comment by kylecarbs** [comment]
I'm not sure we're ready to provide great support for Windows yet. None of us @cdr develop on Windows, so it feels like a risky thing to provide support. I feel like this issue should be closed with v3.0.0 released.

**Comment by nhooyr** [comment]
While I agree it's risky, I think the risk is minimal, especially considering how many times users have asked for it. It's super easy for us to run windows with parallels occasionally to test, we already have a yearly license. nbin was the only blocker for this anyway.

See https://github.com/cdr/code-server/issues/259

None of our code is platform specific anyway and VS Code itself supports windows. Same reason why I opted against abandoning Mac support. https://github.com/cdr/code-server/issues/1332

Also, we still need a .deb for linux and the npm package. I'll make new issues for those.

**Comment by nhooyr** [comment]
Opened a new issue tracking windows.
