### ISSUE TITLE
Fix Docker image issues regarding UID/GIDs

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1307]

**Comment by andylow** [comment]
Hope this fix can be release asap :)

**Comment by nhooyr** [comment]
This is done actually, forgot to close 😉

**Comment by andylow** [comment]
Wondering actually what fixes have been done? Any documentation to refer?
Because I use the latest docker image, still having the same permission issue with different uid/gid.

**Comment by nhooyr** [comment]
We should update the README.md to include the flags to forward uid/gid.

See https://github.com/cdr/code-server/blob/89d78a592161ee6d6e6a12c9ee9fe1c564fc16e4/ci/release-image/Dockerfile

fixuid will adjust all files in the container to whatever UID/GID the image was ran with so there should be no issues as long as you are running it with the right uid/gid but I'd imagine many users are just using the default which is uid 1000.

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/1425
