### ISSUE TITLE
Allow forwarding ports via URL

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1309]
https://github.com/cdr/code-server/issues/512

So like `localhost:8080/port/8080` to access port 8080 view HTTP.

**Comment by Rekrii** [comment]
Currently I do this via a reverse proxy (nginx or similar) on the host box to forward /8080 URL to :8080 the code-server instance, and then an nginx server in CS to host whatever the user (me) wants. Very neat and simple. Not sure how scaleable it is if you needed 10k+ ports. 

Comes down to if CS needs to be a swiss army knife of tools, or just a base IDE and you add stuff yourself (e.g. nginx as above).

**Comment by sr229** [comment]
I think we'll have a lot of benefits having a port forwarding proxy since its been a long overdue request by the community for us. Though I'd prefer we do it as a VS Code extension since its more suitable to do it in  VS Code's own APIs AFAIK.

**Comment by zpfei206** [comment]
@Rekrii Could you share the contents of the nginx.conf ? i am trounble on it now, Thans very much!

**Comment by Rekrii** [comment]
@zpfei206 Sorry I was on holiday. See below:

I use something simple like this in an nginx instance running in code-server:
`server {
       listen 8080;
       server_name my.domain.com;
       root /config/workspace/MyProjectHTMLFiles/;
       index index.html;
}`

On the nginx reverse proxy i use: 
`location /8080/ {
      proxy_pass http://localhost:8080/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
}`

Also ensure all SSL config is secure; ciphers, etc are good (I use Qualsys SSL Labs test). 

As i mentioned above, this won't scale too well into a large number of ports. But I use this to test/host different prototype projects I'm working on - normally say 10 or so, so i can manually do this port forward setup for such a small number.

**Comment by benz0li** [comment]
@Rekrii You might consider

```
location ~ /(\d+)/(.*) {
  proxy_pass http://localhost:$1/$2;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";
}
```

for general port forwarding.

**Comment by kylecarbs** [comment]
Fixed once https://github.com/cdr/code-server/pull/1453 is merged.

**Comment by benz0li** [comment]
Thanks for the great work on #1453.

I think `/p/<number>` would be preferable to `<number>.[domain]` as it remained compatibility running Code Server on Jupyter using [Jupyter Server Proxy](https://github.com/jupyterhub/jupyter-server-proxy).

**Comment by code-asher** [comment]
@benz0li Thanks! I didn't mention it in the PR but `/proxy/<number>` will also work.

**Comment by Rekrii** [comment]
@benz0li oh that's much cleaner - thanks!

**Comment by kylecarbs** [comment]
It's been merged 🎊
