### ISSUE TITLE
iPad: Korean input isn't combined properly

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1314]
See https://github.com/cdr/code-server/issues/1277

**Comment by nhooyr** [comment]
Only happens on iPad, works fine on my Mac.

**Comment by rightones** [comment]
Any updates here?

**Comment by code-asher** [comment]
@jsjoeio I'm curious if you're able to replicate this?

If it's still an issue we might be better off raising it upstream.

**Comment by jsjoeio** [comment]
@code-asher I will take this on and check

**Comment by jsjoeio** [comment]
Okay trying to reproduce here:

## Reproduce
1. Add Korean keyboard under General > Keyboard > Keyboards > Add New Keyboard > Korean
2. Open code-server 
3. Open file (e.g. markdown file)
4. Switch to Korean keyboard  
5. Start typing

**Comment by jsjoeio** [comment]
Opened an issue upstream ^

**Comment by jsjoeio** [comment]
Closing this since the issue has been captured upstream.
