### ISSUE TITLE
Safari: Extension details are not showing up

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1317]

**Comment by nhooyr** [comment]
<img width="955" alt="image" src="https://user-images.githubusercontent.com/10180857/73320305-7779e100-4204-11ea-84a0-ae75b7a75d57.png">

**Comment by nhooyr** [comment]
Works fine in Chrome.

**Comment by enesccinar** [comment]
+1 I am using the code-server as a pwa on the ipadOS (14.5-beta).
