### ISSUE TITLE
Extensions glitching in 2.1698-vsc1.41.1

### ISSUE THREAD

**Issue by EnKrypt** [cdr/code-server#1319]
This is an issue ONLY on release 2.1698-vsc1.41.1 (Works fine on the release prior which I have reverted back to).

Host running Arch Linux. Browser is Firefox.

On that release (currently latest) of code-server, some extensions work, some don't and some work only in certain conditions. For example, the Prettier extension does not work. If I attempt to format a js file, it complains that there is no available formatter for 'javascript' files.
The spellchecker version works in the Problems tab, but it does not highlight in the actual editor.
..and so on.

This could be an issue with upstream, and potentially related to #1317

**Comment by orditeck** [comment]
[intelephense](https://github.com/bmewburn/vscode-intelephense) also doesn't work. I reverted back to 2.1692-vsc1.39.2 until this is resolved.

**Comment by nhooyr** [comment]
Just tested latest docker and seems to work fine for me.

If this is still a problem, please feel free to reopen.
