### ISSUE TITLE
error EEXIST: file already exists, mkdir

### ISSUE THREAD

**Issue by sthulb** [cdr/code-server#1321]
- `code-server` version: 2.1698-vsc1.41.1
- OS Version: Ubuntu Server 18.04 LTS

```
ubuntu@ip-10-0-220-250:~$ code-server
error EEXIST: file already exists, mkdir
ubuntu@ip-10-0-220-250:~$
```

## Steps to Reproduce
1. create t3.large EC2 instance with Ubuntu Server 18.04 LTS
1. install code-server binary from GitHub release
1. start code-server

**Comment by nhooyr** [comment]
Just tested and works fine for me. See #1331
