### ISSUE TITLE
Upvote this issue in upstream to enable upstream extension integration

### ISSUE THREAD

**Issue by frank-dspeed** [cdr/code-server#1322]
I want that the vscode-remote installer gets exposed including extension installer for the remote dir this can then be used by this also so plz upvote if you care for better extension managment and if you want to support my effort to get this current functionality exposed in the upstream repo.

https://github.com/microsoft/vscode/issues/89762

**Comment by nhooyr** [comment]
Will leave this open to get attention on the upstream issue.
