### ISSUE TITLE
Open browser failed!! Please check if you have installed the browser  correctly!

### ISSUE THREAD

**Issue by OvenVan** [cdr/code-server#1323]
## Description
I have installed the <b>OPEN IN BROWSER</b> extension and want to test my <b>html</b> files. but I failed. It shows : <b>Open browser failed!! Please check if you have installed the browser  correctly!</b> I am sure I have installed the browser correctly, because it works well in local VSCode. 

Could AnyOne tell me how I can test my html files?

**Comment by nhooyr** [comment]
See #1331

**Comment by nhooyr** [comment]
code-server runs remotely so this can't work.

**Comment by nhooyr** [comment]
See #1292

**Comment by septianhari** [comment]
> code-server runs remotely so this can't work.

how to turn off the remote remote?

**Comment by jsjoeio** [comment]
@septianhari not sure what you mean but feel free to open a Q and A discussion!
