### ISSUE TITLE
Mapping SSL Certs in docker fails with error EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by NarkedDiver** [cdr/code-server#1324]
## Description

I am running this docker command

docker run -it -p 8888:8080 -v path/to/certs/cert.crt:/home/coder/certs/cert.crt codercom/code-server --cert /home/coder/certs/cert.crt

and I get the error message

error EISDIR: illegal operation on a directory, read

I have removed the --cert command and the container starts correctly and when I go into bash in the container I can see cert.crt and doing ls -l gives

drwxrwxrwx 2 coder coder 4096 Feb  1 03:46 cert.crt

so I'm not sure what the error is (other than a typo by me ;) )

**Comment by nhooyr** [comment]
See #1331
