### ISSUE TITLE
'Go to definition' is not working at C/C++

### ISSUE THREAD

**Issue by zed654** [cdr/code-server#1328]
When I run the exe code(.code-server) as non-sudo, the option of 'Go to definition' not working. But, when I run it as sudo, 'Go to definition' is working well but cannot set the password by writting on the bashrc(export PASSWORD='aaa').

(OS - Ubuntu 18.04/16.04)
could you help me?

**Comment by sr229** [comment]
Sounds like a bug to me. You should be allowed to use go to definition in usermode.

**Comment by nhooyr** [comment]
As far as I can tell, this is a permissions issue, not a bug with code-server.

**Comment by nhooyr** [comment]
We need a better spot for questions.

**Comment by nhooyr** [comment]
https://github.com/cdr/code-server/issues/1331

**Comment by zed654** [comment]
Thanks you, I solved this problem.
At the path of '~/.local/share/code-server', I granted permission by using 'sudo chmod 777 -R'
(sudo chmod 777 -R ~/.local/share/code-server)

**Comment by Ambrodu** [comment]
Gave all the permissions. Doesn't work. This is a code server issue.

**Comment by jsjoeio** [comment]
Hmm...I'm not sure what would be causing this. We'd have to dig in.
