### ISSUE TITLE
Disable insecure access notification

### ISSUE THREAD

**Issue by MGerasimchuk** [cdr/code-server#1329]
## Description

Hello, in https://github.com/cdr/code-server/commit/1474a82c7dafd64a1c7181f18dfec2a9e119f3ae commit was added insecure notification. This notification very noisy for my case, I see this notification every time after the page refresh. 

How can I disable this?

**Comment by sr229** [comment]
Unfortunately there's no way to disable this unless the client side detects you're in a secure domain (TLS/SSL-enabled origin). You'll need to have HTTP/S enabled.

**Comment by nhooyr** [comment]
> Hello, in 1474a82 commit was added insecure notification. This notification very noisy for my case, I see this notification every time after the page refresh.

Please describe your use case.

**Comment by MGerasimchuk** [comment]
> > Hello, in [1474a82](https://github.com/cdr/code-server/commit/1474a82c7dafd64a1c7181f18dfec2a9e119f3ae) commit was added insecure notification. This notification very noisy for my case, I see this notification every time after the page refresh.
> 
> Please describe your use case.

My platform allows creating a virtual server with preinstalled VSCode Cloud IDE(code-server). Every virtual server has a public domain and accessible by http protocol. These virtual servers can be created and delete for 100 or more times per 24 hours. Now I use the http protocol for my case, and a secure issue(https) is not important for my platform. And also I use the old version of cloud-server(2.1692-vsc1.39.2) because this version has not insecure notification for every code-server page opening.
If I will refactor my platform and will using https for my case, then I will catch the next problems:
1. I will have to generate new letsencrypt cert for every new virtual server - this will complicate and slow down the process of creating the environment
2. Letsencrypt has a limit in 50 certificates per week(https://letsencrypt.org/docs/rate-limits), and because of this, my platform is limited to this rule.
3. If I will choose way with https, I won't chance for scaling my platform in the future(see p.1 and  p.2).

**Comment by sr229** [comment]
> > > Hello, in [1474a82](https://github.com/cdr/code-server/commit/1474a82c7dafd64a1c7181f18dfec2a9e119f3ae) commit was added insecure notification. This notification very noisy for my case, I see this notification every time after the page refresh.
> > 
> > 
> > Please describe your use case.
> 
> My platform allows creating a virtual server with preinstalled VSCode Cloud IDE(code-server). Every virtual server has a public domain and accessible by http protocol. These virtual servers can be created and delete for 100 or more times per 24 hours. Now I use the http protocol for my case, and a secure issue(https) is not important for my platform. And also I use the old version of cloud-server(2.1692-vsc1.39.2) because this version has not insecure notification for every code-server page opening.
> If I will refactor my platform and will using https for my case, then I will catch the next problems:
> 
> 1. I will have to generate new letsencrypt cert for every new virtual server - this will complicate and slow down the process of creating the environment
> 2. Letsencrypt has a limit in 50 certificates per week(https://letsencrypt.org/docs/rate-limits), and because of this, my platform is limited to this rule.
> 3. If I will choose way with https, I won't chance for scaling my platform in the future(see p.1 and  p.2).

Based on your response, this is what I can think of a solution for your platform:

- the new version forces HTTP/S since we have Clipboard API being used and Workers extensively, which came native with VSCode. To prevent issuing too much certificates, just have your IDEs run a subdomain over a LE-secured [Wildcard domain](https://medium.com/@saurabh6790/generate-wildcard-ssl-certificate-using-lets-encrypt-certbot-273e432794d7).
    -  This is how Red Hat does theirs over at OpenShift SaaS, I think you can leverage that since its the only way you can have all the origins secure. Not sure how you designed your platform but this is one way to do it.

- Have a option for your platform to use TLS. You don't need to force it if people don't want it, but since we run workers mainly in VS Code the IDE has to require secure context to work 100%.

**Comment by MGerasimchuk** [comment]
> > > > Hello, in [1474a82](https://github.com/cdr/code-server/commit/1474a82c7dafd64a1c7181f18dfec2a9e119f3ae) commit was added insecure notification. This notification very noisy for my case, I see this notification every time after the page refresh.
> > > 
> > > 
> > > Please describe your use case.
> > 
> > 
> > My platform allows creating a virtual server with preinstalled VSCode Cloud IDE(code-server). Every virtual server has a public domain and accessible by http protocol. These virtual servers can be created and delete for 100 or more times per 24 hours. Now I use the http protocol for my case, and a secure issue(https) is not important for my platform. And also I use the old version of cloud-server(2.1692-vsc1.39.2) because this version has not insecure notification for every code-server page opening.
> > If I will refactor my platform and will using https for my case, then I will catch the next problems:
> > 
> > 1. I will have to generate new letsencrypt cert for every new virtual server - this will complicate and slow down the process of creating the environment
> > 2. Letsencrypt has a limit in 50 certificates per week(https://letsencrypt.org/docs/rate-limits), and because of this, my platform is limited to this rule.
> > 3. If I will choose way with https, I won't chance for scaling my platform in the future(see p.1 and  p.2).
> 
> Based on your response, this is what I can think of a solution for your platform:
> 
> * the new version forces HTTP/S since we have Clipboard API being used and Workers extensively, which came native with VSCode. To prevent issuing too much certificates, just have your IDEs run a subdomain over a LE-secured [Wildcard domain](https://medium.com/@saurabh6790/generate-wildcard-ssl-certificate-using-lets-encrypt-certbot-273e432794d7).
>   
>   * This is how Red Hat does theirs over at OpenShift SaaS, I think you can leverage that since its the only way you can have all the origins secure. Not sure how you designed your platform but this is one way to do it.
> * Have a option for your platform to use TLS. You don't need to force it if people don't want it, but since we run workers mainly in VS Code the IDE has to require secure context to work 100%.
>   
>   * If this really needs to be done on a seperate domain, give the user the option to use a wildcard domain in P1 or provide a limited amount of custom domains for them only.

Thanks for your details about Clipboard API and Workers. Now I understand why, https need for vscode and code-server..
And thank you for your suggestion connected with letsencrypt. I will try to refactor my logic connected with the environment creating and I will try based code-server on domains with https protocol.
