### ISSUE TITLE
Cannot find module 'iconv-lite'

### ISSUE THREAD

**Issue by superzhangzl** [cdr/code-server#1330]
- `code-server` version: 1.39.2 and 1.41.1
- OS Version: ubuntu18.04

## Description

add extension  'gbktoutf8', can not use

## Steps to Reproduce
![火星图片_20200203_173419](https://user-images.githubusercontent.com/19573210/73642311-75a09980-46ac-11ea-970d-b9fc56ac8629.jpg)

**Comment by sr229** [comment]
Go to the offending extension's folder and run `npm install`. We think its a faulty build that causes this partially built extensions.

**Comment by superzhangzl** [comment]
i will try it.
but did you know another way to support GBK?
thanks

**Comment by superzhangzl** [comment]
> Go to the offending extension's folder and run npm install. 
it works

**Comment by sr229** [comment]
Thank you, I will close this for now, this will do at the moment until we try to fix the scraper.

**Comment by superzhangzl** [comment]
> but did you know another way to support GBK?

What about this question?did you have a good idea？

like this：
![impicture_20200203_220607](https://user-images.githubusercontent.com/19573210/73659547-713aa780-46d1-11ea-9550-7baa2d10f293.png)

GBK not support
