### ISSUE TITLE
Remove Mac support

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1332]
No one really uses it.

**Comment by sr229** [comment]
I'll start decommissioning the config file later.

**Comment by mrzzheng** [comment]
Hey, I'm sure there are people still using the macOS version, like me.

**Comment by sr229** [comment]
> Hey, I'm sure there are people still using the macOS version, like me.

I think we determined only a small amount of users using the macOS version. Since it doesn't have that large of a demand, you can just build your own moving forward.

**Comment by nhooyr** [comment]
@mrzzheng Do you run code-server on a Mac server and access it from a device or do you run code-server on a linux server and access it from a Mac? The second will still work.

**Comment by nhooyr** [comment]
Going to leave support in until the next major version. See https://github.com/cdr/code-server/pull/1336

**Comment by mrzzheng** [comment]
> @mrzzheng Do you run code-server on a Mac server and access it from a device or do you run code-server on a linux server and access it from a Mac? The second will still work.

Run on a Mac. If building myself, which one is recommended, this or vs code official with yarn; yarn web? What's the difference?

**Comment by nhooyr** [comment]
@mrzzheng Going to add to #1333

**Comment by nhooyr** [comment]
`yarn web` is useless at the moment, only provides a UI you can access without the backend for files/extensions.

**Comment by nhooyr** [comment]
It'll become super easy to support with #1306 so closing. We will keep support moving forward.
