### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1333]
- Security recommendations
- User namespacing
- Bruteforce protection
- Port forwarding
- Docker UID/GIDs
- SSH and GPG forwarding
- Multi tenancy

**Comment by mirsella** [comment]
Hello, i was wondering : 
why using code oss and not [vscodium](https://github.com/VSCodium/vscodium) as a base ? what are the difference between the two ?
I read in #30 that code-server use a tricky way of retrieving extensions from closed microsoft repo ?
how [vscodium](https://github.com/VSCodium/vscodium) retrieve the extensions ? i surely did not understand, so please explain to me. 
i wanted to install : 
https://marketplace.visualstudio.com/items?itemName=softwaredotcom.swdc-vscode
https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode
and there are not in the code-server search engine, and i could not find the .VSIX

thanks

**Comment by nhooyr** [comment]
- vscode-web vs code-server

**Comment by nhooyr** [comment]
> why using code oss and not vscodium as a base ? what are the difference between the two ?

They are the exact same source, just released differently. https://github.com/VSCodium/vscodium#why
