### ISSUE TITLE
window.restoreWindows

### ISSUE THREAD

**Issue by T1mron** [cdr/code-server#1344]
How to set “window.restoreWindows“ in vs settings?  I want to auto reopen files/folders when i launch vs.

**Comment by nhooyr** [comment]
Should be the same as vscode.

**Comment by KaKi87** [comment]
Hi,

I'm looking for this setting too, and it's not there.

Here's VSCodium :

<img width="700" height="199" alt="Image" src="https://github.com/user-attachments/assets/7e3cabd2-abfe-4678-acf4-28bd4efe60a9" />

But here's code-server :

<img width="767" height="240" alt="Image" src="https://github.com/user-attachments/assets/2d41f0d1-9124-4bf7-a073-5722f919f16d" />

Thanks

**Comment by code-asher** [comment]
It does not seem to be available on Codespaces either, so my guess is that it is not supported in web.

Ah yup only declared in the Electron version: https://github.com/microsoft/vscode/blob/ac4cbdf48759c7d8c3eb91ffe6bb04316e263c57/src/vs/workbench/electron-browser/desktop.contribution.ts#L178-L191

**Comment by KaKi87** [comment]
Then I'd like to request the ability to disable the behavior of code-server that automatically reopens the last open project when it hasn't been closed before the browser tab was closed.

Thanks

**Comment by KaKi87** [comment]
Hello,

Any news on this please ?

Thanks

**Comment by code-asher** [comment]
Does `--ignore-last-opened` do what you want?  I believe it should make code-server always open an empty window.

**Comment by KaKi87** [comment]
Indeed, thanks. It would be nice if the GUI setting could do the exact same thing without having to edit the server-side start script ?

**Comment by code-asher** [comment]
True, but it would be a bit awkward; the code-server wrapper that handles this flag is not aware of VS Code and has no access to the API, so we would have to write code to interact with VS Code's settings separately.  Right now there is a clean separation between the two, the wrapper just executes VS Code with certain arguments, so doing that would be a bit of an architectural shift.

**Comment by code-asher** [comment]
I suppose we could implement it completely separately in VS Code as a patch and then deprecate `--ignore-last-opened` rather than trying to combine them though.  But I am not sure this is worth maintaining a patch, it seems more like something that should be committed upstream.

**Comment by KaKi87** [comment]
> this flag is not aware of VS Code and has no access to the API

How about a separate `code-server`-specific settings page then ?

Cause there are tons of feature requests that would benefit from that anyway.

> it seems more like something that should be committed upstream

I hate this sentence 😭

Microsoft does not care about users of code-server, only you care, please take this in consideration when handling feature requests.

**Comment by code-asher** [comment]
> Cause there are tons of feature requests that would benefit from that anyway.

I think the only tricky thing here would be to make it discoverable.  We could put a link on the login page, but not everyone uses built-in auth.  We could print a link to the terminal during startup maybe.

One possibly clever way we could do this is to implement the settings using a built-in plugin.  That would let us integrate with VS Code settings without having to maintain any patches.  The plugin could update code-server's `config.json` and then send a signal to code-server to re-read the settings.

A built-in plugin might let us do some other things that we currently do via patches as well, like check for code-server updates, and maybe some others.

> Microsoft does not care about users of code-server, only you care, please take this in consideration when handling feature requests.

I do appreciate that, but my only goal with code-server is to wrap VS Code and make it more friendly to self-host and remove any proprietary components.  Anything beyond that is outside what I can promise to deliver or maintain.  The main thing I want to avoid is diverging and ending up with a fork of VS Code.
