### ISSUE TITLE
Editor panes not refreshing properly

### ISSUE THREAD

**Issue by fonnesbeck** [cdr/code-server#1345]
- `code-server` version: 2.1698-vsc1.41.1
- OS Version: Debian 9

## Description

Running code-server with multiple panes results in screen artifacts from past output that do not disappear:

![image](https://user-images.githubusercontent.com/81476/73960372-61d57d00-48d0-11ea-91ea-0d5b8416f57e.png)

This example is from running SQL queries, with the mssql plugin. Some of the previous output, originally in the right panel, is now showing in the corner of the left panel.

**Comment by kylecarbs** [comment]
Is this still an issue with v3?

**Comment by fonnesbeck** [comment]
Haven't seen it, no.

**Comment by nhooyr** [comment]
awesome
