### ISSUE TITLE
Opens Recent workspace on new session instead of specified workspace

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#1350]
```
Version: 1.41.1
Commit: f51e045cd5483561afc07694f39307fb673b6d1d
Date: 2020-01-17T22:58:55.612Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Code Server Version: 2.1698-vsc1.41.1
```
- Host: Archlinux

## Description
When you start code-server, you can tell it to open a folder, this works well
the problem is when you change your active folder, and come in on a completely new device/setup, it will open the new folder instead of the specified one
## Steps to Reproduce
1. `code-server /workspace`
2. open code-server in browser and change active workspace
3. close browser and come back later, 
4. code-server will open the new workspace instead of the one it is told to have opened in the first place. 

## Thoughts
I have looked and currently there are no work arounds that i can find at this moment as the only possible workaround i have found, i dont know how to do just yet and that is to 
1. set `"window.restoreWindows": "none",` in settings.json
2. make an extension that gets the current workspace path, if null or matches the default one code-server tells it, change folder to the wanted workspace

but again i dont know how to do this just yet and the idea wouldnt even work since code-server returns this when i try and use that config
![image](https://user-images.githubusercontent.com/10422110/74180679-cc4e2c00-4bf4-11ea-9e10-6dffa6064b56.png)

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/1132

**Comment by Merith-TK** [comment]
last reply to this thread you suggested was literally back in november,

**Comment by nhooyr** [comment]
Please comment on there instead of reopening another.

**Comment by Merith-TK** [comment]
alright
i shall just copy/paste this 

and i couldnt find that thread due to its name being totally confusing

**Comment by nhooyr** [comment]
Yea feel free to copy and paste or link to. this thread. I'll rename it.
