### ISSUE TITLE
tomcat and svn extension can‘t run

### ISSUE THREAD

**Issue by qv1256** [cdr/code-server#1352]
- `code-server` version: 
- OS Version: 
- Extension: 

## Description

after i instal tomcat and SVN extension,when run there are "command "tomcat.server.add" not fund"。
## Steps to Reproduce

1. 
installed tomcat and SVN extension。
1. 
To configure them，it will report errors “command not fund”

**Comment by nhooyr** [comment]
See #1299 

It's a bug in the scraper at the moment, is being actively worked on.
