### ISSUE TITLE
Reconnecting Issue

### ISSUE THREAD

**Issue by SyedGhazanferAnwar** [cdr/code-server#1353]
- `code-server` version: <Every Version>
- OS Version: Ubuntu 18.04

## Description

Hello, when I try to connect with code-server it shows the following error. Then automatically reconnects and work fine for 3-5 mins. After the error pop's up again.The frequency of error is quite often like every 5 minutes . 
The error is as follows:

**Attempting to reconnect**
Snippet attached below.

![Capture](https://user-images.githubusercontent.com/39636624/74275689-31f60180-4d36-11ea-8506-93b08834e15f.PNG)

**Comment by nhooyr** [comment]
This is due to your connection dropping for some reason. Can you monitor the network tab to see if the connection is being dropped?

**Comment by nhooyr** [comment]
Closing as unlikely to be a bug in code-server.
