### ISSUE TITLE
Update to readme?

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#1354]
So basically this is an update to the readme that i am requestion, 
first, nitpicking
1. update gif to match new ui

Others
1. Extensions need to be mentioned that some extensions need you to `cd ${extensionDir}/extension` and then `npm install` them in order to work properly for some weird reason, (i have had to do this with the golang extension)
i have made a bash script for this
```bash
#!/bin/bash

for dir in *; do
        if [[ -d $dir ]]; then
                pushd $dir
                npm install 
                popd
        fi
done
```
2. Elaborate on the "custom extensions" Why you guys have done this? what benefits are there rather than using the code-oss bindings stuff for the store? as far as i know everything is compatible

**Comment by nhooyr** [comment]
See #1014 regarding pt 1

The second issue is being dealt with as part of #1299 

The last point is going to be handled tomorrow in #1333

**Comment by nhooyr** [comment]
Appreciate you looking out!

**Comment by Merith-TK** [comment]
No worries! I enjoy using this software as my windows pc is now appearntly too crap to even run vscode. Or have a vscode startup time under 5 minutes. So I run this on my Dev server and access it over lan
