### ISSUE TITLE
Directly open github repo through repo link

### ISSUE THREAD

**Issue by JalinWang** [cdr/code-server#1355]
I'm very fond of [Gitpod](https://www.gitpod.io/), which supports opening a GitHub repo by prefixing any public GitHub or GitLab URL with gitpod.io/# in the browser. 
e.g.: [https://www.gitpod.io/#https://github.com/cdr/code-server](https://www.gitpod.io/#https://github.com/cdr/code-server)

I want to add this feature to this project but have no idea how and where to start.
My initial thought is to add a rule to the URL parser in the patch, once the URL matched, execute "git clone" and then open.
But later I realized this feature requires git, would it be better to implement this feature as an extension? If yes, use UriHandler API?
or any other better solution?

**Comment by code-asher** [comment]
This would be cool. I don't think we'd need to patch anything to get it working. Maybe if the `?folder` parameter is something like `git://github.com/cdr/code-server` URL we clone before starting VS Code. We need to fix #1294 first though.

**Comment by JalinWang** [comment]
Is it a good way to execute "git clone" in  server.preHandleRequest() and then modify MainServer.handleRequest() to call getRoot() with proper path?
P.S.:
class server and class MainServer are the ones in https://github.com/cdr/code-server/blob/master/src/node/server.ts

**Comment by code-asher** [comment]
Hmm, it might make sense to do this right after the call to
`getFirstValidPath`. You can do the clone then change `startPath` to the
directory of the clone.

**Comment by dougnukem** [comment]
Sail by coder supports this use case with the browser extension:
- https://github.com/cdr/sail
- https://sail.dev/docs/browser-extension/

**Comment by kylecarbs** [comment]
Closing for now.

We don't have immediate plans for this within code-server.
