### ISSUE TITLE
[Question] How to connect 'code-server' running in docker?

### ISSUE THREAD

**Issue by SarbojitAMD** [cdr/code-server#1356]
- `code-server` version: Latest version I have taken from here
- OS Version: Ubuntu 18 / 16 ( both did not work)

## Description
I am trying to remote access my Linux box from windows 10. I have Ubuntu Linux Box where I am running a docker image, inside the docker I have downloaded my source code and making changes. Now I want to debug the source inside the docker. I have launched code-server there but I am not able to connect it from my windows 10 system. 

If I run code-server outside the docker it works absolutely fine but inside docker some how I am not able to connect. Any suggestion with be a great help.

**Comment by nhooyr** [comment]
This isn't a bug, see #1331 

I'd recommend reading the docker docs about port forwarding.

**Comment by SarbojitAMD** [comment]
@nhooyr , can you point me to the docker docs that you are referring?

**Comment by nhooyr** [comment]
https://docs.docker.com/config/containers/container-networking/
