### ISSUE TITLE
browser tab dead when opening minimized js file

### ISSUE THREAD

**Issue by lab4quant** [cdr/code-server#1358]
- `code-server` version: code-server2.1698-vsc1.41.1-darwin-x86_64
- OS Version: MacOS

## Description

i accidently clicked a minimized js file when using code server, then my browser tab went dead

I tried turn off `minimap` and `word wrap` option, it's the same

## Steps to Reproduce

1. open code-server with a project that has minimized js file, say `jQuery.min.js`
2. open `jQuery.min.js`

**Comment by kylecarbs** [comment]
I've done this multiple times without issue. Please try on v3!
