### ISSUE TITLE
Can't install extensions through CLI

### ISSUE THREAD

**Issue by sstone1** [cdr/code-server#1364]
- `code-server` version: codercom/code-server:2.1698
- OS Version: Docker

## Description

I can't install any extensions using the CLI:

```
$ code-server --install-extension redhat.vscode-xml
Installing extensions...
Extension 'redhat.vscode-xml' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-vscode.csharp
error undefined
$ code-server --install-extension ms-vscode.csharp
Installing extensions...
Extension 'ms-vscode.csharp' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-vscode.csharp
error undefined

```

I was able to do this earlier today (morning time GMT).

## Steps to Reproduce

1. 
1.

**Comment by nhooyr** [comment]
@kylecarbs I believe this is related to the new extension marketplace deployment.

**Comment by kylecarbs** [comment]
It is. Investigating now.

**Comment by kylecarbs** [comment]
Pushed a new version of the extension marketplace.

Confirmed to be fixed!

**Comment by rabidpug** [comment]
@kylecarbs some extensions still can't be installed via CLI, even if they're available in the UI, eg:
![image](https://user-images.githubusercontent.com/27880212/74892094-c4547000-53dc-11ea-8a3f-651694bc6d9b.png)

**Comment by kylecarbs** [comment]
Hm will check it out. Thanks!

**Comment by kylecarbs** [comment]
Ah there's a case sensitivity issue. Will fix.

Try: `code-server --install-extension MaxGotovkin.tslens`

**Comment by rabidpug** [comment]
Looks like it changes it to all lowercase:
![image](https://user-images.githubusercontent.com/27880212/74892566-177af280-53de-11ea-82f6-32550689f34d.png)

**Comment by kylecarbs** [comment]
Yup. Will fix!

**Comment by kylecarbs** [comment]
Fixed 🎊

**Comment by sstone1** [comment]
@kylecarbs thanks for the fixes and updates - I've had luck installing most of the extensions we install through the CLI, but for some reason `vscjava.vscode-java-pack` (https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) is no longer available. Any ideas?

**Comment by kylecarbs** [comment]
I'll take a look!

**Comment by kylecarbs** [comment]
Found the problem. That Java pack was failing to build with our extension marketplace. Fixing now.

**Comment by ozboss** [comment]
Still seems to be an issue:

![image](https://user-images.githubusercontent.com/32305849/78162435-2924d080-7447-11ea-997b-d71350a10c1d.png)
