### ISSUE TITLE
Ctrl keyboard shortcuts not working with vim extension

### ISSUE THREAD

**Issue by benny-v** [cdr/code-server#1365]
- `code-server` version: 2.1698-vsc1.41.1
- OS Version: Ubuntu 18.04, Digital Ocean
- Extension: [vim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)

## Description

After installing the vim extension, keyboard shortcuts with the modifier key `ctrl` (`ctrl + F` `ctrl + O`) don't work when the editor is in focus. Shortcuts with multiple modifier keys like `ctrl + shift` (`ctrl + shift + F`) still work, just not single `ctrl` shortcuts.

## Steps to Reproduce

1. Install  [vim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) extension.
2. Attempt any shortcuts with the the `ctrl` modifier key.

**Comment by ryan-allen** [comment]
Hey mate, I had the same problem. I think the browser hijacks this and will not send the keypresses to the app. I don't think there is any work around if you're working directly in the browser.

My solution was to use Chrome/Edge 'save this page as website' and it created an app, which does capture the keys required for the vim extension.

Hope that helps!

**Comment by benny-v** [comment]
![image](https://user-images.githubusercontent.com/25658680/74980753-29fc3700-5485-11ea-92f0-c9299e6ed86e.png)

After digging through the extension settings. I solved the problem by unchecking this setting. Whether this will cause other problems, I am unsure of yet. It did solve this problem though.

Hope it helps any other vim junkies that come across this in the future!
