### ISSUE TITLE
Extension Support: SynthWave '84

### ISSUE THREAD

**Issue by mediocre-code** [cdr/code-server#1366]
Extension: https://marketplace.visualstudio.com/items?itemName=RobbOwen.synthwave-vscode

Just wondering if this extension could get added to the code-server marketplace.  As of version v0.1.0 it no longer requires the Custom CSS and JS extension.

**Comment by kylecarbs** [comment]
Added!

**Comment by mediocre-code** [comment]
Thanks @kylecarbs!

**Comment by stevewongv** [comment]
@dat-mediocre-data Can you enable the glow effect in the code-server?

**Comment by hmmhmmhm** [comment]
@dat-mediocre-data 
can you also add it this one?
https://marketplace.visualstudio.com/items?itemName=webrender.synthwave-x-fluoromachine

**Comment by jsjoeio** [comment]
We're not adding new extensions at this time. Please use Open VSX @hmmhmmhm
