### ISSUE TITLE
Add extra extensions into custom repository

### ISSUE THREAD

**Issue by olylak** [cdr/code-server#1367]
Could you please add the following extensions from official marketplace to your own one?

- ESPHome VSCode plugin - https://marketplace.visualstudio.com/items?itemName=ESPHome.esphome-vscode
- Home Assistant Config Helper - https://marketplace.visualstudio.com/items?itemName=keesschollaart.vscode-home-assistant
- Material Design Icons Intellisense - https://marketplace.visualstudio.com/items?itemName=lukas-tr.materialdesignicons-intellisense

Thanks in advance!

**Comment by kylecarbs** [comment]
All have been added!
