### ISSUE TITLE
Terraform extension disappeared

### ISSUE THREAD

**Issue by scarolan** [cdr/code-server#1368]
- `code-server` version:

```
code-server --version
info  2.1698-vsc1.41.1
info  f51e045cd5483561afc07694f39307fb673b6d1d
info  x64
```

- OS Version: 
```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
```

- Extension: 

https://github.com/mauve/vscode-terraform

## Description

This was working just yesterday and then it disappeared from the Extensions.

## Steps to Reproduce

1. Spin up code server
2. Click the extensions icon
3. Search for "Terraform", normally this one's top of the list:

https://github.com/mauve/vscode-terraform

**Comment by scarolan** [comment]
Incidentally, is there a way to install a vsix extension into code-server from the command line?

**Comment by kylecarbs** [comment]
Working on this right now. I've found the issue.

**Comment by kylecarbs** [comment]
Fixed!

**Comment by scarolan** [comment]
Thank you!  We use code-server in our training workshops at HashiCorp, so this is a huge help.

**Comment by jonasbark** [comment]
Sorry to hijack this issue - has anyone been able to run terraform commands with this extension?
E.g. when I run a command from the Command Palette, e.g. Terraform: Lint it displays the following error:
```Command 'Terraform: Lint' resulted in an error (command 'terraform.lint' not found)```

**Comment by nhooyr** [comment]
@jonasbark Please file a new issue!
