### ISSUE TITLE
Multi-factor authentication using external services

### ISSUE THREAD

**Issue by gasq40** [cdr/code-server#1369]
It will be great if we could use some external authentication system such as Auth0 to perform multi factor authentication. The present password only system could be improved.

**Comment by nhooyr** [comment]
A reverse proxy is the best way to handle this. We want to avoid the additional complexity in code-server itself.

See https://github.com/pusher/oauth2_proxy for example.

I'll add to FAQ

**Comment by nhooyr** [comment]
@kylecarbs Please add to FAQ in #1338
