### ISSUE TITLE
CORS blocking requests to extension market.

### ISSUE THREAD

**Issue by xFlowe** [cdr/code-server#1370]
Hi guys.

I successfully installed code-server on my centos 8 host. For additional security I installed a nginx proxy with basic auth.
Everything works fine except the extension-market. 
![grafik](https://user-images.githubusercontent.com/23379913/75145575-7b146100-56f9-11ea-843e-1b19b5a01b1c.png)

It seems that cors is blocking my requests to https://v1.extapi.coder.com/extensionquery.
Console output from firefox:
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://v1.extapi.coder.com/extensionquery. (Reason: CORS request did not succeed)`

I also tried to set the `Access-Control-Allow-Origin` to `*` on my proxy but unfortunately with no success.

Greetings

**Comment by xFlowe** [comment]
I also investigated a new error, when i tried to update code-server.

![grafik](https://user-images.githubusercontent.com/23379913/75147042-b4020500-56fc-11ea-8d52-1ddcf2ae4fce.png)

Maybe the cors error belongs to this?

**Comment by kylecarbs** [comment]
Hm. Do you have redirects enabled? We'll be releasing a new version of code-server with the updated marketplace URL, but for the meantime:

Set the environment variable:
```
export SERVICE_URL=https://extensions.coder.com/api
```

Should fix the issue!

**Comment by SpinningK** [comment]
> Hm. Do you have redirects enabled? We'll be releasing a new version of code-server with the updated marketplace URL, but for the meantime set the environment variable:
> 
> ```
> export SERVICE_URL=https://extensions.coder.com/api
> ```
> 
> Should fix the issue!

Should the site "https://extensions.coder.com/api" return a 404 code? I set it to the environment variable. It's seems that CORS warning disappeared, but nothing changed to my extension market(maybe due to the 404 code). My extension list is always incomplete. For example, if I search "go",  there will be no extension for "golang" but for "Django". Hope you can fix this issue by next version.

**Comment by kylecarbs** [comment]
It'll return a 404 for `/api` on a GET request.

Hm. Searching "go" returns the Golang extension as the first response for me.

Is something caching the request?

**Comment by mlwkshops** [comment]
Is there documentation available for the api? 

- How to get a list of available extensions?
- How to search for a specific extension?

**Comment by code-asher** [comment]
I don't believe we currently have any documentation about it. I think the only way to get a handle on it is to read the source and/or inspect the browser network calls.
