### ISSUE TITLE
Question: code-server VS Code Remote Development

### ISSUE THREAD

**Issue by infokiller** [cdr/code-server#1371]
Hi,

I'm trying to improve my remote dev setup and came across this project. I'm trying to understand the differences between this project and [VS Code Remote Development](https://code.visualstudio.com/docs/remote/remote-overview).
 
In the README, you mention two pros:

> - **Consistent environment**: Code on your Chromebook, tablet, and laptop with a consistent dev environment. develop more easily for Linux if you have a Windows or Mac, and pick up where you left off when switching workstations.
> - **Server-powered**: Take advantage of large cloud servers to speed up tests, compilations, downloads, and more. Preserve battery life when you're on the go since all intensive computation runs on your server.

Here's my current understanding of the pros/cons of each project (where "VSCRD" is a shorthand for "VS Code Remote Development"):

- VSCRD covers "server powered" equally well
- VSCRD covers "consistent environment" almost equally well: when switching a client device, there will be consistency in the remote environment, but the local VSCode settings won't be consistent (though it's no really hard to solve by syncing the VSCode config between client devices).
- The VSCRD extensions are not OSS, while this project is
- VSCRD runs a regular VSCode UI, which means: 
  - It's possible to use keybindings like <kbd>Ctrl-W</kbd>, while code-server runs as a regular website, and hence has some limitations
  - The UI will be responsive, since everything runs locally. I assume this is not the case for code-server?

Is my understanding correct? Am I missing something?

Thanks in advance!

**Comment by kylecarbs** [comment]
Heyhey! Happy to elaborate.

Your assumptions on similarity are mostly correct. Few key differences:

- `code-server` provides a [PWA](https://developers.google.com/web/progressive-web-apps), which lets you open in a native app window. This allows for keybinds like `Ctrl-W`.
- `code-server` runs the UI on the client-side, making it feel equally responsive as VS Code natively.
- `code-server` only requires a browser. There is no installation on the client-side.
- `code-server` is open source, and MIT licensed. You can mutate the source in any way you'd like with your remote experience.

More is elaborated on in our `restructure` branch. Reading the updated FAQ [here](https://github.com/cdr/code-server/blob/25288b1afd3d2463425f22e839579982a23beb7d/doc/FAQ.md) may help shine some light.

Happy to expand on any questions/ideas/thoughts here. Closing for now.

**Comment by infokiller** [comment]
Thanks a lot, that's very useful!

**Comment by sortedcord** [comment]
Hi, sorry for piggybacking this but are there any major differences between code-server and VSCRD? The only difference that I can see as of now is that I can connect to the tunnel using a client instance of vscode and offload the compiling, and code-editing processes to the server similar to jetbrains' space while the client is rendering the UI, other than that I cannot see a major difference between VSCRD and code-server. So in what use cases should I prefer one over the other from a development standpoint?
