### ISSUE TITLE
Demo code server on a public cloud

### ISSUE THREAD

**Issue by jan-janssen** [cdr/code-server#1372]
I really like the code server project. But it seems to me that many new users would like to play around with it, before downloading. In the scientific community https://mybinder.org is becoming the go-to solution to demonstrate new software. So I gave it a shot and installed code server on mybinder: 
https://mybinder.org/v2/gh/jan-janssen/code-server-example/master?urlpath=nbvscode

The corresponding source code is available at: 
https://github.com/jan-janssen/code-server-example

I guess one could think about a few example projects to demonstrate the abilities of code-server. If that sounds interesting to you, I would be happy to contribute. 
Best regards, 

Jan

**Comment by kylecarbs** [comment]
Hey Jan, I know you closed this but happy to give my take.

We want to have a deep focus on enterprise, and would prefer for consumers of our OSS to try it on their servers. Hosting gets into a weird spot of us managing users files, and secrets.

It's something we may explore in the future, but have on pause for the immediate.
