### ISSUE TITLE
Lost all extensions from marketplace

### ISSUE THREAD

**Issue by lujo777** [cdr/code-server#1373]
- `code-server` version: latest from docker
- OS Version: 

## Description

Lost all extensions from marketplace

**Comment by nhooyr** [comment]
What do you mean you lost all extensions?

**Comment by lujo777** [comment]
I mean there is no extensions found and there is no popular. I tried to find python in marketplace

**Comment by kylecarbs** [comment]
My extensions are working.

Try setting the following environment variable before starting code-server:
```
SERVICE_URL=https://extensions.coder.com/api
```

**Comment by kylecarbs** [comment]
Closing for now. Let us know if this solves your problem!
