### ISSUE TITLE
Is there a way to remove sudo privileges from 'coder' user?

### ISSUE THREAD

**Issue by harsh-m8** [cdr/code-server#1375]
I learned about this project yesterday, it's amazing and exactly what I was looking for!

I plan to give access to my code-server to a freelancer that I haven't worked with in the past, so I'm wondering if there is a way to remove sudo privileges from 'coder' user?  
All that person is going to do is edit the code and run a few commands in the terminal.

**Comment by kylecarbs** [comment]
`code-server` doesn't need sudo privileges to run.

You can run `code-server` outside of the Docker container in a restricted user so they can still code!

Closing for now, but happy to elaborate!

**Comment by chriseizus** [comment]
@kylecarbs can you elaborate what you mean by running outside the container.
I need to run code-server using docker container, but want to disable the sudo privilege inside the docker or is there any way to customize removing sudo privilege for "coder"?

**Comment by demyxco** [comment]
@chriseizus I think @harsh-m8 wants to remove the file `/etc/sudoers.d/nopasswd`. This file is responsible for the coder user to use any sudo commands without a password.

**Comment by kylecarbs** [comment]
@chriseizus code-server can run inside or outside a container, with or without sudo privileges.

**Comment by demyxco** [comment]
@kylecarbs oh sorry, I am always in Docker mode. My statement was for the Docker image.
