### ISSUE TITLE
darwin cannot connect Extensions marketplace cause of CORS

### ISSUE THREAD

**Issue by tces1** [cdr/code-server#1382]
I raise code-server in MACOS, the website works well, but cannot connect the extensions marketplace, the console logs show below.

Access to XMLHttpRequest at 'https://v1.extapi.coder.com/extensionquery' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

I think this is a CORS error, can you help me?

**Comment by tces1** [comment]
Close, search the issues i found this, and it works on me
`export SERVICE_URL=https://extensions.coder.com/api`

**Comment by kylecarbs** [comment]
@tces1 this will be automatically fixed in the latest version of code-server releasing soon. Happy you found the solution!
