### ISSUE TITLE
PWA installability: service-worker not found

### ISSUE THREAD

**Issue by diegosucaria** [cdr/code-server#1383]
Hi!

I'm trying to get this installed as a PWA. I have nginx reverse proxy set. a valid SSL cert. it is serving at https://subdomain.domain.com

I'm also running code-server with valid cert and cert-key paths

Nginx reverse proxy is set to https://127.0.0.1:8080

Everything works fine, except, I can't install the PWA:

![image](https://user-images.githubusercontent.com/4278322/75676227-99351080-5c67-11ea-8a95-b58e394e1de9.png)

Service worker seems to be there:
![image](https://user-images.githubusercontent.com/4278322/75676330-c71a5500-5c67-11ea-85e0-a21a29f45941.png)

Any ideas??   thanks!

**Comment by kylecarbs** [comment]
Fixed in the latest refactor coming soon with v3.

PR here: https://github.com/cdr/code-server/pull/1338

I'll post once we have the fix in a public release!
