### ISSUE TITLE
Drag & Drop download params double encoded

### ISSUE THREAD

**Issue by ggongaware** [cdr/code-server#1385]
- `code-server` version: 2.1698-vsc1.41.1 x84_64
- OS Version: Amazon Linux

## Description

Drag and Drop file from Browser to Desktop yield 404 error In chrome from MacOS.

Path query parameters are double escaped, and rejected with a 404.

I captured traffic packets to see the root cause:
-----
```
 GET /vscode-remote-resource?path%3D%252Fhome%252Fec2-user%252Ftm-xx%252Flogs%252F2020-02-01-xx.log.gz%26tkn%3D HTTP/1.1
 Host: xxx
 Connection: keep-alive
 Referer: xxx/?folder=vscode-remote%3A%2F%2Fxx%3A8080%2Fhome%2Fec2-user%2Ftm-xx
 User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
 Accept-Encoding: gzip, deflate
 Accept-Language: en-US,en;q=0.9,es;q=0.8
 Cookie: key=xxx

 HTTP/1.1 404 Not Found
 Date: Tue, 03 Mar 2020 16:56:55 GMT
 Connection: keep-alive
 Transfer-Encoding: chunked
```
-----

Manually fixed with a curl request for testing:

```
curl -v "http://xxx/vscode-remote-resource?path=%2Fhome%2Fec2-user%2Ftm-xx%2Flogs%2F2020-02-01-xx.log.gz&tkn="

HTTP/1.1 200 OK
Content-Type: text/plain
Date: Tue, 03 Mar 2020 17:02:00 GMT
Connection: keep-alive
Transfer-Encoding: chunked
```
## Steps to Reproduce

1.  Drag file out
2. Observe empty file error

**Comment by kylecarbs** [comment]
We don't currently have functionality for downloading files.

Will add!

**Comment by kylecarbs** [comment]
Tracking here: https://github.com/cdr/code-server/issues/1386
