### ISSUE TITLE
Allow file downloads

### ISSUE THREAD

**Issue by kylecarbs** [cdr/code-server#1386]
Should be able to drag-and-drop from the file browser to my local machine.

**Comment by rubysown** [comment]
Having an option to disable this downloading feature would be nice as well when it is added - I know for example the industry I'm in (financial data) wouldn't want this allowed.

**Comment by nhooyr** [comment]
@rubysown couldn't someone just copy and paste the file?

**Comment by rubysown** [comment]
@nhooyr Yes. That might be easy for small files but not large ones. It's just a suggestion from a real-world scenario I've had to deal with, that's all.

**Comment by tonystarkdo** [comment]
need this function

**Comment by kylecarbs** [comment]
https://github.com/microsoft/vscode/issues/93599 is tackling this.

**Comment by nhooyr** [comment]
Also somewhat related is #1292

**Comment by blaylockbk** [comment]
In another similar server app, JupyterLab (https://jupyter.org/), you can drag and drop a file from local to the remote directory, but you can't drag a file from the remote to local (just like in code-server). **However**, JupyterLab does have an option to download a file from the right-click context menu. Not sure how they do that, but it would be nice if this was in vscode.
![image](https://user-images.githubusercontent.com/6249613/94304625-b5124380-ff24-11ea-8b15-ff9dd34ca11c.png)

**Comment by sr229** [comment]
This seems to be in the works for the upstream side IIRC, might be worth a look.

**Comment by woshiniming007** [comment]
@nhooyr It seems the VSCode 1.51 version has added the function:

https://code.visualstudio.com/updates/v1_51#_download-folders-edge-chrome

**Comment by code-asher** [comment]
1.51.1 has been merged and this'll be released with 3.7.2.

**Comment by lsc196** [comment]
> Having an option to disable this downloading feature would be nice as well when it is added - I know for example the industry I'm in (financial data) wouldn't want this allowed.

i think need this feature

**Comment by lsc196** [comment]
Having an option to disable this downloading feature would be nice as well when it is added . I know for example the industry I'm in (IT) wouldn't want this allowed. Improve code security

**Comment by code-asher** [comment]
@lsc196 I opened https://github.com/cdr/code-server/issues/2426 to address this.
