### ISSUE TITLE
[3.0.0] Multiple error regarding files (no icon, no autocomplete, no syntax syntax highlighting)

### ISSUE THREAD

**Issue by orditeck** [cdr/code-server#1387]
Hi,

Thanks for the new release! I was looking forward to it so I promptly upgraded. 
I noticed some issues:

1. The icons next to the files [are not displayed anymore](https://user-images.githubusercontent.com/2186535/75925354-8fadd300-5e36-11ea-8f9a-297076fc3f29.png) in the File Explorer
2. Autocomplete doesn't work
3. Auto file type detection doesn't work
4. Syntax highlighting doesn't work

I disabled all installed extensions.

I'm also getting this error:
```
[remoteagent] [error] [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
```

System:
```
➜  / uname -a
Linux code 4.15.18-18-pve #1 SMP PVE 4.15.18-44 (Wed, 03 Jul 2019 11:19:13 +0200) x86_64 x86_64 x86_64 GNU/Linux
➜  / lsb_release -a  
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

I'm running code-server using:
```
/root/code-server-3.0.0-linux-x86_64/code-server --auth none --host 0.0.0.0
```

And accessing code-server via http://ip:8080

**Comment by kylecarbs** [comment]
Do you have any fetching errors in your network tab for the icons? Are you using any icon extensions?

**Comment by orditeck** [comment]
@kylecarbs No and no

**Comment by orditeck** [comment]
PHP files (and JS file, and pretty sure any file at this point) are detected as plain text:
![image](https://user-images.githubusercontent.com/2186535/75926355-6726d880-5e38-11ea-810d-03e79a4726e0.png)

Setting it to PHP [doesn't activate syntax highlighting](https://user-images.githubusercontent.com/2186535/75926407-802f8980-5e38-11ea-9886-1727cba7b9ec.png)

**Comment by orditeck** [comment]
I disabled all my extensions just to make sure none of them were causing my problem.

The Language Mode has pretty much all languages missing:
![image](https://user-images.githubusercontent.com/2186535/75926901-4f038900-5e39-11ea-82a6-42558fc9e007.png)

**Comment by kylecarbs** [comment]
Oof super weird. I'll download 3.0.0 and see if I can see the same thing.

**Comment by orditeck** [comment]
Maybe there was some errors in the latest building process that have gone undetected, I'm subscribed to new releases alert so I upgraded right away hehe

**Comment by kylecarbs** [comment]
Fixing this now, yea that's definitely what happened. Thanks!

**Comment by orditeck** [comment]
Awesome. Thank you!

**Comment by code-asher** [comment]
Looks like a bad cache; rebuilding now.

**Comment by code-asher** [comment]
CI has completed the build. :tada:

**Comment by orditeck** [comment]
Works perfectly. Thanks!

**Comment by Abhid14** [comment]
Sorry to let you know here that on 3.0.1 latest I am unable to use any of the features like autocomplete and extensions they fail even html formatting is not working even after installing extensions.

**Comment by nhooyr** [comment]
@Abhid14 Please open a new issue.
