### ISSUE TITLE
v3.0.0 -- it changes directory!

### ISSUE THREAD

**Issue by antofthy** [cdr/code-server#1388]
Testing out pre-release 3.0.0

New start up script changes directory.  That means it is no long er running in the users home directory and it does not automatically open that directory on startup.

**Comment by antofthy** [comment]
**Solution...**

Change the "code-server" start up to remove the "cd"...
```bash
bundle_dir="$(dirname "$(readlink -f "$0" || realpath "$0")")" || exit 1
"$bundle_dir"/code-server-*/node  "$bundle_dir"/code-server-*/out/node/entry.js "$@"
```

This way the current directory is preserved, and code server finds and opens the users current folder and file edits...  (even those from v2)

If you have your own startup script, you can code bundle_dir as appropriate.

**Comment by kylecarbs** [comment]
Wouldn't opening the current PWD be expected?

**Comment by antofthy** [comment]
Except the current PWD is changed by the "code-server" start script!
Which is what my suggested change fixes.

However when another user tried testing the setup with the change (not forgetting the current PWD) his code-server also the starting directory (no open folder).  So looks like v3 remembers it once it is set, but does not remember what it was when you used v2.

So my change may not have done anything to fix the problem...  The default working directory of a user.   Looks like I may have to set that as part of the launch command line, and use a 'clean' user to test.

**Comment by kylecarbs** [comment]
Ah I understand what you're saying. Will fix.

Thanks for reporting!

cc: @code-asher

**Comment by antofthy** [comment]
Yes it would be what is expected... But it doesn't if the user has never used v3 before.
Once they have opened a folder.  code-server v3 seems to remember it in some .local configuration file.

I have added $HOME on the command line to currently fix the problem for users who have not used v3 yet.  (New or comming from v2).

At the moment v3 is only in testing docker images, and not being used by our students.

**Comment by code-asher** [comment]
Thanks for finding this!

v2 won't open a directory if v2 had never been used before either (I just ran 2.1698 to double-check). It's possible an earlier version of v2 did; I don't quite remember when we changed that behavior.

**Comment by code-asher** [comment]
Oh except it should still pull from the same configuration file so if it existed in v2 it's supposed to still use that last known directory. v3 does have a different behavior though because it will always prefer a directory passed on the command line if it exists.

**Comment by antofthy** [comment]
Well I am now passing the directory

**Comment by antofthy** [comment]
I would also recommend you add an "exec" in front of the command so the shell script the user ran is actually replaced by the "node" process.   Saves one extra process.
```bash
exec "$dir/node" "$dir/out/node/entry.js" "$@"
```
I am doing this directly in my own start up script (for docker), so it does not matter to me.

**Comment by code-asher** [comment]
Thanks, that's a great idea.
