### ISSUE TITLE
v3.0.0 node is bundled

### ISSUE THREAD

**Issue by antofthy** [cdr/code-server#1389]
Nodejs is now bundled with code-server.

The docker instance we are using already have node installed, and code-server use that, and remove the nodejs bundle?

**Comment by kylecarbs** [comment]
code-server may require a specific version of node in the future, so we don't have support for this at the moment.

Previous versions also contained a version of node, just packaged inside the single binary.

Closing for now, but happy to elaborate if you're interested!

**Comment by antofthy** [comment]
Okay, understood...  Just would be nice for making smaller docker image, to not duplicate it.

**Comment by nhooyr** [comment]
At some point we might add an non package which would install code-server for the node version you’re using.
