### ISSUE TITLE
Can't build changing the icons

### ISSUE THREAD

**Issue by diegosucaria** [cdr/code-server#1390]
I'm trying to build code-server 3.0.0 with the original vscode icon...

If I build directly, the code-server icon is maintained. So...

I've replaced the icons in code-server/src/browser/media/

I've staged the changes, run yarn vscode:diff to create a new patch. Then run yarn vscode but it fails.
it complains that the path src/browser/media does not exists.
So, I created code-server/lib/vscode/src/browser/media and now the diff patch complains that the file contents are different...

I've tried many other combinations...  (like creating a patch file using --binary but it didn't work either)

Do you have any ideas of what is the correct process to change the icons and build again?

Thanks!

**Comment by kylecarbs** [comment]
When you extract code-server, you should be able to replace `src/browser/media/pwa-icon-*.png` and when you reinstall the PWA your icons should be updated.

LMK if this doesn't work, happy to help!

**Comment by diegosucaria** [comment]
You were right. Simply changing the icons on the already built package worked. No need to rebuild.

Thank you very much!

**Comment by diegosucaria** [comment]
Hi there! the method of replacing the icons at `src/browser/media/pwa-icon-*.png` doesn't work anymore with version 4.1.0

Any ideas why?

**Comment by jsjoeio** [comment]
What version did you upgrade from?

`src/browser` no longer exists at the root so that cold be it. It looks like it's now looking at `   {{BASE}}/_static/src/browser/media/pwa-icon-${size}.png` - does that help?

**Comment by diegosucaria** [comment]
Hi! thanks for the answer.
I still see `src/browser/media` with the icons under the root of code-server-4.1.0-linux-amd64.tar.gz 

What do you consider it to be {{BASE}} in your answer?

**Comment by jsjoeio** [comment]
> I still see src/browser/media with the icons under the root of code-server-4.1.0-linux-amd64.tar.gz

Ah! Sorry, I meant to say it no longer exists in the `code-server` repo (I think we were overwriting those same files inside `vscode`).

> What do you consider it to be {{BASE}} in your answer?

The base URL that servers code-server i.e. `http://localhost:8080`. This is so they work with reverse proxies and other setups.

**Comment by diegosucaria** [comment]
So the only way to change the icons is to rebuild code-server right?

**Comment by jsjoeio** [comment]
Hooray! Glad you got it working.
