### ISSUE TITLE
Add HashiCorp Sentinel syntax highlighter

### ISSUE THREAD

**Issue by rberlind** [cdr/code-server#1393]
Could you add https://marketplace.visualstudio.com/items?itemName=hashicorp-sentinel.sentinel to the list of extensions discoverable from inside this tool?

**Comment by kylecarbs** [comment]
Adding now.

**Comment by kylecarbs** [comment]
Added!

**Comment by rberlind** [comment]
Awesome.  Thanks @kylecarbs

**Comment by rberlind** [comment]
However, when I tried installing it into my local VCScode editor, I got this message:
"Unable to install 'hashicorp-sentinel.sentinel' extension because it is not compatible with the current version of VS Code (version 1.41.1)"

Would that be because it is only available in newer versions based on how you added it?  or because of the version that the author (one of my co-workers) used when building it?

**Comment by kylecarbs** [comment]
Seems like it has a minimum version requirement: https://github.com/glenngillen/vscode-sentinel/blob/master/package.json#L9

Try using the latest v3.0.0 prerelease, and you should be good!

**Comment by rberlind** [comment]
My colleague who created the extension changed the min version to 1.41.0.  My lab environment is using 1.41.1, but I still see the same warning.  Is it possible that you need to add his extension back after he modified it so that it will allow 1.41.0?

**Comment by kylecarbs** [comment]
Yup! I'll try updating it now.

**Comment by kylecarbs** [comment]
Just re-added it. Should be good to go!

**Comment by rberlind** [comment]
That did the trick.  Thanks so much @kylecarbs 
By the way, I live in a neighborhood in Westchester, NY with a Carberry family.  wonder if you're related to them?

**Comment by kylecarbs** [comment]
Haha unlikely. I'm from Saskatchewan, Canada and so is most of my family (to my knowledge). 😄
