### ISSUE TITLE
Select operation (Shift + Arrow key) problem in console

### ISSUE THREAD

**Issue by Yattazemonsei** [cdr/code-server#1394]
Shift + Arrow(select operation) does not work normally.

**Comment by kylecarbs** [comment]
Not sure exactly what you mean.

Do you mean Shift+Arrows in the terminal?

**Comment by nhooyr** [comment]
Just tested and seems to work fine for me in the output console.

**Comment by nhooyr** [comment]
Please do comment though if that's not what you meant.
