### ISSUE TITLE
Error: Jupyter server crashed

### ISSUE THREAD

**Issue by puneethrj** [cdr/code-server#1398]
I'm running code server on ec2 instance ad using port forwarding to open it on my local browser. I am using anaconda environment where jupyter is already installed. 
Python extension is installed. However when i try to run code as a cell using the inbuilt jupyter functionality the python interactive shell fails to start with the following error. 

Jupyter notebook failed to launch. Error: Jupyter server crashed. Unable to connect. Error code from jupyter: 0 [I 16:45:15.493 NotebookApp] The port 8895 is already in use, trying another port. [I 16:45:15.496 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1 [I 16:45:15.497 NotebookApp] [nb_conda] enabled [C 16:45:15.497 NotebookApp] Running as root is not recommended. Use --allow-root to bypass. Failed to run jupyter as observable with args notebook --no-browser --notebook-dir=/tmp/27c1cbe4-3e6a-4258-be97-a8c260a4e4d4 --config=/tmp/27c1cbe4-3e6a-4258-be97-a8c260a4e4d4/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0

I can run the run jupyter notebook from the integrated terminal and it initializes without an issue. 
Is there a way to modify jupyter specific configuration in python extension? It seems like jupyter doesnt have appropriate permission to start.

**Comment by kylecarbs** [comment]
Do you have something else running on port 8895?

**Comment by puneethrj** [comment]
Jupyter server goes through several ports before it finds one that is free. That's how the jupyter notebook ran on the terminal too, though I have to use "jupyter notebook --allow-root " . 
So to conclude main issue seems to be " Use --allow-root to bypass".
Even when I run it in the integrated terminal without "--allow-root ", it fails to start
example output as follows:
The port 8891 is already in use, trying another port.
The port 8892 is already in use, trying another port.
[nb_conda] enabled
Running as root is not recommended. Use --allow-root to bypass.

**Comment by kylecarbs** [comment]
Ah. Is this issue fixed then?

**Comment by puneethrj** [comment]
Its not fixed, I cant access jupyter server functionality through python extension in code server. It seems like code server is running with root permissions and python extension is not starting jupyter server with appropriate permission.

**Comment by kylecarbs** [comment]
How are you running code-server? You don't need to run as root.

**Comment by puneethrj** [comment]
I start code-server with sudo ./code-server. As is suggested in many online articles.
The resulting vscode interface is such that the integrated terminal is also in root.
When I try it without sudo, the python extension had issue starting.

**Comment by code-asher** [comment]
I think you should be able to uncheck `Use default config for Jupyter` in the VS Code settings, then provide your own configuration that contains `c.NotebookApp.allow_root = True`.

What errors did you see when running code-server without root?

**Comment by puneethrj** [comment]
I did the following:
opened command pallete and searched for "settings."
it showed me the option "Open user settings"
![image](https://user-images.githubusercontent.com/13819936/76624676-c0d78300-655b-11ea-8515-a59506455142.png)

Here I found I could change options for User, Remote and workspace. 
I unticked the option "Use default config for Jupyter" for User, remote and workspace

I didnt not get any option to add my own settings except for in remote 
![image](https://user-images.githubusercontent.com/13819936/76624844-0dbb5980-655c-11ea-9c31-560beede96aa.png)
After selecting "Edit setting in JSON", I added `c.NotebookApp.allow_root = True`
![image](https://user-images.githubusercontent.com/13819936/76624991-583cd600-655c-11ea-9afa-f9a0ceb6b5af.png)

I restarted the code server. But still ran into the same error.
I also tried to edit "defaultsettings.json" but it was not editable.
I do not know how to acces the setting.json files of User and workspace.


> What errors did you see when running code-server without root?

I started the code server without sudo. It ran this time. Earlier it used to throw error which sounded like "python extension couldn't start". 
Even if the code server started without error. When I tried to run a jupyter file it does nothing. When I try to open a new jupyter notebook it open up an "Untiitled" file but I can't edit it.

**Comment by code-asher** [comment]
I'm not super familiar with Jupyter but you'd need to to add that
setting to Jupyter's configuration, not VS Code's. This might help:

https://jupyter-notebook.readthedocs.io/en/stable/config.html

I'm going to try Jupyter locally and see if I run into the same issues
with non-root that you are.

**Comment by code-asher** [comment]
Hm, I haven't had any luck replicating the issue without root. Are all
the files and directories you're trying to edit/open owned by the user?

**Comment by puneethrj** [comment]
** Update
I started code server with sudo and tried the following.
I figured out I can change the jupyter notebook settings too. so I located the jupyter notebook config.py file and added the ` c.NotebookApp.allow_root = True` .
The behavior now is like what I mentioned in the previous post. Jupyter server seemed to start, it is asking me the password but after I enter the password it does nothing.

**Comment by code-asher** [comment]
I tested on a remote server and for me it works without a password but once I add a password it fails to connect. Locally everything works fine. :confused:
