### ISSUE TITLE
Jupyter notebooks not rendered with Python extension in code-server3

### ISSUE THREAD

**Issue by fonnesbeck** [cdr/code-server#1405]
I'm running code-server-3.0.0-linux-x86_64, using the Python extension. Having moved from code-server2, I noticed that .ipynb files are no longer rendered after the upgrade. They simply appear as JSON. However, the file language selection is set to "Jupyter", so it looks like the file type is recognized.

I have tried uninstalling and reinstalling the extension, and reloading, but this does not correct the issue.

**Comment by kylecarbs** [comment]
Seems to work for me.

Could you open the console and check for errors? And ss there any way you could post the `.ipynb` file you're using?

**Comment by puneethrj** [comment]
> does
@fonnesbeck 
if you open .py file (or create new)
attach `#%%` to a block of code you get to run it like a cell as shown below.
![image](https://user-images.githubusercontent.com/13819936/76241383-e2362780-625a-11ea-8764-98dcd91904eb.png)

If you get an error "Jupyter server crashed " our issues might be related.

**Comment by fonnesbeck** [comment]
OK, interesting. When I open a new notebook and several other existing notebooks, it works fine. But, for that particular notebook it does not work. Not sure why, as the notebook runs fine in a traditional JupyterLab session. I will see if there are others that do this as well, or if there is something unusual about this one. I can confirm that it worked fine under v2, as I was working on it all of last week under the previous version.

**Comment by kylecarbs** [comment]
Hm very strange. Is it a VS Code-version specific issue? Closing in favor of https://github.com/cdr/code-server/issues/1398 for now.
