### ISSUE TITLE
Markdown preview doesn't work

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1409]
https://github.com/cdr/code-server/issues/296#issuecomment-597781316

**Comment by nhooyr** [comment]
Seems to be an iframe issue https://github.com/cdr/code-server/issues/296#issuecomment-597786909

Maybe related to #1401

**Comment by ViRb3** [comment]
Apologies, the problem was in an inherited nginx config:
```nginx
# XSS
add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
```

**Comment by nhooyr** [comment]
Glad you figured it out.

**Comment by jgsun** [comment]
> Apologies, the problem was in an inherited nginx config:
> 
> ```nginx
> # XSS
> add_header X-Frame-Options DENY;
> add_header X-Content-Type-Options nosniff;
> add_header X-XSS-Protection "1; mode=block";
> ```
> 
> Everything works after I cleared those headers. Feel free to close this issue.

I am wondering how to or where to clear those headers? Thanks you very mucy!

**Comment by miramar-labs** [comment]
It's still happening in the latest builds - any chance you could elaborate on the 'fix' mentioned above ?

**Comment by ViRb3** [comment]
I have a global nginx config called `tls.conf` which sets the following "security" headers:
```nginx
# XSS
add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
```

These cause requests to be blocked by the browser while using code-server, resulting in the issue here. To fix it, simply don't set or clear the three headers mentioned above. For example:
```nginx
server {
    server_name foo.bar;

    location / {
        # override from tls.conf
        # required for Markdown preview
        add_header X-Frame-Options "";
        add_header X-Content-Type-Options "";
        add_header X-XSS-Protection "";

        proxy_pass http://code-server:8080;
    }

    listen 443 ssl http2;
    include presets/tls.conf;
}
```
Hope this makes sense.
