### ISSUE TITLE
New blank page cannot auto redirct, and stuck in login page

### ISSUE THREAD

**Issue by tces1** [cdr/code-server#1410]
I use code-server 3.0 in my centos machine, i made a webpage to link to this, like that
`<a href="http://{{container.ip}}:{{container.port}}" target="_blank">
<i class="fa fa-line-chart text-info"></i>
</a>`

But I found a strange problem when I use it, below are steps:

1. click to create 1st page, redirect login page, input the password, it works well, and redirect to the Code-OSS.
2. click to create 2nd page, redirect to `http://IP:PORT/login?to=%2F`,Now the code-server --vvv logs show that 
`debug Request error {"url":"/static/1f6ff2f7631e0aa93233a54c2eb8b5baf46c87f3/src/browser/media/code-server.png"}`
`debug Error: ENOENT: no such file or directory, open '/code-server/src/browser/media/code-server.png'`
But this page doesn't work well, i send a wrong key, but it redirect a blank page without any tips. now this page will not show anything. When I submit the wrong passwd, the page console show that the POST to http://IP:PORT/login has get 200 OK,but the response shows no data available, and code-server log ouput nothing.

Somebody get the same problem?

**Comment by tces1** [comment]
I found that close all tabs and restart Chrome this problem has gone, but duplicate create code-server page by A _blank link will shown this bug at 100%, my code-server is running  in Centos7, Chrome in MacOS

**Comment by code-asher** [comment]
Ah, I think this is the SameSite cookie attribute at play. From what I
understand if you click a link that redirects to a site it won't send
the cookie, forcing you to log in again. But I'm not sure why it
redirects to a blank page.

We could just set it to `None` which would also fix #1401.

**Comment by tces1** [comment]
@code-asher HI, after investigation, Seems I get the issue clearer, when open the link in new blank page, the first redirect request without any cookies. belows are the first get request and response 302 redirect, the request headers are different:
**Normal Page :**
`GET / HTTP/1.1
Host: 10.109.4.10:42308
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,la;q=0.7
Cookie: key=6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b`

**Unnormal Page:**
`GET / HTTP/1.1
Host: 10.109.4.10:42308
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,la;q=0.7`

I will share my investigation until the issues resolved :)

**Comment by tces1** [comment]
Seems edit js script "SameSite=None", this issue resolved~~~~
