### ISSUE TITLE
Digital Ocean Droplet page is blank

### ISSUE THREAD

**Issue by Qard** [cdr/code-server#1411]
I tried the button to create a droplet on Digital Ocean and, as per the instructions, retrieved and entered the password. However, after attempting to open the IDE it just gives me a blank page. Seems like some information might be missing from the instructions? 🤔

**Comment by nhooyr** [comment]
What device/browser are you using? Can you try a different device/browser?

**Comment by bitsrfr** [comment]
Same. Fired up the droplet for the first time today. I get the login, but after entering the password, blank page. Ipad Pro safari and chrome.

**Comment by tces1** [comment]
Seems I have the same issue #1410 , I am trying read the code, T_T

**Comment by nhooyr** [comment]
cc @nathanpotter

**Comment by nhooyr** [comment]
Ah, yea using HTTPS just doesn't work on iPads with a self signed certificate which is unfortunately what the droplet does by default. You'll have to get a non self signed certificate and then configure the systemd code-server unit to use it.
