### ISSUE TITLE
Safari/iPadOS: menus disappear after clicking

### ISSUE THREAD

**Issue by nsadeh** [cdr/code-server#1414]
When clicking on drop down menus/settings in Safari/iPadOS they disappear immediately making them and code-server unusable.

**Comment by kylecarbs** [comment]
Just to confirm, the File, Edit, View, etc. menus right?

**Comment by nsadeh** [comment]
Yes, all the drop downs including File/Edit/View

**Comment by kylecarbs** [comment]
Will fix. Thanks for the report!

**Comment by shaynem** [comment]
Work around is run it in full screen by creating a desktop shortcut for it.
