### ISSUE TITLE
Attempting to reconnect

### ISSUE THREAD

**Issue by T1mron** [cdr/code-server#1415]
How to disable this message after reconnect 10-15 seconds? 

![8742FD92-1518-4AA0-8707-250C90094314](https://user-images.githubusercontent.com/60440013/76613886-0c743780-6530-11ea-8044-435a1d2c7359.jpeg)

**Comment by kylecarbs** [comment]
Could you provide more info? This notification should only display if you're disconnected, in which case we definitely want to notify you.

Closing for now until more info is provided.
