### ISSUE TITLE
Bring --list-extensions and --show-versions back

### ISSUE THREAD

**Issue by SuperSandro2000** [cdr/code-server#1417]
I was using --list-extensions and --show-versions to dump my installed extensions and install them on a different machine.
Why got this removed in 3.0 without a changelog entry?
Can it be brought back?

**Comment by code-asher** [comment]
Ah this is because we switched to our own command line parser. `list-extensions` can still be used but isn't in the help menu so I'll add it. I'll also add `show-versions`. Let me know if there are any other missing flags from v2.
