### ISSUE TITLE
Cannot debug extension

### ISSUE THREAD

**Issue by ViRb3** [cdr/code-server#1420]
## Issue description
I am attempting to debug the following extension: https://github.com/manuth/MarkdownConverter, but it does not seem to load when debugged.

## Environment
Docker `code-server:v2` and `code-server:3.0.1`

## Steps
1. Install NPM:
```
curl -sL https://deb.nodesource.com/setup_13.x | sudo bash -
sudo apt-get install -y nodejs
```
> from https://github.com/nodesource/distributions/blob/master/README.md

2. Install yarn:
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt install yarn
```
> from https://classic.yarnpkg.com/en/docs/install#debian-stable

3. Clone the repo:
```
git clone https://github.com/manuth/MarkdownConverter
```

4. Install extension dependencies
```
cd MarkdownConverter
yarn install
```

5. Open the new directory in code-server and start debugging via: `Debug and Run` > `Launch Extension`

## Results
Starting the debugger opens a new window which should have the debugged extension loaded. However, it does not. I tried both code-server v2 and v3, neither of which work. I tested the same setup on vanilla VSCode and it works as expected.

**Comment by kylecarbs** [comment]
Hm. I'm not sure debugging extensions works with code-server, although we should definitely make it.

**Comment by ViRb3** [comment]
My only reason to debug it is because the extension does not work on code-server but works on normal VSCode. Any tips on how I can diagnose it? There are no logs or anything...

**Comment by kylecarbs** [comment]
Oh I understand. There's no logs in the client console?

**Comment by ViRb3** [comment]
Nope, but the extension works properly on code-server v3. Still couldn't figure out debugging, though.

**Comment by kylecarbs** [comment]
Going to close if it works in v3 then. 🎊
