### ISSUE TITLE
Folder get parameter dose not handle some paths correctly

### ISSUE THREAD

**Issue by TheHllm** [cdr/code-server#1422]
# The issue
Opening a path wich includes (e.g) # will not work.
This was an issue in previous versions to but was fixed by manually encoding the char (%23).

This is a relevant issue # are not too uncommon since it is part of C#.

# Steps to reproduce
```
mkdir test#
```
Open the folder in code-server

**Comment by kylecarbs** [comment]
We'll definitely fix this. Thanks for the report!

Tracking in: https://github.com/cdr/code-server/issues/1424
