### ISSUE TITLE
vscode login callback, using Azure Accounts extension

### ISSUE THREAD

**Issue by diegosucaria** [cdr/code-server#1423]
Hello!  Running 3.x version here.

When I try to login to azure using the extension "Azure Accounts" it opens a web browser with a callback url like 127.0.0.1:443/callback?asdasdasd

Even if I change 127.0.0.1 to my custom domain where I run code-server behind a nginx reverse proxy that doesn't work....

Is there a known workaround for this? or have you any ideas about what can I try to do to make it work?

Thanks!

**Comment by kylecarbs** [comment]
Their extension probably listens for a callback with auth. Not much we can do here.

We're working on a URL-forwarding solution that might help. Closing for now, would appreciate if anyone finds a workaround!
