### ISSUE TITLE
Support for more extensions

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1427]
See https://github.com/cdr/code-server/issues/577#issuecomment-600349004

**Comment by sr229** [comment]
One of the main issues is some of the many-requested features are from Microsoft - which we can't actually add since it breaks the ToS AFAIK.

**Comment by JayXon** [comment]
Why is this closed? I still can't find these two extentions:
https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode
https://marketplace.visualstudio.com/items?itemName=npclaudiu.vscode-gn

**Comment by nhooyr** [comment]
cc @cmoog

**Comment by nhooyr** [comment]
@JayXon Might have been a mistake.

**Comment by cmoog** [comment]
@JayXon Both are now live in our marketplace 👍

**Comment by JayXon** [comment]
I see it now, thanks!

**Comment by nhooyr** [comment]
@cmoog fastest issue closer 😍
