### ISSUE TITLE
Why not show vscode version in release?

### ISSUE THREAD

**Issue by tonystarkdo** [cdr/code-server#1429]
Why not show vscode version in release in the future? I don't understand. It may be confusing for that people can't know which vscode version is. The version can indicate whether we need to update or not for a new function added in new vscode version.

**Comment by kylecarbs** [comment]
We had a lot of discussion around this, so I'll add some context:

In future versions, we'll be supporting editors beyond VS Code. We wanted to shift architecture and changes more-slowly so people have time to update scripts and such without massive breaks. With this, we felt moving to semantic versioning would be appropriate.

Closing for now, but happy to elaborate.
