### ISSUE TITLE
Symbol not found in alpine

### ISSUE THREAD

**Issue by yujinqiu** [cdr/code-server#1430]
Hi there, 
code-server2.1698-vsc1.41.1-alpine-x86_64  unable to run in Alpine Linux 3.9 with the following error

```
~ # ./code-server -h
Error relocating ./code-server: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
Error relocating ./code-server: _ZNSt19_Sp_make_shared_tag5_S_eqERKSt9type_info: symbol not found
Error relocating ./code-server: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found
```
code-server2.1692-vsc1.39.2-alpine-x86_64  works well. 

```
~ # code-server --version
info  2.1692-vsc1.39.2
info  e14362f3224c101585a26bf7ee5fa6e3bf425046
info  x64
```

**Comment by kylecarbs** [comment]
Weird weird. Any ideas @code-asher ?

**Comment by code-asher** [comment]
We were using Drone for that release; we must have broken the Alpine step in the process. I'm unsure what the best way to fix it is since we no longer have Alpine builds; the current recommendation is to install `libc-dev` so maybe we should just remove the broken Alpine builds from that release?

**Comment by mjgallag** [comment]
I can’t get libc-dev to work in alpine for 3.0.0. I get similar errors. If I take the node binary from official node alpine image it works just fine.

**Comment by nhooyr** [comment]
Looks like there's been confusion regarding libc-dev. I don't think that installs glibc or would help with this issue. I think that was my bad. I think the best approach here is to solve #1396 instead of adding an alpine release but whatever you think is best @code-asher

**Comment by code-asher** [comment]
We'd need an Alpine container on CI either way, I think? In order to build the native Node modules. I suppose that means we'd end up with an Alpine release during deploy anyway.

**Comment by nhooyr** [comment]
We wouldn't include the native node modules, they'd be built by node when fetched.

**Comment by code-asher** [comment]
Oh right, of course. Yeah that sounds good to me.

**Comment by nhooyr** [comment]
Fixed, please use the npm package to install on alpine. The erroneous alpine entry in the FAQ has been removed.

See https://github.com/cdr/code-server#npm

**Comment by anonhostpi** [comment]
If this is an issue on Alpine, it is also likely an issue on OpenWRT as they both use musl instead of glibc
