### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by dvelopin** [cdr/code-server#1431]
Thank you for this project! This is really cool! I just got a new Ubuntu Server setup for development and put this on there. I hope to do more coding from my iPad Pro.

Is it possible for the following extensions be supported?

https://marketplace.visualstudio.com/items?itemName=liximomo.sftp
https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs

**Comment by kylecarbs** [comment]
Sorry for the delay!

I've added the SFTP extension. The PHP extension doesn't compile, but I've [submitted a PR](https://github.com/ikappas/vscode-phpcs/pull/169). Once that gets accepted I'll add it too.

**Comment by dvelopin** [comment]
Certainly no need to apologize. Thank you!

**Comment by Rathna-K** [comment]
For the SFTP it only shows 1.0.0 version and their latest version allows lot more. Any way to update?

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/blob/master/doc/FAQ.md#whats-the-deal-with-extensions

**Comment by nhooyr** [comment]
@Rathna-K Please file a new issue to request an update!
