### ISSUE TITLE
docker Command in READ.md has a problem

### ISSUE THREAD

**Issue by chengziqaq** [cdr/code-server#1434]
docker run -it -p 127.0.0.1:8080:8080 -v "$PWD:/home/coder/project" codercom/code-server
the right is command is : 
docker run -it -p 8080:8080 -v "$PWD:/home/coder/project" codercom/code-server

**Comment by lsmoura** [comment]
I believe the command on the readme file is correct.

On the example you gave, the port is open for whatever host has network access and can reach your machine. On the read me file example, only the local machine has access to the port.

It is a security measure and it works as intended.

**Comment by nhooyr** [comment]
@lsmoura is correct, all is well.
