### ISSUE TITLE
code-server crashes when opening a folder after installing it in google cloud shell

### ISSUE THREAD

**Issue by samorogu** [cdr/code-server#1440]
## Enviroment
* Google cloud 
* Debian GNU/Linux 9.12 (stretch)
* code-server-3.0.0-linux-x86_64

## Steps

` wget https://github.com/cdr/code-server/releases/download/3.0.0/code-server-3.0.0-linux-x86_64.tar.gz`
`tar -xvzf code-server-3.0.0-linux-x86_64.tar.gz`
`cd code-server2.1698-vsc1.41.1-linux-x86_64/`
` ./code-server --auth none`
 Click on Web Preview -> Preview on port 8080

## Behaviour

I can edit a file without a problem. But if I try to open a folder, the page crashes and refreshes without opening the folder. Next, after seeing the console the next warning appears:
info  code-server 3.0.0
info  Server listening on http://127.0.0.1:8080
info    - No authentication
info    - Not serving HTTPS
info    - Automatic updates are enabled
warn  ENOENT: no such file or directory, stat '//8080-dot-<numbers>-dot-devshell.appspot.com/home/<user_name>/<directory>/

**Comment by kylecarbs** [comment]
Does it crash on the client or server? Are there any additional logs in the client?

**Comment by samorogu** [comment]
It crashes on the the client and doesn't gives any other logs:

![openingFile](https://user-images.githubusercontent.com/13773299/77503378-0f6e0280-6e23-11ea-9b4f-8ecaa63015e6.gif)

Meanwhile this is shown on the server:

![crashClient](https://user-images.githubusercontent.com/13773299/77503684-daae7b00-6e23-11ea-9155-6c3b5eeafb42.png)

**Comment by code-asher** [comment]
What does the URL look like? It's supposed to have something like `?folder=/home/...` but it looks like the domain is somehow being included as part of the directory based on the console output.

v3 fixed a few issues with the folder query parameter if you're able to give it a try.

**Comment by samorogu** [comment]
I tried to access the URL giving the query parameter: `https://8080-dot-<numbers>-dot-devshell.appspot.com/?folder=home/samuel_rocha/repos/` 

but it reloads with no message on the client and with the next message on the server:

warn  ENOENT: no such file or directory, stat 'home/samuel_rocha/repos/'

**Comment by code-asher** [comment]
How are you opening the workspace? If you use `?workspace` instead of `?folder` it should work. For example `domain.com?workspace=/home/path/to/file.code-workspace`.

**Comment by samorogu** [comment]
It works if I use the folder query parameter. Thanks for point it out to me! Even thought, you think when using the buttons when opening the folder and workspace, it is a bug?

**Comment by code-asher** [comment]
The buttons and menus are supposed to do the same thing as typing it manually. I tested on v3.0.1 but I haven't been able to replicate the problem. When I go to `File` > `Open Folder` and browse to `/home`, for example, my URL becomes `http://localhost:8080/?folder=/home` which is what is expected.

What does the URL look like for you when you use the menu to open a folder?
