### ISSUE TITLE
code-server cant't launch terminal in my container,(exit code{2})

### ISSUE THREAD

**Issue by leeli73** [cdr/code-server#1442]
This is my container‘s core code.
I colne  NEWUTS,NEWPID,NEWNS,NEWIPC by syscall.

![image](https://user-images.githubusercontent.com/34590213/77247152-45678700-6c69-11ea-8ce8-c2aa00ebff62.png)

![image](https://user-images.githubusercontent.com/34590213/77247157-531d0c80-6c69-11ea-9efe-dae70311d4f4.png)

build it,and run it with code-server image (docker export)
![image](https://user-images.githubusercontent.com/34590213/77247013-fb31d600-6c67-11ea-8a2f-e44ae471b085.png)
![image](https://user-images.githubusercontent.com/34590213/77247006-ebb28d00-6c67-11ea-99fc-46518261fa0f.png)
with error:`The terminal process command '/bin/bash' failed to launch (exit code: {2})`
Path environment variables are normal.
I tried to modify the settings.json and I modified the Terminal>Integrated>Shell>Linux.
But it is useless.
I think this is my container's bug.
Who can help me to fix!!!!
Thank you very very very much!!

**Comment by kylecarbs** [comment]
Hm. Can you launch a TTY normally? I'd assume that's failing.

**Comment by leeli73** [comment]
> Hm. Can you launch a TTY normally? I'd assume that's failing.

Thank you very much，Maybe you're right.
My terminal is not a TTY.
Maybe it caused this problem.
I try to fix it.
Thank you again

**Comment by leeli73** [comment]
> Hm. Can you launch a TTY normally? I'd assume that's failing.

Do you know how to create TTY by golang.
I'm a student, I don't know how to solve it.
If you have similar blogs or documents, can you share them with me.
Thank you very much again.
