### ISSUE TITLE
Improve default setup

### ISSUE THREAD

**Issue by kylecarbs** [cdr/code-server#1447]
Most people don't run code-server in a Dockerfile. Provide better examples for setting-up on bare metal.

**Comment by nhooyr** [comment]
@kylecarbs What are you thinking of providing in the docs here? Most of the Dockerfile stuff is stuff that's normally already done on bare metal machines as standard linux stuff. Only reason we have to do it is because docker images are normally stripped down.

**Comment by kylecarbs** [comment]
I mean for deploying and using code-server daily. I use code-server on GCP and the setup (while similar) is quite different from the Docker cmd we provide by default.

**Comment by nhooyr** [comment]
Like you mean running it as a systemd service?

**Comment by kylecarbs** [comment]
Or even running it in a screen, yea

**Comment by IPvSean** [comment]
there used to be docs on running this as a systemd service... did someone remove them?

**Comment by cmoog** [comment]
@kylecarbs @nhooyr Thoughts? https://github.com/cdr/code-server/blob/default-setup/doc/GettingStarted.md

Figured that we could use a bare setup guide-- one that doesn't include SSL or http proxy.

**Comment by nhooyr** [comment]
Nice, like the screenshots.

Lets use digital ocean instead as the default since we can provide a button and use the DO image which runs code-server on systemd.

The image is built from this packer directory: https://github.com/codercom/do-marketplace-partners/tree/master/packer

**Comment by nhooyr** [comment]
I provided the link there just so we can include it in the docs so users know what the image contains.

**Comment by nhooyr** [comment]
Done, see https://github.com/cdr/code-server/blob/master/doc/guide.md
