### ISSUE TITLE
White Screen with domain

### ISSUE THREAD

**Issue by B4TT3RY** [cdr/code-server#1451]
```
Refused to load the script 'https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
Only Domain can't working. ip:port is working.
Version: `codercom:code-server:3.0.1`

**Comment by kylecarbs** [comment]
You can disable rocket loading on Cloudflare.

We'll add the proper tags so our scripts don't get rocket-loaded by default. [Reference](https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-specific-JavaScripts-)

**Comment by sanjayme97** [comment]
@code-asher  I am also facing same problem it works in ip address:port but for domain name its white screen not working at all.
![error](https://user-images.githubusercontent.com/45826938/80101593-3db04080-858f-11ea-9e70-d231122afa88.PNG)
