### ISSUE TITLE
Installing extensions through command line (--install-extension) stopped working, installs ms-python instead

### ISSUE THREAD

**Issue by ppkwiatkowski** [cdr/code-server#1452]
Installing extensions with `code-server --install-extension` command line seems to be broken since yesterday.

```
~ (:|✔)~$ ls ~/ext-test                                 
~ (:|✔)~$ ./Downloads/code-server2.1698-vsc1.41.1-linux-x86_64\ \(1\)/code-server2.1698-vsc1.41.1-linux-x86_64/code-server --extensions-dir ~/ext-test --install-extension=redhat.vscode-yaml
Installing extensions...
Installing extension 'redhat.vscode-yaml' v2020.2.64397...
Extension 'redhat.vscode-yaml' v2020.2.64397 was successfully installed.
~ (:|✔)~$ ls ~/ext-test                                                                                                                                                                      
ms-python.python-2020.2.64397
~ (:|✔)~$ rm -r ~/ext-test/ms-python.python-2020.2.64397 
~ (:|✔)~$ ls ~/ext-test                                 
~ (:|✔)~$ ./Downloads/code-server-3.0.0-linux-x86_64/code-server --extensions-dir ~/ext-test --install-extension=redhat.vscode-yaml
Installing extensions...
Installing extension 'redhat.vscode-yaml' v2020.3.69010...
Extension 'redhat.vscode-yaml' v2020.3.69010 was successfully installed.
~ (:|✔)~$ ls ~/ext-test                                                                                                            
ms-python.python-2020.3.69010
~ (:|✔)~$
```

As you can see above, it doesn't work in both recent versions `1698-vsc1.41.1` and `3.0.0`.
Particular extension doesn't matter, it always installs `ms-python` instead. Even installing extensions from `.vsix` files has stopped working, however the correct files appear in extensions directory but code-server doesn't detect them. It would be cool if installing from `.vsix` files wouldn't rely on such external dependencies.

Funny thing is that installing from `.vsix` seems to be working with internet connection turned off, so it looks like a problem with some external API request. Market place maybe?

**Comment by kylecarbs** [comment]
We've reverted some extension marketplace changes. Sorry about that, we'll make sure it doesn't happen again!

**Comment by ppkwiatkowski** [comment]
@kylecarbs Great! thanks for fast reaction!

Would it be possible to make installing from `.vsix` entirely independent from market-place in the future? I would like to make my instance as independent from such eternal variables as possible.

**Comment by nhooyr** [comment]
Wasn't aware installing from a .vsix depended on the marketplace, pretty sure I tested it in an airgapped environment where there is no marketplace.

**Comment by benz0li** [comment]
Extensions, which aren't part of your Marketpalce, can't be activated. Although `Activating extension...` is shown in the status bar - and disappears after a few seconds - the extensions do not get activated.

Affected extensions:
*  `Ikuyadeu.r` (v1.2.7)
*  `julialang.language-julia` (v0.14.18)
*  `alefragnani.project-manager` (v10.11.0)

Affected Code Server versions:
*  `3.0.0` (Pre-release)
*  `3.0.1` (Pre-release)

This wasn't the case with the initial Pre-release of Code Server `3.0.0`. Only the currently released versions `3.0.0` (March 25, 2020) and `3.0.1` (March 27, 2020) are affected.

**Comment by benz0li** [comment]
It would be great, if you could update extension `julialang.language-julia` to a current version (e.g. 0.14.18) and add the other two extension to your Marketplace.

**Comment by benz0li** [comment]
Just found out that the problem is not related to Code Server at all: Version `1.3.0` of [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy) doesn't seem to work properly with extensions.

I've pinned jupyter-server-proxy to version `1.2.0` in my Jupyter installation and everything is working properly again.

**Comment by nhooyr** [comment]
Awesome news. Thanks for figuring it out @benz0li
