### ISSUE TITLE
Couldn't run on Debian 9

### ISSUE THREAD

**Issue by qwerzl** [cdr/code-server#1456]
Hi there,
Code server v1 ran properly on my server, but both v2 and v3 stopped after `info - Automatic updates are enabled`. I waited for about an hour but no error information were given. Docker doesn't run either.
![image](https://user-images.githubusercontent.com/46770502/77612384-fa988880-6f62-11ea-9b17-01c6de031a4b.png)

**Comment by nhooyr** [comment]
Might be related to https://github.com/cdr/code-server/issues/1407

Try upgrading nodejs.

**Comment by qwerzl** [comment]
I've already installed nodejs 12. Connection is refused on my browser. Seems that the code server didn't start.

**Comment by code-asher** [comment]
Do you have a reverse proxy in front of code-server or are you accessing it directly? Might need to make the host `0.0.0.0` if you're doing the latter. I think that was v1's default although I might be mis-remembering.

**Comment by qwerzl** [comment]
That works. Thanks!
