### ISSUE TITLE
3.0.0 tag moved but release assets not updated

### ISSUE THREAD

**Issue by mjgallag** [cdr/code-server#1457]
Rather than moving existing tag (which is pretty confusing) perhaps you could consider, `3.0.0-alpha.1`, `3.0.0-beta.1`, `3.0.0-rc.1`, see https://semver.org/#spec-item-9, or `3.0.1`. As an example https://github.com/helm/helm/tags makes good use of semantic versioning.

**Comment by kylecarbs** [comment]
Agreed! Thanks for the tip.

**Comment by code-asher** [comment]
I updated the Travis config to overwrite the assets; they should be correct now. :crossed_fingers:
