### ISSUE TITLE
Spaces in File Paths

### ISSUE THREAD

**Issue by qwertycody** [cdr/code-server#1458]
Log shows this:
- warn  ENOENT: no such file or directory, stat '/mnt/c/Programs/CompanyName/Misc/Portable%20CompanyName%20Image'

When attempting to open a folder as the "workspace" but not as a workspace using the option that literally says "open folder" from file.

This is on the 3.0 version that just came out.

Thoughts?

**Comment by qwertycody** [comment]
Give it a try with this quick docker build I made.
- https://github.com/qwertycody/VS_Code_Server_For_Windows

**Comment by kylecarbs** [comment]
@code-asher does opening folders with spaces work?

**Comment by code-asher** [comment]
Not on the latest release, but it's fixed in master.

**Comment by kylecarbs** [comment]
Should we publish a new release to fix it up?

**Comment by code-asher** [comment]
Yeah that sounds like a good idea to me.

**Comment by code-asher** [comment]
3.1.0 released :confetti_ball:
