### ISSUE TITLE
Python ext. fails after v2019.10.41019 when run behind ShinyProxy/SpringBoot

### ISSUE THREAD

**Issue by dm3ll3n** [cdr/code-server#1461]
The Jupyter functionality provided by the Python extension is dysfunctional after version 2019.10.41019 if running code-server (v2 or v3) via [ShinyProxy](https://www.shinyproxy.io/). For versions of `ms-python.python` later than 2019.10.41019, the Jupyter functionality fails and the ShinyProxy logs read:

```
shinyproxy_1  | 2020-03-28 18:11:12.015 ERROR 1 --- [ XNIO-2 task-10] io.undertow.request
shinyproxy_1  | UT005023: Exception handling request to /app_direct/codeserver/webview//vscode-resource/file///home/coder/.local/share/code-server/extensions/ms-python.python-2020.2.63072/out/datascience-ui/notebook/interactiveWindow.js
shinyproxy_1  | org.springframework.security.web.firewall.RequestRejectedException:
shinyproxy_1  |         The request was rejected because the URL was not normalized.
shinyproxy_1  |         at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:248) ~[spring-security-web-5.0.3.RELEASE.jar!/:5.0.3.RELEASE]
```

ShinyProxy is built with SpringBoot, and the error makes it clear: `The request was rejected because the URL was not normalized`. It doesn't seem to like the extra slashes in the URL: `webview//vscode-resource/file///home`. There doesn't seem to be an easy way to disable this rule in ShinyProxy/SpringBoot.

I created a repo to facilitate testing this configuration:
- one branch with to reproduce the error [here](https://github.com/dm3ll3n/code-server-shinyproxy-test/tree/master)
- and a working (outdated) example [here](https://github.com/dm3ll3n/code-server-shinyproxy-test/tree/working).

Can code-server ensure URLs are normalized before issuing the request?

**Comment by dm3ll3n** [comment]
I'm not comfortable with JS, but I think this could be overcome by ensuring URLs don't contain double-slashes in the method [here](https://github.com/cdr/code-server/blob/7954656610419035a1d96af376e1a4b525706ad0/src/node/app/vscode.ts#L126).

SpringBoot documents their rationale for the rule [here](https://docs.spring.io/spring-security/site/docs/5.0.0.RELEASE/reference/htmlsingle/#request-matching). TLDR:

> There is a danger that when an application is deployed in a container which does not strip path parameters from these values, an attacker could add them to the requested URL in order to cause a pattern match to succeed or fail unexpectedly. [9]. Other variations in the incoming URL are also possible. For example, it could contain path-traversal sequences (like /../) or multiple forward slashes (//) which could also cause pattern-matches to fail. Some containers normalize these out before performing the servlet mapping, but others don’t. To protect against issues like these, FilterChainProxy uses an HttpFirewall strategy to check and wrap the request. Un-normalized requests are automatically rejected by default, and path parameters and duplicate slashes are removed for matching purposes.

**Comment by kylecarbs** [comment]
Closing in favor of https://github.com/cdr/code-server/issues/1529
