### ISSUE TITLE
Cannot log in to code-server running in docker with reverse proxy

### ISSUE THREAD

**Issue by teddue** [cdr/code-server#1469]
I run code-server inside a docker container and put it behind a reverse proxy (for https)

When I access it through its ip address and in plain http I can log in but when i try to access it through the reverse proxy I get the log in screen but cannot log in (without an error message)

**Comment by perelin** [comment]
Hey, whats your actual setup? Maybe you can post your nginx/apache config file. Is your certificate issued for the exact domain you are using? @ttfan240 posted an nginx config that helped me with my setup https://github.com/cdr/code-server/issues/1211#issuecomment-575985054

**Comment by nhooyr** [comment]
It's very unlikely this is a bug in code-server, please ensure your reverse proxy is working correctly and definitely look at #1211
