### ISSUE TITLE
Html formatter extension doesn't works.

### ISSUE THREAD

**Issue by Abhid14** [cdr/code-server#1471]
The apllication is hosted on google cloud shell with all permissions and privileges and 4gb ram.
Extension for html formatting is not working too.
here is the scene.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/34400585/78008306-2188fd00-735d-11ea-851b-06b0969757d5.gif)

**Comment by Abhid14** [comment]
I used it on on other browser and even another device still no hope.

**Comment by Abhid14** [comment]
![image](https://user-images.githubusercontent.com/34400585/78008973-fa7efb00-735d-11ea-8e5a-dd497ec77b4c.png)

**Comment by code-asher** [comment]
What do you see if you go to the extensions and search `@builtin html`?

**Comment by Abhid14** [comment]
> What do you see if you go to the extensions and search `@builtin html`?

Even that's broken. I checked settings.json for them nothing was manipulated reinstalled on other vm still not working getting same issues.

**Comment by code-asher** [comment]
By broken do you mean it says "No extensions found." after doing the search?

**Comment by Abhid14** [comment]
Extensions installed just not working.

**Comment by code-asher** [comment]
I tried this through Google Cloud Shell and sure enough I was able to replicate the issue. It doesn't happen locally or through the Docker image. It looks like the extension host is erroring because of a malformed URI, hopefully it won't be too hard to track down.

**Comment by Abhid14** [comment]
That's good.
