### ISSUE TITLE
Undo shortcut - wrong hotkey mapping

### ISSUE THREAD

**Issue by peet86** [cdr/code-server#1477]
code-server version: 3.0
OS Version: macOS 
Browser: Safari

Description
On certain keyboard layouts chars are not mapped to the same key like on the English one. 
Example:  Z and Y keys are switched on DE/HU/etc. layouts. 

It seems to me you are using key codes to catch the pressed shortcuts..  which is an issue for all users who try to use different layouts than EN. Very popular key combinations like CMD+Z (undo) are mapped to wrong keys (CMD+Y in this case).. 

Steps to Reproduce
Use a DE layout keyboard / change in your OS to another layout and use the Keyboard Viewer utility

**Comment by peet86** [comment]
Just to make it clear: the mapping in vscode seems to be correct, but on a DE/HU/etc. keyboard I need to press CMD+Y to tigger undo. 
 
```
{ "key": "cmd+z",                 "command": "editor.action.customEditor.undo",
                                     "when": "focusedCustomEditorIsEditable && !inputFocus" },
```

**Comment by code-asher** [comment]
I had a similar problem (with local VS Code as well) and changing the `Keyboard: Dispatch` setting to `keyCode` fixed it for me. The default is `code` which is always the same no matter what the layout is.

**Comment by kylecarbs** [comment]
Closing for now. Let us know if that doesn't fix the issue @peet86 !
