### ISSUE TITLE
Error on RPi4

### ISSUE THREAD

**Issue by missaghi** [cdr/code-server#1478]
docker run -it -p 127.0.0.1:8080:8080 -v "$PWD:/home/coder/project" codercom/code-server
standard_init_linux.go:211: exec user process caused "exec format error"
failed to resize tty, using default size

**Comment by nhooyr** [comment]
Unfortunately at the moment we have no arm32 support. See #1337

**Comment by nhooyr** [comment]
Or to clarify, no published docker image.

**Comment by missaghi** [comment]
I think RPiI4 is ARM64 though?

**Comment by nhooyr** [comment]
See https://www.raspberrypi.org/forums/viewtopic.php?t=252369
