### ISSUE TITLE
Where is the Dockerfile?

### ISSUE THREAD

**Issue by dpgeekzero** [cdr/code-server#1480]
I don't see a Dockerfile in this project that generates the image I pulled from Docker Hub.

There are two Dockerfiles in the `ci/image` and `ci/release-image` directories but they do not contain the VOLUME directive that is in the published image.

I saw the previous closed issue: https://github.com/cdr/code-server/issues/1167 which indicates that it is sitting in the root of the repository, but it isn't there.
I cloned the project locally just to make sure.

**Comment by qqice233** [comment]
Hello there,
I found the Dockerfile.
It's here
[https://github.com/cdr/code-server/blob/master/ci/release-image/Dockerfile](https://github.com/cdr/code-server/blob/master/ci/release-image/Dockerfile)

**Comment by dpgeekzero** [comment]
That one doesn't have the volume in it for /home/coder/project, so it can't be for the published image.
Also, the one I pulled this morning was based on ubuntu:18.04.

❯ docker pull codercom/code-server:latest
latest: Pulling from codercom/code-server
Digest: sha256:55774d69929ceed719db03d756ce1f8425c16716669ebc3c5b41d7ff79434f27
Status: Image is up to date for codercom/code-server:latest
docker.io/codercom/code-server:latest

❯ docker run -it --entrypoint bash codercom/code-server:latest
coder@e2b3948381ef:~/project$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by code-asher** [comment]
Sorry for the confusion, the current Dockerfiles in master are for v3. `latest` is still v2. Since we just released v3 yesterday I think I should go ahead and update `latest` to point to v3.

**Comment by dpgeekzero** [comment]
Okay, that makes sense, I hadn't verified what version I was getting when I pulled latest.  :)

**Comment by code-asher** [comment]
Latest now points to 3.0.2 :tada:

**Comment by BBQlee** [comment]
Hi friends, do you hava Dockerfile ? I want to do an image with the code-server-4.5.0-linux-amd64.tar.gz, but I do not know how to do the Dockerfile, can you help me pls~

**Comment by code-asher** [comment]
Here is the Dockerfile we use for our images:

https://github.com/coder/code-server/blob/530bb66d7c91db0113701025d39421d255bffb60/ci/release-image/Dockerfile
