### ISSUE TITLE
Multiple Workspaces

### ISSUE THREAD

**Issue by dvelopin** [cdr/code-server#1482]
It appears that workspaces doesn't work properly.

I created a workspace and added a folder to it, saved the workspace (tried with and without spaces), I created a second workspace and noticed it pulled the same folders as the original workspace, so removed the folder and added the second folder, and saved as a second workspace. Then I tried switching workspaces between the two, and although the name of the workspace changes, the folders stay the same as the "last session" if that makes sense.

Another example is I created a new workspace and added several project folders to it, saved it as a workspace, then removed all folders except one, saved as another workspace, went to load my "all folders" workspace, and it only had the one folder I didn't remove to save as another workspace.

Do workspaces work? Am I doing something wrong?

**Comment by code-asher** [comment]
I think what's happening is that when you add or remove a folder from a workspace it immediately saves that to the current workspace. So if you do "save workspace as" after that, the two workspaces will have the same folders.

**Comment by dvelopin** [comment]
Interesting, I'll try saving workspace as something else first and then remove folders.

**Comment by dvelopin** [comment]
Looks like that did it. I now am able to open different workspaces with different folders. THANK YOU!
