### ISSUE TITLE
code-server deletes olds version when updating

### ISSUE THREAD

**Issue by dmratcliffe** [cdr/code-server#1483]
Coder server just updated, and deleted my projects folder.

Is there anyway to retrieve it? I don't have a backup.
Infact, it delted all configs. It wiped the folder that coder was in an replaced it all.

**Comment by kylecarbs** [comment]
Huge problem. Could you elaborate on your directory structure?

**Comment by nhooyr** [comment]
@dmratcliffe Were you placing your files in the directory code-server was unpacked into?

Regardless, we'll change code-server asap to move the files instead of deleting.

**Comment by dmratcliffe** [comment]
To give more information, my code-server was setup like so:

/home/coder/code-server - the binary of code server
/home/coder/extenstions - the location of extenstions, setup with the command line switch on the coder binary, I had a similar folder for the user data too, forgot the names.
/home/coder/project - the folder coder would load by default, had numerous projects and folders.

It had been setup like this forever, and updates previously had never destroyed my files. It seems insane that an update could even do this.

I don't mean to nitpick, but why was it set to delete files that it didn't create? Did it just run rm * on its folder? Why was there no warning? Why did it happen now and not before?

**Comment by nhooyr** [comment]
> /home/coder/code-server - the binary of code server

Does this mean you were on V2?

**Comment by nhooyr** [comment]
> It seems insane that an update could even do this.

Yes it's insane and unexpected so we're gonna try to fix whatever it is asap.

**Comment by dmratcliffe** [comment]
Hey, I did some looking and I believe the reason it was overwritten is because the move command will overwrite the entire directory if a directory is given as the destination.

I think that's why, which means the current patch will just repeat this but there would be a backup?

Not sure, baseing this stuff of the documentation of fs.move found here:
https://github.com/jprichardson/node-fs-extra/blob/master/docs/move.md
![image](https://user-images.githubusercontent.com/4766858/78305906-b596c800-7507-11ea-91a6-83336bd10ebf.png)

and the implentation that made this happen (I think this is the spot maybe I'm wrong?):
https://github.com/cdr/code-server/blob/d192726e805a5ea608953354ca77ee8cda1647f7/src/node/app/update.ts
![image](https://user-images.githubusercontent.com/4766858/78305977-e545d000-7507-11ea-96ed-8fec7f14c847.png)

**Comment by code-asher** [comment]
You're right, that's exactly what caused this issue. When the new code-server directory was moved on top of the old one it overwrote the old one entirely.

The commit I just made renames the current code-server directory with a timestamp suffix so it won't get overridden. I also removed the `{ overwrite: true }` so it won't be able to overwrite even if the directory wasn't moved.

We could move each file individually but then we might encounter unexpected side effects, such as what might happen if code-server crashed or was killed partway through the update. There's also no guarantee that we wouldn't accidentally overwrite a file the user modified or created if it happens to share the same name. I think renaming the directory is the safest (and fastest) option when considering all the potential edge cases.

**Comment by nhooyr** [comment]
@dmratcliffe Really sorry about this whole situation, hope you can recover your files!

**Comment by dmratcliffe** [comment]
@nhooyr Thanks, filetree was gone, photorec is promising but theres 40gbs of random scambled files :/

**Comment by code-asher** [comment]
@dmratcliffe Just as a heads up, we're going to release 3.1.0 today. It has the update fixes but 3.0.2 still has the old code so an automatic update from 3.0.2 to 3.1.0 will delete the old version again. I hope you've had some luck in the recovery process, sorry again!

**Comment by dmratcliffe** [comment]
@code-asher For sure. Thanks for the headsup.
