### ISSUE TITLE
Can't close folder via File->Close Folder

### ISSUE THREAD

**Issue by confusedguy9** [cdr/code-server#1485]
After reloading, the URL in address bar changes but the folder is still opened. This seems to be broken since 3.0.0 release.

I'm running code-server on a Linux x86_64 machine.

**Comment by dvelopin** [comment]
I think this is related to the workspace issue I opened earlier

**Comment by code-asher** [comment]
code-server remembers and opens the last folder if there is no `folder` query parameter in the URL. That information is in `~/.local/share/code-server/coder.json` by default if you wanted to remove it.

**Comment by confusedguy9** [comment]
I see. Thanks!
