### ISSUE TITLE
Extenstion pages not loading

### ISSUE THREAD

**Issue by dmratcliffe** [cdr/code-server#1487]
![image](https://user-images.githubusercontent.com/4766858/78325958-cc0c4600-753e-11ea-8885-dc8aee2e8d27.png)

When installing extenstions on 3.0.2 the extenstion page fails to load. No error appears in logs or in vscode. It's just empty.

I'm reinstalling extentions and so far its happened with GitLens (pictured), and settings-sync. Didn't see an open issue.

EDIT: actually, there is an error that shows up in console:
`Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://192.168.1.150:8443/webview/') with script ('https://192.168.1.150:8443/webview/service-worker.js'): An SSL certificate error occurred when fetching the script.`

This may be because currently I am loading the site from local IP instead of my domain? I can't test until my ISP gives me a static IP, so if someone could affirm that'd be great!

**Comment by dmratcliffe** [comment]
It's a fresh install of 3.0.2, honestly it might be because of my "invalid" ssl cert. Let me try turing off SSL for a second.

**Comment by dmratcliffe** [comment]
This is fixed with a proper SSL cert. So, one linked to my domain.

**Comment by cmoog** [comment]
Thank you for the update. We're aware of diminished functionality with invalid or non-existent SSL certificates. I'm glad to hear that you've resolved the issue.

**Comment by vladdancer** [comment]
In my case I've just disabled HSTS header https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

**Comment by davidxiaozhi** [comment]
How did you fix this problem?
