### ISSUE TITLE
Can't open Folders or Workspaces with spaces in the file path

### ISSUE THREAD

**Issue by t-d-d** [cdr/code-server#1488]
code-server 3.0.2
Ubuntu 18.04

Spaces are url encoded correctly but code-server still fails to open the folder/ workspace.  It just reverts to the previous workspace/ folder.  E.g. This doesn't work:

https://my.cod.-server.fqdn/?folder=/home/coder/project/path%20with%20spaces

**Comment by nickian** [comment]
I just noticed this as well since upgrading to v3. Same environment for me.

**Comment by pr1metine** [comment]
Same for me.

**Comment by pr1metine** [comment]
Though I ran it on Docker Desktop 2.2.0.5 with codercom/code-server:latest (probably 3.0.2) as its image.
