### ISSUE TITLE
Open new window with empty workspace

### ISSUE THREAD

**Issue by geiseri** [cdr/code-server#1493]
When I first start up code server it will have no workspace loaded.  I can then load one when I open a new window though it now opens the same workspace.  It used to open a default window, but I think the fix for #1350 might have changed that.  Or am I confused on how that is supposed to be configured?

**Comment by code-asher** [comment]
As of v3 code-server chooses what to load by checking the following in order:
1. The query parameter, if any
2. The directory passed on the command line, if any
3. The last folder or workspace that was loaded, if any

**Comment by kylecarbs** [comment]
@code-asher let's document this in the FAQ.
