### ISSUE TITLE
Please add git lense to extensions marketplace

### ISSUE THREAD

**Issue by wolfgangmeyers** [cdr/code-server#1497]
This extension is very, very nice for quickly understanding the history of the code you are looking at:

https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens

**Comment by cmoog** [comment]
This is currently in our marketplace. Search for `gitlens`

**Comment by wolfgangmeyers** [comment]
![image](https://user-images.githubusercontent.com/1783800/78821531-7f859800-798e-11ea-8a8f-255acdb29639.png)

**Comment by wolfgangmeyers** [comment]
Interesting. I think the vscode marketplace has a slightly fuzzier search than the one for code-server. I was misspelling it :)
