### ISSUE TITLE
Can't find vscode version since V3

### ISSUE THREAD

**Issue by davezhouwa** [cdr/code-server#1501]
"V3 has some significant changes that will need to be accounted for in your
scripts.

We use semantic versioning now. The VS Code version will no longer be included
in the tag or the release file name. "

Some extensions are tie to particular vscode version,  so how can we find the version of vscode from the V3 releases?

**Comment by code-asher** [comment]
The two ways I can think of are:
1. Use the "about" menu from VS Code.
2. Run code server with `code-server --version --json` which prints some extra version information in JSON format. It should look something like this (except the commit will be a hash):

```
  { codeServer: '3.0.2', commit: 'development', vscode: '1.43.2' }
 ```

Both of these require you to have already downloaded code-server though. If you're trying to figure out the version before downloading I think the only way is to click the tag from the release then go to `lib/vscode/package.json` and check the version listed there.

I think it might not be a bad idea for us to list the VS Code version in the release notes as well.

**Comment by davezhouwa** [comment]
Please list the vscode version directly in the release notes
