### ISSUE TITLE
3.0.2-arm64 Docker build broken?

### ISSUE THREAD

**Issue by mbreese** [cdr/code-server#1505]
I believe that the 3.0.2-arm64 Docker build is broken. I am running this on a Raspberry Pi4 using 64-bit Ubuntu.

When I try to to run the container, I get the following error:

    $ docker run -it codercom/code-server:3.0.2-arm64
    /usr/local/bin/fixuid: 2: /usr/local/bin/fixuid: Syntax error: word unexpected (expecting ")")

To check into this a bit further, I built a test Dockerfile based on `codercom/code-server:3.0.2-arm64` that is just this:

    FROM codercom/code-server:3.0.2-arm64
    RUN sudo apt-get update; sudo apt-get install -y file
    ENTRYPOINT file /usr/local/bin/fixuid

When I run this container, I get this message:

    /usr/local/bin/fixuid: setuid ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=2zxEqkKfJJwnveNVKDuQ/1ZwU6fMfvcIshc5qwXRB/xOrQ0MI5H54iHr712aDz/hF8w_99k9vhIr1ncU3Pq, with debug_info, not stripped

This leads me to think that the binary that got loaded into the arm64 Docker container is actually an x86-64 binary. Or am I doing something wrong?

**Comment by mbreese** [comment]
If you rebuild a version of fixuid for arm64 (attached), and slip this into the build, then things work as expected. This is a little difficult because the upstream fixuid doesn’t automatically build arm64 packages. I manually built this version.


[Dockerfile.txt](https://github.com/cdr/code-server/files/4453150/Dockerfile.txt)
[fixuid-0.4-arm64.gz](https://github.com/cdr/code-server/files/4453151/fixuid-0.4-arm64.gz)

**Comment by kylecarbs** [comment]
Thanks @mbreese! We'll definitely fix this.

**Comment by nhooyr** [comment]
I'll close https://github.com/cdr/code-server/issues/1481 in favour of this.

**Comment by kylecarbs** [comment]
@code-asher is this fixed in latest?

**Comment by code-asher** [comment]
Negative, we need to build fixuid in the CI for arm64 or perhaps better would be to submit a PR to fixuid so they can have arm64 builds.

**Comment by nhooyr** [comment]
Should be really easy: https://github.com/boxboat/fixuid/blob/0ec93d22e52bde5b7326e84cb62fd26a3d20cead/pack.sh

**Comment by mbreese** [comment]
> Should be really easy: https://github.com/boxboat/fixuid/blob/master/build.sh

A PR for fixuid might not be as easy as you'd think. They hard code amd64 all over their build scripts and expect their filenames to match. Building fixuid in CI would probably be the quickest option... but this is should be do-able.

**Comment by nhooyr** [comment]
https://github.com/boxboat/fixuid/pull/23

**Comment by nhooyr** [comment]
Let's give them a few days to respond.

If not you can go ahead and work on this @mbreese

The travis servers do not have Go but have docker.

You'd want to build fixuid in a docker container in https://github.com/cdr/code-server/blob/8608ae2f08ef1d4cc8ab2bc1d90633b018a4f41b/ci/release-image/push.sh#L16 and inject it into the image and adjust the image to use it instead of the fixuid binary it fetches from the releases.

**Comment by caleblloyd** [comment]
I revamped the `fixuid` CI & release process in https://github.com/boxboat/fixuid/pull/25, if you need any more arch released it should be real easy going forward!

**Comment by nhooyr** [comment]
Awesome thanks @caleblloyd

**Comment by nhooyr** [comment]
Fixed in latest docker image.

You don't need the extra `-arm64` anymore, the latest image is multi arch!
