### ISSUE TITLE
Version information is not displayed in About pane

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#1506]
Reports itself as 
```
Version: 1.43.2
Commit: 5aded14b87e017d32d080b686515f6a26be455f1
Date: 2020-04-09T19:12:56.263Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 Edg/80.0.361.111
```
![image](https://user-images.githubusercontent.com/10422110/78952590-f0aa7580-7a8a-11ea-9f43-0314344abbc5.png)

**Comment by cstrat** [comment]
Yeah I noticed that too. Doesn't have the code-server version on display in there anymore.

**Comment by kylecarbs** [comment]
Will fix! cc: @code-asher

**Comment by code-asher** [comment]
True, that's just the VS Code about panel so it only displays the VS Code version. Should we insert the code-server version into there again? I was trying to reduce patching that didn't seem necessary.

**Comment by kylecarbs** [comment]
I think it'd be a good user experience, primarily because we'll show updates through that pane.

**Comment by Merith-TK** [comment]
We don't want some one to accidentally thing this is a official project.
Also it would be handy for developers to debug an issue, with a specific
version
