### ISSUE TITLE
Disabled in this document by feature policy inside iframe

### ISSUE THREAD

**Issue by rohinrohin** [cdr/code-server#1509]
Hi, 
A couple of our users are facing this issue where we have code-server embedded inside and iframe. It was working fine for a month or so now. 

But recently this issue has started repeating. Any idea on how we can resolve this?

Any help is appreciated. 
Thanks!

**Comment by rohinrohinsa** [comment]
I can confirm that the latest Chro.e update v81(April release) has caused the copy paste feature to break.

**Comment by kylecarbs** [comment]
Will look into this. Thanks!

**Comment by kylecarbs** [comment]
Is this only inside an iframe?

**Comment by rohinrohinsa** [comment]
Yeah only inside an IFrame.

**Comment by code-asher** [comment]
Maybe it's https://github.com/cdr/code-server/issues/1401? If the site hosting the iframe has a different origin then the iframe itself.

**Comment by code-asher** [comment]
Er, nevermind, that would only be for logging in and this issue doesn't say anything about logging in.

**Comment by rohinrohin** [comment]
Hey - any updates on this issue? This is an issue in production for us and users are not able to copy/paste within an iframe.

**Comment by code-asher** [comment]
I haven't had a chance to try Chrome 81 or later yet but I wonder if something like this works:

```
<iframe src="https://example.com..." allow="document.write"></iframe>
```

https://developers.google.com/web/updates/2018/06/feature-policy#iframe

**Comment by code-asher** [comment]
Although that would only affect pasting. If copying also isn't working then I'm not sure. `document.write` seems to be the only related feature name. [Here are the names in the source](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/platform/feature_policy/feature_policy.cc;drc=ab90b51c5b60de15054a32b0bd18e4839536a1c9;l=138?originalUrl=https:%2F%2Fcs.chromium.org%2Fchromium%2Fsrc%2Fthird_party%2Fblink%2Frenderer%2Fplatform%2Ffeature_policy%2Ffeature_policy.cc).

**Comment by scarolan** [comment]
This is also affecting our users. We run code-server inside a container on the Instruqt platform, which apparently uses iframes for each tab in the learning environment.

**Comment by kylecarbs** [comment]
We'll be fixing this ASAP.

**Comment by kylecarbs** [comment]
Seems like there's not much we can do :(

https://github.com/w3c/webappsec-feature-policy/issues/322

**Comment by dway123** [comment]
Sorry, I suspect this was caused by https://crbug.com/1074489, which we're working on fixing right now.

**Comment by scarolan** [comment]
Hello friends.  @kylecarbs you indicated that this is an upstream issue.  @dway123 any progress on a fix?

**Comment by OliverwengFiltered** [comment]
@dway123 any updates on the fix?
we are experiencing the same.

**Comment by dway123** [comment]
Any updates will be available at https://crbug.com/1074489.

**Comment by dway123** [comment]
A fix is now merged to Chrome M85+. Feature policies `clipboard-read` and `clipboard-write` may be used to control the Clipboard API in iframes. For more information, please see https://crbug.com/1074489.

**Comment by rberlind** [comment]
We seem to be seeing this problem starting today again in Chrome 84 accessing Instruqt.

**Comment by rberlind** [comment]
I upgraded Chromse to 85 today and still see same issue.

**Comment by OliverwengFiltered** [comment]
> I upgraded Chromse to 85 today and still see same issue.

I didn't try but I think you need to add feature-policy in iframe with value "clipboard-read" , chrome v85 gives the ability for you to add the clipboard-read as the feature policy, but it doesn't allow it automatically.
Let me know how it goes.

**Comment by rberlind** [comment]
Thanks @OliverwengFiltered.  But the website I'm using is outside my control.  Or I should say, I am embedding something into a learning platform. They control the parent windows while I am inserting VSCode Editor into a tab.

**Comment by OliverwengFiltered** [comment]
> Thanks @OliverwengFiltered. But the website I'm using is outside my control. Or I should say, I am embedding something into a learning platform. They control the parent windows while I am inserting VSCode Editor into a tab.

Hi @rberlind , I just tested, it works in chrome v85 if you add an additional property into iframe tag like below

```html
<iframe allow="clipboard-read;">...</iframe>
```

however you do need ability to change/access to the iframe tag code, which in your case, maybe a block here.

**Comment by rberlind** [comment]
Thanks for checking, @OliverwengFiltered

**Comment by nhooyr** [comment]
Glad this is now fixed. Cheers! 🍻
