### ISSUE TITLE
TypeScript and JavaScript language server dies and renders JavaScript functionality.

### ISSUE THREAD

**Issue by Abhid14** [cdr/code-server#1512]
Sorry to say but new issue Javascript and TypeScript language server and features are failing just after updating to 3.1.0 rendering editing JS & TS features nonfunctional. Rolling back to previous release.
Server is hosted on Google Cloud Shell.
![image](https://user-images.githubusercontent.com/34400585/79011237-3e090e80-7b81-11ea-8e94-ed3af2ff9bd8.png)

**Comment by kylecarbs** [comment]
Could you post additional console output? I'm not experiencing this issue.

**Comment by Abhid14** [comment]
> Could you post additional console output? I'm not experiencing this issue.

Ya sure one thing I on a fresh gcp account also did a fresh install still both ts & js is dead what's interesting is in new account I didn't get the notification that extensions are having error.
Here below is how it is on new account..On old account reports error in vscode but has no console message regarding this..... 
![image](https://user-images.githubusercontent.com/34400585/79253651-30b19400-7ea1-11ea-8f3a-84c5ecc0de13.png)

**Comment by jeromemeichelbeck** [comment]
I have the same issue, code-server is basically unusable with typescript.

Maybe it's the version of typescript that causes problems?

**Comment by Abhid14** [comment]
> I have the same issue, code-server is basically unusable with typescript.
> 
> Maybe it's the version of typescript that causes problems?
> Is there a way to change it in code-server?

Ya sure there is a way to change version but in my case there are issues with both JS & TS hope it will be fixed soon.

**Comment by jeromemeichelbeck** [comment]
> Ya sure there is a way to change version but in my case there are issues with both JS & TS hope it will be fixed soon.
 Oh great thank you! And how if I may ask?

**Comment by Abhid14** [comment]
> > Ya sure there is a way to change version but in my case there are issues with both JS & TS hope it will be fixed soon.
> > Oh great thank you! And how if I may ask?

Go through this page to fulfill your needs

https://stackoverflow.com/questions/39668731/what-typescript-version-is-visual-studio-code-using-how-to-update-it

**Comment by jeromemeichelbeck** [comment]
> Go through this page to fulfill your needs
> 
> https://stackoverflow.com/questions/39668731/what-typescript-version-is-visual-studio-code-using-how-to-update-it

Thanks a lot!

**Comment by code-asher** [comment]
I ran 3.1.0 in Google cloud shell but I haven't been able to replicate the issue. All I did was start cloud shell, download then run 3.1.0 with `--auth none`, then open a TypeScript file. Any ideas on other steps I can try that might trigger this behavior?

**Comment by Abhid14** [comment]
> I ran 3.1.0 in Google cloud shell but I haven't been able to replicate the issue. All I did was start cloud shell, download then run 3.1.0 with `--auth none`, then open a TypeScript file. Any ideas on other steps I can try that might trigger this behavior?

Okay in latest version all the functions I need are working great release I really loved it thank you coder team : ). I am closing the issue.
