### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by gregoryvanko** [cdr/code-server#1513]
if a would like to do "apply update" (code-server has an update: 3.1.0) I received the message "Update failed".
Where can I find logs to understand the problem?
how could I avoid this error?
<img width="472" alt="Capture d’écran 2020-04-10 à 22 22 57" src="https://user-images.githubusercontent.com/30236088/79020717-e024f880-7b79-11ea-80c8-ce2128431c2f.png">

**Comment by code-asher** [comment]
This is probably the bug in 3.0.2 where it would report the update failed even though it actually succeeded. Could you run `code-server --version` to verify the current version it's running?

**Comment by gavin-bd** [comment]
I got the same issue when running through docker:

coder@6356ebe4a4d3:~$ code-server --version
3.0.2 e480f6527e11344a7c69b7cd024bce9379cea7f0

**Comment by gregoryvanko** [comment]
Hi, thank you for the quick answer.
the commande "code-server --version"  doesn't work =>

gregoryweb@deb1:~$ code-server --version
-bash: code-server : commande introuvable

But with systemctl status code-server =>

gregoryweb@deb1:~$ systemctl status code-server
● code-server.service - code-server
   Loaded: loaded (/lib/systemd/system/code-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-04-10 22:13:28 CEST; 15h ago
 Main PID: 18649 (node)
    Tasks: 30 (limit: 4915)
   CGroup: /system.slice/code-server.service
           ├─18649 /var/www/code-server/code-server-3.0.2-linux-x86_64/node /var/www/code-server/code-server-3.0.2-linux-x86_64/out/node/entry.js --auth password
           ├─18659 /var/www/code-server/code-server-3.0.2-linux-x86_64/node /var/www/code-server/code-server-3.0.2-linux-x86_64/out/node/entry.js --auth password
           └─18670 /var/www/code-server/code-server-3.0.2-linux-x86_64/node /var/www/code-server/code-server-3.0.2-linux-x86_64/lib/vscode/out/vs/server/fork

I follow this tutorial to install code-server: https://www.digitalocean.com/community/tutorials/how-to-set-up-the-code-server-cloud-ide-platform-on-ubuntu-18-04-quickstart

here is my code-server.service file
[Unit]
Description=code-server
After=nginx.service

[Service]
Type=simple
Environment=PASSWORD=gregoryvk
ExecStart=/var/www/code-server/code-server-3.0.2-linux-x86_64/code-server --auth password
Restart=always
User=gregoryweb

[Install]
WantedBy=multi-user.target
------end

Some informations maybe useful:
- I use code-server trough HTTP (not yet trough HTTPS...)
- I had a lot of problems to install Extensions because of folder permission problems...

Thank you for your help

**Comment by MillikCN** [comment]
same issue when running through docker:
3.0.2 e480f65

**Comment by 4dams** [comment]
Same issue with DigitalOceans one click deployment.

**Comment by code-asher** [comment]
Interesting, so far I haven't been able to replicate. Here's what I've done (I'm running in a Docker container):

1. Download then run 3.0.2:
```
$ curl -fsSL https://github.com/cdr/code-server/releases/download/3.0.2/code-server-3.0.2-linux-x86_64.tar.gz | tar -xz
$ ./code-server-3.0.2-linux-x86_64/code-server --host 0.0.0.0
info  code-server 3.0.2 e480f6527e11344a7c69b7cd024bce9379cea7f0
info  HTTP server listening on http://0.0.0.0:8080
info    - Using custom password for authentication
info    - Not serving HTTPS
info  Automatic updates are enabled
info  SSH server listening on localhost:38193
```
2. Go to localhost:8080
3. Press "Apply Update"
4. Got "Update failed" (the bug I mentioned)
5. Go back to shell and check output
```
info  Relaunching: 3.0.2 -> 3.1.0
info  code-server 3.1.0 5aded14b87e017d32d080b686515f6a26be455f1
info  HTTP server listening on http://0.0.0.0:8080
info    - Using custom password for authentication
info    - Not serving HTTPS
info  Automatic updates are enabled
info  SSH server listening on localhost:34997
info    - To disable use `--disable-ssh`
```
6. Kill code-server and double-check the version
```
C-c 
$ ./code-server-3.0.2-linux-x86_64/code-server --version
3.1.0 5aded14b87e017d32d080b686515f6a26be455f1
```
As an aside, keep in mind 3.0.2 will delete the old directory so be careful if you have your own files in there. Starting from 3.1.0 code-server will move the directory instead of deleting it.

**Comment by gregoryvanko** [comment]
Ok for me. 

Thank you.

**Comment by rholland** [comment]
same problem for me running  one-click code-server on digital ocean.  I will try the fix above.
