### ISSUE TITLE
Image preview error when the path is not ASCII code

### ISSUE THREAD

**Issue by ynifamily3** [cdr/code-server#1514]
<img width="346" alt="스크린샷 2020-04-11 오전 7 54 37" src="https://user-images.githubusercontent.com/13795765/79028148-ee9b0080-7bc9-11ea-91cb-6bebbffaf63b.png">
<img width="482" alt="스크린샷 2020-04-11 오전 7 54 40" src="https://user-images.githubusercontent.com/13795765/79028154-f2c71e00-7bc9-11ea-91ef-ac1e7dc04245.png">
<img width="328" alt="스크린샷 2020-04-11 오전 7 55 16" src="https://user-images.githubusercontent.com/13795765/79028159-f8246880-7bc9-11ea-80be-f66370920376.png">
<img width="415" alt="스크린샷 2020-04-11 오전 7 55 18" src="https://user-images.githubusercontent.com/13795765/79028170-fc508600-7bc9-11ea-9233-4ea29200bfda.png">
If the path contains non-ASCII characters such as Hangul, an error occurs in the preview.

**Comment by kylecarbs** [comment]
Very strange. Does native VS Code have this issue?

**Comment by ynifamily3** [comment]
no, only this code-server has this issue.

**Comment by code-asher** [comment]
This was fixed with a VS Code update. :tada:
