### ISSUE TITLE
Notify v2 users of v3 update

### ISSUE THREAD

**Issue by YehudaEi** [cdr/code-server#1516]
Every time I try to update the version, I get this error and every time I manually update the version.
This time I was unable to update the version :(
What can be done to resolve this issue?

![image](https://user-images.githubusercontent.com/32451776/79055408-71b56880-7c55-11ea-8daa-fe4f2083991e.png)

**Comment by andgar2010** [comment]
> Every time I try to update the version, I get this error and every time I manually update the version.
> This time I was unable to update the version :(
> What can be done to resolve this issue?
> 
> ![image](https://user-images.githubusercontent.com/32451776/79055408-71b56880-7c55-11ea-8daa-fe4f2083991e.png)

+1

**Comment by code-asher** [comment]
Are you upgrading from v2 to v3?

**Comment by andgar2010** [comment]
> Are you upgrading from v2 to v3?

@code-asher 
yes
![image](https://user-images.githubusercontent.com/19521054/79142216-c6093700-7d80-11ea-9dca-0c9d39ac127e.png)

**Comment by code-asher** [comment]
v2 had a bug when decompressing the gzipped release which I believe is resolved in v3.

It's actually not possible to automatically update from v2 to v3 so it has to be down manually anyway. v3 is now distributed as a loose file release while v2 was packed into a single binary so v2 doesn't have the code required to handle that upgrade.

I wonder if we should build in something that lets us query an endpoint before trying an upgrade. That would let us send back a message like "v2 can't update automatically to v3" even though we didn't know back when we were working on v2 that would be the case.

**Comment by YehudaEi** [comment]
> Are you upgrading from v2 to v3?

my version is 2.1698-vsc1.41.1

**Comment by YehudaEi** [comment]
Sorry, I accidentally closed, and I think it really worthwhile to make an alert that can't be updated automatically ...

**Comment by kylecarbs** [comment]
Something we could do is release a new v2 that can be automatically updated that maybe notifies a user? Thoughts @code-asher

**Comment by code-asher** [comment]
That would be interesting. We could branch off old v2 and set up CI so it'll build releases off that branch as well. This would only help people who specifically download v2 from now on instead of v3 though?

**Comment by nhooyr** [comment]
We decided this isn't worth it since we removed automatic updates in v3 and have a much improved install process which will be on master soon.
