### ISSUE TITLE
missing option "--enable-proposed-api"

### ISSUE THREAD

**Issue by samuelcaldas** [cdr/code-server#1517]
please add the option "--enable-proposed-api" to work with unsigned extensions. it is not possible to use that flag while invoking the binary, results in "Unknown option --enable-proposed-api".

**Comment by kylecarbs** [comment]
Wil do, thanks for the report!

**Comment by code-asher** [comment]
I wonder if we should add something that will allow setting any VS Code flags, much like how Node has `NODE_OPTIONS`. `VSCODE_OPTIONS` maybe. Otherwise we might end up adding all the VS Code flags to code-server's flags (which might not be a bad thing, just something to consider).

**Comment by kylecarbs** [comment]
Yea I completely agree with that. Will create an issue.

**Comment by kylecarbs** [comment]
https://github.com/cdr/code-server/issues/1528

**Comment by samuelcaldas** [comment]
> Will do, thanks for the report!

any way to disable devmode in vscode?

**Comment by code-asher** [comment]
@samuelcaldas What is devmode?
