### ISSUE TITLE
Official Marko extensions

### ISSUE THREAD

**Issue by DylanPiercey** [cdr/code-server#1519]
Somewhat recently [Marko](http://markojs.com) got an official extension for VSCode however only the basic plugins / syntax highlighting are available on the code-server marketplace.

I've tested out the extension for over a month on my code-server instance and it seems to work fine.
Here is the extension: https://marketplace.visualstudio.com/items?itemName=Marko-JS.marko-vscode

Could this be enabled in the code-server marketplace?

**Comment by cmoog** [comment]
Thank you for the request. We've added `Marko VSCode` to the marketplace 👍
