### ISSUE TITLE
Add extension to marketplace

### ISSUE THREAD

**Issue by AdamZaczek** [cdr/code-server#1522]
Cheers guys! Awesome job with coder! We've been using it for a while and it's been working great for us! Could you add this extension to the marketplace:
https://marketplace.visualstudio.com/items?itemName=stroveio.stroveteams

Thanks from the whole strove.io team for the opensource contribution, we genuinely love what you're doing!

**Comment by cmoog** [comment]
Glad to hear you're enjoying the project. Unfortunately, at this time we require extensions in our marketplace to have a public Github repository from which we can build the `.vsix` artifact. For this reason, we cannot add `stroveteams`.

**Comment by AdamZaczek** [comment]
I made the repository public @cmoog  https://github.com/stroveio/stroveTeams
Can you reopen?

**Comment by cmoog** [comment]
Perfect. The extension is now live in our marketplace. Thanks!
