### ISSUE TITLE
Better doc on how to install and use code-server on a single machine

### ISSUE THREAD

**Issue by dclong** [cdr/code-server#1524]
There is almost no documention on how install and use code-server on a single machine. Plus that there are incompatible changes between code-server 2 and code-server 3, it is critical to have clear documentation for users who would like to customize code-server.

**Comment by blackinitial** [comment]
yeah, i confused to install and run code-server v3, last year i install v1 is easy.

**Comment by kylecarbs** [comment]
We've been meaning to add some documentation on the easiest deployment of code-server. cc: @nhooyr

**Comment by nhooyr** [comment]
Will take care of this with #1447

**Comment by nhooyr** [comment]
Done see https://github.com/cdr/code-server/blob/master/doc/guide.md
