### ISSUE TITLE
Unable to login with 3.1.0

### ISSUE THREAD

**Issue by gregoryvanko** [cdr/code-server#1527]
with the new version of code-server (3.1.0). it is not possible to login.
Javascript error on chrome browser:

DevTools failed to parse SourceMap: https://code.aaa.com/static/5aded14b87e017d32d080b686515f6a26be455f1/dist/app.css.map

Could you help me
Thank you

**Comment by kylecarbs** [comment]
cc: @code-asher

**Comment by gregoryvanko** [comment]
More info:
I can connect to code-server without auth (— auth none), but it is not a good practice...

**Comment by code-asher** [comment]
Are you using a reverse proxy? If so, this might help: https://github.com/cdr/code-server/issues/1507#issuecomment-613102477

**Comment by gregoryvanko** [comment]
Yes, and the solution works
proxy_set_header Host $host;

Thank you :-)
