### ISSUE TITLE
Keeps asking to update on freshly installed container

### ISSUE THREAD

**Issue by NotFluffy** [cdr/code-server#1533]
I keep getting the popup that I need to update.
I checked the docker repository, the image should already be on 3.1.1
Doing the update ends in a failure with no logs of what it did.

As said in https://github.com/cdr/code-server/issues/1506, I cannot check in the about section what version it actually is.

Might be linked to https://github.com/cdr/code-server/issues/1532

**Comment by Merith-TK** [comment]
what version are you running? 
![image](https://user-images.githubusercontent.com/10422110/79401134-1cbb7000-7f3d-11ea-8505-49d07635dafb.png)

just click copy to clipboard and paste it ehre

**Comment by briancsimonsen** [comment]
Seems to be a docker versioning issue. According to docker hub the version tagged as 'latest' corresponds to 3.0.2 so that just needs to be updated to tag 3.1.1 as 'latest' instead.

https://hub.docker.com/r/codercom/code-server/tags

**Comment by NotFluffy** [comment]
@briancsimonsen Thank you! I installed with 3.1.1 instead of latest and that took care of it.
