### ISSUE TITLE
I want to know how to python debug in code-server (Python extension install)

### ISSUE THREAD

**Issue by rungjoo** [cdr/code-server#1534]
I've been debugging python using code-server 2.x version on GCP.

When trying to build an environment on a new instance recently, I get the following error:
![20200416_170154](https://user-images.githubusercontent.com/48037590/79434773-d1bb5e80-8009-11ea-9d63-b19622df433d.png)

Same environment as before but ms.python.python is not installed.

What changes have been made to Python extensions? So how can I install python debug tool?

When looking for issues, it is said that debugging can be done by adding requirements.txt in the 3.x version.

However, in version 3.x, the code-server itself cannot be accessed. (I tried 3.0.2, 3.1.0, 3.1.1)
Or maybe we are running with ./code-server in 3.x version? (Unlike the 2.x version)
![20200416_174944](https://user-images.githubusercontent.com/48037590/79435494-b0a73d80-800a-11ea-8d03-36a926dd9bef.png)
Until this time, it was executed as shown in the picture and connected to http://{server_ip}:8000/. (server_ip: external IP, not 127.0.0.1)

**Comment by pr1metine** [comment]
You could try to install the Python extension [manually](https://github.com/microsoft/vscode-python/releases).

**Comment by code-asher** [comment]
I think our extension marketplace is supposed to choose a compatible version of the extension but it could be that this version predates our marketplace improvements.

Could you provide some details on how you're accessing v3? Does it show some kind of error in the browser console when you try to view it?

**Comment by rungjoo** [comment]
> I think our extension marketplace is supposed to choose a compatible version of the extension but it could be that this version predates our marketplace improvements.
> 
> Could you provide some details on how you're accessing v3? Does it show some kind of error in the browser console when you try to view it?

1. Go to the code-server-3.1.1-linux-x86_64 folder location in server.
2. Run sudo ./code-server --port 8000.
When I access http: // {server_ip}: 8000 in Chrome, it will appear on the screen as follows.
![20200417_085753](https://user-images.githubusercontent.com/48037590/79517608-a8daae00-8089-11ea-9b0d-1b022a461033.png)

However, it is not debugged in version 2.x, but it connects well to code-server.
![20200417_085928](https://user-images.githubusercontent.com/48037590/79517672-d58ec580-8089-11ea-98b9-885cddd68bd4.png)
![20200417_085956](https://user-images.githubusercontent.com/48037590/79517676-d7f11f80-8089-11ea-94c5-a0f3839bf3df.png)

**Comment by pr1metine** [comment]
Try running `sudo ./code-server --host 0.0.0.0 --port 8000` inside code-server-3.1.1-linux-x86_64

**Comment by rungjoo** [comment]
@pr1metine 
As you said, I can access code-server and install the python extension.

Thank you!

**Comment by pr1metine** [comment]
Nice, glad that I can be of use.
