### ISSUE TITLE
trouble running code-server 3.1.1 with workspace file

### ISSUE THREAD

**Issue by ppkwiatkowski** [cdr/code-server#1535]
Previously I was able to run code-server with workspace file as first argument (https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file).
It seems to no longer work in version 3.1.1

repro:
`./code-server test.code-workspace --auth none --open`

test.code-workspace:
```
{
  "folders": [
    {
      "path": "somepath"
    },
  ],
}
```

**Comment by lukasek86** [comment]
I confirm this regression. It must be quite recent. Version `3.0.2` works fine.

**Comment by code-asher** [comment]
Ahhh this was changed to align with the documented behavior but I didn't realize anyone knew a workspace could also be passed in since we hadn't documented it. I'll make this work again and add it to the docs.
