### ISSUE TITLE
workbench.api.js takes very long time to load in 3.1.1 and not cached properly on FireFox

### ISSUE THREAD

**Issue by marty1885** [cdr/code-server#1536]
Hi,

I've just updated code-server to 3.1.1. And I run my code-server on a remote server. I find the new code-sever taking fairly long (about 1.3 minute in my case). It seems to be caused by the long loading time of `workbench.api.js`. Furthermore on FireFox, this file although cached by FireFox; FireFox won't use the cache on the next load. Rendering opening code-server a waiting game.

Also, as a side note. My PC can connect to the server at ~30Mbits/s but `workbench.api.js` loads ~880Kbits/s. Which is quite slow.

(loading time of `workbench.api.js` on Chrome)
![image](https://user-images.githubusercontent.com/8792393/79474136-9edc8f00-8038-11ea-9d74-784b3e766902.png)

(FireFox loads the file every time)
![image](https://user-images.githubusercontent.com/8792393/79472998-1ad5d780-8037-11ea-8b7c-14fc0abdd191.png)
![image](https://user-images.githubusercontent.com/8792393/79473431-b23b2a80-8037-11ea-998a-1a6167262c10.png)

Best

OS: Arch Linux AArch64
VSCode: 3.1.1
Installed via PKGBUILD

**Comment by code-asher** [comment]
Maybe we should gzip any file that's over a certain size or just explicitly gzip the workbench file. 

You wouldn't happen to have "disable cache" checked in the Firefox dev tools, do you? (It's along the top near the `Filter URLs` text box.)

**Comment by marty1885** [comment]
No, I don't have cache disabled. (Otherwise I don't think it'd show up in FF's cached file list)

**Comment by code-asher** [comment]
I'm not sure; the checkbox might just prevent Firefox from using the cache rather than preventing it from storing into the cache. Could you verify whether the request has a `Cache-Control` header set? That's what we used to cache files so maybe it's not being sent somehow.

**Comment by marty1885** [comment]
My bad. FireFox sends `Cache-Control: max-age=0` when reloading. Forcing to reload everything.. Is there a way around that? Maybe send 304 Content Not Changed?

**Comment by nhooyr** [comment]
That's interesting, why would Firefox do that?

**Comment by marty1885** [comment]
I believe it's the default behaviour from the older ages of the web when the only reason to reload a page is because something is broken so the cache can't be trusted. And this behaviour seems to be the compliant one with RFCs.

Reference:
https://stackoverflow.com/questions/60902008/why-does-firefox-ignore-cache-headers-and-revalidate-on-refresh

**Comment by code-asher** [comment]
Ahh, that's very interesting. So going to the website again (typing it out, hitting a bookmark or a link, or hitting `enter` again in the URL bar) uses the cache but actually refreshing using the button, F5, etc will not use the cache.

**Comment by code-asher** [comment]
Fixed by https://github.com/cdr/code-server/pull/2680.
