### ISSUE TITLE
iPad app to access code-server over SSH

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1541]
This would be nice as then user's wouldn't need another form of authentication/encryption on top of SSH to access code-server.

**Comment by kylecarbs** [comment]
Like `sshcode` in an app?

**Comment by nhooyr** [comment]
Yes exactly.

**Comment by micodeyt** [comment]
I'd like to mention that @ColdGrub1384 is working on an iOS app (https://vseditor.app/), not sure how he manage authentication but it supports multiple app windows and local file opening, very interesting.

**Comment by ColdGrub1384** [comment]
@micodeyt To login, my app just does it as it would be done in Safari except that everything is setup so each user has access to its own files. A password is automatically generated by the app and that’s used to access the instance, just that the Web view fills automatically the password when it’s asked and doesn’t display the login screen but it’s loaded.

**Comment by GideonSenku** [comment]
> @micodeyt To login, my app just does it as it would be done in Safari except that everything is setup so each user has access to its own files. A password is automatically generated by the app and that’s used to access the instance, just that the Web view fills automatically the password when it’s asked and doesn’t display the login screen but it’s loaded.

On iPad Pro with New Magic Keyboard,Track scoll can't work,please fix it.

**Comment by cmoog** [comment]
> On iPad Pro with New Magic Keyboard,Track scroll can't work,please fix it.

@GideonSenku Please see #1455

**Comment by mbreese** [comment]
The way that I do this is to have code-server running on my server (Dockerized), but then put behind an Nginx front-end (for HTTPS/TLS). Nginx is setup to request username/passwords using HTTP-AUTH (using the subauth request module).

By using only a web server and HTTP-AUTH to manage the connection, I can then "Add to Home Screen" from the Safari sharing menu. (I don't entirely remember if the HTTP-AUTH authentication is required for saving to the Home Screen, but that's my recollection...)

This isn't as clean as accessing code-server over SSH, but it does remove the need for a separate iOS app.

**Comment by GalacticLion7** [comment]
A dedicated iPadOS app to use code-server would be really great. It would solve all o the optimization issues we were having while trying to use it on Safari.

**Comment by Troubadoure** [comment]
> A dedicated iPadOS app to use code-server would be really great. It would solve all o the optimization issues we were having while trying to use it on Safari.

And one that doesn’t use a subscription model. I may pay $2.99 for an app that could use my vscode server. But not $2.99 for something that connects to my own hardware.

**Comment by demyxco** [comment]
@Troubadoure the VSApp in the App Store? It's free for self hosted code-server.

**Comment by mbreese** [comment]
> > A dedicated iPadOS app to use code-server would be really great. It would solve all o the optimization issues we were having while trying to use it on Safari.
> 
> And one that doesn’t use a subscription model. I may pay $2.99 for an app that could use my vscode server. But not $2.99 for something that connects to my own hardware.

FYI - VS Code app doesn't cost anything to use if you connect it to your own self-hosted instance. They don't do a great job of explaining that on their site.

**Comment by Troubadoure** [comment]
@mbreese Ah thanks for pointing that out. Hadn’t realised that. I’ll take back my previous comment

**Comment by GalacticLion7** [comment]
#1822 might be a more effective solution for this issue.

**Comment by nhooyr** [comment]
Also see https://servediter.app/
