### ISSUE TITLE
Activity bar icons missing in Safari and Chrome

### ISSUE THREAD

**Issue by mrmarbury** [cdr/code-server#1543]
Maybe this has been posted already? It least I couldn't find anything helpful. So if this has a solution already, please point me into the right direction

Some base data:
OS: Centos 7 on FreeBSD 12.1 bhyve (centos has: HDD: 200G, CPUs: 4, Ram: 10G)
Code Server-Version: 3.1.1 running as user/group vscode

I use extensions like Docker or Project Manager which create icons in the activity bar. While the icons are shown in Firefox they are not shown in either Safari or Chrome. The Buttons are clickable though but do not have any icon image. All files have -r- or -rw- for the user/group running the server.
Is there some cache I have to truncate/build or some modification I have to do?
Thanks for help

**Comment by code-asher** [comment]
Hmm yeah it could be the browser cache. Have you tried clearing it? For example in Chrome if you open the devtools (F12) then right click the page refresh icon you'll see some new options one of which is "empty cache and hard reload".

**Comment by nhooyr** [comment]
@mrmarbury Feel free to comment if this is still happening and I'll reopen.
