### ISSUE TITLE
127.0.0.1 is not accessed from other devices

### ISSUE THREAD

**Issue by eduardopenedo** [cdr/code-server#1545]
When using version 2.1698-vsc1.41.1 of the code-sever in Termux on Android everything worked normally and access was made from any device on the network. 

![photo4974712975617271902](https://user-images.githubusercontent.com/32422845/80010929-85589e80-84a1-11ea-98fb-8b6e832da3e5.jpg)
![Anotação 2020-04-22 140316](https://user-images.githubusercontent.com/32422845/80011387-2fd0c180-84a2-11ea-8fa8-d79afd5961a9.png)

When updating the code-server to the current version (3.1.1) I can no longer access vscode, I only have access to ssh. To try to open port 8080 I tried to use ufw but termux without root does not let you modify the interfaces and network settings. 

![photo4974712975617271903](https://user-images.githubusercontent.com/32422845/80012272-6eb34700-84a3-11ea-8403-7c75e68841d0.jpg)(code server)
![image](https://user-images.githubusercontent.com/32422845/80012384-a621f380-84a3-11ea-9093-743ef8ce7fc4.png)(can't access vscode in pc)
![image](https://user-images.githubusercontent.com/32422845/80012597-ec775280-84a3-11ea-93f5-ba18b4a9a8e8.png)
(ssh working fine)

So, I realized that the problem occurs because the server address was changed from "localhost" to "127.0.0.1" and this is probably the cause of the reported problem

**Comment by cmoog** [comment]
Try setting the `--host` flag. I think that may solve the issue.

**Comment by eduardopenedo** [comment]
> Try setting the `--host` flag. I think that may solve the issue.

![photo4974712975617271904](https://user-images.githubusercontent.com/32422845/80014190-509b1600-84a6-11ea-907a-e0e2bc461f60.jpg)

when i try " code-server -- host localhost" nothing changes. When i try "code-server -- host localhost:8080" i get a error "ENOTFOUND"

**Comment by eduardopenedo** [comment]
> Try setting the `--host` flag. I think that may solve the issue.

Thank you very much, worked fine :)
![photo4974712975617271905](https://user-images.githubusercontent.com/32422845/80014776-29911400-84a7-11ea-9b40-150aa1e6580f.jpg)
![image](https://user-images.githubusercontent.com/32422845/80014897-5a714900-84a7-11ea-8a7d-46a79030c03b.png)
