### ISSUE TITLE
Bump extension version

### ISSUE THREAD

**Issue by AdamZaczek** [cdr/code-server#1547]
Hi!
Could you guys update this one in the marketplace https://marketplace.visualstudio.com/items?itemName=stroveio.stroveteams ?

Cheers!

**Comment by cmoog** [comment]
Please update the version listed in your [package.json](https://github.com/stroveio/stroveTeams/blob/92dae970da5c5f4e68a9aa9565589527fea9bf54/package.json#L5). 

Consider tagging releases via [git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) and/or [GitHub Releases](https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository).

**Comment by AdamZaczek** [comment]
I pushed the updated version and made a GitHub release as well.

**Comment by cmoog** [comment]
Perfect! `v0.1.1` is live in our marketplace.
