### ISSUE TITLE
Firefox Source Control file changes visual glitch

### ISSUE THREAD

**Issue by Pand9** [cdr/code-server#1549]
Firefox 75.0
Ubuntu 19.10 - Gnome 3 (default)
Code server - I was able to reproduce in a clean container from codercom/code-server:latest.

When highlighting or hovering over a file, the file name is invisible. See the screenshot: [A screenshot](https://i.imgur.com/JRsQIaY.png "A screenshot")

Chrome shows this correctly.

**Comment by code-asher** [comment]
I pulled `codercom/code-server:latest` but I haven't had luck replicating yet. Does it happen with all files or only in certain cases?

I'm on FF 74 though, maybe the problem only manifests in 75 onward? 

I remember this being an issue in the past, actually. Maybe you've got some old CSS cached in Firefox. 

It might also be worth double-checking the version by running `code-server --version` in the VS Code terminal (in case there's some Docker caching going on or something). I get:

```
3.0.2 e480f6527e11344a7c69b7cd024bce9379cea7f0
```

**Comment by Pand9** [comment]
Thanks for responding.

The same version as you.

> I pulled codercom/code-server:latest but I haven't had luck replicating yet. Does it happen with all files or only in certain cases?

Any files.
I've used one-liner from https://github.com/cdr/code-server to start a docker container, then clicked "initialize a repository". I think it initialized in $HOME as you can see on the screen. It happens with any of these files.

> I remember this being an issue in the past, actually. Maybe you've got some old CSS cached in Firefox.

Clearing cached data did not help.

**Comment by code-asher** [comment]
Ahhhhh I was looking at the explorer. I managed to completely miss the `source control` part of the issue title but `initialize a repository` made me realize I was looking at the wrong thing. Can confirm this is an issue.
