### ISSUE TITLE
Where is the Dockerfile?

### ISSUE THREAD

**Issue by ctlajoie** [cdr/code-server#1550]
I would like to make a slight modification (for uninteresting reasons), but in order to know how to extend it properly, I would need to see the Dockerfile that the `codercom/code-server` image is built from. I expected to find it in this repo...

**Comment by ctlajoie** [comment]
Ugh I found it in ci/release-image/Dockerfile

**Comment by maresb** [comment]
I had the same issue:

https://github.com/cdr/code-server/blob/master/ci/release-container/Dockerfile
