### ISSUE TITLE
Misplaced globalStorageHome

### ISSUE THREAD

**Issue by ben-z** [cdr/code-server#1551]
A `globalStorageHome` directory is created in the project root when I use the [VSCodeVim](https://github.com/VSCodeVim/Vim) extension.

```
> tree globalStorageHome/
globalStorageHome/
└── vscodevim.vim
```

[The VSCodeVim extension uses `context.globalStoragePath` to determine storage location](https://github.com/VSCodeVim/Vim/pull/4151/files). Did code-server misconfigure this location to be in the project root?

**Comment by code-asher** [comment]
Ah yeah I think I see the problem. vim runs in the browser and VS Code's worker extension host isn't capable of using the `globalStorageHome` value provided by the environment service yet, so we'll just have to patch that support in.

**Comment by zengming00** [comment]
This bug still exists when I deploy Code-Server on Linux and access it on Windows

**Comment by code-asher** [comment]
I spun up a 3.5.0 Docker image and when I use the vim extension and do something like `:w` it creates the global storage directory.

It doesn't seem to create it on startup though which is odd; I think it's supposed to do that so we might want to look into that.

Are there any specific errors you're running into?

**Comment by zengming00** [comment]
If I access it on windows, the value of 'context.globalStoragePath' will be:
`\home\admin\.local\share\code-server\globalStorage\vscodevim.vim`
If I access it on linux, the value of 'context.globalStoragePath' will be:
`/home/admin/.local/share/code-server/globalStorage/vscodevim.vim`

The code-server always runs on linux, so when I access it with a windows browser, the path separator of 'context.globalStoragePath' is wrong

**Comment by code-asher** [comment]
Ahh I see! I opened a new issue for this: https://github.com/cdr/code-server/issues/2093
