### ISSUE TITLE
Qualify code-server Docker Hub image as Docker Certified

### ISSUE THREAD

**Issue by GalacticLion7** [cdr/code-server#1552]
I think the code-server Docker Hub image should apply for Docker Certified qualification for the enterprise version. See the links below for more details.

https://docs.docker.com/docker-hub/publish/publisher_faq/#what-is-the-certification-program-for-containers-and-plugins-and-what-are-some-benefits
https://docs.docker.com/docker-hub/publish/certify-images/

**Comment by sr229** [comment]
I think it would greatly help this project in a way but @nhooyr would have a final say on this kinds of topics. Would love his say on this.

Personally it would be nice to be "Docker certified" but not all popular projects gets to get that advantage IMO. Theia for example, was not Docker-certified AFAIK.

**Comment by nhooyr** [comment]
We are actually a docker hub partner.

But docker hub won't let us certify an existing image, we'd have to publish a new one and we'd lose all our downloads and it'd cause a lot of confusion.

**Comment by sr229** [comment]
So does that mean certification is limited to new images only @nhooyr ?

**Comment by nhooyr** [comment]
Actually never mind I think I'm referring to something else, I think we should be able to certify an existing image.

**Comment by nhooyr** [comment]
@nathanpotter Can you look into this?

**Comment by GalacticLion7** [comment]
I need to clear something up. I am not interested for the code-server Docker Hub image to be Docker Certified, just a [Docker Official Image](https://docs.docker.com/docker-hub/official_images/). Docker Certified is something for enterprises. I got confused between the two terms.

**Comment by GalacticLion7** [comment]
You could qualify it as Docker Certified so enterprises could benefit from it, though. But for community users, a Docker Official Image is what we need.

**Comment by sr229** [comment]
@GalacticLion7 Having certified and official might be a good thing, because Coder's business is also providing SaaS for the enterprise.

**Comment by GalacticLion7** [comment]
> @GalacticLion7 Having certified and official might be a good thing, because Coder's business is also providing SaaS for the enterprise.

I thought so. I reverted the changes I did to this issue, and I [made a new issue for it](#1815) for what I want.

**Comment by GalacticLion7** [comment]
#1815

(did not reference)
