### ISSUE TITLE
Add helper script for DO Marketplace image

### ISSUE THREAD

**Issue by GalacticLion7** [cdr/code-server#1553]
The code-server DigitalOcean Marketplace image should ship with a helper script, like many other images there, that lets users use their domain name, generate a Let's Encrypt, etc.

**Comment by nhooyr** [comment]
We've deprecated the DO marketplace image in favour of a setup guide.

See https://github.com/cdr/code-server/blob/master/doc/guide.md

**Comment by nhooyr** [comment]
https://github.com/cdr/code-server/issues/1654
