### ISSUE TITLE
Need 2FA Authenticator

### ISSUE THREAD

**Issue by najgit** [cdr/code-server#1556]
Hello is it possible to integrate --auth to use PASSWORD + Google Authenticator 2FA option, to help more secure to access the editor

**Comment by nhooyr** [comment]
See the FAQ.

https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-should-i-expose-code-server-to-the-internet

Best option is to use a reverse proxy that supports this like Cloudflare or https://github.com/oauth2-proxy/oauth2-proxy
