### ISSUE TITLE
Compound debug configuration launching in one terminal

### ISSUE THREAD

**Issue by arseniybanayev** [cdr/code-server#1557]
I use the Python extension to debug Python projects and have some Flask and Quart apps that I like to debug together in a compound configuration (using `flask run...` and `quart run...`). Occasionally, especially after the first run of the compound configuration, the configurations all try to run in the same `Python Debug Console` terminal window, e.g.:

```
root@81bf691c0b5a:/code#  env DEBUGPY_LAUNCHER_PORT=46663 /opt/conda/envs/my_env/bin/python /root/.local/share/code-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/launcher -m quart run -h 0.0.0.0 -p 5000 
 env DEBUGPY_LAUNCHER_PORT=44851 /opt/conda/envs/my_env/bin/python /root/.local/share/code-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/launcher -m flask run -h 0.0.0.0 -p 5002 
 env DEBUGPY_LAUNCHER_PORT=38913 /opt/conda/envs/my_env/bin/python /root/.local/share/code-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/launcher -m flask run -h 0.0.0.0 -p 5001 
 env DEBUGPY_LAUNCHER_PORT=45271 /opt/conda/envs/my_env/bin/python /root/.local/share/code-server/extensions/ms-python.python-2020.3.69010/pythonFiles/lib/python/debugpy/wheels/debugpy/launcher -m quart run -h 0.0.0.0 -p 5003 
```

Of course, this does actually launch multiple configurations; the first one (random) launches and the others wait for the exit code of the previous one(s). Also, the debugger then complains of a timeout attaching to the subsequent ones that never start.

Expected behavior is to launch a separate `Python Debug Console` terminal window for each configurtion.

I just try it a few times, and after a few times, it behaves as expected one time, and then I have to repeat.

**Comment by arseniybanayev** [comment]
Has anyone seen this issue?

**Comment by code-asher** [comment]
I haven't had a chance to test this yet. A few questions:
- What version of code-server are you running? 
- Do you know if this works as expected in local VS Code? 
- Would you be able to provide an example I can use to replicate the issue?

**Comment by arseniybanayev** [comment]
I'm currently running 3.2.0 in a Docker `ubuntu:18.04` container. I have actually never used official VS Code as a standalone application - went straight to you guys :)

Try this example, but it is non-deterministic from my experience. I would expect it to happen within 10 times`
1. Install the `ms-python.python` extension
2. `pip install flask`
3. Add the `flask.py` file below three times into the workspace directory as `flask_1.py`, `flask_2.py` and `flask_3.py`
4. Add `launch.json` to `.vscode/launch.json`
5. Launch the `compound` configuration

When the bug hits, there will be just 1 new `Python Debug Console` open, instead of 3, and it will try to launch all 3 configurations in the one window as separate commands, of course causing the 2nd and 3rd to wait for exit of the 1st. What you will see in that 1 `Python Debug Console` is at the bottom of this post.

`flask.py`
```
import flask
import os

app = flask.Flask(__name__)
app.config.from_mapping({
    'ENV': os.environ['FLASK_ENV'],
    'DEBUG': os.environ['FLASK_DEBUG'],
    'TESTING': os.environ['FLASK_TESTING']
})

@app.route('/hello')
def world():
    return flask.jsonify(which='1')
```

`launch.json`
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "flask-1",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "args": [
                "run"
            ],
            "env": {
                "FLASK_APP": "flask-1:app",
                "FLASK_ENV": "development",
                "FLASK_DEBUG": "1",
                "FLASK_TESTING": "False",
                "SECRET_KEY": "398ouhgny7981ohu3urqye7f8goih13"
            },
            "subProcess": true
        },
        {
            "name": "flask-2",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "args": [
                "run"
            ],
            "env": {
                "FLASK_APP": "flask-2:app",
                "FLASK_ENV": "development",
                "FLASK_DEBUG": "1",
                "FLASK_TESTING": "False",
                "SECRET_KEY": "398ouhgny7981ohu3urqye7f8goih13"
            },
            "subProcess": true
        },
        {
            "name": "flask-3",
            "type": "python",
            "request": "launch",
            "module": "flask",
            "args": [
                "run"
            ],
            "env": {
                "FLASK_APP": "flask-3:app",
                "FLASK_ENV": "development",
                "FLASK_DEBUG": "1",
                "FLASK_TESTING": "False",
                "SECRET_KEY": "398ouhgny7981ohu3urqye7f8goih13"
            },
            "subProcess": true
        }
    ],
    "compounds": [
        {
            "name": "compound",
            "configurations": [
                "flask-1",
                "flask-2",
                "flask-3"
            ]
        }
    ]
}
```

`Python Debug Console`
```
(my-env) root@86fc236454d4:/my-workspace#  env DEBUGPY_LAUNCHER_PORT=34271 /opt/conda/envs/my-env/bin/python /root/.local/share/code-server/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/debugpy/wheels/debugpy/launcher -m flask run 
 env DEBUGPY_LAUNCHER_PORT=42273 /opt/conda/envs/my-env/bin/python /root/.local/share/code-server/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/debugpy/wheels/debugpy/launcher -m flask run 
 env DEBUGPY_LAUNCHER_PORT=40045 /opt/conda/envs/my-env/bin/python /root/.local/share/code-server/extensions/ms-python.python-2020.4.76186/pythonFiles/lib/python/debugpy/wheels/debugpy/launcher -m flask run 
 * Serving Flask app "flask-2:app" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 170-427-968
```

**Comment by code-asher** [comment]
It's been a long time coming but I finally tested this and can confirm the behavior.

I was able to replicate in local VS Code (1.45.1) as well so it looks like this is an upstream bug. So far every time I get one session running and the other two time out.

I don't have the same problem with Node so I wonder if it's an issue with the extension.
