### ISSUE TITLE
A valid git installation was not detected ( But i already have git version 2.17.1 )

### ISSUE THREAD

**Issue by Dj-jom2x** [cdr/code-server#1558]
how to fix this? 

![image](https://user-images.githubusercontent.com/12135498/80315011-8c780780-8827-11ea-819d-45b6bf1a877b.png)

if I look at the output it says,

```
Looking for git in: git
Git installation not found.
````

**Comment by Dj-jom2x** [comment]
nevermind i just add this to settings.json

```
{
    "git.path": "/usr/bin/git",
}
```

**Comment by Dj-jom2x** [comment]
closed!

**Comment by sheramidii** [comment]
thank you! this is my first time coding and this helped me!

**Comment by victor-komolafe** [comment]
thank you... it worked
