### ISSUE TITLE
Jira and BitBucket extension doesn't work

### ISSUE THREAD

**Issue by bhargavim613** [cdr/code-server#1559]
Jira and BitBucket Official Extension  , which is supported by Vscode version 1.40 and later isnt available , when using this Code server VScode. Please resolve this issue.

The following link is about the extension i was talking about

https://marketplace.visualstudio.com/items?itemName=Atlassian.atlascode

**Comment by cmoog** [comment]
Thank you for bringing this to our attention. The extension is now live in our marketplace.

**Comment by bhargavim613** [comment]
which marketplace?? can u please share the url of the extension?

**Comment by nhooyr** [comment]
@cmoog See https://github.com/cdr/code-server/issues/1572

**Comment by bhargavim613** [comment]
@cmoog So, what is an alternative provided?

**Comment by bhargavim613** [comment]
@nhooyr Whats the alternative provided?

**Comment by cmoog** [comment]
@bhargavim613 Updating your version of code-server will resolve the issue.

**Comment by nhooyr** [comment]
@bhargavim613 Please stop spamming.

**Comment by nhooyr** [comment]
@bhargavim613 Feel free to ping me here if this wasn't resolved by @cmoog's suggestion.

**Comment by wjziv** [comment]
Hey, I'm looking to confirm the validity in the Issue's title statement.

I'm having trouble with the Official Atlassian Jira extension, which shows the following upon starting set-up:
> Authentication cannot be done while running remotely.
> To authenticate with a new site open this (or another) workspace locally. Accounts added when running locally will be accessible during remote development.

The phrasing of "open this workspace locally" threw me for a loop, as I'm already running code-server on my machine. Is set-up not possible within code-server?

**Comment by code-asher** [comment]
Ah yeah code-server implements the remote portion of VS Code so it would be the same as if you installed VS Code remote and pointed it to your local machine. Unfortunately there's no detection mechanism in place for seeing if a remote instance is running local to the browser accessing it.

The best way around this would be if the extension supported a remote workflow but for now I think you'll have to authenticate once in local VS Code. :(

**Comment by andre-vspry** [comment]
I found you can click the login buttons on the onboarding page shown once on start. If you didn't do that you can bring it up again with a ctrl+P and search for onboarding.

**Comment by phiiaz** [comment]
I tried that. Still does not let me log in.

I also I notice the version on codeserver marketplace is behind.

**Comment by phiiaz** [comment]
Contacted the Atlascode team (They are working on the Jira and Bitbucket plugin). They are working on the issue of supporting the VS cloudspace.  here is the [ticket](https://bitbucket.org/atlassianlabs/atlascode/issues/429/can-not-login-into-bitbucket-cloud-from) to follow.

**Comment by dsehrawat** [comment]
> The best way around this would be if the extension supported a remote workflow but for now I think you'll have to authenticate once in local VS Code. :(

Can someone please explain how to authenticate "once in local VS Code"? 
I am running code-server in the cloud on a Ubuntu server (EC2 machine). Is there a way to authenticate VS Code (Atlassian VSCode extension) against Bitbucket? A command line option would be great if any.

**Comment by code-asher** [comment]
One way is to launch VS Code locally, authenticate with the extension, then copy up the VS Code data directory to your remote server so code-server can use it. I haven't tested this myself but I think it should be as simple as copying the local `~/.vscode` directory to the remote `~/.local/share/code-server` directory although it's possible the authentication info is stored somewhere else.

I don't know if this extension handles authentication in the same way as the GitHub extension, but if it's similar then this comment might help to find an alternate workaround: https://github.com/cdr/code-server/issues/1883#issuecomment-659836909

**Comment by dsehrawat** [comment]
Thanks for the quick reply. 
I tried the first approach to authenticate the extension locally and then copying ~/.vscode/extensions directory to the remote location (~/.local/share/code-share/extensions). But it did not work. 

Doesn't it use 'keytar' to store auth token / passwords rather than some file?
Can we manually update this info in the keytar somehow?

**Comment by code-asher** [comment]
Ahhhh yeah you're right, I checked the extension code and it seems they save the credentials using keytar.

I'm not sure if you can copy the keychain but one idea would be to manually get and save the credentials:
```
cd /path/to/code-server/lib/vscode
node -e 'require("keytar").findPassword("atlascode-authinfoV3") // run on the local machine
node -e 'require("keytar").setPassword("atlascode-authinfoV3", account, password) // run on the remote machine
```

But I'm not sure it'll work. On my remote machine keytar doesn't seem to work at all because of dbus issues.

**Comment by code-asher** [comment]
Correction: it would be `findCredentials`, not `findPassword`. https://www.npmjs.com/package/keytar#findcredentialsservice

**Comment by dsehrawat** [comment]
That was smart thought. 
But the problem is even if I could authenticate a bitbucket account on a local system (using vscode), it is still asking for authentication on running code-server on the same local system. 

Although it shows on the following on the UI:
"_Authentication cannot be done while running remotely. To authenticate with a new site open this (or another) workspace locally. Accounts added when running locally will be accessible during remote development._".

I can see that the bitbucket account key has been deployed in "password and keys" with "service: atlascode-authinfoV3". But still the code-server can not access it or is not using it.

Not sure what else to try !!! Any suggestion?

**Comment by nhooyr** [comment]
> Authentication cannot be done while running remotely.

Sounds like the extension does not allow you to use it while being accessed via a browser?

**Comment by blaylockbk** [comment]
@cmoog Would an updated extension help the Bitbucekt extension to work? My local vscode says the extension version is **2.8.5**, but code-server has version **v2.4.11-tlsh**

VS Code
![image](https://user-images.githubusercontent.com/6249613/100003030-50cffc80-2d7a-11eb-8c8d-6cb0046b1004.png)

code-server
![image](https://user-images.githubusercontent.com/6249613/100003053-56c5dd80-2d7a-11eb-8cea-506cb5715180.png)

**Comment by code-asher** [comment]
I can't say for sure since I haven't tested the latest version but I
suspect it will have the same problem. Definitely worth testing though.

**Comment by nimda95** [comment]
So here is a simple trick you will change in the bitbucket extension code
P.S Tested on version extension 2.8.5, and working for now.

You go to `~/.local/share/code-server/extensions/atlassian.atlascode-VERSION.NUMBER/build/extension/extension.js` and find the function named `getIsRemote`, you will change the condition there with false (I found the function to be declared twice).

Now reload your vs-code window (didn't have to restart the code-server server), voilà, you will have the button to athenticate now enabled.

Click on that auth button, follow the procedure as usual, and at the end you will come at a `http://127.0.0.1:<int>/bbcloud?state=<string>&code=<string>`, just copy-it and run-it using `curl` or whatever you like (e.g `wget`) in the vscode terminal (if you are running your instance locally, normally it should go ahead normally, but if it's in a container or cloud server as I have ... well, you know the rest of the story).

Congrats, It should be now authenticated.

Message to Atlassian : just please remove the remote verification from the code, we are dev, we'll know what we're dealing with.

**Comment by marsinearth** [comment]
while following the above tip of @nimda95, couldn't  open extensions.js with emacs. don't know why. could open uninstall.js which is 3.8mb but can't open extensions.js which is 4.1mb with emacs with waiting for a long time. the Jira and Bitbucket extension version is v2.4.11-tlsh.

**Comment by MitchTalmadge** [comment]
Thank you @nimda95 for this trick. It worked perfectly.
