### ISSUE TITLE
Closed issue haven't been resolved yet

### ISSUE THREAD

**Issue by bhargavim613** [cdr/code-server#1564]
Could u share the url of the extension and the marketplace

**Comment by code-asher** [comment]
For https://github.com/cdr/code-server/issues/1559 yeah? If you search `@id:Atlassian.atlascode` in the extension sidebar it'll show up.

Our marketplace URL is https://extensions.coder.com but there are no front-facing pages for it at the moment so it's really only meant to be used from code-server.

**Comment by bhargavim613** [comment]
@code-asher the extension u added up isnt working eventhough its compatible, its giving a prompt of not compatible. Please look into it
![cdrissue](https://user-images.githubusercontent.com/52404926/80524377-20271080-89ad-11ea-9fda-f32afaef923d.JPG)

**Comment by code-asher** [comment]
Would you be able to update code-server to 3.1.1?
