### ISSUE TITLE
[mobile] Delete key not working

### ISSUE THREAD

**Issue by vonAlenberg** [cdr/code-server#1565]
Started a minimal code-server via docker, accessing it on mobile (OP7Pro), but neither Chrome nor FF allows to delete text once it is typed.

**Comment by SharifPoetra** [comment]
Same issue here! The delete key is not working. But when I click the key `5`, its working like what dekete key should do!

**Comment by nhooyr** [comment]
Unfortunately very likely some bizarre upstream issue with VS Code web.
