### ISSUE TITLE
How to disable password to use code-server?

### ISSUE THREAD

**Issue by sgnd** [cdr/code-server#1567]
I installed code-server, on my own VPS. But, I disable Environment for PASSWORD and I don't want to use it. How to disable or bypass the password? so, anyone can access my editor. 

For information: my VPS is a private server.

```
Unit]
Description=code-server
After=nginx.service

[Service]
User=samdon
WorkingDirectory=/home/samdon
# Environment=PASSWORD=
ExecStart=/home/samdon/bin/code-server --host 0.0.0.0 --port 3003 --user-data-dir /home/samdon/data 
# --auth password
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by binari** [comment]
Change  `--auth password` to ` --auth none`, that should fix it

**Comment by nhooyr** [comment]
See the FAQ: https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-should-i-expose-code-server-to-the-internet

**Comment by loheagn** [comment]
> See the FAQ: https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-should-i-expose-code-server-to-the-internet

This link is 404.

**Comment by jsjoeio** [comment]
@loheagn https://coder.com/docs/code-server/latest/FAQ#how-should-i-expose-code-server-to-the-internet
