### ISSUE TITLE
Referring #1559

### ISSUE THREAD

**Issue by bhargavim613** [cdr/code-server#1572]
@code-asher the extension u added up isnt working eventhough its compatible, its giving a prompt of not compatible. Please look into it
![cdrissue](https://user-images.githubusercontent.com/52404926/80524377-20271080-89ad-11ea-9fda-f32afaef923d.JPG)

_Originally posted by @bhargavim613 in https://github.com/cdr/code-server/issues/1564#issuecomment-620783415_

**Comment by nhooyr** [comment]
@bhargavim613 Please stop opening new issues and reuse the first one.
