### ISSUE TITLE
Glitch Extension Request

### ISSUE THREAD

**Issue by abhay-ranawat** [cdr/code-server#1573]
Hey Can you Bring Glitch VS code Extension 
https://github.com/vscode-glitch/vscode-glitch/
https://marketplace.visualstudio.com/items?itemName=glitch.glitch

The Extension can be installed using VSIX file but i think it can write data , because it doesn't work after logging in

**Comment by cmoog** [comment]
Thank you for your request. Correct me if I'm wrong, but it looks like the extension does not release its source code and does not publish the `.vsix` bundles in its repository releases. Unfortunately, this means we cannot publish the extension in our marketplace at this time. 

The VSCode Terms of Service restrict our use of the bundles available [here](https://marketplace.visualstudio.com/items?itemName=glitch.glitch) .
