### ISSUE TITLE
not able to find project folder in docker exec bin/bash

### ISSUE THREAD

**Issue by sanjayme97** [cdr/code-server#1576]
Hi I have deployed code-server in Azure and I need to run git commands while container is running.So after container is started I have used `az container exec -g group_name -n container_name --exec-command "/bin/bash"` and try to run commands but  if I run `ls` or `cd`  its not showing any folder.If I run `pwd` it shows home/coder. So I need to go inside project folder but its not showing it. @code-asher @kylecarbs @deansheather  kindly help here
![image](https://user-images.githubusercontent.com/45826938/80672969-ad608700-8acb-11ea-8ab4-8fc3f418f67c.png)

**Comment by sanjayme97** [comment]
I don know how but project folder was not there so I created it.

**Comment by code-asher** [comment]
We don't create that directory so that makes sense. You might be thinking of the Docker command we have in our readme:
```
docker run -it -p 127.0.0.1:8080:8080 -v "$PWD:/home/coder/project" -u "$(id -u):$(id -g)" codercom/code-server:latest
```
This mounts the current directory to `/home/coder/project` in the Docker container, so you might want to do something similar in order to persist your data.
