### ISSUE TITLE
Cant change Layout

### ISSUE THREAD

**Issue by Troubadoure** [cdr/code-server#1578]
When I select 'Layout' in the bottom right hand corner of the screen and select 'British' the Layout stays on US

**Comment by L3P3** [comment]
Auto-detect seems to be always on, US being the default.
When I set the Layout to German, nothing is happening.
My solution is to press some German-only keys like ÄÖÜ. Then, it detects "Swiss German".
When I press ß then, it properly detects my layout as "German".
