### ISSUE TITLE
Upgrade via notification breaks systemd service

### ISSUE THREAD

**Issue by kalikiana** [cdr/code-server#1580]
- I got a notification saying "There's an update available, press to Update".
- My systemd unit failed. `code-server.service: Start request repeated too quickly.`
- **EDIT**: I had to update the folder name to `.1588265231799`.
- After a manual restart it ran fine again.

I'm not sure this is a bug in code-server or an issue with running it as a systemd service.

My unit for reference:

```systemd
[Unit]
Description=VSCode server
[Service]
ExecStart=%h/dev/code-server-3.1.1-linux-x86_64/code-server --host 127.0.0.1 --disable-ssh %h/dev
Restart=always
[Install]
WantedBy=default.target
```

**Comment by AlaaElrifaie** [comment]
Version 3.2.0 has replaced --host and --port with `--bind-addr`.
Just edit your service to run with the `--bind-addr 127.0.0.1:8080` argument and it would work again.

**Comment by nhooyr** [comment]
To clarify, `--host` and `--port` still work, they've only been removed from docs o everything should work.

**Comment by nhooyr** [comment]
@code-asher I definitely think we should just remove automatic updating based on this issue and the other one and with the node package/debs coming.

**Comment by Grimeton** [comment]
> To clarify, `--host` and `--port` still work, they've only been removed from docs so everything should work.

I got error messages as well using --host and --port.

**Comment by code-asher** [comment]
Ah it might be that `--disable-ssh` was removed, so code-server will error if that's provided.

**Comment by code-asher** [comment]
To further explain, `.1588265231799` is the old code-server directory (we move it to prevent potential data loss), so using it will use the old version which is why it'll work.

**Comment by nhooyr** [comment]
`--host` and `--port` work for me @Grimeton

**Comment by code-asher** [comment]
Same here, running latest master. Do the errors specifically say "unknown option: --host" or something like that?

**Comment by kalikiana** [comment]
> Ah it might be that `--disable-ssh` was removed, so code-server will error if that's provided.

That was it! I missed that before. Admittedly trying to get back up and running quickly didn't help.

`Unknown option --disable-ssh`

So I changed it back to the original folder and dropped the option and 3.2 runs like a charm now!

**Comment by nhooyr** [comment]
Sweet.
