### ISSUE TITLE
Code-server refreshing again and again in browser

### ISSUE THREAD

**Issue by ansarizafar** [cdr/code-server#1581]
Code-server refreshing again and again in browser after I installed Dot net 5 preview 3 here is the terminal output

![image](https://user-images.githubusercontent.com/5788284/80740725-f8ad8080-8b31-11ea-8bf0-4d81993bd27f.png)

**Comment by code-asher** [comment]
Is there anything in the browser console?

**Comment by ansarizafar** [comment]
Yes VS code UI appears in the browser and continuously page refreshes again and again.  I have solved this problem by recreating the workspace.

**Comment by code-asher** [comment]
I'm able to replicate by creating a workspace with three directories in it (not sure yet if the number of directories matters) so I'll take a look and see what's going on.

**Comment by ansarizafar** [comment]
I also have three folders in workspace. Everything was working till I installed Dot net 5. Now my workspace has two folders.
