### ISSUE TITLE
Extension Request (Markdown Extended)

### ISSUE THREAD

**Issue by IJuanI** [cdr/code-server#1584]
Could you add [Markdown Extended](https://marketplace.visualstudio.com/items?itemName=jebbs.markdown-extended) to your marketplace?

Here's the github repo: https://github.com/qjebbs/vscode-markdown-extended

**Comment by cmoog** [comment]
It seems I'm having a difficult time building the `.vsix` successfully from the source code. Are you able to provide a procedure that works?

**Comment by IJuanI** [comment]
The `.vsix` can be downloaded from visual studio's marketplace
https://marketplace.visualstudio.com/items?itemName=jebbs.markdown-extended

I'll give it a try on building it from github. If success, will replay with steps to reproduce.

Please let me know if the prebuilt version is enough for adding the extension

**Comment by cmoog** [comment]
Unfortunately, redistribution of release artifacts from the Visual Studio marketplace is prohibited by Microsoft's terms of use.

**Comment by IJuanI** [comment]
Took me a while, but got to build it!

Dependencies are quite messed up, 
- Root `tsconfig.json` is missing `dom` lib.
- `package-lock.json` has wrong `@types/puppeteer` version locked. You should erase it's entry from the lock file before installing. I replaced it with version `1.20.4`.
- You need to manually edit `@types/markdown-it`'s `index.d.ts`.
Replace `Rule` definition (line 99 of `node_modules/@types/markdown-it/index.d.ts` with
```javascript
    interface Rule {
        (state: any, startLine: number, endLine: number, silent: boolean): void;
    }
```

Let me know if you get any further issue with boundling the extension

**Comment by cmoog** [comment]
@IJuanI Nice work! The extension is now available in our marketplace.

**Comment by IJuanI** [comment]
Downloaded and installed the extension, seems to be fully working
