### ISSUE TITLE
Command to open a file from terminal in editor...

### ISSUE THREAD

**Issue by Grimeton** [cdr/code-server#1586]
Hi,

I'm using the terminal a lot when testing shell functions and stuff. Every now and then it happens that I need to edit a file that is not open in the 834905809345 windows already open but I'm missing a command to tell CodeServer to open the file.

Right now I'm doing a `realpath $file` and then click on the file in the terminal while holding ctrl.

Having a command like csedit that tells CodeServer via the IPC socket to open the file in the editor would be awesome.

It would be even more awesome If I could pick the split pane where the file would be opened in, like counting from the left, having three split panes: 1,2,3

I'd write something like this:

[cse|csedit|cso|csopen] [1|2|3] filename

cse 2 lib.sh

and the file would be opened in the middle split pane.

What protocol is CodeServer talking on the IPC sockets? Is there documentation about that somewhere?

Cu

**Comment by code-asher** [comment]
This would definitely be a handy feature, let's track it here: https://github.com/cdr/code-server/issues/164

**Comment by code-asher** [comment]
About the sockets, those are all created and managed by VS Code and I'm not sure if they have documentation on the protocol used.
