### ISSUE TITLE
search is only searching open files 

### ISSUE THREAD

**Issue by hadisajjadi** [cdr/code-server#1588]
hi I've recently updated my code-server to the latest version and now every time I want to search in all files I get no result but if  open a file that contains that I get expected result
search functionality was working just fine until I updated to the current version

**Comment by cmoog** [comment]
Have you opened your intended working directory through the context menu or CLI before you initiate the search? We recently modified some behavior around the default working directory when the code-server is initially loaded.  #1535

**Comment by hadisajjadi** [comment]
sorry about late response yeah i was opening it with context menu. i think now it is fixed with last update

**Comment by zegnog** [comment]
I am experiencing the same issue, but on a version installed using conda-forge. Weirdly enough the bug does not reproduce using the standalone version.

**Comment by code-asher** [comment]
From what I recall this can happen if ripgrep is missing.  I would 
check the logs and see if the binary exists.  I think it should be 
***@***.***/ripgrep/bin/rg.

**Comment by code-asher** [comment]
GitHub mangled the path I was trying to post.  lib/vscode/node_modules/@vscode/ripgrep/bin/rg

**Comment by zegnog** [comment]
For visibility, the above problem I mentioned is related to https://github.com/coder/code-server/issues/5322 .
