### ISSUE TITLE
Copy is unavailable on iPadOS

### ISSUE THREAD

**Issue by chocoford** [cdr/code-server#1589]
I can’t do copy operation on iPadOS safari.
I try to connect via HTTPS. But only got a whole white screen(show nothing). 
And if I access `http://localhost:port` from my computer (which is the machine running `code-server`), I can do copy and paste operation.

**Comment by cblavier** [comment]
I am using lastest version of code-server but I can’t cmd-c, cmd-x, cmd-v, cmd-w, cmd-z ... either

**Comment by pr1metine** [comment]
Duplicate of #1015

**Comment by cmoog** [comment]
Closing. Please track this in 1015 ^^
