### ISSUE TITLE
New release 3.2.0 has disabled the support of Azure file share

### ISSUE THREAD

**Issue by kas301** [cdr/code-server#1590]
I have used the new release posted recently and it does not support Azure file share which was supported before. It is not storing the code-server files in File share directory. Please resolve this ASAP.

**Comment by nhooyr** [comment]
For someone not familiar with azure file share, can you elaborate on what you're trying to do and what's going wrong?

**Comment by kas301** [comment]
Actually I am using Azure kubenets to run code server instance and in that I have mounted the code server files in Azure file share. So when I used the previous release then it was running but after new release 3.2.0 the files are not getting stored in file share.
[https://zimmergren.net/mount-an-azure-storage-file-share-to-deployments-in-azure-kubernetes-services-aks/](url) These are steps I am following. Let me know if you need more info.

**Comment by nhooyr** [comment]
If you test this with regular VS Code, does everything work as expected?

**Comment by nhooyr** [comment]
Also what was the last release where this worked?

**Comment by kas301** [comment]
I don't know if it works with regular VS or not bcz that is not what I have to do as my requirement is to use online code server. And it was working in 3.1.1.

**Comment by nhooyr** [comment]
> I don't know if it works with regular VS or not bcz that is not what I have to do as my requirement is to use online code server. 

Yes but it helps us isolate whether it's a problem in code-server or VS Code. Please do test.

**Comment by kas301** [comment]
I have tested it in VS code and it worked fine. So please check at your side.

**Comment by nhooyr** [comment]
Can you try v3.3.0?

**Comment by Matthew-Beckett** [comment]
This sounds like a Kubernetes deployment issue, @kas301 are you able to provide Helm value files and/or your manifests? Anonymised storage-classes you're using will also help in debugging.

Thanks!

**Comment by Matthew-Beckett** [comment]
@jsjoeio I think this issue can be closed.

**Comment by jsjoeio** [comment]
Awesome! Thanks @Matthew-Beckett 🙌
