### ISSUE TITLE
How can we add new Extension in Code server's VS code?

### ISSUE THREAD

**Issue by kas301** [cdr/code-server#1591]
I want to add C# formatter extension in VS code of code server. So how can I add that globally so that all instances can have that extension installed?

**Comment by cmoog** [comment]
VSIX bundles can be uploaded manually to your code-server instance through the context menu in the Extensions tab. 

For submissions to the code-server extension marketplace, please include the repository URL in your request and we'll do our best to make it available.

**Comment by kas301** [comment]
Below is the URL of Repository.
[https://github.com/OmniSharp/omnisharp-vscode](url)
Please if you can then add it inside the vscode permanently as it is required for all c# coders.

**Comment by cmoog** [comment]
It appears this is already live in our marketplace under the following id: `ms-dotnettools.csharp`. Search for `c#` or `@id:ms-dotnettools.csharp` in the marketplace search menu. 

I'm not sure I understand what you mean by "adding it permanently". Can you explain what that means?

**Comment by kas301** [comment]
I Mean you should add it globally so we don't need to install it everytime.

**Comment by kas301** [comment]
Also can you guide me that how we can add .Net core SDK in all instances of code server?

**Comment by cmoog** [comment]
That’s not something we feel is appropriate to impose on all users.

If you’d like, you can automate the installation of extensions through the code-server CLI.
