### ISSUE TITLE
Architecture arm64 is not supported. 

### ISSUE THREAD

**Issue by a6640002** [cdr/code-server#1594]
when i install C/C++ IntelliSense, debugging, and code browsing.
the program reminds me My platform is not supported.
Is there a solution?
My platform is arm64 s905l.
thanks very much..

**Comment by a6640002** [comment]
![image](https://user-images.githubusercontent.com/1962550/80862744-fbcb7c80-8ca9-11ea-84a2-8986930694af.png)

**Comment by nhooyr** [comment]
I don't believe there's anything we can do here.

Please check to see if you can run VS Code and use the extension on arm64.

**Comment by code-asher** [comment]
Was curious so I checked the repo and here's the relevant issue: https://github.com/microsoft/vscode-cpptools/issues/2506
