### ISSUE TITLE
please update to fixuid-0.4.1 to have a working dockerfile for arm64

### ISSUE THREAD

**Issue by camelator** [cdr/code-server#1597]
The proposed docker image based on Debian 10 can not work on arm64 because it uses an AMD version of fixuid. Fortunately, a new version of fixuid was reeased few days ago, and there is an arm version. may it be possible to have an update of the dockerfile to download the relevant file related to architecture?
many thanks

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/1505
