### ISSUE TITLE
docker run -it -p 127.0.0.1:8080:8080 -v "$PWD:/home/coder/project" -u "$(id -u):$(id -g)" codercom/code-server:latest

### ISSUE THREAD

**Issue by slippis** [cdr/code-server#1598]
docker run -it -p 127.0.0.1:8080:8080 -v "$PWD:/home/coder/project" -u "$(id -u):$(id -g)" codercom/code-server:latest

**Comment by nhooyr** [comment]
Could you'd describe the issue?
