### ISSUE TITLE
Noe able to run ubuntu commands in bash

### ISSUE THREAD

**Issue by sanjayme97** [cdr/code-server#1600]
Previously I used code-server version  2.1698-vsc1.41.1 there I used to try `lsb_release -a` command to check ubuntu version and  I have written some commands to install dotnet core sdk but now I updated to code-server version 3.1.1 here    `lsb_release -a` is not running it shows `lsb_release: command not found` and dotnet core sdk installation commands failing. @code-asher @nhooyr   kindly help here

**Comment by nhooyr** [comment]
Are you using the docker container?

**Comment by nhooyr** [comment]
Might be related to #1585

**Comment by sanjayme97** [comment]
yes I am using docker container, I saw you switched to Debian from ubuntu. I din't understood #1585 . How can I make my old commands work here?

**Comment by nhooyr** [comment]
Looks like it was removed somehow. It's in the package `lsb-release` so just apt install that for now. I'll add it back in.

**Comment by sanjayme97** [comment]
fine,I will do it but why you changed to Debian from Ubuntu ?

**Comment by nhooyr** [comment]
Debian is better suited for a container. Ubuntu is more bloated, containing things like `snap` by default.

**Comment by nhooyr** [comment]
Fixed in the latest image. Thanks for reporting @sanjayme97
