### ISSUE TITLE
nrwl.angular-console extension to marketplace

### ISSUE THREAD

**Issue by eshkard** [cdr/code-server#1603]
Hi,
First of all thanks for exelent product.
Please add this useful for monorepo "Nx Console" extension to your market place

[VSCode Market link](https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console)
[GitHub link](https://github.com/nrwl/nx-console)

Thank`s

**Comment by cmoog** [comment]
Thank you for the request. Nx Console is now live in our marketplace.  Let me know if you experience any issues and I'll reopen this issue.
