### ISSUE TITLE
(Possibly) Provide OpenVSX as default Registry

### ISSUE THREAD

**Issue by sr229** [cdr/code-server#1604]
It seems [OpenVSX](https://open-vsx.org) is a successful implementation of the Visual Studio Code Registry, and has been used our friends from @eclipse-theia. I think it would be nice for us to move away from the private registry method and move the extension support to OpenVSX.

Another good benefit of this is that Enterprise customers can host their own registry using the same OpenVSX registry code.

**Comment by sr229** [comment]
As an added bonus, this will also solve all of the listed extension issues we had previously here - as we can divert the requests to the plugin authors instead to support OpenVSX instead of Coder handling the burden.

**Comment by cmoog** [comment]
The code-server extension marketplace currently supports over 20 times the number of extensions available in the OpenVSX registry. Please reference #1473 to track this issue. 

Closing because this is a duplicate.
