### ISSUE TITLE
Code-server is refreshing itself automatically or throwing a 500 error message

### ISSUE THREAD

**Issue by sujeilyfonseca** [cdr/code-server#1605]
**Version:** code-server-3.2.0-darwin-x86_64
**OS:** Mac OS Mojave 10.14.6
**Browser:** Firefox, Google Chrome

</br>

**Description:** Code-server is refreshing itself automatically or throwing a 500 error message

_Firefox:_ 
I have been using the `code-server` for a while, as I perform quality assurance by working on automation tests for a VS Code plugin using Selenium. It has been working fine until I upgraded to `3.2.0`. Now, it refreshes itself after performing the login:

![macos-code-server](https://user-images.githubusercontent.com/49531960/81121700-59a3d280-8efd-11ea-8117-fd297c622f53.gif)

_Google Chrome:_ 
I get a 500 error message if I use a Google Chrome browser instead:

<img width="1255" alt="Screen Shot 2020-05-05 at 6 33 21 PM" src="https://user-images.githubusercontent.com/49531960/81122553-164a6380-8eff-11ea-96ea-f90ad4bf4991.png">

</br>

**Here is the console output:**
[code-server.txt](https://github.com/cdr/code-server/files/4583942/code-server.txt)

**Comment by code-asher** [comment]
Sorry about this, should have a new release out today with an updated VS Code that has the fix.

**Comment by sujeilyfonseca** [comment]
Ok, thank you very much!

**Comment by skelgaard** [comment]
@code-asher Will that also fix that the docker-latests says
error listen EADDRINUSE: address already in use 0.0.0.0:8080
and then restarts ?

**Comment by code-asher** [comment]
@skelgaard That sounds like a different issue. I just pulled Docker latest but I haven't been able to replicate that one.

**Comment by code-asher** [comment]
Quick update: we're working on a few things before releasing 3.3.0. If this is blocking anyone I'd recommend using 3.1.1 for now or avoid using workspaces (which is the source of the issue).

**Comment by skelgaard** [comment]
> 
> 
> @skelgaard That sounds like a different issue. I just pulled Docker latest but I haven't been able to replicate that one.

Think i found the problem... it seems it doesn't respect the PORT enviroment setting anymore, will open other issue on it

**Comment by sujeilyfonseca** [comment]
Thank you for the update, @code-asher!

**Comment by nhooyr** [comment]
Should be fixed now.
