### ISSUE TITLE
App freezes after trying to open a folder

### ISSUE THREAD

**Issue by karimsa** [cdr/code-server#1609]
This was my setup process:

 * Spin up a VPS (4 GB RAM, 2 CPUs) on DigitalOcean with the code-server marketplace image
 * Set a password for `coder` so I could setup a few other things as a non-root user
 * Install docker for some other services
 * Clone my project manually using an SSH session logged in as `coder` (code-server kept failing to clone, it wasn't loading the ssh keys for some reasons)
 * Ask VSCode to open the folder that the repo is cloned into

After this, the server is completely unavailable. All HTTP requests to the server timeout. I've tried restarting the service using `service code-server restart`. I also do not see any useful logs in `~/.local/share/code-server/logs/*/remoteagent.log` (is that the right place to look?).

**Comment by code-asher** [comment]
That's the right directory but you might want to check for other files if there are any as well as code-server's stdout. You can run code-server with the `--log debug` flag to generate debug logging.

Also are there any messages in the browser console?

**Comment by karimsa** [comment]
How do I go about adding a flag to the daemon?

I've attached the logs directory, I'm not sure what I should be looking for.

[code-server-logs.zip](https://github.com/cdr/code-server/files/4601243/code-server-logs.zip)

**Comment by code-asher** [comment]
I didn't see anything that would explain this in those logs unfortunately.

To add the flag I think you'd need to edit the systemd unit which I think is normally in `/usr/lib/systemd/code-server` but if you run `systemctl status code-server` it should tell you for sure.

It's possible the browser console will be more helpful than the server logs if you could pop that open in your browser and see what it spits out when you load the page.

**Comment by nhooyr** [comment]
Can you try using the latest release instead?

**Comment by karimsa** [comment]
I gave up on this amped moved to docker. Will follow up on that ticket. Feel free to close this.

**Comment by nhooyr** [comment]
Sounds good.
