### ISSUE TITLE
Feature: Ldap login support

### ISSUE THREAD

**Issue by Spacelord09** [cdr/code-server#1614]
Is Ldap login support planned? Or can it be implementet in the near future?

**Comment by geiseri** [comment]
You can do this very easily (and safely) with traefik and forward auth.   What I do is set it to be no-auth, and then use traefik to supply authentication and SSL.  Check out "doc/FAQ.md" under "how-should-i-expose-code-server-to-the-internet" for a great starting point.

**Comment by Spacelord09** [comment]
I'll try it out in the next months. Thanks.

**Comment by nhooyr** [comment]
Highly recommend a reverse proxy for this like @geiseri mentioned.
