### ISSUE TITLE
Integrated terminal does not open after closing

### ISSUE THREAD

**Issue by karimsa** [cdr/code-server#1615]
I am running code-server using the official docker image and having an issue with the integrated terminal. Initially, using Ctrl+\` will open the integrated terminal, and the same keystroke will also hide it. But then using the keystroke again does nothing. There are no log messages even with `--log trace`. I've also tried using the command palette to run "Toggle Integrated Terminal" which also does nothing.

**Comment by karimsa** [comment]
Interestingly, it works fine in Chrome but not Firefox.

**Comment by nhooyr** [comment]
Interesting, does this still occur on the latest release?

**Comment by karimsa** [comment]
I still have this issue in the latest release. Honestly though, it has been hell to try to use code-server with Firefox because Firefox messes up lots of the key bindings. Like there's no way to tell Firefox to ignore Cmd+Shift+P when in code-server, it always open up a private window.

I've only had success with Chrome for this.

**Comment by code-asher** [comment]
I'm still seeing this on Firefox on latest master. It looks like another focus-related issue. VS Code uses focus out to determine if the panel is active but it doesn't fire when the panel is removed so VS Code permanently thinks the panel is active and won't try opening it again.

I'm not sure if this is a Firefox bug or if it's correct behavior for removed elements not to fire blur or focus out (imo it's not but idk what the spec says), but I suppose one fix would be to mark the panel as inactive when removing it.

**Comment by bvilnis** [comment]
Yeah, same issue here. I use Firefox for my personal browser and Chrome for work. I love Firefox but this kind of stuff is annoying. Just means I have to run all my code-server instances via Chrome for now.

**Comment by nhooyr** [comment]
Can confirm this remains an issue.

**Comment by adrusi** [comment]
I also experience this issue, but I'm not using Docker at all.

> Honestly though, it has been hell to try to use code-server with Firefox because Firefox messes up lots of the key bindings. Like there's no way to tell Firefox to ignore Cmd+Shift+P when in code-server, it always open up a private window.

I have a partial fix for this. Enabling `browser.ssb.enabled` in `about:config` and then running code-server "in app mode" (see screenshot) gives you Firefox's version of a PWA, and most keybinding work, notably ctrl+shift+p. This requires code-server to server with SSL.

![open code-server in app mode](https://user-images.githubusercontent.com/183309/104143438-54195900-53b7-11eb-87fc-9bdba785132b.png)

**Comment by crupest** [comment]
I also meet this problem with safari on iPad in PWA mode.

The same symptom as you.

```
code-server: v3.9.0
 VS Code: v1.52.1
Commit: fc6d123da59a4e5a675ac8e080f66e032ba01a1b
Date: 2021-02-12T23:39:50Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
```

**Comment by jsjoeio** [comment]
@jd-erreape thanks for the quick response! That tells me this is an upstream issue then and not specific to code-server. I'm going to mark it as such. Do you mind opening an issue upstream?
