### ISSUE TITLE
vsvim extension doesn't work

### ISSUE THREAD

**Issue by bschau** [cdr/code-server#1617]
Running code-server 3.2.0 on a Ubuntu 18.04 server.   I've install the vsvim extension but it doesn't work:

![image](https://user-images.githubusercontent.com/2059252/81474834-3da77600-9208-11ea-84e3-af8e5e0182e7.png)

**Comment by code-asher** [comment]
Ah yeah is this on Firefox? Unfortunately the extension uses a regular expression that isn't supported by Firefox. :(

**Comment by bschau** [comment]
Yes, this is on firefox.  Bummer.  No polyfill exists for this?

**Comment by bschau** [comment]
According to this thread:

https://github.com/eklem/words-n-numbers/issues/17

... Mozilla will make some changes to their RegExp engine in v78+ of Firefox.
Hopefully, it will solve the problems.
I will close this issue.

**Comment by eklem** [comment]
You can test out Firefox Nightly and see if that does it. [It's v78 now. Release date is at the end of June](https://wiki.mozilla.org/Release_Management/Calendar).

**Comment by bschau** [comment]
I'm running firefox 78.0a1 and it seems to work!

I've seen no errors in the extensions I use.  The only "minor" t
hing was:

A system error occurred (spawn /usr/lib/code-
server/lib/vscode/node_modules/vscode-ripgrep/bin/rg EACCES)

... however, a chmod 755 fixed that :-)

And now vscode-vim works.  So nice!  :-)

**Comment by nhooyr** [comment]
That's awesome, we should add a FAQ entry.

**Comment by nhooyr** [comment]
> I've seen no errors in the extensions I use.  The only "minor" t
hing was:

> A system error occurred (spawn /usr/lib/code-
server/lib/vscode/node_modules/vscode-ripgrep/bin/rg EACCES)

> ... however, a chmod 755 fixed that :-)

Should be fixed in 3.3.1 which was released a few days ago.

**Comment by tidux** [comment]
Firefox 78.0 has been released which fixes the browser side of this issue.

**Comment by nhooyr** [comment]
Awesome, I guess we can just close this issue then!

Thanks for letting us know @tidux
