### ISSUE TITLE
terminal open failed,status starting.......

### ISSUE THREAD

**Issue by joewen85** [cdr/code-server#1620]
I running  code-server release 3.2.0 in centos8.1.use root run code-server
run on chrome and firefox with https have this problem
<img width="1169" alt="code-server_terminal_open_error" src="https://user-images.githubusercontent.com/9345083/81491649-5032b580-92c3-11ea-893f-cff359a3482f.png">

**Comment by code-asher** [comment]
Have you seen any error logs? See https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-debug-issues-with-code-server.

**Comment by nhooyr** [comment]
Please try the latest release.

**Comment by joewen85** [comment]
i try release 3.3.1. fix problem
thx a lots

**Comment by nhooyr** [comment]
<3
