### ISSUE TITLE
vscode log not show in console

### ISSUE THREAD

**Issue by stat0s2p** [cdr/code-server#1621]
I build code-server from source and run `yarn watch -vvv`.some vs-code server site log not show in console.
for example,I edit `workbench/api/extHostTerminalService.ts`  add `this._logService.debug("foobar");`in constructor function after last line.it not show when I create Terminal in client.but when I add `throw new Error('Not implemented');` in constructor last line,client terminal status will stay at starting.it sounds that the code effect correctly.

so how can I make code-server show this log I add in extHostTerminalService.ts?

**Comment by code-asher** [comment]
Are you looking at the log files? That's where VS Code puts all its logging. For example here's what I got when I tried it out.
```
> rg '\[debug\] foobar' ~/.local/share/code-server
~/.local/share/code-server/logs/20200511T162313/extension-host/exthost.log
3:[2020-05-11 16:23:19.967] [exthost] [debug] foobar
```

You can also go to the output panel within VS Code and select "remote extension host" from the dropdown.

**Comment by stat0s2p** [comment]
> Are you looking at the log files? That's where VS Code puts all its logging. For example here's what I got when I tried it out.
> 
> ```
> > rg '\[debug\] foobar' ~/.local/share/code-server
> ~/.local/share/code-server/logs/20200511T162313/extension-host/exthost.log
> 3:[2020-05-11 16:23:19.967] [exthost] [debug] foobar
> ```
> 
> You can also go to the output panel within VS Code and select "remote extension host" from the dropdown.

thx for reply.i execute your command but got `No such file or directory (os error 2)`.is I miss some options for vs-code to tell it log to files?

**Comment by code-asher** [comment]
Your data directory might be different than mine. Check out https://github.com/cdr/code-server/blob/2e31e8f0c9b96bdf56f50bec9a0be1153d17c722/doc/FAQ.md#where-is-the-data-directory

**Comment by stat0s2p** [comment]
i found logs in `~/Library/Application\ Support/code-server`. thx for your help.

**Comment by code-asher** [comment]
No problem, as a heads up in the next version of code-server we're going to move the directory to `~/.local/share/code-server` for macOS, so just something to look out for.
