### ISSUE TITLE
Security problem with plain saved passwords

### ISSUE THREAD

**Issue by okalousek** [cdr/code-server#1624]
When I want to use Coder as autostart on my server, It needs to be password saved plain (systemd unit, et cetera). But this way is not very secure.

What about option of encryption of passwords?

**Comment by code-asher** [comment]
The next version will have a configuration file you can put the password in, then you can restrict access to the configuration file.

**Comment by nhooyr** [comment]
Going to always hash the password.

**Comment by nhooyr** [comment]
So unfortunately we can't do this right now because we randomly generate the password by default and we need users to be able to see it so they can login and we don't want to print it into the logs.

**Comment by nhooyr** [comment]
The config file should help with this as @code-asher mentioned as you can restrict access to it.
