### ISSUE TITLE
Add 2FA support

### ISSUE THREAD

**Issue by andgar2010** [cdr/code-server#1625]
Is double authentication 2FA support planned? Or can it be implementet in the near future?

**Comment by code-asher** [comment]
There are no plans at the moment. Currently our recommendation is to use some kind of external authentication and then reverse proxy to code-server.

**Comment by nhooyr** [comment]
Like @code-asher stated unlikely we'll implement this as we'd rather people use reverse proxies for more advanced authentication.

Using SSH is more secure anyway so if you can, use it!
