### ISSUE TITLE
Dvorak-QWERTY layout is not respected

### ISSUE THREAD

**Issue by gyzerok** [cdr/code-server#1626]
Hello!

I am using Dvorak-QWERTY layout on macOS. This layout is made so, that usually it works as Dvorak, but when command key is pressed it works as QWERTY. The idea is - you can retain the regular hotkeys places, while use Dvorak for typing.

When I work with code server through Google Chrome in app mode, it does not seem to respect this layout and works only as Dvorak.

In VSCode it works as expected and in Google Chrome it works as expected. That's why I am suspecting that it is somehow connected to the `code-server` itself.

**Comment by gyzerok** [comment]
After I wrote this issue I switched back to the window with the `code-server` open and it worked as expected. Not sure what happened.

I'll keep an eye on this behavior and will report here, when I have more data.

**Comment by gyzerok** [comment]
After several relaunches the problem never appeared again. So I will close the issue for now.

**Comment by gyzerok** [comment]
Just got hit by this issue once more.

**Comment by gyzerok** [comment]
Okay, I found what was the problem.

Apparently you need to set `"keyboard.dispatch": "keyCode"` for Dvorak-QWERTY layout to work correctly.

When I opened `code-server` for the very first time I haven't had my settings there, so it misbehaved. Today I was wondering why I even have this setting so I removed it. That's why I've got the problem again.

**Comment by ghj7211** [comment]
Worked for me. I was using 3 languages: dvorak-qwerty, korean and japanese.
Haven't been able to solve the problem for a year and a half. Worked like a charm.

**Comment by nekename** [comment]
> `"keyboard.dispatch": "keyCode"`

This solved my problem using regular Dvorak - for anyone else coming across this, it needs to be set in the User or Default settings, not in the Remote settings.
