### ISSUE TITLE
code-server is being accessed over an insecure domain. Web views, the clipboard, and other functionality will not work as expected.

### ISSUE THREAD

**Issue by milkboylyf** [cdr/code-server#1627]
I use Google Chrome as the default browser, its version is 81.0.4044.138, and I put code-server on a remote server, the system is centos7, and the following reminder is displayed when I log in to the browser:

**code-server is being accessed over an insecure domain. Web views, the clipboard, and other functionality will not work as expected.**

**Comment by yyjlincoln** [comment]
You need a domain and enable https.

**Comment by milkboylyf** [comment]
> You need a domain and enable https.
How dose code-server starts with https. I find that it starts defaultly with http.

**Comment by yyjlincoln** [comment]
You can set up a reverse proxy server using Nginx, and then obtain an SSL certificate from LetsEncrypt or other places.

**Comment by milkboylyf** [comment]
Thank you! I will try it!

**Comment by cmoog** [comment]
Thank you for the assistance @yyjlincoln. We're aware that setup documentation is lacking. 
https://github.com/cdr/code-server/pull/1628 aims to solve this problem.

**Comment by avelinocneto** [comment]
> You can set up a reverse proxy server using Nginx, and then obtain an SSL certificate from LetsEncrypt or other places.

I'm running on Ubuntu using Nginx , so how can I do that ?

**Comment by yyjlincoln** [comment]
> > You can set up a reverse proxy server using Nginx, and then obtain an SSL certificate from LetsEncrypt or other places.
> 
> 
> 
> I'm running on Ubuntu using Nginx , so how can I do that ? 

Those docs might help you.

Configure Nginx:

http://nginx.org/en/docs/http/configuring_https_servers.html

Obtaining a SSL certificate from LetsEncrypt:

https://letsencrypt.org/getting-started/

**Comment by avelinocneto** [comment]
Thanks! It's working. But crashing on AWS free tier machine...

**Comment by censujiang** [comment]
> > > 可以使用Nginx设置反向代理服务器，然后从LetsEncrypt或者其他地方获取SSL证书。
> > 
> > 
> > 我正在使用 Nginx 在 Ubuntu 上运行，那么我该怎么做呢？
> 
> 这些文档可能对您有所帮助。
> 
> 配置 Nginx：
> 
> http://nginx.org/en/docs/http/configuring_https_servers.html
> 
> 从 LetsEncrypt 获取 SSL 证书：
> 
> https://letsencrypt.org/getting-started/

it is do not work on domain with nginx,I see the console have many error code

**Comment by jsjoeio** [comment]
i think this is an error upstream. please look at https://github.com/microsoft/vscode/issues/127770!
