### ISSUE TITLE
Update home-brew package to 3.3.0

### ISSUE THREAD

**Issue by chenrui333** [cdr/code-server#1631]
relates to https://github.com/Homebrew/homebrew-core/pull/54613

@nhooyr as mentioned in the homebrew PR, can we make the release scheme conforming with the homebrew std (https://docs.brew.sh/Acceptable-Formulae#stable-versions)?

cc @SMillerDev

**Comment by nhooyr** [comment]
My bad. https://github.com/Homebrew/homebrew-core/pull/53543 was merged even though it was a rc so I figured it was ok.

When we release 3.3.0 I'll update the home-brew package.

**Comment by chenrui333** [comment]
@nhooyr thanks much appreciated. We do like fast shipping on the homebrew side though :)

**Comment by nhooyr** [comment]
Done in https://github.com/Homebrew/homebrew-core/pull/54883
