### ISSUE TITLE
Add extension: axetroy.vscode-deno

### ISSUE THREAD

**Issue by SharifPoetra** [cdr/code-server#1635]
I'd like to use [Deno](https://deno.land) so this will be helpful for adding this extension: [axetroy.vscode-deno](https://marketplace.visualstudio.com/items?itemName=axetroy.vscode-deno) 
Thanks for your consideration!

**Comment by cmoog** [comment]
Thank you for the request! The `vscode_deno` is now available in the code-server marketplace,
