### ISSUE TITLE
Latest Chrome on Mac doesn't allow forcing through self signed certificate

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1637]
Latest chrome on Mac, just no option to continue

![image](https://user-images.githubusercontent.com/10180857/81902050-82773800-958d-11ea-9baa-f416fbdde8eb.png)

Some research suggests there may be something wrong about our self signed certificate. Something to do with subjectAltName not being set?

**Comment by nhooyr** [comment]
Works in Safari btw, I can force through.

**Comment by keiththomps** [comment]
I was running into this a few months ago when running on a CentOS 7 server and trying to connect from Catalina. You need a new enough version of OpenSSL (I used 1.1.1). The following will generate a cert that meets the requirements in case this is useful for anyone else:

```
/usr/local/ssl/bin/openssl req -newkey rsa:2048 -nodes \
  -x509 -days 365 \
  -out cert.pem \
  -keyout key.pem \
  -config /etc/pki/tls/openssl.cnf \
  -subj "/C=US/ST=Ohio/L=Columbus/O=Business./CN=Server" \
  -addext extendedKeyUsage=serverAuth \
  -addext subjectAltName=DNS:localhost
```

**Comment by nhooyr** [comment]
Awesome!

Let's add this to the FAQ or make code-server automatically generate it correctly.

**Comment by nhooyr** [comment]
Related to https://7402.org/blog/2019/new-self-signed-ssl-cert-ios-13.html

**Comment by nhooyr** [comment]
I ended up fixing this in #2255
