### ISSUE TITLE
Add extension request: vscode-bazel

### ISSUE THREAD

**Issue by InterestedInTechAndCake** [cdr/code-server#1638]
The current most up to date release of code-server has the deprecated version of the vscode-bazel extension, would the developers here kindly add the official version to a code-server release please? Many thanks for this!

Here is where it lives:
https://marketplace.visualstudio.com/items?itemName=BazelBuild.vscode-bazel

And vsix of their latest version (0.3.0) can be downloaded via:
https://github.com/bazelbuild/vscode-bazel/releases/download/0.3.0/vscode-bazel-0.3.0.vsix

**Comment by InterestedInTechAndCake** [comment]
In the interim before it is available, I tried to use the --install-extension command on my dockerfile to have it installed on my container, but it was not successful. The base image I am using is: codercom/code-server:3.2.0

 Here are the two approaches I have tried:

1. installed as root
RUN curl -sfLo /usr/share/code-server/vscode-bazel.vsix https://github.com/bazelbuild/vscode-bazel/releases/download/0.3.0/vscode-bazel-0.3.0.vsix && \
        /usr/local/bin/code-server --install-extension /usr/share/code-server/vscode-bazel.vsix

USER coder
ENTRYPOINT ["/usr/local/bin/code-server"...]

The result is that I can see this created on my container:

/root/.local/share/code-server/extensions/bazelbuild.vscode-bazel

However the extension was not listed on the menu and therefore cannot be installed directly.

2. installed as coder
USER coder
RUN curl -sfLo /home/coder/vscode-bazel.vsix https://github.com/bazelbuild/vscode-bazel/releases/download/0.3.0/vscode-bazel-0.3.0.vsix && \
        /usr/local/bin/code-server --install-extension /home/coder/vscode-bazel.vsix

ENTRYPOINT ["/usr/local/bin/code-server"...]

The result is that there is nothing created under /home/coder, nor /root, nor /home/coder/.local/code-server, e.g.:

[coder@~]$ ls -al .local/share/code-server/
total 20
drwxr-xr-x 4 coder coder 4096 May 14 12:42 .
drwxr-xr-x 4 coder coder 4096 May 14 12:42 ..
-rw-r--r-- 1 coder coder    0 May 14 14:45 heartbeat
drwxr-xr-x 4 coder coder 4096 May 14 13:11 logs
-rw-r--r-- 1 coder coder   36 May 14 12:42 machineid
drwxr-xr-x 3 coder coder 4096 May 14 12:42 User

and the extension was not listed on the extension menu either.

Could anyone suggest any ways to make it work please?

Thanks very much in advance.

**Comment by cmoog** [comment]
Thank you for the report! Bazel version 0.3.0 is now available in the code-server marketplace.
