### ISSUE TITLE
Error 404 with several releases

### ISSUE THREAD

**Issue by SniperGER** [cdr/code-server#1640]
Running a fresh install of ```code-server```  on macOS 10.12.6 (yes, it's old and no, I'm not going to update anytime soon).

I can login using the generated password just fine, but then I receive several 404's, rendering ```code-server``` completely useless for me. Checking in Finder shows me that these files are actually missing, but do in fact exist in the various ```vscode``` build folders.

Next I'm trying to copy the missing files into the output directory, but this breaks more than it fixes.

I've also tried to compile _everything_ myself, but this was just wasted time, because the same files are still missing.

I've checked previous 3.x releases, the last 2.x release and even a few of the earliest releases (which I know at least one of them worked before when I first tried ```code-server```), but even then I'm receiving 404's.

What is going on here?

**Comment by SniperGER** [comment]
Here's the console output on Safari 11.0.3 (12604.5.6.1.1):

    [Error] Unrecognized Content-Security-Policy directive 'manifest-src'.
    
    [Error] SyntaxError: Unexpected identifier 't'. Expected a ';' following a return statement.
    	(anonyme Funktion) (workbench.web.api.js:1574)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (uriIpc.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (uuid.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (cancellation.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (buffer.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (lifecycle.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (request.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (resources.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (browser.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (network.js, line 0)
    [Error] SyntaxError: Unexpected identifier 't'. Expected a ';' following a return statement.
    	(anonyme Funktion) (workbench.web.api.js:1574)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (windows.js, line 0)
    [Error] Unrecognized Content-Security-Policy directive 'manifest-src'.
    
    [Error] SyntaxError: Unexpected identifier 't'. Expected a ';' following a return statement.
    	(anonyme Funktion) (workbench.web.api.js:1574)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (uriIpc.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (uuid.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (cancellation.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (buffer.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (lifecycle.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (request.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (windows.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (resources.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (browser.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (network.js, line 0)
    [Error] SyntaxError: Unexpected identifier 't'. Expected a ';' following a return statement.
    	(anonyme Funktion) (workbench.web.api.js:1574)

**Comment by nhooyr** [comment]
Can you try with the latest release?

**Comment by SniperGER** [comment]
Still exactly the same errors. (This time not copied twice)

    [Error] Unrecognized Content-Security-Policy directive 'manifest-src'.
    
    [Error] SyntaxError: Unexpected identifier 't'. Expected a ';' following a return statement.
    	(anonyme Funktion) (workbench.web.api.js:1607)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (uriIpc.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (uuid.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (cancellation.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (buffer.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (lifecycle.js, line 0)
    [Error] SyntaxError: Unexpected identifier 't'. Expected a ';' following a return statement.
    	(anonyme Funktion) (workbench.web.api.js:1607)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (windows.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (browser.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (request.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (resources.js, line 0)
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (network.js, line 0)

Plus, I had to force Homebrew to upgrade `icu4c` to 66.1 (from 64), which (seemingly) hasn't been mentioned anywhere.

**Comment by nhooyr** [comment]
> Plus, I had to force Homebrew to upgrade icu4c to 66.1 (from 64), which (seemingly) hasn't been mentioned anywhere.

Huh interesting, are you building yourself?

**Comment by SniperGER** [comment]
Nope, downloaded directly from Releases. Without updating, `dyld` was complaining about the missing library.

    dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.66.dylib
      Referenced from: [Redacted]/code-server-3.3.0-macos-amd64/bin/../lib/node
      Reason: image not found
    Abort trap: 6

**Comment by nhooyr** [comment]
Yea yea looks like node depends on libicui dynamically, was not aware.

Not sure but maybe it's possible to add it in statically somehow.

**Comment by nhooyr** [comment]
Probably best for us to just build node from scratch.

**Comment by nhooyr** [comment]
Re the 404s, it's likely a bug with an older version of Safari.

Highly recommend upgrading your OS. But will leave up to @code-asher to see whether we can fix the CSP.

**Comment by code-asher** [comment]
We could remove `manifest-src` since browsers should fall back to `default-src` in theory. If the result is just an error being logged that the directive isn't recognized and it's not causing any issues it might not be worth the change imo.

**Comment by nhooyr** [comment]
Yea, not sure what's causing those 404s. It's also not easy afaik to install older Safari versions one of us will need to VM older macOS.

**Comment by nhooyr** [comment]
Probably best to just recommend using Chrome.

**Comment by nhooyr** [comment]
I think we forgot to close this, it's been dealt with a long time ago.
