### ISSUE TITLE
Accessing from windows is broken

### ISSUE THREAD

**Issue by eugenechyrski** [cdr/code-server#1642]
Hi looks like latest build changes broke path separator.
1. Host machine windows
2. code-server machine linux in docker 
3. Relevant docker part
```
RUN go get github.com/derekparker/delve/cmd/dlv
RUN git clone https://github.com/cdr/code-server.git
WORKDIR code-server
RUN git submodule update --init
RUN yarn
RUN yarn vscode
RUN yarn build
RUN yarn build:vscode
RUN yarn release
WORKDIR release
RUN yarn --production
WORKDIR /
ENTRYPOINT node /code-server/release --disable-telemetry  --host 0.0.0.0 --port 3003 
```

code server is up and running in docker and accessible via 127.0.0.1:3003 on windows host .

Following request fails while ui is loading in browser
http://127.0.0.1:3003/vscode-remote-resource?path=%5Ccode-server%5Crelease%5Clib%5Cvscode%5Cextensions%5Ctheme-defaults%5Cthemes%5Cdark_plus.json&tkn=

Checked and confirmed that file is there.
changin request to http://127.0.0.1:3003/vscode-remote-resource?path=/code-server/release/lib/vscode/extensions/theme-defaults/themes/dark_plus.json&tkn=
returns json data.

**Comment by nhooyr** [comment]
Thanks for reporting we'll look into this.

**Comment by asomethings** [comment]
For any windows users using code-server with chrome. Sharing an [requestly config](https://app.requestly.in/rules#edit/Replace_1589786051836) for replacing backslash to foward slash.

**Comment by nhooyr** [comment]
Will publish a 3.3.1 in the next few hours, just working on #1667

**Comment by eugenechyrski** [comment]
Thank you, now it works fine!

**Comment by nhooyr** [comment]
https://github.com/cdr/code-server/releases/tag/v3.3.1

🎉
