### ISSUE TITLE
Insiders builds?

### ISSUE THREAD

**Issue by izzues** [cdr/code-server#1643]
Hello,

Is it possible to use this with [Visual Studio Code Insiders](https://code.visualstudio.com/insiders/) rather than the stable build?

Thanks!

**Comment by nhooyr** [comment]
At the moment unfortunately not as we patch VS Code to add features to make it work better for the web.

Our dev docs are at https://github.com/cdr/code-server/blob/master/doc/CONTRIBUTING.md#structure

**Comment by izzues** [comment]
No problem, and thanks for the link!
