### ISSUE TITLE
Feature: bigger resolution on iPad Pro

### ISSUE THREAD

**Issue by ralvs** [cdr/code-server#1644]
One of the awesomeness of code-server is that I can develop from my iPad. 
But Apple did not make a good job for adjust the resolution when I connect the iPad on a external monitor. You just get the iPad screen super big. 
Unless you open some streaming video like Netflix, and then the iPad adjust for a bigger resolution (until 4K I guess)

So my question is, would be possible to code-server tricks the iPad Pro with a bigger resolution and then we all could develop using a very big screen space???

**Comment by TechLevelZero** [comment]
one way I get more screen real estate on my iPad is by zooming out on the page itself 
(command and -), hope that helps!

**Comment by ralvs** [comment]
Hey @TechLevelZero, thanks! It helps, but not totally.

Actually, now I realize that the problem is Apple does not permit to Safari go fullscreen, in any web page.
Just the native app of Netflix could use the fullscreen.
So, the only way to code-server goes fullscreen would be throught a native iPadOS app.
Maybe, an app that just wraps the web page, and the user points the URL for its own instance of code-server. This could work :)


- code-server on iPad
![codeserver ipad](https://user-images.githubusercontent.com/5287233/82125749-84ecb400-977e-11ea-81c2-baa9c403affa.jpg)

- code-server on Macbook and fullscreen
![codeserver macbook](https://user-images.githubusercontent.com/5287233/82125758-8c13c200-977e-11ea-8294-3a12a0bdb43d.jpg)

- Netflix native app on iPad
![netflix app ipad](https://user-images.githubusercontent.com/5287233/82125761-8e761c00-977e-11ea-87d1-7ce9a12f626c.jpg)

- Netflix on Safari of iPad
![netflix on safari ipad](https://user-images.githubusercontent.com/5287233/82125762-8fa74900-977e-11ea-9600-0de2b38ae33e.jpg)

**Comment by demyxco** [comment]
@ralvs have you tried shiftscreen? It's $4.99 on the App Store, haven't tried it but I've seen YouTubers use it for a 16:9 resolution on external monitors. It does more too.

**Comment by ralvs** [comment]
Hey @demyxco, very nice app! I managed to use the full screen.
The resolution is still a problem, the letters did not look well. But this, I think it is an iPad problem, or maybe my HDMI cable.
Thanks!

**Comment by demyxco** [comment]
@ralvs yeah it definitely is an iPadOS issue due to it not supporting a 16:9 ratio natively.

**Comment by nhooyr** [comment]
Unfortunately I don't think there's anything we can do here on the code-server side. Seems like an issue with iPadOS as @demyxco mentioned.
