### ISSUE TITLE
Python extension not working & terminal not loading any environment

### ISSUE THREAD

**Issue by opoloko** [cdr/code-server#1645]
Hi I’m trying code-server on my centos7, and I’m having a few problems that I’m not sure are limits of running code-server or rather of my local setup.

I’ve followed this tutorial to install it https://www.digitalocean.com/community/tutorials/how-to-set-up-the-code-server-cloud-ide-platform-on-centos-7

The two problems I’m encountering are (from iOS latest on my iPad):

1) terminal loads a generic sh but not bash, so is without any environment and many things don’t work properly (git). I tried as well launching bash -l from the terminal, or source .bash_profile, somehow the environment variables are never really loaded

2) Jupyter extension fails to load Python somehow, although it perfectly works on the machine and the extension can correctly find the interpreter and the right version (attached the error). Once I try to load a notebook and it launches the Python, I see it starts creating many connections to my machine.

I struggled finding a comprehensive guide of all parameters I could possibly use to launch code-server if needed to fix these two problems. Any suggestion or idea? Thanks! :-)

![76A86AB7-55F3-4938-8C4C-389D20E526E3](https://user-images.githubusercontent.com/1588338/82116496-26b1d800-9762-11ea-99fd-5cef4853c2f4.jpeg)

**Comment by nhooyr** [comment]
Please use our setup guide instead.

https://github.com/cdr/code-server/blob/master/doc/guide.md

If it still happens let me know and I'll reopen this issue.
