### ISSUE TITLE
Add Cloud Code extension

### ISSUE THREAD

**Issue by izzues** [cdr/code-server#1647]
https://marketplace.visualstudio.com/items?itemName=GoogleCloudTools.cloudcode

**Comment by nhooyr** [comment]
@cmoog

**Comment by oxy** [comment]
License needs a review - need to check if https://cloud.google.com/terms/plugins/ permits redistribution, and if building/including it with code-server is allowable.

**Comment by oxy** [comment]
We're planning to move to OpenVSX soon, closing.
