### ISSUE TITLE
Cannot find module '/bin/out/node/entry.js'

### ISSUE THREAD

**Issue by adnanfuat** [cdr/code-server#1651]
I applied these steps ( https://www.youtube.com/watch?v=IdrwbToYmrQ )
I moved Code-server into in bin directory ( https://prnt.sc/sihf6c )

When I execute code-server command returned this error ( **exec: /bin/node: not found** )

After that;
And ı redirect symbolic link with( **ln -s /usr/bin/nodejs /bin/node**  )

When I execute "code-server" command returns Cannot Find Module error
https://prnt.sc/sigw85

uname -m >>> x86_64

UBUNTU, Node and NPM versions: https://prnt.sc/siie9v

**Comment by nhooyr** [comment]
Please follow our instructions on installation instead in the README.md

The instructions in that video appear to be incorrect.

**Comment by adnanfuat** [comment]
> The instructions in that video appear to be incorrect.

This file ? https://github.com/cdr/code-server/blob/master/README.md

**Comment by nhooyr** [comment]
https://github.com/cdr/code-server#releases

**Comment by nhooyr** [comment]
Some much nicer new docs will be up very soon as well.

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/blob/master/doc/guide.md
