### ISSUE TITLE
Remove digital ocean marketplace image

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#1654]
Using the [setup guide](https://github.com/cdr/code-server/blob/master/doc/guide.md) is a much better alternative as it's so easy to setup now.

@nathanpotter

**Comment by nhooyr** [comment]
Need to fix this ASAP to prevent user confusion.

e.g. see https://github.com/cdr/code-server/issues/1852

**Comment by jsjoeio** [comment]
I assume this is referring to the `code-server` [droplet](https://github.com/cdr/code-server/issues/1654) on the DigitalOcean marketplace. I'll see if I can work with @nathanpotter to get this removed.

**Comment by nathanpotter** [comment]
I just logged into the DO vendor portal and there doesn't appear to be a way to remove the listing through there. I've opened a support ticket to take the image down and will update here once I hear back.

**Comment by SubZane** [comment]
I am one of those newbies that installed this droplet...doesn’t even seem to work, but maybe I know why then :P

**Comment by nathanpotter** [comment]
DO support team has taken the image down :+1:
