### ISSUE TITLE
 `GLIBC_2.28' not found running 3.3.0 on Ubuntu 18.04 

### ISSUE THREAD

**Issue by ryan-allen** [cdr/code-server#1656]
Hello! When installing the new deb package for 3.3.0, and I run code-server, I get this error when I try to use the app in the browser:

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/code-server/lib/vscode/node_modules/spdlog/build/Release/spdlog.node)

I'm on Ubuntu 18.04, and have been using prior releases with no issues.

**Comment by nhooyr** [comment]
Can you run `ldd --version` to see what libc version you're on?

**Comment by ryan-allen** [comment]
Thanks for the quick response <3 Here's my ldd --version output:

ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by nhooyr** [comment]
Thank you as well.

Looks like we're going to switch CI to build on an older system.

In the meantime, you can easily install with our `npm` package. See https://github.com/cdr/code-server#npm

**Comment by dntq83** [comment]
I have the same error

**Comment by nhooyr** [comment]
Please refrain from me too comments guys in favour of just thumbs uping the original issue!

**Comment by gyzerok** [comment]
I might be that the issue isn't just about the older version.

```
$ ldd --version
ldd (Debian GLIBC 2.19-18+deb8u10) 2.19
```

And I still get the same error. Might be that I just don't understand anything here though :)

**Comment by nhooyr** [comment]
So you have glibc v2.19 but currently the static releases depend on at minimum v2.28.

#1657 will build on Debian 8 which will make the minimum glibc v2.19.

For anyone who wants it lower I think it's best to just use the npm package otherwise we'll be using a unmaintained distro for the build process.

**Comment by gyzerok** [comment]
Ok, I see. Thank you for clarification.

**Comment by nhooyr** [comment]
I updated the release just now to use depend on glibc 2.19 at minimum for amd64 so you guys should be good.

Just working on CI to automate it.

**Comment by gyzerok** [comment]
Can verify that it works for me

**Comment by ryan-allen** [comment]
Thank you @nhooyr !!! ❤️

**Comment by Hugovidafe** [comment]
I'm having problems ^^

![image](https://user-images.githubusercontent.com/69076992/124079070-f7832680-da48-11eb-8c40-30e132510449.png)
