### ISSUE TITLE
Accessing from windows is broken

### ISSUE THREAD

**Issue by silenceleaf** [cdr/code-server#1659]
I am using static version of linux 64 bit build.

Program can start without any error. when accessing, code highlight is gone. File icon is gone. 

No error log, everything looks correct.

![image](https://user-images.githubusercontent.com/3157196/82169418-134c5d00-9887-11ea-97db-efacee777fe0.png)

Look at the snap shot. The Java file is not highlighted.  File icon missing.

**Comment by nhooyr** [comment]
Can you try to clear your browser cache or try a different browser?

**Comment by nhooyr** [comment]
And follow the debugging steps described at https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-debug-issues-with-code-server

**Comment by nhooyr** [comment]
cc @code-asher

**Comment by silenceleaf** [comment]
> Can you try to clear your browser cache or try a different browser?

Tried clear browser cache, same. 

```
debug Request error {"url":"/vscode-remote-resource?path=%5Chome%5Cjunyan%5Cstorage%5Capp%5Ccode-server%5CCode%5Clib%5Cvscode%5Cextensions%5Ctheme-defaults%5Cthemes%5Cdark_plus.json&tkn=","code":404}
debug Request error {"url":"/vscode-remote-resource?path=%5Chome%5Cjunyan%5Cstorage%5Capp%5Ccode-server%5CCode%5Clib%5Cvscode%5Cextensions%5Ctheme-seti%5Cicons%5Cseti.woff&tkn=","code":404}
debug Request error {"url":"/vscode-remote-resource?path=%5Chome%5Cjunyan%5Cstorage%5Capp%5Ccode-server%5CCode%5Clib%5Cvscode%5Cextensions%5Cjson%5Csyntaxes%5CJSONC.tmLanguage.json&tkn=","code":404}
debug Request error {"url":"/vscode-remote-resource?path=%5Chome%5Cjunyan%5Cstorage%5Capp%5Ccode-server%5CCode%5Clib%5Cvscode%5Cextensions%5Cjson%5Clanguage-configuration.json&tkn=","code":404}
debug Request error {"url":"/vscode-remote-resource?path=%5Chome%5Cjunyan%5Cstorage%5Capp%5Ccode-server%5CCode%5Clib%5Cvscode%5Cextensions%5Cjava%5Csyntaxes%5Cjava.tmLanguage.json&tkn=","code":404}
debug Request error {"url":"/vscode-remote-resource?path=%5Chome%5Cjunyan%5Cstorage%5Capp%5Ccode-server%5CCode%5Clib%5Cvscode%5Cextensions%5Cjava%5Clanguage-configuration.json&tkn=","code":404}
```

When I turn on debug log, lot of 404 errors. seems file not found, but it is there.

**Comment by nhooyr** [comment]
Seems like the same as in #1642

**Comment by immanuelfodor** [comment]
Might be related to #1660 as well.

I have the exact same problems on v3.3.0, Material Theme not loading, icons/fonts missing, YAML syntax highlight not working, etc. Reverted back to 3.2.0 (Docker tag) and it's fine again.

**Comment by silenceleaf** [comment]
When will you issue a fixed version?

**Comment by nhooyr** [comment]
In the next few hours.

**Comment by silenceleaf** [comment]
> In the next few hours.

Super!

**Comment by nhooyr** [comment]
https://github.com/cdr/code-server/releases/tag/v3.3.1

🎉
