### ISSUE TITLE
File toolbar horizontal scroll

### ISSUE THREAD

**Issue by avelino** [cdr/code-server#166]
When I have a big directory tree I can't read the file names

<img width="214" alt="Captura de Tela 2019-03-09 às 7 37 50 AM" src="https://user-images.githubusercontent.com/31996/54070418-95ca9d00-423e-11e9-9b86-69b9a32b6974.png">

- `code-server` version: master branch
- OS Version: Ubuntu

#### Steps to Reproduce

- large directory tree

**Comment by sr229** [comment]
Have you compared this to the latest VSCode to see if this is similar behavior? @avelino

**Comment by avelino** [comment]
VSCode (desktop by Microsoft) no side scroll, but I believe that the use of VSCode and code-server are different
- VSCode: I open the specific project directory
- code-server: I mount the folder volume of all projects, start code-server container once

**Comment by code-asher** [comment]
This requires enabling the `workbench.list.horizontalScrolling` setting but from my testing on v2 it works as expected.
