### ISSUE TITLE
Extensions not working in a PHP file 

### ISSUE THREAD

**Issue by OutdatedDesigns** [cdr/code-server#1661]
I'm working on a PHP Project and the extensions are not working It was a day before.

**Comment by nhooyr** [comment]
What version of cod-server? Are you using windows?

**Comment by OutdatedDesigns** [comment]
Im using windows and what do you mean by COD Server?

**Comment by nhooyr** [comment]
Try the latest release, it should work now.

See #1659

**Comment by OutdatedDesigns** [comment]
Cannot validate since no PHP executable is set. Use the setting 'php.validate.executablePath' to configure the PHP executable.

Extension host terminated unexpectedly.

I get this two errors

**Comment by nhooyr** [comment]
Looks like you need to install `php`.

**Comment by nhooyr** [comment]
As for the host being terminated, can you post some logs by following these steps:

https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-debug-issues-with-code-server

**Comment by OutdatedDesigns** [comment]
I'm confused how to get those logs?

**Comment by nhooyr** [comment]
Could you elaborate on what's confusing? The FAQ entry linked above makes it clear.

https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-debug-issues-with-code-server

**Comment by OutdatedDesigns** [comment]
How do I get Logs

**Comment by nhooyr** [comment]
No idea what you mean, what's confusing about the FAQ?

**Comment by nhooyr** [comment]
Going to close as there hasn't been a response in a long time.
