### ISSUE TITLE
3.3.0 on macOS uses wrong path for the data directory.

### ISSUE THREAD

**Issue by lisanet** [cdr/code-server#1662]
The just released v 3.3.0 has changed the directory path to the data directory from ~/Library/Application Support/code-server to ~/.local/share/code-server, arguing that this would ".. better match user expectations".

macOS has - as any other OS - some standard paths, which users will expect any application uses. This is e.g. ~/Library/Application Support/subdirectory for any data an app uses besides it's configurations. Configurations and preferences go into ~/Library/Preferences.

On macOS most users expect these directories and not dot directories.

Here's the corresponding document from Apple about standard file system paths on macOS

https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW6

and about the Library directory hierarchy 

https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1

**Comment by nhooyr** [comment]
I've been using macOS for many years now and I've seen very few CLI apps that put stuff in `~/Library`, it's pretty much reserved for GUI apps. e.g. git, fish and whatnot all use standard XDG directories.

For the same reason, Neovim uses the XDG directories as well.

**Comment by lisanet** [comment]
The macOS file system standard does not differentiate between GUI and CLI apps. It's valid for both. But sadly you're right, if you think of most - poorly ported - linux / *NIX apps.

code-server only is a CLI app, because there's no GUI to manage the server on macOS and users are forced to use Terminal.app to launch it and leave Terminal.app running all the time. 

So well, if you'll keep the dot directories and of course, if you don't mind, I'll fork this repo and will try to write a small GUI for macOS users. If it's done, I'd be glad if you'll put a link to this fork into your macOS FAQ.

**Comment by nhooyr** [comment]
> So well, if you'll keep the dot directories and of course, if you don't mind, I'll fork this repo and will try to write a small GUI for macOS users. If it's done, I'd be glad if you'll put a link to this fork into your macOS FAQ.

I'd be happy to :)
