### ISSUE TITLE
Search in project not working in 3.3.0

### ISSUE THREAD

**Issue by dr0p** [cdr/code-server#1665]
I am using `code-server-3.3.0-linux-amd64.tar.gz` and the search is broken - the following file is missing the +x (execute) flag
`code-server-3.3.0-linux-amd64/lib/vscode/node_modules/vscode-ripgrep/bin/rg`.

Simple workaround is to run in the root of code-server folder: `chmod +x lib/vscode/node_modules/vscode-ripgrep/bin`

**Comment by TobiaszCudnik** [comment]
`sudo chmod +x /usr/lib/code-server/lib/vscode/node_modules/vscode-ripgrep/bin/rg`
