### ISSUE TITLE
code-server update doesn't download

### ISSUE THREAD

**Issue by captainwasabi** [cdr/code-server#1674]
The url that was pushed was:

https://github.com/cdr/code-server/releases/download/v3.3.0/code-server-v3.3.0-linux-x86_64.tar.gz

The correct url is:

https://github.com/cdr/code-server/releases/download/v3.3.0/code-server-3.3.0-linux-amd64.tar.gz

Note the extraneous v in the incorrect filename.

Suuuuper annoying having the dialog popup over and over and over knowing it doesn't work. (and ignore button would be great, or postpone for a day.  Something.

**Comment by nhooyr** [comment]
Yea, we did not implement automatic updating correctly so we ended up removing it. There are much better install options now.

Sorry for the trouble!

See the release notes for v3.3.0 `https://github.com/cdr/code-server/releases/tag/v3.3.0`

Once you switch to v3.3.1 you should be good! It fixes the bugs in v3.3.0.

I'm going to pin the previous issue on this to avoid more duplicates.
