### ISSUE TITLE
icon-themes & themes not working on Windows (3.3.0)

### ISSUE THREAD

**Issue by cstrat** [cdr/code-server#1675]
- Web Browser: Chrome and Edge
- Local OS: Windows
- Remote OS: Ubuntu
- `code-server --version`: 3.3.0

This issue only happened just now when upgrading to 3.3.0.

Strange but I am finding that I can't see any of the icons only on my windows PC using any browser, but on my mac it all works fine in all browsers on there. Tried rebooting code-server and the PC thinking it might be a caching issue, but hasn't fixed anything and the testing in edge was the first time I've opened it in edge so caching shouldn't have been an issue there.

**Update**: _I also noticed none of the themes are working correctly on windows. I can't change themes and code is not coloured correctly. As with the icon-theme, this is all working fine on mac._

Windows screenshot:
![image](https://user-images.githubusercontent.com/4209076/82273201-39294d00-99c0-11ea-891a-f79987ede201.png)

Mac screenshot:
![image](https://user-images.githubusercontent.com/4209076/82273642-5874aa00-99c1-11ea-8b18-4d835f7c060e.png)

**Comment by cstrat** [comment]
Ahh this is probably related to #1642 although my access is fine, just themes not working.

**Comment by nhooyr** [comment]
I've pinned https://github.com/cdr/code-server/issues/1642 to avoid further duplicates.

Releasing v3.3.1 now.

**Comment by nhooyr** [comment]
https://github.com/cdr/code-server/releases/tag/v3.3.1

🎉

**Comment by cstrat** [comment]
Legend thanks! I'll update once it hits docker hub.

**Comment by nhooyr** [comment]
Just pushed, it's now on docker hub.
