### ISSUE TITLE
Allow user-data-dir and extension-dir in config.yaml

### ISSUE THREAD

**Issue by silenceleaf** [cdr/code-server#1676]
Everything look good!

I am using the new option --config passing a file to code-server.

looks like user-data-dir and extensions-dir  is not read from file.

my config.yaml:

user-data-dir: /home/junyan/mnt/e/Config/code-server/Data/
extensions-dir: /home/junyan/mnt/e/Config/code-server/Extensions/

using command line parameter everything works.

**Comment by nhooyr** [comment]
Looking into it!

**Comment by nhooyr** [comment]
Ah got it, thanks for reporting will push fix soon.

**Comment by ssnjrthegr8** [comment]
Hate to bring this back but I still face this issue on v3.4.0

**Comment by nhooyr** [comment]
Yup, see release notes in #1766
