### ISSUE TITLE
Where is the location of /User/settings.json

### ISSUE THREAD

**Issue by JtMotoX** [cdr/code-server#1680]
I have a wrapper script that does a rsync from my macOS local vscode user-data-dir, extensions-dir, etc.. to the code-server paths respectively before spinning up the code-server process.  This allows me to keep my settings and extensions in-sync.  With the new 3.3.0 this breaks because the 'settings.json' does not seem to be stored in the user-data-dir anymore.  Can you please provide me with the location of this file so I can cp my local settings.json to the code-server settings.json?

Old Location:
~/Library/Application Support/Code/User/settings.json

New Location:
/User/settings.json ???

**Comment by nhooyr** [comment]
code-server prints out the data directory now.

See the https://github.com/cdr/code-server/releases/tag/v3.3.0

Data directory is in `~/.local/share/code-server` now.

So `~/.local/share/code-server/User/settings.json`

**Comment by JtMotoX** [comment]
@nhooyr Thank you for the response.  I checked and I see you are correct the data directory now seems to be the "User" directory.  I am specifying '--user-data-dir ~/.local/share/code-server/data' which is where my settings.json is synced/located.  So it looks like the new 3.3.0 ignores this flag even though it is listed as a flag in '--help'?

**Comment by JtMotoX** [comment]
@nhooyr thank you for the response.  It seems that before the settings were under "$user-data-dir/User/settings.json" but now they are located under "$user-data-dir/settings.json" along with the snippets and a few other things.  I have updated my wrapper script which works perfectly now.

```
# COMPATIBILITY OF USER DATA
cp -rp "$DATADIR/User/"* "$DATADIR/"
```
