### ISSUE TITLE
v3.3.0: search is broken

### ISSUE THREAD

**Issue by chenkai2** [cdr/code-server#1683]
- Web Browser: Chrome 81.0.4044.138 (64bit)
- Local OS: MacOS Mojave 10.14.6
- Remote OS: Debian (in official Docker Image)
- `code-server --version`: 3.3.0 52eeccaba1c20279592d790b053639b5ad8ac99d

I can't search anything since I update docker image from v3.2.0 to v3.3.0
the error message is:
spawn /usr/lib/code-server/lib/vscode/node_modules/vscode-ripgrep/bin/rg EACCES

Meanwhile, the instances that use v3.2.0 are alright with searching.

v3.3.0
![image](https://user-images.githubusercontent.com/14203475/82295689-b665b980-99e2-11ea-8b03-4054e0d2d1c5.png)

v3.2.0
![image](https://user-images.githubusercontent.com/14203475/82296386-b31efd80-99e3-11ea-89a2-9af66bc2324d.png)

**Comment by penuts7644** [comment]
@chenkai2 Try updating to 3.3.1. Should be fixed in that version :)

**Comment by chenkai2** [comment]
> @chenkai2 Try updating to 3.3.1. Should be fixed in that version :)

3ks a lot!
