### ISSUE TITLE
node not found

### ISSUE THREAD

**Issue by CristoAMH** [cdr/code-server#1685]
- Remote OS: Ubuntu 18.04
- `code-server --version`: v3.3.1

if I execute the code-server script like "./code-server" it works perfectly but after placing it on /usr/local/bin/ it give me this error at the time of run "code-server" on my terminal: 
`/usr/local/bin/code-server: 20: exec: /usr/local/bin/../lib/node: not found`

I have node installed but don't know what to do.

**Comment by code-asher** [comment]
The script uses a relative path to the Node binary that's packaged with code-server so it can't be moved. There are two things you could do:

- Add code-server's `bin` directory to your path (example: `export PATH="$PATH:/path/to/code-server/bin"`)
- Use a symlink (example: `ln -s /path/to/code-server/code-server /usr/local/bin/code-server`)

**Comment by code-asher** [comment]
Another option is to install the `deb` which will handle everything for you.

**Comment by jacklolidk** [comment]
same error here, but doesn't work on host. tried using the deb but can't connect.

**Comment by tanveer188** [comment]
i am facing the same issue please help

**Comment by tanveer188** [comment]
> The script uses a relative path to the Node binary that's packaged with code-server so it can't be moved. There are two things you could do:
> 
> * Add code-server's `bin` directory to your path (example: `export PATH="$PATH:/path/to/code-server/bin"`)
> * Use a symlink (example: `ln -s /path/to/code-server/code-server /usr/local/bin/code-server`)

please explain simply

**Comment by tanveer188** [comment]
![Uploading Screenshot_20220608-124844.png…]()

**Comment by tanveer188** [comment]
please help bro

**Comment by code-asher** [comment]
@tanveer188 Please open a new issue describing how you installed code-server, how you are running it, and your error message.  Thanks!
