### ISSUE TITLE
Sidebar icon disappears 

### ISSUE THREAD

**Issue by michael34435** [cdr/code-server#1687]
Sidebar icon disappears, I can’t find installed extension icon on my code-server, is it a known issue? (However it’s clickable)
I installed GitLen

![IMG_0024](https://user-images.githubusercontent.com/3980983/82350344-d078b980-9a2d-11ea-9da0-6f56c010d5c5.jpeg)

- Web Browser: Safari & vsapp
- Local OS: iPadOS 13.4.1
- Remote OS: Raspbian (Raspberry Pi4)
- `code-server --version`: 3.3.0

**Comment by nhooyr** [comment]
@michael34435 Can you try upgrading to v3.3.1?

**Comment by michael34435** [comment]
![IMG_0025](https://user-images.githubusercontent.com/3980983/82358076-97921200-9a38-11ea-88ca-6de8951a8c40.jpeg)

upgraded, not works

**Comment by michael34435** [comment]
Is it possible to get any logs? 🤔

**Comment by nhooyr** [comment]
Managed to reproduce this.

Not sure if it's a bug with code-server or we built the extension wrong.

cc @cmoog

**Comment by cmoog** [comment]
Not a build issue given that we're pulling the release directly from Github [here](https://github.com/eamodio/vscode-gitlens/releases/tag/v10.2.1).

**Comment by nhooyr** [comment]
Looks like it's a Safari issue, icon shows up in Chrome.

**Comment by michael34435** [comment]
yup, i had tried chrome(in macOS) this morning. it works

![IMG_0026](https://user-images.githubusercontent.com/3980983/82393651-a51bbc00-9a79-11ea-9373-0817ffd37fcd.png)

**Comment by michael34435** [comment]
But Safari in macOS ... no icons like iPad too
