### ISSUE TITLE
the handshake took longer than 10 seconds. Error:

### ISSUE THREAD

**Issue by georgica** [cdr/code-server#1690]
- Web Browser: Brave Browser, Chrome, FireFox
- Local OS: Mac
- Remote OS: Ubuntu
- `code-server --version`: all versions
I have installed code-server on a arm64 SBC and 90% of the time i get: 

  ERR [remote-connection][Management   ][51c1f…][initial][localhost:30011] the handshake took longer than 10 seconds. Error:
log.ts:197   ERR Error: handshake timeout
    at remoteAgentConnection.ts:114
log.ts:197   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
log.ts:197   ERR Error: handshake timeout
    at remoteAgentConnection.ts:114
log.ts:197   ERR Error: handshake timeout
    at remoteAgentConnection.ts:114

Any help would be appreciated!

**Comment by nhooyr** [comment]
> code-server --version: all versions

What version are you using?

Can you check the `code-server` logs?

See https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-debug-issues-with-code-server

**Comment by nhooyr** [comment]
This is likely to be part of https://github.com/cdr/code-server/issues/1738 so I'm going to close for now but let me know what you find.
