### ISSUE TITLE
 Always remind this today, but download reminder 404

### ISSUE THREAD

**Issue by gitsrc** [cdr/code-server#1692]
- Web Browser: chrome
- Local OS: mac
- Remote OS: centos7
- Remote Architecture:
- `code-server --version`: 3.2.0 fd36a99a4c78669970ebc4eb05768293b657716f
<img width="473" alt="WX20200520-112051@2x" src="https://user-images.githubusercontent.com/34047788/82401446-680cf500-9a8c-11ea-8c9b-dd037df70e78.png">

**Comment by nhooyr** [comment]
Should be fixed now.
