### ISSUE TITLE
Code server missing globalStorage folder

### ISSUE THREAD

**Issue by nathanrpage97** [cdr/code-server#1693]
code server is missing a globalStorage folder on configuration:

For linux default location:

    ~/.local/share/code-server/User

Missing this issue causes extensions that rely on this folder to error (e.g., todo tree).

Edit: [Reference to vs code api](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext.globalStoragePath)

**Comment by nathanrpage97** [comment]
Actually this is something that todo tree should do based off of API.

**Comment by nathanrpage97** [comment]
I missed the final part

    However, the parent directory is guaranteed to be existent

**Comment by penuts7644** [comment]
As a quick fix you could just make a `globalStorage` directory under `~/.local/share/code-server/User/` and then reinstall Todo Tree.

**Comment by nathanrpage97** [comment]
Yea thats what I did as a temp fix, but this was just for reporting a spec oversight.

**Comment by nhooyr** [comment]
cc @code-asher

**Comment by nathanrpage97** [comment]
Actually this is fixed in v3.3.1.

**Comment by nhooyr** [comment]
Awesome!

**Comment by dvyas1** [comment]
> Actually this is fixed in v3.3.1.

I am on v3.4 and this folder is still missing.
