### ISSUE TITLE
There is no extension I want to use

### ISSUE THREAD

**Issue by lancerXXXX** [cdr/code-server#1698]
I am using an extension called `Hypersnips` which can run both on Windows and Linux. 
I don't know how this code-server work, so I don't know Which side your code-server or the author of that extension for using this extension on my arm device

And I am using  this one , code-server-3.3.1-linux-arm64.tar.gz on my arm devie

**Comment by lancerXXXX** [comment]
I have solved it by cloning the extension files to the user's extension folder

**Comment by nhooyr** [comment]
Nice!
