### ISSUE TITLE
Access vscode object

### ISSUE THREAD

**Issue by gogolith** [cdr/code-server#1700]
Hi, is there any way to access the vscode object via chrome dev console? 
p.e. for accessing the commands api 
(https://vscode-docs.readthedocs.io/en/latest/extensionAPI/vscode-api-commands/)

**Comment by code-asher** [comment]
I think it's only accessible from extension hosts at the moment, so to use it you'd have to create a VS Code extension.

**Comment by nhooyr** [comment]
@code-asher That's the same in regular VS Code right?

Or is this related to the issue about not being able to debug the extension host.

**Comment by code-asher** [comment]
Yep, it's the same in regular VS Code. 

I don't think it's about debugging, I think it's about using the VS Code API so you can do type things like `vscode.executeCommand("workbench.action.files.save")` from the browser console.

I'm not completely certain what the use case would be here that couldn't be fulfilled by using the command palette or writing a normal extension though. @gogolith do you have any specific use cases in mind?

**Comment by gogolith** [comment]
i hoped for something like a js bridge to inject some code within special environments. ok, thank you for the infos... i'll investigate in creating an extension.
