### ISSUE TITLE
Files and folders are not displayed

### ISSUE THREAD

**Issue by lancerXXXX** [cdr/code-server#1702]
I use code-server on my Android device which has installed an ubuntu
I start code-server in ubuntu and then I use an Android browser access localhost: 8080

Everything is ok,  but
the files and folders are not displayed which are cloned with git from github in the sidebar showing documents and folders,
the other files which I created by myself in the Linux can be display.

**Comment by nhooyr** [comment]
Can you please post screenshots, I don't understand the problem.

**Comment by lancerXXXX** [comment]
I have a poor English, I will try my best to make you understand

![image](https://user-images.githubusercontent.com/42160297/82631836-1c438280-9c29-11ea-9874-220a555a8977.png)
I use `Termux` to run an ubuntu on my arm device

![image](https://user-images.githubusercontent.com/42160297/82631922-5a40a680-9c29-11ea-9183-28273b309e60.png)
this folder is git cloned from Github, 
the files in this folder are not showed in the sidebar,

![image](https://user-images.githubusercontent.com/42160297/82632041-b99eb680-9c29-11ea-8c36-701e35c4f379.png)

I tried to open another folder which I download with `Wget`, with the same problem, the folder can not be expanded

but other files or folders created by myself with vim or other tools can be displayed



and if I open the files in the folder that can not be shown with `code`, they can be edited

**Comment by nhooyr** [comment]
Have you been able to reproduce this on the latest versions?
