### ISSUE TITLE
npm install 3.3.1 results in 300MB of extras compared to 3.3.0

### ISSUE THREAD

**Issue by aptalca** [cdr/code-server#1704]
Hi,

I'm doing npm install in a dockerfile: https://github.com/linuxserver/docker-code-server/blob/master/Dockerfile

When I build with 3.3.0, the local image size is 551MB, as expected (~190MB compressed on docker hub).

But when I build with 3.3.1, the local image size is 858MB (~290MB compressed). Same dockerfile.

Any ideas why there is a huge discrepancy in what I assume node module dependencies between the two versions?

Thanks

**Comment by nhooyr** [comment]
Interesting, while there should be a difference between the two because we changed how they're bundled into the final release, it shouldn't be this large.

In 3.3.0, we copied the lib/vscode node_modules directory from the built directories into the final release. Then when you'd install, we'd run `npm rebuild` to rebuild all native modules but the problem with this was some dependencies bundled executables which we also have to refetch so we decided we'd fetch all lib/vscode node_modules in `postinstall` and this seems to work properly.

Now that shouldn't result in such a massive increase in size though. Maybe the build process is doing something to optimize what's included and we should repeat that in the `postinstall`.

cc @code-asher

**Comment by nhooyr** [comment]
Actually it seems to be the same size.

See https://github.com/cdr/code-server/releases

3.3.0 releases are approximately the same size as 3.3.1 and they're all just the npm package with node_modules + node bundled.

**Comment by aptalca** [comment]
In the dockerfile, we simply do `npm install --unsafe-perm -g code-server@"$CODE_VERSION"` using nodejs 12 from their official repo, on an ubuntu bionic baseimage.
We pass a build arg for `CODE_VERSION`.

Here's an image built with 3.3.0: https://hub.docker.com/layers/lsiodev/code-server/v3.3.0-pkg-4c123a3c-dev-9137da0f154cbad6946846cce08ee42ddd603a1a/images/sha256-2c5849899cc173ec18f3eb9d0659fdeb492032913de0b66efeff5937b5dfc11e?context=explore
and here's an image built with 3.3.1: https://hub.docker.com/layers/linuxserver/code-server/v3.3.1-ls42/images/sha256-08a9f7b789ed0e5f5314cea4abeaf655149435322b17c503847a8d767d4d72e0?context=explore

They are using the same dockerfile and the only difference between the two is the `CODE_VERSION` build arg that was passed

**Comment by nhooyr** [comment]
Only difference is we're using yarn. Can you try `yarn` instead?

**Comment by aptalca** [comment]
Same thing with yarn (and both images are larger than their npm counterparts):
```
REPOSITORY    TAG   IMAGE ID            CREATED              SIZE
3.3.0   latest     45d77051815b        About a minute ago   742MB
3.3.1   latest     6c7f5251014f        21 minutes ago       956MB
```
Also noticed that when installed with npm, the executable is at `/usr/bin/code/server` but when installed with yarn, it is at `/usr/local/bin/code-server`

Here's the dockerfile I used with yarn:
```
FROM lsiobase/ubuntu:bionic

# set version label
ARG BUILD_DATE
ARG VERSION
ARG CODE_RELEASE
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="aptalca"

# environment settings
ENV HOME="/config"

RUN \
 echo "**** install node repo ****" && \
 apt-get update && \
 apt-get install -y \
        gnupg && \
 curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - && \
 echo 'deb https://deb.nodesource.com/node_12.x bionic main' \
        > /etc/apt/sources.list.d/nodesource.list && \
 curl -s https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
 echo 'deb https://dl.yarnpkg.com/debian/ stable main' \
    > /etc/apt/sources.list.d/yarn.list && \
 echo "**** install build dependencies ****" && \
 apt-get update && \
 apt-get install -y \
        build-essential \
        libx11-dev \
        libxkbfile-dev \
        libsecret-1-dev \
        pkg-config && \
 echo "**** install runtime dependencies ****" && \
 apt-get install -y \
        git \
        jq \
        nano \
        net-tools \
        nodejs \
        sudo \
        yarn && \
 echo "**** install code-server ****" && \
 if [ -z ${CODE_RELEASE+x} ]; then \
        CODE_RELEASE=$(curl -sX GET "https://api.github.com/repos/cdr/code-server/releases/latest" \
        | awk '/tag_name/{print $4;exit}' FS='[""]'); \
 fi && \
 CODE_VERSION=$(echo "$CODE_RELEASE" | awk '{print substr($1,2); }') && \
# npm install --unsafe-perm -g code-server@"$CODE_VERSION" && \
# npm prune --production && \
 yarn global add code-server@"$CODE_VERSION" && \
 echo "**** clean up ****" && \
 apt-get purge --auto-remove -y \
        build-essential \
        libx11-dev \
        libxkbfile-dev \
        libsecret-1-dev \
        pkg-config && \
 apt-get clean && \
 rm -rf \
        /tmp/* \
        /var/lib/apt/lists/* \
        /var/tmp/*

# add local files
COPY /root /

# ports and volumes
EXPOSE 8443
```

**Comment by aptalca** [comment]
OK, I was able to reduce the sizes significantly by doing:
```
 yarn --production global add code-server@"$CODE_VERSION" && \
 yarn cache clean && \
```
Now the sizes are down to `474MB` for `3.3.1` and `508MB` for `3.3.0` compared to `742MB` and `956MB` before.

The side effect is that the cache clean also gets rid of the `/usr/local/bin/code-server`, but I can easily add a symlink to point to `/node_modules/.bin/code-server`

**Comment by nhooyr** [comment]
Ohh that makes sense, `npm` and `yarn` are both caching all node_modules which causes duplicates.

Before they were never pulling in `lib/vscode` node_modules because they were fully bundled except for the native modules.

Still not sure where that extra 200 MB is coming from hmm

**Comment by aptalca** [comment]
Well, great news. When installed with yarn, the arm32v7 image also works :) I submitted a PR for the linuxserver image: https://github.com/linuxserver/docker-code-server/pull/32

**Comment by nhooyr** [comment]
Now that's seriously weird lol.

**Comment by aptalca** [comment]
New build of 3.3.1 is pushed to the linuxserver repo. Image size is back to normal. Thanks for your help. It also works on arm32v7.
