### ISSUE TITLE
--disable-updates is a huge quality of life feature for Docker installs and it's seemingly an unrecognized option.

### ISSUE THREAD

**Issue by Leopere** [cdr/code-server#1708]
```bash
docker logs -f visual_visual.1.c9ws9k6xup3e0uhu720k7kqm7
Unknown option --disable-updates
```

It seems like kind of a bummer to have to repeatedly dismiss the update notification when the update function has no control over the container itself.  So ideally can we have this back or have the `code-server --help` updated to refer to the new flag?

**Comment by Leopere** [comment]
Even more useful deprecation notices in the code would be awesome when it comes to launch flags because randomly the code-server just gives up existing because a flag got removed almost overnight and this is like the 6th time I've had to re-assess the launch flags since adopting code-server in my workflow.

Amazing work by the way :)

**Comment by nhooyr** [comment]
@Leopere Automatic updates have been completely removed so you shouldn't see that notification anymore at all.

I agree, next time we'll just allow the flag to go through for something simple like this being removed.

Sorry for the trouble and glad you're enjoying it <3

**Comment by Leopere** [comment]
Like I definitely understand the mentality of "if we're not certain then don't" because it may put secure code at risk if the launch flags change without much notification.  

I'm running the latest code-server image `image: codercom/code-server:latest` and I was getting this notification is this a new update you'd just pushed that I've got to wait for the docker hub to build before I can pull?

**Comment by nhooyr** [comment]
Was pushed days ago. What does `code-server --version` report?

**Comment by Leopere** [comment]
I get `image: codercom/code-server:latest` which seems to not be bothering me for updates now that you ask.  By now it would've been bothering me.

**Comment by Leopere** [comment]
Again wonderful work I'm looking forward to deploying this software in a stack for our web dev team in our personal development environments I'm stitching together.

**Comment by nhooyr** [comment]
Awesome, thanks, glad it's all working out well!

**Comment by nhooyr** [comment]
Let me know if you need anything else :)
