### ISSUE TITLE
Static installation: dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.66.dylib

### ISSUE THREAD

**Issue by sujeilyfonseca** [cdr/code-server#1710]
**Version:** code-server-3.3.1-macos-amd64
**OS:** Mac OS Mojave 10.14.6

</br>

**Description:** I need to install statically, as I need to install supported versions in my automation environment. However, after my last issue was solved, I tried to install the latest, but I get the following error: 

```
(base) Sujeilys-MBP:code-server-3.3.1-macos-amd64 sfonseca$ ./code-server 
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.66.dylib
  Referenced from: /Users/sfonseca/Downloads/code-server-3.3.1-macos-amd64/bin/../lib/node
  Reason: image not found
Abort trap: 6
```

Everything is up to date in my environment.

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/1640#issuecomment-629966663

Will fix with in #1701 and then should be in the next release in the next few days.

**Comment by trodemaster** [comment]
So I just pulled down https://github.com/cdr/code-server/releases/download/v3.4.1/code-server-3.4.1-macos-amd64.tar.gz and am seeing this exact issue still. Are we sure this has been fixed? 

```
/Users/username/code-server-3.4.1-macos-amd64/bin/code-server 
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.67.dylib
  Referenced from: /Users/username/code-server-3.4.1-macos-amd64/lib/node
  Reason: image not found
Abort trap: 6
```

**Comment by nhooyr** [comment]
Hmm can reproduce, not sure what happened. Reopening.

**Comment by nhooyr** [comment]
Found it, had $PATH badly set in one of the CI scripts.

**Comment by nhooyr** [comment]
Will be fixed in the next release, sorry 🤦

**Comment by nhooyr** [comment]
I'll also just replace the existing macOS release.

**Comment by nhooyr** [comment]
Updated. Will still be sure to mention in next release's notes.

**Comment by trodemaster** [comment]
OK pulled down the refreshed build and it's working for me now. Thanks!

**Comment by nhooyr** [comment]
[v3.5.0 with VS Code v1.48.2 has been released, fixing this issue!](https://github.com/cdr/code-server/releases/tag/v3.5.0) 🍻
