### ISSUE TITLE
Codespaces availability

### ISSUE THREAD

**Issue by 35359595** [cdr/code-server#1712]
- [ Visual Studio Codespaces ] :
- [ [git](https://github.com/MicrosoftDocs/vsonline) | [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vsonline.vsonline) ] Extension GitHub or homepage:

Not sure if this is possible at all as this extension allows to connect to remote environment and work directly with it and I'm running code-server on my smartphone and basically already connected to "remote" backend.

Thanks for looking into it anyways!

**Comment by cmoog** [comment]
Unfortunately, this extension is closed source and thus cannot be distributed in the `code-server` extension marketplace.

**Comment by nhooyr** [comment]
Yup. We have some docs on the parts of VS Code that are closed source at https://github.com/cdr/code-server/blob/master/doc/CONTRIBUTING.md#vs-code-patch
