### ISSUE TITLE
v3.3.1 Extensions installed via code-server --install-extension in incorrect path

### ISSUE THREAD

**Issue by nathanrpage97** [cdr/code-server#1713]
So when install extension on code-server via cli

```bash
code-server --install-extension ms-python.python
```
It is installing those extensions to ~/.vscode-oss/extensions/.

I can still install successfully via the graphical interface. They correctly show up in ~/.local/share/code-server/extensions/

**Comment by nathanrpage97** [comment]
This issue only shows up in static release install method, it works correctly using debian packaging.

**Comment by nhooyr** [comment]
Ah this is due to #1676 

Will fix ASAP.

**Comment by nhooyr** [comment]
That's bizarre though, Debian package should reproduce it.

🤷 

Either way will be fixed soon.
