### ISSUE TITLE
Vim plugin works with Chromium, but not Firefox or WebKit

### ISSUE THREAD

**Issue by tidux** [cdr/code-server#1715]
![](https://user-images.githubusercontent.com/1330562/82637477-b370f180-9bb9-11ea-9ef0-d2a20da4715a.png)

- Web Browser: Firefox 76 and Epiphany 3.36.1
- Local OS: Arch Linux, Ubuntu 18.04, Windows 10 1809
- Remote OS: Debian 10
- Remote Architecture: aarch64
- `code-server --version`: 3.3.1 6f1309795e1cb930edba68cdc7c3dcaa01da0ab3

Pressing Esc results in a "loading extensions" spinner and then after a few seconds a popup saying toggleVim is not found.  This is not a client-side issue as it is the same across browser engines and OSes, with and without uBlock Origin loaded.  The same version of the extension works with VSCodium 1.45.1 running locally.

The remote server is running code-server and Caddy, both from .debs, with a Let's Encrypt certificate.  I don't think resource pressure is an issue since the system has 4c/4t, 8GB RAM, and with code-server open idles under 10% CPU.

EDIT: mthesaur.txt is used as a lorem ipsum file.  I saw the same issue even on very small source files.

**Comment by tidux** [comment]
Hmm, this might actually be an engine related issue.  The extension works in Chromium.

**Comment by nhooyr** [comment]
Yup, see https://github.com/cdr/code-server/issues/1617
