### ISSUE TITLE
Add Material Theme Icons extension

### ISSUE THREAD

**Issue by CoreyVidal** [cdr/code-server#1717]
- [ ] Extension name: Material Theme Icons
- [ ] Extension GitHub or homepage: https://github.com/material-theme/vsc-material-theme-icons

**Comment by CoreyVidal** [comment]
Just following up on this.

**Comment by cmoog** [comment]
Thank you for the request. `equinusocio.vsc-material-theme-icons` is now live in the `code-server` extension marketplace.
