### ISSUE TITLE
Unknown option --enable-remote-auto-shutdown

### ISSUE THREAD

**Issue by zjcs** [cdr/code-server#1720]
Today, I install the latest code server v3.3.1 on Ubuntu 16.04.5, but  I fail connect the sever throgh VsCode(1.45.1). The log under .vscode-server folder is "Unknown option --enable-remote-auto-shutdown", what does it means?

**Comment by zjcs** [comment]
I try to remove the  --enable-remote-auto-shutdown of vscode extension, the vscode can continue.

But the vscode termianl report the following information after output "Not serving https".

Server id not start successfully. Full server log at ....>>>
> info Using config file ..
...
> info -Not serving HTTPS
><<< End of server log
>
>[timestamp] Received install output:
>[timestamp] Resolver error: The VS Code Server failed to start.

Can you recommand a stable version to me?

**Comment by code-asher** [comment]
The remote extension isn't compatible with code-server unfortunately. Are you running the extension from local VS Code? If so you don't need code-server at all.

**Comment by nhooyr** [comment]
Yea, this issue isn't really clear. Why do you have the `--enable-remote-auto-shutdown` set?

Downloading the latest stable release is documented in the README.

**Comment by zjcs** [comment]
@code-asher @nhooyr 
VsCode is running on the client, and I try to login the remote server by VsCode extension(Remote ssh) which try to download code-server on the remote server. Due to the bad network, I install code-serve offline and meet this issue.

Maybe the remote ssh extension has some problem.

**Comment by zjcs** [comment]
I finnal connect succesfully.

It's due to the server config.

Now, everything works well.

Thanks~
