### ISSUE TITLE
Missing Extension For Spring Boot Dashboard

### ISSUE THREAD

**Issue by ryanjbaxter** [cdr/code-server#1721]
When I start code-server and go to the Spring Boot Dashboard it complains about a missing extension.

This is the extension that is missing, once it is installed everything seems to work.
https://dist.springsource.com/release/STS4/vscode/vscode-spring-boot-1.17.0-RC.1.vsix

**Comment by cmoog** [comment]
Thank you for the request. `pivotal.vscode-spring-boot` is now live in the `code-server` marketplace.

**Comment by ryanjbaxter** [comment]
@cmoog thanks!  Is there anything I need to do to make sure code-server uses it?

**Comment by nhooyr** [comment]
Just install!
