### ISSUE TITLE
Fix Extension request

### ISSUE THREAD

**Issue by Jonpez2** [cdr/code-server#1723]
- [ ] Extension name: Java Language Support
- [ ] Extension GitHub or homepage: https://github.com/georgewfraser/java-language-server

The current installed version of the extension doesn't appear to have been built according to instructions - it's missing a platform-specific embedded jdk, which you get by running the scripts/link_[foo], as instructed on the github readme.  What's the right approach to fixing this please?

Thank you!

**Comment by cmoog** [comment]
Thank you @Jonpez2 for bringing this to our attention! I've pushed a fix to the `code-server` extension marketplace. Please let me know if it doesn't work as expected and I'll reopen this.
