### ISSUE TITLE
Error Lens

### ISSUE THREAD

**Issue by mover96** [cdr/code-server#1728]
- [ ] Extension name: Error Lens by usernamehw
- [ ] Extension GitHub or homepage: https://github.com/usernamehw/vscode-error-lens

**Comment by cmoog** [comment]
Thanks for the request! `usernamehw.errorlens` is now live in the `code-server` extension marketplace.

**Comment by wieluk** [comment]
Hey Is error lens working for you ?
I am getting:
>Unable to open '': Unable to resolve resource file:///?itemName%3Dusernamehw.errorlens.
