### ISSUE TITLE
warn  vscode Unable to retrieve mac address (unexpected format) Browser opens white screen

### ISSUE THREAD

**Issue by 871690991** [cdr/code-server#1731]
Browser opens white screen
Version: code-server_3.3.1_arm64.deb
OS: aarch64

**Comment by 871690991** [comment]
info    - Not serving HTTPS
warn  vscode Unable to retrieve mac address (Error: Command failed: /sbin/ifconfig -a || /sbin/ip link
/data/data/com.termux/files/usr/bin/sh: 1: /sbin/ifconfig: Permission denied
/data/data/com.termux/files/usr/bin/sh: 1: /sbin/ip: Permission denied
)

**Comment by SpinningK** [comment]
me too. Occurred in ubnutu run in termux.

**Comment by code-asher** [comment]
The MAC address is used to generate a unique machine ID for telemetry but it shouldn't affect loading code-server. Still, you can try passing `--disable-telemetry` and see what happens.

If that doesn't help then:

- How are you accessing code-server? For example directly or through a reverse proxy? 
- Are there any logs in the browser console?

**Comment by nhooyr** [comment]
Also see https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-debug-issues-with-code-server

**Comment by 871690991** [comment]
Found the reason, Android browser can't open,Chrome is ok.

**Comment by 871690991** [comment]
> The MAC address is used to generate a unique machine ID for telemetry but it shouldn't affect loading code-server. Still, you can try passing `--disable-telemetry` and see what happens.
> 
> If that doesn't help then:
> 
> * How are you accessing code-server? For example directly or through a reverse proxy?
> * Are there any logs in the browser console?

Found the reason, Android browser can't open,Chrome is ok.

**Comment by 871690991** [comment]
> Also see https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-debug-issues-with-code-server
Found the reason, Android browser can't open,Chrome is ok.

**Comment by 871690991** [comment]
> me too. Occurred in ubnutu run in termux.

Found the reason, Android browser can't open,Chrome is ok.

**Comment by nhooyr** [comment]
Nice!
