### ISSUE TITLE
Support for multiple users?

### ISSUE THREAD

**Issue by nmvega** [cdr/code-server#1734]
Hello Friends:

I'm thinking of running `code-server` on a well-equipped home server for a small class I'm giving.

Does `code-server` support multiple users out of the box? If not, perhaps running parallel instances, each listening on a unique HTTP `port` might do? Or maybe you have a better idea based on your knowledge of the product and it's roadmap?

Thank you in advance! (and for this solution). =:)

**Comment by nmvega** [comment]
Ah, never mind. I found the main thread about this [here](https://github.com/cdr/code-server/issues/33). =:)

**Comment by nhooyr** [comment]
Awesome!
