### ISSUE TITLE
Scopes not working properly

### ISSUE THREAD

**Issue by canbakiskan** [cdr/code-server#1735]
- Web Browser: Safari, Version 13.1 (15609.1.20.111.8)
- Local OS: Mac OS 10.15.4 
- Remote OS: Ubuntu 16.04
- Remote Architecture: x86_64
- `code-server --version`: 3.3.1

Hello, I appreciate the effort you put into this project. I have found a minor bug: I use custom syntax highlighting for member access in Python. I noticed that the scope detection for this type wasn't working properly. On the left you can see code-server scope inspection pop-up, and on the right you can see the same thing for native VS Code.

<img width="250" alt="Screen Shot 2020-05-27 at 16 40 02" src="https://user-images.githubusercontent.com/17336763/83082751-23a7c900-a039-11ea-9f67-419faaf9a9a9.png"> <img width="350" alt="Screen Shot 2020-05-27 at 16 41 01" src="https://user-images.githubusercontent.com/17336763/83082758-27d3e680-a039-11ea-9378-328e8297366d.png">

If you describe why this happens and maybe point out to specific files I can try to fix it myself. Thank you.

**Comment by code-asher** [comment]
I tried out 3.3.1 but mine has the `meta.member.access.python` scope.

Do you have any errors logged in the browser console?

As for the specific files, the grammar can be found [here](https://github.com/microsoft/vscode/blob/074fc4d8da3f3bc8d2a3ca2a9d4034d8c4f6e1bb/extensions/python/syntaxes/MagicPython.tmLanguage.json#L387). This file is loaded by the browser to do the tokenization so it might be worthwhile to double-check it's correct on the browser end by finding it in the network tab. Maybe it's been cached from an older version or something.

**Comment by code-asher** [comment]
Closing for now, please comment if you can still replicate on 3.5.0!
