### ISSUE TITLE
Question: Using code-server with nginx and base path appended

### ISSUE THREAD

**Issue by nao20010128nao** [cdr/code-server#1739]
I expose (old) code-server via nginx, with the base path set. (e.g. expose code-server at `/vs-code/`)      
(SSL is configured at nginx, so I don't need SSL on `code-server`.)    
Is it possible to use `code-server` with the base path in the current version? If it's possible, how should I configure `code-server`?

**Comment by nhooyr** [comment]
cc @code-asher

**Comment by nathanrpage97** [comment]
@nao20010128nao if code server doesn't have the ability to set base path, you can always setup nginx to [rewrite requests](https://gist.github.com/soheilhy/8b94347ff8336d971ad0#step-7----rewriting-requests).

**Comment by dtsmith2001** [comment]
See the Deep Ocean tutorial I put in #1741

**Comment by code-asher** [comment]
Yup, the critical part is the trailing slash on `proxy_pass`.
```
    location /vs-code/ {
      proxy_pass http://localhost:8080/;
```
That's what makes nginx rewrite the URL without the base path.

**Comment by nhooyr** [comment]
Makes sense, all our links are relative otherwise so that's why `--base-path` was removed.

**Comment by bclermont** [comment]
> See the Deep Ocean tutorial I put in #1741

deep ocean?
