### ISSUE TITLE
can not open terminal 3.4.0

### ISSUE THREAD

**Issue by roccqqck** [cdr/code-server#1743]
I can not open a new terminal

- Web Browser: firefox 76.0.1
- Local OS: mac 10.13
- Remote OS: ubuntu18.04
- Remote Architecture: x64
- `code-server --version`: 3.4.0

**Comment by opoloko** [comment]
yeah same problem, also extensions (at least some) are installed but not working, as reported also in https://github.com/cdr/code-server/issues/1742

**Comment by nhooyr** [comment]
Duplicate of https://github.com/cdr/code-server/issues/1742
