### ISSUE TITLE
Not able to open terminal

### ISSUE THREAD

**Issue by dhlassociates** [cdr/code-server#1745]
code-server came up but not able to open terminal.  It is Starting .. indefinitely.

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Redhat 7
- Remote Architecture: x64
- `code-server --version`: 3.3.1

![image](https://user-images.githubusercontent.com/9020003/83181810-4807b200-a0da-11ea-9e7f-0995cb7d9d90.png)

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/1742
