### ISSUE TITLE
Terraform Extension does not seem to work properly

### ISSUE THREAD

**Issue by jonasbark** [cdr/code-server#1748]
E.g. when I run a command from the Command Palette, e.g. Terraform: Lint it displays the following error:
Command 'Terraform: Lint' resulted in an error (command 'terraform.lint' not found)
Steps to reprodue:

1. ```curl -fsSL https://code-server.dev/install.sh | sh```
2. ```code-server --bind-addr 0.0.0.0:8080 --auth none```
3. install Terraform executable locally
4. install Terraform extension in Code Server
5. run Terraform Lint from command palette

- Web Browser: Chrome
- Local OS: Chrome OS 83
- Remote OS: Chrome OS Linux Container
- Remote Architecture: ARM64 (aarch64)
- `code-server --version`: 3.4.0

Thank you for code server!

**Comment by code-asher** [comment]
Looks like the error is:

```
Activating extension 'mauve.terraform' failed: Cannot find module './constants.json' 
```

I was able to work around this by creating an empty `constants.json` file in the extension's directory:

```
echo '{}' > ~/.local/share/code-server/extensions/mauve.terraform-1.4.0/out/src/constants.json
```

It appears that normally this file holds the app insights key (for analytics) so it shouldn't be a problem to just leave it blank.

It looks like normally they generate this file with an extra build step so I suppose we'll need to add that to our build process as well.

**Comment by code-asher** [comment]
A fixed version has been uploaded to our marketplace; please let me know here if you run into any additional problems with the extension!

**Comment by nhooyr** [comment]
cc @cmoog
