### ISSUE TITLE
ARM64 support + Raspbian 64 bit support

### ISSUE THREAD

**Issue by adambutler** [cdr/code-server#1749]
First I’d like to say please excuse my lack of deep understanding here.

I simply wanted to ask the question of if recent developments in Raspbian supporting 64bit OS and the news that VS Code can run on [ARM64](https://www.theregister.co.uk/2020/05/29/visual_studio_code_windows_arm64/) helps efforts to get code-server to work on the Raspberry Pi at all?

**Comment by nathanrpage97** [comment]
I have gotten code-server to run on both [balena 64 bit OS](https://www.balena.io) and [Ubuntu 20.04](https://ubuntu.com/download/raspberry-pi) so if there are any issues I'd imagine it would be with the new Raspbian OS.

**Comment by Merith-TK** [comment]
@nathanrpage97 The default raspbian OS download is for armv7

**Comment by nathanrpage97** [comment]
You are correct that the current OS is for armv7. I assume Adam is talking about the new [Raspberry Pi OS](https://www.raspberrypi.org/forums/viewtopic.php?t=275370) which is a 64 bit arm64. **Note**: It is in beta.

**Comment by nhooyr** [comment]
You can already run it on the pi with the NPM package. See https://github.com/cdr/code-server/blob/master/doc/install.md#yarn-npm

Also see #1337
