### ISSUE TITLE
user-data-dir, extensions-dir  in config file still doesn't work

### ISSUE THREAD

**Issue by silenceleaf** [cdr/code-server#1750]
user-data-dir, extensions-dir 

in config file still doesn't work

please test it.

Version: 3.4.0

**Comment by nhooyr** [comment]
For posterity, this was fixed by https://github.com/cdr/code-server/commit/2c2a6498afe6588e1c2221d2fc2d748a5589c919

**Comment by nhooyr** [comment]
New release is out!
