### ISSUE TITLE
Lando usage

### ISSUE THREAD

**Issue by sebastien-metzger** [cdr/code-server#1751]
Hello,

Is there anybody who successfully use [lando](https://docs.lando.dev/) on a cloud server like DigitalOcean with code-server?

I am not a network expert and I don't know how to configure proxy and DNS stuff: for the moment I have an up and running code-server running on a DigitalOcean Droplet with a custom domain name and lando is starting by overriding proxyHttpsPort set to 444 but I cannot access the running web app I have launched via lando.

Have a good day.
Best Regards,

**Comment by nhooyr** [comment]
Also highly recommend accessing launched web apps via code-server.

See https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-securely-access-web-services

**Comment by sebastien-metzger** [comment]
Thank you @nhooyr!
Have a good day.

PS : my current solution is to disable proxy in Lando and configuring Caddy properly.

**Comment by nhooyr** [comment]
Nice! Caddy is great :)

**Comment by asmerkin** [comment]
Guys, have you had an issue when lando not working properly with code-server?  I can execute lando via SSH to my server but if I want to use the vscode terminal it does nothing ... 

Any clues? Any place to debug vscode to see what's going on? 

Thank you!

**Comment by jsjoeio** [comment]
@asmerkin might be better to ask as a GitHub Discussion!
