### ISSUE TITLE
Add Prisma extension

### ISSUE THREAD

**Issue by Murbal** [cdr/code-server#1752]
- [x] Extension name: Prisma
- [x] Extension GitHub or homepage: https://github.com/prisma/vscode

**Comment by cmoog** [comment]
Thank you for your request! To add this extension to the `code-server` marketplace, we need the extension publisher to include the `vsix` bundle in their Github releases. Please open an issue in the extension repository requesting that the authors do so.

**Comment by janpio** [comment]
Hey, Prisma here. The Github releases of the extension repository include the vsix file for some time now already: https://github.com/prisma/language-tools/releases 

Note that we are publishing both extensions, Prisma and Prisma Insider, via that repository and use a naming scheme to differentiate the releases and tags: https://github.com/prisma/language-tools/releases/tag/2.22.1 vs. https://github.com/prisma/language-tools/releases/tag/insider%2F23.0.11

**Comment by jsjoeio** [comment]
Thanks for the update @janpio!

And it looks like you [publish](https://open-vsx.org/extension/Prisma/prisma-insider) [both](https://open-vsx.org/extension/Prisma/prisma) to open-vsx, which is great!

I'm going to close this.

**Comment by janpio** [comment]
Oh yes we do - if that is helpful we did the right thing here :D
