### ISSUE TITLE
A URL for the latest RPM / DEB / TAR-GZ packaged version of Code Server ...

### ISSUE THREAD

**Issue by nmvega** [cdr/code-server#1754]
Hello Friends:

I hope you're well.

I'm building a `Docker` container (using a `Dockerfile`) and want to install the latest version of your `delightful product` (thank you for it).

I'm doing this as `Infrastructure As Code`. However, I can't tell where to find the `URL` for it's `latest` version [here](https://github.com/cdr/code-server/releases); specifically the latest `RPM`, `DEB` or even `TAR/GZ` packages for it.

Can you create them?

For instance:

```
https://[....]/code-server-LATEST-amd64.rpm
https://[....]/code-server-LATEST-amd64.deb
https://[....]/code-server-LATEST-linux-amd64.tar.gz
```

Thank you in advance.

**Comment by nmvega** [comment]
Ah, never mind. I looked a little more closely and found that the above is accomplished via:

`root# curl -fsSL https://code-server.dev/install.sh | sh`

which will install a `.deb` or `.rpm` package, according to the distribution it discovers.

Closing the issue, but hoping this helps others.

**Comment by nhooyr** [comment]
Yup, the install script is def the easiest way to install the latest version.
