### ISSUE TITLE
Multiple Errors Causing Application to be Unusable

### ISSUE THREAD

**Issue by aidandamerell** [cdr/code-server#1755]
The majority of the functionality of the application is broken and I'm unsure as to the root cause.

The status bar has the following continuously: `Initializing JS/TS language features`, and when I try run a task, `Activating Extensions` but the pallete never opens.

Broken components:
- Terminal
- Run task pallete
- intellisense

Browser Console Error:
```
The connection to wss://<hostname>/?type=ExtensionHost&reconnectionToken=<TOKEN>&reconnection=true&skipWebSocketFrames=false was interrupted while the page was loading.
```
There also appears to be a continuous loop in the browser console of reconnects.

Log (Remote Server) Error Message:
```
[2020-06-02 07:36:59.959] [remoteagent] [error] [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/home/coder/.local/share/code-server/Machine'
```

- Web Browser: Firefox Developer Edition
- Local OS: MacOS Cataline
- Remote OS: Docker (Ubuntu)
- Remote Architecture: x64
- `code-server --version`: code-server 3.3.0 7a74689c439e8e575a13267d24ecd3e1c9f5145e

The application is running on a Docker swarm behind a traefik reverse proxy.

**Comment by code-asher** [comment]
It sounds like VS Code might be crashing on connection, which in my experience usually has something to do with the native node modules.

Could you check code-server's output? That's usually where those errors show up.

**Comment by nhooyr** [comment]
Please upgrade to the latest version as well!

And see https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-debug-issues-with-code-server

**Comment by aidandamerell** [comment]
Seemingly this was caused by running on Phushion Passengers docker image. Built from the docker image seems to have fixed this.

**Comment by nhooyr** [comment]
Awesome!

**Comment by diegosucaria** [comment]
Hey I'm facing the same issue, I'm running code-server on a VM with a lot of cores and ram....

Any ideas what can I try to do?

**Comment by code-asher** [comment]
@diegosucaria Please post some debug logging (https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-debug-issues-with-code-server) in a discussion (under the help category) and we'll see if we can get you sorted.
