### ISSUE TITLE
Release nomenclature inconsistency

### ISSUE THREAD

**Issue by aptalca** [cdr/code-server#1758]
There is a general inconsistency between versioning nomenclature. Some releases are in the format of `X.X.X` and some are `vX.X.X`. In the past, stable releases used one format and pre-releases used another. But now there are two stable releases with the same version number, one with and one without the `v`.

Preferably code-server would pick one nomenclature and run with that for everything (including the npm packages). Constant changes to version and filename formats of bins/packages without any notice make it very difficult for downstream automation.

**Comment by nhooyr** [comment]
I agree there have been mistakes here and I'm sorry!

That second release only exists to make autoupdates work from `3.2.0` work. 

Background at https://github.com/cdr/code-server/releases/tag/v3.4.0

- We made some changes to make autoupdates from `v3.2.0` work again.
   - To recap we removed autoupdating in `v3.3.0` and restructured
      the releases a bit which caused autoupdates on `v3.2.0` to break. See  #1664
   - To fix this:
      1. We added a symlink from `code-server` to `bin/code-server` to the root of the release.
      2. We now upload duplicate release assets for the release naming scheme used by `v3.2.0`.
          - i.e we have `macos-amd64` and `darwin-x86_64` as well as `linux-amd64` and `linux-x86_64`.
  - In the next few weeks the symlinks and the duplicate release assets will be removed so
     please update your scripts to use the new release scheme.

All main releases tags will indeed be prefixed with `v`, we're just trying to update users on the old release structure.

**Comment by nhooyr** [comment]
Updated the release description to make this more clear.
