### ISSUE TITLE
Unable to install termux on OnePlus 5 running on Android pie

### ISSUE THREAD

**Issue by jimsh7237** [cdr/code-server#1760]

**Comment by nhooyr** [comment]
Please provide additional details on what the problem is.

**Comment by jimsh7237** [comment]
I tried to install termux on my OnePlus 5 phone which is running on Android pie non rooted. And I tried to install termux from net hunter app Store and from playstore. But every time it says installation failed.  Theres no details regarding the failure of installation

**Comment by nhooyr** [comment]
@jimsh7237 I'd recommend filing a report with termux, this repository is for code-server.
