### ISSUE TITLE
retrieving extensions from a custom marketplace

### ISSUE THREAD

**Issue by KolyaKorruptis** [cdr/code-server#1762]
In order to get extensions from a custom marketplace, the [FAQ suggest](https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-can-i-request-a-missing-extension) to set two environment variables: $SERVICE_URL and $ITEM_URL. In my experience these are ignored by code-server. 

It turns out you can still achieve this is editing the file: code-server/lib/vscode/product.json
Copying the extension related settings from another product.json like [this one](https://github.com/headmelted/codebuilds/blob/508a782f589c3bf95fc3885e90e52f2dbc2acaa2/overlays/product.json) for example provided me with all the updated extensions.

**Comment by 275761919** [comment]
Thanks very much and that is very helpful!!!
Some extensions that code server caches are too old or have wrong platform version, for example, [codelldb issue 314](https://github.com/vadimcn/vscode-lldb/issues/314)

**Comment by nhooyr** [comment]
@KolyaKorruptis Why'd you end up closing this issue? Did the environment variables end up working?

**Comment by nhooyr** [comment]
Just tested and SERVICE_URL does still work.

**Comment by nhooyr** [comment]
@KolyaKorruptis Yes you technically can use Microsoft's marketplace but please note it is against their terms of use.

See https://github.com/cdr/code-server/blob/master/doc/FAQ.md#differences-compared-to-vs-code

**Comment by nhooyr** [comment]
Documented this further in #1767

**Comment by KolyaKorruptis** [comment]
@nhooyr I closed it immediately, because it isn't actually a feature request. There isn't anything to do here. It's just some information I wanted to pass on.
I realize that if one would use these exact settings, they would technically be in conflict with the TOS, albeit the chances of these being enforced on end users seem pretty slim. 

Regarding the env vars: I may have forgotten to source .bashrc after setting them. Not sure, I'd have to test again. But the changes I described above are easier and more encompassing, as you can also add extension recommendations, etc. So I would always prefer that way. 

Nevertheless some more description on $SERVICE_URL and $ITEM_URL would be welcome. At least it should be mentioned that they are supposed to be set as environment variables. Perhaps even with an example. I wasn't sure if the $-sign should be part of the definition or not. The weirdly overgeneralized named PASSWORD does not take a $-sign.

**Comment by nhooyr** [comment]
> Nevertheless some more description on $SERVICE_URL and $ITEM_URL would be welcome. At least it should be mentioned that they are supposed to be set as environment variables. Perhaps even with an example. I wasn't sure if the $-sign should be part of the definition or not. The weirdly overgeneralized named PASSWORD does not take a $-sign.

I understand but that's standard notation for environment variables. It comes from shell scripts. It gets verbose otherwise to explicitly mention `environment variable` everywhere.

**Comment by KolyaKorruptis** [comment]
Ah, I see, well that's just my ineptitude on linux then. Nevermind.
