### ISSUE TITLE
Control+C not work in code-server integrated terminal

### ISSUE THREAD

**Issue by michael34435** [cdr/code-server#1763]
As mentioned in title, I can't use control+c in integrated terminal. (iPad Pro 2020)

- Web Browser: Safari
- Local OS: iPadOS 13.5
- Remote OS: Raspbian(Raspberry 4)
- Remote Architecture: ARM
- `code-server --version`: 3.4.0

**Comment by nhooyr** [comment]
I thought we had a open issue about this but it does't seem like it.

cc @code-asher

**Comment by chilcano** [comment]
Hi there.
I’m facing similar issue with <kbd>Ctrl</kbd>+<kbd>C</kbd> (copy to clipboard) in the integrated Terminal, but only in Chrome. In Safari and Firefox <kbd>Ctrl</kbd>+<kbd>C</kbd> work. 
However <kbd>Ctrl</kbd>+<kbd>C</kbd> in the Editor panel doesn’t work in any browser. Even I created 1 `Keyboard Shortcut` to copy and it didn't work either.

My config is:
- Web Browser: Safari / Chrome / Firefox
- Local OS: iPadOS 13.5.5
- Remote OS: Ubuntu 20.04
- Remote Architecture: x86_64
- code-server --version: 3.4.0

Regards.

**Comment by nhooyr** [comment]
@chilcano All the browsers on iPad are just reskins of Safari so it's def weird you're seeing issues with chrome.

But anyway, we do have an existing issue see https://github.com/cdr/code-server/issues/1015

No solution as of now though :(

**Comment by michael34435** [comment]
My ctrl + c in code-server works for me 🤣 (I had remapped it)
In terminal... not works 😞
