### ISSUE TITLE
I can't get Java Debugging / Running to work

### ISSUE THREAD

**Issue by Felixkruemel** [cdr/code-server#1768]
- Web Browser: Chrome
- Local OS: Windows 10 2004
- Remote OS: Ubuntu 20.04
- Remote Architecture:  x86_64
- `code-server --version`: 3.4.0 69ad52907e8ea109345831d29da5425cb2a55047

Error: 
ENOENT: no such file or directory, mkdir '/var/lib/code-server/User/globalStorage/redhat.java'
![grafik](https://user-images.githubusercontent.com/12109804/83760439-3b083700-a675-11ea-8458-c1556dbba675.png)

I've installed openjdk-11-jdk openjdk-11-demo openjdk-11-doc openjdk-11-jre-headless openjdk-11-source via apt, but how can I make the code server actually use them? Over the main method standard VS Code has buttons for debugging / running the file.

Either I don't know how to set it up for Java (please explain it then) or that's actually an bug.

**Comment by nhooyr** [comment]
Should be fixed in the new release today. See #1693 and #1766
