### ISSUE TITLE
For building - you may have a look to dockcross

### ISSUE THREAD

**Issue by momiji** [cdr/code-server#1769]
Hello,

I just wanted to share I was once looking for a way to do cross builds for an application, and found something that might be usefull for this project.

It is called [dockcross](https://github.com/dockcross/dockcross) and provides many docker images for compiling projects for several operating systems, including Windows, and maybe MacOS.

Just in case it interests you :)

Good work!

**Comment by nhooyr** [comment]
Going to close this issue but thanks again for the information @momiji
