### ISSUE TITLE
Why duplicate releases and tags?

### ISSUE THREAD

**Issue by SuperSandro2000** [cdr/code-server#1770]
Does this project use git tags with ``v`` or without ``v``? This changed multi times in the last releases which is very confusing and breaks my CI everytime.

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/1758

**Comment by nhooyr** [comment]
My bad, I forgot this changes the latest version for downstream projects pulling code-server.

The release without the v exists only for autoupdates. Context in the above link.

**Comment by nhooyr** [comment]
Yea not sure if we can do anything here now, I don't want to republish two releases again. We wanted to give at least a few weeks for autoupdates to take place.

cc @code-asher 

To be clear, the tag with the `v` **is** the main one. The other is purely for autoupdating users on older versions. If you can, I'd recommend using our install script which handles these things properly.

**Comment by nhooyr** [comment]
[v3.5.0 with VS Code v1.48.2 has been released, fixing this issue!](https://github.com/cdr/code-server/releases/tag/v3.5.0) 🍻

No more tag duplication!
