### ISSUE TITLE
Cannot Load /semver-umd.js

### ISSUE THREAD

**Issue by andre4ik3** [cdr/code-server#1775]
- Web Browser: Firefox Developer Edition 78.0b3 and Chrome Canary 85.0.4165.0
- Local OS: macOS 10.15.5
- Remote OS: Ubuntu 20.04 LTS
- Remote Architecture: x86_64
- `code-server --version`: `3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259`

Whenever I load my code-server through my domain, I get the errors:
- On Firefox DevEdition: `The resource from “https://c.andre4ik3.dev/semver-umd.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).`
- On Chrome Canary: `Failed to load resource server-umd.js: the server responded with a status of 404 ()`

Whenever I connect to it directly, everything works fine.
Here's my [Debug Log](https://github.com/cdr/code-server/files/4736639/code-server-debug.log).
Screenshot:
<img width="1680" alt="blank firefox window with debugger" src="https://user-images.githubusercontent.com/62390580/83888365-a3bce580-a741-11ea-8c42-c731e2f9987e.png">

**Comment by andre4ik3** [comment]
Another thing to note, if password protection is enabled, I can get to the login screen and input my password, before ending up on the blank screen. If password protection is disabled, I am shown the blank screen without anything prior.

**Comment by andre4ik3** [comment]
I just tried using Argo Tunnel for the server, same issue :/
<img width="1288" alt="Снимок экрана 2020-06-05 в 15 52 19" src="https://user-images.githubusercontent.com/62390580/83891079-8c332c00-a744-11ea-9ef7-3fc554ad7a8a.png">
<img width="1680" alt="Скриншот 2020-06-05 15 53 13" src="https://user-images.githubusercontent.com/62390580/83891169-ad941800-a744-11ea-8a61-f8197fb9b5d2.png">

**Comment by nhooyr** [comment]
What happens if you use `v3.4.0`? Or `v3.3.1`?

**Comment by andre4ik3** [comment]
Ok let me install

**Comment by andre4ik3** [comment]
Same thing on `v3.4.0` - now testing `v3.3.1`

**Comment by andre4ik3** [comment]
Same thing on `v3.3.1` as well

**Comment by code-asher** [comment]
That path is odd; it should be `/static/{commit}/lib/vscode/node_modules/semver-umd/lib/semver-umd.js`.

Maybe Cloudflare's Rocket Loader is doing something here?

**Comment by andre4ik3** [comment]
I disabled Cloudflare's Rocket Loader, and that seemed to make some progress, but I am still on a blank screen. The console logs have changed, and it now appears to not be able to establish a WebSocket, both on Firefox and Chrome.
<img width="1680" alt="Снимок экрана 2020-06-08 в 23 49 42" src="https://user-images.githubusercontent.com/62390580/84087763-bc97f600-a9e2-11ea-8bc0-7ecc4f0a8de8.png">
<img width="1680" alt="Скриншот 2020-06-08 23 50 16" src="https://user-images.githubusercontent.com/62390580/84087792-d0dbf300-a9e2-11ea-8b01-420a2eebf3e2.png">

**Comment by code-asher** [comment]
How are you serving code-server? For example nginx, etc. There might be something misconfigured between Cloudflare and code-server.

**Comment by andre4ik3** [comment]
I'm running it through Nginx, as a reverse proxy, with Cloudflare only being used as DNS (i even tried with proxy disabled).

**Comment by code-asher** [comment]
Do you have the upgrade headers set? Something like this:

```
server {
  listen 80;
  listen [::]:80;
  server_name code.example.com code.example.org;
  location / {
      proxy_pass http://localhost:9999/;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection upgrade;
      proxy_set_header Accept-Encoding gzip;
  }
}
```

**Comment by andre4ik3** [comment]
Thanks, setting those headers worked!

**Comment by nhooyr** [comment]
@andre4ik3 We tend to recommend caddy over nginx due to these sorts of issues. Highly recommend checking it out along with https://github.com/cdr/code-server/blob/master/doc/guide.md

**Comment by andre4ik3** [comment]
Yeah I saw that, but I use Nginx for other things on this server, so :/

I'll use it in the future, thanks for telling me.
