### ISSUE TITLE
Code-server won't run after the process been killed

### ISSUE THREAD

**Issue by matheusqueirozzabin** [cdr/code-server#1780]
- Web Browser: Google Chrome 84.0.4147.33
- Local OS: ChromeOS 84.0.4147.33
- Remote OS: Crostini (Debian Buster)
- Remote Architecture: x86_64
- Version: code-server 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259

Every time I run code-server, I can't execute it anymore, even it's not currently running.

If I kill it with Ctrl+C on console, then try to run it again, terminal get stuck forever and doesn't return nothing (then I have to Ctrl+C again to get back to console). I can't even run `code-server --version` for this bug report, it get stuck too.
![image](https://user-images.githubusercontent.com/16930324/83954997-a47a7800-a824-11ea-8ab3-3ff2b9e31e7d.png)

(I've tried `killall code-server` and `killall node` and both return `no proccess found`)

Then you can say - "Ok, so run code-server and forget about it", and I agree, but then come the second bug (which I don't know if it's related with the previous one).

If I let code-server running forever and eventually my Chromebook goes to sleep or suspend mode, when I get back I cant access my repositories anymore, and if I reload the window I can't connect anymore (the dialog says thats impossible to reconnect and says to reload window, then I reload the window again and the loop begins).
![image](https://user-images.githubusercontent.com/16930324/83955277-91b57280-a827-11ea-8927-d777d4d7e1cc.png)

So I have to restart code-server, right? Then I get caught on the first bug and can't use code-server anymore without restarting my container/laptop.

I've run code-server on verbose mode and no errors were shown.

**Comment by matheusqueirozzabin** [comment]
Ok, after all, I've reinstalled and the problem is solved... Closing.

**Comment by nhooyr** [comment]
Glad it worked!

**Comment by jadenPete** [comment]
I just installed code-server and am running into the same issue. Even something as simple as `code-server --help` leaves it unable to run without hanging indefinitely.

**Comment by nhooyr** [comment]
@jadenPete Please file a new issue!

**Comment by jadenPete** [comment]
Oddly enough, I'm not experiencing the issue anymore, but I will if I do!
