### ISSUE TITLE
GitLab Workflow extension

### ISSUE THREAD

**Issue by gyzerok** [cdr/code-server#1781]
- [x] Extension name: GitLab Workflow
- [x] Extension GitHub or homepage: https://gitlab.com/gitlab-org/gitlab-vscode-extension

**Comment by cmoog** [comment]
Thank you for the request! `fatihacet.gitlab-workflow` is now live in the code-server Extension Marketplace.

**Comment by gyzerok** [comment]
Amazing, thanks!
