### ISSUE TITLE
Please add Chat extension

### ISSUE THREAD

**Issue by massimocireddu** [cdr/code-server#1786]
- [ ] Extension name: Chat
- [ ] Extension GitHub or homepage: https://marketplace.visualstudio.com/items?itemName=karigari.chat

**Comment by cmoog** [comment]
Thank you for your request! To add this extension to the `code-server` marketplace, we need the extension publisher to include the `vsix` bundle in their Github releases. Please open an issue in the extension repository requesting that the authors do so.
