### ISSUE TITLE
WHY 'Failed to get D-Bus connection: '?

### ISSUE THREAD

**Issue by fuzheng1998** [cdr/code-server#1787]
I have followed the instruction to make code-server background. However , when I input `sudo systemctl --user enable --now code-server`, it shows `Failed to get D-Bus connection: No such file or directory`, I feel confused why it can be failed.

**Comment by yaerda** [comment]
Me too. I found the solution in another closed issue: [For anyone who just wants to use the bundled service, you can easily fix by running,It'll make code-server a system service and add your current user into the service file and start it for you.](https://github.com/cdr/code-server/issues/1747#issuecomment-639152628)

**Comment by nhooyr** [comment]
See #1771
