### ISSUE TITLE
[Question] how can I get access from iPad?

### ISSUE THREAD

**Issue by radostnomne** [cdr/code-server#1789]
Hi
I have installed code-server via brew (Macos Catalina) and can't connect from ipad in my local network. How can I get access to code-server from iPad?

**Comment by nhooyr** [comment]
Please file questions on our subreddit at https://www.reddit.com/r/codeserver/

Also give https://github.com/cdr/code-server/blob/master/doc/guide.md a read.

You just need to expose code-server on `0.0.0.0` and then access it from your iPad with your MacBook's IP.
