### ISSUE TITLE
Unable to activate ms-python.python

### ISSUE THREAD

**Issue by meain** [cdr/code-server#1792]
- Web Browser: Chrome Version 83.0.4103.97 & Firefox 77.0
- Local OS: MacOS 10.13.6
- Remote OS:  Ubuntu 18.04.3 LTS
- Remote Architecture: amd64
- `code-server --version`:  3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259

---

- `code-server` installed using `.deb` package
- Tried installing extension via `code-server --install-extension` and the gui. Neither seems to work.

### Traceback

```
Activating extension 'ms-python.python' failed: Cannot find module '/home/meain/.local/share/code-server/extensions/ms-python.python-2020.5.2/out/client/extension'
Require stack:
- /usr/lib/code-server/lib/vscode/out/vs/loader.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-fork.js. workbench.web.api.js:3851:320
```

<details> <summary>Full</summary>
<pre>
Activating extension 'ms-python.python' failed: Cannot find module '/root/.local/share/code-server/extensions/ms-python.python-2020.5.2/out/client/extension'
Require stack:
- /usr/lib/code-server/lib/vscode/out/vs/loader.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-fork.js. workbench.web.api.js:3851:320
    _logMessageInConsole http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:3851
    _logOrShowMessage http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:3851
    $onExtensionActivationError http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:3979
    _doInvokeHandler http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:3959
    _invokeHandler http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:3959
    _receiveRequest http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:3957
    _receiveOneMessage http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:3956
    e http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:3954
    fire http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:95
    fire http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:404
    _receiveMessage http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:409
    <anonymous> http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:406
    fire http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:95
    acceptChunk http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:402
    g http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:401
    onData http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:1751
    fire http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:95
    onload http://35.223.194.183:8080/static/48f7c2724827e526eeaa6c2c151c520f48a61259/lib/vscode/out/vs/workbench/workbench.web.api.js:1750
</pre>
</details>

**Comment by keiththomps** [comment]
Hi, if you have version `2020.5.2` then you'll have issues. Right-click the extension in the sidebar and select "Install Another Version" and select the next most recently released version (probably `2020.5.80290`.

**Comment by nhooyr** [comment]
cc @cmoog

**Comment by meain** [comment]
@keiththomps that works, thanks.

Is it possible to specify the extension version with `code-server --install-extension`? I could not find anything related to it.

---

Btw, just for reference. I tried the extenstion with an older version of code-server(3.2.0) which was working before. Seems to have the same issue. So, it could be that the extension is either looking for a new thingy in vscode which is not available or a bug in the extension.

**Comment by keiththomps** [comment]
They cut a new release for the extension (2020.5.86806) that doesn't appear to have any issues, so unless someone explicitly goes out of their way to install this version I don't think there's anything to do here.

**Comment by meain** [comment]
Huh, weird. It was by default installing a different version (`2020.5.2`) before. It seems to work now though.

**Comment by keiththomps** [comment]
Yeah, it looks like some weird version got published to the marketplace. There's not even a github release for `2020.5.2`.

**Comment by nhooyr** [comment]
Looks like it was a bug in our marketplace scraper.

@cmoog has the details

**Comment by davebarkerxyz** [comment]
I get the same error with the extension `hediet.vscode-drawio` from the coder.com repository.

```
abstractExtensionService.ts:396 Activating extension 'hediet.vscode-drawio' failed: Cannot find module '/home/coder/.local/share/code-server/extensions/hediet.vscode-drawio-0.0.1/dist/extension/index'
Require stack:
- /usr/lib/code-server/lib/vscode/out/vs/loader.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-fork.js.
```

I'm not sure if this is caused by the same issue as above or is related to the extension itself.

About screen shows the following versions:

```
code-server: v3.4.1
VS Code: v1.45.1
Commit: 48f7c2724827e526eeaa6c2c151c520f48a61259
Date: 2020-06-04T10:39:14Z (2 mos ago)
Browser: Mozilla/5.0 (X11; CrOS x86_64 13099.102.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.127 Safari/537.36
```

**Comment by nhooyr** [comment]
Please file a new issue @davebarkerxyz! Usually such issues are due to us not building the given extension correctly.
