### ISSUE TITLE
Chrome PWA on macOS crashes when dragging tabs and files

### ISSUE THREAD

**Issue by evanmmitchell** [cdr/code-server#1793]
While running in Chrome on macOS, the PWA crashes if I try to reorder the open tabs or drag a file to another folder. (There is no problem with dragging text, however.) This bug does not appear in Chrome on Windows or when not running as a PWA.

- Web Browser: Google Chrome 83.0.4103.97
- Local OS: macOS 10.15.4
- Remote OS: Ubuntu 18.04.4
- Remote Architecture: x86_64
- `code-server --version`: 3.4.1

**Comment by diegosucaria** [comment]
Yes. It only occurs while pwa is on fullscreen mode. I thought it was something related my machine but if you are facing the same issue it must be a bug.
