### ISSUE TITLE
Heartbeat always gets touched even when no active sockets and browser closed

### ISSUE THREAD

**Issue by lethevimlet** [cdr/code-server#1795]
- `Using docker official image codercom/code-server:latest`
- `code-server --version`: 3.4.1

`.local/share/code-server/heartbeat`
Always get's touched every minute, this happens after the first page load even if there are no active socket connections or browser tabs and never stops.

Having a bogus heartbeat prevents the possibility of shutting containers on AFK clients and you can't rely on a docker container being idle since it might be running a background process like a server or so.

In order to reproduce this issue, just 
1) Run a docker container of code-server, you can do it like on the README.md
2) Login to code-server with your favorite browser (e.g. Chrome)
3) Close browser
4) Run docker exec -it <container_name> bash
5) Watch -n 1 "ls -l .local/share/code-server/heartbeat"

You will see heartbeat file never stops getting touched.
![image](https://user-images.githubusercontent.com/2963923/84327597-0b2ec700-ab80-11ea-92c9-53e4ecac55dd.png)

**Comment by code-asher** [comment]
I can confirm. It looks like Node's `http.getConnections()` returns one even if nothing is connected. Maybe we somehow have a lingering connection somewhere...I'll do some more debugging soon.

**Comment by lethevimlet** [comment]
Any news on this one?

**Comment by code-asher** [comment]
Just tracked it down, will have a PR for it in a sec.
