### ISSUE TITLE
warn  discarding socket connection: vscode is not running

### ISSUE THREAD

**Issue by DynamicDonkey** [cdr/code-server#1796]
- Web Browser: Firefox, Safari, Brave, Chrome
- Local OS: Windows 10, iOS 12.4.7
- Remote OS: XUbuntu
- Remote Architecture:
- `code-server --version`: code-server 3.4.1

Hey there. I'm currently trying to run code-server on my local network for LAN remote development but the server seems to be refusing my connections from other devices, in this case being my desktop PC and iPad Air. I don't believe this is a duplicate of #1484 as following the steps given to resolve the issue do not resolve the problem. 

The server works great over the same device, `http://127.0.0.1:<port>`, but opening up the server with `sudo ufw allow <port>`, then running the server dooes not let me connect to the server. I am greeted by the browsers default "Can't connect to server" page.

The error is the title, but it ends up repeating itself over and over again. Refreshing the page doesn't let me connect, nor does opening a new tab, browser, or using a whole new device.

**Comment by DynamicDonkey** [comment]
Solved. Changing configuration file from 127.0.0.1 to 0.0.0.0 fixed the issue.

**Comment by dongwangdw** [comment]
> Changing configuration file from 127.0.0.1 to 0.0.0.0 fixed the issue.

127.0.0.1 is different from 0.0.0.0. The first is for local access, the later is for external access. Make sure you have this configured properly. I have this warn too:
> warn  discarding socket connection: vscode is not running

But from web, it works well. Refreshing web will stop the messages.
