### ISSUE TITLE
Extensions in the market place are built from master instead of the latest stable tag version

### ISSUE THREAD

**Issue by massimocireddu** [cdr/code-server#1797]
It looks like the extensions in the code-server marketplace are built using the latest master branch snapshot instead of the latest stable tag (for example the GitLab extension).

For this reason many extensions needs the proposed API support #1744 (that should not be needed for stable published version).

Please check if it is possible to improve the code-server marketplace to build the extensions using the latest stable version and not the master snapshot.

Thank you.

**Comment by cmoog** [comment]
Whenever possible, we try to build from the latest tagged version unless there is reason to believe that the latest version published in the VSCode marketplace differs from the repository's latest version. In the case of the GitLab extension, I've pushed a fix.

If there are specific extensions that you believe should be rebuilt from a different version, please dedicated issues and I'll do my best to resolve them.
