### ISSUE TITLE
Python extension installed successfully but cannot activate

### ISSUE THREAD

**Issue by kouzili77** [cdr/code-server#1798]
- Web Browser: Chrome
- Local OS: windows10
- Remote OS: 16.04.1-Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 3.4.1

Python extension is installed but when opening a .py file, the highlight is enabled but there is no python version selector and the run button.

code-server --install-extension makes no help, too

This project is extremely magic! Thx anyway!

**Comment by keiththomps** [comment]
Hi, if you have version `2020.5.2` then you'll have issues. Right-click the extension in the sidebar and select "Install Another Version" and select the next most recently released version (probably `2020.5.80290`.

**Comment by JacobTheEldest** [comment]
Duplicate of #1792

**Comment by kouzili77** [comment]
Nice response thx!
