### ISSUE TITLE
Source control push command error 404 page not found

### ISSUE THREAD

**Issue by ansarizafar** [cdr/code-server#1805]
When I use source control push command it stuck on singing in to github after asking permission to allow and showing 404 page for github callback.

**Comment by 3ehzad** [comment]
Hi, I have the same issue and I tried to generate token and OAuth application with callback URL with no luck!

**Comment by code-asher** [comment]
Yeah I haven't been able to get the oauth stuff working at all yet with code-server. :( 

For now I think the only workaround is to authenticate once with local VS Code and copy or use the configuration files.

**Comment by nhooyr** [comment]
Closing as a duplicate of #1883
