### ISSUE TITLE
Add config.yaml example. 

### ISSUE THREAD

**Issue by thewh1teagle** [cdr/code-server#1807]
when I use docker I need to create it manually 
and I don't know how, and didn't found any example.

**Comment by nhooyr** [comment]
It's auto created for you if it doesn't exist! Example is also here https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-does-the-config-file-work

**Comment by lcuwx2016** [comment]
file is 404

**Comment by code-asher** [comment]
Updated link: https://github.com/coder/code-server/blob/70aa1b77226ea40e5d661103de7b354f742a76df/docs/FAQ.md#how-does-the-config-file-work
