### ISSUE TITLE
Update prettier version

### ISSUE THREAD

**Issue by gyzerok** [cdr/code-server#1809]
- [x] Extension name: prettier-vscode
- [x] Extension GitHub or homepage: https://github.com/prettier/prettier-vscode

According to the [releases page](https://github.com/prettier/prettier-vscode/releases) the current version is 5.0.0, however the one I am getting installed from marketplace is 3.20.0.

Debugging what's wrong has cost me some time which led me wondering:
1. Are extensions updated automatically?
2. If not should there be a pointer somewhere that it might be an issue?

I am feeling like I have to validate all the extensions versions now. Ideally I'd prefer this not to happen :)

**Comment by cmoog** [comment]
Thank you for your request. Version 5.0.0 of `prettier-vscode` is now live in our marketplace.

The best way to ensure that an extension stays up-to-date is to request that the extension authors publish the `.vsix` package as part of the Github release. When an artifact is not provided, our scraper attempts to build the extension from the source which can be less reliable.

**Comment by gyzerok** [comment]
@cmoog https://github.com/prettier/prettier-vscode/issues/1432#issuecomment-645430078

**Comment by nhooyr** [comment]
Nice @gyzerok!
