### ISSUE TITLE
Cannot pull/push and any git operation.

### ISSUE THREAD

**Issue by sleiter88** [cdr/code-server#1812]
- Web Browser: Safary/Chrome
- Local OS: ipadOS
- Remote OS: ubuntu
- Remote Architecture: EC2 instance
- `code-server --version`:code-server2.1692-vsc1.39.2-linux-x86_64

I cloned a repository int o code-server with command line but when I want to make a pull of master branch it show me this error:
Git: fatal: cannot run /src/build/code-server2.1692-vsc1.39.2-linux-x86_64-built/extensions/git/dist/askpass.sh: No such file or directory

I don't know how to connect my git with code-server and I can't find any way to do that.

**Comment by nhooyr** [comment]
Update to the latest version please!
