### ISSUE TITLE
Keyboard shortcuts: One server, different clients with different platforms

### ISSUE THREAD

**Issue by ghost** [cdr/code-server#1813]
Hi, thanks for building such a great project!

I deployed this project on a server with a fixed domain and access it from serveral devices. However, the keyboard shortcuts seem to be configured for MacOS only so it doesn't work for Ubuntu.
Checking the `Keyboard Shortcuts` setting, most of the shortcuts are binded to `command + xxx`, making it unusable from Ubuntu.

I wonder if there is any solution to solve the problem? Thanks in advance.

**Comment by nhooyr** [comment]
Should just work if you use `super + xxx`.

Maybe we should update the UI to reflect the super key.
