### ISSUE TITLE
Feature request Upload l;ocal projects

### ISSUE THREAD

**Issue by sojab0on** [cdr/code-server#1814]
Hello, i am stummed by this webbased visual studio code.

It run fine, but i have multiple local projects on my personal development computer, but i cant get my local visual studio to upload the projects to the server.

Is that option not yet implemented or am i doing something wrong.

**Comment by nhooyr** [comment]
You can just drag and drop the folder into code-server or use something like `rsync` or `scp`.

**Comment by sojab0on** [comment]
i have tried to drag and drop a folder with a C# test project on the webinterface but it does not load it in.

SCP i can try 
Rsync dont know how that will work

**Comment by nhooyr** [comment]
> i have tried to drag and drop a folder with a C# test project on the webinterface but it does not load it in.

What happens?

**Comment by sojab0on** [comment]
nothing that is just it, it does not show its trying to place it anywhere or asks to give a location to put it.

SCP i have not tried yet need to change my NSG settings on Azure to accept SSH/Serial SCP traafic of FTP traffic

**Comment by nhooyr** [comment]
Are you dropping it into the file explorer?

**Comment by sojab0on** [comment]
I have tried uploading in zip or even to sln file from my Visual stduio local project to the web internface but it wont upload it

**Comment by code-asher** [comment]
I tried uploading zips but it seems to be working for me. Uploading directories currently doesn't work but it should work in the next release (it works on master).

**Comment by sojab0on** [comment]
I can try to reset the login password for you to and send it in DM so you can check maybe its somewhere missconfigured

**Comment by sojab0on** [comment]
I found it i think, the user/group premissions where not set on the mounted directory where the server is looking

Zip upload now works, maybe in a later version folder uploads can be implemented and a visual studio local connection option would be nice so real cross device coding is achievable
