### ISSUE TITLE
Code server without websockets?

### ISSUE THREAD

**Issue by Mistic92** [cdr/code-server#1817]
I wanted to run code server on GCP Cloud Run but websockets are not supported there so I'm getting error. Is it possible somehow to run code server without websockets with something different? 

```
errors.ts:26 Uncaught Error: Unable to read file 'vscode-userdata:/User/tasks.json' (Error: WebSocket close with status code 1006)

Error: Unable to read file 'vscode-userdata:/User/tasks.json' (Error: WebSocket close with status code 1006)
    at e.doReadAsFileStream (fileService.ts:457)
    at async e.readFile (fileService.ts:386)
    at /async https:/coder-xxxxxxxxxx-ew.a.run.app/static/69ad52907e8ea109345831d29da5425cb2a55047/lib/vscode/out/vs/workbench/workbench.web.api.js:3367
    at async Promise.all (/index 0)
    at async Promise.all (/index 1)
    at async f.loadConfiguration (configuration.ts:120)
    at async m.reload (configuration.ts:60)
    at errors.ts:26
```

**Comment by nhooyr** [comment]
Unfortunately at the moment there is no other way at the moment.

I suppose we could at some point add a pure HTTP protocol but WebSockets are much more natural abstraction for code-server's protocol and cloud run is likely to add WebSocket support eventually.

cc @code-asher

**Comment by Mistic92** [comment]
Hi, there is plan to support streaming gRPC on Cloud Run to this might be an option too. There is grpc-web but I don't know how stable it is https://github.com/grpc/grpc-web

**Comment by oldsj** [comment]
I was able to get code-server running on App Engine with the flex environment / custom runtime https://cloud.google.com/appengine/docs/flexible/custom-runtimes/quickstart

**Comment by nekename** [comment]
@nhooyr Could you give me some pointers to how I might implement this? The network that I use code-server on has this weird issue where WebSockets stop working every now and then for around half an hour or so, so I would like to be able to connect to my server using some alternative method. 

Maybe using [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events)?

**Comment by code-asher** [comment]
Server-sent events would not work for code-server since it needs two-way communication.

**Comment by nekename** [comment]
Yeah, using normal HTTP on the side for the other direction, of course.

**Comment by code-asher** [comment]
Ooh I see.  Maybe you could provide a custom web socket factory that uses server-sent events and http calls underneath.   https://github.com/microsoft/vscode/blob/ac4cbdf48759c7d8c3eb91ffe6bb04316e263c57/src/vs/platform/remote/browser/browserSocketFactory.ts#L275

Then handle the requests here: https://github.com/microsoft/vscode/blob/ac4cbdf48759c7d8c3eb91ffe6bb04316e263c57/src/vs/server/node/remoteExtensionHostAgentServer.ts#L106  

The codebase assumes a socket being passed around (normally this is the actual web socket), so might be easiest to create a socket you can pass through, and then wire that socket up to the http endpoints.  Not sure actually if you can just create a dummy socket or if it will have to be a real unix socket or something.

**Comment by nekename** [comment]
Interesting, thanks
