### ISSUE TITLE
command 'python.setInterpreter' not found

### ISSUE THREAD

**Issue by syci** [cdr/code-server#1818]
In a new environment, and with the ms-python.python-2020.6.88468 extension, when selecting the pyhton interpreter I get this error:

`Command 'Python: Select Interpreter' resulted in an error (command 'python.setInterpreter' not found)`

- Web Browser: Edge 84.0.522.20
- Local OS: Windows 10
- Remote OS: Ubuntu 18 LTS
- Remote Architecture: x64
- `code-server --version`: 3.4.1
- Python 2.7 & Python 3.6

Logs:

```
[2020-06-19 11:55:18.245] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python {"startup":false,"extensionId":{"value":"ms-python.python","_lower":"ms-python.python"},"activationEvent":"onCommand:python.setInterpreter"}
[2020-06-19 11:55:18.245] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/code/.local/share/code-server/extensions/ms-python.python-2020.6.88468/out/client/extension

```

**Comment by syci** [comment]
I've also tried creating a virutal environment and selecting it in the preferences and it seems that everything to do with python.XXXXX fails.

`'${config:python.interpreterPath}' can not be resolved because setting 'python.interpreterPath' not found.`

**Comment by raulhsant** [comment]
@syci I ran into the same problem.
Solved it by rolling the python extension back to 2020.5.86806

**Comment by gauravk88** [comment]
> @syci I was having the same problem.
> Solved it by rolling the python extension back to 2020.5.86806

Are you able to debug any pytests?

It started giving this error to me : Error: The number of constructor arguments in the derived class s must be >= than the number of constructor arguments of its base class.

Here is a jira for same : https://github.com/microsoft/vscode-python/issues/12465

**Comment by nhooyr** [comment]
cc @cmoog

**Comment by cmoog** [comment]
Closing as this is cannot be fixed within `code-server`. Please reference https://github.com/microsoft/vscode-python/issues/12465

**Comment by cchi-nuro** [comment]
Hi @raulhsant, could you provide some instruction on how to roll back the python extension?

**Comment by syci** [comment]
Hello, first you have to change the option to automatically update the extensions, otherwise it will go to the latest version again.

![pref](https://user-images.githubusercontent.com/7081394/85685700-36103380-b6c7-11ea-8c61-25bbd015f80d.jpg)

Then uninstall the extension and proceed to install it manually from the file.

```bash
code-server --install-extension /tmp/ms-python.python-2020.6.89148.vsix 
```

You can download the version from here https://github.com/microsoft/vscode-python/releases/tag/2020.5.86806

**Comment by rosarioema2020** [comment]
Hxhx Chi
