### ISSUE TITLE
Document file uploading in FAQ

### ISSUE THREAD

**Issue by sojab0on** [cdr/code-server#1819]
Hi,

I am using the code-server on my ububuntu azure host for some weeks now, but i have allot of local projects on my laptop in Visual studio i would like to have an feature or option to link up the deo code server and upload them so i can work on then on all my mashines and deploy it and debug them locally on one of the machines and update ode on the fly trough the web interface 

I dont know if this was requested before, and if this has been implemented already  but better ask 1 time to manny then not 

Regards
Michel

**Comment by nhooyr** [comment]
You can drag and drop any folder and it'll be copied!

We should add this to the FAQ.

**Comment by sojab0on** [comment]
as stated in my request feature

Drag and drop wont work 

Browsers used 
Chrome latest 
Microsoft Edge Chrome core latest update
Firefox 

Oses used 
Windows 10 pro version 1909 

Ubuntu desktop 20.04 

Rabian buster on rpi4 


Server is running on Azure with the ubuntu Server 18.04-LTS

Version of code-server 3.4.0 
VS Code: v1.45.1

**Comment by nhooyr** [comment]
See my response in https://github.com/cdr/code-server/issues/1814

**Comment by sojab0on** [comment]
have tried uploading in zip or even to sln file from my Visual stduio local project to the web internface but it wont upload it
And indeed in file explorer but i will not upload, i resorted to uploading the newest creadted zip file trough en xrdp session to the servers drive on same location as the code server file explorer looks and uzipping there to get the project uploaded to code server and work on its code base but that is hardly ideal

**Comment by nhooyr** [comment]
Sorry I'm not sure I fully understand. Are you dropping directly from visual studio to code-server? Try dragging and dropping from file explorer instead.

**Comment by nhooyr** [comment]
This is resolved, see @sojab0on's response in https://github.com/cdr/code-server/issues/1814#issuecomment-668404204
