### ISSUE TITLE
code-server, can not open terminal from Kubernetes

### ISSUE THREAD

**Issue by aleleba** [cdr/code-server#1820]
Can not open Terminal from Kubernetes pod

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version 3.4.1`:

**Comment by aleleba** [comment]
I solve the problem, the problem was .bashrc, i change the content, then restart the pod, and it works.

**Comment by nhooyr** [comment]
Glad it's working!

**Comment by aleleba** [comment]
I have the same problem, I dont Know why is happening, I change .bashrc and now have same issue.

**Comment by cmoog** [comment]
It's very unlikely that this a code-server issue. If you have additional information that suggests otherwise, please comment the details below and I'll reopen the issue.
