### ISSUE TITLE
Native code-server mobile app using Node.js for Mobile Apps

### ISSUE THREAD

**Issue by GalacticLion7** [cdr/code-server#1822]
Is there anything that’s stopping you from using https://github.com/JaneaSystems/nodejs-mobile to easily make a native code-server mobile app that will solve all the issues iPadOS and Android users are facing?

**Comment by nhooyr** [comment]
Not sure how that helps. `code-server` is still running remotely of course so we wouldn't benefit from nodejs on the mobile device.

**Comment by GalacticLion7** [comment]
@nhooyr I think you missed the point. It’s like Electron.js. Nothing would be running remotely.

**Comment by nhooyr** [comment]
That's not what it does. That's not allowed by the iOS App Store, you can only use webkit.


See https://code.janeasystems.com/nodejs-mobile

> Its core component is a library - available for Android and iOS - that lets you add a Node.js background worker to any mobile app

**Comment by nhooyr** [comment]
Ah sorry I think you want to literally run `code-server` locally on the iPad? We'd still have to access it via webkit and so thing's would still break.

**Comment by nhooyr** [comment]
And of course you wouldn't have remote support as is.
