### ISSUE TITLE
Persistent Terminals across reloads

### ISSUE THREAD

**Issue by stumitchell** [cdr/code-server#1832]
I am accessing a folder with the following url
http://127.0.0.1:8080/?folder=/home/stu/dev/maxim8

when I reload the page because of a dropped connection my terminals are restarted.

I would like them to be persistent like they are in cloud9

**Comment by diegosucaria** [comment]
You can use tmux to achieve that kind of behaviour...  similar to what google shell does...

I've done something like that in the shellArgs settings of vscode, but I could not make it work 100%.

`"terminal.integrated.shellArgs.linux": [ "-c", "tmux attach-session -d -t vscode`pwd | md5` || tmux new-session -s vscode`pwd | md5` " ]`

**Comment by code-asher** [comment]
We're on track to implementing this: tracking here: https://github.com/cdr/code-server/issues/2276

**Comment by leo848** [comment]
Is this implemented now?

**Comment by jsjoeio** [comment]
@leo848 should be I believe!
