### ISSUE TITLE
Limit directory navigation for UX

### ISSUE THREAD

**Issue by IsabellaRO** [cdr/code-server#1834]
Hello,

I would like to suggest a feature that would help me a lot in a project that I am developing with Code Server and I think it could help some other people too.

Basically, I am running Code Server in my laptop and accessing it through Chromium in some Raspberry Pi's.
I am already specifying a directory path when running the code server command, but in the Raspberry Pi's I can access some previous directories by clicking in "Open Folder" and typing ".." in the navigation bar of the VSCode, as you can see in the pictures below .

When I click in "Open Folder":
!["open folder"](https://i.ibb.co/0tPvpg3/code.png)

When I type ".." in the navigation bar:
!["navigating"](https://i.ibb.co/RPFnpbc/code2.png)

I would like to limit this navigation so the Raspberry Pi's can access only the specified directory or the posterior ones (the directories inside the specified directory). This specification could be through command line or the way you find it easier to implement.

Some infos that maybe will help:
I am running code server in Ubuntu 18.04 with this command:
`` console
code-server / home / teacher / SOMAS / --auth none
``

I am accessing code server via Chromium in a Raspbian OS, but the same happens if I access it through Google Chrome in another laptop with Ubuntu 18.04.

If you need any further information, please let me know.

Thank you!

**Comment by code-asher** [comment]
One way I think you could accomplish this is to use `chroot`.

Related: https://github.com/cdr/code-server/issues/1251. We opted not to do anything since from a security perspective it doesn't help since users still have access to the terminal, however maybe this make sense purely from a UX perspective.

Related: https://github.com/cdr/code-server/issues/1251
