### ISSUE TITLE
Puppet VScode Extension

### ISSUE THREAD

**Issue by n0lr4m** [cdr/code-server#1835]
- [ ] Extension name: Puppet VSCODE Extension
- [ ] Extension GitHub or homepage:  https://github.com/puppetlabs/puppet-vscode

**Comment by n0lr4m** [comment]
Pupept VSCODE Extension can be installed manually, but you will need to have the Puppet Agent or Puppet Development Kit (PDK) installed in order to fully use this extension.

PDK version 1.5.0 or higher is required.
 Puppet Agent 5.5 and above is preferred.

**Comment by cmoog** [comment]
The prebuilt `vsix` published in the repository you've shared is already live in the `code-server` marketplace under the id `puppet.puppet-vscode`. Is there something I'm missing here? 

If so, please comment here and I'll reopen.

**Comment by n0lr4m** [comment]
Hello,

Yes, in order to fully use the puppet.puppet-cscode extension the container need the follwing packages installed:

PDK version 1.5.0 or higher is required.
Puppet Agent 5.5 and above is preferred.

Reference: https://github.com/puppetlabs/puppet-vscode#requirements
