### ISSUE TITLE
Python extension fails to activate

### ISSUE THREAD

**Issue by davegaulke** [cdr/code-server#1837]
Edit: the error is

```
The number of constructor arguments in the derived class s must be >= than the number of constructor arguments of its base class
```

------

- Web Browser: Chrome 83.0.4103.116 (Official Build) (64-bit)
- Local OS: macOS 10.13.6
- Remote OS: Clear Linux version 33420
- Remote Architecture: x86_64
- `code-server --version: 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259`

I've loaded the Microsoft python extension. Syntax coloring works, but code completion does not. I also get the error "command 'python.setInterpreter' not found" when clicking on the python interpreter at the bottom of the window.  Remote server python is 3.8.3.

**Comment by Anjum48** [comment]
I'm having the same issue. I've tried reinstalling the extension and rolling back to an older version. No luck :cry:

**Comment by EzzPrograms** [comment]
This is actually an extension problem and this version works https://github.com/microsoft/vscode-python/releases/tag/2020.5.86806

Mine works after installing this one.

Source: Issue #1818

**Comment by szho42** [comment]
@EzzPrograms that works for me. Reverting to an old version enables the intellisense. thanks

**Comment by code-asher** [comment]
Upstream issue: https://github.com/microsoft/vscode-python/issues/12465

**Comment by vumaasha** [comment]
@EzzPrograms can you post the version of the code server and python version you are using. I have downgraded still pylint shows import error

**Comment by EzzPrograms** [comment]
> @EzzPrograms can you post the version of the code server and python version you are using. I have downgraded still pylint shows import error

This is the python extension version I’m using: https://github.com/microsoft/vscode-python/releases/tag/2020.5.86806

For code-server, it should be the latest one.

**Comment by vumaasha** [comment]
> > @EzzPrograms can you post the version of the code server and python version you are using. I have downgraded still pylint shows import error
> 
> This is the python extension version I’m using: https://github.com/microsoft/vscode-python/releases/tag/2020.5.86806
> 
> For code-server, it should be the latest one.

finally I got the python extension to work by disabling Jedi (jediEnabled:false) and by setting PYTHONPATH env var . The PYTHONPATH was not getting picked up from the .env file

**Comment by nhooyr** [comment]
@cmoog Lets revert this extension on the marketplace to the working version.

**Comment by ducalpha** [comment]
On code-server 3.8.0 I have to downgrade Python extension to version 2020.10 (the latest version is 2020.12) to make it work.

**Comment by blaylockbk** [comment]
Same on code-server 3.8.1, have to downgrade to 2020.10. (Also the now latest 2021.1 still doesn't work).

**Comment by MaxG-Git** [comment]
> On code-server 3.8.0 I have to downgrade Python extension to version 2020.10 (the latest version is 2020.12) to make it work.

I have the same issue, Have been looking everywhere for a solution, This finally fixed it for me ~ Thank You!

**Comment by hacke2** [comment]
It seems that this bug will only appear in node 12，Node 10 is

**Comment by oxy** [comment]
Hey there - this issue is stale and the latest versions of Python/Jupyter work as of v3.10.2; closing.

**Comment by jingw222** [comment]
Still an issue here. Activating the extension via the command `Python: Select Interpreter` does not show the window wherein I can select different Python executables. The status bar shows "Activating Extensions.." for a few seconds and disappears, but nothing happens after that. 

```
code-server: v3.10.2
VS Code: v1.56.1
Commit: 387b12ef4ca404ffd39d84834e1f0776e9e3c005
Date: 2021-05-21T23:13:00Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
```

**Comment by jsjoeio** [comment]
@jingw222 please open a new bug report issue with repro steps. Thanks!
