### ISSUE TITLE
Keep vscode running in backend

### ISSUE THREAD

**Issue by hannamtt** [cdr/code-server#1841]
It would be nice if when I closer a code-server browser workspace in a tab and go to that same workspace with its url in another tab or even another browser on another device and see activities continue like compiling even when the browser is closed and reopened again. Cloud9 does this and I liked that a lot

**Comment by code-asher** [comment]
This would be nice. I think this may have to be done upstream though.

**Comment by pblaton** [comment]
You can use screen or byobu, install it on the hos you run vscode server. When switching devices open your code server on the new device and type byobu you will see your current sessions and they do not close when you close the browser either. Ideal for long running terraform/ansible scripts, I keep an eye on them on ipad/iphone while doing other stuff.

**Comment by hannamtt** [comment]
thats great but gui initiated operations will still close on a browser close

**Comment by hannamtt** [comment]
I have an alternate idea that I would like to throughout there, a local electron instance of vscode could be running on my remote machine that sinks and utilizes resources from the host when there is a connection and uses local resources when no connection to the server is available? that would be cool.

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/2276
