### ISSUE TITLE
Installing on RPi4 does not create systemctl service

### ISSUE THREAD

**Issue by ELChris414** [cdr/code-server#1845]
- Web Browser: Chrome 83.0.4103.116
- Local OS: Windows 10
- Remote OS: Raspbian GNU/Linux 10 (buster)
- Remote Architecture: 75-v7l+ is BCM2711 32-bit
- `code-server --version`: 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259

Title says it, trying to run any command with systemctl and code-server gives this:
`Failed to enable unit: Unit file code-server.service does not exist.`

**Comment by jolestar** [comment]
Ubuntu 18.04.4 also have this problem.

**Comment by jolestar** [comment]
download https://github.com/cdr/code-server/blob/master/ci/build/code-server.service  to  /lib/systemd/system/code-server.service fix this.

**Comment by nhooyr** [comment]
The current release only contains a systemd user unit. See the docs on how to use it.

The next release today will include a system unit.

**Comment by nhooyr** [comment]
[v3.5.0 with VS Code v1.48.2 has been released, fixing this issue!](https://github.com/cdr/code-server/releases/tag/v3.5.0) 🍻

**Comment by olegKusov** [comment]
Ubuntu 20.04 LTS. Code server v3.9.1
Trying sudo systemctl enable --now code-server@root and sudo systemctl enable --now code-server@USER
Having error
Failed to enable unit: Unit file code-server@root.service does not exist.

**Comment by Sisyphusean** [comment]
This issue still persists. running sudo systemctl restart code-server returns a service does not exist message

**Comment by code-asher** [comment]
@Sisyphusean how did you install code-server?  Are their any logs from the install?  Are you able to run `code-server` directly without systemd?

**Comment by dingdangdog** [comment]
This issue still persists. when i run `curl -fsSL https://code-server.dev/install.sh | sh -s -- --dry-run` and show:

```
Ubuntu 24.04 LTS
Installing v4.89.1 of the amd64 deb package from GitHub.

+ mkdir -p ~/.cache/code-server
+ curl -#fL -o ~/.cache/code-server/code-server_4.89.1_amd64.deb.incomplete -C - https://github.com/coder/code-server/releases/download/v4.89.1/code-server_4.89.1_amd64.deb
+ mv ~/.cache/code-server/code-server_4.89.1_amd64.deb.incomplete ~/.cache/code-server/code-server_4.89.1_amd64.deb
+ sudo dpkg -i ~/.cache/code-server/code-server_4.89.1_amd64.deb

deb package has been installed.

To have systemd start code-server now and restart on boot:
  sudo systemctl enable --now code-server@$USER
Or, if you don't want/need a background service you can run:
  code-server

Deploy code-server for your team with Coder: https://github.com/coder/coder
```

But have error：

```sh
# run
sudo systemctl enable --now code-server@$USER
# show
Failed to enable unit: Unit file code-server@dddx.service does not exist.

# run
sudo systemctl enable --now code-server
# show
Failed to enable unit: Unit file code-server.service does not exist.
```

Then I Manually [installing](https://coder.com/docs/code-server/latest/install) code-server can Fixed it.

```sh
# export VERSION=4.89.1
curl -fOL https://github.com/coder/code-server/releases/download/v$VERSION/code-server_${VERSION}_amd64.deb
sudo dpkg -i code-server_${VERSION}_amd64.deb
sudo systemctl enable --now code-server@$USER
```

**Comment by code-asher** [comment]
Just to check, did you run without `--dry-run`?  `--dry-run` will not actually do anything, just shows the commands it would run.
