### ISSUE TITLE
Missing extensions for Foam

### ISSUE THREAD

**Issue by AriezLabs** [cdr/code-server#1846]
These extensions are required for [Foam](https://github.com/foambubble/foam) and currently missing in code-server's marketplace:

### Foam

- [ ] Extension name: foam.foam-vscode
- [ ] Extension GitHub or homepage: https://github.com/foambubble/foam-vscode

### VS Code Markdown Notes

- [ ] Extension name: kortina.vscode-markdown-notes
- [ ] Extension GitHub or homepage: https://github.com/kortina/vscode-markdown-notes

### Markdown Links

- [ ] Extension name: tchayen.markdown-links
- [ ] Extension GitHub or homepage: https://github.com/tchayen/markdown-links

**Comment by cmoog** [comment]
Thank you for your requests! The extensions are now live in the code-server extension marketplace.

**Comment by AriezLabs** [comment]
First off, sorry for my ignorance regarding the way you handle extensions. 

Foam previously required VS Code 1.46, this has now [been changed](https://github.com/foambubble/foam-vscode/commit/5adaaaeb50391c1829ad6f06ee4a2a586149d012) to 1.45.1 to support code-server. However, attempting to install Foam results in the same "incompatible with the current version of VS Code" error message. It seems the update hasn't arrived in code-server's marketplace yet.

Do you require any action to pull updates from extensions? Or is it just a matter of waiting a bit longer?

**Comment by code-asher** [comment]
@AriezLabs I'm sorry we missed this; it should automatically grab the vsix from the releases. If the extension doesn't have a vsix then I think it builds off the latest tag. That said, it looks like ours is out of date so it's possible something isn't working there.

**Comment by code-asher** [comment]
Opened https://github.com/cdr/code-server/issues/2015.
