### ISSUE TITLE
new install 500 error

### ISSUE THREAD

**Issue by soitun** [cdr/code-server#1851]
500
VS Code failed to load. 
Above error is shown on fresh install on　ubuntu18.04 .

warn discarding socket connection: vscode is not running

warn discarding socket connection: vscode is not running

(node:24) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit

(Use `node --trace-warnings ...` to show where the warning was created)

(node:24) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit

events.js:292

throw er; // Unhandled 'error' event

^

Error: This socket has been ended by the other party

at Socket.writeAfterFIN [as write] (net.js:453:14)

at h.write (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:169:115)

at g.write (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:170:363)

at g._writeNow (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:160:350)

at Immediate.<anonymous> (/usr/lib/code-server/lib/vscode/out/vs/server/entry.js:160:288)

at processImmediate (internal/timers.js:456:21)

Emitted 'error' event on Socket instance at:

at emitErrorNT (net.js:1340:8)

at processTicksAndRejections (internal/process/task_queues.js:84:21) {

code: 'EPIPE'

}

error VS Code exited unexpectedly with code 1

warn discarding socket connection: vscode is not running

warn discarding socket connection: vscode is not running

warn discarding socket connection: vscode is not running

warn discarding socket connection: vscode is not running

warn discarding socket connection: vscode is not running

warn discarding socket connection: vscode is not running

- Web Browser:  chrome
- Local OS: ubuntu18.04
- Remote OS:  macos 

- `code-server --version`: 3.4.1

**Comment by code-asher** [comment]
Does the error persist if you refresh the page? Looks like we're trying to write to a closed socket so we might want to catch that and provide a better error message.

**Comment by jameszcm007** [comment]
I have the same question, how to fix it?

**Comment by phgogo** [comment]
Got the same problem running on a fresh AWS-Instance.

Strange thing is, the same setup works on an t2.mirco instance but fails on an t3a.micro
Should be easy to reproduce

**Comment by bensonkb** [comment]
Have the same issue. How to fix it

**Comment by code-asher** [comment]
For anyone with this issue, please gather and post debug information according to https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-debug-issues-with-code-server. Thanks!

**Comment by soorena776** [comment]
After installing 3.1.4 version, I've also started seeing intermittent (but frequent) 500 error "VS Code failed to load. timed out". Given the age of this ticket, I'm wondering if there are any workarounds?

**Comment by code-asher** [comment]
@soorena776 Logs might help us pinpoint the issue!

**Comment by nhooyr** [comment]
There's been quite a few fixes on related code so hopefully latest versions don't reproduce!

**Comment by Antrikshy** [comment]
I just installed it on my Raspberry Pi 3 running Raspbian and it's the only page I've seen so far. It appears after I enter my password.

**Comment by urwrstkn8mare** [comment]
@Antrikshy same

**Comment by EdgarAlonsoPerez** [comment]
Same problem in raspberry Pi 3

**Comment by davisnando** [comment]
Getting same error on raspberry pi 2 too

**Comment by code-asher** [comment]
@davisnando Please feel free to open a new issue with debugging info. Thanks!

**Comment by stones-he** [comment]
Getting same error on win10  too

**Comment by jsjoeio** [comment]
@stones-he feel free to open a new bug report!

**Comment by cheungxi** [comment]
> @stones-he feel free to open a new bug report!

how to check bug report, by ` ~/.local/share/code-server/coder-logs` ?
but **code-server-stdout.log** and **code-server-stderr.log**  is null

**Comment by code-asher** [comment]
We have a bug where the stdout is not being logged so I think gathering
the install logs and stdout separately will be helpful.  For example:

```
yarn global add code-server --verbose > install.log 2>&1
code-server > run.log 2>&1
```

Then browse to the code-server page to trigger the 500 and submit the
install.log and run.log files.
