### ISSUE TITLE
UTF-8 text garbling on opening file 

### ISSUE THREAD

**Issue by h-shiina-regolith** [cdr/code-server#1854]
When I open the file ([bake.txt](https://github.com/cdr/code-server/files/4854994/bake.txt)), the editor of vscode tab has a text garbling.

Attached file ([bake.txt](https://github.com/cdr/code-server/files/4854994/bake.txt)) has 1000 repeated same lines and no text garbling.
But, opened file in editor has garbled line, it's line number is always 586.

It is reproduced on chrome and safari.

Log file is here. [ClientLogPane Log(Remote Server).txt](https://github.com/cdr/code-server/files/4855228/ClientLogPane.Log.Remote.Server.txt)

- Web Browser: chrome & safari
- Local OS: MacOS Catalina
- Remote OS: Debian10
- Remote Architecture: x64
- `code-server --version`: code-server 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259

thanks.

**Comment by h-shiina-regolith** [comment]
The picture shows around line 586.
<img width="657" alt="screenshot" src="https://user-images.githubusercontent.com/62930327/86196402-25136680-bb8e-11ea-8c3f-9b5154d5a5b4.png">

**Comment by h-shiina-regolith** [comment]
I edited `bufferSize:65536` to `bufferSize:6553600` of /usr/lib/code-server/lib/vscode/out/vs/server/entry.js.

Text garblings is disappeared.

So, This bug may be related with buffer or data recombination between buffers.

**Comment by code-asher** [comment]
Nice find!! I tried [modifying the code](https://github.com/cdr/code-server/commit/3986c547a2cfaaf849659d9d6e735cad427e6081#diff-8bff7bd674331bf3969196ae526c5504R1539) to call VS Code's own `readFileStream` instead of handling it ourselves but the problem persists. Tomorrow I'm going to try out VS Code's remote SSH extension and see if it has the same problem to see if it's a bug in our implementation.

**Comment by code-asher** [comment]
It works fine with the extension so it could be our implementation or it could be something in the web portion of VS Code, maybe with where it reads the stream returned by the server. :thinking:

**Comment by h-shiina-regolith** [comment]
@code-asher 
Wow, This bug disappeared on ver.3.5.0.!
Do you know something about this.

**Comment by code-asher** [comment]
I wasn't aware but that's great news! I'll go ahead and close the issue.

I wonder if it was accidentally fixed when the streams were modified to support multiple encodings.
