### ISSUE TITLE
code-server to 3.4.1 + python to 2020.5.x still get Debugger Error:The number of constructor arguments in the derived class s must be >= than the number of constructor arguments of its base class.

### ISSUE THREAD

**Issue by alan-he** [cdr/code-server#1855]
The solution is to not only downgrade ms-python to 2020.5.x but also upgrade code-server to 3.4.1

_Originally posted by @gauravk88 in https://github.com/cdr/code-server/issues/1821#issuecomment-647649607_

**Comment by code-asher** [comment]
It looks like this is the same issue as #1837 although it doesn't list the actual problem like this issue does. I'll close this one and add the details to #1837.
