### ISSUE TITLE
Document all environment variables

### ISSUE THREAD

**Issue by nickjanssen** [cdr/code-server#1857]
There is no such documentation currently. It's extremely painful having to search in code just to do something as trivial as setting the directory to be opened.

**Comment by code-asher** [comment]
I think most of our environment variables are either in the FAQ or in the `--help` output. Perhaps it would make sense to have a single consolidated section for them.

I think these are all the environment variables that aren't documented anywhere:
- `LOG_LEVEL`
- `TELEMETRY_URL`

I didn't think we had an environment variable for setting the current directory though?

**Comment by kylecarbs** [comment]
@nickjanssen does `--help` do it for ya?
