### ISSUE TITLE
Add command "loginctl enable-linger $USER" in install.sh

### ISSUE THREAD

**Issue by yu-chenxi** [cdr/code-server#1861]
I install code-server on my ECS by executing `install.sh`.
Then execute following:
```bash
systemctl --user enable --now code-server
systemctl --user start code-server
``` 
But when I disconnect the ssh connection from my ECS, the code-server process will be killed immediately and the connection
between ECS and browser will break. Finally, I find this article [systemd user instance](https://wiki.archlinux.org/index.php/Systemd/User#How_it_works) to solve the problem.

This is  [solution](https://wiki.archlinux.org/index.php/Systemd/User#Automatic_start-up_of_systemd_user_instances).
```bash
loginctl enable-linger $USER
```
The issue is only happends when I run code-server as non-root user.
I think you shound add it.

**Comment by tidux** [comment]
It might be better to leave this as an option behind a y/n prompt than just do it by default.  The enable-linger option has security implications if you're using ssh-agent+keychain or similar tools, and I don't think it should be interfered with silently.

**Comment by nhooyr** [comment]
Let's leave this open until a new release is cut.

**Comment by tidux** [comment]
I would recommend systemd stuff not be in the install script at all, since Amazon Linux 2 very deliberately does not include systemd user session support.

**Comment by nhooyr** [comment]
> I would recommend systemd stuff not be in the install script at all, since Amazon Linux 2 very deliberately does not include systemd user session support.

Yes, we're switching to to a system unit so we're fine.

**Comment by finzzz** [comment]
At least, write it in the documentation

**Comment by nhooyr** [comment]
[v3.5.0 with VS Code v1.48.2 has been released, fixing this issue!](https://github.com/cdr/code-server/releases/tag/v3.5.0) 🍻
