### ISSUE TITLE
Unable to download install.sh

### ISSUE THREAD

**Issue by akirarika** [cdr/code-server#1863]
In China, because of [GFW](https://en.wikipedia.org/wiki/Great_Firewall) `https://raw.githubusercontent.com/` is not accessible

So if `https://code-server.dev/install.sh` can redirect to `https://cdn.jsdelivr.net/gh/cdr/code-server/install.sh`

maybe it's a good idea🙂?

**Comment by nhooyr** [comment]
Can't `cdn.jsdelivr.net` be blocked as well?

We don't want to play a cat and mouse with the GFW. Since you need to use GitHub to get the changelog/releases anyway, using the install script without access to GitHub wouldn't work.
