### ISSUE TITLE
Support HTTPS client certificate for better security 

### ISSUE THREAD

**Issue by aeltawela** [cdr/code-server#1864]
For better security and to avoid any brute force attempt for the login password, we can support https client certificate in code-sever.

That is an example of how easily it [can be supported using node.js](https://github.com/julie-ng/nodejs-certificate-auth).

**Comment by nhooyr** [comment]
Instead of supporting many auth methods within code-server itself, we think it's better to make use of the large ecosystem of reverse proxies.

See https://github.com/cdr/code-server/blob/v3.4.1/doc/FAQ.md#how-should-i-expose-code-server-to-the-internet

> If you want to use external authentication (i.e sign in with Google) you should handle this with a reverse proxy using something like oauth2_proxy or Cloudflare Access.

**Comment by nhooyr** [comment]
To be clear, I fully agree a http client certificate is more secure! We're just trying to avoid configuration complexity within code-server.

**Comment by aeltawela** [comment]
I understand. I just see it is very easy to add because it is natively supported in node.js, in fact it is just 1 parameter in server options (i.e. rejectUnauthorized: true). Any second thoughts?
```
var options = { 
    key: fs.readFileSync('server-key.pem'), 
    cert: fs.readFileSync('server-crt.pem'), 
    ca: fs.readFileSync('ca-crt.pem'), 
    crl: fs.readFileSync('ca-crl.pem'), 
    requestCert: true, 
    rejectUnauthorized: true 
}; 
https.createServer(options, function (req, res) { 
    console.log(new Date()+' '+ 
        req.connection.remoteAddress+' '+ 
        req.socket.getPeerCertificate().subject.CN+' '+ 
        req.method+' '+req.url); 
    res.writeHead(200); 
    res.end("hello world\n"); 
}).listen(4433);
```

**Comment by nhooyr** [comment]
Well, you'd still have to pass in the ca and crl as well right?

cc @code-asher for thoughts.

**Comment by code-asher** [comment]
It seems simple enough that I'm not opposed to it although admittedly I would rather see authentication happen externally via a reverse proxy.

**Comment by nhooyr** [comment]
I think there would also be very few users who would use this as a direct feature in code-server as well so I'm going to close.
