### ISSUE TITLE
How to install an extension of a specific version from the market place using command-line?

### ISSUE THREAD

**Issue by dclong** [cdr/code-server#1865]
We can use the following command to install an extension. 
```
code-server --install-extension extension_name
```
I wonder whether there is any way to install an extension of a specific version from the market place? The command `code-server` does not provide any help doc on this part.

**Comment by code-asher** [comment]
You can specify a version by adding `@version`, for example:

```
code-server --install-extension vscodevim.vim@1.13.1
```

I'm not sure why it's not documented though. I don't see anything about it in the VS Code docs: https://code.visualstudio.com/docs/editor/command-line#_working-with-extensions

**Comment by dclong** [comment]
@code-asher, 

Thank you very much!
