### ISSUE TITLE
the installed extensions seems not work, i build code-server project by myself

### ISSUE THREAD

**Issue by mfkwgizhoujian** [cdr/code-server#1866]
- Web Browser:Chrome 83.0.4103.116 x64
- Local OS:macOS Catalina 10.15.5
- Remote OS:macOS Catalina 10.15.5
- Remote Architecture:
- `code-server --version`:3.4.1

i contribute the code-server project use these steps:
1.yarn
2.yarn vscoe
3.yarn watch
i visit http://localhost:8080, it works normally. then i installed extensions: cpptools and Chinese Language Pack, but the extensions seems not work. it still use English Language, and the vscode-web will pop a warning dialog at bottom-right corner when i first visit. When running the debugger for an active C++ file, the debugger throws an error saying that it cannot find the build task associated with the debug configuration.

but when i develop the code-server use the Standalone Releases 3.4.1, all of these problems disappeared, the extensions work normally.
<img width="490" alt="WeChat2a5ee4d42d1030fe443023ec4c9f0e71" src="https://user-images.githubusercontent.com/33543763/86550058-f1f91a80-bf73-11ea-8085-b22696d96cf6.png">
<img width="383" alt="WeChat1a6db6f687e168f665ac4ad5196cf8a2" src="https://user-images.githubusercontent.com/33543763/86550073-fde4dc80-bf73-11ea-883b-07c5f38eab5a.png">
<img width="927" alt="WeChat1f569098fb08fbe3ab6772e49208f707" src="https://user-images.githubusercontent.com/33543763/86550154-3ab0d380-bf74-11ea-9742-2805335b97ec.png">

**Comment by code-asher** [comment]
The language packs don't work in development mode; you have to do a [full build](https://github.com/cdr/code-server/blob/master/doc/CONTRIBUTING.md#build). It's because the necessary language data is only generated during the full build process (I'm not sure why it's orchestrated it this way though).

I actually can't get tasks to run at all even in 1.4.1 so this might be a bug.

**Comment by code-asher** [comment]
The tasks seem to be working again after I updated the version of VS Code that ships with code-server. Let me know if it still doesn't work for you and we can re-open the issue!

**Comment by mfkwgizhoujian** [comment]
> The tasks seem to be working again after I updated the version of VS Code that ships with code-server. Let me know if it still doesn't work for you and we can re-open the issue!

I updated the latest code. It works correctly. Thanks a lot.
But the pop-up in my first picture still exists, unless I copy the extracted plugin "references-view" to the "lib/vscode/extensions" folder.

If I change "bind-addr" to a special ip in config.yaml, it will pop a message 'code-server is being accessed over an insecure domain. Web views, the clipboard, and other functionality will not work as expected.' and can't find the task again.

So do I have to publish using domain and https for other developers to use? Is there a way for others to use it in a development environment?

**Comment by code-asher** [comment]
Yeah, unfortunately a bunch of functionality depends on service workers and other features (like the clipboard API) which browsers simply won't enable over insecure domains, so https is a requirement for everything to work properly.

About the popup, some plugins aren't generated until the full build process. The references plugin seems to be one, the Node debug plugins are another (so Node debugging won't work in development mode) and there might be others I'm not aware of as well.

**Comment by mfkwgizhoujian** [comment]
> Yeah, unfortunately a bunch of functionality depends on service workers and other features (like the clipboard API) which browsers simply won't enable over insecure domains, so https is a requirement for everything to work properly.
> 
> About the popup, some plugins aren't generated until the full build process. The references plugin seems to be one, the Node debug plugins are another (so Node debugging won't work in development mode) and there might be others I'm not aware of as well.


I use nginx and mkcert to solve this problem. 
I want to modify some logics of login, but I run it by using yarn watch. How can I debug the ".ts" files under the "src" folder?
These files are not available in chrome.

**Comment by code-asher** [comment]
Oh, it looks like our source maps for VS Code are broken. If we fix those the `.ts` files will show up in Chrome.

**Comment by code-asher** [comment]
Oh but the login source files should show up fine. But there isn't any JavaScript logic on the login page. It's only on the Node end. The Node files won't show up in Chrome unfortunately, but it should be possible to connect a debugger to the Node process.

**Comment by code-asher** [comment]
You can connect the Chrome debugger to the Node process by starting code-server like this:

```
NODE_OPTIONS=--inspect yarn watch
```

Then in Chrome go to chrome://inspect.

But, there don't seem to be any files in the developer console so I'm not sure how to use it.

**Comment by code-asher** [comment]
Oh you can just use `ctrl+p` to search files. It works! But we spawn a child process and that's the process that actually needs to be debugged and using `NODE_OPTIONS` doesn't seem to work because the parent process has already taken the port.

I think we'll need to add a command-line flag for passing Node options to the child process.

One manual workaround is to edit this line: https://github.com/cdr/code-server/blob/e858a4f4c7f30898d0a884015f34353b354a04ad/src/node/wrapper.ts#L229

And add the inspect option:

```
const wrapper = new WrapperProcess(require("../../package.json").version, { nodeOptions: "--inspect=9999" })
```

**Comment by mfkwgizhoujian** [comment]
> Oh you can just use `ctrl+p` to search files. It works! But we spawn a child process and that's the process that actually needs to be debugged and using `NODE_OPTIONS` doesn't seem to work ~because the parent process has already taken the port~ nope it's because we override `NODE_OPTIONS` in the `yarn watch` invocation.
> 
> I think we'll need to add a command-line flag for passing Node options to the child process.
> 
> One manual workaround is to edit this line:
> 
> https://github.com/cdr/code-server/blob/e858a4f4c7f30898d0a884015f34353b354a04ad/src/node/wrapper.ts#L229
> 
> And add the inspect option:
> 
> ```
> const wrapper = new WrapperProcess(require("../../package.json").version, { nodeOptions: "--inspect" })
> ```
> 
> Then run code-server normally (without `NODE_OPTIONS`).

It works good. Thanks.

I know that there isn't any logic code on the login page. I debug it to know the process before entering vscode, because I want to change it to different users who login with their own username and password, and can only view their own workspace. ^^

**Comment by code-asher** [comment]
Makes sense!
