### ISSUE TITLE
instead of cloud provider docs, write scripts for each public cloud to startup an instance

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#187]
Would make our docs less bloated, and easier to test/maintain.

Or just make the docs use the docker image instead to simplify deployment.

**Comment by NGTmeaty** [comment]
I kind of disagree here, I think the specific creation guides are useful, but I think we should redirect to using the Docker. I was thinking about putting a PR in last night.

**Comment by nhooyr** [comment]
I don't think the guides are any more useful than scripts that are easier to maintain.

**Comment by nhooyr** [comment]
And more automated.

**Comment by NGTmeaty** [comment]
While I agree they are much easier to maintain, guides are easier to follow for less advanced users. I'm honestly ok with either.

**Comment by nhooyr** [comment]
How are they easier to follow? Scripts are literally, make an account, run this script and enter your creds when prompted.

**Comment by NGTmeaty** [comment]
Scripts would still require cloning and running. Guides are in my opinion, much easier.

**Comment by sherwino** [comment]
The one line script was incredibly easy to use, was able to have it running locally in a minute.

...but when you start getting into deployment, the guides are really helpful.
The scripts might not be able to work for everybody when you consider all of the variables of deployment. I'm still trying to figure out https [on EC2](http://ec2-34-238-162-153.compute-1.amazonaws.com)

If you make a guide with a provider in mind, with a one line script that would be amazing.

i.e. Start server in Digital Ocean guide, ssh, and run this script

**Comment by kylecarbs** [comment]
@NGTmeaty we mean something like the command @bketelsen made:
```
az container create --resource-group yourRG --name bkcoder --image bketelsen/code-server-ubuntu:2 --cpu 4 --memory 8 --dns-name-label bkcoder --ports 9000
```
But for every cloud.

**Comment by NGTmeaty** [comment]
Ah. I guess. That works.

**Comment by nhooyr** [comment]
We can keep the guides but we should move them to the Wiki to make it easier for the community to maintain.

**Comment by sr229** [comment]
I did make a Ansible script to reduce the amount of docs needed per provider. It's currently rejected but I moved it on my own repo.

**Comment by kylecarbs** [comment]
I’m good w/ the ansible guide being on the wiki

**Comment by nhooyr** [comment]
Yup, ansible is linked to from the wiki.

https://github.com/codercom/code-server/wiki/Deployment

**Comment by BinaryBen** [comment]
Guides please. Allows users to understand what is going on and make changes if needed.

**Comment by nhooyr** [comment]
Going to close as it has been a while and I'm not sure if this is relevant anymore.
