### ISSUE TITLE
Support Kubernetes

### ISSUE THREAD

**Issue by AssafKatz3** [cdr/code-server#1870]
Hi,
I understood that this repository contained previously Kubernetes manifests (per #1011) and there were problems with user. I got into this repository from [wrapper](https://github.com/gashirar/code-server-on-kubernetes) of this project so it is feasible. Is there plan to handle this part as part of this repository?
@gashirar - thanks on your wrapper :-)
Thanks,
Assaf

**Comment by nhooyr** [comment]
We would consider it out of scope. It's super easy to get going on k8s as is. Just use the docker image.
