### ISSUE TITLE
python interactive fails with version 2020.06

### ISSUE THREAD

**Issue by rholland** [cdr/code-server#1871]
The most recent version of python extension 2020.6 fails to work (no code lens at cells, does not find Python interpreter) with this version of Code:

```
code-server: v3.4.1
 VS Code: v1.45.1
Commit: 48f7c2724827e526eeaa6c2c151c520f48a61259
Date: 2020-06-04T10:39:14Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
```
However 2020.5 extension works.

I am running on DigitalOcean

**Comment by franz101** [comment]
Same here

**Comment by code-asher** [comment]
Thanks for the report! I think this is likely the same problem reported in #1837 so I'll go ahead and close this issue in favor of that one.
