### ISSUE TITLE
Missing workbench action

### ISSUE THREAD

**Issue by DAddYE** [cdr/code-server#1873]
- Web Browser: Safari
- Local OS: ipadOs 13
- Remote OS: Safari
- Remote Architecture: macOs Catalina
- `code-server --version`: 3.4.1 e858a4f4c7f30898d0a884015f34353b354a04ad

Hi!

The `workbench.action.switchWindow` isn't available in code-server, but is in vscode. 

Do we have an alternate command or would be possible to add it?

Thank you!

**Comment by kylecarbs** [comment]
Each window is a separate tab at the moment, so AFAIK we cannot do this. :(
