### ISSUE TITLE
terminal tmux htop

### ISSUE THREAD

**Issue by roccqqck** [cdr/code-server#1876]
when I use ```htop```,
I cant use mouse and any hotkey like F5 F6

when I use ```tmux```, 
page down page up are not worked

[terminal bug]
- Remote OS:ubuntu18.04
- Remote Architecture:x64
- `code-server --version`: 3.4.1

**Comment by geiseri** [comment]
The VS Code terminal in general is funky even on a desktop.  I actually use `mutantdino.resourcemonitor` on my docker instance to keep track of things.  I have tried to muck around with the profile on the Linux desktop, but it is still not perfect.

**Comment by wbobeirne** [comment]
I can confirm that these commands have the same issues in the local vscode terminal, so this would have to be fixed there first.
