### ISSUE TITLE
npm install fails on FreeBSD 12.1

### ISSUE THREAD

**Issue by mike-pt** [cdr/code-server#1880]
- Local OS: FreeBSD
- Remote OS: FreeBSD
- Remote Architecture: amd64
- `code-server --version`: n/a

I can't seem to install due to missing deps its seems but I also found no clue how to install those:
```
npm WARN @coder/logger@1.1.11 requires a peer of @google-cloud/logging@^4.5.2 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! code-server@3.4.1 postinstall: `./postinstall.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the code-server@3.4.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-14T12_30_33_064Z-debug.log
``

**Comment by code-asher** [comment]
Is there more to the output? I think the cause of the error might be further up. I don't think the peer dependency warnings would cause the script to fail.

**Comment by mike-pt** [comment]
Not that I could see but it was over tmux it's possible it's cutoff indeed, I was wondering if it was indeed related to dependencies missing.

I also tried yarn after and it worked but then It keeps failing with connection issues.

Im on mobile now but I'll check later if there's more output

Thanks

**Comment by nhooyr** [comment]
Please upload the debug log file `/root/.npm/_logs/2020-07-14T12_30_33_064Z-debug.log`.

**Comment by mike-pt** [comment]
This is a azure VM so python3 is installed (not 2 though not sure if that matters)

but I do have:
```
pkg-config libsecret-devel libX11-devel libxkbfile-devel
```

**Comment by nhooyr** [comment]
Got it. Can't comment further without the full log file.

**Comment by mike-pt** [comment]
Dang it I though I uploaded it in the previous post:

[2020-07-14T12_30_33_064Z-debug.log](https://github.com/cdr/code-server/files/4956293/2020-07-14T12_30_33_064Z-debug.log)

That's the one from when I run it originally

**Comment by mike-pt** [comment]
I tied with yarn and it just works:

```
FreeBSD 12.1-RELEASE-p7
No precompiled releases available for freebsd.
Installing with yarn.

+ yarn global add code-server --unsafe-perm
yarn global v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "code-server > @coder/logger@1.1.11" has unmet peer dependency "@google-cloud/logging@^4.5.2".
[4/4] Building fresh packages...
[1/1] _ code-server
success Installed "code-server@3.4.1" with binaries:
      - code-server
Done in 206.03s.

**Comment by xpader** [comment]
Same error on freebsd.

**Comment by mike-pt** [comment]
I went back to try this on a new VM and noticed trying to install the dep manually would fail:

`sudo npm install -g @google-cloud/logging@^4.5.2`

complains that it can't build do to a grpc issue, however latest works just fine 

My best guess is this is related to https://github.com/grpc/grpc/issues/15010 which was since fixed.

Maybe we just need to bump google-cloud/logging version?

**Comment by code-asher** [comment]
The Google cloud logging library is an optional dependency for our
logger but we don't use it in code-server so it's not required. The peer
dependency warning can be safely ignored. :)

**Comment by mike-pt** [comment]
Hum but post install still failed right after that but that was the old log...

I'm actually getting different results now, It did finish install (with the warning) but on running I get:
```
Error: Cannot find module 'yazl'
Require stack:
- /usr/local/lib/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/local/lib/node_modules/code-server/lib/vscode/out/vs/server/fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:900:15)
    at Function.Module._load (node:internal/modules/cjs/loader:745:27)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at t.load (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:17:960)
    at e.load (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:13:941)
    at o (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:31:189)
    at Object.errorback (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:31:313)
    at e.triggerErrorback (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:14:306)
    at /usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:14:10
    at ReadFileContext.callback (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:18:342)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:273:13) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/code-server/lib/vscode/out/bootstrap-amd.js',
    '/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/server/fork.js'
  ],
  phase: 'loading',
  moduleId: 'yazl',
  neededBy: [ 'vs/base/node/zip' ]
}
[2020-11-03T18:01:11.219Z] error VS Code exited unexpectedly with code 0
```

So looks like some deps are not being installed

**Comment by mike-pt** [comment]
ah nvm I'm not even sure how it supposedly finished installing, I wipped all modules and started fresh and noticed I was missing "pkgconf" 

In practice FreeBSD needs:
`sudo pkg install git-lite python3 libsecret libinotify libX11 libxkbfile pkgconf`

But I missed pkgconf -.-'


I wonder if we should have this as part of the install.sh if we detect FreeBSD ?

**Comment by code-asher** [comment]
I think that's a good idea.
