### ISSUE TITLE
Websocket connection drops if user logged out from ssh

### ISSUE THREAD

**Issue by beykansen** [cdr/code-server#1882]
I've installed code-server via sh script as root user. But after closing ssh connection from my mac terminal, on browser web socket connection drops too. Then it turns to 502 error page. After reconnect ssh from terminal and reload web page, 502 goes away and everything returning to normal.

I am not using ssh tuneling. I've nginx reverse proxy front of it. As a workaround, I've created screen session on another vm and connected as root to keep alive ssh connection and keep logged in status of root user.

Why this is happening? Do you guys have any idea? My main use case, turning my ipad to development machine.

Thank you for your help.

**Comment by jinexists** [comment]
I had the same issue, for me it was an issue with systemd not starting services at boot under my user.
I fixed it by enabling user lingering for my user.
`loginctl enable-linger username`
This worked for me on Ubuntu 20.04.

**Comment by preslavrachev** [comment]
@jinexists This worked very well for me too. Thanks!

**Comment by kylecarbs** [comment]
Thanks @jinexists !

**Comment by nhooyr** [comment]
Lets document this in the FAQ.

**Comment by nhooyr** [comment]
[v3.5.0 with VS Code v1.48.2 has been released, fixing this issue!](https://github.com/cdr/code-server/releases/tag/v3.5.0) 🍻
