### ISSUE TITLE
Android Touch issues

### ISSUE THREAD

**Issue by EdSaleh** [cdr/code-server#1887]
Hello,

I'm running code-server on Android using termux and so far it has been working amazingly well and great. However, I am facing problems regarding touch screen typing. VSCode relies on mouse/keyboard and touch input doesn't work very well when typing or deleting on phone, and when you try to scroll up and down, keyboard shows up. Is it possible to find a fix for this keyboard and mouse issue for android?

Thank you,

**Comment by EdSaleh** [comment]
For now, I am using hackers keyboard which allows full control of VSCode using keyboard.

**Comment by EdSaleh** [comment]
I have also noticed that VHSCode app handles hotkeys, keyboard better than runing from chrome.

**Comment by EdSaleh** [comment]
Using the Android app with Hackers Keyboard has been great so far with no touch or mouse or keyboard issues.

**Comment by code-asher** [comment]
I'll have to try out that keyboard. I think VS Code doesn't have any plans right now for fixing this unfortunately.

**Comment by nhooyr** [comment]
I think we need a FAQ entry on termux.

**Comment by DevDK12** [comment]
Can anyone tell that how do we fix this CODE-SERVER typing error on chrome android

**Comment by code-asher** [comment]
The only workarounds I'm aware of are to use a different on-screen keyboard (some seem to work better than others) or a physical keyboard.

**Comment by Splizard** [comment]
Looking for some better options here, are there keyboards that can be manually toggled, or can we create an extension that adds a floating keyboard button that toggles keyboard?

**Comment by zongou** [comment]
> Looking for some better options here, are there keyboards that can be manually toggled, or can we create an extension that adds a floating keyboard button that toggles keyboard?

this issue can be fixed easily

checkout this [pull request](https://github.com/microsoft/vscode/pull/197915/files)

I prefer to use code-server-oss, and i am optimising code-server-oss for android, i compiled it with github action
[![Build vscode server](https://github.com/zongou/actions/actions/workflows/build_vscode_server.yaml/badge.svg)](https://github.com/zongou/actions/actions/workflows/build_vscode_server.yaml)
you can download and try it.

**Comment by zongou** [comment]
try scroll with scroll bar

**Comment by zongou** [comment]
> Looking for some better options here, are there keyboards that can be manually toggled, or can we create an extension that adds a floating keyboard button that toggles keyboard?

try scroll with scroll bar

**Comment by zongou** [comment]
This patch can improve this situation
```patch
diff --git a/src/vs/base/browser/touch.ts b/src/vs/base/browser/touch.ts
index dd74dca3eb4..45f7df1af8f 100644
--- a/src/vs/base/browser/touch.ts
+++ b/src/vs/base/browser/touch.ts
@@ -73,6 +73,7 @@ export class Gesture extends Disposable {
 	private static readonly HOLD_DELAY = 700;
 
 	private dispatched = false;
+	private dispatchedEventType: string | undefined;
 	private readonly targets = new LinkedList<HTMLElement>();
 	private readonly ignoreTargets = new LinkedList<HTMLElement>();
 	private handle: IDisposable | null;
@@ -197,7 +198,7 @@ export class Gesture extends Disposable {
 				const evt = this.newGestureEvent(EventType.Tap, data.initialTarget);
 				evt.pageX = arrays.tail(data.rollingPageX);
 				evt.pageY = arrays.tail(data.rollingPageY);
-				this.dispatchEvent(evt);
+								this.dispatchEvent(evt);
 
 			} else if (holdTime >= Gesture.HOLD_DELAY
 				&& Math.abs(data.initialPageX - arrays.tail(data.rollingPageX)) < 30
@@ -206,7 +207,7 @@ export class Gesture extends Disposable {
 				const evt = this.newGestureEvent(EventType.Contextmenu, data.initialTarget);
 				evt.pageX = arrays.tail(data.rollingPageX);
 				evt.pageY = arrays.tail(data.rollingPageY);
-				this.dispatchEvent(evt);
+								this.dispatchEvent(evt);
 
 			} else if (activeTouchCount === 1) {
 				const finalX = arrays.tail(data.rollingPageX);
@@ -226,16 +227,22 @@ export class Gesture extends Disposable {
 					deltaY > 0 ? 1 : -1,		// y direction
 					finalY						// y now
 				);
+
+				this.dispatchedEventType = EventType.Change;
 			}
 
 
 			this.dispatchEvent(this.newGestureEvent(EventType.End, data.initialTarget));
 			// forget about this touch
 			delete this.activeTouches[touch.identifier];
-		}
+					}
 
 		if (this.dispatched) {
-			e.preventDefault();
+			// make keyboard do not popout when scrolling
+			if (this.dispatchedEventType !== EventType.Change) {
+				e.preventDefault();
+			}
+			this.dispatchedEventType = undefined;
 			e.stopPropagation();
 			this.dispatched = false;
 		}
```

**Comment by RArchered** [comment]
> This patch can improve this situation.
> 
> ```diff
> diff --git a/src/vs/base/browser/touch.ts b/src/vs/base/browser/touch.ts
> index dd74dca3eb4..4e997aff600 100644
> --- a/src/vs/base/browser/touch.ts
> +++ b/src/vs/base/browser/touch.ts
> @@ -73,6 +73,7 @@ export class Gesture extends Disposable {
>  	private static readonly HOLD_DELAY = 700;
>  
>  	private dispatched = false;
> +	private dispatchedEventType: string | undefined;
>  	private readonly targets = new LinkedList<HTMLElement>();
>  	private readonly ignoreTargets = new LinkedList<HTMLElement>();
>  	private handle: IDisposable | null;
> @@ -226,6 +227,8 @@ export class Gesture extends Disposable {
>  					deltaY > 0 ? 1 : -1,		// y direction
>  					finalY						// y now
>  				);
> +
> +				this.dispatchedEventType = EventType.Change;
>  			}
>  
>  
> @@ -235,7 +238,11 @@ export class Gesture extends Disposable {
>  		}
>  
>  		if (this.dispatched) {
> -			e.preventDefault();
> +			// make virtual keyboard do not popup up on android when scrolling
> +			if(this.dispatchedEventType !== EventType.Change){
> +				e.preventDefault();
> +			}
> +			this.dispatchedEventType = undefined;
>  			e.stopPropagation();
>  			this.dispatched = false;
>  		}
> ```

It seems the issue lies within the VSCode project. I wanted to ask if you have any plans to merge this change into the VSCode project? It seems that the problem still exists.

**Comment by zongou** [comment]
> > This patch can improve this situation.
> > ```diff
> > diff --git a/src/vs/base/browser/touch.ts b/src/vs/base/browser/touch.ts
> > index dd74dca3eb4..4e997aff600 100644
> > --- a/src/vs/base/browser/touch.ts
> > +++ b/src/vs/base/browser/touch.ts
> > @@ -73,6 +73,7 @@ export class Gesture extends Disposable {
> >  	private static readonly HOLD_DELAY = 700;
> >  
> >  	private dispatched = false;
> > +	private dispatchedEventType: string | undefined;
> >  	private readonly targets = new LinkedList<HTMLElement>();
> >  	private readonly ignoreTargets = new LinkedList<HTMLElement>();
> >  	private handle: IDisposable | null;
> > @@ -226,6 +227,8 @@ export class Gesture extends Disposable {
> >  					deltaY > 0 ? 1 : -1,		// y direction
> >  					finalY						// y now
> >  				);
> > +
> > +				this.dispatchedEventType = EventType.Change;
> >  			}
> >  
> >  
> > @@ -235,7 +238,11 @@ export class Gesture extends Disposable {
> >  		}
> >  
> >  		if (this.dispatched) {
> > -			e.preventDefault();
> > +			// make virtual keyboard do not popup up on android when scrolling
> > +			if(this.dispatchedEventType !== EventType.Change){
> > +				e.preventDefault();
> > +			}
> > +			this.dispatchedEventType = undefined;
> >  			e.stopPropagation();
> >  			this.dispatched = false;
> >  		}
> > ```
> 
> It seems the issue lies within the VSCode project. I wanted to ask if you have any plans to merge this change into the VSCode project? It seems that the problem still exists.

No plan, i have forked my own vscode repo, you can Download or get my modification code there
[zongou/vscode](https://github.com/zongou/vscode)

**Comment by RArchered** [comment]
> > > This patch can improve this situation.
> > > ```diff
> > > diff --git a/src/vs/base/browser/touch.ts b/src/vs/base/browser/touch.ts
> > > index dd74dca3eb4..4e997aff600 100644
> > > --- a/src/vs/base/browser/touch.ts
> > > +++ b/src/vs/base/browser/touch.ts
> > > @@ -73,6 +73,7 @@ export class Gesture extends Disposable {
> > >  	private static readonly HOLD_DELAY = 700;
> > >  
> > >  	private dispatched = false;
> > > +	private dispatchedEventType: string | undefined;
> > >  	private readonly targets = new LinkedList<HTMLElement>();
> > >  	private readonly ignoreTargets = new LinkedList<HTMLElement>();
> > >  	private handle: IDisposable | null;
> > > @@ -226,6 +227,8 @@ export class Gesture extends Disposable {
> > >  					deltaY > 0 ? 1 : -1,		// y direction
> > >  					finalY						// y now
> > >  				);
> > > +
> > > +				this.dispatchedEventType = EventType.Change;
> > >  			}
> > >  
> > >  
> > > @@ -235,7 +238,11 @@ export class Gesture extends Disposable {
> > >  		}
> > >  
> > >  		if (this.dispatched) {
> > > -			e.preventDefault();
> > > +			// make virtual keyboard do not popup up on android when scrolling
> > > +			if(this.dispatchedEventType !== EventType.Change){
> > > +				e.preventDefault();
> > > +			}
> > > +			this.dispatchedEventType = undefined;
> > >  			e.stopPropagation();
> > >  			this.dispatched = false;
> > >  		}
> > > ```
> > 
> > 
> > It seems the issue lies within the VSCode project. I wanted to ask if you have any plans to merge this change into the VSCode project? It seems that the problem still exists.
> 
> No plan, i have forked my own vscode repo, you can Download or get my modification code there [zongou/vscode](https://github.com/zongou/vscode)

got it，many thanks～
