### ISSUE TITLE
【Debugger for JAVA】debug Java from remote server

### ISSUE THREAD

**Issue by MrLiu0635** [cdr/code-server#1890]
- Web Browser: Chrome
- Local OS: Window
- Remote OS: Centos 7
- Remote Architecture: Docker
- `code-server --version`: 
 ```
 code-server: v3.4.1
 VS Code: v1.45.1
 Commit: 48f7c2724827e526eeaa6c2c151c520f48a61259
 Date: 2020-06-04T10:39:14Z
 Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 
 Safari/537.36
```
When I wanne to debug java, and config launch.json, and click DO, then error occur.
![2](https://user-images.githubusercontent.com/11811899/87894686-09f19380-ca76-11ea-89d6-3942942d88a2.png)

may I hava your suggestions about the problem?

**Comment by Crazykado-iphone8MacProOs** [comment]
I me go

**Comment by nhooyr** [comment]
Please file questions at https://www.reddit.com/r/codeserver/

From what I can tell this doesn't appear to be a bug/feature request in code-server here, looks like a config issue.

Feel free to comment and I'll reopen.

**Comment by MrLiu0635** [comment]
I have got the solution. The plugin 【Debugger for JAVA】depends on java jdk env.
