### ISSUE TITLE
Swap Not Clearing

### ISSUE THREAD

**Issue by rightisleft** [cdr/code-server#1891]
- Web Browser: Chrome
- Local OS: OS X 
- Remote OS: Ubuntu 18.04
- Remote Architecture: X86
- `code-server --version`:

When running debug logging for an app, there should be some type of log rotation that occurs. Currently i'm seeing very large 118GB swap files:

```
root@developer-me:/var/tmp# pwd
/var/tmp
root@developer-me:/var/tmp# ls -lah code-server.conf.swp
-rw------- 1 me me 118G Jul 18 14:13 code-server.conf.swp
```

**Comment by nhooyr** [comment]
Hi @rightisleft code-server doesn't generate any .swp files. I believe this is an unrelated issue, perhaps something in your vim config?

**Comment by rightisleft** [comment]
That's odd. I will have to investigate further.

**Comment by nhooyr** [comment]
Feel free to comment if this needs to be reopened.
