### ISSUE TITLE
Target Node 12

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#1894]
We'll need to target the same version as VS Code to fix these issues:

https://github.com/cdr/code-server/issues/1892
https://github.com/cdr/code-server/issues/1810

**Comment by code-asher** [comment]
Relevant: https://github.com/cdr/code-server/issues/1898

**Comment by nhooyr** [comment]
[v3.5.0 with VS Code v1.48.2 has been released, fixing this issue!](https://github.com/cdr/code-server/releases/tag/v3.5.0) 🍻
