### ISSUE TITLE
Ruby Extension

### ISSUE THREAD

**Issue by pmcnano** [cdr/code-server#1895]
- [ ] Extension name: Ruby
- [ ] Extension GitHub or homepage: https://github.com/rubyide/vscode-ruby

The version in the marketplace is 0.25.0 and intellisync doesn't work. The latest version is 0.27.0. I tried installing it manually but it wouldn't work.

**Comment by oxy** [comment]
Blocked right now - upstream does not mark releases or include `.vsix` files with it, which we need!
