### ISSUE TITLE
Periodically refresh certificate

### ISSUE THREAD

**Issue by CeeJayMI** [cdr/code-server#1900]
For those of us using ACME certificate providers, it would be nice if the certificate would be refreshed without having to restart the service.

**Comment by nhooyr** [comment]
This is best handled by a reverse proxy like Caddy or Nginx. We could implement it into code-server but it seems out of scope.

**Comment by nhooyr** [comment]
Closing with the above justification. Feel free to comment if you'd like it reopened. 🍻
