### ISSUE TITLE
[Electron Replace] libffmpeg replacement issue

### ISSUE THREAD

**Issue by ForeverOpp** [cdr/code-server#1901]
I tried to install an extension via VSIX file from VS Code marketplace below:  
- [ ] Extension name: VSC Netease Music  
- [ ] Extension GitHub or homepage: https://github.com/nondanee/vsc-netease-music  
   
It is a music player plugin like running Spotify in VS Code.  
  
The author said:  
  
> [The Electron version used by VS Code does not contain ffmpeg] (https://stackoverflow.com/a/51735036), you need to replace the built-in ffmpeg dynamic link library to play normally (you need to replace it every time you update VS Code).

But I can't find anything about electron, what should I do?

**Comment by nhooyr** [comment]
code-server doesn't run with electron, it runs in whatever browser you run it inside of.

I'd file an issue with the extension author. I don't think there's anything we can do here.
