### ISSUE TITLE
[SOLVED] Global Search and Replace doesn't work; node.js spawn ENOENT error

### ISSUE THREAD

**Issue by mike-pt** [cdr/code-server#1907]
- Web Browser: Firefox/Edge (Chromium based)
- Local OS: macOS 10.15
- Remote OS: FreeBSD 12.1
- Remote Architecture: amd64
- `code-server --version`: 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259

Fail with “Error: spawn ENOENT” 
![image](https://user-images.githubusercontent.com/2327910/88299249-10903d00-ccfa-11ea-9ecb-d4f6367b4943.png)

**Comment by code-asher** [comment]
That's odd, `vscode-ripgrep` is supposed to download ripgrep as part of the postinstall. When you installed code-server were there any errors about downloading `rg`?

Something that might work to fix it would be to try running the `yarn` in the `vscode-ripgrep` directory and see if it downloads it.

Re-installing code-server might also work.

**Comment by mike-pt** [comment]
I had troubles with npm but yearn worked fine no errors, also search and replace work fine infile just not global.

I'll try the suggestion

**Comment by mike-pt** [comment]
The bin folder was empty but running yarn (and yarn instal) didn't download it either:

```
yarn install v1.22.4
warning ../../../../../../package.json: No license field
[1/4] Resolving packages...
success Already up-to-date.
$ node ./lib/postinstall.js
bin/ folder already exists, exiting
Done in 0.23s.
```

I wonder if it cause there's no binary for FreeBSD

**Comment by mike-pt** [comment]
Yeah I think that might be it:
https://github.com/microsoft/ripgrep-prebuilt/releases/tag/v12.1.1

**Comment by mike-pt** [comment]
There's a port though :)

https://www.freshports.org/textproc/ripgrep/

I installed it and simlinked rg inside the bin dir  `/usr/local/share/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/vscode-ripgrep/bin`

**Comment by code-asher** [comment]
That makes sense! It might make sense to try and fix this on our end even if it's an upstream issue since we list FreeBSD in our install script and docs. Or possibly we can get a PR merged upstream.

**Comment by mike-pt** [comment]
Yeah I looked into that actually we should be easy to do at this side as a post  yarn install (npm is not working for me but I assume it would be the same) that said I was actually gonna submit a GHI on MS side and point to the port

**Comment by nhooyr** [comment]
Should be fixed now!
