### ISSUE TITLE
Can be reached from localhost but can't be reached from a remote client

### ISSUE THREAD

**Issue by FUTURETECH6** [cdr/code-server#1909]
I install the code server by directly download the .deb file and dpkg it.

After `code-server --port 1234 --auth none -vvv` on the remote server, I can reach it from that server (for example, fetching the "index.html" by ` wget localhost:1234`, meantime I have debug log output from code-server), but I can't reach it from my device(with no debug log output).

I though it has nothing to do with code-server itself so I checked the firewall setting and it's alright.

By the way, running `sudo systemctl start coder-web.service` will get an ERROR of "Failed to start coder-web.service: Unit coder-web.service not found."

**Comment by nhooyr** [comment]
Please see https://github.com/cdr/code-server/blob/master/doc/guide.md#3-expose-code-server

> By the way, running sudo systemctl start coder-web.service will get an ERROR of "Failed to start coder-web.service: Unit coder-web.service not found."

We don't ship a `coder-web` service.

**Comment by jiaozibufu** [comment]
try 0.0.0.0:1234

**Comment by FUTURETECH6** [comment]
I tried using another port and it works, I think it's because of some settings of the VPS server
