### ISSUE TITLE
command 'python.setInterpreter' not found

### ISSUE THREAD

**Issue by binfeng** [cdr/code-server#1911]
Cannot change python interpreter. Has error: command 'python.setInterpreter' not found

**Comment by fallenhitokiri** [comment]
@binfeng seems to be the same issue as this one https://github.com/cdr/code-server/issues/1897

**Comment by code-asher** [comment]
Closing as a duplicate of #1897. I've also seen this on the latest version of the extension but I haven't had a chance to debug it yet.
