### ISSUE TITLE
Blank place with external keyboard on ipados with safari/chrome

### ISSUE THREAD

**Issue by Paultje52** [cdr/code-server#1917]
- Web Browser: Safari
- Local OS: IpadOS 14
- Remote OS: Ubuntu 16.04
- `code-server --version`: 3.4.1

I connected an external bluetooth keyboard to my ipad.
When I click on a place where I can type, in the code itself, terminal, creating new files, etc, a blank place where the keyboard should be appears, that takes half of the screen up. It's so annoying that coding isn't possible.

![image](https://user-images.githubusercontent.com/31313717/88519186-00c27280-cff2-11ea-945b-8c8514102853.jpeg)

## Chrome
I also downloaded chrome, and when I try coding on chrome, a bar appears in the middle of the screen.

![image](https://user-images.githubusercontent.com/31313717/88519232-12a41580-cff2-11ea-8d10-b9148278bb65.jpeg)

**Comment by Paultje52** [comment]
I made this issue a week ago. No answer. Is this a bug, or am I doing something wrong? Or is this unfixable bug by ios/ipados?

**Comment by code-asher** [comment]
I don't have an iPad so I can't make any concrete statements but I think it's unlikely these are caused by code-server. @nhooyr are you able to replicate this?

**Comment by Paultje52** [comment]
I tried using https://repl.it on my ipad, and it works just fine, on safari and on chrome. No bar etc, so that means that the issue is with code-server and not with ipados.

**Comment by nhooyr** [comment]
@Paultje52 repl.it isn't browser VS Code, it uses Monaco but is entirely different otherwise. I'll give this a test soon.

**Comment by Paultje52** [comment]
I know that repl.it isn't the same as code-server. I'm just saying that it is possible to remove bars like that.

Anyways, is there any progress?

**Comment by nhooyr** [comment]
Unfortunately not. Also see https://github.com/cdr/code-server/issues/979

Safari's support for running VS Code is very poor!

We currently have 14 open issues for safari! https://github.com/cdr/code-server/issues?q=is%3Aopen+is%3Aissue+label%3Abrowser-safari

**Comment by jsjoeio** [comment]
Hey @Paultje52 - are you still seeing this issue?

I’m currently using `code-server` on iPad and not seeing this issue. 

Here’s a screenshot: 

![8FFF2035-0BC7-4E11-A8E4-729A16D2D7F1](https://user-images.githubusercontent.com/3806031/103934313-01ebe580-50e2-11eb-9637-53ee4ee3480d.png)

I’m using:
- iPad Pro (11 inch, 2nd gen) v14.1
- Apple Magic Keyboard
- Chrome v87.0

If this is no longer an issue, feel free to close.

**Comment by Paultje52** [comment]
Hello. Sorry for the late response, but I installed code-server version 3.8.0 an I don't have any problems in safari or chrome. This issue can be closed, thanks for your help!

**Comment by jsjoeio** [comment]
Hooray! Thanks for following up @Paultje52 - glad to hear it!
