### ISSUE TITLE
White screen after login

### ISSUE THREAD

**Issue by Byrth** [cdr/code-server#1918]
My symptoms are similar to #1362 , but some things are different.

Versions:
* Windows server 2008
* `coder/code-server:latest` image pulled yesterday
* Chrome v58.0.3029.96

I get the sign-in screen and can sign in, but then I am taken to a white screen. The console of chrome looks like this:
![tmp](https://user-images.githubusercontent.com/2229694/88592505-210f2300-d02c-11ea-9be0-20bbf51e9000.png)
The bottom ones there don't seem to be permission errors. The `.vscode` directory is not created.

The other thread gave me the idea that it might be related to network permission problems, so I tried:
* http
* http with ssh port forwarding
* http with disabled auth and ssh port forwarding

No dice. Is my old server incompatible with the javascript (.finally) being used here somehow?

**Comment by Byrth** [comment]
https://developers.google.com/web/updates/2017/12/nic63

Looks like `.finally` was implemented 5 versions after the version I'm using.

**Comment by code-asher** [comment]
That makes sense. I wasn't able to find a minimum browser requirement for VS Code unfortunately. We could consider trying to lower the compile target so it works on older browsers although I'm not sure if that's a good move or if we should try to encourage updating browsers.

**Comment by Byrth** [comment]
I confirmed that upgrading to Chrome v84 (current) solved the problem and now it works as expected. I would guess the lowered limit for version on Chrome is 63 or higher.
