### ISSUE TITLE
code: command not found

### ISSUE THREAD

**Issue by Yegiri** [cdr/code-server#1929]
I can Install 'code' command in PATH
![image](https://user-images.githubusercontent.com/51883273/88899911-3b8e0a00-d281-11ea-8389-18271ab30881.png)

Does the code-server have the same thing?

**Comment by code-asher** [comment]
Not at the moment. I think the main use of this is to be able to open files from the command line right? We'll need to address https://github.com/cdr/code-server/issues/164 first.

**Comment by Yegiri** [comment]
I want to use the following command to install the extension through the terminal.
```
code --install-extension ms-python.pyhon
```
It is work in vscode.

So, do you know how to install extensions through the terminal in code-server.
Or in other words, do you know what command to add to the Dockerfile can pre-install extensions?

**Comment by code-asher** [comment]
Ah I see. If you're using our Docker image `code-server` should already be in your path. Try running this in your terminal:

```
code-server --install-extension ms-python.pyhon
```

**Comment by Yegiri** [comment]
I'll have a try, thank you very much!

**Comment by JammSpread** [comment]
I like using an alias in ~/.bashrc to use it. It's pretty much simpler.
