### ISSUE TITLE
Add extension request: vscode-plantuml

### ISSUE THREAD

**Issue by InterestedInTechAndCake** [cdr/code-server#1930]
Hi,

Could developers here kindly add this extension to the code-server market place please?

https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml

and their github project, if needed:

https://github.com/qjebbs/vscode-plantuml

Many thanks!

**Comment by cmoog** [comment]
Thank you for your request! The extension is now live in the code-server extension marketplace.
