### ISSUE TITLE
C++ Intellisense extension doesn'twork

### ISSUE THREAD

**Issue by Morritz** [cdr/code-server#1935]
I had installed C++ extension and when I press CTRL + SPACE there are no suggestions for autocompleting started syntax, how could i fix that if it is possible?
I know there should be some language server
Remote OS: freebsd
Remote Architecture: x64
`code-server --version`: 3.41

**Comment by ghokun** [comment]
Here is my version of code-server using linuxserver.io's build with OpenCV and clangd added. Install clangd extension from store and it works out of the box.

https://github.com/ghokun/code-cv

**Comment by Morritz** [comment]
> Here is my version of code-server using linuxserver.io's build with OpenCV and clangd added. Install clangd extension from store and it works out of the box.
> 
> https://github.com/ghokun/code-cv

my freebsd has no linux support enabled, is it compatible then, and i cannot run docker

**Comment by ghokun** [comment]
> my freebsd has no linux support enabled, is it compatible then, and i cannot run docker

Actually, I shared my configuration as an example. You can checkout Dockerfile and install corresponding packages to your environment.

**Comment by nhooyr** [comment]
As there is no feature or bug here, please file this instead at https://www.reddit.com/r/codeserver.

Although I believe @Morritz correctly answered your question.

**Comment by Rathna-K** [comment]
> Here is my version of code-server using linuxserver.io's build with OpenCV and clangd added. Install clangd extension from store and it works out of the box.
> 
> https://github.com/ghokun/code-cv

Do you have a prebuilt docker image? If not any chance you can publish one? TIA.

**Comment by ghokun** [comment]
> Do you have a prebuilt docker image? If not any chance you can publish one? Looking for a RPi4 to host the image. TIA.

Please take a look at this [repository](https://github.com/ghokun/code-cv).

There is a dockerfile that you can use to build your own image locally. Also you can check provided docker-compose file, to see how to run (My image can be downloaded from ghcr.io/ghokun/code-cv).

I should mention that my image works for x86_64. I have not tested on a raspberrypi.
