### ISSUE TITLE
Request for pylance extension

### ISSUE THREAD

**Issue by vumaasha** [cdr/code-server#1938]
- [ ] Extension name: Pylance
- [ ] Extension GitHub or homepage: https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance

**Comment by cmoog** [comment]
> The Pylance codebase is not open-source but you can contribute to Pyright to make improvements to the core typing engine that powers the Pylance experience.

Unfortunately, given that Pylance is not open source, we are unable to offer the extension on our marketplace. Redistributing the closed-source extension package present on the Microsoft extension marketplace is against its terms of use.

**Comment by maresb** [comment]
Not only is redistribution not allowed, but even if installed by hand, Pylance will [refuse to run on any unofficial build](https://github.com/microsoft/pylance-release/issues/135#issuecomment-662607952).

Isn't it wonderful that M$ now "loves open source"? /s

**Comment by ackalker** [comment]
I hope this doesn't spell the future of VSCode, as it reminds me too much of the "Embrace, extend, extinguish" mantra. As in: embrace open source, extend (or replace) the most popular extensions with proprietary ones containing binary blobs, extinguish support of the remaining open source bits.

**Comment by MarcSkovMadsen** [comment]
I am interested in getting pylance onto code-server as well.

**Comment by jsjoeio** [comment]
@MarcSkovMadsen I took a look again at Pylance and it's still closed source so I don't think we can support it in code-server at this time. You could open an issue in their repo asking if they might open source or provide a way to use it in a project like code-server. Here is a link to their [new issue page](https://github.com/microsoft/pylance-release/issues/new/choose)

**Comment by maresb** [comment]
@MarcSkovMadsen, the unfortunate situation regarding Pylance and open-source builds is discussed extensively [in this reddit thread](https://www.reddit.com/r/linux/comments/k0s8qw/vs_code_developers_prevent_running_the_new/). I highly recommend that you read through the post and comments.

**Comment by benz0li** [comment]
@MarcSkovMadsen You may be interested in my multi-arch (`linux/amd64`, `linux/arm64/v8`) [[CUDA-enabled] Data Science Development Containers](https://github.com/b-data/data-science-devcontainers) for R, Python and Julia.
