### ISSUE TITLE
Heroku reset password

### ISSUE THREAD

**Issue by devhitx** [cdr/code-server#1945]
Excuse me, I created heroku application using @ivang7 docker but I can not access to website due to password problem. What is its default password or how can I reset password. I tried to run command "code-server --auth none" by heroku cli but it not working. Can anyone help me fix it ? Thank you very much

https://hub.docker.com/r/ivang7/code-server-heroku

**Comment by ivang7** [comment]
Hi, you can set environment variable PASSWORD (in heroku app profile ), code-server use it.
Also you can use this repo for create directly heroku-app from repository https://github.com/ivang7/heroku-vscode (heroku make build Docker file from repository and run application for you)

**Comment by code-asher** [comment]
@ivang7 Thanks for answering this!

@devhitx I'll close the issue for now but feel free to keep responding here.
