### ISSUE TITLE
How to delete the code-server completely from Termux??

### ISSUE THREAD

**Issue by RealGJ** [cdr/code-server#1946]
Is there any way to delete this from Termux on Android?  

Thank You!!!

**Comment by code-asher** [comment]
You can just `rm -r` the `code-server` directory. It depends on where you installed it, but if you used the install script by default it'll be in `~/.local/lib/code-server-<version>` and there will also be a binary symlink in `~/.local/bin/code-server` you can remove.

If you want to delete settings and data as well you can remove `~/.local/share/code-server` and `~/.config/code-server`.

**Comment by code-asher** [comment]
If you used `yarn` or `npm` to install code-server then you can use them to remove it.
