### ISSUE TITLE
Start code-server with no project directory

### ISSUE THREAD

**Issue by geiseri** [cdr/code-server#1951]
I have a single instance code server, but I like to have multiple projects open.  It used to be that if you didn't supply a root directory it would not have any folder open by default.  Is there a way to get this back, or make this a flag at startup?

**Comment by code-asher** [comment]
This is the default still but code-server remembers the last opened directory and stores it in `~/.local/share/code-server/coder.json`. It'll use this if nothing else is provided.

There's no way to circumvent this other than remove the entry from `coder.json` (or delete it entirely) so maybe we should add a flag like `--no-default-dir` or something more clever than that. Or maybe something like `--no-remember` to avoid writing the last opened directory so you can still use `coder.json` to set the default if desired.

**Comment by geiseri** [comment]
The issue I have with the default folder is the base has 10 projects with typescript, javascript,c++, and java.  Needless to say, code-server takes it's sweet time when it starts to parse that and load the respective extensions.  A `--no-default-dir` would be helpful so that when I open a new window I don't have to race that process to open the correct project folder =)

**Comment by code-asher** [comment]
Makes sense to me! In the meantime I'll throw out a couple workarounds that may or may not work for you (you've likely already considered them, but just in case):

- Create and use a workspace that contains all the projects.
- Manually add the `?folder=/path/to/dir` URL parameter when going to code-server to open the right directory (or use bookmarks).
- Kind of a silly one but remove the last visited property from `coder.json` and make it read-only. code-server will log a warning when trying to write but it can be ignored.

**Comment by geiseri** [comment]
I tried the first but VS code workspaces get "funny" if you mix languages.  I was also a bit unwieldy.  The 2nd works pretty well, but for some reason, Google decided that you should not be allowed to open a PWA directly, and need to open it in a browser and then open with the PWA.  I am not sure how unique I am.  I use code-server from a Chromebook remotely, so I tend to use it as someone would use a local instance.  I think its more a limitation of the PWA technology than the code-server product itself.

**Comment by code-asher** [comment]
Ah that's unfortunate. Fortunately adding this flag should be simple and straightforward.

**Comment by geiseri** [comment]
I did finally find a reasonable workaround.  I used the `alefragnani.project-manager` extension and set my startup folder to an empty directory. I tried with a workspace for each project and that worked too, but the extension made it a bit easier to manage.  I think this is a "reasonable" workaround, so I would be comfortable closing this issue, and just putting a note about that in the faq.
