### ISSUE TITLE
Vim extension doesn‘t work on Safari (iPadOS)

### ISSUE THREAD

**Issue by silasalberti** [cdr/code-server#1952]
No key press has any effect when enabling Vim extension. If you press any key, in the bottom it displays “Activating extension“ for a short time and then nothing happens. The cursor just doesn‘t move or insert anything, no matter what you press. It doesn‘t show an error message, that‘s why it seems to be a slightly different issue than #1715 (and #1617 is only about Firefox).

- Web Browser: Safari
- Local OS: iPadOS 13
- Remote OS: Ubuntu 18.04
- Remote Architecture: x86_64
- `code-server --version`: 3.4.1

**Comment by pojntfx** [comment]
I can confirm this on iPad OS 14 Beta 3.

**Comment by code-asher** [comment]
Is the error message about the regular expression? If so, we'll need to wait until Safari supports it or see if we can edit the extension to use a different regular expression.

**Comment by nhooyr** [comment]
Very likely. See #1825

**Comment by nhooyr** [comment]
Please feel free to comment if not, and I'll reopen.

**Comment by jasonjurotich** [comment]
Having the same problem with iPad OS 14 on iPad Pro. You cannot edit anything with Vim extension on.

**Comment by code-asher** [comment]
I suspect it's the regular expression but let us know if it's a different error (there should be errors in the console although I think you'll need to connect the iPad to a Mac to see them).

**Comment by Tsarpf** [comment]
Still doesn't work on iPad. Don't have a mac so can't check the error unfortunately :( 

What sort of regular expression thing is it that is missing in Safari? I'd be interested in searching whether there are any plans for it being supported in the future.

**Comment by Tsarpf** [comment]
Ah this is probably the issue to track https://github.com/VSCodeVim/Vim/issues/5072 if someone else is interested.

**Comment by jsjoeio** [comment]
> Still doesn't work on iPad.

What version of code-server and iPad are you using? Can you please try [deploying code-server with Railway](https://www.youtube.com/watch?v=IWfkkaY5fXs) and testing again? I've used my iPad in the last month with code-server and the Vim extension and haven't seen any issues.

Actually, I see that in code-server, I'm using VSCodeVim 1.18.9 which works. I just tested in Codespaces and I see similar issues so this is upstream (issue you linked). 

Workaround: use ` 1.18.9 < || < 1.20.3`

**Comment by Tsarpf** [comment]
Yass! Downgrading to 1.18.9 fixed the issue. Thanks!
