### ISSUE TITLE
Giving input to Concole.ReadLine() from VSCode

### ISSUE THREAD

**Issue by SaiTeja390** [cdr/code-server#1957]
I'm running [code-server](https://github.com/cdr/code-server) in Google Cloud Shell and since code-server cannot run the Microsoft's C# debugger, I'm running netcoredbg.

 As mentioned [here](https://stackoverflow.com/questions/41195432/debug-console-window-cannot-accept-console-readline-input-during-debugging) I updated my `launch.json` file by adding `"console": "integratedTerminal"`. 

I checked [this link](https://github.com/OmniSharp/omnisharp-vscode/issues/1053#issuecomment-267768206) which says that Debug Console cannot take input to Console.ReadLine() and that it is meant only for inspection. So this means that I cannot send input to my program from Debug Console.

I read [this link](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#console-terminal-window) which says that setting `"console": "integratedTerminal"` will allow us to give input to the program from the `"TERMINAL" `  tab in VSCode. But that doesn't work.

![image](https://user-images.githubusercontent.com/20392034/89733686-e5854780-da74-11ea-98eb-75cc95439aa9.png)

The `"TERMINAL"` opens a shell ready to take usual linux commands, but not the input to the Console.ReadLine().

Can someone help to sort out the issue so that I can give input to the `Console.ReadLine()` from VSCode itself?

**Comment by code-asher** [comment]
I tried out netcoredbg with local VS Code and experienced the same problem so it looks like this is an upstream issue. I'm not sure if the problem lies with netcoredbg or VS Code or the C# extension though.

**Comment by MaxG-Git** [comment]
Running into exact same issue, Im no expert at all but have been trying to fix this for a while and have no idea what to do. Any update or solution for this?

**Comment by code-asher** [comment]
No updates, I haven't dug any further yet to see where the problem is.

**Comment by ktheticdev** [comment]
> No updates, I haven't dug any further yet to see where the problem is.

Actually the problem is that netcoredbg doesn't support the "console" argument. But one can try to implement it

**Comment by code-asher** [comment]
Ahhhhhh that makes sense.
