### ISSUE TITLE
workspace actions

### ISSUE THREAD

**Issue by avelino** [cdr/code-server#196]
- `code-server` version: master branch
- OS Version: Ubuntu 18.04

## Description

https://code.visualstudio.com/docs/editor/multi-root-workspaces#_workspace-file-schema

VSCode is supported in **Create Workspace**, when opening the workspace configuration file automatically pops up a button to load the workspace, this button is not working

![Screen Shot 2019-03-11 at 8 49 53 AM](https://user-images.githubusercontent.com/31996/54122217-3229a680-43db-11e9-88c2-9a1ed91b7228.png)

- [ ] close workspace not working
- [ ] load workspace not working

## Steps to Reproduce

https://code.visualstudio.com/docs/editor/multi-root-workspaces#_opening-workspace-files

**Comment by jwulf** [comment]
If I try opening the workspace file directly from the File > Open dialog, then a key is written to local storage for the workspace with a file path. On refreshing the page, the bundle does not load as the file path fails URI schema validation.

To recover, I have to delete the workspace key from local storage.

**Comment by geoah** [comment]
Having the same issue that @jwulf mentioned. "File > Open Workspace" results in a blank (grey) page with no options. On my local installation I was able to recover by wiping .local, but on `ide.coder.com` there is nothing I can do and the editor is unusable. (Console says `Failed "Start workbench"`)

**Comment by krazyito65** [comment]
> Having the same issue that @jwulf mentioned. "File > Open Workspace" results in a blank (grey) page with no options. On my local installation I was able to recover by wiping .local, but on `ide.coder.com` there is nothing I can do and the editor is unusable. (Console says `Failed "Start workbench"`)

I couldn't recover by wiping `~/.local/` is that the correct location?  I've only been able to get it to work after using a workspace action with incognito mode.

**Comment by jwulf** [comment]
Open developer tools in your browser. In Chrome you are looking for the Application > Local Storage tab. Something like that. It is HTML Local Storage in the browser client, which is why Incognito mode works.

**Comment by vnijs** [comment]
FYI Saving a workspace file doesn't seem to work from the command palette (i.e., nothing happens after providing a name). So I created one in vscode and tried to open it using code-server. It shows the content of the file and a button to open the workspace (see screenshot). Clicking the button shows the the following error in developer tools.

![image](https://user-images.githubusercontent.com/2998956/57174532-58752c80-6df5-11e9-8b34-c900f3749b02.png)

![image](https://user-images.githubusercontent.com/2998956/57174522-42676c00-6df5-11e9-87cc-d34f19bc4b84.png)

**Comment by levifox54** [comment]
im wondering if #490 is related to this and if #755 fixes this

**Comment by danger89** [comment]
I though it was me.. but apparently its not implemented..

**Comment by danger89** [comment]
@sr229 I think V2 gives me only more problems now.

**Issue nr. 1:**

Clicking on the folder won't change the path (which either stays `/home` or `/`), see video:

[![Watch the video](https://img.youtube.com/vi/ndCTFhn-ZJ4/hqdefault.jpg)](https://youtu.be/ndCTFhn-ZJ4)

**Issue nr. 2:**
Moreover, I pressed 'OK', redirected me to a blank page. 

**Issue nr. 3:**
After I reload the code-server URL myself, the folder at least was added to the explorer, but I can't remove it from the explorer without removing the content. Now `/home/coder` folder was added accidentally, which is not ideal.

**Comment by code-asher** [comment]
If you're using Firefox you might be running into this issue: https://github.com/cdr/code-server/issues/1063

**Comment by danger89** [comment]
Yep firefox.

**Comment by sr229** [comment]
We've opened this in Microsoft/vscode so it will be the web team that'll be in charge of this from now on.
