### ISSUE TITLE
Feature request: GitHub links from Codespaces

### ISSUE THREAD

**Issue by Heath123** [cdr/code-server#1960]
On this article:
https://www.freecodecamp.org/news/learn-programming-in-your-browser-the-right-way/
it says that adding this HTML to a page will let you import the repo into Codespaces:
```html
<p>
  <a href="https://online.visualstudio.com/environments/new?name=My%20Project&repo=username/reponame">
    <img src="https://img.shields.io/endpoint?style=social&url=https%3A%2F%2Faka.ms%2Fvso-badge">
  </a>
</p>
```
Is it possible to make this work with code-server? It doesn't seem to work at the moment.

**Comment by code-asher** [comment]
This would be cool although we don't have any plans to add this at the moment. See https://github.com/cdr/code-server/issues/1355

**Comment by Heath123** [comment]
Sorry, I missed that because it was closed

**Comment by Heath123** [comment]
Should this be closed?

**Comment by code-asher** [comment]
For now let's leave it open in case someone wants to work on it.
