### ISSUE TITLE
2 Factor Authentication. Support

### ISSUE THREAD

**Issue by SteamFinder** [cdr/code-server#1962]
**As we all now,the two factor login function is very effective to the security.**

Code-server has full access to server but it only have a **single password function** to protect the security of the server.If we can add 2 factor login on code-server,it will be more safe for the users.Lots of programs has already used two factor two-factor authentication.

I will appreciate that if you could add it.

**Comment by code-asher** [comment]
Thanks for the feature request! Let's track this here instead: https://github.com/cdr/code-server/issues/1625
