### ISSUE TITLE
Add version number option to --install-extension

### ISSUE THREAD

**Issue by arseniybanayev** [cdr/code-server#1965]
Due to [this issue](https://github.com/microsoft/vscode-python/issues/12465#issuecomment-673096760), I would like to be able to declare in my "IDE" Dockerfile that the MS Python extension should be installed at version 2020.05.86806, instead of latest (which is default).

Could you add an option to `code-server --install-extension` to allow specifying the version? Otherwise, I have to manually select the desired version whenever my "IDE" container starts anew. Suggested syntax could be `code-server --install-extension extension-name [--version 2020.05.86806]`.

**Comment by code-asher** [comment]
VS Code lets you do this using `@version` and the same applies to code-server (although VS Code doesn't document this anywhere for some reason, at least not that I could find).

```
code-server --install-extension ms-python.python@2020.5.86806
```

**Comment by code-asher** [comment]
It might not be a bad idea to mention this in our `--help` output or the FAQ.

**Comment by code-asher** [comment]
Actually they recently added it to their help so we should do the same.

**Comment by arseniybanayev** [comment]
Thanks! Awesome

**Comment by nhooyr** [comment]
Nice @code-asher
