### ISSUE TITLE
CTRL-S deletes input

### ISSUE THREAD

**Issue by ribrdb** [cdr/code-server#1967]
- Web Browser: Google Chrome 84.0.4147.110
- Local OS: ChromeOS
- Remote OS: Ubuntu 20.04
- Remote Architecture: amd64
- `code-server --version`: 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259

If I type some text in a file and then quickly press CTRL-S to save, it often deletes what I just typed and saves that.

**Comment by code-asher** [comment]
I experimented with this but I haven't been able to replicate. I'm not on ChromeOS though so maybe it has something to do with that.

Does this still happen without any extensions enabled? Does it happen to all file types or only some?

**Comment by ribrdb** [comment]
I turned off format on save, and that seems to have solved the problem. (Although now I have to remember to manually format).
I think I was mainly seeing it in typescript files using prettier for formatting.

**Comment by nhooyr** [comment]
Glad all is working!
