### ISSUE TITLE
Unbound breakpoint when debugging node using ts-node in vscode

### ISSUE THREAD

**Issue by rightisleft** [cdr/code-server#1968]
- Web Browser: Chrome
- Local OS: Max OS X
- Remote OS: Ubuntu 18.0.4
- Remote Architecture: Node / Docker 
- `code-server --version`: 
```
▶ code-server --show-versions
info  Using config file ~/.config/code-server/config.yaml
info  Using user-data-dir ~/.local/share/code-server
info  code-server 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259
```

Cross posting this as the node debugger in code-servers vscode core seems to be outdated

https://github.com/microsoft/vscode/issues/104526

----

- Version:
code-server: v3.4.1
VS Code: v1.45.1

- OS Version:
Ubuntu 18.0.4

Steps to Reproduce:

1. start a node docker container on port 4080 running via ts-node 
`node --inspect=0.0.0.0:9229 --preserve-symlinks -r ts-node/register src/server.ts` 
2. expose and attach a debugger to port 4080:9229
3. observe console logs and accurate binding of local to remote files
4. place a break point in model.ts and call corresponding api

Expected Results: It should stop on the breakpoint.
Actual Results: It stops on every js method in the stack

launch.json

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "address": "127.0.0.1",
            "name": "Attach to",
            "port": 4080,
            "request": "attach",
            "restart": false,
            "skipFiles": [
                "<node_internals>/**",
                "node_modules/**"
            ],
            "type": "node",
            "localRoot": "${workspaceFolder}/backend",
            "remoteRoot": "/app",
            "trace": true
        }
    ]
}
```
Where the debugger is actually stoping:
<img width="1792" alt="Screen Shot 2020-08-12 at 6 45 58 PM" src="https://user-images.githubusercontent.com/3611930/90075729-13b09480-dccc-11ea-9a8d-bf4b72698a39.png">

Note: the breakpoint for model.ts is Unbound

Logs available upon request

**Comment by nhooyr** [comment]
I'm confused, could you clarify whether this a VS Code bug or a bug in code-server?

**Comment by rightisleft** [comment]
@nhooyr - not sure. The vs-code folks said that they wanted to update to latest before diagnosing. When is the next update coming in?

**Comment by nhooyr** [comment]
Should be Monday!

**Comment by nhooyr** [comment]
Cool, glad all is working now.
