### ISSUE TITLE
Bearded Theme

### ISSUE THREAD

**Issue by 50l3r** [cdr/code-server#1971]
- [ ] Extension name: Bearded Theme
- [ ] Extension GitHub or homepage: https://github.com/BeardedBear/bearded-theme

Its an awesome theme ^^

**Comment by cmoog** [comment]
Thank you for your request! The extension is now live in the code-server extension marketplace.

**Comment by 50l3r** [comment]
I recieve this error when i try to install: 

`Unable to install 'beardedbear.beardedtheme' extension because it is not compatible with the current version of VS Code (version 1.45.1).`

**Comment by nhooyr** [comment]
Will be fixed when we update code-server to the next version of VS Code.

**Comment by nhooyr** [comment]
Which is already done, just need to cut a release.

**Comment by 50l3r** [comment]
Great. I'l wait impatiently.

Much thanks 4 all :D

**Comment by oxy** [comment]
Just tested - works again!
