### ISSUE TITLE
Payara Tools extension

### ISSUE THREAD

**Issue by humbertodias** [cdr/code-server#1972]
- [X] Extension name: Payara Tools
- [X] Extension GitHub or homepage: https://marketplace.visualstudio.com/items?itemName=Payara.payara-vscode

**Comment by humbertodias** [comment]
https://github.com/humbertodias/payara-ide/blob/master/Dockerfile
Line :25
```
ENV VSCODE_PAYARA_VERSION 0.0.4
RUN cd /opt \
    && curl -L https://github.com/payara/ecosystem-vscode-plugin/releases/download/${VSCODE_PAYARA_VERSION}/payara-vscode-${VSCODE_PAYARA_VERSION}.vsix -o payara-vscode-${VSCODE_PAYARA_VERSION}.vsix \
    && code-server --install-extension payara-vscode-${VSCODE_PAYARA_VERSION}.vsix \
    && rm payara-vscode-${VSCODE_PAYARA_VERSION}.vsix
```

I have installed manually and it works. But, if it were directly from UI, would be nicer. 
Thanks.

**Comment by cmoog** [comment]
Thank you for your request! The extension is now live in the code-server extension marketplace.
