### ISSUE TITLE
bind ipv6 address failed

### ISSUE THREAD

**Issue by zccold** [cdr/code-server#1973]
try binding  ipv6 address use "[::]:8080" and ":::8080" and failed.
What should I do to achieve what i want

    zc@ubuntu-server ~                                                                                           [13:16:29]
    > $ head -1 .config/code-server/config.yaml
    bind-addr: "[::]:8080"
    zc@ubuntu-server ~                                                                                           [13:16:29]
    > $ code-server
    info  Using config file ~/.config/code-server/config.yaml
    info  Using user-data-dir ~/.local/share/code-server
    info  code-server 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259
    error getaddrinfo ENOTFOUND [::]

    zc@ubuntu-server ~                                                                                           [13:17:54]
    > $ head -1 .config/code-server/config.yaml
    bind-addr: ":::8080"
    zc@ubuntu-server ~                                                                                           [13:17:59]
    > $ code-server
    info  Using config file ~/.config/code-server/config.yaml
    info  Using user-data-dir ~/.local/share/code-server
    error Invalid URL: http://:::8080

**Comment by code-asher** [comment]
Thanks for reporting! Let's track this in https://github.com/cdr/code-server/issues/1582.

In the meantime you can use `--host ::` as a workaround.
