### ISSUE TITLE
puppet-vscode extensions missing requirements

### ISSUE THREAD

**Issue by n0lr4m** [cdr/code-server#1974]
Hello,

In order to fully use the puppet.puppet-vscode extension the container need the following packages installed:

PDK version 1.5.0 or higher is required.
Puppet Agent 5.5 and above is preferred.

Reference: https://github.com/puppetlabs/puppet-vscode#requirements

- Web Browser:  chrome Version 84.0.4147.105 (Official Build) (64-bit)
- Local OS: Windows 10
- Remote OS: openshift
- Remote Architecture: x86
- `code-server --version`: 3.2.0-rc.6

**Comment by nhooyr** [comment]
Our container is intended to be a general base. Feel free to use the `FROM` docker instruction to create your own container based on ours.
