### ISSUE TITLE
NPM version getting old

### ISSUE THREAD

**Issue by mihailik** [cdr/code-server#1975]
Sorry if it's been requested before, but the <a href="https://www.npmjs.com/package/code-server">code-server npm package</a> is a little bit old now, wondering if it could be bumped?

Is there maybe something I can do to contribute to that please?

Many thanks!

**Comment by nhooyr** [comment]
It's the latest version. We haven't cut a new release yet.

**Comment by ihakh** [comment]
the latest python extension can not be installed in this version(1.45)
please release the (1.47) equivalent version

**Comment by mihailik** [comment]
It would be great!!

Totally understand you might have other priorities,  but maybe I can jump in and help somehow? I'd really love the latest VSCode cut in my code-server, please 🥺

You guys rock! Keep pushing it, good luck in all 👍

**Comment by code-asher** [comment]
I'm hoping to finish the 1.48 update today, maybe we can cut a release sometime soon after that.

**Comment by nhooyr** [comment]
[v3.5.0 with VS Code v1.48.2 has been released, fixing this issue!](https://github.com/cdr/code-server/releases/tag/v3.5.0) 🍻
