### ISSUE TITLE
Extensions missing

### ISSUE THREAD

**Issue by AlfaJackal** [cdr/code-server#1976]
Unfortunately my Extension List won't show me all extensions. Especially `remote ssh` is missing. Also recommended extensions, you can see it both in the screenshots.

I also tried it in docker, on a blank debian/ubuntu and in hassio as an add on (which is also docker). Why is that?

- Web Browser: Firefox
- Local OS: Windows
- Remote OS:
- Remote Architecture: Docker
- `code-server --version`: 3.4.1

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/blob/master/doc/FAQ.md#differences-compared-to-vs-code

We don't support certain extensions as Microsoft prohibits us from doing so.

**Comment by code-asher** [comment]
Related: https://github.com/cdr/code-server/issues/1315
