### ISSUE TITLE
vscode remote containers extension

### ISSUE THREAD

**Issue by JayDoubleu** [cdr/code-server#1977]
- [ ] Extension name:ms-vscode-remote.remote-containers
- [ ] Extension GitHub or homepage:https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

I would find so many use cases of this server when this works with docker :+1: 
This might be a dup: https://github.com/cdr/code-server/issues/1315

**Comment by nhooyr** [comment]
See #1315 

Microsoft won't let use add these extensions to code-server :(

https://github.com/cdr/code-server/blob/master/doc/FAQ.md#differences-compared-to-vs-code

**Comment by AntouanK** [comment]
@nhooyr :point_up:  page link is outdated, gives a 404 now

**Comment by jsjoeio** [comment]
@AntouanK I updated the link.
