### ISSUE TITLE
cannot install chrome extension

### ISSUE THREAD

**Issue by theraw** [cdr/code-server#1978]
- Web Browser: `Google Chrome Version 84.0.4147.125 (Official Build) (64-bit)`
- Local OS: `Windows 10`
- Remote OS: `Docker container codercom/code-server`
- Remote Architecture: `Linux`
- `code-server --version`: `3.4.1`

Is this a general problem with this chrome version and VS Code extension or is just me?!
before i already had vs code on my domain which i'm using currently so i did a reinstall of docker container delete/create,
I tried to open the "code-server" desktop icon that gets created when you click this
![image](https://user-images.githubusercontent.com/32969774/90448999-c9258280-e0e6-11ea-8cb4-85bbef45eb37.png)

i couldn't open IDE but i was like i opened a new chrome tab 😕  so i deleted that i also went to chrome extension folder and deleted all extensions there and i went to my domain where VS Code is running under nginx reverse proxy and i tried to install extension again but now when i click install the desktop icon of the extension is not being created... i click install nothing happens, also tried to open chrome dev console while i click "Install" no error i also tried `docker logs` theres also no error reported

Any idea what's wrong?!

**Comment by code-asher** [comment]
I tried this out on Windows 10 but I couldn't replicate. Here's what I did:
- Start 3.4.1 Docker container
- Browse to localhost:8080 and click the + icon
- A new app window opened displaying code-server and a desktop icon was created
- If I open the desktop icon a new app window displaying code-server opens

**Comment by theraw** [comment]
did you tried on latest chrome version?! if yes then since i don't have anything else like a error or log to provide you can close the issue,

it could also be the problem that i have multiple chrome releases installed on system like chrome, chrome-beta, canary, chromium 😕 so idk

**Comment by code-asher** [comment]
My version is `84.0.4147.135`. 

I just updated to `85.0.4183.83` and tried it out again but now it's not creating a desktop icon even though I deleted it and uninstalled the app. Once it launched I clicked the three dots then "uninstall coder". After that I was able to re-install and it added a desktop icon. 

Give that a try and see if it works for you!

**Comment by theraw** [comment]
the problem is that i cannot see the extension in chrome, i've also manually removed it since i didn't saw extension in chrome but even after that couldn't be able to install it again as i've already explain,

However since all what was needed is a install/reinstall i could clean chrome data and install it thanks for support

**Comment by bbrendon** [comment]
Sorry to bust in. Isn't the Chrome App version of VS Code supposed to be in a browser window  without bookmarks/tabs/URL bar? I thought that was the case and now I can't get it to work. I'm wondering if maybe I'm crazy and I made it up.

**Comment by bbrendon** [comment]
Okay I got it to work and I'm not crazy. I can't figure out how to make it work with the GUI but this did it. If someone knows how to do it with the GUI please do tell. And no, Installing "code-server" as an app using the Chrome browser doesn't work. It creates an icon on my desktop that loads a full browser (tab/url/bookmarks/etc).

`chrome.exe --app=https://vs.domain.com`

**Comment by code-asher** [comment]
I tried out the 3.5.0 Docker image with Chrome but using the `+` button to add code-server as a PWA is working for me. Maybe explicitly uninstalling it then re-installing it will help. I'm sorry I don't have something more helpful!

**Comment by bbrendon** [comment]
So after some trial and error I found the URL `chrome://apps`  . After uninstalling it there and then re-installing it. It works again.

**Comment by delve** [comment]
Just leaving this in case it helps the next person running into this behavior.
The org I work at is running code-server images on ephemeral servers for per-developer use. I've been running into issues registering new code-server instances as apps in Chrome every time my server expires and found this workaround to deal with it.
1. Clean out any existing code-server entries in chrome://apps (this may not be strictly necessary, but it's what I do)
2. Open the code-server URL in a normal tab
3. Open Chrome's 3 dot menu and select More tools... > Create shortcut...
4. In the small dialog that opens at the top of the window check the 'Open as window' box then 'Create'
Code-server is then properly registered in chrome://apps and opens in a bare window as expected.
