### ISSUE TITLE
when I use port forward in edge/chrome, I got `OFFLINE` page.

### ISSUE THREAD

**Issue by dongwangdw** [cdr/code-server#1979]
- Web Browser: edge/chrome
- Local OS: mac
- Remote OS: ubuntu 18.0
- Remote Architecture: amd64
- `code-server --version`: 0,34.1

![Screen Shot 2020-08-18 at 11 01 55](https://user-images.githubusercontent.com/2303377/90465595-44685200-e142-11ea-8920-9190ee77ddd5.png)

**Comment by dongwangdw** [comment]
It recovered after 2 hours. Is this a bug or something condfig issue?

**Comment by code-asher** [comment]
This happens whenever `navigator.onLine` reports false but in your case I'm not sure why it's doing that. But we're going to remove this check entirely so it shouldn't be a problem. Tracking for this here: https://github.com/cdr/code-server/issues/1925
