### ISSUE TITLE
non-italic-monokai Theme

### ISSUE THREAD

**Issue by Neos21** [cdr/code-server#1980]
- [x] Extension name: `neos21.non-italic-monokai`
- [x] Extension GitHub or homepage:
    - https://marketplace.visualstudio.com/items?itemName=Neos21.non-italic-monokai
    - https://github.com/Neos21/vscode-non-italic-monokai

**Comment by cmoog** [comment]
Thank you for your request! The extension is now live in the code-server extension marketplace.
