### ISSUE TITLE
Update the latest version of release

### ISSUE THREAD

**Issue by ppoak** [cdr/code-server#1985]
The python extension 2020.7.x cannot be used in the present 1.45.x version, while python extension 2020.6.x doesn’t work fine in this version of code-server.
Nodejs should also be updated and some other extensions aren’t compatible with this version of code-server.
At the same time, it’s been 3 moths since last release update, will there be any new version of release in the future? If yes, when will be released?

**Comment by nhooyr** [comment]
v3.5.0 has been released!
