### ISSUE TITLE
Extension request: vscode-textlint version 0.8.0

### ISSUE THREAD

**Issue by s2terminal** [cdr/code-server#1992]
- [x] Extension name: vscode-textlint
- [x] Extension GitHub or homepage: https://github.com/taichi/vscode-textlint

I found only version 0.7.0 in code-server marketplace, but I want to use the latest version.

### code-server (0.7.0)
![image](https://user-images.githubusercontent.com/7953751/90856198-62d98200-e3bc-11ea-8b62-723bd9b19229.png)

### VS Code (0.8.0)
![image](https://user-images.githubusercontent.com/7953751/90856490-fdd25c00-e3bc-11ea-8dc6-6e15e9b28f61.png)

**Comment by oxy** [comment]
Blocked right now - we need upstream to use GitHub releases and add `.vsix` files to them - building from upsteam has been unstable lately.
