### ISSUE TITLE
Extension request: mtxr.sqltools-driver-mysql, -mssql, -pg, -sqlite

### ISSUE THREAD

**Issue by karelbilek** [cdr/code-server#2008]
- Extension name: 

SQLTools MySQL/MariaDB

mtxr.sqltools-driver-mysql

and all other drivers (mssql, pg, sqlite)

- Extension GitHub or homepage:

https://github.com/mtxr/vscode-sqltools/tree/master/packages/driver.mysql

Note that the main extension mtxr.sqltools works and is there, just not the mysql driver (and other drivers)

**Comment by oxy** [comment]
Blocked right now - we need upstream to use GitHub releases and add `.vsix` files to them.
