### ISSUE TITLE
Extension request: ocamllabs.ocaml-platform

### ISSUE THREAD

**Issue by crackcomm** [cdr/code-server#2010]
- [ ] Extension name: OCaml Platform
- [ ] Extension GitHub or homepage: https://github.com/ocamllabs/vscode-ocaml-platform

**Comment by oxy** [comment]
Blocked right now - we need upstream to use GitHub releases and add `.vsix` files to them, so we can scrape them and add them to our marketplace.

**Comment by crackcomm** [comment]
It seems like it shouldn't be an issue from now on :smiley:
