### ISSUE TITLE
docs: Add example to demonstrate deployment on k8s along with a helm chart

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#2012]
This has been a heavily requested feature.

See https://github.com/cdr/code-server/issues/914

**Comment by Matthew-Beckett** [comment]
Hi @nhooyr!

I've just reviewed the original Helm chart commit and it needs minimal work to be current best practice, what is the plan for bringing the Helm chart back into the repository after it was removed? Is a new one being created or is the commit being cherry picked?

I am happy to submit an updated Helm chart for this issue if needed.

Thanks,
Matt

**Comment by nhooyr** [comment]
> I am happy to submit an updated Helm chart for this issue if needed.

Please go for it!

I'm not actively working on this but if you put up a solid PR, we can totally get it in for v3.5.1

**Comment by Matthew-Beckett** [comment]
@nhooyr would you be against my PR containing a cherry pick of the original merge commit supplemented with updates for Helm 3 compatibility and best practice improvements?

**Comment by nhooyr** [comment]
No, that sounds great :)

**Comment by hammady** [comment]
I see the PR is closed but not merged, any reason? I can help reviewing it.

**Comment by nhooyr** [comment]
ooo, we took care of this a while back! See the merged PR linked above.
