### ISSUE TITLE
globalState is not persisted across extension updates

### ISSUE THREAD

**Issue by Veetaha** [cdr/code-server#2021]
Our extension fails to work on code-server (https://github.com/rust-analyzer/rust-analyzer/issues/5892).
The problem is that we use [`globalState`](https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage). We expect the contents of `globalState` to persist across the extension version updates. Even though this is not mentioned in `vscode` API docs, but original `vscode` does persist it, but `code-server` doesn't.

For example we check for new nightly extension release and record it in `globalState` [like this](https://github.com/rust-analyzer/rust-analyzer/blob/8146700f82b75cd3cda5191108b4277a9908c744/editors/code/src/persistent_state.ts#L10-L18).
But when we [programmatically install the extension from VSIX](https://github.com/rust-analyzer/rust-analyzer/blob/8146700f82b75cd3cda5191108b4277a9908c744/editors/code/src/main.ts#L201) and reload the window, code-server clears the persistent storage.

# Meta
- Web Browser: `Google Chrome Version 84.0.4147.125 (Official Build) (64-bit)`
- Local OS: `Ubuntu 20.04.1 LTS`
- Remote OS: (idk, just running `code-server` on my local PC, so probably same as Local OS)
- Remote Architecture: `x86_64` my PC
- `code-server --version`: `3.4.1` 48f7c2724827e526eeaa6c2c151c520f48a61259

**Comment by nhooyr** [comment]
cc @code-asher

**Comment by code-asher** [comment]
I can replicate with:

```
await context.globalState.update("key", "value")
vscode.commands.executeCommand("workbench.action.reloadWindow");
```

I think that (in the web version of VS Code at least) the storage file isn't written to immediately but rather after a delay and reloading for some reason interrupts that delay causing it to never write (further supported by the fact that adding a 1s timeout around the reload makes it work).

Hopefully will be able to track down why the write gets canceled and get it fixed today.

**Comment by Veetaha** [comment]
Should we close this?

**Comment by code-asher** [comment]
Recently we've switched to closing the issues once a release with the fix goes out so let's leave it open for now!

**Comment by code-asher** [comment]
I think we're now closing the issues so we can tell how far the milestone has progressed so I'll go ahead and close this out.
