### ISSUE TITLE
Add a code command that mimics standard VS Code's code

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#2023]
See https://github.com/cdr/code-server/pull/2013#issuecomment-682199762

**Comment by shayne** [comment]
I'll start working on this soon.

**Comment by nhooyr** [comment]
@shayne You should know that if you'd be happy working on code-server full time, we're looking for someone right now!

https://jobs.lever.co/coder/e40becde-2cbd-4885-9029-e5c7b0a734b8?lever-origin=applied&lever-source%5B%5D=GitHub

**Comment by JammSpread** [comment]
I just use add this to ~/.bashrc
`
# Code Server
alias code='code-server'
`
then I execute `source ~/.bashrc`.

**Comment by JammSpread** [comment]
I just add this to `~/.bashrc`
```
# Code Server
alias code='code-server'
```
then execute `source ~/.bashrc`.

**Comment by JammSpread** [comment]
I'm currently mimicing that functionality with an alias. :D
