### ISSUE TITLE
Cannot find module '../../../lib/vscode/src/vs/server/ipc'.

### ISSUE THREAD

**Issue by samping** [cdr/code-server#2025]
when i run "npm run build"
the terminal show this error:
src/node/app/vscode.ts:15:8 - error TS2307: Cannot find module '../../../lib/vscode/src/vs/server/ipc'.

15 } from "../../../lib/vscode/src/vs/server/ipc"
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I find the vscode source ,it have not "server" fold?
please help me

**Comment by nhooyr** [comment]
Please read the contributing docs linked in the readme.
