### ISSUE TITLE
MongoDB Extention

### ISSUE THREAD

**Issue by HPaulson** [cdr/code-server#2028]
- [x] Extension name: MongoDB for VS Code
- [x] Extension GitHub or [homepage](https://marketplace.visualstudio.com/items?itemName=mongodb.mongodb-vscode)

**Comment by oxy** [comment]
Thanks for opening an extension request!
We are currently in the process of switching extension marketplaces and transitioning over to [Open VSX](https://open-vsx.org/).
Once https://github.com/eclipse/openvsx/issues/249 is implemented, we can fully make this transition. Therefore, we are no longer accepting new requests for extension requests. 

We suggest installing the VSIX file and then installing into code-server as a temporary workaround. See [docs](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#installing-vsix-extensions-via-the-command-line) for more info.
