### ISSUE TITLE
--enable-proposed-api flag attempts to start another instance of code-server

### ISSUE THREAD

**Issue by rabidpug** [cdr/code-server#2035]
--enable-proposed-api arg attempts to start another instance of code-server.

- Web Browser: Chrome
- Local OS: Arch Linux
- Remote OS: OSX
- Remote Architecture:  x86_64
- `code-server --version`: 3.5.0

**Comment by code-asher** [comment]
Yup, this is currently the expected behavior. We could change it though so if you run this while already inside code-server it'd enabled the proposed API for the current instance. Is this what VS Code does?
