### ISSUE TITLE
Allow opening files in existing code-server instance from a terminal outside code-server

### ISSUE THREAD

**Issue by rabidpug** [cdr/code-server#2036]
running code-server <file> attempts to start another instance of code-server instead of opening the file

Web Browser: Chrome
Local OS: Arch Linux
Remote OS: OSX
Remote Architecture: x86_64
code-server --version: 3.5.0

**Comment by code-asher** [comment]
Are you running it inside code-server's terminal? If you run it outside of code-server it'll just launch another instance. I think it'd be worth figuring out how to make this work in an external terminal too though.

**Comment by code-asher** [comment]
If you run it inside code-server's terminal and it still doesn't work (or if you're already running it in code-server's terminal) then could you run  `printenv VSCODE_IPC_HOOK_CLI` and see if it outputs anything for you?

**Comment by rabidpug** [comment]
Ahh, for whatever reason it wasn't set inside my tmux session, but it's working now, thanks for your help!
Would be good to be able to do it from an external terminal as well though :)

**Comment by nhooyr** [comment]
> Would be good to be able to do it from an external terminal as well though :)

Agreed!
