### ISSUE TITLE
Clicking on linter links browses you away to the URL instead of new tab / window

### ISSUE THREAD

**Issue by wbobeirne** [cdr/code-server#2040]
Clicking on a rule link in eslint (and I assume others) opens it in the same window as code-server. Ideally this would open in a new tab (in browser) or open it in a browser window (PWA).

![Screen Shot 2020-09-01 at 6 57 06 PM](https://user-images.githubusercontent.com/649992/91917405-6ce56580-ec85-11ea-9ea6-0e5b27be50c4.png)

- Web Browser: Chrome 84
- Local OS: macOS
- Remote OS: Ubuntu
- Remote Architecture:
- `code-server --version`: `3.5.0 de41646fc402b968ca6d555fdf2da7de9554d28a`

**Comment by nhooyr** [comment]
Nice catch!

**Comment by VinayChaudhari1996** [comment]
Yeah, same issue is with me , 

When I hit , 

Code-server ./path 

It opens in new tab of vs-code.

How to open it in browser ?

**Comment by code-asher** [comment]
@VinayChaudhari1996 If `./path` is a directory it should open in a new browser tab. If it's a file it'll open in a VS Code tab. There's no way to override that behavior currently.

**Comment by VinayChaudhari1996** [comment]
> @VinayChaudhari1996 If `./path` is a directory it should open in a new browser tab. If it's a file it'll open in a VS Code tab. There's no way to override that behavior currently.

1) Basically , I'm using code server inside docker container of npm app.

2) ./path : is a directly containing files ,

**Comment by code-asher** [comment]
Does it just never open at all? It might be getting blocked by the browser's popup blocker.

If that's not the case for you then could you be point me to the image or the Dockerfile so I can try it out?
