### ISSUE TITLE
Several extensions (incl python and bracket-pair-colorizer) don't seem to work with v3.50

### ISSUE THREAD

**Issue by vnijs** [cdr/code-server#2043]
I just upgraded to v3.5.0 and am noticing a number of extensions from the MS marketplace not working

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Ubuntu 20.04 in Docker
- `code-server --version`: 3.5.0

![image](https://user-images.githubusercontent.com/2998956/91935719-34ed1b00-eca3-11ea-8186-35b22eb42af2.png)

Package versions used are the latest on MS market place that all work with VSCode 1.48.2 and are all copied at the link below so they can be used when creating a docker container. The container is on dockerhub (vnijs/rsm-msba). 

https://github.com/radiant-rstats/docker-vsix

The docker file and relevant scripts etc. are available at the link below.

https://github.com/radiant-rstats/docker/tree/master/rsm-msba

**Comment by vnijs** [comment]
FYI Python 2020.7.1 does seem to work but the 2020.8.106424 version does not

https://marketplace.visualstudio.com/items?itemName=ms-python.python

**Comment by Talent30** [comment]
Same issue for Bracket Pair Colorizer 2

**Comment by code-asher** [comment]
See https://github.com/cdr/code-server/issues/2197 for the bracket plugin. I have not yet been able to debug the Python extension, although maybe https://github.com/cdr/code-server/issues/1837 is related.

**Comment by nhooyr** [comment]
Yup closing this issue, please follow along at #2197
