### ISSUE TITLE
Blurry/improper web assets/favicons

### ISSUE THREAD

**Issue by agneevX** [cdr/code-server#2044]
Favicons are blurry/non-retina.

<img width="191" alt="image" src="https://user-images.githubusercontent.com/19761269/91946441-e4b29f00-ed1c-11ea-8f89-51934e5798af.png">

Icons also look weird in Safari Favorites

<img width="139" alt="image" src="https://user-images.githubusercontent.com/19761269/91946913-07dd4e80-ed1d-11ea-849d-ccdeffcf098e.png">

Note the weird border and non-Retina icon. 

- Web Browser: Safari 13.1.2
- Local OS: macOS Catalina 10.15.6
- Remote OS: Raspberry Pi OS Debian Buster
- Remote Architecture: `armv7l`
- `code-server --version`: 
```
[2020-09-02T07:33:31.473Z] info  Using config file ~/.config/code-server/config.yaml
3.5.0 de41646fc402b968ca6d555fdf2da7de9554d28a
```

**Comment by agneevX** [comment]
How does this look?

![1*aAx4p0ZEF2pU60Vc8VIsFw-2](https://user-images.githubusercontent.com/19761269/91993080-97512480-ed52-11ea-8f26-66ca17e00bb2.png)

**Comment by code-asher** [comment]
My apologies, we let this one slip by. Thank you for opening the issue! We recently replaced the icon, lemme know if there are any problems with it!
