### ISSUE TITLE
Unable to install 'ms-ceintl.vscode-language-pack-zh-hans' extension 

### ISSUE THREAD

**Issue by Jesn** [cdr/code-server#2046]
- [ ] Extension name: Chinese (Simplified) Language Pack for Visual Studio Code

Unable to install 'ms-ceintl.vscode-language-pack-zh-hans' extension because it is not compatible with the current version of VS Code (version 1.41.1).

**Comment by gengchen528** [comment]
same problem

**Comment by KaneLeung** [comment]
same problem

**Comment by code-asher** [comment]
I'm seeing language installation problems with code-server 3.5.0, will investigate today.
