### ISSUE TITLE
code-server as a browser add-on

### ISSUE THREAD

**Issue by sergei3000** [cdr/code-server#2047]
Are there any plans to create browser add-ons/extensions/apps for popular browsers?

Could be a great option for the cases when users don't have sudo rights on their machines where they want to use code-server or where the operating system is not supported by code-server.

**Comment by code-asher** [comment]
We don't have any plans for a browser extension at the moment. Cloud you clarify what the extension would do? code-server would still need to run a backend which means an extension wouldn't help with operating system support.

It might be possible to run the backend in a browser one day but at the moment I don't think that's possible.

You should be able to run code-server as non-root already, by the way.
