### ISSUE TITLE
Default theme when no theme set is switched from dark to light

### ISSUE THREAD

**Issue by imrehg** [cdr/code-server#2052]
Seems like while vanilla VS Code and previous version of code-server had the dark theme as the default if no theme is set up in the `settings.json` file, the latest 3.5.0 release (with VS Code 1.48.2) switched this to light theme. Thus after upgrade by default the theme will be switched for people until they set a value.

- Web Browser: Chrome Version 85.0.4183.83 (Official Build) (64-bit)
- Local OS: MacOS Catalina 10.15.6
- Remote OS: Ubuntu 18.04
- Remote Architecture: x86_64
- `code-server --version`: `3.5.0 de41646fc402b968ca6d555fdf2da7de9554d28a`

**In current code-server**, checking the settings, for some reason the light theme is marked as default

<img width="395" alt="Screenshot 2020-09-03 at 13 19 46" src="https://user-images.githubusercontent.com/38863/92114134-45f37480-ede8-11ea-8abc-fc3da947c98b.png">

**In previous version** (code-server `3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259`) it was the dark:

<img width="368" alt="Screenshot 2020-09-03 at 13 21 27" src="https://user-images.githubusercontent.com/38863/92114833-6839c200-ede9-11ea-96d5-6644f46a5934.png">

**In vanilla VS Code** itself on MacOS, using the same version (1.48.2), the default is dark theme:

<img width="419" alt="Screenshot 2020-09-03 at 13 20 05" src="https://user-images.githubusercontent.com/38863/92114154-4db31900-ede8-11ea-891d-d079a7685497.png">

(or I'm guessing, since they appear to have a bug of not filling in `default` in the display, but that's not the relevant part of this report).

**Comment by imrehg** [comment]
Digging further, seems like it's not a code-server thing after all, see the latest master on `vscode`:

https://github.com/microsoft/vscode/blob/fda9471435f459d72624e5e5a385d0ffee8ee145/src/vs/workbench/services/themes/common/themeConfiguration.ts#L36

The confusing thing was that this change is not in the version that is tagged as 1.48.2:

https://github.com/microsoft/vscode/blob/a0479759d6e9ea56afa657e454193f72aef85bd0/src/vs/workbench/services/themes/common/themeConfiguration.ts#L36

thus I guess code-server pulled in a newer version than that tag for the release? Either way, seems like the report is the new normal.

**Comment by code-asher** [comment]
Ahh thanks for investigating this! I was also wondering about it.

**Comment by nhooyr** [comment]
VS Code team finally realized light theme > dark theme hahaha

For real though, I wonder if accessibility concerns are behind the change.
