### ISSUE TITLE
Fix $DOCKER_USER to use cp and not mv and only convert once

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#2056]
See https://github.com/cdr/code-server/discussions/2051

**Comment by sr229** [comment]
This is actually a bit trickier, if I remember my time with OpenShift, we can actually do that however, the shell script that is responsible for doing that has the username string fixed. I think we can try porting the user hack from Theia for OpenShift.

**Comment by nhooyr** [comment]
This is fixed by #2057
