### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by Milan12332567** [cdr/code-server#206]
Im having this error:

Docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown.

I am first time docker use so i really dont know what is wrong.

I installed docker using apt command

**Comment by kylecarbs** [comment]
https://github.com/docker/for-linux/issues/595 seems to be a tracking issue.

**Comment by nhooyr** [comment]
I don't believe this is a code-server issue. Feel free to reopen if you believe it is.
