### ISSUE TITLE
Extension Request: Dendron

### ISSUE THREAD

**Issue by issmirnov** [cdr/code-server#2066]
- [X] Extension name: Dendron
- [X] Extension GitHub or homepage: https://github.com/dendronhq/dendron
- [X] Extension Visual Studio Link: https://marketplace.visualstudio.com/items?itemName=dendron.dendron

**Comment by issmirnov** [comment]
Note: After setting up `/etc/systemd/user/code-server.service.d/override.conf` with:

```
[Service]
Environment=SERVICE_URL=https://open-vsx.org/vscode/gallery ITEM_URL=https://open-vsx.org/vscode/item
```

so that I could hit https://open-vsx.org/, I got the following error:

![image](https://user-images.githubusercontent.com/5771615/92319387-65e38d80-efcc-11ea-8b72-a038d895b024.png)

I'm not sure what VScode version code-server uses under the hood.

**Comment by cmoog** [comment]
Thanks for bringing this to our attention. Unfortunately, we do not have the ability to update extensions posted to the `open-vsx` registry. 

To view the VSCode version used in your current version of `code-server`, navigate to the `Help -> About` menu.

**Comment by cmoog** [comment]
Regarding including the extension in the default `code-server` marketplace, the best course of action is to request that the publisher include bundled `.vsix` artifacts in their Github Releases.

**Comment by kevinslin** [comment]
have updated dendron to be compatible with code server in the latest release (0.10.5). this issue should be safe to close
