### ISSUE TITLE
code-server in docker can't install any extensions

### ISSUE THREAD

**Issue by B8kingS0ga** [cdr/code-server#2069]
- Web Browser: Chrome, Edge
- Local OS: Windows10
- Remote OS:  Linux
- Remote Architecture: amd64
- `code-server --version`: 3.5.0 de41646fc402b968ca6d555fdf2da7de9554d28a

every time try to install extension from the extensions library, got error toast
![image](https://user-images.githubusercontent.com/58551958/92431496-42863180-f1ca-11ea-83ba-dfcd1dc6eabb.png)

**Comment by code-asher** [comment]
Could you post the logs (https://github.com/cdr/code-server/blob/v3.5.0/doc/FAQ.md#how-do-i-debug-issues-with-code-server). In particular the browser console and extension host logs.

**Comment by jylenhof** [comment]
I had to restart the container to make the extension available....
Looking if there's a way to do it without this restart !

**Comment by code-asher** [comment]
Installing extensions currently requires reloading the page but they
shouldn't require restarting the whole container.

**Comment by nhooyr** [comment]
Should be fixed in the latest release.
