### ISSUE TITLE
Can't unbind some keys

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#2079]
`F10` is bound to `Step Over` but it doesn't work because it's bound to `Focus Application Menu`. Rebinding `Focus Application Menu` just creates a new keybinding instead of changing the default so there's no way to work around this currently.

See https://github.com/cdr/code-server/discussions/2070 for more details.

**Comment by code-asher** [comment]
I think there are others that can't be removed either, like `F1` to show the command palette.

**Comment by tuanpham-dev** [comment]
For now, to make F10 works for `Step Over`, you can patch file `<code-server>/lib/vscode/out/vs/workbench/workbench.web.api.js`, search for `{primary:68` and replace with `{primary:0`. Here is my command to patch it:

**Comment by WhitCrow** [comment]
> 
> 
> For now, to make F10 works for `Step Over`, you can patch file `<code-server>/lib/vscode/out/vs/workbench/workbench.web.api.js`, search for `{primary:68` and replace with `{primary:0`. Here is my command to patch it:
> 
> ```shell
> sudo sed -i 's/{primary:68/{primary:0/g' /usr/lib/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js
> ```

i dont find th `/lib/vscode` folder

**Comment by tuanpham-dev** [comment]
> i dont find th `/lib/vscode` folder

It's in code-server folder which is `/usr/lib/code-server` in my case.

**Comment by WhitCrow** [comment]
> 
> 
> > i dont find th `/lib/vscode` folder
> 
> It's in code-server folder which is `/usr/lib/code-server` in my case.

Its working，Thanks

**Comment by StephanieHerd** [comment]
Is there an ETA on this bug? Thank you.

**Comment by code-asher** [comment]
Not yet, we haven't made any plans to work on it especially since it
might make more sense to fix it upstream.

**Comment by StephanieHerd** [comment]
Thanks for the quick response. I understand I guess the temporary fixed posted above would be ok for now. Cheers.

**Comment by raul87011523** [comment]
Hello, I found a solution

-  Go to File/Preferences/Keyboard Shortcuts.
-  Click on 'Open Keyboard Shortcuts (JSON)' icon.
-  Paste the nest code:

```
[
    {
        "key": "f10",
        "command": "-workbench.actions.menubar.focus",
        "when": "isWeb"
    },
    {
        "key": "f10",
        "command": "",
        "when": "isWeb"
    },
    {
        "key": "f10",
        "command": "extension.node-debug.startWithStopOnEntry",
        "when": "!inDebugMode && debugConfigurationType == 'node'"
    },
    {
        "key": "f10",
        "command": "workbench.action.debug.stepOver",
        "when": "debugState == 'stopped'"
    }

]
```

- Press F5 to refresh the browser

Example ilustrated:

![image](https://user-images.githubusercontent.com/29439123/110570504-41709580-8156-11eb-8f15-96857af756e4.png)

![image](https://user-images.githubusercontent.com/29439123/110570742-b6dc6600-8156-11eb-804f-ef5a8d3a2bfc.png)

![image](https://user-images.githubusercontent.com/29439123/110571310-aaa4d880-8157-11eb-8430-fab0a0dfce36.png)

**Comment by binary-person** [comment]
im a year late to the party, but the issue still persists. The actual keybinding change works, but you need to refresh your browser every time you change a keybinding for changes to take effect

**Comment by jsjoeio** [comment]
@binary-person do you mind opening up a bug report for that?

**Comment by binary-person** [comment]
sure! #4673
