### ISSUE TITLE
Up to date Extensions with simple tools

### ISSUE THREAD

**Issue by und3fined** [cdr/code-server#2082]
Hi team and every one,

I'm make a minimal tools for update extensions to latest version from MS Server
Source code from here: https://github.com/und3fined/code-server-extensions

It's download vsix file from MS, and install via command `code-server --install-extension`

Do you like it?

- <img src="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/144/apple/237/thumbs-up-sign_1f44d.png" alt="+1" width="16" height="16" /> for like

- <img src="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/144/apple/237/white-medium-star_2b50.png" alt="star" width="16" height="16" /> for love

Thanks.

**Comment by code-asher** [comment]
Thanks for sharing. Keep in mind that this is technically a violation of Microsoft's terms of service (https://github.com/cdr/code-server/blob/master/doc/FAQ.md#differences-compared-to-vs-code) so we wouldn't be able to include this with code-server.
