### ISSUE TITLE
no precompiled binary for armv8l

### ISSUE THREAD

**Issue by djdisodo** [cdr/code-server#2088]
aarch64 binary will work on armv8l
![image](https://i.ibb.co/hR5KWpc/photo-2020-09-12-22-22-40.jpg)

**Comment by sr229** [comment]
if I remember we do have a arm64 image already - but for 32-bit compiling for ARMv8L is going to be a bit tricky since we do need to perform cross-compilation but it tends to be impossible sometimes because the compile goes over the 4GB limit.

**Comment by code-asher** [comment]
I'm not super familiar with all these arm versions but it seems armv8 has 64 bit support? So we just need to modify the script to download the arm64 release if the architecture reports armv8l instead of erroring out?

**Comment by sr229** [comment]
> I'm not super familiar with all these arm versions but it seems armv8 has 64 bit support? So we just need to modify the script to download the arm64 release if the architecture reports armv8* instead of erroring out?

armv8l is always 64-bit they just have a 32-bit mode similar to x86 @code-asher. The only way I see this working is if we point Node.js to use Android NDK and build a arm binary from that.

**Comment by nhooyr** [comment]
Yes the install script just needs to be modified to return the aarch64 binary.
