### ISSUE TITLE
chrome use code-oss  crash! 

### ISSUE THREAD

**Issue by au-top** [cdr/code-server#2092]
Accidental page crash 
There are no signs before the crash 
Sometimes it will crash during use ?
Is this caused by the memory limitation in Chrome 
How to increase its memory limit max?

If he happens again, I'll make up the screenshot

- Web Browser: chrome-85.0.4183.83-64bit   
- Local OS: linux-debian10-amd64
- Remote OS: linux-debian9.9-x86_64
- Remote Architecture:
- `code-server --version`: v3.5.0 ( VS Code v1.48.2 )

**Comment by code-asher** [comment]
See if you can get some debug logging too! https://github.com/cdr/code-server/blob/v3.5.0/doc/FAQ.md#how-do-i-debug-issues-with-code-server

**Comment by code-asher** [comment]
I'm not sure if you can get the console logs when the page crashes though, so you might have trouble there. I'm also not sure if there's a way to increase Chrome's memory limit but it might be a good idea to monitor the tab with Chrome's task manager to see how the memory usage goes. https://developers.google.com/web/tools/chrome-devtools/memory-problems/

**Comment by sr229** [comment]
I tested on a 4GB VM and I couldn't replicate this issue - both Chromium and Chrome, I don't think it's a memory issue. 

@auto-p Your bug report is not detailed enough, can you gather logs for us just like asher instructed?

**Comment by auto-p** [comment]
Today, code-server had a problem again. The chrome error code is 15
Unable to get browser console information when crash, this does not seem to be caused by memory
At that time, I opened two code server pages, and they both had code is 15 error. Is this related to the network ?
At the time of the crash, I was continuously typing characters. Is it related to the code prompt function ?
Where can I get the running log of code server client
Chrome version 85.0.4183.102 (official version) (64 bit)

**Comment by sr229** [comment]
@auto-p It's still not enough data - please send us debugging logs since we can't replicate it under your specified conditions.

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by auto-p** [comment]
I don't understand how to debug unpredictable crashes. After a crash, chrome switches pages to crash pages. How do I collect information？

**Comment by code-asher** [comment]
There might be some information from the logs indicated in https://github.com/cdr/code-server/blob/v3.5.0/doc/FAQ.md#how-do-i-debug-issues-with-code-server but I'm not sure they'll show anything in this case.

Since the page crashes I think you're right that you can't collect any information from the browser console though. Well, there's a "preserve log" option but I'm not sure it's able to preserve between crashes. But I think you can launch Chrome with the `--enable-logging` flag. See https://www.chromium.org/for-testers/enable-logging.

**Comment by nhooyr** [comment]
Please let us know if you still experience this in the latest release.
