### ISSUE TITLE
copy/paste issues

### ISSUE THREAD

**Issue by Simon8912** [cdr/code-server#2094]
- Web Browser: Firefox
- Local OS: Windows 10
- Remote OS: Linux ubuntu 20.04
- Remote Architecture: Rancher 
- `code-server --version`: code-server: v3.5.0

The paste command is not working. I can copy a line from the workspace ,but I can't copy it nowhere else. Also the copy/paste is not working in the terminal . Is this a bug? Is there a way to get around this problem? The code-server is runing on a ubuntu server with docker-Kubernetes-rancher.

**Comment by code-asher** [comment]
There are some issues with pasting in Firefox. See here for some potential workarounds: https://github.com/cdr/code-server/issues/1106

**Comment by mirekphd** [comment]
One reproducible situation when paste stops working (in v4.14.0 with Code 1.79.2) is when you copy a file in the file Explorer (using Copy from the mouse right-click menu or Ctrl+C) and from now on the copied path is the only string that can be pasted in the editor until Ctrl+R is hit to reload the Code Server page is reloaded as a workaround). Pasting in the terminal (with Shift+Insert) continues to works fine though.
