### ISSUE TITLE
Extension request: Draw.io VS Code Integration

### ISSUE THREAD

**Issue by MarcusLlewellyn** [cdr/code-server#2117]
- [ ] Extension name: hediet.vscode-drawio
- [ ] Extension GitHub or homepage: https://github.com/hediet/vscode-drawio

Additional notes:

It looks like someone has requested this from the author of the extension at https://github.com/hediet/vscode-drawio/issues/110

It also looks like someone other than the author has attempted to publish this extension, and then unpublished it. See the above issue URL for details.

**Comment by TristanBrotherton** [comment]
Another vote here.

**Comment by TristanBrotherton** [comment]
@MarcusLlewellyn were you ever able to get the other version of the extension running in code-server ?
