### ISSUE TITLE
Cloudron Support

### ISSUE THREAD

**Issue by mitchellurgero** [cdr/code-server#212]
I built a Cloudron image for anyone willing to test it: https://github.com/mitchellurgero/cloudron-vscode

For those that do not know what cloudron is: https://cloudron.io

**Comment by NGTmeaty** [comment]
@nhooyr what would you think about adding this to the [wiki](https://github.com/codercom/code-server/wiki/Deployment)?

**Comment by sr229** [comment]
+1, merits a Third party entry.

**Comment by nhooyr** [comment]
Feel free to add it yourself, the wiki should be editable by everyone.

**Comment by mitchellurgero** [comment]
@nhooyr Unfortunately I cannot edit the wiki.

**Comment by nhooyr** [comment]
Unfortunately this doesn't seem to be a feature requested by users.
