### ISSUE TITLE
Allow multiple plugins to be specified

### ISSUE THREAD

**Issue by wbobeirne** [cdr/code-server#2122]
`PLUGIN_DIR` only accepts a single directory, so if we were to have multiple plugins, we could only choose to use 1 at a time. We could either just split on comma, have the variable accept a JSON array, or change it to a flag that can be specified multiple times (e.g. `--plugin /path/to/plugin1 --plugin /path/to/plugin2`)

**Comment by code-asher** [comment]
fwiw `PLUGIN_DIR` was actually just for development, the original plan was that plugins would be in the `plugins` directory inside th code-server directory. So we could have a flag that sets that directory, or extract plugins to that directory when downloading everything without setting any variables.

**Comment by code-asher** [comment]
It should def be made configurable, not just hardcoded to `plugins` like it currently is.
