### ISSUE TITLE
NGINX 502 Bad Request suddenly without changing anything?

### ISSUE THREAD

**Issue by AlaaElrifaie** [cdr/code-server#2124]
- Web Browser: All on Windows & Android
- Local OS: Windows/Android
- Remote OS: Ubuntu 18.04
- Remote Architecture: amd64
- `code-server --version`: 3.5.0

I tried installing Code Server v3.5.0 a few weeks ago and I encountered this same exact issue, then I gave up and forgot about it. After a few days I decided to try again and then it worked (same config "NGINX as a reverse proxy" but idk how it worked this time). But it was only working on my laptop, not from my Android device. A few days later, I came to my Code Server setup just to find out that it happened again.

### The problem
The page doesn't load properly and when I check the console I see 502 bad request errors. (Screenshot).
![image](https://user-images.githubusercontent.com/9083864/93880397-18faf900-fce6-11ea-8c6b-cf171f8ebd96.png)

My setup is the same recommended NGINX one in the official guide on a AWS EC2 instance.

**Comment by marissa999** [comment]
When you are in the same network as your code-server installation, can you access code-server directly (through the ip/hostname and the port? Might require quickly open the port for code-server to test this, or ssh-forwarding should work too?)
What do the nginx logs say?
If code-server and nginx are running on different machines/container, are you able to ping the code-server machine from the nginx-machine?

Does would be the first 3 things I would try or look at.
