### ISSUE TITLE
Official Svelte extension outdated (still in Beta)

### ISSUE THREAD

**Issue by oguzgelal** [cdr/code-server#2126]
Hello. Below extension *is* available in code-server marketplace, but it's an outdated version (it's still in Beta). Could we have it updated ? Thank you.

- [ ] Extension name: Official Svelte Extension
- [ ] Extension on VSCode Marketplace: https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode
- [ ] Extension on GitHub: https://github.com/sveltejs/language-tools/tree/master/packages/svelte-vscode

**Comment by cmoog** [comment]
Thank you for your request! The extension is now live in the code-server extension marketplace.

**Comment by oguzgelal** [comment]
Thank you @cmoog!
