### ISSUE TITLE
Add documentation for updating / upgrading an existing installation of code-server

### ISSUE THREAD

**Issue by wbobeirne** [cdr/code-server#2131]
We don't have anything in README.md, install.md, or FAQ.md on how this is done.

**Comment by snazzybunny** [comment]
I’d like this as well so we can preserve settings and extensions. Thanks!

**Comment by nhooyr** [comment]
@snazzybunny You just reinstall. Settings and extensions are stored separately and maintained between installs.

**Comment by nhooyr** [comment]
Done in one of the recent documentation update PRs. The release notes also mention how to upgrade now.
