### ISSUE TITLE
Add help information to the extension search view

### ISSUE THREAD

**Issue by cmoog** [cdr/code-server#2132]
Show a yellow or red call to action in the extension search view informing the user of all alternative extension installation methods.

**Comment by jsjoeio** [comment]
@cmoog 

I read the discussion around your previous PR that attempted to solve this: https://github.com/cdr/code-server/pull/2185

Are we okay adding a similar message to the UI like you were planning or do you want to hold off until our extension marketplace is open source (if we move in that direction)?

**Comment by jsjoeio** [comment]
Spoke to @cmoog over Slack:

> So it’s probably the case that, at this point, anything in the UI would be a big improvement from the current state. Possibly a link to open-vsix or even just a warning that the extensions are not official with a link to the code-server FAQ
> But fair warning that any reference to using the MSFT marketplace assets is probably against TOS.

I'm going to brainstorm some ideas and then I'll work on this.

**Comment by jsjoeio** [comment]
Okay here's what I came up with.

<img width="1268" alt="Issue 2132(1)" src="https://user-images.githubusercontent.com/3806031/102667938-e9725600-4147-11eb-9920-9a42b840bce6.png">


Message to user:

> Warning: These extensions are not official. Find open-source extensions [here](https://open-vsx.org/). See [docs](https://github.com/cdr/code-server/blob/v3.8.0/doc/FAQ.md#how-can-i-request-a-missing-extension).

I should be able to open a PR for this next week.

**Comment by jsjoeio** [comment]
Closing via #2501
