### ISSUE TITLE
Haskell Syntax Highlighting is missing from the code-server marketplace

### ISSUE THREAD

**Issue by invakid404** [cdr/code-server#2138]
- [ ] Extension name: Haskell Syntax Highlighting
- [ ] Extension GitHub or homepage: https://github.com/JustusAdam/language-haskell/

**Comment by invakid404** [comment]
The extension in question is a dependency of other Haskell-related extensions, such as Haskelly, meaning they're unusable right now. I suspect there might be other missing dependencies, so it's worth taking a look ^

**Comment by miuirussia** [comment]
yes, can confirm, that official Haskell extension not appear too:
https://marketplace.visualstudio.com/items?itemName=haskell.haskell

because it depends this: 
https://marketplace.visualstudio.com/items?itemName=justusadam.language-haskell
