### ISSUE TITLE
Extension update request: Bracket Pair Colorizer 2

### ISSUE THREAD

**Issue by ntimo** [cdr/code-server#2155]
- [ ] Extension name: Bracket Pair Colorizer 2
- [ ] Extension GitHub or homepage: https://github.com/CoenraadS/Bracket-Pair-Colorizer-2

Additional info:
current the code server marketplace serves version 0.0.28 while the GitHub repo and vscode marketplace is at version 0.2.0.

**Comment by Talent30** [comment]
Bracket Pair Colorizer 2 does not work on code-server 3.5.0.

**Comment by cmoog** [comment]
Thanks for reporting this. It looks like the publisher has stopped updated the public Github repo. I've updated the extension version on the code-server extension marketplace to match the latest version on Github.
