### ISSUE TITLE
Gitea Extension for Visual Studio

### ISSUE THREAD

**Issue by Dhy19971** [cdr/code-server#2162]
- [ ] Extension name: Gitea Extension for Visual Studio
- [ ] Extension GitHub or homepage: https://github.com/maikebing/Gitea.VisualStudio

**Comment by ntimo** [comment]
This is not going to work since this is a Visual Studio extension and not a VSCode extension if I am correct.

**Comment by Dhy19971** [comment]
https://marketplace.visualstudio.com/items?itemName=ijustdev.gitea-vscode#overview

this should be ok .. and i guess it's the usual thing .. it's explicitly written `` Gitea Issue Tracker for vs-code ''

**Comment by nhooyr** [comment]
The correct repo is https://github.com/IJustdev/Gitea-VSCode

**Comment by cmoog** [comment]
Thank you for your request! The extension is now live in the code-server extension marketplace.
