### ISSUE TITLE
Code-server - Frequent reconnect messages

### ISSUE THREAD

**Issue by brettplarson** [cdr/code-server#2163]
- Web Browser: Chrome
- Local OS: Ubuntu 20.04
- Remote OS: Amazon Linux
- Remote Architecture: Kubernetes pod running Code-server in EKS
- `code-server --version`: 3.4.1 993fd4eaac4b6742b7b36b31b33fa3da8a1087a3

Hello,
We are using Code-server in our environment and we are frequently seeing the error "Attempting to reconnect in X seconds..."

![image](https://user-images.githubusercontent.com/33815371/95223317-0e992e80-07bf-11eb-937e-e47dd970310b.png)

From the developer tool logs we are seeing:

```
INFO [remote-connection][ExtensionHost][46135…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:185 INFO [remote-connection][ExtensionHost][46135…][reconnect] waiting for 5 seconds before reconnecting...
log.ts:185 INFO [remote-connection][Management ][3c859…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
log.ts:185 INFO [remote-connection][Management ][3c859…][reconnect] waiting for 5 seconds before reconnecting...
log.ts:185 INFO [remote-connection][ExtensionHost][46135…][reconnect] resolving connection...
log.ts:185 INFO [remote-connection][ExtensionHost][46135…][reconnect] connecting to [ourendpoint.com:80...]
```

It seems like our connection from our VPN may be spotty. I understand that similar issues have been closed in the past as this is not a codehub issue.

However It would be nice to not block the screen and interrupt user's work if this resolves itself after 1 second.

Is there a setting we can tune to adjust the timeout? Or suppress this popup somehow?

Please let me know,
Thank you!

**Comment by nhooyr** [comment]
Hi @brettplarson, please follow along at https://github.com/cdr/code-server/issues/1791 for updates on this feature.
