### ISSUE TITLE
UI bug: Overflowing text in Jupyter notebook prompt box

### ISSUE THREAD

**Issue by dorukkarinca** [cdr/code-server#2166]
Text prompts are overflowing in the Jupyter notebook view. The text in it is not selectable and the links in it are not clickable.

- Web Browser: Chrome
- Local OS: Linux
- Remote OS: Linux
- Remote Architecture: x64
- `code-server --version`: 3.5.0 (vscode 1.48.2)

To reproduce the issue:
1. Run a ColabCode instance in [Google Colab](https://colab.research.google.com/notebooks/empty.ipynb)
```
!pip install colabcode
from colabcode import ColabCode
ColabCode(port=10000, password="asdf")
```

2. Create an .ipynb file and run a cell that posts a long link into the prompt:
```
!pip install kora
from kora import drive as koradrive
koradrive.chdir_notebook()
```
3. Observe the textbox overflow (screenshot below).

![image](https://user-images.githubusercontent.com/9303867/95320014-817ad600-08a1-11eb-8fd4-38503f4afa45.png)

**Comment by dorukkarinca** [comment]
Any updates on this? I'd like to help in any way I can

**Comment by code-asher** [comment]
I tried to run this with 3.7.3 to see if it's still an issue with the
latest VS Code but the Jupyter extension keeps giving me problems.

Assuming it is still a problem I imagine it just needs some CSS
somewhere to make it wrap properly.

**Comment by dorukkarinca** [comment]
I think you are referring to #2341 which should be resolved before we can resolve this issue.
