### ISSUE TITLE
File deletion prompt is issued twice

### ISSUE THREAD

**Issue by schmidDan** [cdr/code-server#2168]
- Web Browser: Firefox 81.0.1 (64-Bit)
- Local OS: MS Windows 10 WSL2 Docker Desktop 2.3.05 (48029)
- Remote OS: Custom Docker Container (`ubuntu:20.04`-based, calling `RUN curl -fsSL https://code-server.dev/install.sh | sh`)
- Remote Architecture: see above + ssh port forwarding
- `code-server --version`: 3.5.0 de41646fc402b968ca6d555fdf2da7de9554d28a
- Cannot be reproduced in vanilla VS Code

# File deletion prompt is issued twice

## Problem Description

If I try to delete a file, I'm issued with two dialogue windows beneath each other (to be deleted is the `my_test.file` shown opened in the editor as well as in left sidebar):

![DeleteOnce](https://user-images.githubusercontent.com/22459026/95363725-20b6c200-08d0-11eb-8cad-4d8a723d9cc7.PNG)

The first dialogue is already sufficient to delete the file (as one can tell from the left sidebar showing the `my_test.file` no more). It's definitely two windows popping up beneath each other, because by closely looking while pressing the "Delete" button within the first window and seeing the window vanishing afterwards, one can tell that the shadows around the window's border got more transparent. As well, the `my_test.file`, which was opened in the editor beforehand is gone and the welcome page is shown:

![DeleteStillIssued](https://user-images.githubusercontent.com/22459026/95363751-28766680-08d0-11eb-9fe5-b03033ee6dc3.PNG)

The second dialogue is non-funcitonal (file was already deleted - deleting once again gives an error):

![WasDeletedAlready](https://user-images.githubusercontent.com/22459026/95363769-2dd3b100-08d0-11eb-9d22-e63a779f7a8d.PNG)

## Steps to reproduce

* Start a  `code-server`
* Connect to `code-server`
* Create a file
* Ctrl+Right-click the file in the side tab
* Choose "Delete Permanently"
* There we are!

## Additional data
I attached the stdout of the `code-server` process. If requested, I can as well provide the stripped down `Dockerfile` etc..

[code-server-stdout.txt](https://github.com/cdr/code-server/files/5342480/code-server-stdout.txt)

**Comment by code-asher** [comment]
The update to VS Code 1.51.1 appears to have resolved this. Will be in the next release.
