### ISSUE TITLE
agda-mode

### ISSUE THREAD

**Issue by glangmead** [cdr/code-server#2177]
- [ ] Extension name: agda-mode
- [ ] Extension GitHub or homepage: https://github.com/banacorn/agda-mode-vscode

Worked OK when I installed it from VSIX

**Comment by oxy** [comment]
Thanks for opening an extension request!
We are currently in the process of switching extension marketplaces and transitioning over to [Open VSX](https://open-vsx.org/).
Once https://github.com/eclipse/openvsx/issues/249 is implemented, we can fully make this transition. Therefore, we are no longer accepting new requests for extension requests. 

We suggest installing the VSIX file and then installing it via the code-server CLI as a temporary workaround. See [docs](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#installing-an-extension) for more info.
