### ISSUE TITLE
Symfony plugin

### ISSUE THREAD

**Issue by Defcon0** [cdr/code-server#2178]
Hello,

at first thanks for the awesome project. We just installed it and it worked like a charm. Only the the symfony plugin is missing.

- [ ] Extension name: Symfony for VSCode
- [ ] Extension GitHub or homepage: https://github.com/TheNouillet/symfony-vscode

Thanks in advance!

**Comment by cmoog** [comment]
Thank you for your request! The extension is now live in the code-server extension marketplace.
