### ISSUE TITLE
Update to 1.5 for flame chart support

### ISSUE THREAD

**Issue by yorrd** [cdr/code-server#2188]
VSCode just released [flame charts in the node debugger](https://code.visualstudio.com/updates/v1_50#_debug-console-filter-improvements), which I would absolutely love to use. Any plans on updating the underlying version of VSCode any time soon? 😄 

have a wonderful day

**Comment by code-asher** [comment]
We're planning on having 1.50.0 in 3.6.1, hopefully this week.

**Comment by yorrd** [comment]
Lovely, thanks! Looking forward to it

**Comment by nhooyr** [comment]
@code-asher merged #2204 so closing this. Release looks good for friday.
