### ISSUE TITLE
Reconnecting after pasting text

### ISSUE THREAD

**Issue by arkjxu** [cdr/code-server#2189]
Hi All,

First time code-server user here.  Recently installed on AWS Ubuntu 20 for my team to WFH.
Upon Pasting text ~30 lines, the page will result in **attempting to reconnect**...

This happens everytime without exception.

I heard this might be extensions, however, the only extension we've installed is Material Theme & Material Icons.

- Web Browser: Chrome, Safari
- Local OS: MacOS Mojave
- Remote OS: AWS Ubuntu 20
- Remote Architecture: x86 - t3.nano
- `code-server --version`: latest

**Comment by nhooyr** [comment]
Hey @arkjxu sorry for the late response. Can you update the issue with the precise version being used and also test the latest? Might be fixed. We've made significant changes to the HTTP layer in recent months.

**Comment by arkjxu** [comment]
Version: 3.6.2

I upgraded the version to  3.7.4, seems like it's fixed now

**Comment by nhooyr** [comment]
Awesome!
