### ISSUE TITLE
Can't copy to clipboard from interactive Python window

### ISSUE THREAD

**Issue by jtilly** [cdr/code-server#2194]
There are several copy+paste issues, but I couldn't find one for this. Please close if this is a duplicate.

I'm using code-server for Python development. As of code-server 3.5, I can't copy _from_ the interactive Python window (neither the command box nor the output). This worked fine with code-server 3.4.*. Pasting _into_ the interactive window works with `Ctrl + Shift + v` (it used to be `Ctrl + v`). Copying from the interactive window doesn't appear to work at all (or maybe I just don't know the new keyboard shortcut? 😉 )

Downgrading the Python extension doesn't help. I have no issues with this when running VSCode directly, so I don't think it's the Python extension.

Any idea what may have caused this change?

- Web Browser: Chrome
- Local OS: Ubuntu and Windows
- Remote OS: Ubuntu
- Remote Architecture: x64
- Python Extension: `2020.9.114305`, `2020.9.112786`, ...
- `code-server --version`: `3.6.0 a4a03c14922ccaec2a9ff8d1b7b2af8522a4214d` same issue with `3.5.0`.

**Comment by jtilly** [comment]
My bad. It's just the key bindings that changed. Pasting in the interactive window works with `Ctrl + Insert`.

**Comment by code-asher** [comment]
I think there still might be a bug here because ctrl+c should also work,
at least it works in VS Code (as you also noticed).

**Comment by jtilly** [comment]
Ctrl + C and Ctrl + V is working again with version 3.8 and python extension v2020.12.424452561.
