### ISSUE TITLE
Package with node_modules.asar

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#2197]
Currently we patch `require` to use `node_modules` but this breaks if an extension explicitly tries to look in `node_modules.asar` like the bracket pair colorizer plugin:

```
Activating extension 'CoenraadS.bracket-pair-colorizer-2' failed: ENOENT: no such file or directory, open '/usr/lib/code-server/lib/vscode/node_modules.asar/vscode-oniguruma/release/onig.wasm'. _logMessageInConsole @ abstractExtensionService.ts:416
```

We should package `code-server` with that directory.

**Comment by code-asher** [comment]
Maybe we should just symlink `node_modules.asar` to `node_modules`.

**Comment by JammSpread** [comment]
Yeah I agree, it would change the workflow and complicate work if we package it.
