### ISSUE TITLE
Query parameters break IDE

### ISSUE THREAD

**Issue by garagatyi** [cdr/code-server#220]
I tried to use code-server in a container on Openshift inside of Che as an alternative to Eclipse Theia. Che adds query parameter `?uid=213488` to ensure that response is not cached and updates of the IDE web page are properly managed.
But code-server doesn't load because of this query parameter. Instead error is returned
`Cannot GET /` with error code 404.
Changing query parameter name doesn't help.
Could you allow passing query parameters to the IDE, so caching prevention would work?
Actually, it might be a good idea to prevent caching by default because some users would want to be able to run new version of the code-server in a docker container and not suffer from cached page issue.

**Comment by sr229** [comment]
From what I can understand, the http server they coded this at only listens to `/` so any query params can break the implementation quite easily.

**Comment by sr229** [comment]
this also breaks in Google Cloud Shell as well.

**Comment by sr229** [comment]
CC any coder maintainer to mark this as a bug and not a feature thanks

**Comment by Multishifties** [comment]
@sr229 Can confirm this is a known issue. I'll look into it today.

**Comment by nir0s** [comment]
This is actually a blocker for me. I'm using a reverse-proxy which identifies origin by a query param.

**Comment by kylecarbs** [comment]
Ah. I guess we'll need to add query params when we make requests.

**Comment by sr229** [comment]
@kylecarbs I think this is high priority since we have a large audience that has reverse proxies. This would be a pain in the ass for them (and for integrators who want to add this toolchain to their own solution)

**Comment by camazorro** [comment]
I got it running on my environment with a hack

<img width="1677" alt="Screen Shot 2019-05-15 at 12 25 39 AM" src="https://user-images.githubusercontent.com/2872969/57748588-99e4c200-76a8-11e9-943d-6c09b68198d1.png">

Basically, I have code-server running outside of Eclipse Che, and created a stack with a docker image with a simple HTTP server in python redirecting to code-server. It is not a secure environment but this is my internal network and is just me 👍

**Comment by sr229** [comment]
sounds like a acceptable workaround but this needs to be fixed upstream

**Comment by camazorro** [comment]
> sounds like a acceptable workaround but this needs to be fixed upstream

agreed

**Comment by jeasonstudio** [comment]
Any progress?

**Comment by sr229** [comment]
I have not heard from our folks at Coder but I'll go ahead CC one so they'll be updated about the need for this fix.

CC @deansheather

**Comment by nir0s** [comment]
> I got it running on my environment with a hack
> 
> <img alt="Screen Shot 2019-05-15 at 12 25 39 AM" width="1677" src="https://user-images.githubusercontent.com/2872969/57748588-99e4c200-76a8-11e9-943d-6c09b68198d1.png">
> 
> Basically, I have code-server running outside of Eclipse Che, and created a stack with a docker image with a simple HTTP server in python redirecting to code-server. It is not a secure environment but this is my internal network and is just me

Would appreciate if you could share your exact implementation. Thanks.

**Comment by deansheather** [comment]
I'll try to make a fix for this tomorrow.

**Comment by nir0s** [comment]
Any updates here?

**Comment by sr229** [comment]
GH-857 should fix this, we use query params in this as well

**Comment by nhooyr** [comment]
If this still occurs, please feel free to reopen.
