### ISSUE TITLE
google drive extension

### ISSUE THREAD

**Issue by trennble** [cdr/code-server#2209]
- [ ] Extension name: google drive for vscode
- [ ] Extension GitHub or homepage: https://github.com/GustavoASC/google-drive-vscode

**Comment by trennble** [comment]
or you can provide some way(or endpoint) let us contribute extension

**Comment by code-asher** [comment]
Currently we don't have a way to accept external contributions. I will
try to add this soon! In the meantime one workaround is to upload the
vsix from the GitHub release.
