### ISSUE TITLE
Add dakara.dakara-foldplus to marketplace

### ISSUE THREAD

**Issue by warenix** [cdr/code-server#2210]
## Code server 

Version

```sh
code-server -v
3.6.0 a4a03c14922ccaec2a9ff8d1b7b2af8522a4214d
```

## Description

I tried to search for extension on the installed code-server but code server said the extension is not found.
The extension is: [Fold plus](https://marketplace.visualstudio.com/items?itemName=dakara.dakara-foldplus)

Via command line:

```
Installing extensions...
Extension 'dakara.dakara-foldplus' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
error vscode undefined
error vscode undefined
```

Via in-browser editor

![image](https://user-images.githubusercontent.com/1849536/96415764-9bada000-1221-11eb-9f98-59a22c3d8a2d.png)

At last I install the extension by the vsix file.

**Comment by oxy** [comment]
Thanks for opening an extension request!
We are currently in the process of switching extension marketplaces and transitioning over to [Open VSX](https://open-vsx.org/).
Once https://github.com/eclipse/openvsx/issues/249 is implemented, we can fully make this transition. Therefore, we are no longer accepting new requests for extension requests. 

We suggest installing the VSIX file and then installing it via the code-server CLI as a temporary workaround. See [docs](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#installing-an-extension) for more info.
