### ISSUE TITLE
Caps Lock not working in Shells on Chrome 86+

### ISSUE THREAD

**Issue by Pand9** [cdr/code-server#2211]
Caps Lock does not work, i.e. does not switch to big letters, in Shells. It doesn't depend on type of shell, i.e. it's true in both Bash and Python shells.
The issue doesn't appear in Chrome/Chromium 85- or Firefox, only in 86+.

I've tested this hyphothesis on two computers. I've checked in Gnome 3 graphical shell, as well as i3 window manager (both X11-based).
Also checked on remote code-server, as well as two localhost versions: 3.0.4 and 3.6, and the issue was the same.
The problem does not appear in the main editor, only shell.

- Web Browser: Chrome / Chromium 86+. 85 is working correctly. Firefox is working correctly as well.
- Local OS: Linux Ubuntu 19.10 / Ubuntu 20.04, X11, Gnome 3 / i3
- Remote OS: (local host & remote unspecified)
- Remote Architecture: (local host & remote unspecified)
- `code-server --version`: Tested on 3.6 & 3.0.4 (latest Docker)

**Comment by code-asher** [comment]
Wow yeah this is weird. It seems to toggle on/off but the letters are
still lowercased but only in the terminal. It doesn't happen in Chrome
or Chromium 86 on Windows.

**Comment by nhooyr** [comment]
I can't reproduce this anymore in the latest code-server version with firefox nightly so I guess it's been fixed somehow.
