### ISSUE TITLE
Virtualenv interpreter not found in code-sever docker.

### ISSUE THREAD

**Issue by johnbritto1** [cdr/code-server#2217]
- Web Browser: chrome
- Local OS: Linux Mint
- Remote OS:
- Remote Architecture: x64
- `code-server --version`: https://hub.docker.com/r/linuxserver/code-server

Hello,

I have deployed the current code server using docker

docker run -d \
  --name=code-server \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e PASSWORD=sode1234 \
  -p 8443:8443 \
  -v /opt/coder-docker/config:/config \
  -**v /opt/app:/opt/app \**
  --restart unless-stopped \
  linuxserver/code-server

My application is in /opt/odoo and requires python interpreter.
I have created virtualenv using cmd:
virtualenv -p /usr/bin/python3.7 --no-site-packages --always-copy /opt/app/my-app/venv

In code-server, I have added workspace folder /opt/odoo/my-app.
Created a python lauch.json, and selected the python interpreter to be added in settings.json.

> {
>     "python.pythonPath": "/opt/app/my-app/venv/bin/python"
> }

Code-server keep prompting "unable to find python interpreter".

What is wrong here?

Thanks,

**Comment by johnbritto1** [comment]
Close this issue as i have posted here: https://github.com/linuxserver/docker-code-server/issues/38

**Comment by skylarkprojects** [comment]
Hiya..

In the code-server terminal:

sudo apt-get update
sudo apt-get install libpython3-dev
sudo apt-get install python3-venv

worked for me
