### ISSUE TITLE
npm-postinstall.sh script is broken on FreeBSD

### ISSUE THREAD

**Issue by zjijz** [cdr/code-server#2229]
- Web Browser: n/a
- Local OS: MacOS
- Remote OS: FreeBSD
- Remote Architecture: amd64 / x86_64
- `code-server --version`: 3.6.0, 3.6.1

Install succeeded on 3.5.0.
NPM log for 3.6.0 (`npm install -g code-server@3.6.0`): [code_server_3_6_0.log](https://github.com/cdr/code-server/files/5432496/code_server_3_6_0.log)
NPM log for 3.6.1 (`npm install -g code-server`): [code_server_3_6_1.log](https://github.com/cdr/code-server/files/5432494/code_server_3_6_1.log)

The issue has to due with a recent addition ([12 days ago](https://github.com/cdr/code-server/commit/a4a03c14922ccaec2a9ff8d1b7b2af8522a4214d#diff-9efc23615796709119daa0db0050a3b67205c9c8ee6d23a2ef635a88958ae777)) that always tries to download an OS-specific cloud-agent from Google Cloud: https://github.com/cdr/code-server/blob/62735da69466a444561ab9b1115dc7c4d496d455/ci/build/npm-postinstall.sh#L28

This fails with a 404 error for FreeBSD. v3.5.0 was before this addition and I did verify it works.

I think this is unrelated to #1880.

**Comment by mike-pt** [comment]
Yeah this is another issue, and I get the 404 too:

```
% http -h https://storage.googleapis.com/coder-cloud-releases/agent/latest/freebsd/cloud-agent
HTTP/1.1 404 Not Found
Alt-Svc: h3-Q050=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private, max-age=0
Content-Length: 215
Content-Type: application/xml; charset=UTF-8
Date: Mon, 02 Nov 2020 19:56:02 GMT
Expires: Mon, 02 Nov 2020 19:56:02 GMT
Server: UploadServer
X-GUploader-UploadID: ABg5-UzQ3Vxz7XIFiHNk9TLk2FAxmRm5HOqraeyZ5URRSXPtxllZk9A2UgfKSciJjye9F9SmWuZENrugCC3l7GwWKFw
``` 

this seems to only work when $OS= linux but that will ofc fail to run

**Comment by zjijz** [comment]
Thank you for the response! Love the project so far!

**Comment by nhooyr** [comment]
Should be fixed in the latest release!
