### ISSUE TITLE
`ALT + ArrowUp` & `ALT + ArrowDown` not working on Chrome OS

### ISSUE THREAD

**Issue by mjarkk** [cdr/code-server#2233]
**Expected:**  
Press `ALT + ArrowUp` and move the active line one line up

**What happens:**  
Cursor goes to the top of the document (And down to the bottom with `ALT + ArrowDown`).  

This is a Chrome OS keybinding and i'm not sure if it's over writable but it would be nice this shortcut would just work

- Web Browser: Chrome (85.0.4183.133) (installed as PWA)
- Local OS: Chrome OS (85.0.4183.133)
- Remote OS: Debian 10
- Remote Architecture: x86_64
- `code-server --version`: "3.6.1 62735da69466a444561ab9b1115dc7c4d496d455"

**Comment by code-asher** [comment]
I don't have a Chromebook to test but I think you're probably right that
they can't be overridden. Still, if someone can confirm that'd be
helpful.

**Comment by mjarkk** [comment]
I neither have a Chromebook though i'm still running Chrome OS using [brunch](https://github.com/sebanc/brunch)  
It's possible to run [brunch](https://github.com/sebanc/brunch) from an USB stick.  
There is also [CloudReady](https://www.neverware.com/freedownload/#intro-text) that is based on the Chromeium OS but i don't know if that has all the features of Chrome OS

**Comment by code-asher** [comment]
Oh awesome! Thanks for those links; will definitely help us test.

**Comment by nhooyr** [comment]
Yea unfortunately if it's a systemd level keybind it will take precedence. There's nothing we can do here. I'd recommend googling to see if you can disable the keybind at the system level so that code-server can catch it.
