### ISSUE TITLE
Unable to start 'cdr/code-server' in Docker container: “error EACCES: permission denied, mkdir '/home/coder/.config/code-server'”

### ISSUE THREAD

**Issue by skbergam** [cdr/code-server#2234]
Here's my script:

```
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo usermod -aG docker $USER
```

Then I disconnect from ssh, connect back, and run this command:

```
docker run -it --name code-server -p 127.0.0.1:8080:8080 -v "$HOME/.config:/home/coder/.config:rw" -v "$PWD:/home/coder/project:rw" -u "$(id -u):$(id -g)" -e "DOCKER_USER=$USER" codercom/code-server:latest
```

The error I get is `error EACCES: permission denied, mkdir '/home/coder/.config/code-server'`.

This is on a brand new EC2 instance. Any ideas? I've been banging my head on this and I don't know how to debug further. I've tried removing the `-e` and `-u` options from the command but those don't seem to have any effect, both with and without running docker with sudo but to no avail. Thank you!

**Comment by code-asher** [comment]
It looks like it might have something to do with the permissions on
$HOME/.config, although that seems unusual.

Are you able to write to that directory? For example with
`mkdir -p $HOME/.config/code-server`? You might need to do something
like `chown $USER $HOME/.config`.

**Comment by nhooyr** [comment]
This has been fixed and the docker command example has been updated.

See https://github.com/cdr/code-server/blob/v3.8.0/doc/install.md#docker

```
# This will start a code-server container and expose it at http://127.0.0.1:8080.
# It will also mount your current directory into the container as `/home/coder/project`
# and forward your UID/GID so that all file system operations occur as your user outside
# the container.
#
# Your $HOME/.config is mounted at $HOME/.config within the container to ensure you can
# easily access/modify your code-server config in $HOME/.config/code-server/config.json
# outside the container.
mkdir -p ~/.config
docker run -it --name code-server -p 127.0.0.1:8080:8080 \
  -v "$HOME/.config:/home/coder/.config" \
  -v "$PWD:/home/coder/project" \
  -u "$(id -u):$(id -g)" \
  -e "DOCKER_USER=$USER" \
  codercom/code-server:latest
```

**Comment by brootware** [comment]
> This has been fixed and the docker command example has been updated.
> 
> See https://github.com/cdr/code-server/blob/v3.8.0/doc/install.md#docker
> 
> ```
> # This will start a code-server container and expose it at http://127.0.0.1:8080.
> # It will also mount your current directory into the container as `/home/coder/project`
> # and forward your UID/GID so that all file system operations occur as your user outside
> # the container.
> #
> # Your $HOME/.config is mounted at $HOME/.config within the container to ensure you can
> # easily access/modify your code-server config in $HOME/.config/code-server/config.json
> # outside the container.
> mkdir -p ~/.config
> docker run -it --name code-server -p 127.0.0.1:8080:8080 \
>   -v "$HOME/.config:/home/coder/.config" \
>   -v "$PWD:/home/coder/project" \
>   -u "$(id -u):$(id -g)" \
>   -e "DOCKER_USER=$USER" \
>   codercom/code-server:latest
> ```

I'm running into the same error using this command on rhel7. @skbergam has this been fixed for you? Is anyone else facing the same?

**Comment by jsjoeio** [comment]
@brootware please open a GitHub Discussion or a bug report if you're experiencing issues!

**Comment by yonixw** [comment]
What worked for me is:
1. to create a folder, `cd` into it,
2. prepare mount folder by `mkdir -p home/.config`
3. Runnit this command:

```
docker run
  -it --name code-server 
  -p 8080:8080 
  -v /var/run/docker.sock:/var/run/docker.sock 
  -v "$(pwd)/home:/home/coder/" 
  -u "$(id -u):$(id -g)" 
  -e "DOCKER_USER=$USER" 
codercom/code-server:latest
```

**Comment by trangvu3103** [comment]
@yonixw Thanks a bunch! I was running into this problem all night long. None of the commands from the document working.

**Comment by aprinaprin** [comment]
cd ~/code-server
