### ISSUE TITLE
3.6.1 doesn't load the vscode editor

### ISSUE THREAD

**Issue by gordon0001** [cdr/code-server#2235]
- Web Browser: MS Edge (Chromium), Firefox, Safari
- Local OS: Ubuntu 20.04.1 LTS, Windows 10 2003, iPadOS 14.0.1
- Remote OS: Debian Buster 10.6
- Remote Architecture: amd64
- `code-server --version`: 3.6.1

I used the install script today and edited the .service file with additional parameters like so:

`code-server --bind-addr 0.0.0.0:123 --user-data-dir /var/codeserver --auth password --cert  /etc/letsencrypt/live/domain/fullchain.pem --cert-key /etc/letsencrypt/live/domain/privkey.pem --disable-telemetry`

but then on the web browser (Edge Win10, Firefox Ubuntu20.04.1, Safari iPadOS14.0.1) after entering the password it doesn't load the vscode editor like it should do - the browser is instead waiting for a response from the code-server but never gets one. 

Didn't know that there was an update, but when I install the 3.6.0 .deb package over the 3.6.1 install, so it replaces 3.6.1, I have no issues and the vscode editor loads up without any problems. Only 3.6.1 makes it not load.

My host system: Debian Buster 10.6 with kernel 5.8.0-0.bpo.2-amd64

**Comment by Chenyu91** [comment]
I also encountered the similar problem. I start the code-server program, open in browser, and enter the password, then the browser has nothing to show. I pressed F12 and there was some errors: Uncaught ReferenceError: globalThis is not defined. I'm using Chrome and the version number is 59.0.3071.115.

**Comment by code-asher** [comment]
Oh that's interesting. It looks like globalThis was added in version 71
of Chrome.

**Comment by gordon0001** [comment]
I upgraded to 3.6.2 and the editor does now load but settings and theme aren't saved anymore and are reset to default when reloading the page. On 3.6.0 I hadn't any problems. I guess it is related to #2274 

Anyway, this issue (#2235) is solved for me, so I close it.
