### ISSUE TITLE
3.6.1 Activating extension 'octref.vetur' failed

### ISSUE THREAD

**Issue by qixin1991** [cdr/code-server#2236]
Upgrade from `3.6.0` to `3.6.1` ,devtools console reports `Activating extension 'octref.vetur' failed`:

![image](https://user-images.githubusercontent.com/10718925/97150490-230e8c80-17a9-11eb-9ddd-d52b5fc87304.png)

- Web Browser: Chrome 86
- Local OS: Mac OSX 10.15.7
- Remote OS: Ubuntu 18.04
- `code-server --version`: 3.6.1

**Comment by qixin1991** [comment]
This issue caused `.vue` files can't be show with highlight.

**Comment by xorik** [comment]
https://github.com/eclipse-theia/theia is working with vetur, but unfortunately it doesn't protect the editor with password

**Comment by qixin1991** [comment]
@xorik So i choose `code-server`

**Comment by nhooyr** [comment]
Can you still reproduce this on the latest release?

**Comment by qixin1991** [comment]
@nhooyr `v3.7.4`  fixed.👍🏻

**Comment by nhooyr** [comment]
Hurray!!!
