### ISSUE TITLE
HTTP 404 in `webview//vscode-resource/file//` for file which name needs urlEncode

### ISSUE THREAD

**Issue by Makiras** [cdr/code-server#2241]
- Web Browser: Chrome/86.0.4240.111
- Local OS: Windows 1909
- Remote OS: Ubuntu 20.04.1 LTS
- Remote Architecture: amd64
- `code-server --version`:  3.6.1

Get 404 for `https://domain/webview//vscode-resource/file///home/makiras/%E6%96%87%E6%A1%A3/scitec-history/homework1/%E7%BB%8419-RSA/README.pdf (file///home/makiras/文档/scitec-history/homework1/组19-RSA/README.pdf) `
But works well for `https://domain/webview//vscode-resource/file///home/makiras/code/os/multiThreads.zip`

**Comment by nhooyr** [comment]
May be fixed in the latest release! We made a bunch of changes to these endpoints. Please test!

**Comment by Makiras** [comment]
It works well now , thanks for your effort ! 😀

**Comment by nhooyr** [comment]
Yay!
