### ISSUE TITLE
Update Python Extension

### ISSUE THREAD

**Issue by blaylockbk** [cdr/code-server#2256]
- [ ] Extension name: Python
- [ ] Extension GitHub or homepage: https://github.com/microsoft/vscode-python

The version installed by code-server is v2020.5.86806, but the most recent version is 2020.10.332292344.

I'm making this request because the copy/paste doesn't work in Jupyter Notebooks (.ipynb files).  The ctrl+c and ctrl+v shortcuts do not interact with the clipboard, and I wonder if it's because the version is old.

**Comment by ErSauravAdhikari** [comment]
Yes, we need to make python extension work in the editor. I can't even install it.

**Comment by cmoog** [comment]
Thank you for reporting this. It seems that the repo name shifted around a bit. We've updated our marketplace with the most recent version.
