### ISSUE TITLE
salesforce.salesforcedx-vscode pack won't work

### ISSUE THREAD

**Issue by vdboots** [cdr/code-server#2260]
- Web Browser: Chrome 
- Local OS: Chrome OS
- Remote OS: Ubuntu 18.04
- Remote Architecture: x64
- `code-server --version`: 3.6.1

**Comment by nhooyr** [comment]
Hi @vdboots can you elaborate on the problem you're encountering here?

**Comment by nhooyr** [comment]
Going to close as there hasn't been a response in a long time.
