### ISSUE TITLE
Cannot preview markdown on iPad

### ISSUE THREAD

**Issue by LeonardAB** [cdr/code-server#2262]
- Web Browser: safari and chrome
- Local OS: iPad OS 13
- Remote OS: ubuntu 
- Remote Architecture: x64
- `code-server --version`: 3.6.1

I tried to open a preview of a markdown file, but failed on chrome and safari on iPad. 
After opening the md file, then choosing the preview menu (F1 then `Markdown: Open Preview` ), the status bar shows `Activating Extensions` for a few seconds, but the preview does not come up.  (This works well on chrome on Windows.)

**Comment by Talent30** [comment]
It is a common issue if you are using Safari #2232

**Comment by jsjoeio** [comment]
I believe this has been fixed. I’m testing on iPadOS in Chrome and it works as expected.

code-server: v3.8.0
VS Code: v1.51.1
Commit: Unknown
Date: Unknown
Browser: Mozilla/5.0 (iPad; CPU OS 14_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/87.0.4280.77 Mobile/15E148 Safari/604.1

See screenshot here: 
![687D080A-114B-495D-BAA2-422F008884EE](https://user-images.githubusercontent.com/3806031/103955480-9a469200-5103-11eb-913f-637e202fe5c2.png)

I’m going to close this issue for now. If you still see problems on your side, please reopen and ping me.
