### ISSUE TITLE
ms-vscode.cpptools is missing files

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#2263]
```
[Extension Host] Extension file mono.linux-x86_64 is missing.
The C/C++ extension failed to install successfully. You will need to repair or reinstall the extension for C/C++ language features to function properly.
```

**Comment by code-asher** [comment]
Interesting, in my case the file does actually exist but has `arm64` instead of `x86_64`. I was able to fix by:
```
cd ~/.local/share/code-server/extensions/ms-vscode.cpptools-1.0.1/debugAdapters
mv mono.linux-arm64 mono.linux-x86_64
```

**Comment by code-asher** [comment]
Another workaround: download the vsix from https://github.com/microsoft/vscode-cpptools/releases/tag/1.0.1 and upload it to code-server.

**Comment by ivang7** [comment]
guys, if you want download vsix from ms marketplace, you should generate special link:
https://stackoverflow.com/questions/42129234/how-to-extract-a-vsix-file-i-e-not-install

**Comment by vipwp** [comment]
you can download cpp-tools_linux.vsix and than install from vsix

**Comment by nhooyr** [comment]
Duplicate of https://github.com/cdr/code-server/issues/2120

**Comment by Srackliff** [comment]
> Another workaround for now: download the vsix from https://github.com/microsoft/vscode-cpptools/releases/tag/1.0.1 and upload it to code-server.

I did this just now, and got the same error:
.vscode-server/extensions/ms-vscode.cpptools-1.2.0-insiders3/debugAdapters/mono.linux-x86_64 is missing.

**Comment by code-asher** [comment]
Which vsix did you download? For x86_64 you'll need `cpptools-linux.vsix`.
