### ISSUE TITLE
Frequent unrecoverable disconnections on localhost

### ISSUE THREAD

**Issue by fonnesbeck** [cdr/code-server#2266]
- Web Browser: Chrome 87
- Local OS: Debian Slim
- Remote OS: Debian Slim
- Remote Architecture: AMD
- `code-server --version`: code-server: v3.6.1
VS Code: v1.50.0

I am running code-server locally and am getting frequent disconnections from which code-server never recovers. Hitting "reconnect now" simply resets the reconnect timer and does not recover the session. I am forced to reload the window and start a new session. This happens often enough to make it unusable for general work.

I am running the Python extension on code-server, incase that is relevant.

![Screenshot 2020-11-03 at 10 18 19 AM](https://user-images.githubusercontent.com/81476/98012133-5ca15200-1dbe-11eb-87be-fcc8477c7c8d.png)

**Comment by code-asher** [comment]
Could you try out 3.6.2? It contains a fix for a connection issue
although it's possible you are experiencing a different problem.

**Comment by vnijs** [comment]
I believe this is fixed in the 3.7.3 release. At least I'm not seeing this happen anymore.

**Comment by code-asher** [comment]
Closing for now, lemme know if the problem persists in the latest release!
