### ISSUE TITLE
settings.json in code server v3.6.2 and v3.6.1 is no longer populated.

### ISSUE THREAD

**Issue by OliverwengFiltered** [cdr/code-server#2274]
- Web Browser: Chrome latest
- Local OS: Mac latest
- Remote OS: Linux
- Remote Architecture: google cloud vm
- `code-server --version`: 3.6.2 and 3.6.1

Recently upgraded to v3.6.2.

one thing seems a bit odd is that the `settings.json` was supposed to be populated under this directory: `~/.local/share/code-server/User` if user has any vscode related settings change like a color theme.

the `settings.json` file was there in`~/.local/share/code-server/User` under v3.6.0
but the same `settings.json` can't be found in the same directory under v3.6.1 or v3.6.2

We are using the settings.json to control the default looking feel of the vscode, so this part is broken when upgrading to the latest.

**Comment by OliverwengFiltered** [comment]
discuss with @code-asher ,

it seems vscode starting to read/set settings.json by using browser storage instead of on a remote disk.

wondering if anyone come across the same situation that needs to set default view when cod-server starts for the first time.

**Comment by code-asher** [comment]
I'm not aware of a way to do this but I think maybe what we do is patch VS Code to use the filesystem again. https://github.com/cdr/code-server/issues/2231#issuecomment-721900830

**Comment by OliverwengFiltered** [comment]
awesome, thanks for letting me know, will keep an eye on the release log in the future about this change.

Thank you. @code-asher  you are amazing!

**Comment by benz0li** [comment]
Thanks for your investigations, @code-asher.

I create customised Docker Images containing code-server and pre-populate `~/.local/share/code-server/User/settings.json`. Using the filesystem again covers this use case, too.

Keep up the great work on code-server!

**Comment by demyxco** [comment]
Any news on this? I'm using a custom path for user data directory and just read this https://github.com/cdr/code-server/issues/2231. Placing a pre-populated settings.json isn't working.

```
# Starting code-server using a custom user data path
code-server /home/demyx --user-data-dir=/home/demyx/.code/data

# Pre-populated settings.json
/home/demyx/.code/data/User/settings.json
```

**Comment by code-asher** [comment]
Nothing yet; still working on the 1.51 VS Code update.

**Comment by cfal** [comment]
The settings.json local to code-server (~/.local/share/code-server/User/settings.json) still seem to work and can be accessed from "Open Remote Settings" inside vscode, but I believe the settings.json stored in the browser's local storage has priority and will override anything you set there.

**Comment by demyxco** [comment]
Yeah looks like I'll have to update all my code-server repos and hardcode it to `3.6.0` until this is resolved.

**Comment by JtMotoX** [comment]
@demyxco yeah I had to create a tap for code-server with 3.6.0 since that seemed to be the only way to downgrade until this is resolved.

**Comment by hgw77** [comment]
with 3.7.2 the problem still exist

**Comment by gsmachado** [comment]
I can also confirm that the problem still exists with `3.7.2`.

As a consequence, it's not possible, at all, to set a custom `settings.json` file that "persists" and that code-server picks it. 😞

**Comment by Leletir** [comment]
Any news about this bug ?

**Comment by code-asher** [comment]
I have a fix in a PR so hopefully we can make a new release soon.

**Comment by nhooyr** [comment]
Will be in `v3.7.3` which I'll get out today!

**Comment by gsmachado** [comment]
@nhooyr Great stuff! Much appreciated!

Looking forward to test `v3.7.3`!

**Comment by Leletir** [comment]
Thank you very much!

**Comment by demyxco** [comment]
`v3.7.3` works 👍
