### ISSUE TITLE
Persistant terminal session on tab refresh

### ISSUE THREAD

**Issue by bpmct** [cdr/code-server#2276]
Eclipse Theia keeps any terminal sessions open when the tab is refreshed. Would it be possible to have this same functionality in code-server? Either enabled at all times, or with a flag.

**Comment by ntimo** [comment]
VSCode 1.51 has been released with support for "Ability to persist/reconnect to terminal sessions." might this actually fix this issue?

Source: https://code.visualstudio.com/updates/v1_51

**Comment by code-asher** [comment]
Yes, I'm pretty sure it should! Will be working on this update soon.

**Comment by ntimo** [comment]
I just installed code server v3.7.2 which contains the update to vscode 1.51 but sadly the terminal sessions are not persistent :(

**Comment by code-asher** [comment]
Sorry about that, we still need to implement the persistence. I have it
partially implemented but it doesn't work for things like htop or vim.

**Comment by outermeasure** [comment]
Any news on this? @code-asher Do you have a starting point so I can take a look?

**Comment by code-asher** [comment]
No updates. The code is all in https://github.com/cdr/code-server/blob/v3.8.1/lib/vscode/src/vs/server/node/channel.ts.

Here is where we force persistence off until we fix it:
https://github.com/cdr/code-server/blob/v3.8.1/lib/vscode/src/vs/server/node/channel.ts#L569

This is the code that tries to store the data:
https://github.com/cdr/code-server/blob/v3.8.1/lib/vscode/src/vs/server/node/channel.ts#L506-L543

And the code that tries to restore it:
https://github.com/cdr/code-server/blob/v3.8.1/lib/vscode/src/vs/server/node/channel.ts#L480-L488

It works for simple text printed to the terminal but it falls apart with
things like htop, vim, etc.

**Comment by outermeasure** [comment]
Thank you. I will send a PR if I get anywhere (but no promises).

**Comment by outermeasure** [comment]
Ok, I found a related but different problem that was a bit more irritating. Terminal processes leak when refreshing the page.
I have a PR for that: https://github.com/cdr/code-server/pull/2723

**Comment by ntimo** [comment]
@outermeasure @code-asher Do you have any news about this? :) This would be super important since for example when your run Ansible from Code Server and your connection for what ever reason breaks being able to reconnect and still having the open terminal would be quite nice.

**Comment by code-asher** [comment]
Nope, we haven't done anything here yet.

**Comment by ServerAcademy** [comment]
Any news about this? It would be great for us as well.

**Comment by raychunghk** [comment]
Now i use control+shift+p , then "Terminal: Attach to Session" to resume the terminal session I was working on.
