### ISSUE TITLE
got error when running `code-server` after being installed.

### ISSUE THREAD

**Issue by chocoford** [cdr/code-server#2285]
got
```sh
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/usr/local/bin/out/node/entry.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

but succeeding in running code-server with `sudo systemctl enable --now code-server@$USER`.

Moreover, when running with command `sudo systemctl enable --now code-server@$USER`, got same problem as #1888

- Web Browser: Safari, Chrome, VSAPP in iPadOS
- Local OS: MacOS, iPadOS
- Remote OS: Ubuntu 18.04
- Remote Architecture: x86_64
- `code-server --version`: 3.6.0

**Comment by code-asher** [comment]
Interesting, that path looks a bit strange, I think it's supposed to be
/usr/local/code-server/out/node/entry.js. How was code-server installed
and started?

**Comment by chocoford** [comment]
I installed `code-server` with command copied from readme, and start with `sudo systemctl enable --now code-server@$USER`.
By the way, current version (which is 3.6.0) is simply upgrade by reinstall `code-server` with the command in ReadMe.

**Comment by chocoford** [comment]
Ok, the problem has been solved by removing `code-server` in `/use/local/bin` and reinstalling with scripts.
And #1888 can be solved by just run `code-server` rather than run `sudo systemctl enable --now code-server@$USER`

**Comment by code-asher** [comment]
Check out https://github.com/cdr/code-server/issues/2231 for the theme
issue and https://github.com/cdr/code-server/issues/2232 for various
other issues with Safari (which I think include the vscode.json issue).

**Comment by ozancakir** [comment]
hello, is there any fix yet ? Should I downgrade to 3.6.0? Thanks for such a powerful tool

**Comment by code-asher** [comment]
Not yet but it's underway!

**Comment by nhooyr** [comment]
Should be fixed in the latest release!
