### ISSUE TITLE
Python extension not loading correctly

### ISSUE THREAD

**Issue by dschartman** [cdr/code-server#2290]
I'm experiencing weird loading behavior of the python extension in code server 3.6.2 and 3.6.1.  Basically, the extension doesn't load at all.  However, if I pull up the developer console, the extension loads after refresh.

### Steps to reproduce

1. Spin up code server

        if [ -d .local ]; then
            rm -rf .local
        fi

        mkdir .local && chmod 777 .local
        docker run -it --rm -v ${PWD}/.local:/home/coder/.local -p 80:8080 codercom/code-server:3.6.2 --auth none --log trace
2. Go to localhost
3. Install python extension
4. Create and open test.py file
5. Refresh page and confirm extension does not load
6. Open the developer console (F12)
7. Refresh page and confirm exension loads

Here is a screenshot of what I see after step 5:
![image](https://user-images.githubusercontent.com/28736137/98861382-cc50b600-242a-11eb-94ea-b134a6afcfcc.png)

After step 7:
![image](https://user-images.githubusercontent.com/28736137/98862244-3027ae80-242c-11eb-9607-5185e9fa60fd.png)

Thanks in advance!

- Web Browser: Chromium
- Local OS: Win10 host / Debian 10 buster VM
- Remote OS: codercom/code-server:3.6.2 container and debian VM
- Remote Architecture: x86_64
- `code-server --version`: 3.6.2 and 3.6.1

**Comment by code-asher** [comment]
Folding into https://github.com/cdr/code-server/issues/2341 since we have a bit more information there on issues with the Python extension.
