### ISSUE TITLE
Binding to specific IP or NIC

### ISSUE THREAD

**Issue by michacassola** [cdr/code-server#2291]
Putting a real IP address into the config like this: `bind-addr: [1234:1234:1234::1234]:443`
results in the following error message:
```
[2020-11-11T21:46:33.879Z] error can not read a block mapping entry; a multiline key may not be an implicit key in "/root/.config/code-server/config.yaml" at line 2, column 5:
    auth: password
        ^
```
Please make it possible to bind to a specific IP address or a NIC like `bind-addr: eth1`.

Use case:
Running a website on eth0 with a different IPv6 address and code-server on eth1 both on port 443.

**Comment by code-asher** [comment]
I think this is a yaml thing; the brackets indicate a list so this isn't
valid syntax. Putting it in quotes should work:

```
bind-addr: "[1234:1234:1234::1234]:443"
```

**Comment by nhooyr** [comment]
@code-asher is correct re this being about yaml syntax.
