### ISSUE TITLE
Request to add ms-toolsai.jupyter to the coder marketplace

### ISSUE THREAD

**Issue by metalshanked** [cdr/code-server#2293]
- [ ] Extension name: ms-toolsai.jupyter
- [ ] Extension GitHub or homepage:https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

I updated to the latest ms-python (2020.11.358366026 and seems like it is now looking for a dependency ms-toolsai.jupyter. 

"Cannot activate the 'Python' extension because it depends on an unknown 'ms-toolsai.jupyter' extension ."

**Comment by garyfanhku** [comment]
can confirm, prompts `Cannot activate the 'Python' extension because it depends on an unknown 'ms-toolsai.jupyter' extension`

**Comment by remeezp** [comment]
I am also attempting to enable python interpreter, but as mentioned above it's not working.  I have tried `code-server --install-extension ms-toolsai.jupyter` but getting the following error:

```root@c8bf0dbfe63e:/home/coder# code-server --install-extension ms-toolsai.jupyter
Installing extensions...
Extension 'ms-toolsai.jupyter' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
error vscode undefined
error vscode undefined```

**Comment by garyfanhku** [comment]
> I am also attempting to enable python interpreter, but as mentioned above it's not working. I have tried `code-server --install-extension ms-toolsai.jupyter` but getting the following error:
> 
> ```
> Installing extensions...
> Extension 'ms-toolsai.jupyter' not found.
> Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
> error vscode undefined
> error vscode undefined```
> ```

Since ms-toolsai.jupyter is a proprietary plugin by MS like pylance, it probably wouldn't be included in code-server's extension pool. For now the workaround seem to be installing previous versions of the python extension. Then the python interpreter will work as usual.

**Comment by remeezp** [comment]
> > I am also attempting to enable python interpreter, but as mentioned above it's not working. I have tried `code-server --install-extension ms-toolsai.jupyter` but getting the following error:
> > ```
> > Installing extensions...
> > Extension 'ms-toolsai.jupyter' not found.
> > Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
> > error vscode undefined
> > error vscode undefined```
> > ```
> 
> For now the workaround seem to be installing previous versions of the python extension. Then the python interpreter will work as usual.

I managed to get it working, by downloading the **ms-python.python-2020.11.358366026.vsix** and **ms-toolsai.jupyter-2020.11.358541065.vsix** packages from the marketplace.  I have code-server running in docker, so copied it into the container and installing the extension using the "Install from VSIX..."

**Comment by dtmddus** [comment]
> > > I am also attempting to enable python interpreter, but as mentioned above it's not working. I have tried `code-server --install-extension ms-toolsai.jupyter` but getting the following error:
> > > ```
> > > Installing extensions...
> > > Extension 'ms-toolsai.jupyter' not found.
> > > Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
> > > error vscode undefined
> > > error vscode undefined```
> > > ```
> > 
> > 
> > For now the workaround seem to be installing previous versions of the python extension. Then the python interpreter will work as usual.
> 
> I managed to get it working, by downloading the **ms-python.python-2020.11.358366026.vsix** and **ms-toolsai.jupyter-2020.11.358541065.vsix** packages from the marketplace. I have code-server running in docker, so copied it into the container and installing the extension using the "Install from VSIX..."

How to install ms-toolsai.jupyter? I could not find it in marketplace

**Comment by ZavShotanCBS** [comment]
Same issue here. @remeezp Can you please post your install code? Or the links for the download?

**Comment by abhishekkrthakur** [comment]
You can download the package and then untar it and use it. However, this is not everyone prefers :D 
It would be nice to have the python extension updated and the jupyter extension too. It is currently breaking ColabCode: https://github.com/abhishekkrthakur/colabcode/issues/42

**Comment by remeezp** [comment]
> Same issue here. @remeezp Can you please post your install code? Or the links for the download?

I downloaded the packages from the marketplace under the Resources section:

[https://marketplace.visualstudio.com/items?itemName=ms-python.python](url)
[https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter](url)

Then from within vs code, I install the extension using the "Install from VSIX..." command on the extensions pane.

**Comment by abhishekkrthakur** [comment]
@cmoog ?

**Comment by bafonso** [comment]
I can install the extension manually but I cannot get Jupyter interactive to work, only cmd line python execution.

**Comment by cmoog** [comment]
I apologize for the delay on fixing this one. I've pushed a fix.

Please open new issues if secondary problems arise as a result of this new split architecture.

**Comment by cmclean165** [comment]
Im still getting the same error

**Comment by RickyWei** [comment]
still have this error for python 3.7.9

**Comment by nayanex** [comment]
Somehow I was able to install it by trying to install other similar extension, called "**Python Extension Pack**", which includes the **ms-python.python** extension. Otherwise, we are provided with the option download the the extension manually.

![image](https://user-images.githubusercontent.com/3999511/110532741-83311a00-811d-11eb-9c16-cc314b2c9949.png)

 Which you can place in the folder `~/.vscode-server/extensions`
 
ms-python.python
![image](https://user-images.githubusercontent.com/3999511/110532278-e79fa980-811c-11eb-9a10-3b212d301520.png)

![image](https://user-images.githubusercontent.com/3999511/110532827-9e9c2500-811d-11eb-82e2-c1d62bc2bd83.png)
