### ISSUE TITLE
ExtensionHostConnection is not disconnected, causing the heartbeat file to continue to update

### ISSUE THREAD

**Issue by fxxjdedd** [cdr/code-server#2295]
> First of all, thank you for making such a great project of code-server, and thank you for taking the time to look at this issue, I am really stuck.

**※This problem only occurs when using `http-proxy` to forward requests, and there is no problem when using ip+port directly.**

Then, the actual request flow is like this:

![image](https://user-images.githubusercontent.com/13739947/98940780-74977500-2526-11eb-9561-c7cffca79dd2.png)

The steps to reproduce are as follows: **Open vscode, after a few seconds, close the page and check the log.**

Here is the log when using Nginx & http-proxy:

![image](https://user-images.githubusercontent.com/13739947/98943513-985cba00-252a-11eb-8f50-2f7156e0f2b1.png)

Here is the log when using ip+port:

![image](https://user-images.githubusercontent.com/13739947/98942586-33549480-2529-11eb-964a-6f734a2ce151.png)

As you can see, in a normal example, `Exited` will be triggered, and then the connection will be disconnected. But in the abnormal example, `Exited` is not triggered, and the connection has not been disconnected.

I know that the problem must be my http-proxy, but what is even more confusing is that even if I turn off the node server, ExtensionHostConnection is still not closed, and the heartbeat file is continuously update.

I'm really stuck, thank God if anyone can help!

- Web Browser: 86.0.4240.183
- Local OS: Macos
- Remote OS: Linux
- Remote Architecture: x86_64
- `code-server --version`: 3.6.2

**Comment by fxxjdedd** [comment]
I guess it is because the node server did not correctly send the close signal to the code-server when the browser page was closed.

**Comment by code-asher** [comment]
I'm not sure why either but thanks for the lead! Should help us figure
out what's going on.

**Comment by fxxjdedd** [comment]
After a day of debugging, it was found that the problem was because the serviceWorker file was not successfully loaded.

> /static/dda533e02eda2e6eff1c77d671ef07f0a2600bc8/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/worker/extensionHostWorkerMain.js

This problem is not caused by code-server, but by my own node service. 🤣

**Comment by fxxjdedd** [comment]
For anyone who encounters this problem, pay attention to whether the Request Headers of this file carries cookies.

The problem of not carrying cookies should start after this commit:

https://github.com/microsoft/vscode/commit/a02c4e72935304e618a7f2fe5d96fdbf51cf9ba6#diff-d716ee6240598a786899299f9bf9f23b6e622fbc41bfb9ab10e12fa0082946bf
