### ISSUE TITLE
Request: The new Jupyter extension from Microsoft

### ISSUE THREAD

**Issue by blaylockbk** [cdr/code-server#2298]
- [ ] Extension name: Jupyter (the new one from Microsoft)
- [ ] Extension GitHub or homepage: https://github.com/Microsoft/vscode-jupyter

Introductory article here: https://devblogs.microsoft.com/python/introducing-the-jupyter-extension-for-vs-code/

**Comment by dclong** [comment]
It is a must as the Python extension depends on it. 

![image](https://user-images.githubusercontent.com/824507/99131284-97c63100-25c7-11eb-841d-46b217bddb44.png)

**Comment by cmoog** [comment]
I apologize for the delay in releasing a patch for this. I've pushed and fixed and verified that the primary user flows are working again. Please open new issues if secondary problems arise as a result of this new split architecture.
