### ISSUE TITLE
Couldn't find a debug adapter descriptor for debug type 'python'

### ISSUE THREAD

**Issue by dclong** [cdr/code-server#2301]
I encountered the following issue while trying to debug Python code in coder-server. 
![image](https://user-images.githubusercontent.com/824507/99119809-afdd8680-25ae-11eb-81d9-00a9c5ddda64.png)

Below is my environment information. 
- Web Browser: Chrome 86
- Local OS: macOS Catalina
- Remote OS: Ubuntu LTS (in Docker)
- Remote Architecture:
- `code-server --version`: 3.6.2

And my launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}
```

**Comment by code-asher** [comment]
Could you post the browser console logs?

**Comment by code-asher** [comment]
I think this is probably the same issue causing https://github.com/cdr/code-server/issues/2341 so I'll close this in order to track there. Please let me know if it doesn't look like the same issue though!

**Comment by mursrira** [comment]
thanks @rajatongit - your suggestion fixed the issue :)
