### ISSUE TITLE
there is no typescript features from 3.6.1

### ISSUE THREAD

**Issue by balazssoltesz** [cdr/code-server#2304]
typescripit language server not loaded at all. 
with version 3.6.1 and 3.6.2 there is no typescript intelisense in code-server at me. there is no Restart TS Server task, and seems to not exist any typescript feature in code-server. There is no error message in output logs, but there is no Typescript option in output panel as well. 
Any idea? Thanks for advance!

additional information:
i create an own docker image based on debian:stable with
```
RUN  curl -sSOL https://github.com/cdr/code-server/releases/download/v3.6.2/code-server_3.6.2_amd64.deb
RUN dpkg -i code-server_3.6.2_amd64.deb    
```
and then entrypoint is
`/usr/bin/code-server --extensions-dir=/home/user/extensions-dir --user-data-dir=/home/user/userdata-dir --auth none --disable-telemetry --bind-addr 0.0.0.0:8080`

everything was nice till 3.6.0, but from 3.6.1 typescript features seems to be disapeared. 
the built in "TypeScript and JavaScript Language Features" extension is enabled.

**Comment by code-asher** [comment]
What browser are you using? Could you post the browser console logs?

**Comment by balazssoltesz** [comment]
Interesting. 
It is working in firefox well, but not in chrome. There is no error in ff console, but has some serviceworker problem in chrome. 

`Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope .... The path of the provided scope ('/') is not under the max scope allowed ('/static/2bf91ff6a6d1f29a8a93f97684177ccf5388cf34/usr/lib/code-server/dist/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.`

`Refused to execute script from '..../static/2bf91ff6a6d1f29a8a93f97684177ccf5388cf34/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/worker/extensionHostWorkerMain.js' because its MIME type ('') is not executable.`

**Comment by code-asher** [comment]
Ah the extension host worker is failing to load. I've seen this on
Safari but I actually haven't seen it on Chrome before. It's also a
different error than the one on Safari. What version of Chrome are you
running?

I'm hopeful the update to VS Code 1.51.1 will fix this, fingers crossed.

**Comment by balazssoltesz** [comment]
im running it on latest chrome (87.0). I have tried to run this in incognito mode, but still have no luck. I hope that next version will fix this issue, but till then im using it on ff. Thanks for your help.

**Comment by jaydensar** [comment]
This was also occurring for me, but after updating to 3.7.2 it no longer fails to load.

**Comment by balazssoltesz** [comment]
yes. confirmed. 3.7.2 solved the problem.
