### ISSUE TITLE
Update Dock Icon

### ISSUE THREAD

**Issue by christianjuth** [cdr/code-server#2307]
### Update Dock Icon

I want to prefix this with this is super nitpicky. I love code-server, but the current dock icon stands out from other applications in the dock in an unpleasant way. I reworked the current design to match the macOS Big Sur icon style, and I think it looks a lot better (see image below). It's pretty rough, but if you like what you see, I would be happy to work on it more and provide variations for Windows and Linux.

### Before

![image](https://user-images.githubusercontent.com/5768801/99205250-fcc78580-2785-11eb-9fd0-036054aba0aa.png)

### After

![icon in dock](https://user-images.githubusercontent.com/5768801/99204933-1ddba680-2785-11eb-9d3e-6c92caf18eaa.png)

![Full icon](https://user-images.githubusercontent.com/5768801/99205104-8d519600-2785-11eb-9171-e2952f22d2ab.png)

**Comment by nhooyr** [comment]
I agree, the current icon is kinda weird. Love the new icon @christianjuth!

The files that would need replacing are in https://github.com/cdr/code-server/tree/master/src/browser/media

If you can open a PR with the new files, I'd be happy to accept as is! What were you thinking of changing for Linux/Windows?

**Comment by christianjuth** [comment]
@nhooyr to be completely honest, I haven't installed code-server on Linux/Windows as a PWA. Now that I'm looking at the current icons, it looks like it uses the same icons for all platforms. Do you think the design above works for Linux/Windows? I want to make sure I'm not only thinking of Mac since that is what I use day-to-day.

Also, is there a place I could save the SVG? That will make it easier to change the icon later. Should I throw it in the same folder you mentioned above? I'm using Sketch, so I could also include the project file if you want.

**Comment by nhooyr** [comment]
> @nhooyr to be completely honest, I haven't installed code-server on Linux/Windows as a PWA. Now that I'm looking at the current icons, it looks like it uses the same icons for all platforms. Do you think the design above works for Linux/Windows? I want to make sure I'm not only thinking of Mac since that is what I use day-to-day.

I think it should work. Though, I did just notice that you didn't use our exact logo. Let me see if I can get our logo as an SVG from our designer.

> Also, is there a place in the project I can put the SVG file? That will make it easier to change the icon later. Should I throw it in the same folder you mentioned above? I'm using Sketch, so I could also include the project file if you want.

Yes, please include both. I think we'll want to use https://git-lfs.github.com though

**Comment by nhooyr** [comment]
Got the icon.


https://drive.google.com/file/d/1k4Tsb-4e5o5ZYGlOFLJfFdmzAoG962Oi/view?usp=sharing

**Comment by nhooyr** [comment]
Will be in the next release!
