### ISSUE TITLE
Warning VSCode version mismatch

### ISSUE THREAD

**Issue by rubn-g** [cdr/code-server#2315]
- Web Browser: Any
- Local OS: MacOS
- Remote OS: Ubuntu Server 20.04
- Remote Architecture: x86_64
- `code-server --version`: 3.7.1 2bf91ff6a6d1f29a8a93f97684177ccf5388cf34

This warning shows up like every second in the server log:
warn  vscode Version mismatch (9bde62fbd611a7a91c5f327fa43e0d06f1379169 instead of 2bf91ff6a6d1f29a8a93f97684177ccf5388cf34)

**Comment by nhooyr** [comment]
Huh interesting.

**Comment by nhooyr** [comment]
cc @code-asher

**Comment by rubn-g** [comment]
@nhooyr @code-asher I'm sorry, my fault. Just in case someone else have this issue in the future, it's because a window with an older version loaded was open. After reloading, warning is gone
