### ISSUE TITLE
Git Graph Extension Broken

### ISSUE THREAD

**Issue by asomethings** [cdr/code-server#2317]
## Steps to reproduce 
1. Install `Git Graph` from Extensions tab

2. Reload VSCode

3. Open Git Graph

4. Git Graph showes you broken ui with nothing showing

![image](https://user-images.githubusercontent.com/16171942/99352928-dec56680-28e6-11eb-8142-b6c9692a27be.png)

Git graph broked right after upgrading to 3.7.1. Tested in Chrome, Firefox.

## Log after opening git graph
```
GET https://url-of-code-server/webview//vscode-resource/file///root/.local/share/code-server/extensions/mhutchie.git-graph-1.27.0/media/out.min.css net::ERR_ABORTED 404 (Not Found)

GET https://url-of-code-server/webview//vscode-resource/file///root/.local/share/code-server/extensions/mhutchie.git-graph-1.27.0/media/out.min.js net::ERR_ABORTED 404 (Not Found)

GET https://url-of-code-server/webview//vscode-resource/file///root/.local/share/code-server/extensions/mhutchie.git-graph-1.27.0/media/out.min.js net::ERR_ABORTED 404 (Not Found)
```

- Web Browser: Chrome 86.0.4240.198 / Firefox Nightly 85.0a1
- Local OS: Windows 10 Pro x64 / macOS Big Sur
- Remote OS: Ubuntu 16.04
- Remote Architecture: x86_64
- `code-server --version`: 3.7.1 2bf91ff6a6d1f29a8a93f97684177ccf5388cf34

**Comment by pfitzseb** [comment]
This seems to be a general problem with resolving webview URIs; I'm seeing the same issue with multiple extensions.

**Comment by BenjaminBeichler** [comment]
@pfitzseb sorry for capturing this issue, but could this also affect vscode.image-preview ? I cannot view PNG files, which are in the project folders.

**Comment by pfitzseb** [comment]
Most likely. Basically every bit of custom UI you can find in VSCode is implemented as a Webview, all of which are broken if they try to load local resources.

**Comment by BenjaminBeichler** [comment]
Seems to be that #2336 is going to fix this, isn't it ?

**Comment by code-asher** [comment]
Fixed, will be in the next release!

**Comment by pfitzseb** [comment]
Thanks for the prompt fix!

**Comment by catthehacker** [comment]
This seems to still be an issue in `v3.9.3`

**Comment by lz1998** [comment]
This seems to still be an issue in `3.11.0 4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd`

**Comment by code-asher** [comment]
It's possible it was re-introduced, we had a bit of a snafu with the
patches.

**Comment by lz1998** [comment]
> It's possible it was re-introduced, we had a bit of a snafu with the patches.

`3.11.1` CSS is still incorrect.

**Comment by jsjoeio** [comment]
@lz1998 I think it has to do with resources being blocked due to CSP.

See https://github.com/cdr/code-server/pull/4131

This should be resolved in the next release.
