### ISSUE TITLE
Bug of extensions in IPadOS which can't be activated

### ISSUE THREAD

**Issue by KannaNyaa** [cdr/code-server#2318]
- Web Browser: Seveditor for Code-Server, or every browsers in iPad. 
- Local OS: Ubuntu 18.04 + iPadOS 14.2
- `code-server --version`: 3.7.1

In this morning, I update the Code-Server from 3.6.0 to 3.7.1.

At first, I found it running faster and  with less delay. 
However, When I use my iPad to Code, I find it can't active extensions like `Code Runner` or anyone else, just show: "activating extensions ..." then , no then. The code runner is not running.
I tried in my desktop's and Android's browsers, it ran perfectly. 

Also in ver 3.6.0, if I change the settings of the IDE, it will become effective in all of other devices.
But in 3.7.1, it can't sync with other devices. I need modify the settings in desktop, laptop, iPad. 
Is it a bug or new function to isolate the devices?

**Comment by labihi** [comment]
I am on version 3.6.2 of code-server and Code Runner doesn’t work for me either, same thing for build task feature and debug, I think it is a bug from iPadOS and the way webkit works from what I’ve found, probably since IPadOS 13 they changed something and it doesn’t work anymore.

Let me know if it ever worked for you on previous versions of both IpadOS and code-server.

**Comment by KannaNyaa** [comment]
> I am on version 3.6.2 of code-server and Code Runner doesn’t work for me either, same thing for build task feature and debug, I think it is a bug from iPadOS and the way webkit works from what I’ve found, probably since IPadOS 13 they changed something and it doesn’t work anymore.
> 
> Let me know if it ever worked for you on previous versions of both IpadOS and code-server.

:(. I haven't solve it. Thus, I rollback it to Ver.3.6.0. This version is quiet stable except that I need install extensions from `.vsix`

**Comment by labihi** [comment]
> > I am on version 3.6.2 of code-server and Code Runner doesn’t work for me either, same thing for build task feature and debug, I think it is a bug from iPadOS and the way webkit works from what I’ve found, probably since IPadOS 13 they changed something and it doesn’t work anymore.
> > Let me know if it ever worked for you on previous versions of both IpadOS and code-server.
> 
> :(. I haven't solve it. Thus, I rollback it to Ver.3.6.0. This version is quiet stable except that I need install extensions from `.vsix`

I understand, with version 3.6.0 are you able to use code runner or open build task? Can you try both and let me know please?

**Comment by KannaNyaa** [comment]
> > > I am on version 3.6.2 of code-server and Code Runner doesn’t work for me either, same thing for build task feature and debug, I think it is a bug from iPadOS and the way webkit works from what I’ve found, probably since IPadOS 13 they changed something and it doesn’t work anymore.
> > > Let me know if it ever worked for you on previous versions of both IpadOS and code-server.
> > 
> > 
> > :(. I haven't solve it. Thus, I rollback it to Ver.3.6.0. This version is quiet stable except that I need install extensions from `.vsix`
> 
> I understand, with version 3.6.0 are you able to use code runner or open build task? Can you try both and let me know please?

Sure, it can.  I think the 3.6.0 is the best version of code-server for iPad users. But I really want to use V3.7.1, because of its faster response :( 
Just wait for them to solve this Bug.. Or not, I'll try to view the source code and develop it by myself :(

**Comment by code-asher** [comment]
Yeah I think it's because of a change to how the web worker extension
host is loaded. The browser throws a security error because it doesn't
support loading web workers with a `data:` URI.

This should hopefully be fixed once we get update to VS Code 1.51.1.

**Comment by KannaNyaa** [comment]
> Yeah I think it's because of a change to how the web worker extension host is loaded. The browser throws a security error because it doesn't support loading web workers with a `data:` URI. This should hopefully be fixed once we update to VS Code 1.51.1.

Okey. Thanks for developing such a good tools for us.

**Comment by nhooyr** [comment]
Please test! Latest release has the updated VS Code version.

**Comment by mrmisto** [comment]
I tested it yesterday and it is working like a charm.

**Comment by nhooyr** [comment]
Awesome!
