### ISSUE TITLE
settings.json is not being loaded in v3.7.1

### ISSUE THREAD

**Issue by eElor** [cdr/code-server#2322]
I just updated code-server to v3.7.1 using conda and noticed that my old settings were not loaded. 
My settings file is not overwritten, but manually inspecting it in a code-server session ( Ctrl + , ) it appear to be empty. Even though the path opened is the correct one and the inspection of apparently the same file outside and inside code-server correctly displays the contents of `settings.json`, code-server is not correctly loading its contents. 

`user-data-dir` is automatically being set to `~/.local/share/code-server`. Manually setting `user-data-dir` to another dir (e. g. `/home/username/code-server`) containing a copy of `settings.json` doesn't help either. 

- Web Browser: Edge
- Local OS: Win10
- Remote OS: fedora
- `code-server --version`: 3.7.1 2bf91ff6a6d1f29a8a93f97684177ccf5388cf34

**Comment by code-asher** [comment]
Tracking for this here: https://github.com/cdr/code-server/issues/2274

The gist is that the settings seem to be stored in browser storage now rather than in the file on disk. I'm considering patching VS Code to revert that behavior.
