### ISSUE TITLE
C# OmniSharp does not install correctly

### ISSUE THREAD

**Issue by dev-kittens** [cdr/code-server#2325]
- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Alpine Edge (musl)
- Remote Architecture: amd64
- `code-server --version`: 3.7.1 2bf91ff6a6d1f29a8a93f97684177ccf5388cf34

**Note:** Neither the install script neither the manual install guide seem to support my platform, so I installed code-server from yarn.

Hi! I am trying to install the C# extension, but it gives me an error in the console, related to not being able to find mono.
Here is the full error log:
```
Starting OmniSharp server at 11/17/2020, 10:05:12 AM
    Target: /root/git/pluralkit/PluralKit.sln

OmniSharp server started.
    Path: /root/.local/share/code-server/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.3/run
    PID: 30810

/root/.local/share/code-server/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.3/run: line 27: /root/.local/share/code-server/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.3/bin/mono: No such file or directory
[ERROR] Error: OmniSharp server load timed out. Use the 'omnisharp.projectLoadTimeout' setting to override the default delay (one minute).
```

I have attempted to remove and reinstall the extension, but it gives me the same error.

**Comment by dev-kittens** [comment]
Oh, I see the issue. Alpine is being dumb and giving me a "not found" error when the error actually is that the installed mono is compiled for glibc instead of musl.
Is there a way to get a musl version of mono, or do I just need to move to glibc?

**Comment by dev-kittens** [comment]
I was able to fix this by installing the `gcompat` alpine package.

**Comment by nhooyr** [comment]
Glad you got it working @dev-kittens!

Yea unfortunately it looks like the extension fetches the `mono` binary so its' not something we could fix ourselves and would have to be reported to Microsoft.

**Comment by dev-kittens** [comment]
yeah, i was talking about this in the dotnet server earlier and i've submitted an issue upstream~
