### ISSUE TITLE
Settings file like settings.json is not located in server, located in client.

### ISSUE THREAD

**Issue by SJang1** [cdr/code-server#2326]
- Web Browser: Firefox
- Local OS: Ubuntu 20.04, Windows 10, Mac, iPadOS
- Remote OS: Ubuntu 20.04
- Remote Architecture: x64
- `code-server --version`: 3.7.1 2bf91ff6a6d1f29a8a93f97684177ccf5388cf34

It happens every time
1. go in code-server
2. change some settings
3. try to use from other client
-> Every setting is gone....

and there was no settings.json on ~/.local/share/code-server, I have founded on browser storage...
It needs to be on server, not client..

This makes extension auto update by on(default) but I need to turn it off, but every new client it is setted to on, need to reinstall extensions, etc..
![image](https://user-images.githubusercontent.com/29011440/99426002-f3394b80-2946-11eb-9259-3f955c6e35a9.png)

**Comment by SJang1** [comment]
It looks like it can be refrence of #2306 and maybe #2322

**Comment by fxxjdedd** [comment]
It should be a problem starting from 3.6.2: https://github.com/cdr/code-server/issues/2274

**Comment by code-asher** [comment]
Closing to track in https://github.com/cdr/code-server/issues/2274.
