### ISSUE TITLE
Release 3.7.1 never set code-server status as expired (`/healthz`)

### ISSUE THREAD

**Issue by wdalmut** [cdr/code-server#2327]
Currently with release 3.7.1 the healthcheck path /healthz replay always with status as *alive*. In release 3.6.2 if you are not connected to the IDE the status is marked as expired with the property lastHeartbeat correctly setted up.

```json
{
    "status": "alive",
    "lastHeartbeat": 1605640224173
}
```

The architecture is this one:

```
+-----+       +------------+
|     |       |            |
|  A  |       |            |
|  L  +------>+    EC2     |
|  B  |       |            |
|     |       |            |
+-----+       +------------+
```

I looked around a little bit and seems that the healthcheck HTTP call set IDE status as *active* so when we check if the IDE is used or not we always get the active status back.

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Ubuntu 20.04
- Remote Architecture: AWS EC2
- `code-server --version`: 3.7.1

**Comment by code-asher** [comment]
Thanks for reporting! It seems when we rewrote with Express we stopped
exempting /healthz from the heartbeat. Will fix asap.
