### ISSUE TITLE
Allow customizing Go Home button

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#2328]
- Web Browser: Brave
- Local OS: Windows
- Remote OS: Arch
- Remote Architecture: amd64
- `code-server --version`: 

I noticed in the newest update, there is this button
![image](https://user-images.githubusercontent.com/10422110/99444895-a9fae480-28d1-11eb-940a-baf17e4ab049.png)

which links directly to `
[microsoft/vscode](https://github.com/microsoft/vscode)

Is this a mistake? Official VSCode does not have this button

**Comment by code-asher** [comment]
Nope, not a mistake, it was added to VS Code web but not local VS Code.

I was going to patch it out but I think instead we're going to make it user-customizable: https://github.com/cdr/code-server/discussions/2245

**Comment by Merith-TK** [comment]
Oh? like a `--homepage "https://merith.tk"` flag?

**Comment by code-asher** [comment]
Yeah, exactly!

**Comment by nhooyr** [comment]
For now I patched it out to avoid confusion.

**Comment by jsjoeio** [comment]
This will be available in the next release. See [the upcoming docs](https://github.com/cdr/code-server/blob/master/doc/FAQ.md#how-do-i-customize-the-go-home-button) to learn how you'll be able to utilize it.

Closing via #2435
