### ISSUE TITLE
Folder in Explorer can not be closed

### ISSUE THREAD

**Issue by zlgxzswjy** [cdr/code-server#2337]
- Web Browser:chrome
- Local OS:mac os11
- Remote OS:Debian 10.1
- Remote Architecture:x86
- `code-server --version`:3.6.2

When I click "File" - "Close folder",but the folder still can not be closed in Explorer

**Comment by code-asher** [comment]
I think this is because if there is no folder we automatically load the
last directory. There is a `ew=true` parameter that we can use to clear
the last directory.

**Comment by nhooyr** [comment]
When I close a folder, the window reloads and `ew` is automatically set @code-asher 

v3.7.4

**Comment by nhooyr** [comment]
But it doesn't close the folder.
