### ISSUE TITLE
Install script uses standalone for Amazon Linux instead of rpm

### ISSUE THREAD

**Issue by jdogwilly** [cdr/code-server#2343]
The install script picks the standalone version instead of the rpm based version when installing on an Amazon Linux 2 ec2 instance. I manually had to use rpm to install, which is included in Amazon Linux 2. The script should also use rpm so that the systemctl service is installed as well

Running: ` curl -fsSL https://code-server.dev/install.sh | sh -s -- --dry-run` gives the following output
```
Amazon Linux 2
Unsupported package manager.
Installing standalone release archive v3.7.2 from GitHub releases.

+ Reusing ~/.cache/code-server/code-server-3.7.2-linux-amd64.tar.gz
+ mkdir -p ~/.local/lib ~/.local/bin
+ tar -C ~/.local/lib -xzf ~/.cache/code-server/code-server-3.7.2-linux-amd64.tar.gz
+ mv -f ~/.local/lib/code-server-3.7.2-linux-amd64 ~/.local/lib/code-server-3.7.2
+ ln -fs ~/.local/lib/code-server-3.7.2/bin/code-server ~/.local/bin/code-server

Standalone release has been installed into ~/.local/lib/code-server-3.7.2
Please extend your path to use code-server:
  PATH="$HOME/.local/bin:$PATH"
Then you can run:
  code-server
```

**Comment by code-asher** [comment]
We use the `OS` environment variable and /etc/os-release to determine
which method to use, what does Amazon Linux 2 have for those?

Or maybe we should base it off whether the `rpm` command is available
instead of the OS.

**Comment by jdogwilly** [comment]
It seems that the OS environment variable isn’t set in Amazon Linux 2. I notice also the script looks at `/etc/os-release` and that might be better, using the `ID_LIKE` field to pick among the options.

Example `/etc/os-release` file
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
````

**Comment by code-asher** [comment]
Thank you! We'll modify the script to check `ID_LIKE` in addition to
`ID`.

**Comment by oxy** [comment]
Planning to move all the distros over to `ID_LIKE`, here's what I documented from a bunch of Docker containers:
```
ubuntu:
	debian
raspbian:
	debian
debian:
	<none>
amazon linux/amzn:
	centos rhel fedora
centos:
	rhel fedora
rhel:
	fedora (source: https://opensource.com/article/18/6/linux-version)
fedora:
	<none>
opensuse-leap:
	suse opensuse
opensuse-tumbleweed:
	suse opensuse
alpine:
	<none>
arch:
	<none>
```

**Comment by nhooyr** [comment]
Whoops too trigger happy, will close after #2423 is merged.
