### ISSUE TITLE
Settings Keep Reverting to Default

### ISSUE THREAD

**Issue by nickian** [cdr/code-server#2352]
The latest version 3.7.2 has not been remembering my settings when I go back to the editor after a while. It seems to reset the settings I've changed (like autosave, word wrap, etc), and the color theme keeps getting reset back to the default after a session ends. Is this a known bug?

**Comment by ghokun** [comment]
Yes see https://github.com/cdr/code-server/issues/2274

**Comment by code-asher** [comment]
Closing as a duplicate. Hopefully should have a release with the fix out soon.
