### ISSUE TITLE
"Linked" terminals when multiple windows open

### ISSUE THREAD

**Issue by blaylockbk** [cdr/code-server#2356]
After the latest code-server release (3.7.2), when I open a second code-server window and type in the terminal, it is "linked" to the first window. 

Typing in the left window **1:bash** terminal results in the same being typed in the right **1: bash** terminal.
![image](https://user-images.githubusercontent.com/6249613/100001350-e3bb6780-2d77-11eb-8481-2e7129332926.png)

This doesn't appear to be an issue when I create a new terminal in both windows...
![image](https://user-images.githubusercontent.com/6249613/100001773-7b20ba80-2d78-11eb-880e-0a484820aca4.png)

- Web Browser: new Edge 87.0.664.41
- Local OS: Windows
- Remote OS: Linux (Red Hat)
- Remote Architecture: x86_64
- `code-server --version`: 3.7.2 a0db6723c1ef22b40d7ac0df5ac1bb9a92e4fe46

**Comment by code-asher** [comment]
Oh interesting. Terminals are automatically re-attached on page load so
it looks like we need to filter out terminals that are already attached
on a different page.
