### ISSUE TITLE
Zooming doesn't work

### ISSUE THREAD

**Issue by neighthan** [cdr/code-server#236]
- `code-server` version: v1.32.0-245
- OS Version: Ubuntu 16.04

## Description

Zooming doesn't work either using the hotkeys (e.g. ctrl+=) or through the command palette (e.g. View: Zoom In). Is this expected behavior? I didn't see it documented anywhere, though I've only just started testing out this project, so I assume it's a bug. If some limitation of running VS Code this way makes it hard/impossible to support zooming, is there a good workaround to make everything smaller/larger?

(This, and hotkeys being used for Chrome things instead of VS Code things, are the only discrepancies I've had so far in reproducing my local setup - thanks for the nice work! EDIT - being full screen changes the effect of the keyboard shortcuts? At least one shortcut that Chrome intercepted previously was used as I expected by VS Code. Though I can't seem to go fullscreen when focused on the tab with code-server's VS Code in it. But I digress..)

## Steps to Reproduce

1. Run `code-server`
2. Try to zoom in/out.

**Comment by sr229** [comment]
Confirming this issue on latest release. I think this is highly dependent on Electron API.

**Comment by kylecarbs** [comment]
We _can_ do this with CSS, but not actually adjust the zoom levels of the browser, unfortunately.

**Comment by kylecarbs** [comment]
Closing as there isn't a great solution for this.

**Comment by kylecarbs** [comment]
Actually, we should just disable the zoom commands.

**Comment by sr229** [comment]
@kylecarbs From what I can see, this seems to be manipulating the zoom in Electron, so I believe we should omit it entirely.

**Comment by jots** [comment]
While waiting for pull request to merge, you can add this to your keybindings so that browser action can take over.  the "-" in front of the command seems to disable it.
```
[
    { "key": "ctrl+shift+=",          "command": "-workbench.action.zoomIn" },
    { "key": "ctrl+=",                "command": "-workbench.action.zoomIn" },
    { "key": "ctrl+numpad_subtract",  "command": "-workbench.action.zoomOut" },
    { "key": "ctrl+-",                "command": "-workbench.action.zoomOut" },
]
```

**Comment by morningspace** [comment]
Hope that can be fixed soon... before that, the workaround mentioned above seems to have some limitation. After I modify the `keybindings.json` as above in `User` directory. I do not see zoom is working until I put the focus on something out of the editor... e.g. the browser address bar... it seems the short cuts will be absorbed/captured by vscode editor...
