### ISSUE TITLE
ws always disconnect

### ISSUE THREAD

**Issue by itheimalitong** [cdr/code-server#2363]
Git not  work ，  No source control providers

**Comment by itheimalitong** [comment]
Always disconnect

**Comment by nhooyr** [comment]
Can you add a screenshot of the problem?

**Comment by itheimalitong** [comment]
> Can you add a screenshot of the problem

Repost using rinetd，

**Comment by itheimalitong** [comment]
> Can you add a screenshot of the problem?

![Uploading image.png…]()

**Comment by itheimalitong** [comment]
![image](https://user-images.githubusercontent.com/29686610/100300540-3479cd00-2fd1-11eb-8cbc-c8b61bf39194.png)

**Comment by itheimalitong** [comment]
![image](https://user-images.githubusercontent.com/29686610/100300625-6a1eb600-2fd1-11eb-8560-49b6e229aaa1.png)


> > Can you add a screenshot of the problem
> 
> Repost using rinetd，

![image](https://user-images.githubusercontent.com/29686610/100300645-71de5a80-2fd1-11eb-8b2e-2b662ce3d36a.png)

**Comment by itheimalitong** [comment]
> Can you add a screenshot of the problem?

Error received from starting extension host

**Comment by nhooyr** [comment]
Closing as a duplicate of #2364
