### ISSUE TITLE
Console output not displayed

### ISSUE THREAD

**Issue by ZeeMoros** [cdr/code-server#2367]
- Web Browser: Google Chrome
- Local OS: Windows 10
- Remote OS: Alpine
- Remote Architecture: amd64
- `code-server --version`: 3.7.3 93fb76e4a71b1959ec2a23481ba2611200d714b2

When I enter a command in the console the output isn't automatically displayed:

![image](https://user-images.githubusercontent.com/42606668/100333704-33e23600-2fd3-11eb-849c-c15efdb835a1.png)

If I scroll or if I change the size of the console then the output is displayed :

![image](https://user-images.githubusercontent.com/42606668/100333835-54aa8b80-2fd3-11eb-9395-47a498a4fbbf.png)

Am I the only one experiencing this issue ?

**Comment by nhooyr** [comment]
Very weird, yes I can confirm I don't see this issue. Output is immediate for me.

Can you try firefox instead of chrome and see if you can reproduce?

**Comment by ZeeMoros** [comment]
It's the same in Firefox 83.0 (64-bit) and chrome 87.0.4280.66 (Official Build) (64-bit).

**Comment by nhooyr** [comment]
Interesting. Can you try debian as the remote OS?

**Comment by ZeeMoros** [comment]
No problem with the debian docker image --'

**Comment by ZeeMoros** [comment]
If you want the same environment I have I can share my dockerfile.

**Comment by nhooyr** [comment]
> If you want the same environment I have I can share my dockerfile.

Please do! This is the alpine image you're using right?

**Comment by ZeeMoros** [comment]
Yes it is :

Dockerfile :
```dockerfile
FROM alpine:3.12

RUN apk add --no-cache alpine-sdk bash libstdc++ libc6-compat npm libx11-dev libxkbfile-dev libsecret-dev && ln /usr/bin/python3 /usr/bin/python
RUN npm install -g --cache /tmp/npm-cache --unsafe-perm code-server && rm -r /tmp/npm-cache

RUN apk add --no-cache docker-cli docker-compose git openssh

COPY ./entrypoint.sh /entrypoint.sh

ENTRYPOINT [ "/entrypoint.sh" ]
```

Entrypoint : 
```sh
#!/bin/sh

FILENAME=/init-done

if [ ! -e "$FILENAME" ]; then
    mkdir /root/.ssh
    cd /root/.ssh/
    echo y | ssh-keygen -q -f ./id_rsa -N ""
    mkdir /data/.secret/ssh
    cp ./id_rsa.pub /data/.secret/ssh/
    touch $FILENAME
fi

echo Image code-server version v3.7.3

/usr/bin/code-server --bind-addr 0.0.0.0:80 --auth none
```

An example of compose :
```yaml
version: '2.4'

services:
  code-server:
    container_name: code-server
    build:
      context: .
      dockerfile: dockerfile
    volumes: 
      - code-server-data:/root
      - sock:/var/run/
      - data:/kikim-data
    networks: 
      - nginx
```

I use an nginx for identification and certification, and the sock is a docker.sock coming from a docker:dind (for context).

**Comment by nhooyr** [comment]
@ZeeMoros there's been quite a few fixes for the npm package so this may be resolved on the latest release. Please test!

**Comment by ZeeMoros** [comment]
I can't even open the terminal on the new version (3.8.0), I checked on the same two browsers and it the same.

I'll try to investigate later on today to see if this problem is on my end before opening a new ticket on this issue

**Comment by ZeeMoros** [comment]
I've just checked quickly and I've noticed this error during the installation :

```log
error /usr/lib/node_modules/code-server/lib/vscode/node_modules/native-is-elevated: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /usr/lib/node_modules/code-server/lib/vscode/node_modules/native-is-elevated
Output:
make: Entering directory '/usr/lib/node_modules/code-server/lib/vscode/node_modules/native-is-elevated/build'
make: printf: Operation not permitted
make: *** [iselevated.target.mk:105: Release/obj.target/iselevated/src/iselevated.o] Error 127
make: Leaving directory '/usr/lib/node_modules/code-server/lib/vscode/node_modules/native-is-elevated/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 4.19.0-12-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/code-server/lib/vscode/node_modules/native-is-elevated
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

It's not always the same package that fails but the error seems consistent. 

I don't have enough time right now to investigate further, sorry but it will have to wait probably until this weekend.

**Comment by ZeeMoros** [comment]
Well the good news is that the new bug I had is now fixed, it was probably caused by a package being bugged on edge (that I was using to get docker-compose ^1.26).

But now that I've successfully built my image the first bug is still there --' it will maybe get better in 3.8.1 🤞 

If you want me to test it further don't hesitate I'll have a bit more time in the following two days ^^

**Comment by ZeeMoros** [comment]
Still the same in 3.8.1 --'

**Comment by code-asher** [comment]
Thank you for testing this! Sounds like we'll need to dig further into
the cause.
