### ISSUE TITLE
can not load the user setting

### ISSUE THREAD

**Issue by canjuly** [cdr/code-server#2368]
- Web Browser: chrome 86.0.4240.198
- Local OS: win10 x64
- Remote OS: Debian 10(docker container)
- Remote Architecture: arm64
- `code-server --version`: v3.7.1

In the user setting, I set the settings.json as follow:
![微信图片_20201126210058.png](https://i.loli.net/2020/11/26/8UyplkrcwWO7ZPi.png)

but when I closed the tabs, change a computer and open a new tab, it disappeared:
![微信图片_20201126210418.png](https://i.loli.net/2020/11/26/ET4UspYQCmJLMxi.png)

This problem confused me so that I could not save my user settings.

**Comment by nhooyr** [comment]
This is fixed in https://github.com/cdr/code-server/releases/tag/v3.7.3!

So you just need to upgrade.
