### ISSUE TITLE
Copy-paste not working well in terminal

### ISSUE THREAD

**Issue by ihainan** [cdr/code-server#237]
- `code-server` version: 1.31.0-20-x86_64-linux
- OS Version: Ubuntu 18.04.1 LTS
- Client Info: macOS 10.14.3  + Chrome 72.0.3626.121

I've read Issue #161 and tried @avelino 's solution, but the copy-paste function still can't work **in terminal**. 

## Steps to Reproduce

I recorded [a video](https://youtu.be/YyZE8KHw1SQ) to show how to reproduce this issue: 

1. Select text in terminal and press <⌘ + C> to copy text
2. Press <⌘ + V> to paste text (not working)
3. Go to the editor area, then return back to the terminal
4. Press <⌘ + V> again

**Comment by avelino** [comment]
VSCode configuration does not work for the terminal, it is editor configuration

**Comment by ihainan** [comment]
Thanks @avelino. I can't find a place to configure the terminal, so it's a bug of code-server, right?

**Comment by naufraghi** [comment]
Similar problem on Linux, both with C-c C-v and X11 selection clipboard / middle click paste.

**Comment by shi-yan** [comment]
I couldn't copy from the terminal and paste into the text editor

**Comment by 4oo4** [comment]
What browsers is everyone using? This problem only happens with me when using Firefox, with Chromium Ctrl + Shift + V works. One thing I noticed is that when I right click in the terminal, in Chromium it says the key combo, while in Firefox it says "must use keybind".

 * Server OS: Ubuntu 16.04 (code-server running in Ubuntu 18.04 docker container)
 * Client OS:  Ubuntu 16.04
 * Firefox: 65.0.1
Chromium: 73.0.3664.3 (Developer Build)

**Comment by shi-yan** [comment]
I use the latest chrome.

copy and pasting doesn't work for me even with the right click menu. 

it's hard to say when it works and when it doesn't. Sometimes, I had trouble copying and pasting at a fresh launch. Then I saw chrome ask me if I allow the page to access clipboard. Sometimes, this notification won't show. 

At one point, I also saw an error pop up from the bottom right corner saying electron.clipboard isn't a function or something. the error message went away pretty quickly, I didn't capture it.

**Comment by syntaxhacker** [comment]
Sometimes cant even type or paste into editor when terminal is open ¯\_(ツ)_/¯

**Comment by shi-yan** [comment]
I realized my copy and pasting issue might be due  to "copy on select".

when I try to paste into the editor, I first select the text I want to replace.

it seems that during selection, the selected text gets copied into the clipboard, so when I paste, it actually pastes the same content as my selection. This made me thinking pasting didn't work.

But I googled, while you can enable "copy on select" with some extension, the default vscode won't do it.

**Comment by yamajik** [comment]
Anyone has ideas？This troubles me.

**Comment by cristiano-belloni** [comment]
> it seems that during selection, the selected text gets copied into the clipboard, so when I paste, it actually pastes the same content as my selection

Same behaviour for me (serving code-server from Ubuntu Bionic, accessing it with Chrome / mac os). Copy on select is always on; it'd be great to be able to disable it.

**Comment by kylecarbs** [comment]
This might be fixed now. We've made some changes to the copy/paste.

**Comment by MostHated** [comment]
> This might be fixed now. We've made some changes to the copy/paste.

Fresh install here on a Google Cloud Platform Ubuntu (specs below from Neofetch). I canno't paste into the terminal.

```
            .-/+oossssoo+/-.               mosthated@hpcsdev 
        `:+ssssssssssssssssss+:`           ----------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 18.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: Google Compute Engine 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.15.0-1030-gcp 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 5 hours, 14 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 921 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.19 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Terminal: /dev/pts/4 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel Xeon (1) @ 2.300GHz 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Memory: 2069MiB / 3693MiB 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+ 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.                           
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/ 
  +sssssssssdmydMMMMMMMMddddyssssssss+ 
   /ssssssssssshdmNNNNmyNMMMMhssssss/ 
    .ossssssssssssssssssdMMMNysssso. 
      -+sssssssssssssssssyyyssss+- 
        `:+ssssssssssssssssss+:` 
            .-/+oossssoo+/-. 

```

**Comment by MostHated** [comment]
Just an update to this. It seems like Firefox has the most issue. In Chrome and Vivaldi it works just fine if you make sure to set clipboard permission.

**Comment by shahidul56** [comment]
step:1 , make sure code server is running on "https://" not http
step:2, In Chrome set clipboard permission go to `chrome://settings/content/clipboard` and add your server url 
step3: now ctrl + v will work in code server

**Comment by deansheather** [comment]
If this is a Chromium permissions issue we might want to add a notification when users try the shortcut for the first time on Chromium browsers. CC: @code-asher @kylecarbs

**Comment by NGarate** [comment]
For me it also fails sometimes in safari on iPadOs beta 3

**Comment by jo32** [comment]
fail on chrome Version 77.0.3865.120 (Official Build) (64-bit) + Mac OS 10.14.4

**Comment by sr229** [comment]
@jo32 refer to @shahidul56's workaround. This is a Chrome permissions issue.

**Comment by code-asher** [comment]
Closing to consolidate into #1106.

**Comment by qm693514099** [comment]
@shahidul56   thx very much! it works for me!

**Comment by dentropy** [comment]
I have the same problem in firefox 74.0 in Windows. Paste works fine on my chrome based browser.

**Comment by nhooyr** [comment]
@dentropy See #1106

**Comment by winetoys** [comment]
is this solved, I am still facing it, I mean i can copy but not paste

**Comment by nhooyr** [comment]
@winetoys Please see #1106

**Comment by xinmans** [comment]
For me it also fails sometimes in safari on iPadOs
