### ISSUE TITLE
Installation error in Centos

### ISSUE THREAD

**Issue by marcelloinfoweb** [cdr/code-server#2380]
Install in CentOS 6.10 Final

> /root/.local/lib/code-server-3.7.3/lib/node -v
/root/.local/lib/code-server-3.7.3/lib/node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by /root/.local/lib/code-server-3.7.3/lib/node)
/root/.local/lib/code-server-3.7.3/lib/node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /root/.local/lib/code-server-3.7.3/lib/node)
/root/.local/lib/code-server-3.7.3/lib/node: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by /root/.local/lib/code-server-3.7.3/lib/node)
/root/.local/lib/code-server-3.7.3/lib/node: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /root/.local/lib/code-server-3.7.3/lib/node)
/root/.local/lib/code-server-3.7.3/lib/node: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /root/.local/lib/code-server-3.7.3/lib/node)
/root/.local/lib/code-server-3.7.3/lib/node: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /root/.local/lib/code-server-3.7.3/lib/node)
/root/.local/lib/code-server-3.7.3/lib/node: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/.local/lib/code-server-3.7.3/lib/node)

- Web Browser: All
- Local OS:
- Remote OS: Centos 6.10
- Remote Architecture:
- `code-server --version`: Lasted

**Comment by nhooyr** [comment]
CentOS 6.10 is not supported by the standalone releases.

You'll have to use the npm package. See https://github.com/cdr/code-server/blob/v3.7.3/doc/install.md#yarn-npm
