### ISSUE TITLE
how to disable autoupdate ?

### ISSUE THREAD

**Issue by momiji** [cdr/code-server#2384]
- Web Browser: Not relevant
- Local OS: Linux RHEL 7.9
- Remote OS: Not relevant, but Windows 10
- Remote Architecture: x86
- `code-server --version`: 3.7.3 93fb76e4a71b1959ec2a23481ba2611200d714b2

Hello,

We're using code-server (installed manually from the tag.gz) on server with no access to internet, and we have several error messages on the console:
```
[2020-12-01T14:32:53.742Z] error Failed to get latest version {"error":"getaddrinfo ENOTFOUND api.github.com"}
```

An option was previsouly available to prevent update, any other way to do it ?

Thank you.

**Comment by code-asher** [comment]
We've implemented a flag to disable the update checker (it won't auto-update btw and is just informative although that doesn't really make a difference in your case) and it'll be in the next release! I'll add this to the milestone for tracking.

**Comment by code-asher** [comment]
Ah nvm we already have https://github.com/cdr/code-server/issues/2361 in the milestone. Would be neat if GitHub had a separate section for fixed issues that aren't yet in a release or something to make finding duplicates easier.

**Comment by momiji** [comment]
Thank you, I've tested and works like a charm!
I didn't find it when searching in issues, but I won't say I'm a github search expert :)
Good work!
