### ISSUE TITLE
Extension request: CodeTour

### ISSUE THREAD

**Issue by bpmct** [cdr/code-server#2392]
- [ ] Extension name: CodeTour
- [ ] Extension GitHub or homepage: https://github.com/vsls-contrib/codetour

This allows a developer to get a live tour of the codebase with injected "comments" similar to Google Docs.

**Comment by cmoog** [comment]
Thank you for your request! The extension is now live in the code-server extension marketplace.

**Comment by cmoog** [comment]
Investigating an issue with the asset built from source...

**Comment by cmoog** [comment]
Thank you for your request! The extension is now live in the code-server extension marketplace.
