### ISSUE TITLE
Allow --link name to start with a number

### ISSUE THREAD

**Issue by scsmithr** [cdr/code-server#2395]
It would be nice to run `docker run -it codercom/code-server:latest --link` and not have to specify an argument to link. However this will fail most of the time with `Name must conform to regex ^[a-z][a-z0-9_]{0,50}$` because `--link` defaults to host name (I think), and docker host names start with a number more often than they start with a letter.

**Comment by nhooyr** [comment]
cc @sreya

**Comment by nhooyr** [comment]
We can strip leading numbers before passing to the cloud agent but I agree, I don't see a good reason why leading numbers shouldn't be allowed.

**Comment by sreya** [comment]
This has already been fixed server-side, should be fixed in the next release for code-server

**Comment by nhooyr** [comment]
Awesome!

**Comment by nhooyr** [comment]
Marking this as fixed then, just need to mention it in the release notes.
