### ISSUE TITLE
I want to use http to get rid of those error prompts, so annoying prompts

### ISSUE THREAD

**Issue by itheimalitong** [cdr/code-server#2408]
I want to use http to get rid of those error prompts, so annoying prompts

**Comment by itheimalitong** [comment]
![image](https://user-images.githubusercontent.com/29686610/101246113-256ee980-374c-11eb-829e-6afa21f914bd.png)
把这个提示去掉吧

**Comment by itheimalitong** [comment]
![image](https://user-images.githubusercontent.com/29686610/101246118-361f5f80-374c-11eb-8047-0fd09c17ac30.png)
Can remove this prompt

**Comment by Stradivario** [comment]
Just use http link instead of https or create a valid SSL certificate for your VsCode.
Or you can put nginx in front of everything.

Regards

**Comment by itheimalitong** [comment]
> Just use http link instead of https or create a valid SSL certificate for your VsCode.
> Or you can put nginx in front of everything to deal with certificates.
> 
> Regards

How to solve the problem just using http

**Comment by code-asher** [comment]
I'm sorry these are causing such a headache for you!

Unfortunately we don't have a way to remove the prompts.

`--link` is definitely your best option here. It'll handle everything.

If you can't use that, you could use `--cert` and code-server will
generate its own certificate. The browser will tell you it's insecure
and you'll have to click past it but it's still better than plain HTTP.
