### ISSUE TITLE
white screen after login

### ISSUE THREAD

**Issue by sweatpotato13** [cdr/code-server#2411]
when I after login with https It appear white screen only

and chrome developer console said

```bash
GET https://mydomain/static/11f53784c58f68e7f4c5b3b8dae9407caa41725b/usr/local/Cellar/code-server/3.7.4/libexec/lib/vscode/out/vs/workbench/workbench.web.api.nls.js net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
```

but http is working 

I am using nginx with letsencrypt

please help me

- Web Browser: chrome
- Local OS: macos bigsur
- Remote OS: macos bigsur
- Remote Architecture: x86
- `code-server --version`: 3.7.4

**Comment by JammSpread** [comment]
May I suggest you try running `chown -R nginx:nginx /var/lib/nginx`? Might be a permission issue with Nginx.

**Comment by sweatpotato13** [comment]
> May I suggest you try running `chown -R nginx:nginx /var/lib/nginx`? Might be a permission issue with Nginx.

it doesnt have ```/var/lib/nginx```

**Comment by JammSpread** [comment]
Maybe nginx:nginx isn't the user Nginx is under. `sudo chown -R nobody:admin /usr/local/var/run/nginx/proxy_temp` or `sudo chown -R nobody:nobody /usr/local/var/run/nginx/proxy_temp` might work. I suggest this because maybe Nginx doesn't have the proper permissions to take the file from its cache folder.

**Comment by JammSpread** [comment]
If even that doesn't work you might want to look into the cache settings or increasing the space of the installation directory of Nginx.

**Comment by sweatpotato13** [comment]
it works thanks @JammSpread

**Comment by JammSpread** [comment]
Glad to help! 👍
