### ISSUE TITLE
PDF content blocked over /proxy/<port>/

### ISSUE THREAD

**Issue by c0ppelius** [cdr/code-server#2413]
First, let me thank you for a great product. My general workflow involves a lot of drawing and frequent use of latex. An iPad makes a perfect travel companion once it comes with a functional latex IDE. Code-server makes that happen. The only issue is the built-in pdf viewer. (Other pdf viewer extensions can be substituted but do not have built in synctex nor behave as smoothly.) In Latex Workshop extension currently, the pdf viewer listens on localhost:<random port> which is not accessible. 

The best VS Code extension for latex is currently Latex Workshop. Unfortunately, the developers there have chosen to not support code-server. As such, one needs to hack in a solution to point their pdf server at code-server.

Of the two methods, available subpaths or subdomains, I chose subpaths. I [modified the source](https://github.com/c0ppelius/latex_code-server) to include a code-server flag and url (`https://code.example.com` below) in the extension settings. The result defaults to the existing setup if the code-server flag is not enabled. Otherwise, it directs the pdf server to serve the pdf file at `https://code.example.com/proxy/<port>/`  Here is a complete example URL generated: 
```
https://code.example.com/proxy/41467/viewer.html?file=pdf..JTJGaG9tZSUyRm1hdHRoZXdyb2JlcnRiYWxsYXJkJTJGbGV0dGVycyUyRkFsZXhfRHVuY2FuJTJGZHVuY2FuX2JyZWFrdGhyb3VnaC5wZGY
```
The behavior in code-server is shown [here](https://github.com/c0ppelius/pictures/blob/main/Screenshot1.png) and if I try to open directly in Firefox I see the toolbox for the pdf viewer but [no content](https://github.com/c0ppelius/pictures/blob/main/Screenshot2.png). The pdf server is poking through but the pdf itself is not. 

My approach is very similar to that of @lukas-hetzenecker taken at #https://github.com/James-Yu/LaTeX-Workshop/pull/2341 except that subdomains are implemented there. 

- Web Browser: Chrome
- Local OS: Ubuntu 18.04
- Remote OS: Debian Buster
- Remote Architecture: x86
- `code-server --version`: 3.7.4

When adding the extension to your code-server install, I have found it loaded incompletely (even with multiple versions of the official release) unless one rigorously follows the following steps:
- Uninstall an existing Latex Workshop extension 
- Close any existing browsers
- Reload code-server 
- Install from the vsix file from the command line
- Reload code-server
- Browse back to your install. 

You can find the modified vsix [here](https://github.com/c0ppelius/latex_code-server/blob/master/latex-workshop-modified-8.15.0.vsix).

**Comment by c0ppelius** [comment]
Some progress. Removing the content security policy on the generated html file allowed rendering in code-server to (look like)[https://github.com/c0ppelius/pictures/blob/main/Screenshot3.png] the external browser. Inspecting the source, it looks like some js files are not running to generate content, probably (viewer.js)[https://github.com/c0ppelius/latex_code-server/blob/master/viewer/viewer.js].

**Comment by code-asher** [comment]
I tried to replicate this but in my case the PDF server keeps giving me
a 500 so I'll need to look more into that.

As for the JS files not running, this is just a guess but maybe they're
requesting against the root (`/viewer.js`) instead of against the proxy
path (`/proxy/<port>/viewer.js`).

**Comment by code-asher** [comment]
Related: https://github.com/cdr/code-server/issues/1862

**Comment by c0ppelius** [comment]
If you used the latest version of [https://github.com/c0ppelius/latex_code-server](https://github.com/c0ppelius/latex_code-server), then that might be a problem. I ended going back using subdomains instead of subpaths in the current version. The [original](https://github.com/c0ppelius/latex_code-server/tree/16c119a6103bae17f897c364446c36da8a65ce5f) still has subpaths. 

I should emphasize that subdomains works out of the box (from [https://github.com/lukas-hetzenecker/LaTeX-Workshop](https://github.com/lukas-hetzenecker/LaTeX-Workshop)) so subpaths isn't a pressing issue.

**Comment by c0ppelius** [comment]
Root viewer.js vs proxy path viewer.js is a problem. It previously could not locate it and other scripts. But, it doesn't seem to solve the issue. In fact, the behavior seems the same. The tool bar renders but not the pdf inside the main container.

**Comment by t-huyeng** [comment]
@c0ppelius any news on getting the pdf viewer working? I think this could be a really a nice piece to push code-server even more.

**Comment by c0ppelius** [comment]
95% all the issues lie in how the latex-workshop is written (the url for pdf viewer server in particular) so this isn't a code-server problem. It is only a problem if you want to use the built in pdf viewer with the latex-workshop extension (say because you like the synctex integration and don't want to write) while using code-server. If you specifically want a working pdf viewer in the latex-workshop extension, you can modify the source code as shown (here)[https://github.com/James-Yu/LaTeX-Workshop/pull/2341/files] and compile the vsix yourself. I did this and have been using it without issue for months.

**Comment by lamnguyenx** [comment]
> 95% all the issues lie in how the latex-workshop is written (the url for pdf viewer server in particular) so this isn't a code-server problem. It is only a problem if you want to use the built in pdf viewer with the latex-workshop extension (say because you like the synctex integration and don't want to write) while using code-server. If you specifically want a working pdf viewer in the latex-workshop extension, you can modify the source code as shown [here](https://github.com/James-Yu/LaTeX-Workshop/pull/2341/files) and compile the vsix yourself. I did this and have been using it without issue for months.

Hi c0ppelius. Could you push the latest compiled VSIX to GitHub? I guess many people like me would also need it!

**Comment by modaresimr** [comment]
I have created the extension working in 9.2.2
https://github.com/modaresimr/LaTeX-Workshop/blob/master/latex-workshop-9.2.2.vsix

**Comment by jdrusso** [comment]
Thanks for that @modaresimr -- unfortunately, that build doesn't work for me (code-server 4.5.1, from the `lscr.io/linuxserver/code-server:latest` Docker image). When I try to open a PDF for preview, a blank tab with a message that it's opening the PDF opens for a bit, then the tab closes.

**Comment by modaresimr** [comment]
I have merged it with the latest code of latex workshop https://github.com/James-Yu/LaTeX-Workshop/pull/3639
In the new version it has been resolved :)

**Comment by modaresimr** [comment]
It is already merged to the code and in the next version of latex workshop you can see it :)
