### ISSUE TITLE
Nothing show in explorer

### ISSUE THREAD

**Issue by sweatpotato13** [cdr/code-server#2420]
![ss](https://i.imgur.com/27OXHAr.png)

when I run the code-server

It doesn't show any files in explorer

EDIT: in terminal, ls, cd is also doesnt work

it said ```ls: .: Operation not permitted```

- Web Browser: Chrome v87
- Local OS: MacOS BigSur
- Remote OS:  MacOS BigSur
- Remote Architecture: x86
- `code-server --version`: 3.7.4 11f53784c58f68e7f4c5b3b8dae9407caa41725b

**Comment by oxy** [comment]
I'm not sure if this is a bug, or if this is to do with the macOS Sandbox restricting file access to `~/Documents` - can you check with another directory?

**Comment by sweatpotato13** [comment]
> I'm not sure if this is a bug, or if this is to do with the macOS Sandbox restricting file access to `~/Documents` - can you check with another directory?

another directory is also doesn't work

**Comment by oxy** [comment]
Can you visit System Preferences -> Security & Privacy -> Privacy -> Files and Folders and ensure that your Terminal has access to those folders?
![macOS TCC screenshot](https://user-images.githubusercontent.com/19502779/101568637-f0d38a00-39f8-11eb-97b7-8105ec05caab.png)

**Comment by uajqq** [comment]
I’m having this same problem, even after I’ve verified that Terminal has access to Documents, Download, and Desktop folders. I can access any file from any other folders, and create files/folders in Documents, Download, and Desktop, but `code-server` can’t see any files in those three locations.

**Comment by tech-with-bolow** [comment]
I was using `brew services start code-server` to register `code-server` as a background service so it keeps running whenever I restart my computer. I don't see any files in the file explorer and the terminal shows `Operation not permitted`.

After I stopped the background service with `brew services stop code-server`, and run the `code-server` command directly in the terminal everything works now.
