### ISSUE TITLE
Unable to use code-server at all

### ISSUE THREAD

**Issue by ChokunPlayZ** [cdr/code-server#2432]
- Web Browser: Firefox
- Local OS: Windows 10 2004
- Remote OS: Ubuntu 18.04.5 LTS (VM)
- Remote Architecture: x86_64
- `code-server --version`: 3.7.4 11f53784c58f68e7f4c5b3b8dae9407caa41725b

I'm able to access the code-server but it says disconnected and it attempting to reconnect but unsuccessful
I know that the problem comes from the server

here is the log I been getting
https://pastebin.com/vPqcYkTw

I tried running both of these commands and still the same problem
`npm rebuild` `npm install`

**Comment by code-asher** [comment]
Could you try going into `lib/vscode` and then running `npm rebuild`?
That should get rid of the version mismatch errors.

This can happen if you run code-server with a different version of Node
than the one it was built with.

**Comment by ChokunPlayZ** [comment]
> 
> Could you try going into `lib/vscode` and then running `npm rebuild`? That should get rid of the version mismatch errors. This can happen if you run code-server with a different version of Node than the one it was built with.

I tried to do rebuild in lib/vscode and this error comes up
[2020-12-10T01_17_06_577Z-debug.log](https://github.com/cdr/code-server/files/5669664/2020-12-10T01_17_06_577Z-debug.log)

and I don't know exactly how to run different version of node
I just installed nodejs with `sudo apt install nodejs` command
