### ISSUE TITLE
Error loading webview: Service Workers are not enabled in browser. Webviews will not work.

### ISSUE THREAD

**Issue by oonqt** [cdr/code-server#2433]
Version: 3.7.4
OS: Ubuntu 20.04
Client: Chrome 87.0.4280.88

Whenever I go to open anything in a webview, whether it be an image, or a markdown document with the markdown preview extension, I get the following error: Error loading webview: Service Workers are not enabled in browser. Webviews will not work.

The webview **still opens**, although I get the above error saying that the webview couldn't load.

**Comment by oxy** [comment]
Tried to repro on both Chromium and Firefox on Fedora, but could not; I tried both http on localhost, and `--link`, but no such error showed up. Can you help me reproduce it with something specific?

**Comment by sar** [comment]
> Tried to repro on both Chromium and Firefox on Fedora, but could not; I tried both http on localhost, and `--link`, but no such error showed up. Can you help me reproduce it with something specific?

Just reproduced it on fedora/chrome (and firefox) when clicking on extensions in the marketplace. It launches the preview with markdown rendering and emits this error.

**Comment by code-asher** [comment]
Is this on a domain over http? If the browser thinks the connection is
insecure it won't enable service workers which will cause this error.

Rendering markdown in webviews will still work in this case but there is
other functionality that webviews provide which will not.

The only solution if this is the case is to use a secure connection
(https).

**Comment by oonqt** [comment]
> Is this on a domain over http? If the browser thinks the connection is insecure it won't enable service workers which will cause this error. Rendering markdown in webviews will still work in this case but there is other functionality that webviews provide which will not. The only solution if this is the case is to use a secure connection (https).

Yes it is. I'm connecting via HTTP on my local network. If I connect to code-server remotely via my domain over HTTPS, this does not happen.
