### ISSUE TITLE
Package 'python-certbot-nginx' has no installation candidate

### ISSUE THREAD

**Issue by mayanxoni** [cdr/code-server#2436]
**Command executed:**
`$ sudo apt install -y nginx certbot python-certbot-nginx`

**Error:**
> E: Package 'python-certbot-nginx' has no installation candidate

**Detailed output:**
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Package python-certbot-nginx is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   python3-certbot-nginx
> 
> E: Package 'python-certbot-nginx' has no installation candidate

**Comment by nhooyr** [comment]
Done :)
