### ISSUE TITLE
Feature request: U2F support

### ISSUE THREAD

**Issue by tidux** [cdr/code-server#2443]
Right now code-server depends solely on password authentication, which is a weakness.  If you use code-server over the Internet from a compromised client device, your credentials get stolen.  With U2F they'd still be locked out so long as they didn't physically steal a registered key device.  My end goal here is to enable code-server to work on shared PCs like at a library or Internet cafe if we ever go back to normal, or just to protect against keyloggers.

**Comment by code-asher** [comment]
We don't have any plans to implement other authentication modes at the moment. Our recommendation is to put something in front of code-server to handle authentication (this is more secure in the long run anyway).

Related: https://github.com/cdr/code-server/issues/1625
