### ISSUE TITLE
Use a tiniest base image for Docker

### ISSUE THREAD

**Issue by jylenhof** [cdr/code-server#2459]
Instead of using debian as image, use a slim image

**Comment by jylenhof** [comment]
Quite some gain (Perhaps a part of the gain here is due to arm deb package not on my server, more tidy to come)

root  ~  docker image ls
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
codercom/code-server-amd64   3.7.4               899c7b2ff7e8        13 minutes ago      717MB
codercom/code-server         latest              b425735a3231        2 weeks ago         873MB
 root  ~ 

**Comment by nhooyr** [comment]
So I looked into this.

See https://stackoverflow.com/questions/59794891/how-does-debian-differ-from-debian-slim

I got

```
$ diff debian-stable-pkgs.txt debian-stable-slim-pkgs.txt
23,24d22
< iproute2					install
< iputils-ping					install
35,36d32
< libcap2:amd64					install
< libcap2-bin					install
40d35
< libelf1:amd64					install
53d47
< libmnl0:amd64					install
77d70
< libxtables12:amd64				install
```

As the additional packages. `iproute2` and `iputils-ping` are extremely useful as a developer. We can add them in manually but I think #2488 is the way to go here.
