### ISSUE TITLE
Installation of an extension in a user customized image

### ISSUE THREAD

**Issue by jylenhof** [cdr/code-server#2464]
To create a docker image file with some already installed extension (and so the actual needed restart of the container to have some extension operational). I did modify the Dockerfile to install some extensions, here the part modifled :

USER 1000
ENV USER=coder
WORKDIR /home/coder
# Some Installations with the user "1000"
# About ~ 100Mb per extension 
RUN code-server --install-extension vscoss.vscode-ansible
RUN code-server --install-extension ms-vscode.azurecli
RUN code-server --install-extension dhoeric.ansible-vault
RUN code-server --install-extension samuelcolvin.jinjahtml
RUN code-server --install-extension HashiCorp.terraform
RUN code-server --install-extension ms-python.python
RUN code-server --install-extension redhat.vscode-yaml
ENTRYPOINT ["/usr/bin/entrypoint.sh", "--bind-addr", "0.0.0.0:8080", "."]

You should probably document it somewhere as it could nice for others people !

**Comment by nhooyr** [comment]
Hi @jylenhof 

It's documented at https://github.com/cdr/code-server/blob/v3.7.4/doc/FAQ.md#where-are-extensions-stored

and in `--help`.
