### ISSUE TITLE
Document npm install requirements for alpine linux

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#2474]
See https://github.com/cdr/code-server/issues/1906#issuecomment-744621921

**Comment by oxy** [comment]
Hey - started with a fresh docker container, and ran `apk add build-base curl libxkbfile-dev libsecret-dev libx11-dev`, but I still get a 500 with a bunch of errors - there seem to be additional dependencies.

See https://gist.github.com/oxy/9e3001beb0dcfcb18fe9651d2520b74d for the log.

**Comment by nhooyr** [comment]
Does #2479 work @oxy?

**Comment by oxy** [comment]
Yep, it does! Tested it in a new alpine container via `podman run -p 8080:8080 -it alpine`.

**Comment by nhooyr** [comment]
@oxy oo, I didn't know you used podman.

Thoughts on podman vs docker?

**Comment by oxy** [comment]
Only used podman because it came configured by default on Fedora Silverblue - been migrating from Arch to Fedora this week :p

**Comment by nhooyr** [comment]
@oxy I've had weird issues with fedora/podman in the past so lmk how it goes!
