### ISSUE TITLE
python extension refactoring tools not working

### ISSUE THREAD

**Issue by blaylockbk** [cdr/code-server#2475]
The Python extension refactoring tools "Extract Variable" "Extract Method" and "Sort Imports" do not do anything. These are the errors:
![image](https://user-images.githubusercontent.com/6249613/102275841-db6bcd80-3eda-11eb-88ea-801806b90b87.png)
![image](https://user-images.githubusercontent.com/6249613/102275901-f3435180-3eda-11eb-81fc-f97fbb637e5b.png)
![image](https://user-images.githubusercontent.com/6249613/102275872-e6bef900-3eda-11eb-98fc-b06a8fd2e82d.png)

- Web Browser: New Edge
- Local OS: Windows
- Remote OS: Linux
- Remote Architecture: Linux
- `code-server --version`: 3.7.4 11f53784c58f68e7f4c5b3b8dae9407caa41725b

**Comment by blaylockbk** [comment]
Oh, I _think_ this is a feature that requires PyLance, which is not an open-source extension and can't be added to code-server, right?)
https://devblogs.microsoft.com/python/python-in-visual-studio-code-december-2020-release/

**Comment by oxy** [comment]
What version of the Python extension do you have installed? Refactor used to not be a PyLance only feature; I think it could be a bug.

**Comment by blaylockbk** [comment]
It is `v2020.12.422005962`. I also tried with the previous version v2020.11.37

**Comment by clouraa** [comment]
Hello, I had the same problem and managed to solve it by following these steps:
Remove all python related extensions
Go to /config/extensions from the terminal delete the ms-python folder
Restart the code-server
Download the ms-python.python-2020.10.332292344 version from the github extension page and install manually
Restart and configure the python interpreter

**Comment by oxy** [comment]
Hey there; tested this with the latest versions (code-server v3.10.2, python v2021.5.926500501, jupyter v2021.6.832593372) and it all works. Closing.
