### ISSUE TITLE
Creating a "latest" tag for your code-server releases (which helps when automating container rebuilds) ...

### ISSUE THREAD

**Issue by nmvega** [cdr/code-server#2481]
Hello Friends:

Can you create a `latest` tag for your releases so that when we, say, rebuild `docker` images, we can always refer to the same `URL` (i.e. the one with the `latest` tag)?

For example:

Instead of referring to this:
```
https://github.com/cdr/code-server/releases/download/v3.7.4/code-server-3.7.4-amd64.rpm
```

We refer to this instead:
```
https://github.com/cdr/code-server/releases/download/latest/code-server-amd64.rpm
```

Is this possible? I always have to check if the URL was updated. `=:)`

P.S. You guys are doing great work and I sincerely appreciate it!

Thank you!

**Comment by code-asher** [comment]
Interesting, I'm not sure about this since I've always seen tags as more or less immutable. Would it work for you to query for the latest release the way we do in our install script?

https://github.com/cdr/code-server/blob/cb11e1f75054ea1faa79f8736d30f568582f1a50/install.sh#L74-L80

**Comment by nmvega** [comment]
@code-asher Ah, okay. I should be able to work with that script to get the version string. Thank you! :blush:

**Comment by code-asher** [comment]
Awesome! In that case I'll go ahead and close this. 😄
