### ISSUE TITLE
remoteagent.log not showing trace level logs

### ISSUE THREAD

**Issue by mklechan** [cdr/code-server#2490]
- Web Browser:
- Local OS: MacOS
- Remote OS: Linux
- Remote Architecture: x86 
- `code-server --version`:3.7.4

It seems that remoteagent.log is no longer showing trace level logs with the latest version.
I tried with code-server --verbose and also --log trace , and its still not there

**Comment by nhooyr** [comment]
Might be fixed with `v3.8.0`!

Just released a few minutes ago. https://github.com/cdr/code-server/releases/tag/v3.8.0

**Comment by mklechan** [comment]
I just tried 3.8.0 and I still dont see the level of loging as before. Any ideas? thanks

**Comment by mklechan** [comment]
specifically, i was looking for the "File Watcher (chokidar)" output in remoteagent.log.  Is this something in the VSCode repo rather than code-server?

**Comment by nhooyr** [comment]
cc @code-asher

**Comment by code-asher** [comment]
Hmm yeah I think something isn't right here, I'm not getting trace logs in any of the VS Code logs.

**Comment by code-asher** [comment]
Should finally be fixed with 4.0.0.  Both the server and browser are showing trace logs.
