### ISSUE TITLE
The language server crashed 5 times in the last 3 minutes. It will not be restarted.(C/C++)

### ISSUE THREAD

**Issue by wyl2008056** [cdr/code-server#2499]
The language server crashed 5 times in the last 3 minutes. It will not be restarted.

- Web Browser: chrome
- Local OS: windows10
- Remote OS: ubuntu
- Remote Architecture: 
- `code-server --version`: v3.7.4

**Comment by KatiGithub** [comment]
Can you post an error log or screenshot?

**Comment by wyl2008056** [comment]
this problem is solved, i install the wrong vsix
