### ISSUE TITLE
Error loading webview: Service Workers are not enabled in browser. Webviews will not work.

### ISSUE THREAD

**Issue by wyl2008056** [cdr/code-server#2500]
Error loading webview: Service Workers are not enabled in browser. Webviews will not work.

- Web Browser: chrome
- Local OS: windows10
- Remote OS: ubuntu20
- Remote Architecture:
- `code-server --version`: v3.7.4

**Comment by jylenhof** [comment]
A probable root cause, use https instead of http if you did !

**Comment by mariorosati** [comment]
I have exactly the same issue and I'm using https:

- Web Browser: chrome
- Local OS: Mac OS 11.1
- Remote OS: ubuntu server 18.04
- code-server version: 3.8.0

**Comment by wyl2008056** [comment]
> I have exactly the same issue and I'm using https:
> 
> * Web Browser: chrome
> * Local OS: Mac OS 11.1
> * Remote OS: ubuntu server 18.04
> * code-server version: 3.8.0

when I used https://xxx   the broswer returns ERR_SSL_PROTOCOL_ERROR

**Comment by wyl2008056** [comment]
> I have exactly the same issue and I'm using https:
> 
> * Web Browser: chrome
> * Local OS: Mac OS 11.1
> * Remote OS: ubuntu server 18.04
> * code-server version: 3.8.0

when I used https://xxx   the broswer returns ERR_SSL_PROTOCOL_ERROR

**Comment by wyl2008056** [comment]
> I have exactly the same issue and I'm using https:
> 
> * Web Browser: chrome
> * Local OS: Mac OS 11.1
> * Remote OS: ubuntu server 18.04
> * code-server version: 3.8.0

hi,mariorosati  ,thank you, solved

**Comment by wyl2008056** [comment]
> A probable root cause, use https instead of http if you did !

hi,jylenhof  thank you ,solved

**Comment by mariorosati** [comment]
Hi wyl2008056, could you could you explain how you solved the issue?

Thanks

**Comment by wyl2008056** [comment]
> Hi wyl2008056, could you could you explain how you solved the issue?
> 
> Thanks

when i used https, the problem is gone
