### ISSUE TITLE
Upgrade Visual Studio Code to V1.52.0

### ISSUE THREAD

**Issue by KatiGithub** [cdr/code-server#2502]
Right now, there is a problem with installing the C++ extension on a raspberry pi due to the incompatibility with the ARM64 architecture and the fixed extension for ARM64 architecture is released but will not be compatible with the current Vs Code version(V1.51.1).

**Comment by leonm1** [comment]
I'm working on a source control extension and would love to have access to the FileDecorationProvider API made public in V.1.52.0 (https://github.com/microsoft/vscode/issues/54938).

Adding another use case to support triaging this issue higher 😊

Thank you for your work!
