### ISSUE TITLE
Not Serving HTTPS

### ISSUE THREAD

**Issue by Agastya-Asthana** [cdr/code-server#2513]
- Web Browser: Chromium 
- Local OS: Alpine Linux
- Remote OS: Raspbian/buster
- Remote Architecture: armv7
- `code-server --version`: 3.8.0

I am trying to dockerize the code-server for armv7 systems. When I run the `code-server` command in the container is outputs a bunch of logs and the last one is "[2020-12-24T03:49:41.745Z] info    - Not serving HTTPS." I have my docker container mapping port 8080 of host to the container's. The code-server doesn't work and I am pretty sure it's because of the error message above.

**Comment by fergy003** [comment]
I had the same issue this morning, which is how I ended up here. A guide I was following was missing this line in the docker compose file under # HTTP Routers
- "traefik.http.routers.vscode-rtr.tls=true"

Not sure if this will help or not, but it worked for me.

**Comment by Agastya-Asthana** [comment]
@fergy003 Could you share the guide you were using too?

**Comment by fergy003** [comment]
https://www.smarthomebeginner.com/wordpress-on-docker-traefik/

Before the main focus of this guide they mention vscode and the
docker-compose file
