### ISSUE TITLE
Python debugger is not working on v3.8.0

### ISSUE THREAD

**Issue by chocoford** [cdr/code-server#2514]
The problem occurs since v3.7.4. 
On 3.8.0, The `Debug` Panel of `VSCode` is blank. So I could not debug or run my code.

- Web Browser: Safari
- Local OS: IPad OS
- Remote OS: Ubuntu
- Remote Architecture: x64
- `code-server --version`: 3.8.0

**Comment by chocoford** [comment]
Also the `source control` panel is not working well either.

**Comment by clouraa** [comment]
Hello, I had the same problem and managed to solve it by following these steps:
Remove all python related extensions
Go to /config/extensions from the terminal delete the ms-python folder
Restart the code-server
Download the ms-python.python-2020.10.332292344 version from the github extension page and install manually
Restart and configure the python interpreter

**Comment by oxy** [comment]
Hi! This is a known issue, please see #2341 about the python extension.
