### ISSUE TITLE
Terminal doesn't autocomplete

### ISSUE THREAD

**Issue by helmut72** [cdr/code-server#2515]
- Web Browser: Safari, Chromium
- Local OS: macOS 15
- Remote OS: Linux/Docker https://hub.docker.com/r/codercom/code-server
- Remote Architecture: AMD64
- `code-server --version`: 3.8.0

When running code-server from the Docker image, autocomplete doesn't work in terminal. It send a tab instead of autocompletion any command. Instead of complete to `top`, output is like this:

<img width="363" alt="Bildschirmfoto 2020-12-25 um 13 14 08" src="https://user-images.githubusercontent.com/1388751/103134675-407dab00-46b3-11eb-8980-52f874667529.png">

**Comment by helmut72** [comment]
Fixed. Sorry, for disturbing your issues.

code-server does have /bin/bash as the default terminal, but vscode is configured using simple `sh`shell.

1. Open the command palette using Ctrl + Shift + P .
2. Type - Select Default Shell.
3. Select Git Bash from the options.

Now, new terminals open with bash and all is fine.

**Comment by code-asher** [comment]
Oh strange, I thought we were setting the default shell to bash in the
Dockerfile but we must not be doing that. We'll probably want to fix
that so users don't have to manually change it.
