### ISSUE TITLE
PYTHON NO AUTOCOMPLETION

### ISSUE THREAD

**Issue by Cr4zyB0t** [cdr/code-server#2517]
The python extension provide no autocompletion

**Comment by clouraa** [comment]
Hello, I had the same problem and managed to solve it by following these steps:
Remove all python related extensions
Go to /config/extensions from the terminal delete the ms-python folder
Restart the code-server
Download the ms-python.python-2020.10.332292344 version from the github extension page and install manually
Restart and configure the python interpreter

**Comment by oxy** [comment]
Hi! This is a known issue, please see #2341 about the python extension.
