### ISSUE TITLE
Running multiple Code-Server applications at the same time

### ISSUE THREAD

**Issue by Suansuan-Keai** [cdr/code-server#2518]
I want to run multiple Code-Server applications at the same time ,
Now I'm using Docker to realize it , but I think it isn't a good way because the problems of language enviroment.
Can we run multiple Code-Server applications with different extensions?

**Comment by Stradivario** [comment]
```
but I think it isn't a good way because the problems of language environment.
```

What does that mean ?

You can install Python or Java inside the IDE so what is your main use case ?

I am using Docker and i have a project with Nodejs and Angular and another project with DotNet and Angular i am running them without problems.

The extensions can be managed using `settings sync` 

Am i missing something ?
