### ISSUE TITLE
The vim plugin in the ipad browser does not work

### ISSUE THREAD

**Issue by no5no6** [cdr/code-server#2527]
ipad browser is not work, open vim mode, in the file, no response after pressing the button, but computer browser is work. computer system: macOS Big Sur。

- vim: 1.16.0
- Web Browser:  chrome and safari
- Local OS:  ipad 14.3
- Remote OS:  CentOS 8.0
- Remote Architecture:  x86_64
- `code-server --version`: 3.8.0

**Comment by code-asher** [comment]
It might be https://github.com/cdr/code-server/issues/1952.

**Comment by nhooyr** [comment]
See issue referenced by @code-asher
