### ISSUE TITLE
Update Documentation with Windows Instalation

### ISSUE THREAD

**Issue by stevensdotb** [cdr/code-server#2531]
I installed code-server and run it successfully on my linux machine but, I want to try to install and run it on another computer with Windows 10. Is it possible to update the documentation for Windows installation, even with Docker or WSL 2 Linux Subsystem?

Is there any instruction for it, please refer a link.

**Comment by tovine** [comment]
With WSL you'd just pick one of the distributions that code-server supports from the Microsoft store and run the install script from inside the WSL distro, no?

**Comment by stevensdotb** [comment]
@tovine Thanks for your soon response. I have installed the ubuntu distro and install code-sever into that WSL. It works perfectly. Thank you very much.
