### ISSUE TITLE
Extension request: Particle Workbench

### ISSUE THREAD

**Issue by faisal-ijaz** [cdr/code-server#2537]
- [x] Extension name: Particle Workbench
- [x] Extension GitHub or homepage: https://marketplace.visualstudio.com/items?itemName=particle.particle-vscode-pack

**Comment by oxy** [comment]
Thanks for opening an extension request!
We are currently in the process of switching extension marketplaces and transitioning over to [Open VSX](https://open-vsx.org/).
Once https://github.com/eclipse/openvsx/issues/249 is implemented, we can fully make this transition. Therefore, we are no longer accepting new requests for extension requests. 

We suggest installing the VSIX file and then installing it via the code-server CLI as a temporary workaround. See [docs](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#installing-an-extension) for more info.
