### ISSUE TITLE
Improve iPad Experience

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#2545]
I've been using `code-server` on an iPad this past week and think there's a lot of room for improvement. I figured this could kick off the discussion.

### ~~Editor window is too large~~
~~Ideally it match the size of the iPad~~ 
It appears this was happening in an older version of `code-server v3.6.0` But does not appear in the latest version.

### Can't scroll with Trackpad
Related: #1455

### ~~Vim extension doesn't work~~
~~Related: #2527~~

### Focus issues
When you change tabs in Chrome/Firefox and go back to the tab with `code-server` you have to click a file and then click back to the original file you had open to focus and actually type. 

I was able to reproduce it with Codespaces. Filed an issue
See: https://github.com/microsoft/vscode/issues/114012

Also related: all the [other issues](https://github.com/cdr/code-server/issues?q=is%3Aissue+is%3Aopen+ipad) related to iPad

*Note: the environment in which I was using iPad was through Coder's product (though shouldn't make a big difference).*

**Comment by jsjoeio** [comment]
I tested out Codespaces to see if they had any of the same issues. Here's what I found:

- Vim extension works correctly (v1.18.5)
- window of editor is correctly sized
- focus issue still exists
- scrolling with trackpad doesn't work

**Comment by ambichetan** [comment]
Hooray!, I can confirm that the scrolling issue is fixed on the latest iPadOS 14.5 dev beta 1. Welcome to true coding on iPad fellas. Super happy 😃 🔥 🚀

https://user-images.githubusercontent.com/16759509/106512454-7ff3a000-6486-11eb-92d5-f7fd82e552f8.mov

**Comment by jsjoeio** [comment]
No way!!! Thanks for posting this update! Downloading the beta to see this myself 🚀 Do you mind posting this to #1455 ?!

**Comment by jsjoeio** [comment]
@ambichetan how does one upgrade to iPadOS 14.5 dev beta 1? I tried a [few things](https://twitter.com/jsjoeio/status/1356381910138638336?s=20) but nothing is working.

**Comment by ambichetan** [comment]
You need to be a registered dev to get the beta profile from https://developer.apple.com/ (if not, wait 1-2 days for the public beta release and then register https://beta.apple.com/) Once you install the profile, just restart your iPad and trigger the update again.

**Comment by robertherber** [comment]
Works fairly well with 14.5 beta. However, I’m experiencing a strange issue where pressing SPACE isn’t forwarded to the terminal in code-server - but going to the editor and pressing space works - and after that it’s working in the terminal again. Strange issue - anyone else experiencing the same?

**Comment by jsjoeio** [comment]
@robertherber That does sound strange... I don't have access to 14.5 beta yet so I can't test right now. Do you mind opening up a separate issue so we can track there?

**Comment by no5no6** [comment]
I upgraded code-server to version 3.9, the vim extension is working! @jsjoeio

**Comment by jsjoeio** [comment]
YES! I can't wait to try it out! Thanks for letting me know @no5no6 ! ♥️

**Comment by jsjoeio** [comment]
Since there are corresponding issues for each item and most of them have been fixed, I'm going to close this issue.
