### ISSUE TITLE
Connect to Local Visual Studio Code

### ISSUE THREAD

**Issue by nathanchu** [cdr/code-server#2549]
Github Codespaces has a feature where you can connect a codespace to a local installation of Visual Studio Code. Could there be a similar feature for code server (an extension maybe)?

**Comment by code-asher** [comment]
Does that functionality just use the remote VS Code extensions? We have
an issue for implementing our own version of those extensions:
https://github.com/cdr/code-server/issues/2549

**Comment by nathanchu** [comment]
That's what I was looking for. Duplicate of #1315.
