### ISSUE TITLE
Make CI work on forks

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#2559]
Unfortunately github actions CI will only work on forks if there are no custom secrets.

So the npm package and docker image release process will have to be ran manually instead of via CI. Those are also in a separate workflow and github actions still won't run the workflow that does not depend on any secrets.

It's a worthy tradeoff to make it easier for contributors to get feedback on their changes.

**Comment by jawnsy** [comment]
This might be a new feature, but I think GitHub Actions supports running builds in forks with secrets, requiring approval before doing so (to avoid people trying to steal secrets using echo $ENV_VAR or whatever): https://docs.github.com/en/actions/reference/environments#environment-secrets
