### ISSUE TITLE
Fix create-react-app to work with relative paths

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#2565]
See #2222 and the associated PRs.

Need to fix it to use a relative `homepage` with webpack-dev-server assets and the `/sockjs-node`.

**Comment by nhooyr** [comment]
See also https://github.com/facebook/create-react-app/issues/8623

**Comment by nhooyr** [comment]
Opened https://github.com/facebook/create-react-app/pull/10503

**Comment by nhooyr** [comment]
So it looks like the reason everyone usually absolute paths is that webpack doesn't support relative urls in its publicPath config for SPAs as it's convention to use a single HTML document for the entire SPA. That way the backend doesn't need to be aware of routing.

Let's say you have a route at `/meow/foo` that serves some page. Then a relative path like `./bundle.js` for that route refers to `/meow/bundle.js` and not `./bundle.js`. But of course you want the latter served. So webpack would need to adjust the relativity of each path in the HTML for each request which isn't something it currently supports.

The other option is to statically render each route but that's beyond CRA.

And you can modify the app's expected absolute public path with `$PUBLIC_URL` at runtime which isn't too bad so I'll just document that.

**Comment by jsjoeio** [comment]
See https://github.com/cdr/code-server/pull/2674
