### ISSUE TITLE
Unable to use Settings Sync extension

### ISSUE THREAD

**Issue by h123hh** [cdr/code-server#2572]
[Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) is not working properly

Open external links are opened using the local computer, how do I configure them on the server?

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/2195#issuecomment-732123786

Not sure what you mean by

> Open external links are opened using the local computer, how do I configure them on the server?

**Comment by NightMachinary** [comment]
This is about the sync extension mentioned on the FAQ, not the official sync feature. When this extension wants to login via Github, it uses a localhost callback (`https://github.com/login/oauth/authorize?scope=gist read:user&client_id=xxx&redirect_uri=http://localhost:54321/callback`) which obviously doesn't work.

![image](https://user-images.githubusercontent.com/36224762/107922449-43936a00-6f85-11eb-9eeb-8a3e48966a66.png)

**Comment by kimtiago** [comment]
Use this extension, it's working

https://marketplace.visualstudio.com/items?itemName=nonoroazoro.syncing
