### ISSUE TITLE
Docker run command produces error

### ISSUE THREAD

**Issue by avarf** [cdr/code-server#2575]
I just copied and paste the docker run command from your docker hub (https://hub.docker.com/r/codercom/code-server) but I get the below error:
```bash
~/test/docker-vscode$ docker run -it -p 127.0.0.1:8080:8080 \
>   -v "$PWD:/home/coder/project" \
>   -u "$(id -u):$(id -g)" \
>   codercom/code-server:latest
[2021-01-13T15:25:01.230Z] error ENOENT: no such file or directory, mkdir '/home/coder/.config'
```

I am using Ubuntu 18.04 and docker version 19.03.13.

**Comment by avarf** [comment]
The `~/.config` also needs to be mounted into the container:
```bash
docker run -it -p 127.0.0.1:8080:8080 \
  -v "$HOME/.config:/home/coder/.config" \
  -v "$PWD:/home/coder/project" \
  -u "$(id -u):$(id -g)" \
  codercom/code-server:latest
```

**Comment by code-asher** [comment]
It might be a good idea to mount `~/.config` anyway just to perserve
settings but I ran the first command and wasn't able to replicate the
error. Maybe you have a cached code-server image? I think we did have
this error at one point.

**Comment by avarf** [comment]
No, I never installed or pulled code-server before, it was my first time.

**Comment by nhooyr** [comment]
Looks like I didn't update the docker hub listing.

See https://github.com/cdr/code-server/blob/v3.8.0/doc/install.md#docker for the correct command!

**Comment by nhooyr** [comment]
Updated.
