### ISSUE TITLE
Extension Request: Quokka

### ISSUE THREAD

**Issue by faisal-ijaz** [cdr/code-server#2583]
- [ ] Extension name: Quokka
- [ ] Extension GitHub or homepage: https://quokkajs.com

**Comment by oxy** [comment]
Thanks for opening an extension request!
We are currently in the process of switching extension marketplaces and transitioning over to [Open VSX](https://open-vsx.org/).
Once https://github.com/eclipse/openvsx/issues/249 is implemented, we can fully make this transition. Therefore, we are no longer accepting new requests for extension requests. 

We suggest installing the VSIX file and then installing it via the code-server CLI as a temporary workaround. See [docs](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#installing-an-extension) for more info.
