### ISSUE TITLE
Hashed Passwort doesnt work

### ISSUE THREAD

**Issue by kaaax0815** [cdr/code-server#2584]
- Web Browser: MS Edge Version 87.0.664.75 (Offizielles Build) (64-Bit)
- Local OS: Windows 10 2004
- Remote OS: Ubuntu 20.04 LTS
- Remote Architecture: x86_64
- code-server --version: 3.8.0 c4610f7829701aadb045d450013b84491c30580d
I created the hash like the example given in the [FAQ page](https://github.com/cdr/code-server/blob/v3.8.0/doc/FAQ.md#can-i-store-my-password-hashed).
I changed `password: <password>` to `hashed-password: <hash>`.
But if i type in the password it just is incorrect.
Are there any steps I should to do to determine the problem closer?

**Comment by kaaax0815** [comment]
Fixed it myself, I used wrong user

**Comment by kaaax0815** [comment]
I used a online sha256 hash generator, and this fixed the problem. I dont know why, but my sha256sum command doenst output the real output

**Comment by code-asher** [comment]
Sorry about this! This is probably because the `echo` in our docs
outputs a newline. It should be `echo -n` or `printf`. We'll be fixing
this soon: https://github.com/cdr/code-server/pull/2503
