### ISSUE TITLE
iPadOS: Don't disable keyboard shortcuts that conflict with browser

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#2586]
The PWA version of code-server can support top-level shortcuts normally reserved for the browser (e.g. `cmd` + `w`).

We _think_ VSCode (upstream) disables keyboard shortcuts which may conflict with browser shortcuts [here](https://github.com/cdr/code-server/blob/master/lib/vscode/src/vs/workbench/services/keybinding/browser/keybindingService.ts#L376). I've tested this out locally by manually adding the keyboard shortcut `cmd` + `w` which normally closes a tab in Safari/Chrome/Firefox. 

## To see this working
Follow these steps to see in action:
1. Install your version of code-server as a PWA on iPad
2. Open up code-serer
3. `Command Palette > Open Keyboard Shortcuts (JSON)`
4. Add the following to your `keybindings.json`
```json
 {      
        "key": "cmd+w",
        "command": "workbench.action.closeActiveEditor"
}
```
5. Test out command by hitting `cmd` + `w` to close an active file

## Solution
Check if code-server is running as a PWA. If it is, allow conflicting keyboard shortcuts (e.g. `cmd` + `w`).

**Comment by DAddYE** [comment]
Question, how do you install it as PWA? Right now I'm adding code-server to the home screen and all the shortcuts works, however, most of the os x shortcuts were missing so [I copied the full list](https://gist.github.com/DAddYE/8d568f756f5a16587e8e835c130b2912#file-keybindingsmac-json). 

The problem I'm facing right now is that every few minutes they stop working and I have to force a refresh.

**Comment by jsjoeio** [comment]
> how do you install it as PWA?
1. Open it up in Safari
2. Hit the Share icon
3. Scroll down and hit "Add to Home Screen"

Then on your iPad, find it on the home screen and open it from there. So it sounds like you're already doing that. 

> The problem I'm facing right now is that every few minutes they stop working and I have to force a refresh

Hmm... that's really strange. I am not sure what could be causing that. Can you record a video and post it here? And during the video, can you open the `keybindings.json` file and show the list of extensions you have installed?

**Comment by DAddYE** [comment]
It seems it's the terminal that at some point takes over the shortcuts, or the editor doesn't acknowledge it's closed/hidden.

https://share.icloud.com/photos/0jF8ajSZYwnybqtel2EFx2fDQ

Thank you!!!!

**Comment by jsjoeio** [comment]
Thanks for the video! I have experienced that exact same Find issue with the integrated terminal - so strange. 

> the editor doesn't acknowledge it's closed/hidden.

Yeah I noticed this as well. Hmm...we'll have to investigate more but hopefully you're at least unblocked for now!

**Comment by Toomoch** [comment]
Is this still working? I added the shortcut cmd+w and it doesn't work in iPadOS 16.5

**Comment by zschiffelbein** [comment]
I am running in to the same issue on iPad OS 17.6. Unable to get the cmd+w shortcut to close the active editor.
