### ISSUE TITLE
windows binary

### ISSUE THREAD

**Issue by lazeebee** [cdr/code-server#259]
whats the timeline of the windows binary release?

**Comment by kylecarbs** [comment]
The windows binary is actually very close to working!

I believe the only change we need to make is including the additional files w/ `node-pty` that windows will output in the `Release/build` dir.

**Comment by OneCyrus** [comment]
i'm interested in a windows version as well

**Comment by nol166** [comment]
@lazeebee I believe we have a new bundler in the works that should get us one step closer to getting the windows binary working

**Comment by Multishifties** [comment]
New Bundler for binary has been released! @nol166 Maybe we can re-test this? (I think Justin has a windows machine, no?)

**Comment by fmichaleczek** [comment]
@Multishifties I would like to test the new bundler, where I can find it ?
I'm a PowerShell developper and I need to use VSCode on Windows to develop for Windows PowerShell Edition. It's why  a windows or windows Docker build is a requirement for me.

**Comment by Multishifties** [comment]
@fmichaleczek new Binary compiler is located here https://github.com/codercom/nbin Code-server uses this now instead of `Nexe`

AFAIK, it SHOULD allow you to compile for any platform where Node.js is supported. But I haven't had a chance to test it extensively yet.

**Comment by fmichaleczek** [comment]
@Multishifties I will try to test this week and give feedback on nbin repo.

**Comment by DiegoBM-DB** [comment]
Was anybody able to produce a Windows binary? Even if beta test only..

**Comment by maxloh** [comment]
Any updates?

Is there an expected time when Windows build will be available?

**Comment by sr229** [comment]
@maxloh Windows builds are low priority since there is more demand for ARM builds than Win32 builds.

**Comment by maxloh** [comment]
@sr229 Vote for windows binary. Hope we can get it one day.

BTW, is there any guides to use code server with WSL?

**Comment by ikarstein** [comment]
I hope for it too

**Comment by nhooyr** [comment]
https://github.com/cdr/code-server/issues/1306 will fix this.

**Comment by DarshanaSubhash** [comment]
Guys, I am looking for VSCode binary on windows.Any help is much appreciated.
Thanks in advance

**Comment by code-asher** [comment]
@DarshanaSubhash We don't publish Windows releases at the moment but you can try installing with `yarn`. https://github.com/cdr/code-server/blob/master/doc/install.md#yarn-npm

**Comment by iwillreku3206** [comment]
I just tried installing via yarn using the command `yarn global add code-server` but then upon typing `code-server` I get this error:
```
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'C:\Users\Windows\AppData\Roaming\npm\node_modules\code-server\out\node\entry.js'     
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I am running Windows 10, node version 14.3.0, yarn version 1.22.10

**Comment by Failip420** [comment]
> I just tried installing via yarn using the command `yarn global add code-server` but then upon typing `code-server` I get this error:
> 
> ```
> internal/modules/cjs/loader.js:1032
>   throw err;
>   ^
> 
> Error: Cannot find module 'C:\Users\Windows\AppData\Roaming\npm\node_modules\code-server\out\node\entry.js'     
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:898:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> ```
> 
> I am running Windows 10, node version 14.3.0, yarn version 1.22.10

same it crashes for me too

**Comment by maxloh** [comment]
> I just tried installing via yarn using the command `yarn global add code-server` but then upon typing `code-server` I get this error:
> 
> ```
> internal/modules/cjs/loader.js:1032
>   throw err;
>   ^
> 
> Error: Cannot find module 'C:\Users\Windows\AppData\Roaming\npm\node_modules\code-server\out\node\entry.js'     
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:898:27)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
>     at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> ```
> 
> I am running Windows 10, node version 14.3.0, yarn version 1.22.10

Do `C:\Users\Windows\AppData\Roaming\npm\node_modules\code-server\out\node\entry.js` exists?
Maybe the path is too long for Windows file system and the file didn't get downloaded to the folder.

**Comment by mkanet** [comment]
Is there a Windows binary yet?  If so, where is the download for it?

**Comment by syKevinPeng** [comment]
> > I just tried installing via yarn using the command `yarn global add code-server` but then upon typing `code-server` I get this error:
> > ```
> > internal/modules/cjs/loader.js:1032
> >   throw err;
> >   ^
> > 
> > Error: Cannot find module 'C:\Users\Windows\AppData\Roaming\npm\node_modules\code-server\out\node\entry.js'     
> >     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
> >     at Function.Module._load (internal/modules/cjs/loader.js:898:27)
> >     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
> >     at internal/main/run_main_module.js:17:47 {
> >   code: 'MODULE_NOT_FOUND',
> >   requireStack: []
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am running Windows 10, node version 14.3.0, yarn version 1.22.10
> 
> Do `C:\Users\Windows\AppData\Roaming\npm\node_modules\code-server\out\node\entry.js` exists?
> 
> Maybe the path is too long for Windows' file system and the file didn't get downloaded to the folder.
> 
> You will also need Python to be installed in your machine as node-gyp requires Python to build.

Hi, I encountered the same issue. The path you mentioned doesn't exist, and I have python installed. Also, I noticed that the script "~/AppData/Local/Yarn/Data/global/node_modules/code-server/postinstall.sh" was opened by the Vscode during the installation. It's looks like it not excuted.
