### ISSUE TITLE
Open Folder on startup and don't open file when opening folder

### ISSUE THREAD

**Issue by kaaax0815** [cdr/code-server#2594]
I didn't find an option to open a specific folder on startup. I use `--ignore-last-opened`, because i want a clean workspace, but
 - When I open the Folder it opens the last opened file from that folder
 
But I want that
- It opens the specified folder with no opened files

**Comment by nhooyr** [comment]
So if you pass a specific folder, `--ignore-last-opened` is ignored as you've specified exactly what you want opened.

I guess you're saying you want a way to make it clear from the CLI to not restore the opened files for the folder?

cc @code-asher

**Comment by kaaax0815** [comment]
And to specify a folder that opens in the workspace
<a href="https://ibb.co/SQRzD59"><img src="https://i.ibb.co/bHzkjQ8/msedge-cy-UKs4-GTON.png" alt="msedge-cy-UKs4-GTON" border="0"></a>
So like this, nothing is opened, but the folder is there

**Comment by code-asher** [comment]
Ah yeah that option prevents automatically opening the last remembered workspace but it doesn't prevent restoring the opened editors belonging to that workpace once it finally is opened.

I think we'd need to patch VS Code to make this possible but I'm not sure we should.

**Comment by JammSpread** [comment]
> I think we'd need to patch VS Code to make this possible but I'm not sure we should.

I think this should be more of a customizability feature on [VS Code](https://github.com/microsoft/vscode)'s end if they don't already have an option for this (which I could not find). I'm imagining this as a setting named something like `files.restore`. I find that to be a better resolution than modifying something that `code-server` probably shouldn't deal with.

**Comment by kaaax0815** [comment]
I thought maybe its like opening VS Code with a Parameter, but I think so too that you shouldn't patch the whole code-server

**Comment by JammSpread** [comment]
Does `code-server ~/foo/bar` work for you? That should open the specified folder in code-server. Could you explain your setup if you have any more questions?

**Comment by kaaax0815** [comment]
`code-server --link --ignore-last-opened /home/bernd/Workplace` does open the Folder, but doesn't ignore last opened files.
Cpu: 1 Core
Ram: 1Gb
Ubuntu: 20.04 LTS
Remote Architecture: x86_64
code-server --version: 3.8.0 c4610f7

**Comment by code-asher** [comment]
If this was to be implemented I definitely agree with the
`files.restore` idea. I did actually actually find a restore setting but
it only affects the Electron version and I'm not sure it does exactly
what is being requested here. I wasn't able to find anything else
either. But maybe this means there is existing code that could be
leveraged.

**Comment by JammSpread** [comment]
Oh I assume that's the `window.restore` option, however that one deals with the feature `--ignore-last-opened` already implements.

**Comment by code-asher** [comment]
Ahh yup that's the one. That makes sense...maybe we should have just
added that option to code-server instead of a new flag...

**Comment by code-asher** [comment]
Actually it's probably good we did it with a flag since we use the start directory in some other places outside of VS Code. The file thing should definitely be an option though.

**Comment by bpmct** [comment]
Would personally love if this was a flag + environment variable :)
