### ISSUE TITLE
JavaScript debug not working

### ISSUE THREAD

**Issue by alexey1966** [cdr/code-server#2619]
Hello, I try to use code-server in my browser. Everything works smoothly except debugging. I click Run and Debug, choose node.js environment and nothing happens. I just see debugging icons above on the screen, but nothing happens, my breakpoints are not working. Please assist.

**Comment by oxy** [comment]
Hi! Can you please provide additional information, such as the version of code-server and node you have installed locally, the distro you're using, and an example file which I can use to attempt to reproduce the same issue?

**Comment by alexey-ambrozevitch** [comment]
I simply add test.js file with 2 lines:
const i = 10;
console.log(i);

Then try to add breakpoints.
Used node —inspect test.js. Even tried to Toggle AutoAttach (attach works properly, but debugging hangs, I mean nothings happens (on left upper corner where run title is located, slider is moving, I can see debugging button on the top, but only refresh and stop buttons are available for clicking)).
Also tried to add launch.json file into .vscode directory:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
      {
        "type": "node",
        "request": "attach",
        "name": "Attach NestJS WS",
        "port": 9229,
        "restart": true,
        "stopOnEntry": false,
        "protocol": "inspector"
      }
  ]
}

Node version is v10.17.0
Information about code-server:
code-server: v3.6.2
 VS Code: v1.50.0
Commit: 9bde62fbd611a7a91c5f327fa43e0d06f1379169
Date: 2020-11-02T23:35:06Z
Browser: Mozilla/5.0 (iPad; CPU OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Mobile/15E148 Safari/604.1

**Comment by oxy** [comment]
Hey - v3.6.2 is quite outdated by now; can you try updating to the latest version to see if the issue persists?

**Comment by alexey-ambrozevitch** [comment]
Updated to 3.8.0 . UI has changed, but the problem still persists (the slider is moving and nothing happens).

code-server: v3.8.0
VS Code: v1.51.1
Commit: c4610f7829701aadb045d450013b84491c30580d
Date: 2020-12-18T20:25:37Z (1 mo ago)
Browser: Mozilla/5.0 (iPad; CPU OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Mobile/15E148 Safari/604.1

**Comment by alexey-ambrozevitch** [comment]
Installed node version 15.6.0 and the problem has gone.

**Comment by code-asher** [comment]
Oh, huh. Maybe we should add the Node binary that code-server ships with to the path so this works out of the box?

**Comment by alexey-ambrozevitch** [comment]
Great idea. Because now it’s not obvious.
