### ISSUE TITLE
github pull request extension not working 

### ISSUE THREAD

**Issue by guyuxiang** [cdr/code-server#262]
- `code-server` version: 1.32.0-282
- OS Version: ubuntu 18.10
- Extension: github.vscode-pull-request-github 

## Description

The extension can be installed. But the extension button disappears after restart the IDE.

**Comment by kylecarbs** [comment]
cc: @foresthoffman

**Comment by code-asher** [comment]
This appears to work with v2 but authentication doesn't work. It looks like it expects to be able to use a `code-oss://` URI which won't work in the browser. It might work to authenticate with VS Code once and then use code-server but I'm not sure yet how/if we can work around this in code-server.

**Comment by nhooyr** [comment]
@kylecarbs

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
