### ISSUE TITLE
conda envs and ms-python extension?

### ISSUE THREAD

**Issue by tyoc213** [cdr/code-server#2629]
Im working with python and when I execute codium on my computer, it autodetects conda environments and show them on the bottom left, which I can switch env if I want.

I have installed ms-python extension on code-server, but I dont see that it shows me the conda environments my user has, it just show me 

![image](https://user-images.githubusercontent.com/506234/105641164-44ceec80-5e48-11eb-9e20-a0b4e8d3359e.png)

Instead of 

![image](https://user-images.githubusercontent.com/506234/105641214-76e04e80-5e48-11eb-9066-63f264ac91f6.png)

also this 2 seems not to show something

![image](https://user-images.githubusercontent.com/506234/105641257-92e3f000-5e48-11eb-8194-0bded0fa8602.png)

They just show 
![image](https://user-images.githubusercontent.com/506234/105641420-77c5b000-5e49-11eb-96d7-90388dda93fc.png)

But no extra log lines with `code-server --log debug`

- Web Browser: chrome
- Local OS: OSX Catalina 10.15.1 Beta (19B77a)
- Remote OS: Ubuntu 20.04
- Remote Architecture: x86
- `code-server --version`: code-server 3.8.0 c4610f7829701aadb045d450013b84491c30580d

**Comment by oxy** [comment]
Hi - do you have your Conda environments present on your Ubuntu remote OS or only locally? You need to have them installed on the remote for them to show up.

**Comment by tyoc213** [comment]
Yeah, in my remote environment I have  my conda environments setup and working correctly! even Codium detects it when I program in that computer and can change the env from the bottom bar if I want.

I executed `code-server --log debug` under my remote user with all conda envs working, but the bottom bar doesn't show them. As a fact in this session I can open the console with the menu and type `conda activate ai` and it will activate the environment, so it is working in codeserver if I use the terminal. But seems that `ms-python` isn't detecting the envs by itself, not showing the run commands and others (and the run that show, doesn't run actually)

**Comment by code-asher** [comment]
I wonder if this is related to the issues we're having with the Python extension: https://github.com/cdr/code-server/issues/2341

**Comment by tyoc213** [comment]
My question would be? code-server should run as my normal codium or code running locally on Linux??

**Comment by code-asher** [comment]
We have our own extension marketplace because Microsoft does not allow
non-VS Code products to use theirs.

In our marketplace authors do not submit extensions; instead ours builds
them automatically.

Unfortunately that process is error-prone and often results in broken
extensions.

One workaround is to download the extension from the GitHub repository
or from OpenVSX and install it manually.

**Comment by phisanti** [comment]
@code-asher I am currently running code-server 3.8.0, `FROM codercom/code-server`. Installing via https://open-vsx.org/extension/ms-python/python allows the use of python REPL. However, interactive window/jupyter seems still block or non responsive after installing ipykernel, ipython and so on..

**Comment by code-asher** [comment]
I tried out 3.8.0 (via yarn) with the Python extension from OpenVSX but
so far everything seems to be working for me. I used "Python: Create New
Blank Jupyter Notebook" then ran some simple code like `print("hello")`.
Is that more or less what you're doing?

If you could post more logs it might shed some light on the issue.
https://github.com/cdr/code-server/blob/v3.8.0/doc/FAQ.md#how-do-i-debug-issues-with-code-server

**Comment by phisanti** [comment]
You are right. Finally, it's working!
 **OpenVSX**  + **no update** was the key. Thanks a lot
