### ISSUE TITLE
vscode-lean4

### ISSUE THREAD

**Issue by huynhtrankhanh** [cdr/code-server#2630]
- [ ] Extension name: vscode-lean4
- [ ] Extension GitHub or homepage: https://github.com/leanprover-community/vscode-lean4

**Comment by oxy** [comment]
Hi! We're currently working on adding support for using Open-VSX in addition to our gallery in `code-server` - I'd recommend reaching out to the author of the extension and requesting them to publish to Open-VSX!

**Comment by huynhtrankhanh** [comment]
Thank you, I've relayed your message to everyone on the Lean Zulip chat. I hope someone knowledgeable could chime in because I couldn't really understand what you're saying.

**Comment by gebner** [comment]
The extension has now been published on Open-VSX.
