### ISSUE TITLE
OAuth Support without `--link`

### ISSUE THREAD

**Issue by kaaax0815** [cdr/code-server#2636]
Please provide a way to login with e.g. Github like in your Cloud Program, but without using the Cloud Program. A list of ways to do it ourself is I think good too

**Comment by code-asher** [comment]
We don't have any plans on adding additional authentication methods so we recommend using an external oauth proxy.

We mention that briefly here: https://github.com/cdr/code-server/blob/v3.8.0/doc/FAQ.md#how-should-i-expose-code-server-to-the-internet

But I think we might be able to  reword this section to make it more discoverable, maybe something like "authentication methods"?

**Comment by kaaax0815** [comment]
So I would Listen white Caddy on Port 80,443 then Pass that SSL Encrypted to the OAuth Proxy, there I login and then it gets passed to the CodeServer on port 8080

**Comment by kaaax0815** [comment]
I got Oauth2_Proxy to work, which works just fine, so maybe adding a bit to the docs, but not more because you are completely right

**Comment by sestegra** [comment]
See https://www.pomerium.io/guides/vs-code-server.html
