### ISSUE TITLE
Latex-Workshop error command 'latex-workshop.build' not found 

### ISSUE THREAD

**Issue by HalliHalloSchatz** [cdr/code-server#2642]
I have setup texlive by these short description.
https://www.tug.org/texlive/quickinstall.html

Running on an Ubuntu LTS. 

Same document on Ubuntu bash console working, command latex test.tex

I have no idea, why code-server don't find the build command.

**Comment by code-asher** [comment]
Are there any errors in the browser console? Our build of the extension
might be broken.

**Comment by HalliHalloSchatz** [comment]
sorry. I see now log/debug messages.
Where can I found them?

**Comment by code-asher** [comment]
You'll need to open the browser's developer tools then copy the logs
from the console tab.

**Comment by HalliHalloSchatz** [comment]
thank you for answer.
I have start code-server with /usr/bin/code-server --user-data-dir /var/www/svn/code-server 


I found this in Firefox Console:
```
Fehler beim Aktivieren der Erweiterung "James-Yu.latex-workshop": Cannot find module '/var/www/svn/code-server/extensions/james-yu.latex-workshop-8.15.0/out/src/main.js'
Require stack:
- /usr/lib/code-server/lib/vscode/out/vs/loader.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-fork.js.
```

folder /var/www/svn/code-server/extensions/james-yu.latex-workshop-8.15.0/out/ with all files and folder not eists.


And I found
```
Fehler beim Aktivieren der Erweiterung "CoenraadS.bracket-pair-colorizer-2": Cannot find module '/usr/lib/code-server/lib/vscode/node_modules**### .asar**/vscode-textmate'
Require stack:
- /var/www/svn/code-server/extensions/coenraads.bracket-pair-colorizer-2-0.1.4/out/src/textMateLoader.js
- /var/www/svn/code-server/extensions/coenraads.bracket-pair-colorizer-2-0.1.4/out/src/settings.js
- /var/www/svn/code-server/extensions/coenraads.bracket-pair-colorizer-2-0.1.4/out/src/documentDecorationManager.js
- /var/www/svn/code-server/extensions/coenraads.bracket-pair-colorizer-2-0.1.4/out/src/extension.js
- /usr/lib/code-server/lib/vscode/out/vs/loader.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-fork.js.
```

Folder not exists, but /usr/lib/code-server/lib/vscode/node_modules/vscode-textmate

only root have write access to /usr/lib/code-server.
Nedd the user under which the code-server running write access or the www-data user under which the apache server is running?

**Comment by HalliHalloSchatz** [comment]
Thank you with the firefox console. Now, that can helped me.


bracket-pair-colorizer-2 error:
I have create a symlink in '/usr/lib/code-server/lib/vscode/' from 'node_modules.asar' -> 'node_modules'
I think thats working. Bujt I have no idea, why I must set a custom symlink?!?


LaTeX Workshop error:
I found this Issue #1828.

I do the same: download https://james-yu.gallery.vsassets.io/_apis/public/gallery/publisher/James-Yu/extension/latex-workshop/8.15.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

unzip the contained extension/out folder and put it in '/var/www/svn/code-server/extensions/james-yu.latex-workshop-8.15.0/'
The missing error is away. Now, I can try to compile my first latex... My first latex document...

**Comment by HalliHalloSchatz** [comment]
now, I have the same issue with #1862

The latex-workshop pdf viewer will connect to localhost:PORT.
The same pdf with vscode-pdf working in vscode-tab.

**Comment by code-asher** [comment]
Ah yeah bracket-pair-colorizer-2 specifically looks for
`node_modules.asar` but we don't include that in any release. We have it
symlinked in master but it's not in a release yet, so for now manually
symlinking is necessary.

Looks like our version of the latex workshop extension is broken. It's a
long story but we're going to switch to OpenVSX soon which should
resolve these kinds of issues with extensions.

However we still don't have a way to fix the localhost issue from our
end.

**Comment by HalliHalloSchatz** [comment]
Latex Workshop:
With these little changes,
1. download it manually
2. extract the missing out folder to extension path
Latex workshop working 

Bracket pair, 
1 create that symlink in vscode lib folder
Bracket pair working

**Comment by sunyongke** [comment]
> now, I have the same issue with #1862
> 
> The latex-workshop pdf viewer will connect to localhost:PORT.
> The same pdf with vscode-pdf working in vscode-tab.

I have the same issue. Did you fix this issue?

**Comment by HalliHalloSchatz** [comment]
No, I have found a answer, that there is no support on code-Serer and they wait, that the native pdf handler will handle this.
