### ISSUE TITLE
Login rate limiter should not count against successful logins

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#2647]
When running e2e tests against the login page, I'm hitting the login rate limit even though I'm using the correct password

<img width="738" alt="image" src="https://user-images.githubusercontent.com/3806031/106203322-6e558400-6178-11eb-86cc-310f60824567.png">

Relevent code:
https://github.com/cdr/code-server/commit/5accf3fe5fe8f3430cf06f95adff18c4107756f7

**Comment by sr229** [comment]
this looks like the limiter couldn't distinguish from successful logins to non-successful logins. Will give this a look later.
