### ISSUE TITLE
Why I can open all files in my server

### ISSUE THREAD

**Issue by jytx** [cdr/code-server#2650]
when i install code server successfully, i request my address immediately ,but when i edited my file and saved it,I found  that i can browse all my files and folders in my server,how can I set specified folder to save my files?

**Comment by code-asher** [comment]
You can use file > open folder to limit the explorer to a specific
directory but there's no way to completely prevent code-server from
opening other files or directories outside that directory.

See https://github.com/cdr/code-server/issues/1834
