### ISSUE TITLE
Stop and error if dependencies fail to install

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#2651]
Right now, builds in CI keep going even if it times out downloading dependencies. Instead it should error and stop the build. This would improve our CI process.

**Comment by oxy** [comment]
I'm not entirely sure why it doesn't stop immediately; we use `set -euo pipefail` in all our shell scripts, which should in theory make bash exit with an error if a step fails. Does GitHub's CI just keep running even when one stage returns an error?

**Comment by code-asher** [comment]
As far as I can tell it's not specific to CI; the `yarn` command itself
just isn't exiting with a non-zero code. I've seen a few reports from
users exhibiting the same issue.

So far they've all been network-related; maybe `yarn` has a bug where it
doesn't exit with non-zero when that happens. Or probably more likely it
has something to do with how the postinstall is set up.

**Comment by code-asher** [comment]
Might make sense to also check for the required system dependencies listed here: https://github.com/cdr/code-server/blob/v3.9.0/docs/npm.md

**Comment by jsjoeio** [comment]
Check to make sure that `ripgrep` exists to prevent #3117
