### ISSUE TITLE
500 URI malformed

### ISSUE THREAD

**Issue by AtyKlaxas** [cdr/code-server#2654]
- Web Browser: Firefox/Opera/Chrome
- Local OS: Windows/MacOS
- Remote OS: Linux Debian 10
- Remote Architecture: KVM
- `code-server --version`: 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259

Hello,
i found a problem about cookies
i don't know why, if i set a cookie on my website, that bug code-server
i have a domain and i host web-server and code-server on this domain
test.fr.nf:80 access my web server i work on
test.fr.nf:8045 acces code-server 

i'm working on login system with cookies
and i notice my cookie cause 500 URI malformed error
then i set my cookie, code_server get it and bug

can you limit this effect ?
i need cookie filter on code-server

thanks for reading me
sorry for bad english

https://youtu.be/3Y5g8D1sQzE

**Comment by oxy** [comment]
I think this is to do with the fact that the Cookie is a urlencoded blob, though I may be wrong; I'll investigate myself to see if I can reproduce the bug.

Can you post the value of the cookie you set?

**Comment by AtyKlaxas** [comment]
my cookie is like `�o�z�[n:B���+��O�/�^...`
its binary
this is a example cookie parsed with `bin2hex()` in php
```
bin2hex($my_cookie_value) =
'41082fb5cdd2929315b92676374982cf63f8a435d9b3adc7a8eab7dbe2e3466920f3b7003cbc0070846dc06eaa51c16c3a6bba06b73c7501ddcfbd58b02fadfe01e644110fd9238f9f023edb9010158126718debd81b43b85912ba96656f03a897b6726759e64b529df3dff1fb5e662e4fd70598bd3c227d10ac181202e55e4ee412a84edf1ad65d387ffb45e7ddc7668816e648a4d70d26ddcf73301ae95c92ea04abb2c5809eb59b9ac4a03bcb72024b63cbd922405c82e8362e9fc6a26507e7f011c976a993158bd616238dd5850e91c74a9497c290f5cc1c1943508368d5c623c486aaebd93a6d7133b369d525b3052689ecc37fe32771ee05db2b93ed15a1389a6bd09fdc1c7a08f56cf99d651878e00131bced3cd16c5140216f3ae7374dee7aab6ef327bc5a5689ce3e12458447f3b1bfc4f7070656098ea52889747dc8fdcb9f593cffff2f367c43ed874ff83c25cd73a8fcac4f60456518ad0d92bee35d2e799aa1af61269de75613ccb54f52703cba76d49730cfbdfa961bc05fba7829913d9ef42b86d7076248afab29a0e7c69c425b11ba0f4c9e31e1029414a5a551c12b61793925281704dfe8408ef0d9a13df3b6aa0a3de41cf2fe8e24c568eeb867ae502daf823b553b4a2bf9425b039c2cc3b407569427a2de558c551afe4c940e30e67ff8c8a3aff9b489a44f6b599628e1800798f5d7837f47d40edf7e'
```

I thought it might come from the fact that my cookie is a binary, rather than a base64.
i test with base64 cookie and ... bug is gone

so it's a bug from me?

**Comment by code-asher** [comment]
Hey, I'm sorry we didn't get back to you. I think you're right; cookies are only allowed to have certain characters so it needs to be encoded in some way. https://www.rfc-editor.org/rfc/rfc6265.txt
