### ISSUE TITLE
vim extension is not working

### ISSUE THREAD

**Issue by sangchul** [cdr/code-server#2655]
- Web Browser: Chrome 88.0.4324.96
- Local OS: macOS Catalina 10.15.7
- Remote OS: CentOS Linux release 7.4.1708 (Core)
- Remote Architecture: x86_64
- `code-server --version`: 3.8.0

I've just upgraded vim extension to version 1.18.7 and it doesn't work with following console messages
<img width="745" alt="vscode vim not working" src="https://user-images.githubusercontent.com/28073/106538281-65c9c880-653f-11eb-9752-164bfa61b63c.png">

and I rollbacked it to version 1.16.0 I'd used well and it works now.

Is it early to upgrade brand new vim extension until new code-server version would be released?

Thanks

**Comment by jsjoeio** [comment]
Hi @sangchul! It looks like this may be a duplicate (see #2319 which I think you opened?)

We're doing everything we can do fix this as soon as possible. In the meantime, there are two workarounds:
- use 1.16.0 (which you know works)
- use the `neovim` extension (see [this comment](https://github.com/cdr/code-server/issues/2319#issuecomment-758529523))

**Comment by sangchul** [comment]
@jsjoeio Oh. thanks reminding me. The post I wrote grew so fast!. I will check it. thanks again
