### ISSUE TITLE
Installed extensions not showing up or can't be enabled

### ISSUE THREAD

**Issue by TheDutchMC** [cdr/code-server#2658]
I have added to the Dockerfile some instructions to install extensions from a .vsix file, during building these are shown as being installed. However after starting the container, the extensions do not show up when filtering for @installed.

Adding to this, extensions installed via the gui using .vsix files cannot be enabled. Example:
![image](https://user-images.githubusercontent.com/28569170/106591882-17bcc100-654f-11eb-9154-ff79a49b508e.png)

This .vsix file was downloaded from the [VScode marketplace](https://marketplace.visualstudio.com/vscode)

Extensions in the Dockerfile installed with ``RUN code-server --install-extension /ext/redhat.java-0.74.0.vsix``

- Web Browser: MS Edge 87.0.664.66
- Local OS: Windows 10
- Remote OS: Ubuntu 20.04 LTS (in Docker)
- Remote Architecture: amd64
- `code-server --version`: 3.8.0 c4610f7829701aadb045d450013b84491c30580d

**Comment by TheDutchMC** [comment]
A ctrl+f5 seems the cant enable it after installing .vsix from gui issue, though the other still exists.

**Comment by jsjoeio** [comment]
Hi @TheDutchMC - thanks for opening this! We will look into this as soon as we can. 

> Adding to this, extensions installed via the gui using .vsix files cannot be enabled

Can you try a different extension to confirm that this is indeed the case?

**Comment by Billyism** [comment]
I have the same problem

**Comment by davids-tips** [comment]
I have looked into the issue. I had it aswell
# Steps i took to fix it.

1. Close the instance of code-server.
2. Restart instance and log back in.
-  The extensions should now be enabled and be able to be toggled on and off

Below is unrelated but some useful information
- As of the issue of not being able to access it from the internet without having to use ssh try setting up ngrok

Hope this works for you,
> David A. Powell
> Beginner in Javascript
> Compentent in Python and Discord.py
> Proficient in html and css.
> OC of WhiskeyBot
> See my latest projects at https://Github.com/Davids-tips
