### ISSUE TITLE
Settings Sync

### ISSUE THREAD

**Issue by Xenfo** [cdr/code-server#2662]
- Web Browser: Brave Mobile, Firefox Ubuntu
- Local OS: iOS, Ubuntu
- Remote OS: Ubuntu
- Remote Architecture: amd64
- `code-server --version`: 3.8.0

The VSCode settings sync feature (looks like a user) doesn't load.

![image](https://user-images.githubusercontent.com/46873232/106689911-cc320380-659e-11eb-89a3-3a697d6c105e.png)

**Comment by kaaax0815** [comment]
Mentioned in this issue: https://github.com/cdr/code-server/issues/2587

**Comment by Xenfo** [comment]
Ah ok
