### ISSUE TITLE
Can't use Python extension

### ISSUE THREAD

**Issue by konradzadroga** [cdr/code-server#2675]
Dear Team,

I am experiencing issue with code-server (latest version, 3.8.0, inside Docker container). 
After installing 'Python' extension I can't use it because of some dependencies. 
Errors in the console:
```
"Activating extension 'ms-toolsai.jupyter' failed: Cannot find module '/home/coder/.local/share/code-server/extensions/ms-toolsai.jupyter-2020.12.1/out/client/extension'
Require stack:
- /usr/lib/code-server/lib/vscode/out/vs/loader.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/code-server/lib/vscode/out/bootstrap-fork.js."
"Cannot activate extension 'Python' because it depends on extension 'ms-toolsai.jupyter', which failed to activate."
```

I would be thankful if you will provide me with some workaround.

Thank you :)

- Web Browser: Google Chrome
- Local OS: Windows 10
- Remote OS: Ubuntu 18.04
- Remote Architecture: ALB + EC2 + Openresty + code-server inside Docker container
- `code-server --version`: 3.8.0

**Comment by jsjoeio** [comment]
Hi @konradzadroga - sorry to hear you'rve having issues with the Python extension! 

Do you mind seeing if this issue has already been opened? Possible duplicates:
- https://github.com/cdr/code-server/issues/1837
- https://github.com/cdr/code-server/issues/2341

**Comment by stefanba3** [comment]
Can confirm, exact same error on the front end. I am on an EC2 Amazon Linux 2 VM.
There is no /home/coder/.local/share/code-server/extensions/ms-toolsai.jupyter-2020.12.1/client directory at all.

**Comment by jsjoeio** [comment]
Thanks for the additional information!

> Can confirm, exact same error on the front end

So this issue is a duplicate then? If so, we're going to close this issue. That will make it easier for us to track and fix this.

Looks like you may want to look at [this workaround](https://github.com/cdr/code-server/issues/2341#issuecomment-739562822)

**Comment by stefanba3** [comment]
This might be #2341, I'll look into it a bit and report back.

**Comment by stefanba3** [comment]
> This might be #2341, I'll look into it a bit and report back.

Installing 2020.10.332292344 from the Manage menu on the extension fixed this for me. Thanks! Similar workaround to #2341, but can just do it straight from the UI.

**Comment by jsjoeio** [comment]
Hooray! Sorry you had to use a workaround. We're close to switching over to a new extension marketplace which I hope helps with issues like these. Closing for now. Feel free to subscribe to the other issue so you get notified when a formal fix happens!

**Comment by ediphy-dcottrell** [comment]
> > This might be #2341, I'll look into it a bit and report back.
> 
> Installing 2020.10.332292344 from the Manage menu on the extension fixed this for me. Thanks! Similar workaround to #2341, but can just do it straight from the UI.

Can you confirm what that is? Version of what? Extension? code-server?

**Comment by stefanba3** [comment]
> > > This might be #2341, I'll look into it a bit and report back.
> > 
> > 
> > Installing 2020.10.332292344 from the Manage menu on the extension fixed this for me. Thanks! Similar workaround to #2341, but can just do it straight from the UI.
> 
> Can you confirm what that is? Version of what? Extension? code-server?

The extension. I also had to turn off automatic updates for it.

**Comment by jsjoeio** [comment]
I just installed the latest version v2021.5.829140558 with code-server 3.10.0 and it appears to be working. 

@keurfonluu 
If you think you've found a bug, please open a separate bug report and we'll be happy to look into it. 


https://user-images.githubusercontent.com/3806031/117868340-58169400-b24e-11eb-8150-ad624b7b26ed.mov
