### ISSUE TITLE
Document how to use code-server with Heroku

### ISSUE THREAD

**Issue by Grumpypjs08** [cdr/code-server#2686]
Heroku deploy link

**Comment by kaaax0815** [comment]
Heroku doesn't have the recommended requirements (2 Core Cpu, 1 GB Ram). You would need Standard, which there are more bang for the buck hoster then heroku

**Comment by jsjoeio** [comment]
@bpmct IIRC, didn't you put something like this together?

**Comment by bpmct** [comment]
code-server will run on Heroku even though it is below the minimum requirements. Here's the WIP: https://github.com/bpmct/code-server-heroku

I don't think it should be officially supported on this repo. Here's why:
- Volumes in Heroku do not persist, so all changes have to pushed to a git remote to prevent data loss
- Dependencies for your development (python, java, node14, github ssh keys) need to be installed at build-time for speed and consistency. This means you need to deploy your own image, not via an existing link.

I'm slowly working on something that makes it easier to build/reconfigure a code-server image with these things, and then it can be deployed to Heroku, hopefully by the press of a button.

I will include in my [awesome-code-server](https://github.com/awesome-code-server) repo which I can link in the README/docs.

**Comment by jsjoeio** [comment]
Thanks for the explanation, Ben! 

> I will include in my awesome-code-server repo which I can link in the README/docs.

Awesome! 

Can you also add an entry to FAQ that either explains how to deploy on Heroku or links to a section in awesome-code-server with instructions?

**Comment by bpmct** [comment]
> Heroku doesn't have the recommended requirements (2 Core Cpu, 1 GB Ram). You would need Standard, which there are more bang for the buck hoster then heroku

@kaaax0815 Are there any "app engines" like Heroku that make it quick to deploy a code-server containers? I know that I was experimenting with Amazon ECR and it worked pretty well.

**Comment by kaaax0815** [comment]
I use a KVM Server, because I deploy code-server in a Container with Caprover and Docker

**Comment by jsjoeio** [comment]
Closing via #2729 

If you still need help, please request to reopen this issue or [start a QA](https://github.com/cdr/code-server/discussions/new?category_id=22503114) on our Discussions board!
