### ISSUE TITLE
Crash when open big file

### ISSUE THREAD

**Issue by thesby** [cdr/code-server#2687]
- Web Browser: Chrome
- Local OS: Mac OS mojave
- Remote OS: centos 7
- Remote Architecture: x86-64 Intel
- `code-server --version`: 1.43.2

After I open any big file (about 100MB), the `code-server` will lose connection with the server, and pop up the reconnection dialog. But it will never reconnect successfully. And the only way is to reload the page.

**Comment by jsjoeio** [comment]
Are there any logs you can provide us with? Might be helpful to see what's happening.

> code-server --version: 1.43.2

Can you try using the latest version of code-server? `3.8.1`

> After I open any big file (about 100MB), the code-server

Can you provide a repo for us to use when reproducing this? (i.e. a repo with the 100MB file)
