### ISSUE TITLE
Open editor tab from command line with contents from stdin

### ISSUE THREAD

**Issue by soccermitchy** [cdr/code-server#2693]
VSCode supports opening files from the command line from stdin, by using `-` as the file name to open. For example, I can do:
```
kube@codekube:~/workspace$ kubectl get deployment codekube | code -
```
and I would have a new editor tab open with whatever `kubectl get deployment codekube` outputs. I'm currently emulating that feature with a script that creates a temporary file then calls `code-server name_of_temp_file`, but it's not the best solution, in my opinion.

**Comment by JammSpread** [comment]
I see, currently you might be able to use this as a workaround:
```
code-server $(kubectl get deployment codekube)
```

**Comment by soccermitchy** [comment]
Wouldn't that need the command to output a filename to open?

**Comment by JammSpread** [comment]
Oh nevermind, sorry, I misunderstood your question.

**Comment by JammSpread** [comment]
Oh never mind, I'm sorry I misunderstood your question. I see you meant that it would open a new untitled with the contents of whatever command you had piped in.
