### ISSUE TITLE
Extension marketplace unavailable

### ISSUE THREAD

**Issue by blaylockbk** [cdr/code-server#2700]
- Web Browser: Edge
- Local OS: Windows 10
- Remote OS: Linux
- Remote Architecture:
- `code-server --version`: 3.8.1, 3.8.0, and 3.7.4

After upgrading, I noticed my python extension isn't working anymore and wanted to reinstall, but I see that the marketplace is unavailable.  Tried with the above versions of code-server.

![image](https://user-images.githubusercontent.com/6249613/107269079-e84dfe80-69fd-11eb-88c0-6a8cb20abea0.png)

**Comment by aflextr** [comment]
now it is OK
