### ISSUE TITLE
request to upgrade to Visual Studio Code 1.53

### ISSUE THREAD

**Issue by aflextr** [cdr/code-server#2703]
Visual Studio Code new version released 1.53 please update?

**Comment by jsjoeio** [comment]
This should be out once we release `3.9.1` (hopefully before EOD!)

**Comment by aflextr** [comment]
> This should be out once we release `3.9.1` (hopefully before EOD!)

Can you update vscode version 1.54 released?
😀😁🤣

**Comment by jsjoeio** [comment]
HA! I know I know...we're behind forsure 😅 We know we're slow, but we do have plans to improve the process of updating VSCode more often and hopefully staying in sync with their release flow. Just know, we're working on it!

**Comment by aflextr** [comment]
haha, i was just kidding. I hope you will develop more code servers. Good work.
