### ISSUE TITLE
--link unable to set --host

### ISSUE THREAD

**Issue by accesstechnology-mike** [cdr/code-server#2704]
- Web Browser: Chrome
- Local OS: Win 10
- Remote OS: Ubuntu 20
- Remote Architecture: Linux
- `code-server --version`: 3.8.1

code-server --link defaults to 127.0.0.1 on launch and won't let me use the --host flag, and I need it to run on 0.0.0.0 to access it remotely. 

I would like to be able to assign the host by launching 'code-server --link --host 0.0.0.0'

**Comment by JammSpread** [comment]
Yup, expected behavior. I think it is supposed to be randomized as you can already just access the link provided after giving the flag.

**Comment by accesstechnology-mike** [comment]
> Yup, expected behavior. I think it is supposed to be randomized as you can already just access the link provided after giving the flag.

Thanks, I've edited the issue to only be concerned about changing the host address from 127.0.0.1 to 0.0.0.0

**Comment by code-asher** [comment]
To echo @JammSpread this is working as intended! You'll be able to access code-server through the address provided by `--link` so there's no need to try accessing code-server directly.
