### ISSUE TITLE
create script to install code-server with link

### ISSUE THREAD

**Issue by bpmct** [cdr/code-server#2709]
Is there a way to auto-start code-server link without the --link flag? Perhaps we could add to `config.yaml`? 

I'd love to work on a script to attach code-server + `--link` to a server and have it run on start. That way, people could set up a remote VM with code-server by doing:
1. create VM
2. paste install script into the [web shell](https://www.linode.com/docs/guides/using-the-linode-shell-lish/) (DigitalOcean, Linode, AWS)
3. navigate to `--link` URL and access their code-server. At any time, code-server can now be accessed via the coder URL.

This would eliminate the need to further configure the server (set up ssh keys, docker, etc) and instead use code-server as the primary access point to the server. Similar to sshcode, but with a domain and TLS set up too and no need to manage SSH keys :)

**Comment by jsjoeio** [comment]
That's a great idea! 🎉

> Is there a way to auto-start code-server link without the --link flag? Perhaps we could add to config.yaml?

I tested it locally and it looks like this is supported. You can set `link: true` in your `config.yaml`

<img width="1923" alt="image" src="https://user-images.githubusercontent.com/3806031/107552391-aef9c800-6b90-11eb-9186-86adae0aa342.png">
