### ISSUE TITLE
RasPi: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by catexis** [cdr/code-server#271]
## System info
OS Version:  
<pre>
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
</pre>
Docker version:
<pre>
Client:
Version:           18.09.0
API version:       1.39
Go version:        go1.10.4
Git commit:        4d60db4
Built:             Wed Nov  7 00:57:21 2018
OS/Arch:           linux/arm
Experimental:      false
Server: Docker Engine - Community
Engine:
Version:          18.09.0
API version:      1.39 (minimum version 1.12)
Go version:       go1.10.4
Git commit:       4d60db4
Built:            Wed Nov  7 00:17:57 2018
OS/Arch:          linux/arm
Experimental:     false
</pre>

## Description
Try to run command:  
```bash
docker run -d -t -p 8443:8443 -v "${PWD}:/root/project" codercom/code-server code-server --allow-http --no-auth
```  

Or:  
```bash
sudo docker run -t -p 127.0.0.1:8443:8443 -v "${PWD}:/root/project" codercom/code-server code-server --allow-http --no-auth
```  

And i see this:  
```bash
standard_init_linux.go:207: exec user process caused "exec format error"
```

**Comment by sr229** [comment]
I'm trying to debug this but it seems to boil down to `code-server` not recognizing PWD, or I might be wrong.

**Comment by catexis** [comment]
@sr229 : with PWD or without - same error

**Comment by sr229** [comment]
@catexis it seems we were running on a `armhf` platform, which sadly we don't compile against, yet.

refer to #35  for progress.

**Comment by nol166** [comment]
We have a new bundler that should make it possible for more CPU architectures to run the binary. Should be finished soon @catexis

**Comment by catexis** [comment]
Great to hear that! Thank you for your responce and support!

**Comment by RelievedStudios** [comment]
> We have a new bundler that should make it possible for more CPU architectures to run the binary. Should be finished soon @catexis

is there any news on when this will drop?

**Comment by sr229** [comment]
We're already using it AFAIK @RelievedStudios  but code-server's memory usage is far from optimal for Raspberry usage.

**Comment by code-asher** [comment]
Tracking here: https://github.com/cdr/code-server/issues/35
