### ISSUE TITLE
code-server for azure app service

### ISSUE THREAD

**Issue by aflextr** [cdr/code-server#2711]
Can you prepare the code-server docker image for Azure's app services?

**Comment by jsjoeio** [comment]
This is a great idea! cc @bpmct

**Comment by bpmct** [comment]
Haven't experimented with it yet, but I'd love to take a look!

**Comment by aflextr** [comment]
@bpmct Hello, how are things going? Maybe I can help you with this. Azure application service code server official docker image works normally, but we can't see the password and we can't access ssh via Azure. However, this link contains information on how to access ssh. If you can fix the ssh issue, you can probably easily create the custom code server image for the application service.

[https://docs.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-linux#enable-ssh](url)

**Comment by bpmct** [comment]
I'm getting to this today. I think a custom image is the right direction to go, so we can add SSH and support for using `code-server --link`. I'll share a GitHub for testing in a few hours :)

**Comment by bpmct** [comment]
Azure app service is a bit tough to debug, but I got code-server running with my custom image and I'm about to get SSH access+custom password configured. I'll publish the image/repo as soon as I do that. Some other things I'm looking to do:
- Experiment with Azure auth, see if we can use that as an auth layer for code-server
- Create a CLI/script to auto-deploy to Azure App service, tail logs

**Comment by bpmct** [comment]
Image is live: https://github.com/bpmct/code-server-azure. Will document soon. LMK if you have questions

**Comment by aflextr** [comment]
After entering the password, it stays on the white screen, so do you?

**Comment by bpmct** [comment]
I just deployed again and it works fine. Try refreshing once after entering the password?

**Comment by bpmct** [comment]
What app type are you using? I'm using this. Not saying this config is necessary, but it may be a hardware limitations thing:
```
P1V2
210 total ACU
3.5 GB memory
Dv2-Series compute equivalent
```

**Comment by aflextr** [comment]
I use the free app

Free F1
1 GB memory

**Comment by aflextr** [comment]
Farklı boyutta bir uygulama hizmeti kullandığımda işe yaradı, ancak ücretsiz boyutta çalışmadı. İlginç. ¯\_(ツ)_/¯

**Comment by bpmct** [comment]
I believe this is due to the SSH server using some resources. I am trying an image without (ssh `:no-ssh` tag) to see if that fixes it. If so, I will set that as an option to disable in the environment variable or see if there is a lightweight alternative.

**Comment by aflextr** [comment]
The free plan (f1) has a shortage of white screens, but other sizes do not. maybe there is a solution for the free plan.

**Comment by bpmct** [comment]
I noticed that "WebSockets" is off and "HTTP" version is low on the free plan. I changed this, as I noticed it was a websocket error. Still no luck. Just sharing findings so far.

**Comment by bpmct** [comment]
This is horribly documented, but I finally found this. I think this is our limitation: https://docs.microsoft.com/en-us/azure/app-service/faq-app-service-linux#web-sockets

**Comment by bpmct** [comment]
I *think* this could be resolved with the `--link` flag and using a tunnel instead. However, I believe the web service will still need something running on port 80 to keep the container alive. With `--link`, the port is randomized.

**Comment by bpmct** [comment]
I can mess with this in the morning with a workaround that makes a simple http server to redirect to the `--link` url based off the logs.

**Comment by aflextr** [comment]
Thank you for helping (● '◡' ●)

**Comment by aflextr** [comment]
@bpmct i used ngrok for the free plan and it worked. maybe the **code-server --link** could work.

**Comment by bpmct** [comment]
I updated the image to work with `--link` and added a dumb web server to keep Azure alive and redirect to the `--link` URL. It now works on the free version 🎉

The image will now run --link by default if $PASSWORD is not set

**Comment by bpmct** [comment]
@aflextr have you attached a volume to your Azure app? if so, would you want to document on the repo?https://github.com/bpmct/code-server-azure

**Comment by aflextr** [comment]
No unfortunately I couldn't add

**Comment by jsjoeio** [comment]
Closing via #2729 

@aflextr if you need more help after this, feel free to start a [QA on our Discussions](https://github.com/cdr/code-server/discussions/new?category_id=22503114)!
