### ISSUE TITLE
Resource  does not exists

### ISSUE THREAD

**Issue by sagarsiddhabhatti** [cdr/code-server#2716]
Getting below error while  building release debian package. 

```
error https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.3.tgz: 
Extracting tar content of undefined failed, the file appears to be corrupt: 
"EIO: i/o error, chmod '/src/.home/.cache/yarn/v6/npm-rxjs-6.5.3-510e26317f4db91a7eb1de77d9dd9ba0a4899a3a-integrity/node_modules/rxjs/_esm2015/internal/operators/retryWhen.js.map'"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
```

There is no resource. @  https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.3.tgz

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

**Comment by jsjoeio** [comment]
Can you please fill out the template with the information requested? 

Could it be some sort of network timeout? When I visit `https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.3.tgz`, I'm able to download the package.
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/3806031/107669939-7ec52e80-6c4f-11eb-8d4f-ec551af6e65d.png">

**Comment by sagarsiddhabhatti** [comment]
yeap it was network issue .
