### ISSUE TITLE
Link to FAQ on Welcome page is incorrect

### ISSUE THREAD

**Issue by MarkAYoder** [cdr/code-server#2725]
https://github.com/cdr/code-server/blob/41ad0c0c4c14df78e1bfa3a44d8b633ed2fc26e5/lib/vscode/src/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page.ts#L42

The above has doc/FAQ.md but should be doc**s**/FAQ.md

--Mark

**Comment by MarkAYoder** [comment]
There's more than one "doc" that should be "docs".

https://github.com/cdr/code-server/blob/41ad0c0c4c14df78e1bfa3a44d8b633ed2fc26e5/lib/vscode/src/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page.ts#L42-L44

**Comment by JammSpread** [comment]
Not only are these links incorrect but also the unofficial extensions warning seems to use the doc path.

**Comment by jsjoeio** [comment]
Thanks for the catch! I didn't realize there was more than one. I'll fix all of these in https://github.com/cdr/code-server/pull/2743

**Comment by jsjoeio** [comment]
Closing via #2743
