### ISSUE TITLE
Code Server 3.9.0 result in error 500 with no extra error messages.

### ISSUE THREAD

**Issue by 7HE-W0R1D** [cdr/code-server#2732]
- Web Browser: Chrome
- Local OS: Win10 64 Build 21313
- Remote OS: Raspbian Buster lite
- Remote Architecture: armv6l
- `code-server --version`: 3.8.0 c4610f7829701aadb045d450013b84491c30580d
- `code-server --version` previously: 3.9.0 fc6d123da59a4e5a675ac8e080f66e032ba01a1b

I'm on a raspberry pi zero w here. When I install code server like half a month ago, I can successfully build and run it--even with some error messages saying some modules were lost. Now when I install code server 3.9.0, I get the same 500 error with no extra error messages, not even when have `--log trace`, which makes it impossible to find where the bugs are. Then I run `yarn global add code-server@3.8.0`, the previous detailed error messages were back. Is it a bug? or are the logs simply moved to some other places?

**Comment by 7HE-W0R1D** [comment]
![image](https://user-images.githubusercontent.com/42311695/108072901-6ebfab80-70a2-11eb-838b-54355d343a58.png)
The above is a screenshot of code server 3.9.0 with `-vvv` on, while below it what code server 3.8.0 with no extra parameters
![image](https://user-images.githubusercontent.com/42311695/108073130-a75f8500-70a2-11eb-80e4-ddaf86d666b0.png)
![image](https://user-images.githubusercontent.com/42311695/108073159-af1f2980-70a2-11eb-8793-ae64a87e2b76.png)

**Comment by code-asher** [comment]
I'm going to close this since we've been discussing it here: https://github.com/cdr/code-server/discussions/2692
