### ISSUE TITLE
Open multiple projects or one code-server per project

### ISSUE THREAD

**Issue by ytjohn** [cdr/code-server#274]
Running code-server-1.32.0-275-darwin-x64.

I was wondering if you have to run one instance of code-server per project, or if you are supposed to be able switch between projects once code-server is up and running. If you can switch or have multiple projects open at once, that would be perfect. If I have to do one instance per project, then I need to work with multiple ports or multiple sub-domains, one per project.

When I try to open a folder in vscode (via code-server) I get `Unable to open '<directory>': File is a directory.`

![image](https://user-images.githubusercontent.com/163156/54492109-05bdd080-489a-11e9-8089-9ee683dbd719.png)

Adding a folder to the workspace seems to break things and just renders a blank screen.

**Comment by sr229** [comment]
use the Open Folder Keystroke combination (Ctrl+ K+O), it should tell code-server to listen to that folder.

Keep in mind code-server only uses one instance, there’s no multiple instances per folder, which would be highly unoptimized

**Comment by vapask** [comment]
> use the Open Folder Keystroke combination (Ctrl+ K+O), it should tell code-server to listen to that folder.
> 
> Keep in mind code-server only uses one instance, there’s no multiple instances per folder, which would be highly unoptimized

It does not work either. The same error: `Unable to open '<directory>': File is a directory`

**Comment by sr229** [comment]
weird, it works on my machine though....

[And this is supposed to be *solved* by Docker, shame on you Docker marketing]

**Comment by kaysond** [comment]
@sr229 I'm trying to use the open folder keystroke, but I can't select subfolders.

For example, I've mapped `/home/coder/project` on the container to `~/git`. Within `~/git` I have several subfolders pointing to different git respositories. I want to access those as individual projects, but as soon as I click the `project` subfolder, it selects that rather than showing its subfolders.

Any ideas?

**Comment by sr229** [comment]
Was this on the folder selection?

**Comment by kaysond** [comment]
Correct. You'll see in this screenshot that I've got several subfolders under `/home/coder/projects`. But as soon as I click `projects` in the dialog box, the dialog disappears

![image](https://user-images.githubusercontent.com/1147328/58741074-3954c500-83ca-11e9-9163-7285eb07e229.png)

**Comment by sr229** [comment]
This might merit as a bug

CC @coadler

**Comment by kaysond** [comment]
Well I copied `~/git` to `~/git2`, removed `~/git` then renamed `~/git2` to `~/git`, and now the problem is gone... no idea why

**Comment by code-asher** [comment]
We used to have a bug where opening a folder would try to open it as a file which sounds like it might be this? The open dialog has been completely redone in v2 so if there are any issues on it definitely ping me here or create a new issue.

**Comment by ytjohn** [comment]
I kind of forgot about this. But after seeing your update I went ahead and tried the latest v2 and it works perfectly - able to open 1 project per tab.  

On a personal note, this comes at a good time because I recently changed jobs and was revisiting the idea of running all my development on a server instead of my laptop.

**Comment by kaysond** [comment]
So I tried this on v2. And while I don't have an issue opening a different folder anymore, the UI is kind of a total mess on Firefox.

If I manually type in the path then it OK, it works just fine. But if I'm navigating through the hierarchy and clicking on folders, it doesn't update the path text, making click-based navigation pretty much impossible.

**Comment by code-asher** [comment]
Yeah Firefox has some really weird issues with the open dialog. https://github.com/cdr/code-server/issues/1063
