### ISSUE TITLE
IPYNB files open as raw text instead of Jupyter GUI

### ISSUE THREAD

**Issue by itaynvn** [cdr/code-server#2741]
im running code-server in an ubuntu 16.04 docker container
until now, i used v3.4.1, and now i decided to upgrade to v3.9.0

the issue im facing: IPYNB notebook aren't opened in Jupyter GUI (as they used to, in version 3.4.1)
im just seeing the raw content:
![image](https://user-images.githubusercontent.com/61652839/108338988-8cdef600-71df-11eb-9310-c5a7fcc2683c.png)

instead of the GUI and cells

- Web Browser: google chrome
- Local OS: macOS bigsur
- Remote OS: ubuntu 16.04
- Extensions:
Jupyter (ms-toolsai.jupyter) v2021.2.0
Python (ms-python.python) v2021.1.502429796
- Remote Architecture:
- `code-server --version`: 3.9.0 fc6d123da59a4e5a675ac8e080f66e032ba01a1b
-

**Comment by code-asher** [comment]
Could you post the logs from the browser console? This might be related to the general issues we've been having with Jupyter and Python recently.

**Comment by itaynvn** [comment]
hi @code-asher , thanks for the fast response :) 
here's the console error, triggered when i opened the IPYNB file:
![Screen Shot 2021-02-23 at 18 32 17](https://user-images.githubusercontent.com/61652839/108875744-2a825d00-7606-11eb-8fc8-314fd236ad72.png)

**Comment by itaynvn** [comment]
hi @code-asher , thanks for the fast response :)
here's the console error, triggered when i opened the IPYNB file:
![Screen Shot 2021-02-23 at 18 32 17](https://user-images.githubusercontent.com/61652839/108876795-433f4280-7607-11eb-912e-447135b38902.png)

**Comment by code-asher** [comment]
Ahh yup it looks like the same issue in https://github.com/cdr/code-server/issues/2341. I'll close this in favor of that one.

Some workarounds are:
  - Install the vsix manually after downloading from the marketplace.
  - Install an older version

More details can be found in the linked issue!
