### ISSUE TITLE
Help with black screen on IPad

### ISSUE THREAD

**Issue by FOOincognita** [cdr/code-server#2747]
- Web Browser: Chrome, Safari 
- Local OS: IPadOS 14.4, IPad Air 4th gen.
- Remote OS: Ubuntu 16.04, Ubuntu 18.04, Ubuntu 20.04 (I have tried all 3)
- Remote Architecture: AMD64
- `code-server --version`:  
- 1.408-vsc1.32.0 with Ubuntu 16.04
-  3.4.0 & 3.9.0 with Ubuntu 18.04 & Ubuntu 20.04 (all combinations)
- Google Cloud Platform VM Instance (32GB SSD, 4 cores, 8GB RAM, HTTPS/HTTP traffic enabled)

Howdy! I am a university student, and Code-Server would be absoluetly perfect for me so that I could have a remote instance of VS Code for when I am away from my main PC. Unfortunately, I can only gte it to work on other PCs, and not my IPad. If I could get it working on my IPad, it would seriously be a life-saver. 

Please keep in mind I have incredibly little experience with linux besides C++ compilation through WSL, and Code-server basic install and run, but the instructions on this GitHub for authentication or SSH are pure gibberish to me, so maybe that's my issue? 

I have looked all over YouTube, this GitHub, message boards, and more, but I can't seem to resolve the black screen issue (allows me to enter password, but then goes to black screen with webpage fully loaded). Code-Server is runny seamlessly for any of my PC browsers, though, whenever I try to access the VM through my IPad on any browser, I get the same issue; It will not show anything other than a black screen after correct password entry. 

I have seen other say its an HTTPS issue, something about authentication errors specific to the IPad, but I honestly only have experience with C++, and that's honesty it; I have no clue how to go about fixing that.

Now, I found an app called "Servereditor for code-server" that allows you to pay for a pre-built instance, or allows you to connect to a self-host. The paid server connects just fine, but it is missing the most important feature; access to bash for code compilation and page installs. When I try to connect to my self-hosted server via the URL, it brings up the password screen, then just says "Invalid Password", even if I copy and paste the password directly from cloud console...I am out of ideas and was hoping maybe I missed a post somewhere where someone found a way to fix it?

Please let me know, and thank you for your time!

**Comment by jsjoeio** [comment]
Hey @FOOincognita - sorry to hear you've run into some issues with code-server on iPad!

We would love to help you figure this out. I'm going to move this over to our Discussions page.
