### ISSUE TITLE
Access code-server via Remote-SSH

### ISSUE THREAD

**Issue by reworkk** [cdr/code-server#2748]
Is it possible to use vscode server via https with interface in vscode (not in browser)? Something like Remote-SSH.

**Comment by reworkk** [comment]
@jsjoeio

**Comment by futureproperty** [comment]
+1，good idea

**Comment by cmoog** [comment]
You could create an HTTP tunnel where you pipe TCP between the client and server machines over an HTTP connection. Then you'd connect via VS Code Remote SSH just like normal, except you'd dial the tunnel. 

A simple implementation I found for Nodejs: https://github.com/johncant/node-http-tunnel (haven't tested).

**Comment by jsjoeio** [comment]
Yeah, echoing what @cmoog said, seems like that might be the quickest option. 

@bpmct this might make for a great YouTube video or tutorial? thoughts?

**Comment by jsjoeio** [comment]
Okay spoke with my teammates about this.

> Remote-SSH is a replacement for code-server, not really an access method for it

So really, you'd be just using VSCode and wouldn't need code-server. 

But, if you're trying to set up "the ultimate remote dev environement" (as @bpmct put it) where you could seamlessly switch between code-server, VSCode Remote, etc. then that might be a different story. 

Quoting @bpmct here:
> We could do a video for the “ultimate remote dev environment” where we set up some VM with
> - code-server --link (iPads, Chromebooks)
> - VS Code Remote - connecting from any VS Code client
> - proxying ports with a domain
> - syncing vs code settings across Remote SSH+code-server
> 
> ^ But code-server itself doesn’t really support using VS Code Remote. You still would have to set up ssh keys or that tcp 
tunnel

@reworkk feel free to add your thoughts that might clarify what you hope to accomplish and we'll do our best to help (if that means recording a video, adding a feature, etc)!

**Comment by code-asher** [comment]
Might be a dup of https://github.com/cdr/code-server/issues/1315.
