### ISSUE TITLE
docker extension not work

### ISSUE THREAD

**Issue by vipwp** [cdr/code-server#2756]
- Web Browser:chrome 88.0.4324.96
- Local OS: windows 10 
- Remote OS: centos 7
- Remote Architecture: amd64
- `code-server --version`: 3.9.0

extension id: ms-azuretools.vscode-docker
docker extension version: v1.10.0

The extension work on 3.6, but then I updated to 3.9.0, the extension get this error.

```
/opt/code-server/code-server-3.9.0-linux-amd64/lib/vscode/node_modules/proxy-agent/node_modules/agent-base/dist/src/index.js:184
                Promise.resolve(this.promisifiedCallback(req, opts)).then(onsocket, callbackError);
                                                                     ^

RangeError: Maximum call stack size exceeded
```

**Comment by jsjoeio** [comment]
Hmm... sorry to hear there's an issue @vipwp 

Do you mind providing reproduction steps?

**Comment by vipwp** [comment]
> Hmm... sorry to hear there's an issue @vipwp
> 
> Do you mind providing reproduction steps? And can you try disabling all other extensions and see if this issue still occurs?

When I start a new server on a new host with clean user data and install docker extension, it works well.But when I do the same thing on the old host ,the issue still occurs.

**Comment by vipwp** [comment]
the chrome console error

`console.ts:137 [Extension Host] stack trace: Error: Request failed with status code 404	at createError (/opt/code-server/extensions/ms-azuretools.vscode-docker-1.10.0/dist/extension.bundle.js:65:196535)	at settle (/opt/code-server/extensions/ms-azuretools.vscode-docker-1.10.0/dist/extension.bundle.js:185:25594)	at IncomingMessage.handleStreamEnd (/opt/code-server/extensions/ms-azuretools.vscode-docker-1.10.0/dist/extension.bundle.js:799:28401)	at IncomingMessage.emit (events.js:327:22)	at endReadableNT (_stream_readable.js:1220:12)	at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by jsjoeio** [comment]
> When I start a new server on a new host with clean user data and install docker extension, it works well

Well that's a positive sign.

> But when I do the same thing on the old host, the issue still occurs.

We're happy to look into this more if you provide steps to reproduce!
