### ISSUE TITLE
C/C++ Debugger

### ISSUE THREAD

**Issue by TheScientist101** [cdr/code-server#2757]
- [ ] Extension name: C/C++
- [ ] Extension GitHub or homepage: https://github.com/microsoft/vscode-cpptools
The extension exists, but does not correctly install, if this is not possible to optimize, is there another good C debugger that works?

This is my first GitHub Issue thing, please let me know what to improve.

**Comment by balajib-b** [comment]
Could you please submit screenshot of any error or the extensions pane atleast.
I tested it with extension version 1.2.2 on code-server 3.9.1 running on Ubuntu 20.04 host. 

it is installed properly and working fine. You can see the extension Name, Version and Installation status

![Screenshot_20210309_123133](https://user-images.githubusercontent.com/64471553/110431168-7091f300-80d3-11eb-9e06-7ac2b3c7fd10.png)

**Comment by code-asher** [comment]
Might be a duplicate of https://github.com/cdr/code-server/issues/2120?

**Comment by TheScientist101** [comment]
I am on version also on version 1.2.2 running on code-server 3.9.1. I am running it on Kali Linux on WSL 2.0. It does successfully install but gives me the error below.
![image](https://user-images.githubusercontent.com/66270347/110528654-016dcc00-80de-11eb-824c-64fa6a14cb3a.png)

**Comment by balajib-b** [comment]
@TheScientist101, could you please help us with following questions?
1.  You are able to compile your project files in WSL terminal? 
2. Other extensions are installed and working properly?
3. GCC and G++ compilers are compatible with the extension?

Moreover, openvsx marketplace extensions are tightly compatible with code server. Visual studio market place extension works fine but not officially supported.

 Just in case you could try the equivalent openvsx extension if any, while we debug the issue

**Comment by TheScientist101** [comment]
I am able to compile the programs from the terminal, however I cannot get the debugger to work. I am able to get other extensions to work, just not this one.

**Comment by code-asher** [comment]
Hmm yeah that definitely looks like https://github.com/cdr/code-server/issues/2120 to me. The ELF error is usually because it's running a binary built for the wrong architecture.

**Comment by TheScientist101** [comment]
I guess I should close this then.
