### ISSUE TITLE
Cloud agent doesn't support Termux

### ISSUE THREAD

**Issue by GNUxeava** [cdr/code-server#2758]
- Web Browser: It hardly matters in this case but here you go: Microsoft Edge 90.0.796.0 (Official build) dev (64-bit)
- Local OS: Android 10 Funtouch 10.0 (non-rooted Vivo Y50)
- Remote OS:  Arch Linux 5.10.16-arch1-1
- Remote Architecture: x86_64
- `code-server --version`: 3.9.0 fc6d123da59a4e5a675ac8e080f66e032ba01a1b
# Log file
[error.log](https://github.com/cdr/code-server/files/6030120/error.log)

# Steps to reproduce
- Update Termux by running `apt update && apt upgrade`
- Install required packages with `apt install build-essential python git nodejs yarn`
- Install code-server with `yarn global add code-server` (this step took around 20 minutes on my phone)
- Edit `~/.config/code-server/config.yml` to be able to connect to code-server from other devices on the same network
- In Termux, run `code-server --link`. It exits with the same error when trying to run `code-server --link subdaminname`

# Result
![image](https://user-images.githubusercontent.com/21287366/108872287-059ae380-7620-11eb-8a59-33236b50c804.png)

**Comment by jsjoeio** [comment]
Thanks for the detailed issue and error log! I'm not super familiar with Termux. Could I follow your reproduction steps on my Android phone (Pixel 2)? 

Either way though, looks like some issue with coder-cloud-agent

**Comment by jsjoeio** [comment]
WOW! I didn't realize you could do this with an Android phone. This is insane.

Anyways, skipped the Edit `config.yml` step and was able to reproduce the issue. Guessing we need to take a look at `--link`. 

![Screenshot_20210223-102713](https://user-images.githubusercontent.com/3806031/108882573-c8076d80-75c1-11eb-8d0a-488b8183ee5b.png)

**Comment by code-asher** [comment]
I don't believe we ship agent binaries that work on Termux. :(

**Comment by jsjoeio** [comment]
Could we change that?

**Comment by code-asher** [comment]
I believe so, but I'm honestly not sure what it involves.

**Comment by iamSlightlyWind** [comment]
* Local OS: Aarch64 Ubuntu 18.04 Chroot (Linux Deploy - Rooted T865)
* `code-sever --version`: `3.9.0 fc6d123da59a4e5a675ac8e080f66e032ba01a1b`


**Step to reproduce:**

* ssh into Ubuntu `with Termux`
* Update `sudo apt-get update`
* Install my required package `sudo apt-get install git build-essential python`
* Install `code-server` `curl -fsSL https://code-server.dev/install.sh | sh`
* run `code-server --link`


**Log**
* [log](https://pastebin.com/6MgFaEBB)




How about ubuntu arm64 running in chroot then:(

**Comment by code-asher** [comment]
I suspect we only ship amd64 binaries.

**Comment by oxy** [comment]
Waiting on https://github.com/cdr/cloud-agent/pull/13 right now.

**Comment by AirplanegoBrr** [comment]
Is this fixed yet?

**Comment by oxy** [comment]
Should actually be fixed! We do ship arm64 binaries now and they should be downloading correctly.
