### ISSUE TITLE
Cannot automatically reconnect when code-server restarts

### ISSUE THREAD

**Issue by fxxjdedd** [cdr/code-server#2764]
Steps to reproduce:

1. `code-server` to start server
2. Open code-server web page
3. `ctrl + c` exit server
4. `code-server` to restart server
5. Wait for the web page to reconnect

But it won't automatically reconnect, unless you refresh the page manually,  is it a bug?

- Web Browser: chrome
- `code-server --version`: 3.9.0

**Comment by fxxjdedd** [comment]
Seems to be the same problem: https://github.com/cdr/code-server/issues/2697#issuecomment-780685621

**Comment by code-asher** [comment]
Yup, that's exactly right. We'll at least make it so VS Code tells you a refresh is required but we'll track that in #2697.
