### ISSUE TITLE
yarn on Termux cannot install code-server 3.9.0

### ISSUE THREAD

**Issue by NotAlone777** [cdr/code-server#2768]
I tried to install code-server with `yarn global add code-server` in termux, but the following prompt appeared
![image](https://user-images.githubusercontent.com/49009400/109176195-86ddac00-77c1-11eb-9753-de2a7260b26f.png)

**Comment by jsjoeio** [comment]
Hi @NotAlone777 - sorry to here isn't not working as expected.

I was able to get code-server 3.9.0 installed on Termux following these steps (thanks to @GNUxeava).

Can you please try again?
1. Update Termux by running `apt update && apt upgrade`
2. Install required packages with `apt install build-essential python git nodejs yarn`
3. Install code-server with `yarn global add code-server` 
4. Run code-server with `code-server`

See comment: https://github.com/cdr/code-server/issues/2758#issuecomment-784373210

Possibly related:
- https://github.com/cdr/code-server/issues/2758
- https://github.com/cdr/code-server/issues/2745
- https://github.com/cdr/code-server/issues/2749

**Comment by starryalley** [comment]
I'm having exactly the same issue as @NotAlone777 . Have you resolved this?

**Comment by jsjoeio** [comment]
@starryalley did you try following [these steps](https://github.com/cdr/code-server/issues/2768#issuecomment-786758980)?

And if you don't mind, can you post your OS information: 
- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

I'm not sure why it's failing...You could also try `yarn global remove code-server` to start over.

**Comment by starryalley** [comment]
Yes I followed the exact step. I'm running on termux (latest on F-droid) on my Android 11 Samsung S21. code-server cannot be installed due to the same error seen by @NotAlone777 so it's not able to `yarn global remove` it.  


![Screenshot_20210313-113325_Termux](https://user-images.githubusercontent.com/1099404/111012530-6849f880-83f0-11eb-9410-5d6005c6de4a.jpg)

It's worth mentioning that I first installed termux from Google Play (the deprecated version) and followed the same step. No errors seen there and I can successfully run code-server without problem. Any idea?

**Comment by starryalley** [comment]
Never mind @jsjoeio , I think it's my setup issue.

After running
`export LD_PRELOAD=${PREFIX}/lib/libtermux-exec.so` as noted from [here](https://wiki.termux.com/wiki/Termux-exec), I'm able to install code-server without issue now. Thanks.

**Comment by jsjoeio** [comment]
Ahhh! Interesting. Glad you found that and were able to get it working. I installed Termux from Google Play too, maybe I have a newer version.

Thanks for posting the solution! 🙌

@NotAlone777 are you able to see if this solution works for you as well? Then we could close this issue.

**Comment by NotAlone777** [comment]
> Ahhh! Interesting. Glad you found that and were able to get it working. I installed Termux from Google Play too, maybe I have a newer version.
> 
> Thanks for posting the solution! 🙌
> 
> @NotAlone777 are you able to see if this solution works for you as well? Then we could close this issue.

Thank you, I successfully installed it.👍

**Comment by rajeshisgood** [comment]
Did any of you used armv7l ?
