### ISSUE TITLE
Contributing Is Missing Requirements

### ISSUE THREAD

**Issue by vapurrmaid** [cdr/code-server#2771]
## Story

[CI was failing on a PR](https://github.com/cdr/code-server/pull/2770/checks?check_run_id=1980623851) so I ran `yarn fmt` locally as was suggested in the run output:

> ```
> $ ./ci/dev/fmt.sh
> Files need generation or are formatted incorrectly:
> HEAD detached at c2de72a9
>	modified:   docs/FAQ.md
>	modified:   docs/install.md
> Please run the following locally:
>  yarn fmt
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
>```

But I received:

>```
> ./ci/dev/fmt.sh: line 7: shfmt: command not found
>```

which implies there's a non standard package missing from the development requirements, `shfmt`.

I tried to inspect the image referenced in the contributing documents <https://github.com/cdr/code-server/blob/v3.9.0/docs/CONTRIBUTING.md#requirements>

But it's a dead link:

https://github.com/cdr/code-server/blob/v3.9.0/ci/images/debian8/Dockerfile

![Screenshot from 2021-02-25 10-28-55](https://user-images.githubusercontent.com/11184711/109184142-4bf15f00-7754-11eb-8087-e393e82a3931.png)

**Comment by vapurrmaid** [comment]
I'm happy to contribute this change with some guidance on which `shfmt` is required. A quick Google shows more than one package by that name:

![Screenshot from 2021-02-25 10-38-32](https://user-images.githubusercontent.com/11184711/109185470-a6d78600-7755-11eb-8cef-b904092e3067.png)

**Comment by jsjoeio** [comment]
@vapurrmaid remember when I had all those issues with getting Go to be included and work in my Coder env? This was the main root of the issue. I vote to replace `shfmt` with something else honestly.

**Comment by code-asher** [comment]
`go get mvdan.cc/sh/v3/cmd/shfmt` should get the right `shfmt`. We should definitely add this to the docs.

**Comment by code-asher** [comment]
I'm also down for something else; feels odd you'd need go just to download a dep. Alternatively we make all dev commands run in our dev container so then the only dependency is Docker.

**Comment by code-asher** [comment]
Also it looks like this happened because we merged a commit from a fork which didn't have CI running on it so we didn't catch the fmt error. So we should look into that as well.

**Comment by jsjoeio** [comment]
Agreed!

> I'm also down for something else; feels odd you'd need go just to download a dep

I opened a separate issue: https://github.com/cdr/code-server/issues/2772

For the CI running on forks: https://github.com/cdr/code-server/issues/2559

## Todo

For this issue,
- [ ] update docs with contributing requirements and add `go get mvdan.cc/sh/v3/cmd/shfmt`

**Comment by vapurrmaid** [comment]
Closed in #2775
