### ISSUE TITLE
[dev]: replace `shfmt` dependency

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#2772]
As discussed in https://github.com/cdr/code-server/issues/2771#issuecomment-786048013, it seems silly to require Go and one dependency to contribute to code-server. 

## Alternative Options

- make all dev commands run in our dev container so then the only dependency is Docker.
- use a prettier plugin like [`prettier-plugin-sh`](https://www.npmjs.com/package/prettier-plugin-sh)
- something else

The goal of this issue is to replace the use of `shfmt` in code-server.

**Comment by code-asher** [comment]
Fixed in https://github.com/cdr/code-server/pull/2891.
