### ISSUE TITLE
Expose Coder Name to Extension

### ISSUE THREAD

**Issue by yorrd** [cdr/code-server#2791]
I'm writing internal tooling and would like to access the coder's name (or URL) from within an installed extension in that specific coder. Is there an API for that?

**Comment by code-asher** [comment]
We have an issue to add an environment variable that extensions could use to get the URL: https://github.com/cdr/code-server/issues/1510#issuecomment-668158890

One workaround is to add a query variable to the URL. Query variables are stored in `[XDG data dir]/coder.json` file so you can read that from your extension.

So for example you could make the URL`mycodeserver.com?name=test` then in your extension you can get that name with `require(`${dataPath}coder.json`).query.name`.

**Comment by yorrd** [comment]
thanks! Will do. Another option that came up in a recent discussion is to use the hostname. They should be set correctly for our containers, so that would also work. Thanks for the input. If you dont need the issue anymore, feel free to close. Not sure how to proceed here.

**Comment by code-asher** [comment]
Ah yeah hostname sounds like a great idea! I'll go ahead and close since we have the other issue.
