### ISSUE TITLE
paste in terminal failed in suse code-server

### ISSUE THREAD

**Issue by alianZhen** [cdr/code-server#2795]
I can paste in terminal in  Alpine Linux

But this action is failed in SUSE Linux.

Is there any solution for this?

**Comment by jsjoeio** [comment]
Hi! Thanks for opening an issue. Can you please fill out the issue template and provide reproduction steps?

Thanks!

**Comment by t0xic0der** [comment]
@alianZhen are you using SSL/TLS (simply put are you using HTTP or HTTPS?)

Using the code-server in an unsecured domain disables a lot of features which also includes multi-step copy-paste from the webterminal.
