### ISSUE TITLE
Extension help dismiss button disappears

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#2799]
- Switch to extensions sidebar
- Refresh page
- Dismiss button disappears after a while

If a different sidebar is showing while VS Code loads then you switch to the extensions sidebar everything is OK. It's only when you load the page with the extensions sidebar enabled.

**Comment by vapurrmaid** [comment]
Fixed by 3e081ea66c5a38bc9898ac616951c47841440d4c
