### ISSUE TITLE
Update AUR package to 3.9.1

### ISSUE THREAD

**Issue by rabidpug** [cdr/code-server#2802]
The AUR package is currently v3.8.1

Thanks!

**Comment by jsjoeio** [comment]
cc @code-asher

**Comment by jsjoeio** [comment]
Update: currently working on this. Hoping to get an update for `3.9.1` out soon.

Also made a new issue to see how we can improve this process for the future. See #2845

**Comment by jsjoeio** [comment]
This has been updated! https://aur.archlinux.org/packages/code-server/
