### ISSUE TITLE
File download over ~30MB fails because file picker fails to open

### ISSUE THREAD

**Issue by josephl310** [cdr/code-server#2808]
Unable to download files larger than some threshold (around 30 MB, not sure on the exact number though) in Chrome and Firefox. I have vscode embedded in an iframe, and browser security measures don't allow vscode to open the directory picker. It would be great to have some sort of fallback in these scenarios so that the file downloads to ~/Downloads by default.

- Web Browser: Chrome
- Local OS: Mac OSX
- Remote OS: Ubuntu 20.04
- Remote Architecture: x86_64
- `code-server --version`: 3.8.0

**Comment by josephl310** [comment]
Actually, I'm going to file this in the vscode repo directly. Sorry!

**Comment by jsjoeio** [comment]
@josephl310 if you think this is an upstream issue, it be best to:
- open an issue upstream
- link here
- close this issue

> Since this is an issue specific to VSCode in the browser

I _believe_ issues with GitHub Codespaces (i.e. VSCode in the browser) are still being tracked in the vscode repo so I think you could still open there.

**Comment by josephl310** [comment]
Gotcha, thanks! I'll open an issue in the VSCode repo.
