### ISSUE TITLE
Code-server doesn't respond

### ISSUE THREAD

**Issue by Paultje52** [cdr/code-server#2810]
When I start code-server with `sudo code-server`, `code-server` or `sudo systemctl enable --now code-server@$USER`, it just doesn't respond when I try to go to the website. I tried deleting the configs, reinstalling code-server with the installation script, but nothing works.

I use the latest code-server version, `3.9.0 fc6d123da59a4e5a675ac8e080f66e032ba01a1b`

When I run `sudo ufw allow 8080`, I get this.
```
Skipping adding existing rule
Skipping adding existing rule (v6)
```

So this isn't a problem with a firewall. I'm trying to access it directly, not via a domain or nginx/apache, so it's a problem with code-server.

**Comment by Paultje52** [comment]
When I look at the logs, I don't see anything strange.
```
Mar 02 19:44:16 vps.server.com systemd[1]: Started code-server.
Mar 02 19:44:24 vps.server.com code-server[364]: [2021-03-02T19:44:24.649Z] info  code-server 3.9.0 fc6d123da59a4e5a675ac8e080f66e032ba01a1b
Mar 02 19:44:24 vps.server.com code-server[364]: [2021-03-02T19:44:24.660Z] info  Using user-data-dir ~/.local/share/code-server
Mar 02 19:44:24 vps.server.com code-server[364]: [2021-03-02T19:44:24.711Z] info  Using config file ~/.config/code-server/config.yaml
Mar 02 19:44:24 vps.server.com code-server[364]: [2021-03-02T19:44:24.711Z] info  HTTP server listening on http://45.13.59.13:8080
Mar 02 19:44:24 vps.server.com code-server[364]: [2021-03-02T19:44:24.711Z] info    - Authentication is enabled
Mar 02 19:44:24 vps.server.com code-server[364]: [2021-03-02T19:44:24.712Z] info      - Using password from ~/.config/code-server/config.yaml
Mar 02 19:44:24 vps.server.com code-server[364]: [2021-03-02T19:44:24.712Z] info    - Not serving HTTPS
Mar 02 19:46:12 vps.server.com systemd[1]: /usr/lib/systemd/system/code-server@.service:6: Failed to parse service type, ignoring: exec
```

**Comment by jsjoeio** [comment]
Hi @Paultje52 - thanks for opening the issue. Can you please fill out the issue template and provide steps to reproduce?

**Comment by Paultje52** [comment]
Hello. Apparently, nginx was interfering somehow. I don't know how or why, but by stopping it it's fixed. Sorry to take up your time1

**Comment by jsjoeio** [comment]
No worries, glad you figured it out!
