### ISSUE TITLE
Add support for the `--wait` cli option

### ISSUE THREAD

**Issue by pelletencate** [cdr/code-server#2816]
As a **user** I'd love to be able to **use `code-server -w` as my $EDITOR** in my integrated terminal
so I can **open/edit files from within other scripts and tools that will wait for me to edit and close a file**, such as various `git` commands, or `rails credentials:edit` that needs to encrypt after saving/closing, without having to resort to neovim on the temrinal.

```
$ code-server --wait path/to/file.txt
```

or

```
$ export EDITOR="code-server --wait"
$ git merge some/dirty/branch
```

**Comment by code-asher** [comment]
Thank you for the feature request!

We have an issue for this here: https://github.com/cdr/code-server/issues/2110
