### ISSUE TITLE
☂️ [Roadmap]: Clean Up

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#2818]
This is an umbrella issue to related to one of our priorities for code-server: clean up.

They're chores. Think of this as cleaning up the repository and making things easier both for maintainers and contributors.

### 1. Easier for Maintainers

code-server is a big project. The easier to maintain, the faster we can fix bugs, ship features and help the community.

- ✅ separate unit and e2e testing #2646 
- ⏳ improve updating vscode process
  - ⏳ improve existing script #2787 
  - figure out a way to pull in their changes on a regular cadence (so updating is easier)
- ⏳ pre-install script that checks dependencies #2807 
- 🚧 automate release process #2817 
  - ✅ automate first step of process #2952 
  - TODO automate attaching artifacts to release
- ✅ add `homebrew` job to `publish.yaml` #2841
- ⏳ add `aur` job to `publish.yaml` #2845 
- TODO investigate dropping `nfpm` see [comment](https://github.com/cdr/code-server/pull/2891#discussion_r594724298)
- TODO clean up images [see comment](https://github.com/cdr/code-server/pull/2891#discussion_r594731273)
  > particularly in light of the fact that CentOS changed their model recently with CentOS Stream
- ⏳ split up github workflows #2903 
- ⏳ try changing `esModuleInterop` to false

### 2. Easier for Contributors 

If we want to encourage contributions from the community (and even Coder employees), we need to make it as simple as possible to contribute. 

- ✅ Remove `shfmt` as a dependency #2772 
- ⏳  "...maybe we could make an image to do code-server development inside code-server, and also a variant for code-server development inside coder." —@jawnsy https://github.com/cdr/code-server/pull/3134#pullrequestreview-636157886

### 3. Remove Dead Code

We need to do an analysis to see how much unused code exists in the code-server codebase. This could slim down the size, maybe help performance but also help with maintenance long-term. 

- ✅ remove pages/updates.css #2823 
- TODO add more tasks here

### 4. Improve Security Practices

We want to make sure we're staying on top of security vulnerabilities in code-server by following best practices.

-⏳ utilize GitHub security tools #2839 

<br>
<br>

```
LEGEND

⏳ = to do
🚧 = in progress
✅ = done
```
_Note: this is part of an experiment to be more transparent about our priorities and our roadmap. See everything related to this effort in the [project board](https://github.com/cdr/code-server/projects/3)_

**Comment by vapurrmaid** [comment]
@jsjoeio can we mark remove pages/updates.css from :construction: -> :heavy_check_mark:

**Comment by jsjoeio** [comment]
We are moving away from the umbrella issue approach and instead only using the Project Board. Things that are not yet issues are cards. Once they are to be worked on, they will be converted to issues.

See items under "To do" in Roadmap: https://github.com/cdr/code-server/projects/4
