### ISSUE TITLE
uploading files or drag-and-drop to upload

### ISSUE THREAD

**Issue by eng-dibo** [cdr/code-server#2829]
the title is enough

**Comment by jsjoeio** [comment]
Hi @eng-dibo - this feature already exists in code-server. See demo:
![2021-03-08 10 11 41](https://user-images.githubusercontent.com/3806031/110355737-c8a6f780-7ff6-11eb-9649-e92ffdd634fd.gif)

If you have something else you're looking for out of the feature, please update your issue description with more information. If it's not working as expected, please open a bug issue with reproduction steps. 

Thanks!
