### ISSUE TITLE
create a code-server app optimized for android

### ISSUE THREAD

**Issue by Piposo** [cdr/code-server#2832]
many people who use this project are on their cell phones for the simple fact that if we had a pc we would be using vscode itself, there is an app called vheditor that uses this project, but it is not very optimized, we will not be able to create a version of this project for android ? we would love it if that were possible or create an app with the same functionality as vs code.

**Comment by phisanti** [comment]
If this project gets an app, then programming on a DEX/EMUI phone will reach a whole new level. Let's mix it with some google cloud or paperspace computing power and full programming capabilities in the phone becomes a reality.
