### ISSUE TITLE
upgrading to 3.9.1 shows wrong version in code-server help 

### ISSUE THREAD

**Issue by haiqiang-zhang** [cdr/code-server#2847]
- Web Browser: iPadOS 14.4
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:  3.9.1
- 
I have upgrade to 3.9.1, but:
In about, the version have maintained 3.9.0.

![IMG_0033](https://user-images.githubusercontent.com/68187985/110405638-d5415380-80bb-11eb-9e1a-6a5d44372d8d.png)

**Comment by balajib-b** [comment]
Could you please mention the remote OS details?
In case of linux you need to restart the code-server systemd service for the changes to take place.
`sudo systemctl restart code-server@$USER.service`

**Comment by jsjoeio** [comment]
Echoing @balajib-b - you may need to restart code-server.

I verified locally (macOS) that upgrading to 3.9.1 and running code-server produces the expected results.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3806031/110514694-cca14b00-80c4-11eb-8fbe-2b41734adc96.png">

**Comment by 5hay** [comment]
Can confirm, after the update (Docker installation) it shows

```
code-server: v3.9.1
VS Code: v1.53.2
```

**Comment by jsjoeio** [comment]
Thanks for chiming in @5hay. 

I'm going to close this issue as it seems like everything is working as expected. @haiqiang-zhang if you still need help, please let us know.
