### ISSUE TITLE
Updated to latest code-server (code-server: v3.9.1), but extensions are not recognized

### ISSUE THREAD

**Issue by blaylockbk** [cdr/code-server#2848]
- Web Browser: Edge
- Local OS: Windows
- Remote OS: Linux
- Remote Architecture:
- `code-server --version`:  3.9.1 e0203f2a36c9b7036fefa50eec6cf8fa36c5c015

I just updated to the latest code-server (via conda). When I opened my instance of code-server, none of the installed extensions are recognized.

![image](https://user-images.githubusercontent.com/6249613/110501524-1d0dae00-80af-11eb-8b75-37dd9c89809e.png)

yet, they still exist in my `~/.local/share/code-server/extensions` folder
![image](https://user-images.githubusercontent.com/6249613/110501935-8c839d80-80af-11eb-9550-805004b44e88.png)

Is there a setting or easy fix to let code-server recognize my extensions, or do I need to reinstall them?

**Comment by code-asher** [comment]
Could you post logs? Most likely there is some error preventing the
extensions from loading.

**Comment by blaylockbk** [comment]
I see what changed.

I have code-server in an anaconda virtual environment called `vscode`. After the last update, code-server looked for the extensions in that virtual environment at `anaconda3/envs/vscode/share/code-server/extensions` instead of `~/.local/share/code-server/extensions`

`~/.local/share/code-server/logs/20210309T160111/remoteagent.log`
```
[2021-03-09 16:01:18.995] [remoteagent] [error] /p/home/blaylock/anaconda3/envs/vscode/share/code-server/extensions {"errno":-2,"code":"ENOENT","syscall":"scandir","path":"/p/home/blaylock/anaconda3/envs/vscode/share/code-server/extensions"}
[2021-03-09 16:01:27.315] [remoteagent] [error] [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
[2021-03-09 16:01:27.315] [remoteagent] [error] [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
```

I did install the extensions again, and it installed them in my conda environment `~/anaconda3/envs/vscode/share/code-server/extensions` and all are working again. Maybe this was a user error. Should the extensions always install in the conda environment instead of the .local directory?

**Comment by code-asher** [comment]
Oh interesting! Does the conda environment set `XDG_DATA_HOME` or
`HOME`? We use those (in that order) to determine the default data
directory which includes the extensions.

The only other way to change the directory it uses is via command-line
flags or config options, but if this is just a straight upgrade that's
probably not what happened here.

**Comment by blaylockbk** [comment]
I haven't set the `XDG_DATA_HOME` value myself (didn't know that existed until now).

I created the anaconda environment with the following file `vscode.yaml`
```yaml
name: vscode
channels:
  - conda-forge
dependencies:
  - code-server >=3.7.2
  - pip
  - pip:
    - fortran-language-server
```
(doubt the fortran language server is important, but it is in my environment)

I created the environment months ago with this...
`conda env create -f vscode.yaml`

and then update environment with this (when I updated to v3.9.1)
`conda env update -f vscode.yaml`


Interestingly, my `settings.json` still resides at `~/.local/share/code-server/User/settings.json`

**Comment by code-asher** [comment]
Hmm I'm not really familiar with conda but assuming I'm looking at the right repository it looks like they set `--extensions-dir` recently: https://github.com/conda-forge/code-server-feedstock/commit/1a3f7eaf329f522056195364d7cbcb83778767f1#diff-d7075654874cb08007a21aaab3ecd4b3453a9087e7505d034d548b8938b599bc

**Comment by blaylockbk** [comment]
Looks like that's what happened. Good to know. 
Ok, so I reinstalled the extensions and should be good moving forward next time I update code-server.

**Comment by xhochy** [comment]
A bit background on the change: We did reroute the default extension dir in `conda` packages as conda environment should be self-contained and not write to anything in your system outside of `$CONDA_PREFIX`. Thus installing the extensions by default outside of the environment violated these constraints.
