### ISSUE TITLE
Remove  F10 shortcut for Focus Application Menu on code-server 

### ISSUE THREAD

**Issue by raul87011523** [cdr/code-server#2853]
Hello, I found a solution

-  Go to File/Preferences/Keyboard Shortcuts.
-  Click on 'Open Keyboard Shortcuts (JSON)' icon.
-  Paste the next code:

```
[
    {
        "key": "f10",
        "command": "-workbench.actions.menubar.focus",
        "when": "isWeb"
    },
    {
        "key": "f10",
        "command": "",
        "when": "isWeb"
    },
    {
        "key": "f10",
        "command": "extension.node-debug.startWithStopOnEntry",
        "when": "!inDebugMode && debugConfigurationType == 'node'"
    },
    {
        "key": "f10",
        "command": "workbench.action.debug.stepOver",
        "when": "debugState == 'stopped'"
    }

]
```

- Press F5 to refresh the browser

Example ilustrated:

![image](https://user-images.githubusercontent.com/29439123/110570504-41709580-8156-11eb-8f15-96857af756e4.png)

![image](https://user-images.githubusercontent.com/29439123/110571681-3585d300-8158-11eb-877b-b2ba951287fe.png)

![image](https://user-images.githubusercontent.com/29439123/110571310-aaa4d880-8157-11eb-8430-fab0a0dfce36.png)

_Originally posted by @raul87011523 in https://github.com/cdr/code-server/issues/2079#issuecomment-794800917_

**Comment by jsjoeio** [comment]
Awesome solution @raul87011523! I don't know if there would be any unintended consequences of adding this into code-server...but we'll take a look when we have time! Otherwise, feel free to submit a PR!

**Comment by raul87011523** [comment]
I'm glad I contributed, thank you!

**Comment by RolKau** [comment]
In case someone finds this issue, I just want to add that there is an alternative version, that adds F10 as Step Over when you are in debug mode, but keeps it as Focus Application Menu in the regular view: Add to your `~/.local/share/code-server/User/keybindings.json` these lines (wrapped in `[]` if nothing else was in that file):

    {
        "key": "f10",
        "command": "workbench.actions.menubar.focus",
        "when": "isWeb && !inDebugMode"
    },
    {
        "key": "f10",
        "command": "workbench.action.debug.stepOver",
        "when": "inDebugMode && debugState == 'stopped'"
    }

**Comment by danog** [comment]
Could this be the default please?

**Comment by jsjoeio** [comment]
You can modify your keybindings or you could submit an issue upstream

**Comment by danog** [comment]
Well AFAIK this is the default behavior in vscode, not sure why is it different in code-server; anyway will submit a patch when I have some free time :)

**Comment by jsjoeio** [comment]
@danog I would check Codespaces/VS Code Web! Could be different there. If not, could definitely be a bug in code-server!
