### ISSUE TITLE
CI: Helm error during lint run step

### ISSUE THREAD

**Issue by jawnsy** [cdr/code-server#2877]
The CI seems to try to run Helm but have an error, see [this run](https://github.com/cdr/code-server/runs/2099592924):

```
$ ./ci/dev/lint.sh
/usr/local/bin/helm
Error: unknown command "kubeval" for "helm"
Run 'helm --help' for usage.
Done in 121.27s.
```

Also, can we create a label for "CI" or "Build" issues?

**Comment by jsjoeio** [comment]
Looking at the current CI workflow, we now install `helm`: https://github.com/cdr/code-server/blob/main/.github/workflows/ci.yaml#L32-L33

I believe this was fixed in https://github.com/cdr/code-server/pull/2966

Closing as I believe it's no longer an issue! 🎉
