### ISSUE TITLE
Escape key exits fullscreen mode

### ISSUE THREAD

**Issue by jhasse** [cdr/code-server#2885]
- Web Browser: Chromium/Chrome
- Local OS: Linux or Windows
- Remote OS: Linux
- Remote Architecture: amd64
- `code-server --version`: `3.9.1 e0203f2a36c9b7036fefa50eec6cf8fa36c5c015`

Pressing Escape exits fullscreen mode, when instead I would expect it to close dialogs or code completion popups (as in fullscreen VSCode). Chrome has an API to lock the escape key, so that it switches to F11 for exiting fullscreen mode:
```js
navigator.keyboard.lock(["Escape"]);
```
Source: https://stackoverflow.com/a/65413565/647898
Calling this once in the developer console works, but I think it would be great if it could be done automatically by code-server.

**Comment by jsjoeio** [comment]
Thanks for opening this issue! I'm having trouble reproducing this locally. Does this all look right below? 

## Steps to Reproduce

1. Open code-server in the browser
2. Enter fullscreen mode
3. Open Application Menu > Help > About
4. Press Escape key

## Expected

Dialog is closed

## Actual

?

- [x] Works as expected on macOS + Chrome
- [x] Works as expected on macOS + Firefox 

## Screenshots

### macOS + Firefox
![2021-03-15 10 47 24](https://user-images.githubusercontent.com/3806031/111197862-32397f80-857c-11eb-90f2-f3fd233d1e8d.gif)

### macOS + Chrome
![2021-03-15 10 48 51](https://user-images.githubusercontent.com/3806031/111197851-2f3e8f00-857c-11eb-8b3b-5ffbc335d45b.gif)

**Comment by jhasse** [comment]
I've just updated from Chromium 88.0.4324 to 89.0.4389 and now it works. Weird. I'll reopen if it happens again and I can find out exactly why. Sorry for the noise.

**Comment by jsjoeio** [comment]
No worries at all! Glad it was resolved!
