### ISSUE TITLE
Unable to enable systemd service

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#2888]
Ubuntu 20.04 LTS. Code server v3.9.1
Trying sudo systemctl enable --now code-server@root and sudo systemctl enable --now code-server@USER
Having error
Failed to enable unit: Unit file code-server@root.service does not exist.

UPDATE

Please, fix docs. After this command user need to run "curl -fsSL https://code-server.dev/install.sh | sh" but command line instructions says that user need to run sudo systemctl enable --now code-server@USER

_Originally posted by @olegKusov in https://github.com/cdr/code-server/issues/1845#issuecomment-799232609_

**Comment by Lestt** [comment]
@code-asher The doc says:

```
curl -fOL https://github.com/cdr/code-server/releases/download/v3.9.1/code-server_3.9.1_amd64.deb
sudo dpkg -i code-server_3.9.1_amd64.deb
sudo systemctl enable --now code-server@$USER
# Now visit http://127.0.0.1:8080. Your password is in ~/.config/code-server/config.yaml

**Comment by code-asher** [comment]
From what I can tell based on their comment they used the install script (see the `curl -fsSL https://code-server.dev/install.sh | sh` command). 

I haven't actually tested any of this myself, I just opened a new issue for them since they posted in a closed issue.

**Comment by code-asher** [comment]
Actually I think I misread the comment. I think they're saying the install script needs to be ran before you can enable the service and that the docs don't mention this? But as far as I can tell they do.

@olegKusov I'm going to close this issue but if you have any insight on where the docs need to be updated please comment! Thank you!
