### ISSUE TITLE
Proposal: remove default assignees and approvers from Dependabot PRs

### ISSUE THREAD

**Issue by jawnsy** [cdr/code-server#2898]
@code-asher seems to have taken a shine to dependabot's PRs :heart:

I propose we remove `jawnsy` from the assignee/approver field in the Dependabot configuration, or set both to the `cdr/code-server-reviewers` team instead (I think the reviewer will be set to `cdr/code-server-reviewers` anyways due to the repository's code owner settings)

Opening this issue to discuss, will open a PR if there's consensus

**Comment by code-asher** [comment]
I'm in favor, reduces steps for me since I won't have to unassign you. :laughing:

**Comment by jsjoeio** [comment]
All those in favor: say "I"!

> (I think the reviewer will be set to cdr/code-server-reviewers anyways due to the repository's code owner settings

Yeah I think you're right here too.

SGTM!
