### ISSUE TITLE
How to preview a website?

### ISSUE THREAD

**Issue by yandan66** [cdr/code-server#291]
## Description
In Visual Studio Code, I can start a front-end project with webpack-dev-server that can preview and hot reload the site in developing environment. 

How can I get this?

**Comment by syntaxhacker** [comment]
**webpack.config.js**

![image](https://user-images.githubusercontent.com/30970495/54608196-32c6da80-4a76-11e9-9cbc-7d0dc650a319.png)
You could view the **port** that in your webpack config file and default url is localhost .
it looks like this after starting your app `http://localhost:9000` where **9000** is your port . If you deployed this on your cloud computing server the port binds to the dev server configuration.

**Comment by hnprashanth** [comment]
What if we are using Coder.com's instance? I'm assuming there will be many containers running inside one server instance which would make it impossible to access a dev server externally.

**Comment by nol166** [comment]
We will be adding back a feature called cdr that will generate a URL for you and show it in the sidebar. In the meantime we can also get you the URL if you shoot us an email at support@coder.com with your coder username

**Comment by code-asher** [comment]
Closing since ide.coder.com was shut down and the self-hosted version has this feature being tracked here: https://github.com/cdr/code-server/issues/512.
