### ISSUE TITLE
Cannot 'Open Folder...' on code-server Welcome Page

### ISSUE THREAD

**Issue by JammSpread** [cdr/code-server#2921]
## OS/Web Information

- Web Browser: Chrome
- Local OS: Chrome OS
- Remote OS: Debian GNU/Linux
- Remote Architecture: amd64
- `code-server --version`: 3.9.1 + 3.9.2

## Steps to Reproduce

1. Load up a fresh setup of `code-server` without specifying a folder or with `--ignore-last-opened` on Linux.
(You could also use the `Help: Welcome` command.)
2. Click `Open Folder` under the `Start` Section.

## Expected

It uses the open folder command specific to your remote OS and you can select a folder.

## Actual

Witness nothing happens as after you click the link as the command it references may not even exist on your version of VSCode.

## Screenshot

![Open Folder](https://user-images.githubusercontent.com/61063879/111537491-e3d5dd80-8741-11eb-8694-4f32d191cfaa.png)

## Notes

Has occurred on multiple Linux machines, this is my third remote machine I'm using to report it.

This issue can be reproduced in VS Code: ***Unknown***

Seems to originate from this [line](https://github.com/cdr/code-server/blob/6892b0be9753fbc2d7da2b1fe462c613388f7e44/lib/vscode/src/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page.ts#L23). This might occur due to the 'mac-only' class version being used wrongly.

**Comment by jsjoeio** [comment]
Thanks for opening this issue and adding all the details @JammSpread ! Yeah that's weird they have the `mac-only` class there. I'm guessing you're right. We'll look into this!

**Comment by oxy** [comment]
Tested on Fedora 34 with the official code-server rpm right now, using either `--ignore-last-opened` or `Help: Welcome` and then clicking `Open Folder` worked on my environment, on both Chromium and Firefox.

Could this be Chrome OS specific?

**Comment by oxy** [comment]
@JammSpread could you view the page with inspect element and find out which `li` element is displayed - the macOS one or the Linux/Windows one (or is something else being displayed)?

**Comment by JammSpread** [comment]
Sure, I'll try that soon.

**Comment by JammSpread** [comment]
I'm very sorry for the late reply.
After trying and inspecting on the local OS (Chrome OS) and Chrome/Firefox on Debian, I've come to a  similar conclusion.
> [Could this be Chrome OS specific?](https://github.com/cdr/code-server/issues/2921#issuecomment-801723895)

The assumption seems to be correct. 
It seems that Chrome OS is falsely detected as macOS and thus uses its platform-specific command.
This doesn't occur, in contrast, on standard Linux environments.

**Comment by JammSpread** [comment]
This might be just a speculation but shouldn't it use the remote OS' command and not the detected local OS'?

**Comment by jsjoeio** [comment]
Do we know if this is an upstream issue or specific to code-server?

Can it be reproduced on Codespaces?

**Comment by JammSpread** [comment]
I haven't been able to access the Codespaces Beta however this is reproducible in Gitpod.
It seems it may be upstream and an issue with handling Chrome OS.

**Comment by jsjoeio** [comment]
Ah gotcha. Well that's a good sign then!

Shoot, I wish I had access to Chrome OS. Or if there were a way for me to lend you access to my Codespaces Beta. Then I could try and reproduce and we could file upstream.

**Comment by JammSpread** [comment]
You might be able to reproduce it by using a similar or the same user agent I have.
```
Mozilla/5.0 (X11; CrOS x86_64 13729.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.95 Safari/537.36
```
You might be able to make use of this through a browser extension or by manually modifying your HTTP(S) requests.
