### ISSUE TITLE
Requesting extension "ngrok for VSCode"

### ISSUE THREAD

**Issue by caiych** [cdr/code-server#2936]
- [x] Extension name: ngrok for VSCode
- [x] Extension GitHub or homepage: https://github.com/philnash/ngrok-for-vscode

IMO this is even more useful in code-server than VSCode, since code-server can't do port forwarding like VSCode remote development.

**Comment by oxy** [comment]
Thanks for opening an extension request!
We are currently in the process of switching extension marketplaces and transitioning over to [Open VSX](https://open-vsx.org/).
Once https://github.com/eclipse/openvsx/issues/249 is implemented, we can fully make this transition. Therefore, we are no longer accepting new requests for extension requests. 

We suggest installing the VSIX file and then installing into code-server as a temporary workaround. See [docs](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#installing-vsix-extensions-via-the-command-line) for more info.
