### ISSUE TITLE
Add changelog.md

### ISSUE THREAD

**Issue by mapl** [cdr/code-server#294]
Please add a changelog.md to communicate changes

**Comment by nol166** [comment]
it would be cool to do something like this: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/CHANGELOG.md

**Comment by zk-g** [comment]
liKe ThIs
https://www.epicgames.com/fortnite/en-US/news/category/patch%20notes

**Comment by nhooyr** [comment]
We will definitely do this for future releases.

**Comment by AckerApple** [comment]
Looking for that changelog. Found this issue instead, was going to create an issue.

I was on 3.5.0 and now on 3.8.0 and want to learn whats updated

**Comment by code-asher** [comment]
For the time being we put all the changes in the GitHub releases which
can be viewed here: https://github.com/cdr/code-server/releases
