### ISSUE TITLE
Extension Sidebar and Menubar not displayed

### ISSUE THREAD

**Issue by 8thHalfHour** [cdr/code-server#2943]
## OS/Web Information

- Web Browser: Chrome 87.0.4280.77 (Official Build) stable (64-bit), Safari iPadOS v14.3, and Brave v1.24 (21.3.17.17)
- Local OS: iPadOS v14.3
- Remote OS: Linux Mint 20.1
- Remote Architecture: Intel NUC
- `code-server --version`: 3.91

## Steps to Reproduce

1. Load code-server from the cloud URL in any browser on the iPad (the ones I’ve tried are above) -OR- by launching the PWA.
2. Extension sidebar is not shown, nor can menubar be toggled on.
3. 

## Expected

The extension sidebar should be visible at all times, and the menubar should become visible when I toggle it. (I could not find a way to toggle the extension bar)

## Actual

Neither loads.

## Notes

This issue can be reproduced in VS Code: No

**Comment by 8thHalfHour** [comment]
@jsjoeio, I forgot to ask if you need screenshots?

**Comment by jsjoeio** [comment]
If you don't mind, that would be helpful! Even a screenrecording (since that's built-in on iPad now)

**Comment by 8thHalfHour** [comment]
Okay, so I think I may have figured out where the problem is occurring. Here is an image taken in the browser when code-server is run with `code-server --link`:

![IMG_0094_sm](https://user-images.githubusercontent.com/44852729/112772744-69317b80-8fe7-11eb-85e1-5665cbafebd1.jpg)

However, when run with the `--user-data-dir` switch, the sidebar disappears:

![IMG_0095_sm](https://user-images.githubusercontent.com/44852729/112772826-cd543f80-8fe7-11eb-8199-1f37c4c75638.jpg)

To be specific, the exact command I call is `code-server --link --user-data-dir ~/.vscode-insiders`.

Hopefully this helps troubleshoot a bit.

**Comment by jsjoeio** [comment]
Now that's really strange...Okay yes, this is super helpful. Thank you!

**Comment by 8thHalfHour** [comment]
I noticed the activity bar is working now, and I just wanted to say thanks! 👍

**Comment by jsjoeio** [comment]
Hooray! Glad to hear that. I'm going to assume we can close this then. If that's a mistake, let me know and I'll reopen.
