### ISSUE TITLE
R Tools Extension for Code-Server

### ISSUE THREAD

**Issue by phisanti** [cdr/code-server#2957]
I would like to know if it is possible to add R Tools to the marketplace. I see that there are already many of the tools, so I am only missing the possibility to plot graphics within the VScode as it happens in the VS code. Normally, VS code prompts a new window, but I assume this is not possible when working on Code-server. Thus, I was wondering if someone could help to port this app or maybe create a tutorial on how to do R plots (base graphics, ggplot or plotly) with code-server.

Kind regards, 

- [ ] Extension name: R Tools
- [ ] Extension GitHub or homepage: https://github.com/MikhailArkhipov/vscode-r

**Comment by oxy** [comment]
Thanks for opening an extension request!
We are currently in the process of switching extension marketplaces and transitioning over to [Open VSX](https://open-vsx.org/).
Once https://github.com/eclipse/openvsx/issues/249 is implemented, we can fully make this transition. Therefore, we are no longer accepting new requests for extension requests. 

We suggest installing the VSIX file and then installing into code-server as a temporary workaround. See [docs](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#installing-vsix-extensions-via-the-command-line) for more info.

I'm not certain about the open-a-new-window workflow; I'd recommend installing it via the `.vsix` and opening another issue if you experience difficulties.
