### ISSUE TITLE
[dev]: run macos-amd64 job on release PRs

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#2970]
Due to the weirdness of our release process, we overlooked the changes to our CI workflow when we merged #2866. 

We turned off CI for `macos-amd64` and only run it on the default branch. 

Unfortunately the release process relies on the artifacts created during a release PR (example: #2953) when uploading release assets. This is a limitation in our workflow that we need to address.

Current workaround: build `macos-amd64` locally and manually upload to release assets. 

## Notes

Ideally, we look into a better process for the release assets. The current solution isn't great. 

Release off a tagged commit instead.

**Comment by code-asher** [comment]
Yeah I think maybe instead of releasing off a PR we could release off a commit in main.

**Comment by jsjoeio** [comment]
Good call! That would save a lot of trouble.

**Comment by oxy** [comment]
We actually resolved this in the major nuke-CI-and-rewrite it; I just forgot to close the issue :sweat_smile:
