### ISSUE TITLE
Yarn package version not updated

### ISSUE THREAD

**Issue by aptalca** [cdr/code-server#2972]
Hi,

I noticed the yarn package version is still 3.9.1
Is it forgotten or was there an issue with the update?
In the past the update on there was more or less in sync with the GitHub releases.

Thanks

**Comment by jsjoeio** [comment]
Thanks for being so quick to notice @aptalca! Yes, when we released `3.9.2` something broke in our `publish` workflow: https://github.com/cdr/code-server/actions/runs/688144994

Once https://github.com/cdr/code-server/pull/2968 passes and we merge it, I'm going to trigger a manual publish, which should publish the new version to `npm`, etc.

**Comment by aptalca** [comment]
I wish I could take credit 😅 Our ci notified me: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-code-server/detail/master/218/pipeline

It is triggered by GitHub releases but uses yarn to install. Perhaps we should change it so it's triggered by yarn registry instead.

**Comment by jsjoeio** [comment]
Woah! Super cool that y'all have that set up. 

> Perhaps we should change it so it's triggered by yarn registry instead

Yeah that could be safer. Though we are working on improving our CI flow! This release today has showed the process is more fragile than it should be 😅

**Comment by jsjoeio** [comment]
Heads-up: we're still running into issues with our publish workflow and scripts. We will continue looking into this first thing tomorrow.

**Comment by PatrickDerichs** [comment]
Oh, this is interesting! I noticed that it affects your install script as well, but I am not sure if it is related. We build an image with code-server with a reverse proxy and I noticed it kept building with version 3.9.1. I was able to work around it by passing `--version 3.9.2` to forcefully install the new version.

**Comment by jsjoeio** [comment]
Interesting! Thanks for the report @PatrickDerichs - we'll have to confirm once we get this fixed if that's a bug as well.

**Comment by aptalca** [comment]
> Heads-up: we're still running into issues with our publish workflow and scripts. We will continue looking into this first thing tomorrow.

Thanks for the heads up. We changed the trigger to check the yarn registry instead so we don't have hourly failing builds anymore. Once you fix your pipeline and push to yarn, our ci should pick it up.

Thanks

**Comment by jsjoeio** [comment]
The issue has been resolved and `3.9.2` is now available on the npm registry.
<img width="452" alt="image" src="https://user-images.githubusercontent.com/3806031/112678848-aef41580-8e28-11eb-8bdf-55ca536e114b.png">

We've also written a regression report which you can read here: https://github.com/cdr/code-server/discussions/2983
