### ISSUE TITLE
New version 3.9.2 not pushed to docker registry codercom

### ISSUE THREAD

**Issue by nodesocket** [cdr/code-server#2973]
> Warning  Failed                  4s (x2 over 17s)  kubelet                  Failed to pull image "codercom/code-server:3.9.2": rpc error: code = Unknown desc = Error response from daemon: manifest for codercom/code-server:3.9.2 not found: manifest unknown: manifest unknown

**Comment by jsjoeio** [comment]
Thanks for reporting! We're aware and working on it. Issue with the publish workflow. 

See: https://github.com/cdr/code-server/issues/2972#issuecomment-807738553

**Comment by jsjoeio** [comment]
Heads-up: we're still running into issues with our publish workflow and scripts. We will continue looking into this first thing tomorrow.

**Comment by nodesocket** [comment]
Ok. Thanks 👍🏻

**Comment by jsjoeio** [comment]
The issue has been resolved and `3.9.2` is now available on the Docker registry.

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/3806031/112678985-df3bb400-8e28-11eb-941a-bf999732b701.png">


We've also written a regression report which you can read here: https://github.com/cdr/code-server/discussions/2983

**Comment by nodesocket** [comment]
@jsjoeio I am now seeing my running `3.9.2` broken after I login. After I login, I see websocket connections failing.

**Comment by jsjoeio** [comment]
@nodesocket hmm...wonder if it's related to this: https://github.com/cdr/code-server/issues/2975

can you please open a new issue (bug report)?
