### ISSUE TITLE
Log out button should not appear if not using password

### ISSUE THREAD

**Issue by alvarolb** [cdr/code-server#2985]
## OS/Web Information

- Web Browser: Chrome
- Local OS: Linux Ubuntu
- Remote OS: Linux Ubuntu
- Remote Architecture: x64
- `code-server --version`: 3.9.2

## Steps to Reproduce

1. Run code-server without password
2. Click on Menu button
3. Log out button is there but has no sense as not using password

## Expected

Log out button should not appear, as the installation is not using a password

## Actual

The log out button appears even if not using a password. In my case I am using code-server inside a reverse proxy that already handles authentication, so, the log out button has no sense in such use cases

## Screenshot

![image](https://user-images.githubusercontent.com/1141353/112717222-78330380-8eeb-11eb-880e-16b5dcc53fd4.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Good call! We didn't consider that when adding the Log out feature. Thanks for bringing this to our attention! Added to an upcoming milestone.
