### ISSUE TITLE
No debugging breakpoints have been set anywhere.

### ISSUE THREAD

**Issue by hmy831004** [cdr/code-server#3021]
## OS/Web Information

- Web Browser: chrome
- Local OS: window10
- Remote OS: Ubuntu 16.04.1 LTS
- Remote Architecture:
- `code-server --version`:  2.1665-vsc1.39.2 ,3d5db8313a91f80dfc402450fd117b4e63f7711e ,x64

## Expected

No debugging breakpoints have been set anywhere.

![K-030](https://user-images.githubusercontent.com/41275943/113406423-6d460a80-93e6-11eb-91b8-08d242cf80eb.png)
![K-031](https://user-images.githubusercontent.com/41275943/113406428-6e773780-93e6-11eb-916c-769f5cd982f6.png)

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by oxy** [comment]
Can you verify if this is reproducible in the latest version of `code-server`?
