### ISSUE TITLE
Something wrong in renaming a file when specific color theme is selected

### ISSUE THREAD

**Issue by CT702-7** [cdr/code-server#3023]
## OS/Web Information

- Web Browser:Firefox
- Local OS:Linux Ubuntu
- Remote OS:Windows
- Remote Architecture:arm64
- `code-server --version`:3.9.2

## Steps to Reproduce

1. Select "Monokai" as color theme
2. Rename a file

## Expected

I can see the old name while renaming it.

## Actual

The total area is blocked.

## Screenshot

![屏幕截图 2021-04-02 224739](https://user-images.githubusercontent.com/75598070/113426082-84e0bb80-9405-11eb-8fe9-01887a903f65.jpg)

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Thanks for bringing this issue to our attention @CT702-7 - I was able to reproduce this locally with `3.9.2`.

## code-server

https://user-images.githubusercontent.com/3806031/113433892-dc930e80-9394-11eb-8fa7-559f76b4ca1d.mov

## VS Code

Could not reproduce in VS Code (local). Did not try Codespaces.

https://user-images.githubusercontent.com/3806031/113433773-a8b7e900-9394-11eb-846e-0b4c52e6e8cf.mov

**Comment by CT702-7** [comment]
@jsjoeio Excuse me , bro. I'm actually a fresh man here. So I don't understand the meaning of "open an issue upstream", could you please elaborate it, what should I do next?

**Comment by jsjoeio** [comment]
@CT702-7 apologies - happy to guide you!

code-server uses [VS Code](https://github.com/microsoft/vscode) under the hood. Sometimes issues are in code-server. Sometimes  they're upstream (meaning in VS Code). 

Here, I mean you should instead file an issue in the VS Code repository. Here is a [link](https://github.com/microsoft/vscode/issues/new/choose). Hope that helps.
