### ISSUE TITLE
always appearing error number 500 

### ISSUE THREAD

**Issue by Shiko21** [cdr/code-server#3029]
after i install code-server i run it it works perfectly fine but after a few hours its disconnects and if i run my vscode again it crash and opening on teermux it says error time out

**Comment by leKamikaze1** [comment]
Same here, termux in android with 500

**Comment by leKamikaze1** [comment]
My trace is the following:

code-server --log trace [2021-04-05T00:25:53.435Z] trace child:16721 got message {"message":{"type":"handshake","args":{"_":[],"bind-addr":"127.0.0.1:8080","auth":"password","password":"wontshowmypwdlol","config":"/data/data/com.termux/files/home/.config/code-server/config.yaml","log":"trace","user-data-dir":"/data/data/com.termux/files/home/.local/share/code-server","extensions-dir":"/data/data/com.termux/files/home/.local/share/code-server/extensions","verbose":true,"host":"127.0.0.1","port":8080,"proxy-domain":[],"usingEnvPassword":false,"usingEnvHashedPassword":false}}} [2021-04-05T00:25:53.453Z] info code-server 3.9.2 109d2ce [2021-04-05T00:25:53.454Z] info Using user-data-dir ~/.local/share/code-server [2021-04-05T00:25:53.455Z] trace Using extensions-dir ~/.local/share/code-server/extensions [2021-04-05T00:25:53.557Z] info Using config file ~/.config/code-server/config.yaml [2021-04-05T00:25:53.558Z] info HTTP server listening on http://127.0.0.1:8080 [2021-04-05T00:25:53.558Z] info - Authentication is enabled [2021-04-05T00:25:53.558Z] info - Using password from ~/.config/code-server/config.yaml [2021-04-05T00:25:53.559Z] info - Not serving HTTPS [2021-04-05T00:26:10.654Z] trace heartbeat [2021-04-05T00:26:10.741Z] debug forking vs code... [2021-04-05T00:26:13.381Z] error VS Code exited unexpectedly with code 0 [2021-04-05T00:26:16.420Z] debug forking vs code... [2021-04-05T00:26:18.833Z] error VS Code exited unexpectedly with code 0

Ideas?

**Comment by jsjoeio** [comment]
@Shiko21 Please open an bug report issue, fill out the template and we'll be happy to take a look!
