### ISSUE TITLE
500 error: 3.9.2 not working on Android + Termux

### ISSUE THREAD

**Issue by leKamikaze1** [cdr/code-server#3036]
## OS/Web Information

- Web Browser: Chrome for Android
- Local OS: Android 9 Pie
- Remote OS: Server? If so, Android 9 Pie on Termux
- Remote Architecture: ARM
- `code-server --version`: 3.9.2 109d2ce3247869eaeab67aa7e5423503ec9eb859

## Steps to Reproduce

1. Install code-server as normal with yarn
2. Start it
3. Log in to localhost:8080

## Expected

VSCode would appear

## Actual

500 error is displayed on the screen, alongside with the "go home" button which gives the exact same error

## Screenshot

https://user-images.githubusercontent.com/77033690/113613110-18dd9d80-9627-11eb-8ed3-778ab7d682ac.mp4

EDIT: Link above is broken, here is a video showing everything: https://youtu.be/w2MCCDTNfsU

## Notes

This issue can be reproduced in VS Code: No

**Comment by leKamikaze1** [comment]
Wait, wtf? The video didn't upload, lemme try to upload it again

**Comment by leKamikaze1** [comment]
@jsjoeio Sorry for the video delay, I didn't see that it didn't record chrome, then I had to install edge, make a new recording, and also compress it due to GitHub limitations, now it's available

**Comment by jsjoeio** [comment]
No worries at all! Thanks for opening this up so quickly. I should be able to investigate today. 

P.S. the video isn't working on my side. I just see a black screen
<img width="390" alt="image" src="https://user-images.githubusercontent.com/3806031/113613382-02731a00-9606-11eb-8ad7-07ae988797c5.png">

**Comment by leKamikaze1** [comment]
> No worries at all! Thanks for opening this up so quickly. I should be able to investigate today.
> 
> P.S. the video isn't working on my side. I just see a black screen
> <img alt="image" width="390" src="https://user-images.githubusercontent.com/3806031/113613382-02731a00-9606-11eb-8ad7-07ae988797c5.png">

~~I'm gonna break something~~Let me try and upload it to YouTube!

**Comment by leKamikaze1** [comment]
https://youtu.be/w2MCCDTNfsU Okay, quality may not be the best because of YouTube, it should be at full res soon

**Comment by jsjoeio** [comment]
That worked! Hmm...so strange. Okay, let me try to reproduce locally on my Android.

**Comment by jsjoeio** [comment]
Well, I have good news and bad news.

## Good News

I was able to successfully reproduce this on my Pixel 2 in both Chrome and Firefox.
https://user-images.githubusercontent.com/3806031/113616529-115bcb80-960a-11eb-88b8-864f251f520d.mp4

## Bad News

Even running with `--log debug` leads to no hints as to what's wrong.

I'll add this to the next milestone so can investigate further. Thanks for helping us find this.

**Comment by leKamikaze1** [comment]
Damn, so it wasn't some weird thing I did. Well, in that case, shouldn't a temporal warning be made on the repo telling that 3.9.2 isn't working in these devices?

**Comment by jsjoeio** [comment]
Yes, good idea! I will pin this issue so people see it and I'll make an announcement in Discussions.

**Comment by leKamikaze1** [comment]
> Yes, good idea! I will pin this issue so people see it and I'll make an announcement in Discussions.

Oki, hmu with any updates on the issue

**Comment by jsjoeio** [comment]
Update:

Starting working on this today. This is terribly difficult to debug. I tried cloning and running code-server on my Android in Termux but couldn't get it working due to issues with native modules needed by vscode. I'll update this thread as I continue to investigate.

**Comment by jsjoeio** [comment]
@leKamikaze1 can you try upgrading to 3.9.3 and seeing if that fixes it? 

I just tried on my Pixel 2 and it's semi-working. The backspace is being funky 🤔


https://user-images.githubusercontent.com/3806031/114103165-79feae80-987d-11eb-81e0-510941d366da.mp4

**Comment by leKamikaze1** [comment]
Sure, wait a sec
PD: About the backspace thing, I noticed the same issue occurred in 3.9.1 in my samsung galaxy tab, it's not something specifically wrong with 3.9.3

**Comment by jsjoeio** [comment]
> About the backspace thing, I noticed the same issue occurred in 3.9.1 in my samsung galaxy tab, it's not something specifically wrong with 3.9.3

Interesting. I wonder if it's something we changed or upstream. I can try to reproduce with Codespaces to check.

**Comment by jsjoeio** [comment]
The backspace works in Codespaces, but it looks like the cursor jumps one. Probably separate issue. 


https://user-images.githubusercontent.com/3806031/114104868-86383b00-9880-11eb-9e3a-9e5115037f6a.mp4

**Comment by jsjoeio** [comment]
Actually, I found out what it is. It's an upstream issue here:

- upstream: [Issues with Backspace in Codespaces on Android (Surface Duo)](https://github.com/microsoft/vscode/issues/107602)
- underlying issue: [Support mobile platforms](https://github.com/xtermjs/xterm.js/issues/1101)

**Comment by leKamikaze1** [comment]
Alright, so I shouldn't make a new issue? Also, code-server 3.9.3 is building, when its done, ill test if everything works

**Comment by jsjoeio** [comment]
No, because it's upstream. What we can do is document the issue in the Termux docs though. I'll create a separate issue for that.

**Comment by leKamikaze1** [comment]
Alright, v3.9.3 is working now, and there's something strange with backspace, it sometimes works and sometimes it doesn't, lemme try to record it

**Comment by leKamikaze1** [comment]
Now backspacing when able CRASHES code-server?! https://youtu.be/WOGQubsOjoo

**Comment by leKamikaze1** [comment]
Well, the backspacing thing is now a completely different thing, now code-server is working and the 500 error isn't present anymore. I'm gonna close this and make a different issue regarding the crash. Thanks for the help @jsjoeio !
