### ISSUE TITLE
Regression: New RegExp format causes blank page

### ISSUE THREAD

**Issue by L3P3** [cdr/code-server#3051]
## OS/Web Information

- Web Browser: Mypal 29.1.1 (Pale Moon/Firefox)
- Local OS: Windows XP SP3
- Remote OS: Debian 10
- Remote Architecture: x86-64
- `code-server --version`: 3.9.2 109d2ce3247869eaeab67aa7e5423503ec9eb859

## Steps to Reproduce

1. Open Mypal
2. Open code-server

## Expected

App opens.

## Actual

Blank page.

## Screenshot

![mpcsb2](https://user-images.githubusercontent.com/4629449/113763605-616d8780-9709-11eb-98b8-b28dc17e0a4b.PNG)

## Notes

Is most probably caused by following lines including quite recent RegExp syntax:

https://github.com/cdr/code-server/blob/f21433a130ab07db569a1ae43a04416e7ec306ba/lib/vscode/src/vs/editor/contrib/linesOperations/linesOperations.ts#L1060

Please either revert these lines (v3.9.0 it worked well) or make them more backwards-compatible (maybe feature check and fallback). Maybe, we can also consider this a bug in closure compiler as it should generate backwards-compatible code out of the box.

**Comment by jsjoeio** [comment]
Hi @L3P3! Thanks for opening the issue. 

> This issue can be reproduced in VS Code: Yes/No

It looks like part of the bug report is missing this line. Can this be reproduced in VS Code? 

Based on what you linked, if that's truly the issue, then it looks like it was introduced/changed here: https://github.com/microsoft/vscode/commit/5c1ff8158b7731a8478cfe0e09a23e59502efb9f#diff-dde3b56145713053f086e5ce1fcea39c4cb171d4555b6ab91256c7cf2b39e9af

We suggest raising this upstream.

> Maybe, we can also consider this a bug in closure compiler as it should generate backwards-compatible code out of the box.

If that's the case, it may be worth raising this there.

**Comment by L3P3** [comment]
Thanks for pointing that out. Did not know that vscode aims for backwards-compatiblity and I thought it is just used in modern electron.
Workaround for now is to simply delete SnakeCaseAction, I will now look into the compiler side of things.

**Comment by L3P3** [comment]
Just for the record, if anyone else has this problem, run this command as root:
```
sed -i 's#return q\.replace(/(\\p{Ll})(\\p{Lu})/gmu,\"\$1_\$2\")\.replace(/(\[^\\b_\])(\\p{Lu})(\\p{Ll})/gmu,\"\$1_\$2\$3\")\.toLocaleLowerCase()#return eval('\''q\.replace(/(\\p{Ll})(\\p{Lu})/gmu,\"\$1_\$2\")\.replace(/(\[^\\b_\])(\\p{Lu})(\\p{Ll})/gmu,\"\$1_\$2\$3\")\.toLocaleLowerCase()'\'')#g' /usr/lib/code-server/lib/vscode/out/vs/workbench/workbench.web.api.js
```
With this, automatic snake case transformation is still not working but at least, everything else does.
