### ISSUE TITLE
just preview local file system code and without backend

### ISSUE THREAD

**Issue by jianboy** [cdr/code-server#3057]
## suggestion

new a branch, it can preview current machine current workspace code, and  **without backend** code-server. it only read local file.

**Comment by jianboy** [comment]
similar project: https://github.com/conwnet/github1s

but that project can only open github repo files.

**Comment by oxy** [comment]
I don't think this is possible without a backend - mostly because VSCode relies on natively running language servers for Intellisense/auto-complete, and because local storage access is pretty limited in a web browser.

**Comment by jsjoeio** [comment]
Yeah, I think @oxy is right. Probably not possible. Though someone internally was exploring a project similar to github1s.

https://coder1s.com/cdr/code-server

But it only works with GitHub repos.

> but that project can only open github repo files.

What kind of projects would you like to open? GitLab? Something else?

**Comment by jianboy** [comment]
@oxy @jpinnix 

ok, First of all, I can tell you that many js lib can preview current system files without the backend(php, nodejs, java and so)

Let me give you some examples. 

1. https://github.com/surfcodes/surf

this project can open github, gitlab, and any others file system.

2. baidu minder project

It is a javascript project, and without backend. it need a static server, like nginx, apache.

3. If it need nodejs backend, that's ok. I want it can package to a Electron app, and it also can start a nodejs server, which we can access it at LAN.

We can code using our windows pc, besides if we share a link(http://192.168.0.111:8898) to you friends, our friends can also preview our code(not microsoft remote develop).

**Comment by jpinnix** [comment]
> @oxy @jpinnix 
> 
> 
> 

I assume you meant to tag @jsjoeio 

But this is an interesting conversation 😃
