### ISSUE TITLE
Git Tab not automatically refreshing.

### ISSUE THREAD

**Issue by ToasterSticks** [cdr/code-server#3073]
## OS/Web Information

- Web Browser: Chrome. 
- Local OS: MacOS 11.3 Beta (20E5224a)
- Remote OS: Railway?
- Remote Architecture: Railway? (no clue)
- `code-server --version`: 3.9.2

## Steps to Reproduce

1. Clone a repo
2. Save a file
3. Head to git tab

https://user-images.githubusercontent.com/64027609/114019870-edcc9700-983c-11eb-8890-c43bc8b50b76.mov

## Expected
Source control should update automatically

## Actual

Nothing, you need to manually refresh

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Thanks for the detailed bug report and the video @ToastOnAStik - we'll investigate this.

**Comment by JammSpread** [comment]
Can confirm this on Railway as well. Though it might be related to Railway exclusively as I never experienced this elsewhere.

**Comment by jsjoeio** [comment]
Thanks for confirming @JammSpread - Ah okay. Good to know. Yeah could be related to Railway then. cc @bpmct

**Comment by ToastOnAStik** [comment]
Fixed in the latest release (9.3.2)

**Comment by ToastOnAStik** [comment]
Opening this issue again as the problem comes and goes

**Comment by bpmct** [comment]
@ToastOnAStik do you have any logs from within VS Code output itself or the browser that would allow us to troubleshoot this?

**Comment by bpmct** [comment]
FWIW I am noticing this sometimes within VS Code itself

**Comment by ToastOnAStik** [comment]
> @ToastOnAStik do you have any logs from within VS Code output itself or the browser that would allow us to troubleshoot this?

Where would I be able to find this?

**Comment by ToastOnAStik** [comment]
Also adding `"git.autorefresh": true` to `settings.json` does not fix the problem. Lmk how it goes for you

**Comment by ToastOnAStik** [comment]
This may have to do with the number of file watchers or something, as nodemon fails with the error `Error: System limit for number of file watchers reached`

**Comment by jsjoeio** [comment]
> Where would I be able to find this?

You can run `code-server --log debug`  and see the logs printed in your terminal. For the browser, open the console and you may see some there too.

**Comment by JammSpread** [comment]
> This may have to do with the number of file watchers or something, as nodemon fails with the error `Error: System limit for number of file watchers reached`

Oh of course, that must be the reason. Though that seems out of our hands as you can't modify the system value Railway set for the max amount of file watchers.

**Comment by ToastOnAStik** [comment]
Yeah as certain times of the day it works

**Comment by JammSpread** [comment]
Yup, at those time you there might be less active watchers.
