### ISSUE TITLE
Document Android backspace issue 

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#3079]
We need to indicate in the Termux docs there are known issues with the backspace key on Android (using on-screen keyboard).

See [comment](https://github.com/cdr/code-server/issues/3036#issuecomment-816278737)

Possibly:
- [ ] add new `docs/termux.md` file and add there.

**Comment by leKamikaze1** [comment]
Backspace works if you start backspacing "in the middle" of the word you wanna delete, but it crashes code-server(? Proof here: https://youtu.be/WOGQubsOjoo

**Comment by jsjoeio** [comment]
Argh, well at least we know there is a workaround.

@leKamikaze1 do you know if the issue occurs with a separate bluetooth keyboard? I can try testing too. Wondering if this is specific to the on-screen keyboard.

**Comment by leKamikaze1** [comment]
> Argh, well at least we know there is a workaround.
> 
> @leKamikaze1 do you know if the issue occurs with a separate bluetooth keyboard? I can try testing too. Wondering if this is specific to the on-screen keyboard.

Sadly, I never had a Bluetooth keyboard In my life, so its pretty impossible for me to test that

**Comment by jsjoeio** [comment]
No worries at all. I have one lying around somewhere so I can test!

**Comment by leKamikaze1** [comment]
@jsjoeio Found something?

**Comment by jsjoeio** [comment]
I finally got around to testing - it works with a bluetooth keyboard! No backspace issues 😄 

## Demo

https://user-images.githubusercontent.com/3806031/114918195-ab2a3200-9ddb-11eb-8c1a-90d466e434c3.mp4

**Comment by leKamikaze1** [comment]
Well, that's great. So, the issue is on Android's on-screen keyboard? Not sure what would cause it 🤔

**Comment by jsjoeio** [comment]
It has to do with the way xterm.js is handling the input for on-screen keyboards I'm guessing:

_Pulled from [comment](https://github.com/cdr/code-server/issues/3036#issuecomment-816278737)_
- upstream: [Issues with Backspace in Codespaces on Android (Surface Duo)](https://github.com/microsoft/vscode/issues/107602)
- underlying issue: [Support mobile platforms](https://github.com/xtermjs/xterm.js/issues/1101)

**Comment by fax1ty** [comment]
Any news? Working solution?

**Comment by jsjoeio** [comment]
Unfortunately, no :/ this is upstream and out of our control to fix. Only working solution I know of is to use an external keyboard.

**Comment by nikey02** [comment]
[https://github.com/microsoft/vscode/commit/20f3ece2e09f86f6a81858cb6e627e1a7afd4422#diff-720a2dcc75d4242d03024e70d87943ebc58dcdbb8baf1d1ab8b78792248b621a](https://github.com/microsoft/vscode/commit/20f3ece2e09f86f6a81858cb6e627e1a7afd4422#diff-720a2dcc75d4242d03024e70d87943ebc58dcdbb8baf1d1ab8b78792248b621a)

**Comment by jsjoeio** [comment]
Thanks for linking that @nikey02 ! Looks like that was part of vscode 1.55.2, which we upgraded to in https://github.com/cdr/code-server/pull/3085 which means...hopefully this isn't an issue in our next release 🤞

**Comment by nikey02** [comment]
@jsjoeio 
glad to hear that but 
i want to point out some issues i facing 

- in code-server `settings UI`  dropdown menu is not working 
- also regarding gboard backspace issue which was in monaco-editor but after patch another problem is shown in monaco-editor@0.23.0 that is backspace not 
working at beginning of the line 

> may be this is specific to me, if anyone has this issue please comment or test it

**Comment by jsjoeio** [comment]
To keep things separate and ensure this doesn't get lost, do you mind opening a separate [bug report issue](https://github.com/cdr/code-server/issues/new?assignees=&labels=&template=bug-report.md&title=)? I'd be happy to take a closer look!

**Comment by nikey02** [comment]
sure I'll make issue with proper testing and confirmation 

thanks @jsjoeio
