### ISSUE TITLE
Vim plugin is slow

### ISSUE THREAD

**Issue by jakegt1** [cdr/code-server#308]
So, i've been using the vim extension downloaded through the main VScode marketplace (due to proxy issues with the code-server API), but the vim plugin is really slow and a pain to use.

Does everyone else have this problem, or is this due to the vim package in the coder API being slightly different then the marketplace one?

**Comment by kylecarbs** [comment]
It currently runs on the server. We'll be fixing this by allowing certain exts to run on the client. You can expect this soon.

**Comment by jakegt1** [comment]
Okay, no worries. Thanks!

**Comment by wende** [comment]
I'm running a setup with over 100 packages. All other ones seem to work flawlessly. Only the vim package is keeping my setup from running on coder. It'd be amazing to see it working at a usable pace

**Comment by jasonharrison** [comment]
The VSCodeVim plugin is rather slow because it listens to all keys and it runs on the server.  

Until client-side extensions are ready, https://marketplace.visualstudio.com/items?itemName=jpotterm.simple-vim is a *much* faster option with some caveats (read the extension's description for a list).

**Comment by code-asher** [comment]
Finally got around to implementing client-side extensions in latest master. :tada: I'm very interested in hearing any bug reports around that. Currently only `vscodevim.vim` is white-listed to run in the browser.

**Comment by jasonharrison** [comment]
@code-asher I'm so excited to hear this, can't wait to try it out. Thanks!
