### ISSUE TITLE
Is code-server free?

### ISSUE THREAD

**Issue by simonjcarr** [cdr/code-server#3094]
The repository contains an MIT Licence, which I think means I can use the software without charge including reselling my own software that includes code-server, as long as I include the licence. 

When I visit the coder website ( https://coder.com/pricing ), it says that a self-hosted version of code-server is $35 per month per user and there is no mention of a community edition.

Which is correct?

**Comment by nooobcoder** [comment]
@simonjcarr do not compare code-server with coder. Both of them are very different in use case. Coder is an enterprise workspace solution for coders to provide environments to people in an organisation on demand whereas code-server is different. @jsjoeio please have an insight on the licensing part. Being not a part / moderator of this project can't say much about it, but i can explain the difference between the two @simonjcarr

**Comment by bpmct** [comment]
Thanks @nooobcoder for the response! code-server is totally free and under the [MIT License](https://github.com/cdr/code-server/blob/main/LICENSE.txt). Coder is our commercial product for developer teams with additional features (user-management, multiple workspaces, etc) is what is discussed on the pricing page.

We'll be sure to add more details on that pricing page to make sure the difference is clear. Some more details on the comparison can be seen here: https://coder.com/docs/comparison
