### ISSUE TITLE
Security issue on /static route

### ISSUE THREAD

**Issue by futurist** [cdr/code-server#3122]
## OS/Web Information

- Web Browser: Any
- Local OS: macOS14
- Remote OS: Deiban9
- Remote Architecture: Linux_x64
- `code-server --version`: 3.8.0

## Steps to Reproduce

1. Start code-server
2. From browser access GET CDR-HOST/static/c4610f7829701aadb045d450013b84491c30580d/usr/lib/code-server/lib/vscode/node_modules/xterm-addon-search/lib/../../../../../../../../../../etc/passwd
3. You get the file content

## Expected

The `/static` route should be restricted.

## Actual

The `/static` route did not have any security check.

**Comment by jsjoeio** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [code-server: set up security policy](https://trello.com/c/wEMSnxE8/36-code-server-set-up-security-policy)

**Comment by bpmct** [comment]
@futurist are you authenticated to code-server when you experience this or are you able to access this before you log in?

**Comment by oxy** [comment]
Tested locally on 3.9.2, but the route in question hasn't had major changes.
```
[oxy@lithium ~]$ curl -k https://127.0.0.1:8080/static/fe2dc2deb08e378069891b622bb62ad1d261d1b1/usr/lib/code-server/dist/pages/../../../../../etc/passwd
{"error":"Unauthorized"}
```

It works in the browser when authenticated, but not when logged out;
we deliberately allow this when authenticated, see https://github.com/cdr/code-server/blob/v3.8.0/src/node/routes/static.ts#L42-L48

I don't see this as a security issue - when logged in, you have access to a terminal and can do pretty much whatever you want on your system.
