### ISSUE TITLE
Markdown preview doesn't work with path relative to workspace root

### ISSUE THREAD

**Issue by caiych** [cdr/code-server#3124]
## OS/Web Information

- Web Browser: Edge
- Local OS: MacOS
- Remote OS: Rasbian code-server image by linuxserver.io
- Remote Architecture: ARM
- `code-server --version`: 3.9.1 e0203f2a36c9b7036fefa50eec6cf8fa36c5c015

## Steps to Reproduce

1. Setting up a directory structure like this:
```
workspace/dir/1.md
workspace/2.md
```
2. 1.md contains
```md
[2](/2.md)
```
3. Open folder workspace
4. Open 1.md and open Markdown preview
5. Click on the rendered 2 link

## Expected

Redirecting to the preview panel of 2.md

## Actual

Does nothing.

## Screenshot

<img width="1616" alt="Screen Shot 2021-04-13 at 5 33 31 PM" src="https://user-images.githubusercontent.com/2850650/114532081-101c4580-9c7f-11eb-8e6d-bd8524381ff1.png">

## Notes

This issue can be reproduced in VS Code: No, VS Code seem to be working.

On code-server, when hovering on the link, it gives `https://$MYHOSTNAME/file//$ABSOLUTE_PATH_TO_2.md` (see bottom left of the screenshot)
A working link with relative path(`[2](../2.md)`) looks like `https://$MYHOSTNAME/webview/vscode-resource/file//$ABSOLUTE_PATH_TO_2.md`

(On VS Code, hovering gives `/file//$ABSOLUTE_PATH_TO_2.md`)

**Comment by jsjoeio** [comment]
There's a chance I'm misunderstanding something here, but I am **not** able to reproduce locally (using macOS + Chrome).

## Demo

https://user-images.githubusercontent.com/3806031/114594361-07f1e500-9c42-11eb-9b21-611d9dc1bb4a.mov

Could one of your extensions be modifying the link paths and causing this behavior?

**Comment by caiych** [comment]
Thanks for looking into this - your understanding is correct.

It's not about extensions, but the image built by https://github.com/linuxserver/docker-code-server

It works correctly on an instance installed by the script in https://github.com/cdr/code-server.

Before closing this out, any chance you have any idea what could be the reason this is happening? 

(I probably should have switched to arm64 at some point..)

**Comment by caiych** [comment]
It seems it's also only broken on 3.9.1. After re-pulling the latest 3.9.3 image it seems to be OK.

Sorry about the noise, I should have try upgrade first.

**Comment by jsjoeio** [comment]
Glad to hear upgrading fixed it! 

> Before closing this out, any chance you have any idea what could be the reason this is happening? (by reading their dockerfile, they doesn't seem to be doing a lot other than just installing it via yarn)

Hmm...yeah, looking at the [Dockerfile](https://github.com/linuxserver/docker-code-server/blob/master/Dockerfile#L41-L48), I don't see anything unusual. Ping @bpmct in case he sees anything I don't.
