### ISSUE TITLE
VSCode api tests

### ISSUE THREAD

**Issue by reactdevvv** [cdr/code-server#313]
VS Code has some API tests: https://github.com/Microsoft/vscode/tree/master/extensions/vscode-api-tests

Is it possible to run this against Coder to see the parity?

**Comment by nol166** [comment]
@reactdevvv I don't believe it would work out of the gate. We would need to add some scaffolding

**Comment by sr229** [comment]
@reactdevvv There is no gurantee those tests would work with our modifications.

**Comment by nhooyr** [comment]
We have very minimal patches so this shouldn't be necessary.
