### ISSUE TITLE
Whether code-server can support container development

### ISSUE THREAD

**Issue by sl6731220** [cdr/code-server#3154]
I really want to know how to use the container for development in code-server. The remote development plug-in of the container cannot be used in code-server. I think this function should be realized, which can directly connect to the docker container in server.You need a Docker container to set up the environment.

**Comment by code-asher** [comment]
You can follow our progress on this here: https://github.com/cdr/code-server/issues/1315

**Comment by sl6731220** [comment]
Thank you very much for your reply. I am looking forward to the success of the extension using the container. I can quickly build any AI environment limited by different CUDA versions, which will be a great advantage.
