### ISSUE TITLE
discord.js?

### ISSUE THREAD

**Issue by Tydium** [cdr/code-server#3159]
Hey I was thinking you guys could add modules for discord.js? Perhaps something like [Discord js tools](https://marketplace.visualstudio.com/items?itemName=jasonhaxstuff.discord-js-tools) so it can be even more easier to code discord bots. I tried searching the custom store for something like it, but couldn't find anything. This would be a great touch!

**Comment by oxy** [comment]
Hi there! Our current extension marketplace is in maintenance mode, and we are currently in the process of switching extension marketplaces and transitioning over to [Open VSX](https://open-vsx.org/).
Once https://github.com/eclipse/openvsx/issues/249 is finalized, we can fully make this transition. Therefore, we are no longer accepting new extension requests. 

We suggest installing the VSIX file and then installing into code-server as a temporary workaround. See [docs](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#installing-vsix-extensions-via-the-command-line) for more info.
