### ISSUE TITLE
rust-analyzer plugin not working on code-server

### ISSUE THREAD

**Issue by Jason5Lee** [cdr/code-server#3179]
## OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: macOS
- Remote Architecture:
- `code-server --version`: 3.9.3 fe2dc2deb08e378069891b622bb62ad1d261d1b1

## Steps to Reproduce

1. run code-server
2. install rust-analyzer plugin
3. open a rust project.

## Expected

The plugin works fine.

## Actual

Plugin starts with error and cannot download rust-analyzer binary.

## Screenshot

![Screen Shot 2021-04-21 at 11 02 55 AM](https://user-images.githubusercontent.com/25118271/115491167-12d7f580-a292-11eb-89db-00db40bc17e6.png)
![Screen Shot 2021-04-21 at 11 03 00 AM](https://user-images.githubusercontent.com/25118271/115491174-15d2e600-a292-11eb-9864-ea7ece573a11.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
I have the same setup (macOS + Chrome) and I was able to download the rust-analyzer binary and get it working (though I did see the `configuration.property` error.

## Screenshot

![image](https://user-images.githubusercontent.com/3806031/115589574-d8b42700-a284-11eb-9fcc-fc3e2eeab02c.png)

It looks like it could be an auth issue or a network error? Did you try updating your GitHub Auth token or retrying the download?

**Comment by Jason5Lee** [comment]
I solve it by manual setup the rust-analyzer path, still have no idea why it fails to download.

**Comment by jsjoeio** [comment]
Very weird. Well if it happens again or you figure out what's causing it, feel free to open a new issue. Glad you got it working though!

**Comment by mota57** [comment]
my issue is that the linting doesn't work! any issues relate to that?
