### ISSUE TITLE
'go to function definition' very slow and stuck

### ISSUE THREAD

**Issue by JJplane** [cdr/code-server#3183]
## OS/Web Information

- Web Browser:Chrome
- Local OS:mac
- Remote OS:Ubuntu
- Remote Architecture:
- `code-server --version`:v3.9.3

## Steps to Reproduce

1.when I put the cursor on the function to look up the  function args
2.Or click on the function name to go to definition

## Expected
qucikly show the definitions

## Actual
everytime I restart the codeserver, it work once.But after once  'loading.... 'appears when I put the cursor on the function.And a progress bar appears when i click on the function.Then it stucks and shows nothing.

## Screenshot
![image](https://user-images.githubusercontent.com/28783826/115524917-31a1b080-a2c1-11eb-93f5-0e867251fb32.png)

## Notes
I have the same question on my vscode to remote to my own machine.  have fixed it by install pylance and set it the python server althoug the speed is still  a little slow.But it doesn't work for codeserver, and code-server doesn't have pylance extentions online. I installed it offline by downloading from the web.
Also solvments about typescript@next doesn't work for me either.
By the way, I am using codeserver on company's machine which has , everytime when I start code server, it shows
![image](https://user-images.githubusercontent.com/28783826/115523768-fce12980-a2bf-11eb-8190-26dcc07200aa.png)

This issue can be reproduced in VS Code: Yes

**Comment by jsjoeio** [comment]
I tested locally using macOS + Chrome and could not reproduce unfortunately.

## Screenshot

https://user-images.githubusercontent.com/3806031/115590114-7576c480-a285-11eb-9efd-66b91d08a9f4.mov

> This issue can be reproduced in VS Code: Yes

If this can be reproduce in VS Code, then you should file it upstream.

> By the way, I am using codeserver on company's machine which has , everytime when I start code server, it shows

This sounds like a separate issue. Do you mind filing a separate bug report issue?

**Comment by code-asher** [comment]
I wonder if service workers are required for the goto functionality. If that's the case the SSL issue will need to be resolved to get this working.

**Comment by JJplane** [comment]
https://user-images.githubusercontent.com/28783826/115809581-f2897180-a41e-11eb-9bbd-5841061bae55.mov


At the begining, cert False shows up, I choose 'continuing ot xxxx', At 00:06, I click the function name, it quickly shows the definition.At 00:11, I mouseover the fuction, 'loading' shows.At00:14

,  I click the function, the progress bar shows. As @code-asher says,:
> I wonder if service workers are required for the goto functionality. If that's the case the SSL issue will need to be resolved to get this working.

Maybe the service doesn't work well. Any help to solve the SSL isuue or other sovelment.If the SSL is the reson, the same issue appears on vscode which remoted to another remoting machine. And it is solved by change python server to pylance(stil a little slower than remoting by Pycharm but tolerable).

**Comment by code-asher** [comment]
It's strange that it works once. You were able to replicate this in local VS Code?

You could try launching chrome with `chrome --ignore-certificate-errors` just to see if the certificate is causing the issue.
