### ISSUE TITLE
Open... and Open Workspace pops up a menu, which is dismissed immediately

### ISSUE THREAD

**Issue by KeyboardNerd** [cdr/code-server#319]
- `code-server` version: 
server/development linux-x64 node-v8.15.0

- OS Version: 
Ubuntu 18.10, running on docker for mac, container image is 
codercom/code-server:latest

## Steps to Reproduce
Here is the video, it should really help you how to reproduce the problem:
https://github.com/KeyboardNerd/keyboardnerd.github.io/blob/master/Screen%20Recording%202019-03-22%20at%206.12.37%20PM.mov

**Comment by nol166** [comment]
@KeyboardNerd can you try running `docker pull codercom/code-server:latest`?

**Comment by nol166** [comment]
and then run the docker command again?
