### ISSUE TITLE
Auth to GitHub on iPad Shows about:blank and Sign in failed: SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by ambroselittle** [cdr/code-server#3190]
## OS/Web Information

- Web Browser: Safari iPadOS
- Local OS: 14.4.2 (18D70)
- Remote OS: bencdr/code-server-azure container 
- Remote Architecture: 
- `code-server --version`: Whatever that image uses.

## Steps to Reproduce

1. Choose Clone repo on main start page.
2. Choose Clone from GitHub
    It prompts: The extension 'GitHub' wants to sign in using GitHub.
3. Choose Allow
    It shows Safari prompt: This site is attempting to open a pop-up window
4. Choose Allow

## Expected

I assume it should do some oAuth type flow to auth with GH.

## Actual

Shows about:blank page. And when going back to the originating window, it shows this error:
Sign in failed: SecurityError: The operation is insecure.

## Notes

This issue can be reproduced in VS Code: No

This was a brand new deploy from the container above. First experience trying to clone and work from iPad using this solution. I am using a p1v3 Linux plan level.

**Comment by jsjoeio** [comment]
Unfortunately, I could not reproduce this locally on my iPad using my code-server deployment on [Railway](https://railway.app/)

To deploy code-server to Railway, check out [this guide](https://github.com/cdr/deploy-code-server/blob/main/guides/railway.md).

## Screenshot
https://user-images.githubusercontent.com/3806031/116130187-cae51400-a67f-11eb-97d9-b4cb4fd545d7.MP4

Could you post the browser logs or the server logs `code-server --log debug`? For getting the browser logs, the only way I know how to do it is using a 3P app like [Inspect](https://apps.apple.com/us/app/inspect-browser/id1203594958), but it costs $6.99

**Comment by ambroselittle** [comment]
@jsjoeio, not ignoring you. Just trying to find time to get back to this. Are you interested in a repro on Azure? Not sure if it is just that deploy config that is messed up or not. Anyhow, I can inspect Safari while connected to my Mac, so if/when I get back, I'll try that and see if I can see the errors.

**Comment by jsjoeio** [comment]
No worries at all! 

> Are you interested in a repro on Azure? Not sure if it is just that deploy config that is messed up or not.

I actually haven't used Azure or deployed code-server there so I might not be much help. I just remembered we have a guide for Azure [here](https://github.com/bpmct/code-server-azure). It might be worth looking at that first and then posting  anything you find so we can help further troubleshoot this.

**Comment by ambroselittle** [comment]
Well.. I don't know what changed. I did change my app plans around and restart. I also have the debugger connected. I guess something could have been cached somewhere. ¯\_(ツ)_/¯

Anyhow, it is working now, authenticated to GH and can clone repos. Thanks.
