### ISSUE TITLE
Cannot insert a new line in LaTeX files with the extension LaTeX Workshop enabled

### ISSUE THREAD

**Issue by NotoOotori** [cdr/code-server#3191]
## OS/Web Information

- Web Browser: Safari
- Local OS: iPadOS 14.4.2 (18D70)
- Remote OS: Ubuntu 18.04.5 LTS
- Remote Architecture: x86_64
- `code-server --version`: 3.9.3 fe2dc2deb08e378069891b622bb62ad1d261d1b1

## Steps to Reproduce

1. Install the extension LaTeX Workshop of version 8.16.1 globally and reconnect to code-server.
2. Create a new file and set the language mode to be LaTeX.
3. Press the key ``Enter``.

## Expected

A new line should be inserted.

## Actual

No new lines are inserted and code-server notifies that

> command ‘latex-workshop.onEnterKey’ not found

## Notes

This issue can be reproduced in VS Code: No

**Comment by NotoOotori** [comment]
## Screenshots

![image](https://user-images.githubusercontent.com/39304463/115681218-e7830280-a386-11eb-8c42-f69e8fd83299.jpeg)

**Comment by code-asher** [comment]
It's possible we have a broken extension; could you post the browser logs?

**Comment by NotoOotori** [comment]
Sorry, could you please tell me where to find the browser logs. By the way, here's what I've found in OUTPUT-Log (Remote Extension). It seems like there is an error finding some module.

> [2021-04-27 06:48:13.209] [exthost] [info] extension host started
> [2021-04-27 06:48:13.571] [exthost] [info] ExtensionService#_doActivateExtension James-Yu.latex-workshop {"startup":false,"extensionId":{"value":"James-Yu.latex-workshop","_lower":"james-yu.latex-workshop"},"activationEvent":"onLanguage:latex"}
> [2021-04-27 06:48:13.571] [exthost] [info] ExtensionService#loadCommonJSModule file:///root/.local/share/code-server/extensions/james-yu.latex-workshop-8.17.0/out/src/main.js
> [2021-04-27 06:48:13.573] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
> [2021-04-27 06:48:13.573] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code-server/lib/vscode/extensions/debug-auto-launch/dist/extension
> [2021-04-27 06:48:13.584] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
> [2021-04-27 06:48:13.584] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code-server/lib/vscode/extensions/git/dist/main
> [2021-04-27 06:48:13.653] [exthost] [error] Activating extension James-Yu.latex-workshop failed due to an error:
> [2021-04-27 06:48:13.655] [exthost] [error] Error: Cannot find module '/root/.local/share/code-server/extensions/james-yu.latex-workshop-8.17.0/out/src/main.js'
> Require stack:
> - /usr/lib/code-server/lib/vscode/out/vs/loader.js
> - /usr/lib/code-server/lib/vscode/out/bootstrap-amd.js
> - /usr/lib/code-server/lib/vscode/out/bootstrap-fork.js
> 	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
> 	at Function.Module._load (internal/modules/cjs/loader.js:667:27)
> 	at Function.a._load (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27293)
> 	at Function.v._load (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:24039)
> 	at Function.W._load (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
> 	at Module.require (internal/modules/cjs/loader.js:887:19)
> 	at require (internal/modules/cjs/helpers.js:74:18)
> 	at Function.t [as __$__nodeRequire] (/usr/lib/code-server/lib/vscode/out/vs/loader.js:4:101)
> 	at l._loadCommonJSModule (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:25445)
> 	at l._doActivateExtension (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:11565)
> 	at l._activateExtension (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:10624)
> 	at Object.actualActivateExtension (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:8287)
> 	at m._activateExtension (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:82365)
> 	at /usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:82047
> 	at Array.map (<anonymous>)
> 	at m._activateExtensions (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:82035)
> 	at m.activateByEvent (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:79605)
> 	at l._activateByEvent (/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:9186)
> 	at /usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:18890
> [2021-04-27 06:48:14.190] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
> [2021-04-27 06:48:14.190] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code-server/lib/vscode/extensions/github/dist/extension.js
> [2021-04-27 06:48:14.486] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":false,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"onStartupFinished"}
> [2021-04-27 06:48:14.487] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code-server/lib/vscode/extensions/emmet/dist/node/emmetNodeMain
> [2021-04-27 06:48:14.507] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":false,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"onStartupFinished"}
> [2021-04-27 06:48:14.507] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code-server/lib/vscode/extensions/merge-conflict/dist/mergeConflictMain
> [2021-04-27 06:48:14.512] [exthost] [info] ExtensionService#_doActivateExtension vscode.testing-editor-contributions {"startup":false,"extensionId":{"value":"vscode.testing-editor-contributions","_lower":"vscode.testing-editor-contributions"},"activationEvent":"onStartupFinished"}
> [2021-04-27 06:48:14.512] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code-server/lib/vscode/extensions/testing-editor-contributions/dist/extension.js
> [2021-04-27 06:48:14.514] [exthost] [info] eager extensions activated
> [2021-04-27 06:48:14.708] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
> [2021-04-27 06:48:14.713] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/lib/code-server/lib/vscode/extensions/ms-vscode.js-debug/src/extension.js

**Comment by code-asher** [comment]
Ah OK yup it looks like the extension is broken in our marketplace.

As a workaround you could download the extension from OpenVSX and install it into code-server manually. https://open-vsx.org/extension/James-Yu/latex-workshop

We are in the process of migrating to OpenVSX so once that is done the workaround will no longer be required.

**Comment by NotoOotori** [comment]
Thanks! The workaround works!

Now I will close the issue.
