### ISSUE TITLE
toggle terminal has wrong behavior when words are selected by user

### ISSUE THREAD

**Issue by hakanaku1234** [cdr/code-server#3192]
## OS/Web Information

- Web Browser: Chrome
- Local OS: Windows10 (10.0.18363 N/A build 18363)
- Remote OS: Ubuntu18.04
- Remote Architecture: x64
- `code-server --version`: 3.9.2 109d2ce3247869eaeab67aa7e5423503ec9eb859

## Steps to Reproduce
0. first of all, setup this shortcut:
```
  {
    "key": "ctrl+`",
    "command":"workbench.action.terminal.toggleTerminal"
  },
```
1. open a file and input random text
2. select any word (or words)
3. press "ctrl+`" 

(this bug only happens when it has selected words)
e.g. 
![image](https://user-images.githubusercontent.com/34119262/115713741-eebb0800-a3a8-11eb-8c87-d01a9533c2ff.png)

## Expected

toggle code-server ingergrated terminal and when open, the terminal should be focused.

## Actual

always focus on text editor while there are words selected by user, nothing happened.

## Notes

This issue can be reproduced in VS Code: Yes/No No

**Comment by jsjoeio** [comment]
I was able to reproduce in 3.9.3 using code-server locally in Chrome. I even tried changing the `when`  clause for the shortcut, but that didn't fix it.

## code-server

https://user-images.githubusercontent.com/3806031/115756346-f8198580-a352-11eb-9561-b8e6bc9df19e.mov

## Codespaces

I was able to reproduce in Codespaces which means it's an upstream issue.

Nice job finding this bug!

https://user-images.githubusercontent.com/3806031/115758695-4418fa00-a354-11eb-87a0-42a5db454fdf.mov
