### ISSUE TITLE
Automatically post release notes to community Slack

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#3193]
When a new release is cut, post the release notes to the code-server Community Slack 

## Notes

- we would just need a Slack token for the Slack community
- it could be automated -> set up a job in the `publish.yaml` called "slack"

H/T to @jawnsy for the idea

**Comment by jawnsy** [comment]
I think this should be done, using the GitHub Slack integration, so we can close this out

![image](https://user-images.githubusercontent.com/52710/141187179-cd909be5-acaa-4275-8d83-cda411281390.png)
