### ISSUE TITLE
The main page is loading urls from {{CS_STATIC_BASE}} after update from a very old version

### ISSUE THREAD

**Issue by AlseinX** [cdr/code-server#3197]
## OS/Web Information

- Web Browser: Edge(Chromium) Stable Latest
- Local OS: Windows 10 20H2
- Remote OS: CentOS 8
- Remote Architecture: AMD64
- `code-server --version`: 3.9.3 fe2dc2deb08e378069891b622bb62ad1d261d1b1

## Steps to Reproduce

1. Remove the rpm package from an old version
2. Install 3.9.3
3. Run and open, login

## Expected

work properly

## Actual

empty page while the developer tools reports a bunch of 404 error.

`require is not defined`

## Screenshot

![image](https://user-images.githubusercontent.com/8338587/115869379-62741800-a470-11eb-9344-e93ce782484b.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by code-asher** [comment]
Are there any logs from code-server on the server side?

I tried replicating this in a Centos8 Docker container and installing with `curl -fsSL https://code-server.dev/install.sh | sh` but it appears to be working for me.
