### ISSUE TITLE
500: ``VS Code failed to load. exited unexpectedly with code 0`` 

### ISSUE THREAD

**Issue by informathemusic** [cdr/code-server#3198]
## OS/Web Information

- Web Browser: Firefox
- Local OS: Windows 10
- Remote OS: Raspbian
- Remote Architecture: armv71
- `code-server --version`:3.9.3

## Steps to Reproduce

1. Install code-server
2. Run code-server
3. Login in browser

## Expected

To be able to use vscode in browser

## Actual

vscode doesn't start

## Screenshot

![](https://imgur.com/QXtjOcv)

## Notes

This issue can be reproduced in VS Code: ~~Yes~~/No

**Comment by informathemusic** [comment]
### Update
Issue is still persisting after a fresh install of debian.
plz help :p

**Comment by code-asher** [comment]
Please post the code-server and browser logs!

**Comment by informathemusic** [comment]
Sorry for dropping in late -- i don't actually have them, i re re installed raspbian because of file system errors

I will install code-server and tell you
