### ISSUE TITLE
Jupyter Notebook cells don’t execute properly 

### ISSUE THREAD

**Issue by gogobd** [cdr/code-server#3199]
## OS/Web Information

- Web Browser: Brave
- Local OS: macOS
- Remote OS: docker on macoS
- Remote Architecture: amd64
- `code-server --version`: 3.9.3

## Steps to Reproduce

1. Click a .ipynb file

## Expected

Jupyter Notebook should open, connect to a Kernel and cells should be ready to run

## Actual

Even after a series of installations of plugins (that seem to work fine) the Notebook can connect to a kernel but no output is being received (all i see is "Loading...", then after some time I get the error shown in the screenshot "ChunkLoadError")

## Screenshot

<img width="1315" alt="Screenshot 2021-04-23 at 20 50 21" src="https://user-images.githubusercontent.com/728976/115916799-9140bd00-a475-11eb-863f-3fdc5ead1ff4.png">

## Notes

This issue can be reproduced in VS Code: No idea.

**Comment by gogobd** [comment]
I tried again, still no dice.

This time I tried to installed (Mini-)conda environment into docker before getting and starting code server.

1.) I click the .ipynb file, Code Server asks me if I want to search the Marketplace for support for ipnb files, I agree and install Jupyter v2021.3.0
2.) I click the .ipynb file again and Code Server installs an ipython kernel
3.) I can select the kernel and get no error message when I connect to it
4.) I try to run a "print('Hello, world!')" cell and get the error message posted previously.

**Comment by code-asher** [comment]
Is that the only error you see in the browser console logs?

**Comment by gogobd** [comment]
This error is seen in the editor, i didn’t look at the browsers console log

**Comment by code-asher** [comment]
Oops my bad. Please post the browser console logs! The code-server logs may also be helpful although in this case probably not.

**Comment by gogobd** [comment]
I was trying to provide the console logs when the bug just went away. I don't know why but it's not an issue any more. I'm closing this, sorry for the fuzz.

**Comment by gogobd** [comment]
Ok; i was able to reproduce this here's the log:

localhost/:1 [Deprecation] ::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead. See https://chromestatus.com/feature/6730096436051968 for more details.
register.ts:14 [Service Worker] registered
webWorkerExtensionHost.ts:125 The web worker extension host is started without an iframe sandbox!
start @ webWorkerExtensionHost.ts:125
abstractExtensionService.ts:846 Extension 'ms-python.python' uses PROPOSED API which is subject to change and removal without notice.
updateEnableProposedApi @ abstractExtensionService.ts:846
abstractExtensionService.ts:846 Extension 'ms-toolsai.jupyter' uses PROPOSED API which is subject to change and removal without notice.
updateEnableProposedApi @ abstractExtensionService.ts:846
console.ts:137 [Extension Host] (node:465) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
m @ console.ts:137
2notificationsAlerts.ts:40 Failed to find a kernelspec to use for ipykernel launch
onDidChangeNotification @ notificationsAlerts.ts:40
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Failed to find a kernelspec to use for ipykernel launch
m @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: Failed to find a kernelspec to use for ipykernel launch	at w.createNotebookInstance (/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:49:823711)
m @ console.ts:137
mainThreadExtensionService.ts:59 [[object Object]]Failed to find a kernelspec to use for ipykernel launch
$onExtensionRuntimeError @ mainThreadExtensionService.ts:59
mainThreadExtensionService.ts:60 Error: Failed to find a kernelspec to use for ipykernel launch
	at w.createNotebookInstance (:8080/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:49)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: Failed to find a kernelspec to use for ipykernel launch
m @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: Failed to find a kernelspec to use for ipykernel launch	at w.createNotebookInstance (/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:49:823711)
m @ console.ts:137
mainThreadExtensionService.ts:59 [[object Object]]Failed to find a kernelspec to use for ipykernel launch
$onExtensionRuntimeError @ mainThreadExtensionService.ts:59
mainThreadExtensionService.ts:60 Error: Failed to find a kernelspec to use for ipykernel launch
	at w.createNotebookInstance (:8080/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/client/extension.js:49)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
DevTools failed to load SourceMap: Could not load content for http://localhost:8080/static/fe2dc2deb08e378069891b622bb62ad1d261d1b1/root/.local/lib/code-server-3.9.3/dist/pages/pages/vscode.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:8080/webview/vscode-resource/file/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/datascience-ui/notebook/monaco.bundle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:8080/webview/vscode-resource/file/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/datascience-ui/notebook/commons.initial.bundle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://localhost:8080/webview/vscode-resource/file/root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/datascience-ui/notebook/nativeEditor.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
console.ts:137 [Extension Host] Starting WebSocket: RAW/api/kernels/e06c821e-a79a-4868-a85f-c69a4adf19d6
console.ts:137 [Extension Host] Kernel: connected (e06c821e-a79a-4868-a85f-c69a4adf19d6)
commons.initial.bundle.js:2 Starting WebSocket: BOGUS_PVSC/api/kernels/e06c821e-a79a-4868-a85f-c69a4adf19d6
commons.initial.bundle.js:2 Kernel: connected (e06c821e-a79a-4868-a85f-c69a4adf19d6)
console.ts:137 [Extension Host] Starting WebSocket: RAW/api/kernels/566d6b79-95f1-4d30-9b8f-187695f0b08f
console.ts:137 [Extension Host] Kernel: connected (566d6b79-95f1-4d30-9b8f-187695f0b08f)
monaco.bundle.js:1 Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/Microsoft/monaco-editor#faq
we @ monaco.bundle.js:1
(anonymous) @ monaco.bundle.js:1
monaco.bundle.js:1 undefined
we @ monaco.bundle.js:1
(anonymous) @ monaco.bundle.js:1
24monaco.bundle.js:1 undefined
we @ monaco.bundle.js:1
(anonymous) @ monaco.bundle.js:1
:8080/webview/vscode-resource/file///app/editor.worker.js:1 Failed to load resource: net::ERR_FAILED
2commons.initial.bundle.js:2 ChunkLoadError: Loading chunk vendors~dataresource~geojson~modeldebug~nteract_transforms~nteract_transforms_vsdom failed.
(timeout: http://localhost:8080/webview/vscode-resource/file///root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/datascience-ui/notebook/vendors~dataresource~geojson~modeldebug~nteract_transforms~nteract_transforms_vsdom.bundle.js)
    at Function.o.e (http://localhost:8080/webview/vscode-resource/file///root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/datascience-ui/notebook/nativeEditor.js:1:1713)
    at http://localhost:8080/webview/vscode-resource/file///root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/datascience-ui/notebook/commons.initial.bundle.js:2:493888
    at http://localhost:8080/webview/vscode-resource/file///root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/datascience-ui/notebook/commons.initial.bundle.js:2:2003054
    at Object.next (http://localhost:8080/webview/vscode-resource/file///root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/datascience-ui/notebook/commons.initial.bundle.js:2:2003159)
    at http://localhost:8080/webview/vscode-resource/file///root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/datascience-ui/notebook/commons.initial.bundle.js:2:2002096
    at new Promise (<anonymous>)
    at s (http://localhost:8080/webview/vscode-resource/file///root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/datascience-ui/notebook/commons.initial.bundle.js:2:2001870)
    at e.importer (http://localhost:8080/webview/vscode-resource/file///root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/datascience-ui/notebook/commons.initial.bundle.js:2:493770)
    at e.getComponent (http://localhost:8080/webview/vscode-resource/file///root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/datascience-ui/notebook/commons.initial.bundle.js:2:485940)
    at http://localhost:8080/webview/vscode-resource/file///root/.local/share/code-server/extensions/ms-toolsai.jupyter-2021.3.0/out/datascience-ui/notebook/commons.initial.bundle.js:2:494869
na @ commons.initial.bundle.js:2
i.componentDidCatch.r.callback @ commons.initial.bundle.js:2
Ki @ commons.initial.bundle.js:2
Ji @ commons.initial.bundle.js:2
Ta @ commons.initial.bundle.js:2
Pa @ commons.initial.bundle.js:2
(anonymous) @ commons.initial.bundle.js:2
t.unstable_runWithPriority @ commons.initial.bundle.js:2
Ms @ commons.initial.bundle.js:2
xs @ commons.initial.bundle.js:2
Es @ commons.initial.bundle.js:2
ms @ commons.initial.bundle.js:2
za @ commons.initial.bundle.js:2
enqueueSetState @ commons.initial.bundle.js:2
E.setState @ commons.initial.bundle.js:2
A.safeSetState @ commons.initial.bundle.js:2
(anonymous) @ commons.initial.bundle.js:2
Promise.catch (async)
A.loadAsync @ commons.initial.bundle.js:2
A.componentDidMount @ commons.initial.bundle.js:2
Ta @ commons.initial.bundle.js:2
Pa @ commons.initial.bundle.js:2
(anonymous) @ commons.initial.bundle.js:2
t.unstable_runWithPriority @ commons.initial.bundle.js:2
Ms @ commons.initial.bundle.js:2
xs @ commons.initial.bundle.js:2
Es @ commons.initial.bundle.js:2
Cs @ commons.initial.bundle.js:2
notify @ commons.initial.bundle.js:2
t.notifyNestedSubs @ commons.initial.bundle.js:2
t.handleChangeWrapper @ commons.initial.bundle.js:2
g @ commons.initial.bundle.js:2
(anonymous) @ commons.initial.bundle.js:2
(anonymous) @ commons.initial.bundle.js:2
(anonymous) @ commons.initial.bundle.js:2
handleMessage @ commons.initial.bundle.js:2
(anonymous) @ commons.initial.bundle.js:2
(anonymous) @ commons.initial.bundle.js:2
(anonymous) @ commons.initial.bundle.js:2
(anonymous) @ commons.initial.bundle.js:2
(anonymous) @ commons.initial.bundle.js:2
s @ commons.initial.bundle.js:2
e.handleMessages @ commons.initial.bundle.js:2
postMessage (async)
(anonymous) @ main.js:677
(anonymous) @ host.js:26
postMessage (async)
doPostMessage @ webviewElement.ts:265
_send @ baseWebviewElement.ts:221
postMessage @ baseWebviewElement.ts:214
postMessage @ dynamicWebviewEditorOverlay.ts:255
$postMessage @ mainThreadWebviews.ts:61
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
(anonymous) @ browserSocketFactory.ts:178
fire @ event.ts:622
_fileReader.onload @ browserSocketFactory.ts:62

**Comment by gogobd** [comment]
I was now reproducing this issue both with a conda environment and debian buster python3 (both inside docker). Code Server asks me to install the Jupyter extension, then Python, then it installs ipython Kernel; unfortunately the ChunkLoadError comes up every time now again.

**Comment by code-asher** [comment]
I tried to replicate but I ran into issues with the extension activating at all; I'm getting the error mentioned here: https://github.com/cdr/code-server/issues/2929

I'd be interested in seeing if downloading and installing the extension from OpenVSX works for you: https://open-vsx.org/extension/ms-python/python

**Comment by gogobd** [comment]
With https://open-vsx.org/api/ms-python/python/2020.10.332292344/file/ms-python.python-2020.10.332292344.vsix installed (and de-selecting Extensions: Automatic Updates first) it was kinda worse - I wasn't even able to connect to the ipython Kernel. Even though at one point Code Server has installed ipython.

**Comment by code-asher** [comment]
I gave it a try and I'm seeing the same thing (or something similar). It says `Not connected`. If I click it to connect it fails with:

```
Error: Jupyter cannot be started. Error attempting to locate jupyter: Data Science libraries jupyter and notebook are not installed in interpreter Python 2.7.17 64-bit
```

If I switch to Python 3 using the button in the status bar I get this instead:

```
Error: Jupyter cannot be started. Error attempting to locate jupyter:
```

Jupyter is in my path so I'm not sure why.

So then I opened the command pallete and switched the interpreter there instead and for some reason that worked. (Credit here: https://stackoverflow.com/questions/60330837/jupyter-server-not-started-no-kernel-in-vs-code)

I don't know if any of that applies to your situation but maybe it'll be helpful.

**Comment by gogobd** [comment]
When I shift-reload code server i see "Connecting to Python 3", then the icon goes green and I'm connected (idle). But a cell containing "print('Hello, world!')" just yields "Loading...", then, later, the error I posted above (ChunkLoadError: Loading chunk vendors~dataresource~geojson~modeldebug~nteract_transf...). So for me connecting (supposedly) works, execution doesn't.
@code-asher Thank you very much for your help, though! I think it helped clarify this issue :-)

**Comment by code-asher** [comment]
Ah that's unfortunate. This won't be helpful but running cells is working for me (similar code, just a simple `print`).

I don't think we've seen the browser logs yet with the OpenVSX version so posting those might lead to a clue.

**Comment by gogobd** [comment]
I was posting the console log before (https://github.com/cdr/code-server/issues/3199#issuecomment-826993002) maybe i should just post the Dockerfile

**Comment by gogobd** [comment]
```
FROM debian:buster-slim

ENV SHELL /bin/bash
  
# Install system dependencies
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    wget \
    git \
    screen \
    unzip \
    vim \
    procps \
 && apt-get clean

# Install miniconda
RUN curl -sfLO https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh \
 && /bin/bash Miniconda3-py39_4.9.2-Linux-x86_64.sh -b -p /root/miniconda \
 && PATH="/root/miniconda/bin:$PATH" \
 && conda install -c anaconda jupyter

## Code server
RUN mkdir -p ~/.local/lib ~/.local/bin
RUN curl -sfL https://github.com/cdr/code-server/releases/download/v3.9.3/code-server-3.9.3-linux-amd64.tar.gz | tar -C ~/.local/lib -xz
RUN mv ~/.local/lib/code-server-3.9.3-linux-amd64 ~/.local/lib/code-server-3.9.3
RUN ln -s ~/.local/lib/code-server-3.9.3/bin/code-server ~/.local/bin/code-server
RUN PATH="~/.local/bin:$PATH"

WORKDIR /app
CMD ~/.local/bin/code-server --bind-addr 0.0.0.0:8080 /app

# docker build -t jupyter .
# docker run -v $(pwd):/app -p 8080:8080 -p ... -it -d jupyter
# docker exec -it <dontainer_id> cat /root/.config/code-server/config.yaml
```

**Comment by code-asher** [comment]
Oh weren't those the logs with the version from our marketplace and not the OpenVSX one?

I'll give the Dockerfile a run when I get a chance.

**Comment by gogobd** [comment]
With OpenVSX I wasn't able to connect to the kernel - and I tried again now via Command Palette: The Command is available but no Kernels are being presented. It's very weird because console log says "Kernel: connected (099ad007-dbfd-48c6-ab30-003320fe07a9)" but the icons don't change, it keeps saying "Python3: Not Started". Note: I had two packages installed: Python (OpenVSX) and Jupyter (from Marketplace).

**Comment by code-asher** [comment]
Oh maybe that's it! I actually forgot to mention I had a similar problem. I tried to uninstall the Python and Jupyter extensions and then install the OpenVSX Jupyter extension (it contains both Python and Jupyter from before they were split) but I ended up having to wipe the extensions in `~/.local/share/extensions` and then install the OpenVSX one again.

VS Code doesn't actually remove extensions from disk when uninstalling so I think it causes weird issues when adding a different version of the extension manually.

**Comment by gogobd** [comment]
I was using docker and actually deleted the images and containers frequently for a fresh start; the ~/.local/share/code-server/extensions/ are not in my /app dir so I think that can't be it...
Thank you very much for your help, it's very appreciated!

**Comment by gogobd** [comment]
Oh, and I can't find a dedicated "Jupyter" Extension on OpenVSX!

**Comment by code-asher** [comment]
Ah right that makes sense.

The Python extension on OpenVSX includes both Python and Jupyter. 

It was split into two extensions but OpenVSX still has the version from before the split.

**Comment by code-asher** [comment]
I gave your Dockerfile a run and everything worked! My exact steps:

1. Save Dockerfile as test.Dockerfile
2. docker build -t code-server . -f test.Dockerfile
3. docker run -e PASSWORD=test -p 8080:8080 code-server
4. Browse to localhost:8080 and log in
5. Open terminal
6. Run `wget https://open-vsx.org/api/ms-python/python/2020.10.332292344/file/ms-python.python-2020.10.332292344.vsix`
7. Extensions > Install from VSIX > Select downloaded VSIX
8. Refresh the page
9. Open command palette
10. Select  `Create New Blank Jupyter Notebook`
11. Add `print("hello")` to the cell
12. Click run

**Comment by gogobd** [comment]
This is so weird, I was trying

docker build -t jupyter .
docker run -v $(pwd):/app -p 8080:8080 -it -d jupyter
docker exec -it <dontainer_id> cat /root/.config/code-server/config.yaml (to see the generated password)

Then follow 4, 5, 6, 7, 8, 9, 10, 11 and 12

And all I got is "Loading..." and then the ChunkLoadError. That was quite unexpected because we were using the same Dockerfile. My Docker host is macOS Big Sur 11.3; But my Broser is Brave - so i tried Safari and: The cell executed!

**Comment by gogobd** [comment]
I turned off "Shields" for localhost:8080 but the cells are still not executing in Brave (still working fine in Safari). This whole thing is a browser issue!

**Comment by gogobd** [comment]
After deleting all user data related to Brave and re-installing it cell execution works again like it should!

**Comment by gogobd** [comment]
Thanks, @code-asher your help solved my issue!

**Comment by code-asher** [comment]
Very interesting! I'm glad we got it sorted! :smile:

**Comment by gogobd** [comment]
For completeness: after resetting Brave this issue is gone even when I use the Marketplace Extensions Jupyter v2021.3.0 and Python v2021.4.765268190 which are being installed as defaults (code server 3.9.3)!
