### ISSUE TITLE
PyLance Language Server by microsoft does not work. Autoimport does not work too.

### ISSUE THREAD

**Issue by nooobcoder** [cdr/code-server#3216]
#3182 
The autoimport feature in Pylance does not work on code-server. I know Pylance is in preview state, but it does not work at all on code-server. Works fine on VSCode though. I have sideloaded the extension from vsix as this is not available in the openvsix repository.
[Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance)

Also, i have enabled the following entry in settings.json to enable the language server across my workspaces.
`"python.languageServer": "Pylance"`

Please bring a patch for this in the next major update. #1938 

I think this has already been answered here somehow
> Not only is redistribution not allowed, but even if installed by hand, Pylance will [refuse to run on any unofficial build](https://github.com/microsoft/pylance-release/issues/135#issuecomment-662607952).
> 
> Isn't it wonderful that M$ now "loves open source"? /s

But, still why it should not work on code-server when it works on VSCode. It should work as code-server is a fork of VSCode right?

Attaching relevant screenshots below, please see that the logs of the language server are empty. Seems like the extension is not loading itself at all.

![image](https://user-images.githubusercontent.com/50350828/116041931-7778c300-a68b-11eb-97e4-215360a10567.png)

Thank You.
Ankur Paul

**Comment by oxy** [comment]
We cannot. Microsoft will not allow us to, and their license prohibits it.
We do offer a fork of VSCode, but the license to the extension (and the extension itself) will *only* allow you to use it on the official Microsoft-provided binary builds, labelled "Visual Studio Code". I can't recommend bypassing this limitation either, because you'd be violating their license.

The issue you linked to has more information.

**Comment by linuxd3v** [comment]
Jedi language server works fine for me in selfhosted vscode.

{
    "python.defaultInterpreterPath": "${workspaceFolder}/.venv/bin/python3",
    "python.languageServer": "Jedi"
}
