### ISSUE TITLE
How to access code --version over CLI

### ISSUE THREAD

**Issue by shivapoudel** [cdr/code-server#322]
## Description
I want to use vscode command over cli but I was unable. Additionally, I want to install PHP too.

**Comment by 5hay** [comment]
Not exactly sure if that's what you mean, but I think I have a similiar problem:

`code-server --version` does not return a version number.
Instead it just outputs 

> server/development linux-x64 node-v8.15.0

Is there another way to show the currently installed version of code-server that I don't know about?

> Additionally, I want to install PHP too.

You can install PHP via the package manager apt.

**Comment by nol166** [comment]
If you have [Docker](https://docker.com) installed you can run the following command in terminal:
`docker run -t -p 127.0.0.1:8443:8443 -v "${PWD}:/root/project" codercom/code-server code-server --allow-http --no-auth`

after that open the terminal and type `apt-get install php`
