### ISSUE TITLE
Extensions details are not displayed

### ISSUE THREAD

**Issue by ChristianWeyer** [cdr/code-server#323]
When searching for extensions in the marketplace and trying to read the Details pane, nothing is shown. For any extension, that is.#

E.g.:
![image](https://user-images.githubusercontent.com/888718/54862719-14dfcb00-4d3f-11e9-9321-bd59b6d34998.png)

**Comment by ab00a** [comment]
It's caused by the server settings that are hosting the app blocking iFrame displays (https://github.com/codercom/bugs/issues/360)

**Comment by code-asher** [comment]
This should be resolved in v2. We had some CSP issues in v1 but they're all resolved now.

**Comment by DAddYE** [comment]
This is happening for me on latest master and Safari on Catalina.

**Comment by code-asher** [comment]
Yeah unfortunately they don't show up on Safari at the moment. We're tracking it here: https://github.com/cdr/code-server/issues/1317
