### ISSUE TITLE
Cannot launch IDE after deleting workspace

### ISSUE THREAD

**Issue by joanrieu** [cdr/code-server#324]
- `code-server` version: https://ide.coder.com (now unusable for me due to that bug)

## Description

If the current workspace folder does not exist (because it has been deleted), the IDE crashes when starting. The result is an empty black page and there is no way to change/reset the workspace.

## Steps to Reproduce

1. Create a folder.
2. Open that folder as workspace.
3. Run `rm -rf /that/folder` in the terminal.
4. Refresh the page.
5. Ta-da: everything is broken.

## Logs

```
INFO   Loading IDE
INFO   Starting socket [1/5]...
INFO   Connected to socket
INFO   Start workbench
ERROR  Failed "Start workbench" duration=760ms
ERROR  Unexpected window configuration without backupPath
WARN   Load completed with errors duration=2560ms

Uncaught Error: ENOENT: no such file or directory, stat '/projects/something-I-deleted'
```

**Comment by UizzUW** [comment]
As a temporary workaround until this gets fixed, clear your browser's Local Storage. That is where the active workspace path is cached.

In Chrome : Chrome devtools -> Application tab -> Local Storage -> ide.coder.com -> delete all key-value pairs there.

**Comment by joanrieu** [comment]
That worked, thanks. 👍
