### ISSUE TITLE
Lando commands fail silently when run from a code-server terminal

### ISSUE THREAD

**Issue by tanc** [cdr/code-server#3306]
## OS/Web Information

- Web Browser: Edge, Safari (iOS)
- Local OS: Windows, iPadOS
- Remote OS: Windows 10
- Remote Architecture: WSL2 running Ubuntu 20.04, ZSH (same issue with Bash)
- `code-server --version`: `3.9.3 fe2dc2deb08e378069891b622bb62ad1d261d1b1`

## Problem description

For reasons I don't understand, a single specific terminal command won't run (silently fails) when executed under code-server's terminal. This does not happen in the 'normal' terminal and does not happen in VS Code's terminal. They are all using exactly the same system (confirmed but entering a command in one, then cycling back through the history in another and confirmed the same commands are executed).

## Steps to Reproduce

1. [Install Lando](https://docs.lando.dev/basics/installation.html#linux)
2. Run `lando version` in any terminal (except the terminal of code server) and confirm there is output
3. Open code server and enter `lando version` in the terminal and confirm there is no output

## Expected

Terminal should output:

```bash
$ lando version
$ v3.1.2
```

## Actual

There is no output after running the command:

```bash
$ lando version
```

An exit code of `4` is shown if `$?` is entered afterwards

## Logs

I ran:

`code-server --log debug`
and entered the command in the terminal.

    1. The most recent files from ~/.local/share/code-server/coder-logs - **There are two files here (stderr, stdout), both empty.**
    2. The browser console. **Attached in logs.zip below**
    3. The browser network tab. **Attached in logs.zip below**

[logs.zip](https://github.com/cdr/code-server/files/6439356/logs.zip)

## Screenshot

`lando version` in the WSL2 terminal:
![image](https://user-images.githubusercontent.com/76320/117404409-2fb72e80-af0a-11eb-94c6-843aab0bd8bf.png)

`lando version` in the code-server terminal:
![image](https://user-images.githubusercontent.com/76320/117404586-773dba80-af0a-11eb-9269-8286d161df2e.png)

## Notes

This issue can be reproduced in VS Code: **No**, the issue does not happen in VS Code.

**Comment by jsjoeio** [comment]
Okay here are the steps I took to reproduce using macOS + Chrome:
1. Install Lando v3.1.2 via the dmg file
2. Open Terminal (macOS default)
3. Run `lando version`

![image](https://user-images.githubusercontent.com/3806031/117487328-cb9f6500-af1f-11eb-8918-b065a383858e.png)


Now, with code-server:
1. Run `code-server --auth none` (code-server 3.9.3 fe2dc2deb08e378069891b622bb62ad1d261d1b1)
2. Open localhost:8080/ in Chrome
3. Open Integrated Terminal
4. Run `lando version`

![image](https://user-images.githubusercontent.com/3806031/117487511-086b5c00-af20-11eb-94ca-03f13d99f006.png)

Actually...none of the Lando commands are working 🤔 That's very strange. 

## Lando Docs

Looking a bit further into this, I see these two messages:

> If you do not run most of these commands in a directory that contains a Landofile you will likely not get the expected result.

> Windows users must use a real, non-emulated, TTY
> This is an upstream "restriction" imposed on us by NodeJS and python. We recommend using the shell shipped with Git for Windows but only the cmd.exe variant NOT the one powered by minTTY. That said your safest bet is to use cmd.exe or PowerShell. Other shells may work but have not been tested.
>
> If your shell does not work you will likely see an error message like the input device is not a TTY. See https://github.com/nodejs/node/issues/3006

I don't think that's related but adding here just in case.

Source: [Lando CLI docs](https://docs.lando.dev/basics/usage.html#cli-usage)

Hard to tell if this is specific to code-server or Lando. Let's see if @code-asher or @oxy has any input.

**Comment by jsjoeio** [comment]
Thanks for leaving such clear instructions! It is very strange. I would think it would at least log an error or something. I'm really unsure of what could be happening. Hopefully the others have an idea.

**Comment by tanc** [comment]
I've added a bug report in the Lando repo to cross reference this issue: lando/lando#3000
Also updated the issue title as I think it is specific to Lando.

**Comment by oxy** [comment]
Thanks for the instructions! I just attempted to reproduce it on my Linux build, and it works perfectly fine on both 3.9.3 and on `main` (which should be 3.10.0 by Monday). I feel like this might be macOS-specific too.

**Comment by tanc** [comment]
Thanks for testing! Interesting... I'm doing this in a Linux environment, using WSL2, so I don't think it's MacOS specific. I'll see if I can test (what will be) 3.10.0 version

**Comment by oxy** [comment]
That's curious - the only thing that differed for me was that I was using lando from git instead of the `.rpm` package because I can't really put `docker-ce` in the toolbox container I use for dev :thinking:

Does using lando from git instead of a release change anything?

**Comment by tanc** [comment]
Ah yes, running the version from git works!

Steps:
1. git clone https://github.com/lando/lando.git
2. cd lando
3. yarn install
4. Open code server terminal and cd to lando repo
5. `cd bin`
6. ./lando.js version

```
./lando.js version
v3.1.2
```

**Comment by oxy** [comment]
That's interesting - looking at commit logs nothing really changed after `v3.1.2` was released besides some documentation... :thinking:

**Comment by tanc** [comment]
Yes I don't think it's lando code itself... I'm just trying different tags to see if any don't work. I suspect its something about the way its packaged and installed but no idea why that would be an issue at this point.

Confirmed, running off different tags from the source (and doing a yarn install to be sure) doesn't seem to make any difference, the tagged version is correctly displayed in code-server's terminal.

**Comment by tanc** [comment]
I've updated the issue on the Lando side, lets see what the maintainers think over there. A very curious issue!
