### ISSUE TITLE
Multiple User Usage Problem

### ISSUE THREAD

**Issue by berkayyildi** [cdr/code-server#3313]
Hi,

When you have a hosting panel like cpanel or plesk. It creates user for each domain for security reasons.

I mount 2 or more different directory for docker to edit different user's files. I need to edit both so I have to start vscode-server as root.

But at this point when I create new file or folder, its owner becomes root.

The correct way to handle this problem should be;

Setting each directory to user.
For example: /home/domain1 -> www-data1
                     /home/domain2 -> www-data2

Also starting vscode as root or setting 0777 is a security risk even if you have password.
With this technique you just pass vscode available users and directories and vscode automatically set the user for directories.

To explain situation I suggest changing uid but, I know changing process' user is not easy, so instead of changing vs-code real uid. Creating extension might be more useful. 
Extension just execute chown by directory after creating file. (Vscode running as root right now)

Do you have any solution for multi user usage of vscode-server.

Thanks.

**Comment by jsjoeio** [comment]
Hey @berkayyildi - I'd like to get some clarification. I see you mentioned vscode-server multiple times. This is code-server. Are you perhaps confusing it with [vscode-remote](https://github.com/microsoft/vscode-remote-release)?

**Comment by berkayyildi** [comment]
Actually I am talking about this: https://hub.docker.com/r/linuxserver/code-server . 
I have never use vscode-remote, probably it does not have this kind of problem because it already logins with different ssh users.
But vscode web version starts with single user like root, this is the problem.

**Comment by jsjoeio** [comment]
Oh! That's a community maintained project. I suggest you open the issue with them and hopefully they can help! 

https://github.com/linuxserver/docker-code-server/issues/new/choose

**Comment by code-asher** [comment]
I think using groups to manage permissions should be able to resolve this. You'll probably want to use `chmod g+s` to ensure the group is inherited for new files.

https://superuser.com/questions/277775/ensuring-new-files-in-a-directory-belong-to-the-group
