### ISSUE TITLE
error [Service Worker] registration: Failed to register a ServiceWorker: The provided scope ('https://sample.com/user/xx-xx%5C%2C%20xx/codeserver/') or scriptURL ('https://sample.com/user/xx-xx%5C%2C%20xx/codeserver/static/xxxxx/usr/lib/code-server/dist/serviceWorker.js') includes a disallowed escape character.

### ISSUE THREAD

**Issue by vMahidhar** [cdr/code-server#3316]
## OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

## Steps to Reproduce

1.
2.
3.

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by oxy** [comment]
Can you please fill in the issue template?
