### ISSUE TITLE
Unable to get multiple repositories to show up in Source Control

### ISSUE THREAD

**Issue by gogobd** [cdr/code-server#3321]
## OS/Web Information

- Web Browser: Safari
- Local OS: macOS Big Sur
- Remote OS: docker
- Remote Architecture: i5
- `code-server --version`: 3.9.3 fe2dc2deb08e378069891b622bb62ad1d261d1b1

## Steps to Reproduce

1. `git clone https://github.com/cdr/code-server.git && cd code-server && mkdir subdir && cd subdir && git clone https://github.com/zopefoundation/Zope.git`
2. click Source Control
3. click Views / Source Control Repositories

## Expected

Both code-server and Zope repositories should be available in Source Control

## Actual

Only code-server repository is available

## Logs

I wasn't trying to retrieve any logs yet.

## Screenshot

<img width="1680" alt="Screenshot 2021-05-08 at 02 09 27" src="https://user-images.githubusercontent.com/728976/117519070-7fe1cf80-afa2-11eb-8b9e-a47ab276f802.png">

## Notes

That's the Dockerfile I was using

```
FROM debian:buster-slim

ENV SHELL /bin/bash
  
# Install system dependencies
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    wget \
    git \
    screen \
    unzip \
    vim \
    procps \
    locales \
    python3-pip \
 && apt-get clean

# Python unicode issues
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

# https://github.com/cdr/code-server
## Code server
RUN mkdir -p ~/.local/lib ~/.local/bin
RUN curl -sfL https://github.com/cdr/code-server/releases/download/v3.9.3/code-server-3.9.3-linux-amd64.tar.gz | tar -C ~/.local/lib -xz
RUN mv ~/.local/lib/code-server-3.9.3-linux-amd64 ~/.local/lib/code-server-3.9.3
RUN ln -s ~/.local/lib/code-server-3.9.3/bin/code-server ~/.local/bin/code-server
RUN PATH="~/.local/bin:$PATH"

# Fix broken python plugin # https://github.com/cdr/code-server/issues/2341
RUN mkdir -p ~/.local/share/code-server/ && mkdir -p ~/.local/share/code-server/User && echo "{\"extensions.autoCheckUpdates\": false, \"extensions.autoUpdate\": false}" > ~/.local/share/code-server/User/settings.json 
RUN curl -sfLO https://github.com/microsoft/vscode-python/releases/download/2020.10.332292344/ms-python-release.vsix \
 && ~/.local/bin/code-server --install-extension ./ms-python-release.vsix || true

WORKDIR /app
CMD ~/.local/bin/code-server --bind-addr 0.0.0.0:8080 /app

# docker build -t vscs .
# docker run -p 8080:8080 -it -d vscs
# docker exec -it <dontainer_id> cat /root/.config/code-server/config.yaml
```

This issue can be reproduced in VS Code: I think Yes

**Comment by jsjoeio** [comment]
## Steps followed to reproduce

Here's what I did to reproduce (macOS Big Sur + Chrome + code-server 3.9.3 running locally)
1. `mkdir two-sources && git clone https://github.com/jsjoeio/awesome-interactive-course-platforms.git && git clone https://github.com/jsjoeio/typescript-concepts-and-examples.git`
2. start code-server `code-server --auth none`
3. Open `two-sources` inside code-server
4. make a change in each repo without committing

## Actual

Both repositories show up in Source Control

![image](https://user-images.githubusercontent.com/3806031/117700640-21bc1480-b17b-11eb-86e0-e276b3006ccc.png)

## Next Steps

> This issue can be reproduced in VS Code: I think Yes

If this can be reproduced upstream, then it's not specific to code-server and should be filed upstream.

**Comment by jsjoeio** [comment]
If you think this was closed by mistake or it can be reproduced another way, please reply here and we'll reopen and take a look!
