### ISSUE TITLE
Java Test Report expanding/collapsing tests opens up a new blank page tab on each click

### ISSUE THREAD

**Issue by MxD-js** [cdr/code-server#3324]
## OS/Web Information

- Web Browser: Chrome/Brave/Firefox
- Local OS: Mac OS X Catalina, Windows 10
- Remote OS: Ubuntu 20.04
- Remote Architecture: Clean install of Ubuntu and code-server, not dockerized.
- `code-server --version`: 3.9.3

## Steps to Reproduce

1. Install java extensions pack form market place (microsoft market place, install manually)
2. run a java test, after java test report comes up, attempt to expand the failed test to reveal the failed reason
3. when clicking on to expand the failed tests, a separate tab opens with with a link to a blank page. 

## Expected

Expanding/Collapsing tests in the report should'nt open a web page that leads no where.
## Actual

A separate tab opens up on each click to collapse/expand a test result. This does not happen in the official msft vscode desktop release, only on code-server.
## Logs

1. The most recent files from ~/.local/share/code-server/coder-logs = Logs are empty, (code-server-stderr.log) and (code-server-stdout.log) files are empty. 

2. The browser console, 
![image](https://user-images.githubusercontent.com/60336163/117547324-e1765e00-afe3-11eb-861a-c52f7c07555a.png)

3. The browser network tab.
![image](https://user-images.githubusercontent.com/60336163/117547364-15ea1a00-afe4-11eb-83c0-ee31fea4bd09.png)

## Screenshot

https://user-images.githubusercontent.com/60336163/117546486-80e52200-afdf-11eb-9918-9432f3ed2c6b.mov

## Notes

Not reproducible in vanilla vscode, works as expected. 
This issue can be reproduced in VS Code: No.

**Comment by MxD-js** [comment]
The link is coming from the "Navigate to Source" Button on the right of each test 
![image](https://user-images.githubusercontent.com/60336163/117762174-80b27580-b1dd-11eb-85ca-0d1e37a60795.png) 
but it spans the entire collapsible test.  Clicking on the navigate to source button also opens the same window with the same URL.

**Comment by jsjoeio** [comment]
Thanks for the extra details @MxD-js ! We'll have to investigate this further.

**Comment by MxD-js** [comment]
I've done some further digging and revering to version 0.27.0 of the extension fixes this issue. I then installed 0.28.0 and issue came back. So something about the changes in 0.28.0 and later versions produces this error. 

![image](https://user-images.githubusercontent.com/60336163/118415470-5cccb500-b65f-11eb-8e84-e19af37f2c66.png)
