### ISSUE TITLE
Terminal Persistence strips terminal names

### ISSUE THREAD

**Issue by ThatCodingGuy8** [cdr/code-server#3340]
## OS/Web Information

- Web Browser: Opera GX
- Local OS: Windows 10
- Remote OS: Ubuntu 20.04
- Remote Architecture: 64-bit
- `code-server --version`: 3.10.0

## Steps to Reproduce

1. Make multiple terminals
2. Rename one or all of them
3. Reload the page
4. Names are now invisible

## Expected
The names persist and continue showing

## Actual
The names disappear and become invisible (buttons can still be clicked although invisible). Its worth noting the actual name resets too, for example back to "bash" on reload and then turns invisible

## Screenshot
https://brandentheprogrammer.is-terrible.com/wI5eJY.png

## Notes

This issue can be reproduced in VS Code: Unsure

**Edit by @code-asher:** invisible names might require enabling terminal tabs first, see https://github.com/cdr/code-server/issues/3454.

**Comment by marsinearth** [comment]
After upgrade to v3.10.0, terminal went blank. I'm running it on AWS Linux 2 and client is iPadOS 14.5

**Comment by jsjoeio** [comment]
@marsinearth please open a separate bug report issue!

**Comment by code-asher** [comment]
This should be fixed in 4.0.0.
