### ISSUE TITLE
terminal text unreadable after page load, since update to 3.10

### ISSUE THREAD

**Issue by fuse314** [cdr/code-server#3346]
## OS/Web Information

- Web Browser: Brave Version 1.24.82 Chromium: 90.0.4430.93 (Official Build) (64-Bit)
- Local OS: Windows 10
- Remote OS: Linux (Docker image)
- Remote Architecture: x64
- `code-server --version`: 3.10.0 f9b6d04cab0463c487e0390fc73e902e1f83a99e

## Steps to Reproduce

1. Load code-server webpage
2. Open terminal window
3. => Unreadable Text
4. Open settings
5. Change terminal font size
6. => Readable Text

## Expected

Terminal window text should be displayed correctly

## Actual

Every character of the terminal window text is clipped on the right and bottom side

## Logs

![image](https://user-images.githubusercontent.com/927896/117815098-63c18500-b265-11eb-80a8-6f1a7a266458.png)
![image](https://user-images.githubusercontent.com/927896/117815469-cdda2a00-b265-11eb-91a8-0be119a5d12e.png)

## Screenshot

![code-server_terminal](https://user-images.githubusercontent.com/927896/117814140-3a542980-b264-11eb-85cf-ccdf0cf03f2d.gif)

## Notes

The issue does not occur in Google Chrome and Microsoft Edge (Chromium) browsers.

This issue can be reproduced in VS Code: No

**Comment by AndreiJirohHaliliDev2006** [comment]
Also @fuse314, can you add the link to the Chromium bug tracker related to this issue at the issue description?

**Comment by AndreiJirohHaliliDev2006** [comment]
The issue can be also reproduced on Microsoft Edge, as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/34998342/117986497-44f9e600-b36c-11eb-96db-cc6d6d364cd3.png)

<details>

<summary>Debugging info</details>

**Browser version**: Microsoft Edge 89.0.774.77 (Official build) (64-bit)
**Local OS**: Windows 10 Version 20H2 (OS Build 19042.928)
**Remote OS**: Linux (Docker container hosted on Divio, formerly Aldryn)
**Remote Archeitechure**: x86_64
**`code-coder` Version**: 3.10.0 f9b6d04cab0463c487e0390fc73e902e1f83a99e

</details>

**Comment by AndreiJirohHaliliDev2006** [comment]
> The issue can be also reproduced on Microsoft Edge, as shown in the screenshot below.
> 
> ![image](https://user-images.githubusercontent.com/34998342/117986497-44f9e600-b36c-11eb-96db-cc6d6d364cd3.png)
> 
> Debugging info
> **Browser version**: Microsoft Edge 89.0.774.77 (Official build) (64-bit)
> **Local OS**: Windows 10 Version 20H2 (OS Build 19042.928)
> **Remote OS**: Linux (Docker container hosted on Divio, formerly Aldryn)
> **Remote Archeitechure**: x86_64
> **`code-coder` Version**: 3.10.0 [f9b6d04](https://github.com/cdr/code-server/commit/f9b6d04cab0463c487e0390fc73e902e1f83a99e)

I may need to check if the bug is still there on Edge/Chrome 90+ after installing the update.

**Comment by cstrat** [comment]
I am also having this issue, pretty much identical setup. (running on Docker on a server, using Brave as my browser)

Thanks @fuse314, I didn't realise changing the font-size would help fix it (even if its just for that session). Better than squinting... 😆

**Comment by fuse314** [comment]
I found this ticket upstream:
https://github.com/brave/brave-browser/issues/14918

If I allow fingerprinting for my domain, the text is rendered correctly.

To fix this:
1. Click on "Brave Shield" logo
2. Under "Fingerprinting", select "Allow fingerprinting"
3. Enjoy

**Comment by jsjoeio** [comment]
Woo! Glad you found it filed upstream and posted the fix/workaround. Thanks @fuse314 !

**Comment by cstrat** [comment]
Amazing, thanks!

**Comment by antofthy** [comment]
I am also having this issue....

![capture_2021-06-02_15-49-22](https://user-images.githubusercontent.com/1214656/120432830-d08bf300-c3bd-11eb-97ce-f9f27bb87cbe.png)

 I was able to fix it by copying the font family settings from  
    Text Editor-> Font -> Font Family
  In to the terminal font family settings
    Features->Terminal -> Font Family
  resulting in..
  
![capture_2021-06-02_16-04-39](https://user-images.githubusercontent.com/1214656/120432994-12b53480-c3be-11eb-9f69-3797a5ab8791.png)

 Of course according the description (visible in the last image) code-server is supposed to do that automatically!   It just didn't happen!

**Comment by jsjoeio** [comment]
If you've having issues, please open a separate bug report! Thank you!
