### ISSUE TITLE
When using code-server's subdomain proxy with authentication, the login screen registers code-server's service worker for the subdomain

### ISSUE THREAD

**Issue by rabidpug** [cdr/code-server#3365]
## OS/Web Information

- Web Browser: Chrome / Safari
- Local OS: macOS
- Remote OS: Arch Linux
- Remote Architecture: amd64
- `code-server --version`: 3.10.0 6610bff3216c48fdd0884191338b1092765dbb5a

## Steps to Reproduce

1. Access a proxied port and log in (EG 3000.domain.com)
2. You can see in dev tools that code-server's service worker has been registered

## Expected

Service worker shouldn't be registered by the login page when accessing a proxied port

## Actual

Service worker is registered

## Screenshot

EG, Vite not liking the service worker being registered when accessing a svelte app on 3000.mydomain.tld:

<img width="922" alt="Screen Shot 2021-05-12 at 15 33 04" src="https://user-images.githubusercontent.com/27880212/117924120-9a1c0480-b338-11eb-8b7b-25ea1f584446.png">

## Notes

This issue can be reproduced in VS Code: N/A

**Comment by code-asher** [comment]
Maybe we have to add the full URL to the `scope`? We only put the path so maybe it gets registered for all sub-domains as well.
