### ISSUE TITLE
Unable to open '<filename>': Unknown encoding: iso88591.

### ISSUE THREAD

**Issue by Muruloki** [cdr/code-server#338]
- `code-server` version: code-server-1.32.0-310-linux-x64
- OS Version: Ubuntu 16.04.6 LTS

## Description

Changing encoding for a single file using UI to iso88591 (by clicking on encoding in right bottom corner and choosing "reopen with....") works fine. However when i try to set default encoding for all files in settings 

`Files: Encoding
The default character set encoding to use when reading and writing files. This setting can also be configured per language.
`

then i get this error message when i try to switch back to any opened file:

`Unable to open '<filename>': Unknown encoding: iso88591.`

The only way to fix this is to set it back to utf-8.

**Comment by nol166** [comment]
@Muruloki How did you get it to save with that encoding? As soon as I changed my file to that format it failed to save and threw this error `Failed to handle server message`. Did you see that at all?

**Comment by nol166** [comment]
I also tried locally in native VSCode and it seemed to revert the encoding to UTF8

**Comment by Muruloki** [comment]
@nol166 

You are right, i wasn't looking at console output. So even using UI the moment i switch to iso88591 i get this in console:
![image](https://user-images.githubusercontent.com/48758424/55021641-85048000-4fcf-11e9-85e1-dae3eee3f8d8.png)

And after trying to save i get this:
![image](https://user-images.githubusercontent.com/48758424/55021666-92ba0580-4fcf-11e9-8ac7-46a7a93b707f.png)


So it just fails but if you don't pay attention to console it fails silently. However if you try to change encoding for all file via settings you will see vscode error message in the bottom right corner.

**Comment by nol166** [comment]
@Muruloki Yeah that is definitely a bug. We will get this fixed.

**Comment by code-asher** [comment]
I tested this out in v2 and it appears to work. :confetti_ball:
