### ISSUE TITLE
E2E Tests

### ISSUE THREAD

**Issue by kylecarbs** [cdr/code-server#339]
Should run E2E tests on the compiled binary.

Works as expected:
- [ ] `--port` flag
- [ ] `--password` flag
- [ ] `--allow-http` flag
- [ ] `--no-auth` flag
- [ ] Can load in successfully.
- [ ] Can open file
- [ ] Can create file
- [ ] Can delete file
- [ ] Can install extension
- [ ] Can uninstall extension
- [ ] Can debug JavaScript file

**Comment by nhooyr** [comment]
We can do this at some later point.
