### ISSUE TITLE
Git Graph extension partially broken

### ISSUE THREAD

**Issue by asomethings** [cdr/code-server#3399]
## OS/Web Information

- Web Browser:
- Local OS: Windows 10 19041.985 / macOS Big Sur 11.2.3
- Remote OS: Ubuntu 20.04.1 LTS
- Remote Architecture: x86_64
- `code-server --version`: 3.10.0

## Steps to Reproduce

1. Download / Install Git Graph Extension
2. Open Git Graph page and open another file inside code-server
3. Open Git Graph again

## Expected

Git Graph should load beautifully every time

## Actual

Git Graph loads perfectly first time but loads without css/js after coming back from another tab

## Logs

Network tab shows Git Graph css/js is pending
![code-server](https://user-images.githubusercontent.com/16171942/118400041-f49bc480-b69a-11eb-9f32-81f0c10587cf.PNG)

## Screenshot
![gif_image.gif](https://user-images.githubusercontent.com/16171942/118399963-a686c100-b69a-11eb-80dd-3462133910a6.gif)

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Apologies, @asomethings I'm not super familiar with Git Graph. I just tested it with the latest version of code-server — 3.10.1 — and I can't seem to understand what is broken or wrong. Could you please elaborate? 

## Screenshot

https://user-images.githubusercontent.com/3806031/118702942-63c40680-b7ca-11eb-9f7b-7bc345a49122.mov

I even tried to compare it between code-server and VS Code

### code-server 
![image](https://user-images.githubusercontent.com/3806031/118703128-98d05900-b7ca-11eb-840d-b5848ffecc47.png)


### VS Code
![image](https://user-images.githubusercontent.com/3806031/118703117-953cd200-b7ca-11eb-9dae-714762847262.png)

**Comment by asomethings** [comment]
@jsjoeio Thanks for fast feedback. I assume few extension was crashing with Git Graph. I did some reinstallation it got fixed. Sorry for bothering closing issue.

**Comment by jsjoeio** [comment]
No worries at all. Thanks for the quick reply. Glad it's all fixed now! 🎉
