### ISSUE TITLE
Scrolling with iPad Pro Magic Keyboard Touchpad Does Not Work

### ISSUE THREAD

**Issue by ambroselittle** [cdr/code-server#3405]
## OS/Web Information

- Web Browser: iPad Safari
- Local OS: iPad OS 14.4.2
- Remote OS: Debian GNU/Linux 10 (buster)
- Remote Architecture: Azure Dev/Test B2 Plan VM Running bencdr/code-server-azure:latest image
- `code-server --version`: 3.9.0 (VS Code 1.52.1)

## Steps to Reproduce

1. Open a (long) code file on an iPad with attached Magic Keyboard (that has the trackpad)
2. Try to use scroll on trackpad (2 fingers).

## Expected
Scrolling

## Actual

Nothing

## Logs

N/A (I think)

## Screenshot

Not much to see except the file is not scrolling. :) 

## Notes

I can access the same deploy in Chrome on Mac, and it scrolls fine. I assume it is not listening for the "right" events to capture the trackpad scrolling maybe?

This issue can be reproduced in VS Code: No - because I can't run Code on iPad. Is why I am trying to get this going. :)

**Comment by jsjoeio** [comment]
This was an upstream issue in Safari and fixed in the latest version of iPadOS 14.5 when you use an app as a PWA/add to home screen. To fix:
1. Upgrade your iPadOS to 14.5
2. Open your code-server deployment in Safar
3. Click "Add to homescreen"

See: https://github.com/cdr/code-server/issues/1455#issuecomment-828781910

**Comment by ambroselittle** [comment]
@jsjoeio, confirmed fix. Sorry. I normally keep my stuff up to date and forgot the latest is 14.5 now. Turns out this iPad was having an issue where it never loaded on the software update screen, so I wasn't being notified. I had to reboot it, once you pointed out I was not on latest. Anyhow, it works now. Easy fix! :D

**Comment by jsjoeio** [comment]
No worries at all. Glad it was any easy fix :D
