### ISSUE TITLE
Bot submits Homebrew PRs on the wrong base

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#3407]
I think it might be because `brew bump-formula-pr`  is basing it off cdrci's fork which is outdated. Perhaps there is a flag to pull the latest changes into the fork first or maybe we'll have to do it before running `brew`.

**Comment by jsjoeio** [comment]
## Notes

The way this currently works is we use `brew bump-formula-pr` using @cdrci's GitHub Token (environment variable). 
The docs for `brew bump-formula-pr`: https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb#L18

**Comment by jsjoeio** [comment]
This is because cdrci/homebrew it out of date, right? So why don't we just add some commands to the script:
- checkout cdr/hombrew 
- pull remote changes
- update fork
- run brew bump-formula step

This could work.
