### ISSUE TITLE
TSLint extension not working

### ISSUE THREAD

**Issue by njbraun** [cdr/code-server#341]
- `code-server` version: 1.32.0-310
- OS Version: Ubuntu 18.04 and/or using the dockerized version

## Description

TSLint extension does not appear to work with code-server.  I don't see any in-editor warnings/errors for things that violate the specified tslint rules.  See repro steps below.

Extension: ms-vscode.vscode-typescript-tslint-plugin

*Side Note:* The download count is VERY different for this extension in code-server vs vscode.  This extension shows ~30 downloads in code-server versus ~400,000 downloads in vscode.  Are these coming from different repos??

## Steps to Reproduce

1. Create a new tslint project via running `tslint --init`.
1. Modify tslint.json to add a rule about quotes for example:
```
{
    "defaultSeverity": "error",
    "extends": ["tslint:recommended"],
    "jsRules": {},
    "rules": {
        "quotemark": [true, "single"]
    },
    "rulesDirectory": []
}
```
3. Create a file `example.ts`:
```
let foo = "bar";
```
4. Note that tslint does not complain about the double quotes.

**Comment by nol166** [comment]
@njbraun we have our own extension marketplace because of Microsoft's TOS. I believe this is why the downloads are different.

**Comment by nol166** [comment]
@njbraun Could it because of the trailing comma in your JSON after the `quotemark` key-value pair?

**Comment by nol166** [comment]
```
module.js:562
    throw err;
    ^

Error: Cannot find module '/Users/user/Documents/coder-stuff/js/code-server/packages/server/-e'
    at Function.Module._resolveFilename (module.js:560:15)
    at Function.Module._load (module.js:487:25)
    at Function.Module.runMain (module.js:726:10)
    at startup (bootstrap_node.js:207:16)
    at bootstrap_node.js:628:3
```

**Comment by njbraun** [comment]
@nol166 That was a copy/paste error. Fixed the trailing comma, but yes you are correct, tslint still doesn't work.

**Comment by foresthoffman** [comment]
There is no `-e` module within code-server, or npm AFAIK, so this is extremely odd.

**Comment by njbraun** [comment]
I'm no longer able to repro this on the latest version of code-server. Fixed?

**Comment by foresthoffman** [comment]
@njbraun sweet! Closing.
