### ISSUE TITLE
Cannot run on Alpine on WSL2

### ISSUE THREAD

**Issue by parsalotfy** [cdr/code-server#3413]
## OS/Web Information

- Web Browser: Edge
- Local OS: Windows 10 build 21382.1
- Remote OS: Windows 10 build 21382.1
- Remote Architecture: x64
- `code-server --version`: 3.10.1

## Steps to Reproduce

1. Install Alpine from windows store (Alpine v3.13)
2. install curl on that Alpine : `apk add curl`
3. run this command : `curl -fsSL https://code-server.dev/install.sh | sh`
4. `cd ~/.local/bin`
5. `./code-server`

## Actual

then this error appears : 

```
DESKTOP-87K2O5K:~/.local/bin# ./code-server
./code-server: exec: line 36: /root/.local/lib/code-server-3.10.1/lib/node: not found
```

Any ideas ?

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by code-asher** [comment]
Our releases don't work on Alpine, I think for now you'll have to use `yarn` or `npm` to install.

**Comment by code-asher** [comment]
But we should modify the installation script to detect this.

**Comment by jsjoeio** [comment]
Yeah, this is mentioned in the install docs [here](https://github.com/cdr/code-server/blob/main/docs/install.md#yarn-npm).

> But we should modify the installation script to detect this.

Agreed!

**Comment by jsjoeio** [comment]
Closing in favor of https://github.com/cdr/code-server/issues/3421

**Comment by parsalotfy** [comment]
Please add alpine to your releases, current docker image runs on ubuntu and its size is more than 188 mb
Alpine is much more lightweight, I don't know why this great project isn't fully compatible with alpine
