### ISSUE TITLE
Fix install script to detect Alpine and suggest installing via npm/yarn

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#3421]
As a user running Alpine, the install script should exit and tell me to install using npm/yarn per [the docs](https://github.com/cdr/code-server/blob/main/docs/install.md#yarn-npm).

Related: 
- https://github.com/cdr/code-server/issues/3413
- https://github.com/cdr/code-server/discussions/2261
- https://github.com/cdr/code-server/discussions/2139

**Comment by jsjoeio** [comment]
Strangely after testing on Alpine 3.12 (iSH app on iPadOS), it works as expected.

https://user-images.githubusercontent.com/3806031/124200098-5b2d4400-da89-11eb-9a1d-27cca0dede7c.MP4

After chatting with @code-asher, it turns out if you're using 64 bit Alpine, it tries to install the standalone and fails

**Comment by cangetright** [comment]
Thanks I don’t know exactly what that means but my psycho ex-boyfriend may be using an iPhone 12. I’m using and 11 but all my stuff synced to him and I have a protective order he keeps violating. Would you happen to be able to tell if I’m hacked by him? I’m sure I am but remotely and every device I have whatever I get gets hacked
