### ISSUE TITLE
I Cannot install extensions, error 403

### ISSUE THREAD

**Issue by parsalotfy** [cdr/code-server#3433]
First time I ran code-server, I couldn't install extensions and bumped into 403 error.
Then I realized that Microsoft prevents vscode forks from accessing their marketplace.
Then I found [this](https://github.com/cdr/code-server/blob/main/docs/FAQ.md#how-do-i-configure-the-marketplace-url) in your docs and changed the configuration. But it didn't solved the problem.

## OS/Web Information

- Web Browser: Microsoft Edge
- Local OS: Windows 10 build 21382.1
- Remote OS: Debian 10 as Host machine , ubuntu as container os
- Remote Architecture: x64
- `code-server --version`: version-v3.10.1

## Steps to Reproduce

1. Run code-server using this docker command : 
``` sudo docker run -d --name=code-server -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -e PASSWORD=mypassword -e SUDO_PASSWORD=mypassword -p 8083:8443 -v /path/to/appdata/config:/config --restart unless-stopped ghcr.io/linuxserver/code-server ```

2. config marketplace : `sudo nano  /config/.config/code-server/product.json`
3. this is product.json :  ```
{
  "extensionsGallery": {
    "serviceUrl": "https://open-vsx.org/vscode/gallery",
    "itemUrl": "https://open-vsx.org/vscode/item"
  }
}   ```

4. save the file
5. go to extension panel in side bar
6. try to install some extensions

## Expected

I expect that I could install extensions without any problem as long as I had changed the marketplace and I'm not using Microsoft marketplace anymore

## Actual

It still gives me 403 error

## Screenshot
![image](https://user-images.githubusercontent.com/30390810/119100741-843fcb00-ba2d-11eb-81c2-8cc73e087b2c.png)

![image](https://user-images.githubusercontent.com/30390810/119100875-a46f8a00-ba2d-11eb-9f5b-ac61af7740e4.png)

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by code-asher** [comment]
The `product.json` file is bundled with code-server; I don't believe it's read from the config directory so adding a `product.json` there probably won't work.

You could edit the bundled `product.json` instead (you will also need to restart code-server if you do that) but I think it would be better to add the `SERVICE_URL` and `ITEM_URL` environment variables to your `docker run` command.

All that said, our default marketplace should work (we provide our own which is separate from Microsoft's) so I'm not sure what's going on. I was unfortunately not able to replicate locally.

But we want to phase it out and move to Open VSX anyway so if you are able to do that now that'd be the best solution.

**Comment by parsalotfy** [comment]
Thank you for answering, I will test setting environment variables in docker run and report the result here.

**Comment by parsalotfy** [comment]
Thank you, I should have set environment variables before running the container.
Changing config file and environment variables after running does not work.

**Comment by sathishkumar-p** [comment]
Hi,
I am facing the same error, i tried to add both env
```
            - name: SERVICE_URL
              value: https://open-vsx.org/vscode/gallery
            - name: ITEM_URL
              value: https://open-vsx.org/vscode/item
```
Still, same issue not helped
