### ISSUE TITLE
Move "Publishing a release" to MAINTAINING.md

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#3441]
Right now, this section of the docs lives in `ci/README.md` and it's hard to find. It would make more sense to put in `MAINTAINING.md`

**Comment by Prashant168** [comment]
[MAINTAINING.md](https://github.com/cdr/code-server/files/6533249/MAINTAINING.md)
Kindly Check to see if your issue is resolved with this change.
#

**Comment by Prashant168** [comment]
I want to work on this , Sir

**Comment by jsjoeio** [comment]
We would be grateful for your help! @Prashant168 I'll assign this to you.

Let me know if you need any help/clarification.

**Comment by Prashant168** [comment]
I am a beginner to Open Source. So ,sorry but after I pulled the request for the issue, I got an email stating a linked error. can you please elaborate if this is some error that I have generated and how to remove it 
![WhatsApp Image 2021-05-26 at 20 16 47]
![error](https://user-images.githubusercontent.com/61613428/119707557-e9098400-be78-11eb-8396-50e2803869eb.jpeg)

**Comment by code-asher** [comment]
It looks like you need to run `yarn fmt`. I think it's erroring because there's an extra blank line.
