### ISSUE TITLE
Update C#/Omnisharp extension

### ISSUE THREAD

**Issue by vimota** [cdr/code-server#345]
- `code-server` version: latest
- OS Version: Linux VM
- Extension: C#

## Description

I'm having issues with the C# extension when running code-server in docker. Even after installing dotnet in the docker container, the extension/omnisharp has issues picking up the right MSBuild directory. I also noticed that the C# extension is out of date, and perhaps these issues may be resolved by updating!

**Comment by NGTmeaty** [comment]
@foresthoffman may be able to help you.

**Comment by foresthoffman** [comment]
@vimota What errors are you seeing in the developer console?

**Comment by vimota** [comment]
It was an issue with dotnet CLI not being installed. I created a Docker image based on code-server that pre-installs the necessary CLI: https://gist.github.com/vimota/14bc6349f6cce30bdd022a5e2ef1abbc.

From there I'm able to:
1. Install Omnisharp
2. Omnisharp starts up and seems to complete restoring project but when you go to a C# file in the project there's hundreds of errors and import issues.
3. In the terminal, you run `dotnet restore <path/to/solution.sln>`.
4. You refresh the page, and on this run omnisharp will pick up all the definitions and cross references, and allow running tests.

It's far from ideal but this setup at least works. Perhaps updating the extension will resolve step 2-4?

**Comment by nhooyr** [comment]
See #1299
