### ISSUE TITLE
Terminal Background with Custom Font and Theme

### ISSUE THREAD

**Issue by kaaax0815** [cdr/code-server#3456]
## OS/Web Information

- Web Browser: Edge 90.0.818.66
- Local OS: Windows 10 20H1
- Local VSCode: 1.56.2
- Remote OS: Ubuntu 20.04
- Remote Architecture: amd64
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

1. Install Theme https://github.com/cdr/code-server/issues/3455
2. Use Fira Code using Cloudflare Proxy https://github.com/cdr/code-server/issues/1374#issuecomment-597267861
3. Open Terminal

## Expected

The Terminal should be the Color of everything else

## Actual

Sometimes: 
![msedge_YuW9yzTWQV](https://user-images.githubusercontent.com/32197462/119349605-9ffdd800-bc9e-11eb-9c24-184c6e36718c.png)

When reoping Terminal:
![msedge_sf4SCfBV5t](https://user-images.githubusercontent.com/32197462/119349712-bc9a1000-bc9e-11eb-9f0c-d7383acd5aaf.png)

## Logs

To be addedd

## Screenshot

Theme in Full:
![msedge_JUg7XXWTeA](https://user-images.githubusercontent.com/32197462/119349802-e5baa080-bc9e-11eb-9b24-23f8169baf9e.png)

## Notes

This issue can be reproduced in VS Code: No

Same Theme, same Font in Vanilla VSCode
![Code_ULRKyepUQ5](https://user-images.githubusercontent.com/32197462/119350000-1b5f8980-bc9f-11eb-973c-1c68c9a099e2.png)

settings.json on Remote:
```json
{
    "workbench.colorTheme": "The Best Theme",
    "workbench.iconTheme": "material-icon-theme",
    "code-runner.executorMap": {
        "javascript": "node",
        "python": "python3",
    },
    "git.autofetch": true,
    "git.confirmSync": false,
    "git.enableSmartCommit": true,
    "editor.fontWeight": "400",
    "editor.fontSize": 16,
    "editor.fontLigatures": true,
    "editor.fontLigatures": null,
    "editor.fontFamily": "Fira Code",
    "terminal.integrated.shell.linux": "/usr/bin/fish",
    "terminal.integrated.fontWeight": "400",
    "terminal.integrated.fontSize": 14,
    "terminal.integrated.fontFamily": "Fira Code",
    "terminal.integrated.letterSpacing": 1.5
}
```
settings.json in Vanilla VSCode:
```json
{
    "tabnine.experimentalAutoImports": true,
    "git.autofetch": true,
    "git.confirmSync": false,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "python.languageServer": "Microsoft",
    "[javascript]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "git.enableSmartCommit": true,
    "workbench.iconTheme": "material-icon-theme",
    "editor.fontLigatures": true,
    "editor.fontFamily": "Fira Code",
    "editor.fontWeight": "400",
    "editor.linkedEditing": true
}
```

**Comment by hanc2006** [comment]
I have the same issue but I using **zsh shell**. If I switch to **sh shell** everything works fine, and color theme is applied.

**Comment by kaaax0815** [comment]
@hanc2006 I have this in my `settings.json`
```json
"terminal.integrated.defaultProfile.linux": "sh",
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "bash"
        },
        "zsh": {
            "path": "zsh"
        },
        "fish": {
            "path": "fish"
        },
        "tmux": {
            "path": "tmux",
            "icon": "terminal-tmux"
        },
        "pwsh": {
            "path": "pwsh",
            "icon": "terminal-powershell"
        },
        "sh": {
            "path": "/bin/sh"
        }
    }
```
but it still uses fish and not sh when starting shell

**Comment by hanc2006** [comment]
Hi @kaaax0815 , I have this settings:

```
"workbench.colorCustomizations": {
    "terminal.background": "#090300",
    "terminal.foreground": "#A5A2A2",
    "terminalCursor.background": "#A5A2A2",
    "terminalCursor.foreground": "#A5A2A2",
    "terminal.ansiBlack": "#090300",
    "terminal.ansiBlue": "#01A0E4",
    "terminal.ansiBrightBlack": "#5C5855",
    "terminal.ansiBrightBlue": "#01A0E4",
    "terminal.ansiBrightCyan": "#B5E4F4",
    "terminal.ansiBrightGreen": "#01A252",
    "terminal.ansiBrightMagenta": "#A16A94",
    "terminal.ansiBrightRed": "#DB2D20",
    "terminal.ansiBrightWhite": "#F7F7F7",
    "terminal.ansiBrightYellow": "#FDED02",
    "terminal.ansiCyan": "#B5E4F4",
    "terminal.ansiGreen": "#01A252",
    "terminal.ansiMagenta": "#A16A94",
    "terminal.ansiRed": "#DB2D20",
    "terminal.ansiWhite": "#A5A2A2",
    "terminal.ansiYellow": "#FDED02"
  },
```

**Comment by kaaax0815** [comment]
On VSCode vanilla `"terminal.background"` changes the whole background, on code-server it only changes the border 
![msedge_53NJLNGw10](https://user-images.githubusercontent.com/32197462/119835447-20bc0e80-bf01-11eb-8435-7617c9307a36.png). 
i have to set `"terminal.ansiBlack"` to change background on bash ( i have sh selected but it still uses bash
