### ISSUE TITLE
When I restarted docker, I found that the previously generated password could not be used.

### ISSUE THREAD

**Issue by JavanTang** [cdr/code-server#349]

**Comment by sr229** [comment]
This is intended. There is no way at the moment to persist the password. However, if I remember the team will allow you to set your own via `--password` very soon.

**Comment by Multishifties** [comment]
@sr229 I believe the `--password` argument is already supported 🙂!  IIRC that was one of the first PRs we merged on this repo that didn't come from someone on the Coder.com team. That PR is located at https://github.com/codercom/code-server/pull/5

As for persisting passwords, I'd love to hear some discussion on the best way to accomplish this. My first inclination would be to have an environment variable (something like `CODE_SERVER_PASSWORD`) and simply check for existence of said env var before proceeding to generate a random password. But I could be overlooking a bunch of important things and introducing a whole new slew of security concerns with this method.

**Comment by seaverd** [comment]
Would love to see an environment variable implemented for password!   Saw another issue listed where developer indicated that environmental variables weren't currently supported and users needed to create their own dockerfile.   As a newbie, I forked and have tested two builds but can't get it.   So far can't even test this as I have no Mac or Linux to run the cli to get password.   Any way to get or set password at bash prompt within the docker container?

**Comment by sr229** [comment]
I did some work on my Coder container but I’ll give a heads up if it works

**Comment by code-asher** [comment]
https://github.com/cdr/code-server/commit/55bfeab20817fd489046b0cdd4242a54592d11f0
