### ISSUE TITLE
[iPadOS] Copy value not working from debugging watch section

### ISSUE THREAD

**Issue by alexey1966** [cdr/code-server#3490]
code-server: v3.10.2
 VS Code: v1.56.1
Commit: 387b12ef4ca404ffd39d84834e1f0776e9e3c005
Date: 2021-05-21T23:13:00Z
Browser: Mozilla/5.0 (iPad; CPU OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1

Copy value is not working from debugging watch section. I try to click on watch variable with Ctrl and then select Copy value in pop-up. It’s not copied.

**Comment by jsjoeio** [comment]
@alexey1966 can you please redo your issue description and fill out the [bug report](https://github.com/cdr/code-server/issues/new/choose)? That way we can look into this. 

Thanks!
