### ISSUE TITLE
auto import is not working in TypeScript.

### ISSUE THREAD

**Issue by alexey1966** [cdr/code-server#3492]
code-server: v3.10.2
 VS Code: v1.56.1
Commit: 387b12ef4ca404ffd39d84834e1f0776e9e3c005
Date: 2021-05-21T23:13:00Z
Browser: Mozilla/5.0 (iPad; CPU OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1

When I try to use external function, it doesn’t suggest me to import proper module.

**Comment by jsjoeio** [comment]
@alexey1966 can you please redo your issue description and fill out the bug report? That way we can look into this.

Thanks!
