### ISSUE TITLE
Default Terminal doesnt work

### ISSUE THREAD

**Issue by kaaax0815** [cdr/code-server#3493]
## OS/Web Information

- Web Browser: Edge 90.0.818.66
- Local OS: Windows 10 20H1
- Local VSCode: 1.56.2
- Remote OS: Ubuntu 20.04
- Remote Architecture: amd64
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

I have this in my settings.json
```json
"terminal.integrated.fontWeight": "400",
"terminal.integrated.fontSize": 14,
"terminal.integrated.fontFamily": "Fira Code",
"terminal.integrated.letterSpacing": 1.5,
"terminal.integrated.defaultProfile.linux": "fish",
"terminal.integrated.profiles.linux": {
    "bash": {
        "path": "bash"
    },
    "fish": {
        "path": "fish"
    },
    "sh": {
        "path": "sh"
    }
}
```
2. I start/open Terminal
3. error

## Expected

In my case the shell should be fish

## Actual

I have bash as my shell

## Logs

To be added

## Screenshot

![msedge_hOygjqkJaX](https://user-images.githubusercontent.com/32197462/119836944-71803700-bf02-11eb-8357-36aee071e97d.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by oxy** [comment]
Can you set the path to the absolute path, eg. `/usr/bin/fish`, and report back?

**Comment by kaaax0815** [comment]
Thanks that works!
