### ISSUE TITLE
--link bug

### ISSUE THREAD

**Issue by zoga-com** [cdr/code-server#3494]
Good day. I have been using your software for over a month. I used the main one on the VM, but then decided to buy another one for this software and host it there. Logged in through github, wrote code-server --link. And suddenly he writes to me, they say the code-server is not included, turn it on and so on ... I think the problem is in changing the VM.

## OS/Web Information

- Web Browser: Firefox 
- Local OS: Debian 9
- Remote OS: Debian 10
- Remote Architecture:  x86_64
- `code-server --version`: 3.10.2

**Comment by jsjoeio** [comment]
@kungermu can you please redo your issue description and fill out the [bug report](https://github.com/cdr/code-server/issues/new?assignees=&labels=&template=bug-report.md&title=)? That way we can look into this.

Thanks!
