### ISSUE TITLE
built-in extensions "simple-browser" not work

### ISSUE THREAD

**Issue by sinoon** [cdr/code-server#3495]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36

## OS/Web Information

- Web Browser: Chrome/90.0.4430.212 
- Local OS: Intel Mac OS X 10_15_7
- Remote OS: Linux
- Remote Architecture: Linux my 4.14.81.bm.19-amd64  SMP Debian 4.14.81.bm.19 Fri Feb 14 02:39:08 UTC 2020 x86_64 GNU/Linux
- `code-server --version`: 3.10.0

## Steps to Reproduce

1. open your code-server page
2. cmd + shift + p and open "Simple Browser Show"
3. enter any valid URL

get this:

![image](https://user-images.githubusercontent.com/6065488/119933264-5bcc4980-bfb6-11eb-990e-5a881ac4cb30.png)

## Expected
open URL success

## Actual
get empty 

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by sinoon** [comment]
seem's like static resource not found
![image](https://user-images.githubusercontent.com/6065488/119933716-34c24780-bfb7-11eb-9e87-161ecc97eecd.png)

**Comment by code-asher** [comment]
Nevermind, please ignore the above. I didn't realize this was a built-in extension. We'll need to look into this.
