### ISSUE TITLE
Code-server as chrome app not functional (keys or clicks not working)

### ISSUE THREAD

**Issue by naderkhalil** [cdr/code-server#3505]
## OS/Web Information

- Web Browser: Chrome
- Local OS: Mac OS
- Remote OS: Debian
- Remote Architecture: x86
- `code-server --version`: 3.9.1 e0203f2a36c9b7036fefa50eec6cf8fa36c5c015

## Steps to Reproduce

1. Run Code-Server
2. Install Chrome App by clicking 3 dots -> more tools -> create shortcut, or the install icon if it's available to you
3. The new code-server app is read only

## Expected

I should be able to interact with the code server app as if it was in a browser tab.

## Actual

The cursor is blinking, but nothing else works. No keys or clicks are responding.

## Screenshot

![image](https://user-images.githubusercontent.com/19561555/120052530-9fd14580-bfda-11eb-8737-982b64b30755.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Can you please try upgrading to the latest version of code-server?

I tried to reproduce locally (macOS + Chrome) but didn't have any luck.

## Screenshot
https://user-images.githubusercontent.com/3806031/120369498-339b5e00-c2c8-11eb-9412-267b596679b1.mov
