### ISSUE TITLE
Add documentation to configure the contents of the green section in the bottom left

### ISSUE THREAD

**Issue by sestegra** [cdr/code-server#3513]
The contents of the green section in the bottom left should be configurable.

In fact, when using a frontend proxy like NGINX, `code-server` is exposed with another address than the bind address (this is the address displayed in the green section in the bottom left). Thus, I need to update that address to the one exposed by NGINX.

**Comment by nakkaya** [comment]
I also use `code-server` behind `nginx`, setting `proxy_set_header Host $host;` in your reverse proxy conf should change the green bar to correct value.

**Comment by sestegra** [comment]
@nakkaya Thank you, it works. So, I changed the issue to document this feature.

**Comment by bpmct** [comment]
didn't know this, very cool!
