### ISSUE TITLE
Terminal error and more

### ISSUE THREAD

**Issue by coder-lg** [cdr/code-server#3527]
I just upgraded to code-server 3.10.2, and I got a TON of errors. This is **very** important.

1. The terminal is screwed up, there are lines between the text.
2. It takes forever, and I literally mean forever, to load. It never happened at Code-Server 3.9.3.
I had to downgrade back. Can you please look up these errors on code-server?

**Comment by jsjoeio** [comment]
Please fill out a proper [bug report](https://github.com/cdr/code-server/issues/new?assignees=&labels=&template=bug-report.md&title=) and we'll be happy to take a look!

**Comment by coder-lg** [comment]
Okay

**Comment by coder-lg** [comment]
Check issue at #3530 please
