### ISSUE TITLE
Terminal glitched out, takes forever to load up.

### ISSUE THREAD

**Issue by coder-lg** [cdr/code-server#3530]
## OS/Web Information

- Web Browser: Brave Browser
- Local OS: Windows Build number 7601
- Remote OS: Debian
- Remote Architecture: idk
- `code-server --version`: problem on 3.10.2, I use 3.9.3

## Steps to Reproduce

1. Change Dockerfile's first line to 3.10.2
2. Wait for redeployment
3. Open the terminal

## Expected

No glitches, like the one on 3.9.3

## Actual

Terminal so screwed out, there is bars between, selection is like burnt paper on edges

## Logs

I am using a deployed version, how?

## Screenshot

a few minutes please

## Notes

This issue can be reproduced in VS Code: No

**Comment by coder-lg** [comment]
About VS code reproduction, it has the latest version but my terminal is not so screwed up

**Comment by coder-lg** [comment]
![image](https://user-images.githubusercontent.com/76845820/120586923-0da1c500-c452-11eb-8c85-e34bbe47699f.png)

**Comment by coder-lg** [comment]
screenshot above is 3.10.2
notice the terminal?
it is not proper

**Comment by coder-lg** [comment]
and the errors started on 3.10.0

**Comment by coder-lg** [comment]
![image](https://user-images.githubusercontent.com/76845820/120587897-d59b8180-c453-11eb-9214-f23618a6bebc.png)

**Comment by oxy** [comment]
Can you double-check if this works in Chrome? Worked locally in both Chrome 91 and Firefox 89 on Linux. If it does work in Chrome for you, can you file this bug with Brave?

**Comment by jsjoeio** [comment]
Possibly related: https://github.com/cdr/code-server/issues/3346#issuecomment-842254457

**Comment by coder-lg** [comment]
So, it is the font?

**Comment by coder-lg** [comment]
It works now, and one small doubt. How do you change the password? I am using a deployed version.

**Comment by jsjoeio** [comment]
Looks like you're using Railway. Go to Dashboard > Project > Variables and change the PASSWORD env var. 

![image](https://user-images.githubusercontent.com/3806031/120843389-e535cb80-c522-11eb-8e98-60d17a49cd36.png)
