### ISSUE TITLE
Adding an "update" bottom on the menu

### ISSUE THREAD

**Issue by phisanti** [cdr/code-server#3541]
I always see this message every new release:

  Upgrading is as easy as installing the new version over the old one. code-server
  maintains all user data in ~/.local/share/code-server so that it is preserved in between installations.

However, I run code-server in a docker container and I am not sure how to proceed, so I would be very grateful if you could create a click-an-update option for the less savvy.

**Comment by jsjoeio** [comment]
This is an interesting ideaI I do agree there is some room for improvement in terms of the UX around upgrading code-server. Thanks for the suggestion!
