### ISSUE TITLE
Code-server PWA hangs

### ISSUE THREAD

**Issue by c0ppelius** [cdr/code-server#3543]
## OS/Web Information

- Web Browser: Safari 
- Local OS: iPadOS 14.6
- Remote OS: Raspbian Buster 
- Remote Architecture: arm64
- `code-server --version`: 3.10.2

## Steps to Reproduce

1. SSH from iPad to Raspberry Pi and forward port 8080
2. On iPad, open PWA from app icon 
3. PWA initializes but does not load the browser content

## Expected

I should see the editor page appear.

## Actual

Blank white screen below the iPad status bar. 

## Logs

I ran `code-server --log trace`, opened the PWA, and have attached the [output](https://github.com/cdr/code-server/files/6600205/cs.log).

Both the stderr and stdout logs were empty.

## Screenshot
<img width="1366" alt="File Jun 04, 12 46 40 PM" src="https://user-images.githubusercontent.com/2692610/120839670-3a7bd800-c537-11eb-8dd5-e0c7d4784665.png">

## Notes

There is no problem loading code-server in the Safari browser directly. Deleting and reinstalling the PWA makes no difference. Rebooting the iPad works for the first session. Subsequent sessions have the same issue. I attempted to run `code-server --link` to test but my connection latency exceeded the threshold.  

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Hmm...interesting. I'll have to see if I can reproduce. Usually this works for me:
1. run `code-server --link` from macOS laptop
2. access link on iPad

I have also had success [deploying code-server with Railway](https://github.com/cdr/deploy-code-server/blob/main/guides/railway.md) and using the PWA on my iPad. Though I need to test 3.10.2. It should work though.

I'll see if I can replicate.

**Comment by c0ppelius** [comment]
My connection calmed down and I was able to access a PWA installed running `code-server --link`. After passing through the GitHub authentication page, I saw the same behavior. Again, going through the browser directly wasn't a problem (though I had to reload the page initially).

**Comment by jsjoeio** [comment]
Interesting! Okay, I will definitely take a look then and get back to you.

**Comment by c0ppelius** [comment]
## Update: tested from other OS's both local and remote
### OS Info (Now)
- Web Browser: Safari 
- Local OS's: iPadOS 14.6, macOS 11.4 
- Remote OS's: Raspbian Buster, Ubuntu 20.04 
- Remote Architectures: arm64, amd64

### Behavior 
In addition to not rendering in the PWA, I noticed that on the initial load on the iPad that code-server would finish loading but fail to render the editor (either via port forwarding or `--link`). This problem would disappear if I reloaded the page. I looked at the behavior on macOS and it was the same but I can at least pull some data here. I have attached the html generated in the non-rendered and rendered.  
- [not_rendered.txt](https://github.com/cdr/code-server/files/6617702/not_rendered.txt)
- [rendered.txt](https://github.com/cdr/code-server/files/6617707/rendered.txt)
In theory, I should be able to use Web Inspector on macOS Safari to pull this data for iPadOS Safari but I have not been to get this working for either iPadOS or iOS. 

### Notes
I purged code-server from the Raspberry Pi and reinstalled with the current release but the behavior did not change. 

I tested on Chromium and Firefox (on Ubuntu 20.04 amd64) but things rendered fine on the initial load for both browsers from both remote machines. It may or may not be related but using the `--link` option Safari reports the page is not secure and prevents the web workers from loading whereas Chromium and Firefox report secure.

### Workaround
Downgraded to v3.8 and things work again (so far) though not after a reboot on the iPad.

**Comment by jsjoeio** [comment]
> code-server from the Raspberry Pi and reinstalled with the current release

How are you installing code-server on your Pi?

**Comment by c0ppelius** [comment]
> How are you installing code-server on your Pi?

- `curl -fsSL https://code-server.dev/install.sh | sh` for the current release. 

- `curl -fOL https://github.com/cdr/code-server/releases/download/v$VERSION/code-server_$VERSION_amd64.deb` for older releases. 

> P.S. - thank you for the detailed notes! Super helpful.

Thanks. Just let me know if there is anything I can do to be useful. Code-server is great. 

Also, my "workaround" declaration was premature. The problem reemerged after install an extension from the command line.

**Comment by jsjoeio** [comment]
Hmm... could you try uninstalling and installing via npm/yarn as suggested by [the docs](https://github.com/cdr/code-server/blob/main/docs/install.md#raspberry-pi)?

Don't know if that will fix, but worth a try (I was able to run it on my Pi this way)

**Comment by jsjoeio** [comment]
Ah gotcha. That makes sense.

> iPadOS beta release

I should have mentioned that I am using the beta release. Let us know what happens!

**Comment by c0ppelius** [comment]
No luck with iPadOS 14.7. Restarting the iPad almost always seems to get the PWA to load. Sometimes re-forwarding the port will also work.  Since I switched from the light to the dark theme, I can now notice that the background loads always. Below is a video of the behavior. 

https://user-images.githubusercontent.com/2692610/121413696-f3755480-c933-11eb-9361-c66424b575d3.mov

**Comment by jsjoeio** [comment]
Could this be related to Blink then?

I only say this because I am able to successfully run the PWA on my iPad which means we know, the issue isn't:
- code-server 3.10.2 
- the PWA 
- Safari

## Video 
https://user-images.githubusercontent.com/3806031/121418548-e9495b00-c91f-11eb-9a3c-03037802e3e4.MP4

Wait a second... now that you say this 

> Safari reports the page is not secure and prevents the web workers from loading whereas Chromium and Firefox report secure

When you SSH into your Pi and port forward 8080, this means you're accessing code-server on your iPad insecurely (through HTTP), which is probably why things aren't working as expected I think. Hopefully @code-asher can correct me if I'm wrong.

**Comment by c0ppelius** [comment]
> Could this be related to Blink then?

I thought that but I still have the problem if I serve it via `--link` and set the PWA via ***.cdr.co. 

The problem is also strange in that often only manifests after opening and closing the PWA some number of times (as seen in the video). It also has been progressively worsening. By this I mean that the number of reload cycles for the PWA after which the screen blanks has been trending down. 

> When you SSH into your Pi and port forward 8080, this means you're accessing code-server on your iPad insecurely (through HTTP), which is probably why things aren't working as expected I think. Hopefully @code-asher can correct me if I'm wrong.

I don't have a problem accessing `http://localhost:8080` from the iPadOS Safari browser (possibly after firing a page reload) after port-forwarding so the web socket is connecting.

**Comment by jsjoeio** [comment]
> I thought that but I still have the problem if I serve it via --link

We have seen issues with using `--link` on Pi's so that could be a separate issue. 

> I don't have a problem accessing http://localhost:8080 from the iPadOS Safari browser (possibly after firing a page reload) after port-forwarding so standard problems with an insecure server aren't present.

Ah, okay. Good point.

This is very strange indeed 🤔 I am not even sure what else we should try looking at.

One idea — if you're up for it — is to follow the [deploy on Railway guide](https://github.com/cdr/deploy-code-server/blob/main/guides/railway.md) and try installing/using that PWA to see if code-server works as expected. 

I think that would rule out the iPad or the PWA being the issue, right?

**Comment by c0ppelius** [comment]
Taking the Pi out of the conversation, the videos below show the behavior rendering a `—link` deployed server from my amd64 Ubuntu 20.04 machine. One video shows how iPadOS Safari fails to load ***.cdr.co completely. If I hit reload from here, then everything renders appropriately. 

https://user-images.githubusercontent.com/2692610/121539445-afd22780-c9d3-11eb-9e83-0a6c79193fac.MP4

The other shows the PWA installed from ***cdr.co hang. 

https://user-images.githubusercontent.com/2692610/121539435-aea0fa80-c9d3-11eb-9b7f-85d7d888aa07.MP4

One other piece of strange behavior: when I can get the PWA to load, it sometimes reports that there is an insecure connection.

**Comment by jsjoeio** [comment]
Thanks for the videos! This is very strange indeed 🤔

Let me try a similar thing. I'll run `code-server --link` from my macOS and open that URL on my iPad.

**Comment by jsjoeio** [comment]
> sometimes reports that there is an insecure connection

This is strange. `--link` serves the URL over HTTPS so it shouldn't be showing insecure 🤔 Could it be a Safari setting that causes the URL to not be trusted?

It loads for me in Safari and I'm able to install the PWA. When I do install it at first it shows a white screen, but if I reload the page, it works as expected (I do have a white bar at the bottom but I've fixed that before in the past). 


https://user-images.githubusercontent.com/3806031/121564603-7d72fb00-c9d0-11eb-94cc-30da160ddf1e.MP4

**Comment by c0ppelius** [comment]
OMG Command-R! Realizing this was supported on iPadOS would have saved me so much time. Though you need a keyboard for this, right?

The behavior of the PWA is similar to the behavior of the browser now: sometimes blanks but a reload fixes it. 

I also tested which browsers/OS combination reported ***.cdr.co as secure. 

### OK
- Chrome/Ubuntu 20.04
- Firefox/Ubuntu 20.04

### Not Secure
- Chrome/macOS 11.4 
- Firefox/macOS 11.4
- Safari/macOS 11.4
- Chrome/Windows 10 
- Edge/Windows 10

**Comment by jsjoeio** [comment]
I should have said that earlier - lol my bad 😅 But yes, I should say I'm using the iPad + Magic Keyboard and Trackpad. 

Okay thats good then! Is it okay to close this issue then?

Weird to hear about the secure thing though (and thanks for the thorough testing). I'm on macOS 11.3. I wonder if there was a change to how websites are considered secure or not 🤔

**Comment by c0ppelius** [comment]
> Okay thats good then! Is it okay to close this issue then?

Sounds good to me. 

> Weird to hear about the secure thing though (and thanks for the thorough testing). I'm on macOS 11.3. I wonder if there was a change to how websites are considered secure or not

The windows machine had not been booted in a long time.

**Comment by jsjoeio** [comment]
Team make made it happen! Glad we got it resolved.

**Comment by AaronHeee** [comment]
I encountered the same problem on the same version iPadOS & ubuntu 18.04. Command-R works for me! Thanks a lot!

**Comment by Tsarpf** [comment]
Refreshing the PWA with cmd+r fixes it for me as well. Finally!

**Comment by chinyee8896** [comment]
Thanks!!! I have the same problem with ubuntu 20.04 and iPadOS 14.6. cmd R saves the day!!

**Comment by LYF123123** [comment]
Dear developer, I use  self-signed certificates code server on Centos8 Version 3.32.2, It can work when I use Firefox (78.13.Oser 64bit)on my linux laptap and Chrome(93.0.4577.63) on my Win10 laptap; But  I can not use it on my ipad Pro Gen 4th[ipadOS 14.7.1](Both Chrome and Safari). After I enter ther url and the password(It show the password input box), it becomes blank and without anything, I have already tried cmd+R but it is useless, Please help me .

**Comment by jsjoeio** [comment]
Hi @LYF123123 sorry to hear you're having trouble! Can you please open a bug report and provide a video? Thanks!
