### ISSUE TITLE
Proxying of port does not work for React Native (Expo) apps

### ISSUE THREAD

**Issue by nooobcoder** [cdr/code-server#3550]
I have read gone through many docs of code-server **about the proxying of port**. The syntax for that is 
`https://address-of-code-server/proxy/19002`

But in the case of metro apps, **it does not work.** Let me attach a screenshot for better reference. Any help in this case would be pretty helpful. 
FYI: I know I can expose the ports like `19002` that expo uses, but that would not be the end solution, hence I want to go forward with proxying. (Also, to expose a port on my docker container, would require rebuilding it and it would take a time and effort for me atleast.)
Tagging few whom I know helpful in this organisation, @jsjoeio @bpmct @code-asher 

**[SCREENSHOT OF INITIALISING A BLANK REACT NATIVE PROJECT]**
![image](https://user-images.githubusercontent.com/50350828/120880253-d6185180-c5e6-11eb-9e97-7309a43fb6a7.png)

**[SCREENSHOT OF THE EXPO APP BEEN BUILT AND EXPOSING THE DEV TOOLS ON `http://localhost:19002` ]**
![image](https://user-images.githubusercontent.com/50350828/120880260-ef210280-c5e6-11eb-9f9e-4b8f70c11bfe.png)

**[SCREENSHOT OF EXPO DEV TOOLS ON BROWSER VIA code-server PROXY]**
![image](https://user-images.githubusercontent.com/50350828/120880276-0d86fe00-c5e7-11eb-810c-bfdc9365329d.png)
Here, it seems like, the page title 
![image](https://user-images.githubusercontent.com/50350828/120880293-4626d780-c5e7-11eb-8dce-ff89919e8191.png)
 is being loaded as it is evident, but somehow the page content is not being served, Things might be related to Next.js as expo uses Next.js to serve the dev tools in the browser.

**[SCREENSHOT OF THE NETWORK TAB LOADING THE FILES FROM THE DEV SERVER]**
![image](https://user-images.githubusercontent.com/50350828/120880298-5343c680-c5e7-11eb-9fa7-f6eabfdf0adb.png)

Any help would be very helpful, thank you!

**Comment by jsjoeio** [comment]
Thanks for the screenshots and information @nooobcoder! Do you mind instead filling out a bug report? That way we have repro steps and can help you faster!

**Comment by nooobcoder** [comment]
> Thanks for the screenshots and information @nooobcoder! Do you mind instead filling out a bug report? That way we have repro steps and can help you faster!

Yes, please @jsjoeio

**Comment by code-asher** [comment]
Does `https://address-of-code-server/absproxy/19002` work? I know it works for Create React App but I don't know if the same applies here. https://github.com/cdr/code-server/blob/main/docs/FAQ.md#proxying-to-create-react-app

It's possible `/absproxy` or `/proxy` might have to be added to the settings so the app is aware of the base path (I'm not familiar with React Native so I have no idea if this is the case).

For details: `proxy` strips the base path while `absproxy` does not.

**Comment by nooobcoder** [comment]
@code-asher I knew about `absproxy`, I read about it in the docs, also gave a shot to it, if it worked out this time. Unfortunately, it did not work out, I am attaching relevant screenshots and error codes for reference.

![image](https://user-images.githubusercontent.com/50350828/121287085-8e533c00-c8fe-11eb-9124-9a25cf72389f.png)
![image](https://user-images.githubusercontent.com/50350828/121287106-9612e080-c8fe-11eb-8ca8-b0d90ea491f2.png)
![image](https://user-images.githubusercontent.com/50350828/121287192-b6db3600-c8fe-11eb-95ae-ccca434f9957.png)
![image](https://user-images.githubusercontent.com/50350828/121287207-bd69ad80-c8fe-11eb-914f-a61a3268c0e6.png)
![image](https://user-images.githubusercontent.com/50350828/121287218-c2c6f800-c8fe-11eb-9e36-dfb8606a2b1a.png)

**Comment by code-asher** [comment]
I think that makes sense since Expo sees /absproxy/19002 and that path
doesn't exist.

From here we would need to configure Expo to understand that
/absproxy/19002 is the base path but they don't seem to have any
documentation on how to do that.

It looks like it uses Webpack so I tried to set the public path but I
didn't have any luck. I found an upstream issue about it though; it
seems they hardcode `/`: https://github.com/expo/expo-cli/issues/3092

**Comment by hesa2020** [comment]
I was also having a similar issue, 

I created a webpack.config.js file with following content:

`const createExpoWebpackConfigAsync = require('@expo/webpack-config');
// Expo CLI will await this method so you can optionally return a promise.
module.exports = async function(env, argv)
{
	const config = await createExpoWebpackConfigAsync(env, argv);
	if (config.mode === 'development')
	{
		config.output.publicPath = "https://code.mydomain.com/proxy/19006/";
	}
	return config;
};`

Then after that it started working, You might get some "watchers limit reached" if you are running a ubuntu docker image like me but this was easy to fix with a few commands to raise the limit.
