### ISSUE TITLE
Proper way to use code-server with multiple team members

### ISSUE THREAD

**Issue by Muruloki** [cdr/code-server#356]
Say in a simplest case i have a remote server which has several code repos, each one corresponding to a dev web server. Each dev env belongs to different developer. So something like this:

folder1
folder2
...
folder20

What's the best way to use code-server? Run only one instance and then everyone connects to it and opens their own folder or each developer runs their own instance of code-server? 

The reason i'm asking is that I tried running one instance of code-server and open 10 folders in different tabs, it was becoming pretty slow on 3rd folder or so. Our codebase is pretty large. I wonder if everyone having its own code-server instance will be faster.

Another scenario is a server where each dev has multiple different code repos. I guess in this case it makes more sense to have code-server instance for each dev?

How was it designed to be used to begin with? :)

**Comment by Multishifties** [comment]
Related issue https://github.com/codercom/code-server/issues/33

**Comment by Muruloki** [comment]
@Multishifties i think that one is a bit different and more advanced - looks like in that case they want to edit the same file simultaneously by different users.

My case is much easier - each dev has their own codebase so that scenario above isn't relevant. Sharing code is happening via git pull/push etc.

**Comment by Multishifties** [comment]
Ah, ok. That makes sense.

We have a new release out that should speed things up a bit. Hopefully that will be enough to allow for an single instance to be used by multiple users at the same time.

That said, I see now major downside to running multiple instances of code-server if your computer can support it.

**Comment by rafket** [comment]
Hi, I wanted to achieve the same as @Muruloki, so I made [this](https://github.com/rafket/vscode-hub). It essentially downloads the binary release of code-server, makes a new image (cause I wanted to have the ability to add packages like gcc), and spins up containers on demand. I think it is somewhat orthogonal to code-server, but I could try to improve code quality and make a pull request if other people are interested.

**Comment by deansheather** [comment]
One use case of this would be using one code-server to provide individual working directories for each student in a class.

**Comment by sr229** [comment]
Also another use case is one imstance to many developers as well.

**Comment by HULANG-BTB** [comment]
I want my users to use their own ssh account as the login verification, and after the verification is passed, locate it in their own user directory. Is this possible by starting only one instance, what should I do?

**Comment by deansheather** [comment]
Multiple users using one instance in separate directories is currently not supported (neither is collaboration on a single directory).

**Comment by Aelindgard** [comment]
> Ah, ok. That makes sense.
> 
> We have a new release out that should speed things up a bit. Hopefully that will be enough to allow for an single instance to be used by multiple users at the same time.
> 
> That said, I see no major downside to running multiple instances of code-server if your computer can support it.

Hi can I know what feature in the new release would allow this? Is it based on separate user login per each dev?

Awesome stuff as always.

Thank you.

**Comment by nhooyr** [comment]
Will add to the FAQ.

**Comment by Songkeys** [comment]
In the FAQ, I say it suggests use "kubevirt" for this. But I still don't get how to do it properly. Is there any detail or examples? thanks.

**Comment by caio-vinicius** [comment]
Did anyone implement some solution? I'm currently working on a server to provide VSCode to multiple users in different folders

**Comment by makwanji** [comment]
Hello, dose this feature out? I have same requirement, 
1 code server and 10 users, having their username, password and workspace.

**Comment by code-asher** [comment]
I don't think we have any specific examples on how to use KubeVirt or how to deploy with Kubernetes. There's a Helm chart in the works (https://github.com/cdr/code-server/pull/2048) that might be of use though.

**Comment by paulchill** [comment]
any update on this?

**Comment by jsjoeio** [comment]
@paulchill I might have some coming! What are you hoping for?

**Comment by jsjoeio** [comment]
@paulchill super super interesting! cc @bpmct 

Have you trialed [coder/coder](https://github.com/coder/coder) yet? Wondering if that would suit your needs better.
