### ISSUE TITLE
formulahendry.vscode-mysql, mtxr.sqltools settings panel is blank

### ISSUE THREAD

**Issue by shetubd** [cdr/code-server#3573]
## OS/Web Information

- Web Browser: Firefox 89.0 (32 bit)
- Local OS: Windows 7
- Remote OS: Cent OS 7 (docker)
- Remote Architecture:

code-server: v3.10.2
 VS Code: v1.56.1
Commit: 387b12ef4ca404ffd39d84834e1f0776e9e3c005
Date: 2021-05-21T23:13:00Z
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0

## Steps to Reproduce
I install mysql extension (formulahendry.vscode-mysql, mtxr.sqltools) and their settings panel are blank. 
extension details page are blank too.

## Screenshot

![query](https://user-images.githubusercontent.com/37763269/121235293-85d71300-c8b6-11eb-9a7a-dda9034f551b.png)
![sql tools](https://user-images.githubusercontent.com/37763269/121235299-87a0d680-c8b6-11eb-8de6-50a1bd42e72f.png)
![details page](https://user-images.githubusercontent.com/37763269/121235425-b1f29400-c8b6-11eb-9f7d-44f89d66e48f.png)

## Notes

This issue can be reproduced in VS Code: Yes/No
I do not know

**Comment by code-asher** [comment]
Is this using HTTPS? I can't remember if the padlock with a cross means HTTP or mixed content.

This might be because these panels use web views which only work in a secure context (HTTPS or localhost).

**Comment by shetubd** [comment]
> 
> 
> Is this using HTTPS? I can't remember if the padlock with a cross means HTTP or mixed content.
> 
> This might be because these panels use web views which only work in a secure context (HTTPS or localhost).

No. Just http,

**Comment by shetubd** [comment]
Today I change code-server address http to https now panel show. Only setcap command failed (sudo: setcap: command not found), but code-server run over https. 
Thanks everyone.
# Replaces "cert: false" with "cert: true" in the code-server config.
sed -i.bak 's/cert: false/cert: true/' ~/.config/code-server/config.yaml
# Replaces "bind-addr: 127.0.0.1:8080" with "bind-addr: 0.0.0.0:443" in the code-server config.
sed -i.bak 's/bind-addr: 127.0.0.1:8080/bind-addr: 0.0.0.0:443/' ~/.config/code-server/config.yaml
# Allows code-server to listen on port 443.
sudo setcap cap_net_bind_service=+ep /usr/lib/code-server/lib/node


![https](https://user-images.githubusercontent.com/37763269/121370282-6d223800-c95e-11eb-9234-6eaf077d14e0.png)

**Comment by jsjoeio** [comment]
Great! I'm interpreting that as fixed so I'll close this issue.
