### ISSUE TITLE
Add Download for Folder (As ZIP)

### ISSUE THREAD

**Issue by chickentom** [cdr/code-server#3577]
> Is it possible to add the Download Button for Folder? So far it's only aviable for Files and i have to manually zip the files and download them. Thanks

**Comment by vital987** [comment]
Have a look at my [customization](https://github.com/vital987/code-server), it auto zips workspace directory and uploads it to your Google drive (you need to set it up first), refer [readme](https://github.com/vital987/code-server/blob/master/README.md) for more info.
