### ISSUE TITLE
Install script tries to use root if install destination does not yet exist even in standalone mode.

### ISSUE THREAD

**Issue by nugend** [cdr/code-server#3585]
https://github.com/cdr/code-server/blob/d8c3ba6a179d185aa42ceb6761dd8a2be339d68f/install.sh#L378

The '-w' test fails if  "$STANDALONE_INSTALL_PREFIX" doesn't exist. Since this variable defaults to $HOME/.local the user may not have created that hidden directory before attempting to install.

**Comment by jsjoeio** [comment]
Ah, nice catch! Thanks for pointing this out and raising an issue.
