### ISSUE TITLE
"Git:View File History" is not working

### ISSUE THREAD

**Issue by sangchul** [cdr/code-server#3594]
## OS/Web Information

- Web Browser: Chrome Version 91.0.4472.101 (Official Build) (x86_64)
- Local OS: macOS Big Sur Version 11.2.3
- Remote OS: CentOS Linux release 7.4.1708 (Core)
- Remote Architecture: x86_64
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

"Git: View File History" which is in popup menu at sidebar is not working. It didn't show any contents and I checked Javascript Console, following was shown

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/28073/121618343-95ff1600-caa1-11eb-9f30-36e692a8214d.png">

and I downgraded code-server to 3.9.0 which I used before 3.10.2 and it works fine. 

I've been using git history plugin, "Git History" and its version is 0.6.15

Thanks in advance

**Comment by jsjoeio** [comment]
I tried using [the extension](https://github.com/DonJayamanne/gitHistoryVSCode) but couldn't get it to work 😢 I did get it to work in VS Code desktop though.

It's hard to tell why it's not working though. I do not see those console errors (not sure why Service Workers aren't enabled for you). There are also no logs from code-server (even running `--log trace`).

![image](https://user-images.githubusercontent.com/3806031/121726368-4d465d80-ca9f-11eb-93aa-926595b0faf2.png)

Thanks for filing! We'll have to investigate further.

**Comment by sangchul** [comment]
I attached two video captures, one is 3.10.2 and the other is 3.9.0

the strange thing happens at not only "Git history plugin" but also other plugins. my attached video shows that everytime I click the plugin name to see its information, the console prints similar error messages and vscode doesn't show any information in 3.10.2. 

but in 3.9.0, it also prints different error message but shows plugin information as we expected.

I hope my videos help solve the problems


https://user-images.githubusercontent.com/28073/121980037-361cae00-cdc6-11eb-9f5f-d5bc9d680735.mov


https://user-images.githubusercontent.com/28073/121980056-40d74300-cdc6-11eb-892a-d07bdf615617.mov

**Comment by jsjoeio** [comment]
Very strange indeed. Thanks for the videos and thorough testing! We'll have to see what changed upstream between 3.10.2 and 3.9.0 that would affect this

**Comment by sangchul** [comment]
I solved this problem. It seems to be related to security things. I read this article and set up ssh with port forwarding as it guided.

https://coder.com/docs/code-server/v3.11.0/guide

**Comment by jsjoeio** [comment]
Awesome! Glad to hear the guide helped. I'm going to close this now.
