### ISSUE TITLE
code-server not loading on iPad

### ISSUE THREAD

**Issue by mrFred-1a4** [cdr/code-server#3618]
## OS/Web Information

- Web Browser: safari
- Local OS: ipad os 1.14.6
- Remote OS: unraid
- `code-server --version`: 1.10.2

## Steps to Reproduce

installed code-server on Unraid thru Community applications, image based of https://hub.docker.com/r/linuxserver/code-server/tags?page=1&ordering=last_updated. configured everithyng. Using Nginx proxy manager with authelia and cloudflare. everything works fine on desktop, But on ipad in every browser there is just a blank screen. 

## Expected

vs-studio opens after login

## Actual

just a white screen

## Logs

unfortunately i cant collect logs from ipad, because i dont have a mac to read them out

This issue can be reproduced in VS Code: Yes/No

**Comment by jsjoeio** [comment]
What happens if you refresh/reload the page?

**Comment by mrFred-1a4** [comment]
When refreshing / using command+r on safari i still get the white screen

**Comment by jsjoeio** [comment]
Hmm... can you [record a video](https://support.apple.com/guide/ipad/take-a-screenshot-or-screen-recording-ipad08a40f3b/ipados) and show me the whole process on your iPad? (I just tested on my iPad and things are working as expected)

**Comment by mrFred-1a4** [comment]
https://user-images.githubusercontent.com/72572280/122277137-d7e6ec80-cee5-11eb-810b-f725b7cfdd64.MOV

**Comment by mrFred-1a4** [comment]
on local ip it works fine but with the domain it wont load

**Comment by jsjoeio** [comment]
Hmm... this appears to be a local environment issue (at least, I say this because things are working on my setup with Railway). I'm going to convert this to a Discussion and we can continue the conversation there.
