### ISSUE TITLE
Search for not opened files does not worked on FreeBSD

### ISSUE THREAD

**Issue by oklas** [cdr/code-server#3669]
## OS/Web Information

- Web Browser: not concern (safari/chrome)
- Local OS: not concern (BigSur)
- Remote OS: **FreeBSD** 12.2-RELEASE r366954 GENERIC 
- Remote Architecture: UNIX
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

```
# code-server
```
* open client app from browser
* possible open some files on not
* navigate to search tab and enter text

## Expected

Show files list on result area one by one with short time interval

## Actual

Result list has only files that opened in tabs
There is no result from remote files that is no opened
Blue progress line above search text field is continuously and endlessly moving 

![image](https://user-images.githubusercontent.com/8123356/123323357-0e53e580-d53e-11eb-8aba-3bfed1b5a53f.png)

Above image shows `styles` result only for file that already opened.
There is no results for other files, many of them of course contain `styles`.

No any errors/warnings/output on server side.

This issue can be reproduced in VS Code: No

Any any possible additional info or help with debug or inspect problem will be provided

**Comment by jsjoeio** [comment]
I believe this is because there is no prebuilt binary for ripgrep for FreeBSD. 

Can you try [this solution](https://github.com/cdr/code-server/issues/1907#issuecomment-663888997)?

**Comment by oklas** [comment]
possible related #3665

**Comment by oklas** [comment]
I tried mentioned solution, it seems reasonable. But it is possible another problem. After first request from browser one of the server workers starts to take up all the CPU time. More details in related issue.

**Comment by oklas** [comment]
Actually I found another problem, so both proms was:

* The first problem was absence of `ripgrep` and solution is described at link provided above by @jsjoeio 
* The second problem and solution was issue that I created and associated as related #3665
