### ISSUE TITLE
close whole page when close non editing panel using c-w

### ISSUE THREAD

**Issue by y1rn** [cdr/code-server#3678]
## OS/Web Information

- Web Browser: chrome
- Local OS: mac/windows
- Remote OS:  Debian 5.10.24-1~bpo10+1 (2021-03-29) aarch64
- Remote Architecture: aarch64
- `code-server --version`:3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

1.open md file
2.press preview button
3.focus on preview panel and click c-w shortcut

## Expected

close preview panel

## Actual

close whole page

**Comment by jsjoeio** [comment]
This is because the global shortcut for closing pages in Chrome is c/cmd-w. We can't override this, but you can avoid this from happening by using the PWA.

## Video


https://user-images.githubusercontent.com/3806031/123687145-6ec87880-d805-11eb-903d-9336a1b93349.mov

**Comment by y1rn** [comment]
> This is because the global shortcut for closing pages in Chrome is c/cmd-w. We can't override this, but you can avoid this from happening by using the PWA.
> 
> ## Video
>  Screen.Recording.2021-06-28.at.11.38.34.AM.mov

still close PWA while focusing on none editing preview panel

**Comment by jsjoeio** [comment]
> still close PWA while focusing on none editing preview panel

Hmm...you may need to change the binding manually then. Here I recorded a video showing you how to change the shortcuts and check what is set. 

https://www.loom.com/share/7f043c1101b2494a80427412d7981522
