### ISSUE TITLE
Search does not exclude .gitignore

### ISSUE THREAD

**Issue by andreimc** [cdr/code-server#368]
- `code-server` version: 1.408-vsc1.32.0
- OS Version: ubuntu

## Description

Right click search in folder, it includes all files even in .gitignore

Vscode excludes gitignored files

## Steps to Reproduce

as above

**Comment by nol166** [comment]
Thanks for the report. It also looks like code-server doesn't grey them out either
![image](https://user-images.githubusercontent.com/5651438/55259825-c053b880-5234-11e9-9df3-984eae66c041.png)

**Comment by myelsukov** [comment]
Do you have `.git` directory? I believe VSCode do not honor `.gitignore' files if the project is not a git project. See https://github.com/microsoft/vscode/issues/69231

**Comment by code-asher** [comment]
I did some testing with v2 and the `.gitignore` appears to be respected both with and without a `.git` directory which is neat. This might be because VS Code shells out to `ripgrep` for searching now.
