### ISSUE TITLE
Bad "edit docs" link

### ISSUE THREAD

**Issue by elliott-king** [cdr/code-server#3693]
That's the one at the bottom of each page. Probably due to your static site configuration.

<img width="765" alt="Screen Shot 2021-06-29 at 4 53 14 PM" src="https://user-images.githubusercontent.com/8884571/123865942-80d81300-d8fa-11eb-9a33-7f20b2166049.png">

**Comment by jsjoeio** [comment]
@BrunoQuaresma can you take a look at this?

**Comment by BrunoQuaresma** [comment]
@jsjoeio thinking on have this redirecting to the `cdr/code-server/docs/README` page. What do you think?

**Comment by jsjoeio** [comment]
Is it possible for us to have the "Make an edit" link work as expected?

i.e. if I'm on https://coder.com/docs/code-server/v3.10.2/guide and click the link, it should go to `https://github.com/cdr/code-server/edit/main/docs/guide.md`.

**Comment by BrunoQuaresma** [comment]
The fix should be live in a few minutes. Thanks @elliott-king for reporting this.
