### ISSUE TITLE
Problems with GLIBC_2.28 on raspbian

### ISSUE THREAD

**Issue by Hugovidafe** [cdr/code-server#3701]
I'm having problems ^^

![image](https://user-images.githubusercontent.com/69076992/124079070-f7832680-da48-11eb-8c40-30e132510449.png)

_Originally posted by @Hugovidafe in https://github.com/cdr/code-server/issues/1656#issuecomment-871972657_

**Comment by jsjoeio** [comment]
Can you please open a proper [bug report](https://github.com/cdr/code-server/issues/new?assignees=&labels=&template=bug-report.md&title=)? We'd be happy to help you then. Thanks!
