### ISSUE TITLE
editor.action.clipboardCutAction doesn't seem work.

### ISSUE THREAD

**Issue by RyanK1m** [cdr/code-server#376]
- `code-server` version: 1.408-vsc1.32.0
- OS Version: Linux 4.12.8-2-ARCH #⁠1 SMP PREEMPT Fri Aug 18 14:08:02 UTC 2017 x86_64 GNU/Linux

## Description

editor.action.clipboardCutAction action doesn't seem work at all.
editor.action.clipboardCutAction should cut entire line without selection.
current behavior or Ctrl+x is cut selected part.

## Steps to Reproduce

1. press Ctrl + x on any line without selection
2. nothing happen.

1. press Ctrl + shift + p (open up command pallet)
2. choose Cut
3. nothing happens.

**Comment by nol166** [comment]
@RyanK1m Does an error pop up in the bottom right when you try to cut (either method)?

**Comment by RyanK1m** [comment]
@nol166 No, there's no error pop up for either method.

**Comment by RyanK1m** [comment]
@nol166 found the solution

I removed these changes, and cut the entire line without selection works properly. 
I thinks this line overwrite behavior.

scripts/vscode.patch file
@@ -364 +363 @@ export class Configuration extends CommonEditorConfiguration {
-			emptySelectionClipboard: browser.isWebKit || browser.isFirefox,
+			emptySelectionClipboard: false, // browser.isWebKit || browser.isFirefox,

**Comment by code-asher** [comment]
That part of the patch has been removed in v2.
