### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by yogeshvar** [cdr/code-server#377]
- `code-server` version: Latest [1.408-vsc1.32.0](https://github.com/codercom/code-server/releases/tag/1.408-vsc1.32.0)
- OS Version: Linux VM, Chrome 73.0.3683.86 

## Description
Tired to open the developer console in chrome. Lost connection to the socket and keeps on trying again and again. 

<img width="1280" alt="Screenshot 2019-03-29 at 1 09 38 PM" src="https://user-images.githubusercontent.com/17572818/55218546-65b45f80-5228-11e9-96c1-b81fbc54722b.png">

<img width="1054" alt="Screenshot 2019-03-29 at 1 14 05 PM" src="https://user-images.githubusercontent.com/17572818/55218558-71a02180-5228-11e9-9a2e-c9b6f1e7c375.png">

It looks like working fine in local setup.

<img width="1280" alt="Screenshot 2019-03-29 at 1 31 40 PM" src="https://user-images.githubusercontent.com/17572818/55218569-78c72f80-5228-11e9-8f38-f6691beed33c.png">

Please find the attachments for more details. 

## Steps to Reproduce

1. Deploy your code-server in Gcloud
2. Try to open your developer console (CMD + Shift + c)

**Comment by kondongx** [comment]
same issue

**Comment by nol166** [comment]
@yogeshvar Do you know what version of linux your VM is running?

**Comment by nol166** [comment]
We have a fix for the socket disconnects, but it looks like the disconnects here were a result of the terminal spawn error. Thanks for reporting!

**Comment by Athul-CA** [comment]
I too am getting the same error,
I cannot load or download any extensions too. I'm currently self-hosting it

**Comment by yogeshvar** [comment]
> @yogeshvar Do you know what version of linux your VM is running?

Yes, I use `Linux version 4.15.0-1028-gcp`

**Comment by niallobrien** [comment]
Same issue here, I'm using Ubuntu 18.04 on Digital Ocean.

**Comment by karanwadhwa** [comment]
I noticed that this issue goes away upon specifying the data directory.
`./code-server --data-dir /root/code-server` works fine but without the `--data-dir` argument code-server crashes within a few minutes of launch.

**Comment by mertcancam** [comment]
Same issue here, I'm using Ubuntu 18.04 on Vultr. After sometime it just crashes.

**Comment by muhammadomais** [comment]
Same issue i am using Digital Ocean, following is the error i am getting on terminal

> INFO  http://localhost:80/
INFO   
INFO  Starting shared process [1/5]...
WARN  stderr {"data":"(node:1260) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
INFO  Starting shared process [2/5]... {"error":"Exited unexpectedly"}
WARN  stderr {"data":"(node:1274) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
internal/child_process.js:366
    throw errnoException(err, 'spawn');
    ^

> Error: spawn ENOMEM

    at ChildProcess.spawn (internal/child_process.js:366:11)
    at Object.spawn [as _spawn] (child_process.js:538:9)
    at t.async (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:34598)
    at e.exports (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:34099)
    at e (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:32722)
    at Timeout.u [as _onTimeout] (/home/travis/build/codercom/code-server/packages/server/out/cli.js:504:33015)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

> root@test-ubuntu-1-1:~/myapp# packet_write_wait: Connection to 206.189.228.176 port 22: Broken pipe

**Comment by nhooyr** [comment]
If this still occurs, please feel free to reopen.
