### ISSUE TITLE
Jupyter Notebooks don't work

### ISSUE THREAD

**Issue by gogobd** [cdr/code-server#3776]
Juoyter extension doesn't install properly / doesn't work.
Run cdr/code-server, create test.ipynb file, install Jupyter Extension.
Jupyter doesn't initialize, Notebooks don't work.

THe last time it was ok was with v3.9.3 and 
`https://github.com/microsoft/vscode-python/releases/download/2020.10.332292344/ms-python-release.vsix` installed manually.

**Comment by jsjoeio** [comment]
@gogobd can you please open a bug report issue using the issue template? That will help us help you faster! Thank you!

**Comment by gogobd** [comment]
I think now that's https://github.com/cdr/code-server/issues/3782
