### ISSUE TITLE
3.11.0 release did not bump Helm chart version

### ISSUE THREAD

**Issue by ssmall** [cdr/code-server#3794]
It looks like the [3.11.0 release](https://github.com/cdr/code-server/commit/52579f182d420849693039b72523ddd601fdd246) changed the app version but not the chart version. My understanding of Helm chart versioning semantics is that any app version change should also bump the chart version to provide a clean upgrade path for Helm users.

**Comment by jsjoeio** [comment]
@oxy @code-asher any ideas on what happened here?
