### ISSUE TITLE
I am unable to use Live server for HTML

### ISSUE THREAD

**Issue by sudhanshuprasad2002** [cdr/code-server#3795]
## OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

## Steps to Reproduce

1.
2.
3.

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by jsjoeio** [comment]
Please fill out a bug report and we'll be happy to take a look!
