### ISSUE TITLE
Docker image for 3.11 not published

### ISSUE THREAD

**Issue by alpesh1988** [cdr/code-server#3814]
Hello Guys,

Somehow docker latest image is still running on vscode previous version and not with 1.57.1. You can check by looking at build size for latest and 3.10.2 images in the link below, Both have same sizes.

See [here](https://hub.docker.com/r/codercom/code-server/tags?page=1&ordering=last_updated)

Request you to fix that issue,

Looking forward to receive your response,

Regards,
Alpesh

**Comment by stilleshan** [comment]
The same problem, the image pulled shows that it was created 8 weeks ago

GitHub action workflows had error 4 days ago
https://github.com/cdr/code-server/actions/runs/1039022443

**Comment by jsjoeio** [comment]
Yes, we're having some troubles updating the Docker image for 3.11. Please read this thread for details: https://github.com/cdr/code-server/discussions/3779#discussioncomment-1010599

**Comment by alpesh1988** [comment]
Is it really taking too long or missed to update an issue ?

**Comment by jsjoeio** [comment]
As you probably saw #3838 was merged today.

It "partially addresses this issue, though a new release needs to be made for the workflow to kick in."

Hopefully we can do that tomorrow on Monday. cc @oxy

**Comment by jsjoeio** [comment]
![image](https://user-images.githubusercontent.com/3806031/127701626-94cec3da-345c-4641-b4f2-3e524de950c6.png)

@code-asher has updated the images. Thanks for your patience!
