### ISSUE TITLE
Code-server vscode terminal text blurry

### ISSUE THREAD

**Issue by danielreyes61** [cdr/code-server#3848]
## OS/Web Information

- Web Browser: Google Chrome
- Local OS: Windows 10
- Remote OS: Heroku
- Remote Architecture: Linux?
- `code-server --version`: Latest release? Installed 24July2021

## Steps to Reproduce

1. Fresh install
2. View Terminal

## Expected

Text should be visible when viewing on PC as well as tablet.  

## Actual

All parts of vscode are clear text but the terminal text is blurry.

## Logs

N/A

## Screenshot

![image](https://user-images.githubusercontent.com/10054066/126874482-c7b92364-30f7-48c6-8561-fbbbda0e568e.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Thanks for the bug report!

We had a similar issue reported [here](https://github.com/cdr/code-server/issues/3346) ([solution was related to Brave](https://github.com/cdr/code-server/issues/3346#issuecomment-842254457)).

[Another solution](https://github.com/cdr/code-server/issues/3346#issuecomment-852768704) was related to the font family:
>  was able to fix it by copying the font family settings from
> Text Editor-> Font -> Font Family
> In to the terminal font family settings (which was blank)
> Features->Terminal -> Font Family

Mind seeing if either of these fix it? 

Are you using a custom font family by chance?

**Comment by danielreyes61** [comment]
It is working on my laptop and I'm confident this would have fixed the issue on my other monitor. Thank you.
