### ISSUE TITLE
Getting 404 on Helm link

### ISSUE THREAD

**Issue by brootware** [cdr/code-server#3867]
Hello, the link on installation using Helm seems to be broken and returning 404. I can't seem to find the original link referenced from the markdown either. Please look into it. Link to the doc is below.

https://github.com/cdr/code-server/blob/main/docs/install.md#helm

**Comment by jsjoeio** [comment]
I'm assuming you mean clicking the Helm link from [here](https://coder.com/docs/code-server/v3.11.0/install#helm)?

It seems like it should point to here: https://github.com/cdr/code-server/blob/main/ci/helm-chart/README.md

Thanks for filing an issue for that!

**Comment by brootware** [comment]
Yes, @jsjoeio it's working on GitHub but seems like it's broken on the main coder.com page.

https://coder.com/docs/code-server/v3.11.0/ci/helm-chart/README
![Screenshot 2021-07-29 at 9 28 41 AM](https://user-images.githubusercontent.com/7734956/127417991-e9964c69-2faf-47b9-b1ee-df3add99530e.png)
