### ISSUE TITLE
Unable to write to Folder Settings because no resource is provided.

### ISSUE THREAD

**Issue by caochuansong** [cdr/code-server#3873]
- Web Browser: chrome
- Local OS: macos
- Remote OS: centos
- Remote Architecture: 
- `code-server --version`: 3.11

every time I refresh web page, I got this error:
Unable to write to Folder Settings because no resource is provided.

how to config it?

<img width="1789" alt="Screen Shot 2021-07-29 at 20 15 36" src="https://user-images.githubusercontent.com/3212570/127490188-23b530a1-58a2-4f43-a250-b03c95d4c061.png">

## Steps to reproduce

1. install code-server 3.11
2. `code-server --auth none`
3. open in browser
4. see error toast notification

### Expected

No error 

### Actual

https://user-images.githubusercontent.com/3806031/127692356-5d22ace9-a1ae-45db-8aa1-256548c878ca.mov

**Comment by jsjoeio** [comment]
Thanks for filing! I think we need to investigate this.

I noticed this happening in 3.11 - I wonder if something changed in VS Code upstream that we forgot to change. Any ideas @oxy @code-asher ?

**Comment by code-asher** [comment]
I can't think of anything off the top of my head. What are the
full reproduction steps?

**Comment by jsjoeio** [comment]
Updated description with repro steps!

**Comment by code-asher** [comment]
Oh you were able to reproduce like that? Odd, it didn't reproduce for
me. This couldn't somehow be related to the local OS being MacOS could
it? Seems unlikely.

**Comment by jsjoeio** [comment]
Hmm...could question. Here is the stack trace:

```javascript
ERR Unable to write to Folder Settings because no resource is provided.: Error: Unable to write to Folder Settings because no resource is provided.
    at b.reject (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:2403:15316)
    at b.resolveAndValidate (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:2403:19500)
    at b.doWriteConfiguration (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:2403:12506)
    at Object.factory (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:2403:12282)
    at y.consume (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:68:15342)
    at http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:68:15157
    at new Promise (<anonymous>)
    at y.queue (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:68:15081)
    at b.writeConfiguration (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:2403:12267)
    at y.writeConfigurationValue (http://localhost:8080/static/4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd/usr/local/Cellar/code-server/3.11.0/libexec/lib/vscode/out/vs/workbench/workbench.web.api.js:2403:41475)
```
Maybe something changed with how the configuration is stored locally on macOS?

**Comment by wjziv** [comment]
Chiming in to say I have the same experience every time I refresh the IDE window on a different OS.
Code-Server is hosted in a container by Unraid.

- Web Browser: chrome
- Local OS: chromeOS
- Remote OS: Unraid
- Remote Architecture: docker
- code-server --version: 3.11

**Comment by djasonweiser** [comment]
Also chiming in to say that this happens to me as well. 

- Web Browser: Firefox 90.0.2
- Local OS: MacOS 11.4
- Remote OS: Ubuntu 20.04.2
- Remote Architecture: used the install script?
- Code-server version: 3.11.1

**Comment by jsjoeio** [comment]
Thanks all for the notes! I've added this to the next upcoming milestone so we'll work on it soon.

**Comment by caochuansong** [comment]
thanks @jsjoeio

**Comment by jsjoeio** [comment]
I'm starting to work on this and taking notes here. I'll update this message as I go so I'm not spamming the issue with new comments each update.

## Notes

searching for "Unable to write to Folder Settings because no resource is provided" reveals `lib/vscode/src/vs/workbench/services/configuration/common/configurationEditingService.ts` which has a private method called `toErrorMessage` and a switch statement to handle each error case.

**Comment by jsjoeio** [comment]
@caochuansong @djasonweiser @aryasenna @wjziv can one of you confirm that this fixes it?

## Solution
1. Open Command Palette
2. Open "Preferences: Open Settings (JSON)
3. Look for "workbench.editorAssociations"
4. Change it to this:
```json
"workbench.editorAssociations": {
    "*.ipynb": "jupyter.notebook.ipynb"
},
```

And let me know if that fixes it?

**Comment by wjziv** [comment]
@jsjoeio 
This appears to resolve the notification! I haven't seen it come back in existing directories.

I noticed at the same time as I the "Unable to write..." notification, when I navigated to subdirectories which did not exist, behavior changed from: "automatically create the subdirectory" to the familiar message "Unable to write to folder settings..."

Now I get the following response:
> Unable to open 'new_subdir': Unable to read file 'vscode-remote://code.domain.com/config/workspace/dir/new_subdir' (Error: Unable to resolve non-existing file 'vscode-remote://code.domain.com/config/workspace/dir/new_subdir').

And it asks if I'd like to create the directory.

Sounds like a much better behavior, IMO!

**Comment by TeffenEllis** [comment]
@jsjoeio that's some incredible detective work. Incredible 👏🏻

**Comment by jsjoeio** [comment]
> This appears to resolve the notification! I haven't seen it come back in existing directories. 🎉

Hooray! Thank you for confirming!

> Unable to open 'new_subdir': Unable to read file 'vscode-remote://code.domain.com/config/workspace/dir/new_subdir' (Error: Unable to resolve non-existing file 'vscode-remote://code.domain.com/config/workspace/dir/new_subdir').

Weird...Well if you can easily reproduce, will you open an issue and I'll take a look? 

> However, there still exists a semi-related error on my end where Jupyter Notebooks aren't rendering... See #3874

Yeah, that's next on my list!

**Comment by rebelliousconformist** [comment]
Reopening this isssue. 
`Unable to open 'selfpractice': Unable to resolve resource vscode-remote://wsl%2Bubuntu-20.04/home/bapatnext/nac_dev/selfpractice.`

`Unable to write to Folder Settings because no resource is provided.`

getting the same problems again

vscode server is  VS Code Server for x64 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e)

vscode version is 

`1.63.0
7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
x64`

**Comment by jsjoeio** [comment]
@rebelliousconformist can you please open a new bug report with repro steps? Thank you!
