### ISSUE TITLE
Add support for live share

### ISSUE THREAD

**Issue by steven4547466** [cdr/code-server#388]
I recently got code-server running on my server, but I was unable to get live share. I know that you have to manually install it with the .vsix, which I did. However, the status bar item won't show up and I can't access any of it's commands from the command palette either. It does show that it's installed and enabled as well.
![Screenshot 2019-03-31 at 12 08 50 PM](https://user-images.githubusercontent.com/23726534/55291566-d5078c00-53ad-11e9-84e1-7b91d403d4f1.png)
Sorry if I'm not setting it up right and it's on my side, but I tried what I knew to add this extension.

**Comment by andreimc** [comment]
@steven4547466 git@github.com:devonlineco/ansible-roles.git --> I have support for liveshare here, you need to install vscode and install the ext from microsoft and symlink. It's a closed source extension. Also doesn't work unless you open vscode first then it works in code server

<img width="527" alt="Screen Shot 2019-04-01 at 2 02 46 pm" src="https://user-images.githubusercontent.com/1446134/55309199-40715c80-5487-11e9-9bfb-1b2d8178a12f.png">
<img width="1920" alt="Screen Shot 2019-04-01 at 2 03 08 pm" src="https://user-images.githubusercontent.com/1446134/55309201-436c4d00-5487-11e9-8f38-7f5b0ba41b5f.png">
<img width="1920" alt="Screen Shot 2019-04-01 at 2 03 29 pm" src="https://user-images.githubusercontent.com/1446134/55309208-49622e00-5487-11e9-84e4-5d01117ed114.png">
<img width="1920" alt="Screen Shot 2019-04-01 at 2 03 55 pm" src="https://user-images.githubusercontent.com/1446134/55309210-4e26e200-5487-11e9-9573-b35bd5954544.png">
<img width="1920" alt="Screen Shot 2019-04-01 at 2 05 24 pm" src="https://user-images.githubusercontent.com/1446134/55309221-55e68680-5487-11e9-9504-35a4ad42b0e7.png">

**Comment by steven4547466** [comment]
I have a virtual private server running on Ubuntu, I tried to install vscode, but it doesn't have a desktop I can view so I don't actually know how to download vscode on it or if I even can

**Comment by andreimc** [comment]
@steven4547466 I added an ansible role in the post above, you need to install x11 and a vnc server if you want to actually launch vscode, works pretty well. But yeah you need x11 and vnc to get started as it needs to launch in vscode for the first time then it works in code-server

**Comment by code-asher** [comment]
I gave this a go on v2 and it works up until I try to connect and then it just spins forever. Interestingly enough the same thing happens to me on local VS Code so I might just have something misconfigured but I haven't looked further into it yet.

**Comment by michaeldv-pg** [comment]
@code-asher Are there any ETA on Live Share?

**Comment by gotjoshua** [comment]
I managed to get the code-server running in a docker container and hack my way around the errors that arise when installing MS Live Share via vsix. I think that part of my solution belongs in the main repo but I didn't manage to get a full build working with an adapted Dockerfile in my fork (I guess due to build environment differences between docker-compose and travis-ci...)

So MS Live share is [easy to find](https://www.vsixhub.com/vsix/1507/) in vsix format online...
When I installed in a working docker container I got an error about `Couldn't find a valid ICU package` which was solved by extending the Dockerfile like this:
```Dockerfile
 FROM codercom/code-server:v2
 USER root
 RUN apt update && apt install icu-devtools -y
 USER 1000
```
Then the next error is related to "Proposed APIs" , which can be solved bu installing:
[Live Share Extension Pack 0.3.4](https://www.vsixhub.com/vsix/97/)

So then the cute little Live Share Button will show in the bottom bar, but clicking it will not succeed to login and give this error:
```
Starting collaboration session: [ms-vsliveshare.vsliveshare]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-vsliveshare.vsliveshare
```
Does anyone know how and where to implement that command line switch or run option?
I tried to add parameters to the entrypoint like this:
```
ENTRYPOINT ["dumb-init", "code-server", "--host", "0.0.0.0", "--enable-proposed-api", "ms-vsliveshare.vsliveshare"]
```
but that didn't seem to work : -(

any help?  it seems like i'm so close....

Note: This is also related to #173...

**Comment by sr229** [comment]
Due to licensing restrictions, we will not support Live Share.

**Comment by caioquirino** [comment]
Is there any way to reassess with Microsoft a way to change the licensing model for the LiveShare extension?

**Comment by jsjoeio** [comment]
@caioquirino I don't think they'd be interested in doing that since Coder/code-server is a competitor to Codespaces. You may try and ask them to change it though for the betterment of the community

**Comment by apoorvkh** [comment]
Just want to say that I am currently able to download and install the .vsix, and Live Share (1.0.5857) works for me on code-server (4.11.0).

**Comment by bilogic** [comment]
> Just want to say that I am currently able to download and install the .vsix, and Live Share (1.0.5857) works for me on code-server (4.11.0).

how did you download VSIX of 1.0.5857?

**Comment by bilogic** [comment]
This is the link https://marketplace.visualstudio.com/_apis/public/gallery/publishers/MS-vsliveshare/vsextensions/vsliveshare/1.0.5857/vspackage

Using Windows Chrome downloads the file as 6961167 bytes which installs properly.
But for some strange reason windows and linux cURL downloads it as 6,684,230 bytes which has a corruption error when installing, would be great if anyone has this figured out.

Note: I actually even copied the headers from Chrome, by right clicking on `curl (bash)` in the developer tools.

**Comment by Taolinyinjiu** [comment]
> This is the link https://marketplace.visualstudio.com/_apis/public/gallery/publishers/MS-vsliveshare/vsextensions/vsliveshare/1.0.5857/vspackage
> 
> Using Windows Chrome downloads the file as 6961167 bytes which installs properly. But for some strange reason windows and linux cURL downloads it as 6,684,230 bytes which has a corruption error when installing, would be great if anyone has this figured out.
> 
> Note: I actually even copied the headers from Chrome, by right clicking on `curl (bash)` in the developer tools.

I just clicked on your connection and was able to download to 5857.vsix, which works very well on code-server deployed on my linux server.Doesn't look like this version adds too many checks on vscode?
Thank you bilogic and apoorvkh for reminding us

**Comment by ZigZagT** [comment]
Just want to share the latest version of live share (v1.0.5941) has stopped working for me. I had to manually ralling back to 5857 and disable auto update.

**Comment by ghost** [comment]
Did someone get it running with current versions?
