### ISSUE TITLE
Ubuntu Chrome PWA can not use vimplugin esc key

### ISSUE THREAD

**Issue by whenSunSet** [cdr/code-server#3888]
## OS/Web Information

- Web Browser: Chrome 92.0.4515.107
- Local OS: Ubuntu 18
- Remote OS:debain
- `code-server --version`: code-server 3.10.2

## Steps to Reproduce

1.Code Server install vscodevim.vim
2.Open Chrome and Open Code-Server with PWA full screen or normal mode
3.input in Code-Server editor with vim insert mode, and pressed esc key

## Expected

vim mode change to normal mode

## Actual

input cursor disappeared, editor not unfocused 

please help me. thanks

**Comment by jsjoeio** [comment]
I couldn't reproduce locally.

## Video


https://user-images.githubusercontent.com/3806031/127900259-7003308c-a468-469d-92bb-bfd02e09c684.mov


Hmm... are you sure this isn't related to your vim extension settings? Mind sharing your `settings.json` and any relevant changes you've made to your config for the vscodvim extension?

**Comment by whenSunSet** [comment]
https://user-images.githubusercontent.com/16758988/127962832-960a707c-c2c1-4f8d-be18-713b9f56b138.mp4

this is my reproduce in mac os and chrome PWA

this is my setting.json
`{
    "editor.fontFamily": "monospace, Monaco, Menlo, 'Courier New'",
    "terminal.integrated.shell.linux": "/bin/zsh",
    "terminal.integrated.fontFamily": "'Hack Nerd Font'",
    "workbench.colorTheme": "Solarized Light",
    "redhat.telemetry.enabled": false
}`

this is my keybindings.js

`// Empty
[
    {
        "key": "ctrl+shift+alt+meta+1",
        "command": "breadcrumbs.focus",
        "when": "breadcrumbsPossible"
    },
    {
        "key": "ctrl+shift+;",
        "command": "-breadcrumbs.focus",
        "when": "breadcrumbsPossible"
    },
    {
        "key": "ctrl+shift+;",
        "command": "workbench.action.showCommands"
    },
    {
        "key": "f1",
        "command": "-workbench.action.showCommands"
    },
    {
        "key": "ctrl+shift+p",
        "command": "-workbench.action.showCommands"
    },
    {
        "key": "alt+b",
        "command": "workbench.action.quickOpen"
    },
    {
        "key": "ctrl+e",
        "command": "-workbench.action.quickOpen"
    },
    {
        "key": "ctrl+shift+tab",
        "command": "workbench.action.previousEditor"
    },
    {
        "key": "ctrl+pageup",
        "command": "-workbench.action.previousEditor"
    },
    {
        "key": "ctrl+tab",
        "command": "workbench.action.nextEditor"
    },
    {
        "key": "ctrl+pagedown",
        "command": "-workbench.action.nextEditor"
    },
    {
        "key": "ctrl+shift+alt+meta+3",
        "command": "workbench.action.quickOpenLeastRecentlyUsedEditorInGroup"
    },
    {
        "key": "ctrl+shift+tab",
        "command": "-workbench.action.quickOpenLeastRecentlyUsedEditorInGroup"
    },
    {
        "key": "ctrl+shift+alt+meta+3",
        "command": "workbench.action.quickOpenNavigatePreviousInEditorPicker",
        "when": "inEditorsPicker && inQuickOpen"
    },
    {
        "key": "ctrl+shift+tab",
        "command": "-workbench.action.quickOpenNavigatePreviousInEditorPicker",
        "when": "inEditorsPicker && inQuickOpen"
    },
    {
        "key": "ctrl+tab",
        "command": "workbench.action.nextEditorInGroup"
    },
    {
        "key": "ctrl+k ctrl+pagedown",
        "command": "-workbench.action.nextEditorInGroup"
    },
    {
        "key": "ctrl+shift+tab",
        "command": "workbench.action.previousEditorInGroup"
    },
    {
        "key": "ctrl+k ctrl+pageup",
        "command": "-workbench.action.previousEditorInGroup"
    },
    {
        "key": "ctrl+shift+alt+1",
        "command": "editor.action.replaceAll",
        "when": "editorFocus && findWidgetVisible"
    },
    {
        "key": "ctrl+alt+enter",
        "command": "-editor.action.replaceAll",
        "when": "editorFocus && findWidgetVisible"
    },
    {
        "key": "ctrl+shift+alt+1",
        "command": "search.action.replaceAll",
        "when": "replaceActive && searchViewletVisible && !findWidgetVisible"
    },
    {
        "key": "ctrl+alt+enter",
        "command": "-search.action.replaceAll",
        "when": "replaceActive && searchViewletVisible && !findWidgetVisible"
    },
    {
        "key": "ctrl+w",
        "command": "workbench.action.closeActiveEditor"
    },
    {
        "key": "ctrl+w",
        "command": "-workbench.action.closeActiveEditor"
    },
    {
        "key": "ctrl+alt+enter",
        "command": "extension.vim_ctrl+w",
        "when": "editorTextFocus && vim.active && vim.use<C-w> && !inDebugRepl"
    },
    {
        "key": "ctrl+w",
        "command": "-extension.vim_ctrl+w",
        "when": "editorTextFocus && vim.active && vim.use<C-w> && !inDebugRepl"
    },
    {
        "key": "ctrl+alt+enter",
        "command": "workbench.action.closeGroup",
        "when": "activeEditorGroupEmpty && multipleEditorGroups"
    },
    {
        "key": "ctrl+w",
        "command": "-workbench.action.closeGroup",
        "when": "activeEditorGroupEmpty && multipleEditorGroups"
    },
    {
        "key": "ctrl+shift+alt+1",
        "command": "workbench.action.lastEditorInGroup"
    },
    {
        "key": "alt+0",
        "command": "-workbench.action.lastEditorInGroup"
    },
    {
        "key": "ctrl+shift+alt+1",
        "command": "workbench.action.terminal.openNativeConsole",
        "when": "!terminalFocus"
    },
    {
        "key": "ctrl+shift+c",
        "command": "-workbench.action.terminal.openNativeConsole",
        "when": "!terminalFocus"
    },
    {
        "key": "ctrl+shift+alt+1",
        "command": "workbench.action.terminal.new"
    },
    {
        "key": "ctrl+shift+`",
        "command": "-workbench.action.terminal.new"
    },
    {
        "key": "alt+0",
        "command": "workbench.action.terminal.toggleTerminal"
    },
    {
        "key": "ctrl+`",
        "command": "-workbench.action.terminal.toggleTerminal"
    },
    {
        "key": "ctrl+n",
        "command": "workbench.action.files.newUntitledFile"
    },
    {
        "key": "ctrl+n",
        "command": "-workbench.action.files.newUntitledFile"
    },
    {
        "key": "ctrl+alt+h",
        "command": "workbench.action.navigateBack"
    },
    {
        "key": "ctrl+alt+-",
        "command": "-workbench.action.navigateBack"
    },
    {
        "key": "ctrl+alt+l",
        "command": "workbench.action.navigateForward"
    },
    {
        "key": "ctrl+shift+-",
        "command": "-workbench.action.navigateForward"
    },
    {
        "key": "ctrl+shift+w",
        "command": "workbench.action.closeWindow",
        "when": "!editorIsOpen && !multipleEditorGroups"
    },
    {
        "key": "ctrl+w",
        "command": "-workbench.action.closeWindow",
        "when": "!editorIsOpen && !multipleEditorGroups"
    },
    {
        "key": "f3",
        "command": "-workbench.action.terminal.findNext",
        "when": "terminalFindFocused && terminalProcessSupported || terminalFocus && terminalProcessSupported"
    }
]`

**Comment by jsjoeio** [comment]
Thank for the video! Are you saying the mouse cursor is disappearing?

I'm not sure what could be causing this from code-server's end 🤔 

Hmmm...a couple things come to mind:
- we're using different versions of the extension. I wonder if this is related to the extension 🤔 can you try downgrading the extension and seeing if that fixes it?
- you're overriding the font settings

Can you try removing this from your settings and see if it fixes the issue?

```json
{
  "editor.fontFamily": "monospace, Monaco, Menlo, 'Courier New'"
}
```

**Comment by whenSunSet** [comment]
i think i find the result why my cursor is disappearing

because my chrome used a plugin named vimium.

this plugin will make my cursor disappear when i pressed esc

Thanks for your help。 @jsjoeio

**Comment by jsjoeio** [comment]
OH! That makes more sense. Sure thing! Glad you found it 🎉
