### ISSUE TITLE
use npm instead of yarn

### ISSUE THREAD

**Issue by issac4892** [cdr/code-server#3896]
since yarn swallows all logs on ``yarn global add``, how about using npm and tell how to debug on problem? 
```
npm uninstall -g --unsafe-perm code-server > /dev/null 2>&1 //uninstall
npm install --loglevel verbose -g --unsafe-perm code-server //install wtih logging
```

**Comment by jsjoeio** [comment]
I _think_ we've had issues with `npm` not working in the past (hence why we encourage `yarn`), but maybe it's better now. And this should definitely go in our debugging/troubleshooting section. Thank you for the suggestion!
