### ISSUE TITLE
Unable to open projects in code-server

### ISSUE THREAD

**Issue by YunoGasai67** [cdr/code-server#3898]
after a bit of nginx tinkering i was able to get it to work, however i cannot open any projects, or folders. I click and it does nothing.

Currently using the latest version.

**Comment by YunoGasai67** [comment]
Turns out installing an extension solves this issue for whatever reason.

**Comment by jsjoeio** [comment]
That's very strange. Okay I'm going to close this out then if your issue is resolved.
