### ISSUE TITLE
iPadOS: Screen completely glitches when removing keyboard 

### ISSUE THREAD

**Issue by 7ua** [cdr/code-server#3916]
## OS/Web information
- Web Browser: Safari (using pwa version of code-server)
- Local OS: IPadOS 14.6
- Remote OS: IPadOS 14.6
- Remote Architecture:
- `code-server --version`:

## Steps to reproduce 
While using iPadOS 14.6
- Deploy code server on railway
- open code server in safari
- Press the share button
- Add to Home Screen
- Login
- Try to remove connection with your keyboard and try to use your hand

## Expected
Let me switch between keyboard & no keyboard normally on the pwa version

## Actually happens

https://user-images.githubusercontent.com/80481493/128528326-bd567e11-a819-4aea-9787-03dd742ed1d2.mov

## Also read

This issue can be reproduced in VS Code: Mac: No Windows: Unsure Linux: Unsure

When I use the non pwa version in normal safari I can switch between the two easily with no issues

**Comment by jsjoeio** [comment]
Hmm 🤔 I don't think this is related to code-server specifically (I could be wrong) and more so related to Settings on your iPad (though we should document). 

Do you have [Shortcuts disabled](https://github.com/microsoft/vscode/issues/108111#issuecomment-704605562)?

**Comment by 7ua** [comment]
> This happens when using the floating keyboard in PWA mode, and then focusing on a uneditable position.

Seems that this might be the issue. @jsjoeio

**Comment by awahlig** [comment]
I’m also having this issue. It happens only in PWA mode and indeed seems to be related to the Shortcuts setting (iPad Settings | General | Keyboard).

**The issue happens only when the Shortcuts setting is on.**

Turning it off and switching back to Code Server immediately fixes the glitch.

It’s reproducible on https://vscode.dev as well.

**Comment by oxkenshin** [comment]
In my case, this issue happens no matter "Keyboard->Shortcuts" is on or off.
