### ISSUE TITLE
Upgrade to VS Code 1.60

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#3917]
Upgrade to VS Code 1.59

**Comment by CAFA1** [comment]
how to upgrade to vs code 1.59?

**Comment by jsjoeio** [comment]
You can't unfortunately. We have to but we should have an update out soon!

**Comment by CAFA1** [comment]
./ci/dev/update-vscode.sh
can I use this script to update?

**Comment by mknj** [comment]
1.60 is out ;)

**Comment by jsjoeio** [comment]
> can I use this script to update?

On your personal code-server instance? No you can't :( 

> vscode 1.60 is out, it would be nice to upgrade vscode-server to 1.60 instead of 1.59

@TeffenEllis can confirm which version she is upgrading us to! But it's a WIP

**Comment by TeffenEllis** [comment]
@jsjoeio, @CAFA1,

That’s correct! We’re currently working through the upstream changes in 1.60.0 and should have a release out within this or next week.

**Comment by jsjoeio** [comment]
Awesome! Thanks for clarifying. I updated the issue title.
