### ISSUE TITLE
Add the possibility to keep the code on the server encrypted at rest to avoid intellectual property leaks to VPS operators

### ISSUE THREAD

**Issue by doplumi** [cdr/code-server#3927]
Doesn’t seem to be available atm.
Sockets are encrypted on transmission but the code files sit on the disk unencrypted. 
A curious VPS operator can read the disk and have all of my intellectual property. 

No bueno.

**Comment by HuJK** [comment]
Use encrypted file system such as fscrypt/eCryptfs/EncFS. I think this is not vs-code's jobs.

**Comment by doplumi** [comment]
Sounds reasonable. Thanks for the advice!
