### ISSUE TITLE
It doesn't work properly in CentOS 8.

### ISSUE THREAD

**Issue by EXStevens** [cdr/code-server#3930]
## OS/Web Information
- Remote OS:CentOS 8.2
- `code-server --version`:3.10.1

When I use it in CentOS 7, it works.
But when I use it in CentOS 8, it just doesn't work. 

I asked others for help, they just told me it doesn't support CentOS 8.

**Comment by balajib-b** [comment]
Hi @EXStevens, Im using CentOS Linux release 8.4.2105 with code server 3.11.0 without any issues. Requesting you to check by installing latest version of code server before submitting issues.

**Comment by EXStevens** [comment]
> Hi @EXStevens, Im using CentOS Linux release 8.4.2105 with code server 3.11.0 without any issues. Requesting you to check by installing latest version of code server before submitting issues.

Thanks, I just wanna know if it support now.
