### ISSUE TITLE
Error while launching code-server

### ISSUE THREAD

**Issue by mrfoxie** [cdr/code-server#3942]
## OS/Web Information

- Local OS: `Ubuntu 18.04.2 LTS (Bionic Beaver)`
- Remote OS: `Ubuntu 18.04.2 LTS (Bionic Beaver)`
- Remote Architecture: `aarch64`
- `code-server --version`: getting error while fetching
## Log
```
internal/modules/cjs/loader.js:888                      throw err;
  ^
                                                      Error: Cannot find module '/usr/lib/code-server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',                             requireStack: []
}
```
this is the error I got when I ran it on `Ubuntu 18.04.2 LTS (Bionic Beaver)`
## Screenshot
![img](https://i.imgur.com/Hd8mbN7.png)

## Notes

This issue can be reproduced in VS Code: Yes

**Comment by balajib-b** [comment]
@mrfoxie if you are submitting a new issue, please fill in the details asked in issue template for better reader understanding

**Comment by mrfoxie** [comment]
ok

**Comment by mrfoxie** [comment]
> @mrfoxie if you are submitting a new issue, please fill in the details asked in issue template for better reader understanding

I have changed it
