### ISSUE TITLE
add proxy from vscode terminal

### ISSUE THREAD

**Issue by seyeeet** [cdr/code-server#3946]
If we can activate proxy from terminal and vscode understand that for applying it to extension installation that would be great.
for example, I go to vscode terminal and activate the proxy, but it seems like that the ssh local installation for terminal is not using that proxy.

**Comment by jsjoeio** [comment]
Hmm...I'm not sure I fully understand. Maybe @code-asher does though?

**Comment by code-asher** [comment]
How are you activating the proxy? Is it through the
HTTP_PROXY/HTTPS_PROXY environment variables or something else?

If you are using those environment variables when spawning code-server
it's possible they aren't getting inherited by the terminal.

**Comment by seyeeet** [comment]
@code-asher I am doing that in the terminal of vscode via `module load proxy_activate`
can you tell me how you mean I should do it? sorry I am a newbie so I need am not sure what you mean

**Comment by code-asher** [comment]
Oh this is an Apache proxy? That won't affect the terminal, that only
affects web requests to your Apache webserver.

**Comment by seyeeet** [comment]
I am not actually what it is, I am sorry

**Comment by code-asher** [comment]
No worries. If you are trying to use code-server to download extensions
through a proxy you could try this:

```
HTTPS_PROXY=https://<proxy-domain> code-server --install-extension <extension-id>
```

**Comment by seyeeet** [comment]
Thank you for trying to help me! that is actually what I am trying to do.
should I run this command in the vscode terminal? or in my linux terminal?
Also, how I can install code-server?
I am running   
```
HTTPS_PROXY=http://MYPROXYADDRESSc ode-server  --install-extension ms-python.python-2021.8.1105858891.vsix
```
in the vscode terminal and im getting
```
bash: code-server: command not found
```

**Comment by code-asher** [comment]
I'm sorry for the delayed response; I've been out of the office.

Ahhhhhhh it looks like you are using VS Code remote and not
code-server. You will probably have better luck looking for help
upstream!

https://github.com/microsoft/vscode/search?q=http_proxy&type=issues

I am not sure if VS Code supports HTTP_PROXY on the terminal.

**Comment by jsjoeio** [comment]
@seyeeet since this is upstream, I'm going to label as so and we'll close the issue
