### ISSUE TITLE
Add docs around using CodeTogether for collaboration

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#3964]
- [ ] Test out in code-server
- [ ] Document how to use

Related:
- https://github.com/cdr/code-server/issues/33#issuecomment-890184201

**Comment by galesky** [comment]
At [duckly](https://duckly.com) I made some changes yesterday and now we also support code-server. 

This version is not released yet but I can send you a .vsix and would be glad to help out with this

**Comment by jsjoeio** [comment]
Oh awesome! Sure, feel free to open a new issue "Add docs around using duckly for collaboration" with the vsix, then I can try, ask questions and when I understand, I'll submit a PR to add to our docs. How does that sound?

**Comment by galesky** [comment]
Sound awesome, will do!

**Comment by bpmct** [comment]
oh whoops didn't realize this issue existed
