### ISSUE TITLE
Add docs around using duckly for collaboration

### ISSUE THREAD

**Issue by galesky** [cdr/code-server#3970]
- [x] Test out in code-server
- [x] Document how to use
- [x] Append extension URL (or `vsix` if not released yet)

Related:
* https://github.com/cdr/code-server/issues/33

**Comment by galesky** [comment]
I'll get the whole thing ready tomorrow along with instructions and examples so you can try it out :smiley:

**Comment by jsjoeio** [comment]
![](https://media.giphy.com/media/rmi45iyhIPuRG/giphy.gif)

**Comment by galesky** [comment]
Hey! 

I prepared some basic steps that will help you try it out. Let me know if I can help with anything. Some feedback on the UX would be awesome :)

This are the steps you have to follow, there is also a[ video version of them here](https://app.tella.tv/video/ckscblvor000308mmb2rfc28m/view)

### Step 1 - Install the extension

Right now this build is an insider one, so you will need the `.vsix`

This week we should release the correct one so you will be able to grab it from here
https://open-vsx.org/extension/gitduck/code-streaming

### Step 2 - Choose a username an login on duckly

Opening this URL (https://duckly.com/code-server/join?t=RTGPIQKC4F8_I9cFiB504m9) you will be able to choose an username and will automatically join a team I created

To share your code you first need to be in a room - like Discord

Feel free to create users and teams

### Step 3 - On the extension, login and start sharing

You can start sharing from code server or from another IDE (in that case, the code server one will the guest)

You should be able to see the code that is being shared both on the IDEs and on the duckly client on the web

Many users can make edit files at the same time, browser the shared folders, etc

**Comment by jsjoeio** [comment]
I got stuck on Step 3 (I think we broke something in code-server :( )

https://user-images.githubusercontent.com/3806031/130529692-1ddf6dd7-1147-4750-8588-efcfa9987e8d.mov

```javascript
Refused to load the script 'https://vscode-remote+localhost.vscode-resource.vscode-webview.net:8080/Users/jp/.local/share/code-server/extensions/gitduck.code-streaming-0.3.7/dist/duckly-web.js' 
because it violates the \following Content Security Policy directive: "script-src 'unsafe-eval' 'unsafe-inline' https://*.vscode-webview.net". 
Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

**Comment by galesky** [comment]
Hey!

It's a problem with the build I sent you, totally my fault, so sorry about that

I'll update a fixed version tomorrow

**Comment by jsjoeio** [comment]
Ah-HA! Okay, I'll use that one instead!

**Comment by jsjoeio** [comment]
Shoot, I'm still running into that same error :( 

I am guessing we need to fix on code-server's side.


https://user-images.githubusercontent.com/3806031/130661803-c0fac76b-e590-4c1f-9341-20e838dfa1e6.mov

**Comment by galesky** [comment]
That file that breaks the import should not be there at all, I'll check this later today, thanks for the video

**Comment by galesky** [comment]
That was on me, I missed an `env` flag while building the insiders version.

I own you a beer now :sweat_smile: 

Please try again using this version
[DUCKLY.zip](https://github.com/cdr/code-server/files/7042691/DUCKLY.zip)

**Comment by jsjoeio** [comment]
Now we're on a goose hunt. At least this time I'm getting a different error 😂

![image](https://user-images.githubusercontent.com/3806031/130833343-c6bf6ed3-3dba-4318-bab1-112d62f8e9d5.png)

```javascript
mainThreadExtensionService.ts:95 Activating extension 'gitduck.code-streaming' failed: Cannot find module './darwin-x64/wrtc.node'
Require stack:
- /Users/jp/.local/share/code-server/extensions/gitduck.code-streaming-0.3.7/dist/lib/wrtc/wrtc-node-binding.js
- /Users/jp/.local/share/code-server/extensions/gitduck.code-streaming-0.3.7/dist/extension.js
- /Users/jp/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js
- /Users/jp/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
- /Users/jp/.config/yarn/global/node_modules/code-server/lib/vscode/out/bootstrap-fork.js.
```

Is it expected I have this installed globally? https://github.com/node-webrtc/node-webrtc
