### ISSUE TITLE
Use GitHub's Wiki for all docs

### ISSUE THREAD

**Issue by nhooyr** [cdr/code-server#401]
https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

The workaround presented in that article makes it a very elegant model.

**Comment by NGTmeaty** [comment]
#191 was closed before? Are we going with this now?

**Comment by sr229** [comment]
I'll be assigning this to myself. Porting the docs should be easy to do.

**Comment by nhooyr** [comment]
Yea I'm not sure if this is the best move considering translations/versions will be hard to manage when the docs are not managed directly with the source code.

Deferring to @code-asher.

**Comment by sr229** [comment]
It's actually trackable since the wiki itself is a Git Repository @nhooyr

**Comment by nhooyr** [comment]
> It's actually trackable since the wiki itself is a Git Repository @nhooyr

It is, but it gets harder to manage since the wiki will be a different repository and so you'll have to remember to always update the wiki as the features get updated instead of managing all of that in a single PR/repository.

**Comment by sr229** [comment]
We can actually have the docs be a link to the wiki version and we can just push from `code-server.wiki` which could be automated anyways.

**Comment by code-asher** [comment]
It sounds like if I have a feature branch that also has doc changes I'd have to maintain two PRs in separate repos for the same feature which doesn't sound like a super fun time to me. I also don't like that if I go back through code-server's history I don't also get the documentation for code-server at that point in time.

**Comment by sr229** [comment]
> It sounds like if I have a feature branch that also has doc changes I'd have to maintain two PRs in separate repos for the same feature which doesn't sound like a super fun time to me. I also don't like that if I go back through code-server's history I don't also get the documentation for code-server at that point in time.

From what I can see we can definitely have pushing to the Wiki page automated via `docs/`. This is something I'll work on. For now you can settle with me maintaining it up to date for now.

**Comment by nhooyr** [comment]
> From what I can see we can definitely have pushing to the Wiki page automated via docs/. This is something I'll work on. For now you can settle with me maintaining it up to date for now.

At that point, why not just let people browse docs directly? The Wiki doesn't add anything other than a table of contents.

**Comment by code-asher** [comment]
Hmm I'm not really seeing the gain here either. :thinking:

**Comment by sr229** [comment]
Based on internal discussion, we just disabled Wiki. Closing.
