### ISSUE TITLE
[node.js fs] readdir with filetypes failed with error:  [Error: EACCES: permission denied, scandir '/home/coder/project']

### ISSUE THREAD

**Issue by ItzMiracleOwO** [cdr/code-server#4058]
## OS/Web Information

- Web Browser: Opera
- Local OS: Windows 10
- Remote OS: Synology
- Remote Architecture: Docker
- `code-server --version`: 3.10.2 387b12ef4ca404ffd39d84834e1f0776e9e3c005

## Steps to Reproduce

1. Create code server
2. Create some file in coder/project
3. See error in logs

## Expected

Files should show up

## Actual

Nothing show up but there is file in the file explorer

## Logs

[node.js fs] readdir with filetypes failed with error:  [Error: EACCES: permission denied, scandir '/home/coder/project'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/home/coder/project'
}

## Screenshot

![image](https://user-images.githubusercontent.com/76854136/131211557-14a29b64-9997-41b0-8abb-782cb5178974.png)

**Comment by jsjoeio** [comment]
Hmm...I can't reproduce this. This seems to be a permissions issue. My hunch says that the user in your Docker container does not have the right permissions. 

cc @code-asher how can they fix this?

**Comment by ItzMiracleOwO** [comment]
Hi there
Yes i know it is a perm issue but my another code-server with the same version work perfectly fine

**Comment by jsjoeio** [comment]
Ah I see. I didn't realize you were running 3.10.2. Does it happen in the latest version of code-server?

**Comment by ItzMiracleOwO** [comment]
Same thing happened in the latest version :/
btw i m using a Synology Device

**Comment by ItzMiracleOwO** [comment]
bruh i miss-click

**Comment by jsjoeio** [comment]
Hmm...okay so this is a permission issue in your Docker environment 🤔

@code-asher any ideas on how to troubleshoot or fix this?

**Comment by code-asher** [comment]
What is the Docker command you are running?

Does your user have permissions to the directory you are mounting?

**Comment by ItzMiracleOwO** [comment]
I was creating the container with Docker UI in synology DSM 6.2, and the other code server mounted with same dir works fine like I said before so it should have the right permissions

**Comment by code-asher** [comment]
I hear ya but we cannot reproduce with the information you have provided
so more information (like the commands you use to run the code-server
Docker images) may help us identify the issue.

**Comment by ItzMiracleOwO** [comment]
Hi, sorry for the latency
The commands we used to run the code-server is:
```
docker run -it --name code-server -p 8701:8080 \
  -v "mds/vm1/projects:/home/coder/project"
  codercom/code-server:latest
```

**Comment by ItzMiracleOwO** [comment]
Here is full log after startup, with the latest version
```
[main 2021-09-17T11:04:48.868Z] [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
[main 2021-09-17T11:04:48.875Z] [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
[2021-09-17T11:05:49.376Z] info  code-server 3.12.0 2661a690ac228872e8d1dc28ab6d33e8afc30add
[2021-09-17T11:05:49.386Z] info  Using user-data-dir ~/.local/share/code-server
[2021-09-17T11:05:49.434Z] info  Using config file ~/.config/code-server/config.yaml
[2021-09-17T11:05:49.434Z] info  HTTP server listening on http://0.0.0.0:8080 
[2021-09-17T11:05:49.435Z] info    - Authentication is enabled
[2021-09-17T11:05:49.435Z] info      - Using password from $PASSWORD
[2021-09-17T11:05:49.436Z] info    - Not serving HTTPS 
[2021-09-17T11:05:57.438Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14)
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5
[2021-09-17T11:05:57.476Z] error vscode is not running Error: vscode is not running
    at VscodeProvider.send (/usr/lib/code-server/out/node/vscode.js:121:19)
    at VscodeProvider.sendWebsocket (/usr/lib/code-server/out/node/vscode.js:117:14)
    at async /usr/lib/code-server/out/node/routes/vscode.js:205:5
[main 2021-09-17T11:06:06.950Z] [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
[main 2021-09-17T11:06:06.953Z] [File Watcher (chokidar)] Inotify limit reached (ENOSPC)
[node.js fs] readdir with filetypes failed with error:  [Error: EACCES: permission denied, scandir '/home/coder/project'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/home/coder/project'
}
```
The error changes after updating to latest

**Comment by jsjoeio** [comment]
> [2021-09-17T11:05:57.438Z] error vscode is not running Error: vscode is not running

Usually this log happens if you left code-server open in a tab or window. 

> [main 2021-09-17T11:06:06.950Z] [File Watcher (chokidar)] Inotify limit reached (ENOSPC)

I don't recognize this error 🤔 (though I have seen issues with chokidar before).

> [node.js fs] readdir with filetypes failed with error:  [Error: EACCES: permission denied, scandir '/home/coder/project'] {

same error 🤔

Noob question: is there a way to check if the Docker user running code-server has access to `/home/coder/project`? And can we give that user access?

**Comment by code-asher** [comment]
Huh, this is weird, I am not getting the permission error in the console
but I am unable to view or create files in the project directory.

Replicated in a Coder environment with this:

```
cd /tmp
mkdir test-dir
docker run -it --name code-server -p 8080:8080 \
  -v "test-dir:/home/coder/project"
  codercom/code-server:latest --auth none
# 1. Open 8080 in a browser
# 2. Browse to the project directory
# 3. Create or edit a file
```

I am able to `touch test-dir/hello` outside of Docker so I have
permissions.

```
$ whoami
coder
$ touch /tmp/test-dir/hello
$ ls -la /tmp/test-dir
total 8
drwxrwxr-x   2 coder          coder    4096 2021-09-17 12:16 .
drwxrwxrwt   1 root           root     4096 2021-09-17 12:09 ..
-rw-rw-r--   1 coder          coder       0 2021-09-17 12:16 hello
```

**Comment by code-asher** [comment]
Interesting, using an absolute path works (notice `$PWD/test-dir` instead of `test-dir`):

```
docker run -it --name code-server -p 8080:8080 \
  -v "$PWD/test-dir:/home/coder/project"
  codercom/code-server:latest --auth none
```

**Comment by jsjoeio** [comment]
That's very very strange 🤔 Nice debugging though. 

Do you think this is a code-server quirk or a Docker quirk?

**Comment by ItzMiracleOwO** [comment]
touch testdir/hello.js also works outside dockerin my case, even in a ubuntu containet, it still work but the code-server cannot read the file. But when i try to create a file in code-server, it appears both in the server and the mounted folder

**Comment by code-asher** [comment]
From what I can tell Docker will only mount the directory if it is an
absolute path. However, it will still create the mount path but it will
be owned by root (thus permissions are denied).

**Comment by ItzMiracleOwO** [comment]
Interestingly, when I try to install code server out of docker, everything works damn fine, so I guess that's an issue produced by docker. I will try to debug by reinstalling docker 🙃

**Comment by ItzMiracleOwO** [comment]
Alright guys, the same command works perfectly fine on Ubuntu 20.04, but it just won't work on DSM. I have no idea what the heck is happening...

**Comment by ItzMiracleOwO** [comment]
It So confusing... I just open a new droplet on digital ocean and test it... it worked totally fine...

**Comment by code-asher** [comment]
Strange, maybe wiping Docker clean and re-pulling the images will help?

**Comment by ItzMiracleOwO** [comment]
guys this is interesting
After adding `—pid=host` into the command, everything works fine!
I have never seen something like this before.. Any idea?

**Comment by ItzMiracleOwO** [comment]
I have just reinstalled the docker... The image works just fine.. Even without --pid=host
So I guess this is an installation issue?

**Comment by code-asher** [comment]
It could be!  Maybe related to cache somehow.

**Comment by jsjoeio** [comment]
Interesting! Should we close this now?

**Comment by ItzMiracleOwO** [comment]
Yes, thank for your help!
