### ISSUE TITLE
Command + X is not working.

### ISSUE THREAD

**Issue by imtoanle** [cdr/code-server#4061]
- code-server version: 3.11.1
- OS Version: Ubuntu 18.04

### Description
Ctrl+x seems not to work like in vs code. When nothing is selected the whole line gets cut in vs code. In code server, it seems like nothing happens unless some code is marked.

https://github.com/cdr/code-server/issues/533
I found same issue in the past. Can anyone confirm is it work on latest version.

### Steps to Reproduce
Set the cursor somewhere in the editor
Press Ctrl+x

**Comment by jsjoeio** [comment]
Are there any logs in the browser console or the server? (Can you fill out the entire bug report?)

Cmd + x works for me in 3.11.1


https://user-images.githubusercontent.com/3806031/131376140-84f14a7a-58e1-491b-8ebe-654f1924a037.mov

**Comment by imtoanle** [comment]
@jsjoeio I mean Command + X without select any text. That's mean Cut single line.
Below video is working function from Original VS Code.

http://g.recordit.co/9GOLLAI2jl.gif

**Comment by imtoanle** [comment]
@jsjoeio I had fresh install and it's working as expected. I'm not sure what i did in previous install.
Sorry for bothering. Thanks you so much.

**Comment by jsjoeio** [comment]
No worries - glad it was an easy fix! :)
