### ISSUE TITLE
Different / weird key mappings in terminal in Chrome

### ISSUE THREAD

**Issue by jmbarbier** [cdr/code-server#4087]
## OS/Web Information

- Web Browser: Chrome 93.0.4577.63 64 bits / Firefox 91.0.2 64 bits
- Local OS: Ubuntu 20.04
- Remote OS: Ubuntu 20.04
- Remote Architecture: amd4
- `code-server --version`: 3.11.1 c680aae973d83583e4a73dc0c422f44021f0140e

## Steps to Reproduce

1. With a french keyboard
2. Open a terminal under Chrome
3. Type some non-letter keys (example : @&é"'...)

## Expected

The letters @&é"' shoud appear in terminal

## Actual

- with firefox : the letters @&é"' appear in terminal (good)
- with chrome : the letters '123456 appear in terminal (bad)

## Screenshot

![Firefox result](https://user-images.githubusercontent.com/434239/131764593-a3390764-6082-4f2f-af26-8207d10c5f07.jpg)

![Chrome result](https://user-images.githubusercontent.com/434239/131764596-2412dae2-683f-4de9-b2a1-32374de783ee.jpg)

## Notes

This issue is only present in terminal, for editors all keys are OK for all browsers.
Changing vscode keyboard layout from us to fr have absolutely no effect.
Trying to remap keys in keyboardLayout.json have no effect.

Code-server runs from these 2 Dockerfiles :

https://dev.solidev.net/school/develspace/develspace-services/-/blob/develop/base/Dockerfile
https://dev.solidev.net/school/develspace/develspace-services/-/blob/develop/vscode/Dockerfile

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Hmm 🤔 I wonder if this is an upstream issue. Do you mind seeing if this can be reproduced in [Xterm.js](https://xtermjs.org/)?

In the meantime, I'll see if I can reproduce locally. Just gotta find a French keyboard...

**Comment by jsjoeio** [comment]
I'm using a French keyboard input on my macOS + Brave and I'm not sure if I'm reproducing or not 🤔 Very hard to tell since I'm not sure which keys I should be hitting. Let me know exactly what keys I should hit on a US QWERTY keyboard and I can try to reproduce.

https://user-images.githubusercontent.com/3806031/131890979-9e921850-f398-43e2-bd7a-3b2d5377d9e3.mov

Other thought, could this be a browser issue?

**Comment by bcouetil** [comment]
I have the exact same problem (and I'm french too).

In fact, the numbers act like an US QWERTY keyboard, so when hitting the first number key, we get a `1` and should get a `&`. Combined with `MAJ` we get a `!` and should get a `1`.

If this can help, I'm on Ubuntu and my keyboard is french but my language is English :

![Screenshot from 2021-09-05 22-33-23](https://user-images.githubusercontent.com/42612335/132140694-33ae1070-9ad4-4f55-87b1-544c5816c2f1.png)

**Comment by bcouetil** [comment]
And Opera browser does not have the problem, even being a chrome-like browser.

**Comment by jmbarbier** [comment]
@jsjoeio nice catch, the behaviour is exactly the same for xterm.js, in https://xtermjs.org/ for example (and also in jupyterlab).

@bcouetil exact, this seems to be a Chrome-only problem, i just tried https://w3c.github.io/uievents/tools/key-event-viewer.html on the following browsers

- Chromium Version 93.0.4577.63 (Build officiel) snap (64 bits)
- Edge Version 95.0.997.1 (Version officielle) dev (64 bits)
- Firefox 91.0.2 (64 bits)

![Edge](https://user-images.githubusercontent.com/434239/132164921-c8392c8d-e484-41c6-b3a5-aa461b4b1a08.jpg)
![Chromium](https://user-images.githubusercontent.com/434239/132164941-012e6570-7565-490a-90fe-75bfb389d327.jpg)
![Fifefox](https://user-images.githubusercontent.com/434239/132164952-5de225b6-2941-4cf0-b65e-47e857eb19e1.jpg)

while in Chrome, keypress and keydown events are mismatched :

![Chrome](https://user-images.githubusercontent.com/434239/132164988-49f963f6-93b5-4431-9c6e-22f16a5168c2.jpg)

So this is clearly an upstream issue, feel free to close this.

**Comment by jmbarbier** [comment]
Closing in favor of https://bugs.chromium.org/p/chromium/issues/detail?id=1245196

**Comment by jsjoeio** [comment]
Wow, that's cool to see you figured out it's upstream in Chromium! Thanks for double-checking and linking upstream!
