### ISSUE TITLE
Apk installation fail termux v 117

### ISSUE THREAD

**Issue by BaritskiyIllya** [cdr/code-server#4097]
INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Reconciliation failed...: Reconcile failed: Package com.termux has no signatures that match those in shared user com.termux; ignoring!
Devise: Oppo reno 2; Android 11; stock firmware ColorOs v 11.1

**Comment by jsjoeio** [comment]
Can you please open a bug report using the template?

Thanks!
