### ISSUE TITLE
code-server installing extension in wrong arch

### ISSUE THREAD

**Issue by dna2github** [cdr/code-server#4100]
## OS/Web Information

- Web Browser: Chrome 92
- Local OS: MacOS Big Sur (Interl CPU)
- Remote OS: Debian
- Remote Architecture: x86_64 (uname -m)
- `code-server --version`: 3.11.1

## Steps to Reproduce

- recently i built code-server from source on a Linux x86_64 machine:

```
git clone https://github.com/cdr/code-server
cd code-server
yarn
yarn run build:vscode
yarn run build
yarn run release
yarn run release:standalone
```

- then there is a folder `release-standalone` generated;
- removed `node_modules` inside the folder and package the whole folder into `code-server.tar.gz`.
- scp the tarball to another machine with Linux x86_64
- extract the tarball and do `yarn --prod`
- run code-server.
- when i go to extension marketplace, **insatall c/c++ extension by Microsoft (ms-cpptools)** and reload window, it show a warning message to tell me about not compatible with current arch, the extension is arm64 version.

## Expected

the extension should be installed with AMD64 version.

## Actual

the extension is in ARM64 version.

## Logs

 INFO Installing extension: ms-vscode.cpptools
 INFO Downloaded extension: ms-vscode.cpptools /opt/config/user/CachedExtensionVSIXs/ms-vscode.cpptools-1.5.1
 INFO Extracted extension to /opt/config/ext/.9b6f7f14-9de3-403d-a327-5f74abd24eb2: ms-vscode.cpptools
 INFO Renamed to /opt/config/ext/ms-vscode.cpptools-1.5.1
 INFO Installation completed. ms-vscode.cpptools
 INFO Extensions installed successfully: ms-vscode.cpptools

This issue can be reproduced in VS Code: unknown

**Comment by jsjoeio** [comment]
Hi there! This is a known issue. See https://github.com/cdr/code-server/issues/2120
