### ISSUE TITLE
code-server fail to install in termux with yarn

### ISSUE THREAD

**Issue by layaachmad** [cdr/code-server#4106]
## OS/Web Information

- Web Browser: none
- Local OS: none
- Remote OS: Termux 0.117 (Android 11) on POCO X3 NFC
- Remote Architecture: none
- `code-server --version`: none

## Steps to Reproduce

```yarn global add code-server```

## Expected

code-server Should Be Installed Manually

## Actual

Failed to install code-server on Termux Android 11 with yarn

## Logs

❯ yarn global add code-server                                                           yarn global v1.22.10
[1/4] Resolving packages...                                                             [2/4] Fetching packages...
[3/4] Linking dependencies...                                                           warning "code-server > @coder/logger@1.1.16" has unmet peer dependency "@google-cloud/logging@^4.5.2".                                                                          [4/4] Building fresh packages...                                                        [1/3] ⠄ argon2                                                                          [-/3] ⠄ waiting...
error /data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2: Command failed.
Exit code: 1                                                                            Command: node-pre-gyp install --fallback-to-build
Arguments:                                                                              Directory: /data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2
Output:                                                                                 node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.5                                              node-pre-gyp info using node@14.15.4 | android | arm64
node-pre-gyp info check checked for "/data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2/lib/binding/napi-v3/argon2.node" (not found)
node-pre-gyp http GET https://github.com/ranisalt/node-argon2/releases/download/v0.28.2/argon2-v0.28.2-napi-v3-android-arm64-unknown.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.2/argon2-v0.28.2-napi-v3-android-arm64-unknown.tar.gz                                                                                        node-pre-gyp WARN Pre-built binaries not installable for argon2@0.28.2 and node@14.15.4 (node-v83 ABI, unknown) (falling back to source compile with node-gyp)                  node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.2/argon2-v0.28.2-napi-v3-android-arm64-unknown.tar.gz                                                                                      gyp info it worked if it ends with ok                                                   gyp info using node-gyp@5.1.0                                                           gyp info using node@14.15.4 | android | arm64                                           gyp info ok                                                                             gyp info it worked if it ends with ok                                                   gyp info using node-gyp@5.1.0                                                           gyp info using node@14.15.4 | android | arm64                                           gyp info find Python using Python version 3.9.7 found at "/data/data/com.termux/files/usr/bin/python"                                                                           gyp info spawn /data/data/com.termux/files/usr/bin/python                               gyp info spawn args [                                                                   gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',                                                             gyp info spawn args   'binding.gyp',                                                    gyp info spawn args   '-f',                                                             gyp info spawn args   'make',                                                           gyp info spawn args   '-I',                                                             gyp info spawn args   '/data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2/build/config.gypi',                                                             gyp info spawn args   '-I',                                                             gyp info spawn args   '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',                                                                  gyp info spawn args   '-I',                                                             gyp info spawn args   '/data/data/com.termux/files/home/.cache/node-gyp/14.15.4/include/node/common.gypi',                                                                      gyp info spawn args   '-Dlibrary=shared_library',                                       gyp info spawn args   '-Dvisibility=default',                                           gyp info spawn args   '-Dnode_root_dir=/data/data/com.termux/files/home/.cache/node-gyp/14.15.4',                                                                               gyp info spawn args   '-Dnode_gyp_dir=/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp',                                                              gyp info spawn args   '-Dnode_lib_file=/data/data/com.termux/files/home/.cache/node-gyp/14.15.4/<(target_arch)/node.lib',                                                       gyp info spawn args   '-Dmodule_root_dir=/data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2',                                                             gyp info spawn args   '-Dnode_engine=v8',                                               gyp info spawn args   '--depth=.',                                                      gyp info spawn args   '--no-parallel',                                                  gyp info spawn args   '--generator-output',                                             gyp info spawn args   'build',                                                          gyp info spawn args   '-Goutput_dir=.'                                                  gyp info spawn args ]                                                                   gyp info ok                                                                             gyp info it worked if it ends with ok                                                   gyp info using node-gyp@5.1.0                                                           gyp info using node@14.15.4 | android | arm64                                           gyp info spawn make                                                                     gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]                              make: Entering directory '/data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2/build'                                                                         CC(target) Release/obj.target/libargon2/argon2/src/ref.o                                CC(target) Release/obj.target/libargon2/argon2/src/argon2.o                             CC(target) Release/obj.target/libargon2/argon2/src/core.o                               CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o                     CC(target) Release/obj.target/libargon2/argon2/src/thread.o                             CC(target) Release/obj.target/libargon2/argon2/src/encoding.o                           AR(target) Release/obj.target/argon2.a                                                  COPY Release/argon2.a                                                                   CXX(target) Release/obj.target/argon2/src/argon2_node.o                                 SOLINK_MODULE(target) Release/obj.target/argon2.node
make: https://github.com/xshin404: No such file or directory                            make: *** [argon2.target.mk:145: Release/obj.target/argon2.node] Error 127
make: Leaving directory '/data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2/build'
gyp ERR! build error                                                                    gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)                              gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)                                                                                    gyp ERR! System Linux 4.14.180-perf-g43fb8887b4f5                                       gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2/lib/binding/napi-v3/argon2.node" "--module_name=argon2" "--module_path=/data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2/lib/binding/napi-v3" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"   gyp ERR! cwd /data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2   gyp ERR! node -v v14.15.4                                                               gyp ERR! node-gyp -v v5.1.0                                                             gyp ERR! not ok
node-pre-gyp ERR! build error                                                           node-pre-gyp ERR! stack Error: Failed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2/lib/binding/napi-v3 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/data/data/com.termux/files/home/.config/yarn/global/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)                     node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 4.14.180-perf-g43fb8887b4f5                              node-pre-gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2
node-pre-gyp ERR! node -v v14.15.4                                                      node-pre-gyp ERR! node-pre-gyp -v v1.0.5
node-pre-gyp ERR! not ok                                                                Failed to execute '/data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/data/data/com.termux/files/home/.config/yarn/global/node_modules/argon2/lib/binding/napi-v3 --napi_version=7 --no

## Screenshot

![Screenshot_2021-09-05-18-07-27-632_com termux](https://user-images.githubusercontent.com/86137443/132124588-535699d8-b213-4088-877c-729c138d3bfb.jpg)

## Notes
Tried run npm install code-server but i got this

1199 verbose stack Error: argon2@0.28.2 install: `node-pre-gyp install --fallback-to-build`
1199 verbose stack Exit status 1
1199 verbose stack     at EventEmitter.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
1199 verbose stack     at EventEmitter.emit (events.js:315:20)
1199 verbose stack     at ChildProcess.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
1199 verbose stack     at ChildProcess.emit (events.js:315:20)
1199 verbose stack     at maybeClose (internal/child_process.js:1048:16)
1199 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
1200 verbose pkgid argon2@0.28.2
1201 verbose cwd /data/data/com.termux/files/home
1202 verbose Linux 4.14.180-perf-g43fb8887b4f5
1203 verbose argv "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/bin/npm" "install" "code-server"
1204 verbose node v14.15.4
1205 verbose npm  v6.14.10
1206 error code ELIFECYCLE
1207 error errno 1
1208 error argon2@0.28.2 install: `node-pre-gyp install --fallback-to-build`
1208 error Exit status 1
1209 error Failed at the argon2@0.28.2 install script.

**Comment by Nightmare-MY** [comment]
you can try download release for arm64,install nodejs/yarn in termux,and delete node_modules directory,delete `/lib/node`,create `/lib/node` input `node $@` ,exec `yarn install` on project root dir,

**Comment by jsjoeio** [comment]
Thank you @Nightmare-MY for posting that!

@layaachmad ^Let us know if that works

**Comment by Nightmare-MY** [comment]
> Thank you @Nightmare-MY for posting that!
> 
> @layaachmad ^Let us know if that works

I tried it. It worked

**Comment by jsjoeio** [comment]
Hooray! Well I think we can close this then? @layaachmad feel free to reopen if you have more issues.

**Comment by mengyanshou** [comment]
> Hooray! Well I think we can close this then? @layaachmad feel free to reopen if you have more issues.

sure~
