### ISSUE TITLE
Jupyter still not work after update to new version

### ISSUE THREAD

**Issue by wanningfe** [cdr/code-server#4110]
## OS/Web Information

- Web Browser: Safari
- Local OS: macOS 
- Remote OS: Manjaro Linux
- Remote Architecture: X84
- `code-server --version`: 3.11.1 c680aae973d83583e4a73dc0c422f44021f0140e

## Steps to Reproduce

1. Install Jupyter extension 
2. Create new blank notebook
3. 命令"Jupyter: 创建新的空白 Jupyter 笔记本"导致错误 (command 'jupyter.createnewnotebook' not found)

## Expected

new notebook created ,no error happend

## Actual

can't create new notebook

## Notes

This issue can be reproduced in VS Code: No

**Comment by shdowofdeath** [comment]
@wanningfe  any updates on this ?

**Comment by jsjoeio** [comment]
@shdowofdeath is this the same issue? https://github.com/cdr/code-server/issues/3874 Feel free to subscribe there since this is closed
