### ISSUE TITLE
terminal fails to launch | Windows 10

### ISSUE THREAD

**Issue by AirplanegoBrr** [cdr/code-server#4115]
## OS/Web Information

- Web Browser: Firefox
- Local OS: Windows 10
- Remote OS: Windows 10
- Remote Architecture: ??
- `code-server --version`: 3.11.1

## Steps to Reproduce

1. Start code server
2. Goto webpage
3. Try to open terminal. (It doesnt open)

## Expected

terminal should open

## Actual

terminal doesn't open and I get an error (see SS)

## Logs
https://pastebin.com/bvMnKWK3
(Sorry its a pastebin Its kinda a long log so meh)

## Screenshot

![image](https://user-images.githubusercontent.com/71111395/132373230-0bac733d-a073-4041-aa74-300f069ce658.png)

## Notes

Sorry if im just dumb I do that sometimes.
code-server is installed with yarn 
`Yarn -v`: 1.22.11
`node -v`: v16.8.0
If I try to install `vscode` (with yarn) code-server stops working and I just get a 501 error everytime I goto the site (prob just dumb)
code-server WAS working on my WSL ubuntu but I moved to windows as I dont like moving files between WSL and windows
I am having this issue on BOTH my computers (I am trying to run 2 diff code-servers and yes they ARE on diff ports)

This issue can be reproduced in VS Code: No
 
 (Edit 1: Adding notes)

**Comment by bpmct** [comment]
This error usually happens when VS Code does not properly build. Could you try uninstalling code-server and installing again?

```sh
yarn global remove code-server
yarn global remove vscode
```

I would also recommend using a terminal such as git bash to install code-server and run the postinstall script.

**Comment by AirplanegoBrr** [comment]
Ok im not 100% what fixed it but I installed Visual Studio installer and got Visual Studio Build tools 2019 then set the msvs_verison to 2019 and then I reinstalled code-server thanks so much for your help!! 😄 I also installs NVM for windows if that did anything

`npm config set msvs_version 2019`
(Not sure it I close this or not)

**Comment by bpmct** [comment]
Glad you got it working! I'll close this and link to the PR in our running Windows 10 thread (#1397)
