### ISSUE TITLE
Notify users of new github web editor

### ISSUE THREAD

**Issue by sharedrory** [cdr/code-server#4123]
A couple of weeks ago, github added a web based editor. Using it is simple, change the url to github.dev or press `.` in any repo.

While this version of vscode is limited as it has no backend I think it can be useful for quick edits/contributions.

Perhaps let users know they can use it as an alternative if they cannot setup code-server or if they can't deploy it to a cloud provider or aren't able to pay for github codespaces.

I'm not saying it is hard to setup code-server (its very easy actually).

https://docs.github.com/en/codespaces/developing-in-codespaces/web-based-editor

**Comment by bpmct** [comment]
We can update the FAQ to include this, we also mention Codespaces here, and it could use a refresher. https://coder.com/docs/code-server/v3.12.0/FAQ#whats-the-difference-between-code-server-and-vs-code-codespaces.

I use GitHub's web editor to inspect repos but an IDE such as code-server or VS Code to make/test changes, this distinction is important
