### ISSUE TITLE
code-server --cert keep giving error even on correct use

### ISSUE THREAD

**Issue by Unstable0** [cdr/code-server#4134]
## OS/Web Information

- Web Browser: Safari
- Local OS: macOS Monterey Beta 6
- Remote OS: Ubuntu Server 20.04
- Remote Architecture: ARM64? (I'm not sure what to put here but it's Raspberry Pi 4 Model B 8GB RAM)
- `code-server --version`: 3.11.1 c680aae973d83583e4a73dc0c422f44021f0140e

## Steps to Reproduce

1. I did many times didn't work
2. AdGuard Home can detect it
![Screen Shot 2564-09-10 at 3 19 41 PM](https://user-images.githubusercontent.com/46888825/132823317-1d9cf263-66c9-40db-b21c-014deacbed13.png)

3.it's so annoying

## Expected

It should use my certificate i got from letsencrypt

## Actual

It kept saying stupid error of 'Please specify at least one file or folder' even when i specified the file

![Screen Shot 2564-09-10 at 3 13 15 PM](https://user-images.githubusercontent.com/46888825/132822399-f7b10e39-cadf-464a-9977-2aaaff836f58.png)

## Logs

First run code-server with at least debug logging (or trace to be really
thorough) by setting the --log flag or the LOG_LEVEL environment variable. -vvv
and --verbose are aliases for --log trace. For example:

code-server --log debug >>> I did code-server --log debug and it said same error 
![Screen Shot 2564-09-10 at 3 14 58 PM](https://user-images.githubusercontent.com/46888825/132822618-a7b3effb-7f09-4288-8826-168705d0cd76.png)
so i guess i can't provide the logs ._.
![Screen Shot 2564-09-10 at 3 16 35 PM](https://user-images.githubusercontent.com/46888825/132822833-bba8e25b-9047-43d3-87ac-6bc70f10efb1.png)
Btw --verbose doesn't even work

Once this is done, replicate the issue you're having then collect logging
information from the following places:

    1. The most recent files from ~/.local/share/code-server/coder-logs. > I can't find that file, it doesn't exist
    2. The browser console.
    3. The browser network tab.

Additionally, collecting core dumps (you may need to enable them first) if
code-server crashes can be helpful.

## Screenshot

![Screen Shot 2564-09-10 at 3 17 53 PM](https://user-images.githubusercontent.com/46888825/132823131-d6fb3157-c5ee-4192-8fb0-b80373819cb6.png)
![Screen Shot 2564-09-10 at 3 17 58 PM](https://user-images.githubusercontent.com/46888825/132823142-2b2a92ab-3a46-49e7-8794-4179fc1ee60b.png)

## Notes

This issue can be reproduced in VS Code: No. it's code-server bug

**Comment by jsjoeio** [comment]
Hi there! Sorry to hear you're having trouble. Do you mind updating the reproduction steps? If you provide clear steps for how you encountered this error, I'd be happy to test locally. That will help us help you faster. Thanks!

**Comment by Unstable0** [comment]
I don't know how it happened, first i tried installing code-server with npm but it told me to use v14 but im v16 so i had to downgrade it, after downgrading i tried to install again and it stuck on **yarn add v1.11** something like that and so i cancelled the installation and tried other method and it works. Maybe thats because why it error? 
I don't know tho, in the settings i have cert set to true and port on 2083

**Comment by Unstable0** [comment]
Oh wait never-mind, you meant the reproduction steps not how it happened.

**Comment by Unstable0** [comment]
Yeah its still happening, i reinstalled and the issue still occur.

**Comment by Unstable0** [comment]
the issue was solved, It didn't work because i ssh my machine.
