### ISSUE TITLE
Cannot open code-server

### ISSUE THREAD

**Issue by sajjad-ali60** [cdr/code-server#4155]
## OS/Web Information

- Web Browser: Google Chrome
- Local OS: Android 6.0.1 (Marshmallow) 
- Remote OS: Ubuntu 18.04.6
- Remote Architecture: armv7l
- `code-server --version`: code-server-3.11.1

## Steps to Reproduce

1. I had installed my Ubuntu in [UserLAnd](https://play.google.com/store/apps/details?id=tech.ula) application on my android phone by following steps from [this](https://www.how2shout.com/how-to/how-to-install-ubuntu-linux-on-android-without-root.html) article. I am also mentioning them below.
2. Install [UserLAnd](https://play.google.com/store/apps/details?id=tech.ula) application from Google Playstore and after opening it just tap on the ubuntu in distributions sections.
3. Set the **Username** and **Password** *(for localhost)* and **VNC password** and it will automatically download *ubuntu-rootfs* fle and setup the machine.
4. Update and Upgrade the ubuntu as generally by `sudo apt-get update` and `sudo apt-get upgrade`.
5. Install `wget` package by `apt install wget -y`
6. After installing `wget` download the code-server asset in ubuntu by `wget https://github.com/cdr/code-server/releases/download/v3.11.1/code-server-3.11.1-linux-arm64.tar.gz`
7.  After download done Extract it by `tar -xvf code-server-3.11.1-linux-arm64.tar.gz` . 
8. Adter extracting head towards the bin directory located in *code-server-3.11.1-linux-arm64* by `cd code-server-3.11.1-linux-arm64/bin`
9. At last set the password for vs code by `export PASSWORD="password"` and execute the file *code-server* in bin directory by `./code-server`

## Expected

The command `./code-server` executes the file and generates localhost port number. I would open the browser and type the port number to access the code-server

## Actual

The file does not execute and generates an error instead of assigning a port number to access code-server. 
**Error:** ./code-server: 36: exec: /home/ubuntu/code-server-3.11.1-linux-arm64/lib/node: not found
and also shown in screenshot below
## Screenshot
![Screenshot_20210913-204317](https://user-images.githubusercontent.com/90617891/133115628-0f7dd746-fe48-4945-a84f-ec1ef6acdc4e.png)

## Notes

This issue can be reproduced in VS Code: Yes/No Yes

**Comment by jsjoeio** [comment]
Interesting 🤔

Just a guess but what happens if you run `code-server-3.11.1-linux-arm64/bin/code-server`? 

And can you also run `node --version` just to confirm your Node version?

**Comment by sajjad-ali60** [comment]
here's the result sir 
![Screenshot_20210913-231515](https://user-images.githubusercontent.com/90617891/133135630-74f48fde-bf53-4f23-ab3a-fb0be9c31813.png)

**Comment by jsjoeio** [comment]
Oh...well that seems like a big issue. You need Node to user code-server so I would install that and try again

**Comment by sajjad-ali60** [comment]
> Oh...well that seems like a big issue. You need Node to user code-server so I would install that and try again

i had already installed node by `sudo apt install npm`
and output is shown in the screenshot below in which the error remains intact.. 😢
![Screenshot_20210914-012603](https://user-images.githubusercontent.com/90617891/133151921-75b200c3-90cf-4497-97d1-d06aa1b6de81.png)

**Comment by jsjoeio** [comment]
Hmm... you have node 8.10.0 though. code-server needs v14 or higher 😢 Can you try upgrading?

**Comment by sajjad-ali60** [comment]
i don't understand that it already prompt that that you have latest version. can you guide me how to upgrade it to latest version because I only get this method from the internet.
![Screenshot_20210914-022405](https://user-images.githubusercontent.com/90617891/133158926-ce7b1271-3a1f-4db9-bd6b-3c7db8d33dbb.png)

**Comment by jsjoeio** [comment]
I am no expert, but it looks like `sudo apt install npm` would install `npm`. We want to upgrade node. 

```shell
sudo apt update && sudo apt install nodejs
```

Try that and then run `node -v` and see what you get.

By the way, here is a [handy article](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-18-04).

If you're comfortable, I would try the NVM approach (that's what I use). It's halfway down in that article.

**Comment by amiria703** [comment]
Not a actual solution for your problem, but try out [termux](https://termux.com/), I've already ran code-server in it successfully without pain

**Comment by sajjad-ali60** [comment]
Issue solved...
As i mentioned at top in OS web informtion my remote architecture is armv7l.
The latest version include 32 bit architecture.
