### ISSUE TITLE
Add docs for collaborating with CodeTogether

### ISSUE THREAD

**Issue by bpmct** [cdr/code-server#4157]
Document using CodeTogether with code-server

Document how to:
- [x] Download extension (from their website)
- [x] Run in code-server (needs `--enable-proposed-api` config/flag)
- [x] Update extension (edit: they are on open-vsx)

**Comment by toddewilliams** [comment]
Thanks for adding these steps for using CodeTogether with code-server! By posting here I'll be monitoring this thread to see if any questions or issues arise.
