### ISSUE TITLE
welcome page shows 404 not found

### ISSUE THREAD

**Issue by fbirlik** [cdr/code-server#4173]
## OS/Web Information

- Web Browser: chrome
- Local OS: mac/linux
- Remote OS: ubuntu-18.04, ubuntu-20.04
- Remote Architecture: amd64
- `code-server --version`: 3.12.0

## Steps to Reproduce

1. upgrade from 3.11.1 using 3.12.0 deb package

![Screen Shot 2021-09-15 at 3 35 45 PM](https://user-images.githubusercontent.com/31392854/133506058-c1e3a6e5-8e8d-456d-8b41-3bf2d2fcdb51.png)

**Comment by fbirlik** [comment]
For ubuntu-20.04
Restarting service manually fixes the issue:
`sudo service code-server@ubuntu restart`

I believe deb package pre-install and post-install hooks don't touch the active service.

For ubuntu-18.04, an additional systemd daemon-reload needed as follows:
`sudo systemctl daemon-reload`
`cloud@ares:~$ sudo service code-server@cloud restart`

**Comment by jsjoeio** [comment]
Awesome! Thanks for reporting this @fbirlik and posting the fix! Should we close this?

**Comment by fbirlik** [comment]
Yes, definitely.  I don't see any other problems related to startup.
