### ISSUE TITLE
Add testing guidelines

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#4177]
I would like to add a section to `MAINTAINING` which adds Testing Guidelines. This should explain:
- how testing works in code-server
- where to put your tests
- how to figure out what needs more tests
- how tests work in CI

**Comment by bpmct** [comment]
We might want to add sections/instructions for manually testing things that don't have tests yet (such as the postinstall script or things to test post-release on different operating systems)

**Comment by jsjoeio** [comment]
Good idea!
