### ISSUE TITLE
Cannot edit default key bindings

### ISSUE THREAD

**Issue by sortedcord** [cdr/code-server#4181]
## OS/Web Information

- Web Browser: Vivaldi | 4.2.2406.42 (Stable channel)
- Local OS: Windows 10 19043
- Remote OS: Ubuntu Server 20.0 LTS
- Remote Architecture: amd64
- `code-server --version`: 3.11.1

## Steps to Reproduce

1. Go to Preferences > Open default Shortcuts
2. Try to delete a keybinding

## Expected

The keybinding should get deleted, edited

## Actual

Nothing happens and no changes take place

The same is the case with the default keybings file. It's read-only and I cannot edit it. How do I change the default bindings?

**Comment by jsjoeio** [comment]
I believe you have to refresh the page for the changes to take affect. See this:

## Video

https://user-images.githubusercontent.com/3806031/133655144-1c29b79e-cfb7-4f02-b4ed-e3a00417a2ad.mov

Let me know if that works!

**Comment by sortedcord** [comment]
Yeah, that was it. Thank you!
