### ISSUE TITLE
Package 3.12.0 wrong arm64 architecture

### ISSUE THREAD

**Issue by stan-kondrat** [cdr/code-server#4183]
Looks like latest 3.12.0 release has wrong architecture or file naming:

```sh
wget https://github.com/cdr/code-server/releases/download/v3.12.0/code-server_3.12.0_arm64.deb
sudo dpkg -i code-server_3.12.0_arm64.deb 
dpkg: error processing archive code-server_3.12.0_arm64.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 code-server_3.12.0_arm64.deb
```

Package 3.11.1 works well:
```sh
wget https://github.com/cdr/code-server/releases/download/v3.11.1/code-server_3.11.1_arm64.deb
sudo dpkg -i code-server_3.11.1_arm64.deb 
Selecting previously unselected package code-server.
(Reading database ... 140538 files and directories currently installed.)
Preparing to unpack code-server_3.11.1_arm64.deb ...
Unpacking code-server (3.11.1) ...
Setting up code-server (3.11.1) ...
```

Ubuntu 21.04 arm64 as guest at UTM Apple M1 host

**Comment by mhhakim** [comment]
Having the same issue on oracle ARM instance.

<pre>
$ sudo dpkg -i code-server_3.12.0_arm64.deb
dpkg: error processing archive code-server_3.12.0_arm64.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 code-server_3.12.0_arm64.deb
</pre>

**Comment by jsjoeio** [comment]
Thanks for reporting this! Yeah, I think we missed a step when we redid our packaging. We're investigating this!

**Comment by jsjoeio** [comment]
We just uploaded new assets to the 3.12.0 release [here](https://github.com/cdr/code-server/releases/tag/v3.12.0). Can you try again and let us know if it works?

**Comment by stan-kondrat** [comment]
Thank you, it works!

```
sudo dpkg -i code-server_3.12.0_arm64.deb 
(Reading database ... 140521 files and directories currently installed.)
Preparing to unpack code-server_3.12.0_arm64.deb ...
Unpacking code-server (3.12.0) over (3.11.1) ...
Setting up code-server (3.12.0) ...
```
