### ISSUE TITLE
Not version 3.12.0 on docker hub repository.

### ISSUE THREAD

**Issue by aleleba** [cdr/code-server#4188]
## OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

## Steps to Reproduce

1. There are not a version 3.12.0 on docker hub repository.

## Expected

There should be a docker hub image.

## Actual

There are not a version 3.12.0 on docker hub repository.

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by jsjoeio** [comment]
Thanks for opening this! We're aware and sharing updates here: https://github.com/cdr/code-server/discussions/4178
