### ISSUE TITLE
css/js doesnt work on proxy (plain text site on npm start)

### ISSUE THREAD

**Issue by TheAlphaReturns** [cdr/code-server#4216]
## OS/Web Information

- Web Browser: Opera GX
- Local OS: Windows
- Remote OS: Linux
- Remote Architecture: amd64
- `code-server --version`: 3.12

## Steps to Reproduce

1. Clone and deploy code-server on railway
2. Make a html/js/css project with node.js (I am working on https://github,com/TheAlphaReturns/unblocked-sites)
3. Run npm install/npm start
4. open (site)/proxy/(port)
5. There is no css, It is a plain-text site

## Expected
CSS Loads

## Actual
CSS Doesnt load

Note that this issue can occur on repl.it, and other online ide's

**Comment by jsjoeio** [comment]
Hmm 🤔 I wonder what it could be. Are there any logs in the browser console?

Do you see anything in the Network tab either?

I wonder if it's the browser. Does this happen with other browsers like Chrome/Firefox?

**Comment by TheAlphaReturns** [comment]
I have used both, it doesn't work. If I try a local environment on my computer, it will work (so there is nothing wrong with my code). I mostly use code-server for working on my Chromebook, which can't run node.js locally. This issue occurs on repl.it, stackblitz, google cloud ide, and other vscode-based IDEs.

GitPod _does_ work but it got blocked by my school's network, so I am unable to use it.

**Comment by jsjoeio** [comment]
> This issue occurs on repl.it, stackblitz, google cloud ide, and other vscode-based IDEs.

Oh, so this isn't specific to code-server then.

What if you use React? Would that work?

**Comment by TheAlphaReturns** [comment]
ill try it.

**Comment by TheAlphaReturns** [comment]
Also edit: gitpod got unblocked (yay) but now the bug occurs on their site too.

**Comment by jsjoeio** [comment]
Hmm...if it occurs in all these web IDES, then it's probably worth opening an issue upstream

**Comment by jsjoeio** [comment]
Closing this but feel free to open a Discussion if you need more help!
