### ISSUE TITLE
Run extensions in production mode 

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#4219]
> ExtensionContext.extensionMode (passed to activate) is set to ExtensionMode.Development (integer value of 2) instead of Production. In other words, code-server runs extensions in non-production mode, which my extension took as a sign to enable that devserver shortcut. Not really a problem, if it weren't for the next problem

@SchoofsKelvin

Originally posted: https://github.com/cdr/code-server/discussions/4075#discussioncomment-1363660

Related: https://github.com/SchoofsKelvin/vscode-sshfs/issues/279

**Comment by jsjoeio** [comment]
cc @TeffenEllis (I figured you would find this interesting! Probably something we did a long time ago if I had to guess?)

**Comment by benz0li** [comment]
Related: https://github.com/REditorSupport/vscode-R/issues/275#issuecomment-929253126

**Comment by benz0li** [comment]
This issue seems to be resolved with v4.0.0.

**Comment by jsjoeio** [comment]
Woohoo! Thank you for confirming @benz0li 

I'll close this for now then.
