### ISSUE TITLE
Installing on Termux failed due to Node version

### ISSUE THREAD

**Issue by AbdullahBinJahed** [cdr/code-server#4225]
## OS/Web Information

Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.117+ #1 SMP PREEMPT Wed May 27 17:13:44 WIB 2020 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 6

## Steps to Reproduce

1. yarn global add code-server

## Expected

it should work

## Actual

![Screenshot_2021-09-23-13-05-47-327_com termux](https://user-images.githubusercontent.com/39275638/134466937-169bc8ff-fd55-445a-8d79-7611f1852a60.jpg)

## Screenshot

also tried with npm ...
![Screenshot_2021-09-23-13-08-26-320_com termux](https://user-images.githubusercontent.com/39275638/134467270-7b80888b-c324-4240-9349-10af39ea2b1d.jpg)

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by etienne1911** [comment]
Same issue here. 
Nodejs version installed with termux is 16 but code-server expects 14...
Tried also with ` --ignore-engines` flag set in `yarn` but doesn't help much..

**Comment by AbdullahBinJahed** [comment]
> Same issue here.
> Nodejs version installed with termux is 16 but code-server expects 14...
> Tried also with ` --ignore-engines` flag set in `yarn` but doesn't help much..

i uninstalled nodejs and installed nodejs-lts by ```pkg i nodejs-lts``` which is node 14 ... then yarn command worked and it did installed but can't download any extension on it

**Comment by jsjoeio** [comment]
Hmm...I think this is because we use `= 14` in our `package.json`

https://github.com/cdr/code-server/blob/main/package.json#L121-L122

@TeffenEllis should we change this to `>= 14`?

**Comment by Vaitek** [comment]
Seems i have the same problem. After installing nodejs-lts and upgrading code-server any attempts to install extensions was finished with "extension because it is not compatible with the current version of VS Code (version 1.60.0)." message...

**Comment by AbdullahBinJahed** [comment]
> Seems i have the same problem. After installing nodejs-lts and upgrading code-server any attempts to install extensions was finished with "extension because it is not compatible with the current version of VS Code (version 1.60.0)." message...

same problem here ...
btw ... something related ...
https://github.com/vhqtvn/VHEditor-Android

**Comment by jsjoeio** [comment]
> After installing nodejs-lts and upgrading code-server any attempts to install extensions was finished with "extension because it is not compatible with the current version of VS Code (version 1.60.0)." message...

I think that's a different problem unfortunately. We need to investigate that further as well.

**Comment by jawnsy** [comment]
@Vaitek @AbdullahBinJahed I'm curious why you are installing from source, rather than using our install.sh script -- can you provide any details on that?

The binary builds include the version of Node.js that we build and test with, which should be a more seamless experience than building from source, especially with a version of Node.js (16) that we do not currently test with. Is it because of a processor architecture difference; are we missing builds to make things more compatible?

> i uninstalled nodejs and installed nodejs-lts by pkg i nodejs-lts which is node 14 ... then yarn command worked and it did installed but can't download any extension on it

I think if you can use Node 14 (whether via nodejs-lts or from Nodesource), then that's a better solution, and we can (as a separate issue) help you debug the extension issue.

**Comment by AbdullahBinJahed** [comment]
> @Vaitek @AbdullahBinJahed I'm curious why you are installing from source, rather than using our install.sh script -- can you provide any details on that?
> 
> The binary builds include the version of Node.js that we build and test with, which should be a more seamless experience than building from source, especially with a version of Node.js (16) that we do not currently test with. Is it because of a processor architecture difference; are we missing builds to make things more compatible?
> 
> > i uninstalled nodejs and installed nodejs-lts by pkg i nodejs-lts which is node 14 ... then yarn command worked and it did installed but can't download any extension on it
> 
> I think if you can use Node 14 (whether via nodejs-lts or from Nodesource), then that's a better solution, and we can (as a separate issue) help you debug the extension issue.

uhhh... what ? I didn't got most of it ...
installing from source ? I just typed ``` yarn global install code-server ``` .
what install.sh script ? i didn't even git clone it . Processor arch type ? well i'm using a armv7l 32 bit Android phone.

With npde-lts it code-server does install but installing extensions doesn't work .. It just says code-server is old version and newer version is required
