### ISSUE TITLE
V3.12.0 cannot display image, pdf, and preview markdown!

### ISSUE THREAD

**Issue by liaomingg** [cdr/code-server#4238]
## OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`: 3.12.0

## Steps to Reproduce

1. open image, or pdf or markdown file. (installed extensions of pdf and markdown, tested by vscode.)
2.
3.

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by jsjoeio** [comment]
Unfortunately, I cannot reproduce this.

<img width="1792" alt="Screen Shot 2021-09-24 at 10 29 57 AM" src="https://user-images.githubusercontent.com/3806031/134716671-956cca01-f026-42ed-8240-763f5eea6d58.png">

For PDFs, you need to use a separate extension.

Can you please fill out the bug report and we'll see if we can help?

Are you using accessing code-server via HTTPS?

**Comment by liaomingg** [comment]
Thanks,

I use the url: http://0.0.0.0:6008.

Web Browser: Google Chrome.
Local OS: MacOS
Remote OS: Ubuntu16.04
Remote Architecture: X86-amd64
code-server --version: 3.12.0

I installed the code-server by release file: **code-server-3.12.0-linux-amd64.tar.gz.**
I have reinstalled many times, but still cannot display image, pdf and preview markdown. what's error with me?
and how to export the logs?

 - code server display error
![coder-server-error](https://user-images.githubusercontent.com/26960050/134753507-db7688e9-6b7f-4c0d-9dbb-a1da0017d12a.jpg)

 - coder server installed extensions
 
![code-server-extensions](https://user-images.githubusercontent.com/26960050/134753512-08cf522e-529d-4746-b1ed-7e07cdb33a2c.jpg)

 - vscode display normal.  (use the same Web Browser and display the same file.)
![vscode](https://user-images.githubusercontent.com/26960050/134753520-7271eac0-ca70-47f9-a393-21f3d96c0dff.jpeg)

**Comment by liaomingg** [comment]
I have tested the docker image step by step as the pic shows. but still got the same problem. 
Google Chrome and Safari also tested.

![docker](https://user-images.githubusercontent.com/26960050/134767749-2fbf8281-72b5-43f6-a28c-0bacdbfcf51c.jpg)

**Comment by liaomingg** [comment]
Hi,
      I have tested code-server 3.9.3, 3.10.0.
      3.9.3 is worked (as the picture shows.), but 3.10.0 not work.
![code-server-3 9 3-worked](https://user-images.githubusercontent.com/26960050/134775364-e0faddc2-3dfd-43f4-b3f7-1cf619a41210.jpg)
.

**Comment by wantao666** [comment]
i have the same question...

**Comment by wantao666** [comment]
> i have the same question...

![image](https://user-images.githubusercontent.com/29670394/134813100-00303c0b-6704-4d36-a0f4-8480cb86ec1c.png)

**Comment by LRHstudy** [comment]
I have the same problem

**Comment by jsjoeio** [comment]
> I use the url: http://0.0.0.0:6008.

This is the most common reason - you're not serving code-server via HTTPS, which means the images, etc. are probably being blocked.

## How to check?

@LRHstudy @liaomingg I suggest going through these steps to see if you're experiencing this issue for the same reasons:
- [ ] Are you serving code-server over HTTPS? (i.e. does the URL have `https` in it?)
- [ ] Are there any logs in the browser? (Right click page -> Inspect -> click on "Console" tab -> look for errors)

## How to fix

Read our docs for setting up HTTPS and getting self-signed certificates [here](https://coder.com/docs/code-server/v3.12.0/guide#https-and-self-signed-certificates). You can also run `code-server --link` (which should handle this for you).

**Comment by liaomingg** [comment]
Thanks, self-signed certificates for https is workded.

**Comment by yifangtan** [comment]
> 我有同样的问题...@jsjoeio
> 
> ![图像](https://user-images.githubusercontent.com/29670394/134813100-00303c0b-6704-4d36-a0f4-8480cb86ec1c.png)

Is it settled now? I have the same problem.

**Comment by jsjoeio** [comment]
@yifangtan please upgrade to the latest version of code-server and ensure you're using HTTPS!
