### ISSUE TITLE
svn extension is not working

### ISSUE THREAD

**Issue by WengShengyuan** [cdr/code-server#424]
- `code-server` version: 1.408-vsc1.32.0
- OS Version: macOS Mojave 10.14.4
- Extension: svn

## Description
1. Click "+" button, or refresh button ,shows 'svn.repolog.addrepolike' not found, or 'svn.repolog.refresh' not found.
2. SOURCE CONTROL panel shows 'No source control providers registered.'

## Steps to Reproduce
step1. I tried download svn vsix file and install offline or install directly in vscode, and none of those work.
step2. Click "+" button, or refresh button ,shows 'svn.repolog.addrepolike' not found, or 'svn.repolog.refresh' not found.
<img width="1389" alt="屏幕快照 2019-04-04 20 12 41" src="https://user-images.githubusercontent.com/9462331/55556452-374bee00-571a-11e9-9a2f-33d61f93ffdc.png">

**Comment by kylecarbs** [comment]
Will fix. Thanks for the report!

**Comment by effolkronium** [comment]
+1. Where is the fix ?

**Comment by sr229** [comment]
I think this is fixed by v2 so we're gonna close this off.

**Comment by qv1256** [comment]
when I use 2.1698-vsc1.41.1，the problems still exist

**Comment by nhooyr** [comment]
See #1299 

Will be fixed soon, sorry about this @qv1256.
