### ISSUE TITLE
settings.json issue on v 3.12.0

### ISSUE THREAD

**Issue by OliverwengFiltered** [cdr/code-server#4249]
it seems code server is no longer reading the settings file from /home/xxx/.local/share/code-server/User/settings.json

whatever settings that I change in the above file has no effect to the editor.

![Screen Shot 2021-09-27 at 12 05 30 PM](https://user-images.githubusercontent.com/28814939/134945108-efcceea2-6f4c-4363-b372-c0fca9112a78.png)

**Comment by jsjoeio** [comment]
I could not reproduce this locally.

https://user-images.githubusercontent.com/3806031/134968240-c6d145c0-4b3c-4117-93d6-dd395d4a21fe.mov

If you open a complete bug report, we'll be able to better help you troubleshoot this! Thank you!

**Comment by OliverwengFiltered** [comment]
for example, if you set `"workbench.startupEditor": "readme",` in the /home/xxxx/.local/share/code-server/User/settings.json

before code server launches, in previous version, it works, it will just bright readme file, but with latest version, it's always the welcome page (with the walk through steps).

**Comment by OliverwengFiltered** [comment]
@jsjoeio  opened the bug report: https://github.com/cdr/code-server/issues/4263

Thanks
