### ISSUE TITLE
Uninstallable under Termux due to node version

### ISSUE THREAD

**Issue by MAProsper** [cdr/code-server#4250]
## OS/Web Information

- Web Browser: Chrome 93.0.4577.82
- Local OS: Android 11
- Remote OS: Android 11
- Remote Architecture: aarch64
- `code-server --version`: none

## Steps to Reproduce

1. Install Termux from F-Droid.
2. Make sure it's up-to-date: apt update && apt upgrade
3. Install required packages: apt install build-essential python git nodejs yarn
4. Install code-server: yarn global add code-server

## Expected

code-server should be able to install.

## Actual

code-server is unable to install since Termux installs node 16.10 insted of 14.X.

## Logs

~ $ apt install build-essential python git nodejs yarn
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (4.1).
git is already the newest version (2.33.0-1).
python is already the newest version (3.9.7).
The following NEW packages will be installed:
  nodejs yarn
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/8865 kB of archives.
After this operation, 53.7 MB of additional disk space will be used.
Do you want to continue? [Y/n]
(Reading database ... 79224 files and directories currently installed.)
Selecting previously unselected package nodejs.
Preparing to unpack .../nodejs_16.10.0_aarch64.deb ...
Unpacking nodejs (16.10.0) ...
Selecting previously unselected package yarn.
Preparing to unpack .../archives/yarn_1.22.10_all.deb ...
Unpacking yarn (1.22.10) ...
Setting up nodejs (16.10.0) ...
Setting up yarn (1.22.10) ...
Processing triggers for man (1.14.5-2) ...
~ $ yarn global add code-server
yarn global v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error code-server@3.12.0: The engine "node" is incompatible with this module. Expected version "= 14". Got "16.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Thanks for the details! This issue was fixed in https://github.com/cdr/code-server/pull/4230 and will be out in the next release!

Until then, you can either:
- downgrade Node to v14 in Termux
- use an earlier version of code-server
