### ISSUE TITLE
Webview related errors with SSH FS Addon. Blank tabs.

### ISSUE THREAD

**Issue by flaektrem** [cdr/code-server#4259]
## OS/Web Information

- Web Browser: Firefox
- Local OS: Homeassistant OS
- Remote OS:
- Remote Architecture:
- `code-server --version`:

## Steps to Reproduce

1. Install SSH FS Addon from marketplace
2. Open SSH FS configuration and add new connection
3. Blank tab appears

## Expected
A tab with SSH FS settings should appear

## Actual
Just a blank tab appears, and some webview related errors in Firefox console. 

![InkedScreenshot 2021-09-28 at 08-00-52 Visual Studio Code - Home Assistant_LI](https://user-images.githubusercontent.com/58172129/135031998-62a6fd9f-7e78-404a-bba1-15e405bc78b6.jpg)
## Logs
Not able to provide logs right now. See all information about this in link below.
https://github.com/SchoofsKelvin/vscode-sshfs/issues/279

## Notes
All information can be found here:
https://github.com/SchoofsKelvin/vscode-sshfs/issues/279
I'm not sure if it's OK to open a bug report and just refer to another topic. But this is all I can do right now. Just trying to help out to get this bug sorted out. At least to start somewhere.

This issue can be reproduced in VS Code: Yes/No

**Comment by jsjoeio** [comment]
> I'm not sure if it's OK to open a bug report and just refer to another topic. But this is all I can do right now. Just trying to help out to get this bug sorted out. At least to start somewhere.

Really appreciate that ♥️

So I'm using code-server 3.12.0 on macOS + Brave and this is what happens when I try to reproduce this.

## Reproducing

1. Download extension from [VSX marketplace](https://open-vsx.org/extension/Kelvin/vscode-sshfs)
2. Install in code-server 
3. Add new configuration

![image](https://user-images.githubusercontent.com/3806031/135156822-c252577d-2fb7-431a-948b-7d375fa50f31.png)

It works as expected. I think we're going to have to wait until you get more information so we can have you look at the browser logs.

If you're getting a blank tab, it's probably the resources failing to load, which is common when you're not using HTTPS.

**Comment by flaektrem** [comment]
I can try get the logs from where I am right now (not home). 
So the easiest way to get browser logs?

**Comment by jsjoeio** [comment]
> Tell me and I'll try to bring that up for you.
I'm not a programmer/coder so maybe someone can help me out with this

No worries at all! I made a video to show you. Let me know if that helps.

## Video 

https://user-images.githubusercontent.com/3806031/135330178-8ee7a795-fefa-40da-b66d-24f47a792d83.mov

**Comment by flaektrem** [comment]
Thank you very much for that beautiful instruction.

Got the logs from when I press "Add new configuration"
I'm on remote access via Nabu Casa right now as you can see in the logs. It doesn't matter if I'm doing this locally, the tab is blank anyway.

```
08:10:45.532 Feature Policy: Skipping unsupported feature name “clipboard-read”. webviewElement.ts:84:10
08:10:45.532 Feature Policy: Skipping unsupported feature name “clipboard-write”. webviewElement.ts:84:10
08:10:45.536 Feature Policy: Skipping unsupported feature name “clipboard-read”. webviewElement.ts:117:16
08:10:45.536 Feature Policy: Skipping unsupported feature name “clipboard-write”. webviewElement.ts:117:16
08:10:45.537 Feature Policy: Skipping unsupported feature name “clipboard-read”. webviewElement.ts:130:10
08:10:45.537 Feature Policy: Skipping unsupported feature name “clipboard-write”. webviewElement.ts:130:10
08:10:45.600 GEThttps://xxxx.ui.nabu.casa/api/hassio_ingress/WtaX-gg53dk1GeSkD5WUAKEQDCtkRyj-evGkjQTShZg/webview/index.html?id=ad398544-4049-4be9-9088-25cdd9aa35f7&swVersion=2&extensionId=Kelvin.vscode-sshfs&vscode-resource-base-authority=vscode-resource.vscode-webview.net
[HTTP/1.1 200 OK 240ms]

08:10:45.610 GEThttps://xxxx.ui.nabu.casa/api/hassio_ingress/WtaX-gg53dk1GeSkD5WUAKEQDCtkRyj-evGkjQTShZg/vscode-remote-resource?path=/data/vscode/extensions/kelvin.vscode-sshfs-1.22.0/resources/icon.svg&tkn=
[HTTP/1.1 200 OK 245ms]

08:10:46.016 GEThttps://xxxx.ui.nabu.casa/api/hassio_ingress/WtaX-gg53dk1GeSkD5WUAKEQDCtkRyj-evGkjQTShZg/webview/host.js
[HTTP/1.1 200 OK 90ms]

08:10:46.167 GEThttps://xxxx.ui.nabu.casa/api/hassio_ingress/WtaX-gg53dk1GeSkD5WUAKEQDCtkRyj-evGkjQTShZg/webview/main.js
[HTTP/1.1 200 OK 119ms]

08:10:46.449 Feature Policy: Skipping unsupported feature name “clipboard-read”. main.js:677:12
08:10:46.449 Feature Policy: Skipping unsupported feature name “clipboard-write”. main.js:677:12
08:10:46.449 Feature Policy: Skipping unsupported feature name “clipboard-read”. main.js:682:36
08:10:46.449 Feature Policy: Skipping unsupported feature name “clipboard-write”. main.js:682:36
08:10:46.449 Feature Policy: Skipping unsupported feature name “clipboard-read”. main.js:685:17
08:10:46.449 Feature Policy: Skipping unsupported feature name “clipboard-write”. main.js:685:17
08:10:46.474 GEThttps://xxxx.ui.nabu.casa/api/hassio_ingress/WtaX-gg53dk1GeSkD5WUAKEQDCtkRyj-evGkjQTShZg/webview/fake.html?id=ad398544-4049-4be9-9088-25cdd9aa35f7
[HTTP/1.1 200 OK 85ms]

08:10:46.722 GEThttps://vscode-remote+xxxxx.ui.nabu.casa.vscode-resource.vscode-webview.net/data/vscode/extensions/kelvin.vscode-sshfs-1.22.0/webview/build/static/js/runtime-main.bundle.js
CSP

08:10:46.722 Content Security Policy: The page’s settings blocked the loading of a resource at https://xxxx.ui.nabu.casa/api/hassio_ingress/WtaX-gg53dk1GeSkD5WUAKEQDCtkRyj-evGkjQTShZg/webview/service-worker.js?id=ad398544-4049-4be9-9088-25cdd9aa35f7&swVersion=2&extensionId=Kelvin.vscode-sshfs&vscode-resource-base-authority=vscode-resource.vscode-webview.net (“script-src”).
08:10:46.722 Loading failed for the <script> with source “https://vscode-remote+xxxx.ui.nabu.casa.vscode-resource.vscode-webview.net/data/vscode/extensions/kelvin.vscode-sshfs-1.22.0/webview/build/static/js/runtime-main.bundle.js”. index.html:116:1
08:10:46.739 Content Security Policy: The page’s settings blocked the loading of a resource at https://xxxx.ui.nabu.casa/api/hassio_ingress/WtaX-gg53dk1GeSkD5WUAKEQDCtkRyj-evGkjQTShZg/webview/service-worker.js?id=ad398544-4049-4be9-9088-25cdd9aa35f7&swVersion=2&extensionId=Kelvin.vscode-sshfs&vscode-resource-base-authority=vscode-resource.vscode-webview.net (“script-src”).
08:10:46.740 GEThttps://vscode-remote+xxxxx.ui.nabu.casa.vscode-resource.vscode-webview.net/data/vscode/extensions/kelvin.vscode-sshfs-1.22.0/webview/build/static/js/269.bundle.js
CSP

08:10:46.740 Loading failed for the <script> with source “https://vscode-remote+xxxxx.ui.nabu.casa.vscode-resource.vscode-webview.net/data/vscode/extensions/kelvin.vscode-sshfs-1.22.0/webview/build/static/js/269.bundle.js”. index.html:116:1
08:10:46.740 Content Security Policy: The page’s settings blocked the loading of a resource at https://xxxxx.ui.nabu.casa/api/hassio_ingress/WtaX-gg53dk1GeSkD5WUAKEQDCtkRyj-evGkjQTShZg/webview/service-worker.js?id=ad398544-4049-4be9-9088-25cdd9aa35f7&swVersion=2&extensionId=Kelvin.vscode-sshfs&vscode-resource-base-authority=vscode-resource.vscode-webview.net (“script-src”).
08:10:46.741 GEThttps://vscode-remote+xxxxx.ui.nabu.casa.vscode-resource.vscode-webview.net/data/vscode/extensions/kelvin.vscode-sshfs-1.22.0/webview/build/static/js/main.bundle.js
CSP

08:10:46.741 Loading failed for the <script> with source “https://vscode-remote+xxxxx.ui.nabu.casa.vscode-resource.vscode-webview.net/data/vscode/extensions/kelvin.vscode-sshfs-1.22.0/webview/build/static/js/main.bundle.js”. index.html:116:1
```

**Comment by jsjoeio** [comment]
```javascript
08:10:46.722 Content Security Policy: The page’s settings blocked the loading of a resource at https://xxxx.ui.nabu.casa/api/hassio_ingress/WtaX-gg53dk1GeSkD5WUAKEQDCtkRyj-evGkjQTShZg/webview/service-worker.js?id=ad398544-4049-4be9-9088-25cdd9aa35f7&swVersion=2&extensionId=Kelvin.vscode-sshfs&vscode-resource-base-authority=vscode-resource.vscode-webview.net (“script-src”).
08:10:46.722 Loading failed for the <script> with source “https://vscode-remote+xxxx.ui.nabu.casa.vscode-resource.vscode-webview.net/data/vscode/extensions/kelvin.vscode-sshfs-1.22.0/webview/build/static/js/runtime-main.bundle.js”. index.html:116:1
08:10:46.739 Content Security Policy: The page’s settings blocked the loading of a resource at https://xxxx.ui.nabu.casa/api/hassio_ingress/WtaX-gg53dk1GeSkD5WUAKEQDCtkRyj-evGkjQTShZg/webview/service-worker.js?id=ad398544-4049-4be9-9088-25cdd9aa35f7&swVersion=2&extensionId=Kelvin.vscode-sshfs&vscode-resource-base-authority=vscode-resource.vscode-webview.net (“script-src”).
08:10:46.740 GEThttps://vscode-remote+xxxxx.ui.nabu.casa.vscode-resource.vscode-webview.net/data/vscode/extensions/kelvin.vscode-sshfs-1.22.0/webview/build/static/js/269.bundle.js
CSP
```
Ah-ha! Yup, it's been blocked. This could be a couple things:
- are you using code-server 3.12.0? We fixed a bug related to this in that release.
- are you running code-server over HTTPS? if not, that could be related.
- do you have an ad-blocker or privacy settings? (like Brave) that could be related

**Comment by flaektrem** [comment]
Ad-block extensions in Firefox was inactivated during testing.

I don't think it's running over HTTPS. 
The URL I'm using right now remotely to my HA instance is:
```https://xxxx.ui.nabu.casa/hassio/addon/a0d7b954_vscode/info```. 
But when I'm using it locally the URL is:
```http://192.168.x.x/hassio/addon/a0d7b954_vscode/info```. 

It seems like the VSCode addon using code-server ``3.11.1.``
![Screenshot 2021-10-01 at 09-37-40 Supervisor - Home Assistant](https://user-images.githubusercontent.com/58172129/135583298-dead2eaf-7824-471a-9894-b9b429c5eed8.png)

**Comment by jsjoeio** [comment]
> But when I'm using it locally the URL is:
http://192.168.x.x/hassio/addon/a0d7b954_vscode/info.

This might be the source of the issue then. Can you try using HTTPS? We have some docs [here](https://coder.com/docs/code-server/v3.12.0/guide#https-and-self-signed-certificates) or you can try running `code-server --link`.

**Comment by flaektrem** [comment]
Ad-block extensions in Firefox was inactivated during testing.

I don't think it's running over HTTPS. 
The URL I'm using right now remotely to my HA instance is:
```https://xxxx.ui.nabu.casa/hassio/addon/a0d7b954_vscode/info```. 
But when I'm using it locally the URL is:
```http://192.168.x.x/hassio/addon/a0d7b954_vscode/info```. 

It seems like the VSCode addon using code-server ``3.11.1.``
![Screenshot 2021-10-01 at 09-37-40 Supervisor - Home Assistant](https://user-images.githubusercontent.com/58172129/135583298-dead2eaf-7824-471a-9894-b9b429c5eed8.png)

**Comment by flaektrem** [comment]
@jsjoeio sorry, I accidentally messed up and closed this. Reopened again.

I'm not sure how to get the whole Home Assistant instance under HTTPS. It's strange because this blank tab and "react server" error has never showed up before and suddenly HTTPS it's a must. 🤓 I think I have missed some breaking change or something lately.

I tried  ``code-server --link`` and went through those steps and ended up with VSCode on this address: 
``https://a0d7b954_vscode-xxx.cdr.co/``.
Then I installed SSH FS addon and tried again. Exactly the same behavior with blank tab when I tried to create new configuration.
The logs from Firefox are a bit different now:

```javascript
10:27:31.533 Feature Policy: Skipping unsupported feature name “clipboard-read”. webviewElement.ts:84:10
10:27:31.533 Feature Policy: Skipping unsupported feature name “clipboard-write”. webviewElement.ts:84:10
10:27:31.538 Feature Policy: Skipping unsupported feature name “clipboard-read”. webviewElement.ts:117:16
10:27:31.538 Feature Policy: Skipping unsupported feature name “clipboard-write”. webviewElement.ts:117:16
10:27:31.539 Feature Policy: Skipping unsupported feature name “clipboard-read”. webviewElement.ts:130:10
10:27:31.539 Feature Policy: Skipping unsupported feature name “clipboard-write”. webviewElement.ts:130:10
10:27:31.595 GEThttps://a0d7b954_vscode-xxx.cdr.co/vscode-remote-resource?path=/root/.local/share/code-server/extensions/kelvin.vscode-sshfs-1.22.0/resources/icon.svg&tkn=
10:27:31.708 GEThttps://a0d7b954_vscode-xxx.cdr.co/webview/index.html?id=95ac0ffd-d310-48b3-bc0f-ec687c066be6&swVersion=2&extensionId=Kelvin.vscode-sshfs&vscode-resource-base-authority=vscode-resource.vscode-webview.net
[HTTP/2 200 OK 1344ms]

10:27:33.061 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing. a0d7b954_vscode-xxx.cdr.co
10:27:33.130 GEThttps://a0d7b954_vscode-xxx.cdr.co/webview/host.js
[HTTP/2 304 Not Modified 1338ms]

10:27:34.546 GEThttps://a0d7b954_vscode-xxx.cdr.co/webview/main.js
[HTTP/2 304 Not Modified 2602ms]

10:27:50.007 Error in parsing value for ‘height’.  Declaration dropped. a0d7b954_vscode-xxx.cdr.co
10:27:50.084 GEThttps://a0d7b954_vscode-xxx.cdr.co/static/c680aae973d83583e4a73dc0c422f44021f0140e/usr/local/lib/code-server/lib/vscode/node_modules/xterm/lib/xterm.js
[HTTP/2 200 OK 2679ms]

10:27:52.890 GEThttps://a0d7b954_vscode-xxx.cdr.co/static/c680aae973d83583e4a73dc0c422f44021f0140e/usr/local/lib/code-server/lib/vscode/node_modules/xterm-addon-search/lib/xterm-addon-search.js
[HTTP/2 200 OK 2602ms]

10:27:52.890 GEThttps://a0d7b954_vscode-xxx.cdr.co/static/c680aae973d83583e4a73dc0c422f44021f0140e/usr/local/lib/code-server/lib/vscode/node_modules/xterm-addon-unicode11/lib/xterm-addon-unicode11.js
[HTTP/2 200 OK 2604ms]

10:27:52.891 GEThttps://a0d7b954_vscode-xxx.cdr.co/static/c680aae973d83583e4a73dc0c422f44021f0140e/usr/local/lib/code-server/lib/vscode/node_modules/xterm-addon-webgl/lib/xterm-addon-webgl.js
[HTTP/2 200 OK 2609ms]
```

**Comment by jsjoeio** [comment]
> I think I have missed some breaking change or something lately.

Nope, not a breaking change on our side (you would have known due to major version bump). But hey, maybe browsers made CSPs and/or service worker policies more strict? I'm not sure 🤷‍♂️

Hmm... those logs are different but I'm not sure if it helps.

Let's call in an expert - @code-asher any ideas how to help them?

**Comment by flaektrem** [comment]
I don't know what "CSPs" are. 
But I tried same procedure again, locally on Microsoft Edge and got following errors in Edge console:

```javascript    
Uncaught (in promise) Error: Service Workers are not enabled in browser. Webviews will not work.
    at main.js:211
    at new Promise (<anonymous>)
    at main.js:209
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at createWebviewManager (main.js:291)
    at host.js:111    
```

**Comment by jsjoeio** [comment]
> I don't know what "CSPs" are.

My bad! [Content Security Policies](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).

> Uncaught (in promise) Error: Service Workers are not enabled in browser. Webviews will not work.

Yeah same problem :( You're going to have to get HTTPS working in your environment to get this working. Sadly, we can't do much on code-server's end :(

**Comment by flaektrem** [comment]
I understand. But what I don't understand is why this blank tab never appeared before, without HTTPS.
This is so strange.

Anyway, I appreciate your help 🙏🏻

**Comment by code-asher** [comment]
It does seem odd that you are getting a blank page on HTTP but we only
test on secure contexts like HTTPS so it is possible something changed.
Definitely try with HTTPS and see if that resolves the issue!

**Comment by flaektrem** [comment]
But I'm not sure how to do that. 
VSCode running as a Home Assistant addon. 
I connect to HA either locally (192.168.x.x:8123) or via Nabu Casa cloud/remote service. With Nabu Casa i get a HTTPS url. But maybe that's not enough. Either way, it gives blank tab.

**Comment by code-asher** [comment]
Actually I should have read your logs more carefully since they indicate
you are already using HTTPS.

Your browser seems to be missing some features.  Are you using an old
version of Firefox?

**Comment by flaektrem** [comment]
Latest Firefox. Same problem with Microsoft Edge. Also same through Home Assistant app

**Comment by code-asher** [comment]
There are some other instances where service workers will be disabled,
namely ESR releases before Firefox 78 and in private browsing mode.

I am not sure what else could cause them to be disabled...maybe
certificate issues?

**Comment by SchoofsKelvin** [comment]
Looked into it and explained some stuff on [the other issue](https://github.com/SchoofsKelvin/vscode-sshfs/issues/279#issuecomment-943548921). Looks like it might be a Firefox bug. It's probably up to Firefox to fix it, or have VS Code change their webview code to account for this bug (if there's even a way to bypass it).

**Comment by flaektrem** [comment]
> @flaektrem guessing you saw @SchoofsKelvin's debugging in the other issue. Since this is a Firefox issue (most likely), do you mind if we close this?

I saw that, it's ok. 🙂

**Comment by joole** [comment]
I found 3.10 - the latest version that all has the same problem,
If you use 127.0.0.1 to access code-server page all the webview ok which like tabnine, platformio,eg
If you use real-ip like 192.168.x.x to access code-server page, all the webview is blanked screen

**Comment by jsjoeio** [comment]
I think service workers work on localhost/127.0.0.1 because they're allowlisted but anything else without https will not work

**Comment by joole** [comment]
> ause they're allowlisted

maybe,but `code-server --link` alway errors......

**Comment by jsjoeio** [comment]
> maybe,but code-server --link alway errors......

Yeah, unfortunately, we can't recommend that right now. I would advise you to check the docs [here](https://coder.com/docs/code-server/latest/guide#using-lets-encrypt-with-caddy). You might have luck with using Caddy.
