### ISSUE TITLE
run `code-server --link` command show error

### ISSUE THREAD

**Issue by wantao666** [cdr/code-server#4277]
## OS/Web Information

- Remote OS: ubuntu18.04
- Remote Architecture: x64
- `code-server --version`: 3.12.0

## Steps to Reproduce
i want to use code-server by https, and i use `code-server --link` command.but it's show error like screenshot.

## Screenshot
![image](https://user-images.githubusercontent.com/29670394/135404906-1ced61fe-a380-4a1d-9f94-f39d891656d7.png)

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by jsjoeio** [comment]
There error is there in the screenshot. We're currently working on accommodating users with low latency but we're not there yet! I'm going to close this now since this is expected. Keep an eye out though! We'll have news soon.

cc @bpmct
