### ISSUE TITLE
Update "differences compared to" section of docs

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#4289]
Suggested by @bpmct.

Now that Codespaces is becoming more  widely known and other projects are sprouting up, we should revisit [this section](https://coder.com/docs/code-server/v3.12.0/FAQ#whats-the-difference-between-code-server-and-theia) of the docs.

**Comment by bpmct** [comment]
similar to #4123

**Comment by jsjoeio** [comment]
Closed via #4307
