### ISSUE TITLE
Unable to work.The website shows nothing.

### ISSUE THREAD

**Issue by danuonuo** [cdr/code-server#4295]
Hello,

## OS/Web Information

- Web Browser:Google Chrome	93.0.4577.82（64 Bit） (cohort: Stable)
- Local OS:Windows10 LTSC
- Remote OS:Ubuntu20.04LTS
- Remote Architecture:
- `code-server --version`:Latest

## Steps to Reproduce

1.Install
2.Visit the website

## Expected
Sometimes the webpage shows nothing but white.

## Actual
![0FD67C03-0940-4F6C-8946-A085849C2588](https://user-images.githubusercontent.com/40296672/135721395-c9a5dc6c-0435-4a2a-9920-c322bd54e055.png)

## Logs
![7D9729C7-87F7-4779-8706-EFBA7ECE70CD](https://user-images.githubusercontent.com/40296672/135721420-3c0c4424-3793-477a-a0f4-67cfa935dd86.png)

This issue can be reproduced in VS Code: No

**Comment by senyai** [comment]
Just to be sure, can you try another browser?

**Comment by danuonuo** [comment]
> Just to be sure, can you try another browser?

I tried. But they all sometimes work now. It likes a random thing.

**Comment by jsjoeio** [comment]
Hmm... which version of code-server are you using?

Can you try restarting code-server and then launching in an incognito in the browser? It's strange that it can't initialize VS Code...

**Comment by danuonuo** [comment]
> 嗯。。。您使用的代码服务器版本是什么版本的？
> 
> 您可以尝试重新启动代码服务器，然后在浏览器中隐身启动吗？很奇怪， 它不能初始化 Vs 代码...

Hmm... After I rebooted the server, it worked properly again...
Next time when it has something wrong I'll open another issue.
Thanks.

**Comment by jsjoeio** [comment]
Awesome! Closing for now.
