### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by FlameQuard** [cdr/code-server#4302]
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

code-server: v3.12.0
 VS Code: v1.60.0
Commit: 2661a690ac228872e8d1dc28ab6d33e8afc30add
Date: 2021-09-16T21:13:32Z
Browser: Mozilla/5.0 (Linux; Android 9) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36

**Comment by jsjoeio** [comment]
I am not sure this is specific to code-server but could be wrong. Could you please open a full bug report with screenshots and logs? Then we can take a look. Thanks!
