### ISSUE TITLE
Two-Factor Authentication

### ISSUE THREAD

**Issue by fsociety3765** [cdr/code-server#4308]
Would be great to get two-factor auth if possible.

Thanks,

FS

**Comment by jsjoeio** [comment]
I think this has been asked in the past. We don't plan on adding this to code-server itself, but you might be able to build something on top of code-server.

https://github.com/cdr/code-server/issues/1625

Feel free to chime in on the [Plugin API discussion](https://github.com/cdr/code-server/discussions/4072)
