### ISSUE TITLE
Yarn on Termux can't install code-server

### ISSUE THREAD

**Issue by itsanuragshukla** [cdr/code-server#4339]
I tried to download Code-server by using 'yarn global add code-server' but it is not downloading . It showing node version incompatible . Here's what I got-

![20211012_071533](https://user-images.githubusercontent.com/71091279/136877003-fb3b9e71-80a2-43ef-a397-cb9712e2d6aa.jpg)

**Comment by itsanuragshukla** [comment]
ok thanks, but why is this a thing that code-server is compatible with node14 and not with node16. I thought that basic binaries remains the same when upgrading a package.

**Comment by YgtOz** [comment]
You need the `nodejs-lts` (or perhaps `node-lts`) package (`pkg install nodejs-lts`). That is a 14.x version of node, and I can confirm it will let you install code-server on Termux.
