### ISSUE TITLE
How to start the project with source code？

### ISSUE THREAD

**Issue by piaoxiaobo** [cdr/code-server#4341]
Hello everyone,
I am a front-end developer, and I want to deploy an online IDE in the near future. I want to know how to compile the source code of the code-server.

**Comment by SeibertronSS** [comment]
> Follow the instructions on [CONTRIBUTING](https://coder.com/docs/code-server/latest/CONTRIBUTING)

@aztack 您好，我看了这个文档，可是当我用 yarn 命令编译的时候，会出现很多 ERROR，最后的服务也起不起来。

**Comment by aztack** [comment]
> > Follow the instructions on [CONTRIBUTING](https://coder.com/docs/code-server/latest/CONTRIBUTING)
> 
> @aztack 您好，我看了这个文档，可是当我用 yarn 命令编译的时候，会出现很多 ERROR，最后的服务也起不起来。

贴一下你的报错日志。
我在MacOS上需要先checkout v3.12.0。main分支上的代码运行报404错。
