### ISSUE TITLE
Code-server instances "stay open" after being closed from browser

### ISSUE THREAD

**Issue by Sharpz7** [cdr/code-server#4351]
## OS/Web Information

- Web Browser: Chrome
- Local OS: Windows
- Remote OS: Docker Linux
- Remote Architecture: Docker Compose Contianer
- `code-server --version`:

## Steps to Reproduce

1. Open htop
2. Open multiple tabs and close them again when code-server loads
3. The instance stays open, with HTOP showing that the CPU usuage and RAM increases with each closed instance until it crashes.

## Expected

The RAM and CPU usage should decrease after the instance is closed 

## Actual

It doesn't :)

## Logs

https://files.mcaq.me/8xad.png
I also don't understand why the code-server items are tied to my user "adam" instead of root. This doesn't make much sense to me?

This is difficult to show with logs, or at least I don't know how to do it well with my setup.

**Comment by code-asher** [comment]
Does the reproduction require opening a terminal or does this happen when opening code-server without a terminal open?
