### ISSUE TITLE
Cross Site Scripting（XSS）vulnerability in code-server

### ISSUE THREAD

**Issue by Jyhtpy** [cdr/code-server#4355]
## OS/Web Information

- Web Browser: **firefox**
- Local OS: **Debian**
- Remote OS:**Debian**
- Remote Architecture:
- `code-server --version`: **v3.12.0**

## Steps to Reproduce

1.Open your browser and insert payload `/static/test%3Cmy_tag_efb4535077ba29aaca28167c491b4249/%3E%3Cimg%20src=x%3E%3Cscript%3Ealert(1)%3C/script%3E`

2.example: `http://127.0.0.1:8080/static/test%3Cmy_tag_efb4535077ba29aaca28167c491b4249/%3E%3Cimg%20src=x%3E%3Cscript%3Ealert(1)%3C/script%3E`

## Screenshot
![image](https://user-images.githubusercontent.com/17903984/137276639-c78d62b4-a91c-467f-a676-50a8abb65fad.png)

## Notes

This issue can be reproduced in VS Code: Yes

**Comment by mauri-sfdc** [comment]
@code-asher I can take a crack at the fix

**Comment by jsjoeio** [comment]
@mauri-sfdc that would be awesome! Thank you for reporting this and providing extra links (for me!). Let us know how we can help.
