### ISSUE TITLE
Keytar missing for Docker-extension

### ISSUE THREAD

**Issue by roflcoopter** [cdr/code-server#436]
- `code-server` version: 1.408-vsc1.32.0
- OS Version: Ubuntu 16.04 container
- Extension: https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker

## Description
When i try to use the Docker-extension above it throws this error;

`Activating extension 'PeterJausovec.vscode-docker' failed: Internal error: Could not find keytar module for reading and writing passwords.`

Where and how can i install keytar?
## Steps to Reproduce

1. Install Docker extension from marketplace
1. Click the Docker icon in the left hand toolbar

**Comment by kylecarbs** [comment]
Will fix! Keytar is an interesting one since it uses the system keychain.

**Comment by gorzell** [comment]
I am wondering of you all made any progress on this? It seems like `libsecret`, which is the Linux implementation that this is using doesn't support any type of headless or CLI mode, it wants X11 to be functioning.

**Comment by deansheather** [comment]
Does libsecret really need X11? I understand it uses Dbus but I didn't think it required a running X11 server.

**Comment by matthew-parlette** [comment]
I'm also checking in on this one as I've run into this as well. Any progress here? Or has anyone found a workaround?

I've tried to just install npm and then keytar in the docker container, but it doesn't seem to be working (though I didn't really dive into why that didn't work, yet)

**Comment by deansheather** [comment]
No workaround or solution at the moment, the issue is that libsecret requires Dbus (a message bus) and possibly X11 (a desktop environment) to be running and accessible to code-server.

I'm not completely sure, but the easiest solution seems to be writing a "fake" keytar that stores passwords by some other method instead of using those dependencies.

**Comment by kylecarbs** [comment]
Could be helpful: https://wiki.archlinux.org/index.php/GNOME/Keyring#Using_the_keyring_outside_GNOME

**Comment by brandonkal** [comment]
I use this library for accessing keyrings in Go: https://github.com/99designs/keyring
It has a list of backends that it supports. `pass` may be a good one for writing a fake keytar.

**Comment by nhooyr** [comment]
Works fine now. If this is still a problem, please feel free to reopen.
