### ISSUE TITLE
Investigate replacing ts-jest with swc-node/jest

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#4403]
@jawnsy shared [this tweet](https://twitter.com/huozhi/status/1449314595861004292)

Might be worth exploring since we use `ts-jest`

![image](https://user-images.githubusercontent.com/3806031/139118625-bc1dee79-f235-4bbd-a5e0-84d384df2b3a.png)

**Comment by jsjoeio** [comment]
I would still like to look into this!

**Comment by F3n67u** [comment]
could you assign this task to me? I have some experience in replace ts-jest with swc/jest in my company
