### ISSUE TITLE
unable to hide behind apache proxypass, websocket has error

### ISSUE THREAD

**Issue by peterremote1980** [cdr/code-server#442]
unable to hide behind apache proxypass, websocket has error:

c01964.bundle.js:53 WebSocket connection to 'wss://code.quantr.hk/' failed: Error during WebSocket handshake: Unexpected response code: 200

```
<VirtualHost *:80>
        ServerAdmin peter@quantr.hk
        ServerName code.quantr.hk
        ServerAlias code.quantr.com
        ProxyPass / http://192.168.10.124:8443/
        ProxyPassReverse / http://192.168.10.124:8443/
</VirtualHost>



<VirtualHost *:443>
            ProxyRequests Off

    SSLEngine On
    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off

        SSLCertificateFile /etc/letsencrypt/live/mail.findjob.la/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mail.findjob.la/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf

        ServerAdmin peter@quantr.hk
        ServerName code.quantr.hk
        ServerAlias code.quantr.com
        ProxyPass / https://192.168.10.124:8443/
        ProxyPassReverse / https://192.168.10.124:8443/
</VirtualHost>
```

```
/root/Downloads/code-server1.604-vsc1.32.0-linux-x64/code-server  -P password --cert /etc/letsencrypt/live/mail.findjob.la/fullchain.pem --cert-key /etc/letsencrypt/live/mail.findjob.la/privkey.pem ~/workspace/
```

**Comment by MalikBrown** [comment]
> unable to hide behind apache proxypass, websocket has error:
> 
> c01964.bundle.js:53 WebSocket connection to 'wss://code.quantr.hk/' failed: Error during WebSocket handshake: Unexpected response code: 200
> 
> ```
> <VirtualHost *:80>
>         ServerAdmin peter@quantr.hk
>         ServerName code.quantr.hk
>         ServerAlias code.quantr.com
>         ProxyPass / http://192.168.10.124:8443/
>         ProxyPassReverse / http://192.168.10.124:8443/
> </VirtualHost>
> 
> 
> 
> <VirtualHost *:443>
>             ProxyRequests Off
> 
>     SSLEngine On
>     SSLProxyEngine On
>     SSLProxyVerify none
>     SSLProxyCheckPeerCN off
>     SSLProxyCheckPeerName off
> 
>         SSLCertificateFile /etc/letsencrypt/live/mail.findjob.la/fullchain.pem
>         SSLCertificateKeyFile /etc/letsencrypt/live/mail.findjob.la/privkey.pem
>         Include /etc/letsencrypt/options-ssl-apache.conf
> 
>         ServerAdmin peter@quantr.hk
>         ServerName code.quantr.hk
>         ServerAlias code.quantr.com
>         ProxyPass / https://192.168.10.124:8443/
>         ProxyPassReverse / https://192.168.10.124:8443/
> </VirtualHost>
> ```
> ```
> /root/Downloads/code-server1.604-vsc1.32.0-linux-x64/code-server  -P password --cert /etc/letsencrypt/live/mail.findjob.la/fullchain.pem --cert-key /etc/letsencrypt/live/mail.findjob.la/privkey.pem ~/workspace/
> ```

Silly question but did You open port 8443?

**Comment by peterremote1980** [comment]
I am using ProxyPass module, i confirm 8443 is opened.

**Comment by MalikBrown** [comment]
ProxyPass is just an argument in the config make sure you have the respective apache modules installed to support headers and such.
Here is the command to install the mod_prox module using aptitude.
`aptitude install -y build-essential`
`aptitude install -y libapache2-mod-proxy-html libxml2-dev`
`a2enmod`
`proxy proxy_ajp proxy_http rewrite deflate headers proxy_connect proxy_html`
You will then see a list of modules you can install. Then restart after you have what you need.

**Comment by abl** [comment]
https://github.com/codercom/code-server/blob/master/doc/self-hosted/index.md#apache-reverse-proxy

Take a look at that; you're missing a few directives. `Unexpected response code: 200` means that your websocket request is getting a normal web page back.

**Comment by sr229** [comment]
From first glance your configuration does not support HTTP upgrades, which the websocket needs.

**Comment by ColdSphinX** [comment]
You might want to use rewrite to proxy depending on http upgrade.
`RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket
RewriteRule /(.*)              ws://192.168.10.124:8443/$1 [P,QSA,L]
RewriteCond %{HTTP:Upgrade} !=websocket
RewriteRule /(.*)              http://192.168.10.124:8443/$1 [P,QSA,L]`
