### ISSUE TITLE
iPadOS - Can't press status bar buttons through touch 

### ISSUE THREAD

**Issue by brendanefro** [cdr/code-server#4432]
## OS/Web Information

- Web Browser: IOS Safari
- Local OS: iPadOS 14.8
- Remote OS: WSL2 (Ubuntu 18.04 LTS) on Windows 10 (20H2 19042.1288)
- Remote Architecture: Intel x64
- `code-server --version`: 3.12.0

## Steps to Reproduce
All buttons in the status bar (e.g. pressing on the Git branch) can't be activated through touch. The only way they can be activated is by clicking on them when an external mouse is connected to the ipad. 

E.g.
1. Connect to a Git Repo
2. Click on where it says "master" in the status bar in the bottom left using touch
3. Nothing happens
4. Alternatively try clicking any button in the status bar through touch

## Expected

When touching the buttons in the status bar they should activate in the same way as if they were clicked with a mouse (E.g. clicking "master" will bring up the command palette" 

## Actual

Touching the buttons causes them to highlight but not activate

## Logs

Probably not needed in this case but if required I can provide them. 

## Screenshot
This video first shows what happens when I click status bar buttons with a mouse and when the cursor disappears that is me trying to activate them with touch (notice they highlight but don't do anything):

https://user-images.githubusercontent.com/38585705/140015532-d122fa03-8ad8-466e-ab17-653d5a2ad569.MP4

## Notes

This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment]
Can you try reproducing this in Codespaces or vscode.dev?

I don't think this is in our control unfortunately (and I would bet it's an upstream issue)

**Comment by brendanefro** [comment]
Ah yes you’re right actually! I just checked vscode.dev and the same thing happens. I will post the issue to VSCode instead. Thanks!

**Comment by jsjoeio** [comment]
Hooray! Marking as upstream and closing then.
