### ISSUE TITLE
duplicate values in helm chart example

### ISSUE THREAD

**Issue by bpmct** [cdr/code-server#4441]
@Matthew-Beckett. I noticed a couple duplicate values in the example [values.yaml](https://github.com/cdr/code-server/blob/main/ci/helm-chart/values.yaml) such as `securityContext` and `serviceAccount`.

Happy to contribute with a PR, but your guidance on which example to keep would be helpful :)

**Comment by Matthew-Beckett** [comment]
Hi Ben,

Thanks for spotting this, I'll take a look this evening GMT and submit a fix 😊

Thanks!
Matt ❤️

**Comment by Matthew-Beckett** [comment]
@bpmct ready for review!
