### ISSUE TITLE
The workbench failed to connect to the server (Error: WebSocket close with status code 1006)

### ISSUE THREAD

**Issue by n3rd3x3** [cdr/code-server#4443]
## OS/Web Information

- Web Browser: Chromium (brave), although I also tested with Firefox and Edge and got the same result.
- Local OS: Windows 11
- Remote OS: Ubuntu
- Remote Architecture: x86-64
- `code-server --version`: 3.12.0

## Steps to Reproduce

1. Ran code-server (i also tried using --proxy-domain <my domain> to see if I got any different results.) I used nginx to reverse proxy to my domain, I also use Cloudflare.
2. When I open the domain on my browser, I get 
``` An unexpected error occurred that requires a reload of this page.
The workbench failed to connect to the server (Error: WebSocket close with status code 1006)
```

## Expected

The server would work normally.

## Actual

See error above.

## Logs

Logs look normal for the remote server, however browser gives error:
```
[vscode] failed to initialize VS Code vscode.browserified.js:726:13
    [4]< <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:726
    o <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:1
    r <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:1
    <anonymous> <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:1
```

(I replaced my domain with <domain> for privacy reasons.)

```
Error: [vscode] Could not set body background to theme background color. Could not find colorThemeData in localStorage.
    setBodyBackgroundToThemeBackgroundColor <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:668
    main <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:719
    [4]< <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:723
    o <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:1
    r <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:1
    <anonymous> <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:1
vscode.browserified.js:727:13
    [4]< <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:727
    o <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:1
    r <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:1
    <anonymous> <domain>/static/b37ff28a0a582aee84a8f961755d0cb40a4081db/usr/lib/code-server/out/browser/pages/vscode.browserified.js:1
 ```

## Screenshot

![image](https://user-images.githubusercontent.com/57784409/140235477-2d744d7f-02b8-4040-a52c-c97dbd621825.png)

## Notes

This issue can be reproduced in VS Code: No

**Comment by woshilaiba** [comment]
i got this too. i ran it in docker.
i found there must be lines below in the nginx.conf to make it work
  location / {
    proxy_pass http://codeserver.xxx.xxx:8443/;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Accept-Encoding gzip;
}

**Comment by ChrisKimZHT** [comment]
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection upgrade;
proxy_set_header Accept-Encoding gzip;

**Comment by n3rd3x3** [comment]
> proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection upgrade; proxy_set_header Accept-Encoding gzip;

Thanks, that seemed to work.

**Comment by bobbywaz** [comment]
Any idea which version broke this? I can't get it to work with Nginx-Proxy-Manager so I'll just downgrade until code-server gets it's sh*t together.

**Comment by jsjoeio** [comment]
cc @code-asher

**Comment by code-asher** [comment]
Those headers enable proxying websockets so it is not a code-server issue as far as I can tell.

**Comment by BSmithIO** [comment]
If anyone is looking for a solution for ingress-nginx on Kubernetes like I was, add this annotation to your ingress

nginx.org/websocket-services: "code-server"

Replace code-server with whatever your code-server service name is.

**Comment by ZandercraftGames** [comment]
A little late now, but does anyone have a working configuration for Apache2?

**Comment by tinuh** [comment]
> A little late now, but does anyone have a working configuration for Apache2?

Hey looking for the same thing, having issues proxying code server in apache2

**Comment by 1m188** [comment]
A little late now, but does anyone have a working configuration for caddy2?

**Comment by sowhile** [comment]
> proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection upgrade; proxy_set_header Accept-Encoding gzip;

Thank you very much. It's very useful to me.

**Comment by getkub** [comment]
> If anyone is looking for a solution for ingress-nginx on Kubernetes like I was, add this annotation to your ingress
> 
> nginx.org/websocket-services: "code-server"
> 
> Replace code-server with whatever your code-server service name is.

Unfortunately didn't work. Did you mean to do the change you suggested + modification of ngnix too?

**Comment by getkub** [comment]
for kubernetes, I had to add BOTH suggestions from [Link1](https://github.com/coder/code-server/issues/4443#issuecomment-960591558) and annotations as follows.
```
    nginx.org/websocket-services: code-server-{{ .Values.user }}
    nginx.org/server-snippets: |
      location / {
      proxy_pass http://{{ .Values.host_domain }}:{{ .Values.port }}/;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection upgrade;
      proxy_set_header Accept-Encoding gzip;
      }  
```

Entire example below using helm chart
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server-{{ .Values.user }}
  namespace:  {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/websocket-services: code-server-{{ .Values.user }}
    nginx.org/server-snippets: |
      location / {
      proxy_pass http://{{ .Values.host_domain }}:{{ .Values.port }}/;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection upgrade;
      proxy_set_header Accept-Encoding gzip;
      }   
spec:
  tls:
  - hosts:
    - {{ .Values.host_domain }}
    secretName: code-server-secret-{{ .Values.user }}
  rules:
  - host: {{ .Values.host_domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: code-server-{{ .Values.user }}
            port:
              number: {{ .Values.port }}
```

**Comment by jeremynguyencs** [comment]
Hello, leaving this comment here just in case anyone in the future is having this issue.

Cloudflare tunnels, got this same error. Solution was going to dash.cloudflare.com and setting websockets to enabled

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/43259194/187953864-13324ca7-b350-4d09-a300-2e6e1c6da3bd.png">

**Comment by thinktech2go** [comment]
> When adding the domain or subdomain for code-server on Nginx Proxy Manager make sure to check the Websockets support to solve the problem. [![Screenshot-2022-03-25-175109](https://camo.githubusercontent.com/53d05660eba90e0ca4d5f70d5dd8e5db477b03b2f728b9e370597f292b9f4f8b/68747470733a2f2f692e6962622e636f2f436254506664782f53637265656e73686f742d323032322d30332d32352d3137353130392e706e67)](https://imgbb.com/)

This worked Thank you. I was having trouble with error on OpenBooks and this fixed that to.

**Comment by smseidl** [comment]
> A little late now, but does anyone have a working configuration for caddy2?

Did you ever get a resolution to this?

**Comment by janisii** [comment]
If you are facing wss:// websocket 1006 error on kubernetes with [NGINX Ingress Controller](https://docs.nginx.com/nginx-ingress-controller/), you can try to add timeout annotations to service ingress. 

```
nginx.org/proxy-read-timeout: "3600"
nginx.org/proxy-send-timeout: "3600"
```

**Comment by keesfluitman** [comment]
I don't want to wake up an old issue. But I've had it working, and suddenly this error came.
I'm using swag and my reverse proxy conf was working fine. The suggested addition of headers didn't work. Any tips?

**Comment by mturilli** [comment]
@code-asher thanks. Adding `Host` solved the issues with v4.12.0.

**Comment by gngpp** [comment]
code-server version: 4.12.0
NginxProxyManager custom config:
```config 
location /
{
    proxy_pass http://10.0.0.3:80;
    proxy_set_header Host code.xxx.com:7443;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header   Upgrade          $http_upgrade;  
    proxy_set_header   Connection       "Upgrade";
    proxy_connect_timeout      60;   
    proxy_send_timeout         90;   
    proxy_read_timeout         90; 
    proxy_buffer_size          4k; 
    proxy_buffers              4 32k;
    proxy_busy_buffers_size    64k;  
    proxy_temp_file_write_size 64k;
    add_header X-Cache $upstream_cache_status;
}
```

**Comment by code-asher** [comment]
`proxy_set_header Host $http_host;` should also work if you want to avoid hard-coding the host.

**Comment by keesfluitman** [comment]
I just added these headers:
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app binhex-code-server;
        set $upstream_port 8500;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Accept-Encoding gzip;
        
        Should I try to delete the binhex image and use yours? Cause it's not working for me.

**Comment by code-asher** [comment]
I am not familiar with the binhex image but if you add `--log debug` to the code-server invocation it should tell you what it is getting for the headers which might provide a clue on what is going wrong.

**Comment by aayusharyan** [comment]
Please. Please don't forget to restart ngnix after changing the configuration.
`sudo systemctl restart nginx `

**Comment by xTCry** [comment]
Fix for **Nginx-Proxy-Manager**
**VS Code** since version `4.10.1`

**"Advanced" → Custom Nginx Configuration**:
```nginx
location / {
    # proxy_ssl_verify off;
    proxy_set_header Host $host;
    proxy_set_header Accept-Encoding gzip;
    proxy_set_header X-Forwarded-Host $host;
    #proxy_set_header X-Forwarded-Host $host:$server_port;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;

    # Proxy!
    include conf.d/include/proxy.conf;
}
```

**Comment by nabilfikri** [comment]
> 

this works for me. Thanks!

**Comment by nabilfikri** [comment]
> > 
> 
> this works for me. Thanks!



> Fix for **Nginx-Proxy-Manager** **VS Code** since version `4.10.1`
> 
> **"Advanced" → Custom Nginx Configuration**:
> 
> ```nginx
> location / {
>     # proxy_ssl_verify off;
>     proxy_set_header Host $host;
>     proxy_set_header Accept-Encoding gzip;
>     proxy_set_header X-Forwarded-Host $host;
>     #proxy_set_header X-Forwarded-Host $host:$server_port;
> 
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection $http_connection;
>     proxy_http_version 1.1;
> 
>     # Proxy!
>     include conf.d/include/proxy.conf;
> }
> ```

this one works for me. Thanks!

**Comment by maxoyed** [comment]
> `proxy_set_header Host $http_host;` should also work if you want to avoid hard-coding the host.

works, Thanks!

**Comment by liuxhit** [comment]
> i got this too. i ran it in docker. i found there must be lines below in the nginx.conf to make it work location / { proxy_pass http://codeserver.xxx.xxx:8443/; proxy_set_header Host $host; proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection upgrade; proxy_set_header Accept-Encoding gzip; } this is from https://github.com/cdr/code-server/blob/main/docs/guide.md#using-lets-encrypt-with-nginx

I re-produced too, caused by the slight differences in nginx config template from https://github.com/cdr/code-server/blob/main/docs/guide.md#using-lets-encrypt-with-nginx , and issued a pull-request: https://github.com/coder/code-server/pull/6471

**Comment by zeno-io** [comment]
for me, below is work: (docker run & nginx proxy outside the docker container)
```
location / {
         add_header Access-Control-Allow-Origin *;
         add_header Access-Control-Allow-Methods *;
         add_header Access-Control-Allow-Headers *;
 
         # proxy_ssl_verify off;
         proxy_set_header Host $host;
         proxy_set_header Accept-Encoding gzip;
         #proxy_set_header X-Forwarded-Host $host;
         proxy_set_header X-Forwarded-Host $host:$server_port;
 
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection $http_connection;
         proxy_http_version 1.1;
 
         proxy_pass http://127.0.0.1:8081/;
 
       }
```

**Comment by KJZH001** [comment]
> Hello, leaving this comment here just in case anyone in the future is having this issue.
> 
> Cloudflare tunnels, got this same error. Solution was going to dash.cloudflare.com and setting websockets to enabled
> 
> <img alt="image" width="1058" src="https://user-images.githubusercontent.com/43259194/187953864-13324ca7-b350-4d09-a300-2e6e1c6da3bd.png">

Thank you. Your reply solved the problem I encountered.

**Comment by EITSxiaozhai** [comment]
> 对我来说，下面是工作：（docker run & nginx proxy externals of docker 容器）
> 
> ```
> location / {
>          add_header Access-Control-Allow-Origin *;
>          add_header Access-Control-Allow-Methods *;
>          add_header Access-Control-Allow-Headers *;
>  
>          # proxy_ssl_verify off;
>          proxy_set_header Host $host;
>          proxy_set_header Accept-Encoding gzip;
>          #proxy_set_header X-Forwarded-Host $host;
>          proxy_set_header X-Forwarded-Host $host:$server_port;
>  
>          proxy_set_header Upgrade $http_upgrade;
>          proxy_set_header Connection $http_connection;
>          proxy_http_version 1.1;
>  
>          proxy_pass http://127.0.0.1:8081/;
>  
>        }
> ```

This config file worked for me. Solved the websock error. Thanks a lot!
code-server ---> nginx

**Comment by octopus2181** [comment]
Hi,   I found an issue where if I set the port to 443:443 in the docker compose of Nginx-Proxy-Manager  ,reverse proxies are good. I was able to use code-server in the docker . But If I set a different port mapping 443 in the docker compose of Nginx-Proxy-Manager  (such as 9091:443), I can't use   linuxserver/code-server . There is an error, **"The workbench failed to connect to the server (Error: WebSocket close with status code 1006)"** . Because my port 443 is forbidden, I want to use a different port.

**Comment by code-asher** [comment]
@octopus2181 Could you open a new issue with a Docker compose I can use to reproduce the issue?  I will look into it.

**Comment by keskinonur** [comment]
For you referece, with code-server version 4.20.1, my working nginx configuration is:

```
  location / {
    proxy_pass http://localhost:8080/;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;
    proxy_set_header Accept-Encoding gzip;
  }
```

**Comment by octopus2181** [comment]
> For you referece, with code-server version 4.20.1, my working nginx configuration is:
> 
> ```
>   location / {
>     proxy_pass http://localhost:8080/;
>     proxy_http_version 1.1;
>     proxy_set_header X-Forwarded-Host $http_host;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection upgrade;
>     proxy_set_header Accept-Encoding gzip;
>   }
> ```

Yes, you are right !  Setting proxy_set_header X-Forwarded-Host $http_host , the port 9091 can connect to the code-server .
Thank you !

**Comment by wangyizhi1** [comment]
> `proxy_set_header Host $http_host;` should also work if you want to avoid hard-coding the host.
> 
> _Edit_: Or `proxy_set_header X-Forwarded-Host $http_host;`.

@code-asher 's answer works for me, and a faster way:
```
./bin/code-server --host 0.0.0.0 --trusted-origins=* ...
```

**Comment by freeluo22** [comment]
> for me, below is work: (docker run & nginx proxy outside the docker container)
> 
> ```
> location / {
>          add_header Access-Control-Allow-Origin *;
>          add_header Access-Control-Allow-Methods *;
>          add_header Access-Control-Allow-Headers *;
>  
>          # proxy_ssl_verify off;
>          proxy_set_header Host $host;
>          proxy_set_header Accept-Encoding gzip;
>          #proxy_set_header X-Forwarded-Host $host;
>          proxy_set_header X-Forwarded-Host $host:$server_port;
>  
>          proxy_set_header Upgrade $http_upgrade;
>          proxy_set_header Connection $http_connection;
>          proxy_http_version 1.1;
>  
>          proxy_pass http://127.0.0.1:8081/;
>  
>        }
> ```
This configuration works for me.

**Comment by yifanlu0227** [comment]
> --host 0.0.0.0 --trusted-origins=*

@wangyizhi1 Awesome, this works!

**Comment by kimboslice99** [comment]
For those that may be needing to proxy through IIS, here is a couple rewrite rules for that. This app uses permessage-deflate which ARR does not support, so the request fails with this 1006 error message

```xml
<rule name="removepermessagedeflate">
    <match url=".*" />
    <conditions>
        <add input="{HTTP_SEC_WEBSOCKET_EXTENSIONS}" pattern="permessage-deflate(.*)" />
    </conditions>
    <serverVariables>
        <set name="HTTP_SEC_WEBSOCKET_EXTENSIONS" value="{C:1}" />
    </serverVariables>
    <action type="None" />
</rule>
<rule name="proxy">
    <match url=".*" />
    <action type="Rewrite" url="http://10.8.0.4:8080/{R:0}" />
</rule>
```

**Comment by vector090** [comment]
> > > for me, below is work: (docker run & nginx proxy outside the docker container)对我来说，下面是工作：（docker在docker容器外运行nginx代理）
> > > ```
> > > location / {
> > >          add_header Access-Control-Allow-Origin *;
> > >          add_header Access-Control-Allow-Methods *;
> > >          add_header Access-Control-Allow-Headers *;
> > >  
> > >          # proxy_ssl_verify off;
> > >          proxy_set_header Host $host;
> > >          proxy_set_header Accept-Encoding gzip;
> > >          #proxy_set_header X-Forwarded-Host $host;
> > >          proxy_set_header X-Forwarded-Host $host:$server_port;
> > >  
> > >          proxy_set_header Upgrade $http_upgrade;
> > >          proxy_set_header Connection $http_connection;
> > >          proxy_http_version 1.1;
> > >  
> > >          proxy_pass http://127.0.0.1:8081/;
> > >  
> > >        }
> > > ```
> > 
> > 
> > This configuration works for me.这个配置对我来说很有用。
> 
> This works for me. I've tried lots of configuration, the key line is `proxy_set_header X-Forwarded-Host $host:$server_port;`这对我很有效。我尝试过很多配置，关键行是`proxy_set_header X-Forwarded-Host $host:$server_port;`

Worked like a charm.
Indeed the key line is proxy_set_header X-Forwarded-Host $host:$server_port;

**Comment by starseaheart** [comment]
> > > for me, below is work: (docker run & nginx proxy outside the docker container)
> > > ```
> > > location / {
> > >          add_header Access-Control-Allow-Origin *;
> > >          add_header Access-Control-Allow-Methods *;
> > >          add_header Access-Control-Allow-Headers *;
> > >  
> > >          # proxy_ssl_verify off;
> > >          proxy_set_header Host $host;
> > >          proxy_set_header Accept-Encoding gzip;
> > >          #proxy_set_header X-Forwarded-Host $host;
> > >          proxy_set_header X-Forwarded-Host $host:$server_port;
> > >  
> > >          proxy_set_header Upgrade $http_upgrade;
> > >          proxy_set_header Connection $http_connection;
> > >          proxy_http_version 1.1;
> > >  
> > >          proxy_pass http://127.0.0.1:8081/;
> > >  
> > >        }
> > > ```
> > 
> > 
> > This configuration works for me.
> 
> This works for me. I've tried lots of configuration, the key line is `proxy_set_header X-Forwarded-Host $host:$server_port;`

This is particularly important for those who access other programs on the server through the proxy + nginx, and these programs only listen on the port of 127.0.0.1.
