### ISSUE TITLE
resource files in termux

### ISSUE THREAD

**Issue by essential-existence** [cdr/code-server#4445]
Some pictures do not load in android chrome:
`/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/vendor/modules/code-oss-dev/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark.png`, `/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/vendor/modules/code-oss-dev/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light.png`...

**Comment by jsjoeio** [comment]
Hi there! Can you please open a complete bug report? Then we'll be able to help!

**Comment by essential-existence** [comment]
OK. I've done
