### ISSUE TITLE
Terminal text not clear

### ISSUE THREAD

**Issue by tomleo** [cdr/code-server#4456]
## OS/Web Information

- Web Browser: Brave (`Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (64-bit)`)
- Local OS: Ubuntu
- Remote OS: Ubuntu
- Remote Architecture: LInode
- `code-server --version`: latest

## Steps to Reproduce

1. Set-up linode using `StackScript`
2. Open a workspace in the browser
3. Open a terminal

## Expected

Clearly rendered text

## Actual

Hard to read text

## Screenshot

![Screenshot from 2021-11-05 23-24-16](https://user-images.githubusercontent.com/114260/140596358-ef15a116-d966-4a80-8b8b-6b089b9c2da3.png)

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by Slodziak190q** [comment]
Can you install chrome or Firefox and tell us IS this happening again?

**Comment by A2uma0** [comment]
Make sure to turn off the built in Brave Ad/Tracker-Blocker (Turn of the Shields) and any other Extensions that may block this.

**Comment by tomleo** [comment]
@A2uma0 Oh wow that did the trick! I should have checked the network tab... Thanks!

![Screenshot from 2021-11-11 09-55-31](https://user-images.githubusercontent.com/114260/141319231-83e048bd-c61b-4df5-bae0-d344a963d4b7.png)

(And thanks to everyone else who were active on this PR!)
