### ISSUE TITLE
Error with Node version

### ISSUE THREAD

**Issue by AlexandraX221** [cdr/code-server#4463]
hello i got a problem! I can't install code-server (termux)!

I use Yarn package Manager...

My nodejs version is 17.0.1, but code-server for some reason he claims that he needs version 14 and that my version is not compatible!

**Comment by jsjoeio** [comment]
This is expected! Please see this issues:
- https://github.com/cdr/code-server/issues/4415
- https://github.com/cdr/code-server/issues/4422
- https://github.com/cdr/code-server/issues/4286

Closing so we can track in those!
