### ISSUE TITLE
Code-server installation failed on Termux (Android 11)

### ISSUE THREAD

**Issue by codebysumit** [cdr/code-server#4465]
## OS/Web Information

![Screenshot_20211108-124034](https://user-images.githubusercontent.com/87431704/140699619-92f0284b-cf7e-4540-ab55-0ca2b96554f0.png)

## Steps to Reproduce

![Screenshot_20211108-124948_1](https://user-images.githubusercontent.com/87431704/140699868-1110f38a-822f-4c66-8f18-f4f55c3a925f.png)

## Expected

![Screenshot_20211108-123817](https://user-images.githubusercontent.com/87431704/140699951-2b016015-89de-4898-8217-e3ca0bd7d3c0.png)
![Screenshot_20211108-123833](https://user-images.githubusercontent.com/87431704/140699959-e8b39a43-a51e-48b5-b7ae-401d229c3649.png)
![Screenshot_20211108-123847](https://user-images.githubusercontent.com/87431704/140699964-ebfaa105-3195-4627-9072-c33ad33ede98.png)

## Actual

code-server couldn't install

**Comment by jsjoeio** [comment]
This is expected! Please see this issues:
- https://github.com/cdr/code-server/issues/4415
- https://github.com/cdr/code-server/issues/4422
- https://github.com/cdr/code-server/issues/4286

Closing so we can track in those!

**Comment by Dark652** [comment]
![Uploading 54437519-fdad4600-475e-11e9-8f14-4e7ea35fa11b.png…]()
