### ISSUE TITLE
Function call completion 

### ISSUE THREAD

**Issue by Msadat97** [cdr/code-server#4467]
### Discussed in https://github.com/cdr/code-server/discussions/4434

<div type='discussions-op-text'>

<sup>Originally posted by **Msadat97** November  3, 2021</sup>
Hi, 

I'm using code-server and python extension, and there is a feature that has frustrated me recently. Whenever I use autocompletion for typing a function name, it automatically types its arguments too. This feature is not present in the original vscode. Could you please tell me how to disable this type of autocompletion?</div>

Dear all,

I recently noticed that a feature had been added to the code-server python extension that types the input parameters of a function call as part of auto-completion. It would be great if you could make an option available for turning this feature off for several reasons:

1. It isn't easy to type a function call with different names other than the ones mentioned in the function definition (I need to erase the parameters and type them all over again.)
2. Type hinting is now extremely difficult as the call to a class automatically types everything in the __init__ function.
3. It does not provide auto-completion once you are inside the placeholders. 

Also, as I mentioned above, this feature is not present in the original vscode python extension and is introduced in the code-server python extension v2021.10.

**Comment by jsjoeio** [comment]
We don't own the Python Extension! This is by Microsoft. Can you please open an extension on [their repo](https://github.com/Microsoft/vscode-python/issues)?

**Comment by Msadat97** [comment]
I don't think they can do much. The new update of the Microsoft python extension uses Pylance by default, and this issue is related to Jedi. Are you going to support Pylance too? I heard that's not possible due to license issues.

**Comment by jsjoeio** [comment]
> The new update of the Microsoft python extension uses Pylance by default, and this issue is related to Jedi 

Ah okay, hmm...well I'm not sure we can do much either here. 

> Are you going to support Pylance too

We're not going to do anything to _not_ support Pylance. I am not finding it on Open VSX and it doesn't look open source. I think you're right, I am not sure if the license permits it to be used in code-server.

I'm going to close this for now since any issues that are specific to the extension should be raised upstream (we can't do much unfortunately).
