### ISSUE TITLE
Theme images on the welcome page are broken

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#4483]
Introduced in #4414

@code-asher may have more details.

**Comment by code-asher** [comment]
To test:

1. Open the welcome page
2. Observe broken images

The images do exist and you can open them manually so it is unclear why they fail to load.

**Comment by jsjoeio** [comment]
I will probably pick this up Monday or Tuesday (might not have time today).

**Comment by jsjoeio** [comment]
Verified this is still an issue

![image](https://user-images.githubusercontent.com/3806031/141538684-39306cba-85ea-46ab-89cf-a61619e8e565.png)

Errors observed in the console:
![image](https://user-images.githubusercontent.com/3806031/141538872-a34f6fb3-dff1-4341-a5dd-f89b89b42949.png)

```javascript
index.html:1 Mixed Content: The page at 'https://d9385a7a-36ed-4047-9202-43fc2176f639.vscode-webview.net/insider/dc1a6699060423b8c4d2ced736ad70195378fddf/out/vs/workbench/contrib/webview/browser/pre/index.html?id=d9385a7a-36ed-4047-9202-43fc2176f639&swVersion=2&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=http%3A%2F%2Flocalhost%3A8080' was loaded over HTTPS, but requested an insecure element 'http://localhost:8080/static/out/vs/workbench/contrib/welcome/gettingStarted/common/media/light.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
index.html:1 Mixed Content: The page at 'https://d9385a7a-36ed-4047-9202-43fc2176f639.vscode-webview.net/insider/dc1a6699060423b8c4d2ced736ad70195378fddf/out/vs/workbench/contrib/webview/browser/pre/index.html?id=d9385a7a-36ed-4047-9202-43fc2176f639&swVersion=2&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=http%3A%2F%2Flocalhost%3A8080' was loaded over HTTPS, but requested an insecure element 'http://localhost:8080/static/out/vs/workbench/contrib/welcome/gettingStarted/common/media/dark.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
index.html:1 Mixed Content: The page at 'https://d9385a7a-36ed-4047-9202-43fc2176f639.vscode-webview.net/insider/dc1a6699060423b8c4d2ced736ad70195378fddf/out/vs/workbench/contrib/webview/browser/pre/index.html?id=d9385a7a-36ed-4047-9202-43fc2176f639&swVersion=2&extensionId=&platform=browser&vscode-resource-base-authority=vscode-resource.vscode-webview.net&parentOrigin=http%3A%2F%2Flocalhost%3A8080' was loaded over HTTPS, but requested an insecure element 'http://localhost:8080/static/out/vs/workbench/contrib/welcome/gettingStarted/common/media/monokai.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
light.png:1 Failed to load resource: net::ERR_FAILED
dark.png:1 Failed to load resource: net::ERR_FAILED
monokai.png:1 Failed to load resource: net::ERR_FAILED
```

**Comment by jsjoeio** [comment]
## Notes

### Do the files exist? 

When the images fail to load, the first question we ask is, "Do the images exist in the locations we expect them to exist?"

In upstream, they live [here](https://github.com/microsoft/vscode/tree/main/src/vs/workbench/contrib/welcome/gettingStarted/common/media).

Looking at our fork, we see them [here](https://github.com/cdr/vscode/tree/code-server-v2/src/vs/workbench/contrib/welcome/gettingStarted/common/media).

✅ Files exist (at least in the correct place).

### Do the files exist in the build output?

When we run `yarn watch`, we create an `/out` directory. Let's check if they exist there.

**Comment by jsjoeio** [comment]
(this would break for airgapped users so good thing we are fixing it)

## Notes on Solution

Looking at `vscode/src/vs/server/webClientServer.ts` around L303, we want to use the `webviewEndpoint` but when we do, the iframe is blank 🤔

**Comment by jsjoeio** [comment]
Fixed via https://github.com/cdr/vscode/pull/16
