### ISSUE TITLE
Add back support for non-encoded syntax for folder and workspace query params

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#4484]
Introduced in #4414

@code-asher may have more details.

**Comment by code-asher** [comment]
To test:
1. Try going to localhost:8080/?folder=/path/to/my/directory
2. Observe the directory does not open

We used to patch it so you could use this paths like these but currently you have to do some encoding by hand, for example vscode-remote%3A%2F%2Fpath%2Fto%2Fmy%2Fdirectory which feels unreasonable.

**Comment by jsjoeio** [comment]
@code-asher can we close this via https://github.com/cdr/vscode/pull/15?
