### ISSUE TITLE
Open the last opened workspace/directory when there is no folder/workspace query param 

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#4485]
Open the last opened workspace/directory when there is no folder/workspace query param (unless the ignore-last-opened flag is set)

Introduced in #4414

@code-asher may have more details.

**Comment by code-asher** [comment]
To test:
1. Open a directory or workspace
2. Remove the ?folder or ?workspace query param and reload
3. Observe the last directory/workspace you opened is no longer open

**Comment by TeffenEllis** [comment]
I believe this is no longer possible since upstream moved this to behavior to a client.

**Comment by code-asher** [comment]
The way we did this before was to read our settings file and set it in the workbench web configuration which takes a URIs for the folder and workspace to open.

**Comment by jsjoeio** [comment]
Should be fixed by https://github.com/cdr/vscode/pull/18

**Comment by jsjoeio** [comment]
Fixed via https://github.com/cdr/vscode/pull/18
