### ISSUE TITLE
Add back removed `ignore-last-opened` functionality 

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#4487]
Add back removed `ignore-last-opened` functionality (actually the last opened functionality is missing entirely)

**Comment by jsjoeio** [comment]
## Raw Notes

Get the last opened directory (folder or workspace).
- check query variables
- look at settings.jon

**Comment by jsjoeio** [comment]
We believe this has been fixed via https://github.com/cdr/vscode/pull/18 but assigning to @code-asher to confirm and close.

**Comment by code-asher** [comment]
There is still no way to force code-server to always open to an empty/no
workspace which is the feature this flag enables.

**Comment by jsjoeio** [comment]
Ahhh okay so we need to implement this still then.

**Comment by jsjoeio** [comment]
We think this may be in `main`. I will test then close if true.

**Comment by jsjoeio** [comment]
I tested the above cases and here is what the results where.

## Running code-server should open previously opened directory

This works as expected. Steps to reproduce:
1. run `yarn watch` to start code-server locally
2. open localhost:8080 in browser
3. open a directory: `cs-test`
4. close tab
5. repeat step 2
6. see new directory `cs-test` opened in new tab

![image](https://user-images.githubusercontent.com/3806031/144133814-7ef248a1-81bc-4b3a-b0bd-cc86c2d4c9dd.png)
