### ISSUE TITLE
code-server: incompatible node version in Termux

### ISSUE THREAD

**Issue by masterjavaofficial** [cdr/code-server#4500]
## OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

## Steps to Reproduce

1. apt update && apt full-upgrade -y
2. apt install nodejs yarn -y
3. yarn global add code-server

## Expected
Code-Server should be installed.

## Actual
Node version seems to be incompatible, so Code-Server is not getting installed.

## Logs
```
~ $ yarn global add code-server
yarn global v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
error code-server@3.12.0: The engine "node" is incompatible with this module. Expected version "= 14". Got "16.13.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
~ $
```

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by sascha1337** [comment]
same. ffi bindings wont compile, in case of patched version in package.json. sad. maybe manually install nodejs tarball with linked musl arm64 libc

**Comment by masterjavaofficial** [comment]
> same. ffi bindings wont compile, in case of patched version in package.json. sad. maybe manually install nodejs tarball with linked musl arm64 libc

Huh. When will code server support Node 16? ☹️

**Comment by jsjoeio** [comment]
Hey all! We're aware of this and hope to have a fix out soon! We have to prioritize some other things but please follow these issues for updates:
- https://github.com/cdr/code-server/issues/4458
- https://github.com/cdr/code-server/issues/4422
- https://github.com/cdr/code-server/issues/4415
- https://github.com/cdr/code-server/issues/4286

**Comment by AFOEK** [comment]
Hi, I got same error but I had different version node error. Pics included
![image](https://user-images.githubusercontent.com/52521676/236372400-83b69d20-591c-4181-97a9-1740f444f4a1.png)

**Comment by code-asher** [comment]
code-server depends on Node 16 so you will need to downgrade Node or attempt to bypass the restriction.

`FORCE_NODE_VERSION=19 yarn global add --ignore-engines code-server` to bypass but there is no guarantee code-server will run correctly (or at all) or even build.

**Comment by felipechierice** [comment]
> code-server depends on Node 16 so you will need to downgrade Node or attempt to bypass the restriction.
> 
> `FORCE_NODE_VERSION=19 yarn global add --ignore-engines code-server` to bypass but there is no guarantee code-server will run correctly (or at all) or even build.

Worked for me. Thank you Mr.
