### ISSUE TITLE
[Helm chart] Typo in Helm chart notes

### ISSUE THREAD

**Issue by louis030195** [cdr/code-server#4504]
In
https://github.com/cdr/code-server/blob/66060408354c223918cb1df4b0cb8849aad4c9c7/ci/helm-chart/templates/NOTES.txt#L20

you forgot the namespace, i.e. `--namespace {{ .Release.Namespace }`

**Comment by jsjoeio** [comment]
Oh no! cc @jlandowner do you think that was in your PR?

**Comment by jlandowner** [comment]
Do you mean #4497?  It's not for `NOTES.txt`.
This is another issue.
