### ISSUE TITLE
Broke Log-in Screen and Blank White Background Upon Login

### ISSUE THREAD

**Issue by Arbsahoy** [cdr/code-server#4513]
## OS/Web Information

- Web Browser: Chrome and Edge
- Local OS: Linux Server Ubuntu 20.04 (server code-server is running)
- Remote OS: Windows 10 fresh-install
- Remote Architecture: x64
- `code-server --version`: 3.12.0 b37ff28a0a582aee84a8f961755d0cb40a4081db

## Steps to Reproduce

1. Unsure, went to login today and it was jacked
2.
3.

## Expected

Login with the password, goes to main screen.

## Actual

Login screen looks jank, has a spot for what looks like a user name and password, enter password and am presented with a blank white screen.

## Logs

I ran the --log debug and then checked the logs and there was no information in them; may need help running the codes again.

## Screenshot

Login screen:
https://snipboard.io/xByLNC.jpg

After login:
https://snipboard.io/UZaAIE.jpg

## Notes

I thought it could be websockets so I verified my chrome was indeed running websockets. 

I have the system reversed proxied from cloudflare domain using ngnix. verified websockets was enabled on cloudflare.

I am also running a Wordpress site with out issue reversed proxied as well. 

Have TLS encryption from Cloudflare.

Everything was working alright a few days ago - I do not know what has changed. I tried clearing chrome cache, cloudflare cache, re-running the install command for code-server, looked at the other reasons why there would be a blank screen and added a few lines that said "would work".

This issue can be reproduced in VS Code: Not Tested

**Comment by Arbsahoy** [comment]
I am wondering if it's not the wordpress nginx config that is messing it up. I have my reverse proxy to look at:

location /aWebName {
 reverse_proxy http://localhost:8080
 rest of the configs. . .
 }
 
 When I ran the 'code-server --log debug' it returned with the /login redirect to ./ which my noobish mind thinks it's trying to forward to one of the Wordpress sites?

**Comment by Arbsahoy** [comment]
Are there any specific ways to enable the logging? If not, I'm pretty sure
I can Google it.

**Comment by jsjoeio** [comment]
@Arbsahoy [this article](https://appuals.com/open-browser-console/) explains how to view the console in any browser.

And then wherever you run `code-server`, you should see logs (maybe you run that in a terminal in your Linux environment?)

**Comment by Arbsahoy** [comment]
Log-in screen: 
https://snipboard.io/pS5zsM.jpg
After Log-in
https://snipboard.io/HoKLRy.jpg

code-server --log debug:
debug redirecting from / to ./login
debug 0 active connections
---tried logging in here---
debug got cookie doman {"host":"domain.com"}
debug redirecting from / to ./login
debug forking vs code
debug setting up vs code
debug vscode got meesgae from code-server {"type":"init"}
debug 0 active connections

When I inspected the log they are empty... maybe I am not looking at the right ones?

**Comment by jsjoeio** [comment]
Those screenshots are helpful. I don't know why a bunch of resources are failing though 🤔 Do you have some ad blocker on? Or a firewall maybe? this is very strange

**Comment by Arbsahoy** [comment]
I built a new computer and it started happening then. I wonder if it's part
of the chrome install it put in an old ad block? I'll look into that in a
bit. Baby crying n all....

**Comment by Arbsahoy** [comment]
update: there is not ad blocker on my chrome, i've tried edge with the same results. There were no changes in firewalls to upset Code-Server. Perhaps it is my nginx config? Since i have WP and CS on the same machine. But it *was* working it what's getting me.

**Comment by jsjoeio** [comment]
> Baby crying n all....

Ha, I know that feeling.

> Perhaps it is my nginx config? Since i have WP and CS on the same machine. But it was working it what's getting me.

Most likely! Mind posting your nginx config here?

> But it was working it what's getting me.

There's a chance something changed upstream (i.e. in VS Code) in between upgrades that affected it.

**Comment by Arbsahoy** [comment]
Blocks between #new and #end new are my attempts at adding some nginx config to correct the issue, since they arent a fix I am going to remove them. As for the Wordpress config I just copied/pasted and it was working..

`server {
  listen 80;
  listen [::]:80;
  server_name <domain>.com www.<domain>.com;
  return 301 https://$host$request_uri;
}

 server{
 #ssl parts

  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  ssl_verify_client on;

#new
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GC>
#END NEW

  ssl_client_certificate /etc/ssl/cloudflare.pem;
  ssl_certificate /etc/ssl/certs/codeserver.pem;
  ssl_certificate_key /etc/ssl/private/codeserver.key;

  server_name codingwarden.com www.codingwarden.com;
  root /usr/share/nginx/wordpress/wordpress/;
  index index.php index.html index.htm index.nginx-debian.html;
  location / {
    try_files $uri $uri/ /index.php;
  }

   location ~ ^/wp-json/ {
     rewrite ^/wp-json/(.*?)$ /?rest_route=/$1 last;
   }

  location ~* /wp-sitemap.*\.xml {
    try_files $uri $uri/ /index.php$is_args$args;
  }

  error_page 404 /404.html;
  error_page 500 502 503 504 /50x.html;

  client_max_body_size 2M;

  location = /50x.html {
    root /usr/share/nginx/html;
  }

  location ~ \.php$ {
    fastcgi_pass unix:/run/php/php7.4-fpm.sock;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
    include snippets/fastcgi-php.conf;
  }

  #enable gzip compression
  gzip on;
  gzip_vary on;
  gzip_min_length 1000;
  gzip_comp_level 5;
  gzip_types application/json text/css application/x-javascript application/javascript image/svg+xml;
  gzip_proxied any;

  # A long browser cache lifetime can speed up repeat visits to your page
  location ~* \.(jpg|jpeg|gif|png|webp|svg|woff|woff2|ttf|css|js|ico|xml)$ {
       access_log        off;
       log_not_found     off;
       expires           360d;
  }

  # disable access to hidden files
  location ~ /\.ht {
      access_log off;
      log_not_found off;
      deny all;
  }


#for codeserver
  location /codeserver/ {
      proxy_pass http://127.0.0.1:8080/;
      proxy_set_header Host           $host;
#new
      proxy_set_header X-Real-IP      $remote_addr;
      proxy_set_header X-Forwaded-For $proxy_add_x_forwarded_for;
      proxy_http_version              1.1;
      access_log                      off;
#end new added
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Accept-Encoding gzip;
  }


}`

**Comment by jsjoeio** [comment]
Hmm...I haven't used nginx in a while but maybe @code-asher sees something

**Comment by Arbsahoy** [comment]
I'll await then. Using VS Code till then XD

**Comment by code-asher** [comment]
The janky login screen seems to indicate the CSS has failed to load.
Could you look at the network tab in the browser and post the URL for
the CSS and what the error is?

**Comment by Arbsahoy** [comment]
Apologize for the delay it appears the holiday season has started.

When I get home tonight I'll give it a go.

**Comment by Arbsahoy** [comment]
I haven't forgot about you guys, but i did forget it was the holiday season.....

**Comment by Arbsahoy** [comment]
Login screen: 
![image](https://user-images.githubusercontent.com/82701320/144716965-656cdd18-c2a7-473a-9393-bdb95f096654.png)

error 1, global.css: 
![image](https://user-images.githubusercontent.com/82701320/144716954-3d06df6e-ffb3-40a6-98d5-f75287bc3787.png)

error 2, login.css: 
![image](https://user-images.githubusercontent.com/82701320/144716943-eb12262a-e470-4f72-8404-29dce9d9b376.png)

error 3, browserified.css: 
![image](https://user-images.githubusercontent.com/82701320/144716923-e7952100-cd84-459e-8000-13137b1b616e.png)

**Comment by Arbsahoy** [comment]
After Logging in:
![image](https://user-images.githubusercontent.com/82701320/144716984-56ebb5f9-9bef-4381-bd66-e20d082499a5.png)

workbench: 
![image](https://user-images.githubusercontent.com/82701320/144716999-1d2a6dca-afba-459d-b6dc-c4fbcaf90f26.png)

vscode.broswerified.js: 
![image](https://user-images.githubusercontent.com/82701320/144717003-2b2fc306-a5c8-45f6-8838-d6512d8335d8.png)

loader:
![image](https://user-images.githubusercontent.com/82701320/144717006-c8da4657-b040-47e7-b618-e9c9ff892883.png)

workbench.nls.js:
![image](https://user-images.githubusercontent.com/82701320/144717017-f20aead0-236f-4bb7-b93f-ddf52e562d8d.png)

workbench.api.js:
![image](https://user-images.githubusercontent.com/82701320/144717026-a9708f7a-e210-4ae9-a9b7-bd8af1e3134d.png)

loader:
![image](https://user-images.githubusercontent.com/82701320/144717031-f930bf15-5dd2-45a3-914b-5b290652f283.png)

workbench.nls.js:
![image](https://user-images.githubusercontent.com/82701320/144717050-ab1fd95f-2cfd-45b5-bfab-2ca1e8575493.png)

**Comment by Arbsahoy** [comment]
it appears the WP installation is interfering with code-server.... which is odd because I also think it's theme based; it wasn't until I installed astera theme that this became an issue iirc.

**Comment by Arbsahoy** [comment]
I'll leave the site up and running for the time being.

**Comment by Arbsahoy** [comment]
Baby clicked wrong button, my apologizes.

**Comment by code-asher** [comment]
Ah interesting maybe it is this line:

location ~* \.(jpg|jpeg|gif|png|webp|svg|woff|woff2|ttf|css|js|ico|xml)$ {

Could be since that triggers the code server block does not get
triggered?  I am definitely not an NGINX expert.

**Comment by Arbsahoy** [comment]
oo interesting... I'll look into that - i think I know exactly which bit that is. I'll comment it out and see what happens

**Comment by Arbsahoy** [comment]
![image](https://user-images.githubusercontent.com/82701320/145664016-94efd2a8-dfb2-456e-8122-e8c4c7baf41f.png)
Victory! Seems the issue was with that bit which was added to allow a longer browser cache lifetime:

`location ~*\.(jpg|...|xml)${
  access_log off;
  log_not_found off;
  expires 360d;}`

**Comment by Arbsahoy** [comment]
just realized this is probably going to drive a lot of traffic to my site... welp.
