### ISSUE TITLE
Some issues running code-server within code-server

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#4519]
It should spin up a new code-server as long as something in the format `code-server [file]` is not passed (in that case it opens in the existing instance) but it seems to spawn some other CLI instead.

Installing extensions also seems to hang at the end.

**Comment by jsjoeio** [comment]
I think this is an edge case that can be moved to 4.0.1. @code-asher let me know if you disagree.

**Comment by code-asher** [comment]
This happens consistently and all you have to do is run code-server so
it does not feel like an edge case to me.

Anyone trying to develop code-server from code-server will run into
issues (for example from the product).

The extension installation hang is also consistent and pretty serious
IMO.

**Comment by jsjoeio** [comment]
> (for example from the product)

Didn't consider that scenario. Fair point! Moved back to 4.0.0

**Comment by jsjoeio** [comment]
Heads-up: we've started working on this.
