### ISSUE TITLE
404s are reported as 500s

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#4521]

**Comment by jsjoeio** [comment]
How critical is this? Could this one be pushed to the next milestone? (asking to see if we can prevent increasing the scope of 4.0.0)

**Comment by code-asher** [comment]
We could probably push this off.  It is not impossible this could cause
issues if users are depending on the code in some way but it does seem
unlikely?

**Comment by jsjoeio** [comment]
Ah got it. Well I guess we'll see. Shooting for Dec. 3rd release. I guess this could be a potential easy/quick fix, right?
