### ISSUE TITLE
/vscode no longer works

### ISSUE THREAD

**Issue by code-asher** [cdr/code-server#4523]
It requires a trailing slash where it did not before (was optional before).

**Comment by jsjoeio** [comment]
Fixed via https://github.com/cdr/code-server/pull/4522

**Comment by jsjoeio** [comment]
@TeffenEllis feel free to pick this one up if you want

**Comment by TeffenEllis** [comment]
Resolved via https://github.com/cdr/vscode/commit/43af6fc0c92bb211dbea9f8357698be330e749b1
