### ISSUE TITLE
Document updating VS Code

### ISSUE THREAD

**Issue by jsjoeio** [cdr/code-server#4533]
With our new fork, our docs are out-of-date for how to update VS Code. We should document this so anyone can do it.

**Comment by andreivisan** [comment]
I have written a description here https://github.com/andreivisan/Raspberry-Pi-4-Code-Server and created a video here https://youtu.be/75Sn-fGt3UA .

**Comment by jsjoeio** [comment]
@andreivisan awesome! You should share those under Show and Tell [here](https://github.com/cdr/code-server/discussions/new) 🙌

**Comment by andreivisan** [comment]
Thank you @jsjoeio ! I created it here https://github.com/cdr/code-server/discussions/4583
