### ISSUE TITLE
"java.configuration.runtimes" setting is not available.

### ISSUE THREAD

**Issue by neesonqk** [cdr/code-server#4555]
## OS/Web Information

- Web Browser: Chrome
- Local OS: MacOS BigSur
- Remote OS: Ubuntu 20.04 LTS
- Remote Architecture: 
- `code-server --version`: 3.12.0 b37ff28a0a582aee84a8f961755d0cb40a4081db

## Steps to Reproduce

<img width="882" alt="Screenshot 2021-11-27 at 5 21 20 PM" src="https://user-images.githubusercontent.com/7279067/143675678-691fe2e3-2512-487e-9f95-458b925b4313.png">

**Comment by jsjoeio** [comment]
Hi there! Do you mind opening a full bug report [here](https://github.com/cdr/code-server/issues/new?assignees=&labels=&template=bug-report.md&title=)? That'll help us help you faster! Thanks!

**Comment by thinkbase** [comment]
It seems "Machine" settings take effect :
```
$more ~/.local/share/code-server/Machine/settings.json 
{
    "java.configuration.runtimes": [
        {
          "name": "JavaSE-1.8",
          "path": "/usr/lib/jvm/java-8-openjdk-amd64"
        },
        {
          "name": "JavaSE-17",
          "path": "/usr/lib/jvm/java-17-openjdk-amd64",
          "default": true
        }
    ]
}
```
