### ISSUE TITLE
How is the custom marketplace API set up?

### ISSUE THREAD

**Issue by haydennyyy** [cdr/code-server#460]
## Description

Basically I'm looking into building a custom version of VSCode (not with code-server, that serves a different purpose) and I'd just like to know how Coder deals with the marketplace issue. I think @coadler told me you guys have a custom marketplace API in place, so I'd like to know how that's set out. Thanks in advance!

## Related Issues

None

**Comment by nol166** [comment]
The extension marketplace API doesn't require any authorization or anything.

A sample query would be:
`http://v1.extapi.coder.com/search?vim`

but I believe you can also add some other query params like (50 is the max per page)
`page=1&page_size=50&sort=downloads`

**Comment by kylecarbs** [comment]
Our extension API is not publicly documented though, so endpoints may change.

We also use the TAR format instead of ZIPs.

**Comment by haydennyyy** [comment]
Well, what's the basic layout of it? If it's lengthy I can hop on Discord quickly.

**Comment by kylecarbs** [comment]
My apologies for the slow resp!

`/search` queries for extensions. That's pretty much it!
