### ISSUE TITLE
code-server 4.0.0 behind nginx reports wrong port

### ISSUE THREAD

**Issue by fritterhoff** [cdr/code-server#4607]
Using the following nginx configuration (fragment) in combination the SSL and code server reports port 80 in code-server instead of 443/https?

```
    location / {
      proxy_pass http://localhost:8080/;
      proxy_set_header Host $host;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection upgrade;
      proxy_set_header Accept-Encoding gzip;
    }
```

**Comment by benz0li** [comment]
Same problem with my setup. I'm running code-server via JupyterHub as part of a JupyterLab image with Traefik as a reverse proxy.

@code-asher @jsjoeio @bpmct You may check at https://vscode-r.jupyter.b-data.ch.  
ℹ️ I have whitelisted your GitHub accounts for this deployment back in June.

**Comment by fritterhoff** [comment]
Propably completely independent from the proxy. Can reproduce it with Caddy and Apache ;).

**Comment by jsjoeio** [comment]
@fritterhoff do you mind posting repro steps for Caddy? I have experience with that so it'd be easier for me to investigate

**Comment by fritterhoff** [comment]
Well pretty simple and without any magic:

1. Configure Caddy:
```
mydomain.com {
  reverse_proxy 127.0.0.1:8080
}
```
2. Restart caddy
3. Start code-server 
4. Open code-server in your browser 
5. Recognize that the port in lower left corner is :80 and service-workers don't work

**Comment by fritterhoff** [comment]
@code-asher you mention in your last commit "does not work behind reverse proxies unless they send the right headers containing information about the proxied source" which headers would be required?

**Comment by code-asher** [comment]
`Forwarded` is the best one (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded) followed by `X-Forwarded-Proto` combined with either `X-Forwarded-Host` or `Host`.

**Comment by code-asher** [comment]
There might still be weirdness caused by the code explicitly adding an `80` or `443` to the authority for some reason but I think it will work if forwarding headers are set.

**Comment by fritterhoff** [comment]
Mhm okay than the current implementation may also have a bug as caddy sets some headers by default:

```
By default, Caddy passes thru incoming headers to the backend-including the Host header—without modifications, with two exceptions:

    It adds or augments the X-Forwarded-For header field.
    It sets the X-Forwarded-Proto header field.
```

**Comment by benz0li** [comment]
@code-asher Træfik also sets `X-Forwarded-Proto` and `X-Forwarded-Host` (among others) at https://vscode-r.jupyter.b-data.ch.  
ℹ️  See https://whoami.b-data.ch for all headers set by default by Træfik.

**Comment by code-asher** [comment]
Huh, interesting.  There must be something else wrong with the code.  I am curious as to the problem but I ended up just removing the logic entirely in favor of just setting it to `location.host` on the frontend so it should just work regardless of headers now.  I might look into it later just to see what went wrong.

**Comment by code-asher** [comment]
I poked into it anyway but it seems like the location headers should work:

```
> uri = getRemoteAuthority({headers: { "X-Forwarded-Proto": "https", "X-Forwarded-Host": "vscode-r.jupyter.b-data.ch" }})
> `${uri.hostname}:${uri.port || (uri.protocol === 'https:' ? '443' : '80')}`
'vscode-r.jupyter.b-data.ch:443'
```

And yet it is actually sending "vscode-r.jupyter.b-data.ch:80".

I guess it is academic at this point but quite confusing. :confused:

**Comment by code-asher** [comment]
Ah...the headers appear to be lowercased so they do not match.  Not sure if they always come that way or if Express lowercases them.  :facepalm:

**Comment by voxsoftware** [comment]
still same problem

**Comment by tjpalanca** [comment]
As a temporary solution just in case this helps anyone, I've just made sure that `X-Forwarded-Host` returned the `https://<code-server-url>:443` and everything works perfectly.

**Comment by rrgeorge** [comment]
I fixed this issue in Apache by adding a Forwarded header to my apache config as follows:
`RequestHeader set Forwarded "for=%{REMOTE_ADDR}s;host=%{SERVER_NAME}s;proto=https"`
Not sure exactly what the syntax is for nginx, but a similar approach should solve it.
