### ISSUE TITLE
code-server v4 unable to load resources (e.g. new theme) -- requesting to port 80?

### ISSUE THREAD

**Issue by drmrbrewer** [cdr/code-server#4608]
I'm getting the following error in the console when trying to load a new theme (in a fresh v4 installation):

	  GET https://code-server.mydomain.com:80/vscode-remote-resource?path=%2Fusr%2Flib%2Fcode-server%2Fvendor%2Fmodules%2Fcode-oss-dev%2Fextensions%2Ftheme-defaults%2Fthemes%2Fdark_plus.json&tkn=0000 net::ERR_SSL_PROTOCOL_ERROR

	  ERR Unable to load vscode-remote://code-server.mydomain.com:80/usr/lib/code-server/vendor/modules/code-oss-dev/extensions/theme-defaults/themes/dark_plus.json: Failed to fetch: Error: Unable to load vscode-remote://code-server.mydomain.com:80/usr/lib/code-server/vendor/modules/code-oss-dev/extensions/theme-defaults/themes/dark_plus.json: Failed to fetch
		at https://code-server.mydomain.com/static/out/vs/workbench/workbench.web.api.js:1926:79062
		at async Z.restoreColorTheme (https://code-server.mydomain.com/static/out/vs/workbench/workbench.web.api.js:1926:79687)

My installation is in this context:  https://github.com/cdr/code-server/discussions/4529#discussioncomment-1717543  (just replacing `curl install.sh | sh` with `curl install.sh | sh -s -- --version=4.0.0`).

I also have the following `ENTRYPOINT` (i.e. binding to `8443` rather than `8080`):

    ENTRYPOINT [ "code-server", "/root/workspace", "--bind-addr", "0.0.0.0:8443" ]

It all seems to fire up just fine with `v4`... just not able to change theme for a start.

I'm also seeing the following (not really doing anything to prompt it):

	  ERR Unable to load and parse grammar for scope source.json.comments from vscode-remote://code-server.mydomain.com:80/usr/lib/code-server/vendor/modules/code-oss-dev/extensions/json/syntaxes/JSONC.tmLanguage.json TypeError: Failed to fetch
		at v.readExtensionResource (extensionResourceLoaderService.ts:46)
		at Object.readFile (abstractTextMateService.ts:246)
		at Object.loadGrammar (TMGrammarFactory.ts:53)
		at e.<anonymous> (main.js:107)
		at main.js:46
		at Object.next (main.js:27)
		at main.js:21
		at new Promise (<anonymous>)
		at i (main.js:17)
		at e._doLoadSingleGrammar (main.js:103)
	log.ts:313   ERR No grammar provided for <source.json.comments>: Error: No grammar provided for <source.json.comments>
		at d (https://code-server.mydomain.com/static/node_modules/vscode-textmate/release/main.js:1:3170)
		at e.processQueue (https://code-server.mydomain.com/static/node_modules/vscode-textmate/release/main.js:1:2533)
		at e.<anonymous> (https://code-server.mydomain.com/static/node_modules/vscode-textmate/release/main.js:1:30634)
		at https://code-server.mydomain.com/static/node_modules/vscode-textmate/release/main.js:1:28678
		at Object.next (https://code-server.mydomain.com/static/node_modules/vscode-textmate/release/main.js:1:28783)
		at s (https://code-server.mydomain.com/static/node_modules/vscode-textmate/release/main.js:1:27497)

**Comment by drmrbrewer** [comment]
I suspect that this is a duplicate of: https://github.com/cdr/code-server/issues/4607

**Comment by drmrbrewer** [comment]
When I access code-server via http rather than https, switching theme does work... though the theme previews are not shown so it's a case of choosing the theme via "Browse Color Themes".

**Comment by drmrbrewer** [comment]
@jsjoeio I've set up a demo deployment of code-server v4 [over here](https://vscode4.cloud3squared.com/) so that you can play around with it.  Password is `issue-4608`.

**Comment by code-asher** [comment]
Thank you for the bug report and the demo!  Will try to fix this asap.

**Comment by drmrbrewer** [comment]
This is the Dockerfile used to build the code-server image (it's basically what @code-asher suggested [here](https://github.com/cdr/code-server/discussions/4529#discussioncomment-1717543) but with a few extra bits and pieces):

	FROM ubuntu:20.04
	ENV DEBIAN_FRONTEND=noninteractive
	RUN apt-get update \
	 && apt-get install -y curl \
	 && curl -fsSL https://code-server.dev/install.sh | sh -s -- --version=4.0.0 \
	 && apt-get clean \
	 && rm -rf /var/lib/apt/lists/*
	RUN apt-get update \
	 && apt-get install -y \
		git \
		zip \
		curl \
		tzdata \
		iputils-ping \
		nano \
	 && apt-get clean \
	 && rm -rf /var/lib/apt/lists/*
	RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
	RUN apt-get update && apt-get install -y nodejs \
	 && apt-get clean \
	 && rm -rf /var/lib/apt/lists/*
	RUN sed -i 's/#force_color_prompt=yes/force_color_prompt=yes/g' /root/.bashrc
	RUN mkdir -p /root/workspace /root/.ssh
	EXPOSE 8443
	ENTRYPOINT [ "code-server", "/root/workspace", "--bind-addr", "0.0.0.0:8443" ]

**Comment by drmrbrewer** [comment]
Having now tried v4.0.1 I can confirm that this issue appears to be resolved... but you knew that already!  Nice work!
