### ISSUE TITLE
Can't install code-server 3.12.1

### ISSUE THREAD

**Issue by amiria703** [cdr/code-server#4618]
I have problem with node version which is solved in 3.12.1 but whenever I'm trying to install it using yarn or npm I get the error that this version does not exist:
![Screenshot_20211214-180045_Termux](https://user-images.githubusercontent.com/54179379/146017753-d4012942-d954-4b6e-a331-c4f101fa67ce.png)

_Originally posted by @amiria703 in https://github.com/cdr/code-server/discussions/4617_

**Comment by jsjoeio** [comment]
That's expected - if you see in your screenshot, it prints a list of the available versions. There is no 3.12.1. You probably want to install 3.12.0 then.

I'm going to close this but feel free to reply if you're confused or need more help

**Comment by amiria703** [comment]
@jsjoeio 
Thanks for your reply
I have some problems with #4230 
It fixed my problem and I checked it should be in the 3.12.1 version
Anyway, I can't install versions in the npm and yarn because of nodejs version
Is there anyway to build and run the code-server from main branch (source in GitHub)?

**Comment by jsjoeio** [comment]
> I checked it should be in the 3.12.1 version

Sorry, we changed some things and never released 3.12.1. But we're releasing 4.0.0 very soon.

> Is there anyway to build and run the code-server from main branch (source in GitHub)?

You could, but it might be easier to download a release from the releases page under Assets [here](https://github.com/cdr/code-server/releases). Follow the docs [here](https://coder.com/docs/code-server/latest/install#standalone-releases). Let me know if that works!

**Comment by amiria703** [comment]
:(
Sadly, Based on this link:
https://wiki.termux.com/wiki/Differences_from_Linux#Termux_uses_Bionic_libc
I can't run any pre-compiled binaries
Only I can install ones with configs and  patches for termux
Even I tried to run node v14 using tarball with no results
Sadly, It looks like I can't have code-server in my Android device for now

**Comment by jsjoeio** [comment]
@amiria703 shoot :( 

Can you try [this approach](https://github.com/cdr/code-server/pull/4621/files#diff-75ef442502f500fc1f10e52492c7d74be563334c0fe49fd0b57af8776e3e8684)?

**Comment by amiria703** [comment]
@jsjoeio 
Solved!
Using this command to install it:
apt update && apt upgrade && apt install python binutils && env FORCE_NODE_VERSION=16 yarn global add code-server --ignore-engines

**Comment by jsjoeio** [comment]
Hooray! thanks for sharing!
