### ISSUE TITLE
Using install.sh fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by sknauff** [cdr/code-server#4634]
Installation of code-server via `install.sh` fails on Ubuntu 20.04 docker images. But the same approach worked a few days ago.

## OS/Web Information

- Remote OS: Ubuntu 20.04 (Docker version, including official base image but also e.g., `jupyter/datascience-notebook:2021-12-15`)
- Remote Architecture: amd64

## Steps to Reproduce

1. Install Docker
2. Run `docker run --rm -ti -u root jupyter/datascience-notebook:2021-12-15 bash`
3. Within container, execute: `curl -fsSL https://code-server.dev/install.sh | sh`

As the jupyter image has `curl` preinstalled, I use it to skip `curl` installation, but I could reproduce the same behavior with `docker run --rm -ti ubuntu` and the additional steps to install `curl`.

## Expected

Code-server should get installed.

## Actual

Installation fails and I get the following output:
```
Ubuntu 20.04.3 LTS
Installing vhttps://github.com/coder/code-server/releases/tag/v3.12.0 of the amd64 deb package from GitHub.

+ mkdir -p ~/.cache//code-server
+ curl -#fL -o ~/.cache//code-server/code-server_https://github.com/coder/code-server/releases/tag/v3.12.0_amd64.deb.incomplete -C - https://github.com/cdr/code-server/releases/download/vhttps://github.com/coder/code-server/releases/tag/v3.12.0/code-server_https://github.com/coder/code-server/releases/tag/v3.12.0_amd64.deb
######################################################################## 100.0%curl: (22) The requested URL returned error: 404
```

**Comment by fritterhoff** [comment]
Same issue in my case. Worked until yesterday.

**Comment by kylecarbs** [comment]
We're moving to our new organization, @coder. 

I overlooked a few changes that needed to be made before that'd work, so I moved the repo back to @cdr.
