### ISSUE TITLE
How do you get a website to auto deploy the code server?

### ISSUE THREAD

**Issue by crazytaj** [cdr/code-server#467]
I was wondering if there was some way to basically do what you guys did on coder.com. I want to be able to use the same password every time, and start it from a website. I do not really know how to do this, but I have root access to a Ubuntu 16.04 VPS so any help would be really cool.

**Comment by sr229** [comment]
Hey @crazytaj, you can self host! We provided examples written in `docs/`, you just need to expose it to the internet.

We provide two ways to host your instance: Docker or manual install.

**Comment by NavinNavi19** [comment]
@crazytaj You can write a Unit File in Systemd service for the code server to start and restart even after a VPS restart.

### Part 1
```shell
[Unit]
Description=Code Server AutoStart
After=http://network.target 

[Service]
Type=simple
User=$USER
WorkingDirectory=/path/to/start/your/working/directory/inside/vscode
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Restart=on-failure

ExecStart=/path/to/codeserver/binary --allow-http --password=xxxxxxx

[Install]
WantedBy=http://multi-user.target 
```
Then run the below commands
```
sudo systemctl daemon-reload
sudo systemctl start code-server.service
sudo systemctl enable code-server.service
```
This will start your code-server at the` port 8443` and test this by directly going to your `IP:8443` in the browser and the password you mentioned above will be the same untill you edit your Unit File.

[Learn more about systemctl](https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units)

---

### Part 2
Do the Prerequisites Part and Step 4 in the below link to proxy your port 8443 to your own domain using nginx.

[Digital Ocean Tutorial](https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-18-04)

**Comment by crazytaj** [comment]
I tried starting the code server, but I got a JSON error. It says unexpected end of file in some bootstrap directory. I can paste it in here if you want.

**Comment by haoteng10** [comment]
@crazytaj Just ignore the JSON error.

**Comment by crazytaj** [comment]
I cant because it causes the page to not load and fail

**Comment by NavinNavi19** [comment]
@crazytaj Did you try the docker file.?

**Comment by crazytaj** [comment]
I dont have docker installed, it is a vps with 1 gb of ram

**Comment by Multishifties** [comment]
I think if you use the docker file and increase the RAM to 2gb things should work just fine.

**Comment by crazytaj** [comment]
I dont have enough for a 2gb vps, thats all I have. But I dont think that is the issue. The error it gives when I try to connect is about an unexpected end to a JSON file and was left hanging. If you need me to I can record me trying to install it.

**Comment by sr229** [comment]
the JSON error is minor, and we’re figuring out how to run code-server in Raspberry Pi Zero

**Comment by crazytaj** [comment]
Alright. Is there a way to get it to run successfully, or is it just a wait until it is fixed kind of deal?

**Comment by sr229** [comment]
Feel free to check it out at #140 for progress.

**Comment by coadler** [comment]
You could always add swap. Works well for my on a 600mb VM

**Comment by crazytaj** [comment]
what is swap?

**Comment by crazytaj** [comment]
never mind, it is just 'RAM' on the HD. Do you think more ram is needed for it to run? I thought I had successfully run it before but after I setup my web server, it isn't running. I tried doing it on a clean install of Ubuntu 16.04 but it didn't work either.

**Comment by crazytaj** [comment]
here is a video of the problem if it helps:
https://www.youtube.com/watch?v=3jMiHl0Pqjc

**Comment by crytos** [comment]
Are you running the server behind nginx?

**Comment by crazytaj** [comment]
no, my server is running apache. I just moved into that folder for the editing part.

**Comment by code-asher** [comment]
@crazytaj Have you had a chance to try out v2? It might solve the problem. It's also possible Apache needs to be configured according to this: https://github.com/cdr/code-server/blob/master/doc/quickstart.md#apache-reverse-proxy

**Comment by crazytaj** [comment]
I haven't gotten a chance to check out v2 yet. Kinda got demoralized after my failed attempt at customizing the server. Might pick it up again.

**Comment by sr229** [comment]
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
