### ISSUE TITLE
"Open next recently used editor in group" by ctrl-tab

### ISSUE THREAD

**Issue by jin-chong** [cdr/code-server#474]
## Description

Environment: Google Chrome 73.0.3683.86 (Official Build) 

I want to switch back to the recently used editor tab.  and this short cut is registered at "View: Open next recently used editor in group" with "Ctrl-tab".
I know it is reserved by Chrome, but is there any way to use "Ctrl-tab" for  "View: Open next recently used editor in group" as it is designed?

**Comment by cy91244** [comment]
When the app is in full-screen mode, the `ctrl+tab` function seems to be working.

**Comment by code-asher** [comment]
Yup full-screen mode or starting Chrome with `--app=http://my.ide.com` should work.
