### ISSUE TITLE
Keep tasks and debug sessions running in the background when browser closes and show up when reconnect

### ISSUE THREAD

**Issue by epoot** [cdr/code-server#481]
When tasks and or launch configs are started and you refresh or close/reopen your browser, all tasks have been killed. 

Since we are developing on chromebooks it would be great that when the browser is closed or connection is lost and reconnects again, all processes started by tasks or launch configs are still running and the frontend reconnects again. This will save a lot of hassle during working on projects and your laptop is not always connected because of travel or just simply a short period of being not online.

**Comment by nhooyr** [comment]
This is going to be too much of a refactor at the moment according to @code-asher

**Comment by NovoG93** [comment]
It's been two years, could this be implemented soon?

**Comment by jsjoeio** [comment]
@NovoG93 does this functionality exist in VS Code Web or Codespaces?
