### ISSUE TITLE
AWS EC2 Timed Out Error

### ISSUE THREAD

**Issue by abbylovesdon** [cdr/code-server#491]
version: 1.604-vsc1.32.0
OS Version: Ubuntu 18.0 Amazon EC2 instance Laravel Project

## Description

Everything is working fine except when I click into my folder project. Every thing errors with a 'Timed Out' notification. I can't access anything.

**Comment by sr229** [comment]
This does not concern code-server, since when I tested it at localhost it works fine.

AWS has one of the terrible latencies out there and you might need to compensate for that if you have a slow connection.

TL;DR: It's not this project - its them or you.

**Comment by foresthoffman** [comment]
@abbylovesdon Are there any errors in the browser developer console? Do you have any extensions installed?

**Comment by abbylovesdon** [comment]
That’s a good idea I’ll check the dev console.

Im sure it’s me lol, but I don’t think it’s latency. I’m able to view vs code extensions, they load relatively fast, and the search is responsive.

It seems to be only when I try to open a file or drop down a directory. I wonder if it may be a permissions issue?

**Comment by sr229** [comment]
Is this ran as systemd unit, docker, or just binary? @abbylovesdon

**Comment by abbylovesdon** [comment]
I'm running it as binary @sr229 

So I figured out I'm able to access a file for the first couple of seconds and open it, but then nothing can be opened after that. I'm posting a screen shot and the error stack from web console:

![Screen Shot 2019-04-13 at 7 59 39 AM](https://user-images.githubusercontent.com/30388387/56080110-6d483c80-5dc2-11e9-9e6b-5809dcc18724.png)

Console Stack:
c01964.bundle.js:53  INFO  Loading IDE
c01964.bundle.js:53  INFO  Starting socket [1/5]...
c01964.bundle.js:53  INFO  Connected to socket
c01964.bundle.js:53  INFO  Start workbench
c01964.bundle.js:53  INFO  Finished "Start workbench" duration=1384ms
c01964.bundle.js:53  INFO  Finished all queued tasks duration=1593ms
c01964.bundle.js:53  INFO  Load completed duration=1598ms
c01964.bundle.js:23   ERR Cannot read property 'clientWidth' of undefined: TypeError: Cannot read property 'clientWidth' of undefined
    at t.adjustTitleMarginToCenter (https://ec2-18-204-209-208.compute-1.amazonaws.com:8443/c01964.bundle.js:60:5202088)
    at e._runner (https://ec2-18-204-209-208.compute-1.amazonaws.com:8443/c01964.bundle.js:60:5202987)
    at e.execute (https://ec2-18-204-209-208.compute-1.amazonaws.com:8443/c01964.bundle.js:16:22529)
    at I (https://ec2-18-204-209-208.compute-1.amazonaws.com:8443/c01964.bundle.js:16:22725)
c01964.bundle.js:60 [Extension Host] debugger listening on port 23452
The resource https://ec2-18-204-209-208.compute-1.amazonaws.com:8443/1-c01964.bundle.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
c01964.bundle.js:60 Cannot read file /home/travis/build/codercom/code-server/packages/server/build/extensions/node_modules/package.json: undefined.
t._logMessageInConsole @ c01964.bundle.js:60
t._logOrShowMessage @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.error @ c01964.bundle.js:60
e.error @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
Promise.then (async)
t.parse @ c01964.bundle.js:60
e.scanExtension @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
s @ c01964.bundle.js:16
Promise.then (async)
c @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
u @ c01964.bundle.js:16
e.scanExtensions @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
s @ c01964.bundle.js:16
Promise.then (async)
c @ c01964.bundle.js:16
s @ c01964.bundle.js:16
Promise.then (async)
c @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
u @ c01964.bundle.js:16
t._scanExtensionsWithCache @ c01964.bundle.js:60
t._scanInstalledExtensions @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
s @ c01964.bundle.js:16
Promise.then (async)
c @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
u @ c01964.bundle.js:16
t.startScanningExtensions @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
u @ c01964.bundle.js:16
t._scanAndHandleExtensions @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
requestIdleCallback (async)
t.runWhenIdle @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:60
Promise.then (async)
t._startDelayed @ c01964.bundle.js:60
t @ c01964.bundle.js:60
t.create @ c01964.bundle.js:16
e._createInstance @ c01964.bundle.js:67
e.createInstance @ c01964.bundle.js:67
hn.initServices @ c01964.bundle.js:60
hn.doStartup @ c01964.bundle.js:60
hn.startup @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
Promise.then (async)
(anonymous) @ c01964.bundle.js:60
Promise.then (async)
n.open @ c01964.bundle.js:60
t.main @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
e.initialize @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
s @ c01964.bundle.js:38
Promise.then (async)
c @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
e.task @ c01964.bundle.js:60
r.initialize @ c01964.bundle.js:60
e @ c01964.bundle.js:60
r @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
r @ c01964.bundle.js:1
(anonymous) @ c01964.bundle.js:60
r @ c01964.bundle.js:1
(anonymous) @ c01964.bundle.js:60
r @ c01964.bundle.js:1
(anonymous) @ c01964.bundle.js:1
(anonymous) @ c01964.bundle.js:1
c01964.bundle.js:53  INFO  Starting searcher [1/5]...
c01964.bundle.js:23  INFO no standard startup: not using cached data
c01964.bundle.js:60 Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/Microsoft/monaco-editor#faq
t.logOnceWebWorkerWarning @ c01964.bundle.js:60
t._getOrCreateWorker @ c01964.bundle.js:60
t._getProxy @ c01964.bundle.js:60
t._withSyncedResources @ c01964.bundle.js:60
t.computeLinks @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
Promise.then (async)
provideLinks @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
d @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
l @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
u @ c01964.bundle.js:16
e.beginCompute @ c01964.bundle.js:60
e.onModelChanged @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
t.setModel @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:67
Promise.then (async)
(anonymous) @ c01964.bundle.js:67
Promise.then (async)
t.setInput @ c01964.bundle.js:67
t.doSetInput @ c01964.bundle.js:60
t.openEditor @ c01964.bundle.js:60
t.doShowEditor @ c01964.bundle.js:60
t.doOpenEditor @ c01964.bundle.js:60
t.openEditor @ c01964.bundle.js:60
t.doOpenEditor @ c01964.bundle.js:60
t.openEditor @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
t.doOpenEditor @ c01964.bundle.js:60
t.openEditor @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:67
e.fire @ c01964.bundle.js:16
t.open @ c01964.bundle.js:23
t.onSelection @ c01964.bundle.js:23
(anonymous) @ c01964.bundle.js:23
e.fire @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
e.fire @ c01964.bundle.js:16
e.set @ c01964.bundle.js:60
t.setSelection @ c01964.bundle.js:60
e.onPointer @ c01964.bundle.js:53
t.onPointer @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
e.fire @ c01964.bundle.js:16
r @ c01964.bundle.js:38
c01964.bundle.js:60 Cannot find module './workerMain.js'
t.logOnceWebWorkerWarning @ c01964.bundle.js:60
t._getOrCreateWorker @ c01964.bundle.js:60
t._getProxy @ c01964.bundle.js:60
t._withSyncedResources @ c01964.bundle.js:60
t.computeLinks @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
Promise.then (async)
provideLinks @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
d @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
l @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
u @ c01964.bundle.js:16
e.beginCompute @ c01964.bundle.js:60
e.onModelChanged @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
t.setModel @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:67
Promise.then (async)
(anonymous) @ c01964.bundle.js:67
Promise.then (async)
t.setInput @ c01964.bundle.js:67
t.doSetInput @ c01964.bundle.js:60
t.openEditor @ c01964.bundle.js:60
t.doShowEditor @ c01964.bundle.js:60
t.doOpenEditor @ c01964.bundle.js:60
t.openEditor @ c01964.bundle.js:60
t.doOpenEditor @ c01964.bundle.js:60
t.openEditor @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
t.doOpenEditor @ c01964.bundle.js:60
t.openEditor @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:67
e.fire @ c01964.bundle.js:16
t.open @ c01964.bundle.js:23
t.onSelection @ c01964.bundle.js:23
(anonymous) @ c01964.bundle.js:23
e.fire @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
e.fire @ c01964.bundle.js:16
e.set @ c01964.bundle.js:60
t.setSelection @ c01964.bundle.js:60
e.onPointer @ c01964.bundle.js:53
t.onPointer @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
(anonymous) @ c01964.bundle.js:16
e.fire @ c01964.bundle.js:16
r @ c01964.bundle.js:38
c01964.bundle.js:60 Activating extension 'vscode.extension-editing' failed: ENOENT: no such file or directory, open '/product.json'.
t._logMessageInConsole @ c01964.bundle.js:60
t._logOrShowMessage @ c01964.bundle.js:60
e.$localShowMessage @ c01964.bundle.js:60
t._doInvokeHandler @ c01964.bundle.js:60
t._invokeHandler @ c01964.bundle.js:60
t._receiveRequest @ c01964.bundle.js:60
t._receiveOneMessage @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
s @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
c @ c01964.bundle.js:60
_socketDataListener @ c01964.bundle.js:60
n.emit @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:53
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.emit @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
s @ c01964.bundle.js:38
Promise.then (async)
c @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
e.emitEvent @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
e.handleMessage @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.emit @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:53
c01964.bundle.js:60 [Extension Host] Activating extension 'vscode.extension-editing' failed: ENOENT: no such file or directory, open '/product.json'. (at Object.showMessage (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:177866:37))
t.log @ c01964.bundle.js:60
e.$logExtensionHostMessage @ c01964.bundle.js:60
t._doInvokeHandler @ c01964.bundle.js:60
t._invokeHandler @ c01964.bundle.js:60
t._receiveRequest @ c01964.bundle.js:60
t._receiveOneMessage @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
s @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
c @ c01964.bundle.js:60
_socketDataListener @ c01964.bundle.js:60
n.emit @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:53
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.emit @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
s @ c01964.bundle.js:38
Promise.then (async)
c @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
e.emitEvent @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
e.handleMessage @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.emit @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:53
c01964.bundle.js:60 [Extension Host] Activating extension `vscode.extension-editing` failed:  ENOENT: no such file or directory, open '/product.json' (at newlyActivatingExtension._host.actualActivateExtension.then (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:177722:25))
t.log @ c01964.bundle.js:60
e.$logExtensionHostMessage @ c01964.bundle.js:60
t._doInvokeHandler @ c01964.bundle.js:60
t._invokeHandler @ c01964.bundle.js:60
t._receiveRequest @ c01964.bundle.js:60
t._receiveOneMessage @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
s @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
c @ c01964.bundle.js:60
_socketDataListener @ c01964.bundle.js:60
n.emit @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:53
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.emit @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
s @ c01964.bundle.js:38
Promise.then (async)
c @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
e.emitEvent @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
e.handleMessage @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.emit @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:53
c01964.bundle.js:60 [Extension Host] Here is the error stack:  Error: ENOENT: no such file or directory, open '/product.json'
	at fs.openSync (fs.js:646:18)
	at n (nbin.js:1:6441)
	at Object.n.(anonymous function).e [as openSync] (nbin.js:1:6627)
	at fs.readFileSync (fs.js:551:33)
	at n (nbin.js:1:6441)
	at Object.n.(anonymous function).e [as readFileSync] (nbin.js:1:6627)
	at Object.<anonymous> (/home/travis/build/codercom/code-server/packages/server/build/extensions/extension-editing/dist/extension.js:1:131919)
	at n (/home/travis/build/codercom/code-server/packages/server/build/extensions/extension-editing/dist/extension.js:1:220)
	at Object.defineProperty.value (/home/travis/build/codercom/code-server/packages/server/build/extensions/extension-editing/dist/extension.js:1:128478)
	at n (/home/travis/build/codercom/code-server/packages/server/build/extensions/extension-editing/dist/extension.js:1:220)
	at r (/home/travis/build/codercom/code-server/packages/server/build/extensions/extension-editing/dist/extension.js:1:1019)
	at /home/travis/build/codercom/code-server/packages/server/build/extensions/extension-editing/dist/extension.js:1:1029
	at d (/home/travis/build/codercom/code-server/packages/server/out/cli.js:259:25757)
	at global.nativeNodeRequire.e (/home/travis/build/codercom/code-server/packages/server/out/cli.js:259:26467)
	at loadCommonJSModule (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:178356:24)
	at ExtHostExtensionService._doActivateExtension (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:178057:17)
	at ExtHostExtensionService._activateExtension (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:178015:25)
	at ExtHostExtensionService.<anonymous> (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:177882:33)
	at Generator.next (<anonymous>)
	at /home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:177757:71
	at new Promise (<anonymous>)
	at ./lib/vscode/src/vs/workbench/api/node/extHostExtensionService.ts.__awaiter (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:177753:12)
	at Object.actualActivateExtension (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:177875:67)
	at ExtensionsActivator._activateExtension (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:177720:57)
	at Promise.all.green.map (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:177705:58)
	at Array.map (<anonymous>)
	at ExtensionsActivator._activateExtensions (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:177705:42)
	at ExtensionsActivator.activateByEvent (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:177612:25)
	at ExtHostExtensionService._activateByEvent (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:177936:36)
	at _readyToRunExtensions.wait.then._ (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:178299:33)
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:189:7) (at newlyActivatingExtension._host.actualActivateExtension.then (/home/travis/build/codercom/code-server/packages/server/build/bootstrap-fork.js.gz:177723:25))
c01964.bundle.js:60 [Extension Host] Git installation not found. (at t.activate (/home/travis/build/codercom/code-server/packages/server/build/extensions/git/dist/main.js:1:126859))
t.log @ c01964.bundle.js:60
e.$logExtensionHostMessage @ c01964.bundle.js:60
t._doInvokeHandler @ c01964.bundle.js:60
t._invokeHandler @ c01964.bundle.js:60
t._receiveRequest @ c01964.bundle.js:60
t._receiveOneMessage @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
s @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
c @ c01964.bundle.js:60
_socketDataListener @ c01964.bundle.js:60
n.emit @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:53
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.emit @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
s @ c01964.bundle.js:38
Promise.then (async)
c @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
e.emitEvent @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
e.handleMessage @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.emit @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:53
c01964.bundle.js:60 Couldn't start client JSON Language Server
t.onDidNotificationChange @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
t.notify @ c01964.bundle.js:53
t.notify @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e._showMessage @ c01964.bundle.js:60
e.$showMessage @ c01964.bundle.js:60
t._doInvokeHandler @ c01964.bundle.js:60
t._invokeHandler @ c01964.bundle.js:60
t._receiveRequest @ c01964.bundle.js:60
t._receiveOneMessage @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
s @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.fire @ c01964.bundle.js:16
c @ c01964.bundle.js:60
_socketDataListener @ c01964.bundle.js:60
n.emit @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:53
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.emit @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
s @ c01964.bundle.js:38
Promise.then (async)
c @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
e.emitEvent @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
e.handleMessage @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:38
u @ c01964.bundle.js:38
(anonymous) @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:60
e.emit @ c01964.bundle.js:60
(anonymous) @ c01964.bundle.js:53
c01964.bundle.js:23   ERR Cannot read property 'clientWidth' of undefined: TypeError: Cannot read property 'clientWidth' of undefined
    at t.adjustTitleMarginToCenter (https://ec2-18-204-209-208.compute-1.amazonaws.com:8443/c01964.bundle.js:60:5202088)
    at e._runner (https://ec2-18-204-209-208.compute-1.amazonaws.com:8443/c01964.bundle.js:60:5202987)
    at e.execute (https://ec2-18-204-209-208.compute-1.amazonaws.com:8443/c01964.bundle.js:16:22529)
    at I (https://ec2-18-204-209-208.compute-1.amazonaws.com:8443/c01964.bundle.js:16:22725)
c01964.bundle.js:23   ERR Failed to watch /var/www/html/MyProject/.vscode for changes (Error: watch /var/www/html/MyProject/.vscode ENOENT, undefined)
2c01964.bundle.js:23   ERR timed out: Error: timed out
    at https://ec2-18-204-209-208.compute-1.amazonaws.com:8443/c01964.bundle.js:60:2846645
c01964.bundle.js:23   ERR Failed snippets from folder 'file:///home/ubuntu/.local/share/code-server/User/snippets' Error: timed out
    at c01964.bundle.js:60
c01964.bundle.js:23   ERR Unable to load and parse grammar for scope source.css from file:///home/travis/build/codercom/code-server/packages/server/build/extensions/css/syntaxes/css.tmLanguage.json Error: timed out
    at c01964.bundle.js:60
2c01964.bundle.js:23   ERR timed out: Error: timed out
    at https://ec2-18-204-209-208.compute-1.amazonaws.com:8443/c01964.bundle.js:60:2846645
c01964.bundle.js:23   ERR Unable to load and parse grammar for scope text.html.basic from file:///home/travis/build/codercom/code-server/packages/server/build/extensions/html/syntaxes/html.tmLanguage.json Error: timed out
    at c01964.bundle.js:60
c01964.bundle.js:23   ERR timed out: Error: timed out
    at https://ec2-18-204-209-208.compute-1.amazonaws.com:8443/c01964.bundle.js:60:2846645

**Comment by sr229** [comment]
Try a hard reset and see if that solves the problem

**Comment by nol166** [comment]
Will you send what is in the code server console please? That would be on your instance rather than the browser

**Comment by sr229** [comment]
No response for 26 days so I think OP has fixed it by their own.
