### ISSUE TITLE
Syntax highlighting not working sporadically

### ISSUE THREAD

**Issue by roflcoopter** [cdr/code-server#493]
- `code-server` version: v1.696
- OS Version: Ubuntu 18.04 (16.04 in container)

## Description

Syntax highlighting does not appear sporadically.
There are no errors in the logs or console so this might be hard to trace down.
Anyone else experiencing the same?

## Steps to Reproduce

1. Just open any file in code-server

**Comment by nhooyr** [comment]
If this still occurs please reopen.
