### ISSUE TITLE
Build Error Help

### ISSUE THREAD

**Issue by oonqt** [cdr/code-server#495]
Gives me an error about a node module requiring a specific version, but I don't exactly know what to do change the version. 

error: https://paste.memester.cf/acugopowuz.bash

**Comment by kylecarbs** [comment]
Try removing the `~/.local/share/code-server/dependencies/` folder. This will be fixed in a future release!

**Comment by oonqt** [comment]
I have no share folder in .local

**Comment by creativeguy2013** [comment]
Simple answer:
Just build using docker. All node versions are set correctly there.

The node version was recently upgraded to node 10 so you should not have compatibility issues anymore if you use node LTS. Could you check again with the latest release?
