### ISSUE TITLE
ERROR Failed to read certificate: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by DjBlarx** [cdr/code-server#514]
- `code-server` version: 1.604-vsc1.32.0
- `OS` version: Debian GNU/Linux 9 (stretch)

## Description

I try to secure my setup but I got the following problem :
`ERROR Failed to read certificate: EISDIR: illegal operation on a directory, read`

## Steps to Reproduce

1. `wget https://github.com/codercom/code-server/releases/download/1.604-vsc1.32.0/code-server1.604-vsc1.32.0-linux-x64.tar.gz`
2. `tar xvfz code-server1.604-vsc1.32.0-linux-x64.tar.gz`
3. `cd code-server1.604-vsc1.32.0-linux-x64`
4. `mv code-server /bin`
5. `mkdir ~/certs && cd ~/certs`
6. `openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ~/certs/MyKey.key -out ~/certs/MyCertificate.crt`
7. `code-server --cert=~/certs/MyCertificate.crt --cert-key=~/certs/MyKey.key`

**Comment by onekyle** [comment]
I have the same issue.
And I have solved this by using Relative Path.

```
// $pwd = /home/ubuntu  
// MyCertificate.crt and MKey.key are in the /home/ubuntu/certs  
./code-server ~/your_project_path --cert=certs/MyCertificate.crt --cert-key=certs/MyKey.key  
```

**Comment by code-asher** [comment]
If you use spaces it should work.

```
code-server --cert ~/certs/MyCertificate.crt --cert-key ~/certs/MyKey.key
```

Without those your shell won't expand `~` so it'll be looking for a directory literally called `~`.
