### ISSUE TITLE
Use bcrypt for password parameter

### ISSUE THREAD

**Issue by rcarmo** [cdr/code-server#515]
It would be very helpful if the server could take `bcrypt` passwords, such as the output of `htpasswd -nB username` and use that username/cypher pair for authentication instead of having cleartext passwords all over the place... :)

**Comment by lucacasonato** [comment]
I agree. At that point I think we should implement proper token based authentication. JWT and OAuth2 would be my preferred method. This would also enable different login providers later down the line.

**Comment by boardfish** [comment]
+1 for OAuth2, especially with generic providers! I'll be using Keycloak if this becomes an option. i'll open a separate issue for that.

**Comment by nhooyr** [comment]
The password is meant more of as a crutch, its best to put a reverse proxy in front for auth.
