### ISSUE TITLE
convertToDto unexpected type

### ISSUE THREAD

**Issue by asyzdykov** [cdr/code-server#516]
Hi.
 
I don't know if it's a bug, but I have error while trying to debug my project:
"convertToDto unexpected type"
with "OK" and "Open launch.json" buttons.

The same project debugger works in VS Code with no issues

**Comment by NENightElves** [comment]
Hi, I have the same issue with docker image codercom/code-server:1.939.
I use that image just installed openjdk-8-jdk and maven.
In addtion I added some extensions: redhat.java, vscjava.vscode-java-debug, vscjava.vscode-maven.

**Comment by bluntcoder** [comment]
Same problem here. Simply trying to use the lime extension in VSCode and try out some interactive debugging.

**Comment by kushalbhola** [comment]
same thing. It is happening for me in vscode to run a java program. I get this error when I try to debug.

**Comment by heyucongtom** [comment]
Same here.

**Comment by Lujaw** [comment]
having the same problem, any solution for this ?

**Comment by Lujaw** [comment]
The issue for me was solved by adding, 
`"java.home": <absolutePathToJDK>"`
in the settings.json for the workspace.

**Comment by michaeltlewis** [comment]
Adding java.home to settings,json didn't fix it for me. The problem persists.

**Comment by NourElMenshawy** [comment]
![VScode error](https://user-images.githubusercontent.com/31157471/60015438-cfa3a000-9683-11e9-9e2d-233e0960b4a0.JPG)

I have same issue and debugging for C++

**Comment by jeffythedragonslayer** [comment]
I was able to resolve this error by changing "cppvsdbg" to "cppdbg" in launch.json

**Comment by 10bosal** [comment]
In my case, uninsall and reinstall the "C/C++ Extension" and than resolve the problem. (My case is C++ debuging env.)

**Comment by sr229** [comment]
This is a upstream problem. Please move this issue there.

**Comment by Ricbet** [comment]
Same here.

**Comment by FroilanRoy** [comment]
Please help me with this error "converToDto Unexpected Type". It appears whenever I try to debug.
