### ISSUE TITLE
Upload latest binary to cdr.sh

### ISSUE THREAD

**Issue by kylecarbs** [cdr/code-server#526]
Makes for easy grabbing within dockerfiles.

**Comment by lucacasonato** [comment]
This might seem stupid, but what exactly is cdr.sh? Google can't seem to find it.

**Comment by nol166** [comment]
it's just a domain that we use to host files

**Comment by lucacasonato** [comment]
Ah ok - thanks for the info

**Comment by nhooyr** [comment]
This is done.
