### ISSUE TITLE
Macro not working

### ISSUE THREAD

**Issue by toreskogp** [cdr/code-server#532]
- `code-server` version: 1.868-vsc1.33.1
- OS Version: Ubuntu 16.04.4 LTS

## Description

The macros plugin seems to not work on code server, although it works on vs code. I followed the setup guide, but it says that the macro was not found.
Here is the link to the macro plugin: https://marketplace.visualstudio.com/items?itemName=geddski.macros

## Steps to Reproduce

1. Install macro plugin (https://marketplace.visualstudio.com/items?itemName=geddski.macros)
1. Add macro to settings.json:
   ```
   "macros": {
        "commentDown": [
            "editor.action.copyLinesDownAction",
            "cursorUp",
            "editor.action.addCommentLine",
            "cursorDown"
        ]
    }
   ```
1. Add keybinding:
    ```
    {
        "key": "ctrl+/",
        "command": "macros.commentDown"
    }
    ```
1. Use the newley created keybinding

**Comment by nhooyr** [comment]
Confirmed it works now.

If this is still a problem, please feel free to reopen.
