### ISSUE TITLE
File paths not canonicalized so you can open the same file twice

### ISSUE THREAD

**Issue by Timmmm** [cdr/code-server#534]
- `code-server` version: 1.868-vsc1.33.1
- OS Version: Ubuntu 18.04

## Description

It is possible to open the same file twice if one is via `/home/me/file.txt` and the other is via `~/file.txt` (for example).

## Steps to Reproduce

1. Create a file `~/file.txt`
2. Open it from the file explorer.
3. Open the terminal and type `echo /home/you/file.txt`
4. Ctrl-click the path.

You now have the same file open twice.

**Comment by GCole64** [comment]
I was trying to send E-mail to Sparkchain and tab in Firefx crashed .

**Comment by GCole64** [comment]
Also discovered email was not syncing properly , was all turned off so no new mail would load .

**Comment by sr229** [comment]
No report since 26 days so we'll go over this as fixed.

**Comment by Timmmm** [comment]
Ah sorry, I didn't see your first message. I switched to using bind mounts instead, which is a nicer solution to my problem.
