### ISSUE TITLE
How to change the password

### ISSUE THREAD

**Issue by oonqt** [cdr/code-server#548]
How can I change the password used to authenticate into code-server?

**Comment by mbayabo** [comment]
If you're using the binary, the latest version of code-server allows you to set an environment variable PASSWORD

```
export PASSWORD="yourpassword"
./code-server
```

If you're using docker,  you can use the -e flag to pass environment variables to your container

`docker run -it -p 127.0.0.1:8443:8443 -e PASSWORD='yourpassword' -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth`

**Comment by ahjsrhj** [comment]
@mbayabo Why add the parameter of --no-auth?

**Comment by mbayabo** [comment]
> @mbayabo Why add the parameter of --no-auth?

You actually don't need that, sorry.

**Comment by MinchinWeb** [comment]
Using the `--password` option in Docker, code-server complains that it don't recognize the command line option and refuses to start.

**Comment by mbayabo** [comment]
> Using the `--password` option in Docker, code-server complains that it don't recognize the command line option and refuses to start.

If you're using the newest release, the --password argument has been deprecated. It won't work anymore. You need to set an environment variable called PASSWORD.

export PASSWORD="yourpassword"

**Comment by MinchinWeb** [comment]
@mbayabo Thanks! That works for me!

**Comment by ntindle** [comment]
This should be added to [the self-hosted guide](codercom/code-server/blob/master/doc/self-hosted/index.md)

**Comment by oonqt** [comment]
> This should be added to [the self-hosted guide](codercom/code-server/blob/master/doc/self-hosted/index.md). Do we want to do that as a new issue?

If you actually read the self-hosted guide you would have seen it's already in there bro... 
[Code-Server Usage](https://github.com/codercom/code-server/blob/master/doc/self-hosted/index.md#usage)

**Comment by ntindle** [comment]
> > This should be added to [the self-hosted guide](codercom/code-server/blob/master/doc/self-hosted/index.md). Do we want to do that as a new issue?
> 
> If you actually read the self-hosted guide you would have seen it's already in there bro...
> [Code-Server Usage](https://github.com/codercom/code-server/blob/master/doc/self-hosted/index.md#usage)

I must be missing where it says the updated details about environment variables that were introduced in [`1.903-vsc1.33.1`](https://github.com/codercom/code-server/releases/tag/1.903-vsc1.33.1)

**Comment by oonqt** [comment]
> > > This should be added to [the self-hosted guide](codercom/code-server/blob/master/doc/self-hosted/index.md). Do we want to do that as a new issue?
> > 
> > 
> > If you actually read the self-hosted guide you would have seen it's already in there bro...
> > [Code-Server Usage](https://github.com/codercom/code-server/blob/master/doc/self-hosted/index.md#usage)
> 
> I must be missing where it says the updated details about environment variables that were introduced in [`1.903-vsc1.33.1`](https://github.com/codercom/code-server/releases/tag/1.903-vsc1.33.1)

My bad, I thought you were talking about the old method of setting passwords

**Comment by ntindle** [comment]
no worries

**Comment by mbayabo** [comment]
We probably should add it as an issue.

**Comment by xinmans** [comment]
how to disable password when i use docker

**Comment by code-asher** [comment]
Something like: 

```
docker run codercom/code-server --auth none
```
