### ISSUE TITLE
I keep getting "socket disconnected" message

### ISSUE THREAD

**Issue by tutiplain** [cdr/code-server#556]
## Description

 Hi all, I am new to code-server, but I just can't seem to get it to work. I am hosting on a basic DigitalOcean droplet with ubuntu linux. I can run the ide and I can log in to it, and even view the folder contents. However, opening any code file will cause a "socket disconnect" message and then I can't do anything else. Is there a fix for this, or does code-server simply require more bandwidth than my droplet has?

**Comment by oonqt** [comment]
Are you running through a reverse proxy on NGINX?

**Comment by ammarjabakji** [comment]
I have the same problem on a Bitnami server every 10 minutes it disconnects.

**Comment by nol166** [comment]
Will you copy the terminal output for code server?

**Comment by kylecarbs** [comment]
Are you using the latest release? Sockets should reconnect

**Comment by ammarjabakji** [comment]
Oh Sorry I got  "Lost connection to socket" broken pipe
I solved it with this code:
Host *
ServerAliveInterval 120
Thanks

**Comment by roberthmiller** [comment]
Hey mates, I think that this is because of resource requirements.

I had spun up a tiny AWS Lightsail instance ($3.50), and it had the same effect.

I think that we should specify some minimal VPS specs within the README.

**Comment by maithoi** [comment]
> Oh Sorry I got "Lost connection to socket" broken pipe
> I solved it with this code:
> Host *
> ServerAliveInterval 120
> Thanks

pls share more details where this code should be applied. typing terminal or anywhere else?

**Comment by deansheather** [comment]
@maithoi That looks like SSH client configuration, which only makes sense if you're using [sshcode](https://github.com/cdr/sshcode) or something similar.

**Comment by maithoi** [comment]
thanks @deansheather, I know where the problem came from, I just make disconnect with coder-server to use the terminal of my local machine ==> this `lost connection to socket `error.

**Comment by sr229** [comment]
Since there has been zero response I will mark this as closed.
