### ISSUE TITLE
unable to load Material Theme 

### ISSUE THREAD

**Issue by MrJCJ** [cdr/code-server#567]
- `code-server` version: 1.903-vsc1.33.1
- OS Version: Ubuntu 18.04.2 LTS
- Extension: Material Theme

## Description
after "installing" Material Theme  when trying to enable any of the color-modes I get this Error:

`Unable to load file:///root/.local/share/code-server/extensions/equinusocio.vsc-material-theme-2.7.0/out/themes/Material-Theme-Darker-High-Contrast.json: File not found (file:///root/.local/share/code-server/extensions/equinusocio.vsc-material-theme-2.7.0/out/themes/Material-Theme-Darker-High-Contrast.json)`

## Steps to Reproduce

1. open Extensions Tab
2. look for material Theme
3. click install
4. click bottom left & select "color theme"
5. choose any of the Material Themes

**Comment by foresthoffman** [comment]
@MrJCJ Interesting! Will look into this. Thanks!

**Comment by rev1be** [comment]
is there any soulution yet?
![Unbenannt](https://user-images.githubusercontent.com/39281427/57278294-a14b1080-7095-11e9-94c9-597cb8d88bff.PNG)

**Comment by barberdt** [comment]
I receive the same error at @rev1be, however other installed third-party themes seem to apply just fine. Wondering if this is an issue with https://github.com/equinusocio/vsc-material-theme. That being said, no issues applying that theme on regular VSCode.

**Comment by jots** [comment]
I had the same problem.  I had to download the vsix file from https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme and then "install from vsix" from the more actions "..." menu item on the extensions pane.

this did bring up another bug:  I have a symlink to an external drive in my homedir and if the external drive is not connected, a dialog pops up saying there's an error with that file and I can't choose the vsix file in my homedir.  fix is to temporarily move vsix file to /home/

**Comment by code-asher** [comment]
This appears to be fixed in v2. :tada:
