### ISSUE TITLE
window.beforeclose prompt should not alert if running in app mode in chrome

### ISSUE THREAD

**Issue by weikinhuang** [cdr/code-server#574]
- `code-server` version: v1.939-vsc1.33.1
- OS Version: linux server, osx client

## Description

When running code-server in chrome app mode (ex sshcode) the window close prompt should not show up when doing ctrl+w, since running in app mode, it's able to overload the ctrl/cmd+w shortcut to actually close editor tabs

## Steps to Reproduce

1. Start code-server
1. Open app with
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --app=https://server-ip:8443
```
1. Open several editor tabs
1. cmd+w to close 1 tab

**Comment by code-asher** [comment]
This was removed in v2. :tada:
