### ISSUE TITLE
Req: Home Assistant Config Helper and Material Design Icons Intellisense

### ISSUE THREAD

**Issue by raulvasquez** [cdr/code-server#590]
If possible please add:

Home Assistant Config Helper: https://marketplace.visualstudio.com/items?itemName=keesschollaart.vscode-home-assistant

Material Design Icon Intellisense: https://marketplace.visualstudio.com/items?itemName=lukas-tr.materialdesignicons-intellisense

**Comment by nol166** [comment]
@foresthoffman Is this something we could add?

**Comment by raulvasquez** [comment]
@nol166 and @foresthoffman fwiw they are included in the hass.io vscode addon by default, but do not pop up in the codeserver store: https://github.com/hassio-addons/addon-vscode

Looks like the hass.io version uses code-server as the base.

**Comment by foresthoffman** [comment]
@raulvasquez @nol166 Interesting. It's on the list of extensions to look into!

**Comment by seaverd** [comment]
@foresthoffman  -  Just wondering what the status was of adding these two extensions?

Thanks,
Dan

**Comment by SAOPP** [comment]
Guys, so currently we can't install this extension from code market yet? I can to install it from vsix?

**Comment by code-asher** [comment]
Yeah installing them manually should work. We'll be working on our
marketplace soon which should resolve these issues but there's no
timeline yet.

**Comment by SAOPP** [comment]
Thank u very much guys! Amazing product, only go ahead!

**Comment by nhooyr** [comment]
See #1299
