### ISSUE TITLE
Auto updater

### ISSUE THREAD

**Issue by oonqt** [cdr/code-server#592]
I think a code-server auto updater would be nice, even though it doesn't take long to update to the latest release, it would still be nice to have for convenience.

**Comment by sr229** [comment]
There's a problem with this approach however, it either has to run as root or this won't work. I think like a package manager like snaps can do this where it auto updates every new release

**Comment by code-asher** [comment]
v2 implemented auto-updating but as mentioned it means you need the permissions to overwrite the binary.
