### ISSUE TITLE
bash: npm: command not found

### ISSUE THREAD

**Issue by jishnutv** [cdr/code-server#596]
## Description

I am running coder in Docker and it works fine. I opened my project folder and try to run `ionic serve`, `npm i` then it showing  `bash: npm: command not found` how to fix this ?

![DeepinScreenshot_select-area_20190425133618](https://user-images.githubusercontent.com/40197322/56719846-27df2400-675f-11e9-9300-e30344c98953.png)

**Comment by romanrehacek** [comment]
You have to [install](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-18-04) nodejs and npm.

**Comment by jishnutv** [comment]
> You have to [install](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-18-04) nodejs and npm.

I installed both nodejs and ionic CLI on my system but still i am getting this error on coder
![DeepinScreenshot_select-area_20190425175635](https://user-images.githubusercontent.com/40197322/56736795-b0bd8600-6786-11e9-9148-25fa8d7d8b57.png)

**Comment by romanrehacek** [comment]
Coder in Docker has separate ubuntu system. So, terminal in coder is not yours terminal in pc.
Install nodejs and another dependencies into coder's terminal.

**Comment by kylecarbs** [comment]
You could also launch the binary on your host to solve this problem.

**Comment by jishnutv** [comment]
> Coder in Docker has separate ubuntu system. So, terminal in coder is not yours terminal in pc.
> Install nodejs and another dependencies into coder's terminal.

I am new to Docker can you explain how to do that ?

**Comment by jishnutv** [comment]
> You could also launch the binary on your host to solve this problem.

Can you tell me how to do that, I am new to linux and docker

**Comment by romanrehacek** [comment]
Read [readme](https://github.com/codercom/code-server#binaries) file.
Download file code-server1.939-vsc1.33.1-linux-x64.tar.gz, unzip and run the command code-server.
This will run coder inside your pc, not in Docker. The terminal will be the same as in you pc.

**Comment by sr229** [comment]
@jishnutv Docker containers have their own isolated environment, you should supply Node.js and NPM.

**Comment by yyynnn** [comment]
Here is the coder with fresh node 10 inside
https://hub.docker.com/r/yyynnn/code-server
