### ISSUE TITLE
can't back root folder when push 'Reveal in Finder'

### ISSUE THREAD

**Issue by canonrock16** [cdr/code-server#602]
- `code-server` version: 1.792
- OS Version: Ubuntu 16.04.5 LTS

## Description
Once click 'Reveal in Finder' button from right click menu on EXPLORER in state of selecting folder, only the selecting folder opens in EXPLORER, and I can't see any other folders.
Even if I reload or restart code-server, this situation didn't change.

![reveal_in_finder](https://user-images.githubusercontent.com/35710450/56777764-228ce280-680e-11e9-8702-660906150bdd.gif)

Then I found a solution.The root directory was back when I deleted the browser's history.

## Steps to Reproduce

1. step 1: click 'Reveal in Finder' button from right click menu on EXPLORER in state of selecting folder

**Comment by nol166** [comment]
should be fixed by https://github.com/codercom/code-server/pull/586
