### ISSUE TITLE
Can't select a .file from File Open dialog

### ISSUE THREAD

**Issue by t-d-d** [cdr/code-server#603]
- `code-server` version: 1.939-vsc1.33.1
- OS Version: Docker ubuntu:18.10

## Description

Files beginiing with a . aren't visible in the Open File dialog.

## Steps to Reproduce

File->Open File...

**Comment by code-asher** [comment]
Was fixed by https://github.com/cdr/code-server/commit/a2ad3d4ff4ae6019627028d6a65ef5f228d5b6f7.
