### ISSUE TITLE
Vim extension is not working after installation

### ISSUE THREAD

**Issue by chaopli** [cdr/code-server#61]
- `code-server` version: 1.31.0-20
- OS Version: Ubuntu 16.04
- Extension: [vim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)

#### Steps to Reproduce

1. After installation of Vim extension and reload the vs code window, Vim mode is not toggled.
2. When trying to toggle the Vim mode manually "command 'toggleVim' not found" popped up.

**Comment by kylecarbs** [comment]
Should work once we release 1.31.1. Should release tomorrow

**Comment by chaopli** [comment]
Thanks!

**Comment by chaopli** [comment]
Just upgraded to v1.31.1-100, but the vim extension is still not working

**Comment by kylecarbs** [comment]
We likely have to re-fetch the Vim extension. Likely will occur within ~12hrs.

cc: @foresthoffman

**Comment by pollenjp** [comment]
I'm hitting the same problem like [this](https://github.com/VSCodeVim/Vim/issues/3519) (vim plugin v1.1.0) in v1.31.1-100. I think this issue has relation to it.
![image](https://user-images.githubusercontent.com/33354327/53945125-3e281680-4104-11e9-8f2d-ba3d5d3988fe.png)

I try to downgrade vim version, but I don't know how to do. https://github.com/codercom/code-server/issues/77

**Comment by foresthoffman** [comment]
Hmm the suggested fix was to upgrade to v1.31.1, but since that isn't doing the trick, i'll try downgrading vim. Will respond with an update soon.

**Comment by foresthoffman** [comment]
v1.0.8 of vscodevim seems to work with v1.31.1. Will push the downgraded version.

**Comment by nhooyr** [comment]
@foresthoffman was it pushed?

**Comment by NGTmeaty** [comment]
We seem to have updated VSCode which I believe was the problem. https://github.com/codercom/code-server/pull/117

**Comment by foresthoffman** [comment]
@nhooyr Yes, I had to make some changes to prevent rolling the version forward before VSCode removes negative look behinds. v1.0.8 of VSCodeVim.Vim should refresh and be functional in about an hour.

**Comment by foresthoffman** [comment]
Vim was fixed over the weekend, should be good to go!

**Comment by NerdsvilleCEO** [comment]
I seem to be getting this error 

```
Activating extension 'vscodevim.vim' failed: Not Implemented: IExtensionStoragePaths->globalValue.
```

**Comment by floZx** [comment]
> I seem to be getting this error
> 
> ```
> Activating extension 'vscodevim.vim' failed: Not Implemented: IExtensionStoragePaths->globalValue.
> ```

Like me, Did you find a solution?

**Comment by code-asher** [comment]
That error has been fixed but it's not in a release yet. Should have one
out today.

**Comment by NerdsvilleCEO** [comment]
@code-asher did this fix end up in a release?

**Comment by code-asher** [comment]
It did, check out the latest (2.1698). Keep in mind Chrome is still the
only supported browser since the Vim extension uses regular expressions
not supported by Firefox and Safari.

**Comment by AlbertDeFusco** [comment]
Hey, there. This problem seems to have resurfaced. [VSCodeVIM](https://github.com/VSCodeVim/Vim) versions 1.13.0 and 1.13.1 **do not** work with code-server 2.1698-vsc1.41.1 or 3.0.1

**Comment by vnijs** [comment]
@AlbertDeFusco Are you getting the same message shown below in the browser's developers console?

![image](https://user-images.githubusercontent.com/2998956/78508572-b2d0e880-773c-11ea-8d96-0459e4d12eea.png)

**Comment by vnijs** [comment]
@chaopli Can you reproduce? If so, could you reopen the issue?

**Comment by nhooyr** [comment]
@cmoog

**Comment by cmoog** [comment]
@AlbertDeFusco @vnijs I've experienced the same issue. I believe it may be related to https://github.com/VSCodeVim/Vim/issues/4173

Regardless, downgrading to VSCodeVIM version 1.12.4 fixed the issue for me. 1.12.4 can be installed from the code-server extension marketplace directly.

**Comment by nhooyr** [comment]
Nice @cmoog

**Comment by JosXa** [comment]
Downgrading to 1.12.4 did not help for me on `code-server` (however installed directly through VSCode marketplace, not sure what the "code-server extension marketplace" is).
Still experiencing `Activating extension 'vscodevim.vim' failed: Not Implemented: IExtensionStoragePaths->globalValue.` on 1.12.4 and 1.14.5.

**Comment by nhooyr** [comment]
@JosXa See https://github.com/cdr/code-server/blob/master/doc/FAQ.md#whats-the-deal-with-extensions

**Comment by nhooyr** [comment]
Also please file a new issue if still doesn't work installing from our marketplace.
