### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by DaniloAguiar** [cdr/code-server#611]
## Description

Hello everyone,
I'm having trouble starting the server-code.
first I thought I was a user, so I tried with sudo.
then I thought it was the certificate.

what do I have to do :(

![Captura de tela de 2019-04-27 19-01-07](https://user-images.githubusercontent.com/13169364/56855592-d16d1380-691f-11e9-89ad-5ce818bbbc58.png)

**Comment by nhooyr** [comment]
It started just fine. Visit `http://localhost:8443` to use it.

**Comment by DaniloAguiar** [comment]
it's on an online server, but when I type the www.link ... with: 8443 it will not go

**Comment by nhooyr** [comment]
Will improve this message thanks.
