### ISSUE TITLE
When a symbolic link is broken the opening folder don't work

### ISSUE THREAD

**Issue by ruslanguns** [cdr/code-server#614]
- `code-server` version: 1.939-vsc1.33.1
- OS Version: Ubuntu 18.04 

## Description

When a symbolic link is broken inside a folder, the opening of a folder does not work just crash and brings an error in console about ENOENT Can't open directory

## Steps to Reproduce

1. Create a Symbolic link and point it to a file
2. Delete that file and then you will have a Symbolic link
3. Start coder and then try to open the folder where this broken symbolic link is present

You will get as result that the box closes.

**Comment by ruslanguns** [comment]
A workaround is deleting the symbolic link, however my point of view is that the folder should be opened even there are symbolic links broken and coder just ignore them.

**Comment by kylecarbs** [comment]
Will fix! Thanks for the report.

**Comment by code-asher** [comment]
This was fixed by https://github.com/cdr/code-server/commit/4c5bb83fc11b71664783c6abd081ff318663f107.

**Comment by ruslanguns** [comment]
Awesome !
