### ISSUE TITLE
JS/TS language service not working properly

### ISSUE THREAD

**Issue by pstjvn** [cdr/code-server#616]
OS: Linux Ubuntu 18.04
Browser: Chrome (latest stable)

I have been running on 1.6xx for a while and after update my project (a TS electron app) is not longer working properly.

After initially loading the js/ts language service (observed in blue status bar) it finally starts displaying weird errors in the problems panel, like the following:
```
Property 'forEach' does not exist on type '{}'. 
Cannot find global type 'Promise'.
```

The same code does not produce these errors on VSCode (run locally vs code-server also run locally).

Started backing down on versions and the last version that works properly is 1.792 

Please let me know if anything else is needed to track this down.

Thanks

**Comment by ismaproco** [comment]
Same thing is happening for me, running from the docker.

I have a simple interface:
```javascript
interface NameProb {
  name: string;
  prob: number;
}
```

and if I initialize and array object with it get the same error.

```
const someProb: NameProb[] = obj.nameProbs;
someProb.forEach // ------ERROR Property 'forEach' does not exist on type '{}'. 
```


It does work in VSCode though

**Comment by fskorzec** [comment]
Same for me

**Comment by fskorzec** [comment]
Actually, I have installed typescript module locally in the project, and changed the settings for the TSDK key to "./node_module/typescript/lib". Then changed the default compiler to the settings one by clicking on the typescritp version in the taskbar at the bottom right and everything is now ok

**Comment by pstjvn** [comment]
Great, that works for me too.
