### ISSUE TITLE
ERROR VSCODE:INSTALL Failed: connect ETIMEDOUT 104.27.132.26:443

### ISSUE THREAD

**Issue by bardenthenry** [cdr/code-server#617]
- `code-server` version: latest
- OS Version: ubuntu 16.04

## Description

I got some error message when I use docker build to build "Dockerfile" to docker image.
The build step is:
````bash
 yarn && NODE_ENV=production yarn task build:server:binary
````

And the erroe message:
````bash
INFO  BUILD:SERVER:BINARY Starting...
INFO  VSCODE:INSTALL Starting...
ERROR VSCODE:INSTALL Failed: connect ETIMEDOUT 104.27.132.26:443
ERROR VSCODE:INSTALL Stack: Error: connect ETIMEDOUT 104.27.132.26:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````
I have added the http_proxy and https_proxy ENV in front of Dockerfile, but still got this error message.

How can I fix this error? 
thx

**Comment by alexbumbacea** [comment]
the problem is that the default node http client doesn't understand http proxy env variables.
Possible solutions are available here: https://github.com/nodejs/node/issues/8381

**Comment by nhooyr** [comment]
Upstream issue.
