### ISSUE TITLE
Microsoft Edge compatibility

### ISSUE THREAD

**Issue by LamDang** [cdr/code-server#619]
- `code-server` version: 1.939-vsc1.33.1
- OS Version: Ubuntu 16.04

## Description

I have multiple issues with Microsoft Edge client (the same server don't have any issue with Chrome and Firefox clients):

* Some icons are not displayed correctly 
![edge_code_server_1](https://user-images.githubusercontent.com/11425355/56911717-dfe93580-6aad-11e9-9360-6a7921753127.PNG)
* Python code not colored correctly and pylint check not displayed
![edge_code_server_2_uncolored_python](https://user-images.githubusercontent.com/11425355/56911718-e081cc00-6aad-11e9-91ce-7188175aa9d2.PNG)

Is there any work on Edge compatibility? 

## Steps to Reproduce

1. step 1: Run a code-server instance
1. step2: access with Microsoft Edge (version tested : Microsoft Edge 40.15063.674.0)

**Comment by Multishifties** [comment]
Due to a number of reasons, support for Microsoft Edge is not planned.
