### ISSUE TITLE
embed in an iframe

### ISSUE THREAD

**Issue by mikestaub** [cdr/code-server#621]
Would it be possible to embed this in an iframe? How could the parent page communicate with the vscode client running inside?

My use case is that I want a custom vscode extension to send a message up to a parent page that is embedding the ide-client. I doesn't look like the vscode api supports this.

**Comment by foresthoffman** [comment]
@multishifties may correct me, but I believe that using iframes in this way is an example of CORS, which is prohibited generally speaking. If you want your extension to communicate with the parent origin, you'd have to send an explicit request from the origin hosting the IDE.

If they are from the same origin, that maybe possible, but requires some configuration.

**Comment by Multishifties** [comment]
If you're self-hosting you should be able to set any headers you want, including those necessary for code-server to be iframed/embedded.

As for communication between your vscode extension and your parent page, you'll probably have to write your own script.

Now I'm imagining a situation where you have an IDE embedded into a website, where you can use the embedded IDE to modify the source code for the host website in real time. That's outright meta!

**Comment by mikestaub** [comment]
What do you mean 'write my own script'? I think the only way is to fork vscode and insert a 'backdoor' to allow my extension to access the global window object. This feels hacky though.

**Comment by Shurov** [comment]
What about wrapping in iFrame for use in [Organizr](https://organizr.app)?
Does the docker image support required headers? Could you add them to the installation manual?

**Comment by sr229** [comment]
Looks like someone in strove.io did it so our newer releases can work in iframes.
