### ISSUE TITLE
Easiest way to download files?

### ISSUE THREAD

**Issue by dmratcliffe** [cdr/code-server#623]
## Description
Whats the best way on a linux server to allow the downloading of files from coder?

If I host another website, codeserver is already using 443, so I'd have to run on a different port which isn't very nice.

Is there anything I can run alongside coder so that coder.mydomain.com/files opens some sort of browser? Or is my best bet really mucking about with ports to host a second webserver?

**Comment by oonqt** [comment]
Install an FTP server

**Comment by dmratcliffe** [comment]
@oonqt fair, but on computers I do not own, I can't conviently download a client to get my files.

**Comment by oonqt** [comment]
You can still view and download the files of an FTP server through a web browser

**Comment by khoomeister** [comment]
scp

**Comment by t-d-d** [comment]
It seems code-server happily serves out any file via the /resource endpoint.  e,g,
http://my.domain.name/resource/home/coder/project/my-project/my-file.txt will download my-file.txt.

Doesn't serve out a file list for a directory though.

**Comment by dmratcliffe** [comment]
@t-d-d That is nice to know, and will be useful for single files. The main problem is grabbing directories which browsers don't seem to be able to do with FTP.

@oonqt The problem is if I need to download a folder or entire project ect

**Comment by dmratcliffe** [comment]
My solution for this problem was to:

- Host the code server on port 8443
- Forward a subdomain in nginx to this port (so I don't have to type the port)
- Host another server with a simple filebrowser script I wrote on a different subdomain with nginx
(the main reason I didn't use an existing script was the lack of zipping a directory, I couldn't find a script that did it default. I may post a repo with the code or something once I refactor some stuff)
- ???
- profit
