### ISSUE TITLE
Settings within subdirectories are not applied in multi-root setup

### ISSUE THREAD

**Issue by transcranial** [cdr/code-server#626]
- `code-server` version: 1.939-vsc1.33.1
- OS Version: Ubuntu 18.04

## Description

Running `code-server` in a root directory like:
```
example
├── repo1
│   └── .vscode
│       └── settings.json
├── repo2
│   └── .vscode
│       └── settings.json
└── repo3
    ├── .venv
    └── .vscode
        └── settings.json
```

The `settings.json` files in the individual repo subdirectories are not applied.

Additionally, and possibly related: let's say `repo3` is a python project with a locally-installed virtualenv. The python interpreter cannot be set to use this virtualenv, either through the project `settings.json` (due to above), or manually at the global level (as code-server does not detect the existence of the python binary in the `.venv` subdirectory. 

## Steps to Reproduce

1. Create directory structure as above
2. Run code-server from root directory
3. Modify individual `settings.json` and observe they have no effect

**Comment by nhooyr** [comment]
If this still occurs, please feel free to reopen.
