### ISSUE TITLE
Extension icons don't load

### ISSUE THREAD

**Issue by t-d-d** [cdr/code-server#627]
- `code-server` version: 1.939-vsc1.33.1
- OS Version: docker ubuntu:18.10
- Extension: A few.  E.g. auchenberg.vscode-browser-preview

## Description

Some extension icons for the tool bar fail to load.

## Steps to Reproduce

1. Extension is installed in docker build
2. Run the container
3. Open Chrome web browser - extension starts but icon in left palette is missing.  Tooltip still works.

Chrome console log reports resource failed to load - Host Not Found.  URL it's trying to load is missing the hostname:  http://my_sub_path/resource/home/coder/.local/share/code-server/extensions/chrome-preview/resources/icon.svg

Note that I am hosting on a path - my_sub_path.

**Comment by foresthoffman** [comment]
@t-d-d If you `ls` that directory (`/home/coder/.local/share/code-server/extensions/chrome-preview/resources/`) what are the contents?

**Comment by t-d-d** [comment]
```
>ls /home/coder/.local/share/code-server/extensions/chrome-preview/resources/
demo.gif  demo.mp4  icon_128.png  icon_dark.svg  icon_light.svg  icon.svg  inspect.svg
```

From Chrome console log:
```
ide.main.92c1f4.js:67 GET http://my_sub_path/resource/home/coder/.local/share/code-server/extensions/chrome-preview/resources/icon.svg net::ERR_NAME_NOT_RESOLVED
```
You can see that the hostname is missing in the url.  It's not just this extension - seems the same for most/ all.

Note that I fetch and unzip the extensions directly from ms marketplace, not from coder.com (waiting on https://github.com/cdr/code-server/issues/124)  Are they built differently or should they be identical?

**Comment by t-d-d** [comment]
I've actually found that the issue went away when I deployed behind a newer k8s nginx ingress controller.  Which led me to look at how the rewrite rules are generated.  Which lead me to find an erroneous extra '/' in my URL!

Closing.

**Comment by trobert2** [comment]
hello @t-d-d, would you mind sharing your ingress definitions?
I am having trouble loading some of the resources myself.
