### ISSUE TITLE
Increase fs.inotify.max_user_watches in docker container

### ISSUE THREAD

**Issue by RyanEwen** [cdr/code-server#628]
Opening certain projects leads to [this error](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc). However I am not sure how to work around it within the container. I have tried simply mounting a modified `/etc/sysctl.conf` from my host but it doesn't seem to make a difference.

How can we increase this within the container?

**Comment by RyanEwen** [comment]
Arg.. appears I forgot to run `sudo sysctl -p` after editing the conf file. Will have to test if the conf file even needs to be mounted into the container at all now.

**Comment by ammario** [comment]
I believe there’s no concept of namespacing that value so it will just transparently share whatever is set on the host.

**Comment by RyanEwen** [comment]
Perfect. I just tested and the container inherits the setting without mounting in the conf file. Thanks :)

**Comment by perguth** [comment]
```bash
docker run -dit -p 8443:8443   -v "${HOME}/.code-server:/home/coder/.local/share/code-server"   -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth
# ...
# 💻 Via a web terminal of `code-server`:
coder@6495fcb79cd7:~/project$ cat /proc/sys/fs/inotify/max_user_watches
8192
coder@6495fcb79cd7:~/project$ echo 'fs.inotify.max_user_watches=524288' | sudo tee -a /proc/sys/fs/inotify/max_user_watches
tee: /proc/sys/fs/inotify/max_user_watches: Read-only file system
```

😿

**Comment by ammario** [comment]
@perguth Docker mounts `/proc` as read-only since many of its knobs are global.

If you run that same command on the host, the container will transparently inherit the new setting.

**Comment by wellmsan** [comment]
I resolved by running the command on docker host machine:

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf`

`sudo sysctl -p`

Success, thanks!

**Comment by anion155** [comment]
Worked for me `sysctl fs.inotify.max_user_watches=524288`

**Comment by maitrungduc1410** [comment]
The solution of @wellmsan  works perfectly, but it misleading me at the first time because of "docker host machine". That means on your host machine, not inside docker container :)

**Comment by tcyfree** [comment]
Run the below command on docker host machine:
`echo 524288| sudo dd of=/proc/sys/fs/inotify/max_user_watches`

**Comment by doem97** [comment]
So there's nothing I can do within docker container? Somehow I can not get a root privilege on host, but I got root within docker container.

**Comment by ammario** [comment]
@doem97 if you're in a privileged container, you can set `max_user_watches` the same way you would on the host. For example, by running `echo 524288 > /proc/sys/fs/inotify/max_user_watches`.

It's possible that you're root within the container, but that user is mapped to an unprivileged one on the host. In such a case there's no way for you to change that setting.

**Comment by Francis235** [comment]
Hi， I have already increased {max_queued_events,max_user_instances,max_user_watches}, but I still have the issue: 
(executorch) root@dev-aigc-5:/mnt/nfs/dev-aigc-0/data1/bobozhou/worksapce/executorch# sysctl fs.inotify.{max_queued_events,max_user_instances,max_user_watches}
fs.inotify.max_queued_events = 999999
fs.inotify.max_user_instances = 999999
fs.inotify.max_user_watches = 5242880
(executorch) root@dev-aigc-5:/mnt/nfs/dev/worksapce/executorch# /tmp/buck2 build //examples/portable/executor_runner:executor_runner --show-output
Error initializing DaemonStateData

Caused by:
    0: Error creating a FileWatcher for project root `/mnt/nfs/dev/worksapce/executorch`
    1: Creating notify file watcher
    2: OS file watch limit reached. about ["/mnt/nfs/dev/worksapce/executorch"]
Build ID: 6d237e90-089f-4210-ad00-3edaeaac79ae
Jobs completed: 0. Time elapsed: 0.0s.
BUILD FAILED 
Any suggestions?  thanks.
