### ISSUE TITLE
Escape key caused losing focus out of editor on Vivaldi

### ISSUE THREAD

**Issue by lamnguyen95** [cdr/code-server#638]
- `code-server` 1.939-vsc1.33.1
- OS Version: Ubuntu 16.04 (Host) - Windows 8 Server (Local)
- Browser: Vivaldi 1.24

## Description
I usually hit Escape when editing (e.g: cancel intellisense suggestion). It's working normally on Chrome. However, on Vivaldi (which lets you change browser's color, reduce tab's size and hide address bar for less distraction), Escape key constantly cause losing focus out of the editor. I had to press Ctrl + 1 to refocus every time.

## Steps to Reproduce

1. Start Vivaldi and open code-server.
1. Edit any file and press Escape, then try typing any characters.

**Comment by nhooyr** [comment]
Not really sure what's going on. If anyone figures out, please let us know.

**Comment by KaKi87** [comment]
Hello,
I'm experiencing the same issue.
Thanks

**Comment by wh0am1-dev** [comment]
Same here. For reference, I think code-server should call `preventDefault()` on keyboard events for this to be fixed:

- https://forum.vivaldi.net/topic/73501/unmapped-esc-key-changes-focus/16
- https://github.com/codemirror/codemirror5/issues/7056#issuecomment-1732334071

I've tried adapting the user-script from the Vivaldi Forums link above, but it didn't work:

```javascript
// ==UserScript==
// @name         code-server-handle-esc.user.js
// @version      0.1
// @description  Support Esc key in code-server by preventing propagation Vivaldi blur event.
// @match        http://*/*
// @match        https://*/*
// ==/UserScript==

// https://forum.vivaldi.net/topic/73501/unmapped-esc-key-changes-focus/16

;(function () {
  function addEscListener(e) {
    window.removeEventListener('load', addEscListener)
    const monaco = document.querySelector('#workbench\\.parts\\.editor')
    if (monaco) {
      const textarea = monaco.querySelector('textarea')
      textarea.addEventListener('keydown', e => {
        if (e.key === 'Escape') e.stopPropagation()
      })
    }
  }
  window.addEventListener('load', addEscListener)
})()
```

**Comment by wh0am1-dev** [comment]
@code-asher, I disagree. VSCode doesn't run within a browser, but rather it's own native wrapper window. Since this project wraps VSCode to make it accessible within **any** browser, it's on this project to prevent browser-specific default behaviors when needed.

**Comment by code-asher** [comment]
VS Code contains both an Electron and web version.  We use the web version.

You can run VS Code's web version directly without our wrapper using `code serve-web`.

**Comment by wh0am1-dev** [comment]
All right, understood, will open an issue there. Thanks @code-asher !

**Comment by KaKi87** [comment]
> If they refuse to fix/add something, we can talk about patching it here though.

Would you add microsoft/vscode#77363 then ?

**Comment by code-asher** [comment]
@KaKi87 It looks like they are still open to the change if someone opens a new PR?

Bug fixes are one thing, but I would hesitate to maintain features that change this many lines.  If we think there are unlikely to be conflicts moving forward though I think we could consider it.
