### ISSUE TITLE
Use system user password for sign in?

### ISSUE THREAD

**Issue by ammario** [cdr/code-server#64]
How about we allow using the system user's password instead of a code-server specific one.

**Comment by lotusirous** [comment]
How about configure basic authentication by nginx reverse proxy ?

**Comment by kylecarbs** [comment]
The idea is more to use the system user/pass.

We could use https://github.com/Rush/node-authenticate-pam

**Comment by zk-g** [comment]
agree with pam, maybe also integrated in the settings of vs code

**Comment by schristm** [comment]
This would be a great feature

**Comment by sr229** [comment]
@ammario I wonder if this is still relevant?

**Comment by ammario** [comment]
@sr229 I think so, if we want to enable usage of code-server without an authenticating proxy.

**Comment by nhooyr** [comment]
No one really uses remote passwords anymore, only SSH keys.

We should just focus on Google Auth.
