### ISSUE TITLE
code : VSCode cli

### ISSUE THREAD

**Issue by iwoogy** [cdr/code-server#642]
Hello

I need to use the VSCode cli but I cannot find it.

## Description

```
root@13857b5bdf7d:/home/coder/project# command -v code
root@13857b5bdf7d:/home/coder/project# which code
root@13857b5bdf7d:/home/coder/project# code --version
bash: code: command not found
```

## Question

Is there a way to install VSCode command line ?

Thanks

Regards

Bobby

**Comment by vnijs** [comment]
Have you tried `code-server`?

**Comment by iwoogy** [comment]
Is it the same as the reguler code cli ?

What I try to achieve is to open a file programmatically.

For example on VSCode I will call :

`code --goto src/app/pages/main.tsx:24:9`

and VSCode will open the file at the line 24.

I tried :

```
code-server --goto src/app/pages/main.tsx:24:9
error: unknown option `--goto'
```

**Comment by vnijs** [comment]
As far as I know you cannot do that. See command line help below. `code-server` will start a web service that, once you are in the application in your browser, will work like vscode. 

![image](https://user-images.githubusercontent.com/2998956/57174621-7db66a80-6df6-11e9-870d-8c4696a4933e.png)

**Comment by haydennyyy** [comment]
They should make an RPC plugin and make a CLI that hooks into it. That'd be cool

**Comment by code-asher** [comment]
This isn't supported but hopefully it will be eventually: https://github.com/cdr/code-server/issues/164.

**Comment by sandric** [comment]
Any progress in that?
