### ISSUE TITLE
can't connect to localhost:8443 

### ISSUE THREAD

**Issue by zhengduoru** [cdr/code-server#645]
I run ` ./code-server .` and it returns like
![image](https://user-images.githubusercontent.com/30524929/57180514-bec48280-6ebb-11e9-9076-d95eb638944e.png)
then I try to connect to  localhost:8443 . 
![image](https://user-images.githubusercontent.com/30524929/57180519-dc91e780-6ebb-11e9-8f16-d1053f6836b7.png)
it is really hard for me to figure out what's wrong here..please help!

**Comment by oonqt** [comment]
Are you running code-server on your own computer or on a separate device?

**Comment by zhengduoru** [comment]
@oonqt I am running code-server on a remote server, which I have to ssh to a jumper server(I don't have root) and then ssh to the remote server.

**Comment by oonqt** [comment]
That's your problem. Localhost refers to your local machine, you cannot use it to access external machines. If you want to access code-server on your remote server, you need the IP address of your remote server.

**Comment by ookangzheng** [comment]
你要輸入 remote server 的IP地址如
http://1.1.1.1:8443 
防火墻也記得開啟 TCP 8443端口

**Comment by code-asher** [comment]
Closing since the question was answered.
