### ISSUE TITLE
No recommended extensions

### ISSUE THREAD

**Issue by LucasLeeDotNet** [cdr/code-server#646]
- `code-server` version: 1.939
- OS Version: OSX 10.13.6, Ubuntu 18.04

## Description
After one or more extension is installed and the app is reloaded, the list of marketplace extension won't load any more. Only by deleting all extension and reloading the app will restore the list. 

![empty-marketplace](https://user-images.githubusercontent.com/17604927/57187782-2c73ad00-6ec2-11e9-9ff1-e5b55915297e.jpg)

## Steps to Reproduce

1. Add a new extension
2. Reload the app (browser tab reload)

**Comment by nol166** [comment]
Thanks for the report! What browser are you using? Also if you click the three dots in the top right and click something like show popular extensions does anything show up?

**Comment by LucasLeeDotNet** [comment]
@nol166 It appears clicking on popular extensions will load the list of extensions, I may have been only observing the recommended list which always returns a empty list in code server, while the local vs code will returns a list of recommended plugin for the same exact project workspace.

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.

**Comment by nhooyr** [comment]
Related #1311
