### ISSUE TITLE
Is there any way to compile Pascal?

### ISSUE THREAD

**Issue by rev1be** [cdr/code-server#649]
Hello,
I host my code-server on Ubuntu 16.04.6 x64 (Digital Ocean) and wanted to ask if there is any way to compile my Pascal Code on the Code-Server?

**Comment by oonqt** [comment]
You can compile it using the terminal. It can be opened with Ctrl + `

**Comment by rev1be** [comment]
> You can compile it using the terminal. It can be opened with Ctrl + `

How? Is it even possible to compile Pascal code without any extention or FPC installed?
The Terminal is open - what do I need to press/do to run a .pas file?

**Comment by oonqt** [comment]
What linux distro are you using?

**Comment by sr229** [comment]
@rev1be keep in mind VSCode/code-server are both lightweight editors, in order to get your own tailored experience you must customize your IDE to fit your needs.  Please also keep in mind we don't come with a runtime to run Pascal code, you need to provide your own via APT.

**Comment by sr229** [comment]
CC @coadler for closure. Issue Invalid - Out of Scope for the project.
