### ISSUE TITLE
[Bug]: Can't install llm-vscode

### ISSUE THREAD

**Issue by ucalyptus2** [cdr/code-server#6490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Linux 
- Remote Architecture: forgot
- `code-server --version`: 4.11.0

### Steps to Reproduce

1. just try to install llm-vscode from the open vsx marketplace on the sidebar
2. install in bla bla bla ngrok.app
3. click install

### Expected

should be able to install

### Actual

cant install

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

![image](https://github.com/coder/code-server/assets/8037297/85779a48-bdbb-4406-9c29-2c36d75f763d)

![image](https://github.com/coder/code-server/assets/8037297/24353cee-027d-459f-b4c7-7c045e8db460)

**Comment by python-and-fiction** [comment]
Have you tried this in latest code-server?
