### ISSUE TITLE
Save opened session?

### ISSUE THREAD

**Issue by mrWiga** [cdr/code-server#652]
Hi, Is it possible to save opened session before closing? Example, if I'm working on file A and have terminal open with virtualenv etc.. if I close the browser, reopen url it would then directed me to the welcome screen instead of my last session.
Thanks

**Comment by nol166** [comment]
It isn't possible currently but this would be cool to add. Mind if I throw the feature tag on this one?

**Comment by hillsdong** [comment]
Great Feature!

**Comment by zpon** [comment]
This would be great. It seems like some state is saved sometimes, i.e. I usually see some files open when i reopen the editor. But it is always the same files that are shown and rarely files from the last session.

**Comment by hgw77** [comment]
is there anything new here? can see the same behavior like @zpon

**Comment by deansheather** [comment]
This is a known issue regarding service workers. We've changed some code that was running in the main thread to run in a service worker thread for better performance, but service workers unfourtunately cannot access localStorage, which is where we were storing session details.

Closing this in favor of #801 which has more information.
