### ISSUE TITLE
Corrupt json file, if json file is UTF-8 with BOM

### ISSUE THREAD

**Issue by andreyvoronko** [cdr/code-server#653]
- `code-server` version: 1.939-vsc1.33.1
- OS Version: Linux 

## Description

If the json file is UTF-8 with BOM, then a zero-length file is written. After that we can not close the tab with the file.
Microsoft vscode have not this problem.
## Steps to Reproduce

1. Open Json file in editor.
2. Edit
3. Save Json file 
4. Result: File corrut and lenth 0. The tab does not close.

**Comment by sr229** [comment]
No longer relevant to new releases. Closing as fixed
