### ISSUE TITLE
Archive in favor of vscode-remote?

### ISSUE THREAD

**Issue by kylecarbs** [cdr/code-server#655]
[vscode-remote](https://github.com/Microsoft/vscode-remote-release) was recently released :confetti_ball: 

Some quick differences:
- `code-server` is entirely open-source. `vscode-remote` is not **for now**.
- `code-server` provides access via a web-browser. `vscode` has this in the works ATM.

Does anyone extract value from `code-server` that `vscode-remote` doesn't provide? If not, it'd be great to archive.

**Comment by Multishifties** [comment]
From what I understand, the `vscode-remote` is essentially vscode with remote file system mounting. The binary is still running on a local machine. For resource-limited devices `code-server` would still be the preferred choice until such a time that `vscode-remote` allows web-browser porting/access.

**Comment by mengjuleu** [comment]
I tried to open super large project with both solution (code-server & MS Remote Development) on my macbook. TBH, code-server is way more faster than the extension.

**Comment by coadler** [comment]
https://code.visualstudio.com/docs/remote/faq#_why-arent-the-remote-development-extensions-or-their-components-open-source

To me it seems like they don't want to open source it at all

**Comment by t-d-d** [comment]
Self-hosted online VSCode.  VSCode Remote and the future VSCode Online don't seem to offer that.  Self-hosting is required in an enterprise setting.

**Comment by dr-br** [comment]
> The binary is still running on a local machine.

The vscode binary: yes. The application binary, however, runs on the remote machine. I don't think this is an issue for resource-limited devices.

**Comment by pstjvn** [comment]
I think its important for users without access to OS that can support VSCode binary, strange as it may seem I find myself often with a Chromebook only and travelling and I highly value the option this projects gives me which is NOT what vscode-remote provides at all!

**Comment by fbartels** [comment]
While I do see that the introduction of this service may put the current business model behind code-server at jeopardy I also want to express that I value the possibility to use this editor without the being dependent on Microsoft or its infrastructure.

If you decide to stop development maybe https://github.com/theia-ide could be an alternative (although at this point in time it does not offer the same "one binary" convenience as code-server does).

**Comment by sr229** [comment]
We still have a market for this thing. The only problem that I encounter that people might also encounter is the memory usage spike on a active session. This should have been fixed at some point in time, but it seems to be buried in backlog for now. Until it matches Theia's memory usage (~150MB), its almost impossible to use Code-server for Kubernetes hosts that has stricter memory requirements.

**Comment by jeasonstudio** [comment]
`code-server` has its unique application scenario, neither `vscode-remote` nor `visual studio online` can replace the status of `code-server` perfectly.

**Comment by geiseri** [comment]
I use a Chromebook for 99% of my work now.  1% is done via a RDP session via my Chromebook.   Eclipse Che is way to complicated and heavyweight.  It is trying to adopt a more modern approach but is painful to use outside of Java.  Cloud9 seems to have died on the vine, and theia is more of a toolkit than a usable product.  VS Code is one of the best dev envs to come along in a while as it is not just good at once language.  Yes, Javascript is the most popular, but its actually enjoyable to use with python and even strange formats like ReST.  I understand that what the coder guys are doing is NOT trivial and I hope there is a way they can monetize it and still be open source.  Open source dev tools are hard, the audience can go from using it because they can't (or don't want to) afford a paid solution, or they genuinely do want to be part of an open ecosystem. Ask Trolltech/Nokia/Digia/QtCompany how easy that is :P   Either way, I think this project is nice.  I just hope we can all come to an agreeable arrangement here so they can pay the rent, and we can enjoy coding on our Chromebooks!

**Comment by sr229** [comment]
@geiseri if this also consoles you, try hosting code-server on your Crostini instance as well.

**Comment by sr229** [comment]
I can assure you, with Microsoft's stance on hosted platforms, our project will stay @geiseri. We won't go anywhere.

**Comment by cstoddart** [comment]
Code-server has been one of my favorite projects since its release. I love managing my setup on my own server. I do use a Chromebook over my Macs when I can and plan to continue to do so. So far, this project has played a huge part in that, and I for one expect to see this project thrive

**Comment by camazorro** [comment]
How about both? have code-server to run on the browsers and connecting  to vscode-remote

**Comment by sr229** [comment]
its up to you if you really want to use both, however, in our side, this seems redundant for the VSO one, but the vscode remote tools would definitely allow more interopability.

**Comment by camazorro** [comment]
Yeah, I think that most of the "workspace" extensions are available and you can install them on vscode-remote. Is code-server have its own marketplace? If so this could open to having more extensions consumed by code-server because they're on vscode-server.

**Comment by fangli** [comment]
They work in a different way.
The users don't have to install anything when accessing the code-server.
If portable or flexible matters in such scenario, code-server is the only choice.

**Comment by code-asher** [comment]
`code-server` development will be continuing. :confetti_ball:
