### ISSUE TITLE
Reveal in folder bug

### ISSUE THREAD

**Issue by oonqt** [cdr/code-server#656]
Steps: 
right click folder > reveal in explorer

Result: Window reloads

Expected result: UNKNOWN

**Comment by sigxcpu76** [comment]
to me it reloads the window with the workspace rooted at that folder which i find much more useful than "open folder"

**Comment by code-asher** [comment]
This was removed in https://github.com/cdr/code-server/commit/4e62f938a967eb2e38d944408d28296bf75b9e5a.
