### ISSUE TITLE
Is visual studio online base on code server？

### ISSUE THREAD

**Issue by yamajik** [cdr/code-server#658]
Anyone has idea？

**Comment by yamajik** [comment]
https://devblogs.microsoft.com/visualstudio/intelligent-productivity-and-collaboration-from-anywhere/

**Comment by coadler** [comment]
I don't think so, but there's really no way to know since none of it is open source

**Comment by idoprz** [comment]
Maybe it's the other way around.. I believe many of the code change needed for VS online were helping code-server...

**Comment by yamajik** [comment]
vscode remote is a better solution with less resources for self host. 

code server should do much for code service case.

**Comment by code-asher** [comment]
The comments above are correct. :100:
