### ISSUE TITLE
Failed to save 'file': timed out error 

### ISSUE THREAD

**Issue by rielzzapps** [cdr/code-server#659]
- `code-server` version: latest
- OS Version: Ubuntu 18.04

## Description

I am running the code-server binairy in a 'screen', to be able to close the terminal and have it 'always on'. After a certain period of time (20 min?) when saving the file (ctrl-s) in VSCode, the 'dot' on the filetab will not dissapear, and VSCode shows the error above.

Only copypasting the whole code, and refresh the browser, will fix the issue.

## Steps to Reproduce

1. install screen
2. run code-server with screen ./code-server --host 0.0.0.0
3. open a file
4. keep saving changes until above error appears.

![Screenshot 2019-05-07 at 15 11 28](https://user-images.githubusercontent.com/9515736/57305497-7b4b5d80-70e1-11e9-8cf8-3fc2eeffa1f6.png)

**Comment by tkalpakidis** [comment]
have the same issue, trying on a k3s pod...

**Comment by nhooyr** [comment]
If this still occurs, please feel free to reopen.
