### ISSUE TITLE
Quick open feature shows no results

### ISSUE THREAD

**Issue by losnir** [cdr/code-server#661]
- `code-server` version: `1.939-vsc1.33.1`
- OS Version: `macOS 10.13.6`

## Description

The "quick open" / "go to file" feature shows empty results.
It is only when navigating a file in the first place (by clicking it in the file tree), then it will show up on the quick open.

## Steps to Reproduce

1. Download the latest macOS binary (`code-server1.939-vsc1.33.1-darwin-x64.zip`)
2. Extract and execute:
`$ code-server ~/path/to/repo`
3. Navigate to https://localhost:8443 and authenticate (or use `--no-auth`)
4. Use the Quick Open shortcut (CMD + P) to go to a file
5. The search results are always empty, even though it is possible to see the files in the tree

<img width="1680" alt="Screen Shot 2019-05-08 at 4 00 51 AM" src="https://user-images.githubusercontent.com/3738205/57342320-09a5fa80-7147-11e9-9cd0-44c987f9eaf5.png">

**Comment by losnir** [comment]
After some digging, it looks like this is a regression introduced somewhere between `1.408-vsc1.32.0
` and `1.604-vsc1.32.0`.

**Comment by code-asher** [comment]
Fixed in v2. :tada:
