### ISSUE TITLE
Developing VS Code Extensions in code-server

### ISSUE THREAD

**Issue by jots** [cdr/code-server#667]
## Description
I see that code-server known issue of: "Creating custom VS Code extensions and debugging them "  I'm curious if we will be able to create and debug extensions in the near future?

I'm on a chromebook and running vscode via xwindows is very laggy, code-server is a dream compared to it, but I would really like to develop an extension with it.

**Comment by sr229** [comment]
It's already possible to create extensions. Please use the same extension API with VSCode's as we share pretty much all the things from VSCode @jots.

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
