### ISSUE TITLE
I keep getting this error when I try and run code-server

### ISSUE THREAD

**Issue by WovenCoast** [cdr/code-server#668]
`./code-server: /lib64/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (required by ./code-server)
./code-server: /lib64/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found (required by ./code-server)
./code-server: /lib64/libstdc++.so.6: version 'CXXABI_1.3.9' not found (required by ./code-server)`

I keep getting this error when trying to run it.

**Comment by subchen** [comment]
Same issue found in centos 7

**Comment by subchen** [comment]
I successful to update `/lib64/libstdc++.so.6` and `/lib64/libc.so.6`

```bash
wget http://download-ib01.fedoraproject.org/pub/fedora/linux/updates/29/Everything/x86_64/Packages/l/libstdc++-8.3.1-2.fc29.x86_64.rpm

wget http://download-ib01.fedoraproject.org/pub/fedora/linux/updates/29/Everything/x86_64/Packages/g/glibc-2.28-27.fc29.x86_64.rpm

rpm -ivh --force --nodeps libstdc++-8.3.1-2.fc29.x86_64.rpm glibc-2.28-27.fc29.x86_64.rpm

./code-server
```

rpm downloaded from:
- https://fedora.pkgs.org/29/fedora-updates-x86_64/libstdc++-8.3.1-2.fc29.x86_64.rpm.html
- https://fedora.pkgs.org/29/fedora-updates-x86_64/glibc-2.28-27.fc29.x86_64.rpm.html

**Comment by sr229** [comment]
CC @Multishifties for closure. Solved by workaround.

**Comment by tumregels** [comment]
one workaround for centos/ubuntu distributions is to package `code-server` via [conda](https://docs.conda.io/projects/conda-build/en/latest/) and host it on anaconda's conda-forge, like [electron](https://anaconda.org/conda-forge/electron).
then these issues with missing libraries will be gone for good.

**Comment by sr229** [comment]
I don't think using such is a good idea. Targeting across GLIBC instance can already be done via CI by providing multiple OSes instead.

**Comment by radonn24** [comment]
> I succeeded to run by upgrade `/lib64/libstdc++.so.6` and `/lib64/libc.so.6`
> 
> ```shell
> wget http://download-ib01.fedoraproject.org/pub/fedora/linux/updates/29/Everything/x86_64/Packages/l/libstdc++-8.3.1-2.fc29.x86_64.rpm
> wget http://download-ib01.fedoraproject.org/pub/fedora/linux/updates/28/Everything/x86_64/Packages/g/glibc-common-2.27-38.fc28.x86_64.rpm
> wget http://download-ib01.fedoraproject.org/pub/fedora/linux/updates/28/Everything/x86_64/Packages/g/glibc-2.27-38.fc28.x86_64.rpm
> wget http://download-ib01.fedoraproject.org/pub/fedora/linux/updates/28/Everything/x86_64/Packages/g/glibc-langpack-en-2.27-38.fc28.x86_64.rpm
> 
> rpm -ivh --force *.rpm
> 
> ./code-server
> ```
> 
> rpm downloaded from https://pkgs.org/

Ran the commands above successfully, but now I get `Aborted (core dumped)`.

My CentOS VPS doesn't support Docker, so I am trying to install this manually ...

Any advice on how to proceed? I can provide the dump file, if needed...

**Comment by sr229** [comment]
Please do NOT use Fedora packages on CentOS systems, you are risking your system with further breakages because CentOS is for production ready systems. Fedora is a rolling distribution that has no gurantee being production ready.
