### ISSUE TITLE
Best way to add additional packages to container?

### ISSUE THREAD

**Issue by DanTulovsky** [cdr/code-server#672]
Hi..

So I've setup code-server to run on a kubernetes cluster and it works great.  It's using the codercom/code-server image provided.  

I need to install additional packages into the container (for example, golang).  I can do this if I clone the repo, edit the Dockerfile and add what I need in there.

Is this the best way to handle this?  The concern is that when the container restarts, I lose any apt-get installs I do manually.

Thank you
Dan

**Comment by losnir** [comment]
The right way would be to create your own Dockerfile and “inherit” the code-server image.

```
FROM codercom/code-server
RUN apt-get install golang
```

**Comment by DanTulovsky** [comment]
Thank you, that's much better.  I had to add

USER root

before the RUN.

**Comment by DanTulovsky** [comment]
For those that might be trying this at home, you need to switch back to coder user at the end:

FROM codercom/code-server
USER root
RUN apt-get install golang
USER coder
