### ISSUE TITLE
Nano editor does not work properly

### ISSUE THREAD

**Issue by syfxlin** [cdr/code-server#675]
- `code-server` version: Latest from Docker (codercom/code-server)
- OS Version: Ubuntu 18.04

## Description

When using the nano editor to open a file, it will display a misplacement when going to the previous page. For details, please see gif below.

> 使用nano编辑器打开文件时，在向上翻页的时显示错位，具体请看下面的gif

![nano](https://user-images.githubusercontent.com/28844480/57564315-83a2e180-73dc-11e9-872b-ebccf7af2141.gif)

## Steps to Reproduce

1. Open the file with the nano editor
1. Page down
1. Move the cursor up until the nano editor goes to the previous page

> 1. 使用nano编辑器打开文件
> 1. 向下翻页
> 1. 向上移动光标，直到nano编辑器去到上一页

**Comment by sr229** [comment]
This is because the terminal buffer is not refreshed properly, this might be a recurring issue with VSCode itself.

**Comment by syfxlin** [comment]
After confirmation, VSCode also has this problem, the problem is caused by VSCode.
