### ISSUE TITLE
extension Easy CoffeeScript didn't work after install

### ISSUE THREAD

**Issue by jots** [cdr/code-server#677]
- `code-server` version: code-server v1.939-vsc1.33.1
- OS Version: ubuntu in crouton
- Extension: https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-easy-coffeescript
## Description
after installing extension, it didn't work.  console showed error that it couldn't find module lodash.  fix:
~/.local/share/code-server/extensions/mkloubert.vscode-easy-coffeescript-1.2.0 $ npm install

**Comment by jaitaiwan** [comment]
I think if you don't install the extension using the --install-extension command then it won't work.

**Comment by nhooyr** [comment]
Works fine now. If this is still a problem, please feel free to reopen.
