### ISSUE TITLE
Code-server version jumps.

### ISSUE THREAD

**Issue by c608345** [cdr/code-server#6801]
- [X] I have searched the existing issues

### Steps to Reproduce

Code-server version jumps from 4.23.0 to 4.89.0. Is this a feature or bug?
https://github.com/coder/code-server/tags

### Expected

version   v4.24.0

### Actual

version   v4.89.0

**Comment by benz0li** [comment]
@c608345 Idea/Feature: See https://github.com/coder/code-server/pull/6783#issuecomment-2098332304 ff.

**Comment by benz0li** [comment]
@c608345 See also https://github.com/coder/code-server/discussions/6795
