### ISSUE TITLE
Need fix required parameter --allow-http for run with nginx

### ISSUE THREAD

**Issue by kondr1** [cdr/code-server#684]
I want use nginx reverse-proxy and i dont need http. But it doesn't work without it. How to use code-server without --allow-http param? I think it is a bug

**Comment by Xaver2k** [comment]
I had this concern too, but i think the necessary step is to tell the nginx-proxy to allow https from vscode even with the maybe invalid certificate.

**Comment by Rakiah** [comment]
I think it actually allow http even though no certificate is passed (because it is handled by the reverse proxy), it actually sound clear to me ? I might be wrong

**Comment by sr229** [comment]
@kondr1 you can also pass it without that flag. I think you misconfigured your proxy. Normally you could also handle TLS/SSL via nginx itself as well, but reverse proxy's certificate will take precedence, not the code-server's certificate.

**Comment by sr229** [comment]
CC @coadler for closure as this is invalid. using HTTP/S default is by design.

**Comment by antofthy** [comment]
See   https://github.com/cdr/code-server/issues/609   which includes a copy of the niginx conf I used.
I got it working...   three things were needed.
1/ nginx must proxypass as https  with the right port
2/ You also need to set the port in the proxy_set_header Host
3/ the cert-ssl package must be installed on the machine with code-server

The nginx does not care (by default) if the certificate is valid.
Though you may want its own certificate (the users see) to be valid.
