### ISSUE TITLE
How to get websocket connection count

### ISSUE THREAD

**Issue by gyuhwankim** [cdr/code-server#692]
I'm working the project that generates automatically code-server instance on new ec2 with terraform.
I will shutdown the ec2 when not in use with aws lambda to reduce cost.
If there is no connection for 30 minutes, I will shutdown ec2.

So, I require the ways that get websocket connection count.
Does the relevant API exist?

**Comment by roberthmiller** [comment]
No API exists for this. Also, just curious.. why don't you just create a fork of [sshcode](https://github.com/cdr/sshcode) and add this logic there to distribute to your userbase? You could simply use the aws sdk (if you trust the clients) or you can use a lambda to perform the actions from the sdk. Is this a viable option for you?

**Comment by jeasonstudio** [comment]
I use `code-server` behind NodeJS tcp proxy, so you can count websocket connection here.

**Comment by gyuhwankim** [comment]
@roberthmiller Thank you for your advice.
sshcode is considered, but I need a suitable solution for my case.

Unfortunately, I 'm doing military service, so 
I just can use Windows machine for sharing.
And, It must not install any program on local. 
Therefore, It is cumbersome to use terminal.

I just need that connect code-server on the browser directly.

**Comment by gyuhwankim** [comment]
Thanks @jeasonstudio!
I think your advice will help in my case.
