### ISSUE TITLE
python extension 

### ISSUE THREAD

**Issue by vnijs** [cdr/code-server#697]
- `code-server` version: 1.939-vsc1.33.1 and 1.1099-vsc1.33.1
- OS Version: Docker with Ubuntu 18.04 on macOS host
- Extension: https://marketplace.visualstudio.com/items?itemName=ms-python.python and also the "insider" version at https://pvsc.blob.core.windows.net/extension-builds/ms-python-insiders.vsix

## Description

When I start code-server and open a python file everything seems to work ok but there are quite a few errors shown in JS console. See the attached log file. This may not be much of an issue as the main things I want to use seem to work. Still seemed worth reporting errors however.

[code-server-python-extension.log](https://github.com/cdr/code-server/files/3195941/code-server-python-extension.log)

**Comment by davezhouwa** [comment]
Since this is the only one opening to track the python extension, can someone investigate on this. I'm desperately need the python debug function.

**Comment by code-asher** [comment]
I haven't been able to replicate any issues except for when I use code-server over an insecure domain. Does this match anyone else's experience?

**Comment by code-asher** [comment]
Good grief I keep speaking too soon. It seems to be related to whether service workers are enabled or not. So basically HTTP won't work (service workers aren't supported over HTTP) but HTTPS will work (even if it's an insecure HTTPS connection).

**Comment by vnijs** [comment]
FYI I was able to get release 2.1655-vsc1.39.2 to launch from jupyter and the latest python extension (2019.10.44104) seems to work. However, there are still a bunch of error messages. See image below. I'm running code-server from jupyter in a docker container. The url for container is http://localhost:8989. It could be that the errors are because I'm not using HTTPS but I'm not sure how to set that up.

![image](https://user-images.githubusercontent.com/2998956/67813382-a3979180-fa5e-11e9-9f2c-079549ec13de.png)

**Comment by davezhouwa** [comment]
I just tried ms-python extension 2019.10.44104 on a ubuntu 18.04 docker, the debug function still not working.

**Comment by vnijs** [comment]
I don't really use the python debugger, but as far as I can tell it is working in a docker image. You can get a (large) example image from vnijs/rsm-msba. When you start jupyter (port 8989), open a terminal and type "setup" to install vscode extensions.

Perhaps the easiest way to try the image is to download the shell script (https://github.com/radiant-rstats/docker/blob/master/launch-rsm-msba.sh) and run it. Press 3 to start jupyter, type "setup" in a terminal, and then start code server. All settings, extensions, etc. will be stored in ~/.rsm-msba

![image](https://user-images.githubusercontent.com/2998956/67817965-dd6f9480-fa6c-11e9-8d24-42e6ae99debe.png)

**Comment by davezhouwa** [comment]
@vnijs have you tried to run to the break points?
For me, it is still not working. 
My set up is like the following:
1.I have a docker running at http://hostIp:7001
2.Inside the docker, I have a reverse proxy setup which redirect http request to codeserver which is running at https://localhost:8080 on the same docker. the reverse proxy and codeserver use the same self signed certs created through openssl.
3. I access the webide through http://hostIp:7001 through Chome.

Is Python debug suppose to work in this environment setup? @code-asher

**Comment by vnijs** [comment]
FYI In another container where I also use codeserver, started from jupyter, and see the following. Could this be a jupyter-server-proxy issue?

```
[I 19:27:01.681 LabApp] 302 GET /vscode/manifest.json (172.17.0.1) 0.90ms
[E 19:27:01.681 LabApp] Uncaught exception GET /vscode/manifest.json (172.17.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/vscode/manifest.json', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/usr/local/lib/python3.6/dist-packages/jupyter_server_proxy/websocket.py", line 96, in get
        return await self.http_get(*args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/jupyter_server_proxy/handlers.py", line 452, in http_get
        return await self.proxy(self.port, path)
    TypeError: object NoneType can't be used in 'await' expression
```

**Comment by code-asher** [comment]
Ahh, that's interesting. It might be. I'll have to give it a spin and see if the same thing happens to me.

**Comment by davezhouwa** [comment]
FYI, I install latest release, python debug is working without https. I'm curious what has been done on the service worker.

**Comment by vnijs** [comment]
As far as I can tell the remaining error messages in developer tools may be due to issues in the python extension. See links below. I think this issue can be closed. Thanks for making this great tool!

https://github.com/microsoft/vscode-python/issues/7380
https://github.com/microsoft/vscode-python/issues/7380

**Comment by code-asher** [comment]
@davezhouwa I think I was wrong about the service worker. It was trying to block access to `self.caches.open` which apparently isn't available on HTTPS (in Chrome and Safari at least) but trying to do so caused it to panic.

**Comment by code-asher** [comment]
Ah so to continue I just skipped that line when `self.caches` isn't available. I'm not sure this fixes all extension issues on HTTPS but it does seem to fix some at least.
