### ISSUE TITLE
How to login to firebase tools or other similar services

### ISSUE THREAD

**Issue by muhammadomais** [cdr/code-server#702]
## Description
How can i use firebase tools on Coder. When i try to login using cli it generates a link for localhost but after signing into an account and authenticate the redirect link cant take you back to the coder to complete the authentication process

**Comment by cstoddart** [comment]
This is not an issue with code-server. You'll need to use the --no-localhost flag when you run firebase login

**Comment by muhammadomais** [comment]
Thanks
