### ISSUE TITLE
How much memory does it use with a bare setup?

### ISSUE THREAD

**Issue by CrazyPython** [cdr/code-server#704]
I'm trying to see if it would be viable to fit coder.com on production instances.

**Comment by sr229** [comment]
As of the latest release, it eats 800MB and 900MB-1GB with extensions. We're still working on reducing this.

**Comment by sr229** [comment]
I might as well actually document this.

**Comment by code-asher** [comment]
Closing since we recommend 1GB in the readme. I've been seeing around 600MB when first starting up.
