### ISSUE TITLE
Cannot open multiple editors (sometimes) 

### ISSUE THREAD

**Issue by fbartels** [cdr/code-server#705]
- `code-server` version: 1.1119-vsc1.33.1
- OS Version: Ubuntu 16.04 64bit

## Description

~~Previous versions (could be 1.903-vsc1.33.1 or earlier, did not check exact version) allowed to open multiple files with the same name in the editor. In more recent version opening a second editor replaces the editor of the previous file.~~

In a so far not reproducible way every know and then code-server does not allow additional editor tab and instead replaces the existing tab with the new file. Originally this seemed to be related to the filename, but afterwards I noticed that if happens with any file.

When this occurs, closing code-server in the browser and reopening makes it work again.

## Steps to Reproduce

1. open file with the name `Dockerfile`
2. browse to a different location on your disk and open another `Dockerfile`

Result: instead of opening another tab with the editor the original Dockerfile is replaced with the more recent one.

**Comment by fbartels** [comment]
hm.. that actually does not always seem to be the case. Right now I've tried it again (still in the same session, have not closed code-server in between) and I can open files with the same name without problems.

**Comment by fbartels** [comment]
After further observation the issue is as followed:

- every now and then when I open code-server (I always connect to the same instance from multiple systems) it just opens one editor tab
- when a second editor tab is opened it replaces the already existing one.

**Comment by deansheather** [comment]
Cannot reproduce. I can open multiple Dockerfiles at the same time from multiple folders, and they show as separate tabs even after reloading the browser.

**Comment by fbartels** [comment]
Hi @deansheather,

thanks for giving it a try. I had previously posted a comment to clarify the behavior I see a bit. But in a comment this is indeed easy to overlook. I have now updated the original description.

**Comment by code-asher** [comment]
I haven't replicated this with v2 but I'll keep an eye out.

**Comment by sr229** [comment]
Confirming no longer present on v2.
