### ISSUE TITLE
Set value of 'vscode.env.appRoot'

### ISSUE THREAD

**Issue by edgardmessias** [cdr/code-server#706]
- `code-server` version: 1.1119-vsc1.33.1
- OS Version: wsl (Ubuntu 18.04.2 LTS)

## Description

Set value of 'vscode.env.appRoot' to resolve with `<vscode path>/resources/app`.

Some extensions use a tip to load the native node_modules of VSCode, like `require(appRoot + "/node_modules.asar/<module_name>")`.

This can solve the problem with "Bracket Pair Colorizer 2" (#544)

Current value of `vscode.env.appRoot` is empty, and "Bracket Pair Colorizer 2" try load the `/./node_modules.asar/vscode-textmate`

**Comment by ahmedanis03** [comment]
how can we set this value?

**Comment by code-asher** [comment]
Definitely should be fixed in v2. We map `node_modules.asar` to `node_modules` to make it all work properly.
