### ISSUE TITLE
CloudFormation template for AWS wanted

### ISSUE THREAD

**Issue by hicke** [cdr/code-server#707]
There is an easy way to deploy infrastructure in AWS: Cloudformation. You can create a template and distribute it as code which means you would keep the deployment of coder consistent even if you make changes.

**Comment by sr229** [comment]
We won't cover all use cases, unfortunately, please make your own instead.

**Comment by sr229** [comment]
CC @Multishifties or @deansheather for closure. Insufficient use case scenario to merit support

**Comment by deansheather** [comment]
I think this should be left open and possibly tagged help wanted. I don't use AWS enough to know how to create a CloudFormation template the "correct" way, and it'd be nice if someone could add it the repo alongside our k8s files.

**Comment by sr229** [comment]
We can have Ansible instead to do the same thing but in a more cloud-neutral way. Having vendor-specific deployment manifests seems make this repo more inclusive for a provider.

**Comment by sr229** [comment]
Closing as wontfix since we provide a basic documentation for all providers instead.
