### ISSUE TITLE
Vim extension is not working

### ISSUE THREAD

**Issue by codeurge** [cdr/code-server#708]
- `code-server` version: code-server v1.1119-vsc1.33.1
- OS Version: DigitalOcean Ubuntu 18.04
- Extension: [VSCodeVim](https://github.com/VSCodeVim/Vim)

## Description

After installing the VSCodeVim extension, I'm unable to use vim keymappings. I tried toggling vim mode as well, to find the error `command 'toggleVim' not found`.

I've tried installing extension versions 1.4.0, 1.8.0, and 1.0.8 as per indicated in previous similar issues but am not able to get it to work at all. Any version of code-server in particular I should try downgrading to?

## Steps to Reproduce

1. Install code-server v1.1119-vsc1.33.1
2. Install VSCodeVim (1.4.0)
3. Try Vim Keybindings / Toggle Vim Mode

**Comment by deansheather** [comment]
Could not reproduce with same code-server and VSCodeVim versions. I was able to navigate around the file with vim keybindings and toggle vim mode through the command palette.

**Comment by fangli** [comment]
Try run the browser in incognito mode.
Probably some chrome plugins mess up the keybindings.

**Comment by alanpog** [comment]
I've got the same issue, similar setup. An additional piece of info: whenever I try to use Vim with `:` or `/` I get an "Activating Extensions" briefly loading on the bottom bar, then disappears. Also, I can't see other extensions loaded, like `pretty` either. Though they are all there on the extensions tab showing as *Enabled* (tried to disbale en re-enable, no luck).

**Comment by alanpog** [comment]
Used `--skipsync` and installed Vim extension fresh, on a new install, then it worked. It was syncing my extensions through `sshcode` before.

**Comment by codeurge** [comment]
I wasn’t able to get this working, but am also not going to be using the project in the near future as it was part of a lost battle in discussion at work.

Thanks for the awesome work here, it’s really impressive.

**Comment by vnijs** [comment]
Any chance this could re-opened? Or should I open a new issue?

Running 2.1692-vsc1.39.2 in a docker container (Ubuntu 18.04) with VSCodeVim 1.12.2

![image](https://user-images.githubusercontent.com/2998956/71126667-4c7c8600-219e-11ea-86c2-7f599ce2dc4f.png)

![image](https://user-images.githubusercontent.com/2998956/71126590-29ea6d00-219e-11ea-977e-7a073419963f.png)

**Comment by fwcd** [comment]
This is the issue I get when trying to launch VSCodeVim:

![image](https://user-images.githubusercontent.com/30873659/85224758-d49d4b80-b3cc-11ea-90fc-d2d471729dda.png)

**Comment by code-asher** [comment]
@fwcd Is that Firefox? The vim extension uses regular expressions Firefox doesn't support yet, so for now the only workaround is to use Chrome.

**Comment by nhooyr** [comment]
Let's add this to the FAQ.

**Comment by DAddYE** [comment]
Quick question, if the issue is with Safari, why in online.microsoft.com vim works quite well? Do they use a different one?

**Comment by code-asher** [comment]
We run it in the browser while they probably run it on the server. The issue we had with running it on the server is that depending on your connection it can get rather laggy because it has to communicate to the server and back for every keystroke. Perhaps we should have a way to force it to load on the server though? Or keep it on the server by default and have a way to make it run in the browser?

**Comment by DAddYE** [comment]
> We run it in the browser while they probably run it on the server. The issue we had with running it on the server is that depending on your connection it can get rather laggy because it has to communicate to the server and back for every keystroke. Perhaps we should have a way to force it to load on the server though? Or keep it on the server by default and have a way to make it run in the browser?

Yup I noticed is a little slow, but I agree that we running it on the server can be a good choice if you have a good connection or better, `code-server` is in your LAN.

Do you have a document or instructions to force it on the server?

**Comment by code-asher** [comment]
Nope, unfortunately at the moment it's hard-coded so we'd need to make that customizable.

**Comment by shritesh** [comment]
This is being fixed upstream https://github.com/VSCodeVim/Vim/pull/3525#issuecomment-662529074
