### ISSUE TITLE
Freezing when viewing modernizr 3.5.0 (Custom Build) file

### ISSUE THREAD

**Issue by meoz** [cdr/code-server#714]
code-server v1.939-vsc1.33.1
OS Version: ubuntu 18.04 x64

## Description

I'm unable to open the modernizr.js file, clicking the file makes the editor freeze. Only way to go forward is refreshing the browser.
It seems the file must contain something the editor does not like much, all other files open just fine. 

update:
Did try to open the un-minified versioin of the file, this opens without problems. Looks like it happens only with the minified file. Does the editor have issues loading files with very long lines ? (enabling word-wrap in settings did not make a difference).

**Comment by deansheather** [comment]
I can reproduce this with a large minified JS file (~86k). If I click on the filename multiple times it eventually opens with a warning notification saying "Tokenization is skipped for long lines for performance reasons. The length of a long line can be configured via `editor.maxTokenizationLineLength`". Perhaps decreasing this value in code-server could fix this issue.

For reference, opening the non minified version of the same file (~274k) would load every time, albeit slowly.

**Comment by meoz** [comment]
Thanks, lowering the editor.maxTokenizationLineLength number did solve the problem. I guess the tokenize length depends on the available memory of the server.

**Comment by code-asher** [comment]
Tokenization actually happens on the client in the UI thread unfortunately, which is why it can hang your browser. :crying_cat_face:
