### ISSUE TITLE
IPad black screen

### ISSUE THREAD

**Issue by andreyvoronko** [cdr/code-server#715]
- `code-server` 1.1099-vsc1.33.1
- OS Version: linux
## Description
IPad 10.5 2016  iOS 12.3 , IPhone XS , Client Safari 
Does not work. Black screen.

**Comment by coadler** [comment]
Mobile versions of safari won't work with invalid certificates. Consider getting one issued from https://letsencrypt.org/ or use the `--allow-http` flag if running on your local network.

**Comment by andreyvoronko** [comment]
You're right. Thank. It all worked.

**Comment by az0uz** [comment]
For anyone on iPadOS, and trying to get https with a self signed certificate:
There is another way to make it work by doing the same as what has been done here:
https://7402.org/blog/2019/new-self-signed-ssl-cert-ios-13.html
