### ISSUE TITLE
`ctrl + t` keybinding

### ISSUE THREAD

**Issue by roberthmiller** [cdr/code-server#716]
## Description

I am trying to open a tab in chrome.

In chrome, `ctrl + t` normally brings up a new tab, but since code-server has this keybinding for symbols, it is impossible to open a new without using the mouse, which kills my workflow.

What would you guys recommend that I do in this situation?

**Comment by deansheather** [comment]
I can't reproduce on Linux. Have you tried changing/unbinding all instances of `Ctrl+T` in `File > Preferences > Keyboard Shortcuts`?

**Comment by roberthmiller** [comment]
![image](https://user-images.githubusercontent.com/23535075/58422593-f3fa6580-8060-11e9-9400-58f566b0338d.png)
It is a default binding. I can, of course, change it, but it would be nice if it would by default be set to something other than ctrl + t.

**Comment by roberthmiller** [comment]
I can just unbind it (because, if you open up command palette, you can get to this feature). 

I will close this because the question has been answered.
