### ISSUE TITLE
Unable to create new file or folder

### ISSUE THREAD

**Issue by roberthmiller** [cdr/code-server#717]
- `code-server` version: 1.1119-vsc1.33.1 (using sail)
- OS Version: Ubuntu 19.04

## Description
Cannot create a new directory or folder through the UI

1. Try to create a new file

![Peek 2019-05-26 16-26](https://user-images.githubusercontent.com/23535075/58386826-74728500-7fd3-11e9-88f5-a73a73c7eb10.gif)

**Comment by deansheather** [comment]
Does the browser console show anything when this happens?

**Comment by erwinverdonk** [comment]
Looks like a permissions issue to me. double the permissions of the parent folder and maybe provide additional information regarding.

**Comment by roberthmiller** [comment]
Hm, now I am able to create a folder... that is odd...Will close this for now, but will reopen it if I find this issue again.
