### ISSUE TITLE
Trouble getting docker image to work

### ISSUE THREAD

**Issue by mackenziemi** [cdr/code-server#718]
code-server version: 1.621
- OS Version: Ubuntu 16.04

## Description

Starting up the docker container for the first time and getting this error 

Error: ENOENT: no such file or directory, scandir '/home/coder/.local/share/code-server/User/workspaceStorage'
    at Timeout.setTimeout [as _onTimeout] (/src/packages/server/build/bootstrap-fork.js.gz:57684:27)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

## Steps to Reproduce

1. Setup Ubuntu VM in Azure
2. Install Docker
3. Pull and run docker container per, https://dev.to/babak/how-to-run-vs-code-on-the-server-3c7h

**Comment by roberthmiller** [comment]
Hey! That version is really old. Is it possible that you could update code-server image? You could simply omit the tag for the docker image like so: 
```
docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth
```
After this, can you please tell me if the problem persists?

**Comment by sr229** [comment]
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/1307
