### ISSUE TITLE
Extension Bug — publisher:"small"

### ISSUE THREAD

**Issue by ruslanguns** [cdr/code-server#720]
- `code-server` version:  code-server v1.1119-vsc1.33.1
- OS Version:  Ubuntu 18
- Extension: 
https://marketplace.visualstudio.com/items?itemName=small.php-ci

## Description

Can't find the extension in marketplace.

## Steps to Reproduce
Search the extension, it wouldn't be found.

Thanks for your help.

**Comment by sr229** [comment]
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.

**Comment by code-asher** [comment]
So I think this is because our marketplace currently doesn't handle all
types of queries and querying by publisher name is one thing that
doesn't work yet.

**Comment by code-asher** [comment]
Actually maybe we just haven't added it yet.

**Comment by sr229** [comment]
@code-asher Confirm this was already added?

**Comment by code-asher** [comment]
@sr229 I checked and it does seem to be added. However, searching with the `publisher:` prefix doesn't work so we should fix that.

**Comment by sr229** [comment]
Keeping it open till that's fixed.

**Comment by nhooyr** [comment]
See #1299
