### ISSUE TITLE
Accessing VSCode via Javascript

### ISSUE THREAD

**Issue by freman** [cdr/code-server#723]
## Description

So, I'm working (as I said before) on my own sshcode tool that does much like the existing cdr tool does but with a bit more power and flexibility.

I've got it working, installing vscode and launching a browser window (github.com/zserge/lorca) but I'm looking to write an extension that allows code-browser to dynamically create port forwards (or rather allows people to create them from within vscode) and I will need to inject some parameters for that to work (ie: local websocket address)

I'm thinking the easiest way to do this is to simply inject via js/dom on the browser window.

Does anyone know how to access the actual vscode application instance via javascript?

Options considering

* Pass arguments on startup to an extension?
* Inject javascript in the _browser_ window
* Per workspace/project settings and having my sshcode tool read those (Would need some way of knowing that the workspace has changed and what it currently is)

edit: ooh I just found the `ide` object
edit: ooooh 
![image](https://user-images.githubusercontent.com/506680/58458125-b9312400-816b-11e9-85b5-67a6b816859d.png)

hmmm webview seems a little unreliable? all I've got is a copy of the cat demo

![image](https://user-images.githubusercontent.com/506680/58460537-34e19f80-8171-11e9-9774-d4a5712bb6da.png)

**Comment by roberthmiller** [comment]
It looks like you have found it. Is that correct?

**Comment by freman** [comment]
Yes, seems so, I might have other issues, but yay for this one :D
