### ISSUE TITLE
command 'docker-explorer.refreshDockerHub' not found

### ISSUE THREAD

**Issue by K-Salokhiddin** [cdr/code-server#726]

**Comment by K-Salokhiddin** [comment]
command 'docker-explorer.refreshDockerHub' not found

**Comment by roberthmiller** [comment]
do you have any more detail?

I don't even know where this is being used to begin to help you debug...

**Comment by K-Salokhiddin** [comment]
Hello,

I installed Docker Extension pack and after installation when i press
refresh button at docker explorer it gives error *command
'docker-explorer.refreshDockerHub' not found.  *And i have another one
question. I want to install remote container extension, but as discovered
it is not available yet in code-server, i tried to install it manually from
vsix file. But there is a same problem. And i made some research  and
analysed. This is only my opinion maybe i am making mistake: this problem
coming because the main file of extension is minimized and mapped but map
file is not exists on code-server. Can you give me this
*extension.js.map *file.
Thank you in advance.
With regards,
Salokhiddin Kurbonov

**Comment by nhooyr** [comment]
Duplicate #1299
