### ISSUE TITLE
Dont find a extension totvs.tds-vscode

### ISSUE THREAD

**Issue by matheus-sales** [cdr/code-server#728]
- `code-server` version: v1.1119-vsc1.33.1
- OS Version: All OS
- Extension: https://marketplace.visualstudio.com/items?itemName=totvs.tds-vscode and https://marketplace.visualstudio.com/items?itemName=totvs.tds-monitor

## Description

I can not find the extensions on the market. By VSIX works, but would like to see in the marketplace. I'm the extension developer

Thanks.

https://github.com/totvs/tds-vscode
https://github.com/totvs/tds-monitor

## Steps to Reproduce

1. Opent the marketplace
2. Write "tds" or "totvs.tds-vscode" or "totvs.tds-monitor".
![notfound](https://user-images.githubusercontent.com/11618741/58500778-3c954a00-8159-11e9-9e93-a8e8f0dc160c.png)

**Comment by roberthmiller** [comment]
Hey!

At the moment, since VSCode marketplace is fully closed source, we are unable to use it within code-server. I believe that there is a marketplace for code-server, but I am not entirely sure.

**Comment by matheus-sales** [comment]
> Hey!
> 
> At the moment, since VSCode marketplace is fully closed source, we are unable to use it within code-server. I believe that there is a marketplace for code-server, but I am not entirely sure.

Yes, has a closed and different marketplace for code-server and I would like add my plugin in code-server marketplace. How I do this? Do you can help me?

Thanks!

**Comment by sr229** [comment]
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.

**Comment by code-asher** [comment]
Don't we just need to add it to our marketplace?

**Comment by sr229** [comment]
Seeing this has been open since May I think it should have been added by now.

**Comment by code-asher** [comment]
It doesn't seem to come up in the search so it's possible no one got
around to it.

**Comment by nhooyr** [comment]
#1299
