### ISSUE TITLE
Binary for Mac OS

### ISSUE THREAD

**Issue by myelsukov** [cdr/code-server#729]
## Description
Are you going to include a binary for Mac OS in the releases?

**Comment by roberthmiller** [comment]
Just tried on my mac, and I noticed that there is a format error (os does not understand). I would recommend that you use docker in this case.

**Comment by myelsukov** [comment]
Latest released simply do not include `darwin` version. Just two linux versions: a regular one and a `musl` one.

**Comment by roberthmiller** [comment]
@kylecarbs can you please update the github release assets?

@myelsukov as a workaround, for now, I would use the docker version, or... use an older release.

**Comment by myelsukov** [comment]
I am using the older version. I hoped though to start using a newer version with some bugs fixed/features implemented :)

**Comment by roberthmiller** [comment]
@myelsukov as a note, you can get the latest release for mac [here](https://github.com/cdr/code-server/releases/tag/1.1156-vsc1.33.1)

**Comment by myelsukov** [comment]
@roberthmiller Thank you! I already found it :)

**Comment by roberthmiller** [comment]
Close this?

**Comment by myelsukov** [comment]
Sure
