### ISSUE TITLE
Connect to Existing session?

### ISSUE THREAD

**Issue by Merith-TK** [cdr/code-server#732]
The basic gist of this, is an Extension for a DESKTOP client, to connect to a Code-Server session

Words are hard, Diagram
Desktop VSCode `code.exe`> Code-Server-Remote_Plugin > Code-Server at `code.example.com`

**Comment by sr229** [comment]
This is similar to the remote extension. We can just install it with the instance and run it like that.

**Comment by nhooyr** [comment]
Please use vscode-remote.
