### ISSUE TITLE
How to run locally after clone for development mode?

### ISSUE THREAD

**Issue by mukeshkmr776** [cdr/code-server#735]
## Description

Please provide clear steps on how to run this project (after git clone) from local. 

I saw  #17 #335 #430 #555 #571, but no clear steps were ever mentioned. If there is any document for the same, please give me a link.

## Related Issues
I had a look in **package.json** which is placed in root folder of this project.

Tried few steps to start it locally:
1. npm install <- successfully executed
2. npm start <- failed with TS Errors. See attached logs for the same.

My Machine Details:-
Ubuntu - 19.04

LOG- [npm-start.log](https://github.com/cdr/code-server/files/3244134/npm-start.log)

Screenshot below:
![screenshot](https://user-images.githubusercontent.com/18456767/58752720-7e175380-84d1-11e9-8398-7a81d0c577f2.png)

**Comment by mukeshkmr776** [comment]
@coadler  @kylecarbs  @scsmithr

**Comment by deansheather** [comment]
After installing `libxkbfile-dev` and `libsecret-1-dev` dependencies, you should be able to do `yarn` and `NODE_ENV=production yarn task build:server:binary` to build a binary.

You can find the binary in `./packages/server/cli-linux-64`.

**Comment by ddezoysa** [comment]
1. Newly installed Ubuntu 19.04 into a VM.
2. Cloned the code from master.
3. Installed Node v10.16.0, Yarn 1.13, libxkbfile-dev, libsecret-1-dev, net-tools
4. Executed `yarn` and `NODE_ENV=production yarn task build:server:binary`.  Build worked with no issues.
5. Tried `yarn start` but receiving below error.

ddezoysa@vm-ddezoysa:~/code-server$ yarn start
yarn run v1.13.0
$ cd ./packages/server && yarn start
warning package.json: No license field
warning ../package.json: No license field
$ node --max-old-space-size=32384 --require ts-node/register --require tsconfig-paths/register src/cli.ts

/home/ddezoysa/code-server/packages/server/node_modules/ts-node/src/index.ts:261

    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
../protocol/src/browser/modules/spdlog.ts(1,25): error TS7016: Could not find a declaration file for module 'spdlog'. '/home/ddezoysa/code-server/node_modules/spdlog/index.js' implicitly has an 'any' type.
  Try `npm install @types/spdlog` if it exists or add a new declaration (.d.ts) file containing `declare module 'spdlog';`

    at createTSError (/home/ddezoysa/code-server/packages/server/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/home/ddezoysa/code-server/packages/server/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/home/ddezoysa/code-server/packages/server/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/home/ddezoysa/code-server/packages/server/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/ddezoysa/code-server/packages/server/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

6. Tried again after `yarn postinstall` as well but no luck. Getting the same error.

How to get the code running in developer mode to do some enhancements without building and running in production mode?

**Comment by deansheather** [comment]
Oh, my bad. Try this:
```
yarn
NODE_ENV=production VERSION=local-dev yarn task build:server:binary
yarn task package local-dev
```

Then you can run the produced binary in the `release` folder. I don't think `yarn start` works.

**Comment by mukeshkmr776** [comment]
Tried.Its working. Thanks.

Could you please share detailed structure of this project? I couldn't even find the starting point of this. Also, not sure from where how the VSCode view is generating. 

Please help here to share some kind of porject structure. It would be easy on me to start working on this asap.
:)

@coadler @kylecarbs @scsmithr @sr229

**Comment by sr229** [comment]
`code-server` uses a patched version of the Visual Studio Code and runs it under a HTTP/S server. So you'd be looking for two things - the Visual Studio Code codebase and the server codebase. 

Keep in mind we don't directly submodule or keep our own copy of the vscode repository, we use a patchfile to insert our changes. I forgot how to generate your patchfiles but the developers at Discord will walk you through on how to submit a modification to the patchfile @mukeshkmr776 .

@mukeshkmr776

**Comment by mukeshkmr776** [comment]
Exactly! You got my point. I am looking for that. 
Please  walk me through the Patch file, how to apply, on VSCode codebase.

I want to see the diff just to be aware what exactly  we have changed to make it live on http/s.

Please help. Connect me with right person. @sr229

**Comment by sr229** [comment]
I think we should wait for GH-795 since its going to be easier to work with the codebase.

**Comment by VN666** [comment]
> Oh, my bad. Try this:
> 
> ```
> yarn
> NODE_ENV=production VERSION=local-dev yarn task build:server:binary
> yarn task package local-dev
> ```
> 
> Then you can run the produced binary in the `release` folder. I don't think `yarn start` works.

when I try your method,it runs! But another question happen:
I run binary code in realse, the terminal module cannot use, details as follow:
![image](https://user-images.githubusercontent.com/19190890/60957257-e8c07800-a336-11e9-86ad-895e9a6a5887.png)

**Comment by sr229** [comment]
CC @coadler, I believe you might have an idea with the Terminal not working for @VN666

**Comment by deansheather** [comment]
`pty.node` is supplied from `node-pty`: https://github.com/microsoft/node-pty/issues/256. Ensure `python --version` returns 2.x (if not, change your python preference to python2), as most native Node packages require python2 to build properly, then clean and reinstall with yarn.

Make sure your Node version is v10.15.1, as this is the version we use when building nbin and code-server. `node-pty` will fail to load `pty.node` if the version it was compiled with (`node --version`) doesn't match the version of Node used when running it.

**Comment by VN666** [comment]
> CC @coadler, I believe you might have an idea with the Terminal not working for @VN666

just use node v10.15.1, this question will done

**Comment by code-asher** [comment]
The new README provides all the steps required to start development. :tada: Let me know if anything is unclear.
