### ISSUE TITLE
Binary for AIX

### ISSUE THREAD

**Issue by mukeshkmr776** [cdr/code-server#736]
## Description

Also supports running code-server in AIX machine?
Any possibility of building binary locally for AIX machine and then running it there?

Scenario:
I am having remote machine of AIX OS. I had to do coding stuffs by logging into that AIX machine via terminal. Its very hard to modify js/ts/css/ via vi-editor. So, I want this code-server to run on AIX machine.

**Comment by mukeshkmr776** [comment]
@coadler  @kylecarbs  @scsmithr

**Comment by sr229** [comment]
@mukeshkmr776 We do not support AIX targeting for a variety of reasons:

- AIX is hard to source for development purposes. This Unix distribution can only be found shipped on IBM Z servers and we do not even have the funds to buy one.

- Keep in mind while AIX has Node.js packages, there's a large chance native modules are not compensating for AIX which can break the functionality.

**Comment by coadler** [comment]
Gonna close this one as wontfix since this won't be tackled internally at Coder. If anyone in the community has an AIX system and would like to contribute patches/instructions that'd be more than welcome.

It's very possible it works now since this issue is phrased as more of a question, but there's no way for us to find out currently.

**Comment by mukeshkmr776** [comment]
@coadler I have AIX system. Maybe I can try supporting it.
Just give me the project dependencies list and I will try it out on AIX.

**Comment by sr229** [comment]
@mukeshkmr776 even if you add support, our CI system does not have access to AIX images, which makes it entirely pointless since we can't distribute AIX images officially

**Comment by mukeshkmr776** [comment]
:/
Ok. Then leaving it for AIX -_-

Thanks for info :) :+1:
