### ISSUE TITLE
[Raspberry Pi] ARM architecture not supported

### ISSUE THREAD

**Issue by danhab99** [cdr/code-server#742]
- `code-server` version: latest
- OS Version:  Raspbian 9.9 stretch

## Description

Unable to start server:

```
pi@danpi:~ $ docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http
docker: Error response from daemon: failed to create endpoint silly_babbage on network bridge: failed to add the host (veth4ce237b) <=> sandbox (vethd881caf) pair interfaces: operation not supported.
```

## Steps to Reproduce

1. Run `docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http`

**Comment by RyoshiKayo** [comment]
@danhab99 Have you tried rebooting the Pi? From my research it looks like thag might be a possible resolution.

**Comment by danhab99** [comment]
Did a reboot and tried running the command again, no change

```
pi@danpi:~ $ docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http
standard_init_linux.go:207: exec user process caused "exec format error"
```

**Comment by coadler** [comment]
We don't currently distribute ARM binaries, but we're working on it

**Comment by danhab99** [comment]
Bet. Close when ARM is supported.

**Comment by coadler** [comment]
https://github.com/cdr/code-server/issues/35 is currently tracking ARM releases. https://github.com/cdr/nbin/pull/7 is open to add ARM targeting support to our binary compiler

**Comment by sr229** [comment]
This has been highly requested in #35 btw, you can track what we have in place.

Next up is making the necessary modifications for code-server.

**Comment by coadler** [comment]
closing in favor of #35
