### ISSUE TITLE
Darwin (macOS) release stopped after 1.939-vsc1.33.1?

### ISSUE THREAD

**Issue by Tehnix** [cdr/code-server#748]
Latests releases have not included any Darwin (macOS) release, and seems to have been replaced with a musl release instead. This means that the latest release for macOS is 1.939-vsc1.33.1.

Is this intentional, or did something perhaps just go wrong in the release pipelines?

**Comment by nhooyr** [comment]
Definitely a bug, thanks for reporting. cc @kylecarbs

**Comment by code-asher** [comment]
https://github.com/cdr/code-server/releases/tag/1.1140-vsc1.33.1
