### ISSUE TITLE
Firefox Alt key not working in keybinds

### ISSUE THREAD

**Issue by deansheather** [cdr/code-server#749]
- `code-server` version: 1.1119-vsc1.33.1
- OS Version: Linux 4.19.36_1 x86_64
- Browser version: GNU IceCat 60.3.0esr 64-bit

## Description

Making a keybinding like `Ctrl+Alt+R` doesn't work. You can't type `Alt` into the create keybind input box, so clicking `Ctrl+Alt+R` will only result in `Ctrl+R` being displayed.

If something registers a keybind with `Alt` in it, it doesn't work either.

Strangely, using editor keybinds like `Alt+Up` or `Alt+Down` to move a line work properly (these show up in keybindings list). I tried to use `Ctrl+Alt+R` while focused on the editor, and it still didn't work.

## Steps to Reproduce

1. Go to keybinding settings
2. Edit some keybinding and try to set it to `Ctrl+Alt+R`
3. Notice that it shows `Ctrl+R` instead of what you'd expect

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
