### ISSUE TITLE
Command not found error

### ISSUE THREAD

**Issue by muhammadomais** [cdr/code-server#751]
- `code-server` version: code-server1.1119-vsc1.33.1-linux-x64.tar.gz
- OS Version: Ubuntu 18.04 x64 

## Description

When i try to run command 
code-server
I get an error command not found.
Running it as a root user on Digital Ocean

**Comment by coadler** [comment]
Could you provide the steps you took? This isn't a `code-server` bug.

**Comment by muhammadomais** [comment]
1- Create new instance of a server from droplet
2- Login as root
3- wget https://github.com/cdr/code-server/releases/download/1.1119-vsc1.33.1/code-server1.1119-vsc1.33.1-musl-x64.tar.gz
4- tar  xvfz code [Press tab]
5- cd code [Press tab]
6- code-server

When i try to run the code-server command i get the error command not found.

If i download following version then it works but not with the latest version
wget https://github.com/cdr/code-server/releases/download/1.939-vsc1.33.1/code-server1.939-vsc1.33.1-linux-x64.tar.gz

**Comment by coadler** [comment]
You need a `./` to run binaries in the current directory.

![image](https://chito.ge/6EuUCuR.png)

**Comment by muhammadomais** [comment]
Thanks for the help @coadler that fixed my issue

**Comment by TierGamerpy** [comment]
it doesn't work for me means i also have same error but i tried `./` but it doesn't work

**Comment by jsjoeio** [comment]
@TierGamerpy if you're having issues, please open up a separate bug report issue and we'll see how we can help!
