### ISSUE TITLE
Setup a Custom Systemd Service for code-server on Ubuntu 18.0.4

### ISSUE THREAD

**Issue by Josh-Uvi** [cdr/code-server#758]
Please I need help to setup a Custom Systemd Service for code-server on Ubuntu 18.0.4
Here is my code
[Unit]
Description=Code Server AutoStart
After=http://network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=/path/to/start/your/working/directory/inside/vscode
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Restart=on-failure

ExecStart=/path/to/codeserver/binary --allow-http --password=xxxxxxx cert=/path/fullchain.pem cert-key=/path/privkey.pem
[Install]
WantedBy=http://multi-user.target

But it doesn't work with the password. How can I improve this code to make it work? Also, I would like to add my letsencrypt certificate to secure it. Thanks!

**Comment by RyoshiKayo** [comment]
Your service file should look something like this:

```
[Unit]                                                            
Description=VSCode on the web pog                                 After=network.target                                                                                                                [Service]                                                         
User=kayo                                                         
Group=kayo                                                                                                                          WorkingDirectory=/home/kayo/coder                                 Environment="PATH=/home/kayo/coder"                               ExecStart=/home/kayo/coder/code-server -p 8443 --allow-http --no-auth                                                                                                                                 [Install]                                                         WantedBy=multi-user.target
```

**Comment by deansheather** [comment]
@RyoshiKayo your formatting appears broken in my browser, you might want to make sure your newlines are behaving correctly

**Comment by RyoshiKayo** [comment]
@deansheather thank you for pointing that out, I fixed the formatting 👍

**Comment by Josh-Uvi** [comment]
Thanks for your help @RyoshiKayo  how would you handle failure/restart with the systemd service script. Thanks

**Comment by RyoshiKayo** [comment]
If coder exits with a non-zero exit code then system should automatically restart the service. The name you use in commands is the same as the filename you saved in `/etc/systemd/system/coder-web.service`.

Start: `sudo systemctl start coder-web.service`
Stop: `sudo systemctl stop coder-web.service`
Enable on OS restart: `sudo systemctl enable coder-web.service`

Note: Once you save the service file you will need to reload the systemd daemon with `sudo systemctl daemon-reload`

**Comment by Josh-Uvi** [comment]
@RyoshiKayo I just noticed a bug. I tried to add my SSL Certificate and Key with --cert and --cert-key and it didn't work with the right path. Any suggestion why that is happening?

**Comment by Josh-Uvi** [comment]
![Screenshot 2019-06-17 at 17 09 05](https://user-images.githubusercontent.com/40158394/59619567-b8fcc680-9122-11e9-964f-21da3b4b8d36.png)
error preview

**Comment by RyoshiKayo** [comment]
The user you're running the service as doesn't have permissions to the letsencrypt files

**Comment by Josh-Uvi** [comment]
@RyoshiKayo thanks, solved it. I had to change the user permissions
- sudo chgrp -h {username} privkey.pem, 
- sudo chown -h {username} privkey.pem, 
- sudo chown -h {username} fullchain.pem , 
- sudo chgrp -h {username} fullchain.pem

because I disabled the root user, also I copied the certificates 
`sudo cp coder-server /etc/letsencrypt/live/your-website-name/fullchain.pem /bin/fullchain.pem` 
to the bin folder to ensure I have the right path.

**Comment by nhooyr** [comment]
If this still occurs, please feel free to reopen.
