### ISSUE TITLE
How to handle system dependencies in docker-compose.yml

### ISSUE THREAD

**Issue by drewcovi** [cdr/code-server#759]
## Description
For various use cases, local dependencies are required (nodejs, npm). To persist these, ideally we can still use the existing Dockerfile, but provide a custom set of instructions to the **command** parameter, so that on recreation these can be quickly re-installed.

It seems the entrypoint usage in the Dockerfile clobbers our ability to add additional commands.

Is guidance at this point to simply fork the Dockerfile? Or how are other folks handling system dependencies?

**Comment by 5hay** [comment]
I'm pretty sure this is not a clean way at all, but it's working for me. I have a script (install.sh) that'll be copied into the container after its creation and run. In that script I install nodejs and other tools.

I start the vscode container with another script (run.sh) that includes the copying and running of the install.sh script.

**Comment by deansheather** [comment]
Try out [Sail](https://github.com/cdr/sail), which should allow you to do what you need using Dockerfiles.

**Comment by drewcovi** [comment]
I'm a bit confused by Sail right now, only because my endgoal is to keep my server setup nimble, and portable. ideally this means that most of my setup can be housed in one docker-compose.yml and a series of `data-dir`s.

It seems the best solution would be if we could have an empty shell script that gets triggered during initial boot, or perhaps on `entrypoint`.

**Comment by Disane87** [comment]
I guess this question is related to my question #1023

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
