### ISSUE TITLE
editor.fontFamily Support

### ISSUE THREAD

**Issue by drewcovi** [cdr/code-server#760]
At present it doesn't appear that you can install a local font (Fira Code) and have it presented as an editor font in the browser.
```
"editor.fontFamily": "Fira Code",
"editor.fontLigatures": true
```
only converts the fonts to serifs (unknown font)

**Comment by deansheather** [comment]
Try:
```
{
    "editor.fontFamily": "'Fira Code', 'Droid Sans Mono', 'monospace', monospace, 'Droid Sans Fallback'",
    "editor.fontLigatures": true
}
```

Make sure that Fira Code is installed to the machine accessing code-server in the browser, not the server (as it's the client browser that renders the fonts). I don't have any issues using Fira Code with code-server.

**Comment by yw662** [comment]
There is an alternative way to let your browser use fira code fonts, as long as you can use user style.

* add this user style to the domain of code-server:
 `@import url(https://cdn.jsdelivr.net/gh/tonsky/FiraCode@1.206/distr/fira_code.css);`

**Comment by GJRTimmer** [comment]
@yw662 where would I make this change ?

**Comment by HenrikSolver** [comment]
@GJRTimmer Install the stylus extension in chrome and add a "style" for the url where you access code-server. In my case it is http://penguin.linux.test:8080 (I am running code-server in crostini on a chromebook). Add the line @yw662 suggests to the style.

**Comment by nhooyr** [comment]
Thank yo @HenrikSolver and @yw662 for answering

**Comment by SuperSandro2000** [comment]
If anyone is here for JetBrains Mono
````
    "editor.fontFamily": "JetBrains Mono, Consolas, 'Courier New', monospace",
    "editor.fontLigatures": true,
````

**Comment by HenrikSolver** [comment]
It seems that this trick doesn't work with 3.0.2.  Maybe it is caused by #1470 .

**Comment by nhooyr** [comment]
We have an open issue re this at https://github.com/cdr/code-server/issues/1374
