### ISSUE TITLE
Zen Mode Fullscreen Not working on Safari

### ISSUE THREAD

**Issue by drewcovi** [cdr/code-server#761]
- `code-server` version: **development**
- OS Version: Ubuntu

## Description
When toggling Zen mode (CMD K Z), an error shows in Safari when attempting fullscreen.

prefixing with webkitReqestFullscreen would likely resolve the issue:
https://www.w3schools.com/jsref/met_element_requestfullscreen.asp

## Steps to Reproduce

1. Keyboard Command CMD+K Z in Safari

**Comment by sr229** [comment]
This is a upstream bug so please open this in Microsoft/vscode with [web] prefixed.
