### ISSUE TITLE
i want to remove menu item on ide toolbars, what should I do?

### ISSUE THREAD

**Issue by xmpilot** [cdr/code-server#763]
## Description
i want to remove menu item on ide mainpage, for example: the menu item "File", "Edit" need to be delete.  What should I do? thanks!

**Comment by deansheather** [comment]
If you want to hide the entire bar, there's a command `View: Toggle Menu Bar` which can also be found under View > Appearance.

If you're looking to hide a few items on the menu bar so the user can't access their functionality, every function in the menu bar also has a command that can be assigned to a keyboard shortcut or accessed from the command palette, which means hiding the menu bar items won't actually disable their functionality.

If you understand the risks but still want to hide them, I don't think that VS Code lets you do this.

**Comment by xmpilot** [comment]
@deansheather I've found a solution. Thank you for your advice.
