### ISSUE TITLE
How can I access the local server when I run ng serve on Corder -Digital Ocean 

### ISSUE THREAD

**Issue by muhammadomais** [cdr/code-server#769]
How can I access the local server which run 
`ng serve` or `ionic serve` commands

I have deployed coder with lets encrypt but
when i run ng serve i am not able to access the local serve 
I looked for some reference or tutorial which can 
help me with that but was not able to find some.
I have opened all incoming and out going ports as well but not
able to access that. Can you guys help me with that.

**Comment by roberthmiller** [comment]
You will need to specify the `--host` argument like so: `--host=0.0.0.0` and then go to port 4200. As a note, you have to allow port 4200 through your firewall within Digital Ocean.

**Comment by muhammadomais** [comment]
@roberthmiller Thanks for the reply. That resolved the issue.
