### ISSUE TITLE
The cache is not cleared after golang debugging.

### ISSUE THREAD

**Issue by andreyvoronko** [cdr/code-server#771]
- `code-server` version:1.1119-vsc1.33.1
- OS Version: linux

## Description

When you start debugging dalve with golang extension, a folder /home/user/.cache/go-build/..... is created. 
After end debugging the folder is not cleared.

**Comment by sr229** [comment]
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.
