### ISSUE TITLE
selfhost preview feature

### ISSUE THREAD

**Issue by runningman84** [cdr/code-server#772]
## Description

I saw a video where a user could use some preview feature in order to access a local running app on port 3000 using some special vhost name. Is this also possible using the official docker image? I have not found any button for this in the IDE.

My use case is running multiple developer workspaces within a kubernetes cluster. I could also route other virtual hosts to the same container.

**Comment by code-asher** [comment]
We had a service that would do this back when we were running a hosted code-server platform but it wasn't part of the IDE itself. There's tracking for that feature here: https://github.com/cdr/code-server/issues/512

Although it wouldn't be too hard to implement outside of the IDE using Nginx or something.
