### ISSUE TITLE
Are there any key bindings for the open file (Ctrl+o)  dialog once it's open?

### ISSUE THREAD

**Issue by mattford63** [cdr/code-server#775]
For the life of me I can't figure out how to go up a directory or change root via the keyboard....

**Comment by Merith-TK** [comment]
Ctl+k O

**Comment by mattford63** [comment]
Sorry, to be clear, I mean once I'm in it.  I can filter but not do much else...

**Comment by Merith-TK** [comment]
Look at the default key bindings of vscode

**Comment by mattford63** [comment]
I did try...I looked for anything to do with remoteFileDialog.  Nothing leaps out at me....

It's not like a local vscode running file open dialog so this is something coder specific I wonder?

**Comment by Merith-TK** [comment]
Oh. I have not found a way to open a specific file except to symlink the file to the current working directory

**Comment by sr229** [comment]
Ctrl K+O works now so I'll go mark this as closed.
