### ISSUE TITLE
SSH FS extension not working at all

### ISSUE THREAD

**Issue by agent306** [cdr/code-server#776]
SSH FS extension from Kelvin is not working on a self-hosted setup. I have checked and tried that an ssh connection in-fact is possible from the terminal, but I get no response what-so-ever when I click on "connect" or "reconnect" to server

**Comment by muammar** [comment]
Did you solve this?

**Comment by raulvasquez** [comment]
I am this issue as well. Any solutions?

**Comment by sr229** [comment]
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.

**Comment by code-asher** [comment]
It appears to error with "Extension 'SSH FS' failed to update workspace
folders: Error: Workspace folders from different providers are not
allowed in the same workspace." I verified that VS Code does not do this
although I'm not certain yet if it's a bug with web or code-server.

**Comment by sr229** [comment]
@code-asher checking this might be a platform issue, web isn't exactly supporting all of the extensions yet. I suggest forwarding this to Microsoft.

**Comment by nhooyr** [comment]
Works fine now. If this is still a problem, please feel free to reopen.

**Comment by nhooyr** [comment]
Nvm, confirmed this is a bug;.

**Comment by nhooyr** [comment]
@cmoog Can you add https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs

We're missing it now.

**Comment by cmoog** [comment]
Done 👍

**Comment by nhooyr** [comment]
@cmoog Did you confirm it works?

**Comment by hluker** [comment]
> It appears to error with "Extension 'SSH FS' failed to update workspace folders: Error: Workspace folders from different providers are not allowed in the same workspace." I verified that VS Code does not do this although I'm not certain yet if it's a bug with web or code-server.

Still getting same error.

**Comment by code-asher** [comment]
Yeah this is unfortunately still a problem with 3.2 but it should be fixed in the next release!

**Comment by nhooyr** [comment]
Should be good then in the latest versions.
