### ISSUE TITLE
Failed to load message bundle. See console for detail

### ISSUE THREAD

**Issue by ZyairYH** [cdr/code-server#777]
- `code-server` version: docker image latest
- OS Version: ubuntu

## Description
when debug get
![image](https://user-images.githubusercontent.com/19263658/59557605-721eac00-9010-11e9-9bcb-89348b8d5179.png)

**Comment by deansheather** [comment]
Could you please share with us the console output?

**Comment by cortopy** [comment]
@ZyairYH how did you solve this issue? I'm experiencing it now

**Comment by sr229** [comment]
Reopening since we need to investigate this.

**Comment by sr229** [comment]
@cortopy share your console logs for us, thanks!

**Comment by cortopy** [comment]
This has been puzzling me, because the message obviously says I should check the console, but I can't find any message anywhere.

The debug console is empty and so is the code-server process itself

Any idea where I could look to get some debug info?

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
