### ISSUE TITLE
Log out button

### ISSUE THREAD

**Issue by vwxyzjn** [cdr/code-server#778]
## Description

I couldn’t find a way to logout of the code server once logged in to the code-server

The following docker command was used to host the code-server

```bash
docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth
```

This functionality is kind of important to me as sometimes I have to use different machines temporarily. Is there by chance a way for me to logout? Thanks a lot.

**Comment by deansheather** [comment]
We currently don't have a logout mechanism that I know of.

In the meantime, you can logout of code-server by deleting the `password` cookie. This cookie should also be deleted when you restart your browser as it's a session cookie (at least on my machine). If you want to logout everywhere, you can change the server password and every device will prompt you to login again.

**Comment by vwxyzjn** [comment]
Closing the browser indeed log me out of the code-server. Thanks!

**Comment by bbrendon** [comment]
For me, closing Chrome does not logout so instead I'm using an Incognito browser.

**Comment by bwnstck** [comment]
deleting the cookie helps ... but why not implementing a logout feature?

**Comment by nhooyr** [comment]
Why do you need to log out?

**Comment by nhooyr** [comment]
Sorry I guess that's a dumb question. I can see the security advantages for sure and it really doesn't make sense we don't have this so I'm reopening.

**Comment by nhooyr** [comment]
Perhaps `File -> Log Out`?

**Comment by vwxyzjn** [comment]
@nhooyr Thats how I imagined it originally 😆. I guess I do have a use case. As a Teaching Assitant, sometimes I get annoyed with students’ editor and wanted to do some formatting using vscode server but then want to log out.

**Comment by bwnstck** [comment]
> Perhaps `File -> Log Out`?

I would put somewhere at the top-level, so people can find it directly. Under or above GoHome makes sense to me :) 

I attached a screenshot so folks can imagine the menustructure! 

![Proposal](https://user-images.githubusercontent.com/37471898/106209728-d088a600-61c5-11eb-93cf-5173d1ede202.png)

**Comment by susverwimp** [comment]
@nhooyr A possible use case would be that the code server is behind a oauth2 proxy server. To access the code server public url, one would need to login with an oauth2/oidc identity provider and a customizable logout button could be configured to remove the code-server-session/idp-session so that a user should login again with the idp before they can access the code-server again.

This is something I did before with https://github.com/oauth2-proxy/oauth2-proxy

**Comment by zhz** [comment]
> @nhooyr Thats how I imagined it originally 😆. I guess I do have a use case. As a Teaching Assitant, sometimes I get annoyed with students’ editor and wanted to do some formatting using vscode server but then want to log out.

Same to me. I use code-server as a portable dev env while teaching in public classrooms . It's necessary to logout manually, closing browser does not work.

**Comment by jsjoeio** [comment]
Thanks for sharing that with us @zhz! I was waiting for #2648 to get merged in before picking this up so that we could make sure to add the proper e2e tests when this feature is added. Hoping to get to this soon!

**Comment by binaryfire** [comment]
+1 for this. Would be great to have as an option
