### ISSUE TITLE
Incorrect reporting in the terminal when --port 0 is used

### ISSUE THREAD

**Issue by PEERCRED** [cdr/code-server#779]
- `code-server` version: `v1.1156-vsc1.33.1`
- OS Version: Ubuntu 18.04

## Description

When started with `--port 0` (`-p 0`) option, `code-server` does not show the actual port the kernel allocated for it:
```
INFO  Started (click the link below to open):
INFO  http://localhost:0/
```
Compare with, for example, python simple http server:
```
$ python3 -m http.server 0
Serving HTTP on 0.0.0.0 port 41051 (http://0.0.0.0:41051/) ...
```

## Steps to Reproduce

Start `code-server` with `-p 0` option.

**Comment by RyoshiKayo** [comment]
Port 0 isn't actually a valid port number, you need to run it on either port 80 (If another Webserver isn't running on the same host) or anything from 1024-49151.

Also the Python example you showed is running on port 41051, not 0.

**Comment by deansheather** [comment]
Port 0 is usually translated to a random port on the machine, and that's the case in this instance. You can verify this by running code-server on port 0 and checking netstat for active listeners, you should see code-server listening on a random port.

It seems really easy to get the port from a node http server, so I'll open a PR in a sec.
