### ISSUE TITLE
No Python in Docker

### ISSUE THREAD

**Issue by gerroon** [cdr/code-server#783]
Hi

It seems like the docker container does not contain any Python interpreter. It would be nice at least ther minimal 3.7 is included in the container.

thanks

**Comment by deansheather** [comment]
It's very simple to install a Python interpreter using the apt-get command:
```
sudo apt-get update
sudo apt-get install python3
```

**Comment by gerroon** [comment]
Hi, sure I already installed it, just that you know it is not permanent

**Comment by deansheather** [comment]
Since code-server doesn't require Python to run, it's probably best for us to not include it in the image to keep the image's size down. If you need Python in the image, I would suggest making your own image.

**Comment by gerroon** [comment]
makes sense ,t ahnks

**Comment by Troubadoure** [comment]
Incase anyone else is having a similar issue I used this for my Dockerfile

```
FROM codercom/code-server:latest

USER root
RUN sudo apt-get update && sudo apt-get -y install python3 python3-pip
```

and built the image.

**Comment by danionescu2007** [comment]
the docker image provides nicely the option to set a sudo password. Opening the terminal in the UI of code-server and issuing: `sudo <command>` is more than convenient, IMHO.
Nice work people. Keep up the good work!
