### ISSUE TITLE
I got an error when trying to open a fiel with encoding GB2312

### ISSUE THREAD

**Issue by Kiris-tingna** [cdr/code-server#784]
## Description
I an runing on my server which hoding a poject. And there are some chinese comment within the code.  I am trying to set the file.encoding = gb2312 or gb18030 or some others, after the set, I open the file with on error: unknown encoding "gb12312" or unknown encoding "gb18030"

## Related Issues
It seems only utf-8 works.

**Comment by sr229** [comment]
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.
