### ISSUE TITLE
Incompability in the network stack between Docker and KaOS

### ISSUE THREAD

**Issue by ShalokShalom** [cdr/code-server#785]
Since no documentation says anything about, I ask here: 

Does your test instance intent to provide software installation support?

Since it fails to reach the Ubuntu servers

**Comment by deansheather** [comment]
Could you please clarify what you meant by "test instance"? Do you mean the docker command in teh README?

**Comment by ShalokShalom** [comment]
Yep.

**Comment by deansheather** [comment]
If the docker container can't reach Ubuntu's repositories, it's likely an issue with your network configuration as I'm able install software just fine through `apt-get` and the default repositories in the image.

**Comment by ShalokShalom** [comment]
Well, my network configuration is totally fine with absolutely everything. So, I guess there is a chance that the docker instance which you provide is incompatible with my system. How to succeed?

**Comment by sr229** [comment]
It's not *our* Docker instance, its yours, and to be fair, your Docker runtime seems to be denied to access any network, check your iptables configuration. @ShalokShalom
