### ISSUE TITLE
Is rg supposed to kill my CPU?

### ISSUE THREAD

**Issue by ShalokShalom** [cdr/code-server#786]
![Screenshot_20190617_080755](https://user-images.githubusercontent.com/6344099/59582051-47e3f180-90d7-11e9-886c-121d9de5ed4e.png)

Test Instance: 

```docker run -it -p 127.0.0.1:8443:8443 -v "${PWD}:/home/coder/project" codercom/code-server --allow-http --no-auth```

**Comment by deansheather** [comment]
Try setting `search.followSymlinks` to `false` in your `config.json`: https://github.com/Microsoft/vscode/issues/35659

**Comment by ShalokShalom** [comment]
This is the test instance. Do I can change it there as well? Will try it on my own instance

**Comment by deansheather** [comment]
You need to set that configuration option on whichever code-server has this problem.

**Comment by ShalokShalom** [comment]
Would this not run in any test instance the same, or is there something I dont understand about Docker?

**Comment by sr229** [comment]
It should work as-is @ShalokShalom

**Comment by fbartels** [comment]
@sr229 its https://nicolargo.github.io/glances/
