### ISSUE TITLE
Golang syntax highlighting is not working after Microsoft Go extension installed

### ISSUE THREAD

**Issue by morningspace** [cdr/code-server#788]
- `code-server` version: 1.1156-vsc1.33.1
- OS Version: Ubuntu 18.04.2 LTS

## Description

I want to use code-server for my golang programming. Before I install the [Microsoft Go extension (i.e. ms-vscode.Go)](https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go), it looks all good if I new a .go file w/ something put into it. I can see the syntax highlighting is working. However, after I install the extension, it looks I cannot see the syntax highlighting anymore.

## Steps to Reproduce

1. Create a .go file then check the syntax highlighting, and it works
1. Install the Microsoft Go extension
1. Check the .go file again, and syntax highlighting is gone

**Comment by bitterpilot** [comment]
I had a similar problem this morning. Reloading the browser after installing the Go extension helped the issue for me.

**Comment by morningspace** [comment]
Oops... that seems to be the best workaround for now... I didn't realize that... thanks a mil :-)

**Comment by roberthmiller** [comment]
I think that when installing extensions, you have to reload the browser. Am not entirely sure why though.

**Comment by code-asher** [comment]
Currently a browser reload is required after installing extensions. It's possible that v1 didn't correctly report that a reload was required? v2 will say "reload required" in place of the installation button.
