### ISSUE TITLE
Support Browser Preview Extensions

### ISSUE THREAD

**Issue by baoduy** [cdr/code-server#789]
When running the application in docker. Exposing 1 more port for app debugs quite challenge instead we can browse the debug app via Browser Preview extension.

Hope this will be available soon.

Thanks
Duy

**Comment by mohammedri** [comment]
@baoduy did you have an alternative way to solve this?

**Comment by baoduy** [comment]
@mohammedri, yes I upload the extension to the server manually and instal it from the file. The issue shall be closed.
