### ISSUE TITLE
 Error from the extension host: timed out

### ISSUE THREAD

**Issue by Dj-jom2x** [cdr/code-server#793]
Error from the extension host: timed out

**Comment by deansheather** [comment]
Could you please provide us with log output from the output tab in vscode?

**Comment by Dj-jom2x** [comment]
it just happened randomly.. and vs code is up 13 days or so ... I download the latest and run it again forever seems fine now .. but .. kindly tell me how to start extension host service? because if it's down it means its dead right?

**Comment by Dj-jom2x** [comment]
grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr why always this happened.. like we cant do **** about it zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz all extension doesnt work all became plain text whyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by sr229** [comment]
Since you are not willing to help us out why code-server is not working on your system, I will close this off. Please elaborate further what's the issue by providing log files then I'll reopen it.
