### ISSUE TITLE
Use default port on 8080 instead of 8443.

### ISSUE THREAD

**Issue by grant** [cdr/code-server#796]
It would be great if the default port and instructions were for PORT 8080 instead of 8443.

This is more standard in practice, and allows for easier integration with tools like Google Cloud Run.

https://github.com/cdr/code-server/blob/master/Dockerfile#L51

**Comment by deansheather** [comment]
I'm not familiar with Google Cloud Run, but how difficult is it to change the port it uses from 8080 to 8443?

**Comment by grant** [comment]
It's not possible to change the port for Cloud Run.
I'm currently looking at ways to get around that.

**Comment by deansheather** [comment]
Could you try wrapping code-server in a shell script that runs it with `-p $PORT`?

**Comment by grant** [comment]
Yeah, I'm just not sure how to create wrapper scripts to do that.

**Comment by deansheather** [comment]
Try making a Dockerfile with the following and push it to Google's container registry:
```Dockerfile
FROM codercom/code-server

EXPOSE 8080
ENTRYPOINT ["dumb-init", "code-server", "-p", "8080"]
```

It should solve your specific issue. It's a shame that Google Cloud Run doesn't seem to permit changing the arguments provided to the container, as this would be easily solved by adding `-p 8080` to the launch parameters.

**Comment by grant** [comment]
I think you just can't configure the port, other args are fine.

I'll have to debug with my colleague later this week.
I'm getting ERR_TOO_MANY_REDIRECTS, which seems like my issue.

Would be cool to have a "Deploy to Google Cloud" button or some instructions for this project.

**Comment by deansheather** [comment]
If you're getting too many redirects error, add `--allow-http` to that args list in ENTRYPOINT.

**Comment by yw662** [comment]
but you can easily change the port using `-p`. Why would `8080` be a better default value?

*I would rather suggest `0xc0de`, or `49374`, as default port, if possible :-)*

**Comment by deansheather** [comment]
The point that the OP brought up for changing the port to 8080 was that
it's a more common port than 8443. We won't be changing the default port
from 8443 as it's very easy to change it like you said.

**Comment by code-asher** [comment]
Default port is 8080 now. :confetti_ball:
