### ISSUE TITLE
Stuck on grey screen due to websocket error 500

### ISSUE THREAD

**Issue by Burn-E99** [cdr/code-server#797]
- `code-server` version: 1.1156-vsc1.33.1
- OS Version: Ubuntu Server 16.04 on private VPS

## Description

Installed code-server a couple days ago and finally went around to getting the reverse proxy working so I can use it on a semi-restricted network (network blocks direct IP:port access). Followed the docs for setting one up using Apache, and it somewhat works. The login page shows up and is usable, but once logged in, it sits on a grey screen repeatedly spitting out `websocket connection to 'ws://coder.mydomain.com' failed: Error during websocket handshake: Unexpected response code: 500`. Direct access over IP:port works, but the Apache reverse proxy only seems to partially work.

This happens in latest version of desktop chrome.

## Steps to Reproduce

1. Download the binary and run it on server with --allow-http
2. Configure Apache according to docs
3. Attempt to access via chrome
4. Enter password and your at a grey screen, constantly getting a websocket 500.

Let me know if more details are needed, such as what my configs are currently set at.

**Comment by SimonLindberg98** [comment]
I have the same issue.

**Comment by grant** [comment]
Is there any support for alternatives (like long-polling / socket.io) rather than web sockets? Some environments don't support websockets.

**Comment by Mrgove10** [comment]
Same issue, even whit HTTPS

**Comment by deansheather** [comment]
This is likely caused by a misconfigured reverse proxy. I'm reviewing the reverse proxy documentation and rewriting parts that aren't clear or incorrect with the current version right now.

**Comment by Mrgove10** [comment]
i was not using a reverse proxy in my case

**Comment by deansheather** [comment]
@Mrgove10 Does anything appear in the code-server log or browser log that could be helpful?

**Comment by code-asher** [comment]
If anyone still experiences this on v2 lemme know.
