### ISSUE TITLE
Add apple-touch-icon for ipad webapp

### ISSUE THREAD

**Issue by el** [cdr/code-server#802]
After the release of the new iPadOS, code-server works pretty well on the iPad.

Configuring the web app for the ipad makes sense now:

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

Here is how it looks right now:
![ECA17C4A-CC37-4E4B-9EAB-1E8F32601A10](https://user-images.githubusercontent.com/1488164/59969866-498f3880-9561-11e9-9e84-d64c79d0012b.jpeg)

**Comment by Revengervn** [comment]
Also, another important point: 
Coder's copy,cut and paste doesn't work on the ipadOS safari which is weird. 
Theia and other VS code-based IDE work perfectly. 
I spent the entire day trying to figure out why but couldn't.

**Comment by code-asher** [comment]
Was added by https://github.com/cdr/code-server/pull/1060.
