### ISSUE TITLE
ms-vscode.Go auto-suggestion went wrong: provider FAILED

### ISSUE THREAD

**Issue by xtlsoft** [cdr/code-server#803]
- `code-server` version: 1.1156-vsc1.33.1
- OS Version: Ubuntu 18.04, Docker (Dockerfile: https://github.com/xtlsoft/dev-environment/blob/master/Dockerfile)
- Extension: ms-vscode.Go

## Description

The auto-suggestions are not avaliable (with all tools installed).
ExtHost Log:
```
[2019-06-23 16:47:30.001] [exthost] [error] [ms-vscode.Go] provider FAILED
[2019-06-23 16:47:30.001] [exthost] [error] undefined
```
Chrome console:
![image](https://user-images.githubusercontent.com/16159830/59973864-944b9780-95d7-11e9-8d16-a091fb534cb4.png)

## Steps to Reproduce

1. Build my image
2. Start editing a Go file
3. Something goes wrong

**Comment by deansheather** [comment]
Does this occur if you try it in the container image we supply?

**Comment by xtlsoft** [comment]
In your image, I didn't even able to use code hightlighting.

I know it may be my problem (I'm in China and have GFW enabled), so I built another image myself.

**Comment by deansheather** [comment]
I'm not having any issues with `ms-vscode.go` running locally, so maybe it's caused by your configuration or mounting extensions into the container. Try with this Dockerfile (after changing the mirrors) and this command to make sure nothing's mounted in:
```Dockerfile
FROM codercom/code-server

RUN sudo apt-get update && sudo apt-get install -y golang
ENV GOPATH /home/coder/go
ENV PATH $GOPATH/bin:$PATH
RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
```

```
docker run -it --rm --name cdr -p 8443:8443 code-server-local --allow-http --no-auth
```

Open it in incognito mode, install the extension and reload.

**Comment by deansheather** [comment]
@xtlsoft bump

**Comment by xtlsoft** [comment]
Thank you!

Sorry for not replying because I wasn't likely to check GitHub very often.

I'll try this when I come back and this could be closed.
