### ISSUE TITLE
Service-File - GIT Extension don't exist any more

### ISSUE THREAD

**Issue by kulle418** [cdr/code-server#806]
I want to start the code server by default with the service file.
Everything works fine, but if I want to push the code from the server to  the repo, this issue would be displayed. 
![image](https://user-images.githubusercontent.com/52175164/60042166-5c1e8480-96bd-11e9-9603-028638401d52.png)

So I disable the service file and start the server from the console and i can push the code to the repo. I thing I don't have the right parameters at the service file. My service file looks like this: 

![image](https://user-images.githubusercontent.com/52175164/60042356-d18a5500-96bd-11e9-92da-a6fb72d7c9aa.png)

I believe I need to put a path to the git configuration but I don't know which parameter I have to take. thank u for your help

**Comment by aptalca** [comment]
When you start it from command line, you start it with your linux user, and the apps accesses your user's environment where the username and email are set.

But your systemd is starting it as root and that info is not set for the root user

**Comment by kulle418** [comment]
Thank you, but I work in both senario with the root user and I set the global git varibales for the root user. Can you find any trouble with my service file?
