### ISSUE TITLE
Run Code Server on a Server

### ISSUE THREAD

**Issue by abubakar-bilal** [cdr/code-server#807]
I've a server, where my projects are deployed and accessible via urls. What I want to do is, to install code server on my server. Then run code server on my server and access it via browser on my local machine. I don't want to run code server OR sshcode on my local machine.

I also want to access it with some specific url e.g. https://mysite.com/ide

Please let me know is there any way to achieve this?

And what about team access to same project? Do you have team collaboration OR multiple users accessing same project and doing their changes?

**Comment by roberthmiller** [comment]
You don't have to run code server on your local machine for this. You would access it via a browser. Code Server would simply listen on the port that you specify. Accessing the machine via ssh(code) is highly recommended.

**Comment by deansheather** [comment]
sshcode is an option that's available for you, but it's definitely not the only way. We have guides in the `doc/` directory in our repo which should help you with setting up code-server on your own server securely.

At the moment, you can't currently run code-server on a webserver mounted at a non-root path because of a bug: #670 #722 

Regarding collaboration and multiple-users (working on same project or working on different projects through a single code-server instance), this is currently not supported but something we're tracking: #33.

**Comment by abubakar-bilal** [comment]
@deansheather @code-asher Can you please let me know any deadline about team collaboration feature in code-server? It would be good to have an estimate to use this for our product.

Thanks alot.

**Comment by coadler** [comment]
Team collaboration is not planned in the near future and has no deadline or estimate

**Comment by abubakar-bilal** [comment]
@coadler  Any idea if I can run vs live share with code-server in some way?

**Comment by coadler** [comment]
It's not open source so we cannot provide it on our marketplace

**Comment by abubakar-bilal** [comment]
@coadler  So right now, we cannot use code-server in a scenario where we need teams to collaborate on code via IDE? But it's definitely very good using in single user case.

**Comment by coadler** [comment]
Unfortunately there is no first class support for collaboration, although it seems some people have had live share working in #33

**Comment by yw662** [comment]
what if you and your team just open multiple browser pages of code-server site ?

I am not quite sure how it would work, but it seems to be somehow usable.

**Comment by deansheather** [comment]
@yw662 It doesn't work. You'll run into problems if multiple browsers access a code-server instance simultaneously, especially if they are working on the same files.

**Comment by roberthmiller** [comment]
Curious, is there anything like `sync.Mutex` for files? This might allow for this to work.. Not entirely sure though.

**Comment by coadler** [comment]
There's [flock](https://linux.die.net/man/1/flock) but the IDE would have to do a lot more than just lock files for writing, such as conflict resolution and the like. It's definitely a beast all of its own.

Going to close since it seems like the original issue was solved.

**Comment by roberthmiller** [comment]
@coadler I know that vscode has some built-in file resolution when the copy on disk does not match the one in the editor. What are your thoughts about that? Not sure if as an unexpected side effect, code-server has this functionality.
