### ISSUE TITLE
Can i make it work with no internet?

### ISSUE THREAD

**Issue by GAZ082** [cdr/code-server#808]
Hey. I want to use a linux VM that can have either internet or local connection, not both at the same time (this is how the network is configured and I cannot use the Bridge mode with internet).

The script does some checks and downloads stuff from the internet, i wonder if there is a way to activate it locally, let it download all the stuff it wants, and then re-enable the local connection between the host and the VM.

Thanks.

**Comment by roberthmiller** [comment]
if I were you, I would fork the repo and remove this the things that use the internet so you can use this on your local network without internet access.

**Comment by deansheather** [comment]
I just downloaded the code-server binary onto a machine that's never had VSCode or code-server before, unplugged the ethernet before running it and it worked fine. Other than downloading extensions (which obviously won't work without a working internet connection), what features aren't working for you while offline?

**Comment by GAZ082** [comment]
> I just downloaded the code-server binary onto a machine

So easy. I had used the script because was the "easiest" thing to get started but downloading the binary is the true easiest way, hah.

Thanks a lot.
