### ISSUE TITLE
`fork: Cannot allocate memory` on aws t2.micro instance.

### ISSUE THREAD

**Issue by yw662** [cdr/code-server#809]
- `code-server` version: v1.1156-vsc1.33.1
- OS Version: aws, amazon linux, irrelevant

## Description

OK, I know t2.micro is not suggested, but it has 1gb memory. :-)
Running code-server on t2.micro result in `fork: Cannot allocate memory`.

## Steps to Reproduce

1. run code-server on aws ec2 t2.micro
1. try doing sth. now :-)

**Comment by roberthmiller** [comment]
This is a known problem due to the limited amount of resources that the t2.micro provides.

**Comment by deansheather** [comment]
We're working on reducing the memory footprint of our code-server binaries.

**Comment by coadler** [comment]
Adding swap will let you run code server on 1gb or 512mb vms

**Comment by yw662** [comment]
@coadler good idea. I tried it, everything works well (at least for now). I noticed that it requires at least 1GB free swap space to work. I allocated a 4GB swap file for it. It works.

Very much thanks for the idea.

It is a t2.micro instance with EBS gp2 SSD storage (everything within free tier), FYI.
