### ISSUE TITLE
multiple code-server by one domain

### ISSUE THREAD

**Issue by zengbin3013** [cdr/code-server#810]
I want to open multiple code-server, access by one domain name and different path,example,a.com/code1;a.com/code2, can I enable code-server to support custom domain access path,or custom path prefix

**Comment by sr229** [comment]
At the moment its not possible since we still have issues open about the server breaking when used in a non`/` type of route.

**Comment by deansheather** [comment]
Issue: #670 PR: #722

**Comment by deansheather** [comment]
Closing in favor of #670.
