### ISSUE TITLE
dockerhub repo description

### ISSUE THREAD

**Issue by huahuayu** [cdr/code-server#812]
hi, I just visit code-server docker hub page, there's no description there, please add it.
![image](https://user-images.githubusercontent.com/1725060/60246360-1b0eb600-98f1-11e9-954a-7dc6c90d75d0.png)

**Comment by sr229** [comment]
I don't think that's an issue, keep in mind most of the people have heard of code-server here and not from DockerHub.

**Comment by code-asher** [comment]
I put a link to the GitHub in the overview.
