### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by abubakar-bilal** [cdr/code-server#814]
I have major concerns of memory. Let's say I've a server with 2GB memory. I ran code-server for one of my 10 projects. And my free memory went down to 400MB almost. Then I ran code-server for my second project. So my free memory went down to 0MB almost and second code-server process exited by saying cannot allocate memory.

What you guys say on this issue? Can I use code-server in my server for let's say I've 5 projects. and I wanna use IDE for all projects.

**Comment by abubakar-bilal** [comment]
@sr229 I need your expert opinion on this.

**Comment by deansheather** [comment]
You could just use a single code-server instance for all of your projects, and change folder every time you want to work on a different project.

**Comment by abubakar-bilal** [comment]
Let's say I've a shared server, where different users have their projects hosted. And I want everyone to have access only to their projects. And they can open their projects via IDE? Then is it doable using code server?

**Comment by deansheather** [comment]
In that case, you would need separate instances of code-server.

You might be able to squeeze 2 code-server instances into 2GB of RAM if you add a little bit of swap, but if you add enough swap for 10 instances of code-server the performance will likely be greatly reduced.

**Comment by abubakar-bilal** [comment]
Makes sense. thanks alot.
