### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by kasuganosora** [cdr/code-server#818]
INFO  http://localhost:8443/
INFO   
WARN  stderr {"data":"(node:19) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
INFO  Connected to shared process
INFO  WebSocket opened / {"client":1,"ip":"172.17.0.1"}
INFO  Starting shared process [1/5]... {"error":"Exited with null"}
WARN  stderr {"data":"(node:265) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
INFO  Starting shared process [2/5]... {"error":"Exited unexpectedly"}
WARN  stderr {"data":"(node:291) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
WARN  stderr {"data":"Uncaught Exception:  { Error: spawn ENOMEM\n    at ChildProcess.spawn (internal/child_process.js:366:11)\n    at spawn (child_process.js:538:9)\n    at /src/packages/server/out/cli.js:259:2339\n    at /src/packages/server/out/cli.js:259:2295\n    at /src/packages/server/out/cli.js:504:22829\n    at /src/packages/server/out/cli.js:504:23213\n    at /src/packages/server/out/cli.js:504:24010\n    at FSReqWrap.oncomplete (fs.js:155:5) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }\n"}
INFO  Connected to shared process
INFO  Starting shared process [1/5]... {"error":"Exited with null"}
WARN  stderr {"data":"(node:346) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
INFO  Starting shared process [2/5]... {"error":"Exited unexpectedly"}
WARN  stderr {"data":"(node:388) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
WARN  stderr {"data":"Uncaught Exception:  { Error: spawn ENOMEM\n    at ChildProcess.spawn (internal/child_process.js:366:11)\n    at spawn (child_process.js:538:9)\n    at /src/packages/server/out/cli.js:259:2339\n    at /src/packages/server/out/cli.js:259:2295\n    at /src/packages/server/out/cli.js:504:22829\n    at /src/packages/server/out/cli.js:504:23213\n    at /src/packages/server/out/cli.js:504:24010\n    at FSReqWrap.oncomplete (fs.js:155:5) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }\n"}
INFO  Connected to shared process
INFO  Starting shared process [1/5]... {"error":"Exited with null"}
WARN  stderr {"data":"(node:433) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
INFO  Connected to shared process
WARN  stderr {"data":"Uncaught Exception:  { Error: spawn ENOMEM\n    at ChildProcess.spawn (internal/child_process.js:366:11)\n    at spawn (child_process.js:538:9)\n    at /src/packages/server/out/cli.js:259:2339\n    at /src/packages/server/out/cli.js:259:2295\n    at /src/packages/server/out/cli.js:504:22829\n    at /src/packages/server/out/cli.js:504:23213\n    at /src/packages/server/out/cli.js:504:24010\n    at FSReqWrap.oncomplete (fs.js:155:5) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }\n"}
INFO  Starting shared process [1/5]... {"error":"Exited with null"}
WARN  stderr {"data":"(node:459) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
WARN  stderr {"data":"Uncaught Exception:  { Error: spawn ENOMEM\n    at ChildProcess.spawn (internal/child_process.js:366:11)\n    at spawn (child_process.js:538:9)\n    at /src/packages/server/out/cli.js:259:2339\n    at /src/packages/server/out/cli.js:259:2295\n    at /src/packages/server/out/cli.js:504:22829\n    at /src/packages/server/out/cli.js:504:23213\n    at /src/packages/server/out/cli.js:504:24010\n    at FSReqWrap.oncomplete (fs.js:155:5) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }\n"}
INFO  Connected to shared process
INFO  Starting shared process [1/5]... {"error":"Exited with null"}
WARN  stderr {"data":"(node:485) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
INFO  Connected to shared process
INFO  Starting shared process [1/5]... {"error":"Exited with null"}
WARN  stderr {"data":"(node:531) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:782:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:607:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:784:10)

**Comment by deansheather** [comment]
There are ENOMEM errors in the output which means that code-server has run out of RAM. Try adding swap to your server so it can go over by a bit.
