### ISSUE TITLE
Dragging tabs causes Coder to crash in Chrome app mode on MacOS

### ISSUE THREAD

**Issue by KitKat7** [cdr/code-server#820]
- `code-server` version: 1.1156-vsc1.33.1
- OS Version: Ubuntu 18.04.2 LTS
- Client Info: macOS 10.14.5 + Chrome 75.0.3770.100

## Description

Drag the tabs in `Coder` (Chrome app mode) will cause the `Coder` crashing.

But if it is not in the `Chrome app mode` (normal tab in `Chrome`) or some tabs like `Welcome` or new file without saving, dragging will not cause crashes.
This problem does not appear in `sshcode`, which seems to directly open in the `Chrome app mode`.

## Steps to Reproduce

1. Start `code-server` on the remote server.
2. Enter the address of the server locally into `Chrome` if not installed; otherwise, open the `Coder` Chrome app directly, then jump to 4.
3. Click the top right three-dot button in `Chrome`, then click `Install Coder...` if not installed before, or `Open in Coder` otherwise.
4. Open any remote file in the `Coder`, and try to drag that tab, the `Coder` will crash.

**Comment by CN-Ping** [comment]
Dragging files in the file tree also crashes the whole app. 
To create an app short cut I did:
- Open the code server in Chrome
- Three dot menu -> More tools -> Create shortcut (check open as window)
- Dragging any file in file panel crashes immediately.

**Comment by garbage-collector** [comment]
Same issue here

**Comment by orditeck** [comment]
Same issue here

**Comment by orditeck** [comment]
For me it also happen when trying to drag/move a file using the Explorer's sidebar. Instant crash. When not in "Chrome app mode", so when in a regular Chrome tab, it works without any issue. Must be a Chrome bug on MacOS....

**Comment by sr229** [comment]
Please avoid saying "Same issue here", just +1 this issue and we'll get it sorted.

**Comment by nhooyr** [comment]
Works fine now. If this is still a problem, please feel free to reopen.
