### ISSUE TITLE
Manifest is not able to be successfully fetched from behind an authenticating proxy.

### ISSUE THREAD

**Issue by FrankPetrilli** [cdr/code-server#822]
- `code-server` version: 1.1156-vsc1.33.1
- OS Version: Docker image on Kubernetes

## Description

I run code-server behind an authenticating Kubernetes Ingress which sets a cookie after a successful login is performed. Since this cookie is not set when fetching the manifest, the fetch fails and gets redirected to the authentication page, breaking code-server completely.

## Steps to Reproduce

1. Utilize an authenticating proxy which uses cookies to tag an authorized browser
2. Access code-server

## Next-steps:

Pending PR incoming. Issue for tracking.

**Comment by ediphy-azorab** [comment]
Is your authenticating proxy google's IAP by any chance? I've been experiencing the same issue with several apps and hadn't tracked it down to the lack of cookie before.
