### ISSUE TITLE
Trying to run on Google Cloud by I don't know wha'ts to put in Source IPs (it is required)

### ISSUE THREAD

**Issue by Ridermansb** [cdr/code-server#828]
## Description

After [follow the tutorial][1].. in `Firewall rule details` I don't know what's values to fill

![image](https://user-images.githubusercontent.com/725337/60635190-3d6c6c00-9de8-11e9-9a6b-d2e57fcef704.png)

[1]: https://github.com/cdr/code-server/releases/download/1.1156-vsc1.33.1/code-server1.1156-vsc1.33.1-linux-x64.tar.gz

**Comment by fouad** [comment]
@Ridermansb if you want it to be publicly accessible: `0.0.0.0/0`
