### ISSUE TITLE
Support for modal popups

### ISSUE THREAD

**Issue by laurentenhoor** [cdr/code-server#829]
Currently the following API is not supported:
```javascript
vscode.window.showErrorMessage(errorMessage, { modal: true });
```
This (`modal: true`) is supported by the desktop version, however it seems to be handled by a OS native popup. I need a blocking modal (that needs an explicit user action to hide) for a certain feature.

Is this already available in code-server? Or -alternatively- is it possible to fire the browser's native `alert()` javascript API?

<img width="586" alt="37958613-e2121f8c-31a8-11e8-9af1-eae9826b9d20" src="https://user-images.githubusercontent.com/32955832/60674178-dbf4dd80-9e79-11e9-9259-9fc72becc917.png">

**Comment by sr229** [comment]
We could shim the API to use `alert()` for that part IMO

**Comment by code-asher** [comment]
I tried out `vscode.window.showErrorMessage("hello", { modal: true });` on v2 and it appears to work as expected. :bear:
