### ISSUE TITLE
Pre-install extension

### ISSUE THREAD

**Issue by laurentenhoor** [cdr/code-server#830]
Is it possible to pre-install an extension while building the project?
I have a *.vsix extension package and that needs to be included by default.
What is the best way to approach this, to make sure the extension is installed after `docker build .`?

**Comment by deansheather** [comment]
There's a flag on code-server called `--install-extension` which will install extensions by ID or from a  VSIX file. Here's a minimal Dockerfile which installs a VSIX extension during the Docker build:
```Dockerfile
FROM codercom/code-server:latest

COPY extension.vsix /tmp/
RUN code-server --install-extension /tmp/extension.vsix
```
