### ISSUE TITLE
when you use search function it shows a split second then goes Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by Dj-jom2x** [cdr/code-server#832]
- `code-server` version: just now fresh build
- OS Version:  18.04

## Steps to Reproduce

step 1: search

**Comment by Dj-jom2x** [comment]
i already install net-tools

**Comment by Dj-jom2x** [comment]
```
Error: spawn /tmp/code-server/dependencies/rg EACCES    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)    at onErrorNT (internal/child_process.js:415:16)    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by deansheather** [comment]
Looks like it's failing to run ripgrep for the search. code-server contains `rg` inside of it's executable, and extracts it so it can run it.

Try running `/tmp/code-server/dependencies/rg` in a terminal, and if you get "permission denied", run `sudo chmod +x /tmp/code-server/dependencies/rg` before trying again.

**Comment by Dj-jom2x** [comment]
still permission denied

**Comment by Dj-jom2x** [comment]
any news?

**Comment by code-asher** [comment]
Does this issue persist in v2? I haven't been able to replicate it.

**Comment by Dj-jom2x** [comment]
well it happened to me on v1. if you use the binary ..on server that has web hosting panel on it.. such as cpanel or cyberpanel those guys mount tmp without execution thats why this happened.. the only solution is to build it under their jailed ssh account..  .. 

in v2.... still happening .. building it from source will fix it.. because the vscode is right beside code server ..if i go in tmp .. i dont see that /tmp/code-server/..


maybe I suggest that just extract it beside where user put it.. not on the temp it self.. example if i do 

mkdir lol
cd lol
wget binary url here
then execute
the binary will create the folder beside it self..

**Comment by sr229** [comment]
I'm debugging latest LKGR, this is no longer present.

**Comment by Dj-jom2x** [comment]
LKGR compatible even if tmp had no exec perm? does it not extract on tmp anymore?

**Comment by code-asher** [comment]
Ohh that's interesting. So you can write to /tmp you just can't execute from it?

**Comment by code-asher** [comment]
I opened an issue: https://github.com/cdr/code-server/issues/1102.
