### ISSUE TITLE
Latest version is named incorrectly

### ISSUE THREAD

**Issue by ckathleen** [cdr/code-server#833]
- `code-server` version: 1.1156-vsc1.33.1

- OS Version: linux-x64, all cloud providers 

## Description

Throughout your documentation you write ```code-server-{version}``` but the latest linux version is named ```code-server{version}```. There is no hyphen between the word server and the version string. 

## Steps to Reproduce

1. Try to visit https://github.com/cdr/code-server/releases/download/1.1156-vsc1.33.1/code-server-1.1156-vsc1.33.1-linux-x64.tar.gz in your browser and it will fail to download 
2. Instead visit https://github.com/cdr/code-server/releases/download/1.1156-vsc1.33.1/code-server1.1156-vsc1.33.1-linux-x64.tar.gz and it will download! 

## Finders
@iyengarvinay and @ckathleen

**Comment by deansheather** [comment]
This just seems like a documentation mistake. I looked back through a page of releases and none of them have a hyphen after `code-server` before the version. The GitHub releases are drafted for us by CI, which names and uploads the binaries for us, so it makes sense that it probably hasn't changed.

Would appreciate a PR that fixes the documentation. I think the only place that we say `code-server-{version}` is in our `doc/admin/install/*` guides.

**Comment by deansheather** [comment]
Found a really old PR that seems to address this: #730. Asked for PGP signatures so we can merge it.

**Comment by ckathleen** [comment]
Okay, happy to submit a new PR tonight if that would help.

**Comment by deansheather** [comment]
Merged.
