### ISSUE TITLE
Add Visual Studio IntelliCode for the Coder Marketplace

### ISSUE THREAD

**Issue by zenof** [cdr/code-server#838]
- Extension: https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode

## Description

It will be great if the Visual Studio IntelliCode can added to the Coder Marketplace. I have tried download `vsix` file and install manually and it works great.

By the way, how does the Coder Marketplace sync extension up to date with VS Code MarketPlace? Because I saw lots of outdated extensions in the Coder Marketplace.

**Comment by sr229** [comment]
@zenof as stated before, any closed source extensions cannot be added to Coder. We can only add open source extensions on the registry.
