### ISSUE TITLE
when run "yarn start",a bug appear!

### ISSUE THREAD

**Issue by VN666** [cdr/code-server#842]
## when I down the code and install dependencies, when I run "yarn start", a bug appear like this: 
![image](https://user-images.githubusercontent.com/19190890/60939950-530ff300-a30c-11e9-930d-ca88b82b0a3c.png)
I strongly want to know how to solve this question。

**Comment by deansheather** [comment]
Instead of running `yarn start`, run the following:
``` 
yarn install
NODE_ENV=production VERSION=local-dev yarn task build:server:binary
./packages/server/cli-linux-x64 --help
```

**Comment by VN666** [comment]
> Instead of running `yarn start`, run the following:
> 
> ```
> yarn install
> NODE_ENV=production VERSION=local-dev yarn task build:server:binary
> ./packages/server/cli-linux-x64 --help
> ```

when I try your method runs ./cli-darwin-x64, the terminal module does not working, details as follow:
![image](https://user-images.githubusercontent.com/19190890/60957921-12c66a00-a338-11e9-9c41-963be1854e38.png)

**Comment by deansheather** [comment]
`pty.node` is supplied from `node-pty`: https://github.com/microsoft/node-pty/issues/256. Ensure `python --version` returns 2.x (if not, change your python preference to python2), as most native Node packages require python2 to build properly, then clean and reinstall with yarn.

Make sure your Node version is v10.15.1, as this is the version we use when building nbin and code-server. `node-pty` will fail to load `pty.node` if the version it was compiled with (`node --version`) doesn't match the version of Node used when running it.

**Comment by VN666** [comment]
> `pty.node` is supplied from `node-pty`: [microsoft/node-pty#256](https://github.com/microsoft/node-pty/issues/256). Ensure `python --version` returns 2.x (if not, change your python preference to python2), as most native Node packages require python2 to build properly, then clean and reinstall with yarn.
> 
> Make sure your Node version is v10.15.1, as this is the version we use when building nbin and code-server. `node-pty` will fail to load `pty.node` if the version it was compiled with (`node --version`) doesn't match the version of Node used when running it.

Well done! As I use npm v10.15.1,  terminal works well, thanks for your work ^ ^
