### ISSUE TITLE
Scala Extension

### ISSUE THREAD

**Issue by yqszxx** [cdr/code-server#843]
- `code-server` version: Not related
- OS Version:  Not related
- Extension: [Scala (Metal)](https://github.com/scalameta/metals-vscode) 

## Description
Scala is a widely used language for constructing Domain Specific Languages. It will be awesome to have this scala language extension in Coder Extension Marketplace.

## Steps to Reproduce
Not related.

**Comment by captainwasabi** [comment]
I second this, I really hoped this was going to work. I tried installing from the .vsix but it said that it didn't support VS 1.33.1

**Comment by sr229** [comment]
We don't do custom extensions, sorry. But try out the Scala extension again in the v2 preview.

**Comment by jiminhsieh** [comment]
I did try v2 preview, Scala (Metals) still doesn't work.

**Comment by yqszxx** [comment]
Found a temporary solution for who is eagarly wants to use Metal.
Download Metal vsix from VSCode Marketplace, unpackage (unzip infact) it, update `/extension/package.json` `engines->vscode` value to `^1.33.0`, repack and then install it in your online ide.

**Comment by sr229** [comment]
@yqszxx we use VSCode upstream in v2, so yes.

**Comment by sr229** [comment]
> I did try v2 preview, Scala (Metals) still doesn't work.

You can try out the Marketplace version, @code-asher told me there was deviation from the Marketplace versions to their own registry (might be build issues).

**Comment by olafurpg** [comment]
FWIW, the latest metals-vscode extension uses v1.34 
https://github.com/scalameta/metals-vscode/blob/e57020554af9c90073ecd9c4fc71439a0b3ff731/package.json#L38

**Comment by sr229** [comment]
@olafurpg currently we target `master` so I think API would be less stable.

**Comment by easel** [comment]
Looks like latest upstream are in sync and the extension will install in v2 previews, however when attempting to load a Scala project the extension blows up failing to load ‘promisify-child-process’. That module is referenced in the package.json, but the crash occurs in extension.ts, so maybe there’s something going on wrt init order or node module path?

**Comment by sr229** [comment]
@easel looks like the extension wasn't compiled properly on our end, you can try running a `yarn` or `npm i -S` on the extension directory.

**Comment by easel** [comment]
@sr229 thanks for the hint, it worked! In this case, I did the following:

```
cd ~/.local/share/code-server/extensions/scalameta.metals-1.5.6
yarn
```

And now metals is working beautifully. Is there anything I can do to help get a fix upstream, and to get metals included in the extensions marketplace?

**Comment by sr229** [comment]
I don't think metals has a problem with theirs, we're probably building the extensions incorrectly once more. For now I'll be closing this off.

CC @code-asher this might be need in fixing really really soon.
