### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by jritsema** [cdr/code-server#844]
- `code-server` version: 1.1156-vsc1.33.1
- OS Version: macOS 10.12.6 (16G2016); docker 2.0.0.3 (31259)

## Description

I get the following error when trying to build the docker image:

https://gist.github.com/jritsema/4379d2423cc2b31278e2aee5a1027068

## Steps to Reproduce

1. clone repo
1. docker build -t vscode .

**Comment by deansheather** [comment]
Could be an out of memory crash. Make sure you have enough available RAM, and have enough [allocated to Docker](https://github.com/moby/moby/issues/21083#issuecomment-329374116).

**Comment by jritsema** [comment]
Thanks for the tip.  I'll give it a try.

**Comment by jritsema** [comment]
@deansheather Confirming that increasing docker's allowable memory from 2Gb to 4Gb fixed the build.  Thanks again for the tip.
