### ISSUE TITLE
fetching .wasm does not work behind proxy

### ISSUE THREAD

**Issue by recro-lataille** [cdr/code-server#845]
Im using HA proxy for ssl termination with client certificate validation. the fetch for f8f821a66b20e5801e35df5ec4565b30.wasm  (onigasm I believe) fails this was reproduced in the firefox browser by using the console fetch('f8f821a66b20e5801e35df5ec4565b30.wasm') the solution was tested by doing fetch('f8f821a66b20e5801e35df5ec4565b30.wasm', {credentials: 'same-origin') and the fetch is successful.  

## Steps to Reproduce

1. ssl terminating load balance validating client certs 
1. load the codeserver on the browser

**Comment by code-asher** [comment]
Closing per comments in https://github.com/cdr/code-server/pull/846.
