### ISSUE TITLE
Retain last opened session

### ISSUE THREAD

**Issue by dejunzhou** [cdr/code-server#850]
I would like to have code server running on my remote server, and every time after I open my browser,  I can see all the files opened and terminals running which all the histories in my last session.

This feature is offered by Jupyter and Theia, I'm wondering if code-server can do the same.

**Comment by deansheather** [comment]
We used to have this functionality but it got lost when we transitioned to service workers instead of running the IDE in the main JS thread. There's an issue about fixing it, so I'm closing this issue in favor of it: #801.
