### ISSUE TITLE
I want open a file when code-server startup

### ISSUE THREAD

**Issue by synuwxy** [cdr/code-server#851]
I want open a file when code-server startup
but i can not find any command about that
where should I need to find these commands?

**Comment by debuggermalhotra** [comment]
You figured it out?

**Comment by deansheather** [comment]
This is currently not supported.

**Comment by frank-dspeed** [comment]
i think now it is supported via ?file= @deansheather ?

**Comment by nhooyr** [comment]
Duplicate of #164
