### ISSUE TITLE
how can i start code-server by backgroup-service In the process of development ?

### ISSUE THREAD

**Issue by xmpilot** [cdr/code-server#852]
## Description
In the process of development,  start code-server by command " yarn start  --allow-http --no-auth", but it will stop when i close terminal.
if not start by docker or release, i need code-server always running，how can i to do?

**Comment by KeithIMyers** [comment]
I typically add a command to my server's startup script to launch coder in a screen and detach.

sudo apt install screen

screen -d code-server .... options

**Comment by deansheather** [comment]
You could use screen, tmux, or any other terminal multiplexer. You could also make a service file for whatever service manager your distro uses.
