### ISSUE TITLE
how to set context path? for example: http://localhost:8433/test/

### ISSUE THREAD

**Issue by xmpilot** [cdr/code-server#853]
## Description
code-server default start web server is http://localhost:8433/, i want to set the context path, for example: http://localhost:8433/test/ , how can id do ?

**Comment by jeasonstudio** [comment]
Behind a proxy.  
See: https://github.com/cdr/code-server/blob/master/doc/self-hosted/index.md#nginx-reverse-proxy

**Comment by xmpilot** [comment]
@jeasonstudio 貌似可行，我后面试下，谢了哈！

**Comment by antofthy** [comment]
FYI for english uses...  xmpilot said...  Looks like it is feasible, I will know more later, thank you

**Comment by deansheather** [comment]
Unfourtunately, service workers are broken on custom directories in the current release version. It has been fixed and merged into master, but we won't release it until we merge the next version.

**Comment by sr229** [comment]
@xmpilot Try out the new v2 preview, setting context is now possible.
