### ISSUE TITLE
C# compilation does not work

### ISSUE THREAD

**Issue by oxodao** [cdr/code-server#859]
- `code-server` version: 1.1156-vsc1.33.1
- OS Version: Debian 9 (kernel 4.19)

## Description

Trying to run a C# project won't work on code-server.
I know that this is more likely related to OmniSharp server but since it does work correctly on a standard VSCode setup I think the problem comes from server...
Error reported:

```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
```

## Steps to Reproduce

1.  Clean install of code-server (I'm running it without docker)
2. Install the official C# plugin
3. Let it download & install OmniSharp server
4. Create a new C# project (I created an asp.net one)
5. Try to run it (F5)

**Comment by sr229** [comment]
@oxodao Try out the v2 Preview and see if that works. We use proper VS Code upstream now.

**Comment by oxodao** [comment]
This message seems to still be showing up.
I'm facing a few other problems now, it shows a message that it can't find dotnet core tools and this when I try to open a C# file: `The SDK 'Microsoft.NET.Sdk.Web' specified could not be found`

This even though the dotnet core is in my path and I can execute command from the terminal

**Comment by deansheather** [comment]
From the error, it looks like vsdbg checks that the VS Code version you are using is stock. We can't really fix this without breaking the license.

I think there's a setting that lets you use a different debugger instead of vsdbg, however.

**Comment by sr229** [comment]
Marking as wontfix due to Dean's comment.
