### ISSUE TITLE
change storage.googleapis.com/coder-production-extensions to alternate host

### ISSUE THREAD

**Issue by amaline** [cdr/code-server#860]
## Description

Is there any way to change the host portion of the https://storage.googleapis.com/coder-production-extensions location so I can route the request through a proxy?

**Comment by deansheather** [comment]
Does setting a `HTTP_PROXY` or `HTTPS_PROXY` env var work?

**Comment by frank-dspeed** [comment]
@amaline look into the master branch in src the marketplace ts at the end of the file is the marketplace url go to the url and call /search there you will find where that url comes from you will need to change the marketplace.ts and also serve a edited /search aka extensions api

**Comment by sr229** [comment]
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.
