### ISSUE TITLE
Not Loading with Self-Signed Certificate

### ISSUE THREAD

**Issue by mehmetoguzderin** [cdr/code-server#862]
- `code-server` version: code-server1.1156-vsc1.33.1-linux-x64
- OS Version: iPadOS

## Description

When a Code Server instance is launched with self-signed certificate, after authentication, you get left with a blank, black screen. On server, it says "can not find favicon.ico". But when using --allow-http, it loads correctly.

## Steps to Reproduce

1. Launch a self-signed Code Server instance
2. Connect from an iPad with iPadOS

**Comment by deansheather** [comment]
Unfourtunately, secure websockets (`wss://`) don't work with self-signed certificates on iPad OS due to a webkit bug. We recommend using letsencrypt to issue a trusted certificate.
