### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/root/code/code-server/packages/server/build/web/login/index.html'

### ISSUE THREAD

**Issue by Dj-jom2x** [cdr/code-server#864]
- `code-server` version: next or current
- OS Version:  Ubuntu 18

## Description

Error: ENOENT: no such file or directory, open '/root/code/code-server/packages/server/build/web/login/index.html'

out of no where its gone poof xD its been working for sometime and today i saw this.. when i login

## Steps to Reproduce

1. visit https://example.net:8443

**Comment by deansheather** [comment]
This is usually cased by your browser not negotiating support for gzip files. It will be fixed by GH-826.

**Comment by code-asher** [comment]
Resolved with v2.
