### ISSUE TITLE
How to change current open files ?

### ISSUE THREAD

**Issue by xiangnanscu** [cdr/code-server#866]
## Description
Every time I open code-server, it always opens several fix files : `package.json`, `ide.conf` and so on. I just want the code-server to remember which files I left open when closing the browser tab and open them when I use code-server again. 
I've tried the following but doesn't work:
1.  fresh the page
2. reboot the server

**Comment by deansheather** [comment]
Duplicate of #801. This should be fixed pretty soon (as part of our v2).
