### ISSUE TITLE
why editorconfig doesn't work?

### ISSUE THREAD

**Issue by vvkkhjt** [cdr/code-server#867]
## Description
I install editorconfig plugin, and i create .editorconfig file but it doesn't work,who can help me.thks.

**Comment by sr229** [comment]
Seems to happen in v2 preview as well. I was able to extract this for v2

```
Activating extension 'EditorConfig.EditorConfig' failed: Cannot find module 'lodash.get'.
```

**Comment by code-asher** [comment]
Commenting to link this issue: https://github.com/cdr/code-server/issues/971

**Comment by sr229** [comment]
Marking as bug
