### ISSUE TITLE
Is it possible to use Azure Devops TFVC

### ISSUE THREAD

**Issue by tsgiannis** [cdr/code-server#868]
At first GREAT IDE..great idea for getting VSCode on self hosted.
I have a small issue
I want to use TFVC Source Control with code-server
I have installed Azure Repos along with Team Explorer Everywhere...i have filled the tf script location but is not getting registered as Source Control Provider.
Any idea ?

**Comment by deansheather** [comment]
Likely an extension bug. Could you list the extensions you tried?

**Comment by tsgiannis** [comment]
I am so sorry for the late reply...i was on vacation
Anyway i have installed both TFS and Azure Repos ....but they seem pretty much dead...i have installed the TF script for connecting to Azure Devops via console but Code-Server doesn't seems to support it.... :(

**Comment by sr229** [comment]
Hey @tsgiannis, have you tried using the extensions on the v2 Preview? This should allow you to use it properly since its a minimally patched version of VSCode Web.

**Comment by nhooyr** [comment]
If this still occurs, please feel free to reopen.
