### ISSUE TITLE
Code server and Monaco editor

### ISSUE THREAD

**Issue by devfeeddev** [cdr/code-server#869]
## Description

Anyone tested/used code server with [Monaco Editor ](https://microsoft.github.io/monaco-editor/)?
Any tip on how to setup both ?

**Comment by lfx** [comment]
I wondering what is your intentions?

As per docs: 
> The Monaco Editor is the code editor that powers VS Code.  

Monaco Editor is inside VS Code.

**Comment by deansheather** [comment]
Monaco is built into VS Code, which is what code-server is based on.
