### ISSUE TITLE
the amount of code-server processes start from 6 to 13 is this normal?

### ISSUE THREAD

**Issue by xiangnanscu** [cdr/code-server#870]
## Description
I just use the code-server bin like this on Ubuntu 18.04 Server 2 core 4G. It starts six processes. But when I close the current browser and open it in another computers, the processes keep increasing, and finally to 13.
Is this normal?
```
code-server -p 1111 ~/p
```
```
root@dev:~/works# yarn show
yarn run v1.16.0
$ top -b -n 1 | grep -E '%CPU|nginx|code-server'
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  968 root      20   0 1348512  92056  21580 S   6.7  2.3   1:11.57 code-server
 1080 root      20   0 1226320 212264  20928 S   0.0  5.3   0:03.96 code-server
 7496 root      20   0  798320 208300  20056 S   0.0  5.2   0:01.44 code-server
 7842 root      20   0  797668 208132  20080 S   0.0  5.2   0:01.47 code-server
 8021 root      20   0  797664 207772  19980 S   0.0  5.1   0:01.40 code-server
 9069 root      20   0  797804 208192  20024 S   0.0  5.2   0:01.50 code-server
10101 root      20   0  797284 208512  20080 S   0.0  5.2   0:01.48 code-server
11525 root      20   0  798308 208100  20044 S   0.0  5.2   0:01.45 code-server
11721 root      20   0  797800 208560  20064 S   0.0  5.2   0:01.48 code-server
17922 root      20   0 1188388 235600  26800 S   0.0  5.8   0:02.09 code-server
17929 root      39  19 1110568 281700  25192 S   0.0  7.0   0:01.57 code-server
17952 root      20   0  797656 212940  25192 S   0.0  5.3   0:01.44 code-server
17961 root      20   0  572828  47636  25092 S   0.0  1.2   0:00.28 code-server
```

**Comment by xiangnanscu** [comment]
the version
```
root@dev:~/works# code-server --version
1.1156-vsc1.33.1
```

**Comment by lfx** [comment]
How much work are you doing? Do you use different programming languages? Do you have a lot of extensions installed? 

On 'normal' Visual Studio Code on my Mac, there are a lot of vscode-helper processes running depending on a different project I'm working. Assumingly those code-server processes just 'hides' mentioned helper processes.

But would be interesting to hear from the developer's team.

**Comment by antofthy** [comment]
I would be interested in knowing if all these processes are ever 'reaped' when no longer needed?

I have seen users (students) close their browsers, so the browser is no longer connecting to code-server (every 5 minutes, according to log updates, if browser is open), and yet LOTS of code-server processes remain.

**Comment by xiangnanscu** [comment]
@lfx my project is simple, just lua and js. extentions is just 5. the point is, the same project, same work load, the processes keep increasing. I doubt it has something to do with reopen project in different computer. Even if I already close previous one.

**Comment by lfx** [comment]
@antofthy it seems so, today during the development of react app I had around 15 of those. Now I see only 6. So definitely they are discarded.

**Comment by deansheather** [comment]
It's normal for code-server to have more than one process. Processes by themselves don't take up much resources, but allow code-server to perform better. If you are seeing an extreme amount of processes (probably somewhere above 30 per instance of code-server), feel free to comment so I can reopen this issue.

If you're concerned about resource usage, the next version of code-server should reduce it's memory usage significantly.

**Comment by antofthy** [comment]
@deansheather  Looking forward to the memory reduction.

ASIDE:

We are currently reaching a maximum of 40 docker containers each with a code-server and apache running in it.  At that point the 64 Gb memory of the VM server becomes exhausted.   We are currently expanding our system to multi-machine docker swarm, due to this memory problem. Sticking point with that expansion was with the provision of SSH file transfer to a multi-server swarm, but have worked out a solution to that.

We have seen a couple of instances of code-server going CPU bound, but do not know what the user did to cause this condition.

**Comment by deansheather** [comment]
You can monitor Docker container CPU usage using `docker stats` and restart them if it becomes too much. Additionally, you can restrict the amount of CPU and memory usage during container creation: https://docs.docker.com/config/containers/resource_constraints.

Hopefully the CPU issues you're seeing are fixed in the next version.

**Comment by antofthy** [comment]
Haven't seen any CPU bound code-servers for a while.. Mostly when users were first 'trying out' the code-server.  Probably doing something 'weird' at the time, like perhaps trying a file transfers of some kind.  Or perhaps the last update fixed it.  Don't know.

`docker stats` is a useful command...   CPU, Memory and IO for each container.  That with knowing how 'idle' code-server is with regards to the user, will make cleaning up a problem like that a lot easier.   Thanks.
