### ISSUE TITLE
Change password does not work for me

### ISSUE THREAD

**Issue by thierschi** [cdr/code-server#874]
I wanted to set a custom password for my code-server latest version by setting an enviroment variable, but it does not work althogh it is described to work that way in issue #548 .
Also I don't find anything related to passwords in the docs (self-hosted/index.md) althought it should be there (See Issue #625)

**Comment by deansheather** [comment]
Could you demonstrate how exactly you were specifying the password and launching code-server? Also, please provide information about your OS (local and whatever code-server is running on).
