### ISSUE TITLE
./code-server doesn't working on gcp vm

### ISSUE THREAD

**Issue by WilliamNAM** [cdr/code-server#878]
## Issue description

1. I have installed code-server on vm of gcp

2. cd code-server1.1156-vsc1.33.1-linux-x64

3. ./code-server

4. doesn't work...

I think it's related with port, so have got a setting VPC network > fire wall regulation
for http-8443 following the code-server/doc/admin/install/google_cloud.md 

anyone help me? ;)

**Comment by lfx** [comment]
@WilliamNAM I have it running on GCP.

When you say `doesn't work...` what do you mean specifically? 

Did you set up ports as described? 

When you start ./code-server, what happens? Can you provide a log?

**Comment by WilliamNAM** [comment]
> 
> 
> @WilliamNAM I have it running on GCP.
> 
> When you say `doesn't work...` what do you mean specifically?
> 
> Did you set up ports as described?
> 
> When you start ./code-server, what happens? Can you provide a log?

**Comment by WilliamNAM** [comment]
first of all, thax for your reply~ ;)

I have get a solving the issue because I didn't add a network tag!

Have use  with sudo ./code-server .. -p 8443 command~

Thanx!
