### ISSUE TITLE
dockerfile build error for branch web

### ISSUE THREAD

**Issue by synuwxy** [cdr/code-server#880]
code-server: branch web
os: centos 

set ENV like README.md
ENV  codeServerVersion=development
ENV vscodeVersion=1.36.0
ENV target=linux
ENV arch=x64
ENV OUT=/usr/local

docker build -t code-server-web .  

Installing VS Code dependencies have a error:
[4/4] Building fresh packages...
error /usr/local/build/vscode-1.36.0-source/node_modules/keytar: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments: 
Directory: /usr/local/build/vscode-1.36.0-source/node_modules/keytar
Output:
/usr/local/build/vscode-1.36.0-source/node_modules/node-abi/index.js:30
  throw new Error('Could not detect abi for version ' + target + ' and runtime ' + runtime + '.  Updating "node-abi" might help solve this issue if it is a new release of ' + runtime)
  ^

Error: Could not detect abi for version 4.2.5 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at getAbi (/usr/local/build/vscode-1.36.0-source/node_modules/node-abi/index.js:30:9)
    at module.exports (/usr/local/build/vscode-1.36.0-source/node_modules/prebuild-install/rc.js:64:12)
    at Object.<anonymous> (/usr/local/build/vscode-1.36.0-source/node_modules/prebuild-install/bin.js:8:25)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.16.0 | linux | x64
gyp http GET https://atom.io/download/electron/v4.2.5/node-v4.2.5-headers.tar.gz
gyp http 200 https://atom.io/download/electron/v4.2.5/node-v4.2.5-headers.tar.gz
gyp http GET https://atom.io/download/electron/v4.2.5/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v4.2.5/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/build/vscode-1.36.0-source/node_modules/keytar/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/4.2.5/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/4.2.5',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/4.2.5/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/usr/local/build/vscode-1.36.0-source/node_modules/keytar',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
make: Entering directory '/usr/local/build/vscode-1.36.0-source/node_modules/keytar/build'
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/keytar/src/async.o
In file included from ../node_modules/nan/nan.h:50:0,
                 from ../src/async.cc:4:
/root/.node-gyp/4.2.5/include/node/uv.h:24:0: error: unterminated #ifndef
 #ifndef UV_H
 
In file included from /usr/include/c++/6/memory:66:0,
                 from /root/.node-gyp/4.2.5/include/node/v8.h:21,
                 from /root/.node-gyp/4.2.5/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:51,
                 from ../src/async.cc:4:
/usr/include/c++/6/bits/stl_tempbuf.h:62:1: error: expected ',' or '...' before 'namespace'
 namespace std _GLIBCXX_VISIBILITY(default)
 ^~~~~~~~~
In file included from /usr/include/c++/6/memory:71:0,
                 from /root/.node-gyp/4.2.5/include/node/v8.h:21,
                 from /root/.node-gyp/4.2.5/include/node/node.h:67,
                 from ../node_modules/nan/nan.h:51,
                 from ../src/async.cc:4:
/usr/include/c++/6/typeinfo:39:37: error: expected ')' before end of line
 #pragma GCC visibility push(default)
                                     ^
/usr/include/c++/6/typeinfo:39:37: error: expected initializer before end of line
/usr/include/c++/6/typeinfo:39:37: error: expected '}' before end of line
/usr/include/c++/6/typeinfo:39:37: error: expected declaration before end of line
keytar.target.mk:109: recipe for target 'Release/obj.target/keytar/src/async.o' failed
make: Leaving directory '/usr/local/build/vscode-1.36.0-source/node_modules/keytar/build'
make: *** [Release/obj.target/keytar/src/async.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.10.0-957.21.3.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/build/vscode-1.36.0-source/node_modules/keytar
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command

---

使用README.md所说的方法，docker build 失败
系统: centos
操作方法: 
1. 设置ENV
ENV codeServerVersion=development
ENV vscodeVersion=1.36.0
ENV target=linux
ENV arch=x64
ENV OUT=/usr/local
2. docker build -t code-server-web .
3. 报如上错误

不知道这个操作是否正确

**Comment by deansheather** [comment]
If there's an issue with the web branch, you should comment on the pull request: #857.
