### ISSUE TITLE
Detect when user is trying to close the editor

### ISSUE THREAD

**Issue by voluntadpear** [cdr/code-server#882]
## Description

For a little experiment, I'm trying to detect when the user is trying to close the editor (like pressing "cmd + W" when there are no open files or going to "File" -> "Close Editor").

I'm able to attach a listener to the `successEmitter` like this:
```js
window.ide.client.successEmitter.listeners = [(e) => console.log('success: ', e)]
```

and I see that it receives events when I'm trying to close the editor. However, inside the event payload I'm not able to find relevant properties that would allow me to identify the close attempt.

Other attempts used:

```js
// Registering additional workbench actions somehow
window.ide.workbench.actionsRegistry.registerWorkbenchAction

// Listen to the 'workbench.action.quit' command
window.ide.workbench.commandRegistry._commands.get('workbench.action.quit')
```

All of them unsuccessful so far.

Do you have any idea if this is possible attaching a listener of somehow under any of the emitters available to the client on `window.ide` or if there is another way I could do it?

Thanks!

**Comment by sr229** [comment]
@voluntadpear This seems an area v2 wants to fix, v2 uses VSCode Web (aka VS Online Upstream), so you should be able to raise this to `vscode` as well.

**Comment by nhooyr** [comment]
Not sure why you need this feature. We'd like to follow VS Code's API so its best to file this upstream.
