### ISSUE TITLE
Latest Flutter/Dart extensions won't install

### ISSUE THREAD

**Issue by sionicion** [cdr/code-server#886]
- 1.1156-vsc1.33.1
- Ubuntu 19.04 local install
- Extensions: https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code
https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

## Description

My extensions weren't updating, specifically Flutter and Dart. So I uninstalled them and tried reinstalling. It errored out, possibly because the version of VSCode that code-server is based off is too old, but not sure.

## Steps to Reproduce

1. Without Flutter and Dart extensions installed, try installing them.
2. Errors appear "Unable to install because, the extension 'dart-code.flutter' compatible with current version '1.33.1' of VS Code is not found."

**Comment by ahjota** [comment]
I am currently having the same issue with ms-python.python in an image based FROM 1.1156-vsc1.33.1. Thought it was due to the Python extension having just been updated yesterday (6 August).

**Comment by deansheather** [comment]
v2 of code-server will be released soon, and it will be based on a newer version of VS Code which should solve this problem.

**Comment by deansheather** [comment]
GH-857

**Comment by AppleEducate** [comment]
Any update or workaround on how to install these extensions?

**Comment by sr229** [comment]
@AppleEducate please use v2. v1 is now a deprecated version and we won't release fixes in v1.

**Comment by AppleEducate** [comment]
Oh gotcha, I just saw prerelease and didnt know if it was ready. cool ill install the new one then :)

**Comment by sr229** [comment]
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.

**Comment by sr229** [comment]
@sionicion Try running `npm install` or if Dart has any other postinstall tasks, run it manually.

**Comment by nhooyr** [comment]
Works fine now. If this is still a problem, please feel free to reopen.
