### ISSUE TITLE
Better Mobile GUI

### ISSUE THREAD

**Issue by Developer626** [cdr/code-server#888]
One feature that I'd like to see is a better or a more usable GUI for small screen mobile devices. The current setup works as it is, but every now and then I have trouble navigating to different windows, clicking on different files, and a few other issues. Maybe a button in the top corner to hide portions of the menu and add some extra controls you'd get on a full sized computer that is hard to do on a mobile device, which could also open up some extra screen real state for text editing.

**Comment by sr229** [comment]
@Developer626 Unfortunately we use upstream VSCode and we want to use minimal patches as possible. So if you want a better GUI for VSCode, I suggest you wait for v2 or participate at the VSCode Web development so this can be properly raised.

**Comment by Developer626** [comment]
@sr229 I was thinking about getting involved, and I've only just started looking at the code. I can't wait to see what **v2** will be like. I'll see if there is anything that I can contribute to until then.
