### ISSUE TITLE
[code-server2.preview.2] - Extensions: Cannot install via VSIX

### ISSUE THREAD

**Issue by fromage9747** [cdr/code-server#890]
- `code-server` version: 2.preview.2-vsc1.36.1
- OS Version: Ubuntu 18.04 Server, self-hosted on Proxmox
- Browser: Chrome Version 76.0.3809.100 (Official Build) (64-bit) being used on Windows 10 1903

## Description

Cannot install extensions via VSIX, error produced in bottom right hand corner:

![image](https://user-images.githubusercontent.com/23147783/62754095-9ccd3400-ba98-11e9-8a61-8632b97bddab.png)

## Steps to Reproduce

1. Download https://github.com/cdr/code-server/releases/download/2.preview.2-vsc1.36.1/code-server2.preview.2-vsc1.36.1-linux-x86_64.tar.gz
2. Extract code-server2.preview.2-vsc1.36.1-linux-x86_64.tar.gz
3. Move code-server to /bin
4. Navigate to the desired project folder location
5. Start code-server with coder-server, no extra parameters
6. Navigate to http://IP_ADDRESS_OF_SERVER:8080
7. Click on Extensions from the sidebar
8. Click on Install from VSIX...
9. Note the error produced in the bottom right-hand corner of the screen: "not-implemented"

![image](https://user-images.githubusercontent.com/23147783/62754247-3694e100-ba99-11e9-8612-487c22556b03.png)

**Comment by deansheather** [comment]
This should be fixed in 1.37.0 according to the v2 PR.
