### ISSUE TITLE
[v2] Remote Extension - fails to connect to host

### ISSUE THREAD

**Issue by LukasMasuch** [cdr/code-server#892]
- `code-server` version: 2.preview.9-vsc1.37.0
- OS Version: Ubuntu 16.04
- Extension: [Remote SSH - 0.45.5](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)

## Description

The Remote SSH extension does not seem to work with code-server. When trying to connect to a Host, nothing happens. 

![image](https://user-images.githubusercontent.com/2852129/62779803-7a491400-bab4-11e9-883c-516e83d72e5a.png)

I wasn't able to find any error message or logs related to this issue.

## Steps to Reproduce

1. Install and start code server preview 9
2. Install Remote SSH Extension
3. Create SSH connection in ~/.ssh/config
4. Try to connect to created connection via Remote SSH extension

**Comment by ViRb3** [comment]
[VS Code SFTP](https://marketplace.visualstudio.com/items?itemName=suntobright.vscode-sftp) extension fails as well.

**Comment by roflcoopter** [comment]
This would be an extremely extension feature if it worked.

I have not been able to find any log entries which point to the problem.

**Comment by sr229** [comment]
@code-asher I don't think this was fixe don current VSCode releases?

**Comment by NotFluffy** [comment]
I tried to test remote SSH but it gave me a version error "Unable to install extension 'ms-vscode-remote.remote-ssh' as it is not compatible with VS Code '1.39.2'."

With vs code sftp I can open a file, but not a folder. It simply reloads an empty workspace.

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/1315
