### ISSUE TITLE
Firefox scrolling on steroids in text editor for macOS

### ISSUE THREAD

**Issue by demyxco** [cdr/code-server#895]
## Description

Text editor and explorer scrolls are jacked way up but terminal scrolls fine. Is this a Firefox issue or macOS issue?

## Related Issues

`"editor.smoothScrolling": true,` does not help either. I tried turning off both auto/smooth boxes in Firefox settings, same results.

**Comment by deansheather** [comment]
Does the same thing happen in Chromium or Safari?

**Comment by demyxco** [comment]
I am closing this because I went back to a Chromium-based browser (Brave) due to Firefox being just plain weird. To answer your question incase you want to further diagnose this:

code-server: 1.1156-vsc1.33.1
macOS: 10.13.6
Firefox: 68.0.1
