### ISSUE TITLE
Cannot install extension via CLI (no incompatible version notice)

### ISSUE THREAD

**Issue by StudioEtrange** [cdr/code-server#896]
- `code-server` version: code-server v1.1156-vsc1.33.1
- OS Version: centos 7
- nodejs version tried : v10.14.2 and v10.16

## Description

When trying to install extension with command line, it does not work.

## Steps to Reproduce

Try to install any extension :
* /opt/vscode-server/code-server --install-extension eamodio.gitlens --user-data-dir=/root/.vscode
* /opt/vscode-server/code-server --install-extension ms-python.python --user-data-dir=/root/.vscode

Got same result :

```
(node:697) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
INFO  code-server v1.1156-vsc1.33.1
ERROR (node:709) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ERROR 
ERROR Extension 'eamodio.gitlens' not found.
ERROR Make sure you use the full extension ID, including the publisher, eg: ms-vscode.csharp
ERROR 
ERROR Failed Installing Extensions: eamodio.gitlens
ERROR 
```

**Comment by deansheather** [comment]
Unfortunately, it looks like gitlens doesn't support vscode 1.33.1 anymore. When you install an extension from the command line it doesn't report that a compatible version wasn't found.

code-server v2 is almost out, and the VS Code version bundled with code-server will be on par with the release version of VS Code.

**Comment by sr229** [comment]
Issue is stale. Closing as no longer relevant to current tree.
