### ISSUE TITLE
[v2] Cannot re-enable extension from additional extensions after uninstalling it

### ISSUE THREAD

**Issue by ViRb3** [cdr/code-server#899]
- `code-server` version: v2, preview 4
- Host OS Version: Debian 10 Buster (running on ChromeOS via Crouton)
- Client OS Version: ChromeOS 75

## Steps to Reproduce
1. Use mainline VSCode to install an extension
2. Run `code-server` with `--extra-extensions-dir .vscode/extensions`
3. Uninstall the extension from `code-server`
4. `~/.code-server/extensions/.obsolete` entry is added and extension is no longer loaded
5. No way to re-enable it unless you manually delete/modify `.obsolete`

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
