### ISSUE TITLE
[v2] Input with dead keys

### ISSUE THREAD

**Issue by erickthered** [cdr/code-server#900]
- `code-server` version: 2-preview4
- OS Version: Ubuntu 18.04 running on Digital Ocean

## Description

I´m in Colombia using Chrome 76.0.3809.100 (latest stable) on Windows 10 with a US English Keyboard with International layout (dead keys).  Normally when I try to put a double quote character I have to press the " key and then press space for it in order to appear.  This doesn´t work in preview4 (not sure if this worked before), I have to change my keyboard to plain US English for the double quotes to appear once I click the " char.

## Steps to Reproduce

1. Set your windows keyboard layout to US - International
2. Login to your server
3. Start code-server
4. Visit the ip+port using latest stable Chrome
5. Create a file and try to type the double quotes char... may happen with some other special characters such as: ñ, á, é, í.

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
