### ISSUE TITLE
Email Password to user & Run Code-server as deamon?

### ISSUE THREAD

**Issue by sajjad207** [cdr/code-server#904]
## Description
Hi All, Is there a way in which i can make the process run as a deamon and the password it spits out be somehow sent to an email so in this way the user on the web never needs to interact with the Server  it self? I am bascially looking for a way to capture the Password and send it to the user and also run the code-server in the background.

**Comment by sajjad207** [comment]
These are 2 seprate Questions put into one awnsering either one would be Great...!

**Comment by deansheather** [comment]
code-server doesn't have a daemonize flag, so I'd recommend using a process supervisor to run it in the background.

Regarding the emailing stuff, the easiest way would be to write a little wrapping script that generates a password, runs code-server with `PASSWORD=abc123 code-server ...`, then uses sendmail to send the email.

**Comment by sajjad207** [comment]
@deansheather hey Thanks for your reply i am still pretty new at this when you say "Runs code-server with PASSWORD=abc123 code-server" when do i enter that? would would be the full command? i start the serivce with  "./code-server" do i add it to this same line? if possible can you give me the full command?

**Comment by deansheather** [comment]
If you're using a process manager, I'd recommend setting a script similar to the following as your entry point:
```sh
#/bin/sh

FROM="server@email.com"
TO="me@email.com"

export PASSWORD=$(openssl rand -hex 8)
MAIL="Subject: code-server password\nFrom: $FROM\nTo: $TO\n\nPassword: $PASSWORD"
echo -e $MAIL | sendmail -t
code-server
```
