### ISSUE TITLE
SSO Integration

### ISSUE THREAD

**Issue by sajjad207** [cdr/code-server#905]
Is it possible to integrate code-server to an SSO provider rather than using the passwords generated by default?

**Comment by deansheather** [comment]
At the moment, code-server only supports password authentication. If you want to use another authentication provider, you'll need to use a proxying service like CloudFlare Access, BeyondCorp, etc.

**Comment by sajjad207** [comment]
thanks @deansheather

**Comment by deansheather** [comment]
Another feature would be a local authentication provider with usernames and passwords for multiple users, once we sort out collaboration stuff.

**Comment by dx034** [comment]
Is it possible to disable password authentication? I run code-server behind Cloudflare Access, so there's no need for additional authentication. As far as I see, --auth only accepts "password". Do you plan to add "none" to this?

**Comment by desimone** [comment]
FYI, for those looking for an open-source solution check out pomerium. We've got a guide for [vs code server](https://www.pomerium.io/recipes/vs-code-server.html) too.

**Comment by sr229** [comment]
@desimone that's an awesome integration! If there's any other SSO proxy like this would be awesome to be documented as well. Please let me know other ways of doing it from other people so we can compile it as a documentation, thanks!

**Comment by sr229** [comment]
I'll be porting over the Pomerium example for SSO since I think it'll be a great help for everyone.

**Comment by nhooyr** [comment]
Definitely use a reverse proxy for this.

**Comment by karel-3d** [comment]
Note, there is issue with Pomerium

It does not terminate websockets when user logs out (I found that out on weekend so it might get fixed later). And code server is all websockets. So when user logs out, the VSCode is still open

See

https://github.com/pomerium/pomerium/issues/1279

**Comment by a019647** [comment]
> FYI, for those looking for an open-source solution check out pomerium. We've got a guide for [vs code server](https://www.pomerium.io/recipes/vs-code-server.html) too.

This link has gone stale, but another link seems to have relevant info:
https://www.pomerium.com/docs/guides/code-server#what-is-code-server

**Comment by nettnikl** [comment]
For anyone coming to this ticket from a web search, you are probably looking for https://github.com/oauth2-proxy/oauth2-proxy , or any other auth reverse proxy, like the authentik reverse proxy provider or what authelia offers.

There seems to be no integrated auth, or plan to include such.

Ensure that you have websockets working as expected over the reverse proxy.
