### ISSUE TITLE
User-Password Authentication Features

### ISSUE THREAD

**Issue by BeckettOBrien** [cdr/code-server#908]
Does Code-server have the ability to have multiple users(or even just one) sign in with a username and password stored in a database? I assume that this feature exists on the commercial version of code-server (and that it would be a selling point to keep it that way) But if it does not, I think it would be a good feature to add to the platform.

**Comment by deansheather** [comment]
One way to add authentication to your code-server instance would be to implement an authenticating proxy like CloudFlare Access or BeyondCorp. We don't have any plans for authentication providers right now, but there's another feature request for SSO integration: #905.

I don't believe we have any plans for a local username/password setup in code-server, so I'm closing this in favor of the SSO issue.
