### ISSUE TITLE
[v2] code-server crashes if the system doesn't have ifconfig or ip available

### ISSUE THREAD

**Issue by deansheather** [cdr/code-server#911]
- `code-server` version: v2

## Description

If `ifconfig` or `ip` isn't on the computer/container, code-server will crash unless `--disable-telemetry` is set.

## Steps to Reproduce

1. Ensure `ifconfig` and `ip` don't exist on the system
2. Run `code-server` without `--disable-telemetry`: it crashes
3. Run `code-server --disable-telemetry`: no crash

## Possible solution

Disable telemetry with a warning if the command fails.

**Comment by eVanasse** [comment]
I tried disabling the telemetry, but it's not working properly.
When I run
```
code-server --disable-telemetry
```
I get this output
```
INFO  Server listening on http://localhost:8080
INFO    - No authentication
INFO    - Not serving HTTPS
```

And when I reach `localhost:8080` from a browser, I get a blank page, and the code-server logo on the web tab. But nothing is happening.

**Comment by deansheather** [comment]
@eVanasse This seems like an unrelated issue. If this was related code-server should've crashed before the "Server listening" log line.

Please open a new issue with the `[v2]` tag in the name with the full log output from code-server and the browser console logs.
