### ISSUE TITLE
Code-server sshcode all requests time out

### ISSUE THREAD

**Issue by BeckettOBrien** [cdr/code-server#912]
- `code-server` version: Latest sshcode release
- OS Version: Connecting through sshcode on Mac. Code-server running on Ubuntu 18 LTS (Running On Google Cloud)

## Description
When I run sshcode, it successfully syncs my settings and extensions, then starts code-server on my server. The IDE is opened in chrome, but nothing will load. I cannot save, open, or create any files, the terminal will not open, the extensions window will not load, and the dev tools console is filled with errors. This is what I see in the sshcode output:
```
INFO  Starting webserver... {"host":"127.0.0.1","port":"60220"}
WARN  No certificate specified. This could be insecure.
WARN  Documentation on securing your setup: https://github.com/cdr/code-server/blob/master/doc/security/ssl.md
WARN   
WARN  Launched without authentication.
INFO   
INFO  Started (click the link below to open):
INFO  http://localhost:60220/
INFO   
INFO  Starting shared process [1/5]...
WARN  stderr {"data":"(node:10954) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.\n"}
Error: ENOENT: no such file or directory, open '/src/packages/server/build/web/favicon.ico'
INFO  WebSocket opened / {"client":1,"ip":"127.0.0.1"}
INFO  Connected to shared process
WARN  stderr {"data":"Uncaught Exception:  { Error: spawn ENOMEM\n    at ChildProcess.spawn (internal/child_process.js:366:11)\n    at spawn (child_process.js:538:9)\n    at /src/packages/server/out/cli.js:259:2339\n    at /src/packages/server/out/cli.js:259:2295\n    at /src/packages/server/out/cli.js:504:22829\n    at /src/packages/server/out/cli.js:504:23213\n    at /src/packages/server/out/cli.js:504:24010\n    at FSReqWrap.oncomplete (fs.js:155:5) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }\n"}
```
And this is what I see in dev tools:
<img width="1022" alt="Screen Shot 2019-08-15 at 12 08 19 PM" src="https://user-images.githubusercontent.com/44044350/63119758-28672900-bfa1-11e9-94da-7d6529d2a114.png">

## Steps to Reproduce

1. Download latest release of sshcode for Darwin
1. Run `./sshcode code@code.mysite.com` and enter password when prompted
1. Wait for server to start
1. Code-server will open in a chrome app window, but nothing will load

**Comment by coadler** [comment]
The instance that `code-server` is on is running out of ram, indicated by the `ENOMEM` error. I would recommend adding swap or upgrading the amount of ram on your GCP instance.

**Comment by BeckettOBrien** [comment]
What is the recommended amount of RAM that `code-server` needs to run?

**Comment by coadler** [comment]
For my development instance I have 3-4gb. Depends on how many sessions you have open at a time.

**Comment by coadler** [comment]
Feel free to reopen if you have any more issues.

**Comment by crossan007** [comment]
I'm seeing the same behavior here while running the `codercom/code-server` docker image on Windows Server 2019 via Docker LCOW (Linux Containers on Windows). 

It appears that the default memory allocation of LCOW is 1GB, so this makes sense: https://github.com/docker/for-win/issues/1357

**Comment by crossan007** [comment]
It *looks like* this should be fixed soon: https://github.com/moby/moby/pull/37296

One comment suggests it's already present in Docker 19.03.0: https://github.com/microsoft/mssql-docker/issues/293#issuecomment-513214344 but It doesn't seem to work for me _yet_
