### ISSUE TITLE
[v2] Use bash by default in the Docker container

### ISSUE THREAD

**Issue by paolomainardi** [cdr/code-server#918]
#  Description

Terminal does not start with bash shell when opened for the first time.

<img width="662" alt="Screenshot 2019-08-18 at 13 35 52" src="https://user-images.githubusercontent.com/8747/63223942-5759e680-c1bd-11e9-9b89-d150a0e464d5.png">

**Comment by deansheather** [comment]
In my experience it just uses your login shell. Could you try `chsh -s bash` and see if that helps?

**Comment by cfi2017** [comment]
vscode also has a setting to override the default shell used. In our case, it was easier to do something like:
```bash
cat << EOF > /home/coder/.config/code-server/User/settings.json
{
    "terminal.integrated.shell.linux": "/bin/bash"
}
EOF
```
since we also needed to override other settings.

**Comment by code-asher** [comment]
For anyone wondering, VS Code uses $SHELL by default so this 
happens when that environment variable isn't set.

**Comment by code-asher** [comment]
Closing since I don't believe there is anything reasonable we can do here. If `$SHELL` isn't set `sh` is the safest fallback.

**Comment by code-asher** [comment]
Reopening because in the Docker container at least we should be able to set the default shell to bash.

**Comment by sr229** [comment]
just slap this in and this will make it the default

```dockerfile

ENV SHELL /bin/bash
```

**Comment by code-asher** [comment]
I was thinking the same thing but then I wondered if we could pull it from the user. Normally I think `login` sets `$SHELL` based on `/etc/passwd` but maybe we can just read it ourselves when `$SHELL` isn't set. That would have the advantage of working in other situations as well.

**Comment by ishu-harsh** [comment]
It's Works - saved my time

**Comment by soerendip** [comment]
Hm, does not work for some strange reason. 

`FROM ubuntu:focal

ENV PYTHONUNBUFFERED=1

ENV SHELL /bin/bash

RUN mkdir /data /compute /static /appmedia

RUN apt update && apt install -y build-essential wget

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

WORKDIR /app
COPY requirements.txt /app/
RUN conda install --file requirements.txt`

returns:

> ERROR: Service 'web' failed to build: The command '/bin/sh -c conda install --file requirements.txt' returned a non-zero code: 127

**Comment by code-asher** [comment]
@soerendip I believe 127 means command not found so you probably need to install conda.
