### ISSUE TITLE
Re-running on docker sometimes causes code-server to exit

### ISSUE THREAD

**Issue by cfi2017** [cdr/code-server#919]
- `code-server` version: 2.preview.6-vsc1.37.0
- OS Version: ubuntu 18.04 (binary from release on custom docker build)

## Description

We've been running into a strange issue where code-server sometimes exits with a success exit code (causing the docker container to stop) when you try to load the page. This seems to happen when you start a fresh instance of code-server on the same url and port (hence the browser cache from the older instance still being in place?). 

The command being used to run code-server is the same one as the official docker image, proxied by dumb-init:
`dumb-init code-server --host 0.0.0.0 --cert --auth password`
The docker run command used to start code-server is as follows:
`docker run -p 8080:8080 -p 4201:4200 -h <hostname> bit`

Clearing the browser cache for localhost:8080 seems to fix this issue. This leads me to believe that some value locally stored by code-server that doesn't fit the new instance causes it to exit (without an error).

I have attached screenshots of my browsers console log as well as the docker logs output.

<img width="1107" alt="Screenshot 2019-08-19 at 12 43 58" src="https://user-images.githubusercontent.com/20141618/63259713-6dc87680-c27f-11e9-9147-0a2f66c87cd4.png">
<img width="849" alt="Screenshot 2019-08-19 at 12 42 48" src="https://user-images.githubusercontent.com/20141618/63259719-73be5780-c27f-11e9-877e-e23ec06a2114.png">

**Comment by yuri2peter** [comment]
me too

**Comment by sr229** [comment]
I've never encountered this when I was using it on OpenShift. This is definitely worth investigating because this is definitely a show-stopper if it has a major impact.

**Comment by nhooyr** [comment]
See #1009
