### ISSUE TITLE
why “bash: nvidia-smi: command not found”

### ISSUE THREAD

**Issue by moon290** [cdr/code-server#922]
## Description

If I need to do something on deep learning，Should cuda and cudnn be installed in containers？

## Related Issues
terminnal：
coder@15a2d07c1ad2:~/project$ nvidia-smi
bash: nvidia-smi: command not found

**Comment by coadler** [comment]
This is something you would have to install yourself. It wouldn't make sense for us to ship nvidia drivers with `code-server`.

**Comment by sirgogo** [comment]
If you install [nvidia-docker2](https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)), you should be able to run the docker-run command with the `--runtime=nvidia` option. Then you can install cudnn/etc in your container, as needed.

**Comment by moon290** [comment]
Thank you. I get it

**Comment by coadler** [comment]
Thanks @sirgogo
