### ISSUE TITLE
Can't use arrow keys when lauching code-server at rc.local  script

### ISSUE THREAD

**Issue by xiangnanscu** [cdr/code-server#924]
- `code-server` version: 2.preview.7-vsc1.37.0 
- OS Version: ubuntu server 18.04 lts

## Steps to Reproduce

1. in `/etc/rc.local` write as:
```
#!/bin/bash 
code-server ~
exit 0
```
2. reboot the server, open browser and press arrow up key in terminal, you will get:
```
# ^[[A
```
And you can't use `git commit` even if you already set the git user :
```
# git add . && git commit -am "x"
*** Please tell me who you are.
```
If you manually start code-server at a regular shell, these problem don't exist.
I doubt some environment varibles is not loaded when using `rc.local`. So what is the right way to auto start code-server?

**Comment by BeckettOBrien** [comment]
If you want to create a service to auto-start `code-server`, look here:
#906

**Comment by xiangnanscu** [comment]
@BeckettOBrien  Git problem solved but still can't use arrow keys in terminals

**Comment by xiangnanscu** [comment]
Client environment is chrome 75 and mac os high sierra

**Comment by BeckettOBrien** [comment]
@xiangnanscu Do you still get this issue when you create a new terminal inside of vscode? I remember having trouble with the first terminal window opened, and I just had to create a new one.

**Comment by xiangnanscu** [comment]
@BeckettOBrien Still exits. But I find that it uses `sh` if autostart. `bash` if manually starting. Also, if you using `bash` in the sh, the problem disappears.
So the problem seems to be the use of `sh`(why not `bash`?)

**Comment by BeckettOBrien** [comment]
@xiangnanscu For now, I recommend trying to set the default shell to bash inside of vscode (if that doesn't work properly then just switch to bash every time you start it) And hopefully someone on the team will get to this and fix it.

**Comment by xiangnanscu** [comment]
@BeckettOBrien It works. Thank you.

**Comment by BeckettOBrien** [comment]
@xiangnanscu Great! But leave the thread open so that I team member can find a more permanent fix.

**Comment by sr229** [comment]
I'll be closing this issue and pin it for everyone so they have a reference for the workaround.

**Comment by code-asher** [comment]
Also see https://github.com/cdr/code-server/issues/918#issuecomment-524931986 for why this happens.
