### ISSUE TITLE
Reverse proxy Issue Related to Security Header (V2 Preview)

### ISSUE THREAD

**Issue by weikai** [cdr/code-server#925]
- `code-server` version: 2.preview.7-vsc1.37.0
- OS Version: Ubuntu

## Description

The reverse proxy on V2 Preview doesn't work.  It looked like there're issues with ws forwarding.

Error during WebSocket handshake: Invalid status line

Error: HTTP/1.1 400 Bad Request
    at ve.preHandleWebSocket (/src/build/code-server2.preview.8-vsc1.37.0-linux-x86_64-built/out/vs/server/src/cli.js:413:924)
    at ve.<anonymous> (/src/build/code-server2.preview.8-vsc1.37.0-linux-x86_64-built/out/vs/server/src/cli.js:411:549)
    at Generator.next (<anonymous>)
    at /src/build/code-server2.preview.8-vsc1.37.0-linux-x86_64-built/out/vs/server/src/cli.js:16:979
    at new Promise (<anonymous>)
    at r (/src/build/code-server2.preview.8-vsc1.37.0-linux-x86_64-built/out/vs/server/src/cli.js:16:756)
    at Server.onUpgrade (/src/build/code-server2.preview.8-vsc1.37.0-linux-x86_64-built/out/vs/server/src/cli.js:411:501)
    at Server.emit (events.js:189:13)
    at onParserExecuteCommon (_http_server.js:552:14)
    at onParserExecute (_http_server.js:500:3)

**Comment by RDMStreet** [comment]
+

**Comment by fbartels** [comment]
Hmm, I'm on 2.preview.11-vsc1.37.0 and dont have a problem with my reverse proxy (Nginx), also still using exactly the same config as the with last final release.

**Comment by weikai** [comment]
I'm using apache2 for reversed proxy server.  The same configuration works for codeserver V1 but not V2.

`RewriteEngine on
UseCanonicalName on
ProxyPreserveHost on
ProxyRequests off

RequestHeader set X-Forwarded-Proto https
RequestHeader set X-Forwarded-Port 443

RewriteCond %{HTTP:Upgrade}  =websocket [NC]
RewriteRule /(.*)            ws://192.168.19.11:9000/$1 [P,L]
RewriteCond %{HTTP:Upgrade}  !=websocket [NC]
RewriteRule /(.*)            http://192.168.19.11:9000/$1 [P,L]

#ProxyPass / http://192.168.19.11:9000/
#ProxyPassReverse / http://192.168.19.11:9000/
`

**Comment by sr229** [comment]
I don't think its our fault, you misconfigured your proxy hence this error appears. I can't replicate this issue at all at nginx and Apache

**Comment by weikai** [comment]
I'm using the Apache configuration documented at https://github.com/cdr/code-server/blob/master/doc/quickstart.md.  It works perfectly fine on V1 but not V2 preview


Reverse proxy config
![image](https://user-images.githubusercontent.com/2759725/64902246-b7836180-d671-11e9-98ba-9cb06a78484a.png)


The ws request should return 101 but returned 200 http status code
![image](https://user-images.githubusercontent.com/2759725/64902261-04ffce80-d672-11e9-8e1b-2f724749492d.png)


Same Apache reversed proxy config works fine on code-server code-server V1
![image](https://user-images.githubusercontent.com/2759725/64902297-b7379600-d672-11e9-816c-9f02b71dbde0.png)

**Comment by sr229** [comment]
@weikai You might need to do the debug yourself then PR a fixed config.

**Comment by waclaw66** [comment]
I have the same problem and I suspect that the problem is not in the Apache proxy config.
While accessing the code server directly without a proxy, it responds to the upgrade to websocket (?reconnectionToken) correctly by code 101. But accessing via proxy doesn't respond at all in my case. The question is why? The only thing what debug log of code server shows while upgrade request is:
`HTTP/1.1 400 Bad Request`

**Comment by sr229** [comment]
> I have the same problem and I suspect that the problem is not in the Apache proxy config.
> While accessing the code server directly without a proxy, it responds to the upgrade to websocket (?reconnectionToken) correctly by code 101. But accessing via proxy doesn't respond at all (using Fifrefox) or returns 200 with message _Error during WebSocket handshake: Invalid status line_ (using Chrome) in my case. The question is why? The only thing what debug log of code server shows while upgrade request is:
> `HTTP/1.1 400 Bad Request`

I suggest debugging it and see if its really code-server. I have never encountered this on GCP so I don't think it'd be an issue.

**Comment by weikai** [comment]
@sr229 Can you share your Apache2 configuration that you tested was working?  I'm trying to figure out the differences.  I've been Googling and testing different Apache2 configurations for 3 weeks but none of them have worked.

**Comment by sr229** [comment]
@weikai I use nginx so I was not able to reproduce it.

**Comment by sr229** [comment]
@weikai I used nginx so I was not able to reproduce it. I tried Apache breifly from the docs and it should work fine as well. I'll go raise this issue to the team to see if its really from our side.

**Comment by weikai** [comment]
Thank you @sr229.  I'm able to get Nginx working on the same testing server with no problem as well. However, my production server has to use Apache2 for various reasons.  It will be great to get Codeserver V2 working with Apache2 reverse server.
