### ISSUE TITLE
Using a toolchain inside another docker container

### ISSUE THREAD

**Issue by SomeGeek** [cdr/code-server#928]
I want to use code-server as a docker container. My development stack consist of other docker containers (on the same docker host), one of them containing the interpreter and other tools like preprocessors. Like [this](https://code.visualstudio.com/docs/remote/containers). Only, I cannot find any of the extensions mentioned in the list of extensions.

How do I configure something like that?

Edit: Just found out that you can install the Docker extension. I can, indeed, connect to a container. However, the integration is far from ideal. For example, the path to a interpreter binary can only exist on the local machine, not the container.

**Comment by SomeGeek** [comment]
Eclipse Che is quite different from code-server though, isn't it? It needs to be deployed on a Kubernetes or OpenShift cluster, which are both heavy on resources. I like the fact that code-server has a small footprint.

So it would be really nice if code-server would have sidecar-based tooling support.

**Comment by sr229** [comment]
I don't think we'd support such a use case that only a few users would benefit @SomeGeek. Likewise, you can do the same by figuring out how Che does sidecars for the IDEs. 

Also PS, Che is not a Cloud IDE, its a Workspace server that provides Cloud IDEs and Tooling.

**Comment by sr229** [comment]
I don't think we'd support such a use case that only a few users would benefit @SomeGeek. Likewise, you can do the same by figuring out how Che does sidecars for the IDEs. 

Also PS, Che is not a Cloud IDE, its a Workspace server that provides Cloud IDEs and Tooling.

**Comment by frank-dspeed** [comment]
@sr229 we simply need to get remote development extensions from vscode working after that all will work i run at present docker containers from inside a code-server container it was no problem i simply share the docker.socket and installed the same docker cli version inside the container it works all as expected

**Comment by sr229** [comment]
@frank-dspeed that's a initiative we're going to be evaluating if its worth implementing, we've already considered internally to implement a open source version of VSR, so let's wait and see.

**Comment by nhooyr** [comment]
We don't support remote docker like VS Code at the moment.
