### ISSUE TITLE
[v2] Eslint -e error in v2.

### ISSUE THREAD

**Issue by balazssoltesz** [cdr/code-server#932]
Eslint crashes with the -e error on v2.preview.9.
Eslint looking for a "-e" file in the same folder where i open a file.

**Comment by balazssoltesz** [comment]
is there any workaround on this? 
Its quite hard to work without eslint on javascript projects. 
We can't install more eslint extension on v1 (due to version incompatibility) and it's not working on v2. 
Is there any setting or little trick to make it work on v2?

**Comment by code-asher** [comment]
2.preview.11 will be up soon which will fix this issue. 
:running_man:

**Comment by balazssoltesz** [comment]
it works like a charm in preview.11
really really thank you
