### ISSUE TITLE
[v2] Missing meta tag in head to allow fullscreen webapp on iOS

### ISSUE THREAD

**Issue by ibanezbass** [cdr/code-server#933]
Adding a shortcut to home page allowed for the app to be launched full screen on v1. v2 is missing this feature.

**Comment by tdegrunt** [comment]
As a work-around you could first save it to home-page with v1 and then launch the v2 server.

**Comment by code-asher** [comment]
What tags do we need for this, anyway? I think in v1 they were all generated by webpack-pwa-manifest but we don't use that anymore.

**Comment by ibanezbass** [comment]
I believe this is it:

<meta name="apple-mobile-web-app-capable" content="yes">

**Comment by code-asher** [comment]
Thanks!
