### ISSUE TITLE
Error: unknown option --trust-proxy

### ISSUE THREAD

**Issue by tgkenney** [cdr/code-server#934]
- `code-server` version: v1.1156-vsc1.33.1 (Latest docker version)

## Description

I'm trying to set up code-server in docker behind a nginx reverse proxy.  According to the documentation I should be launching the container with `--trust-proxy` but when I try to add this the container errors out and exits with `error: unknown option '--trust-proxy'`

Has the required argument changed for reverse proxy use?  Launching the container without this and going to my external domain redirects to the internal IP of the container host instead

## Steps to Reproduce

1. Try and launch container with `--trust-proxy` 
1. Container exits with error

**Comment by code-asher** [comment]
Ah, --trust-proxy hasn't made it into the latest release so you 
can leave it out (the next version will remove that flag anyway).

I believe all it does though is change the IP address that is 
logged when there is a failed login attempt so I don't think it 
would solve the redirection issue you're experiencing. If you can, 
give v2 a try and see if it solves it.

**Comment by tgkenney** [comment]
Yeah I loaded up the preview of V2 on docker and everything works now. I'll probably just keep using that until the full release of V2
________________________________
