### ISSUE TITLE
How to hide the private key used by code-server (with --cert-key)

### ISSUE THREAD

**Issue by levifox54** [cdr/code-server#935]
For example, when running "code-server --cert-key=MyKey.key", how do I hide the MyKey.key from being viewed by "Open File..." or through the Explorer or through the terminal? Is there a way to let another user handle the encrypting/decrypting stuff maybe?

**Comment by cfi2017** [comment]
I ended up using an nginx proxy with SSL termination and no SSL certificate on code-server itself.

**Comment by levifox54** [comment]
nvm, i tried this but the same thing happened
```
Listen 8081
<VirtualHost *:8081>
  ServerName mysite.ca

  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /(.*)           ws://localhost:8080/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /(.*)           http://localhost:8080/$1 [P,L]

  ProxyRequests off

  RequestHeader set X-Forwarded-Proto https
  RequestHeader set X-Forwarded-Port 443

  ProxyPass / http://localhost:8080/ nocanon
  ProxyPassReverse / http://localhost:8080/
</VirtualHost>
```
