### ISSUE TITLE
about language server protocol support

### ISSUE THREAD

**Issue by chanrai** [cdr/code-server#936]
I can't run the follwing microsoft example in the code-server.

https://github.com/microsoft/vscode-extension-samples/tree/master/lsp-sample

can code-server supported the LSP(language server protocol) ?

**Comment by sr229** [comment]
@chanrai We explicitly use VSCode upstream so yes, we have LSP support baked in from day one. I suggest trying out v2 so you'll have a more optimized experience with developing with LSP.

**Comment by chanrai** [comment]
Thank you for your comment.

I tried to run the microsoft lsp-sample  by the latest version '2.preview.11-vsc1.37.0' , but it could not communicate with the Debug port 6009 by the browser(chrome). 

Can you give me some advice for running the lsp-sample code?

Best regards

**Comment by code-asher** [comment]
Closing in favor of https://github.com/cdr/code-server/issues/667. code-server doesn't support developing/debugging extensions yet.
