### ISSUE TITLE
Drag and drop file permission Error

### ISSUE THREAD

**Issue by zhijun1997** [cdr/code-server#937]
- `code-server` version: 2.preview.9-vsc1.37.0
- OS Version: Debian10, my own local server

## Description

I Try to upload files through web IDE, but I get the NoPermissions Error.
I pretty sure I have the right Permissions (i can write a test file in the terminal at the same position)

did the path problem? I saw a wried path at:

 Error: EACCES: permission denied, open '/\home\zhijun\work-space\
 --------------------------------------There ↑

i think it should be:```/home/zhijun/work-space/```
not the: ```/\home\zhijun\work-space\``` ?

## Steps to Reproduce

1. drag the png file in workspace
2. Get the Error:
```
Unable to write file (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/\home\zhijun\work-space\.code-server-partial-upload-a.png-8882c271-ce03-4805-b1a0-fc03525575d6')
```

--------------------------------
## Systemctl config File:
[Unit]
Description=VSCode Online Daemon
After=network.target

[Service]
User=zhijun
WorkingDirectory=/home/zhijun/work-space
ExecStart=/opt/code-server/code-server --user-data-dir=/home/zhijun/.vscode --port 8001

[Install]
WantedBy=multi-user.target

**Comment by brettplarson** [comment]
I believe we're also having this issue.

**Comment by yuri2peter** [comment]
I believe we're also having this issue +1.

**Comment by cjackson234** [comment]
any update?

**Comment by antofthy** [comment]
We are also seeing this same drag and drop error.
Backslashes used instead of forward-slashed.

**Comment by wilj** [comment]
+1 using the official docker image with a few additional packages, same error with backslashes instead of forward slashes:

Unable to write file (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/\home\coder\workspace\remote-development-stack\api\.code-server-partial-upload-test.txt-b3f6145b-2d9e-4999-bc88-d7e12cd6f5a5')

**Comment by sr229** [comment]
@code-asher I think the file upload service is doing something wrong, looks like it doesn't know how to convert back slashes to forward ones.

**Comment by code-asher** [comment]
Hopefully this is resolved with the latest version because we dropped
our upload service entirely since the VS Code team added their own.

Note that you'll need to use the 2.1698 image and not latest since that
tag been updated yet.

**Comment by wilj** [comment]
> Hopefully this is resolved with the latest version because we dropped our upload service entirely since the VS Code team added their own. Note that you'll need to use the 2.1698 image and not latest since that tag has not been updated yet.

Worked for me, thanks!

**Comment by sr229** [comment]
I think this is no longer persistent and relevant with current version so I'll close this off

**Comment by timsayshey** [comment]
Wait, the VS Code team added the "Upload Files" option was added to the file explorer? 

I'm running 2.1698 and I don't see any way to upload files when I right click.

Do I need a plugin or something?

![image](https://user-images.githubusercontent.com/1148940/73978034-197a8700-48f1-11ea-9ff5-4eee9ef4598e.png)

**Comment by nhooyr** [comment]
You need to drag and drop @timsayshey
