### ISSUE TITLE
[v2] --verbose and --log options don't do anything

### ISSUE THREAD

**Issue by zulrang** [cdr/code-server#939]
- `code-server` version: 2.preview.11-vsc1.37.0
- OS Version: Ubuntu 18.04.2 LTS (AWS EC2)

## Description

The --verbose and --log command flags don't have any effect.

## Steps to Reproduce

1. $ code-server (observe output)
1. $ code-server --verbose --log debug (output is the same)

**Comment by code-asher** [comment]
It looks like you're only looking at the terminal output? We only 
log a few lines of startup information there. Everything else goes 
into VS Code's logs (you can use the output panel in the IDE to 
view it) and the browser console.

**Comment by zulrang** [comment]
It's kind of hard to use the IDE to view the code-server logs when the process isn't working correctly and you cannot connect to it.

**Comment by code-asher** [comment]
Oof that's rough. code-server puts the logs in 
~/.local/share/code-server/logs by default so give that a scan if 
you can. It can also be helpful to check the browser console.

**Comment by zulrang** [comment]
Thanks!  That helps.
