### ISSUE TITLE
how to use another port rather than 8080 in v2

### ISSUE THREAD

**Issue by shahidul56** [cdr/code-server#944]
- `code-server` version: code-server2.preview.11-vsc1.37.0-linux-x86_64 
- OS Version: ubuntu 18

## Description

> error listen EADDRINUSE: address already in use :::8080

default 8080 port may cause problem with some common application which is necessary sometime . so how to change the default port to some other number like previous one 8443.
And is v2 support `--port 8443 `like input
![qwe](https://user-images.githubusercontent.com/11449967/64032953-4cb03180-cb6d-11e9-8f3a-1a68030554c5.PNG)

**Comment by code-asher** [comment]
You can use the --port flag with v2. Run code-server with --help 
to see all the available options.

**Comment by Miguelklappes** [comment]
> 
> You can use the --port flag with v2. Run code-server with --help to see all the available options.

What is the default command now? code-server doesn't work and I can't find anything in the docs, not sure if I'm being overly stupid here

**Comment by jsjoeio** [comment]
@Miguelklappes I figured it would be easier to show you. Here is a demo: 

https://user-images.githubusercontent.com/3806031/112367019-a8ce2f80-8c96-11eb-8b6c-d32422abc6f8.mp4

Let us know where you looked in the docs so we can update it!

**Comment by Miguelklappes** [comment]
> 
> 
> @Miguelklappes I figured it would be easier to show you. Here is a demo:
> Terminal.-.jp.jp@joes-mbp.-zsh.54x30.mp4
> 
> Let us know where you looked in the docs so we can update it!

Thank you so much for the video Joe! the thing is "code-server" command wasn't returning anything, even though it was installed (through a one-click app in Linode). So I manually installed it and everything works great now.

Again, thanks for your help!

**Comment by jsjoeio** [comment]
Hooray! Glad to hear it was an easy fix. No problem!

**Comment by oluwatunbi** [comment]
I got the same error connecting to code server to port 8080. i then used port 3000 but i got this error " couldn't connect to a server on this por
![code-server](https://user-images.githubusercontent.com/43700026/137607136-e995ed5f-938c-48e9-895a-083fe03e08f1.png)
t"

**Comment by sahilrajput03** [comment]
I found the default config for starting the code-server starting which works for systemctl is at path `~/.config/code-server/config.yaml` and we can change line in it there like that below:

```
bind-addr: 127.0.0.1:8082
auth: password
password: 9de9bb96df2c98d1a7074879
cert: false
```

So as you can see I modified the port number in line 1 from `8080` (default) to `8082` so now when system boots up it'll use that port number.

Also you can use below command to start using new port number right away: `sudo systemctl restart code-server@$USER` as well.
