### ISSUE TITLE
Code server (on digital ocean) crashing after php install

### ISSUE THREAD

**Issue by sincorecom** [cdr/code-server#946]
So I'm not sure where to start here everything was working fine on a new setup of code server on digital ocean. Then I installed php 7 so that code server can do it's debugging thing. Since that code server randomly crashes every 10 min or so and requires a reboot to start. Any help would be great.

**Comment by sr229** [comment]
Requesting further information. Failure to reply means it was fixed in your end and I'll close this automatically after 3 days.
