### ISSUE TITLE
can not install Chinese (Simplified) Language Pack for Visual Studio Code

### ISSUE THREAD

**Issue by ywuiaayydev** [cdr/code-server#948]
- `code-server` version:  last
- OS Version: arch
- Extension: Chinese (Simplified) Language Pack for Visual Studio Code

## Steps to Reproduce

1. 
1.

**Comment by Hcyan-H** [comment]
我下载了1.33.1的vsix包，然后安装成功了，结果，切换不了

**Comment by sr229** [comment]
@ywuiaayydev Please confirm the latest v2 fixes your issue?

**Comment by maplebeats** [comment]
it still not work on 2.1485-vsc1.38.1

**Comment by code-asher** [comment]
@maplebeats could you try restarting code-server once? It looks 
like we have a bug with changing the language while code-server is 
still running. I'm looking into it now.

**Comment by LeuisKen** [comment]
![image](https://user-images.githubusercontent.com/7701575/65286920-ddc66700-db73-11e9-9a0a-739cddb48f8f.png)

Works in my local environment. Release 2.1523-vsc1.38.1

**Comment by maplebeats** [comment]
> @maplebeats could you try restarting code-server once? It looks like we have a bug with changing the language while code-server is still running. I'm looking into it now.

it works on 2.1523-vsc1.38.1

**Comment by sr229** [comment]
Looks like everyone reports this as fixed now but we'll wait for @code-asher to fix it if there's anything to fix

**Comment by FanyangMengDev** [comment]
I have aloready tried for many times and it still displays that I cannot install the Chinese language pack in the latest binary.
Could you please have a check on it?
