### ISSUE TITLE
 Loading too slowly

### ISSUE THREAD

**Issue by ThePartyOfGUN** [cdr/code-server#949]
Why the size of **workbench.api.js**  is so large in version 2. Due to my slow network speed to cloud server, it takes at least 1.7 min to load the full UI. But in version 1, it just take serveral seconds to load. ![image](https://user-images.githubusercontent.com/29013148/64087780-180cc780-cd71-11e9-8edc-cb8f69857a6a.png)

**Comment by code-asher** [comment]
It looks like I forgot to minify the latest pre-release. Normally 
it will be 5.4 MB although that's still about 2 MB bigger than v1 
(I'll be checking some time soon to see if we can shrink it any). 
We also don't have caching enabled yet. Once we do that subsequent 
loads should be very quick.

**Comment by sr229** [comment]
Since we're not hearing anymore from OP, I'm writing this off as fixed.
