### ISSUE TITLE
Error when auto upgrading: Unable to write file (Error: unexpected end of file)

### ISSUE THREAD

**Issue by xiangnanscu** [cdr/code-server#950]
- `code-server` version: 
v10.15.1
- OS Version: 
ubuntu 18.04
## Description
I'm prompt to upgrade so I click ok and then failed `Unable to write file (Error: unexpected end of file)`

## Steps to Reproduce
none. the code-server popup a window prompt
1. 
1.

**Comment by code-asher** [comment]
Ah, this is for v2 right? Currently auto-update won't work because 
we have no real releases for v2. I should probably have a check 
for that case, but since it will only happen until we publish a 
real version I haven't put a high priority on it.

**Comment by xiangnanscu** [comment]
Yeah baby. Thanks.
