### ISSUE TITLE
Wish adding an icon to show the connection status with the server

### ISSUE THREAD

**Issue by phoenixsfly** [cdr/code-server#951]
While I was writing code, my computer was disconnected from the server for some reason, but I didn't know.
I pressed Ctrl+S to save the file and close the browser, but there was no doubt the file wasn't saved -- I had no idea I was disconnected from the server.
So I wanted to be able to add an icon to show the status of the browser's communication with the server.
Thank you very much!

**Comment by sr229** [comment]
I'll be marking this as a wontfix since this should be raised on VSCode Web. This is not something we can do on our end because VSCode Web is on early stages so expected for such to apper.

**Comment by sr229** [comment]
@code-asher Actually I think we can use the VSCode Remote status used in the status bar for this, wdyt?

**Comment by code-asher** [comment]
VS Code web ended up adding an indicator before we did. It's in latest master and there will be another pre-release soon. They implemented it as a full-screen notification so there's no missing it.
