### ISSUE TITLE
Cannot close the window if open the url in electron

### ISSUE THREAD

**Issue by yamajik** [cdr/code-server#953]
Cannot close the window while opening the code server url in electron

## Steps to Reproduce

1. start a code server
2. open the code server url from <a> as a new window in electron
3. the window close button is useless

**Comment by yamajik** [comment]
The problem is onbeforeunload(return or returnValue) hook not work as usual in eletron

**Comment by nhooyr** [comment]
If this still occurs, please feel free to reopen.
