### ISSUE TITLE
Jupyter Notebook Connection Fails when Connecting to Custom NGINX URI 

### ISSUE THREAD

**Issue by sshantt** [cdr/code-server#954]
- `code-server` version: 2.preview.11-vsc1.37.0
- OS Version: Ubuntu 18.04.2 LTS

## Description

I'm running a Jupyter notebook with a c.NotebookApp.base_url that allows me to access it using web.page.com/jupyter/?token=1234. Its running on the same server code-server is running on. When I set the "python.dataScience.jupyterServerURI" as localhost:8888/jupyter/?token=1234 I am able to start and use a Jupyter notebook on my local ssh instance of VScode. However when I try to do the same in my code-server web server using web.page.com/jupyter/?token=1234 or localhost:8888/jupyter/?token=1234 I get an error saying 

```
Failed to connect to remote Jupyter notebook. 
Check that the Jupyter Server URI setting has a value running server specified. 
http://localhost:8888/ Error: Invalid response 404 Not Found

Source:Python (Extension)
```

## Steps to Reproduce

1. Setup Jupyter Notebook with c.NotebookApp.base_url
2. Install python extension 
2. Set "python.dataScience.jupyterServerURI" to localhost:port/base_url
3. Open a Python file and run a Jupyter notebook script to invoke Python Interactive Jupyter Notebook

**Comment by nhooyr** [comment]
We're not really familiar with jupyter notebook, if this still occurs, please feel free to reopen.
