### ISSUE TITLE
[v2] Bracket Pair Colorizer extension error

### ISSUE THREAD

**Issue by balazssoltesz** [cdr/code-server#955]
v2.preview.11

Bracket Pair Colorizer extension throws the following error message:

> Activating extension 'CoenraadS.bracket-pair-colorizer' failed: Cannot find module 'prismjs'.

**Comment by frank-dspeed** [comment]
@balazssoltesz  Issue #982 is related and has a working workaround for the issue

**Comment by EnKrypt** [comment]
Another thing to note is that there is now also Bracket Pair Colorizer v2, which is supposed to be a ground up rewrite by the same author that makes use of some built-in VS Code features.

Although it's in beta, I've used it without any issues, so maybe you can look into that and see if it makes a difference.

**Comment by balazssoltesz** [comment]
> Another thing to note is that there is now also Bracket Pair Colorizer v2, which is supposed to be a ground up rewrite by the same author that makes use of some built-in VS Code features.
> 
> Although it's in beta, I've used it without any issues, so maybe you can look into that and see if it makes a difference.

Indeed. Perfect.
