### ISSUE TITLE
Live Server doesn't work

### ISSUE THREAD

**Issue by realmayus** [cdr/code-server#958]
- `code-server` version: 1.1156
- OS Version: Mac OS 10.13.6
- Extension: Live Server

## Description

When trying to "open in live server", I get this error message:
![Screen Shot 2019-09-06 at 23 01 54](https://user-images.githubusercontent.com/38134006/64460314-5e0fb580-d0fa-11e9-9c29-046b99daee79.png)

## Steps to Reproduce

1. Download Live Server
2. Press F1 and select Open with Live Server

**Comment by Nick-Hopps** [comment]
The same

**Comment by cespedesj** [comment]
Same problem here.

**Comment by frank-dspeed** [comment]
#990 is related

**Comment by sr229** [comment]
Tested out Live Server today, it works properly now.

**Comment by realmayus** [comment]
Thanks
