### ISSUE TITLE
how to retore code-server from sleeping without refreshing page?

### ISSUE THREAD

**Issue by xiangnanscu** [cdr/code-server#960]
## Description
My code-server is running at Ubuntu 18.04 Server and it's set to be always running. The client OS is windows or mac os. When I wake the client OS from sleeping I need to refresh the page in the browser to use code-server.

**Comment by sr229** [comment]
If you're using docker, you can always set the Restart policy to Always so it starts even on boot (Docker already starts on startup on Docker for Windows and macOS).

**Comment by xiangnanscu** [comment]
@sr229 the code-server is running at Ubuntu 18.04 Server and it's set to be always running. The client OS is windows or mac os. When I wake the client OS from sleeping I need to refresh the page in the browser.

**Comment by sr229** [comment]
I think in v2 this shouldn't be the case anymore @xiangnanscu

**Comment by sr229** [comment]
we already documented starting up code-server on boot. Closing.
