### ISSUE TITLE
Can't install Language Support for Java by RedHat

### ISSUE THREAD

**Issue by jtuttas** [cdr/code-server#961]
- Docker Image on Ubuntu 18.04
- Ubuntu 18.04
- Language Support for Java(TM) by Red Hat redhat.java

## Description

Hi, when I try to install the Language Support for Java by ReadHat, I've got the error message "_Unable to install because, the extension 'redhat.java' compatible with current version '1.33.1' of VS Code is not found._"

## Steps to Reproduce

1. Run the docker container
1. install the extension

**Comment by jtuttas** [comment]
Ok great the v2 container works perfect!

**Comment by sr229** [comment]
@jtuttas nice to see you're up to speed now, let us know if you encounter further hiccups.

**Comment by Avinashachu007** [comment]
Getting the same error. Iam using the latest docker image of code server

![image](https://user-images.githubusercontent.com/12245421/72203030-71f26c00-348c-11ea-9afd-c4a31c704a54.png)
