### ISSUE TITLE
[v2] Terminal fails to spawn properly

### ISSUE THREAD

**Issue by Mackaber** [cdr/code-server#964]
## Description

When I want start a terminal it gets stuck at "Starting..."

I'm using code-server2.preview.11-vsc1.37.0-linux-x86_64
in Version 76.0.3809.132 (Official Build) (64-bit) on MacOS El Capitan

## Related Issues

#194

**Comment by sr229** [comment]
No longer happening on v2 GA releases so this is closed.

**Comment by alan-he** [comment]
Version: 1.41.1
Commit: f51e045cd5483561afc07694f39307fb673b6d1d
Date: 2020-01-17T22:58:55.612Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
Code Server Version: 2.1698-vsc1.41.1

Occasionally, this version codeserver terminal still occur this phenomenon and stuck at "starting"

**Comment by kylecarbs** [comment]
Weird, I'm unable to reproduce. Is there anything you notice that could be affecting it? (like high latency, slow network, etc.)

**Comment by alan-he** [comment]
> Weird, I'm unable to reproduce. Is there anything you notice that could be affecting it? (like high latency, slow network, etc.)

Yes, often occurred in slow network, and one or tow times occurred in the long period of no operation

**Comment by kylecarbs** [comment]
Hm. Any ideas @code-asher ?

**Comment by code-asher** [comment]
I haven't had any luck reproducing it by simulating latency; the
terminal always comes up eventually. Is there any information in the
browser console? It might also help to run code-server with `--verbose`.

**Comment by ming0520** [comment]
![image](https://user-images.githubusercontent.com/31769920/80224034-bbea1100-867b-11ea-858b-da76f8eb6ce8.png)
I am also facing this problem, im using code-server2.1692-vsc1.39.2-linux-x86_64. on Ubuntu 18.04 LTS hosted on gcp

**Comment by ming0520** [comment]
> ![image](https://user-images.githubusercontent.com/31769920/80224034-bbea1100-867b-11ea-858b-da76f8eb6ce8.png)
> I am also facing this problem, im using code-server2.1692-vsc1.39.2-linux-x86_64. on Ubuntu 18.04 LTS hosted on gcp

solution: code-server --verbose --auth none
only --verbose doesn't work for me
