### ISSUE TITLE
Extension Registry has broken extensions

### ISSUE THREAD

**Issue by sr229** [cdr/code-server#971]
## Description

There's a percentage of extensions in the cdr registry that are distributed incorrectly. One of the most prominent ones is the Discord extension because its dist files are missing. I encourage eveyrone to report broken extensions here as well.

**Comment by frank-dspeed** [comment]
#990 is related

**Comment by aptalca** [comment]
I'm getting the following errors when trying to use some of the extensions (install is completed successfully)

`Activating extension 'redhat.vscode-yaml' failed: Cannot find module 'vscode-languageclient'.`

and

`Activating extension 'DavidAnson.vscode-markdownlint' failed: Cannot find module '/config/extensions/davidanson.vscode-markdownlint-0.30.2/bundle'.`

These were both working fine with code-server v1

**Comment by nhooyr** [comment]
See #1299
