### ISSUE TITLE
CentOS 7 support

### ISSUE THREAD

**Issue by MrMoronIV** [cdr/code-server#973]
Please provide a binary that runs on CentOS 7, this project seems promising but I can't get it to run on CentOS 7 with the provided linux binary

**Comment by MrMoronIV** [comment]
Well, fyi, the latest preview release as of today runs without any hassle, so somebody took care of it :)

On the other hand, if it was such an obvious and frequently asked question, why not put something into the readme so people know. Believe, I've searched the tickets to look for a solution first.

**Comment by sr229** [comment]
> Well, fyi, the latest preview release as of today runs without any hassle, so somebody took care of it :)
> 
> On the other hand, if it was such an obvious and frequently asked question, why not put something into the readme so people know. Believe me, I've searched the tickets to look for a solution first.

We don't need to document such since we're doing the support in the CI side already.
