### ISSUE TITLE
Scrolling broken in Firefox (newest pre-release only)

### ISSUE THREAD

**Issue by dx034** [cdr/code-server#976]
- `code-server` version: 2.1472-vsc1.38.1
- OS Version: Ubuntu 18.03 LTS

## Description

With the newest pre-release, scrolling isn't working in Firefox 69 in any window. Scrolling works fine in Chrome. The bug didn't occur with last week's pre-release. I skipped two pre-releases so I'm not sure which commit introduced the bug.

## Steps to Reproduce

1. Use code-server in Firefox

**Comment by sr229** [comment]
We're gonna be digging a whole lot of history but I think @code-asher has an idea.
