### ISSUE TITLE
Recent folders are not saved

### ISSUE THREAD

**Issue by partyka1** [cdr/code-server#977]
- `code-server` version: code-server1.1156-vsc1.33.1-linux-x64
- OS Version: ubuntu 18.04 digitalocean

## Description

Recent folders are not saved

## Steps to Reproduce

1. Open some folder using File > Open Folder
2. Repeat few times
3. Recent folders do not show last visited places: 
![image](https://user-images.githubusercontent.com/19314216/64871320-4b8b0400-d645-11e9-802c-1092ab12facd.png)

**Comment by sr229** [comment]
@partyka1 give v2 a try. v1 is already a deprecated version and we won't be issuing fixes in v1.

**Comment by sr229** [comment]
@partyka1 give v2 a try. v1 is already a deprecated version and we won't be issuing fixes in v1.

**Comment by sr229** [comment]
based on my recent testing this is not the case anymore for v2. Closing.
