### ISSUE TITLE
Open different project on separate browser tabs

### ISSUE THREAD

**Issue by partyka1** [cdr/code-server#980]
I want to be able to open different projects/folders on different tabs in chrome. Right now, when you open project on TAB1, then open other project on TAB2, after refreshing(for any reason) TAB1 it shows you content of TAB2, but it should show the last state before refreshing, of TAB1

**Comment by sr229** [comment]
We already have this on v2. Simply append a folder query parameter @partyka1 , do it like this: 

``https://asatomi.fedora.local/cdr/asatomi?folder=/home/asatomi/projects/code-server``

**Comment by sr229** [comment]
@partyka1 I don't think we need to support this moving forward as we want to be close to Microsoft upstream. It's too much effort to do this and a lot of patching. You may however append a `folder` parameter per tab in v2, like this: ``https://asatomi.fedora.local/cdr/asatomi?folder=/home/asatomi/projects/code-server``

**Comment by sr229** [comment]
Closing this off as a wontfix since we want to use as minimal patches with VSCode as possible, and this does not merit the effort. If you want this feature, raise it on VSCode Web, not here.
