### ISSUE TITLE
[v2] Trying to copy within Terminal is broken

### ISSUE THREAD

**Issue by sr229** [cdr/code-server#985]
- `code-server` version: `master` LKGR (1.38.1 Upstream)
- OS Version: Ubuntu 18.04.03 LTS on Hyper-V

## Description

Trying to copy from the terminal will break code-server. This used to work up until the current LKGR.

## Steps to Reproduce

1. Spawn Terminal
1. Highlight selection and hit Ctrl+C

![image](https://user-images.githubusercontent.com/14976516/64919453-727c3e00-d7dd-11e9-8d0a-0b0ea0ef7c66.png)

**Comment by sr229** [comment]
Checking console, this error pops up:

```
TypeError: Cannot set property 'open' of undefined
    at extensionHostWorker.js:586
    at Function.t._safeInvokeFunction (loader.js:1014)
    at Function.t._invokeFactory (loader.js:1033)
    at t.complete (loader.js:1046)
    at s._onModuleComplete (loader.js:1663)
    at s._resolve (loader.js:1623)
    at s.defineModule (loader.js:1274)
    at o (loader.js:1713)
    at extensionHostWorker.js:586
    at extensionHostWorker.js:587
r @ loader.js:267
```

**Comment by maplebeats** [comment]
i have then same question when use  chromium on ubuntu18.04

**Comment by sr229** [comment]
> i have then same question when use chromium on ubuntu18.04

Try running it on localhost and see if that works. The reason for this is because the browser prevents clipboard access on insecure remotes.

**Comment by maplebeats** [comment]
> > i have then same question when use chromium on ubuntu18.04
> 
> Try running it on localhost and see if that works. The reason for this is because the browser prevents clipboard access on insecure remotes.

ubuntu only? my mac's chromium works well.

**Comment by sr229** [comment]
@maplebeats all versions of Chromium regardless of platform is affected.

**Comment by darkdragn** [comment]
This is going to sound a little stupid, but Chrome only did this to me if the connection was untrusted. 

As soon as I got an SSL Cert from a trusted source, it started working like a charm. Both copy and paste, I just needed that site "Allow Access to Clipboard" setting to be tripped. This applies to both the linux chromium, running on CentOS and Chrome OS' browser.

So, sorry to be the barer of bad news, but it looks like it's a Chrome Permissions issue, that applies to untrusted connections, not something the code server guys can do anything about.

**Comment by sr229** [comment]
> This is going to sound a little stupid, but Chrome only did this to me if the connection was untrusted.
> 
> As soon as I got an SSL Cert from a trusted source, it started working like a charm. Both copy and paste, I just needed that site "Allow Access to Clipboard" setting to be tripped. This applies to both the linux chromium, running on CentOS and Chrome OS' browser.
> 
> So, sorry to be the barer of bad news, but it looks like it's a Chrome Permissions issue, that applies to untrusted connections, not something the code server guys can do anything about.

I did hear `localhost` and `.local` (avahi-daemon domains) are exempt from this, butyeah what @darkdragn said.

**Comment by oldrichsmejkal** [comment]
Not sure how they achieve it, but in Jupyter lab copying (from Terminal with ctrl+c) working without any issue, even on non trusted site 
(Ubuntu 18 on DigitalOcean as remote and Chrome in Windows 10 as local - same setup as I am trying with code-server)

**Comment by oldrichsmejkal** [comment]
I think this quite kills usability for many users. Working without clipboard is quite hard some times..

**Comment by sr229** [comment]
> I think this quite kills usability for many users. Working without clipboard is quite hard some times..

I think you should raise this to Chromium, this is beyond our control sadly, and we're not going to compromise code quality for features which might make it hard to maintain over time.

**Comment by code-asher** [comment]
Closing to consolidate into #1106.

**Comment by oldrichsmejkal** [comment]
> > I think this quite kills usability for many users. Working without clipboard is quite hard some times..
> 
> I think you should raise this to Chromium, this is beyond our control sadly, and we're not going to compromise code quality for features which might make it hard to maintain over time.

It doesn't work in any browser as far as I know. 
Definitely not in Firefox/Vivaldi.
So raising issue to Chromium doesn't make much sense...

Maybe it would be better to make this work as it is elsewhere, than insist on solution purity...
