### ISSUE TITLE
[V2] SCM Diff contextual menu

### ISSUE THREAD

**Issue by elgandoz** [cdr/code-server#988]
- `code-server` version: = 2.1472 & 2.1478
- OS Version: CentOS / RHEL 7

## Description
In the SCM 'Working Tree' diff view, the contextual menu for commits is missing/different.
That is a very handy way to commit selected hunks.
The menu is visible in code-server v1 and in code 1.38.1.

The action is still available via command palette.

## Steps to Reproduce

1. Modify a file in a git repo 
1. Go to the SCM view, and click the modified file
1. Right click on the modified line

*code-server v2.1472-vsc1.38.1*
<img width="449" alt="Screen Shot 2019-09-17 at 08 49 36" src="https://user-images.githubusercontent.com/5859926/64998799-e9721d80-d928-11e9-9901-c380b08cdfcd.png">

*regular code v1.38.1*
<img width="595" alt="Screen Shot 2019-09-17 at 08 49 54" src="https://user-images.githubusercontent.com/5859926/64998805-f0009500-d928-11e9-89cd-0b1cb13673a2.png">

**Comment by sr229** [comment]
@code-asher

**Comment by code-asher** [comment]
Should be fixed by https://github.com/cdr/code-server/commit/7e4a73ce2d19eee08ceea25113debefeb8ac27e2.

**Comment by elgandoz** [comment]
I can confirm the contextual menus (stage selected range, etc) are appearing now.  Thanks heaps
