### ISSUE TITLE
Adding folders to Workspace not working

### ISSUE THREAD

**Issue by Creling** [cdr/code-server#989]
## env
1. code-server version: `code-server2.1485-vsc1.38.1`
2. OS version: Ubuntu 18.04
## description
first, I succeed to create a workspace via `File -> Open Folder...`， but when I want to add another folder to current workspace, the `code-server` is unresponsive.

![1gCExeo1yP](https://user-images.githubusercontent.com/43109504/65007911-21ce2780-d93a-11e9-89c9-3dba61b59c4e.gif)

**Comment by frank-dspeed** [comment]
@Creling can you change the title to "Adding folders to Workspace not working"

**Comment by Creling** [comment]
> @Creling can you change the title to "Adding folders to Workspace not working"

Done

**Comment by frank-dspeed** [comment]
@code-asher should look into this

**Comment by frank-dspeed** [comment]
@Creling i looked into this v2 does not even have menu items for that but it is generaly working

i created the .code-workspace file from hand and opened it i also added pathes and it works like a charm

```json
{
	"folders": [
		{
			"path": "."
		},
		{
			"path": ".."
		}
	],
	"settings": {}
}
```

**Comment by sr229** [comment]
Raising as urgent due to the nature of the usage of the bug.

**Comment by nhooyr** [comment]
If this is still a problem, please feel free to reopen.
