### ISSUE TITLE
What is blocking us from using the Offical MarketPlace

### ISSUE THREAD

**Issue by frank-dspeed** [cdr/code-server#990]
Please line out and share any details about the issues with the Offical MarketPlace used by vscode.

**Comment by frank-dspeed** [comment]
#971 is related

**Comment by sr229** [comment]
As outlined within Visual Studio's ToS, we cannot use their official marketplace - hence this limitation. The only way to distribute extensions is to write our own. Closing as a `wontfix` - until Microsoft's position changes, we won't be revisiting this further.

**Comment by Logunov** [comment]
Some workaround:
```bash
SERVICE_URL='https://CUSTOM_MARKETPLACE/_apis/public/gallery/' ./code-server ...
```

**Comment by frank-dspeed** [comment]
@sr229  so you say the only problem is that microsoft does not allow that? no tech issues? I can talk to them to fix that i have frinds working there and i know some managers related to OSS

**Comment by frank-dspeed** [comment]
https://cdn.vsassets.io/v/M146_20190123.39/_content/Microsoft-Visual-Studio-Marketplace-Terms-of-Use.pdf i see no issues at present please line out the relevant sections so i can talk to them and request a change!

**Comment by sr229** [comment]
This has been highly requested but it has never been considered by MS. We technically can support VSM but we will be in trouble for that. Even our folks at Theia is not allowed to use the marketplace.

**Comment by sr229** [comment]
As for ToS, refer to the Acceptable Policy Clause. Any type of service that uses the marketplace that isn't related to VS Code itself is considered breaking the terms as it is not the official way to get extensions.

**Comment by frank-dspeed** [comment]
@sr229 out of my point of view this product is vscode it self ! Will ask a lawyer from MS as this is build on top of vscode and its allowed to modify vscode and still use the marketplace this is no issue. 

My Privat IT Lawyer from Germany also told me he does not see any problems Over 90% of the code is vscode the changes  here are not breaking that fact. Its a Simpl Patch and some Additions. All is allowed out of the OSS Licence

**Comment by sr229** [comment]
> @sr229 out of my point of view this product is vscode it self ! Will ask a lawyer from MS as this is build on top of vscode and its allowed to modify vscode and still use the marketplace this is no issue.
> 
> My Privat IT Lawyer from Germany also told me he does not see any problems Over 90% of the code is vscode the changes here are not breaking that fact. Its a Simpl Patch and some Additions. All is allowed out of the OSS Licence

We are not, however, a official Microsoft product, and the marketplace is for official Microsoft products **ONLY**. The only reason why the likes of VSCodium is allowed is because of its unmodified VSCode with telemetry. It's not a case of using the code, its a case of a proprietary registry prohibiting third party distributions to use their marketplace. We won't be discussing this any further.

**Comment by sr229** [comment]
Locking this down to prevent more conflicts. See @chrisdias's input on this - [link](https://github.com/microsoft/vscode/issues/81173#issuecomment-533332743).
