### ISSUE TITLE
Enforce user permissions for user data and extension dirs on container startup

### ISSUE THREAD

**Issue by frank-dspeed** [cdr/code-server#992]
## Description
When we start code-server as a docker container and mounting a path for extensions we need to make sure on startup that it belongs to the same user as the code-server

## Steps to Reproduce
use the oneliner from README.md

## Result

```bash
docker run -it -p 127.0.0.1:8080:8080 -v "${HOME}/.local/share/code-server:/home/coder/.local/share/code-server" -v "$PWD:/home/coder/project" codercom/code-server
(node:6) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ERROR { [Error: EACCES: permission denied, mkdir '/home/coder/.local/share/code-server/extensions']
  [stack]:
   'Error: EACCES: permission denied, mkdir \'/home/coder/.local/share/code-server/extensions\'',
  [message]:
   'EACCES: permission denied, mkdir \'/home/coder/.local/share/code-server/extensions\'',
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/coder/.local/share/code-server/extensions' }

```

**Comment by frank-dspeed** [comment]
or we add instructions for mkdir -p befor running that and chmod 0777 so that it will work

**Comment by DDeme** [comment]
I got the same problem.

**Comment by sr229** [comment]
This is a open field of debate at the moment as one of the Engineers declined to have the RW access workaround due to "permission concerns" - where it shouldn't. Revisiting this once more.

**Comment by frank-dspeed** [comment]
@sr229 but this issue is about the extensions dir i think there the discussion is less relevant as it is always clear that extensions need to be readwrite by code-server user it self its not about the project files

**Comment by nhooyr** [comment]
Yes this is a separate issue. But closely related to #640

**Comment by mukk85** [comment]
I am still getting this error. Are we waiting for an updated push for this to be fixed?

**Comment by frank-dspeed** [comment]
@mukk85 current state is you manualy create the extensions dir befor you run the oneliner and chmod the folder right befor you start the oneliner

because when docker creates the folder while starting it will be owned by root

**Comment by mukk85** [comment]
@frank-dspeed even when I create the directory and chmod the code-server directory to 0777 I still get the error.

**Comment by pedrolucasoliva** [comment]
Running:
`docker run -d -p 0.0.0.0:8000:8080 --name codeserver -v "/home/dev/codeserver/.local/share/code-server:/home/coder/.local/share/code-server" -v "/home/dev/projects:/home/coder/project"  codercom/code-server:v2`
I resolve this problem with:
`sudo chmod 777 -R dev/`

**Comment by sr229** [comment]
mode `0777` is a dangerous permission to give since it gives R/W and execution perms, you should only give it R/W perms (mode `0600` AFAIK).

**Comment by frank-dspeed** [comment]
@pedrolucasoliva 
i am docker specialist i give you a little hint the --user flag
```
docker run --user $(id):$(id) -d -p 0.0.0.0:8000:8080 --name codeserver -v "/home/dev/codeserver/.local/share/code-server:/home/coder/.local/share/code-server" -v "/home/dev/projects:/home/coder/project" codercom/code-server:v2
```

the --user $(id):$(id) will switch the user id of the coder user to your user id and group :)

**Comment by CXZ7720** [comment]
I still have same issue on Ubuntu server 18.04 LTS
![image](https://user-images.githubusercontent.com/29659112/70790073-a1538180-1dd7-11ea-84e9-512513297ae9.png)

**Comment by nhooyr** [comment]
See https://github.com/cdr/code-server/issues/1307
