### ISSUE TITLE
"yarn install" fails

### ISSUE THREAD

**Issue by oonqt** [cdr/code-server#995]
Yarn: 1.16.0
Node: 10.16.3
OS: Ubuntu 18.04
Starting occurring at release: 2.1472-vsc1.38.1
Commands ran:
    `git clone https://github.com/cdr/code-server.git`
    `cd code-server`
    `yarn install`

Output: [Output: https://paste.memester.cf/asovayiwuc.bash](Output: https://paste.memester.cf/asovayiwuc.bash)

**Comment by code-asher** [comment]
If you're trying to develop you'll need to be inside VS Code. See the readme: https://github.com/cdr/code-server#development. If you're just trying to build it, see the build section in the readme instead: https://github.com/cdr/code-server#build.
