### ISSUE TITLE
Show message when service workers are blocked

### ISSUE THREAD

**Issue by frank-dspeed** [cdr/code-server#997]
- `code-server` version:v2
- OS Version: docker image

## Description
console output on extension install
```
Service Workers are not enabled. Webviews will not work properly
Blocked script execution in 'http://0.0.0.0:8080/webview/fake.html?id=extensionEditor' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.
```

## Steps to Reproduce

open code-server install remote workspace extension

**Comment by sr229** [comment]
@code-asher I'm sure we did have service workers enabled for some builds but we have them disabled by default somehow, hence this error.

**Comment by code-asher** [comment]
Unfortunately service workers will only work over secure origins (`localhost`/`127.0.0.1` or `https`). You'll need to browse using something other than `http://0.0.0.0`. :cry:

**Comment by code-asher** [comment]
Re-opening though because we should have some sort of message explaining what's going on to the user. Also, while some of the webview stuff won't work you should still at least be able to see an extension's data. Are you just trying to view an extension's README or something?

**Comment by frank-dspeed** [comment]
@code-asher yes i can see the general data like the readme all is working it only hangs on install but then finishes correctly. i will try the https suggestion and i think we should stop then supporting running under http as it makes no sense to run a product in a inconsistent state.

**Comment by frank-dspeed** [comment]
i think this needs to be documented directly in the readme with high priority

**Comment by frank-dspeed** [comment]
@code-asher i browse using localhost;8080 but that redirects to a code-server instance bound to 0.0.0.0 which means all devices in nodejs so it listens on 0,0.0,0:8080 => 172.168.22.1:8080
but the browser calls http://localhost:8080

**Comment by frank-dspeed** [comment]
ah so the url in the error is wrong!!!! this is some how set by code-server as it is the listing url not the calling url

**Comment by sr229** [comment]
> i think this needs to be documented directly in the readme with high priority

I say we hold it for now. I'm opening a line of dialogue within the Chromium developers regarding reserved internal IP CIDRs for service workers and clipboard API. 

> @code-asher yes i can see the general data like the readme all is working it only hangs on install but then finishes correctly. i will try the https suggestion and i think we should stop then supporting running under http as it makes no sense to run a product in a inconsistent state.

Forcing HTTP/S is not exactly a good state either - this is where some of the complexity Kubernetes had as well because of its strict requirement for HTTP/S (which is understandable).

Again, refer to my response - I'm still opening a line of dialogue with the Chromium team regarding to consider allowing internal CIDRs to use HTTP/S-restricted features.
