### ISSUE TITLE
[v2] Tasks not working in any way

### ISSUE THREAD

**Issue by choephix** [cdr/code-server#999]
- Using official docker image, tagged "v2" (although I first noticed this in "2.1472-vsc1.38.1") 
- On a Google Cloud vm instance (Debian 9.9 installed).

## Description

There seems to be a problem with VSCode Tasks.

* Clicking on "Run Task" in the 'Terminal' menu does not load the popup, asking me which task to run. Nothing happens, other than "Activating Extensions" showing up with a spinner for a few seconds on the bottom left.

![image](https://user-images.githubusercontent.com/962412/65163242-4530c980-da43-11e9-92ac-248793c1f485.png)

* Clicking on "Configure Tasks..." in the 'Terminal' menu does show the popup on the top center, with text "Select tasks to configure" with no tasks listed, even if there is a '.vscode/tasks.json' file.
The loading animation never ends.

![image](https://user-images.githubusercontent.com/962412/65163699-12d39c00-da44-11e9-99ec-e328d6ef61fc.png)

* Any extensions that manage or rely on tasks also break.

**Comment by sr229** [comment]
@choephix Have you tried the binary release to see if its the same as well?

**Comment by choephix** [comment]
Finally managed to try the latest binary directly (`2.1485-vsc1.38.1`). 
Yes, it shows the same behavior.

**Comment by code-asher** [comment]
I finally ran into this issue using an HTTP domain. It seems tasks use service workers which aren't available over HTTP.

**Comment by code-asher** [comment]
@choephix I'm very curious whether you're also using code-server over HTTP or if you're experiencing a different issue.

**Comment by jaehunkim** [comment]
Faced same problem here. Never happened in v1.

**Comment by sr229** [comment]
@code-asher can we verify if its upstream so we can raise this to Microsoft?

**Comment by choephix** [comment]
> @choephix I'm very curious whether you're also using code-server over HTTP or if you're experiencing a different issue.

Yes, so far I've only used code-server over the cloud via HTTP, this may definitely be connected to the issue.

**Comment by sr229** [comment]
@choephix try running this over in HTTP/S, I think the reason we can't run this is because VSCode Web largely runs Web Workers which is banned on HTTP remotes.

**Comment by SheepDomination** [comment]
Can anyone even open a `tasks.json` file ?

**Comment by code-asher** [comment]
I'm able to open it directly and from the command palette (Tasks:
Configure Tasks). Are you accessing code-server over HTTPS?

**Comment by SheepDomination** [comment]
@code-asher No, I'm not accessing code-server over HTTPS. I'm not able to open it directly from the command palette; as you can.

**Comment by code-asher** [comment]
I've had issues in the past with tasks over HTTP so I thought that might
be it but I just tried again now over HTTP and it still seems to be
working for me. :confused: Still, if you can try HTTPS (or localhost) it
might be worth giving it a shot.

Do you see any errors in the browser console or in VS Code's output panel
when you try to use tasks from the palette?

**Comment by SheepDomination** [comment]
There is errors in the console, I've reported them.

**Comment by nhooyr** [comment]
Works fine now. If this is still a problem, please feel free to reopen.
